### ISSUE TITLE
[TextInputLayout] [Exposed Dropdown Menu] wrap_content only considers currently selected item

### ISSUE THREAD

**Issue by wondering639** [material-components/material-components-android#1001]
**Description:** 
- If one puts multiple items in a Spinner and sets its width to wrap_content, the spinner considers the width of the first 15 items and sets its width to the maximum width found in these 15 items.
(see [spinner source code](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:appcompat/appcompat/src/main/java/androidx/appcompat/widget/AppCompatSpinner.java;l=77?q=spinner%20measureContentWidth), search for MAX_ITEMS_MEASURED)
- In contrast to that, exposed dropdown menu ONLY considers the currently selected item. Selecting items with different widths leads to a  resize each time an item is selected. Also, when initially no item is selected, even the dropdown list is not wide enough and won't show the complete item text.

**Expected behavior:** 
Here you see a spinner followed by an exposed dropdown menu. Both have the same items. 
![image](https://user-images.githubusercontent.com/25722498/74155442-e5ff6b80-4c14-11ea-9808-a7c8b5b9da86.png)

expanded spinner menu:
![image](https://user-images.githubusercontent.com/25722498/74155472-f9123b80-4c14-11ea-8257-96e3436661ae.png)

and the expanded exposed dropdown menu - notice how the items are cut off:
![image](https://user-images.githubusercontent.com/25722498/74155530-092a1b00-4c15-11ea-94a3-f01ba4d97840.png)

after an item was selected in the exposed dropdown menu:
![image](https://user-images.githubusercontent.com/25722498/74155581-1c3ceb00-4c15-11ea-8aa4-d9589fad717e.png)
as this is not the longest item, the text of some items is still cut off.

everything is fine when one selects the longest item:
![image](https://user-images.githubusercontent.com/25722498/74155703-54442e00-4c15-11ea-9dbe-c38603b052f8.png)

Expected behaviour: like on the spinner, on wrap_content give the exposed dropdown menu the width of the largest item, no matter if it is selected or not to prevent jumping sizes of the exposed dropdown menu. I wanted to place it next to a TextInputLayout showing only text and to save space I of course do not want to make it larger than needed. However, that is currently not possible with the exposed dropdown menu, due to the described behaviour. match_parent is also no option, as I don't want it to span more width as needed.

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**activity_main.xml**
`<?xml version="1.0" encoding="utf-8"?>

<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        tools:context=".MainActivity">

        <Spinner
            android:id="@+id/spinner"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:entries="@android:array/emailAddressTypes" />

        <com.google.android.material.textfield.TextInputLayout
            style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox.ExposedDropdownMenu"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="hint_text">

            <AutoCompleteTextView
                android:id="@+id/filled_exposed_dropdown"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"/>

        </com.google.android.material.textfield.TextInputLayout>

    </LinearLayout>

</layout>
`

**MainActivity.kt**
`package com.example.testlayout

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.ArrayAdapter
import androidx.databinding.DataBindingUtil
import com.example.testlayout.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)

        val adapter = ArrayAdapter.createFromResource(
            this,
            android.R.array.emailAddressTypes,
            R.layout.dropdown_menu_popup_item
        )

        binding.filledExposedDropdown.setAdapter(adapter)
    }
}
`

**dropdown_menu_popup_item.xml**
`<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="16dp"
    android:ellipsize="end"
    android:maxLines="1"
    android:textAppearance="?attr/textAppearanceSubtitle1"/>`

**styles.xml**
`<resources>

    
    <style name="AppTheme" parent="Theme.MaterialComponents.Light">
        
    </style>

</resources>`

app **build.gradle**
`apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.example.testlayout"
        minSdkVersion 15
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    dataBinding {
        enabled = true
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.android.material:material:1.1.0'
}
`

**Android API version:** minSdkVersion 15, targetSdkVersion 29, Android 10 on Pixel 2

**Material Library version:** Tried with 1.1.0 stable and 1.2.0-alpha4

**Device:** Pixel 2

**Comment by maltaisn** [comment]
I needed the old behavior on this (wrapping to currently selected item). It seems like it's not possible to achieve it anymore with `MaterialAutoCompleteTextView`, at least not without subclassing it. For those in the same situation, I fixed it by using `androidx.appcompat.widget.AppCompatAutoCompleteTextView` in my layouts instead.
