### ISSUE TITLE
[MaterialButton] Can't set background as gradient drawable

### ISSUE THREAD

**Issue by kuuuurt** [material-components/material-components-android#1005]
**Description:** 
I'm using a button and I'm trying to set a gradient drawable as its background but it doesn't work.

**Expected behavior:** 
It should get the gradient background like in `AppCompatButton`

**Android API version:** 29

**Material Library version:** 1.2.0-alpha04

**Comment by vitorhugods** [comment]
Woudln't it be preferable if MaterialShapeDrawable supported Gradient color? As talked about in #1167?

**Comment by kuuuurt** [comment]
I think it's better to support it in background so as not to confuse people with using shapes or background over it.

**Comment by s7aycool** [comment]
Any solutions on that question?

**Comment by leticiarossi** [comment]
Material button supports custom backgrounds as of https://github.com/material-components/material-components-android/commit/309d71860f0686137277915fb09e7502cbafc2b4, see https://github.com/material-components/material-components-android/issues/889  especifically this comment https://github.com/material-components/material-components-android/issues/889#issuecomment-621194246
