### ISSUE TITLE
[FloatingActionButton] & [ExtendedFloatingActionButton] speed dial options

### ISSUE THREAD

**Issue by javaherisaber** [material-components/material-components-android#1006]
Hi
I need to add speed dial options to my floating action button and extended floating action buttons
since 3rd party libraries does not match my requirements, it would be great to have this feature bundled with official component or via compose functions

** Additional info **
https://material.io/components/buttons-floating-action-button/#types-of-transitions

I've developed a solution for this [here](https://github.com/javaherisaber/FabSpeedDial)

**Comment by vitorhugods** [comment]
Duplicate of https://github.com/material-components/material-components-android/issues/12.
