### ISSUE TITLE
[TextInputLayout] dose not appear in new version 1.1.0 ..!

### ISSUE THREAD

**Issue by devBoyoot** [material-components/material-components-android#1008]
**Description:** Full description of issue here

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Android API version here

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

**Device:** Device on which the bug was encountered here

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
Can you provide more details about the issue you're having?

**Comment by leticiarossi** [comment]
Closing this as more info hasn't been given.
