### ISSUE TITLE
[DayNight Theme] White text on EditTextPreference buttons

### ISSUE THREAD

**Issue by gmikhail** [material-components/material-components-android#1009]
**Description:** After changing the theme to `Theme.MaterialComponents.DayNight` the EditTextPreference buttons has white text

![Аннотация 2020-02-11 192537](https://user-images.githubusercontent.com/4838367/74263526-b1201100-4d07-11ea-994f-6f10849a48c2.png)

**Expected behavior:** On a light theme, I expect to see dark text on buttons

**Source code:** 
`styles.xml`
```
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
</style>
```
`preferences.xml`
```
<PreferenceScreen xmlns:app="http://schemas.android.com/apk/res-auto">
    <EditTextPreference
        app:key="signature"
        app:title="@string/signature_title"
        app:useSimpleSummaryProvider="true" />
</PreferenceScreen>
```

**Android API version:** 28

**Material Library version:** 1.1.0

**Device:** Emulator and real device (Android 7)

**Comment by leticiarossi** [comment]
where are you defining your colors? (how is your folder structure?)

**Comment by gmikhail** [comment]
@leticiarossi Thanks for the guess. After changing the default `colors.xml` to
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="colorPrimary">#FF0000</color>
    <color name="colorPrimaryDark">#00FF00</color>
    <color name="colorAccent">#0000FF</color>
</resources>
```
I was able to determine that the color of the text on the buttons is taken from `colorPrimary`. 

![Аннотация 2020-02-12 080653](https://user-images.githubusercontent.com/4838367/74307723-db58e980-4d6e-11ea-8dfd-ade3f5b8fe1b.png)

Is this expected behavior? How then can I create a light theme if `ToolBar `color are the same as EditTextPreference buttons text color? 

After all, in the standard theme `Theme.AppCompat.Light` the text color of the EditTextPreference buttons is taken from `colorAccent` which is more logical (accent only for interactive things, the rest is for statics).

**Comment by leticiarossi** [comment]
That's right, `colorPrimary` is the default color for the text for the text button, which is controlled by the `android:textColor` attribute. You can find more info in the [buttons documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md). To change colors of specific components you can do so via theming and styling (in the buttons doc there is an example of theming but there is also info in the [Color theming doc](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md)). 
We're currently working on improving documentation and on migration guides to help the transition between 1.0.0 and 1.1.0!
