### ISSUE TITLE
Supporting DayNight Theme

### ISSUE THREAD

**Issue by kimcy929** [material-components/material-components-android#101]
Will the lib support DayNight Theme in the future?

**Comment by kimcy929** [comment]
Thank you so much.

**Comment by herbeth1u** [comment]
@gabrielittner Looks good, but what if my "light theme attributes" and my "dark theme attributes" are the same? Since multiple style inheritance isn't a thing, I haven't found a way to not copy-paste these attributes  and have them twice in the same file... `Theme.MaterialComponents.DayNight` would be more convenient for this.

**Comment by gabrielittner** [comment]
@herbeth1u Something like this should work:

`res/values/themes.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.YourApp.Light" parent="Theme.MaterialComponents.Light">
        <!-- your light theme attributes -->
    </style>

    <style name="Theme.YourApp.Dark" parent="Theme.MaterialComponents">
        <!-- your dark theme attributes -->
    </style>

    <style name="Base.Theme.YourApp.DayNight" parent="Theme.YourApp.Light" />

	<style name="Theme.YourApp.DayNight" parent="Base.Theme.YourApp.DayNight">
        <!-- your light/dark theme independent attributes -->
    </style>

</resources>
```

`res/values-night/themes.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Base.Theme.YourApp.DayNight" parent="Theme.YourApp.Dark" />
</resources>
```

If you don't put anything into `Theme.YourApp.Light` and `Theme.YourApp.Dark` you can remove those two and let the two `Base.Theme.YourApp.DayNight` use MaterialComponents directly as parent.

**Comment by malodita** [comment]
After trying to use this method of implementing DayNight support, I found that there is a strange smearing effect of all the views in the screen. Using RC1 of material components.
![screenshot_1535461293](https://user-images.githubusercontent.com/21246191/44732175-a30f0e00-aadc-11e8-9d90-c2a2003461e1.png)

**Comment by gaara87** [comment]
https://github.com/material-components/material-components-android/issues/101#issuecomment-388542143 is that meant to be the official solution?
i think we should expose a `Theme.MaterialComponents.DayNight` as suggested earlier

**Comment by dsn5ft** [comment]
We now support `DayNight` themes:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/theme/res/values/themes_daynight.xml

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/theme/res/values-night/themes_daynight.xml

**Comment by mgray88** [comment]
@dsn5ft Do I have to use androidx if I want to use `DayNight`?

**Comment by dsn5ft** [comment]
Yes, this is available in `com.google.android.material:material:1.1.0-alpha02` which requires androidx. There will be no more feature releases for the non-androidx 28.0.0 path, across all of the Support Libraries.

**Comment by ligi** [comment]
Will this be released as a non alpha/beta version any time soon? As far as I see this feature is only available in alpha/beta versions
