### ISSUE TITLE
[MaterialShapeDrawable] Interpolation does not work when isRoundRect is true

### ISSUE THREAD

**Issue by jkarlsson** [material-components/material-components-android#1010]
Description: 
If you're using a basic shape with rounded corners, interpolation does nothing. If you let at least one of the corners have a different radius or a completely different corner treatment interpolation works as intended.

The issue appears to be that the code is being clever and replacing the path with a simple rounded rect when it detects this condition is true (isRoundRect() returns true). I believe this can be fixed rather straight forward by simply scaling the radius used here with drawableState.interpolation.

Expected behavior: Interpolation should work even if all four corners have the same radius.

Here's a sample project demonstrating this with MaterialCardViews. The middle one is not able to interpolate since it is drawn as a rounded rect.

[MaterialCardViewTest.zip](https://github.com/material-components/material-components-android/files/4187415/MaterialCardViewTest.zip)

Android API version: Tested on API 29

Material Library version: Tested on 1.1.0 and 1.2.0-alpha04

**Comment by ymarian** [comment]
That makes sense to me, good catch!

**Comment by ymarian** [comment]
Solved here and included in the latest alpha:

https://github.com/material-components/material-components-android/commit/8e8d20c94f3573f7f7418f3971fbbc41a4fa83bd
