### ISSUE TITLE
Accent color problem after update to 1.1.0

### ISSUE THREAD

**Issue by ligi** [material-components/material-components-android#1012]
when updating from 1.0.0 to 1.1.0 I am having problems with the accent color. E.g. on the FAB - had the accent color before - now is weirdly blue. And TextInputs now use the primary color instead of the accent color for hint and so.

**Comment by gmikhail** [comment]
Probably I have the same problem: https://github.com/material-components/material-components-android/issues/1009

**Comment by leticiarossi** [comment]
Hello, as mentioned in #1009 we're working on migration guides to help transitioning from 1.0.0 to 1.1.0. For now, there is more info about default color and attributes in the individual components docs, but there is also this general [Color theming doc](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md).
You can also check on the individual `styles.xml` of each component to see what defaults and attributes they use ([FAB](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/floatingactionbutton/res/values/styles.xml) and [Text fields](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/values/styles.xml)).
