### ISSUE TITLE
android:textAppearance color doesn't work for MaterialButton

### ISSUE THREAD

**Issue by kirvis250** [material-components/material-components-android#1013]
In fact it works, with some hacks like 
`<item name="android:textColor">@null</item>`  in button style.

But this kind of behavior caused me 2 hours of headache (writing this bug report included). 
And i doubt that i'm the only one who spend way too much time for something as minor as this. 

Exact place in 1.2.0-alpha04 which causes the issue:
![Screenshot from 2020-02-12 16-14-56](https://user-images.githubusercontent.com/6008835/74342889-e2a1e680-4db2-11ea-8988-e153e706da13.png)

The marked line should be defined in `TextAppearance.MaterialComponents.Button`  or  `Base.TextAppearance.MaterialComponents.Button` (in my opinion ofc)

**Comment by leticiarossi** [comment]
Hi, that's the expected behavior, your solution is not a hack. If set, the `android:textColor` takes precedence over `android:textAppearance`. Helpful info about text appearance can be found in this article: https://medium.com/androiddevelopers/whats-your-text-s-appearance-f3a1729192d

**Comment by kirvis250** [comment]
Expected behavior by Contributors or developers who have to spend extra hour or two trying to figure out why the hell this doesn't work?

**Comment by mtrakal** [comment]
I spend hours with that, until I found that root style `<style name="Widget.MaterialComponents.Button" parent="Widget.AppCompat.Button">` has defined default color `<item name="android:textColor">@color/mtrl_btn_text_color_selector</item>` 🤦‍♂️. My textAppearance with color is ignored all the time...
