### ISSUE TITLE
[BottomAppBar - BottromNavigationView] Ripple is not working correctly

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [material-components/material-components-android#1021]
**Description:** The `BottomAppBar` has a notch because it has a fab attached. Inside the `BottomAppbar` I placed a `BottomNavigationView` but when I press in some item, de ripple is appearing over "nothing" because the `BottomNavigationView` is not respecting the bounds.

**Expected behavior:** Ripple should respect the bounds.

**Source code:**  
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_anchor="@id/bottomAppBar" />

    <com.google.android.material.bottomappbar.BottomAppBar
        android:id="@+id/bottomAppBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        app:contentInsetStart="0dp"
        app:fabCradleMargin="24dp"
        app:fabCradleRoundedCornerRadius="24dp"
        app:fabCradleVerticalOffset="10dp">

        <com.google.android.material.bottomnavigation.BottomNavigationView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom"
            android:background="@android:color/transparent"
            app:elevation="0dp"
            app:itemBackground="?attr/selectableItemBackground"
            app:menu="@menu/some_menu" />

    </com.google.android.material.bottomappbar.BottomAppBar>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Android API version:** 29

**Material Library version:** 1.1.0-rc01

**Device:** Emulator Pixel 3

**Comment by JavierSegoviaCordoba** [comment]
In general, any `View` is not respecting the notch (really the parent shape), for example if I add a `FrameLayout` with a background color inside the `BottomAppBar`, the notch is being hidden after the `FrameLayout`.

**Comment by ymarian** [comment]
Unfortunately the `ViewOutlineProvider` class for Android which decides the shape of the content only supports round rects. In addition I don't think any of our examples support adding BottomNav inside a BAB.
I think it's infeasible for us to support this for now. 

https://developer.android.com/reference/android/view/ViewOutlineProvider.

If you really need this I recommend trying to extend BAB and doing the same this does:
https://gist.github.com/BatmanInGotham2/3e040163bc396205d8add8713d46c154

That will clip the canvas of your children but I don't think we'll support it out of the box.
