### ISSUE TITLE
When i update to 1.1.0 all my input layouts go wrong and crash app

### ISSUE THREAD

**Issue by joaogarrido98** [material-components/material-components-android#1026]
When i update to 1.1.0 all my input layouts go wrong and crash app! can anybody explain whats going on?

**Comment by leticiarossi** [comment]
Can you post a stack trace of your crash?

**Comment by TorkelV** [comment]
In 1.1.0 textinput layouts crash if your app theme does not inherit from a Material theme. Can that be the case?

**Comment by joaogarrido98** [comment]
> In 1.1.0 textinput layouts crash if your app theme does not inherit from a Material theme. Can that be the case?

I dont know how to check that! im new at all this

**Comment by joaogarrido98** [comment]
> Can you post a stack trace of your crash?

How do I do that?

**Comment by TorkelV** [comment]
> 
> 
> > In 1.1.0 textinput layouts crash if your app theme does not inherit from a Material theme. Can that be the case?
> 
> I dont know how to check that! im new at all this

In `AndroidManifest.xml`, find 
```
<application
...
android:theme="@style/AppTheme"
```

Find your theme and see what the parent is. It should be `Theme.MaterialComponents...`, for example use: `<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">`
