### ISSUE TITLE
[MaterialTextView] android:textAppearance on MaterialTextView should support android:lineSpacingExtra defined in text appearance style

### ISSUE THREAD

**Issue by AradiPatrik** [material-components/material-components-android#1030]
Inside the material-theme-builder project I configured my `Body1` type like this
```
<!-- Inside types.xml -->
<style name="TextAppearance.MyTheme.Body1" parent="TextAppearance.MaterialComponents.Body1">
  <item name="android:lineSpacingExtra">4dp</item>
</style>

<!-- Inside themes.xml -->
<item name="textAppearanceBody1">@style/TextAppearance.MyTheme.Body1</item>

<!-- Inside view -->
<TextView
 android:id="@+id/usage_body_text_view"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:layout_marginTop="@dimen/keyline_5"
 android:layout_marginBottom="@dimen/keyline_5"
 android:text="@string/instructions_how_to"
 android:textAppearance="?textAppearanceBody1"
 android:alpha="?alphaEmphasisMedium" />
```

Unfortunately this won't add extra line spacing. But if I replace `android:textApearance` with `style` it ads the extra line spacing.
If I use `android:lineHeight` it wokrs with `android:textAppearance` but the required api level for `android:lineHeight` is too high for me (api level 28).

It is very easy to reproduce this issue inside the material-theme-builder project (just add the `<item name = "android:lineSpacingExtra">4dp</item>` inside the `TextAppearance.MyTheme.Body1` style, then observe that it has no effect.

Thank you for your assistance in advance :)

**Comment by AradiPatrik** [comment]
I found that MaterialTextView redeclares the `lineHeight` attribute, so using `<item name="lineHeight">20sp</item>` solved the issue for me.
The weird thing is that it seems to be redeclaring the `android:lineHeight` attribute too, but the android linter generates a warning, that it is only available on api level 28

**Comment by drchen** [comment]
Actually - neither lineHeight nor lineSpacingExtra is intended to be supported by the Android framework. 

We already added extra support of lineHeight in the Material library which I think should serve most of the use cases?

And - I don't think Android linter can recognize attribute overriding so please just use lineHeight we defined instead of the framework one if you want to avoid lint errors. (Or add tools:ignore="NewApi" in your XML files.)
