### ISSUE TITLE
[BottomSheet] dark mode composants overlay

### ISSUE THREAD

**Issue by benjaminledet** [material-components/material-components-android#1031]
**Description:**
I have disabled the elevation overlay for my Bottom Sheets in dark mode. It works fine for the background. But the background of my chips still looks like the overlay is applied.

Here are the chips in a regular fragment : 

![Screenshot_20200218-145924~2](https://user-images.githubusercontent.com/23617972/74750913-c26b9f00-526c-11ea-9817-5c905a8a6199.png)

Here are the chips in a bottomSheetFragment : 

![Screenshot_20200218-145837~2](https://user-images.githubusercontent.com/23617972/74751020-ecbd5c80-526c-11ea-8cca-ecb9ba6512bd.png)

**Expected behavior:** 
The chips on the bottom sheet should look like the one in a regular fragment.
As you can see with the chips, the background color modified by the elevation overlay doesn't looks good with my colorPrimary that's why I have disabled it.

**Source code:** 

The colors : 
```
 <item name="android:colorBackground">#212121</item>
 <item name="colorPrimary">#b0bec5</item>
```

The bottomSheetDialog style : 

```
   <style name="ThemeOverlay.Budget.BottomSheetDialog" parent="@style/ThemeOverlay.MaterialComponents.BottomSheetDialog">
        <item name="elevationOverlayEnabled">false</item>
    </style>
```

The style of the chip : 
```
   <style name="Widget.Budget.Chip.Choice" parent="Widget.MaterialComponents.Chip.Choice">
        <item name="chipStrokeWidth">1dp</item>
        <item name="rippleColor">?colorPrimary</item>
        <item name="chipStrokeColor">@color/chip_choice_stroke</item>
        <item name="chipBackgroundColor">@color/chip_choice_background</item>
        <item name="chipSurfaceColor">@null</item>
        <item name="android:textColor">@color/chip_choice_text</item>
        <item name="android:textAppearance">?textAppearanceButton</item>
        <item name="chipMinHeight">35dp</item>
        <item name="chipStartPadding">8dp</item>
        <item name="chipEndPadding">8dp</item>
    </style>

```
The background of the chip (chip_choice_background): 

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:alpha="0.24" android:color="?attr/colorPrimary" android:state_enabled="true" android:state_selected="true"/>
    <item android:alpha="0.24" android:color="?attr/colorPrimary" android:state_enabled="true" android:state_checked="true"/>
    <item android:color="?android:colorBackground"/>
</selector>
```

If I replace  `<item android:color="?android:colorBackground"/>` by <`item android:color="@android:color/transparent"` the background issue is resolved but then the ripple doesn't work anymore so it's not a solution.

I tried to put  `<item name="elevationOverlayEnabled">false</item>` on the chip style but it doesn't work neither.

**Android API version:** 29

**Material Library version:** 1.2.0-alpha04

**Device:** Pixel 3 XL

**Comment by dsn5ft** [comment]
Hi @benjaminledet, you should be able to set a theme overlay on the chip as well:

```
<style name="ThemeOverlay.Budget.ElevationOverlayDisabled" parent="">
    <item name="elevationOverlayEnabled">false</item>
</style>
```

`android:theme="@style/ThemeOverlay.Budget.ElevationOverlayDisabled"`
