### ISSUE TITLE
[TextInputLayout] Ability to Programmatically Set TextInputLayout Stroke Color

### ISSUE THREAD

**Issue by Logikgate** [material-components/material-components-android#1032]
**Is your feature request related to a problem? Please describe.**
It does not appear to be possible to set the TextInputLayout stroke color of an inactive field programmatically (i.e. not in XML). There has been a lot of talk surrounding this issue, ref #593, #524, #534, #258.

All of those issues/pull requests have been closed with what appears to be no resolution. 

**Describe the solution you'd like**
Pull request #524 appeared to have fixed the underlying issue by adding a setBoxStrokeColorStateList method that allowed us to pass in a complete state list to describe the colors of the stroke in all situations.  This seems like the ideal situation as it allows us to specify the colors for each state.

**Describe alternatives you've considered**
It is possible to set these colors via xml but that forces us to hard code the colors at build time which is not ideal.

**Comment by Logikgate** [comment]
Ah, never mind it does look like setBoxStrokeColorStateList was added to TextInputLayout. Were the docs updated to reflect this? I couldn't find a reference to it anywhere.

https://github.com/material-components/material-components-android/blob/a040af5bd3a4e429f5d1323e72519e002ef4f4bb/lib/java/com/google/android/material/textfield/TextInputLayout.java#L958

**Comment by ymarian** [comment]
Thanks! We'll update the docs soon

**Comment by Logikgate** [comment]
Thanks! Also, I just confirmed this actually isn't in the 1.1.0 stable build, it is included 1.2.0-alpha04 so it makes sense the docs haven't been updated :)
