### ISSUE TITLE
[MaterialButton] Programmatically setting background tint having alpha blends with existing tint rather than replacing

### ISSUE THREAD

**Issue by damianw** [material-components/material-components-android#1033]
**Description:**
Setting a non-opaque background tint (via `setBackgroundTintList`) on a `MaterialButton` causes the new background tint to blend with the previous background tint, rather than replace it. This is especially noticeable when trying to set a transparent background tint, which has no effect.

**Source code:** A sample app that reproduces the problem can be found here: https://github.com/damianw/MaterialButtonTransparentTint

**Expected behavior:**
In the following demo ([MainActivity](https://github.com/damianw/MaterialButtonTransparentTint/blob/master/app/src/main/java/wtf/log/materialbuttontransparenttint/MainActivity.kt), [activity_main.xml](https://github.com/damianw/MaterialButtonTransparentTint/blob/master/app/src/main/res/layout/activity_main.xml)), we define a `MaterialButton` like so:
```xml
<com.google.android.material.button.MaterialButton
    android:id="@+id/button"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:backgroundTint="#F00"
    android:text="Click to change tint"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    tools:ignore="HardcodedText" />
```

and change the background tint whenever the button is pressed:
```kotlin
class MainActivity : AppCompatActivity() {

    private var color = Color.RED

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val button: AppCompatButton = findViewById(R.id.button)
        button.setOnClickListener {
            // does not appear at all
            val altColor = 0x00000000
            // blends with red, result is purple
            // val altColor = 0x660000FF
            val nextColor = if (color == Color.RED) altColor else Color.RED
            button.backgroundTintList = ColorStateList.valueOf(nextColor)
            color = nextColor
        }
    }
}
```

As seen in the demonstration below, clicking the button has no effect:

<img src="https://github.com/damianw/MaterialButtonTransparentTint/raw/master/demo-material-transparent.gif" width="480"/>

The issue appears to be that the new color is actually blended with the previous color - an effect that can be confirmed by changing `altColor` to `0x660000FF` (translucent blue). In this demonstration, the new color is purple:

<img src="https://github.com/damianw/MaterialButtonTransparentTint/raw/master/demo-material-blue.gif" width="480"/>

This issue is not present when with either `android.widget.Button` or `androidx.appcompat.widget.AppCompatButton`.

Using an `altColor` of `0x00000000` on an `androidx.appcompat.widget.AppCompatButton`:

<img src="https://github.com/damianw/MaterialButtonTransparentTint/raw/master/demo-appcompat-transparent.gif" width="480"/>

Using an `altColor` of `0x660000FF` (translucent blue) on an `androidx.appcompat.widget.AppCompatButton`:

<img src="https://github.com/damianw/MaterialButtonTransparentTint/raw/master/demo-appcompat-blue.gif" width="480"/>

**Android API version:** 29

**Material Library version:** `com.google.android.material:material:1.2.0-alpha04`

**Device:** API 29 Emulator

**Comment by ymarian** [comment]
Hi thanks for the detailed bug report. 
If the tints are blending setting a different tint mode on the button might help:

```xml
<com.google.android.material.button.MaterialButton
     android:backgroundTintMode="src_over"
     ...
/>
```

**Comment by ymarian** [comment]
Actually the problem seems to be using
android:backgroundTint="#F00" delegates tinting to Appcompat.

using app:backgroundTint="#F00" on the xml works as expected without changing tint modes.

**Comment by damianw** [comment]
@ymarian How should apps handle re-usable styles and themes which apply to views other than just `MaterialButton`? We have some generic styles that specify `android:backgroundTint` - are you saying that any such styles need to be specialized specifically for `MaterialButton`, and that `MaterialButton` is incompatible with `android:backgroundTint`?

That doesn't really seem like the right resolution to me, given that `AppCompatButton` had an identical issue as of `androidx.appcompat:appcompat:1.0.2` which was fixed in `androidx.appcompat:appcompat:1.1.0`. Given that such a fix was made in `appcompat`, is it possible to port that same fix to `MaterialButton`?

**Comment by ymarian** [comment]
That makes sense, we should fix it if AppCompat did

**Comment by thevoiceless** [comment]
Any update on this?

**Comment by artakhnoyan** [comment]
@ymarian Do we have any update on this?

**Comment by drchen** [comment]
I believe it's fixed with the upgrading of appcompat version to 1.1.0.

Let me know if this is still happening. : )
