### ISSUE TITLE
[transition] transition has bug in api 21

### ISSUE THREAD

**Issue by flashiran1** [material-components/material-components-android#1037]
hi i can not test Container Transform (Activity) has error 

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {io.material.catalog/io.material.catalog.transition.TransitionContainerTransformStartDemoActivity}; have you declared this activity in your AndroidManifest.xml?
```
but this activity declared in AndroidManifest!

Android version: API 21 Android 5.1.1
Device brand: Huawei
Device model: huawei p7-l10

**Comment by ymarian** [comment]
I think this was fixed here:

https://github.com/material-components/material-components-android/commit/c589d8df7db480de489f4490086a267cb02b1ef6

**Comment by flashiran1** [comment]
I had this problem with the latest pull!
