### ISSUE TITLE
theming/Motion.md is not available in latest version 1.2.0-alpha04

### ISSUE THREAD

**Issue by Artman12** [material-components/material-components-android#1039]
**Description:** When looking at [Motion.md](https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md) it states:

_Before you can use the motion library, you need to add a dependency on the Material Components for Android library. For more information, go to the Getting started page._

After using following tutorial and adding `implementation 'com.google.android.material:material:1.2.0-alpha04'` I see that there is no `transition` namespace in plugin.

Please update Motion.md or add transition namespace

**Comment by afohrman** [comment]
Thanks for filing this. The release that includes motion is actually 'com.google.android.material:material:1.2.0-alpha05' which will be released shortly. We will update the documentation to reflect the correct release to depend on.

**Comment by afohrman** [comment]
Looks like the documentation doesn't actually point to `'com.google.android.material:material:1.2.0-alpha05'`, just to the Getting Started page which indicates that the latest release should be used. This will be resolved with the release of `'com.google.android.material:material:1.2.0-alpha05'`.
