### ISSUE TITLE
error: string too large to encode using UTF-8 written instead as 'STRING_TOO_LARGE'. when i add this lib

### ISSUE THREAD

**Issue by pahnpiseth** [material-components/material-components-android#104]
### Overview
For usage questions: ask on
[Stack  Overflow](http://stackoverflow.com/questions/tagged/material-components).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

### Reproduction steps

 - Detailed steps to reproduce

### Version number

 - Found in CHANGELOG.md

### Related issues

 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by Mistic92** [comment]
@pahnpiseth I see you closed this issue. Can you write solution?

**Comment by pahnpiseth** [comment]
because,I put big vector drawable...I just delete it.

**Comment by Mistic92** [comment]
Interesting. But I can't just delete vector. I have a lot of them and I don't know which one cause problem.

**Comment by Mistic92** [comment]
I had to simplify vectors. For some of them helped decreasing decimal number or if it was something long, cut and show in few elements instead of one big
