### ISSUE TITLE
FAB changes appearance

### ISSUE THREAD

**Issue by magnusfernandes** [material-components/material-components-android#1042]
**Description:** FAB changes color and border
![Screenshot_20200221-041624](https://user-images.githubusercontent.com/8638822/74987725-daf0da80-5461-11ea-97db-881bcf67a901.jpg)

**Expected behavior:** FAB should look like this
![Screenshot_20200221-041347](https://user-images.githubusercontent.com/8638822/74987751-ee03aa80-5461-11ea-8b29-7300cb2b49e9.jpg)

**Source code:** 
`<com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/createVisitor"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="16dp"
        android:src="@drawable/ic_add_users"
        android:tint="@color/colorWhite"
        app:layout_anchor="@id/linear"
        app:layout_anchorGravity="end|bottom" />`

**Android API version:** Android API 29

**Material Library version:** Material Android Library version 1.1.0

**Device:** OnePlus 3 and OnePlus 6t

**Comment by LukasVykuka** [comment]
Use `app:tint="@color/colorWhite"`, **app** prefix solve it.

**Comment by minas1** [comment]
It would be really nice to have a migration guide between versions 1.0.0 and 1.1.0...

**Comment by wcshi** [comment]
Please check out @ricknout 's [migration guide](https://medium.com/androiddevelopers/migrating-to-material-components-for-android-ec6757795351).
