### ISSUE TITLE
[motion] Fragment to Activity

### ISSUE THREAD

**Issue by flashiran1** [material-components/material-components-android#1043]
hi in https://material.io/develop/android/theming/motion/
Explained about
Container transform Transition between Fragments
or
Container transform Transition between Activities

But you didn't say anything about Container transform Transition between Fragment to Activity !

How should it be implemented?

**Comment by hunterstich** [comment]
Hey there. 
You can transition from a Fragment to an Activity basically the same way you'd transition from an Activity to an Activity since a Fragment can be thought of as just a view hierarchy inside of an Activity.

For example, to implement a container transform from FragmentA in ActivityA to ActivityB, follow the same steps in [Container transform: Transition between Activities](https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md#container-transform), setting up both ActivityA and ActivityB by enabling transitions, adding the shared element callbacks, etc. 

Then, in FragmentA, when you're ready to container transform to ActivityB, call startActivity with the same ActivityOptions as written in the Motion documentation but pass in the View in FragmentA from which you are transitioning. 

Let me know how this works for you.

**Comment by hunterstich** [comment]
Going ahead and closing this but feel free to re-open if you feel it hasn't been answered.

**Comment by flashiran1** [comment]
i add in Activitya
```kotlin
    window.requestFeature(Window.FEATURE_ACTIVITY_TRANSITIONS)
        setExitSharedElementCallback(MaterialContainerTransformSharedElementCallback())
        window.sharedElementsUseOverlay = false
        
        super.onCreate(savedInstanceState)
```

and activityb

```kotlin
    //for Transition
        window.requestFeature(Window.FEATURE_ACTIVITY_TRANSITIONS)
        findViewById<View>(android.R.id.content).transitionName = "shared_element_container"
        setEnterSharedElementCallback(MaterialContainerTransformSharedElementCallback())
        window.sharedElementEnterTransition = MaterialContainerTransform(this)
        window.sharedElementReturnTransition = MaterialContainerTransform(this)

        super.onCreate(savedInstanceState)
```

and fragmenta
```kotlin
  fun goDetailNews2(view: View, news: News?, activity: Activity) {
        val intent = Intent(BaseApp.context, NewsDetailActivity::class.java)
        intent.putExtra("news", news)
        val options =  ActivityOptions.makeSceneTransitionAnimation(
                activity,
                view,
                "shared_element_container"  // The transition name to be matched in Activity B.
        )
        activity.startActivity(intent, options.toBundle())
    }
```

and set xml item
```xml
    android:transitionName="shared_element_container"
```

The error happened!

```error
   java.lang.IllegalArgumentException: negative durations are not allowed
        at com.android.internal.policy.impl.PhoneWindow.setTransitionBackgroundFadeDuration(PhoneWindow.java:4391)
        at com.google.android.material.transition.MaterialContainerTransformSharedElementCallback.updateBackgroundFadeDuration(MaterialContainerTransformSharedElementCallback.java:228)
        at com.google.android.material.transition.MaterialContainerTransformSharedElementCallback.setUpEnterTransform(MaterialContainerTransformSharedElementCallback.java:168)
        at com.google.android.material.transition.MaterialContainerTransformSharedElementCallback.onMapSharedElements(MaterialContainerTransformSharedElementCallback.java:89)
```

**Comment by EdricChan03** [comment]
You need to set a duration (using [`Transition#setDuration`](https://developer.android.com/reference/android/transition/Transition#setDuration(long))) or `Transition` (the class that `MaterialContainerTransform` extends from) will revert to a value of `-1` (or no duration):

```java
MaterialContainerTransform transform = MaterialContainerTransform(this)
        .setDuration(/* a duration in long (e.g. 300L or 275L) */);
```

This behaviour is documented in the [`Transition#setDuration`](https://developer.android.com/reference/android/transition/Transition#setDuration(long)) method:

> Sets the duration of this transition. By default, there is no duration (indicated by a negative number), which means that the Animator created by the transition will have its own specified duration. If the duration of a Transition is set, that duration will override the Animator duration.

(P.S. Is this a bug or is it intentional?)

**Comment by flashiran1** [comment]
i add in FragmentA
```kotlin
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        sharedElementEnterTransition = MaterialContainerTransform(requireContext()).setDuration(300L)
    }
```

Again have error

‍‍‍‍```error
  java.lang.IllegalArgumentException: negative durations are not allowed
        at com.android.internal.policy.impl.PhoneWindow.setTransitionBackgroundFadeDuration(PhoneWindow.java:4391)
        at com.google.android.material.transition.MaterialContainerTransformSharedElementCallback.updateBackgroundFadeDuration(MaterialContainerTransformSharedElementCallback.java:228)
        at com.google.android.material.transition.MaterialContainerTransformSharedElementCallback.setUpEnterTransform(MaterialContainerTransformSharedElementCallback.java:168)
        at com.google.android.material.transition.MaterialContainerTransformSharedElementCallback.onMapSharedElements(MaterialContainerTransformSharedElementCallback.java:89)
```

**Comment by EdricChan03** [comment]
Could you try removing the `L` suffix from the duration?

**Comment by flashiran1** [comment]
remove it but Again have top error

```kotlin
sharedElementEnterTransition = MaterialContainerTransform(requireContext()).setDuration(300)
```

**Comment by flashiran1** [comment]
in MaterialContainerTransformSharedElementCallback function
```java
private static void updateBackgroundFadeDuration(
      Window window, MaterialContainerTransform transform) {
    window.setTransitionBackgroundFadeDuration(transform.getDuration() * 2);
  }
```
getDuration() is -1

**Comment by flashiran1** [comment]
Can't manually inject to getDuration?

**Comment by flashiran1** [comment]
im debug function updateBackgroundFadeDuration in  MaterialContainerTransformSharedElementCallback two reference it first 300 but two is -1

**Comment by EdricChan03** [comment]
Did you set it as well in activity B?

**Comment by flashiran1** [comment]
yes
```kotlin
 override fun onCreate(savedInstanceState: Bundle?) {
        //for Transition
        window.requestFeature(Window.FEATURE_ACTIVITY_TRANSITIONS)

        val transform = MaterialContainerTransform(this)
        transform.duration = 300
        window.sharedElementEnterTransition = transform


        findViewById<View>(android.R.id.content).transitionName = "shared_element_container"
        setEnterSharedElementCallback(MaterialContainerTransformSharedElementCallback())
        window.sharedElementEnterTransition = MaterialContainerTransform(this)
        window.sharedElementReturnTransition = MaterialContainerTransform(this)

        super.onCreate(savedInstanceState)
```

**Comment by flashiran1** [comment]
oh fix this error with this code
```kotlin
  //for Transition
        window.requestFeature(Window.FEATURE_ACTIVITY_TRANSITIONS)

        val transform = MaterialContainerTransform(this)
        transform.duration = 300
        window.sharedElementEnterTransition = transform


        findViewById<View>(android.R.id.content).transitionName = "shared_element_container"
        setEnterSharedElementCallback(MaterialContainerTransformSharedElementCallback())
        window.sharedElementEnterTransition = transform
        window.sharedElementReturnTransition = transform

        super.onCreate(savedInstanceState)
```

Another bug found!

‍‍‍‍‍```error
 java.lang.IllegalArgumentException: 16908290 not a valid ancestor
        at com.google.android.material.transition.TransitionUtils.findAncestorById(TransitionUtils.java:204)
        at com.google.android.material.transition.MaterialContainerTransform.createAnimator(MaterialContainerTransform.java:713)
        at android.transition.Transition.createAnimators(Transition.java:723)
        at android.transition.TransitionSet.createAnimators(TransitionSet.java:405)
        at android.transition.TransitionSet.createAnimators(TransitionSet.java:405)
        at android.transition.TransitionSet.createAnimators(TransitionSet.java:405)
        at android.transition.Transition.playTransition(Transition.java:1761)
        at android.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:298)
```

**Comment by hunterstich** [comment]
@flashiran1 Apologies for the delayed response. 

Try setting a target on ActivityB's enter shared element transition like:

```
  window.sharedElementEnterTransition = MaterialContainerTransform(this).apply {
    addTarget(android.R.id.content)
    duration = 300L
  }
```

**Comment by zenyagami** [comment]
Sorry to re open this issue, I'm using the Fragment to Activity like the following

```kotlin
// Activity B
override fun onCreate(savedInstanceState: Bundle?) {
        window.requestFeature(Window.FEATURE_ACTIVITY_TRANSITIONS)
findViewById<View>(android.R.id.content).transitionName = transitionName
        setEnterSharedElementCallback(MaterialContainerTransformSharedElementCallback())
        window.sharedElementEnterTransition = buildContainerTransform(true)
        window.sharedElementReturnTransition = buildContainerTransform(false)
}
   private fun buildContainerTransform(entering: Boolean): MaterialContainerTransform? {
        return MaterialContainerTransform(this, entering).apply {
            // Use all 3 container layer colors since this transform can be configured using any fade mode
            // and some of the start views don't have a background and the end view doesn't have a
            // background.
            setAllContainerColors(
                MaterialColors.getColor(findViewById(android.R.id.content), R.attr.colorSurface)
            )
            addTarget(android.R.id.content)
            pathMotion = MaterialArcMotion()
            fadeMode = MaterialContainerTransform.FADE_MODE_IN
        }
    }


// Activity A calling to start an Activity

 @CallSuper
    fun startTransitionActivity(
        sharedView: View,
        transitionName: String,
        intent: Intent
    ) {

        setExitSharedElementCallback(MaterialContainerTransformSharedElementCallback())
        window.sharedElementsUseOverlay = false
        ViewCompat.setTransitionName(sharedView, transitionName)
        ActivityOptions.makeSceneTransitionAnimation(
            this, sharedView, transitionName
        ).also {
            startActivity(intent.putExtra(EXTRA_TRANSITION_NAME, transitionName), it.toBundle())
        }
    }

```

This seems to work from Fragment A to Activity B (I'm using a BottomNavigationView with  fragments inside, where im calling to start a new Activity) but when click the back button, the return animation does not work.
