### ISSUE TITLE
Why bugfixes are in 1.2.0-alphaXX instead of 1.1.1-xxx

### ISSUE THREAD

**Issue by gabrielemariotti** [material-components/material-components-android#1044]
It is not a bug, it is just a question.  
There are **a lot of fixes** in the current 1.2.0-alphaXX.  
These fixes are related to the component/code released with the **1.1.0**.

It would be useful to have the fixes in the **1.1.X** (alpha-beta as you prefer) versions, and the 1.2.0 reseverd to new features/components like Sliders,ShapeableImageView.

Leaving the bugfixes in the 1.2.0 the time needed for a stable release is very long.

**Comment by ymarian** [comment]
Hi thanks for the question. It would be a lot of overhead for us trying to maintain to which release each bug fix goes, and keeping branches active for ever wouldn't scale very well. 

Now that all our deps are stable we will move to 1.2.0-beta sooner. 

The current plan is to lunch Alphas with whatever is at Head, assuming all our tests and sanity checks pass. Cut a Beta branch after a few alphas and start soaking and testing that trying to get another *Stable*. 

We will only use a bug fix release eg: *1.1.X* if there is a bug in a stable release that we consider extremely important like a Binary compatibility breakage or some other high priority crash in a common scenario.
