### ISSUE TITLE
Problems with BottomAppBar Elevation 

### ISSUE THREAD

**Issue by arthur3486** [material-components/material-components-android#105]
### Version number

Library version: 1.0.0-alpha2

### Details

While trying out the all-new BottomAppBar I've noticed that it has no elevation, which should be present by default as per the [**guidelines**](https://material.io/design/components/app-bars-bottom.html), and even worse than that is the fact there is no way to set it manually (**.setElevation(...)** & **.setTranslationZ(...)** have no effect).

I have also analyzed the [**source code**](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomappbar/BottomAppBar.java#L149) of the aforementioned widget and it seems like the following should be responsible for the drawing of the background shadow:

````java
    topEdgeTreatment =
        new BottomAppBarTopEdgeTreatment(fabCradleMargin, fabCornerRadius, fabVerticalOffset);
    ShapePathModel appBarModel = new ShapePathModel();
    appBarModel.setTopEdge(topEdgeTreatment);
    materialShapeDrawable = new MaterialShapeDrawable(appBarModel);
    materialShapeDrawable.setStrokeWidth(1f /* hairline */);
    materialShapeDrawable.setShadowEnabled(true);
    materialShapeDrawable.setPaintStyle(Style.FILL);
    DrawableCompat.setTintList(materialShapeDrawable, backgroundTint);
    ViewCompat.setBackground(this, materialShapeDrawable);
````

while it hints at its role in the drawing of the shadow, no shadow is actually getting drawn. 

I believe this is a bug as the same widget is used in the Google I/O 2018 app, where it is displayed properly (with default elevation).

### Screenshots

* **My sample app**

![screenshot_20180513-175640 2](https://user-images.githubusercontent.com/8213520/39968550-720cf1c2-56d7-11e8-8719-43d2f56cbd14.png)

* **Google I/O 2018 app**

![screenshot_20180513-175652 2](https://user-images.githubusercontent.com/8213520/39968553-758e22da-56d7-11e8-9e81-16b86b03ad4b.png)

**Comment by arthur3486** [comment]
The same problem has also been seen in the **BottomNavigationView**.

**Comment by RobertZagorski** [comment]
The reason might be in [`MaterialShapeDrawable`](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/shape/MaterialShapeDrawable.java) and it's [onDraw(Canvas)](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/shape/MaterialShapeDrawable.java#L351) method. 
`paint.setShadowLayer(...)` Which is known to be working only with drawing text. 

Source: see [Hardware acceleration](https://developer.android.com/guide/topics/graphics/hardware-accel#unsupported) developer's page.

**Comment by Sonhvp** [comment]
I have the same issue when using "com.android.support:design:28.0.0-alpha1"

**Comment by arthur3486** [comment]
@cketcham thank you for letting us know! Any information on when the stable release comes out?

**Comment by cketcham** [comment]
We're currently tied in to the support library release cycle. They haven't set a date for stable, but the beta release is scheduled for sometime in June so it will definitely be after that.

**Comment by davidlira94** [comment]
having the same problem, any of you guys have an update? we are currently using the alpha3 but still nothing... i dont know if maybe putting the element inside another component will work as it has to be.

**Comment by arthur3486** [comment]
@davidlira94 still waiting for the stable release, which should have that issue addressed.

**Comment by duzechao** [comment]
is it work now?

**Comment by davidlira94** [comment]
@duzechao nop! Still the same issue

**Comment by cketcham** [comment]
This is something we want to work on this quarter. I've created https://issuetracker.google.com/issues/111403334 to track it so there is more visibility around when we are able to work on it and when it is fixed.

**Comment by JasonAndujar** [comment]
Any progress? I see there was a fix for this, but even after upgrading I see no shadow when anchoring a FAB

**Comment by cketcham** [comment]
How are you trying to set the elevation? What device are you trying it on? What version of the library are you trying with? It should be working now.

**Comment by rexdarel** [comment]
My bad. I update the dependency

**implementation 'androidx.appcompat:appcompat:1.1.0-alpha01'
    implementation 'com.google.android.material:material:1.1.0-alpha02'**

The shadow works fine now but when I set the fab to the end of bottomappbar the icons on the bottomappbar are also aligned at the end instead of the right side. It makes the icons and the fab collapsed at the end of bottomappbar

**Comment by dexxtr** [comment]
> My bad. I update the dependency
> 
> **implementation 'androidx.appcompat:appcompat:1.1.0-alpha01' implementation 'com.google.android.material:material:1.1.0-alpha02'**
> 
> The shadow works fine now but when I set the fab to the end of bottomappbar the icons on the bottomappbar are also aligned at the end instead of the right side. It makes the icons and the fab collapsed at the end of bottomappbar

It helps me with shadow as well. Thanks @rexdarel

**Comment by binaryKarmic** [comment]
Is this fixed for "compile 'com.android.support:design:28.0.0'" implementations ?

**Comment by MGaetan89** [comment]
I don't think that the Design Support Library is receiving any more updates. You'll have to update to Material Components to use this.

**Comment by Fauzdar1** [comment]
I don't know to enforce the elevation shadow, they brute-forced it or something or most probably they're still using a drawable but now, setting `android:elevation="any value"` in `BottomAppBar` in xml gives an NPE as 

````
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.shape.MaterialShapeDrawable.setElevation(float)' on a null object reference
        at com.google.android.material.bottomappbar.BottomAppBar.setElevation(BottomAppBar.java:450)
````
I've also the latest support libraries : 
   ```
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.3.0-alpha01'
```
I want to remove the elevation completely and setting the background null as below does nothing either.
  ```
  android:background="@drawable/transparent_background_bottom_navigation_view"
  android:outlineAmbientShadowColor="@android:color/transparent"
  android:outlineSpotShadowColor="@android:color/transparent"
```
                        
Complete Log:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.app/com.app.app.activity.Home}: android.view.InflateException: Binary XML file line #177: Binary XML file line #177: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6517)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: android.view.InflateException: Binary XML file line #177: Binary XML file line #177: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #177: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:656)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:798)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.app.app.activity.Home.onCreate(Home.kt:54)
        at android.app.Activity.performCreate(Activity.java:6915)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6517)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.shape.MaterialShapeDrawable.setElevation(float)' on a null object reference
        at com.google.android.material.bottomappbar.BottomAppBar.setElevation(BottomAppBar.java:450)
        at android.view.View.<init>(View.java:4688)
        at android.view.ViewGroup.<init>(ViewGroup.java:578)
        at android.view.ViewGroup.<init>(ViewGroup.java:574)
        at androidx.appcompat.widget.Toolbar.<init>(Toolbar.java:236)
        at com.google.android.material.bottomappbar.BottomAppBar.<init>(BottomAppBar.java:227)
```

**Comment by DmitriyKhalturin** [comment]
> I don't know to enforce the elevation shadow, they brute-forced it or something or most probably they're still using a drawable but now, setting `android:elevation="any value"` in `BottomAppBar` in xml gives an NPE as
> 
> ```
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.shape.MaterialShapeDrawable.setElevation(float)' on a null object reference
>         at com.google.android.material.bottomappbar.BottomAppBar.setElevation(BottomAppBar.java:450)
> ```
> 
> I've also the latest support libraries :
> 
> ```
>  implementation 'androidx.appcompat:appcompat:1.1.0'
>  implementation 'com.google.android.material:material:1.3.0-alpha01'
> ```
> 
> I want to remove the elevation completely and setting the background null as below does nothing either.
> 
> ```
> android:background="@drawable/transparent_background_bottom_navigation_view"
> android:outlineAmbientShadowColor="@android:color/transparent"
> android:outlineSpotShadowColor="@android:color/transparent"
> ```
> 
> Complete Log:
> 
> ```
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.app/com.app.app.activity.Home}: android.view.InflateException: Binary XML file line #177: Binary XML file line #177: Error inflating class <unknown>
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
>         at android.app.ActivityThread.-wrap12(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:156)
>         at android.app.ActivityThread.main(ActivityThread.java:6517)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
>      Caused by: android.view.InflateException: Binary XML file line #177: Binary XML file line #177: Error inflating class <unknown>
>      Caused by: android.view.InflateException: Binary XML file line #177: Error inflating class <unknown>
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Constructor.newInstance0(Native Method)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
>         at android.view.LayoutInflater.createView(LayoutInflater.java:656)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:798)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
>         at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
>         at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
>         at com.app.app.activity.Home.onCreate(Home.kt:54)
>         at android.app.Activity.performCreate(Activity.java:6915)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
>         at android.app.ActivityThread.-wrap12(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:156)
>         at android.app.ActivityThread.main(ActivityThread.java:6517)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
>      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.shape.MaterialShapeDrawable.setElevation(float)' on a null object reference
>         at com.google.android.material.bottomappbar.BottomAppBar.setElevation(BottomAppBar.java:450)
>         at android.view.View.<init>(View.java:4688)
>         at android.view.ViewGroup.<init>(ViewGroup.java:578)
>         at android.view.ViewGroup.<init>(ViewGroup.java:574)
>         at androidx.appcompat.widget.Toolbar.<init>(Toolbar.java:236)
>         at com.google.android.material.bottomappbar.BottomAppBar.<init>(BottomAppBar.java:227)
> ```

I have same issue(

**Comment by dagoston93** [comment]
I have same issue...

**Comment by Fauzdar1** [comment]
Hey, I had found a solution of it back then, @dagoston93's message reminded me of this thread. The solution is to use a `MaterialShapeDrawable`.

First, dynamically create a `MaterialShapeDrawable` as 

    val backgroundDrawable = MaterialShapeDrawable().apply {
           //You can change various properties of MaterialShapeDrawable here
            setTint(Color.WHITE)
            shadowCompatibilityMode = SHADOW_COMPAT_MODE_NEVER
            elevation = 0f 
            //shadowElevation = 0
            setUseTintColorForShadow(false)
    }

Then, set it to the BottomAppBar as 

    bottomBar.background = backgroundDrawable

That's it.
