### ISSUE TITLE
[Chipgroup] checkedchipid returning chipid which has no use

### ISSUE THREAD

**Issue by sartajroshan** [material-components/material-components-android#1051]
**Description:** 

checkedchipid returns just Chip id and has no use. It useful when it returns index of chip 

**Source code:** 

```
 for (data in result){
                        
                        val chip = Chip(chipgroup.context)
                        chip.isCheckable = true
                        chip.isClickable  = true
                        chip.hint = data.id
                        chip.text = data.type

                        chipgroup.addView(chip)
                        
                    }
```

```
val btype = chipgroup.getChildAt(chipgroup.checkedChipId) as Chip
```

**Android API version:** Android API 23

**Material Library version:**  1.2.0-alpha05

**Device:** HTC DESIRE 10 PRO

**Comment by ymarian** [comment]
Hi this is consistent with RadioGroup

https://developer.android.com/reference/android/widget/RadioGroup#getCheckedRadioButtonId()

And with MaterialButtonToggleGroup. You can use findViewById instead of getChildAt.
