### ISSUE TITLE
[CollapsingToolbarLayout] Slight misalignment during transition in multiline mode

### ISSUE THREAD

**Issue by johan12345** [material-components/material-components-android#1052]
**Description:** This affects the multiline mode of the CollapsingToolbarLayout that was added as an experimental feature in 1.2.0-alpha05 (see also: #413). Upon closer inspection of the new implementation, I found that there is a slight misalignment in the positions of the expanded text and the overlays drawn during the transition, as seen in the screenshot below. Also, when the text snaps to the completely collapsed state, there is a slight upwards jump of the text position. Both of these problems can be seen in the catalog app and were not present in my original version in #413.

![Screenshot_1582471001](https://user-images.githubusercontent.com/5310424/75114630-f9b8c200-5657-11ea-8499-5e99af8f12c2.png)

**Expected behavior:** Smooth transition without misalignments. This worked correctly in our original PR:

![Demo image](https://raw.githubusercontent.com/opacapp/multiline-collapsingtoolbar/master/demo.gif)

**Source code:** see catalog app -> Top App Bar -> Collapsing Demo (Multiline title)

**Android API version:** 28

**Material Library version:** 1.2.0-alpha05

**Device:** Android Emulator

I haven't found the source of the issue yet, but it should be possible to find when comparing my implementation in #413 with the one added by @ymarian in 83e4e47d2225cd281bef195d1baf035117cda4cd.

**Comment by catellie** [comment]
Possibly intentional, but still odd IMHO:
I just tried this on an Activity which has three action buttons in the toolbar, and although it technically works as such, my three line title will never use the area underneath the three action button which looks a bit sub-optimal.
![Screenshot_1582985651](https://user-images.githubusercontent.com/499325/75609117-3f690500-5b06-11ea-9886-c7bc14017f53.png)
Other than that it looks great!

**Comment by brudaswen** [comment]
@johan12345 Thanks a lot for contributing the multi-line support! I also realized that the text is misaligned. This becomes even more prominent (to unusable) when the different between expanded and collapsed textSize is larger.

I created a PR, so let's hope it gets included, soon. Maybe you can also have a look to verify that I did not miss anything.

**Comment by johan12345** [comment]
Yes, it works much better with that change in #1408. Thank you for figuring this out!
