### ISSUE TITLE
[motion] Transition between Activities

### ISSUE THREAD

**Issue by flashiran1** [material-components/material-components-android#1061]
hi Transition between Activities has bug in my phone 
i have last push !
See the gif below

<img src="https://dl.dropboxusercontent.com/s/h1givdktjkxts37/Untitled.gif">

Android version: API 21 Android 5.1.1
Device brand: Huawei
Device model: huawei p7-l10a

**Comment by hunterstich** [comment]
Hey there. Thanks for reporting this! 

I am able to reproduce this issue and am looking into a fix. For the time being, you can solve this by setting your second Activity's shared element callback to not use a transparent window background by calling [MaterialContainerTransformSharedElementCallback.setTransparentWindowBackgroundEnabled(false)](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/transition/MaterialContainerTransformSharedElementCallback.java#L159). The downside of this workaround is that the background of your second activity will start fading in before the transition ends.
