### ISSUE TITLE
[TextInputLayout][Accessibility] Touch target box overlap with the input field label

### ISSUE THREAD

**Issue by tillygajanayake** [material-components/material-components-android#1062]
**Description:** The touch target box overlaps with the input field label when the field is in an active state.

**Expected behavior:** The touch target box should not overlap the input field label when the field is in an active state.

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Android API version 28

**Material Library version:** 1.1.0

**Device:** Emulator Pixel 3

<img src="https://user-images.githubusercontent.com/61483610/75344026-cbecab00-58ed-11ea-8b23-58e893ee733b.png" width=300>

**Comment by leticiarossi** [comment]
Hi, what exactly is the issue? This looks like it's working as intended.

**Comment by tillygajanayake** [comment]
> Hi, what exactly is the issue? This looks like it's working as intended.

I'm referring to the touch target box (Green box around the input field) is overlapping the label text. Please refer to the attached screenshot. 

Shouldn't the expected behavior be the touch target box (Green box around the input field) does NOT overlap the label? Please advise.

**Comment by leticiarossi** [comment]
The target box looks right! It's ok that it overlaps with the label as the label itself isn't clickable

**Comment by tillygajanayake** [comment]
Yes, It is true that the label is not selectable however not all screen reader users are legaly blind and some screen reader users are actually low vision user. By 'blocking' the label withe the green outline, it will affect low vision screen reader users' ability to read. 

The suggestions would be: 
- When the input field is in selected mode, the green box should outline both label and the edit box. (i.e. touch target box will include both and it will be bigger)

You can find out more by reading [WCAG 2.1 Success Criterion 1.4.8: Visual Presentation.](https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation)

We would recommend to re-open this ticket as this will pose a high impact to the screen reader low vision user.
