### ISSUE TITLE
[Transition] Transition between Activities 'not a valid ancestor'

### ISSUE THREAD

**Issue by NightRich** [material-components/material-components-android#1064]
**Description:** Full description of issue here

**Expected behavior:** 
![error](https://user-images.githubusercontent.com/20264712/75382846-516f5b80-58ec-11ea-87c1-6e219832f67a.PNG)

**Source code:** https://material.io/develop/android/theming/motion/#container-transform. (I did not apply the same here.) Note: The activity starts from the adapter.
```@SuppressLint("SetTextI18n")
    override fun onBindViewHolder(holder: OrderViewHolder, position: Int){
        val order: Order = data[position]
        val customer: Customer = order.customer

        holder.username.text = "${customer.name} ${customer.surname}"
        holder.miniAddress.text = "${customer.provinceString}/${customer.districtString}"

        holder.card.setOnClickListener{
            context.startActivity(
                Intent(context, OrderContentActivity::class.java),
                ActivityOptions.makeSceneTransitionAnimation(
                    MainActivity.self(),
                    holder.linear,
                    "shared_element_container"
                ).toBundle()
            )
        }
    }

**Android API version:** 29

**Material Library version:** 1.2.0-alpha5

**Device:** Samsung M20

**Comment by NightRich** [comment]
Oh okey, I solved the problem from this url; https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md#container-transform
The content of the documentation here is incomplete; https://material.io/develop/android/theming/motion/#container-transform

**Comment by EasonLiu09** [comment]
Thanks for the information, i got this problem too
