### ISSUE TITLE
[ProgressDialog] ProgressDialog spinner is always green, regardless of theme colors

### ISSUE THREAD

**Issue by AradiPatrik** [material-components/material-components-android#1068]
**Description:** `andoird.app.ProgressDialog`'s circular indeterminate progress indicator is green, regardless of theme attributes values. This is issue is present in 1.1.2-alpha05, but not present in 1.1.2-alpha04

**Expected behavior:** I expect that the spinner will be the same color as my `colorPrimary` theme attribute

**Source code:** 
my theme colors:
```
        <item name="colorPrimaryDark">?colorPrimaryVariant</item>
        <item name="colorAccent">?colorSecondary</item>
        <item name="colorPrimary">@color/color_primary</item>
        <item name="colorPrimaryVariant">@color/color_primary_variant</item>
        <item name="colorSecondary">@color/color_secondary</item>
        <item name="colorSecondaryVariant">@color/color_secondary_variant</item>
```

**Android API version:** 
I've tested it on api level 24 and 29, the issue is present on both of them

**Material Library version:** 
1.1.2-alpha05

**Device:** Emulator, and my samsung galaxy s7 edge

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.
✔️ 

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ymarian** [comment]
The attribute for that is 
`android:indeterminateTint`
