### ISSUE TITLE
[MaterialDatePicker] Displaying incorrect Today date

### ISSUE THREAD

**Issue by amg** [material-components/material-components-android#1069]
MaterialDatePicker displaying incorrect Today date. I can't find a way to override this to correct as a workaround.
Library version: 1.1.0
Android 9.0

![Screen Shot 2020-02-28 at 10 24 38 am](https://user-images.githubusercontent.com/4544118/75496804-7102a300-5a16-11ea-897a-bb3adbf35bc3.png)

![Screen Shot 2020-02-28 at 10 33 34 am](https://user-images.githubusercontent.com/4544118/75496827-7cee6500-5a16-11ea-97b1-80859eee97e5.png)

Am I doing something wrong?

```
val dialogBuilder = MaterialDatePicker.Builder.datePicker()
// defaultDate.asUTCCalendar() corrects the selection
//  to display correct timezone for selected date
dialogBuilder.setSelection(defaultDate.asUTCCalendar().timeInMillis)
dialogBuilder.setCalendarConstraints(
    CalendarConstraints.Builder()
        .apply {
            minDate?.invoke()?.let { setStart(it.asUTCCalendar().timeInMillis) }
            setOpenAt(defaultDate.asUTCCalendar().timeInMillis)
            minDate?.invoke()?.let { setValidator(DateValidatorPointForward.from(it.asUTCCalendar().timeInMillis)) }
        }.build()
)
```

Kind regards,
Alex

**Comment by ymarian** [comment]
https://github.com/material-components/material-components-android/issues/882
