### ISSUE TITLE
[MaterialAlertDialog] Styled action buttons invalid positioning

### ISSUE THREAD

**Issue by fistuk** [material-components/material-components-android#1074]
**Description:** 
When using a custom styling for the dialog actions it seems the button positioning ignores the button background and does all the calculations according to the text.
<img width="337" alt="Screen Shot 2020-03-01 at 12 15 34" src="https://user-images.githubusercontent.com/1989685/75625060-09d62180-5bc3-11ea-91b2-91fe377fc769.png">

**Expected behavior:** 
Properly position actions with a background.

**Source code:**
```
MaterialAlertDialogBuilder(this)
                .setTitle("Save")
                .setMessage("Do you wish to save the file?")
                .setPositiveButton("Save", null)
                .setNegativeButton("Don't save", null)
                .setNeutralButton("Cancel", null).create().show()

<!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.Light">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="materialAlertDialogTheme">@style/AlertDialog</item>
    </style>

    <style name="AlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="materialAlertDialogTitleTextStyle">@style/DialogTitleTextStyle</item>
        <item name="materialAlertDialogBodyTextStyle">@style/DialogBodyTextStyle</item>
        <item name="buttonBarPositiveButtonStyle">@style/PositiveButtonStyle</item>
        <item name="buttonBarNegativeButtonStyle">@style/NegativeButtonStyle</item>
        <item name="buttonBarNeutralButtonStyle">@style/NegativeButtonStyle</item>
    </style>

    <style name="NegativeButtonStyle" parent="Widget.MaterialComponents.Button.OutlinedButton">
        <item name="android:textColor">#3c3c3c</item>
        <item name="backgroundTint">#FFFFFF</item>
        <item name="strokeColor">#80808080</item>
        <item name="strokeWidth">1dp</item>
        <item name="textAllCaps">false</item>

    </style>

    <style name="PositiveButtonStyle" parent="Widget.MaterialComponents.Button.TextButton">
        <item name="android:textColor">#FFFFFF</item>
        <item name="backgroundTint">#0696d7</item>
        <item name="textAllCaps">false</item>
    </style>

    <style name="NeutralButtonStyle" parent="Widget.MaterialComponents.Button.TextButton">
        <item name="android:textColor">#3c3c3c</item>
        <item name="backgroundTint">#FFFFFF</item>
        <item name="strokeColor">#80808080</item>
        <item name="strokeWidth">1dp</item>
        <item name="textAllCaps">false</item>
    </style>

    <style name="DialogBodyTextStyle" parent="MaterialAlertDialog.MaterialComponents.Body.Text">
        <item name="android:textColor">#3c3c3c</item>
        <item name="android:textSize">14sp</item>
    </style>

    <style name="DialogTitleTextStyle" parent="MaterialAlertDialog.MaterialComponents.Title.Text">
        <item name="android:textColor">#3c3c3c</item>
        <item name="android:textSize">20sp</item>
    </style>
```

**Android API version:** 
Android 10

**Material Library version:** 
1.1.0

**Device:** 
Pixel 3 XL

**Comment by gabrielemariotti** [comment]
What does it mean
_positioning ignores the button background and does all the calculations according to the text._?

Also be aware that the original style of the buttons is `Widget.MaterialComponents.Button.TextButton.Dialog` and not `Widget.MaterialComponents.Button.TextButton`.

**Comment by fistuk** [comment]
Hey, Im not sure that the original issue is still relevant. I think the title may be changed a bit and the issue changed from bug to question. Let's say I want to use Outlined button or Contained button styles as my dialog buttons and I also want to control the spacing around them:
https://stackoverflow.com/questions/60738264/android-material-dialog-actions-panel-height 

Is something like that currently possible?

**Comment by gabrielemariotti** [comment]
You can do it also if you are going to destroy the design guidelines.

For the OutlinedButton just use:

    <style name="AlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="buttonBarPositiveButtonStyle">@style/PositiveButtonStyle</item>
    </style>

    <style name="PositiveButtonStyle" parent="Widget.MaterialComponents.Button.OutlinedButton">
        <item name="textAllCaps">false</item>

        <item name="android:minWidth">@dimen/mtrl_btn_dialog_btn_min_width</item>
        <item name="android:lines">1</item>
        <item name="android:ellipsize">end</item>
        <item name="android:singleLine">true</item>
        <item name="android:layout_marginStart">@dimen/mtrl_btn_text_btn_padding_left</item>
        <item name="android:layout_marginLeft">@dimen/mtrl_btn_text_btn_padding_left</item>
    </style>

About the spacing in the buttonbar you can use something like:

   <style name="AlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="buttonBarStyle">@style/myButtonBar</item>
    </style>

    <style name="myButtonBar" parent="Widget.AppCompat.ButtonBar">
        <item name="android:paddingTop">16dp</item>
        <item name="android:paddingBottom">16dp</item>
        <item name="android:paddingEnd">16dp</item>
        <item name="android:paddingStart">16dp</item>
    </style>

<img width="274" alt="Schermata 2020-08-02 alle 19 37 12" src="https://user-images.githubusercontent.com/2583078/89128733-16ef9780-d4f8-11ea-885d-03819686ad8c.png">

**Comment by fistuk** [comment]
Thanks a lot for the detailed explanation.
