### ISSUE TITLE
[MaterialAlertDialog] Full screen stacked actions

### ISSUE THREAD

**Issue by fistuk** [material-components/material-components-android#1075]
**Is your feature request related to a problem? Please describe.**
Dialog stacked actions look weird when styled with background:
<img width="337" alt="Screen Shot 2020-03-01 at 12 17 30" src="https://user-images.githubusercontent.com/1989685/75625259-0e9bd500-5bc5-11ea-8bc1-3c9cb01c2cd8.png">

**Describe the solution you'd like**
I would like to get an option to make the stacked buttons full screen:
<img width="290" alt="Screen Shot 2020-03-01 at 14 05 01" src="https://user-images.githubusercontent.com/1989685/75625327-cc26c800-5bc5-11ea-8a80-9f900bcc7b8c.png">

**Describe alternatives you've considered**
1. Give up on the background which will hurt the brand identity.
2. Trying to apply a custom styling to the buttons on runtime, may be problematic with all the calculations going on to decide whether to show side by side or stacked actions.

**Comment by drchen** [comment]
We are supporting full width buttons now.

Please check Widget.MaterialComponents.Button.TextButton.Dialog.FullWidth.
