### ISSUE TITLE
[BottomNavigationView]  Weird background using Material 1.1.0 and Navigation component

### ISSUE THREAD

**Issue by l3vick** [material-components/material-components-android#1077]
I am using some BottomNavigationViews with transparent background in my app and It was working really well but I had to add budgets to my BNV so I added  com.google.android.material:material:1.1.0 stable version

Now my BNV has some weird shadow/background behind and it looks really bad and it's happening everywhere.

![asd](https://user-images.githubusercontent.com/15629729/75661496-b53bb080-5c6d-11ea-9a92-8103963d5b73.png)

![asd2](https://user-images.githubusercontent.com/15629729/75661509-bd93eb80-5c6d-11ea-8925-d39f33d17c77.png)

This is on emulator but on a real device is even worst. It has trapeze form.

I am using: 

minSdkVersion 26

targetSdkVersion 29

navigation_version  2.2.0

material_version 1.1.0

And my BNV is:

```<com.google.android.material.bottomnavigation.BottomNavigationView
                android:id="@+id/topNavigationView"
                style="@style/SearchBottomMenu"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:background="#00000000"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/autoTv"
                app:menu="@menu/search_nav_menu" />
```

This is the style:

```
    <style name="SearchBottomMenu">
        <item name="itemIconTint">@drawable/nav_item_color_state_dark</item>
        <item name="itemTextColor">@drawable/nav_item_color_state_dark</item>
        <item name="android:paddingTop">@dimen/padding_nano</item>
    </style>
```

and this is the menu

```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:id="@+id/trendingSearchFragment"
        android:icon="@drawable/ic_trending"
        android:title="Tendencias" />
    <item
        android:id="@+id/mySearchesFragment"
        android:icon="@drawable/ic_my_preferences"
        android:title="Favoritos" />
    <item
        android:id="@+id/favoriteSearchFragment"
        android:icon="@drawable/ic_my_search"
        android:title="Mis busquedas" />
</menu>
```

if I remove android material 1.1.0 and not excluding material 1.0.0 from navigation component it just looks perfect.

![asd3](https://user-images.githubusercontent.com/15629729/75663213-be7a4c80-5c70-11ea-9f22-936868a543f5.png)

Thanks for any help.

**Comment by PiotrPrus** [comment]
I encounter exactly the same problem and found another fix for it. Or maybe a bypass. The problem occurs only when I am using transparency hex code, for example, color: #CC141414.
Erasing CC helps. The color #141414 does not have this weird rectangle/trapezoidal shape.

**Comment by l3vick** [comment]
Setting elevation to 0 dp also solves the problem

**Comment by rosuH** [comment]
Well... Yes. I had the same problem. I set `android:background=#78ffffff` for it. Remove the Alpha channel and it's fine. But setting elevation to 0 dp not help.

**Comment by norio-agoop** [comment]
Same as here. I'd like to use transparent background color to my BottomNavigationView because I use gradient background color but I just removed alpha for now.

**Comment by hunterstich** [comment]
Yea, what you're seeing is the shadow behind your transparent BottomNavigationView. If you set `app:elevation="0dp"` on your BottomNavigationView, you should get what you're looking for.

**Comment by norio-agoop** [comment]
The point was `app:elevation="0dp"`. Not `android:elevation="0dp"`

**Comment by ericntd** [comment]
Dang, this is very weird. I think one is gonna better of implementing their own BottomNavigationView with something like TabLayout

**Comment by saurabhthorat** [comment]
Another solution that worked for me was using a custom drawable with a transparent rectangle:

```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="#00000000" />
</shape>
```

And setting it to the BottomNavigationView: `android:background="@drawable/bg_bottom_nav"`

**Comment by mrArtCore** [comment]
Prorbably too late but maybe it'll help somebody in the future. 
I encountered the same issue and found out that the problem was in blending overlay color and backgroundColor. Yes we could set elevation to '0dp', but I didn't want to fix it with a workaround. So in my case, the fix was in disabling`elevationOverlay`

```
<style name="AppThemeOverlay.MyTheme.BottomNavigationView" parent="ThemeOverlay.MaterialComponents">
        ...
        <item name="elevationOverlayEnabled">false</item>
</style>
```
and then apply overlayTheme to your BottomNavigation

```
<com.google.android.material.bottomnavigation.BottomNavigationView
    android:id="@+id/bottom_nav_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:theme="@style/AppThemeOverlay.MyTheme.BottomNavigationView" />
```

It doesn't affect your elevation, it doesn't blend colors. 
Like a charm

Material version - **1.2.1**

For more info, see  `com.google.android.material.elevation.ElevationOverlayProvider#compositeOverlayIfNeeded`

**Comment by YongfaWang** [comment]
Thank you. I used `app:elevation="0dp"`. It's very good. The problem has been solved. Google search is good. Baidu search is really rubbish
