### ISSUE TITLE
[Toolbar] Highlight color not updated

### ISSUE THREAD

**Issue by gabrielittner** [material-components/material-components-android#1079]
**Description:** When you use a `Widget.MaterialComponents.Toolbar.Primary` the `colorOnPrimary` is set to `colorControlNormal` in a `ThemeOverlay`. However the `colorControlHighlight` is not set. This means that if your primary color is very dark you get a dark touch feedback on the dark primary color.

**Expected behavior:** `colorControlHighlight` is set to the on surface color or a variation of it.

**Source code:** You can see it in the catalogue app. There is a dark touch feedback on toolbar elements in the light theme and a light touch feedback in the dark theme.

**Android API version:** 29

**Material Library version:** 1.1.0 and 1.2.0-alpha05

**Device:** Emulator

**Comment by dsn5ft** [comment]
Hi @gabrielittner, thanks for filing this issue. In the latest [M3 guidance for Top App Bars](https://m3.material.io/components/top-app-bar/overview), it's not recommended to use a dark primary color as the background anymore. We now have new [`Widget.Material3.*` Top App Bar styles](https://github.com/material-components/material-components-android/blob/382ce9c792e6c4fa5c9728602d68c5b42061682d/lib/java/com/google/android/material/appbar/res/values/styles.xml#L149-L262) which reflect the latest designs, which should also mean that the dark touch feedback should no longer be an issue in M3.
