### ISSUE TITLE
Checking for the size of visible items in BottomNavigationMenu.

### ISSUE THREAD

**Issue by ghost** [material-components/material-components-android#108]
### Version number

 Library version: 1.0.0-alpha2

### Issue

BottomNavigationMenu currently checks the size of menu items instead of currently visible menu items. This restricts from having multiple items whose visibility can be toggled on the fly.

**Comment by drchen** [comment]
Hi, does getMenu().getVisibleItems() serve your needs? 

Since the issue has been really old, I'll close this for now. Feel free to reopen it if this is still something problematic. Thanks!
