### ISSUE TITLE
Exposed Dropdown Menu - Click sounds twice when clicking

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android#1080]
**Description:**
When implementing the menu on Android as per https://material.io/develop/android/components/menu/ if your device or emulator (tested and verified with both) and you click on the field, you hear two quick clicks as if the listener was called twice. If you click the little drop down arrow instead of the text field, you only hear a single sound.

**Expected behavior:** Only a single sound (or maybe single event) should be fired on click

**Android API version:** Only tried on Android 10

**Material Library version:** 1.2.0-alpha05

**Comment by ethanhsuhsu** [comment]
I can confirm this issue, I have experienced this in the catalog app when I added a similar menu

**Comment by lectricas** [comment]
confirm

**Comment by leticiarossi** [comment]
Closed in https://github.com/material-components/material-components-android/commit/fd848e8aaceee6178577fd3af9fe07609158d402
