### ISSUE TITLE
[TextInputLayout][Accessibility] Incorrect error message is announced after activating the TextInputLayout

### ISSUE THREAD

**Issue by tillygajanayake** [material-components/material-components-android#1082]
**Description:** Incorrect error message is announced after activating the TextInputLayout when there are more than one TextInputLayouts available in their error state. This happens in a screen when there are more than one TextInputLayouts available and their error state is active while the TalkBack is on. Please follow these steps to reproduce.
1. Prepare a screen with at least two text input fields.
2. Set all of them with errors to activate their error states.
3. Enable TalkBack
4. Select one text input field and double-tap to activate it.
5. Then select another text input field and double-tap to activate.

It'll be noticed error message of the last selected TextInputLayout will be announced when double-tap to activate another TextInputLayout.

Can keep selecting and double-tapping to activate each TextInputLayout and observe the device will announce the error message of the last selected TextInputLayout.

Please observe the following sequence. The announcements are shown at the bottom of the screen.
<img src="https://user-images.githubusercontent.com/61483610/75743518-5c4f4380-5d65-11ea-9b07-1fa5cebace1e.gif" width=300>

**Expected behavior:** When double-tap to activate a TextInputLayout after select it, the device should not announce anything other than the soft keyboard is been displayed.

**Android API version:** Android API version 29

**Material Library version:** 1.1.0

**Device:** Samsung Galaxy S10+ / Pixel 3

**Comment by leticiarossi** [comment]
I can't reproduce this. There's been improvements to the error message announcement (such as in https://github.com/material-components/material-components-android/commit/11c57abbd6b11829f49bbeafee4153e5442b2725, current available in latest alphas), so I believe this has been fixed.
