### ISSUE TITLE
[TextInputLayout][Accessibility] Editing cursor doesn't appear when activating a TextInputLayout

### ISSUE THREAD

**Issue by tillygajanayake** [material-components/material-components-android#1083]
**Description:** Editing cursor doesn't appear after activating a TextInputLayout when TalkBack is on. Easy to test when there are more than two TextInputLayouts on the screen. Please follow these steps to reproduce. 
1. Turn on the TalkBack.
2. Select any view.
3. Select a TextInputLayout.
4. Select some other view.
5. Select another TextInputLayout.

It'll be noticed the cursor will not be visible when activating the TextInputLayout.

Please observe the following sequence.
<img src="https://user-images.githubusercontent.com/61483610/75744998-07fa9280-5d6a-11ea-97af-956176bf405c.gif" width=300>

**Expected behavior:** The cursor should be visible at the end of the input text when activating the TextInputLayout.

**Android API version:** Android API version 29

**Material Library version:** 1.1.0

**Device:** Samsung Galaxy S10+ / Pixel 3

**Comment by collinbus** [comment]
I think this is unrelated to the TextInputLayout as it is also happening for me in an AppCompatEditText where there is no TextInputLayout wrapped around it. If I'm not mistaken I think that his issue can be closed as it is out of our control.

**Comment by leticiarossi** [comment]
I can see it happening in an EditText alone as well. It's either a framework bug or a TalkBack bug so will close this issue.
