### ISSUE TITLE
[TextInputLayout] Make available to set ellipsize options on the hint

### ISSUE THREAD

**Issue by tillygajanayake** [material-components/material-components-android#1084]
**The problem description**
Unable to set ellipsize options on the hint. The hint always ellipsis at the end. If this option is available for change, developers could decide how they want to use it. 

In my case, I need to wrap the content in the hint to support the large text users. As per WCAG guidelines, the hint should always be visible whether large text/display size is enabled or not. With no ellipsize option available, the hint will not wrap hence it will go into ellipses state. This will hinder label information to the large text user ([WCAG criteria 1.4.4 Resize text failure](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html)). 

**Solution I'd like to propose**
Please provide an attribute exposed to set the ellipsize on the hint. By default, it can be an ellipsis end.

**The only alternatives we've considered**
Limit the content length of the hint to fit in when large text on.

**Additional context**
Please refer to these screenshots to understand the problem.
<img src="https://user-images.githubusercontent.com/61483610/75750890-4c415f00-5d79-11ea-9855-53df4480b12e.png" width=200> <img src="https://user-images.githubusercontent.com/61483610/75750893-4e0b2280-5d79-11ea-9b2c-7483ffe05bd9.png" width=200>

**Material Library version:** 1.1.0

**Comment by drchen** [comment]
This can result in very broken UX. I would suggest you to avoid long labels in large text mode and use helper text or add a separate label text view instead in this use case.

Closing the issue for now.
