### ISSUE TITLE
[BottomSheet] @style/Widget.MaterialComponents.BottomSheet should be public

### ISSUE THREAD

**Issue by GSala** [material-components/material-components-android#1085]
`@style/Widget.MaterialComponents.BottomSheet`
and
`@style/Widget.MaterialComponents.BottomSheet.Modal`
should be made public.

Otherwise, we can only inherit a bottom sheet style from `@style/Widget.Design.BottomSheet.Modal` which doesn't use the `shapeAppearance` theme attributes, for example.

**Additional context**
These are public:
```
<public name="Theme.MaterialComponents.BottomSheetDialog" type="style"/>
<public name="Theme.MaterialComponents.Light.BottomSheetDialog" type="style"/>
<public name="Theme.Design.BottomSheetDialog" type="style"/>

<public name="Widget.Design.BottomSheet.Modal" type="style"/>
```
These are NOT public:
```
<public name="Widget.MaterialComponents.BottomSheet" type="style"/>
<public name="Widget.MaterialComponents.BottomSheet.Modal" type="style"/>
```

**Comment by melaniegoetz** [comment]
Hi there!
This looks like a quick fix so I'll sync out a change for it this week. Thanks for pointing this out to us!

**Comment by melaniegoetz** [comment]
This fix has been [synced out](https://github.com/material-components/material-components-android/commit/d0f13768b5b05d423a6c3c24520eac116cafd97c)! Thanks again for reporting
