### ISSUE TITLE
[BottomSheet] Theme.MaterialComponents.BottomSheetDialog uses wrong bottomSheet style

### ISSUE THREAD

**Issue by GSala** [material-components/material-components-android#1086]
**Description:** 
```
<style name="Theme.MaterialComponents.BottomSheetDialog" parent="Theme.MaterialComponents.Dialog">
  <item name="android:windowBackground">@android:color/transparent</item>
  <item name="android:windowAnimationStyle">@style/Animation.MaterialComponents.BottomSheetDialog</item>
  <item name="bottomSheetStyle">@style/Widget.Design.BottomSheet.Modal</item>
</style>
```
in [source](lib/java/com/google/android/material/bottomsheet/res/values/themes.xml).
Theme uses `@style/Widget.Design.BottomSheet.Modal` instead of `@style/Widget.MaterialComponents.BottomSheet.Modal`.

`@style/ThemeOverlay.MaterialComponents.BottomSheetDialog` uses `@style/Widget.MaterialComponents.BottomSheet.Modal`.

**Comment by melaniegoetz** [comment]
Hi there! Thanks for pointing this out, this is indeed a bug. 
Look out for a fix for this to be synced out soon!
