### ISSUE TITLE
Exposed Dropdown Menu - If dropdown is disabled, the arrow still spins on click

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android#1087]
Description:
When implementing the menu on Android as per https://material.io/develop/android/components/menu/ if you set isEnabled = false you can click the field and nothing happens. But if you click the downward arrow, it flips to be upward

Expected behavior: Arrow should be disabled as well

Android API version: Only tried on Android 10

Material Library version: 1.2.0-alpha05

**Comment by leticiarossi** [comment]
Hi, I see this is reproducible if you set `android:enabled` on the `AutoCompleteTextview`, but you should be setting it on the `TextInputLayout` instead. That should fix your issue!

**Comment by ColtonIdle** [comment]
@leticiarossi confirmed that this worked! I'd love for there to be a callout in the docs for this stuff. I think I read on twitter that you're revamping a lot of docs and so something like this is so basic that it should be called out. Similar problem. Just figuring out how to clear the selection of dropdown or getting the selection from the dropdown. All "basic" usages that would be great to outline. Or just lint checks for all of this... =)

**Comment by leticiarossi** [comment]
Will update the text fields doc to include `android:enabled` in its container's attrs table! We haven't updated the Menus doc yet but will keep that in mind, thank you.

**Comment by ColtonIdle** [comment]
Thank you!
