### ISSUE TITLE
[TextInputLayout] Unable to set a content description to error message

### ISSUE THREAD

**Issue by tillygajanayake** [material-components/material-components-android#1088]
**Description:** Unable to set a content description into the error message. Without having the content description it is difficult to announce certain error messages correctly.

**Expected behavior:** There should be a way to set a content description into the error message.

**Android API version:** Android API version 28

**Material Library version:** 1.1.0

**Device:** Emulator Pixel 3

**Comment by leticiarossi** [comment]
Hi, this has been implemented in https://github.com/material-components/material-components-android/commit/aeb9eea9d86a8abe58b09daa6964d5a09523d363 and is available in the most recent alphas. It'll be available in the next stable.
