### ISSUE TITLE
[TextInputLayout] Unable to set a content description to support message

### ISSUE THREAD

**Issue by tillygajanayake** [material-components/material-components-android#1089]
**Description:** Unable to set a content description into the support message. Without having the content description it is difficult to announce certain support messages correctly.

**Expected behavior:** There should be a way to set a content description into the support message.

**Android API version:** Android API version 28

**Material Library version:** 1.1.0

**Device:** Emulator Pixel 3

**Comment by leticiarossi** [comment]
What's your use case for that?
Usually the error message would be the one to have special characters that would require content description.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if there is still a need for this.
