### ISSUE TITLE
[ExtendedFloatingActionButton] Elevate Visibility of Behavior Implementation

### ISSUE THREAD

**Issue by froriz5** [material-components/material-components-android#1091]
**Problem**
Currently, the `CoordinatorLayout.Behavior` implemention used by `ExtendedFloatingActionButton`, [ExtendedFloationActionButtonBehavior](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/floatingactionbutton/ExtendedFloatingActionButton.java#L659) has its visibility as `protected`.

Therefore, the only way to access that implementation or build upon it is to extend the `ExtendedFloatingActionMenu` with your own custom view. 

**Solution**
Raising the visibility of this class to `public` would make it easier to access the default Behavior's implementation or build upon it, without having to extend `ExtendedFloatingActionButton`.

**Comment by drchen** [comment]
Can you describe your need in more details? 

ExtendedFloatingActionButtonBehavior is intended to work with ExtendedFloatingActionButton so if you want to customize either of them, you can/have to customize the other one.

It's not intended to be used outside the ExtendedFloatingActionButton.

**Comment by froriz5** [comment]
Apologies, I have since moved on from this issue, and do not recall the particular use case.

**Comment by drchen** [comment]
No worries. Sorry for that the request had been left unnoticed for a long while. 

I'll close the issue for now but please feel free to reopen it or open a new one when the need resurges.
