### ISSUE TITLE
[Pickers] Can't access to android pickers page (status 404)

### ISSUE THREAD

**Issue by renaudmathieu** [material-components/material-components-android#1093]
**Description:** 404 Page not found on https://material.io/develop/androidcatalog/picker.html 

<img width="1157" alt="404_android_pickers" src="https://user-images.githubusercontent.com/4282867/76084967-5d74b080-5fb1-11ea-8688-f7432a896ca2.png">

**Expected behavior:**  Website with the doc

Alternative: https://github.com/material-components/material-components-android/blob/master/docs/components/Picker.md

**Comment by leticiarossi** [comment]
The issue that was causing this was fixed and the page should be live soon. Thanks for reporting!
