### ISSUE TITLE
[lists] Background for selected and checked state

### ISSUE THREAD

**Issue by Sourav-21** [material-components/material-components-android#1095]
Material list item use `?attr/selectableItemBackground` as the background which doesn't have any tint for selected and checked state. But in many cases list items are selectable.

**Comment by ethanhsuhsu** [comment]
I am looking into implementing checkable items as soon as the initial resources for Material Lists have been put in place. If that does not answer your question, please clarify with a response @Sourav-21.

**Comment by Sourav-21** [comment]
@ethanhsuhsu `?attr/selectableItemBackground` provides ripple effect for focused, hover and pressed states. But it doesn't provide any background overlay for selected and checked state. But list items may be checkable or selectable also. So there is no way to distinguish selected or checked list items.

**Comment by drchen** [comment]
I think you can override the theme attribute ?attr/selectableItemBackground to provide your own drawable version of it. 

Does that serve your need?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if the solution doesn't work.
