### ISSUE TITLE
setOnNavigationItemSelectedListener of BottomNavigationView is not triggered?!

### ISSUE THREAD

**Issue by Robotecom** [material-components/material-components-android#1099]
**Description:** 
OnNavigationItemSelectedListener listener is not called when i select any tab in bottomNavigationView

````
private void setupBottomNavigation(NavController navController) {
        BottomNavigationView bottomNavigationView = findViewById(R.id.bottom_navigation);
```

        bottomNavigationView.setOnNavigationItemSelectedListener(new BottomNavigationView.OnNavigationItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                if (item.getItemId() == R.id.search_dest) {

                    Log.d(TAG, "onNavigationItemSelected: search fragment");

                } else {
                    Log.d(TAG, "onNavigationItemSelected: default fragment");
                }
                return true;
            }
        `});`  
  NavigationUI.setupWithNavController(bottomNavigationView, navController);
    }``


currently I'm using 'com.google.android.material:material:1.2.0-alpha05'

**Comment by ymarian** [comment]
seems NavigationUI replaces the lisitener you are setting. Since this is outside our library. Maybe report a bug with them.

https://issuetracker.google.com/issues/new?component=409828

**Comment by aaron-bamboo** [comment]
@Robotecom I ran into a similar issue.  You might have already solved this, but I solved it as follows:

Instead of returning `true` from your `OnNavigationItemSelectedListener`  return ` NavigationUI.onNavDestinationSelected(menuItem, navController)`.

Also, call `setupWithNavController` **before** adding your listener.
