### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by jeevansurendran** [material-components/material-components-android#110]
I tried to use the material design for chips and these are the problems I faced
1) I first implemented the plugin and it only works for Android P
2)Then when I implemented it. It seems that I cannot use "com.android.support:support-v4:28.0.0-alpha1" because of some error.

> program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy 
   Message{kind=ERROR, text=Program type already present: 
   android.support.v4.app.INotificationSideChannel$Stub$Proxy, sources=[Unknown source file], tool 
   name=Optional.of(D8)}

3)i then used support library 27.1.1 it worked but ram consumtion became very high.

**Comment by dsn5ft** [comment]
If you want to use `com.android.support:support-v4:28.0.0-alpha1`, then you have to use `com.android.support:design:28.0.0-alpha1` instead of `com.google.android.material:material:1.0.0-alpha1`.

**Comment by jeevansurendran** [comment]
I have implemented everything it's still shows an error. It's a build error.

**Comment by jeevansurendran** [comment]
My gradle is here. 
I will link a related stackoverflow question [here](https://stackoverflow.com/questions/50289355/google-material-design-library-error-program-type-already-present-android-suppo/50301692#comment87750145_50301692). 

    apply plugin: 'com.android.application'
    
    android {
        compileSdkVersion 'android-P'
    
        defaultConfig {
            applicationId "com.silverpants.todolist"
            minSdkVersion 21
            targetSdkVersion 27
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
        compileOptions {
            targetCompatibility JavaVersion.VERSION_1_8
            sourceCompatibility JavaVersion.VERSION_1_8
        }
    }
    
    dependencies {
        implementation fileTree(include: ['*.jar'], dir: 'libs')
    
        implementation 'com.android.support:appcompat-v7:28.0.0-alpha1'
        implementation 'com.android.support:design:28.0.0-alpha1'
        implementation 'com.android.support:support-v4:28.0.0-alpha1'
    
        implementation 'com.android.support.constraint:constraint-layout:1.1.0'
        implementation 'com.google.android.material:material:1.0.0-alpha1'
    
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test:runner:1.0.2'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    }

Thhe problem I am facing while developing the app is that, i am not able to use support libarary

>    implementation 'com.android.support:support-v4:28.0.0-alpha1'

because it says the program type is already present.
Error Log Below.

> Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy Message{kind=ERROR, text=Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy, sources=[Unknown source file], tool name=Optional.of(D8)}

some link which might help you :- 
https://material.io/develop/android/components/chip/
https://material.io/develop/android/docs/getting-started/

**Comment by braulio94** [comment]
Same error here:
* If I implement support for android P I can't install app on my android api 27 device.
* If I implement the material library it will fail to build project.
What's the solution for this?

**Comment by braulio94** [comment]
> What's the solution for this?
[Follow this steps](https://codelabs.developers.google.com/codelabs/mdc-101-java/index.html?index=..%2F..%2Findex#1)

**Comment by dsn5ft** [comment]
@jeevansurendran the error is happening because you are using both `com.android.support:design:28.0.0-alpha1` and `com.google.android.material:material:1.0.0-alpha1`. You either have to stick with all of the `com.android.support` libraries and use `com.android.support:design:28.0.0-alpha1`, or you have to migrate to androidx and then you can use `com.google.android.material:material:1.0.0-alpha1` (without `com.android.support:design:28.0.0-alpha1`). I've updated our getting started docs to be more clear about this - https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md

**Comment by jeevansurendran** [comment]
What about these views?
android.support.design.widget.CoordinatorLayout
android.support.design.widget.AppBarLayout
android.support.v7.widget.Toolbar

What will be the replacement in the class

**Comment by dsn5ft** [comment]
CoordinatorLayout has moved to the `androidx.coordinatorlayout:coordinatorlayout:1.0.0-alpha1` dependency, and the `androidx.coordinatorlayout.widget` package.

AppBarLayout is still in MDC-Android (`com.google.android.material:material:1.0.0-alpha1`) in the `com.google.android.material.appbar` package.

Toolbar has moved to the `androidx.appcompat:appcompat:1.0.0-alpha1` dependency, and the `androidx.appcompat.widget` package.

I recommend following the instructions here for how to migrate to the new androidx libraries - https://developer.android.com/studio/preview/features/#androidx_refactoring.

**Comment by jeevansurendran** [comment]
Thanks a lot @dsn5ft that link was very helpful.
