### ISSUE TITLE
BottomNavigationView unwanted insets

### ISSUE THREAD

**Issue by kirvis250** [material-components/material-components-android#1100]
It's rather simple request. I need ability to implement my own insets handling. 
In fact i have my own insets handling and BottomNavigation makes it double.

**Comment by kirvis250** [comment]
For my usage changing `private void applyWindowInsets()` to `protected void applyWindowInsets()` 
would suffice.
![insets](https://user-images.githubusercontent.com/6008835/76325719-4fe06300-62f0-11ea-9bf0-b33600c70d2f.png)

**Comment by drchen** [comment]
Hi, I think you can just reset OnApplyWindowInsetsListener on your custom view. Would that work for your case?

**Comment by josefigueroa168** [comment]
We are currently on updating the insetWindow logic. In the meantime, if you update the following bottomsheet flags in your theme to false, the current logic does not apply a window inset listener, so yours would take precedent (not double as you describe it):

```XML
  <style name="Base.V14.ThemeOverlay.Material3.BottomSheetDialog" parent="Base.ThemeOverlay.Material3.Dialog">
    <item name="paddingBottomSystemWindowInsets">false</item>
    <item name="paddingLeftSystemWindowInsets">false</item>
    <item name="paddingRightSystemWindowInsets">false</item>
    <item name="paddingTopSystemWindowInsets">false</item>
  </style>
```
and 

```XML
<FrameLayout
        app:layout_behavior="@string/bottom_sheet_behavior"
         ...
        app:gestureInsetBottomIgnored="true"
/>
```

Let me know if this resolves your use case.

**Comment by josefigueroa168** [comment]
Apologies, the former post was referring to bottomsheet, not bottom navigation.

**Comment by drchen** [comment]
@pubiqq I meant you can just call `ViewCompat.setOnApplyWindowInsetsListener(bottomNavigationView, your_custom_inset_listener)` to reset the listener the Material library set and consume the insets if you want. Wouldn't that work for you?

**Comment by dsn5ft** [comment]
Setting a new inset listener as mentioned above is the recommendation from the Android framework on how the default listener of a view/component can be overridden.
