### ISSUE TITLE
[MaterialButtonToggleGroup] Build abstraction to handle "singleSelection" and "selectionRequired" in other components

### ISSUE THREAD

**Issue by GSala** [material-components/material-components-android#1101]
**Is your feature request related to a problem? Please describe.**
I like the built in logic to handle `singleSelection` vs `multipleSelection` for choices (and choice listeners) in the `MaterialButtonToggleGroup` but having that in this `ViewGroup` itself limits it to this specific layout. Sometimes I'd like to have the same behavior in a list of selectables items. Or any other layout with items that wouldn't really fit the `MaterialButtonToggleGroup` use case.

**Describe the solution you'd like**
I'd like to separate the logic that manages the selected/cecked states into a `Helper` class that could be made public and usable for other views or components.

It's not a well-formed idea but I'd like to discuss if anyone else would find this useful.
It also seems a bit outside of this library's responsibilities.

**Comment by ymarian** [comment]
We talked about this a bit in the past, it does seem like a reasonable idea but I agree it falls outside the library responsibilities and separating into more classes without a usecase in the lib for another components will add maintenance burden.
