### ISSUE TITLE
[com.google.android.material.textfield.TextInputLayout] Outline overlaps hint

### ISSUE THREAD

**Issue by AnastasiaRainMaker** [material-components/material-components-android#1102]
**Issue**: Hint is crossed by the outline of the OutlinedBox TextInoutLayout no matter the length of the hint.

**Expected behavior**: Hint is displayed without overlapping with the box. 

**Library**: 'com.google.android.material:material:1.2.0-alpha05'
**Device** Android 7.1, Pax Aries 8
**Orientation**: always landscape. 

**Sample code:**

```
<com.google.android.material.textfield.TextInputLayout
                            android:id="@+id/text_special_requirements"
                            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_marginTop="24dp"
                            android:layout_marginBottom="16dp"
                            android:hint="@string/edittext_hint_comments"
                            android:textColorHint="@color/medium_gray"
                            app:boxStrokeColor="@color/medium_gray"
                            app:boxStrokeWidth="1dp"
                            app:layout_constraintBottom_toBottomOf="parent"
                            app:layout_constraintEnd_toEndOf="@+id/options_recycler"
                            app:layout_constraintHorizontal_bias="0.0"
                            app:layout_constraintStart_toStartOf="@+id/options_recycler"
                            app:layout_constraintTop_toBottomOf="@+id/options_recycler"
                            app:layout_constraintVertical_bias="1.0">

                            <com.google.android.material.textfield.TextInputEditText
                                android:id="@+id/special_requirements_edit_text"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                             android:digits="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890 ,."
                                android:imeOptions="actionDone"
                                android:inputType="text"
                                android:maxLines="5"
                                android:singleLine="true"
                                android:text="@={viewmodel.commentText}"
                                android:textColor="@color/dark_gray"
                                android:textSize="@dimen/text_size_normal"
                                tools:text="More onions" />
                        </com.google.android.material.textfield.TextInputLayout>
```

**Screenshots of the issue:**

![Screenshot_20200310-140349](https://user-images.githubusercontent.com/33650124/76354820-308e0980-62e1-11ea-9e38-ffdcce781f42.png)

![Screenshot_20200310-140533](https://user-images.githubusercontent.com/33650124/76354845-38e64480-62e1-11ea-9109-a512a540e098.png)

**Comment by blackevil2703** [comment]
I'm having a different kind that outlinedbox overlaps the hint

**Comment by wcshi** [comment]
@AnastasiaRainMaker re: "Orientation: always landscape", does this mean it consistently happens in landscape OR that your app's orientation is set to landscape? 
Do you focus on the input before or after the device is in the landscape orientation?

**Comment by wcshi** [comment]
@blackevil2703 please provide details about the overlap issue you are experiencing.

**Comment by AnastasiaRainMaker** [comment]
@wcshi I mean the app is locked to landscape.  No orientation change is happening for the app.

**Comment by wezley98** [comment]
Not seeing this anymore in 1.2.0-beta01

**Comment by AnastasiaRainMaker** [comment]
the overlap is gone but no there is an empty space between the label and the outline

**Comment by AnastasiaRainMaker** [comment]
![Screenshot_20200729-153527](https://user-images.githubusercontent.com/33650124/88850752-6872ec00-d1b1-11ea-94e8-9cd6504ceec3.png)

**Comment by leticiarossi** [comment]
can you provide a sample app where the issue is reproducible?

**Comment by leticiarossi** [comment]
We've recently made changes to how the cutout is made. If you're still seeing issues please reopen and provide a sample app so we can investigate it.
