### ISSUE TITLE
[TextInputLayout] I don't change underline color for textInput with Editext inside it. help me

### ISSUE THREAD

**Issue by lvhuy1102** [material-components/material-components-android#1103]
**Description:** I don't change underline color for textInput with Editext inside it. help me

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** android 4.2 and android 9.0

**Material Library version:** implementation 'com.google.android.material:material:1.1.0'

**Device:** android 4.2 and android 9.0

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
If you're referring to the filled style, the underline color is set via `app:boxStrokeColor`. More info on the [text fields doc](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#activation-indicator-attributes) 
I'll close this but feel free to reopen with more info/details if you still have an issue.
