### ISSUE TITLE
[FloatingActionButton] FAB Icon is Always Black

### ISSUE THREAD

**Issue by HeyItsMedz** [material-components/material-components-android#1106]
Hello!

For some reason when I set an icon using `android:src` on a FAB, it will force the icon to be black rather than whatever colour the (vector) icon actually is. The issue popped up once I upgraded from 1.0.0 to 1.1.0, and can be seen directly from the XML layout preview. Using `android:tint` does not resolve the issue

Unfortunately I'm also relying on a bug fix in 1.1.0 for another component, so it's not like I can revert back to 1.0 and call it a day

I tried to see if the issue still occurred if I opened a new application from Android Studio. Interestingly, the icon will stay black if app theme's parent is set to `Theme.MaterialComponents.Light` but shows correctly if changed to `Theme.AppCompat.Light`

**Source code**
This can be reproduced by opening a new project in Android Studio, choosing the Empty Activity option. 

Set the AppTheme parent to `Theme.MaterialComponents.Light`, and change the generated activity_main.xml to this:

activity_main.xml
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="56dp"
        android:layout_marginBottom="36dp"
        android:src="@drawable/ic_arrow_forward_white_24dp"
        android:tint="@android:color/white"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

ic_arrow_forward_white_24dp.xml (this is generated as a Vector Asset within Android Studio):
```
<vector android:height="24dp" android:tint="#FFFFFF"
    android:viewportHeight="24.0" android:viewportWidth="24.0"
    android:width="24dp" xmlns:android="http://schemas.android.com/apk/res/android">
    <path android:fillColor="#FF000000" android:pathData="M12,4l-1.41,1.41L16.17,11H4v2h12.17l-5.58,5.59L12,20l8,-8z"/>
</vector>
```

Switching `com.google.android.material:material` version between 1.0.0 and 1.1.0 will show the icon changes colour

**Material Library version:**
1.0.0: Works correctly
1.1.0-alpha01: Does not work as expected
1.1.0: Does not work as expected
1.2.0-alpha05: Does not work as expected

I hope that helps! Any solution or workaround would be much appreciated. I'm happy to answer any questions if needed.

All the best!
Medz

**Comment by EdricChan03** [comment]
Could you try using `app:srcCompat` instead?

**Comment by HeyItsMedz** [comment]
Hi Edric.

I'm afraid `app:srcCompat` has the same effect and doesn't fix the issue

**Comment by cmoijulien** [comment]
I have the same issue.
Works well with theme Theme.AppCompat.DayNight.DarkActionBar but not with theme Theme.MaterialComponents.DayNight.DarkActionBar.
Unfortunately, to use the components we have to use the theme **Theme.MaterialComponents**

**Comment by Jordan-Turgeon** [comment]
Setting the colour programatically seems to work

**Comment by alyrow** [comment]
Hi,
Try to replace ```android:tint="@android:color/white"``` by ```app:tint="@android:color/white"```.

**Comment by FadwaBechri** [comment]
Hello,
try to put this line : `app:tint="@null"` it worked for me.

**Comment by calvarez-ov** [comment]
For info, `app:imageResource` (instead of `android:src` or `app:srcCompat`) works with `app:tint` as well.

This is useful if you use databinding: `app:srcCompat` doesn't work with databinding by default (it requires writing a custom databinding adapter, which can be simple, but hey, if `app:imageResource` works, why write more code? 😄 )

**Comment by computer-zombie** [comment]
> Hello,
> try to put this line : `app:tint="@null"` it worked for me.

Yes, it works.. It make the icon use its original color

**Comment by computer-zombie** [comment]
The IDE doesn't recognized app:tint
you have to type it manually ->
app:tint="@null" -> the icon will be it's original color
app:tint="@color/white" (if you have white in your colors) -> the icon will use white color or any other designated color

**Comment by Gaurav-Joshi-31** [comment]
> Hello,
> try to put this line : `app:tint="@null"` it worked for me.

Thank you bro. It worked

**Comment by drchen** [comment]
I'll close the issue since it seems we already have the right answer here. : )

**Comment by MrAgui** [comment]
> Hi, Try to replace `android:tint="@android:color/white"` by `app:tint="@android:color/white"`.

works well for me! Cheers

**Comment by lil-dua** [comment]
> 



> Hi, Try to replace `android:tint="@android:color/white"` by `app:tint="@android:color/white"`.

thank you so much, i fixed it <3

**Comment by Atomix2402** [comment]
> Hello, try to put this line : `app:tint="@null"` it worked for me.

Hey uh, I'm new to android studio and i wanna ask where to put this line and also whenever i try "app:tint" i'm getting an error could you help

**Comment by rehmanjameel** [comment]
> Hi, Try to replace `android:tint="@android:color/white"` by `app:tint="@android:color/white"`.

it's worked for me too.
