### ISSUE TITLE
[TabLayout] ripple is darker than set color

### ISSUE THREAD

**Issue by ursusursus** [material-components/material-components-android#1109]
Hi, all my ripples are of color ?attr/colorControlHighlight which I override to #11000000.

However if I override it on tabLayout via

```
<style name="DefaultTabLayout" parent="Widget.MaterialComponents.TabLayout">
    ...
    <item name="tabRippleColor">?attr/colorControlHighlight</item>
    ...
</style>
```

Its ripple is still way darker than some component next to it on which I manually set a ripple foreground selector

For completeness, here is the ripple selector I use on my other views
```
<?xml version="1.0" encoding="utf-8"?>
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
    android:color="?attr/colorControlHighlight">

    <item android:id="@id/android:mask">
        <color android:color="@color/colorWhite" />
    </item>

</ripple>
```
First I thought It was a MDC thing, but then I also override rippleColor of a MaterialButton and that works fine.

Here is a screenshot

![Screenshot_20200313-040540 (1)](https://user-images.githubusercontent.com/1503402/76586155-52091400-64e0-11ea-9230-086d96ca80bd.png)

You can see both the button and unselected tab pressed, and observe tab being way darker

**Comment by drchen** [comment]
Is this still an issue with the Material 3 themes/styles?

**Comment by ArcherEmiya05** [comment]
Any update on this? We are not using Material 3 Theme and migrating to it requires a huge amount of time and effort. Now is not a right time for us to do it so we hope that there is an alternative way to fix this. Thanks

**Comment by Janneman84** [comment]
I'm experiencing the same thing in Android 13. It's impossible to set `app:tabRippleColor` fully transparent...

What you can do for now is setting it to #0000, which is transparent white (instead of transparent black what android:color/transparent is.

Change white to whatever the background color is. Only problem this way is that it's still broken in automatic dark mode in Android 13.

These are just workaround though, it's something broken that hopefully gets fixed someday.

**Comment by huangssh** [comment]
> I'm experiencing the same thing in Android 13. It's impossible to set `app:tabRippleColor` fully transparent...
> 
> What you can do for now is setting it to #0000, which is transparent white (instead of transparent black what android:color/transparent is.
> 
> Change white to whatever the background color is. Only problem this way is that it's still broken in automatic dark mode in Android 13.
> 
> These are just workaround though, it's something broken that hopefully gets fixed someday.

Try this for a solution
`app:tabRippleColor="@null"`

**Comment by Janneman84** [comment]
> Try this for a solution `app:tabRippleColor="@null"`

Wow this actually works! I can't believe I hadn't tried his myself...
