### ISSUE TITLE
Badge feature is not implemented for Android BottomNavigationView

### ISSUE THREAD

**Issue by ultraon** [material-components/material-components-android#111]
### Overview
 - According to https://material.io/design/components/bottom-navigation.html#behavior (Badge section) BottomNavigationView has to support badge icon or badge with number. But current public API doesn't contain such a feature.

### Version number

 - Found in CHANGELOG.md - There is no CHANGELOG.md file.
But I think the version is 1.0.0-alpha1

### Operating system and device
Android OS

**Comment by nthieu90** [comment]
Waiting for support badge icon. Or Is there any way to change the icon with a red dot? Because It effects by tint color.

**Comment by umang6891** [comment]
Any updates on the badge?

**Comment by Ghedeon** [comment]
Honestly, it's ridiculous how poorly this widget is implemented. After 2 years of development, it still lacks functionality that is expected by the guidelines. That doesn't make any sense.

**Comment by wcshi** [comment]
Thank you for your patience, please follow the feature request here: https://issuetracker.google.com/issues/119868633
