### ISSUE TITLE
[TabLayout] Background color behavior changed without mention in release notes

### ISSUE THREAD

**Issue by carstenhag** [material-components/material-components-android#1110]
Hey, I can imagine many things get changed in one release and it is difficult to properly sum it up.

It was a bit annoying though, having to manually go through the app and find some instances where suddenly a button did not have styling anymore (theme issues) or for example the TabLayout now not being transparent anymore, but now having a white background per default, it seems.

Before: 1.0.0
(The tablayout is at the bottom, we only show page indicators which don't show up in the preview)
<img width="381" alt="Bildschirmfoto 2020-03-13 um 17 56 47" src="https://user-images.githubusercontent.com/3776997/76642945-6d156b80-6554-11ea-88c4-b3643840b7fb.png">

After: 1.0.0
<img width="375" alt="Bildschirmfoto 2020-03-13 um 17 57 05" src="https://user-images.githubusercontent.com/3776997/76642960-76063d00-6554-11ea-9776-0f56a0163fbc.png">

Had to manually debug 20 minutes into this (we have multiple brands, for some it was fine) and then look at the 10 coloring options, then finding that I just had to manually set `android:background`.

Perhaps you can just close this issue, but it would be super great if in the future the release notes would be more meaningful.

**Comment by melaniegoetz** [comment]
Thanks so much for this feedback! We are actively working on more in-depth documentation and release notes, so appreciate you sharing your experience
