### ISSUE TITLE
Why MaterialBadge does not support all Views?

### ISSUE THREAD

**Issue by dariush-fathie** [material-components/material-components-android#1112]
Why limit MaterialBadge to bottomNavigation. if we can use Badges with all type of view it's can be great.
For example FAB with a badge or ImageView(commonly-used) with a badge

thank you all

**Comment by wcshi** [comment]
Thanks for your interest, badge is currently supported for bottom nav and tabs. This component is currently under development and Material is plans to do more research on expanded use cases. Thanks for your patience. 

Could you please explain specifically when you'd like to show a badge with a FAB or an imageview? It will help our designers evaluate your use cases.

**Comment by paulkugaev** [comment]
@wcshi for instance ImageView with src like `ic_notification` and badge on it

**Comment by wcshi** [comment]
Hi @paulkugaev could you please provide the following so i can share with our designers:
1)  mock of what you want
2) description of business use case

Thanks!

**Comment by paulkugaev** [comment]
![image](https://user-images.githubusercontent.com/9088784/76982762-62404980-694d-11ea-9c73-d35ec99f9487.png)

**Comment by wcshi** [comment]
Similar to https://github.com/material-components/material-components-android/issues/445, closing this and tracking there.
