### ISSUE TITLE
[BottomSheetDialog] BottomSheetDialog.Bridge style missing

### ISSUE THREAD

**Issue by samlu** [material-components/material-components-android#1114]
Please add the following 2 styles
Theme.MaterialComponents.BottomSheetDialog.Bridge
Theme.MaterialComponents.BottomSheetDialog.Light.Bridge

**Comment by wcshi** [comment]
Could you please explain your use case?

**Comment by samlu** [comment]
I am following instructions of **Bridge Themes** section (https://material.io/develop/android/docs/getting-started/#bridge-themes) to define my own theme.

I can see `Theme.MaterialComponents.Dialog.Bridge`, `Theme.MaterialComponents.Dialog.Alert.Bridge`, `Theme.MaterialComponents.Dialog.MinWidth.Bridge`, etc. from the library. 
But, unfortunatly, there is no `Theme.MaterialComponents.BottomSheetDialog.Bridge` style defined. That's why I request to add the following 2 missing styles
`Theme.MaterialComponents.BottomSheetDialog.Bridge`
`Theme.MaterialComponents.BottomSheetDialog.Light.Bridge`

**Comment by drchen** [comment]
We have no plan to support bridge themes anymore. 

Please use theme overlays instead.
