### ISSUE TITLE
[DialogWhenLarge] DialogWhenLarge.Bridge style missing

### ISSUE THREAD

**Issue by samlu** [material-components/material-components-android#1115]
Please add the following 2 styles:
Theme.MaterialComponents.DialogWhenLarge.Bridge
Theme.MaterialComponents.Light.DialogWhenLarge.Bridge

**Comment by wcshi** [comment]
Could you please explain your use case?

**Comment by samlu** [comment]
I am following instructions of **Bridge Themes** section (https://material.io/develop/android/docs/getting-started/#bridge-themes) to define my own theme.

I can see `Theme.MaterialComponents.Dialog.Bridge`, `Theme.MaterialComponents.Dialog.Alert.Bridge`, `Theme.MaterialComponents.Dialog.MinWidth.Bridge`, etc. from the library. 
But, unfortunately, there is no `Theme.MaterialComponents.DialogWhenLarge.Bridge` style defined. That's why I request to add the following 2 missing styles
`Theme.MaterialComponents.DialogWhenLarge.Bridge`
`Theme.MaterialComponents.DialogWhenLarge.Light.Bridge`

**Comment by wcs-dev** [comment]
any particular reason you are not using the full themes?

**Comment by samlu** [comment]
Why does your team provide Material Components Bridge theme?

**Comment by drchen** [comment]
Since we launched Material 3 which doesn't support bridge themes anymore. I'll close this issue as obsolete.
