### ISSUE TITLE
[Toolbar] Navigation icon color red on Android 5.1.1

### ISSUE THREAD

**Issue by wbervoets** [material-components/material-components-android#1119]
**Description:** 

`<com.google.android.material.appbar.AppBarLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/appBarLayout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
    <com.google.android.material.appbar.MaterialToolbar
        android:id="@+id/toolBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        style="@style/Widget.MaterialComponents.Toolbar.Surface" />

</com.google.android.material.appbar.AppBarLayout>` 

I'm using the style @style/Widget.MaterialComponents.Toolbar.Surface 
I expect it to use my colorSurface and colorOnSurface attributes from my theme for the background and the tinting of the hamburger navigation icon

My colorSurface color is white / my colorOnSurface color is black in Day (light) mode

This issue is that on Android 5.1.1 devices the hamburer icon is tinted red. The background color of the toolbar is white and the title of the toolbar is also black as expected. The only red color I'm using is for errors (colorError). I do not understand where this red color comes from

My app theme parent is Theme.MaterialComponents.DayNight.NoActionBar 

I do not see this bug when using Widget.MaterialComponents.Toolbar.PrimarySurface on Android 5.1.1 but then it uses my primary color / primary on color which in this case I do not want to use

**Expected behavior:** 

I would expect the navigation icon to be black too.

**Android API version:** 

API 21

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

1.1.0 or any 1.2 alpha

**Device:**

LGE Nexus 4 running Android 5.1.1

**Comment by aL05flas** [comment]
Hello! I also encountered this problem and after three days of research I found out that the dark theme uses the resource to colorControlNormal across ColorStateList with alpha and color+theme attribute, what work since Android M+, otherwise there will be an error and red color. The material design library currently does not represent the correct implementation of resources for Android < M.

**Comment by killvetrov** [comment]
I've also done some research on this issue with repro project in #1820.

**Comment by ArcherEmiya05** [comment]
Is this fix in Material 3? I tried to provide `colorOnSurfaceVariant` for action menu but it seems not working. It works when using `colorControlNormal`. Thanks

**Comment by drchen** [comment]
I think this is fixed with Material 3. Since we deprecated Material 2, let me close this issue as obsolete.
