### ISSUE TITLE
Attribute to customize Bounding box stroke

### ISSUE THREAD

**Issue by RowlandOti** [material-components/material-components-android#112]
I can see that the bounding box for the `TextInputLayout` has been explicitly declared here:

```java
 defaultStrokeColor =
        ContextCompat.getColor(context, R.color.mtrl_textinput_default_box_stroke_color);
    disabledColor = ContextCompat.getColor(context, R.color.mtrl_textinput_disabled_color);
    hoveredStrokeColor =
        ContextCompat.getColor(context, R.color.mtrl_textinput_hovered_box_stroke_color);
```

i.e : 

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/TextInputLayout.java#L314

Are there plans to provide an attribute that allows developers, to for example override these? For example, use color states?

**Comment by snotyak** [comment]
I should mention that while this default looks alright on when using light backgrounds, it looks terrible with dark ones.

**Comment by petrkubac** [comment]
Hello guys, you can override the color in your colors.xml
` <color name="mtrl_textinput_default_box_stroke_color" tools:override="true">@color/white_40</color>`

**Comment by RowlandOti** [comment]
Bad approach, @petrkubac  we may want to use themes. Attributes are a better alternative.

**Comment by petrkubac** [comment]
@RowlandOti I have updated my post to make it more understandable what I was talking about. You can still use themes, but if you need to change the default box stroke colour now (until the issue is resolved), you can override it like I did.

**Comment by RowlandOti** [comment]
Cool. Thanks for clarifying, it's currently the solution I was using, as it seems to be the only alternative at the moment. It is quite unsatisfactory, hence I look forward to a fix from the team.

**Comment by asmaa-adel** [comment]
@afohrman any updates for this issue as i have more than one theme and in each one i want deferent default color for the box stroke

**Comment by mrZizik** [comment]
What is status of this issue?

**Comment by afohrman** [comment]
We are aware of this issue and we plan to add a defaultBoxStrokeColor (or similarly named) attribute so that this value can be parameterized. We plan to do this after we finish the color system, but we'd be happy to accept a pull request for this if anyone would like to contribute.

**Comment by selena775** [comment]
~petrkubac , what if we want to have two different TextInputLayouts depending on a theme. How can we use mtrl_textinput_default_box_stroke_color to set two different colours. TextInputLayout should be the very foundation of UI controls. Please provide a solution.

**Comment by RowlandOti** [comment]
Hi, @selena775  I don't think it is possible to do that without attributes that we can override in themes.  Th PR #181 could have helped, but I don't think it has been merged yet.

**Comment by selena775** [comment]
@RowlandOti, in my opinion every colour and every text style should be configurable. That way the  component is reusable, easily customisable and it will make developers life much easier. It is not only the stroke color that is a problem here, it is also primaryColor used as text color and one cannot change it easily.  I would be very grateful if you make TextInputLayout completely configurable.

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by joost-klitsie** [comment]
Hi all, I am writing to show my displeasure while figuring out the coloring of this element and hopefully someone will take a look at it.

Is there anything against using color state lists? Shouldn't it be possible to just give a statelist for the floating label, or the border, or the background, or whatever? Like all other Android components have? I have to override now mtrl_textinput_disabled_color, mtrl_textinput_default_box_stroke_color so I can follow a design for those colors when I disable the element, I have to access defaultStrokeColor through reflection, I have to call setBoxBackgroundColorResource manually when I enable/disable the view... This is very ugly in the code and also it was very time consuming to figure it all out. It is not my style to put hacky stuff into a production app, but there is no other way here (if I want to use official components)

**Comment by leticiarossi** [comment]
Hello everyone, as of the most recent version released (1.1.0-alpha02, although I believe it was available by alpha01) it is possible to use a color state list to change the stroke color of outlined text fields (through the boxStrokeColor attribute). (We currently use this color state list https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/color/mtrl_box_stroke_color.xml)

There are also different attributes for text/hint/helper texts colors and appearances (https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/values/styles.xml) and we are continuing the work to make text input layouts more configurable.

**Comment by sinhpn92** [comment]
I have same issue. How can to do that? @Corsage @joost-klitsie

**Comment by Corsage** [comment]
I believe I was able to do it with the following:
```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@android:color/background_light" android:state_focused="true"/>
    <item android:color="@android:color/background_light" android:state_hovered="true"/>
    <item android:color="@android:color/background_light" android:state_enabled="false"/>
    <item android:color="@android:color/background_light" />
</selector>
```

Take a note of the different android states, and then lastly the default state. Change the colors accordingly to what you need and then you can use it as a theme, an example is shown below.

```xml 
<!-- Hint text appearance (used only when the background is colorPrimary). -->
    <style name="TextInputLayoutWhiteBox" parent="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense">
        <item name="boxStrokeColor">@color/layout_text_input_white</item>
        <!-- The color of the label when it is collapsed and the text field is active -->
        <item name="hintTextColor">@android:color/background_light</item>
        <!-- The color of the label in all other text field states (such as resting and disabled) -->
        <item name="android:textColorHint">@android:color/background_light</item>
    </style>
```

**Comment by bernaferrari** [comment]
I suffered a lot today and my suggestion would be to make defaultStrokeColor public like the other. This is not intuitive and dark theme looks really bad. 
![screenshot_20190228-163503_sdk monitor](https://user-images.githubusercontent.com/351125/53593464-96e13780-3b77-11e9-92dd-bc804dd60394.jpg)

**Comment by dsn5ft** [comment]
Can you post your code that resulted in the outline being that color in your dark theme? It shouldn't look like that by default so I'm just trying to understand what customizations are being made.

**Comment by bernaferrari** [comment]
I think it was a bug that got fixed on one of the alphas, because I just tested on alpha04 and it is working as intended (just not in 1.0.0).

**Comment by dsn5ft** [comment]
Thanks for checking. We set up our dark theme's color palette in one of the alphas so that makes sense.

**Comment by bernaferrari** [comment]
I really wish the release update was faster. It has been in alpha for 3 months, and will probably be for another few. iOS MDC release updates like crazy, I stayed one year outside iOS development, it went from v56 to v74 or something like that.

**Comment by victorkaput** [comment]
In the alpha 4.0.0 the corner radius in dense style dont work.. :(

**Comment by victorkaput** [comment]
My solution was :
```
///Normal
        inputLayout.boxBackgroundColor = Color.TRANSPARENT
//Error
       inputLayout.error = "un error"
//Correct
       editText.setBackgroundResource(R.drawable.correct)
```
xml 
```
`  <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/inputLayout"
                android:layout_width="200dp"
                android:layout_height="60dp"
                style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox.Dense"
                app:errorEnabled="true"
                app:boxBackgroundColor="#F9F0F0">
            <com.google.android.material.textfield.TextInputEditText android:layout_width="match_parent"
                                                                     android:layout_height="match_parent"
                                                                     android:id="@+id/editText"
                                                                     />`

```

correct.xml drawable 
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <solid android:color="#5CD515" />
        </shape>
    </item>
    <item android:bottom="2dp">
        <shape android:shape="rectangle">
            <solid android:color="#fff" />
        </shape>
    </item>
</layer-list>
```

**Comment by victormanuelfrancodev** [comment]
My solution was :

```
///Normal
        inputLayout.boxBackgroundColor = Color.TRANSPARENT
//Error
       inputLayout.error = "un error"
//Correct
       editText.setBackgroundResource(R.drawable.correct)
```
xml

```
`  <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/inputLayout"
                android:layout_width="200dp"
                android:layout_height="60dp"
                style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox.Dense"
                app:errorEnabled="true"
                app:boxBackgroundColor="#F9F0F0">
            <com.google.android.material.textfield.TextInputEditText android:layout_width="match_parent"
                                                                     android:layout_height="match_parent"
                                                                     android:id="@+id/editText"
                                                                     />`

```
correct.xml drawable

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <solid android:color="#5CD515" />
        </shape>
    </item>
    <item android:bottom="2dp">
        <shape android:shape="rectangle">
            <solid android:color="#fff" />
        </shape>
    </item>
</layer-list>
```

**Comment by Svoka** [comment]
I don't know why @Corsage answer gets downvoted, because in my case it actually working

**Comment by gauravdhim1990** [comment]
@Svoka, is it possible   <item name="boxStrokeColor">@color/layout_text_input_white</item>

**Comment by M0N3** [comment]
You can set it like this:
```
val colorList = ColorStateList(
        arrayOf(
                intArrayOf(-android.R.attr.state_enabled),  // Disabled
                intArrayOf(android.R.attr.state_enabled)    // Enabled
        ),
        intArrayOf(
                Color.BLACK,     // The color for the Disabled state
                Color.RED        // The color for the Enabled state
        )
)
yourTextInnput.setBoxStrokeColorStateList(colorList)
```
See this thread to more info:
[https://stackoverflow.com/questions/15543186/how-do-i-create-colorstatelist-programmatically/58121371#58121371](url)
