### ISSUE TITLE
[Slider] Halo of the Slider will be triggered when tapping on its superview if superview is clickable

### ISSUE THREAD

**Issue by mxalbert1996** [material-components/material-components-android#1121]
**Description:** Put a Slider in a container, set the container clickable, and the halo (ripple) of the Slider will be triggered when tapping on the rest area of the container.

**Expected behavior:** The halo of the Slider shouldn't be triggered when tapping on the rest area of the container.

**Source code:** 
````XML
<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    android:focusable="true">

    <com.google.android.material.slider.Slider
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</FrameLayout>
````

**Android API version:** Tested on API 29

**Material Library version:** 1.2.0-alpha05

![device-2020-03-20-004419](https://user-images.githubusercontent.com/9391933/77086924-c0505800-6a45-11ea-8763-a9f907fd2d2e.gif)

**Comment by opatry** [comment]
I'm integrating such component in custo `Preference` and it makes the user feedback weird.
I add my vote :+1: to this one.

**Comment by mxalbert1996** [comment]
I have found the cause of this issue which is that `ViewGroup`s will pass their own pressed state to their children which are not clickable or long-clickable.
Here's the `ViewGroup.dispatchSetPressed()` method:
````Java
@Override
protected void dispatchSetPressed(boolean pressed) {
    final View[] children = mChildren;
    final int count = mChildrenCount;
    for (int i = 0; i < count; i++) {
        final View child = children[i];
        // Children that are clickable on their own should not
        // show a pressed state when their parent view does.
        // Clearing a pressed state always propagates.
        if (!pressed || (!child.isClickable() && !child.isLongClickable())) {
            child.setPressed(pressed);
        }
    }
}
````

By now, this issue can be solved by setting `android:clickable="true"` and `android:focusable="true"` on the `Slider`.
But IMHO `Slider`s should be clickable by default (since they really are).
