### ISSUE TITLE
[Material Transition in Java] Material Shared Transitions are not available in Java, please add it

### ISSUE THREAD

**Issue by arunkbabu90** [material-components/material-components-android#1122]
The Material Shared Transitions like MaterialSharedAxis, MaterialFadeThrough, etc.. are not available in Java. But it's available in Kotlin. There is documentation in Kotlin but not in Java.  I took a look at the library via Android Studio and I could find such a class either. I think you forgot to add it to the java library. Please add it

I want the Material Transitions to be available to code in Java too. Please update it in the Java Library too

**Comment by dsn5ft** [comment]
The transitions themselves are written in Java and are available for both Java and Kotlin.
