### ISSUE TITLE
[MaterialDatePicker] API to disable dialog auto dismiss

### ISSUE THREAD

**Issue by andob** [material-components/material-components-android#1125]
**Is your feature request related to a problem? Please describe.**
I use a ``MaterialDatePicker.Builder.dateRangePicker()``. When the user clicks the save button, the dialog is automatically dismissed. I don't want that, in my use case I need the dialog to be dismissed by the user with the back button or programatically.

**Describe the solution you'd like**
I request an official API to disable auto dismiss when save button is clicked.
Something [similar to this](https://stackoverflow.com/a/7636468). On ``AlertDialog``, we can get the positive button and set the on click listener on it, thus preventing the default behavior.

**Describe alternatives you've considered**
I made a hack:

```kotlin
val picker=MaterialDatePicker.Builder.dateRangePicker()
    .build()

Handler().postDelayed({
    //hack - disable dismiss on confirm button click
    val confirmButton=picker::class.java.declaredFields
        .find { field -> field.name=="confirmButton" }
        ?.let { field ->
            field.isAccessible=true
            field.get(picker) as? Button
        }

    confirmButton?.setOnClickListener {
        val interval=picker.selection as Pair<Long?, Long?>
        doSomething(interval)
    }
}, 1000)
```

**Comment by andob** [comment]
Was this issue deleted? It doesn't appear on any issue list pages anymore (Issues created by me, Issues on material-components-android repo).

I think it's a valid, useful feature request.

Is this a duplicate of another issue??

**Comment by sanjogshrestha** [comment]
May be similar approach can be helpful.  [Check this link](https://github.com/material-components/material-components-android/issues/998#issuecomment-635850054)

**Comment by andob** [comment]
Thanks.

The ``MaterialAlertDialog`` class has a ``getButton`` method so you can do ``dialog.getButton(DialogInterface.BUTTON_POSITIVE).setOnClickListener``

The ``MaterialDatePicker`` class doesn't have such method. That's the problem.

**Comment by andob** [comment]
I don't need this feature anymore because I don't use the library anymore. I'll leave this issue as it is.

**Comment by GautamChibde** [comment]
@andob did you find any workaround for this issue?

**Comment by andob** [comment]
no, I always used that hack with reflection. regarding your issue, I guess you could use the same hack:
- grab confirmButton using reflection
- when date is selected: set confirmButton.isEnabled to true/false
