### ISSUE TITLE
[MaterialContainerTransform] Elevation disappears during transition

### ISSUE THREAD

**Issue by b0r1s** [material-components/material-components-android#1126]
Description: elevation on MaterialCardView disappears during transition.

1) I set android:transitionName on a MaterialCardView in Fragment A and B
2) In Fragment A:
`FragmentNavigator.Extras extras = new FragmentNavigator.Extras.Builder()
                .addSharedElement(view.findViewById(R.id.card), "card")
                .build();
        NavHostFragment.findNavController(this).navigate(R.id.action_AFragment_to_BFragment,null,null,extras);`
3) In Fragment B:
`MaterialContainerTransform transition = new MaterialContainerTransform(getContext());
 transition.setDuration(1000);
 transition.setScrimColor(ContextCompat.getColor(getActivity(),android.R.color.transparent));
 setSharedElementEnterTransition(transition);`

**Comment by jkarlsson** [comment]
This can be seen also in the included "catalog" sample app (TransitionContainerTransformDemoFragment, tested commit ae7177d9de9). It is very apparent if you slow down the transition duration.

I'm curious if this is a bug or intended behaviour.

**Comment by dsn5ft** [comment]
Thanks @b0r1s and @jkarlsson, this is a known issue that we are currently thinking about. It's tricky because the elevation shadow rendering happens at a lower level than how we're drawing the views to the canvas during the transition. We may end up approximating the shadow using the canvas, similar to `MaterialShapeDrawable`, but we're not sure yet.

**Comment by jkarlsson** [comment]
I'm guessing that it is a very likely use case that the shared element is a MaterialCardView with a MaterialShapeDrawable as background. If that makes it less complicated to render shadows maybe it is a reasonable first step to support shadows only on views with a MaterialShapeDrawable as background.

**Comment by dsn5ft** [comment]
Agreed, that's what we will be looking into at first, or at least using the same mechanism as `MaterialShapeDrawable` to draw the shadow.

**Comment by b0r1s** [comment]
Hi, I updated to material 1.3.0-alpha02 (API 29) and I can see the new elevation shadow, but I think the shadow is a bit moved downwards (?): it seems that there is less shadow behind the top of the card (and more behind the bottom of the card) while the animation is running vs at the beginning or the end of the animation.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/36534836/88845466-7db53e00-d1e4-11ea-867f-fd0d865c5e37.gif)

GIF's project: [MyApplication - shadow.zip](https://github.com/material-components/material-components-android/files/4997106/MyApplication.-.shadow.zip)

**Comment by hunterstich** [comment]
Hey @b0r1s,

What you're seeing is the switch between your card drawing native shadows and MaterialContainerTransform using compat shadows manually. If I remember correctly, this is the only way we are able to draw shadows during a transition but @dsn5ft, who worked on the elevation implementation, might have more details/suggestions.

**Comment by SamYStudiO** [comment]
What about others transitons than ContainerTransform? Fade, Hold, etc...?

**Comment by dsn5ft** [comment]
@SamYStudiO if you add your root view as a target (`addTarget`), then I think the Android Transition system will preserve elevation. We only had to add custom support to the container transform because of how we're manually drawing the views to the canvas.

**Comment by iregados** [comment]
I am on com.google.android.material:material:1.3.0-alpha03

my transition comes from a a LinearLayout inside a RecyclerView item...

set my transition on origin fragment as:

        val extras = FragmentNavigatorExtras(view to "design_fragment")
        val direction = SectionPickerFragmentDirections.sectionPickerFragmentToDesignFragment(section.id)
        findNavController().navigate(direction, extras)

and on fragment that i am going to i have:

        sharedElementEnterTransition = MaterialContainerTransform().apply {
            drawingViewId = R.id.navHostFragment
            duration = 3000
            scrimColor = Color.TRANSPARENT
        }

my MaterialCardView xml code is :

        <com.google.android.material.card.MaterialCardView
        android:layout_margin="16dp"
        android:layout_width="match_parent"
        android:transitionGroup="true"
        app:cardElevation="5dp"
        android:layout_height="wrap_content">

and my shadow while transitioning looks like:

![IkVZ6NkJ59](https://user-images.githubusercontent.com/2482702/95659304-7e2c5800-0af6-11eb-87c2-b2889954171b.gif)

**Comment by dsn5ft** [comment]
Hi @iregados, what API level are you running on?

Can you share a sample app project that reproduces the issue?

Can you try experimenting with `materialContainerTransform.setElevationShadowEnabled(true)` and `materialContainerTransform.setEndElevation(...)`?

**Comment by iregados** [comment]
Hello, my emulator is on Android 10...its sdk version 29

with 

      isElevationShadowEnabled = true
      endElevation = 5f

i've been able to create shadow arround the container that I am transitioning to ...not on the cards that are inside that container...

i will create a sample project and post it here in a while

**Comment by dsn5ft** [comment]
Ah I see. Unfortunately it seems we are not able to support drawing elevation shadows for child views within the container transform. This is because we draw the start/end parent container views to the canvas:

https://github.com/material-components/material-components-android/blob/cd36c2f5e77461b26f4723a765e11e6bf16a2a86/lib/java/com/google/android/material/transition/MaterialContainerTransform.java#L974-L1006

And the native elevation shadow rendering is handled at a [lower level](https://stackoverflow.com/questions/34711211/draw-elevation-shadows-to-canvas).

A possible workaround is to not use native elevation shadows and instead use shadow approximation based on a Drawable/Paint.
