### ISSUE TITLE
[Motion] Bug in container transform

### ISSUE THREAD

**Issue by ansman** [material-components/material-components-android#1135]
**Description:** When using the container transform with a simple view leads to an unexpected layout behavior:
[device-2020-03-20-115754.mp4.zip](https://github.com/material-components/material-components-android/files/4369266/device-2020-03-20-115754.mp4.zip)
The button in the first fragment is positioned incorrectly when returning.  

**Expected behavior:** The button should be laid out correctly.

**Source code:** 
[AnimationBug.zip](https://github.com/material-components/material-components-android/files/4369260/AnimationBug.zip)

**Android API version:** API 29

**Material Library version:** 1.2.0-alpha05

**Device:** Google Pixel 4 XL, Samsung Galaxy Note10+

**Comment by hunterstich** [comment]
This looks like it's a targeting issue with the FirstFragment's Hold exitTransition. The Hold was targeting all views in the first layout and adding the container transform's shared element back to transition.

This can be solved by adding `android:transitionGroup=true` to your first Fragment's root layout group or by specifying a target on your Hold transition with `#addTarget(R.id.first_fragment_container)`.
