### ISSUE TITLE
[TextInputEditText] Vertically cut off

### ISSUE THREAD

**Issue by GuilhE** [material-components/material-components-android#1136]
**Description:**
TextInputEditText are getting vertically cut off
![Screenshot 2020-03-23 at 13 31 55](https://user-images.githubusercontent.com/2677139/77321834-af843880-6d0a-11ea-98f2-a22bc530331d.png)

**Expected behavior:** 
Not getting cut off, just downgrade to 1.1.0 and it works.
![Screenshot 2020-03-23 at 13 23 01](https://user-images.githubusercontent.com/2677139/77321439-1a813f80-6d0a-11ea-9aba-d7638fd4101e.png)

**Source code:** 
 ```
 <com.google.android.material.textfield.TextInputEditText
                    style="@style/App.EditTextStyle"
                    android:layout_width="0dp"
                    android:layout_height="50dp"
                    android:layout_marginStart="7dp"
                    android:layout_marginTop="78dp"
                    android:layout_marginEnd="17dp"
                    android:background="@android:color/transparent"
                    android:digits="0123456789 "
                    android:hint="@string/hint_insert_phone"
                    android:imeOptions="actionDone"
                    android:inputType="number|phone"
                    android:text="@={viewModel.phoneNumber}"
                    android:fontFamily="@font/open_sans"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toEndOf="@+id/tv_phone_input_label"
                    app:layout_constraintTop_toBottomOf="@+id/const_title" />
```

```
    <style name="App.EditTextStyle" parent="Widget.MaterialComponents.TextInputLayout.FilledBox">
        <item name="android:fontFamily">@font/open_sans_semibold</item>
        <item name="android:textSize">16sp</item>
        <item name="android:maxLines">1</item>
        <item name="android:singleLine">true</item>
        <item name="android:backgroundTint">@android:color/transparent</item>
        <item name="android:textColorHint">?android:attr/textColorSecondary</item>
    </style>
```

**Android API version:**
API 29

**Material Library version:**
1.2.0-alpha05

**Device:**
Pixel 3a

**Comment by leticiarossi** [comment]
Are you using a `TextInputEditText` without a surrounding `TextInputLayout`?
I see your custom style extends from a `TextInputLayout` style instead of the `Widget.MaterialComponents.TextInputEditText.FilledBox` style.
I don't know if that could be the cause of the issue, but it's worth a try.

**Comment by GuilhE** [comment]
Nice catch! But unfortunately it's not the cause. And no, I'm not using inside a `TextInputLayout` and that apparently is the cause, because if I use it inside it works.

**Comment by GuilhE** [comment]
Just to make clear, `TextInputEditText` when we have a `TextInputLayout`, `EditText` when we don't right?

**Comment by leticiarossi** [comment]
yes, that's the expected approach!

**Comment by msthapacse** [comment]
TextInputLayout contains some inside padding which causes the issue, only solution i found is making TextInputLayout height as wrap content
