### ISSUE TITLE
[Exposed Dropdown Menu] Outline style displays surface color background when set editable=false

### ISSUE THREAD

**Issue by lcdsmao** [material-components/material-components-android#1137]
**Description:** Full description of issue here
|colorSuface=red|colorSurface=white|
|-|-|
|![Screen Shot 2020-03-23 at 23 37 21](https://user-images.githubusercontent.com/13031690/77328175-85a93100-6d5f-11ea-8b13-0cb73f21c8d1.png)|![Screen Shot 2020-03-23 at 23 38 48](https://user-images.githubusercontent.com/13031690/77328181-880b8b00-6d5f-11ea-998c-8c76efcd66c4.png)|

I try to create an uneditable Exposed dropdown menu with `Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu` style.
If I set attr `android:editable="false"` for AutoCompleteTextView, text field get background of surface color when focused.
Is this the documented behavior?

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Android API version here

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.1.0

**Device:** Device on which the bug was encountered here

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
Hi, that's correct. Because the layout needs to have a ripple on press, a background with the surface color is set.

**Comment by lcdsmao** [comment]
@leticiarossi Thank you! 
Maybe it can be helpful to state this behavior in the documentation? (Or maybe I missed it)
I have searched a lot to find where this background color comes from. ☺️

**Comment by leticiarossi** [comment]
We've been updating our components documentation but haven't gotten to menus yet, will make sure to include that! The code itself can be found [here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/DropdownMenuEndIconDelegate.java#L279).
