### ISSUE TITLE
[TextInputLayout] Placeholder text not center vertical

### ISSUE THREAD

**Issue by lcdsmao** [material-components/material-components-android#1139]
**Description:** Full description of issue here
![Screen Shot 2020-03-24 at 19 36 59](https://user-images.githubusercontent.com/13031690/77416117-d58f0300-6e06-11ea-8be2-c241cf8440b5.png) ![Screen Shot 2020-03-24 at 19 37 20](https://user-images.githubusercontent.com/13031690/77416145-e2135b80-6e06-11ea-99e8-44fffb2dacd0.png)
Placeholder text not center vertical but align to the top.
Or how can I make it center vertical like editable text?

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

```xml
    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/text_input"
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:placeholderText="Placeholder"
        app:layout_constraintBottom_toTopOf="@+id/textView"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        >
        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/auto_complete"
            android:layout_width="200dp"
            android:layout_height="80dp"
            android:hint="Hint"
            />
    </com.google.android.material.textfield.TextInputLayout>
```

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.2.0-alpha05

**Comment by perfect-ux** [comment]
layout gravity usually works fine
