### ISSUE TITLE
box...PaddingBottom of TextInputLayout

### ISSUE THREAD

**Issue by Aleksander3007** [material-components/material-components-android#114]
After viewing source code of the TextInputLayout class, I noticed that the boxCollapsedPaddingBottom attribute has no effect.
It also seems that a mistake occurs while installing boxExpandedPaddingBottom. This attribute affects both the distance from the bottom of EditText to the helper text, and from the helper text to the bottom of the bottom of the TextInputLayout.

**Comment by afohrman** [comment]
Thanks for filing this issue and for the fix. Will take a look at your PR.

**Comment by afohrman** [comment]
This was fixed in https://github.com/material-components/material-components-android/commit/84663583b71f3b4f4a1e6cd2825e22bbd4448348. Thanks for the PR!
