### ISSUE TITLE
[Slider] Enable thumb drawable usage

### ISSUE THREAD

**Issue by carstenhag** [material-components/material-components-android#1140]
**Is your feature request related to a problem? Please describe.**
Hey there! We want to use a customized thumb drawable for the sliders we use in our app. 
Example: 
<img width="129" alt="Bildschirmfoto 2020-03-24 um 13 22 53" src="https://user-images.githubusercontent.com/3776997/77425203-a5c60800-6dd2-11ea-887d-f1c2ccdaa606.png">

**Describe the solution you'd like**
Afaik this is possible with an old SeekBar, but I haven't found a way to do this with a Slider. Not sure how the solution should look like. I'd guess there should be a thumbDrawable property/setter to set a drawable with the possible states? 

**Describe alternatives you've considered**
Currently I would probably need to use an old SeekBar or tell our designer that we can't support this currently on Android :(.

**Comment by mueller-ma** [comment]
Duplicate of #935?

**Comment by carstenhag** [comment]
Yep, you are right.

**Comment by carstenhag** [comment]
@ymarian  FYI this ticket can be closed/marked as duplicate.
