### ISSUE TITLE
[Slider] Thumb flickers when reaching start or end of slider

### ISSUE THREAD

**Issue by carstenhag** [material-components/material-components-android#1144]
**Description:**
Not always but very often, the thumb and its surrounding "holo" circle flickers when moving the thumb to the start or the end of the slider. See this gif:

![sldier-flickering](https://user-images.githubusercontent.com/3776997/77520542-a5387a80-6e81-11ea-8f6e-e17f1f4ef6ad.gif)

**Expected behavior:** No flickering should occur.

**Source code:**

```xml
        <com.google.android.material.slider.Slider
            android:id="@+id/slider"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:value="20"
            android:valueFrom="5.0"
            android:valueTo="100.0"
            app:labelBehavior="gone"
            app:trackColorActive="@color/icon_primary"
            app:trackColorInactive="@color/ui_dark" />
```

**Android API version:** 28

**Material Library version:** 1.2.0-alpha05

**Device:** Samsung A70, OnePlus 5

**Comment by drchen** [comment]
Hi, I can't really reproduce the issue. Does it happen on different API/devices?

**Comment by carstenhag** [comment]
I also can't reproduce it anymore (we are currently using `1.4.0`), so I'll close this
