### ISSUE TITLE
[BottomNavigationView] Invalid background color in dark mode.

### ISSUE THREAD

**Issue by Shipaaaa** [material-components/material-components-android#1148]
**Description:**
When I change the background color of BotomNavigationView by `android:background` or `backgroundTint` in the light theme, it displays correctly, but not in the dark one. 

In a dark theme, some other color is superimposed, which can be disabled only through `itemBackground`, but then the ripple effect disappears.

Wrong result:
![image](https://user-images.githubusercontent.com/11670840/77591021-2b93a180-6f00-11ea-8e4f-06012cccb9a0.png)

**Expected behavior:** 
The color is right:
![image](https://user-images.githubusercontent.com/11670840/77591828-dc4e7080-6f01-11ea-8b13-8489ef250ab4.png)

**Source code:** 
fragment.xml
```xml
    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/fragment_main_bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/background_primary"
        app:menu="@menu/bottom_navigation" />
```
themes.xml
```xml
<item name="colorSurface">@color/background_primary</item>
```

colors.xml
```xml
// Light theme
<color name="background_primary">#FFFFFD</color>
// Dark theme
<color name="background_primary">#261D32</color>
```

Correct result in ligth theme:
![image](https://user-images.githubusercontent.com/11670840/77591167-76adb480-6f00-11ea-80df-cd27da2015d3.png)

Wrong result in dark theme:
![image](https://user-images.githubusercontent.com/11670840/77591021-2b93a180-6f00-11ea-8e4f-06012cccb9a0.png)

**FIX 1**
I can fix this by `itemBackground`, but ripple isn't working:

```xml
    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/fragment_main_bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:itemBackground="@color/background_primary"
        app:menu="@menu/bottom_navigation" />
```
Result:
![image](https://user-images.githubusercontent.com/11670840/77591567-46b2e100-6f01-11ea-8a97-569032ee49c1.png)

**FIX 2**
I can fix this by changing `colorSurface`:

themes.xml
```xml
    <style name="ThemeOverlay.AppTheme.BottomNavigationView" parent="@style/ThemeOverlay.MaterialComponents">
        <item name="colorSurface">@null</item>
    </style>
```

```xml
<com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/fragment_main_bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.AppTheme.BottomNavigationView"
        android:background="@color/background_primary"
        app:menu="@menu/bottom_navigation" />
```

Correct result:
![image](https://user-images.githubusercontent.com/11670840/77591828-dc4e7080-6f01-11ea-8b13-8489ef250ab4.png)

**Android API version:** 
I tested it on 26, 28 and 29 API

**Material Library version:** 
1.1.0

**Device:** 
Nexus 5x, OnePlus 6t, Emulator Pixel 3a.

**Comment by wcshi** [comment]
The superimposed overlay color you are observing may be the elevation overlay, try setting elevationOverlayEnabled=false

https://material.io/develop/android/theming/dark/

**Comment by Steppschuh** [comment]
Glad I stumbled upon this thread. Had the same issue when setting the background color to black in dark mode. As I didn't want to remove the elevation in light mode, I've added a runtime check:

```java
private void initializeNavigation() {
    BottomNavigationView navigationView = findViewById(R.id.bottomNavigationView);

    // setting configuration, controllers, ...

    if (application.isInDarkMode()) {
        // workaround for removing the elevation color overlay
        // https://github.com/material-components/material-components-android/issues/1148
        navigationView.setElevation(0);
    }
}

private boolean isInDarkMode() {
    int currentNightMode = getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
    return currentNightMode == Configuration.UI_MODE_NIGHT_YES;
}
```

You could also add an xml attribute for the elevation with a night mode qualifier (being `0dp` in night and your desired elevation in day mode).

Hope this gets fixed though, would prefer not to use this workaround 🙂

**Comment by NLLAPPS** [comment]
I was also struggling with this until I found this issue. Thank you! Setting elevation to 0 works.

However elevationOverlayEnabled=false as @wcshi suggested doesn't seem to work for me.

I have used it like this:

`<style name="Widget.MyTheme.BottomNavigation" parent="Widget.MaterialComponents.BottomNavigationView">
              <item name="elevationOverlayEnabled">false</item>
 </style>`

**Comment by boggsey** [comment]
Thanks for this! Elevation to 0 solved it for me. I could not figure out what the extra weird color was.

**Comment by vimalcvs** [comment]
`

    <style name="ThemeOverlay.AppTheme.BottomNavigationView" parent="@style/ThemeOverlay.MaterialComponents">
        <item name="elevationOverlayEnabled">false</item>
    </style>


`
