### ISSUE TITLE
[MaterialDatePicker] window background color applied with an unnecessary alpha.

### ISSUE THREAD

**Issue by jukov** [material-components/material-components-android#1151]
**Description:** I try to set background color to material date picker, but an unnecessary alpha affect color that i want to set. Eg. i try to set #FF0000, but actual color is #FF2626. Seems like color affected with an alpha. I use `colorSurface` attr for set color.

![scrcpy_MwLtGottNW](https://user-images.githubusercontent.com/8081721/77641306-e6f21f80-6f6c-11ea-9a89-cb5c7414fe9d.png)

**Expected behavior:** Color should be set without an unnecessary modifications.

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Min Sdk 19, Target Sdk 29

**Material Library version:** 1.2.0-alpha05

**Device:** Xiaomi MIA2

[material_picker_test.zip](https://github.com/material-components/material-components-android/files/4386823/material_picker_test.zip)

**Comment by wcshi** [comment]
This may be due to an elevation overlay, try setting elevationOverlayEnabled=false 

https://material.io/develop/android/theming/dark/

**Comment by jukov** [comment]
Seems like elevationOverlayEnabled=false solve problem. Thank you! I'll close this issue
