### ISSUE TITLE
TextInputLayout - OutlineBox RTL

### ISSUE THREAD

**Issue by MHKalantarian** [material-components/material-components-android#1152]
**Description:**
When I set style to OutlineBox the box renders on the left side and hint goes on the right side
**Expected behavior:**
Outline space and hint should go to right
**Source code:**
```
                 <com.google.android.material.textfield.TextInputLayout
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layoutDirection="rtl">

                    <com.google.android.material.textfield.TextInputEditText
                        android:id="@+id/title_et"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="right|top"
                        android:hint="نام مارکت"
                        android:inputType="textPersonName"
                        android:textSize="@dimen/_10ssp" />

                </com.google.android.material.textfield.TextInputLayout>
```
**Android API version:** Android API version here
Android 10 - 29
**Material Library version:** 
1.2.0-alpha05

**Comment by leticiarossi** [comment]
Hi, because you're setting the edit text `android:gravity` to `right` it's getting inverted since it's in RTL, so you don't need to specify any gravity. Also, as best practice, you should set `android:hint` in the `TextInputLayout` instead of on the `TextInputEditText`.

**Comment by njarun** [comment]
Extend the TextInputEditText class and override the getGravity() method

`@Override
    public int getGravity() {
        return Gravity.START;
    }`

If you want to show your outine box cut out left and right for LTR and RTL
