### ISSUE TITLE
[MaterialContainerTransform] Transition between fragments of same base class/layout

### ISSUE THREAD

**Issue by luanmm** [material-components/material-components-android#1161]
**Description:** I'm using the same base (abstract class) and layout XML for a series of "on boarding" pages that application shows at start. So, when transitioning from one fragment to another, in practice, the configuration is the same (BaseIntroFragment -> BaseIntroFragment), except for the concrete classes, that are independent (HelloIntroFragment -> SignUpIntroFragment, for instance).

**Expected behavior:** Expected to see an animation as any other use case. But it isn't working (it seems that the animation is done before the layout calculation).

**Source code:** 

BaseIntroFragment onCreate:
```
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val transition = MaterialContainerTransform(requireContext()).apply {
            isDrawDebugEnabled = true
            duration = 3000L
        }

        sharedElementEnterTransition = transition
        sharedElementReturnTransition = transition

        exitTransition = Hold()
    }
```

BaseIntroFragment navigation:
```
            val extras = FragmentNavigatorExtras(
                    nextButton to getString(R.string.transition_intro_button))
            navController.navigate(destination, null, null, extras)
```

As there only one layout file (fragment_intro.xml), there is only one "transitionName" defined (in the "next" button) for source -> destination (from two different fragment instances).

Result:
![device-2020-03-27-151541](https://user-images.githubusercontent.com/1708808/77788740-8c29f800-7040-11ea-8d2c-42e9a033d1cd.gif)

As the result image shows, when transitioning between the first intro screen (blue) and second intro screen (orange), the "next" button (that should move between the screens) shows up in the top-left corner until animation is done, then is correctly "calculated" to get into the right position. Its not the same scenario of the last transition (when the button correctly goes into the center of the app main fragment).

*The 3s delay is for debug purposes.

**Android API version:** Android API version 29 (min 19)

**Material Library version:** Material Android Library version 1.2.0-alpha05

**Device:** Android Emulator x86_64 (Google Play APIs)

**Comment by dsn5ft** [comment]
Hi @luanmm, sorry for the delay. Is this still an issue for you?

Can you try passing in args to the re-used fragment for anything like `transitionName` that needs to be differentiated? And then, e.g., in `onViewCreated` you can use `ViewCompat#setTransitionName` to set it programmatically.

**Comment by luanmm** [comment]
Thanks for the response, @dsn5ft.

It is still an issue and I couldn't dive so deep to try to understand (my knowledgement about shared elements is not so good to understand why this may fail the way it is).

Based on your answer, I tried this way:

```kotlin
        // The "transitionName" was removed from the XML, so I'm setting it here now (when the button is pressed and the navigation is fired)
        val nextButtonTransitionName = getString(R.string.transition_intro_button, destination) // This is just a custom string formatting, to force it to have unique IDs for transitions ("transitionIntroButton(%d)")
        ViewCompat.setTransitionName(nextButton, nextButtonTransitionName)

        val args = Bundle()
        args.putString(NEXT_BUTTON_TRANSITION_NAME_ARGS_KEY, nextButtonTransitionName)

        val options = NavOptions.Builder()
                .setEnterAnim(R.anim.enter_from_right)
                .setExitAnim(R.anim.exit_to_left)
                .setPopEnterAnim(R.anim.enter_from_left)
                .setPopExitAnim(R.anim.exit_to_right)
                .setPopUpTo(R.id.invoiceFragment, false)
                .build()

        val extras = FragmentNavigatorExtras(
                nextButton to nextButtonTransitionName)

        navController.navigate(destination, args, options, extras)
```

Then, in the onViewCreated I set it like this:

```kotlin
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        arguments?.getString(NEXT_BUTTON_TRANSITION_NAME_ARGS_KEY)?.let {
            ViewCompat.setTransitionName(nextButton, it)
        }

        // Other initializations
        // ...
    }
```

In the first attempt, the IDs was always the same (a fixed string "transitionIntroButton", without the composition with "(%d)" as stated above). So your recommendation seemed to be a point to a solution. But the problem still persists, even with this unique ID strategy.

Any other possible thoughts? I really have no clue in solving this.

PS: Now I'm using the Material Design 1.3.0-alpha01. I have updated it to see if any corrections applied in this version could help me in my scenario, with no luck too.

**Comment by dsn5ft** [comment]
Hmm not that this would solve the problem, but this horizontal stepper onboarding flow seems like it would be better suited for the `MaterialSharedAxis` x-axis transition ([spec here](https://material.io/design/motion/the-motion-system.html#shared-axis)).

It doesn't require transitionNames or shared elements so it should be easier to set up, and the animation may feel more appropriate.

There's an example of this in our Catalog demo app:

https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/transition/TransitionSharedAxisDemoFragment.java

And in our Reply sample app:

https://github.com/material-components/material-components-android-examples/blob/develop/Reply/app/src/main/java/com/materialstudies/reply/ui/search/SearchFragment.kt

What do you think about that?

**Comment by luanmm** [comment]
It is a good UX tool, but not what I wanted to achieve here. It is not so dynamic as the shared element transition (as it does not have the "user-teaching" appeal). It may be an workaround for the moment, but definately it isn't a definitive solution.

No other thoughts about what is happening in this scenario?

**Comment by dsn5ft** [comment]
No other immediate thoughts. Can you create a GitHub repo with a minimal sample app that reproduces the issue? That way I can try to debug.

**Comment by dsn5ft** [comment]
Thanks! Will take a look soon.

**Comment by dispaz** [comment]
I would like to share with you bug in MaterialContainerTransition, here you can see strange middle-screen bug (i guess it's appearing when recyclerviewitem is at the middle of the fragment), another one bug appears on 2 other elements - blinking on the beginning of transition (you can see that on gif below) I can't find solution to this :( 
I hope you will help me 
![container-transform-bug](https://user-images.githubusercontent.com/8697328/85207549-cfd38b80-b329-11ea-873a-eac335f2f138.gif)

**Comment by dsn5ft** [comment]
@dispaz please file a separate issue, and provide a GitHub repo with a minimal sample app that reproduces the issue.

**Comment by hunterstich** [comment]
Hey @dispaz, any chance you can share a sample repo that reproduces the gif you attached?
