### ISSUE TITLE
[ChipDrawable] Set textColor programmatically

### ISSUE THREAD

**Issue by dadino** [material-components/material-components-android#1165]
**Is your feature request related to a problem? Please describe.**
Unable to set textColor programmatically.

**Describe the solution you'd like**
Add the setTextColor found in Chip.

**Describe alternatives you've considered**
Unable to create TextAppearance for each possible color since they're loaded from a backend.

**Comment by AndreSand** [comment]
Hi, I think you can use:
`chip.setTextColor(getColorStateList(context, R.color.red))`

**Comment by adesamp** [comment]
> Hi, I think you can use:
> `chip.setTextColor(getColorStateList(context, R.color.red))`

nothing `setTextColor` in ChipDrawable afaik

**Comment by samuelchou** [comment]
`ChipDrawable` is such an abandoned thing, that material team didn't even want to provide a `setTextColor` method for months. 😢

**Comment by samuelchou** [comment]
I'd also like to point out that `ChipDrawable.setText` could not help in this case: the `Span` set inside `SpannableString` which apply to this ChipDrawable seems not working.

```Kotlin
val chipText = "TEXT"
val textColorSpan = ForegroundColorSpan(getColor(R.color.RED))
chipDrawable.text = SpannableStringBuilder(chipText).apply {
    setSpan(textColorSpan, 0, chipText.length, 0) // not working!
}
```

**Comment by pubiqq** [comment]
Well, it looks like the fix got into the `master` branch (commit https://github.com/material-components/material-components-android/commit/10edcd11d527996c22d29ce2d0c95ab6533eee73, based on https://github.com/material-components/material-components-android/pull/2526). Maybe we can close this issue and update irrelevant labels in [pr](https://github.com/material-components/material-components-android/pull/2526)?

**Comment by drchen** [comment]
Yes. Somehow it doesn't automatically close the issue. Thanks for the reminder and your effort on this! : )
