### ISSUE TITLE
[MaterialDatePicker] Consider using a prefix that is unique to the module

### ISSUE THREAD

**Issue by kfaraj** [material-components/material-components-android#1166]
**Description:** The MaterialDatePicker component embeds drawable resources marked as private:
- ic_calendar_black_24dp.xml
- ic_clear_black_24dp.xml
- ic_edit_black_24dp.xml
- ic_keyboard_arrow_left_black_24dp.xml
- ic_keyboard_arrow_right_black_24dp.xml
- ic_menu_arrow_down_black_24dp.xml
- ic_menu_arrow_up_black_24dp.xml

However, those common resource IDs are not prefixed which prevent us from using the same name in our app and forces us to pick a different name.

**Expected behavior:** Those resources should be prefixed to avoid resource conflicts for common resource IDs:
- mtrl_ic_calendar_black_24dp.xml
- mtrl_ic_clear_black_24dp.xml
- mtrl_ic_edit_black_24dp.xml
- mtrl_ic_keyboard_arrow_left_black_24dp.xml
- mtrl_ic_keyboard_arrow_right_black_24dp.xml
- mtrl_ic_menu_arrow_down_black_24dp.xml
- mtrl_ic_menu_arrow_up_black_24dp.xml

For more information please refer to https://developer.android.com/studio/projects/android-library#Considerations

**Material Library version:** 1.1.0

**Comment by hunterstich** [comment]
Thanks for filing Kamal. Adding this to our list of things to look into
