### ISSUE TITLE
[TabLayout] Tabs don't take badges into consideration when measuring width

### ISSUE THREAD

**Issue by ryandt** [material-components/material-components-android#1168]
**Description** 
When a `TabLayout` is set to `tabGravity="center"` and it contains a tab with a `BadgeDrawable`, the badge gets cut off if the drawable extends beyond the right bound of its tab.

![tab-badge-cutoff](https://user-images.githubusercontent.com/4073952/77972230-66a62400-72b6-11ea-911d-5b9b21b8cd97.png)

**Expected behavior**
A `TabLayout` tab should take the size of its badge into consideration when determining its width.

**Relevant code**
```
<com.google.android.material.tabs.TabLayout
    android:id="@+id/tab_layout"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:background="?attr/colorSurface"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    app:tabGravity="center" /> 
```
```
tab.getOrCreateBadge().apply {
    number = 100
    maxCharacterCount = 3
    isVisible = true
}
```

**Android API version** 
Android 29

**Material Library versions** 
1.1.0
1.2.0-alpha05

**Device**
Pixel 3

**Comment by wcshi** [comment]
I can make a small change that alleviates your specific situation, re-writing tablayout to account the badge width will be a larger effort.

**Comment by ryandt** [comment]
@wcshi Understood. What change do you have in mind? Making the badge offset configurable?

**Comment by wcshi** [comment]
The badge offset is currently configurable via BadgeDrawable#setHorizontalOffset and BadgeDrawable#setVerticalOffset so you may adjust if you wish.

I am planning to call setClipChildren(false) and setClipToPadding(false) on the SlidingTabIndicator, which tabview's parent.

**Comment by ryandt** [comment]
Sounds good. Setting a negative horizontal offset would not be ideal for me since it would overlay text a little more than I'd like it to. Looking forward to seeing the result of `setClipToPadding(false)`. Cheers!

**Comment by KoTius** [comment]
`If a long badge is shown on an end tab with a long string, it could still be clipped off. Current workaround is to adjust the badge offset.`
Great fix 👍
