### ISSUE TITLE
if having dependency on the material-component, does it still need dependency on ViewPager2

### ISSUE THREAD

**Issue by lannyf77** [material-components/material-components-android#1170]
Having project using ViewPager2, and it does not put in the dependency to ViewPager2 directly in the gradle like it would:

implementation 'androidx.viewpager2:viewpager2:1.0.0'

But it works fine without dependency on ViewPager2, and seems the

implementation 'com.google.android.material:material:1.1.0' implicitly adds the dependency on the ViewPager2.

![image](https://user-images.githubusercontent.com/19765258/78175838-86118e00-7429-11ea-8ae9-4ea006f11458.png)

Question: is it good enough to have dependency on materialComponent, or it's better to also add the dependency on the ViewPager2?

**Comment by PaulWoitaschek** [comment]
Nope, keep your dependencies up to date instead of relying on transitive dependencies.

**Comment by lannyf77** [comment]
Thanks Paul! and will add the ViewPager2 dependence then.
