### ISSUE TITLE
[TextInputLayout] Show/Hide Password Icons are Mixed Up

### ISSUE THREAD

**Issue by zkovar** [material-components/material-components-android#1171]
**Description:** 

I am using:
```
<com.google.android.material.textfield.TextInputLayout>
<com.google.android.material.textfield.TextInputEditText />
</com.google.android.material.textfield.TextInputLayout>
```
with
`<item name="passwordToggleEnabled">true</item>`

To create the UI for a Password entry with a show/hide password toggle. The behavior matches the specs from the Material Guidelines shown [here](https://material.io/components/text-fields/#outlined-text-field). However, these feel entirely counter-intuitive **AND** Google's own behavior for other apps does not match this.

**Current Behavior**
![component_show_password](https://user-images.githubusercontent.com/2594178/78181656-c4f81180-7432-11ea-9f69-1a160453fd71.png)
![component_hide_password](https://user-images.githubusercontent.com/2594178/78181646-c32e4e00-7432-11ea-9b3f-146b4b95c800.png)

**Expected Behavior (and Google's own behavior)**
![hide_password](https://user-images.githubusercontent.com/2594178/78181658-c590a800-7432-11ea-859d-677275941b1a.jpg)
![show_password](https://user-images.githubusercontent.com/2594178/78181661-c6c1d500-7432-11ea-9cef-f1fb02c1cb8c.jpg)

**Android API version:**
All versions

**Material Library version:** 
1.2.0-alpha05

**Device:** All devices

**Comment by hunterstich** [comment]
Thanks for filing this @zkovar. I'm bringing this up with design to see what they have to say.

**Comment by leticiarossi** [comment]
designed agreed the current behavior should be flipped, so that the icon shows the action (what will happen after the click), instead of how now it shows the current status

**Comment by zkovar** [comment]
This has been fixed by 99c6a28.

**Comment by sinnavj** [comment]
`    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/layout_password_callback"
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/padding_medium"
        android:layout_marginTop="@dimen/padding_xlarge"
        android:layout_marginEnd="@dimen/padding_medium"
        android:layout_marginBottom="@dimen/padding_medium"
        app:passwordToggleEnabled="true"   // It works in all api versions 1.2.0 to 1.3.0-beta01
        app:endIconMode="password_toggle". // it's still behaving in opposite order
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/tv_forgot_user_name">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/edit_password_callback"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:imeOptions="actionDone"
            android:importantForAutofill="no"
            android:maxLength="@integer/password_length"
            android:singleLine="true" />
    </com.google.android.material.textfield.TextInputLayout>`


And in the docs it's written that 
 
    <attr format="boolean" name="passwordToggleEnabled"/>
so is there any update on it when it's going to be fixed 
Thanks

**Comment by Reubencfernandes** [comment]
yes it is still happening

**Comment by goputtanz** [comment]
The issue is  **outdated functionality of password toggle enabled**, It is **not officially removed**, but we can fix this by adding **custom end icon drawable to TextInput Layout** as

        app:endIconMode="password_toggle"


**and drawable file as**

    <?xml version="1.0" encoding="utf-8"?>
    <selector xmlns:android="http://schemas.android.com/apk/res/android">
        <item android:drawable="@drawable/ic_opened_eye"
            android:state_checked="true"/>
        <item android:drawable="@drawable/ic_closed_eye"/>
    </selector>

_this worked for me_

**Comment by Hk952700** [comment]
HELP ME !!!     It is still happening ...... @hunterstich

**Comment by ItsHiraeths** [comment]
Surprisingly it is still happening untill this day. I dont know why they never fix this.

**Comment by MKoleff** [comment]
Still not fixed...

**Comment by YhanChristian** [comment]
Still not fixed, i created an custom xml, follow steps to do:

1. create 2 drawables ic_visibility and ic_not_visibility

ic_visibility.xml
 `<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960"
    android:tint="?attr/colorControlNormal">
  <path
      android:fillColor="@android:color/white"
      android:pathData="M480,640Q555,640 607.5,587.5Q660,535 660,460Q660,385 607.5,332.5Q555,280 480,280Q405,280 352.5,332.5Q300,385 300,460Q300,535 352.5,587.5Q405,640 480,640ZM480,568Q435,568 403.5,536.5Q372,505 372,460Q372,415 403.5,383.5Q435,352 480,352Q525,352 556.5,383.5Q588,415 588,460Q588,505 556.5,536.5Q525,568 480,568ZM480,760Q334,760 214,678.5Q94,597 40,460Q94,323 214,241.5Q334,160 480,160Q626,160 746,241.5Q866,323 920,460Q866,597 746,678.5Q626,760 480,760ZM480,460Q480,460 480,460Q480,460 480,460Q480,460 480,460Q480,460 480,460Q480,460 480,460Q480,460 480,460Q480,460 480,460Q480,460 480,460ZM480,680Q593,680 687.5,620.5Q782,561 832,460Q782,359 687.5,299.5Q593,240 480,240Q367,240 272.5,299.5Q178,359 128,460Q178,561 272.5,620.5Q367,680 480,680Z"/>
</vector>
`

ic_visibility_off
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960"
    android:tint="?attr/colorControlNormal">
  <path
      android:fillColor="@android:color/white"
      android:pathData="M644,532L586,474Q595,427 559,386Q523,345 466,354L408,296Q425,288 442.5,284Q460,280 480,280Q555,280 607.5,332.5Q660,385 660,460Q660,480 656,497.5Q652,515 644,532ZM772,658L714,602Q752,573 781.5,538.5Q811,504 832,460Q782,359 688.5,299.5Q595,240 480,240Q451,240 423,244Q395,248 368,256L306,194Q347,177 390,168.5Q433,160 480,160Q631,160 749,243.5Q867,327 920,460Q897,519 859.5,569.5Q822,620 772,658ZM792,904L624,738Q589,749 553.5,754.5Q518,760 480,760Q329,760 211,676.5Q93,593 40,460Q61,407 93,361.5Q125,316 166,280L56,168L112,112L848,848L792,904ZM222,336Q193,362 169,393Q145,424 128,460Q178,561 271.5,620.5Q365,680 480,680Q500,680 519,677.5Q538,675 558,672L522,634Q511,637 501,638.5Q491,640 480,640Q405,640 352.5,587.5Q300,535 300,460Q300,449 301.5,439Q303,429 306,418L222,336ZM541,429L541,429Q541,429 541,429Q541,429 541,429Q541,429 541,429Q541,429 541,429Q541,429 541,429Q541,429 541,429ZM390,504Q390,504 390,504Q390,504 390,504L390,504Q390,504 390,504Q390,504 390,504Q390,504 390,504Q390,504 390,504Z"/>
</vector>
`

3. Create a custom drawable selector (show_password_selector)
`<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/ic_visibility" android:state_checked="true"/>
    <item android:drawable="@drawable/ic_visibility_off"/>
</selector>
`

4. Include in your xml editText, for example:
`    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/text_input_signup_password"
        style="@style/Theme.FinanceControl.FormEditTextInput"
        app:passwordToggleEnabled="true"
        app:passwordToggleDrawable="@drawable/show_password_selector"
        android:layout_marginTop="16dp"
        app:layout_constraintTop_toBottomOf="@+id/text_input_signup_email"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:hintEnabled="false">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/edit_signup_password"
            style="@style/Theme.FinanceControl.FormEditText"
            android:autofillHints="@null"
            android:hint="@string/password"
            android:textColorHint="@color/gray_text"
            android:inputType="textPassword"/>
    </com.google.android.material.textfield.TextInputLayout>`

**Comment by dev-divyansh** [comment]
Still not fixed its almost end of 2024
