### ISSUE TITLE
[MaterialDatePicker] Numbers are not aligned on the center

### ISSUE THREAD

**Issue by donnkii** [material-components/material-components-android#1172]
**Description:** Numbers are not aligned on the center
![Screenshot_1585816072](https://user-images.githubusercontent.com/58042472/78227093-089f5980-74cd-11ea-8655-03f2a3f568da.png)

**Expected behavior:** Numbers should be aligned on the center

**Source code:** 
**NOTE: The same behavior occured even before adding any style**

    <style name="OeamtcThemeOverlay_MaterialCalendar"
        parent="@style/Theme.MaterialComponents.Light.Dialog">
        <item name="android:colorAccent">@color/oeamtc_accent</item>
        <item name="headerLayout">@style/Oeamtc_MaterialCalendar_Header</item>
        <item name="android:colorButtonNormal">@color/oeamtc_accent</item>
        <item name="android:button">@color/oeamtc_accent</item>
        <item name="buttonBarPositiveButtonStyle">@style/ThemeMaterialCalendarButton</item>
        <item name="buttonBarNegativeButtonStyle">@style/ThemeMaterialCalendarButton</item>
        <item name="materialCalendarStyle">@style/Oeamtc_MaterialCalendar</item>
        <item name="materialButtonStyle">@style/ThemeMaterialButton</item>
    </style>

    <style name="Oeamtc_MaterialCalendar"
        parent="@style/Widget.MaterialComponents.MaterialCalendar">
        <item name="rangeFillColor">@color/oeamtc_accent_transparent_50</item>
        <item name="dayStyle">@style/Oeamtc_CalendarDay</item>
        <item name="dayTodayStyle">@style/Oeamtc_CalendarToday</item>
        <item name="daySelectedStyle">@style/Oeamtc_CalendarSelected</item>
    </style>

    <style name="ThemeMaterialCalendarButton" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="android:textColor">@color/oeamtc_accent</item>
    </style>

    <style name="ThemeMaterialButton" parent="Widget.MaterialComponents.Button">
        <item name="android:textColor">@color/white</item>
        <item name="android:backgroundTint">@color/oeamtc_accent</item>
    </style>

    <style name="Oeamtc_CalendarDay" parent="Test.Widget.MaterialComponents.MaterialCalendar.Day">
        <item name="itemTextColor">@color/black</item>
        <item name="itemFillColor">@color/transparent</item>
        <item name="itemStrokeColor">@color/white</item>
        <item name="itemStrokeWidth">0dp</item>
        <item name="android:gravity">center</item>
        <item name="itemShapeAppearance">@style/Test.ShapeAppearanceOverlay.MaterialComponents.MaterialCalendar.Day</item>
        <item name="itemShapeAppearanceOverlay">@style/Test.ShapeAppearanceOverlay.MaterialComponents.MaterialCalendar.Day</item>
    </style>

    <style name="Oeamtc_CalendarSelected" parent="">
        <item name="itemFillColor">@color/oeamtc_accent</item>
        <item name="itemTextColor">@color/white</item>
        <item name="itemStrokeColor">@color/oeamtc_accent</item>
        <item name="itemStrokeWidth">0dp</item>
        <item name="itemShapeAppearance">@style/Test.ShapeAppearanceOverlay.MaterialComponents.MaterialCalendar.Day</item>
        <item name="itemShapeAppearanceOverlay">@style/Test.ShapeAppearanceOverlay.MaterialComponents.MaterialCalendar.Day</item>
    </style>

    <style name="Oeamtc_CalendarToday" parent="">
        <item name="itemTextColor">@color/black</item>
        <item name="itemStrokeColor">@color/oeamtc_accent</item>
        <item name="itemFillColor">@color/white</item>
        <item name="itemStrokeWidth">3dp</item>
        <item name="itemShapeAppearance">@style/Test.ShapeAppearanceOverlay.MaterialComponents.MaterialCalendar.Day</item>
        <item name="itemShapeAppearanceOverlay">@style/Test.ShapeAppearanceOverlay.MaterialComponents.MaterialCalendar.Day</item>
    </style>`

**Android API version:** 29

**Material Library version:** 1.1.0

**Device:** Oneplus 6t and all nexus emulators

**Comment by hunterstich** [comment]
Hey @donnkii 

Do you mind attaching a minimal sample that reproduces this so we can look into what's happening?

**Comment by donnkii** [comment]
@hunterstich I have already attacked the styles.xml file.
Here is the implementation file:

```
  interface RangeDatePickerListener {
        fun onPositiveButtonClick(datePair: Pair<Long, Long>)
        fun onNegativeButtonClick(view: View)
    }

    companion object {
        fun createRangeDatePickerInstance(rangeFrom: Long, rangeTo: Long, minDate: Date, maxDate: Date, @StyleRes themeResId: Int, listener: RangeDatePickerListener): DialogFragment {
            val constraints: CalendarConstraints.Builder = CalendarConstraints.Builder()
            constraints.setStart(minDate.time)
            constraints.setEnd(maxDate.time)
            constraints.setOpenAt(rangeFrom)

            val builder: MaterialDatePicker.Builder<Pair<Long, Long>> =
                    MaterialDatePicker.Builder.dateRangePicker()
            builder.setSelection(Pair(rangeFrom, rangeTo))
            builder.setTheme(themeResId)
            builder.setCalendarConstraints(constraints.build())

            val picker: MaterialDatePicker<Pair<Long, Long>> = builder.build()
            picker.addOnPositiveButtonClickListener { datePair ->
                listener.onPositiveButtonClick(datePair)
            }
            picker.addOnNegativeButtonClickListener { view ->
                listener.onNegativeButtonClick(view)
            }
            return picker
        }
    }

**Comment by donnkii** [comment]
I believe the problem was because I wasn't inheriting Theme.MaterialComponents on application theme.

**Comment by hunterstich** [comment]
Nice. Going to go ahead and close this.
