### ISSUE TITLE
[Chip Group] app:singleSelection doesn't work with added dynamically chips.

### ISSUE THREAD

**Issue by ruifernando7** [material-components/material-components-android#1178]
I declare ChipGroup on xml
```
 <com.google.android.material.chip.ChipGroup
                    android:id="@+id/cg_time"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:singleSelection="true"
                    app:selectionRequired="true "/>
```
I added checkable chips dynamically from a fragment with code below and i initilize only one chip to be checked
```
data.forEach { item ->
            val chip = Chip(context)
            chip.text = item.data.name
            chip.isCheckedIconVisible = true
            chip.isCheckable = true
            chip.isClickable = true
            
            **chip.isChecked = item.isSelected**
            cg_time.addView(chip)
        }
```
When I run the application, one chip got checked as expected. But when I click on other chips, I got two chips checked. The previous chip is still checked. In conclusion, I think there is a bug on app:singleSelection. Please clarify this problem. Thanks in advance

**Comment by hunterstich** [comment]
I'm guessing this is because you're setting the checked state on a chip before it gets added to the ChipGroup? What happens if you used `ChipGroup#check(id)` instead of setting each chip to checked?

Do you mind supplying a small sample that reproduces this?

**Comment by ruifernando7** [comment]
Finally it works well with ChipGroup#check(id) as you suggested. I set the id of each chip using `ViewCompat.generateViewId()` . I think it would be better when `app:singleSelection` can handle dynamic chips scenario.

**Comment by hunterstich** [comment]
Glad that worked.

Will think about what we can do for dynamically adding Chips to a single selection ChipGroup

**Comment by Flatigers** [comment]
> I am also facing the same issue. What do you mean by this ChipGroup#check(id)? I have set the id for each chip using ViewCompat.generateViewId() as mentioned above but still does not work.

Maybe you should try to new a Chip by `val chip = Chip()`, and then use `chipGroup.addView(chip)` to add it to the group, instead of using `LayoutInflater`. I made this mistake just now.
