### ISSUE TITLE
[MaterialButton] Creating a button with a style programmatically does not set all attributes

### ISSUE THREAD

**Issue by bryandunbar** [material-components/material-components-android#1183]
When creating a MaterialButton in code and passing a style from styles.xml not all attributes apply to the button,. Specifically backgroundTint, iconTint, and textColor, although there may be others.  When building the component from an xml layout all styling is applied correctly

**Expected behavior:** Styles should be applied as if they were created in xml

`val button = MaterialButton(newContext, null, R.style.Widget_Cladwell_Button_FilterCapsule)

<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowLightStatusBar">true</item>
    </style>
 <style name="Widget.Cladwell.Button.FilterCapsule" parent="Widget.MaterialComponents.Button">
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">40dp</item>
        <item name="android:layout_marginEnd">8dp</item>
        <item name="cornerRadius">14dp</item>
        <item name="android:checkable">true</item>
        <item name="iconGravity">textStart</item>
        <item name="android:textStyle">normal</item>
        <item name="android:textAllCaps">false</item>
        <item name="iconTint">@drawable/category_filter_foreground</item>
        <item name="backgroundTint">@drawable/category_filter_background</item>
        <item name="android:textColor">@drawable/category_filter_foreground</item>
    </style>`

**Android API version:** 29

**Material Library version:** 1.2.0-aplpha05

**Comment by hunterstich** [comment]
Hey there. Do you mind attaching a small project that demonstrates the problem you're describing? It's much easier for us to diagnose if we can look at how everything in your project is connected and what your theme/style/layout hierarchy looks like. 

Thanks!

**Comment by apkelly** [comment]
I've noticed the same, 

```
    <style name="Widget.Button.Normal" parent="Widget.MaterialComponents.Button">
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">72dp</item>
        <item name="android:textSize">18sp</item>
        <item name="android:layout_marginStart">3.5dp</item>
        <item name="android:layout_marginEnd">3.5dp</item>
        <item name="android:textAllCaps">false</item>
        <item name="android:gravity">center</item>
        <item name="android:elevation">3dp</item>
        <item name="backgroundTint">@color/btn_bg_tint</item>
        <item name="android:textColor">@color/btn_text_color</item>
    </style>
```
I've tried using the 3 arg constructor for MaterialButton, and the "old" ContextThemeWrapper pattern, but in neither case is my style applied to my button.

```
        val tipButton = MaterialButton(ContextThemeWrapper(requireContext(), R.style.Widget_Button_Normal)).apply {
            text = "tip amount"
        }
        tip_content.addView(tipButton)
```

When the style above is applied to other MaterialButtons in xml layouts directly it works as expected.

I'm using Material version 1.2.0-alpha06 on Android 8.1

**Comment by alapshin** [comment]
I have created repo that demonstrates this problem: https://github.com/alapshin/materialissue1183.

**Comment by gabrielemariotti** [comment]
You can't assign a style using:
`MaterialButton(wrap(context, attrs, defStyleAttr, defStyleRes), attrs, defStyleAttr)`

The` MaterialThemeOverlay.wrap `method uses the `materialThemeOverlay` attribute to create a themed context.

You apply a **theme overlay** using something like:

```
class AccentButton @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        @AttrRes defStyleAttr: Int = R.attr.materialButtonStyle,
        @StyleRes defStyleRes: Int = R.style.AccentButtonThemeOverlay
) : MaterialButton(ContextThemeWrapper(context, defStyleRes), attrs, defStyleAttr) {
}
```

with:

```
    <style name="AccentButtonThemeOverlay" parent="">
        <item name="materialThemeOverlay">@style/buttonoverlay</item>
    </style>

    <style name="buttonoverlay">
        <item name="colorPrimary">@color/...</item>
    </style>
```

If you want to create a custom button with a **custom style** you have to:

- define an attribute in `attrs.xml`
` <attr name="myButtonStyle" format="reference"/>`
- assign in your app theme a value to this new attr:
```
    <style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
        <item name="myButtonStyle">@style/AccentButtonStyle</item>
   </style>

```
with:
```
    <style name="AccentButtonStyle" parent="Widget.MaterialComponents.Button">
        <item name="backgroundTint">@color/...</item>
        <item name="icon">@drawable/....</item>
        <item name="iconTint">@color/....</item>
    </style>
```
and then use this constructor:

```
class AccentButton @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        @AttrRes defStyleAttr: Int = R.attr.myButtonStyle
  ) : MaterialButton(context, attrs, defStyleAttr) {
}
```

**Comment by gabrielemariotti** [comment]
You can't assign a style using:
`MaterialButton(wrap(context, attrs, defStyleAttr, defStyleRes), attrs, defStyleAttr)`

The` MaterialThemeOverlay.wrap `method uses the `materialThemeOverlay` attribute to create a themed context.

You apply a **theme overlay** using something like:

```
class AccentButton @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        @AttrRes defStyleAttr: Int = R.attr.materialButtonStyle,
        @StyleRes defStyleRes: Int = R.style.AccentButtonThemeOverlay
) : MaterialButton(ContextThemeWrapper(context, defStyleRes), attrs, defStyleAttr) {
}
```

with:

```
    <style name="AccentButtonThemeOverlay" parent="">
        <item name="materialThemeOverlay">@style/buttonoverlay</item>
    </style>

    <style name="buttonoverlay">
        <item name="colorPrimary">@color/...</item>
    </style>
```

If you want to create a custom button with a **custom style** you have to:

- define an attribute in `attrs.xml`
` <attr name="myButtonStyle" format="reference"/>`
- assign in your app theme a value to this new attr:
```
    <style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
        <item name="myButtonStyle">@style/AccentButtonStyle</item>
   </style>

```
with:
```
    <style name="AccentButtonStyle" parent="Widget.MaterialComponents.Button">
        <item name="backgroundTint">@color/...</item>
        <item name="icon">@drawable/....</item>
        <item name="iconTint">@color/....</item>
    </style>
```
and then use this constructor:

```
class AccentButton @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        @AttrRes defStyleAttr: Int = R.attr.myButtonStyle
  ) : MaterialButton(context, attrs, defStyleAttr) {
}
```

**Comment by bryandunbar** [comment]
So why does it work in xml layout? This seems like a lot of extra code/indirection to do something that works out of the box for non material components.

**Comment by dsn5ft** [comment]
Unfortunately this is just a limitation of the Android framework. Using a theme overlay that sets the default widget style and wrapping the context passed into the constructor is the recommended approach.

**Comment by bryandunbar** [comment]
Gotcha. Will give it a shot!! Thanks for the detailed explanation!

**Comment by sjaramillo10** [comment]
@gabrielemariotti your explanation is great! Thank you! I spent hours trying to achieve this and when I was about to give up I found this issue. It finally worked! Also thanks to @bryandunbar for asking this question 🎉

**Comment by bryandunbar** [comment]
@gabrielemariotti works like a charm. thanks!!

**Comment by debugmoov** [comment]
Why MaterialButton doesn't have the constructor that accepts a default style attribute as its fourth argument?

**Comment by pollux-** [comment]
> [gabrielemariotti](/gabrielemariotti)

Thanks for your response, I could have never figured this out without your help. Thanks you 💯

**Comment by Devs-97Eats** [comment]
> You can't assign a style using: `MaterialButton(wrap(context, attrs, defStyleAttr, defStyleRes), attrs, defStyleAttr)`
> 
> The`MaterialThemeOverlay.wrap`method uses the `materialThemeOverlay` attribute to create a themed context.
> 
> You apply a **theme overlay** using something like:
> 
> ```
> class AccentButton @JvmOverloads constructor(
>         context: Context,
>         attrs: AttributeSet? = null,
>         @AttrRes defStyleAttr: Int = R.attr.materialButtonStyle,
>         @StyleRes defStyleRes: Int = R.style.AccentButtonThemeOverlay
> ) : MaterialButton(ContextThemeWrapper(context, defStyleRes), attrs, defStyleAttr) {
> }
> ```
> 
> with:
> 
> ```
>     <style name="AccentButtonThemeOverlay" parent="">
>         <item name="materialThemeOverlay">@style/buttonoverlay</item>
>     </style>
> 
>     <style name="buttonoverlay">
>         <item name="colorPrimary">@color/...</item>
>     </style>
> ```
> 
> If you want to create a custom button with a **custom style** you have to:
> 
> * define an attribute in `attrs.xml`
>   ` <attr name="myButtonStyle" format="reference"/>`
> * assign in your app theme a value to this new attr:
> 
> ```
>     <style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
>         <item name="myButtonStyle">@style/AccentButtonStyle</item>
>    </style>
> ```
> 
> with:
> 
> ```
>     <style name="AccentButtonStyle" parent="Widget.MaterialComponents.Button">
>         <item name="backgroundTint">@color/...</item>
>         <item name="icon">@drawable/....</item>
>         <item name="iconTint">@color/....</item>
>     </style>
> ```
> 
> and then use this constructor:
> 
> ```
> class AccentButton @JvmOverloads constructor(
>         context: Context,
>         attrs: AttributeSet? = null,
>         @AttrRes defStyleAttr: Int = R.attr.myButtonStyle
>   ) : MaterialButton(context, attrs, defStyleAttr) {
> }
> ```

Thanks a lot @gabrielemariotti  , it's working properly now
