### ISSUE TITLE
[TextInputLayout] Stroke around FilledBox or changing position and background color of label in OutlinedBox

### ISSUE THREAD

**Issue by lebzuch** [material-components/material-components-android#1187]
**Is your feature request related to a problem? Please describe.**
I love material TextInputLayout but my clients aren't ready for changing layouts. They used to have background with border in edit texts and label inside of the container.

**Describe the solution you'd like**
I would love to have possibility to setting stroke around FilledBox edit text.

**Describe alternatives you've considered**
As alternative there can be possibility of setting label position inside of the container in OutlinedBox edit text which will work as label in FilledBox and label background color which will fit to container background color.

Right now I found workaround by setting background with different states on FilledBox edit text but you clearly annotate in material components readme to do not set background for it.

**Additional context**

Normal view:
![normal](https://user-images.githubusercontent.com/1751998/78558957-d155e300-7813-11ea-9b31-38bb611c80c0.png)

Filled focused:
![focused](https://user-images.githubusercontent.com/1751998/78558961-d450d380-7813-11ea-8084-d82839eed5ee.png)

**Comment by hunterstich** [comment]
You could create something like this if you remove the background  from both TextInputLayout and TextInputEditText and remove stroke from a TextInputLayout and provided your own StateListDrawable as the background of TextInputLayout.

```
    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/text_input_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="24dp"
        android:layout_marginLeft="24dp"
        android:layout_marginRight="24dp"
        android:hint="Email"
        app:boxBackgroundColor="@android:color/transparent"
        app:boxStrokeWidth="0dp"
        app:boxStrokeWidthFocused="0dp">
        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/edit_text"
            android:background="@android:color/transparent"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </com.google.android.material.textfield.TextInputLayout>
```

// res/drawable/text_field_background.xml

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_focused="true">
        <shape android:shape="rectangle">
            <solid android:color="@android:color/white"/>
            <stroke android:width="1dp" android:color="?attr/colorPrimary"/>
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <solid android:color="@android:color/white"/>
            <stroke android:width="1dp" android:color="?attr/colorControlNormal"/>
        </shape>
    </item>
</selector>
```


<img width="471" alt="Screen Shot 2020-04-09 at 14 57 03" src="https://user-images.githubusercontent.com/7459254/78930622-6a823500-7a72-11ea-8915-e2f94a759417.png">
<img width="471" alt="Screen Shot 2020-04-09 at 14 57 13" src="https://user-images.githubusercontent.com/7459254/78930627-6ce48f00-7a72-11ea-89d9-653e93a31a29.png">

**Comment by hunterstich** [comment]
Since we already have 2 well-defined text field variants its unlikely design and/or eng would approve pulling a third as an official feature. 

Going to go ahead and closing this but feel free to continue discussing and I'll try to answer any questions. If the above state list solution doesn't work we can brainstorm on other solutions

**Comment by lebzuch** [comment]
Hi @hunterstich, thanks for response. Like I said
> Right now I found workaround by setting background with different states on FilledBox edit text but you clearly annotate in material components readme to do not set background for it.

If this is your recommended way of doing this so I'm happy :)

**Comment by thevoiceless** [comment]
Commenting in case anyone else stumbles across this issue in the future: Providing your own background works for almost everything, but you do lose the automatic error coloring:
<img width="304" alt="Screen Shot 2020-08-13 at 5 54 02 PM" src="https://user-images.githubusercontent.com/1574103/90273502-4bc6ed00-de1c-11ea-88b7-4f369ec9e8d0.png">

**Comment by oradkovsky** [comment]
I don't think I lost any styling, but here is the way I did it:

1. Base my TextInputLayout style on parent="@style/Widget.MaterialComponents.TextInputLayout.FilledBox"
2. Provided custom materialThemeOverlay inheriting @style/ThemeOverlay.MaterialComponents.TextInputEditText.OutlinedBox
3. Inside materialThemeOverlay implementation, used color state list for backgroundTint

Also worth mentioning, my input layout was actually outlined type, and I was directly setting boxStrokeColor as another color state list. But in the end when setError got called the outline was correctly drawn as "red".

**Comment by Dona278** [comment]
Just to share with community:
I used the approach described by @hunterstich and I created a selector drawable resource that I used as a background for `TextInputEditText`:

// text_input_white_background.xml
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <!-- Focused -->
  <item android:drawable="@drawable/text_input_white_background_focused"
        android:state_focused="true"/>

  <!-- Disabled -->
  <item android:drawable="@drawable/text_input_white_background_disabled"
        android:state_enabled="false"/>

  <!-- Normal -->
  <item android:drawable="@drawable/text_input_white_background_normal"/>
</selector>
```
in this way each state can be customized, for example:

// text_input_white_background_normal.xml
```
<?xml version="1.0" encoding="utf-8"?>
<shape
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:shape="rectangle">
  <corners android:radius="4dp"/>
  <stroke
     android:width="1dp"
     android:color="@color/text_input_white_border" />
  <solid android:color="@color/text_input_white_background" />
</shape>
```
But this led to the issue described by @thevoiceless so I created another drawable for error state:

// text_input_white_background_error.xml
```
<?xml version="1.0" encoding="utf-8"?>
<shape
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:shape="rectangle">
  <corners android:radius="4dp"/>
  <stroke
     android:width="1dp"
     android:color="@color/button_warn_border" />
  <solid android:color="@color/text_input_white_background" />
</shape>
```

and then, I extended the `TextInputLayout` class by adding an override on the `setErrorEnabled" property which update the `TextInputLayout.editText`'s background with the correct drawable: normal or error.

I added the "Normal selector" and  "Error" drawables as a custom attributes of `TextInputLayout` (yes, I named the new widget with the same name of the extended android widget :)).

// attrs.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <!-- TextInputLayout -->
  <declare-styleable name="TextInputLayout">
    <attr name="textInputLayoutNormalSelectorDrawable" format="reference"/>
    <attr name="textInputLayoutErrorDrawable" format="reference"/>
  </declare-styleable>
</resources>
```

Finally, I changed the style of the `TextInputLayout`, according to the suggestion of @oradkovsky:

styles.xml
```
  <style name="TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.FilledBox">
    <item name="materialThemeOverlay">@style/CustomTextInputLayoutThemeOverlay</item>
    <item name="shapeAppearanceOverlay">@style/CustomTextInputLayoutShapeAppearanceOverlay</item>
    <item name="textInputLayoutNormalSelectorDrawable">@drawable/text_input_white_background</item>
    <item name="textInputLayoutErrorDrawable">@drawable/text_input_white_background_error</item>
    <item name="boxCollapsedPaddingTop">4dp</item>
    <item name="boxStrokeWidth">0dp</item>
    <item name="boxStrokeWidthFocused">0dp</item>
    <item name="hintEnabled">true</item>
  </style>

  <style name="CustomTextInputLayoutThemeOverlay" parent="ThemeOverlay.MaterialComponents.TextInputEditText.OutlinedBox">
    <item name="editTextStyle">@style/CustomTextInputLayoutEditTextStyle</item>
  </style>

  <style name="CustomTextInputLayoutEditTextStyle" parent="Widget.MaterialComponents.TextInputEditText.OutlinedBox">
    <!-- Padding values that total 34dp to visually match the spec. -->
    <item name="android:paddingTop">24dp</item>
    <item name="android:paddingBottom">10dp</item>
  </style>

  <style name="CustomTextInputLayoutShapeAppearanceOverlay" parent="">
    <item name="cornerSizeBottomLeft">4dp</item>
    <item name="cornerSizeBottomRight">4dp</item>
  </style>
```

In this way we got hybrid FilledBox background behaviour, with OutlinedBox hint behaviour, with custom background and border color, with all views aligned vertically, that can be used as the classic TextInputLayout but using the custom widget created previously with the custom style.

```
<xxx.widgets.TextInputLayout
    style="@style/TextInputLayout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <com.google.android.material.textfield.TextInputEditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</xxx.widgets.TextInputLayout>
```

Final result:
![image](https://user-images.githubusercontent.com/10567243/116012455-deb25b00-a62a-11eb-9107-cbae7da88d94.png)
![image](https://user-images.githubusercontent.com/10567243/116011582-22569600-a626-11eb-896a-3c8992196b81.png)

**Comment by thebestpol** [comment]
I based my solution on @Dona278's one but to cover all scenarios I recommend to override function **addView** in order to cover the case if the character counter functionality is enabled or not. Digging in the TextInputLayout source code I didn't find any other way.

```
  override fun addView(child: View, index: Int, params: ViewGroup.LayoutParams) {
        super.addView(child, index, params)

        (child as? EditText)?.doAfterTextChanged {
            if (isCounterEnabled) {
                if (it != null && it.length > counterMaxLength) {
                    editText?.setBackgroundResource(R.drawable.text_input_background_error)
                }
            }
        }
    }
````

Thanks you!

**Comment by AndroidLab** [comment]
You can use my solution https://github.com/AndroidLab/InputLayoutInnerHint
