### ISSUE TITLE
[TextInputLayout] Property boxBackgroundColor not change correctly

### ISSUE THREAD

**Issue by joaoeudes7** [material-components/material-components-android#1191]
**Description:** 
Changing the component's property does not have the expected behavior

**Source code:** ` container_odd.boxBackgroundColor = ContextCompat.getColor(requireContext(), color)`

**Android API version:** 29

**Material Library version:** 'com.google.android.material:material:1.2.0-alpha05'

**Device:** Mi 8

**Comment by leticiarossi** [comment]
can you provide your source code and screenshots of what you're getting and what you'd expect to get?

**Comment by joaoeudes7** [comment]
Sorry I'm late!

```kotlin
fun changeColorLayoutInputOdd(context: Context, oddInputLayout: TextInputLayout, typeBet: Bet.TypeBet) {
    val color = when (typeBet) {
        Bet.TypeBet.LAY -> ContextCompat.getColor(context, R.color.lay)
        Bet.TypeBet.BACK -> ContextCompat.getColor(context, R.color.back)
    }

    oddInputLayout.boxBackgroundColor = color
}

edt_odd.setOnLongClickListener {
    item.changeTypeBet()
    changeColorLayoutInputOdd(context, container_odd, item.typeBet)

    return@setOnLongClickListener true
}
```

Bug running:
https://www.youtube.com/watch?v=bzs-nxDNcD4

Expects:
https://www.youtube.com/watch?v=2mQ23uuNIr0

**Comment by joaoeudes7** [comment]
Thanks!! :)
