### ISSUE TITLE
TextInputLayout - Null Pointer Exception on setBoxCornerRadii

### ISSUE THREAD

**Issue by HoseinHaqiqian** [material-components/material-components-android#1192]
**Description:** 
In Version : 1.1.0 
calling 
textInputLayout.setBoxCornerRadii(radius, radius, radius, radius);
before 
textInputLayout.addView(editText); causing Null Pointer Exception 
because of boxBackground is null.
in 1.0.0 Version All Works Fine.

**Comment by leticiarossi** [comment]
Why do you need to call `textInputLayout.setBoxCornerRadii` before `textInputLayout.addView`?
The text field uses the edit text's background for its background, so the corner radii will be applied to it.
