### ISSUE TITLE
[MaterialButtonToggleGroup] margins of buttons have no effect

### ISSUE THREAD

**Issue by dstudiocontent** [material-components/material-components-android#1196]

**Comment by dstudiocontent** [comment]
MaterialButton doesn't seperating even after adding margin to it

**Comment by wcshi** [comment]
The Material Design spec does not provide guidance on toggle buttons with padding. 

https://material.io/components/buttons#toggle-button

could you please explain your use case?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with more details.
