### ISSUE TITLE
TabLayout start offset in RTL direction

### ISSUE THREAD

**Issue by ahmaducg** [material-components/material-components-android#1197]
**Description:** The TabLayout starts with a bit of offset from the first item.

![image](https://user-images.githubusercontent.com/45195295/78871573-94c2fb00-7a50-11ea-9e5b-cd242b06f8b0.png)

**Android API version:** 29

**Material Library version:** 1.1.0

**Device:** Emulator

**Comment by hunterstich** [comment]
Hey thanks for filing a bug. Do you mind including a small sample that reproduces this?

**Comment by ahmaducg** [comment]
This is not reoccurring in a new project. Even though this occurred twice for me before, even before ViewPager2 and 1.1.0

**Comment by drchen** [comment]
Given this is not happening anymore and it's a bit old, I'll close the issue for now. Feel free to reopen it if this is still happening.
