### ISSUE TITLE
[CollapsingToolbarLayout] A title without space isn't displayed correctly

### ISSUE THREAD

**Issue by esnaultdev** [material-components/material-components-android#1201]
**Description:**
![Screenshot_1586525028_small](https://user-images.githubusercontent.com/7100677/78994543-51b17680-7b7b-11ea-92b0-5868ff08c006.png)

Using a title without spaces in a CollapsingToolbarLayout results in the text being laid out below the last line.

**Expected behavior:**
The title should break as it does in the screenshot, but all the lines should be displayed properly. Since the title gravity is bottom and the maxLines 3, in this example two lines should be displayed.

**Source code:**
Using the catalog source code:
Updating `cat_topappbar_collapsing_multiline_fragment.xml` to have bigger margins on the `CollapsingToolbarLayout`:
```
app:expandedTitleMarginStart="72dp"
app:expandedTitleMarginEnd="56dp"
```

Updating the `cat_topappbar_collapsing_multiline_demo_toolbar_title` string value to "Thisisalongtitlewithoutspace".

Resulting files:

`catalog/java/io/material/catalog/topappbar/res/layout/cat_topappbar_collapsing_multiline_fragment.xml`
```
...
<com.google.android.material.appbar.CollapsingToolbarLayout
      android:id="@+id/collapsingtoolbarlayout"
      style="?attr/catalogToolbarStyle"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:collapsedTitleTextAppearance="?attr/textAppearanceHeadline6"
      app:expandedTitleGravity="bottom"
      app:expandedTitleMarginBottom="24dp"
      app:expandedTitleMarginStart="72dp"
      app:expandedTitleMarginEnd="56dp"
      app:expandedTitleTextAppearance="?attr/textAppearanceHeadline5"
      app:maxLines="3"
      app:layout_scrollFlags="scroll|exitUntilCollapsed|snap">
...
 ```

`catalog/java/io/material/catalog/topappbar/res/values/strings.xml`
```
...
<string name="cat_topappbar_collapsing_multiline_demo_toolbar_title" description="Long title [CHAR_LIMIT=NONE]">Thisisalongtitlewithoutspace</string>
...
```

**Android API version:** API 29

**Material Library version:** 1.2.0-alpha05

**Device:** Android Emulator - Pixel 3

**Comment by drchen** [comment]
Looks like it's been fixed.
