### ISSUE TITLE
[MaterialDatePicker] Date range pickers with time start and end

### ISSUE THREAD

**Issue by Angelk90** [material-components/material-components-android#1202]
**Is your feature request related to a problem? Please describe.**

Going in the official documentation on the material design of the Date Picker component for the selection of a range of dates, i.e. start date and end date, I found the following reference on how everything should be.
But I am not able to find an example of range date pickers with time start and end event in the official documentation.

There is no such example, how one should act accordingly.

@ymarian, @cketcham, @dsn5ft: 
![](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1584058305895%2Fassets%2F1RfERhlpCPjmRWnHffpdVZV0Fy22zTU7H%2Fpicker-date-range-redline.png)

**Comment by wcshi** [comment]
Have you taken a look at the picker demo in the catalog app?

**Comment by Angelk90** [comment]
@wcshi  : could you tell me exactly where?

**Comment by wcshi** [comment]
IIUC, you are looking for the date range picker example in the picker demo. 
Open the Catalog app > Pickers > DatePickerMainDemoFragment
Choose "Date Range" under selection mode and switch to the calendar picker via by clicking on the calendar icon to the right of "End date"

**Comment by dsn5ft** [comment]
Code is located here:

https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/datepicker/DatePickerMainDemoFragment.java

**Comment by Angelk90** [comment]
@wcshi , @dsn5ft : You could post a screen?

**Comment by wcshi** [comment]
@Angelk90 Did you try the demo following the instructions I provided or look at the code linked by @dsn5ft?

**Comment by Angelk90** [comment]
@wcshi , @dsn5ft : I downloaded the repo, I was able to try the projects inside:
catalog and demos-java-io-material-demo-shire, but within these two projects that I have carried out inside my device, I find no example to try inside my device.

so how do i try the range picker calendar with time.

What steps should I take?

**Comment by wcshi** [comment]
I don't understand your confusion.
@Angelk90 Did you follow these steps using the catalog app?
https://github.com/material-components/material-components-android/issues/1202#issuecomment-615233704

**Comment by Angelk90** [comment]
@wcshi : Ok, I managed to find the Pickers inside the demo app, but I don't find a way to enable time, I only find DatePickerMainFragment.

**Comment by wcshi** [comment]
MaterialDatePicker only supports picking dates, not time. Time picker is under development.

**Comment by Angelk90** [comment]
@wcshi : What I speak at the beginning of the issues is if there is a date range picker with timer, therefore the possibility of being able to select a start and end date and also specifying the start time and the end time.
