### ISSUE TITLE
[Slider] For range slider, get min and max value and max thumb should not overlap min thumb

### ISSUE THREAD

**Issue by bhavyahmehta** [material-components/material-components-android#1205]
Problem:
I am developing slider to select price range between min and max value.The problem is from current slider component I did not separate value of two thumbs to show user min and max value.
Also one thumb overlaps other one, I want like max and min value range selection thumbs should not overlap each other.

Any suggestions to solve this problem will be appreciated.

**Comment by wcshi** [comment]
What do you mean " I did not separate value of two thumbs to show user min and max value."?

Could you please share a screenshot that shows the behavior you are reporting? thanks

**Comment by ymarian** [comment]
https://github.com/material-components/material-components-android/commit/b8f4b221f45a876c57205acc143aee484af3e868
