### ISSUE TITLE
[EditText] Monospace documentation with passwords

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android#1206]
I was looking at the documentation for dialogs on the Android page https://developer.android.com/guide/topics/ui/dialogs and I noticed this line

>Tip: By default, when you set an EditText element to use the "textPassword" input type, the font family is set to monospace, so you should change its font family to "sans-serif" so that both text fields use a matching font style.

I was wondering if this is still true for material. If so, should that be added to the docs for mdc android?

**Comment by leticiarossi** [comment]
I don't think that's necessary since by default we set the `TextInputEditText`'s text appearance in its styles https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/values/styles.xml#L177
