### ISSUE TITLE
[TextInputLayout] Material design is not working for hint /background selectors 

### ISSUE THREAD

**Issue by AtifAbbAsi19** [material-components/material-components-android#1207]
I was using Material design 1.1.0 .

For tabs with viewpager2 I updated it to '1.2.0-alpha05' Material library version it was working fine for single module but was crashing for another module where I've developed my custom material designed TextInputLayout. I changed theme from 'Theme.AppCompat.Light.NoActionBar' to Theme.MaterialComponents.Light.NoActionBar and crash fixed. After fixing crash and upgrading theme it is showing me white floating label , buttons , indiators etc.

old file had conflict with material while using `AppCompact `with `parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"` after updating to `1.2.0-alpha05` it was resolved but style background is not working now.

```

 <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/textInputLayout"
        style="@style/contentInputLayoutStyle"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/_8dp"
        android:paddingStart="5dp"
        android:paddingLeft="5dp"
        app:helperTextEnabled="true"
        android:layout_marginLeft="@dimen/_8dp"
        android:layout_marginEnd="@dimen/_8dp"
        android:layout_marginRight="@dimen/_8dp"
        app:errorEnabled="false"
        app:layout_constraintBottom_toTopOf="@+id/errorTextView"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:hint="@string/EnterMobileNumber">


        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/textInputEditText"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="phone"
            android:gravity="start"
            android:textDirection="anyRtl"
            tools:text="0335510023"
            android:background="@null"
            android:paddingEnd="@dimen/inputFieldPadding_36dp"
            android:paddingRight="@dimen/inputFieldPadding_36dp" />

    </com.google.android.material.textfield.TextInputLayout>

style.xml

<style>
   <!-- your app branding color for the app bar -->
    <item name="colorPrimary">@color/white</item>

    <!-- darker variant for the status bar and contextual app bars -->
    <item name="colorPrimaryDark">@color/colorPrimary_New</item>

    <!-- theme UI controls like checkboxes and text fields also known as secondary color -->
    <item name="colorAccent">@color/a465661</item>
</style>

<style name="AppTheme"  parent="Theme.MaterialComponents.Light.NoActionBar" >
            <!-- Customize your theme here. -->
            <item name="colorPrimary">@color/white</item>
            <item name="colorPrimaryDark">@color/green</item>
            <item name="colorAccent">@color/a465661</item>
        </style>

 <style name="contentInputLayoutStyle" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense">
        <item name="boxStrokeColor">@color/border_stroke_grey</item>
        <item name="android:textColor">@color/black</item>
        <item name="android:textStyle">normal</item>
        <item name="errorTextAppearance">@style/error_label</item>
        <item name="counterOverflowTextAppearance">@style/AppTheme.TextFloatLabelAppearance</item>
        <item name="android:actionOverflowButtonStyle">@style/AppTheme.TextFloatLabelAppearance
        </item>
        <item name="hintTextAppearance">@style/text_label</item>
    </style>

 <style name="text_label" parent="TextAppearance.Design.Hint">
        <item name="android:textSize">@dimen/title_heading_12sp</item>
        <item name="colorControlNormal">@color/black</item>
        <item name="colorControlActivated">@color/black</item>
        <item name="colorControlHighlight">@color/black</item>
    </style>

    <style name="text_label_green" parent="TextAppearance.Design.Hint">
        <item name="android:textSize">@dimen/title_heading_12sp</item>
        <item name="colorControlNormal">@color/green_field</item>
        <item name="android:background">@null</item>
        <item name="colorControlActivated">@color/green_field</item>
        <item name="colorControlHighlight">@color/green_field</item>
    </style>

    <style name="AppTheme.TextFloatLabelAppearance" parent="text_label">
        <!-- Floating label appearance here -->
        <item name="android:textColor">@color/label_title_black</item>
        <item name="android:textSize">@dimen/title_heading_12sp</item>
        <item name="android:background">@android:color/transparent</item>
        <item name="colorControlNormal">@color/label_title_black</item>
        <item name="colorControlHighlight">@color/label_title_black</item>
        <item name="colorControlActivated">@color/label_title_black</item>

    </style>

  <style name="material_edit_text" parent="Widget.AppCompat.EditText">
        <item name="android:paddingStart">50dp</item>
        <item name="android:paddingLeft">50dp</item>
        <item name="android:background">@null</item>
        <item name="android:textSize">16sp</item>
    </style>

    <style name="error_label" parent="TextAppearance.Design.Hint">
        <item name="android:textSize">0sp</item>
        <item name="android:textColor">@color/red</item>
        <item name="android:visibility">gone</item>
    </style>

  <style name="BtnCustomStyle">
        <item name="android:background">@drawable/btn_confirm_selector</item>
        <item name="android:textColor">@android:color/white</item>
        <item name="android:textSize">15dp</item>
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">46dp</item>
        <item name="android:layout_marginStart">10dp</item>
        <item name="android:layout_marginEnd">10dp</item>
        <item name="android:textAllCaps">false</item>
        <item name="android:foreground">android:attr/selectableItemBackground</item>
    </style>

```
![de4c1](https://user-images.githubusercontent.com/9381006/79140899-2aa0b200-7dd2-11ea-8b19-190bb0bd2786.png)

**Comment by leticiarossi** [comment]
The image you uploaded it not showing, could you fix it? I'm not sure what you mean by style background not working.

The reason you had white color for a bunch of things when you updated your theme is because your `colorPrimary` is set to `@color/white`, and those elements you mentioned all derive their color from `colorPrimary`.  I suggest you take a look at the [theming section of the text fields doc](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#theming-text-fields) to see a more detailed example of theming. 

If you want your `colorPrimary` to be different for text fields, for example, in your `contentInputLayoutStyle` style you should set `materialThemeOverlay` to a custom `ThemeOverlay` where you can set `colorPrimary` there and other theme attributes, including setting `editTextStyle` to your `material_edit_text` style (which you probably want it to extend from `Widget.MaterialComponents.TextInputEditText.OutlinedBox.Dense` instead of `Widget.AppCompat.EditText` as you have now).

**Comment by AtifAbbAsi19** [comment]
I have posted this question on stackoverflow few days back. You jave have a look at it. or else I can update Picture here too.but why its working fine with `<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">` and when I change it to `<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">`
button selector stop working , floating label turns white.
https://stackoverflow.com/questions/60850751/switching-to-material-theme-from-app-compact-shows-white-blank-labels-buttons

**Comment by leticiarossi** [comment]
Your colors changed because you changed your theme from an AppCompat one to a MaterialComponents one. The same thing would happen if you were using 1.1.0

You'll want to change the theme color attrs in your theme to adjust the components' colors (like colorPrimary, colorOnPrimary, colorSurface, etc). Take a look at this [themes section of our getting started doc](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#4-change-your-app-theme-to-inherit-from-a-material-components-theme).

**Comment by AtifAbbAsi19** [comment]
@leticiarossi  but after updating to latest it crash using `Theme.AppCompat.Light.NoActionBar` to fix it I switched to MaterialComponent. it should work fine even after updating library right.?

**Comment by AtifAbbAsi19** [comment]
"Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense" this line is causing crashed using Theme.AppCompat.Light.NoActionBar

**Comment by wcshi** [comment]
@AtifAbbAsi19 could you post a stacktrace and verify if using a MaterialComponents theme fixes the crash?

**Comment by AtifAbbAsi19** [comment]
```
<com.google.android.material.textfield.TextInputLayout
        android:id="@+id/textInputLayout"
        style="@style/contentInputLayoutStyle">
```
actually the problem is with style , while using appCompact theme it crashes and switching whole app theme  to `<style name="AppTheme"  parent="Theme.MaterialComponents.Light.NoActionBar" >` fixes the crash .. but again it changes background, TextLabel colors to white making them invisible  , and Background style for buttons..
@wcshi

**Comment by vellrya** [comment]
+1, to repeat the bug just update material library from 1.0.0 to 1.1.0, change styles from Theme.AppCompat to Theme.MaterialComponents and all buttons with background properties started to display incorrect colors. I take it that the attribute is ignored and instead primaryColor from the theme is used.

**Comment by FlavioMarcondes** [comment]
Same problem here, already updated to "1.2.0-beta01" and android:background still not working, always get the primaryColor. Tried to use a @drawable/btn_orange, @color/white, "#000", nothing works! @leticiarossi: Ajuda nóis rs, pelo menos uma previsãozinha pra saber se devo ir por outro caminho.

**Comment by milan-codes** [comment]
Still hasn't been fixed, could anyone come up with a temporary solution?

**Comment by drchen** [comment]
Is this still an issue?

**Comment by muhammadatifarif** [comment]
yes it is still happening what I did is updated the widget theme check stack updated post

**Comment by drchen** [comment]
Will you be able to update your theme/styles to Material3? I strongly recommend you use the same Material version for both your theme and style (say, Material 3 + Material 3) or their might be some unexpected hiccups in colors or layouts.
