### ISSUE TITLE
[MaterialCardView] Add EdgeTreatment hides MaterialCardView

### ISSUE THREAD

**Issue by m4rcl** [material-components/material-components-android#1208]
**Description:** I use the MaterialCardView and set the ShapeAppearanceModel with an EdgeTreatment. After that the View is not shown. 

**Expected behavior:** The MaterialCardView is shown with the EdgeTreatment.

**Source code:** Here is an example project. https://github.com/m4rcl/MaterialTicketView

**Material Library version:** 
- not working for verion higher than 1.1.0-alpha10

**Comment by ymarian** [comment]
See https://github.com/material-components/material-components-android/issues/594 
for a workaround. We'll try to get a fix for next release.

**Comment by m4rcl** [comment]
The issue #594 is not the same. It is regarding the content of the MaterialCardView. 

The issue here is about the Card itself. 

 Behaviour at 1.1.0-alpha10 
![example](https://user-images.githubusercontent.com/1965605/79303644-ac3a3200-7eef-11ea-9b0c-0b5ee3f7230c.JPG)

 Behaviour at version higher than 1.1.0-alpha10 
![example2](https://user-images.githubusercontent.com/1965605/79303666-beb46b80-7eef-11ea-8dfd-8f44f3bc0d08.JPG)

**Comment by ymarian** [comment]
Did you try the workaround?

`ticketView.setClipToOutline(false);`

**Comment by wcshi** [comment]
We cannot reproduce the issue with your sample app.

**Comment by m4rcl** [comment]
in the sample app i use the wokring version 1.1.0-alpha10 
did you try it with an newer version?
