### ISSUE TITLE
[MaterialDatePicker] How to change language in Mobile date input picker

### ISSUE THREAD

**Issue by holoc285** [material-components/material-components-android#1216]
I want to change the language When the user click in button input mode, like this

Can anyone help me? Thanks in advance
 
![Screenshot_1587051051](https://user-images.githubusercontent.com/38504232/79475811-62a63000-8032-11ea-8c6f-9cb54cadb2e2.png)

**Comment by dsn5ft** [comment]
Hi @holoc285, you can localize the strings for things like hint and error text by following the suggestions in https://github.com/material-components/material-components-android/issues/761. Please let us know if there is more that you would like to change.

**Comment by mays123** [comment]
@dsn5ft how about the language of the months and week days?

**Comment by holoc285** [comment]
thanks @dsn5ft I resolved it.

**Comment by basmasrour** [comment]
> @dsn5ft how about the language of the months and week days?

How did you translate the months names?

**Comment by Avishek1989** [comment]
@dsn5ft hey how do I translate the Month names?
