### ISSUE TITLE
BottomAppBar is too small in support library

### ISSUE THREAD

**Issue by kptlronyttcna** [material-components/material-components-android#122]
BottomAppBar is too small when I use the support library but looks fine with the com.google.... version.

This is how it looks from the support library.
https://imgur.com/a/EeRgU2H

This is how it looks with the com.google... repository
https://imgur.com/a/udrT0re

**Comment by HiroyukTamura** [comment]
set style to BottomAppBar : 
`style="@style/Widget.MaterialComponents.BottomAppBar"`

**Comment by cketcham** [comment]
Are you using the theme in both cases? That should automatically apply the style which should set the height.
