### ISSUE TITLE
[Chip] Unexpected additional small border when using stroke color

### ISSUE THREAD

**Issue by AOrobator** [material-components/material-components-android#1220]
**Description:** 

When using a white stroke color for a Chip, I see an additional darker outline of the chip's background color. 

![Screenshot_1587140086](https://user-images.githubusercontent.com/4106884/79606219-40a6bf00-80bf-11ea-8723-b894b22f8199.png)

**Expected behavior:** Screenshots and/or description of expected behavior

![Screenshot_1587152935](https://user-images.githubusercontent.com/4106884/79608462-0fc88900-80c3-11ea-8d3a-decd4d4e6415.png)
The desired effect contains no thin ring around the whitespace in order to make it appear as if there is a cutout in the square.

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

```xml
  <com.google.android.material.chip.Chip
    android:id="@+id/badge"
    android:layout_width="wrap_content"
    android:layout_height="48dp"
    android:layout_marginStart="16dp"
    android:layout_marginBottom="16dp"
    android:clickable="false"
    android:elevation="10dp"
    android:enabled="false"
    android:focusable="false"
    android:outlineProvider="none"
    android:scaleX=".6"
    android:scaleY=".6"
    android:textColor="@color/white"
    android:textSize="12sp"
    app:layout_constraintBottom_toBottomOf="@id/imageView"
    app:layout_constraintStart_toStartOf="@id/imageView" />

```

**Android API version:** 29

**Material Library version:** 1.2.0-alpha06

**Device:** Emulator, Google Pixel 3 XL

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by wcshi** [comment]
Do you have a custom default chip style set in your theme? That code snippet does not render the chip in your screenshot. e.g. chip is not black nor does it have a stroke.

**Comment by AOrobator** [comment]
I'm using another view to simulate a stroke so I'm closing this out
