### ISSUE TITLE
[Bottom Sheet] Not showing under navigation bar in edge to edge UI mode

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android#1222]
**Description:** I have the newest MDC. I set my UI to edge to edge as per Chris Banes' Going edge to edge guide (I actually use his Insetter library on github) and set my navigation bar to transparent. This makes my app look cool, but the bottom sheet looks sooo bad.

Maybe I'm just setting it up incorrectly? Would love some help since drawing under the navigation bar according to android dev summit 2019 is a recommended practice.

Reproducible in another project here where I use a bottom sheet. https://github.com/ColtonIdle/NavDrawerIssue

**Comment by ColtonIdle** [comment]
I also just tried the sample app in this repo and it also has the same issue. =)

**Comment by ColtonIdle** [comment]
@dsn5ft @melaniegoetz is there any workaround for the time being? This is really killin my design team.

**Comment by ColtonIdle** [comment]
"@ColtonIdle ColtonIdle unassigned melaniegoetz 18 minutes ago"

I did not unassign anyone? idk why that appeared

**Comment by Hal1ucinogen** [comment]
Same issue

**Comment by ColtonIdle** [comment]
@wcshi this issue was closed, but I don't see it in the release notes. Was it missed, or did it just not make the release in time?

**Comment by wcshi** [comment]
This fix was not included in the 1.3.0-alpha04 release

**Comment by wcshi** [comment]
If you are interested in trying to fix, please consider using our daily snapshots: https://github.com/material-components/material-components-android/blob/dc1a7fb7c19d84eb2b91a8b9331489a4623dae29/docs/using-snapshot-version.md

**Comment by b95505017** [comment]
Any reason not included in `1.3.0-rc01`?  Which version it will be included?
