### ISSUE TITLE
[ShapeableImageView] Issues when extending from ShapeableImageView

### ISSUE THREAD

**Issue by jahirfiquitiva** [material-components/material-components-android#1223]
**Description:** 
I am currently using a custom ImageView to make images have the same height based on its width, to make them look taller than wider.

When I extend from ShapeableImageView, the corners are set from the drawable height instead of the view height, or something like that. Basically, set incorrectly.

This is how it looks: It's the ImageView inside a CardView. The cyan comes from the `cardBackgroundColor`

![Screenshot_1587230501](https://user-images.githubusercontent.com/10360816/79644558-596ead80-816f-11ea-8155-91741daaea29.png)

This is my current implementation which works fine if I extend from `ImageView`

```kotlin
open class PortraitImageView @JvmOverloads constructor(
    context: Context,
    attributeSet: AttributeSet? = null,
    style: Int = 0
) : ImageView(context, attributeSet, style) {

    private var heightMultiplier: Float = 1.25F

    init {
        init(context, attributeSet)
    }

    private fun init(context: Context, attributeSet: AttributeSet?) {
        val a = context.obtainStyledAttributes(attributeSet, R.styleable.PortraitImageView, 0, 0)
        try {
            heightMultiplier = a.getFloat(R.styleable.PortraitImageView_heightMultiplier, 1.25F)
        } finally {
            a.recycle()
        }
    }

    override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec)
        setMeasuredDimension(measuredWidth, (measuredWidth * heightMultiplier).toInt())
    }
}
```

**Expected behavior:** 

The corners set properly after calling `setMeasuredDimension`:

![Screenshot_1587230435](https://user-images.githubusercontent.com/10360816/79644582-83c06b00-816f-11ea-841a-01e7c2c4267d.png)

**Source code:** 
The same as above, just that instead of extending from `ImageView`, it'd extend from `ShapeableImageView`

**Android API version:** 29

**Material Library version:** 1.2.0-alpha06

**Device:** Pixel 3a

**Comment by ymarian** [comment]
Thanks I didn't think about that. I changed the logic to be onSizeChanged which is called during layout so you shouldn't have problems after a new release.
