### ISSUE TITLE
[TextInputLayout] boxBackgroundColor not changing with state

### ISSUE THREAD

**Issue by travismmorgan** [material-components/material-components-android#1228]
**Description:** When setting boxBackgroundColor to use a selector, the color does not change when state is changed

**Expected behavior:** boxBackgroundColor should change with state changes when using a selector

**Source code:** "<item name="boxBackgroundColor">@drawable/background_edittext_contained</item>"

"<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_focused="true" android:color="@color/colorFieldVariant"/>
    <item android:state_enabled="false" android:color="@android:color/transparent"/>
    <item android:color="@color/colorField"/>
</selector>"

**Android API version:** 24

**Material Library version:** 1.1.0

**Device:** Pixel 3

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
I'm not able to reproduce your issue, can you test it using our latest alpha release 1.2.0-alpha06?
Are you using the FilledBox text field style? If the issue still persists can you provide more of your source code and screenshots of what you're getting/what you expect?

**Comment by travismmorgan** [comment]
@leticiarossi confirmed this is fixed in 1.2.0.
