### ISSUE TITLE
[TextInputLayout] setErrorIconVisible(true) is not called

### ISSUE THREAD

**Issue by teemuSoInno** [material-components/material-components-android#1232]
**Description:** TextInputLayout.setErrorIconVisible(true) is never called if errorIconDrawable is set from .xml, resulting in custom error icon not showing. 

The error icon is only visible if it's explicitly set via setErrorIconDrawable after TextInputLayout.setError("text here") is called, and then set to null after TextInputLayout.setError(null) is set.

**Expected behavior:** TextInputLayout.setErrorIconVisible(true) is never called, because textInputView.updateEditTextBackground() can't be accessed when IndicatorViewController.setErrorEnabled(true) is called (displaying error).

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue. 

Style as

`<style name="TextInputLayoutAppearance" parent="Widget.Design.TextInputLayout">
        <item name="errorTextAppearance">@style/ErrorTextAppearance</item>
</style>`

Assignment
`
<com.google.android.material.textfield.TextInputLayout
        style="@style/TextInputLayoutAppearance"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="40dp"
        android:layout_marginTop="20dp"
        android:layout_marginEnd="40dp"
        app:errorEnabled="true"
        app:errorIconDrawable="@drawable/text_field_error_icon">
`

Later error is enabled with
`
emailInputLayout.error = "error"
`

**Android API version:** 28

**Material Library version:** 1.2.0-alpha06

**Device:** Nexus S

**Comment by leticiarossi** [comment]
Hi, I see your style extends from `Widget.Design.TextInputLayout` which is our legacy style and because of that doesn't have support for all text field features that the `*.OutlinedBox` and `*.FilledBox` styles have (those two are what `TextInputLayout` expects).
If you switch to any of those, setting an error icon via xml should work as expected, so will close this as WAI.
