### ISSUE TITLE
[TextInputLayout] suffixText and text gravity. 

### ISSUE THREAD

**Issue by Zeliret** [material-components/material-components-android#1244]
Hi there!
I have a question about suffix text. 
I tried to set gravity to end to achieve behaviour like here https://material.io/components/text-fields#filled-text-field when your text aligned to the right and there is a suffix after that (example with email address). But the problem is that the hint label gets aligned to the right as well. But the example says it should not.

**Comment by dsn5ft** [comment]
Hi @Zeliret, can you attach screenshots of the behavior you're seeing, as well as the specific behavior from the spec that you're trying to achieve. The link isn't specific enough.

Also, please provide code snippets so we know exactly which APIs you are using.

**Comment by gabrielemariotti** [comment]
@Zeliret 
You can find an example in the catalog:

<img width="304" alt="Schermata 2020-08-26 alle 17 55 15" src="https://user-images.githubusercontent.com/2583078/91327016-4e82f400-e7c5-11ea-8a9d-308bc6fb2a5b.png">

Just use something like:

```
 <com.google.android.material.textfield.TextInputLayout
      app:suffixText="@string/cat_textfield_suffix">

    <com.google.android.material.textfield.TextInputEditText
        android:textAlignment="textEnd"/>

  </com.google.android.material.textfield.TextInputLayout>
```

**Comment by leticiarossi** [comment]
The above suggestion should be what you want to achieve end text alignment

**Comment by SpinnerWebs** [comment]
Same problem as @Zeliret. I'm trying to format a box similar to the screenshot by @gabrielemariotti (though as an outlined box), but setting android:textAlignment="textEnd" doesn't appear to have any effect. If I use android:gravity="end" instead, it aligns the label as well as the contents, which is even less desirable. Target SDK version 29, testing on a Pixel 5 API 30 emulator.
