### ISSUE TITLE
[Badge drawable] badge drawable recreated when activity state is restored

### ISSUE THREAD

**Issue by susonthapa** [material-components/material-components-android#1247]
In my app I use bottom navigation with badge, and in onCreate() of the activity I initialize the badge with this code
```kotlin       
        val chatBadge = binding.bottomNav.getOrCreateBadge(R.id.recent_private_message)
        chatBadge.maxCharacterCount = 2
        chatBadge.badgeTextColor = ContextCompat.getColor(this, R.color.white)
        chatBadge.backgroundColor = ContextCompat.getColor(this, R.color.primaryColor)
```
When there is no notification to show, I follow this material [guildeline](https://material.io/develop/android/components/bottom-navigation-view/) to set the visibility of the badge with this code
```kotlin   
private fun updateBadgeCount(badge: BadgeDrawable, count: Int) {
        if (count == 0) {
            // hide the badge
            badge.isVisible = false
        } else {
            badge.number = count
            badge.isVisible = true
        }
    }
```
Every thing works normal except when I toggle the dark mode in android, which causes the badge to show dots like this
![image](https://user-images.githubusercontent.com/33973551/80297597-4037b380-87a4-11ea-8873-055946d7ab5e.png)

![image](https://user-images.githubusercontent.com/33973551/80297548-ca334c80-87a3-11ea-8d93-1cb9abc9ef10.png)

After some research I found that when the dark mode is turned on, the view is recreated and it's state is restored (I may be wrong here). On debugging the source code, it turns out that [BottomNavigationPresenter](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomnavigation/BottomNavigationPresenter.java) onRestoreInstanceState() creates badges from the saved state. So, there are two badges that I initialize in onCreate() and two badges that the view restores. This  causes the restored badges to show the dots (I hide the visibility of the badges that I create). 
If I use removeBadge() instead of using visibility everything works fine. I don't know if this is the expected behavior or am I missing something in my code. Any help would be appreciated.

**Android API version:** API 29

**Material Library version:** 1.1.0 but the same happened with 1.2.0-alpha04

**Device:** Android emulator

**Comment by wcshi** [comment]
This recent change (https://github.com/material-components/material-components-android/commit/bcb148681b2b5e866e1119dc748e82af12a665a0), which restores the badge's visibility should also fix this issue.
