### ISSUE TITLE
[MaterialComponents Outline Button] Set Stroke Color Programmatically

### ISSUE THREAD

**Issue by QInfro** [material-components/material-components-android#1248]
As of now we can set stroke color of the Material Outline Button in xml only, but we want it set programmatically also, so please provide ability to set stroke color programmatically (for MaterialComponent Outline buttons & MaterialButtonToggleGroup).

**Comment by gabrielemariotti** [comment]
You can use `materialButton.setStrokeColor()`

**Comment by dsn5ft** [comment]
Make sure to cast your `Button` to a `MaterialButton`, then you should be able to use the following methods:

- https://developer.android.com/reference/com/google/android/material/button/MaterialButton#setstrokecolor
- https://developer.android.com/reference/com/google/android/material/button/MaterialButton#setstrokecolorresource
- https://developer.android.com/reference/com/google/android/material/button/MaterialButton#setstrokewidth
- https://developer.android.com/reference/com/google/android/material/button/MaterialButton#setstrokewidthresource
