### ISSUE TITLE
[MaterialAlertDialog] Wrong elevation 

### ISSUE THREAD

**Issue by esm950** [material-components/material-components-android#1255]
**Description:** 
I'm having an issue getting my custom dialog to appear as the same surface color as the MaterialAlertDialog in dark mode and it appears that the MaterialAlertDialog's elevation is set to 16dp instead of 24dp.

I am referencing the official guidelines  [here](https://material.io/components/dialogs) for material design dialog elevation which states that "Dialogs are displayed at 24dp elevation and can display a shadow" but following up the theme inheritance I found that the elevation of MaterialAlertDialog is set at 16dp instead.

The chain of inheritance is as follows:

The default theme overlay defined in `MaterialAlertDialogBuilder` class's `MATERIAL_ALERT_DIALOG_THEME_OVERLAY` constant references and the respective parent
->`@style/ThemeOverlay.MaterialComponents.MaterialAlertDialog`  
->`Base.ThemeOverlay.MaterialComponents.MaterialAlertDialog` 
->`Base.V14.ThemeOverlay.MaterialComponents.MaterialAlertDialog` 
->`ThemeOverlay.AppCompat.Dialog.Alert`
-> `Base.ThemeOverlay.AppCompat.Dialog.Alert` 
->`Base.ThemeOverlay.AppCompat.Dialog` 
->`Base.V21.ThemeOverlay.AppCompat.Dialog` (in API 21 onwards) which defines the item
 `<item name="android:windowElevation">@dimen/abc_floating_window_z</item>`

The `@dimen/abc_floating_window_z` dimension has the value of 16dp which does not align with the material spec, causing custom widget that follows the anatomy of the material spec to have inconsistent shadow in light theme and different alpha values in dark theme. 

`android:windowElevation` attribute should be set in one of the MaterialComponents base style to override the value from appCompat library

**Expected behavior:** 
Alert dialog elevation is set at 24dp

**Android API version:** 
Android 10 (API level 29)

**Material Library version:** 
1.1.0-rc2

**Device:** 
Oneplus 7T Pro

**Comment by drchen** [comment]
I'll close the issue here. Please check more detailed explanation in  https://github.com/material-components/material-components-android/pull/1556
