### ISSUE TITLE
[MaterialButtonToggleGroup] Single visible button corners

### ISSUE THREAD

**Issue by Anigif** [material-components/material-components-android#1259]
**Description:** If a `MaterialButtonToggleGroup` contains more than one button but only one is visible it gets the shape as if was the first button in the group, even though it's the only (visible).

**Expected behavior:** The single visible button should have its original shape.

**Source code:** The issue seems to be happening in `getNewCornerData(...)`, where we don't consider that child views can be gone.

**Material Library version:** Original found in `1.1.0`, but it's also occuring in `1.2.0-alpha06`

**Comment by wcshi** [comment]
Could you please explain your use case? Why are you using a MaterialButtonToggleGroup and only showing one button?

Please provide a minimal app that demonstrates your bug, thanks!

**Comment by Anigif** [comment]
We have an app that has a `RecyclerView`. Each view in the `RecyclerView` has a set of buttons (in a `MaterialButtonToggleGroup`) that is set up with singleSelection, but depending on the row only some (or in some cases only 1) button will be visible. Each row represent a setting and the button-group is a set of sub-settings for that row. In some cases there's however only 1 sub-setting.

**Comment by wcshi** [comment]
Fixed by merging in https://github.com/material-components/material-components-android/pull/1260
