### ISSUE TITLE
BottomAppBar always shows menu items on overflow menu

### ISSUE THREAD

**Issue by firatkarababa** [material-components/material-components-android#126]
`I am using com.google.android.material.bottomappbar.BottomAppBar` with a xml menu file located under res/menu folder with 1 item in it which has `android:showAsAction="always"` attribute. But when I run the app, the bar menu is shown through the overflow. Is this a bug or am I missing something? How can I make bottomAppBar to show menu icons on it?

Here is a screenshot:

![image](https://user-images.githubusercontent.com/14335270/40590584-c579e0d0-6209-11e8-963e-0d7a748ea9c6.png)

**Comment by yornel13** [comment]
same issue, any solution?

**Comment by firatkarababa** [comment]
@dsn5ft any comment?

**Comment by karan26796** [comment]
Instead of android:shows Action, use app:showAsAction and ignore the warning as tools:ignore="AppCompatResource". This is what made it work for me

**Comment by firatkarababa** [comment]
That has worked but I do not think that is the legal way to implement it. Thanks anyway, I could finally place the menu icons on bottomAppBar.

**Comment by karan26796** [comment]
You are what right, but this is the only way I got it to work for me, your initial solution is what is given on Android developers website. But you'll have to Make it work like this until a legal solution comes up

**Comment by cketcham** [comment]
You should be using `app:showAsAction` instead of `android:showAsAction`. The error is a bug in Android Studio caused by the androidx namespacing.

**Comment by firatkarababa** [comment]
thanks @karan26796  @cketcham I think we have found the right solution.
