### ISSUE TITLE
"backgorundColor' attribute from"Badge" styleable conflict with SystemUI attribute "backgroundColor"

### ISSUE THREAD

**Issue by sevenpoul** [material-components/material-components-android#1263]
`**Description:**`  
i library use 1.2.0-alpha06 verison , library compile with SystemUI , it wrong : AAPT：error: dulicate value for resource 'attr/backgroundColor' with config "".

implementation 'com.google.android.material:material:1.2.0-alpha06'

**Expected behavior:** please modify attribute "backgroudColor" to another name or format in "Badge" styleable, ensure it will not conflict with SystemUI attribute "backgroudColor". because we can't modify native attribute.

**Source code:** 
`<declare-styleable name="Badge">
	<attr format="color" name="backgroundColor"/>
	<attr format="color" name="badgeTextColor"/>
</declare-styleable>`
`<declare-styleable name="TonedIcon">
	<attr name="backgroundColor" format="integer" />
	<attr name="fillColor" format="integer" />
	<attr name="singleToneColor" format="integer" />
</declare-styleable>`
[https://android.googlesource.com/platform/frameworks/base/+/master/packages/SystemUI/res/values/attrs.xml](url)

**Android API version:** Android Q

**Material Library version:** 1.2.0-alpha06

**Device:**  android Q machine

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by wcshi** [comment]
This is considered an API change and will need to wait till the next major version to avoid binary imcompatibility.

**Comment by sabinebarrera** [comment]
Relate to **compile error due to resources not being prefixed** #1146

**Comment by drchen** [comment]
Hey I think it's a general issue that we are aware of. As @wcshi said, unfortunately we cannot change it at this moment since it's a released API and we have to live with it until the next major version change.

On the other hand I'm not sure if the original case will actually cause a problem with the latest AAPT version? I'll close the issue for now. Feel free to reopen it if this is still an issue.
