### ISSUE TITLE
[androix Toolbar] A glitch in showing toolbar title text when theme is material themes

### ISSUE THREAD

**Issue by DHosseiny** [material-components/material-components-android#1267]
I set the theme of activity to "Theme.MaterialComponents.Light.DarkActionBar"(or any other **non-bridge** theme) and fontfamily to "press_start_2p"(found in google fonts).
```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="fontFamily">@font/press_start_2p</item>
    </style>
```
Then I created two fragment and both of them has toolbar but titles are different.
When I navigate from first fragment to second there is A glitch in showing toolbar title. This is not happening with "Theme.AppCompat.Light.DarkActionBar" theme and just happens with some fonts not all fonts.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9461116/80858860-8a6fd780-8c71-11ea-9436-3fff5ad63f20.gif)

**Android API version:** Any API version but tested with 23 and 28

**Material Library version:** 1.1.0
**Device:** pixel 2 xl emulator and Samsung galaxy s6 real device

**Comment by drchen** [comment]
Is this still happening with the latest library version?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
