### ISSUE TITLE
Curved expanding motion

### ISSUE THREAD

**Issue by csaq7151** [material-components/material-components-android#127]
Hi,

I wanted to achive this behaviour (opening the shopping cart layout from a bottom sheet with an arc motion to show the full layout)
[here under the section SHOPPING CART] (https://material.io/design/material-studies/shrine.html#product-architecture)

Any ideas how to do it?

I searched the last days on every possible site on google but there is no real code example how to make such a layout and behaviour.

**Comment by NickM-27** [comment]
Maybe you could achieve this using two fragments and a custom fragment transition?

**Comment by csaq7151** [comment]
I was able to "solve" it by setting the layoutParams of the bottomsheet from wrap_content to match parent onClick on the shoppingCart icon. But it is expanding linear and not as arc. I´m ok with that solution until I find a better way. 

@NickM-27 I cannot use a fragment because it is not possible to place it in the bottom right corner like in the example shown above.

**Comment by vipulasri** [comment]
@csaq7151 You can check this https://github.com/material-components/material-components-android-examples/tree/develop/Owl

**Comment by hunterstich** [comment]
@vipulasri Thanks for adding that link.

@csaq7151 Owl, the Material study sample app, is doing something similar by using a bottom sheet and setting the sheet's translationX whenever the sheet's slide offset is changed - https://github.com/material-components/material-components-android-examples/blob/develop/Owl/app/src/main/java/com/materialstudies/owl/ui/lessons/LessonsSheetFragment.kt#L129. Hopefully that helps get you started.
