### ISSUE TITLE
[BottomSheetDialog] Rounded corners in expanded state

### ISSUE THREAD

**Issue by dostalleos** [material-components/material-components-android#1278]
**Description:** `BottomSheetDialog` has rounded corers only if it's not expanded. Corners are rounded as it's specified in the `ShapeAppearance` during swipe or in collapsed state. Once `BottomSheetDialog` becomes expanded, rounded corners are animated to sharp corners.

**Expected behavior:** Rounded corners should not change in expanded state if expanded state is not full screen. It would be great to have ability to disable this behavior at least.

**Source code:** 
```xml
<style name="ThemeOverlay.App.BottomSheetDialog"parent="ThemeOverlay.MaterialComponents.Dialog">
	<item name="android:windowIsFloating">false</item>
	<item name="android:windowBackground">@android:color/transparent</item>
	<item name="android:windowAnimationStyle">@style/Animation.MyTheme.BottomSheet.Modal</item>
	<item name="android:statusBarColor">@android:color/transparent</item>
	<item name="bottomSheetStyle">@style/Widget.App.BottomSheet.Modal</item>
	<item name="android:navigationBarColor">?colorSurface</item>
	<item name="android:navigationBarDividerColor" tools:ignore="NewApi">@android:color/transparent</item>
	<item name="android:windowLightStatusBar" tools:ignore="NewApi">false</item>
</style>

<style name="Widget.App.BottomSheet.Modal" parent="Widget.MaterialComponents.BottomSheet.Modal">
	<item name="shapeAppearanceOverlay">@style/ShapeAppearance.App.BottomSheet</item>
</style>

<style name="ShapeAppearance.App.BottomSheet" parent="ShapeAppearance.MaterialComponents.LargeComponent">
	<item name="cornerFamily">rounded</item>
	<item name="cornerSizeTopLeft">16dp</item>
	<item name="cornerSizeTopRight">16dp</item>
	<item name="cornerSizeBottomLeft">0dp</item>
	<item name="cornerSizeBottomRight">0dp</item>
</style>
```

**Android API version:** 29

**Material Library version:** 1.2.0-alpha06

**Device:** Pixel 3

**Comment by hrach** [comment]
See comments on #437.

**Comment by wcshi** [comment]
This sounds related to something @melaniegoetz is working on internally/

**Comment by jimmy-tap** [comment]
@wcshi @melaniegoetz Please provide us with expected date for solving this issue

**Comment by TonnyL** [comment]
`1.3.0-alpha01` still has this issue 🙁.

**Comment by gabrielemariotti** [comment]
It seems to be an expected behavour.

Check the this [comment](https://github.com/material-components/material-components-android/pull/437#issuecomment-536668983) in PR: #437 

> **Bad news: Our design team is strongly opinionated that rounded corners indicate scrollable content while flat corners indicate that there is no additional content. As such, they do no want us to add this change with fitToContents.**

Also in the [design doc ](https://material.io/design/shape/applying-shape-to-ui.html#baseline-shape-values)there is indication to use flat corners when the bottomsheet is expanded..

<img width="769" alt="Schermata 2020-08-01 alle 23 27 33" src="https://user-images.githubusercontent.com/2583078/89110793-96289100-d44e-11ea-940a-53bbd3051aae.png">

> **Good news: You should be able to fix this for your case by setting up a callback and overriding the shapeAppearance in the expanded state.**

You can find in the PR a solution or you can check this question on SO:
https://stackoverflow.com/questions/43852562/round-corner-for-bottomsheetdialogfragment/57627229#57627229

**Comment by Fishfield** [comment]
I just stumbled upon another solution to keep the rounded corners.  If you just set `cornerSize`, the rounded corners stay as they are when the bottom sheet is expanded. I hope this helps some of you in order to avoid those hacky workarounds

```
<style name="ShapeAppearance.App.LargeComponent" parent="">
	<item name="cornerFamily">rounded</item>
	<item name="cornerSize">@dimen/corner_radius_s</item>
</style>
```

**Comment by thevoiceless** [comment]
@Fishfield Can you share a more complete example? I've tried setting `shapeAppearance` and `shapeAppearanceOverlay` and neither seems to apply when the sheet is expanded like you said.

**Comment by lsuski** [comment]
You can try this:
```
<style name="BottomSheetDialog" parent="@style/ThemeOverlay.MaterialComponents.BottomSheetDialog">
    <item name="bottomSheetStyle">@style/BottomSheet</item>
    <item name="android:colorBackground">@color/white</item>
</style>
<style name="BottomSheet" parent="Widget.MaterialComponents.BottomSheet.Modal">
    <item name="backgroundTint">@android:color/transparent</item>
</style>
```
in bottom sheet layout
```
android:background="@drawable/rounded_top_corners_background"
```
drawable/rounded_top_corners_background :
```

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
   <corners
          android:topLeftRadius="24dp"
          android:topRightRadius="24dp" />
   <solid android:color="?android:attr/colorBackground" />
</shape>
```

in activity/application theme
```
<item name="bottomSheetDialogTheme">@style/BottomSheetDialog</item>

**Comment by Gidde-Abhishek** [comment]
> You can try this:
> 
> ```
> <style name="BottomSheetDialog" parent="@style/ThemeOverlay.MaterialComponents.BottomSheetDialog">
>     <item name="bottomSheetStyle">@style/BottomSheet</item>
>     <item name="android:colorBackground">@color/white</item>
> </style>
> <style name="BottomSheet" parent="Widget.MaterialComponents.BottomSheet.Modal">
>     <item name="backgroundTint">@android:color/transparent</item>
> </style>
> ```
> 
> in bottom sheet layout
> 
> ```
> android:background="@drawable/rounded_top_corners_background"
> ```
> 
> drawable/rounded_top_corners_background :
> 
> ```
> 
> <?xml version="1.0" encoding="utf-8"?>
> <shape xmlns:android="http://schemas.android.com/apk/res/android">
>    <corners
>           android:topLeftRadius="24dp"
>           android:topRightRadius="24dp" />
>    <solid android:color="?android:attr/colorBackground" />
> </shape>
> ```
> 
> in activity/application theme
> 
> ```
> <item name="bottomSheetDialogTheme">@style/BottomSheetDialog</item>
> ```

This worked for me! 8/2021

**Comment by SamYStudiO** [comment]
> You can try this:
> 
> ```
> <style name="BottomSheetDialog" parent="@style/ThemeOverlay.MaterialComponents.BottomSheetDialog">
>     <item name="bottomSheetStyle">@style/BottomSheet</item>
>     <item name="android:colorBackground">@color/white</item>
> </style>
> <style name="BottomSheet" parent="Widget.MaterialComponents.BottomSheet.Modal">
>     <item name="backgroundTint">@android:color/transparent</item>
> </style>
> ```
> 
> in bottom sheet layout
> 
> ```
> android:background="@drawable/rounded_top_corners_background"
> ```
> 
> drawable/rounded_top_corners_background :
> 
> ```
> 
> <?xml version="1.0" encoding="utf-8"?>
> <shape xmlns:android="http://schemas.android.com/apk/res/android">
>    <corners
>           android:topLeftRadius="24dp"
>           android:topRightRadius="24dp" />
>    <solid android:color="?android:attr/colorBackground" />
> </shape>
> ```
> 
> in activity/application theme
> 
> ```
> <item name="bottomSheetDialogTheme">@style/BottomSheetDialog</item>
> ```

Can't make it work with 1.5.0-alpha03; anyone has it working?

**Comment by drchen** [comment]
I'll close the issue since it's WAI according to our designers' opinion and there are solutions for clients to override the behavior. Thank you all for your feedbacks!

**Comment by Devs-97Eats** [comment]
> You can try this:
> 
> ```
> <style name="BottomSheetDialog" parent="@style/ThemeOverlay.MaterialComponents.BottomSheetDialog">
>     <item name="bottomSheetStyle">@style/BottomSheet</item>
>     <item name="android:colorBackground">@color/white</item>
> </style>
> <style name="BottomSheet" parent="Widget.MaterialComponents.BottomSheet.Modal">
>     <item name="backgroundTint">@android:color/transparent</item>
> </style>
> ```
> 
> in bottom sheet layout
> 
> ```
> android:background="@drawable/rounded_top_corners_background"
> ```
> 
> drawable/rounded_top_corners_background :
> 
> ```
> 
> <?xml version="1.0" encoding="utf-8"?>
> <shape xmlns:android="http://schemas.android.com/apk/res/android">
>    <corners
>           android:topLeftRadius="24dp"
>           android:topRightRadius="24dp" />
>    <solid android:color="?android:attr/colorBackground" />
> </shape>
> ```
> 
> in activity/application theme
> 
> ```
> <item name="bottomSheetDialogTheme">@style/BottomSheetDialog</item>
> ```

Your solution worked, you saved my day!

**Comment by jahongir28** [comment]
Try this 
```
class MyBottomSheer: BottomSheetDialogFragment() {

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        disableShapeAnimation()
    }

    @SuppressLint("RestrictedApi", "VisibleForTests")
    private fun disableShapeAnimation() {
        try {
            val dlg = dialog as BottomSheetDialog
            dlg.behavior.disableShapeAnimations()
        } catch (ex: Exception) {
            Log.e("BaseBottomSheet", "disableShapeAnimation Exception:", ex)
        }
    }
}
```

**Comment by drchen** [comment]
FYI since 1.8 rounded corners become a standard design with M3 styles, no matter it's collapsed or expanded. : )

**Comment by genaray** [comment]
Out of curiosity, what needs to be done that the damn bottom sheet actually keeps its rounded corners in expanded state?
Im struggling the whole day with that issue, i have a bottomsheet defined in XML, material design 1.9 and it still flattens them. Are there any files that require a replacement?

Depends...
```
dependencies {

    implementation project(':unityLibrary')
    implementation fileTree(dir: project(':unityLibrary').getProjectDir().toString() + ('\\libs'), include: ['*.jar'])

    implementation 'androidx.core:core-ktx:1.10.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.squareup.picasso:picasso:2.8'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation("com.android.volley:volley:1.2.1")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0")    // Kotlin

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
```

```XML

            <androidx.coordinatorlayout.widget.CoordinatorLayout
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="0.6">

                <FrameLayout
                    android:id="@+id/standard_bottom_sheet"
                    style="@style/Widget.Material3.BetterBottomSheet"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    app:behavior_hideable="false"
                    app:behavior_peekHeight="32dp"
                    app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior">
...
```

```    
<style name="Widget.Material3.BetterBottomSheet" parent="Widget.Material3.BottomSheet">
        <item name="android:elevation">@dimen/m3_bottom_sheet_elevation</item>
        <item name="marginLeftSystemWindowInsets">true</item>
        <item name="marginRightSystemWindowInsets">true</item>
        <item name="paddingBottomSystemWindowInsets">true</item>
        <item name="paddingTopSystemWindowInsets">true</item>
        <item name="paddingLeftSystemWindowInsets">false</item>
        <item name="paddingRightSystemWindowInsets">false</item>
        <item name="shapeAppearance">@macro/m3_comp_sheet_bottom_docked_container_shape</item>
        <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.Material3.Corner.Top</item>
        <item name="shouldRemoveExpandedCorners">false</item>  // True also does not work
        <item name="backgroundTint">@macro/m3_comp_sheet_bottom_docked_container_color</item>
    </style>
```

What am i doing wrong here?

**Comment by oOJohn6Oo** [comment]
For those who do not want to use M3, just upgrade to latest version and add `<item name="shouldRemoveExpandedCorners">false</item>` to your `bottomSheetStyle` theme.

**Comment by Zee604** [comment]
pougf
