### ISSUE TITLE
BottomNavigationView:  ActionLayout problem

### ISSUE THREAD

**Issue by sawyerhard** [material-components/material-components-android#128]
Hi, i tried to add custom layout as menu item for bottom navigation view, but it isn't showing, i have this:

`    <item
        android:id="@+id/action_in_progress"
        android:enabled="true"
        android:actionLayout="@layout/in_progress_layout"
        android:title="@string/in_progress_screen_title"
        app:showAsAction="ifRoom" />`

I found one desicion : inflate this layout programmatically and it's working well, but i cant understand how to set title for this, because i have message: "BottomNavigationItemView.setTitle can only be called from within the same library group (groupId=com.android.support). This API has been flagged with a restriction that has not been met."

Thanks)

**Comment by kavanmevada** [comment]
Check out this implementation : https://github.com/kavanmevada/Material-Case-Studies-Owl

**Comment by ldjcmu** [comment]
Closing this issue as it was filed a log time ago and BottomNavigationView has changed a lot since then. Please re-open if this is still problematic.
