### ISSUE TITLE
[MaterialDatePicker] Open up customisability for custom DateSelectors 

### ISSUE THREAD

**Issue by CasperHalleriet** [material-components/material-components-android#1280]
I was wondering if there are any plans to make the DateSelector class public and not restrict to library group only.

In MaterialDatePicker.Builder there is an option to pass in a custom DateSelector. But you can't create your own selector now because DateSelector is limited to Library Group only

**Comment by froriz5** [comment]
This is being tracked here: #1268

**Comment by CasperHalleriet** [comment]
Ah thx. I had searched for it (looks like i searched not good enough). I will close this then
