### ISSUE TITLE
[TextInputEditText] Incompatable with adjustPan

### ISSUE THREAD

**Issue by alexmkunz** [material-components/material-components-android#1282]
**Description:** When I have a TextInputEditText nested within a TextInputLayout, adjustPan does not work. Two issues arise:

1. When the TextInputEditText is at the bottom of the ScrollView, the screen is not panned up to show the current text. This is shown in the picture below. You can see the purple cursor, in between the x and c keys on the keyboard, that signifies where the text currently is. The soft keyboard covers this text, and you cannot scroll down to view the text. It is permanently covered by the keyboard when the keyboard is visible and the text input is large. 
![Screenshot_2020-05-08-03-31-11](https://user-images.githubusercontent.com/22206953/81387839-fcff0e00-90dc-11ea-97ff-d74e634f9c86.png)

2. When you have a large amount of text in the TextInputEditText, as shown in the first screenshot, and you click near the top of this text, the pan does not work properly. The third picture shows what happened when I click on the word "the" on the first line of the input to the TextInputEditText. It scrolls all of the text upwards, off screen, and you can no longer see where the cursor is.
![Screenshot_2020-05-08-03-31-28](https://user-images.githubusercontent.com/22206953/81387847-fe303b00-90dc-11ea-863a-bc60c912dec9.png)
![Screenshot_2020-05-08-03-31-37](https://user-images.githubusercontent.com/22206953/81387845-fd97a480-90dc-11ea-8648-7232f06cc3fb.png)

The reason I think this is a bug, rather than my incorrect xml attributes, is the fact that **it pans correctly when I replace TextInputEditText with a regular EditText**. When I keep everything the same, except I change "<com.google.android.material.textfield.TextInputEditText" for "<EditText", the problem is solved and it pans correctly. Because of this, it seems to be an issue with the material TextInputEditText.

**Expected behavior:** The expected behavior is the screen to pan to include the selected text/cursor.

**Source code:** 

Activity in Android Manifest:

        <activity
                android:name=".MainActivity"
                android:screenOrientation="portrait"
                android:windowSoftInputMode="stateHidden|adjustPan">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

XML Layout: 

    <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

        <ScrollView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:fillViewport="true"
                android:layout_alignParentTop="true"
                android:layout_above="@id/...">

            <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@color/background">

                ...
                ...
                ...

                <com.google.android.material.textfield.TextInputLayout
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        app:layout_constrainedWidth="true"
                        app:layout_constraintEnd_toEndOf="@id/..."
                        app:layout_constraintHorizontal_bias="0.0"
                        app:layout_constraintStart_toStartOf="@id/..."
                        app:layout_constraintTop_toBottomOf="@id/...">

                    <com.google.android.material.textfield.TextInputEditText
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:textColor="@color/..."
                            android:textSize="@dimen/..."
                            android:inputType="textMultiLine"
                            android:minLines="5"
                            android:gravity="top"
                            android:hint="@string/..."
                            app:formatInstructions="@{...}"/>
                </com.google.android.material.textfield.TextInputLayout>

            </androidx.constraintlayout.widget.ConstraintLayout>

        </ScrollView>

        ...
        ...
        ...

    </RelativeLayout>

**Android API version:** 6.0.1

**Material Library version:** 1.2.0-alpha06

**Device:** Galaxy S5

**Comment by keciciler** [comment]
Same here, does anyone have working solution?

**Comment by SebLorea** [comment]
Same here, still no update on this ?

**Comment by pedrex1987** [comment]
Is there still hope?

**Comment by TeoVogel** [comment]
Hey there, try changing TextInputEditText for EditText. That did it for me

**Comment by Benjiko99** [comment]
This behavior can be disabled by adding `app:textInputLayoutFocusedRectEnabled="false"` to the TextInputEditText.

**Comment by leticiarossi** [comment]
I believe this has been fixed in https://github.com/material-components/material-components-android/commit/a8d8e70d898e61a190f0fc64eae298a713fbbdb8 available in 1.6.0. Will close this issue but feel free to reopen if it's still happening.
