### ISSUE TITLE
[Exposed Dropdown Menu] shows object info instead of text with custom ArrayAdapter

### ISSUE THREAD

**Issue by ThanosFisherman** [material-components/material-components-android#1286]
**Description:**  Exposed Dropdown Menu Not Properly displaying Items in **selected state** when using a custom ArrayAdapter

**Expected behavior:** Selected state of dropdown should display the item exactly as it appears on the dropdown menu list but that does not happen as you see in the screenshot below.
![dropdownfail](https://user-images.githubusercontent.com/4888330/81500472-19689980-92db-11ea-8b6f-584c0b43e4cb.png)

**Source code:** 

```kotlin
class PulseArrayAdapter(context: Context, @LayoutRes private val resId: Int, private val items: List<SonicoParam.ParamValue>) :
    ArrayAdapter<SonicoParam.ParamValue>(context, resId, items) {

    override fun getDropDownView(position: Int, convertView: View?, parent: ViewGroup): View {
        return getCustomView(position, convertView, parent)
    }

    override fun getView(position: Int, convertView: View?, parent: ViewGroup): View {
        return getCustomView(position, convertView, parent)
    }

    override fun getCount(): Int {
        return items.size
    }

    override fun getItem(position: Int): SonicoParam.ParamValue? {
        return items[position]
    }

    override fun getItemId(position: Int): Long {
        return position.toLong()
    }

    private fun getCustomView(pos: Int, contertView: View?, parent: ViewGroup): View {
        var view = contertView
        if (view == null) {
            view = LayoutInflater.from(context).inflate(resId, parent, false)
        }
        view?.txtItem?.text = items[pos].paramDesc.let { context.getString(it) }
        return view as View
    }
}
```

**Android API version:** 27,28,29

**Material Library version:** 1.2.0-alpha06

**Device:** Xiaomi Mi A1

**Comment by Egi10** [comment]
You can add getFilter

`class RecommendationAdapter(context: Context, private val list: MutableList<Recommendation>) :
    ArrayAdapter<Recommendation>(context, 0, list) {

    private val listNew: List<Recommendation> = list

    override fun getView(position: Int, convertView: View?, parent: ViewGroup): View {
        var dropdownItemView = convertView

        if (dropdownItemView == null) {
            val inflater = (parent.context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE) as LayoutInflater)
            dropdownItemView = inflater.inflate(R.layout.item_list_drop_down, parent, false)
        }
        val tvTitle = dropdownItemView!!.findViewById<TextView>(R.id.tvTitle)
        tvTitle.text = list[position].text
        return dropdownItemView
    }

    override fun getFilter(): Filter {
        return object : Filter() {
            override fun convertResultToString(resultValue: Any): String {
                return (resultValue as Recommendation).text.toString()
            }

            override fun performFiltering(constraint: CharSequence): FilterResults {
                val filterResults = FilterResults()
                val recommendationSuggestion: MutableList<Recommendation> = ArrayList<Recommendation>()
                for (recommendation in listNew) {
                    if (recommendation.text?.toLowerCase(Locale.ROOT)
                            ?.startsWith(constraint.toString().toLowerCase(Locale.ROOT))!!
                    ) {
                        recommendationSuggestion.add(recommendation)
                    }
                }
                filterResults.values = recommendationSuggestion
                filterResults.count = recommendationSuggestion.size
                return filterResults
            }

            override fun publishResults(
                constraint: CharSequence, results: FilterResults
            ) {
                list.clear()
                if (results.count > 0) {
                    for (recommendation in results.values as List<*>) {
                        if (recommendation is Recommendation) {
                            list.add(recommendation)
                        }
                    }
                    notifyDataSetChanged()
                }
            }
        }
    }

    override fun getCount(): Int {
        return list.size
    }
}
`

**Comment by hanif-virtueinfo** [comment]
You can override the **toString()** method:

` override fun toString(): String {
        return paramDesc
    }`

in your data model class. So it will show the value of specific parameter on selection.

**Comment by Hanif-abuvani** [comment]
You can override the **toString()** method:

`override fun toString(): String { return paramDesc }`

in your data model class. So it will show the value of specific parameter on selection.

**Comment by drchen** [comment]
+1 to @Hanif-abuvani. I'll close the issue since it's the right way to implement this.

The relevant logic resides in Android framework code so there's no way for us to fix it either.
