### ISSUE TITLE
[TextInputLayout/TextInputEditText] TextInputEditText does not update, as default EditText does, during Espresso test

### ISSUE THREAD

**Issue by MFrat** [material-components/material-components-android#1287]
**Description:** During Espresso tests if you try to screenshot before and after typing a text, the component just don't update, but default EditText does update as expected. I think it is a animation problem, i tried to disable it in developer options but the problem persisted (TextInputLayout/TextInputEditText's animation persisted), so a think there is some animation happening inside a handler or some stuff.

**Expected behavior:** 
All three fields should have been filled. If you pay attention you can see "Description" label during its animation.
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/gueEg.png

**Source code:** 

``` kotlin
ScreenShotter.takeScreenshot("before", activity)

onView(withId(id)).perform(typeText(text))
onView(withId(id2)).perform(typeText(text2))
onView(withId(id3)).perform(typeText(text3))

ScreenShotter.takeScreenshot("after", activity)
```

**Android API version:** 24

**Material Library version:** 1.2.0-alpha06
Also occurs in 1.1.0

**Device:** Android Emulator Pixel API 24

**Comment by drchen** [comment]
Is this still an issue?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
