### ISSUE TITLE
[Button] Allow icons without tint to use its own colors

### ISSUE THREAD

**Issue by danielgomezrico** [material-components/material-components-android#1289]
The problem is that currently you can set the property `icon` and it will put the drawable in the button *with a tint color*.

I want to be able to use the default colors from the drawable in the button itself.

# Current
```
<Button
            style="@style/Widget.MaterialComponents.Button.OutlinedButton.Icon"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:icon="@drawable/ic_google"
            app:iconGravity="textStart"
            app:iconPadding="24dp" />
```

![image](https://user-images.githubusercontent.com/76348/81569550-09959780-9365-11ea-8f4a-f09d9dc1245b.png)

# Expected

![image](https://user-images.githubusercontent.com/76348/81569604-1e722b00-9365-11ea-87a5-ef23901e8833.png)

## One possible solution 

Set the `iconTint` to `@null`.

```
<Button
            style="@style/Widget.MaterialComponents.Button.OutlinedButton.Icon"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:iconTint="@null"
            app:icon="@drawable/ic_google"
            app:iconGravity="textStart"
            app:iconPadding="24dp" />
```

- [Source](https://stackoverflow.com/a/55568056/273119)

But this solutions feels hacky and dangerous to me.

**Comment by leticiarossi** [comment]
Hi, the solution you have is correct! `iconTint` can be `null` and that should give the result you want

**Comment by krunalpatel3** [comment]
@danielgomezrico thanks it solved me issue.
