### ISSUE TITLE
[BottomNavigationView] Tint Color in Items Inactive

### ISSUE THREAD

**Issue by joaoeudes7** [material-components/material-components-android#1291]
**Describe the solution you'd like**
I need a property to set colors of "text" and "ripple" to items inactives

**Describe alternatives you've considered**
Create properties:
- [ ]  "itemInactiveRippleColor"
- [ ]  "itemInactiveTextColor"

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by joaoeudes7** [comment]
I found a solution using the selector:
https://stackoverflow.com/questions/38799535/how-to-change-inactive-color-on-bottom-navigation

**Comment by TacoTheDank** [comment]
And perhaps "itemInactiveIconTint" as well

**Comment by drchen** [comment]
You can override app:itemTextColor and app:itemRippleColor attributes in the style. For inactive state, set colors with android:state_checked=false.
