### ISSUE TITLE
[MaterialDatePicker] Localized strings needed

### ISSUE THREAD

**Issue by CoolMind** [material-components/material-components-android#1294]
**Is your feature request related to a problem? Please describe.**
When we call `MaterialDatePicker.Builder` (datePicker or dateRangePicker), we see English captions.

**Describe the solution you'd like**
I want to output them in the language default to device. I can only affect on "select a date", but not "selected date". I think these labels should be translated and be kept in system strings.

**Additional context**
![изображение](https://user-images.githubusercontent.com/10630436/81722634-532bd280-948a-11ea-9890-ead08b17e45b.png)

**Comment by leticiarossi** [comment]
Hi, you're able to localize that string by following what's suggested in https://github.com/material-components/material-components-android/issues/761
So you can redefine 
`<string name="mtrl_picker_range_header_unselected" tools:override="true">[your translation]</string>`
You can find the strings in the [strings.xml](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/res/values/strings.xml#L24) file

**Comment by CoolMind** [comment]
@leticiarossi, thank you! I will try.

**Comment by basmasrour** [comment]
> Hi, you're able to localize that string by following what's suggested in #761
> So you can redefine
> `<string name="mtrl_picker_range_header_unselected" tools:override="true">[your translation]</string>`
> You can find the strings in the [strings.xml](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/res/values/strings.xml#L24) file

how to override the months' names?
