### ISSUE TITLE
[MaterialCardView] stroke BindingAdapter invalidate

### ISSUE THREAD

**Issue by zmunm** [material-components/material-components-android#1299]
**Description:** 
layout :   RecyclerView > ViewHolder > MaterialCardView
so I have materialCardView List and I want to change each stroke dynamically
MaterialCardView's stroke not update even if `setStrokeWidth` or `setStrokeColor` invoked but it updated when I `ACTION_DOWN` specific card

**Expected behavior:** I think stroke should be updated dynamically

**Source code:** 
```xml
    <com.google.android.material.card.MaterialCardView
        .....
        app:strokeColor="@{ isStrokePink ? @color/pink20 : @color/blue20 }"
        app:strokeWidth="1dp" />
```

and I tried this, it worked

```kotlin
@BindingAdapter("strokeColor")
fun MaterialCardView.setStrokeStyle(
    @ColorInt strokeColor: Int
) {
    setStrokeColor(strokeColor)

    // I added this
    invalidate()
}
```

**Android API version:** 9

**Material Library version:** `com.google.android.material:material:1.2.0-alpha06`

**Device:** SAMSUNG SM-A505N

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by matheusbrunetti** [comment]
I've tried it and this solution solves my problem. Thanks so much!
