### ISSUE TITLE
Changing MaterialCardView radious dynamically while using stroke

### ISSUE THREAD

**Issue by dhruvmi** [material-components/material-components-android#130]
Changing corner radius of MaterialCardView according to scroll position,
When I set a stroke on it, the stroke stays at the initial position rather then changing with the changed radius

currently using
implementation 'com.google.android.material:material:1.0.0-alpha1'

**Comment by dsn5ft** [comment]
This was addressed by https://github.com/material-components/material-components-android/commit/4ceaaf519668714d6af1f7f15c6f014706efe51f. Will be available in the next release coming soon.
