### ISSUE TITLE
CollapsingToolbarLayout only scrolls header when coming back from another activity

### ISSUE THREAD

**Issue by mariuspena** [material-components/material-components-android#1301]
I have almost the same issue. I have tried version 1.1.0, and 1.2.0-alpha06

See video: 
https://youtu.be/Q_LaMnwhOyU

1. 1st view: a Fragment that has CoordinatorLayout, it scrolls fine. 
2. go to another activity (same setup.. ) 
2.1. if I do not touch any view in the activity and go back, the fragment scrolls fine
2.2. if I focus on an EditText, or click on a Button and then go back > the header scrolls, the content stays in the same place. 

PS: since the 1st view (the fragment) is part of a Navigation (with NavHostFragment and BottomNavigationView) ... sometimes the other fragments have 0 width and height (so a blank page.. although the api calls work, recyclers are populated, etc) 

**Source code:** 
`<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/bgColor"
    android:id="@+id/root"
    android:fitsSystemWindows="true">

    

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fitsSystemWindows="true"
            app:layout_scrollFlags="scroll|exitUntilCollapsed|snap">

            <include
                android:id="@+id/header_profile"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                layout="@layout/header_profile"
                app:layout_collapseMode="pin"
                />

        </com.google.android.material.appbar.CollapsingToolbarLayout>
    </com.google.android.material.appbar.AppBarLayout>

    

    

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        android:fillViewport="true">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">
            <TextView
                android:id="@+id/tv_requests"
                style="@style/Text.Profile"
                android:text="@string/requests"
                android:drawableStart="@drawable/ic_requests"
                android:layout_marginTop="@dimen/margin_default"
                />
            <androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/tv_notification_settings"
                style="@style/Text.Profile"
                android:text="@string/not_settings"
                android:drawableStart="@drawable/ic_notification_settings"
                android:alpha="0.9"
                />
            <androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/tv_chat_support"
                style="@style/Text.Profile"
                android:text="@string/chat_support"
                android:drawableStart="@drawable/ic_chat_support"
                android:alpha="0.8"
                />
            <androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/tv_privacy_policy"
                style="@style/Text.Profile"
                android:text="@string/privacy_policy"
                android:drawableStart="@drawable/ic_privacy_policy"
                android:alpha="0.7"
                />
            <androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/tv_terms"
                style="@style/Text.Profile"
                android:text="@string/terms"
                android:drawableStart="@drawable/ic_terms"
                android:alpha="0.6"
                />
            <androidx.appcompat.widget.AppCompatTextView
                android:id="@+id/tv_logout"
                style="@style/Text.Profile"
                android:text="@string/logout"
                android:drawableStart="@drawable/ic_logout"
                android:alpha="0.5"
                />

        </LinearLayout>
    </androidx.core.widget.NestedScrollView>

</androidx.coordinatorlayout.widget.CoordinatorLayout>`

**Android API version:** 
Android 9 (works on Android 10!)

**Material Library version:** 
1.1.0, 1.2.0-alpha06

**Device:** 
Nexus 5X (works on Pixel 3 with Android 10!)

**Comment by ymarian** [comment]
Can you include the sample app?

**Comment by drchen** [comment]
I'll close the issue as there's no further info. 

Feel free to reopen the issue if this is still reproducible.
