### ISSUE TITLE
[ShapeableImageView] when add padding to the ImageView it is not working on design wizard 

### ISSUE THREAD

**Issue by MinaSamirCap** [material-components/material-components-android#1303]
**Description:** when adding padding to the ShapeableImageView it is not working on the design wizard of the android studio but is working when running the app.

Maybe it is not an urgent issue but when adding padding to the view. the view itself disappeared but it is shown as expected on the device I can not see it to adjust my design.

I made a workaround to show the image at least by adding padding using tool namespace with 0dp as a value to padding to be able to see the render but still padding not working.
![1](https://user-images.githubusercontent.com/7923425/82214795-a680a380-9916-11ea-9f23-5f52a0881f61.PNG)
![2](https://user-images.githubusercontent.com/7923425/82214800-a97b9400-9916-11ea-833a-bdb3dd1a9115.PNG)

**Comment by ymarian** [comment]
I tested on AS 3.6 Canary 12 and it's working well. Can you share what version of the library and of Android studio you're using? Also what format is the image

<img width="1068" alt="Screen Shot 2020-05-18 at 3 27 59 PM" src="https://user-images.githubusercontent.com/38727469/82251954-29582d00-991c-11ea-8476-f43bcb05ad68.png">

**Comment by MinaSamirCap** [comment]
Library version: **1.2.0-alpha06**
Android Studio version: **3.6.3** stable channel
Image type: **.png file**. Also, **I tested it with a vector image** but the same result.
Also, I tried to use `android:src` attribute instead of `app:srcCompat` but the same result
if I add padding the image disappeared.

**Comment by ymarian** [comment]
Thanks I confirmed it's a duplicated of this bug:
https://github.com/material-components/material-components-android/issues/1046

It should be fixed in newer versions of AS, hopefully it moves to stable soon
