### ISSUE TITLE
[ExposedDropDown] Accessbility issue related to AutoCompleteTextVieew

### ISSUE THREAD

**Issue by navczydev** [material-components/material-components-android#1305]
**Description:**  I tried to use AutoCompleteTextView with TextInputLayout for ExposedDropDown.

It work as expected without Talkback. But when Talkback is turned on and Drop down is opened, it talkback not able to navigate through it.

**Expected behavior:** Talkback should able to behave properly and when dropdown is opened it should process it as expected.

**Material Library version:** Material Android Library version you are using here (1.1.0)

Thanks

**Comment by leticiarossi** [comment]
There was a fix introduced in 1.2.0-alpha01 for that issue for the non-editable dropdown menu which will be included in the next stable release.

**Comment by navczydev** [comment]
Thanks for quick response @leticiarossi
