### ISSUE TITLE
[Material.io site] Getting started page refers to Android 9

### ISSUE THREAD

**Issue by kkuan2011** [material-components/material-components-android#1306]
**Description:** 
https://material.io/develop/android/docs/getting-started/

On this documentation page, step 2 refers to Android 9: "Compile your app with Android 9"
"In order to use Material Components for Android, and the latest versions of the Support Libraries, you will have to update your app’s compileSdkVersion to 28 and download the Android 9 using the SDK manager. For more information on Android 9 and its timeline, take a look at the Program Overview page."

**Expected behavior:** 
Update that step to refer to Android 10.

**Comment by leticiarossi** [comment]
Thanks for the catch! This has been updated in github and will be updated in material.io soon
