### ISSUE TITLE
Outline button material theme is not showing in latest version.

### ISSUE THREAD

**Issue by soodkartik24** [material-components/material-components-android#1309]
**Description:** IN latest version 1.2.0-alpha06 outline button is not working. It will work only in 1.2.0-alpha02

**Expected behavior:**  Please fix this in the next version

**Comment by bhoomi0104** [comment]
I am facing the same issue

**Comment by leticiarossi** [comment]
Can you provide source code and screenshots of your issue? Is it not showing on Android Studio preview or on your app?

**Comment by soodkartik24** [comment]
Both of them(Android studio preview and android emulator). I am using android studio version number 3.6.3

**Comment by soodkartik24** [comment]
`app:strokeColor=#FFFFFF ` simply using the same but it's not working in version 1.2.0-alpha06 but it works well in version 1.2.0-alpha02

**Comment by leticiarossi** [comment]
Android Studio fixed some preview issues in its most recent release candidate version, could you test on that? 
Regarding the emulator, our buttons are working as expected on my end. If you still find the issue in the release candidate version could you provide a sample app where your issue happens?

**Comment by soodkartik24** [comment]
In Android Latest beta version 4.0.0 Beta5. It is working fine. Thanks

**Comment by leticiarossi** [comment]
Thanks for confirming! Will close this then
