### ISSUE TITLE
Button size increased in version 1.2.0-alpha06

### ISSUE THREAD

**Issue by soodkartik24** [material-components/material-components-android#1312]
**Description:** Button height seeing very large in version 1.2.0-alpha06 but it looks fine in 1.2.0-alpha02

**Expected behavior:**  it should be look fine as version 1.2.0-alpha02

**Comment by leticiarossi** [comment]
can you provide screenshots and source code?

**Comment by soodkartik24** [comment]
Well adding android:background and app:backgroundTint increased button size. But if I am using only app:backgroundTint. It is working fine.

**Comment by ymarian** [comment]
Please reopen if you can provide a sample repro of the issue.
