### ISSUE TITLE
[MaterialCardView] Card is not visible with SHADOW_COMPAT_MODE_ALWAYS 

### ISSUE THREAD

**Issue by vladimir-vladykin** [material-components/material-components-android#1313]
**Description:** 
MaterialCardView is not visible, if you apply SHADOW_COMPAT_MODE_ALWAYS to its MaterialShapeDrawable. 
Compact shadows for card view worked correctly in version 1.1.0-alpha10, but since 1.1.0-beta01 content of card view, and card itself, became invisible if you apply SHADOW_COMPAT_MODE_ALWAYS. Also this statement is correct for latest version, 1.2.0-alpha06.

Here's how card looks with 1.1.0-alpha10:
![Screenshot_20200521-155332__01](https://user-images.githubusercontent.com/8830607/82567487-1cd70d00-9b86-11ea-97d9-e49439f5b173.jpg)

But with any version starting 1.1.0-beta01 card is absolutely invisible. I'm attaching screenshot with layout bounds enabled, and you can see that card is there, but content is invisible, as well as shadows.
![Screenshot_20200521-155630__01](https://user-images.githubusercontent.com/8830607/82567433-09c43d00-9b86-11ea-9929-aad6c7c2716d.jpg)

**Expected behavior:**
MaterialCardView and its content are visible after applying SHADOW_COMPAT_MODE_ALWAYS.

**Source code:** 
Run code bellow under 1.1.0-alpha10 and you'll see card with correct content and perfect shadows.
Under 1.1.0-beta01+ screen will be empty.

Layout:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- activity theme is Theme.MaterialComponents.Light.NoActionBar -->
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity"
    android:clipChildren="false"
    >

    <com.google.android.material.card.MaterialCardView
        android:id="@+id/card_view"
        android:layout_width="match_parent"
        android:layout_height="150dp"
        android:layout_margin="16dp"
        app:cardCornerRadius="10dp"
        app:cardElevation="8dp"
        >

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:padding="16dp"
            >

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Some title"
                android:textSize="24sp"
                android:textStyle="bold"
                />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Some description"
                android:textSize="18sp"
                android:layout_marginTop="5dp"
                />
        </LinearLayout>

    </com.google.android.material.card.MaterialCardView>
</FrameLayout>
```

Code of activity, inflates layout and enables compact shadow:
```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val cardView = findViewById<MaterialCardView>(R.id.card_view)
        getShapeBackground(cardView)?.shadowCompatibilityMode = MaterialShapeDrawable.SHADOW_COMPAT_MODE_ALWAYS
    }

    private fun getShapeBackground(view: View): MaterialShapeDrawable? {
        val background = view.background

        if (background is MaterialShapeDrawable)
            return background

        if (background is DrawableWrapper) {
            val wrappedDrawable = background.drawable
            if (wrappedDrawable is MaterialShapeDrawable)
                return wrappedDrawable
        }

        return null
    }
}
```

**Android API version:** 
I reproduced on Android 8 and Android 10

**Material Library version:** 
Any version after 1.1.0-alpha10, so 1.1.0-beta01 - 1.2.0-alpha06

**Device:**
OnePlus 6 running Android 10
Nexus 5 emulator running Android 8.

**Why do I need this:**
Ability to enable compact shadows for MaterialCardView is important for my app, that's why I stuck with 1.1.0-alpha10.
My app heavily uses cards with semitransparent background, and because of that I'm forced to use compact shadows, since native shadows don't play nice with translucent backgrounds.
But in example above I used opaque background to show that problem is not related to translucent backgrounds.

**Comment by ymarian** [comment]
Hi this is because to remove the native shadow we return a null outline. You can set 

```kotlin
cardView.clipToOutline = false
```
In addition since you mentioned your cards are semitransparent you'll want to do  

```kotlin
getShapeBackground(cardView)?.setShadowBitmapDrawingEnable(true)
```

Note that the second line will be bad for performance since be allocate an extra bitmap the size of your card but that's the default behavior in the version you're using anyway.
