### ISSUE TITLE
[TextInputLayout] Counter is hidden by keyboard

### ISSUE THREAD

**Issue by Jeyveen7** [material-components/material-components-android#1314]
**Description:** 
If app:counterEnabled="true" is set in a TextInputLayout, whenever a user opens a keyboard to type in something, the counter is hidden by the keyboard thus defeating its purpose of letting the user know how much he/she has typed and how much character(s) are left.

**Expected behavior:**
The expected behavior, IMHO, would be to make the modify the component in such a way that the keyboard no longer hides the counter and allows the user to know how much character(s) he/she is left to type. 

**Source code:**

```
    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/textInputDescriptionLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/TextInputLayoutAppearance"
        app:counterEnabled="true"
        app:counterMaxLength="35">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/tvDescription"
            style="@style/Text12RegularBlack"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:digits="@string/account_holder_name_input_keys"
            android:hint="@string/description"
            android:imeOptions="actionDone"
            android:inputType="textFilter"
            android:maxLength="35"
            android:paddingBottom="@dimen/padding_16dp"
            android:textSize="@dimen/text_size_16sp" />
    </com.google.android.material.textfield.TextInputLayout>
```

**Android API version:**
29

**Material Library version:**
1.1.0-alpha08

**Device:** 
Pixel 2

**Comment by leticiarossi** [comment]
Hi, can you test if this happens in our most recent release 1.2.0-alpha06?

**Comment by Jeyveen7** [comment]
Hi, thanks for your reply. Let me test and get back to you.

**Comment by Jeyveen7** [comment]
Hello @leticiarossi , unfortunately, it did not work. I used the most recent release 1.2.0-alpha06 as you mentioned and made a few changes. Is there something specific that I need to do in the TextInputLayout after upgrading so that the keyboard does not hide the counter?

![image](https://user-images.githubusercontent.com/9960074/82640832-53f7fd80-9c1c-11ea-955f-16051b629578.png)

![image](https://user-images.githubusercontent.com/9960074/82640883-6ffb9f00-9c1c-11ea-8423-6898dd749654.png)

**Comment by leticiarossi** [comment]
By default the`TextInputEditText` sets `textInputLayoutFocusedRectEnabled` to true so that it will use the `TextInputLayout`'s rectangle so that the helper or counter views wouldn't be hidden in cases like that. Could you provide a sample app with the issue so I can look into it?

**Comment by Jeyveen7** [comment]
From TextInputEditText.java, in the 1.2.0-alpha06 release, I see:

` setTextInputLayoutFocusedRectEnabled(
        attributes.getBoolean(R.styleable.TextInputEditText_textInputLayoutFocusedRectEnabled, **false**));`

Is that something of concern?

**Comment by leticiarossi** [comment]
We set it to true on the TextInputEditText's default style here! https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/values/styles.xml#L178 so the `R.styleable.TextInputEditText_textInputLayoutFocusedRectEnabled` will be true by default

**Comment by drchen** [comment]
Looks like we can close the issue. : )
