### ISSUE TITLE
[MaterialAlertDialog] Message limited to one line

### ISSUE THREAD

**Issue by jmartingit** [material-components/material-components-android#1315]
**Description:** messages in MaterialAlertDialogBuilder are always truncated at the first line.

**Expected behavior:** messages should be multi-line like before.

**Android API version:** tested on API 23 and 29

**Material Library version:** 1.1

**Device:** Nexus 5 and Pixel 2

**Comment by leticiarossi** [comment]
Can you provide source code and screenshots of what you mean?

**Comment by wcshi** [comment]
Please see "long message" dialog demo in the catalog app which shows messages on multiple lines.

**Comment by jmartingit** [comment]
I created a demo app and the problem doesn't happen there, so it must be a problem on my end.

Sorry for the trouble. I'm closing the issue now.

Thanks a lot for your work 👍

**Comment by wcshi** [comment]
Thanks for the update!

**Comment by fabirt** [comment]
Please could you tell me how you solved it? I have the same problem, the support text is limited to one line.

**Comment by jmartingit** [comment]
I still have the problem 😢

In the end, I avoided it by using a custom view in my dialogs instead of using 'setMessage'.

If I ever find the cause, I'll post it here.

**Comment by jmartingit** [comment]
For future readers who have this issue, here's what I did wrong:

I was overriding materialAlertDialogBodyTextStyle with my custom style, but I used 'MaterialAlertDialog.MaterialComponents.Title.Text' as the parent for my custom style, when I should have used 'MaterialAlertDialog.MaterialComponents.Body.Text'.
