### ISSUE TITLE
[Slider] Label always visible

### ISSUE THREAD

**Issue by sdsantos** [material-components/material-components-android#1316]
**Is your feature request related to a problem? Please describe.**

There's currently no easy way to keep the slider label always visible. The existing `labelBehavior`s don't cover it.

**Describe the solution you'd like**

Add a new `labelBehavior` called `LABEL_ALWAYS_VISIBLE` that would keep the label always visible, and not dependent on touch.

**Describe alternatives you've considered**

Right now, to implement this behavior, one must use reflection to access private methods and fields of the `BaseSlider`, or re-create the label outside of the view, and make it track the slider thumb position.

**Comment by vbarbieux** [comment]
That'd help us a lot.

**Comment by gabrielemariotti** [comment]
This change is quite simple and I can submit a PR.
But I am not sure that it follows the material guideline.

<img width="778" alt="Schermata 2020-08-18 alle 12 49 02" src="https://user-images.githubusercontent.com/2583078/90504395-4b4a9100-e151-11ea-8692-86db124bebdd.png">

**Comment by itsjustbrian** [comment]
@sdsantos Hi! I'm newer to Android development and trying to get this behavior. Do you think you could provide an example or a little more explanation on the workaround(s) you used? It would really help me out. Thank you!

**Comment by sdsantos** [comment]
> @sdsantos Hi! I'm newer to Android development and trying to get this behavior. Do you think you could provide an example or a little more explanation on the workaround(s) you used? It would really help me out. Thank you!

I ended up not implementing any alternatives I mentioned, cause they seemed to brittle to me. The easier one would be to design yourself the label, then listen to progress changes, and adjust the label position to always match the progress thumb position.

**Comment by lesniakania** [comment]
Omg, I'm trying to implement a colorful multirange slider from Friday and I tried a ton of libraries and there is always some feature missing for me. @sdsantos thanks for this comment! It saved me today!

**Comment by baldhead69** [comment]
I would like this feature too(Label always visible).

**Comment by baldhead69** [comment]
How can i change the label ?

Example:
When the thumb value are 0 i would like to show off and when the thumb value are 100 show full.
Between 0 and 100, ie: 5 and 95, show 5%, 10%, 15%, ......., 95%.

The stepSize are 5.

**Comment by baldhead69** [comment]
Change the label value are solved with LabelFormatter class.

**Comment by MithrilMan** [comment]
So, isn't this a use case worth of a solution?
Does this violate any Material guideline and won't be implemented?

**Comment by baldhead69** [comment]
"Label always visible" nothing yet ?

**Comment by wongcain** [comment]
I also would like always displayed labels.  I am trying to replace a legacy custom slider with the Slider component, and this is the one feature that I haven't been able to replicate with styling.

**Comment by Nikola-Milovic** [comment]
Why is this not a thing, does it really change that much and affect anything? It's a genuine use-case that could be helpful and adding another flag to the behaviour shouldn't hurt anyone.

**Comment by vvictor10** [comment]
We need an always on state for the label for our design as well. Missing it :(

**Comment by baldhead69** [comment]
10 years from now they will implement this.  Hahahaha

**Comment by sebastianharder** [comment]
As much as I like the material components and am grateful that they exist, it's really unfortunate that the styling is so much limited that it's almost impossible to implement s.th. not exactly matching the material design guidelines.

**Comment by wongcain** [comment]
In case it is helpful to others, I ended up disabling the built-in labels and adding my own that are always visible.  I then made use of the `Slider.OnChangeListener` callback to update the text and position of the label like this:
```
    override fun onValueChange(slider: Slider, value: Float, fromUser: Boolean) {
       // valueTextView is my custom label
        valueTextView.apply {
            text = getSliderValueLabel(value)
            requestLayout()
        }
        post { updateValueLabelPosition() }
    }

    private fun getSliderValueLabel(value: Float): String {
        val valueRoundedToTenth = (value * LABEL_ROUNDING_FACTOR).roundToInt() / LABEL_ROUNDING_FACTOR
        return when {
            valueRoundedToTenth == 0f -> "0"
            valueRoundedToTenth > 0 -> "+$valueRoundedToTenth"
            else -> valueRoundedToTenth.toString()
        }
    }

    private fun updateValueLabelPosition() {
        val valueRangeSize = sliderView.valueTo - sliderView.valueFrom
        val valuePercent = (sliderView.value - sliderView.valueFrom) / valueRangeSize
        val valueXDistance = valuePercent * sliderView.trackWidth
        val offset =
            sliderView.x + sliderView.trackSidePadding - (valueTextView.width.toFloat() / 2)
        valueTextView.x = (valueXDistance + offset).let {
            if (labelTextView.visibility == View.VISIBLE) {
                it.coerceAtLeast(labelTextView.right.toFloat())
            } else {
                it
            }
        }
    }

```

**Comment by mtrakal** [comment]
Using DataBinding with custom view to show current value

ViewState / Fragment
```
import androidx.lifecycle.map

val sliderValue = MutableLiveData(0F) // default slider value
val sliderText = sliderValue.map { "$it" }
```

XML:
```
<TextView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="end"
    android:text="@{viewState.sliderText}"/>

<com.google.android.material.slider.Slider
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:labelBehavior="gone" // hide native Thumb
    android:value="@={viewState.sliderValue}"/> // @= for two way DataBinding
```

**Comment by CsabaMiomni** [comment]
v1.7.0-alpha02 looks fine to me, thank you for the improvement!

**Comment by phazei** [comment]
There seems to be a significant bug with this.  I'm using Android Studio Electric Eel and material 1.8.  If app:labelBehavior="visible" the labels are always visible, but they don't move unless the slider is actively being changed.  If it's in a Scroll view, they remain fixed.  When the screen transitions to a different fragment, they stay in place and don't even follow fade transitions.
