### ISSUE TITLE
[TextInputLayout] Expose `floating label` background

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#1319]
The `floating label` background becomes a problem when you are using a different background in your container. I should be able to set the `floating label` background="@null" assuming that the `outline box` won't be visible under the label.

<details>
<summary>Impl Screen</summary>

<img src="https://user-images.githubusercontent.com/1494577/82715231-08a71480-9c47-11ea-83d9-4f7e2473db95.png" width="500"/>
</details>

<details>
<summary>Design Screen</summary>

<img src="https://user-images.githubusercontent.com/1494577/82716037-7274ed80-9c4a-11ea-9384-397d9bdc426d.png" width="500"/>
</details>

Or Am I missing something?

**Comment by thevoiceless** [comment]
+1

Trying to do the same. [This comment](https://github.com/material-components/material-components-android/issues/1187#issuecomment-611698853) on a different issue might be an okay workaround, but doesn't achieve exactly the look we're going for.

**Comment by gabrielemariotti** [comment]
The submitted PR doesn't expose the collapsed hint background.
However it allows to achieve an empty background as shown in desired solution.

<img width="271" alt="Detail" src="https://user-images.githubusercontent.com/2583078/91341443-d07d1800-e7d9-11ea-99ce-c17e3a96486e.png">

**Comment by thevoiceless** [comment]
@ikim24 Is the Travis CI build all that is blocking https://github.com/material-components/material-components-android/pull/1660 ?
