### ISSUE TITLE
Navigation Drawer stops working along with missing icon

### ISSUE THREAD

**Issue by adevezin** [material-components/material-components-android#132]
### Overview
When upgrading to android-P and build version 28 the navigation drawer stops working. The icon will no longer appear but when clicking where the icon shoudl be, you do see the ripple effect. However nothing happens upon click.

### Reproduction steps

 - Detailed steps to reproduce
Upgrade to android-p and use 28 alpha build version

### Version number

 - Found in CHANGELOG.md

### Operating system and device
Emulator on Android P

### Related issues

 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by dsn5ft** [comment]
This is a known issue that has been fixed and will be available in the next release coming soon - https://buganizer.corp.google.com/issues/74357002.

The workaround is to add the following to your App Theme:
```
<item name="navigationViewStyle">@style/Widget.Design.NavigationView</item>
```
