### ISSUE TITLE
[BottomAppBar + NavigationView] clip children even if specifying not to

### ISSUE THREAD

**Issue by cesards** [material-components/material-components-android#1323]
**Description:** BottomAppBar + NavigationView clip children even if specifying not to.

**Expected behavior:** 

Ripple shouldn't be clipped, as the following screenshot shows:

![image](https://user-images.githubusercontent.com/1536079/82765223-bef33100-9de2-11ea-8e9c-afc0aa5abf6d.png)

**Source code:** 

In order to easily reproduce this, just add the following XML to an Activity:
```
<com.google.android.material.bottomappbar.BottomAppBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        app:backgroundTint="?attr/colorPrimary"
        app:contentInsetEnd="0dp"
        app:contentInsetStart="0dp"
        app:fabAlignmentMode="end">

        <com.google.android.material.bottomnavigation.BottomNavigationView
            android:id="@+id/bottomNavigation"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginEnd="100dp"
            app:backgroundTint="@android:color/transparent"
            app:elevation="0dp"
            app:itemIconTint="@android:color/white"
            app:itemRippleColor="@android:color/white"
            app:itemTextColor="@android:color/white"
            app:menu="@menu/menu_activity_home_bottom_navigation" />

    </com.google.android.material.bottomappbar.BottomAppBar>
```

`@menu/menu_activity_home_bottom_navigation"` a simple menu is needed.

**Android API version:** API 28

**Material Library version:** 1.1.0

**Device:** Reproducible in Galaxy S9 + Pixel 3 (emulators too)

**Comment by ymarian** [comment]
Hi this is a duplicate, of https://github.com/material-components/material-components-android/issues/1021

Check https://github.com/material-components/material-components-android/issues/1021#issuecomment-592560062 for a potential workaround
