### ISSUE TITLE
[ShapeableImageView] Rounded corners stroke is cut-off by default

### ISSUE THREAD

**Issue by LouisCAD** [material-components/material-components-android#1329]
**Description:**
By default, when a `ShapeableImageView` has rounded corners and you define `strokeWidth` and `strokeColor`, it will be **cut-off**.
In the screenshot just below, you can see it compared to `TextInputLayout` below it, which renders fine.

![screenshot_20200526-105209](https://user-images.githubusercontent.com/6975237/82885737-d1d24680-9f45-11ea-8f44-b7a30ea51ff0.png)

**Expected behavior:**
Rendering to not appear cut-off by default, without having to increase the `padding`.

**Source code:**
Extension:
```kotlin
fun ShapeableImageView.roundAllCorners(@Dimension radius: Float) {
    shapeAppearanceModel = shapeAppearanceModel.toBuilder()
        .setAllCorners(CornerFamily.ROUNDED, radius)
        .build()
}
```
Code:
```kotlin
myImageView.apply {
    roundAllCorners(dp(8f))
    strokeColor = colorSL(R.color.image_border_on_background)
    strokeWidth = dp(2) // Happens with bigger values as well.
    //padding = strokeWidth // Uncommenting this fixes rendering.
    adjustViewBounds = true
}
```

The `dp` extensions come from [Splitties](https://github.com/LouisCAD/Splitties/blob/49e2ee566730aaeb14b4fa9e395a677c3f214dba/modules/dimensions/src/androidMain/kotlin/splitties/dimensions/Dimensions.kt).

**Android API version:** 29

**Material Library version:** 1.2.0-alpha06

**Device:** Google Pixel 2 XL

**Comment by ymarian** [comment]
This is a tricky one. We could add 1/2 of the strokeWidth to the default padding. That doesn't cover all shapes though. 

Would adding padding be unexpected/undesirable?

**Comment by LouisCAD** [comment]
Is it required that the stroke is snapped by its middle to the frontier between the content and the padding?

If not, then, it could be snapped by the boundaries of the View itself:
By default it'd get the stroke just right, cropping the image by the stroke width (allowing transparency effects), and adding padding of the same width as the stroke would push the borders so the image is not getting overlapped. One could also have fun with different padding for partially overlapping stroke, or gap between the image content and the stroke.

**Comment by ymarian** [comment]
Yes that's rather unfortunate imo. Drawing strokes always snaps them in the middle of the frontier or path and there is no way to modify that as far as I know. 

We can transform the frontier but again that only works nicely for round rects, circles, and rects where the increase is half of the stroke width in every direction. Knowing how to transform the path for an arbitrary shape seems quite complicated. For example this is what happens with cut corners, here we try to draw the stroke inside rather than outside, but the result would be similar.

![test](https://user-images.githubusercontent.com/38727469/83145145-5d70e200-a0c2-11ea-90aa-82d42d11db79.png)

You can see the stroke is Blue with an opacity,  so it overlaps perfectly with the edges (purple). But on the corners it bleeds through a bit so you can see the blue.  

I'm going to keep an eye on this. Please share any other thoughts you have!

**Comment by ymarian** [comment]
@LouisCAD oh one more thing if you do want to achieve that result (stroke drawn outside the bounds of the image), setting android:background and padding, instead of strokeColor and strokeWidth respectively would work I think.

**Comment by LouisCAD** [comment]
I'm confused by the screenshot you posted:
Aren't both the stroke path and the image cutting coming from the same corner treatments?
If so, they should result in the same size if the stroke is snapped by its outside to the image boundaries?

Or is there a limitation that makes this challenging or impossible?

**Comment by ymarian** [comment]
Yeah there is a limitation using paint style stroke draws half inside half outside the provided path. In that screenshot we scaled down the path by 1/2 stroke width in every dimension before drawing.

**Comment by Dvik** [comment]
> setting android:background and padding, instead of strokeColor and strokeWidth respectively would work I think.
This didn't work for me. Can you tell me how? I had to add a cardview around the photo to make it work.

```
<com.google.android.material.card.MaterialCardView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:theme="@style/Theme.MaterialComponents.Light"
        app:cardCornerRadius="85dp"
        app:cardPreventCornerOverlap="false"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:strokeColor="#fff"
        app:strokeWidth="3dp">

        <com.google.android.material.imageview.ShapeableImageView
            android:id="@+id/civ_photo"
            android:layout_width="320dp"
            android:layout_height="320dp"
            android:scaleType="centerCrop"
            android:theme="@style/Theme.MaterialComponents.Light"
            app:shapeAppearance="@style/PhotoShape"
            tools:src="@drawable/photo_placeholder" />
    </com.google.android.material.card.MaterialCardView>
```

**Comment by procmixin** [comment]
Setting the padding, and adjusting the shape dimensions WTR  to the padding, worked for me.

```xml
<com.google.android.material.imageview.ShapeableImageView
      android:id="@+id/image"
      android:layout_width="90dp"
      android:layout_height="90dp"
      android:background="@color/my_color"
      android:padding="4dp"
      android:scaleType="centerCrop"
      android:src="@drawable/some_drawable"
      app:contentPadding="20dp"
      app:shapeAppearance="@style/myShapeAppearance"
      app:strokeColor="@color/stroke_color"
      app:strokeWidth="2dp"
      app:tint="@color/image_tint" />
```

ShapeAppearance
```xml
<style name="myShapeAppearance" parent="ShapeAppearance.MaterialComponents.MediumComponent">
    <item name="cornerFamily">rounded</item>
    <item name="cornerSize">41dp</item>
</style>
```

This allowed my image to be drawn without the box clipping effect

**Comment by drchen** [comment]
There seems like no general solutions for all possible cases. 

I'll close this as infeasible for now. Please feel free to reopen it or create a PR if you have a good idea to solve this.
