### ISSUE TITLE
[ShapeableImageView] NullPointerException when setting nullable annotated strokeColor to null

### ISSUE THREAD

**Issue by LouisCAD** [material-components/material-components-android#1331]
**Description:**
If you call `setStrokeColor(null)`, whenever the `onDraw` method of the `ShapeableImageView` is called, it will crash the entire app with a `NullPointerException`.

_**Side note**: Kotlin would not let this compile at all if MDC Android was using it._

**Expected behavior:**
Have the `strokeColor` private field be `@Nullable` annotated, assign it to locals and null check it before use.

Here's the line where the NPE strikes:
https://github.com/material-components/material-components-android/blob/1a6ebc0c56e3ed553a64f9f06a9d2fb6b4ec7da3/lib/java/com/google/android/material/imageview/ShapeableImageView.java#L151

**Material Library version:** 1.2.0-alpha06

**Comment by LouisCAD** [comment]
@ymarian Why not `@Nullable` annotate the `strokeColor` field? It'd prevent regressions, and would encourage you to make race conditions impossible by assigning `strokeColor` to a local variable before null checking and using.

**Comment by ymarian** [comment]
I missed adding the annotation! Will add, not sure I follow the rest. A race condition shouldn't be possible. It's a strong reference and Invalidate cannot be called outside the UI thread so I think just checking the field is safe. Let me know if I'm missing anything
