### ISSUE TITLE
[MaterialDatePicker] SingleDatePicker InputText on Samsung device keyboard missing separator characters

### ISSUE THREAD

**Issue by BlackHornet** [material-components/material-components-android#1335]
https://github.com/material-components/material-components-android/blob/56b33909ee3651e74120bc89e95af534dc546f1c/lib/java/com/google/android/material/datepicker/SingleDateSelector.java#L106

This should be "||" instead of "&&"!

**Comment by dsn5ft** [comment]
Thanks! This has been addressed internally and will be synced out soon.
