### ISSUE TITLE
[Chip] extra margin has been added to the component

### ISSUE THREAD

**Issue by br00** [material-components/material-components-android#1337]
**Description:** The Chip component has extra margin as you can see in the screenshots. This is happened just upgrading the _com.google.android.material:material:1.0.0_ to _com.google.android.material:material:1.1.0_. 

**Expected behavior:** The margin should not be included in the Chip component

**Android API version:** All versions

**Material Library version:** com.google.android.material:material:1.1.0

**Device:** All devices
![Screenshot_1590583572](https://user-images.githubusercontent.com/4648706/83038219-9e221a00-a034-11ea-9dac-3c190e3b00fc.png)
![Screenshot_1590583695](https://user-images.githubusercontent.com/4648706/83038222-9f534700-a034-11ea-8545-21336a54adb9.png)

**Comment by wcshi** [comment]
Hi @br00 the "extra margin" is due to updates in the lib to meet android's min touch target size of 48dp x 48dp. You can turn this off by setting android: ensureMinTouchTargetSize ="false" in your chip style
