### ISSUE TITLE
I have been trying to add chips to a chips group dynamically, but the chips don't seem to wrap the text completely and text isn't aligned in the center either.

### ISSUE THREAD

**Issue by karan26796** [material-components/material-components-android#134]

**Comment by markizdeviler** [comment]
How can change selected chip color?
I couldn't find anything about chips

**Comment by karan26796** [comment]
I was using the alpha version but there was no documentation regarding chips; thanks for the help.

**Comment by pahnpiseth** [comment]
i use chip.setChipText("Hello");

**Comment by SilverHoodCorp** [comment]
Any way possible to set the style of the chips to Filter Type programmatically?

**Comment by eldarj** [comment]
Had the same issue, this post helped a lot. Thanks!
Did you check again on the documentation if they added this? I couldn't find anything either.

**Comment by AdhamGamal** [comment]
you can just create xml layout at res/layout/chip.xml
`<com.google.android.material.chip.Chip xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    style="@style/Widget.MaterialComponents.Chip.Filter"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:elevation="@dimen/dimens4dp"
    android:padding="@dimen/dimens8dp"
    tools:text="@string/check"
    android:textColor="@color/black"
    app:checkedIconTint="@color/white"
    app:chipBackgroundColor="@color/white"
    app:chipCornerRadius="@dimen/dimens8dp"
    app:chipIconEnabled="true"
    app:closeIconEnabled="false" />`

then inflate that chip layout and change it's text like that
`val chip = LayoutInflater.from(_activity).inflate(R.layout.fliter_item,null) as Chip
            chip.text = "the text'
            parent.addView(chip)`
