### ISSUE TITLE
[MaterialCardView, MaterialButton] The elevation's direction change from top-to-bottom to bottom-to-top

### ISSUE THREAD

**Issue by Madina-S** [material-components/material-components-android#1340]
**Description:** There is dragging view on the top of the view. While dragging the view, its height also expands. When the dragging occurs (even a bit, almost no dragging), the card view below changes the direction of its elevation. However, the behavior is different in different devices (on Samsung everything is ok, but on Xiaomi and Huawei the behavior is strange).
**Source code:** 
`<androidx.cardview.widget.CardView 
    android:layout_width="100dp"
    android:layout_height="70dp"
    android:background="@color/color_bg_primary"
    app:cardCornerRadius="@dimen/item_corner_radius"
    app:cardElevation="5dp"/>`

**Android API version:** Android API version here

**Material Library version:** 1.1.0-alpha02, then I tried 1.2.0-alpha06. The same issue occured.

**Device:** Sumsung A6 (Android 10), Xiaomi Note 7 API level 28

**Comment by ymarian** [comment]
I'm not sure I follow, can you share a video? Are you calling setDragged?

If you want to opt out of this behavior you can set:

you can set android:stateListAnimator="@null" on your card

**Comment by ymarian** [comment]
Actually are you using androidx.cardview.widget.CardView instead of MaterialCardView?

**Comment by Madina-S** [comment]
I have the same behavior in the both components

**Comment by Madina-S** [comment]
`android:stateListAnimator="@null"` did not help, there is reference to screen record https://youtu.be/b_iTljYPB8A

**Comment by ymarian** [comment]
Cannot really tell what's happening from the video. Can you share a sample app?

**Comment by Madina-S** [comment]
While providing the sample, I understood that the reason for this behavior was changing translationY of other views

**Comment by Madina-S** [comment]
The reason for such behavior was setting translationY for other values
