### ISSUE TITLE
[Slider] Slider.LabelFormatter is no longer accessible from Kotlin code in version 1.2.0-beta01

### ISSUE THREAD

**Issue by Thomas-Vos** [material-components/material-components-android#1342]
**Description:** The `Slider.LabelFormatter` class cannot be accessed from Kotlin code anymore. See screenshots below for an example.

Java code:
![Screenshot 2020-05-29 at 12 03 32](https://user-images.githubusercontent.com/11077217/83247973-a8fbbc80-a1a4-11ea-9a33-6d284d8fb288.png)

Kotlin code:
![Screenshot 2020-05-29 at 12 04 18](https://user-images.githubusercontent.com/11077217/83247978-aac58000-a1a4-11ea-8595-82b60ca0a6d2.png)

Workaround is to just use a Kotlin lambda:
![Screenshot 2020-05-29 at 12 17 28](https://user-images.githubusercontent.com/11077217/83249148-6e931f00-a1a6-11ea-96ef-cb28161a00dc.png)

But adding Slider.LabelFormatter breaks it again:
![Screenshot 2020-05-29 at 12 19 06](https://user-images.githubusercontent.com/11077217/83249266-a13d1780-a1a6-11ea-9576-5103c1800e28.png)

**Expected behavior:** No compile errors

**Material Library version:** 1.2.0-beta01

**Comment by Thomas-Vos** [comment]
Similar issue for addOnChangeListener when using the Android Studio autocomplete:

![Screenshot 2020-05-29 at 12 13 07](https://user-images.githubusercontent.com/11077217/83248722-cd0bcd80-a1a5-11ea-8405-ff4c7c209c67.png)

But in this case you can add `Slider.OnChangeListener` to fix it.

![Screenshot 2020-05-29 at 12 14 27](https://user-images.githubusercontent.com/11077217/83248841-f593c780-a1a5-11ea-8f3b-3b4ec9489b01.png)

**Comment by ymarian** [comment]
Thanks for providing the workarounds, I messed that up. We'll address soon and include in next beta or RC

**Comment by ymarian** [comment]
@Thomas-Vos Can you share an entire code snippet for the issue with the listener?
Also what version of Android Studio and of the Kotlin plugin are you using?

**Comment by ymarian** [comment]
Thanks for the details @Thomas-Vos it does seem this is an issue with Kotlin, I filled this if you want to follow the resolution:

https://youtrack.jetbrains.com/issue/KT-39265

We'll address the label formatter though

**Comment by adendiamond** [comment]
A workaround I am using is to make the slider a separate java class (this the only java file that I have written in my app)

```
public class JavaSlider extends Slider {

    public JavaSlider(@NonNull Context context) {
        super(context);
        init();
    }

    public JavaSlider(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    public JavaSlider(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init();
    }

    void init() {
        setLabelFormatter(new ProgressLabelFormatter());
    }

    static class ProgressLabelFormatter implements LabelFormatter {

        String formattedValue(int value) {
            switch (value) {
                case -1: return "PNS";
                case 15: return "PNA";
                default: return "P" + value;
            }
        }

        @NonNull
        @Override
        public String getFormattedValue(float value) {
            return formattedValue(Math.round(value));
        }
    }
}
```
