### ISSUE TITLE
MaterialDatePicker OK button is not fully visible (3 dots)

### ISSUE THREAD

**Issue by ghost** [material-components/material-components-android#1346]
This BUG appears only on the specific devices, the "OK" button is not fully visible, and it displays as a "3 dots".

**Current behavior:**
Nokia 7 Plus
![85e24d84-ab07-44ea-a83f-576edfa8f8a9](https://user-images.githubusercontent.com/46451579/83291214-45937e00-a1e8-11ea-8af9-9117f1e4fa76.png)

**Expected behavior:** 
Pixel 3:
![IMAGE 2020-05-29 20:04:36](https://user-images.githubusercontent.com/46451579/83290881-b1c1b200-a1e7-11ea-930b-c13e7c389ff8.jpg)

**Source code:** 
Extension function:
```
fun AppCompatActivity.datePicker(
    titleId: Int? = null,
    minusYears: Int = 0,
    minusDay: Int = 0,
    startDate: Long? = null,
    datePattern: String = DMY,
    dateChosen: (String, Long) -> Unit
) {
    val endDate = LocalDate().minusYears(minusYears).minusDays(minusDay)
    MaterialDatePicker.Builder.datePicker().apply {
        titleId?.let { setTitleText(it) }
        setCalendarConstraints(CalendarConstraints.Builder().apply {
            startDate?.let { setStart(it) }
            setEnd(endDate.toDate().time)
        }.build())
    }.build().run {
        addOnPositiveButtonClickListener {
            dateChosen.invoke(DateTime(it).toLocalDate().toString(datePattern), it)
        }
        show(supportFragmentManager, toString())
    }
}
```
On the place of call:
```
datePicker(
                R.string.some_str,
                PAST_18_YEARS,
                PAST_1_DAY
            ) { date, timestamp ->
                espUser.birthDate = timestamp.mlsToSeconds()
            }
```
**Android API version:** - 29

**Material Library version:** 1.2.0-alpha06

**Device:** : Nokia 7 Plus

**Comment by wcshi** [comment]
Based on [these specs](https://www.gsmarena.com/nokia_7_plus-9058.php), both the Nokia 7 Plus and the Pixel 3 have the same screen resolution: 1080 x 2160 pixels, 18:9 ratio (~403 ppi density)

Are you using a non-default screen display or font size setting?

**Comment by PavelPetkevich** [comment]
Hello @wcshi , 

Thank you for reacting to the issue.

Nop, both devices have all settings by defaults...

Nevertheless, as I found on the same website, pixel density (resolution) is not entirely the same:

[• Pixel 3: ~443 ppi density](https://www.gsmarena.com/google_pixel_3-9256.php)
[• Nokia 7 Plus: ~403 ppi density](https://www.gsmarena.com/nokia_7_plus-9058.php)

**Comment by sergiySVB** [comment]
on huawei p30 the same
![image](https://user-images.githubusercontent.com/62641230/83892471-619e9e80-a757-11ea-854a-1e3b2abad221.png)

**Comment by wcshi** [comment]
Tested on pixel 3a xl emulator which has [~402 ppi density](https://www.gsmarena.com/google_pixel_3a_xl-9690.php) and could not reproduce bug. 

Looks like Huawei P30 has [~422ppi](https://www.gsmarena.com/huawei_p30-9530.php)

**Comment by PavelPetkevich** [comment]
Hi @wcshi, I understand you that is hard to reproduce this kind of bug with emulator. I also tried to create the same device with emulator and unfortenutly same as you not be able to reporduce it. Nevertheless, I don't think so that is the point to clos this issue, I will send this task to our testers and they will try to reproduce it on Emulators. Also, I will be happy if you will try it from your side on different real devices not only on the Pixels, mostly on them everything works perfectly.

Thank you and see you again soon.

**Comment by NikolaiPN** [comment]
Hello,
I have exactly the same problem. I have tested my app on physical device and there is no problem there, but when I test on emulator the "OK" button becomes "..." which to me is indication that the width of the button is not enough. When I inspect the layout The layout_width of both buttons is wrap_content but the negative button is much wider than it's content "Cancel".

**Comment by wcshi** [comment]
@NikolaiPN could you please share the device configs of the emulator you used to reproduce the bug?

**Comment by leticiarossi** [comment]
@PavelPetkevich or anyone else having the issue, could you confirm if it has been fixed after this commit https://github.com/material-components/material-components-android/commit/d868be243c1116de62e000af75dd78127d1cc10d ?
You can test it with [our daily snapshots](https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md). The snapshot with the commit should be available as of tomorrow.

**Comment by PetkevichPavel** [comment]
Hi @leticiarossi , we will test it as soon as possible and write you back after. Thank you and have a nice day.

**Comment by PavelPetkevich** [comment]
Hi @leticiarossi , we will test it as soon as possible and write you back after. Thank you and have a nice day.

**Comment by BlackGoblin** [comment]
I'm still facing this issue on Huawei P40 lite and `com.google.android.material:material:1.3.0-alpha02`

**Comment by Verdant90** [comment]
Has this been fixed? still getting the ellipsis :(

**Comment by yavski** [comment]
@wcshi can this be reopened and fixed properly? I'm also observing the same issue with a Huawei P40 device.

**Comment by wcshi** [comment]
@yavski which version of the library are you using?

**Comment by yavski** [comment]
@wcshi I'm using `1.2.1`, I see that [the positive / confirm button](https://github.com/material-components/material-components-android/blob/c8197e3a26f0c56964427bea438cc95a8440ff29/lib/java/com/google/android/material/datepicker/res/layout/mtrl_picker_actions.xml) uses [@android:string/ok](https://github.com/material-components/material-components-android/search?p=1&q=mtrl_picker_confirm.) string res internally; it made me think this is about some Locale and the framework can't resolve the string resource and it falls back to truncated text. Do you think that's likely?

**Comment by HariniAndroid** [comment]
@wcshi @yavski was mentioned , I am also getting the same issue .
I am have tried latest 1.3.0-alpha04 , but still i am not able find OK button in Huawei P40 device.
can this be reopened and fixed properly? 
kindly please refer the screenshot .
<img width="327" alt="Screenshot 2020-12-16 at 1 19 47 PM" src="https://user-images.githubusercontent.com/76096389/102325374-13414680-3fa9-11eb-9727-f18c83cf3e68.png">

**Comment by HariniAndroid** [comment]
Team is there any Update regarding this issue?

**Comment by HariniAndroid** [comment]
@wcshi Is there any update about this defect?

**Comment by wcshi** [comment]
Sorry we are having trouble reproducing this bug.

**Comment by HariniAndroid** [comment]
@wcshi as mentioned early , we are testing in Huawei P40 device we are still see this issue,
Can you please let me know if any new version is updated.

**Comment by mfzagal** [comment]
Huawei P40 Lite version (JNY-LX2) Same Issue

**Comment by HariniAndroid** [comment]
Hi Team,
@wcshi 
Kindly Please make this high priority of the bug fixing,
Most of them facing this issue.

**Comment by matecheck27** [comment]
> Sorry we are having trouble reproducing this bug.

Hello, any update regarding with the issue? we're now using 1.4.0-alpha01, but we still getting the issue.

**Comment by matecheck27** [comment]
Hello, I just want to update this thread, we've fixed this bug with overriding the string resource used by material design.

just put this in your string xml
<string name="mtrl_picker_confirm" description="Button text to indicate that the widget will save the user's selection [CHAR_LIMIT=16]">OKAY</string>

by the way, we're using, 1.4.0-alpha02 version.

**Comment by Papashkin** [comment]
Agree with @matecheck27.
Only one solution works for me:

```
<string name="mtrl_picker_confirm" tools:override="true">Ok</string>
```

**Comment by eddiemuc** [comment]
Many thanks to @matecheck27 for providing this easy workaround! We had the same problem (using V1.3.0), now it works like a charm!

**Comment by drchen** [comment]
It did look like the Android framework string is missing on certain OEM devices. (Material is using @android:string/ok for the button.) I guess we can fix it by replacing the string with proper values.
