### ISSUE TITLE
[Transition] Bug: sample of "transition" cause no transition and resets scrolling in some cases

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#1349]
**Description:** 
In the sample, if you click a partially visible item and go back, there is no transition and the list gets reset to a different scrolling state.

**Expected behavior:** 
Have transition back, as we had a transition to go forward, and let the list stay as it was before entering

Here's how it looks like:
[device-2020-05-30-104648.zip](https://github.com/material-components/material-components-android/files/4705279/device-2020-05-30-104648.zip)

**Source code:** 
It's the sample of "catalog", when pressing on "transition".

**Android API version:** 
API 29 

**Material Library version:** 
The repository is a mess. Really hard to find the version. I hope this helps:

  androidXVersions = [
    annotation            : '1.0.1',
    appCompat             : '1.1.0',
    cardView              : '1.0.0',
    constraintlayout      : '1.1.3',
    coordinatorlayout     : '1.1.0',
    core                  : '1.2.0',
    experimental          : '1.0.0',
    fragment              : '1.0.0',
    lifecycle             : '2.0.0',
    recyclerView          : '1.0.0',
    recyclerViewSelection : '1.0.0',
    transition            : '1.2.0',
    vectorDrawable        : '1.1.0',
    viewpager2            : '1.0.0',
    dynamicanimation      : '1.0.0',
  ]

  mdcLibraryVersion = '1.2.0-alpha06'

**Device:** 
Pixel 4

**Comment by AndroidDeveloperLB** [comment]
Closed because fixed?

**Comment by hunterstich** [comment]
Yep, this should be fixed in https://github.com/material-components/material-components-android/commit/03145403669f8515207ee02fcec9e122e0e440b4

**Comment by AndroidDeveloperLB** [comment]
Available if I clone from main one?

**Comment by hunterstich** [comment]
Yep. If you clone the `master` branch and run the catalog, the main transition demo should retain scroll positions correctly now

**Comment by AndroidDeveloperLB** [comment]
@hunterstich Can't confirm. Still has various glitches, especially when changing orientation. See:

[aC8kgwTsmA.zip](https://github.com/material-components/material-components-android/files/5164213/aC8kgwTsmA.zip)

Also, check this one of "Container Transform" . It lets you click things behind the FAB's menu, and yet the menu is on top of them, and it stays this way.  Clicking back key also doesn't close the menu.
The transition is bad on this too, as it overlaps the menu of the FAB. For a moment it's on top of it, and in the end it's below.

[rAtlqOkhlG.zip](https://github.com/material-components/material-components-android/files/5164232/rAtlqOkhlG.zip)

**Comment by hunterstich** [comment]
Got catch. I'll look into it

**Comment by AndroidDeveloperLB** [comment]
@hunterstich Speaking about the "transition" sample, can you please tell me if there is some minimal tutorial/sample of FAB transition? 
I mean of these types:
https://material.io/components/buttons-floating-action-button#types-of-transitions

"Speed dial" and "Transform into a menu with the related actions".
Only the second is on the current repository, and even then it has a lot of code that doesn't seem required. 
And I don't see one of the first type.

**Comment by hunterstich** [comment]
Re: swapping - Yes, exactly. You'd switch your start and end views and change back the visibility to get the reverse transition. 

I just wrote that snippet in GH so it might not be exactly copy-pastable, but that should be all you need to run a container transform. There's a section in the [Motion.md](https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md#container-transform) documentation under `Container transform`>`Transition between views` that has additional info around how to configure what would be a FAB->Card, or similar, transform.

**Comment by AndroidDeveloperLB** [comment]
@hunterstich Interesting. To have dialog/menu-like effect, though, you'd need to add some semi-transparent background, too, right? and block touches on it, while also handling back-key.

About "Speed dial", why isn't it offered? Something bad about using this style? Too old?

**Comment by hunterstich** [comment]
We also have [Reply](https://github.com/material-components/material-components-android-examples/tree/develop/Reply), a sample app that uses Material motion, if you want some additional examples of how to use the transitions. There's a transition from a Chip to a Card ([spec](https://kstatic.googleusercontent.com/files/1830b26386c564bbebf730f05f5cffc7eea37d91df75e0bcf16993d84925277de6f7771483aec035ac80aba24a11facad436ba679390761bc90c7ba345daf3c5) | [implementation](https://github.com/material-components/material-components-android-examples/blob/develop/Reply/app/src/main/java/com/materialstudies/reply/ui/compose/ComposeFragment.kt#L153-L170)), which uses the same formula as what you would need for a FAB to a Card.

The documentation also has a bunch of additional [resources](https://medium.com/androiddevelopers/material-motion-with-mdc-c1f09bb90bf9), like codelabs and blog posts, if you're interested.

**Comment by hunterstich** [comment]
Re: Speed dial - https://github.com/material-components/material-components-android/issues/12

**Comment by AndroidDeveloperLB** [comment]
@hunterstich While I do like to try&see amazing samples , I also like to try out samples to learn how to do things, and for that I prefer to see the minimal of the minimal code possible, to avoid looking at stuff that are not relevant or are optional.

Google tends to work on amazing samples usually. That's why it's hard for me to learn from it, and then I just think to myself "wow how did they do this?" instead of "ok I'm going to do this too".

About speed-dial, thanks. It was written there "adopt better patterns for their particular use case", but it doesn't say which. I guess it's the one with the card as you've shown here?

**Comment by hunterstich** [comment]
@AndroidDeveloperLB Gotcha! Well if you get stuck looking through Reply, the catalog, or the documentation and need helping creating what you're looking for, let me know. Maybe you could create your own minimal sample for a FAB to Card transition, ping the repo here, and I can help if you run into questions or issues : ).

**Comment by AndroidDeveloperLB** [comment]
@hunterstich Thank you!

**Comment by AndroidDeveloperLB** [comment]
@hunterstich I've succeded implementing it, but I have some issues with it:
1. As you wrote, there is a "scrim". It's shown during the transition which is nice, but not at the end.The sample avoid this. 
2. Not sure how to make the scrim to fill the entire screen (including system bars), including being on top of all views except the card. The transition doesn't seem to  be set on the entire screen like a dialog, but even if it did, I need to do the same and yet let only the cardView to stay on top, while the rest, which might have elevation (example is a button).
I tried to set translationZ to the scrim, but then it is also on top of the card for some reason, even if the translationZ I set for the card is higher.
3. Even if I somehow solve this, not sure I can make it work well for old Android versions, because there is no translationZ for them.

Here's what I did:

[TransitionFabSample.zip](https://github.com/material-components/material-components-android/files/5171600/TransitionFabSample.zip)

I've noticed another issue on the sample regarding this. On dark theme, the icons of the items stay dark, so it's dark icons on dark cards...

**Comment by hunterstich** [comment]
Hey @AndroidDeveloperLB ,

I just took a look at your sample.

2. 
Making the scrim go edge-to-edge is a matter of setting your `systemUiVisibility` flags correctly (or using the new `window.setDecorFitsSystemWindows(false)` method). There is a bunch of great content on this. See [Animating your keyboard > How do apps go edge-to-edge?](https://medium.com/androiddevelopers/animating-your-keyboard-fb776a8fb66d). You also *might* need to use a `.NoActionBar` theme and manually include an `AppBarLayout` in your xml file so you can better control the z-ordering of your views (if you want the scrim to be above your app bar).

3.
As far as your sample's z-order bug goes. The only way I can see to fix this is to set the view elevations manually - e.g. the scrim is given a 14dp elevation with `ViewCompat.setElevation` and the card is given a 16dp elevation. On older versions of Android, views should be drawn in the order they appear in your layout. As long as the views are in the correct order in your xml layout, the scrim should be properly drawn above the button.

**Comment by AndroidDeveloperLB** [comment]
@hunterstich 
2. Thing is, this should be possible and shown on the sample, because there is no reason to have both the expanded FAB with all that's around it. 
And we should be able to mimic how it works with DialogFragment/Dialog.
Why is it related to keyboard though?
3. As for the issue, using Z or elevation won't work on older Android versions, and material library is used for them too. 
We should have a solution that work for them as well. 
In fact, it's quite problematic to have the scrim effect (the transition that animates its alpha) if it can't cover the entire screen because it needs to also be constrained so that the card will be in the same position as the FAB. 

I don't think an expandable FAB is usable if used like on the sample. 

How could you achieve all of these on all Android versions? 
Can you please fix (or improve, depending on how you see it) the sample to have these?
