### ISSUE TITLE
BottomAppBar replaceMenu() doesn't work

### ISSUE THREAD

**Issue by BulatMukhutdinov** [material-components/material-components-android#135]
### Overview
BottomAppBar replaceMenu() has no effect. Also, setting menu through XML also has no effect

### Version number
com.google.android.material:material:1.0.0-alpha1

### Operating system and device
MacOS, Nexus 5X

**Comment by firatkarababa** [comment]
Does your activity extends AppCompatActivity?

**Comment by BulatMukhutdinov** [comment]
Yes, it extends androidx.appcompat.app.AppCompatActivity

**Comment by firatkarababa** [comment]
Without seeing your code I cannot comment much but I have made it work.
I have written the implementation details on Medium, can you check the link below to see what is missing?

https://android.jlelse.eu/implementing-bottomappbar-material-components-for-android-f490c4a01708

**Comment by firatkarababa** [comment]
The problem seems to be `setSupportActionBar(bottomAppBar)` used together with `replaceMenu`. Just remove setSupportActionBar and everything will be fine.

**Comment by BulatMukhutdinov** [comment]
Yes, it works now. Thank you!
