### ISSUE TITLE
[SwipeRefreshLayout] After dragging and returning to the initial position manually, the elevation of the view is visible.

### ISSUE THREAD

**Issue by Madina-S** [material-components/material-components-android#1352]
**Description:** After the dragging bottom occurred, and the view is dragged to the top to the initial position, the swipe refresh does hide entirely (the elevation is visible).

 https://youtu.be/QMXUFL1BVjE

**Source code:** `<androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/swipeRefreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:clipToPadding="false"
            android:clipChildren="false"
            android:layout_height="match_parent" />
    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>`

**Android API version:** 29

**Material Library version:** 1.2.0-alpha06

**Comment by ymarian** [comment]
Please file in the right component:
https://issuetracker.google.com/issues/new?component=460836&template=1422576
