### ISSUE TITLE
[ConstraintLayout]TransitionListener Bug since beta05

### ISSUE THREAD

**Issue by samirbasnetview9** [material-components/material-components-android#1355]
When using motion layout and transition listener since beta05 of constraint layout the onTransition Completed method is called multiple times (in my case 3 times). It was ok till beta 4. 

` binding.container.setTransitionListener(new MotionLayout.TransitionListener() {
            @Override
            public void onTransitionStarted(MotionLayout motionLayout, int i, int i1) {

            }

            @Override
            public void onTransitionChange(MotionLayout motionLayout, int i, int i1, float v) {

            }

            @Override
            public void onTransitionCompleted(MotionLayout motionLayout, int i) {
                Log.d("Splash", "onTransitionCompleted: called ");
                startActivity(new Intent(context, MainActivity.class));
                finish();

            }

            @Override
            public void onTransitionTrigger(MotionLayout motionLayout, int i, boolean b, float v) {

            }
        });`

That onTransitionCompleted method is called 3 times but it gets called only once in beta04 of constraint layout. Also checked in new beta06 of constraint layout and same issue

Tested Device: MiA2
Android Version: Android 10(q)

**Comment by MGaetan89** [comment]
This is the repository for Material Components Android.
To reports an issue with ConstraintLayout, please use the following form: https://issuetracker.google.com/issues/new?component=323867&template=1023345
