### ISSUE TITLE
Backgroud color of root view  changing automatically when click on material button

### ISSUE THREAD

**Issue by RR-Reddy** [material-components/material-components-android#1357]
sample project : 
[gradientEx.zip](https://github.com/material-components/material-components-android/files/4709678/gradientEx.zip)

steps to reproduce 
1) install app from above sample app
2) click on button 

issue : the background color of ConstraintLayout is changing 
expected: the background color of ConstraintLayout  should respect the attribute value of android:backgroud

**Comment by ymarian** [comment]
It's not recommended to name your color colorPrimary.
https://www.youtube.com/watch?v=Owkf8DhAOSo&t=1056s. 

We can amend the docs for that, my guess is that this is causing a collision too. Renaming them should work
