### ISSUE TITLE
[ExtendedFloatingActionButton] Touch ripple animation is systematically aborted on touch up

### ISSUE THREAD

**Issue by LouisCAD** [material-components/material-components-android#1359]
**Description:** Contrary to regular `MaterialButton` and `FloatingActionButton`, `ExtendedFloatingActionButton` has an issue where when the finger leaves the screen after having touched it, the ripple animation is aborted, giving a rough look and feel, which also feels inconsistent with how the ripple nicely starts, and how it works in other components.

**Expected behavior:** The ripple animation should not be aborted, but should signal touch up just like `FloatingActionButton`, `MaterialButton` and other components do.

**Source code:** This can be tested with the material builder already existing in this repository.

**Android API version:** Tested on API 29 (Android 10)

**Material Library version:** 1.2.0-beta01

**Device:** Tested on a Google Pixel 2 XL

**Comment by dummyco** [comment]
Experiencing the same issue:

![vg6QfhdcXY](https://user-images.githubusercontent.com/3989453/85926304-3e26c980-b8a7-11ea-8f24-0d41c910c04f.gif)

**Comment by ymarian** [comment]
I closed in this in 61e927e you should be able to workaround it before a new release, by setting app:rippleColor to a copy of the CSL in that commit

**Comment by LouisCAD** [comment]
Could you cherry pick it to 1.2.0?

**Comment by ymarian** [comment]
@LouisCAD will do!
