### ISSUE TITLE
Issue #882 happened again in 1.2.0-beta01

### ISSUE THREAD

**Issue by Vadim-Smirnov** [material-components/material-components-android#1360]
Datepicker to highlight wrong the day as today

**Comment by ColtonIdle** [comment]
I see that https://github.com/material-components/material-components-android/issues/882 is related to datepicker.

Can you try version 1.3.0-alpha01?

They just released it with a few fixes under the "MaterialDatePicker" category. Looks like this issue is in that list.

https://github.com/material-components/material-components-android/releases/tag/1.3.0-alpha01

**Comment by b95505017** [comment]
@ColtonIdle It's the same commit cherry-pick to beta release, so nothing has changed.

**Comment by Vadim-Smirnov** [comment]
@ColtonIdle I see that they marked it as fixed, but really nothing changed.

**Comment by DvTonder** [comment]
The issue still exists for users in UTC + timezones like British standard time (UTC+1)

**Comment by postfixNotation** [comment]
I'm experiencing the same issue with **1.3.0-alpha01**, I'm in Germany UTC+2.

**Comment by Manu-Jindal** [comment]
Even I am facing this problem, I am in India Timezone (GMT+5:30), and the current date is showing to be yesterdays date.
@ymarian @wcshi, any idea when the change will be rolled out? Kindly try to look into this with priority as it is a production app where we are facing this issue.

Using version 1.3.0-alpha01

**Comment by wcshi** [comment]
Hi @Manu-Jindal this commit (https://github.com/material-components/material-components-android/commit/712a2ce92040b6fc90530ad853633ecd7f258dfc) was made after the 1.3.0-alpha01 cut. It is in our [daily release](https://github.com/material-components/material-components-android/packages/81484), could you please try it to verify whether it fixes the problem you are facing?
Here are some instructions for how to use the daily build:
https://github.com/material-components/material-components-android/issues/824#issuecomment-567044986

**Comment by Manu-Jindal** [comment]
Hi @wcshi, it worked! Thanks a lot! :D

**Comment by ed-george** [comment]
Do we have any idea when this will make it into a release? It seems like the project is on roughly a monthly release cycle so can we expect this in July's release?

**Comment by Abu-Abdullah** [comment]
Hi @wcshi 
i used the `material-1.3.0-20200711.074248-15.aar` and it seems it solves one issue of highlighting the initial current day. on the other hand, it seems it still has an issue when i use setSelection(long ms). it is not accounting for the time zone offset and is selecting the day prior.

**Comment by ymarian** [comment]
@Abu-Abdullah It's simpler for us to maintain everything in UTC and let the client do conversions. Please let us now if any method is not document correctly.

**Comment by aoben10** [comment]
Still confused by this. So the picker displays UTC dates by default, and if we wanted to use date in local timezone, we would have to convert the selected date on the picker to local date. Wouldn't that mean the user could select a certain day and local time could show the previous day? Wouldn't that be confusing for the user?

Struggling to figure this one out

**Comment by VincentJoshuaET** [comment]
I think doing setSelection(${epochMilliInUTC} + TimeZone.getDefault().rawOffset) does the trick!

**Comment by vishalpatel1327** [comment]
Having the same issue in  **material:1.3.0**  ;(

**Comment by ubuntudroid** [comment]
I was confused by all of this as well and just want to sum up how to do things properly client side.

To properly set the selection in UTC:

```
MaterialDatePicker.Builder.datePicker()
    .setSelection(localTimeInMillis + TimeZone.getDefault().getOffset(localTimeInMillis))
```

To properly retrieve selection in local time:

```
val localTimeInMillis = selection - TimeZone.getDefault().getOffset(selection)
```

And I agree, this should really be part of the documentation.

**Comment by NonCoderF** [comment]
val finalDate = (SpecificDate?.time ?: 0L)
        val timeOffset = TimeZone.getDefault().getOffset(finalDate).toLong()

        val datePicker = datePicker {
            this.date = finalDate + if (timeOffset > 0) timeOffset else - timeOffset
            this.validTo = Date().time + timeOffset
            this.positiveButton(context.getString(R.string.common_global_okay)) { _, y ->

                val offset = TimeZone.getDefault().getOffset(y).toLong()

                val selectedDate = y + if (offset > 0)  offset else - offset
            }
        }
        datePicker.safeShow((context as AppCompatActivity))
        
        DatePicker is a wrapper DSL over the MaterialDialog.........
        
        The offset is added and subtracted accordingly. You guys can figure out the rest.....CHILLLLLL
