### ISSUE TITLE
[ChipGroup] Uncheck a single chip

### ISSUE THREAD

**Issue by ffloreani** [material-components/material-components-android#1369]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to uncheck a single chip in the ChipGroup. Currently, I can only clear the entire selection.

**Describe the solution you'd like**
A method in the API that can be called with the ID of a chip that should be unchecked. Something like `clearCheck(chipId: Int)`.

**Comment by wcshi** [comment]
Seems reasonable, just curious, could you please explain your use case?

**Comment by ffloreani** [comment]
I'm using filter chips in a chip group and would like to be able to add some business logic between the chips. 

For example, I have 3 chips - Apple, Banana, Citrus. If Apple & Banana are selected, Citrus can't be selected. 
Say the user selected Apple & Citrus, and wants to select Banana. When this happens, I'd like to programmatically uncheck Apple & Citrus, leaving the user with just Banana.

This may not be the clearest example, but should show the purpose of this request. 🙂

**Comment by wcshi** [comment]
@ffloreani you can already programmatically uncheck any chip you like by finding it and calling chip#setChecked(false). ChipGroup#clearCheck does something similar by iterating through all of its child chips.
