### ISSUE TITLE
Cutted cradle shape on top of BottomAppBar

### ISSUE THREAD

**Issue by tommybuonomo** [material-components/material-components-android#137]
### Overview
![BottomAppBar](https://material.io/design/assets/1XkzfKt_zJQXv0GWH4wy0tfNNI5dMfkmp/appbarbottom-posivibes-ahero.png)

I want to achieve this top cradle cutted edge for the BottomAppBar.
The problem is the BottomAppBar have a BottomAppBarTopEdgeTreatment that only draw a rounded path.

Any ideas how to do it?

### Version number

com.google.android.material:material:1.0.0-alpha3

**Comment by firatkarababa** [comment]
I am looking into that as well but I do not think that FAB button will be supported given the available BottomAppBar attributes. Defining your custom shape for FAB and cradling it into bar through fabAttached=true attribute could be a way to achieve that but I didn't try it out. 

Btw I could not find this Chill Vibes study within material.io website, is it removed?

**Comment by NickM-27** [comment]
You can set the radius of the BottomAppBar corners right? So maybe using that will at least allow for the BottomAppBar to have the correct look and then a custom FAB background would do the rest?

**Comment by VyMajoris** [comment]
1+

Please add some guide on how to customize the shape of the FAB and the BottomAppBar.

**Comment by charlieAndroidDev** [comment]
This hasn’t been implemented yet, just be patient guys, i know it’s frustrating...

![04669a5d-9bc6-48d8-bde9-e8e8aba2162d](https://user-images.githubusercontent.com/18074024/42155493-74715d92-7de0-11e8-9aad-119578bb9a71.jpeg)

**Comment by firatkarababa** [comment]
In the road map, the date for Shape Theme release and Shape Theme support for buttons is given as R18 - August 2018
[Roadmap link](https://github.com/material-components/material-components/blob/develop/ROADMAP.md#r18---august-2018)

**Comment by cketcham** [comment]
Yes unfortunately it isn't ready yet, but we're working on shape theming this quarter.

**Comment by ESLHemantSangle** [comment]
@cketcham well i am still not able to do this with 'com.google.android.material:material:1.1.0-alpha05'  version of library

**Comment by ikim24** [comment]
This is being tracked in https://issuetracker.google.com/issues/127454207
