### ISSUE TITLE
[ChipGroup] Define maximum selection

### ISSUE THREAD

**Issue by ffloreani** [material-components/material-components-android#1370]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set the maximum number of chips in the chip group that can be selected. For example, say that the group has 10 chips, I'd wish to define that only 5 chips can be selected at any one time. 

**Describe the solution you'd like**
An XML attribute and an API method that limits the maximum number of chips that can be selected. Mirroring the existing `app:singleSelection="true|false"`, maybe we could have `app:maxSelection="integer"`.

**Comment by wcshi** [comment]
Could you please explain your use case?

**Comment by ffloreani** [comment]
**Use case:**

I have a bunch of chips in a multi-select chip group. The chips represent a user's interests. One of the business rules states that the user can select up to 4 interests, meaning that only up to 4 chips may be selected.

I haven't seen a way to limit the number of selected chips anywhere in the API (apart from the single selection option).

**Comment by wcshi** [comment]
This sounds like business logic to be handled on your end and not the intent of chipgroup.

**Comment by ffloreani** [comment]
Eh, you're probably right, it does seem a bit specific. I was tempted by the `singleSelection` attribute and just didn't think it through properly. Now that I've learned how to unset a single chip, that's not a bad idea. Thanks for your assistance! 🙂
