### ISSUE TITLE
[MaterialButton] app:iconGravity="textEnd" not working properly

### ISSUE THREAD

**Issue by edvaldeysteinsson** [material-components/material-components-android#1371]
**Description:**
When creating a MaterialButton that has an icon and is **android:layout_width="match_parent"**
and has **android:textAlignment="viewStart"** the **app:iconGravity="textEnd"** 
seems to place the icon in the middle between the end of the text and the end of the view.
![icon_gravity_issue](https://user-images.githubusercontent.com/608698/83665947-769af680-a5cc-11ea-9e3c-9598f857d8f6.png)

**Expected behavior:**
I would expect it to place the icon at the end of the text like this
![icon_gravity_expected](https://user-images.githubusercontent.com/608698/83666209-dc877e00-a5cc-11ea-8c3e-dfb2445571b3.png)

**Source code:**
<com.google.android.material.button.MaterialButton
        android:layout_width="match_parent"
        android:layout_height="48dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:textAlignment="viewStart"
        android:textColor="?attr/colorOnPrimary"
        app:icon="@drawable/ic_right_arrow"
        app:iconGravity="textEnd"
        app:iconPadding="8dp"
        app:iconTint="?attr/colorOnPrimary"
        android:insetLeft="0dp"
        android:insetRight="0dp"
        android:insetTop="0dp"
        android:insetBottom="0dp"
        android:paddingHorizontal="8dp"
        app:cornerRadius="0dp"
        style="@style/Widget.MaterialComponents.Button.UnelevatedButton"
        android:text="Checkout now" />

**Android API version:**
29

**Material Library version:**
1.3.0-alpha01

**Device:**
Pixel 3XL

**Comment by Toubap** [comment]
Same here :/

**Comment by drchen** [comment]
I cannot reproduce the issue on my end. Can you confirm if this is still reproducible with the latest library version?

**Comment by edvaldeysteinsson** [comment]
Yes, still the same issue. Checked in both `1.5.0-rc01` and `1.6.0-alpha01` and this is how it looks.

![button](https://user-images.githubusercontent.com/608698/148846669-dacc70e0-877f-4673-8136-f334987193e3.png)

**Comment by drchen** [comment]
Ah cool. I guess I figured out the reason. android:textAlignment="viewStart" is not taken into account in the icon positioning logic. I'll try to make a fix. Thanks for providing the info!
