### ISSUE TITLE
[R.dimen.abc_action_bar_content_inset_material] Marked as private R.dimen.abc_action_bar_content_inset_material

### ISSUE THREAD

**Issue by F4bioo** [material-components/material-components-android#1372]
The resource @dimem/abc_action_bar_content_inset_material is marked as private in com.google.android.material:material

**Comment by ymarian** [comment]
This is an appcompat resource, it's not declared in our library please consider filling a bug in their issue tracker:
https://issuetracker.google.com/issues/new?component=460343&template=1422420
