### ISSUE TITLE
[MaterialCheckBox] Wrong colors if colorAccent is defined in the theme

### ISSUE THREAD

**Issue by gabrielemariotti** [material-components/material-components-android#1378]
**Description:** If in the app theme is defined the `colorAccent` attribute

```
  <style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
    <item name="colorAccent">@color/colorAccent</item>
    ....
  </style>
```
the selected state of the  `MaterialCheckBox` is tinted by the `colorAccent` instead of `colorSecondary`.

**Expected behavior:** 
The color of the checbox defaults to `?attr/colorOnSurface` (unchecked) and ?`attr/colorSecondary` (checked) defined in the app theme.

**Material Library version:** 1.2.0-beta01

**Comment by matpag** [comment]
Following the table below:
![image](https://user-images.githubusercontent.com/4432213/84550632-6e993000-ad0b-11ea-8984-49a277ecc4b4.png)
took from [here](https://medium.com/androiddevelopers/migrating-to-material-components-for-android-ec6757795351), this seems to be the correct behaviour.

Currently `MaterialCheckBox`, `MaterialRadioButton`, `SwitchMaterial` and `MaterialToolbar` still rely on old colors like `colorControlActivated`.

`colorAccent` should not be used in a non-bridged Material theme, based on the migration guide above, and there is an open proposal by Nick [here](https://github.com/material-components/material-components-android/issues/1376) to add lint warnings to prevent this.

With a non-bridged material theme like this:
```
  <style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
    <item name="colorControlActivated">#3330F6</item>
    <item name="colorSecondary">#BA0938</item>
     ....
  </style>
```
the color priority is: `colorControlActivated` ->  `colorSecondary`

If we use a bridged theme:
```
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.Bridge">
  <item name="colorAccent">#32A852</item>
  <item name="colorControlActivated">#3330F6</item>
  <item name="colorSecondary">#BA0938</item>
  ...
</style>
```
the color priority is: `colorControlActivated` ->  `colorAccent` and `colorSecondary` is ignored at all which doesn't seem correct to me.

Should we consider all material colors in the bridge?
For example, If I move [those lines](https://github.com/material-components/material-components-android/blob/c596a77a313e2d6140310efabcbcf8a67625dc0e/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L75-L81) inside the bridge theme [here](https://github.com/material-components/material-components-android/blob/147620fc10694b9756f24746b7428a62fa4264ef/lib/java/com/google/android/material/theme/res/values/themes_base_bridge.xml#L33-L35), `colorSecondary` is correctly considered as the third color option in bridged themes.

**Comment by drchen** [comment]
I'll close this issue as obsolete since Material 3 has a very different color settings.
