### ISSUE TITLE
Can material components be used under AS 3.1.2

### ISSUE THREAD

**Issue by kingofswing** [material-components/material-components-android#138]
### Overview

Just try to make it work under Android Studio 3.1.2  but failed, It seems we have to use the 
latest Preview ver. of AS?

### Version number
Android Studio 3.1.2 
 compileSdkVersion 'android-P'

`implementation 'com.android.support:appcompat-v7:28.0.0-alpha1'`
` // https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md`
`implementation 'com.google.android.material:material:1.0.0-alpha3'`
`implementation 'com.android.support:design:28.0.0-alpha1'`

can the upper two coexist in the project ? 

`implementation 'com.android.support:support-v4:28.0.0-alpha1'`

I've already install a new 3.2 canary-14 version of AS, but one of dependencies:
`'cn.bmob.android:bmob-sdk:3.6.2'`  didn't work under the preview verison, so have to 
stick to AS 3.1.2.

Having done through the steps provided with no errors, but can't continue at the step of 
 `Refacto Android X`.  So if click `Run`, then got the error:
`Error: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver`

**Comment by dsn5ft** [comment]
Yes that would be possible, here are the dependency and class mappings you would have to use for the refactor - https://developer.android.com/topic/libraries/support-library/refactor.
