### ISSUE TITLE
[ProgressBarIndicator] Don't hide if calling show/hide is too fast

### ISSUE THREAD

**Issue by kimcy929** [material-components/material-components-android#1382]
**Material design version 1.3.0-alpha01**
**Test device: Galaxy S10+ Android 10, Galaxy J5 Android 6.0.1**

ProgressBarIndicator didn't hide if I called show/hide too fast. I need to call in next time to hide it or call immediately **set progressBarIndicator.isGone = true** but it will not have animation or **delay(1second)** before progressBarIndicator.hide(). It is the same the case when I use ContentLoadingProgressBar.

```kotlin
launch {
     progressBarIndicator.show()

     val videos = videoModel.getVideos()
     videosAdapter.addData(videos.toMutableList())

     //delay(1000L)
     progressBarIndicator.hide() // don't hide if time between show and hide not enough long
 }

```

```xml
<com.google.android.material.appbar.AppBarLayout
            android:id="@+id/appBar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:elevation="0dp">

            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_scrollFlags="scroll|enterAlways">

                <com.google.android.material.appbar.MaterialToolbar
                    android:id="@+id/toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="?attr/actionBarSize"
                    android:background="?themePrimary"
                    app:title="@string/videos" />

                <com.google.android.material.progressindicator.ProgressIndicator
                    android:id="@+id/progressBar"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/Widget.MaterialComponents.ProgressIndicator.Linear.Indeterminate"
                    android:layout_gravity="bottom"
                    android:visibility="gone"
                    app:growMode="outgoing"
                    app:indicatorColor="?colorSecondary"
                    tools:visibility="visible"/>

            </FrameLayout>

</com.google.android.material.appbar.AppBarLayout>
```

**Comment by matpag** [comment]
I think we should have a new property to emulate the `ContentLoadingProgressBar`.
Something like: `app:minHideDelay="millis"` in XML.
Where we can set a minimum delay and if `hide()` is called before this time is expired, it will schedule the `hide()` to act when delay has ended.

This is a common use case to improve UI experience.

**Comment by ymarian** [comment]
@matpag That sounds like a reasonable addition to me, but shouldn't we fix the root issue first, cancelling ongoing animators and executing the new request ones? Were you planning to address both things?

**Comment by matpag** [comment]
@ymarian You are right, we should keep the issue clean.
I've created a PR for the bug.

I will create a new feature request/PR for the additional feature

Let me know if I have to do more work

**Comment by pekingme** [comment]
@matpag thanks for working on the issue. As 1 of 2 steps to resolve this, your PR has been merged. Would you still like to continue working on this? If so, please assign yourself to this issue. About the next step, I have some other thoughts. Let me know what you think.

When `hide()` is called before enter animator finishes, we can either 1) start the exit animator immediately or 2) wait until enter animator finishes. If `hide()` is called after enter animator finishes, it will just start exit animator. So if there's no other case, then we may only need a binary attribute for whether skip the enter animator when `hide()` is called. Then we can utilize the animator callback to schedule exit animator if it's set to false (or not skip).

**Comment by matpag** [comment]
I can sure try to work on this.

My idea was to emulate the ContentLoadingProgressBar, with a variable delay which could be set by the user from XML (max capped at 1 second).
In this way, someone can add a delay which is greater than the enter animation duration if they want

**Comment by pekingme** [comment]
Thanks for contributing to MDC Android! Your idea also sounds good to me. It could involve with more changes but make the component more customizable. Let me assign it to you. And let me know if you need any help on this.

**Comment by matpag** [comment]
Perfect 👍 
Will start to work on this tonight
