### ISSUE TITLE
[TextInputLayout] Restore hint in config change

### ISSUE THREAD

**Issue by JulioCottaN26** [material-components/material-components-android#1384]
**Description:** 
Hint is not properly restored when a config change happens

**Expected behavior:** 
To show the same hint as before a config change

**Source code:** 
```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        if (savedInstanceState == null) {
            inputLayout.setHint("Hint 1")
            editText.setText("Text 1")

        }
    }
}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".MainActivity">

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/inputLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/editText"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </com.google.android.material.textfield.TextInputLayout>

</LinearLayout>
```

Rotate the screen and verify that the hint is not displaying anymore.

Tested in 1.3.0-alpha01

**Comment by joost-klitsie** [comment]
Okay so now when I change the language of my phone or in the application itself the hint (and I guess helpertext) is no longer translated, as it restores the old state. Any hints (aside from the obvious programmatically having to set the values myself) for that?

**Comment by jorisdeguet** [comment]
Same behavior here TextInputLayout hint is not translated when the configuration is changed.

**Comment by Mil0o118** [comment]
I have the same problem. The EditText works perfectly, but if I change to TextInputLayout it doesn't work anymore! If I program the values ​​myself it works, but it would be great if it was automatic like the others.
