### ISSUE TITLE
[MaterialButtonToggleGroup] `checkedButtonIds` returns incorrect value when added via Scene

### ISSUE THREAD

**Issue by eSoares** [material-components/material-components-android#1387]
**Description:** 

When a MaterialButtonToggleGroup is in a layout added to another layout via a Scene (example bellow), getting the checkedButtonId(s) is always -1.
The button is correctly visibly selected in the UI, but in code it has a wrong state.

**Expected behavior:** 

Calling checkedButtonId should have the correct value.

**Source code:** 

Having two XMLs, one inflated when created the activity with a linearlayout, after adding the second layout with the MaterialButtonToggleGroup via:
```java
TransitionManager.go(Scene.getSceneForLayout(root, R.layout.layout_with_material_button_toggle_group, this));
```

Note: both TransitionManager and Scene are imported from androidx.

**Android API version:** Tested in Android 9 (28)
 
**Material Library version:** Tested both 1.3.0-alpha01 and 1.2.0-alpha06.

**Device:** Tested in Samsung S8.

**Comment by ymarian** [comment]
When are you using checkedButtonIds. In an enter action? Could you create a small sample app reproing the issue.

**Comment by eSoares** [comment]
Sorry, doing more debugging and trying to replicate the behaviour I found a mistake that caused the issue. 
Nothing wrong with the library.
