### ISSUE TITLE
[Slider] RangeSlider display the label of the non-moving thumb instead of the moving thumb while sliding.

### ISSUE THREAD

**Issue by rickymohk** [material-components/material-components-android#1393]
**Description:** RangeSlider display the label of the non-moving thumb instead of the moving thumb while sliding.

**Expected behavior:** Label of the moving thumb should be displayed

**Android API version:** 29

**Material Library version:** 1.3.0-alpha01

**Device:** CAT S41 Android 8.0.0

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by melaniegoetz** [comment]
Hi there! We'd be happy to look into prioritizing this as a feature request. Could you provide some more information about your use case?

**Comment by rickymohk** [comment]
I am using a RangeSlider for selecting heart rate zone in my app. As shown in the screenshot, when one thumb is dragged, the label of the opposite thumb is displayed.
![image](https://user-images.githubusercontent.com/17548814/84879281-98f93d80-b0bd-11ea-92d3-c38ed0167cf0.png)
![image](https://user-images.githubusercontent.com/17548814/84879321-a4e4ff80-b0bd-11ea-9d17-0eefeb6417e9.png)

**Comment by ymarian** [comment]
This should be fixed, all labels should be visible now

**Comment by yasirali133314** [comment]
range slider is showing label above the slider.. no option there to change label from top to bottom.
