### ISSUE TITLE
[MaterialTextView] defStyleRes doesn't behave as expected

### ISSUE THREAD

**Issue by ataulm** [material-components/material-components-android#1397]
**Description:**
Passing `defStyleRes` doesn't behave as expected; attributes inside this style resource are ignored.

This is because this constructor chains up to the 3-arg AppCompatTextView constructor (the 4 arg one doesn't exist there), meaning the `defStyleRes` is only used to resolve `android:lineHeight` / `lineHeight`.

The consequence is that for folks who are updating from `TextView` to `MaterialTextView` then there's a massive behavior change.

**Expected behavior:**

If the 4-arg constructor is called with 0 as the value for `defStyleAttr` (or where the theme doesn't define `textViewStyle`), then the passed style resource should be treated as the default style.

```kotlin
class MyCustomTextView(context: Context, attrs: AttributeSet) :
    MaterialTextView(context, attrs, 0, R.style.Widget_Demo_MyCustomTextView)
```

**Suggest**

Deprecating this 4-arg constructor. It doesn't make sense until AppCompatTextView supports it too.

Alternatively, add a lint check which will flag usage of this constructor as an error if the passed style contains anything except `android:lineHeight` or `lineHeight`.

**Android API version:** 
n/a

**Material Library version:**
1.1.0, current alpha too

**Device:**
n/a

**Comment by consp1racy** [comment]
The 4-arg constructor wasn't introduced until Lollipop.

From what I understand `defStyleRes` is ignored altogether if `defStyleAttr` is defined on the theme.

So yeah, delete the 4-arg constructor.

**Comment by ataulm** [comment]
Related https://issuetracker.google.com/issues/159928344

**Comment by consp1racy** [comment]
`defStyleRes` is only taken account if `defStyleAttr` is 0 or isn't defined on the theme.
```
 * @param defStyleRes A resource identifier of a style resource that
 *                    supplies default values for the TypedArray,
 *                    used only if defStyleAttr is 0 or can not be found
 *                    in the theme.  Can be 0 to not look for defaults.
```
Source:  [Resources.Theme#obtainStyledAttributes](https://developer.android.com/reference/android/content/res/Resources.Theme#obtainStyledAttributes(android.util.AttributeSet,%20int[],%20int,%20int))

`MaterialTextView` extends `AppCompatTextView`, which defines `defStyleAttr = android.R.attr.textViewStyle`. And that is defined on all Android themes. You would have to actively null it in your theme. So `defStyleRes` is, in practice, never taken into account.

So yeah, delete the 4-arg constructor. It's confusing at best. And avoid `defStyleRes` internally.
