### ISSUE TITLE
[TimePicker] Improve convenience/fluidity by changing defaulting behavior

### ISSUE THREAD

**Issue by yuzhshen** [material-components/material-components-android#1398]
**Is your feature request related to a problem? Please describe.**
Setting a time in the time picker is unintuitive and requires high touch target accuracy. The current time picker implementation defaults to the current time and often requires users to go through the high-precision operation of setting minutes back to "00" with 60 touch targets.

**Describe the solution you'd like**

I'm proposing that the time picker should default to the earliest available time that's on the hour (for example, if it's 8:37 AM, the selector defaults to 9:00 AM). The main benefit of this is allowing users to schedule on the hour (a common occurrence) without engaging in the previously mentioned high-precision operation.

**Full proposal:**

When the user chooses a time in the time selector, they must choose the hour, minutes, and AM/PM. The current state of things is that the time defaults to the current time (if it's 8:37 AM, the time selector defaults hour to 8, minutes to 37, and AM/PM to AM). Although this makes sense, there's a missed opportunity to make life easier for the user, since the user doesn't often need to schedule something for the exact time which they opened the time selector. Preferably, by implementing smart defaulting behavior, they don't have to choose all three.

My proposal is to make the time selector default to the earliest available time that's on the hour (for example, if it's 8:37 AM, the selector defaults to 9:00 AM). The benefits of this are as follows:

By defaulting minutes to 00, the common CUJ of scheduling something on the hour is easy and takes at most two taps, skipping the high-precision operation of setting the minute with 60 touch targets. It's also generally logical that if I want to schedule something for 7, I should just be able to touch the 7 and not worry about setting the minutes back to 00.

I think ideally the AM/PM toggle should adjust based on what the user selects for hours and minutes so that it indicates the time that comes soonest. For example, if it's 8:37 AM and I schedule something for 9, it should be AM, but if I schedule something for 8 it should be PM since 8 PM will come sooner than 8 AM. I think this simplifies some CUJs (like "remind me in a bit").

Picking an hour is the action that has the weakest priors (don't think there are any good signals for what hour someone might pick), but also the weakest need for defaulting. The next hour from opening the selector just makes the most logical sense, since you can't do too much inference here.

**Describe alternatives you've considered**
N/A

**Additional context**
This would be a huge boon to convenience for alarms, timers, events, etc on Android.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ymarian** [comment]
The default is up to the app, you can call setHour and setMinute and implement whatever behavior makes more sense to your specific app.
