### ISSUE TITLE
[Chip] Support InputChip in TextInputLayout

### ISSUE THREAD

**Issue by NitroG42** [material-components/material-components-android#1404]
**Is your feature request related to a problem? Please describe.**
In official Material Design guide, there is a description of input chip : https://material.io/components/chips#input-chips
It includes having the chips inside a text field, like a TextInputLayout/EditText/AutocompleteTextView.
I don't think there is a way right now to do that without rewriting components by hands.

**Describe the solution you'd like**
Provide a way to use chips inside AutocompleteTextView just like the MDC guide.

**Describe alternatives you've considered**
If it's possible with the components you're already providing, add a sample to the catalog and the MDC Android doc.

**Comment by melaniegoetz** [comment]
Thanks so much for submitting this feature request! We will bring this to the attention of our Product team for consideration

**Comment by gabrielemariotti** [comment]
@NitroG42 Did you check https://github.com/material-components/material-components-android/blob/master/docs/components/Chip.md#standalone-chipdrawable?

**Comment by scottyab** [comment]
`Chipdrawable` seems like it would enable what @NitroG42 mentions. I think what would be awesome is a new input view that ties everything together. i.e is allows input of a string such as an email, space/comma converts it to a `Chipdrawable` or selected from the auto complete suggestion dropdown. Also has support for multiple chips and ontap behaviour to expand and make editable. 

There are some chip libraries eg [android-chips](https://github.com/klinker41/android-chips) that offer a similar view but AFAIK they aren't based on the MDC library. Interested to hear thoughts on this kind of view being added.

**Comment by NitroG42** [comment]
It's funny because it seems the documentation has been updated with the ChipDrawable about one month after my current issue request. It seems like it solved my initial issue, I'm closing it but feel free to tell me if it should stay open for what you suggested. (or open another issue)

**Comment by LucasFebatis** [comment]
The [Standalone ChipDrawable](https://github.com/material-components/material-components-android/blob/master/docs/components/Chip.md#standalone-chipdrawable) section in the MDC Guide mentioned by @gabrielemariotti don't explain some things, like

- How to set spaces between chips under EditText?
- How to implement a TextWatch or Tokenizer for adding and removing chips under EditText or AutoCompleteTextView?

**Comment by jishindev** [comment]
Any updates on this yet?

**Comment by ranjan-technoexponent** [comment]
> The [Standalone ChipDrawable](https://github.com/material-components/material-components-android/blob/master/docs/components/Chip.md#standalone-chipdrawable) section in the MDC Guide mentioned by @gabrielemariotti don't explain some things, like
> 
>     * How to set spaces between chips under `EditText`?
> 
>     * How to implement a TextWatch or Tokenizer for adding and removing chips under `AutoCompleteTextView`?
> 
>     * How to define a `clickListener` or `closeIconClickListener`

Any update on this question?? 
Thanks in advance.
