### ISSUE TITLE
[TabLayout] set tag for TabItem in xml is useless

### ISSUE THREAD

**Issue by zilchzz** [material-components/material-components-android#1409]
**Description:** I want to index a tabitem with the attribute tag when use tablayout, but I can't get that tag runtime 'cause you guys ignored the tag when add a new tab into tablayout.

**Source code:** 
//The tab should be add the tag from tabItem
private void addTabFromItemView(@NonNull TabItem item) {
    final Tab tab = newTab();
    if (item.text != null) {
      tab.setText(item.text);
    }
    if (item.icon != null) {
      tab.setIcon(item.icon);
    }
    if (item.customLayout != 0) {
      tab.setCustomView(item.customLayout);
    }
    if (!TextUtils.isEmpty(item.getContentDescription())) {
      tab.setContentDescription(item.getContentDescription());
    }
    addTab(tab);
  }

**Material Library version:**1.1.0

**Comment by matpag** [comment]
If you check the documentation of `TabItem` which you can find [here](https://github.com/material-components/material-components-android/blob/5febeba67e5b382c244330a2d5fe1df22256dde8/lib/java/com/google/android/material/tabs/TabItem.java#L27-L31).
they explicitly say that the `TabItem` is not a real view, which is added as a child of `TabLayout`.
So you can't use it for set and retrieve a tag and you can't use it like a regular child view.

**Comment by zilchzz** [comment]
> If you check the documentation of `TabItem` which you can find [here](https://github.com/material-components/material-components-android/blob/5febeba67e5b382c244330a2d5fe1df22256dde8/lib/java/com/google/android/material/tabs/TabItem.java#L27-L31).
> they explicitly say that the `TabItem` is not a real view, and it is not added as a child of `TabLayout` like a `ViewGroup` would do.
> So you can't use it for set and retrieve a tag and you can't use it like a regular view.

Thank you for reply anyway.
When I read the source code, I have found that TabItem is not a regular view.
In that case, how can I index a Tab within TabLayout.
I can only do that with hardcode in activity or fragment, which not so convenient.
It's there any good way for that?

**Comment by matpag** [comment]
Why you would need to get the index of a Tab?
If you create them programmatically, you probably need to use the index of the list you use for creating the TabItems

**Comment by zilchzz** [comment]
> Why you would need to get the index of a Tab?
> If you create them programmatically, you probably need to use the index of the list you use for creating the TabItems

I create them in the xml file , just like the code below:
<com.google.android.material.tabs.TabLayout
        android:layout_width="wrap_content"
        android:layout_height="35dp">
        
        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="match_parent"/>
        
        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="match_parent"" />
        
        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="match_parent" />
        
        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="match_parent" />
    
    </com.google.android.material.tabs.TabLayout>

In that case, attribute tag is useful.

**Comment by PawelDecowski** [comment]
I agree with @zilchzz. It’s infuriating that you can’t identify a tab in code, by anything from the XML.

The only way to identify a selected tab is by its position so when I reorder the tabs in XML, I have to remember to update the `OnTabSelectedListener`, too.

Some kind of identifier from `TabItem` should be passed on to the `TabLayout.Tab` so you can see in in `onTabSelected`.

**Comment by TomasRiker** [comment]
Just ran into the same problem. This issue should be re-opened! It would be an easy thing to fix, just copy the TabItem's ID from XML into the Tab instance.
