### ISSUE TITLE
[TextInputEditText] Extending TextInputEditText breaks the layout

### ISSUE THREAD

**Issue by vincent-paing** [material-components/material-components-android#1414]
**Description:** Create a class that extends TextInputEditText

```kotlin
class MyCustomEditText @JvmOverloads constructor(
  context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : TextInputEditText(context, attrs, defStyleAttr) 
```

Use it as child of `TextInputLayout`. And the edit text is smaller than a usual `TextInputEditText`

**Expected behavior:** The Layout should render edit text correctly.

**Android API version:** Any version

**Material Library version:** 1.3.0-alpha01

**Device:** All devices

**Comment by gabrielemariotti** [comment]
Use` R.attr.editTextStyle` instead of `0` as `defStyleAttr`:

```
class MyCustomEditText @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = R.attr.editTextStyle
): TextInputEditText(context, attrs, defStyleAttr)
```

**Comment by leticiarossi** [comment]
hi @vincent-paing if the above doesn't solve your issue feel free to reopen
