### ISSUE TITLE
[ShapeableImageView] Cuts out background of other views.

### ISSUE THREAD

**Issue by Laimiux** [material-components/material-components-android#1416]
**Description:** 
ShapeableImageView doesn't show the background of views below it.

**Expected behavior:** 
This is how it looks currently:
<img width="236" alt="Screen Shot 2020-06-17 at 2 28 27 PM" src="https://user-images.githubusercontent.com/2983787/84952447-d9998c80-b0a6-11ea-990e-ca53ebb6e1b6.png">

Expected:
<img width="233" alt="Screen Shot 2020-06-17 at 2 27 32 PM" src="https://user-images.githubusercontent.com/2983787/84952364-b8d13700-b0a6-11ea-97c2-bb4744a4bd44.png">

**Source code:**
Styles:
```xml
    <style name="roundImageView">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">12dp</item>
    </style>

    <style name="circleImageView">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">50%</item>
    </style>
```

Views:
```xml
           <com.google.android.material.imageview.ShapeableImageView
                android:id="@+id/logo_background_view"
                android:layout_width="82dp"
                android:layout_height="82dp"
                android:scaleType="centerCrop"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:shapeAppearanceOverlay="@style/roundImageView"
                tools:src="@tools:sample/avatars" />

            <com.google.android.material.imageview.ShapeableImageView
                android:id="@+id/logo_view"
                android:layout_width="48dp"
                android:layout_height="48dp"
                app:shapeAppearanceOverlay="@style/circleImageView"
                app:layout_constraintBottom_toBottomOf="@id/logo_background_view"
                app:layout_constraintEnd_toEndOf="@id/logo_background_view"
                app:layout_constraintStart_toStartOf="@id/logo_background_view"
                app:layout_constraintTop_toTopOf="@id/logo_background_view"
                tools:src="@tools:sample/avatars" />
```

**Android API version:** 
27

**Material Library version:** 
1.2.0-beta01
1.3.0-alpha01

**Device:** 
Emulator -> Pixel 1 API 27

**Comment by Laimiux** [comment]
Note: seems related to `ColorDrawable(Color.BLUE)` usage. Using `ShapeDrawable` seems to work fine.
```kotlin
val shapeDrawable = ShapeDrawable(RectShape())
shapeDrawable.colorFilter = PorterDuffColorFilter(Color.BLUE, PorterDuff.Mode.SRC_IN)
view.setImageDrawable(shapeDrawable)
```

**Comment by ymarian** [comment]
Can you share a sample app with exactly with you are doing? I tried `app:srcCompat="@color/...."` on both images and it seems to work fine. Is this specific to API 27?

**Comment by ymarian** [comment]
Please re-open If you can help me repro

**Comment by mohamedelbarrak** [comment]
same problem

**Comment by bolaware** [comment]
Same thing still happening

**Comment by drchen** [comment]
Can you provide a repro sample app so we can help debug?

**Comment by JBramauer** [comment]
Experiencing the same issue, this is definitely not fixed and should be reopened.

Material Versions tested: 1.5.0, 1.6.1

Steps to reproduce:
- Displaying an image with transparent background (loading via Coil)
- ShapeableImageView is placed inside a MaterialCardView, which itself is a Google Maps SDK Info Window

Result:
<img width="124" alt="image" src="https://user-images.githubusercontent.com/39763866/179234111-30209c39-3f75-4bc2-87e0-57f519d976fe.png">

**Comment by zeroDivider** [comment]
I am experiencing same thing.. It has appeared when I introduced dark mode in my app, but I did not touch any of my ShapeableImageViews or resources I use for them. Here is code I use:
```
<com.google.android.material.imageview.ShapeableImageView
    android:id="@+id/ivDanger"
    android:layout_width="48dp"
    android:layout_height="48dp"
    android:background="@color/reddish"
    android:paddingHorizontal="2dp"
    android:paddingVertical="2dp"
     android:scaleType="center"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    app:shapeAppearanceOverlay="@style/ShapeAppearanceOverlay.ImageView.CircleImage"
    app:srcCompat="@drawable/ic_danger"
    app:strokeColor="@color/red_light"
    app:strokeWidth="1dp" />
```
`theme.xml`:
```
    <style name="ShapeAppearanceOverlay.ImageView.CircleImage" parent="Theme.CarGOPartner">
        <item name="cornerSize">50%</item>
        <item name="cornerFamily">rounded</item>
    </style>
```
