### ISSUE TITLE
[MaterialCardView] Applying colorFilter on background or foreground not working on 1.1.0

### ISSUE THREAD

**Issue by GoUpNorth** [material-components/material-components-android#1418]
**Description:** 
Since the release of the version 1.1.0-alpha02, applying a colorFilter to a MaterialCardView background is not working. Prior to this release, PorterDuffColorFilter or BlendModeColorFilter could be applied properly.

**Source code:** 
`        findViewById<MaterialCardView>(R.id.card).background.colorFilter = BlendModeColorFilter(
            ContextCompat.getColor(
                this,
                R.color.colorAccent
            ), BlendMode.SRC_ATOP
        )
`
In addition to the code above, I attached a sample app that demonstrates the issue.
[ColorFilterBug.zip](https://github.com/material-components/material-components-android/files/4797386/ColorFilterBug.zip)

**Android API version:** Android API 29

**Material Library version:** The bug was reproduced on the version 1.1.0-alpha02 of the library up to the final release 1.1.0

**Comment by ymarian** [comment]
can you explain your use case. Why not just use CardView#setCardBackgroundColor() ?

**Comment by GoUpNorth** [comment]
Hi,
I am using it in a RecyclerView ViewHolder that can either have a MaterialCardView or a ConstraintLayout as root view.
I need to apply a color to the background of the root view, without changing the background drawable that is already defined in the xml layouts.

We have found a workaround and are using setTint instead.
