### ISSUE TITLE
[Chip] Vertical alignment issue

### ISSUE THREAD

**Issue by Shusshu** [material-components/material-components-android#1424]
**Description:** 
<img width="677" alt="Screenshot 2020-06-19 at 14 51 14" src="https://user-images.githubusercontent.com/1760011/85134259-7f323480-b23c-11ea-81d7-1a9974bfbc44.png">

How can I improve the vertical alignment of this Chip with a custom font?

**Expected behavior:** 
Centre_vertical

**Android API version:**
All

**Material Library version:** 
All

**Comment by wcshi** [comment]
The text in chip are rendered by its super class TextView, Does your font look vertically aligned in a TextView?

**Comment by Shusshu** [comment]
Yes 
![Screenshot_20200622-084724](https://user-images.githubusercontent.com/1760011/85258203-5b066b80-b467-11ea-8e16-f8ae90d9027b.png)

**Comment by Shusshu** [comment]
Chip with default font
![Screenshot_20200622-090943](https://user-images.githubusercontent.com/1760011/85258694-38288700-b468-11ea-8c56-4e63247e14b5.png)

**Comment by wcshi** [comment]
@Shusshu did you mean to share a different screenshot? The screenshot above looks identical to your first image, which you stated used a custom font.

**Comment by wcshi** [comment]
I tried your text using chip action style and default font, this is what I see:
![Screenshot_1592858437](https://user-images.githubusercontent.com/38438920/85337391-5fa24280-b4ae-11ea-97a8-4be9b0da32e7.png)

**Comment by Shusshu** [comment]
Indeed it's the font ! :( bad news

**Comment by Shusshu** [comment]
Thanks @wcshi

**Comment by Shusshu** [comment]
Actually I finally found the issue

Left Textview: default font
<img width="375" alt="Screenshot 2020-06-23 at 10 38 22" src="https://user-images.githubusercontent.com/1760011/85380853-b440ce80-b53d-11ea-8c43-80eed662c40f.png">

**Comment by wcshi** [comment]
hmm, looks like need it to ensure that chip text is centered using the default font, so I plan to move this into the base default style. this way you can override it attribute in your app.
