### ISSUE TITLE
TextInputLayout suffixText programmatically.

### ISSUE THREAD

**Issue by IniongunIsaac** [material-components/material-components-android#1427]
Please how can I set the suffixText/prefixText programmatically? I can set those via XML but how about setting them via code?

**Comment by kroegerama** [comment]
There is a `setSuffixText()` method right here: [TextInputLayout.java:L2269](https://github.com/material-components/material-components-android/blob/74508c89c87f3f17db8f952319ccb4daee60a260/lib/java/com/google/android/material/textfield/TextInputLayout.java#L2269)

And `setPrefixText()` also exists: [TextInputLayout.java:L2187](https://github.com/material-components/material-components-android/blob/74508c89c87f3f17db8f952319ccb4daee60a260/lib/java/com/google/android/material/textfield/TextInputLayout.java#L2187)

**Comment by IniongunIsaac** [comment]
@kroegerama I can't find those methods when I place a dot on my "textInputLayout" reference. Perhaps this has to do with the versions of MaterialDesign?

**Comment by kroegerama** [comment]
So, which version are you using? :)

**Comment by IniongunIsaac** [comment]
Version 1.1.0 which is the latest stable.
I've even updated to 1.3.0-alpha01 but still can see the methods.

**Comment by kroegerama** [comment]
Do you use Kotlin? Then it's something like this: `inputMail.suffixText = "km/h"`. I just tested it on 1.3.0-alpha01.
What's your layout exactly? Is your textInputLayout reference maybe pointing to the `TextInputEditText` in your `TextInputLayout` instead of the parent?
Are you using `com.google.android.material.textfield.TextInputLayout` in your xml layout?

**Comment by IniongunIsaac** [comment]
Yes I use Kotlin and I'm using `com.google.android.material.textfield.TextInputLayout`.
I'm also using `1.3.0-alpha01` right now and setting the suffix via code but it doesn't seem to be working at the moment.

**Comment by kroegerama** [comment]
One last thing: The suffix/prefix will only be visible when the view is focused 😉

**Comment by IniongunIsaac** [comment]
`1.3.0-alpha01` finally worked for me, thank you @kroegerama
