### ISSUE TITLE
[TextInputLayout] in ExposedDropDown with hint

### ISSUE THREAD

**Issue by ahgamalaglan** [material-components/material-components-android#1428]
**Description:** when using dropdown icon with using hint inside the edit text the hint padding is gone

**Android API version:** 29

**Material Library version:** 1.2.0-beta-01

**Device:** all devices

**Comment by gabrielemariotti** [comment]
@ahgamalaglan 
It happens only if you don't set the right style in the `TextInputLayout`

<img width="311" alt="Schermata 2020-08-14 alle 21 07 01" src="https://user-images.githubusercontent.com/2583078/90284430-48f6e700-de72-11ea-96b9-ff5a805a8a2b.png">

Use the **`Widget.MaterialComponents.TextInputLayout.FilledBox.ExposedDropdownMenu`** style

```
   <com.google.android.material.textfield.TextInputLayout
       style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox.ExposedDropdownMenu"
       android:hint="Label"
       app:endIconMode="dropdown_menu"
       >

       <AutoCompleteTextView />

   </com.google.android.material.textfield.TextInputLayout>
```

<img width="311" alt="Schermata 2020-08-14 alle 21 07 47" src="https://user-images.githubusercontent.com/2583078/90284557-70e64a80-de72-11ea-83f0-dd690b14203c.png">
