### ISSUE TITLE
TextInputLayout isn't given "filled box" style by default

### ISSUE THREAD

**Issue by miketrewartha** [material-components/material-components-android#143]
### Overview

When using a material theme (mine inherits from `Theme.MaterialComponents.Light.DarkActionBar`), `TextInputLayout` doesn't seem to be styled using the "filled box" background that it used to (in `1.0.0-alpha1`, at least). The [documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/TextInputLayout.md) states that:

>Using TextInputLayout with an updated Material theme (Theme.MaterialComponents) will provide the correct updated Material styles to your text fields by default.

This seems to be in contradiction with what actually happens in the newest version of this library.

### Reproduction steps

1. Create a layout for an activity that uses a theme inheriting from `Theme.MaterialComponents`
2. Add the following to the layout:
  ```
  <com.google.android.material.textfield.TextInputLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="Email">

            <com.google.android.material.textfield.TextInputEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="textEmailAddress|textNoSuggestions"
                android:maxLines="1"
                android:singleLine="true" />

</com.google.android.material.textfield.TextInputLayout>
  ```
3. Launch the app and notice that there's no "filled box" background style.
4. Add `style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox"` to the `TextInputLayout`.
5. Relaunch the app and notice that the "filled box" background style is now applied.

### Version number

`1.0.0-alpha3`

### Operating system and device

I'm compiling against and targeting API 28, with a min of API 21. This happens on my Pixel XL 2 running the Android P beta (DP3) and a Nokia 6.1 (2018) running Android 8.1.0.

### Related issues

None

**Comment by chantw** [comment]
This is noticeable. Also, when the style is applied, the layout does not seem to have correct padding that confirms to [**Material Text Field** specs](https://material.io/design/components/text-fields.html#spec).
![Preview produced by the same library version](https://user-images.githubusercontent.com/34728894/41806247-b5509774-76ec-11e8-9695-a5455f30ac25.png)

**Comment by Thomas-Vos** [comment]
I'm experiencing the same issue in version `1.0.0-beta01`. The style isn't automatically set and needs to be added manually in XML although I'm using the MaterialComponents theme.

**Comment by afohrman** [comment]
Thanks for reporting this. Theme.MaterialComponents does not set the text field to the filled box style by default. This is because TextInputLayout uses ThemeOverlays to set the child TextInputEditText's style, and ThemeOverlays can't be set in a default style attribute. I'll clarify this in the TextInputLayout documentation.

**Comment by cketcham** [comment]
We're investigating a workaround for this.

**Comment by joselabelette** [comment]
Still not fixed

**Comment by afohrman** [comment]
This fix should be live in the latest release of our library, 1.1.0-alpha-01.
