### ISSUE TITLE
[MaterialButtonToggleGroup] MaterialButton of MaterialButtonToggleGroup transparent stroke color is not transparent in fact

### ISSUE THREAD

**Issue by tipapro** [material-components/material-components-android#1436]
**Description:** If MaterialButton (outlined) of MaterialButtonToggleGroup stroke color is set to transparent it will have other color. If single MaterialButton (outlined) stroke color is set to transparent it will have transparent color.

**Comment by ymarian** [comment]
The color is ?attr/colorsurface. This is because colors sometimes have opacity so they would be a different color when they overlap each other. You have a couple options, depending on what result you would expect from a transparent stroke.

1. For no stroke set stroke width to 0
2. You can set the stroke color to the same color as your background. 
3. For space between the buttons, without stroke you can set stroke width to 0 and add insetLeft, insetRight as necessary.

**Comment by ReeMiXeR** [comment]
@ymarian what should i do if i want 20% transparent white stroke?
i set `app:strokeColor="#33FFFFFF"`, but it becomes transparent black
<img width="589" alt="Screenshot 2020-06-24 at 21 27 49" src="https://user-images.githubusercontent.com/18577596/85612458-92d90300-b661-11ea-8f96-f1d92f83ad93.png">

**Comment by ymarian** [comment]
@ReeMiXeR how does it look if you set 

layout.xml

```xml
<com.google.android.material.MaterialButtonToggleGroup
   ...
   app:materialThemeOverlay="@style/button_overlay" 
```

styles.xml
```xml
<style name="button_overlay" >
    <item name="colorSurface">@android:color/white</item>
</style>
```

**Comment by ReeMiXeR** [comment]
fragment.xml

```
 <?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#000000"
    tools:context=".FirstFragment">


    <com.google.android.material.button.MaterialButtonToggleGroup
        android:id="@+id/clip_feed_switcher"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:theme="@style/SelectorTheme"
        app:checkedButton="@id/switcher_1"
        app:materialThemeOverlay="@style/button_overlay"
        app:singleSelection="true">

        <com.google.android.material.button.MaterialButton
            android:id="@+id/switcher_1"
            style="@style/Widget.MaterialComponents.Button.OutlinedButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:backgroundTint="@color/background_selector"
            android:text="Button 1"
            android:textColor="@android:color/white"
            app:strokeColor="#33FFFFFF" />

        <com.google.android.material.button.MaterialButton
            android:id="@+id/switcher_2"
            style="@style/Widget.MaterialComponents.Button.OutlinedButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:backgroundTint="@color/background_selector"
            android:text="Button 2"
            android:textColor="@android:color/white"
            app:strokeColor="#33FFFFFF" />

    </com.google.android.material.button.MaterialButtonToggleGroup>
</FrameLayout>
```

styles.xml

```
<style name="button_overlay" >
        <item name="colorSurface">@android:color/white</item>
    </style>

    <style name="SelectorTheme" parent="@style/Theme.MaterialComponents"/>
```

background_selector.xml

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:alpha="0.2" android:color="@android:color/white" android:state_checked="true"/>
    <item android:color="@android:color/transparent" android:state_checked="false"/>
</selector>
```
white background

<img width="484" alt="Screenshot 2020-06-24 at 23 49 38" src="https://user-images.githubusercontent.com/18577596/85626556-e48b8880-b675-11ea-9f52-f06381a0592b.png">

black background

<img width="436" alt="Screenshot 2020-06-24 at 23 53 07" src="https://user-images.githubusercontent.com/18577596/85626586-ee14f080-b675-11ea-8aaa-e6fed69c525a.png">

**Comment by ymarian** [comment]
![Screenshot_1593047896](https://user-images.githubusercontent.com/38727469/85642757-5e187c00-b660-11ea-8c27-653652abc280.png)

Weird it doesn't work to put the overlay on the ToggleGroup. 

If I put the overlay on each button it looks good to me. I also changed colorSurface to be black instead of white in the style

**Comment by ReeMiXeR** [comment]
okay,  i will try this, thank u for the help!

**Comment by ymarian** [comment]
@ReeMiXeR let me know if that works for you
