### ISSUE TITLE
[MaterialAlertDialogBuilder] Set different title size

### ISSUE THREAD

**Issue by DanielMartinus** [material-components/material-components-android#1437]
**Description:**

The text size of the title in `MaterialAlertDialogBuilder` can't be changed by defining a textSize in the textAppearance or by inheriting `MaterialAlertDialog.MaterialComponents.Title.Text` and setting the textSize directly. The text size of the dialog always seems to fallback to a default size.

_See source code below_

**Expected behavior:** 

I would expect the text size to change with the textAppearance. Even though the TextAppearance defines a textSize of 16sp or when you directly change it in the title style of the dialog, the size doesn't change.

![image](https://user-images.githubusercontent.com/1636897/85550469-48d02d00-b621-11ea-91b7-951f1c53efce.png)

The dialog remains unchanged when changing the textSize in either the textAppearance or directly with `android:textSize`

**Source code:** 

I'm changing the appearance of the Dialog by implementing the following styling:

```xml
<style name="Components.Temper.DialogThemeOverlay" parent="@style/ThemeOverlay.MaterialComponents.MaterialAlertDialog">
    <item name="materialAlertDialogTitleTextStyle">@style/Components.Temper.Dialog.Title</item>
</style>

<style name="Components.Temper.Dialog.Title" parent="@style/MaterialAlertDialog.MaterialComponents.Title.Text">
    <item name="android:textAppearance">@style/TextAppearance.Body1.Medium</item>
</style>
```

When the dialog is created the theme is set:

```kotlin
val builder = MaterialAlertDialogBuilder(requireContext(), R.style.Components_Temper_DialogThemeOverlay)
```

The textAppearance is correctly set and the text changes to the font family that we have set in our DesignSystem. However, the text size doesn't change for the dialog title. The title is always bigger. We try to set it to 16sp whilst it seems to fallback to around 17 or 18sp. 

```xml
<style name="Components.Temper.Dialog.Title" parent="@style/MaterialAlertDialog.MaterialComponents.Title.Text">
    <item name="android:textAppearance">@style/TextAppearance.Body1.Medium</item>
    <item name="android:textSize">10sp</item>
</style>
```

Changing the text size directly in the styles also doesn't make it smaller. Is this a bug? Or do you have to change the text size a different way?

**Android API version:** 10

**Material Library version:** `com.google.android.material:material:1.3.0-alpha01`

**Device:** Tested on multiple devices and Android versions but I mainly test on a Nexus 5 emulator with Android 10

**Comment by marynovskyi** [comment]
The same for the MaterialAlertDialog.MaterialComponents.Body.Text style

**Comment by gabrielemariotti** [comment]
Tried with `1.3.0-alpha02`.

You can use:


```
    <style name="MyTitle_ThemeOverlay.MaterialComponents.MaterialAlertDialog" parent="@style/ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="materialAlertDialogTitleTextStyle">@style/MyTitle</item>
    </style>
    <style name="MyTitle" parent="@style/MaterialAlertDialog.MaterialComponents.Title.Text">
        <item name="android:textAppearance">@style/MyTitle_TextAppearance</item>
    </style>
    <style name="MyTitle_TextAppearance" parent="@style/TextAppearance.MaterialComponents.Subtitle1">
        <item name="android:textSize">34sp</item>
    </style>
```

or:

    <style name="MyTitle" parent="@style/MaterialAlertDialog.MaterialComponents.Title.Text">
        <item name="android:textAppearance">?attr/textAppearanceHeadline4</item>
    </style>

or:

    <style name="MyTitle" parent="@style/MaterialAlertDialog.MaterialComponents.Title.Text">
        <item name="android:textAppearance">TextAppearance.MaterialComponents.Headline4</item>
    </style>

<img width="275" alt="Schermata 2020-07-27 alle 23 17 28" src="https://user-images.githubusercontent.com/2583078/88593308-a233dd80-d05f-11ea-96a6-c1a991292193.png">

**Comment by wolfkruger** [comment]
How to set buttons text color, background or outline color?
