### ISSUE TITLE
[MaterialButtonToggleGroup] Add space between buttons inside group

### ISSUE THREAD

**Issue by Vadim-Smirnov** [material-components/material-components-android#1438]
I have a few ToggleButtons into MaterialButtonToggleGroup with singleSelection mode. 
And now it look like this 
![Снимок экрана 2020-06-24 в 16 13 17](https://user-images.githubusercontent.com/24462394/85562946-9eaed000-b635-11ea-83d7-f03fb91c7d89.png)

I want to separate buttons. It's should be like this

![Снимок экрана 2020-06-24 в 16 25 20](https://user-images.githubusercontent.com/24462394/85564878-4ed10880-b637-11ea-92b0-ac478991c617.png)

**Comment by ymarian** [comment]
Hi!

 I don't think will support this. All the logic on MaterialButtonToggleGroup is specifically to handle the case where buttons should change shapes and be next to each other. Seems just using checkable buttons would work well for your use case.

**Comment by ymarian** [comment]
Chips and chip group might also be a good fit:

https://github.com/material-components/material-components-android/blob/master/docs/components/Chip.md

**Comment by Vadim-Smirnov** [comment]
@ymarian Thanks a lot! I'll try

**Comment by okaymak** [comment]
Because `MaterialButtonToggleGroup` is a `LinearLayout`, you can use this to add spacing between items:
```xml
<com.google.android.material.button.MaterialButtonToggleGroup
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:divider="@drawable/divider"
        android:showDividers="middle">
```

and set the divider drawable as:
```xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <size
        android:width="16dp"
        android:height="16dp" />
</shape>
```
