### ISSUE TITLE
Legacy TextInputLayout text not aligned vertically

### ISSUE THREAD

**Issue by Dwite** [material-components/material-components-android#144]
Is it possible to align text vertically inside legacy TextInputLayout according to material design spec?

Right now, only new text fields have text aligned vertically.

**Comment by afohrman** [comment]
Are you referring to aligning the hint or the input text vertically?

We are not planning changes to the legacy Widget.Design.TextInputLayout style, but you should be able to achieve this with setting android:padding on the child TextInputEditText (or other attributes, depending on what exactly your goal is).
