### ISSUE TITLE
[BottomNavigationView ] itemTextAppearanceActive not working

### ISSUE THREAD

**Issue by akul1994** [material-components/material-components-android#1443]
**Description:** attributes    app:itemTextAppearanceActive and  app:itemTextAppearanceInactive are not working as expected. They were working in v1.1.0 not working v.1.2.0-beta01 onwards

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** ` app:itemTextAppearanceActive="@style/BottomNavigationViewActive"
        app:itemTextAppearanceInactive="@style/BottomNavigationViewInActive"
`

**Android API version:** Android API version here

**Material Library version:** 1.2.0-beta01

**Device:** One plus 7t

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by gabrielemariotti** [comment]
It works with `1.2.0-beta01`,`1.2.0-rc01`, `1.3.0-alpha02`.
What is the issue?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
