### ISSUE TITLE
[ChipGroup] Vertical chip spacing can't be reduced below certain dp

### ISSUE THREAD

**Issue by Ostkontentitan** [material-components/material-components-android#1445]
Description:

When setting spacing for Chips in a ChipGroup spacing should match the given attribute value.

E.g.:

      app:chipSpacing="0dp"
      app:chipSpacingVertical="0dp"
      app:chipSpacingHorizontal="0dp"

Should result in chips sitting right next to each other.

This works well for horizontal spacing but vertical spacing does not seem to be affected from a certain point.

- Expected behavior: Vertical spacing can be brought down all the way to 0dp.

- Source code: See attachment

- Android API version: 29

- Device: Pixel 4
[Demo Project](https://github.com/material-components/material-components-android/files/4837587/ChipSpacing.zip)
<img src="https://user-images.githubusercontent.com/2793777/85870410-41e61d80-b7cd-11ea-9fda-553620520aae.png" width=350 />

**Comment by wcshi** [comment]
hi @Ostkontentitan there's a flag on by default to ensure that chips meet Android's minimum recommended touch size. You can disable it by setting ensureMinTouchTargetSize == false
