### ISSUE TITLE
ProgressIndicator - Listener to effectivity hide progress indicator with animation

### ISSUE THREAD

**Issue by kevintorch** [material-components/material-components-android#1446]
**Is your feature request related to a problem? Please describe.**
Yes,  it's related to hiding progress indicator with animation. the problem is I was hiding progress indicator with `hide()` method after calling `show()` method. but it doesn't hide the progress indicator And the documentation says _wait for some time after calling `show()` method to hide the progress indicator_. but i much time do I have to wait?. i end up using a handler with a post delay of 1 second or simply change the visibility to invisible. please improve the `hide()` method or give us some listeners. So we could hide the indicator with animation.

**Describe the solution you'd like**
- I don't really know the solution. but I can only think of listeners.

**Describe alternatives you've considered**
- i had to change the visibility to `View.INVISIBLE.` to hide the progress indicator without animation.

**Additional context**
- none.

**Comment by pekingme** [comment]
Hi @kevintorch, thanks for reporting this. Recently we have added a new attribute called `minHideDelay`. When `hide()` is called before the show animation ends, the hide animation will start at the specified time in milliseconds (capped to 1s) from the start of the show animation. This is similar to your first workaround using the handler to delay. If `minHideDelay` is negative (-1 by default) or zero, hide animation will start immediately once called. May I ask if there are other actions, except hiding, which have to be taken at the end of show animation in your app?

**Comment by kevintorch** [comment]
no. I'm using it in webview. so onPageFinished, I have to just hide the progress indicator

**Comment by matpag** [comment]
@kevintorch You have to wait for [this commit](https://github.com/material-components/material-components-android/commit/924ac3fe850372d452a5f73bc3deef2e86f28995) to land on the next `1.3.0-alpha02` release or test it now using the [1.3.0-SNAPSHOT](https://github.com/material-components/material-components-android/packages/81484?version=1.3.0-SNAPSHOT)

**Comment by pekingme** [comment]
Closed as 1.3.0-alpha02 is out.
