### ISSUE TITLE
[Component name] Short description of issue

### ISSUE THREAD

**Issue by UnleashedMors** [material-components/material-components-android#1447]
**Description:**
I am currently working on an app and have found the bug in the coding that since material: 1.2.0-alpha06, if you use a persistent bottomsheet, the xml method setPeekHeight ignores all entered values and simply sets an unchangeable standard.

**Expected behavior:** the method should Change/Set the peek height but instead the value is ignored and eine dort of Default ist used

**Android API version:** 26-29

**Material Library version:** 1.2.0-alpha06 and following

**Device:** emulated devices, Xiaomi Mi Mix 2s, Samsung TabS6

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

Update: 23.02.2022

The bug is not showing on later versions, i cannot reproduce so i am closing the issue.

**Comment by drchen** [comment]
Is this still happening? Can you provide more details like your code snippet?

**Comment by UnleashedMors** [comment]
I have to check, i will try to give code snippet and more information at the end of the month.

**Comment by UnleashedMors** [comment]
Cannot reproduce, the issue is fixed in versions after 1.2.0 alpha6. Now at 1.4.0 the bottomSheet is using the setPeekHeight correctly
