### ISSUE TITLE
[Tablayout] Does not focus on selected tab when using accessibility swipe navigation

### ISSUE THREAD

**Issue by michaelJCBSH** [material-components/material-components-android#1449]
Tablayout  does not focus on selected tab when using accessibility swipe navigation to swipe to tablayout

**Current behavior:**
the left most visible tab will always be focused on. 

**Expected behavior:**
The selected should be focused on

**Comment by wcshi** [comment]
Could you please elaborate on how to reproduce the behavior you are reporting, either using the catalog app or a sample app, thanks

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
