### ISSUE TITLE
[TabLayout] ArrayList<BaseOnTabSelectedListener> gets cleared when app is backgrounded

### ISSUE THREAD

**Issue by ivanalvarado** [material-components/material-components-android#1453]
**Description:** TabLayout Tabs don't respond to clicks after being backgrounded. I've set breakpoints and noticed `TabLayout.clearOnTabSelectedListeners()` gets invoked when the app goes to the background. I can, however, still swipe between tabs, but `OnTabSelectedListener` methods don't fire.

**Expected behavior:** I would expect to still be able to switch between pages by clicking on the Tabs after backgrounding the app.

**Source code:** 
The following method is invoked after the app is backgrounded. I assume something internally is listening to the host Activity's `onPause()` lifecycle method.
```
public class TabLayout extends HorizontalScrollView {
  
    ...

    private final ArrayList<BaseOnTabSelectedListener> selectedListeners = new ArrayList<>();

    ...

    public void clearOnTabSelectedListeners() {
        selectedListeners.clear()
    }

    ...

}
```

**Android API version:** Observed on Android device running Android 10 (latest as of now).

**Material Library version:** 1.1.0

**Device:** Google Pixel 3.

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
In the current code base we don't really call clearOnTabSelectedListeners anywhere, so I believe it's been fixed?

Feel free to reopen this if it's still happening with the latest library version.
