### ISSUE TITLE
[CollapsingTextHelper] not showing in RTL locales android <= 19

### ISSUE THREAD

**Issue by mahmoudafarideh** [material-components/material-components-android#1454]
Starting from the 1.2.0-alpha02 hint in TextInputLayout not showing in devices running below android 4.4 and I think this is because of changes in CollapsingTextHelper.

![LTR mode](https://user-images.githubusercontent.com/20106258/86495837-31ffa800-bd90-11ea-844b-048e98537376.jpg)

![RTL Locale](https://user-images.githubusercontent.com/20106258/86495861-3fb52d80-bd90-11ea-98d1-6a84b143eabc.jpg)

1.3.0-alpha01

Google Nexus

**Comment by matpag** [comment]
2 questions:
1) Are you using the gravity parameter in the `TextInputLayout`? If yes, which one?
2) With 1.2.0-alpha01 was working fine?

Thank you

**Comment by mahmoudafarideh** [comment]
Hi
1. yes i'm using gravity 'START'
2. No '1.1.0-alpha05' is working fine all the upper version not working as
expected.

best regards

**Comment by matpag** [comment]
Can you post the XML of TextInputLayout which is not working?
Thank you

**Comment by Pourqavam** [comment]
I have the same issue on **API 17 (Android 4.2)** with `com.google.android.material:material:1.4.0`.
The hint animation has also an unexpected horizontal jump:
![English Hint](https://s9.gifyu.com/images/simplescreenrecorder-2021-11-13_21.33.08.gif) ![Persian Hint](https://s9.gifyu.com/images/simplescreenrecorder-2021-11-13_21.35.52.gif)
It works fine on **API 17** with `com.google.android.material:material:1.1.0`.
I tested it by Android Virtual Device.

**Comment by drchen** [comment]
Is this still an issue with the latest library version? We've pushed several fixes regarding the collapsing hint since.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
