### ISSUE TITLE
CollapsingToolbarLayout maxlines acting not as expected.

### ISSUE THREAD

**Issue by lectricas** [material-components/material-components-android#1458]
**Description:** Hi. I'm trying to make my CollapsingToolbarLayout to have two lines, which I do with 
`app:maxLines="2"`

There is some margins in expanded title, so I removed it like this:

```
            app:expandedTitleMarginBottom="0dp"
            app:expandedTitleMarginEnd="0dp"
            app:expandedTitleMarginStart="0dp"
            app:expandedTitleMarginTop="0dp"
```

Now my second line is cut out of view. I need to set 
`app:expandedTitleMarginBottom="8dp"`
in order to see the full two line title.
When I remove `app:maxLines="2"` it works as expected. 

It is not clear for me why this happens. Also CollapsingToolbarLayout is very mysterious, consider writing some docs on how this thing works.

<img width="490" alt="Screenshot 2020-07-03 at 15 06 09" src="https://user-images.githubusercontent.com/8782219/86467806-c50ff200-bd3e-11ea-9546-2efb050f85e3.png">

**Comment by SonOfBowser** [comment]
Have you tried this on a snapshot? I think this is the same thing I fixed in https://github.com/material-components/material-components-android/pull/1432
