### ISSUE TITLE
Suffix/prefix for TextInputLayout is visible only when the view is focused

### ISSUE THREAD

**Issue by pchmielowski** [material-components/material-components-android#1459]
One last thing: The suffix/prefix will only be visible when the view is focused 😉

_Originally posted by @kroegerama in https://github.com/material-components/material-components-android/issues/1427#issuecomment-647332783_

Is it possible to somehow change this behavior? 
My use case is: in the text input for phone number I'm displaying area code as a prefix.
It would be nice if the area code is visible all the time, regardles of the current focus.

**Comment by kroegerama** [comment]
It's visible when focused or when the `EditText` is filled.

**Comment by pchmielowski** [comment]
For my use case it would be great if is visible even if the input is empty and not focused.
User picks country using spinner, usually before entering the phone number so they expect the area code to be visible immediately after choosing the country.

**Comment by kroegerama** [comment]
Can't you use the `hint` attribute? It's always visible, if the `EditText` is empty.

**Comment by pchmielowski** [comment]
Thanks, it solves the problem!

However I still believe that changing the `prefix` behavior to be always displayed or making it configurable (maybe some `app:prefixAlwaysVisible` attribute) could be a good idea.
Now, to show my area code correctly I had to use `setOnFocusChangeListener` and update `hint` to empty string after gaining focus (otherwise both `prefix` and `hint` were visible on empty focused input).

**Comment by thomas-lebihan** [comment]
Is there any update about it?

**Comment by codefury** [comment]
You can use app:expandedHintEnabled="false" to display the suffix/prefix also when the text field is empty.
