### ISSUE TITLE
Chip attributes table not displayed properly

### ISSUE THREAD

**Issue by VictorBG** [material-components/material-components-android#146]
Chip attributes table is not displayed properly on the [chip documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/Chip.md)

**Comment by wcshi** [comment]
Fixed in [commit fab7b4b97d4af2792f66f0343e62f6d579b6ab55](https://github.com/material-components/material-components-android/commit/fab7b4b97d4af2792f66f0343e62f6d579b6ab55)
