### ISSUE TITLE
[RangeSlider] Right Tooltip missing if values set with delay

### ISSUE THREAD

**Issue by mhettig** [material-components/material-components-android#1460]
**Description:**
In case the values of a (Range)Slider are set in code via a delay, the tooltip for the right thumb is missing:
![IMG_20200703_212210](https://user-images.githubusercontent.com/2598617/86493969-da534380-bd73-11ea-9194-e1c2a4d044a1.jpg)
To be precise the right tooltip appears very short on first touch and is then gone forever until app restart.

**Expected behavior:**
Right tooltip shown as usual.

**Source code:**
For demonstration purposes the code given below uses a `postDelayed()` but issue also happens in case of other delays. E.g. when observing some computation results before setting RangeSlider values via `LiveData#observe()`

The following code was tested in Activity's `onCreate()` and in Fragment's `onViewCreated()` as well as `onCreateView()`

Working:
```
slider.valueFrom = 1.0f
slider.valueTo = 10.0f
slider.setValues(1.0f, 10.0f)
```
Not Working:
```
Handler().postDelayed({
	slider.valueFrom = 1.0f
	slider.valueTo = 10.0f
	slider.setValues(1.0f, 10.0f)
}, 500)
```
Also happens with discrete slider.

**Android API version:** 29

**Material Library version:** 1.3.0-alpha01

**Device:** Xiaomi Mi Mix 2S

**Comment by ymarian** [comment]
Thanks this is helpful. This is because we are only adding the labels on attachedToWindow so at the beginning there is only one.

We'll fix on our end. A temporal workaround is to preset values to the number you require. For example:

```kotlin
// Set two values to attach enough labels at the beginning. 
slider.setValues(0.0f, 0.0f)
Handler().postDelayed({
  slider.valueFrom = 1.0f
  slider.valueTo = 10.0f
  slider.setValues(1.0f, 10.0f)
}, 500)
```

**Comment by mhettig** [comment]
Thank you very much for your answer and the workaround. Works like a charm :)

I observed a similar issue in case of fragment transactions:
- Precondition: App available with one activity and two fragments. Transaction provided by Android Jetpack Navigation Component
- Add Slider to first / home fragment
- Add button to first fragment allowing to switch to second fragment. With ClickListener code like: `findNavController().navigate(R.id.action_fragment1_to_fragment2)` (no transition animation applied or parameters passed)
- Switch to second fragment
- Navigate back to first fragment via Android's back button
- Result: Right thumb (again) gone. 

In this case it doesn't seem to matter whether the mentioned workaround is used or not. Also there is no change when applying the values with a `postDelay()` or not.

**Comment by ymarian** [comment]
Can you test on the latest snapshot? Not sure if I follow exactly the second case but I think it should be fixed as well:

https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md

**Comment by mhettig** [comment]
I tested the latest snapshot and both cases are working fine now. Also without the initial proposed workaround. Thank you very much.
