### ISSUE TITLE
[Theming] Introduce another color attribute for text which is 'close to' the primary color.

### ISSUE THREAD

**Issue by MachFour** [material-components/material-components-android#1461]
**Is your feature request related to a problem? Please describe.**
My `colorPrimary` is #ffcd17 which I like having for the action bar, UI controls, etc. but is illegible on white text. I'd like to be able to use a slightly different color (which currently is my `colorPrimaryDark`, #a98400) in all instances where `colorPrimary` is used as a text colour (e.g. on Dialog buttons, DatePicker buttons, Navigation drawer action items, TabLayout tabs) without having to go in and retheme each one manually. 

In Dark mode, however I'd like to use the original primary colour. 

**Describe the solution you'd like**
Add a theme attribute `colorPrimaryAsText` which is used in these situations, instead of `colorPrimary`. This allows avoiding illegible text in not-Night mode when `colorPrimary` is a light colour, and avoiding illegible text in Dark mode when `colorPrimary` is a dark colour.

**Describe alternatives you've considered**
Retheming each component that I use, one by one. This is time consuming, not just because of the repetitive nature of this task but because the documentation is poor on how to do this. Basically we have to go into the source here and, for each component, find precisely which style hierarchy needs to be duplicated in order to override the desired theme attributes.

**Comment by consp1racy** [comment]
1. Set `<item name="colorPrimary">?colorPrimaryDark</item>`.
2. Create a new theme attribute `colorPrimaryBright` which would be set to your original `colorPrimary` value.
3. Use `?colorPrimaryBright`.

I'm assuming there's not many places where you use the bright color (i.e. the dark color is the default and very few styles need to be altered to reference the bright color).

Make sure the naming can be applied for your dark theme.

**Comment by MachFour** [comment]
Thanks for the suggestion however it's more than 'not many places' where the 'bright' primary colour is used. 

- App bar
- Surfaces and non-text highlights for date and time pickers
- floating action button
- other colour buttons, sliders, toggles, etc. 

Or in other words the, bright `colorPrimary` _is_ the default colour. It's also semantically the primary colour of my app. It's literally just the brightly coloured text on a white background which is the problem.

With some effort it's possible to find workarounds, sure, but given the nature of Material design concept, it's just a surprising oversight to have to work around contrast issues caused by the current styling limitations of the official Android Material design library.  

It's not

**Comment by hunterstich** [comment]
Hi, given the inactivity and the fact that this isn't something we plan to support, I'm closing this issue. If you still have questions on how to achieve this, feel free to comment and continue the conversation.

**Comment by MachFour** [comment]
For anyone in the future reading this issue, the solution I ended up with was to rewrite my UI using Jetpack Compose 🙃
