### ISSUE TITLE
[Slider] Allow "Max" or "Infinity" as valueTo in Sliders

### ISSUE THREAD

**Issue by VincentJoshuaET** [material-components/material-components-android#1463]
I want to create a range slider to filter the items on a list by price.

**Comment by consp1racy** [comment]
The slider is just a visual representation (view) of data. The slider doesn't need to know about infinity or what "infinity" means in your app.

Pick some value that represents infinity that makes sense in your domain, and present it to the user as such using `LabelFormatter`. For example:

    
    slider.setLabelFormatter { value -> 
        if (value == slider.valueTo) {
            slider.context.getString(R.string.infinity)
        } else {
            value.toInt().toString()
        }
    }

"Infinity" doesn't automatically mean "positive infinity as specified by a IEEE 754 float". It's what you make it.

**Comment by ymarian** [comment]
I think the above makes sense, not sure what we can offer besides that.
