### ISSUE TITLE
Using Snapshot Version

### ISSUE THREAD

**Issue by OnClickListener2048** [material-components/material-components-android#1465]
**Description:** Full description of issue here

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Android API version here

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

**Device:** Device on which the bug was encountered here

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by OnClickListener2048** [comment]
Using Snapshot Version is Down

**Comment by dsn5ft** [comment]
How is it down?

**Comment by ymarian** [comment]
Hi I just tried it now and it's working, please carefully follow the instructions here:

https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md

I would double check the to make sure the token used has the read:packages permission
