### ISSUE TITLE
[SwitchMaterial] Track and thumb sizes.

### ISSUE THREAD

**Issue by JeanCarrot** [material-components/material-components-android#1466]
**Is your feature request related to a problem? Please describe.**
I would like to reduce the width of the track.

**Describe the solution you'd like**
We could have xml parameters and their related methods like `trackWidth`, `trackHeight`, `thumbWidth`, `thumbHeight`.

**Describe alternatives you've considered**
I could not find any good solution using the material library. I've tried many things, none of them were satisfying. However, I've noticed we can increase the track's width by using `switchMinWidth`.
I could have used the `Switch` embedded class, which seems to have a smaller width. However, I'd prefer to use the Material one.

**Comment by hunterstich** [comment]
Hey @JeanCarrot 

I'm going to run this by design and see what they have to say. Any chance you have a mock of what you're trying to accomplish?

**Comment by hunterstich** [comment]
@JeanCarrot 
Heard back from design. They mentioned having explored this recently and decided the result felt unbalanced. It doesn't look like this is something we're going to prioritize anytime soon.

I would recommend looking into subclassing SwitchMaterial and using your own [track](https://developer.android.com/reference/androidx/appcompat/widget/SwitchCompat#setTrackDrawable(android.graphics.drawable.Drawable)) and [thumb](https://developer.android.com/reference/androidx/appcompat/widget/SwitchCompat#setThumbDrawable(android.graphics.drawable.Drawable)) drawables.
