### ISSUE TITLE
Calling AppCompatDelegate.setDefaultNightMode() leaves afterimage on restarted activity

### ISSUE THREAD

**Issue by hdpe1399** [material-components/material-components-android#1467]
**Description:** In my app I'm calling AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES) on a Preference screen SwitchPreference listener, that is opened on the MainActivity.

The app switches to dark mode normally, after I press the back button and go back to the MainActivity, after the activity restarts to dark mode, the whole activity leaves an afterimage on the background.

**Expected behavior:** No afterimage on background

video to problem: [https://www.youtube.com/watch?v=QV8diUuCY9s](https://www.youtube.com/watch?v=QV8diUuCY9s)

**Source code:** link to example project producing this issue https://github.com/hdpe1399/DayNightTest

**Android API version:** 29, 30

**Material Library version:** 1.3.0-alpha01

**Device:** all physical devices + emulator

**Comment by consp1racy** [comment]
Can you post a *minimal* repro project? There's a lot to go thorugh that probably isn't relevant. You don't need databinding, app icon, maybe custom theme, definitely no example tests...

**Comment by hdpe1399** [comment]
> Can you post a _minimal_ repro project? There's a lot to go thorugh that probably isn't relevant. You don't need databinding, app icon, maybe custom theme, definitely no example tests...
> 
> MDC 1.3.0 isn't out yet, did you mean 1.3.0-alpha01? Please be precise.

Thank you for the answer. 
I've removed all the extra things on the project please consider taking a second look :)

**Comment by hunterstich** [comment]
Hey @hdpe1399,

To me, this doesn't look like it's related to Material Components. 

It looks like you might be adding a second PostListFragment after returning to your MainActivity, causing the duplicate effect your seeing. Does changing `supportFragmentManager.beginTransaction().add(` to `supportFragmentManager.beginTransaction().replace(` fix this?

I'm going to go ahead and close this so our team isn't tracking it as a bug against us, but feel free to continue discussing here if you need help.
