### ISSUE TITLE
[Bottom Sheet] Bottom Sheet peek height gives different results on API 29

### ISSUE THREAD

**Issue by FahadSaleem** [material-components/material-components-android#1472]
**Description:** The bottom sheet's peek height appears differently on API 29. It works correctly for 28 and below but gives incorrect peek behavior on 29.

**Expected behavior:** I set the peak height to be 77dp which should only show the bottom navigation bar at start. On API 27,28 it shows up correctly, as you can see on the left emulator device on which we can only see the bottom bar. But on API 29 as you can see on the right, it shows some extra space from beneath which is incorrect. It only occurs on API 29. 
![image](https://user-images.githubusercontent.com/21174438/86999004-0c790100-c1cb-11ea-97c6-faf5bd57ba35.png)

**Source code:** I have attached a minimal project that shows this behavior. Please run this on API 29 and 28,27 to see the difference.
[BottomSheetPeekError.zip](https://github.com/material-components/material-components-android/files/4894614/BottomSheetPeekError.zip)

**Android API version:** 29

**Material Library version:** 1.3.0-alpha01, 1.2.0-beta01, 1.2.0-alpha06 (they all give incorrect peak height on API 29, the minimum I have to use is 1.2.0-alpha05)

**Device:** Multiple devices running API 29

**Comment by Sanlorng** [comment]
maybe caused by gestureBottomInsets ，BottomSheet will setGestureBottomInsets in default behavior，you can try use setGestureBottomInsetsIgnore(false) to solve this issue

**Comment by pablovguillen** [comment]
Changed In style. It worked for me. Thanks @dsn5ft 

> maybe caused by gesture bottom insets ，BottomSheet will set gesture bottom insets in default behavior that available on API 29 to avoid BottomSheet Gesture conflicts with System Navigation Gesture，you can try use **setGestureInsetBottomIgnored(true)** to solve this issue , sample code:
> 
> ```
> BottomSheetBehavior<View> behavior = BottomSheetBehavior.from(bottomSheetBehaviorView);
> behavior.setGestureInsetBottomIgnored(true);
> ```
> 
> or In Style：
> 
> ```
> in styles.xml
> 
> <style name="Widget.MyBottomSheetBehavior" >
>     <item name="gestureInsetBottomIgnored">true</item>
> </style>
> 
> <style name="AppTheme">
>     <item name="bottomSheetStyle">@style/Widget.MyBottomSheetBehavior>
> </style>
> 
> in your layout file
> <View
>     android:id="@+id/my_bottom_sheet_view"
>     style="?attr/bottomSheetStyle"
> </View>
> ```

**Comment by rekire** [comment]
Normally I avoid to comment on old issues, but this resolves a visual bug I searching for 2 weeks. In my case this makes not any sense because I have a bottom bar below my bottom sheet. This should be out of my view no default behavior.

**Comment by Sruf-y** [comment]
A single line of legacy code. That's all it took to solve the visual bug i've been battling with for 2 days...

**Comment by michael-winkler** [comment]
@pubiqq Maybe you are so friendly to help here? 🙂

**Comment by pubiqq** [comment]
> @pubiqq Maybe you are so friendly to help here? 🙂

The issue is marked as resolved in https://github.com/material-components/material-components-android/commit/7b620035a78f15284aed82ec6c09d5f6eb4249dc, I'm not sure what is expected of me here?

**Comment by michael-winkler** [comment]
Oh sorry.. did not see the merged symbol. My fault.
