### ISSUE TITLE
[DatePicker] Single DateSelector Conversion time zone error

### ISSUE THREAD

**Issue by abhimaanmadhav** [material-components/material-components-android#1476]
**Description:** setSelection in SingleDateSelector converts date in UTC date. Assume a scenario where the user is in India (+5:30). The time is 13/jul/2020 5am local time. setSelection in SingleDateSelector is giving in mill sec the function creates a calender object at UTC the date would be 12/jul/2020 . The selected date in the ui would be 12/jul/2020 rather than 13/jul/2020 which was the input. 

**Expected behavior:** expected behavior should be date should be converted based on system default setting rather than UTC.

**Source code:** 
 ```
@Override
  public void setSelection(@Nullable Long selection) {
    selectedItem = selection == null ? null : UtcDates.canonicalYearMonthDay(selection);
  }
```

**Material Library version:** Material Android Library version you are using here  1.1.0

**Comment by abhimaanmadhav** [comment]
can raise a pull request once the bug is verified and accepted

**Comment by matpag** [comment]
I know you are on stable but could you try with the latest snapshot?: https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md

Recently raajkumars fixed some bugs which have not landed on an 1.3.0-alpha release yet, maybe you can check if this is your case or not.

**Comment by abhimaanmadhav** [comment]
yes fix is the proper one . Looks good to my usecase also.

**Comment by matpag** [comment]
Great! :)

**Comment by hunterstich** [comment]
Nice. Going ahead and closing this
