### ISSUE TITLE
error: failed linking references.

### ISSUE THREAD

**Issue by tuanct1997** [material-components/material-components-android#148]
I follow Get Started. Have maven and lib already but still Error: Failed linking references

**Comment by NickM-27** [comment]
Do you have multiple color resources in different folders? I would check those, I got this error because the new gradle version now requires you to have all colors that are in the night / nonnight folder also in the default folder.

**Comment by colinrtwhite** [comment]
I ran into this issue when upgrading to alpha 3. The solution for me was to change `Widget.MaterialComponents.TextInputLayout.OutlineBox` to `Widget.MaterialComponents.TextInputLayout.OutlinedBox` in my XML layout files.

**Comment by tuanct1997** [comment]
Thank you for all your support. @colinrtwhite thank you for letting me know this. I have fixed it.
