### ISSUE TITLE
when custom height of bottombar,navigation icon not at the center.how to set it to center of height?

### ISSUE THREAD

**Issue by pahnpiseth** [material-components/material-components-android#149]
### Overview
For usage questions: ask on
[Stack  Overflow](http://stackoverflow.com/questions/tagged/material-components).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

### Reproduction steps

 - Detailed steps to reproduce

### Version number

 - Found in CHANGELOG.md

### Related issues

 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by dsn5ft** [comment]
We fixed this issue on our side in https://github.com/material-components/material-components-android/commit/f2aba00d8a0549f7cb5d52a43430e146f174adb2, however if you are setting a custom height then you might need to also set maxButtonHeight to the same value as your height for the button to be centered.
