### ISSUE TITLE
[ProgressIndicator] Property indicatorWidth redundant/missleading

### ISSUE THREAD

**Issue by mpost** [material-components/material-components-android#1491]
**Is your feature request related to a problem? Please describe.**

The following applies to the `LINEAR` indicator:

Using the `ProgressIndicator` property `indicatorWidth` changes the height of the `ProgressIndicator` which is not obvious from its name. In addition the height should rather be controlled by the regular height property on the given layout params. Atm the `indicatorWidth` is used as a fix constant wich makes it unnecessarily complicated to control the View height with layout params.

**Describe the solution you'd like**

Remove misleading `indicatorWidth` in favor of the layout params height

**Comment by hunterstich** [comment]
Hey @mpost,

Thanks for the feedback. Can definitely see where you're coming from. If I remember correctly, I think indicatorWidth was the most universal property name considering it also maps to the "strokeWidth" of a circular indicator,  but @pekingme might have some more info. I'll bring this up with the team.

**Comment by pekingme** [comment]
Hi @mpost, thanks for sharing your POV. Like @hunterstich mentioned, `indicatorWidth` defines the width of the `indicator` (the stroke/highlighted part on the track) across all types of `ProgressIndicator`. Especially, since 1.3.0-alpha02, the custom drawing shapes are supported in `ProgressIndicator` (check the catalog for a demo of applying custom shapes). `indicatorWidth` is not redundant as it defines a very essential property of the drawing. Besides, `ProgressIndicator` should not be used as a container or composite component. Thus, letting layout params control its size is somehow unconventional. Maybe we can find a better name to eliminate the misleading in the use of LINEAR types.

**Comment by mpost** [comment]
Thank you for your detailed answer. I understand your reasoning behind having a separate property. Coming from a regular `ProgressBar` from the android SDK it was confusing to me to not be able to use the the regular layout params to size the `LINEAR` `ProgressIndicator`. Eg. the `ProgressBar` allows you to create a 1dp high progress indicator with the height layout params.

My general thinking is that if possible view dimensions should be controlled by layout params. Not by view specific properties. In this scenario i do not see a reason why this established behavior would need to be changed for the `ProgressIndicator`. Controlling the indicator line/graphics should be separate from the dimensions.

**Comment by pekingme** [comment]
I do like the idea to separate the graphics from the dimensions. But there's no clean cut between these two. E.g., letting `layout_height` control the width of the linear indicator track doesn't align with this, either.

`ProgressBar` provides several styles, most of which (except `progressDrawable` in `Horizontal` style) use static drawables, i.e., png(s). They'll be scaled to comply the size defined by layout params. But when comes to the specific spec requirements (by applying custom drawables), the sizes defined by drawables and by layout params might also end up with conflicts. In these cases, we should prioritize the drawables dimension to meet the spec requirements, i.e., `wrap_content` should be used. This is also what we consider in different use cases of `ProgressIndicator`. 

I'll replace the `indicatorWidth` with `indicatorSize` to eliminate the confusion in `LINEAR` types.

**Comment by mpost** [comment]
Thanks for the additional info. I understand the constraints applied to the layout behavior in regards to the drawable used by the view. Therefore it could be argued that the intrinsic size has precedence over any layout height given. 

Renaming the property to `indicatorSize` is a good step.
