### ISSUE TITLE
Changing the default TextInputLayout Border & Hint Color when focused & not focused

### ISSUE THREAD

**Issue by akinfopark** [material-components/material-components-android#1492]
The Latest version of material components library by takes the dark grey & colorPrimary value for border color & hint text color when not focused & focused respectively. This can be a problem when we have to use colorPrimary as screen background. How do I change these default colors for these?

**Comment by gabrielemariotti** [comment]
You can define a custom style:

```
  <style name="MyTextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.*">
    <!-- border color -->
    <item name="boxStrokeColor">@color/text_input_layout_stroke_color</item>

    <!-- The color of the label when it is collapsed and the text field is active -->
    <item name="hintTextColor">@color/....</item>
    <!-- The color of the label in all other text field states (such as resting and disabled) -->
    <item name="android:textColorHint">@color/.....</item>
  </style>
```

or you can simply override them with

```
<com.google.android.material.textfield.TextInputLayout
   android:theme="@style/MyTextInputLayout_overlay"
   ..>
```

with:

```
<style name="MyTextInputLayout_overlay">
    <item name="colorOnSurface">@color/....</item>
    <item name="colorPrimary">@color/....</item>
</style>
```

**Comment by akinfopark** [comment]
> You can define a custom style:
> 
> ```
>   <style name="MyTextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.*">
>     
>     <item name="boxStrokeColor">@color/text_input_layout_stroke_color</item>
> 
>     
>     <item name="hintTextColor">@color/....</item>
>     
>     <item name="android:textColorHint">@color/.....</item>
>   </style>
> ```
> 
> or you can simply override them with
> 
> ```
> <com.google.android.material.textfield.TextInputLayout
>    android:theme="@style/MyTextInputLayout_overlay"
>    ..>
> ```
> 
> with:
> 
> ```
> <style name="MyTextInputLayout_overlay">
>     <item name="colorOnSurface">@color/....</item>
>     <item name="colorPrimary">@color/....</item>
> </style>
> ```

The 1st method is working for hint text but the border changes color only when it is focused else the border background is the default grey. And the cursor color is also colorPrimary how to change that

**Comment by gabrielemariotti** [comment]
> but the border changes color only when it is focused 

You can define the `boxStrokeColor` attribute as a selector:

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:alpha="..." android:color="@color/...." android:state_focused="true"/>
  <item android:alpha="..." android:color="@color/...." android:state_hovered="true"/>
  <item android:alpha="..." android:color="@color/...." android:state_enabled="false"/>
  <item android:alpha="..." android:color="@color/...."/>  <!-- unfocused -->
</selector>
```

**Comment by Lukman-AMIKOM** [comment]
@gabrielemariotti I'm trying to set the hint text color to 3 different colors, e.g. green for when it's focused & enabled, blue for when it's unfocused & enabled, and red for when it's disabled.
How can I accomplish this?

So far, I only managed to set it two colors, one color is applied to when the `textInputLayout` is in two states: disabled & (unfocused + enabled), the other one is applied when it's focused and enabled.

**Comment by gabrielemariotti** [comment]
You can try with:

```
<style name="CustomOutlineBox" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
    <item name="boxStrokeColor">@color/text_input_layout_stroke_color</item>
    <item name="android:textColorHint">@color/text_color_hint</item>
    <item name="hintTextColor">@color/green</item>
</style>
```

with the `@color/text_color_hint` selector:

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:alpha="..." android:color="@color/red" android:state_enabled="false"/>
    <item android:alpha="..." android:color="@color/blue"/>
</selector>
```

and the `@color/text_input_layout_stroke_color` selector:

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:alpha="..." android:color="@color/green" android:state_focused="true"/>
    <item android:alpha="..." android:color="@color/green" android:state_hovered="true"/>
    <item android:alpha="..." android:color="@color/red" android:state_enabled="false"/>
    <item android:alpha="..." android:color="@color/blue"/>  <!-- unfocused -->
</selector>
```

Focused:

<img width="355" alt="Qbplb" src="https://user-images.githubusercontent.com/2583078/97775131-878d6b00-1b5e-11eb-8845-094de72e8371.png">

Unfocused:

<img width="353" alt="k7zTN" src="https://user-images.githubusercontent.com/2583078/97775134-8c521f00-1b5e-11eb-950b-6afcca0c0c17.png">

Disabled:

<img width="346" alt="dSdod" src="https://user-images.githubusercontent.com/2583078/97775137-8f4d0f80-1b5e-11eb-803f-179a5b16e077.png">

**Comment by Lukman-AMIKOM** [comment]
I'm still unable to get it to work for the disabled state. I think I'm doing something wrong.
How is the recommended way to disable the TextInputEditText?
I'm currently using `setEnabled()`.

**Comment by gabrielemariotti** [comment]
@Lukman-AMIKOM 
Disable the `TextInputLayout` not the `TextInputEditText`.
Use `textinputlayout.isEnabled = false`

**Comment by Lukman-AMIKOM** [comment]
Yes, it works now. Thank you.

**Comment by ranjeetsinha13** [comment]
It does not work for case when I set `app:errorEnabled="true"` in the xml or code. I such cases I see the hintLabel (when not in collapsed state) is always RED

**Comment by gabrielemariotti** [comment]
@ranjeetsinha13 With an error you have to use the `boxStrokeErrorColor` and `errorTextColor` attributes.

**Comment by ranjeetsinha13** [comment]
@gabrielemariotti `errorTextColor` would change the color of `errorText` as well. The usecase is such that the floating label color should be the default [colorPrimary] and the `errorText` color should remain RED

**Comment by sabinebarrera** [comment]
@gabrielemariotti I ran into an issue when styling the `TextInputLayout`, `hintTextColor`, `android:textColorHint`, and `errorTextColor`. I want users to have a less overwhelming experience when the `TextInputLayout` is in error. I want to only show error text and/or char count in red but I am not able to change the color of the floating label (hintTextColor) when in error. This is shown in red. Have you seen this issue?

<details>
<summary>Screen</summary

<img src="https://user-images.githubusercontent.com/1494577/107170336-ea1faf80-6974-11eb-8045-839acbae6a24.png" width="400"/>
</details>

**Comment by chaleao** [comment]
@sabinebarrera and @ranjeetsinha13 were you guys able to make it work?

**Comment by ranjeetsinha13** [comment]
@chaleao Nope. I was not able to make this work. It does not look like this is possible. I tried this 6 months back. I am not sure if things have changed since then

**Comment by Kareem7assan** [comment]
> > but the border changes color only when it is focused
> 
> You can define the `boxStrokeColor` attribute as a selector:
> 
> ```
> <selector xmlns:android="http://schemas.android.com/apk/res/android">
>   <item android:alpha="..." android:color="@color/...." android:state_focused="true"/>
>   <item android:alpha="..." android:color="@color/...." android:state_hovered="true"/>
>   <item android:alpha="..." android:color="@color/...." android:state_enabled="false"/>
>   <item android:alpha="..." android:color="@color/...."/>  
> </selector>
> ```

sorry but state hovered never work , it works around focused and unfocused state 
i need 3 states default state - focused state - and third state when text input filled with some text but not focused

**Comment by imkhalid** [comment]
@gabrielemariotti i have studied your solution, i need you help regarding this behaviour, normal(hint and border grey), focused(hint and bordor black) and not focused with value(hint and border blue)

**Comment by aeroxr1** [comment]
I should change the color programmatically , is possible ? I don't know how to do..

**Comment by aeroxr1** [comment]
> > > but the border changes color only when it is focused
> > 
> > 
> > You can define the `boxStrokeColor` attribute as a selector:
> > ```
> > <selector xmlns:android="http://schemas.android.com/apk/res/android">
> >   <item android:alpha="..." android:color="@color/...." android:state_focused="true"/>
> >   <item android:alpha="..." android:color="@color/...." android:state_hovered="true"/>
> >   <item android:alpha="..." android:color="@color/...." android:state_enabled="false"/>
> >   <item android:alpha="..." android:color="@color/...."/>  
> > </selector>
> > ```
> 
> sorry but state hovered never work , it works around focused and unfocused state i need 3 states default state - focused state - and third state when text input filled with some text but not focused

I should change this color programmatically , is possible ? I don't know how to do..

**Comment by aeroxr1** [comment]
> 

thanks ! Good Idea !

I'm trying in this way:

`    val colorState = ColorStateList(
            arrayOf(intArrayOf(android.R.attr.state_active),
                intArrayOf( android.R.attr.state_focused),
                intArrayOf( -android.R.attr.state_focused),
                intArrayOf( android.R.attr.state_hovered),
                intArrayOf( android.R.attr.state_enabled),
                intArrayOf(- android.R.attr.state_enabled)),
            intArrayOf(
                Color.parseColor("#FF03DAC5"),
                Color.parseColor("#FF03DAC5"),
                Color.parseColor("#FF03DAC5"),
                Color.parseColor("#FF03DAC5"),
                Color.parseColor("#FF03DAC5"),
                Color.parseColor("#FF03DAC5"))
        )

    

        binding.testEditLayout.setBoxStrokeColorStateList(colorState)
        binding.testEditLayout.hintTextColor =  ColorStateList.valueOf(Color.parseColor("#FF03DAC5"))`

and it seems works pretty well.. the only things that it doesnt work is the hint color whent the edit text is unfocused.

**Comment by imkhalid** [comment]
@aeroxr1 well I guess you can try using color states for textColorHint value and hintTextColor as well

**Comment by SmartAppsDevelopment** [comment]
In order to apply this states on outline text box [Filled Bg Color ](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/color/mtrl_filled_background_color.xml) 
set  android:backgroundTint="@color/form_edt" like 
```
 <com.google.android.material.textfield.TextInputLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/outlinedTextField"
    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="@dimen/_16sdp"
app:boxBackgroundColor="@color/form_edt"
    **app:boxBackgroundMode="outline"
    app:hintEnabled="false"**
    app:layout_constraintTop_toTopOf="parent">

    <com.google.android.material.textfield.TextInputEditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        **android:backgroundTint="@color/form_edt"**
    ] />

</com.google.android.material.textfield.TextInputLayout>
```

**Comment by thedipsy** [comment]
> @aeroxr1 thank you. I have achieved it by doing a few things.
> 
> 1. I created an state attribute as filled_unfocus.
> 2. than I created two selectors for unfocused and empty field and second for unfocused and filled field
> 3. than I change these selector programmatically by checking field after text changes and apply appropriate selector. And it works.


@imkhalid Could you provide the solution please?
