### ISSUE TITLE
[TabLayout] tabPadding is effectively tabPaddingVertical

### ISSUE THREAD

**Issue by MeilCli** [material-components/material-components-android#1498]
**Description:** 
Currently, TabLayout has default `tabPaddingStart` and `tabPaddingEnd`. In TabLayout, `tabPaddingStart` and `tabPaddingEnd` and `tabPaddingTop` and `tabPaddingBottom` are resolved in preference to `tabPadding` .
So, `tabPadding` is effectively `tabPaddingVertical`.

**Expected behavior:**
I think 2 pattern of expected behavior in this case
1. remove default `tabPaddingStart` and `tabPaddingEnd` to be effected `tabPadding` that user's defined at layout.xml.
2. rename `tabPadding` to `tabPaddingVertical` to be behavior that does not interfere with appearance

**Source code:** 
https://github.com/material-components/material-components-android/blob/8f7dc21a27880eed391f45548a40de8189f31172/lib/java/com/google/android/material/tabs/res/values/styles.xml#L19-L38

https://github.com/material-components/material-components-android/blob/f945a0649b9cddc13afafeb80df7218f1aa85ef8/lib/java/com/google/android/material/tabs/TabLayout.java#L180

https://github.com/material-components/material-components-android/blob/f945a0649b9cddc13afafeb80df7218f1aa85ef8/lib/java/com/google/android/material/tabs/TabLayout.java#L473-L480

https://github.com/material-components/material-components-android/blob/f945a0649b9cddc13afafeb80df7218f1aa85ef8/lib/java/com/google/android/material/tabs/TabLayout.java#L501-L510

**Material Library version:** master branch

**Comment by dsn5ft** [comment]
I'm not sure I follow this request. I believe the way that `tabPadding` works is similar to `android:padding`, in that both `tabPadding` and `android:padding` would apply to the start, end, top, and bottom paddings by default. And then the more specific start, end, top, and bottom paddings would take precedence if they are set.

The fact that we happen to set `tabPaddingStart` and `tabPaddingEnd` in our default `TabLayout` style should have no bearing on how `tabPadding` behaves in relation to the start, end, top, and bottom paddings. If you'd like to have `tabPadding` apply to all start, end, top, and bottom paddings when using the default `TabLayout` style, then you can set `tabPaddingStart` and `tabPaddingEnd` to `@empty`.
