### ISSUE TITLE
[TextInputLayout] Nested views cause high CPU usage

### ISSUE THREAD

**Issue by baggednismo** [material-components/material-components-android#1499]
**Description:** Full description of issue here
When nesting one or many TextInputLayouts in a compound view this causes steady high CPU usage. This makes it impossible to create custom views with TextInputLayout items (could be others as well). I do _**not**_ have this problem using EditText or non-material components. This screenshot was clipped but this loop continues what feels like indefinitely. 
![image](https://user-images.githubusercontent.com/10716226/88075371-b602af80-cb46-11ea-8042-b430b1385387.png)
![image](https://user-images.githubusercontent.com/10716226/88076052-96b85200-cb47-11ea-8065-7b154b3e2f80.png)

**Expected behavior:** Screenshots and/or description of expected behavior
not getting stuck in a childView loop.

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.
this was double nested in a single XML. Normally this view is a parent ConstraintLayout which is either ```<include>``` into another view OR used with a custom view which has the same result of high CPU usage.
[https://gist.github.com/baggednismo/74a3bffd4ee5e0491560e16523822568](https://gist.github.com/baggednismo/74a3bffd4ee5e0491560e16523822568)

**Android API version:** Android API version here
29

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
both 1.2.0-rc01 and 1.3.0-alpha1

**Device:** Device on which the bug was encountered here
Emulator and S9

**Comment by baggednismo** [comment]
While testing I have identified this issue does **_NOT_** occur using LinearLayout

**Comment by dsn5ft** [comment]
Is there a specific version of the Material Android and/or Constraint Layout libraries where this issue started happening?

Is the doubly nested ConstraintLayout a requirement for reproducing the issue?

Instead of just the gist, can you provide a minimal sample app repo that reproduces the problem reliably? It's difficult to say whether something else in your app/setup could be contributing.

**Comment by baggednismo** [comment]
> Is there a specific version of the Material Android and/or Constraint Layout libraries where this issue started happening?

unknown. I am seeing the problem with new development.

> Is the doubly nested ConstraintLayout a requirement for reproducing the issue?

yes, If I place the material components at the direct child level of a ConstraintLayout there is no issue. If I add the items to a child LinearLayout there is no issue. If I add them to a child ConstraintLayout this is where the problem unravels.

> Instead of just the gist, can you provide a minimal sample app repo that reproduces the problem reliably? It's difficult to say whether something else in your app/setup could be contributing.

I will work on a new project just to highlight the issues. It will take a bit of time.

**Comment by drchen** [comment]
We've merged a change to make text input layout inflation more efficient. Can you try it with the latest library version and see if it improves the CPU usage as well?
