### ISSUE TITLE
[MaterialDatePicker] DateRangePicker Showing wrong Date

### ISSUE THREAD

**Issue by deepakgupta7403** [material-components/material-components-android#1503]
**Description:** When MaterialDatePicker opens the first time it's showing the wrong date range, but after that, it's showing the right date range. Setting IST time to setSelection(). **Date Range Text and Dialog pair milliseconds are same** 

![date_range_error](https://user-images.githubusercontent.com/29679194/88237665-57037e80-cc9d-11ea-9d4d-54fc9c229dc0.png)

**Android API version:** 29

**Material Library version:** 1.2.0-rc01

**Device:** Realme Note 5 Pro

**Comment by matpag** [comment]
Try suggestions here: https://github.com/material-components/material-components-android/issues/1476
Maybe it is the same problem

**Comment by deepakgupta7403** [comment]
@matpag Thanks problem is resolved not from given solution. the issue is am setting time millis according to IST and its showing Dialog Picker according to UTC. going to close this issue.
