### ISSUE TITLE
[RangeSlider] Getting min and max thumb values 

### ISSUE THREAD

**Issue by sarwadnya1996** [material-components/material-components-android#1504]
I am sing RangeSlider in my project, I am unable to get both min and max  thumb value  at a time,It there any way to do this?

**Comment by chriswiesner** [comment]
`slider.getValues()` is returning an array of the (thumb-)values.

**Comment by sarwadnya1996** [comment]
getValues() returns list but I want value at the current thumb position. Using getValues() it's hard to manage to get values from both the thumbs

**Comment by chriswiesner** [comment]
i'm using it like this
```
rangeSlider.addOnChangeListener { slider, value, fromUser ->

                val vals = slider.values

                updateSth(vals[0] // current value of first thumb,
                          vals[1] // second thumb)
            
        }
```

**Comment by sarwadnya1996** [comment]
No this is not like that list stores values of individual thumb not botj

**Comment by dsn5ft** [comment]
As @chriswiesner mentioned, `slider.getValues()` is the correct API for getting the current range slider thumb values.

```
    List<Float> values = slider.getValues();
    float min = Collections.min(values);
    float max = Collections.max(values);
```

**Comment by EmilioHoffmann** [comment]
If you want to get the current changed value you could do something like

```sliderView.addOnChangeListener { slider, value, fromUser ->
            slider.values[slider.activeThumbIndex]
}
```
