### ISSUE TITLE
[TabLayoutMediator] Add `isAttached` getter for getting information about `attached` state 

### ISSUE THREAD

**Issue by rmyhal** [material-components/material-components-android#1506]
I work with mutable collection of fragments and when only one fragment is in the collection I want to hide TabLayout and detach TabLayoutMediator from ViewPager2 or attach it again when I have more than one fragment in the collection. But, when I call attach twice in a row, I get IllegalStateException with message: "TabLayoutMediator is already attached". So to achieve that now I have to create duplicated variable of TabLayoutMediator's state in my own code and update it locally when i call attach() or detach().

### Possible solution
I want to have method `isAttached()` which will return attached state of TabLayoutMediator

**Comment by wcshi** [comment]
Just to confirm, you are requesting that we add a getter method to TabLayoutMediator that returns the value in the private `attached` variable?

**Comment by rmyhal** [comment]
@wcshi Yes, correct
