### ISSUE TITLE
[MaterialButtonToggleGroup] setEnabled() method is not making MaterialButtons inside the group

### ISSUE THREAD

**Issue by pinakinkansara** [material-components/material-components-android#1509]
**Description:** setEnabled() method on MaterialButtonToggleGroup is not taking effect in the child of the group

**Expected behavior:** setEnabled() method on MaterialButtonToggleGroup should enable or disable all the child inside the group.

**Android API version:** 21 to 29

**Material Library version:** 1.3.0-alpha01

**Device:** One Plus 6T
To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by dsn5ft** [comment]
`MaterialButtonToggleGroup` is a `ViewGroup`, and I believe `ViewGroup`s usually don't enable/disable all of their child views when `setEnabled` is called. So to do this you have to do something similar to https://stackoverflow.com/a/7069377.

**Comment by pinakinkansara** [comment]
I have a difference of opinion here, Viewgroup also usually don't support checked and unchecked state on the child view. Then why checked & unchecked state of child is managed by ViewGroup. it can also be done by developers by them self by getting list of childs and managing by self.

**Comment by dsn5ft** [comment]
The difference is that the main purpose of the `MaterialButtonToggleGroup` is to handle that checked state, and we've added in that functionality. Whereas the enabled state is something that's just handled by `View`.

RadioGroup is a similar example that behaves the same way.

**Comment by pinakinkansara** [comment]
Same argument should go for state as well, view should only hold its state why would viewgroup needs to do that.

I assume while passing state related decision to viewgroup ease of implementation may be in the thought process. same applies to enable and disable state, if `MaterialButtonToggleGroup` is given the responsibility will bring ease of implementation.

Scenario of disabling or enabling only specific child in the `MaterialButtonToggleGroup` is not going to be the case, in such scenario giving control to `MaterialButtonToggleGroup` to enable and disable child state gives singline line solution.

You can also consider the same for `MaterialRadioGroup` when in the making.

For example you can take reference of `TextInPutLayout` which enforces style and other property to `EditText` even though that should remain with the view only.

**Comment by pinakinkansara** [comment]
We can take approach of exposing method like `setChildEnabled()` for controlling  child's enabled disabled state in such viewgroup.

this way we can provide easy method for developer and keep `setEnabled()` of viewgroup intact.
