### ISSUE TITLE
FAB with BottomAppBar attached states problem

### ISSUE THREAD

**Issue by firatkarababa** [material-components/material-components-android#151]
In Material Design guidelines [page ](https://material.io/develop/android/components/bottom-app-bar/), attachment specs for FAB when used with BottomAppBar are given as below.

_FAB Attached States
The FAB can either be attached or detached by calling setFabAttached(boolean). When attached, the FAB will be cradled in the BottomAppBar. When detached, the FAB will float above it._

From this guide, when `app:fabAttached="false"` I expect the FAB to be like this:

![image](https://user-images.githubusercontent.com/14335270/41622088-351369c4-7417-11e8-8e11-34716ef74e5a.png)

However when I set `app:fabAttached="false"` I get this:

![image](https://user-images.githubusercontent.com/14335270/41622047-1c9ed928-7417-11e8-99cc-7351b36cbf11.png)

Am I missing something or is there a bug with the component?

**Comment by cketcham** [comment]
This behavior was actually was changed and there is explicit guidance to keep the fab touching the BottomAppBar at all times while they are both on the screen.

If you want the behavior in the first picture, you should set `fabCradleMargin` to `0dp`.

The `fabAttached` attribute is being removed in the next release.

**Comment by firatkarababa** [comment]
great to know, thanks @cketcham

**Comment by firatkarababa** [comment]
@cketcham I have another problem related to this issue. Setting `fabCradleMargin `to `0dp` in resting condition seems to be working but when using BottomAppBar hide on scroll behaviour, the cradle is explicitly shown. I guess we need some attribute to set fab cradle diameter to `0dp `but as far as I see `fabCradleDiameter ` attribute is also gone in alpha3.

![scroll](https://user-images.githubusercontent.com/14335270/42172637-4571b786-7e25-11e8-9e0a-32996368eeb2.gif)

**Comment by cketcham** [comment]
yeah... You're right, the cradle is supposed to animate around the fab, so when the BottomAppBar scrolls off the screen, the cutout shouldn't be visible.

I didn't fix this since I'm waiting for the shape theming to be finished since I'm planning to have the cutout of the BottomAppBar react to the shape of the fab.

This is an interesting case I didn't think about though... If you have space around the cutout it's less obvious. haha.

**Comment by firatkarababa** [comment]
It will be fixed on August then I guess. Should I look for some workaround, if there exist any? 😃

**Comment by cketcham** [comment]
For now the only work around would be to not anchor the Fab to the BottomAppBar, just position the Fab above the BottomAppBar in the layout. This way the BottomAppBar will think there is no Fab and won't draw the cutout
