### ISSUE TITLE
compileSdkVersion = 'android-P' All packages are not available for download! The following packages are not available: - Package id platforms;android-P

### ISSUE THREAD

**Issue by akashjpro** [material-components/material-components-android#152]
*Fix to Built project:
1.Change 'android-P' -> 28
2.Change targetSdkVersion 27 -> 28 
3.Sync project
4. File -> Setting -> Buil, Execution, Deployment -> Install Run -> Uncheck "Enable instant run..."

**Comment by kokoimagine** [comment]
I cannot install apk.
Thank you.

**Comment by popeye17** [comment]
Actually:
1. change compileSdkVersion 'android-P' -> 'android-28'

**Comment by akashjpro** [comment]
Thanks
