### ISSUE TITLE
[ProgressIndicator] Add behavior for show delay like ContentLoadingProgressBar

### ISSUE THREAD

**Issue by vrendina** [material-components/material-components-android#1524]
**Is your feature request related to a problem? Please describe.**
ContentLoadingProgressBar implements a delayed show mechanism. It seems like a common practice to wait ~500ms before showing a loading indicator and in most cases it does not need to be shown at all if the request completes quickly enough.

**Describe the solution you'd like**
ProgressIndicator should implement a customizable `showDelay` to allow the view to become visible only if `hide` has not been called within the interval. 

In addition to the above request, it may also make sense to allow customization of how the progress bar is hidden (invisible vs gone).

**Comment by matpag** [comment]
I can work on the base implementation of this if @pekingme is ok with that.

Should the delay be fixed or customizable? In ContentLoadingProgressBar it wasn't

**Comment by vrendina** [comment]
@matpag I think it would be great if it was customizable since the min show time is already customizable. We usually end up having to copy `ContentLoadingProgressBar` and modify it to suit our needs, ideally you wouldn't need to do that with the `ProgressIndicator` if it is flexible enough.

**Comment by matpag** [comment]
I think you are talking about `minHideDelay`.

By the way a customizable property for a `minShowDelay` or `showDelay`, would bring some more complexity, because if someone call "setMinShowDelay" while the delay is already in progress we can end up with subtle bug if not handled correctly, we should add more checks for this to not happen.

**Comment by pekingme** [comment]
Hi @matpag, adding this as a customizable attribute sounds good to me. We don't have a setter for `minHideDelay`, so if we apply the same on `minShowDelay`, we don't need to deal with the case of changing while the delay in progress. Do you foresee any other unsafe cases to customize this, in opposite to make it fixed?

**Comment by matpag** [comment]
No, I don't see any problem other than the one mentioned, and I forgot that we already thought about it in the previous change >.<

We can stick to the same logic for sure.

**Comment by pekingme** [comment]
Right. Do you want to make the PR for that? I'd also like to do it. Your call 🙂

**Comment by matpag** [comment]
If you have time to work on this, go on ;)
I will follow your commits when you are done
