### ISSUE TITLE
[ShapeAppearanceModel] The strange cut corners

### ISSUE THREAD

**Issue by Kyouha2020** [material-components/material-components-android#1525]
**Description:** When I set 24dp cut corners to a 48dp-height button, its shape may be wrong. But I can't ensure whether the rounded corners behave that.

**Expected behavior:** The button shouldn't have a strange shape

**Source code:** 
the forth button:
![image](https://user-images.githubusercontent.com/59816797/88496388-87c21b80-cfef-11ea-8b2c-307be1ab7b80.png)

![image](https://user-images.githubusercontent.com/59816797/88496194-f94d9a00-cfee-11ea-9b9c-111585b3a7b2.png)
This is not Jetpack Compose. "cutCorners(24.px)" equals to "CornerFamily.CUT, 24.px"
![image](https://user-images.githubusercontent.com/59816797/88496314-56495000-cfef-11ea-9e2d-a18b5341e231.png)
![image](https://user-images.githubusercontent.com/59816797/88496468-c48e1280-cfef-11ea-8978-0e09c2318c34.png)

**Android API version:** 30

**Material Library version:** 1.3.0-alpha02

**Device:** Google Pixel

**Comment by gabrielemariotti** [comment]
Use` 50%` in the `shapeAppearanceModel`.

`.setAllCorners(CutCornerTreatment()).setAllCornerSizes(RelativeCornerSize(0.5f))`

**Comment by Kyouha2020** [comment]
@gabrielemariotti But can't I set corner size by a certain dp value?

**Comment by gabrielemariotti** [comment]
@Kyouha2020 Yes of course, but you have to consider paddings and insets (it should be `18dp`)
If you want an half cut corner the best way is to use `50%`.

**Comment by Kyouha2020** [comment]
@gabrielemariotti Thank you. Why it should be 18dp but not 24dp? I don't think paddings or insets can impact on it.

**Comment by gabrielemariotti** [comment]
Just remove the top and bottom `inset`:

```
       <com.google.android.material.button.MaterialButton
            android:insetBottom="0dp"
            android:insetTop="0dp"
```
Using `50%` with `inset=0dp` and default insets:

<img width="279" alt="Schermata 2020-07-27 alle 13 39 51" src="https://user-images.githubusercontent.com/2583078/88538031-f4004780-d00e-11ea-9bdd-ff0d41e85e39.png">

Now using:

- `24dp` and` inset = 0dp`
- `24dp` and default insets
- `18dp` and default insets


<img width="329" alt="Schermata 2020-07-27 alle 13 41 43" src="https://user-images.githubusercontent.com/2583078/88538154-290c9a00-d00f-11ea-9cfb-73c9e2a9d921.png">

**Comment by Kyouha2020** [comment]
@gabrielemariotti Understood. I ignored the insects. Thank you very much.
