### ISSUE TITLE
[Material Alert Dialog] Buttons don't have states

### ISSUE THREAD

**Issue by janbolat** [material-components/material-components-android#1526]
**Description:** 
Buttons used in Alert Dialogs (which is built with MaterialAlertDialogBuilder) don't have background set (missing pressed and focused states).

I set buttons using the below documentation
https://material.io/develop/android/components/dialogs

Here is my code:
```
<style name="AppTheme">
<item name="materialAlertDialogTheme">@style/AppTheme.Dialog.Alert</item>
</style>

<style name="AppTheme.Dialog.Alert" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
<item name="buttonBarPositiveButtonStyle">@style/MaterialAlertDialog.Button</item>
</style>

<style name="MaterialAlertDialog.Button" parent="Widget.MaterialComponents.Button.TextButton.Dialog" />
```

But if I change `Widget.MaterialComponents.Button.TextButton.Dialog` to `Widget.AppCompat.Button.ButtonBar.AlertDialog`, buttons have correct background (and states)

Using `com.google.android.material:material:1.2.0-rc01`

**Comment by dsn5ft** [comment]
What are you trying to accomplish? The code snippet you provided doesn't change anything from the library's defaults. Also, I tried the code snippet and the button has the correct pressed, focused, etc. states. Are you sure you're not doing anything else in your custom `MaterialAlertDialog.Button` like setting the `android:background` to a color as opposed to a ColorStateList?

If you are trying to change the positive/negative button text color, this is an example of how you could do that:

```
    <style name="AppTheme" parent="Theme.MaterialComponents.Light">
        <item name="materialAlertDialogTheme">@style/ThemeOverlay.MyApp.MaterialAlertDialog</item>
    </style>

    <style name="ThemeOverlay.MyApp.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="buttonBarNegativeButtonStyle">@style/Widget.MyApp.NegativeButton</item>
        <item name="buttonBarPositiveButtonStyle">@style/Widget.MyApp.PositiveButton</item>
    </style>

    <style name="Widget.MyApp.NegativeButton" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="materialThemeOverlay">@style/ThemeOverlay.MyApp.NegativeButton</item>
    </style>

    <style name="Widget.MyApp.PositiveButton" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="materialThemeOverlay">@style/ThemeOverlay.MyApp.PositiveButton</item>
    </style>

    <style name="ThemeOverlay.MyApp.NegativeButton" parent="">
        <item name="colorPrimary">#f00</item>
    </style>

    <style name="ThemeOverlay.MyApp.PositiveButton" parent="">
        <item name="colorPrimary">#00f</item>
    </style>
```

Please re-open if needed, and provide a minimal sample app repo that reproduces the issue.
