### ISSUE TITLE
[Slider] Attribute "android:enabled" not working

### ISSUE THREAD

**Issue by QuentinLB** [material-components/material-components-android#1531]
**Description:**
When using the default slider, if provided the `android:enabled` attribute inside a layout, the slider is not disabled.

**Expected behavior:** 
I expect that using  `android:enabled`  has the same effect than `slider.isEnabled = false` (kotlin) which works properly.

**Source code:** 

```xml
<com.google.android.material.slider.Slider
            android:layout_width="200dp"
            android:layout_height="wrap_content"
            android:enabled="false"/>
```

**Android API version:** 
* Execution env : API 22
* Target env : API 29

**Material Library version:** 1.3.0-alpha02

**Device:** No name tablet running API 22

**Comment by matpag** [comment]
`Slider.processAttribute(...)` is missing `android:enabled` evaluation.
Probably we should have it

**Comment by QuentinLB** [comment]
Thanks a lot @matpag !
