### ISSUE TITLE
Error inflating class com.google.android.material.slider.Slider

### ISSUE THREAD

**Issue by Mayank1904** [material-components/material-components-android#1532]
**Description:** Error inflating class com.google.android.material.slider.Slider

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** 
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/colorPrimary">

    <com.google.android.material.slider.Slider
            android:id="@+id/seekBar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:value="70"
            android:valueFrom="0"
            android:valueTo="100"
            app:labelBehavior="withinBounds"
            app:labelStyle="@style/Widget.MaterialComponents.Tooltip"

            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
**Android API version:** Android API version here

**Material Library version:** com.google.android.material:material:1.3.0-alpha01
**Device:** Realme 2 pro

**Comment by dsn5ft** [comment]
@Mayank1904 what is the exception?
