### ISSUE TITLE
[MaterialButton] strokeColor and strokeWidth not working after set background attr

### ISSUE THREAD

**Issue by DreamerLeon** [material-components/material-components-android#1536]
**Description:** MaterialButton set strokeColor 、strokeWidth and background attr in my layout xml file,border not display , only remove background node that strokeColor and strokeWidth can working

**Expected behavior:** MaterialButton border can display

**Source code:** 
    
``    <com.google.android.material.button.MaterialButton
        android:id="@+id/button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="51dp"
        android:text="Button"
        android:background="@drawable/btn_bg"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:strokeColor="@android:color/holo_red_light"
        app:strokeWidth="4dp" />
``

**Android API version:** Android 10

**Material Library version:** 1.3.0-alpha02

**Device:** Leeco 1pro

**Comment by gabrielemariotti** [comment]
I think it is an expected result.  
If you are using the `background` attribute the MaterialButton doesn't use a` MaterialShapeDrawable`

Checking the [source code](https://github.com/material-components/material-components-android/blob/1.3.0-alpha02/lib/java/com/google/android/material/button/MaterialButtonHelper.java#L120):

```
    if (attributes.hasValue(R.styleable.MaterialButton_android_background)) {
      setBackgroundOverwritten();
    } else {
      materialButton.setInternalBackground(createBackground());
      MaterialShapeDrawable materialShapeDrawable = getMaterialShapeDrawable();
      if (materialShapeDrawable != null) {
        materialShapeDrawable.setElevation(elevation);
      }
    }
```
and the stroke (and not only) is applied in the `materialShapeDrawable`

**Comment by dsn5ft** [comment]
Correct, stroke is only supported with `MaterialButton`'s default `MaterialShapeDrawable` background.

**Comment by DreamerLeon** [comment]
@dsn5ft Thanks for your answer!  I found that I can use `backgroundTint` change background color .

**Comment by DreamerLeon** [comment]
@gabrielemariotti Thanks for your answer!  I found that I can use `backgroundTint` change background color .

**Comment by zeinabrahnamaee** [comment]
@0xByteLeon yeap! `backgroundTint` solved my problem.
