### ISSUE TITLE
[AppBar] AS complains behaviour string as non-public 

### ISSUE THREAD

**Issue by andhie** [material-components/material-components-android#154]
### Reproduction steps
Use `app:layout_behavior="@string/appbar_scrolling_view_behavior`, Android Studio will complain its not a public res

### Version number
Still exists android Design support lib v28.0.0-alpha3

### Operating system and device
N/A. AS Linting issue

### Related issues

 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by dsn5ft** [comment]
Thanks for pointing this out! We have submitted your PR internally and synced it back here.
