### ISSUE TITLE
[Chip] Close button's color doesn't match the one from Material Design specs site

### ISSUE THREAD

**Issue by leinardi** [material-components/material-components-android#1540]
**Description:** The color of the Close button of the Chips does not match the one visible on the Material Design specification web site.

**Expected behavior:** The color of the close button is too dark if compared to the one from the specs website

[Spec site](https://material.io/components/chips#input-chips): ![image](https://user-images.githubusercontent.com/273338/88815933-29966380-d1bc-11ea-92e7-8b143902faae.png)
Library: ![image](https://user-images.githubusercontent.com/273338/88815808-0cfa2b80-d1bc-11ea-91b0-cd244e56f9c1.png)

**Source code:** The source of the issue seems to be`@color/mtrl_chip_close_icon_tint`
```xml
<selector xmlns:android="http://schemas.android.com/apk/res/android">

  <item android:alpha="1.0" android:color="?attr/colorOnSurface" android:state_pressed="true"/>
  <item android:alpha="1.0" android:color="?attr/colorOnSurface" android:state_focused="true" android:state_hovered="true"/>
  <item android:alpha="1.0" android:color="?attr/colorOnSurface" android:state_focused="true"/>
  <item android:alpha="1.0" android:color="?attr/colorOnSurface" android:state_hovered="true"/>
  <item android:alpha="0.87" android:color="?attr/colorOnSurface" android:state_enabled="true"/>
  <!-- 38% of 54% opacity. -->
  <item android:alpha="0.21" android:color="?attr/colorOnSurface"/>

</selector>
```

A better fitting value for the alpha seems to be `0.54`: ![image](https://user-images.githubusercontent.com/273338/88816345-93af0880-d1bc-11ea-8585-2ebfb58c7922.png)

The disabled alpha seems also wrong, this is what to me looks more similar to the website images:

```xml
<selector xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:alpha="1.0" android:color="?attr/colorOnSurface" android:state_pressed="true" />
    <item android:alpha="1.0" android:color="?attr/colorOnSurface" android:state_focused="true" android:state_hovered="true" />
    <item android:alpha="1.0" android:color="?attr/colorOnSurface" android:state_focused="true" />
    <item android:alpha="1.0" android:color="?attr/colorOnSurface" android:state_hovered="true" />
    <item android:alpha="0.54" android:color="?attr/colorOnSurface" android:state_enabled="true" />
    <!-- 25% of 54% opacity. -->
    <item android:alpha="0.15" android:color="?attr/colorOnSurface" />

</selector>
```

**Android API version:** API 29

**Material Library version:** 1.2.0-rc01

**Device:** Google Pixel 2

**Comment by wcshi** [comment]
This is WAI, the spec website is out of date.

The alpha value was enabled state used to be 0.54 but was updated to 0.87 (along with other adjustments see https://github.com/material-components/material-components-android/commit/5834d44a8533de7f6186b92bee789548e131f623 to ensure that close icon has sufficient contrast.) to ensure a contrast ratio > 4.5

**Comment by wcshi** [comment]
I will request an update to the spec site.
