### ISSUE TITLE
MaterialAlertDialog Transparent Background

### ISSUE THREAD

**Issue by ridwan-aswan** [material-components/material-components-android#1541]
**Description:** I use the material design component for alert dialog, I want a transparent black background color, but there is something strange in the backgound, there is a little white color, how to solve this problem. please the solution.

![device-2020-07-29-210643](https://user-images.githubusercontent.com/56959334/88816894-16e55400-d1e7-11ea-8a5f-96ade7ad4103.png)
<img width="756" alt="Screen Shot 2020-07-29 at 22 01 15" src="https://user-images.githubusercontent.com/56959334/88816953-28c6f700-d1e7-11ea-982a-114c9d48b39c.png">

**Android API version:** 29

**Material Library version:** 1.1.0

**Comment by gabrielemariotti** [comment]
It is enough to replicate the issue:

```
 new MaterialAlertDialogBuilder(MainActivity.this,R.style.AlertDialogTheme)
       .setPositiveButton("OK", null)
       .show(); 
```

 ```
  <style name="AlertDialogTheme" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="colorSurface">@android:color/transparent</item>      
    </style>
```

<img width="280" alt="Schermata 2020-07-29 alle 20 17 37" src="https://user-images.githubusercontent.com/2583078/88837629-adf6df80-d1d8-11ea-9218-a4d1f989614b.png">

**Comment by dsn5ft** [comment]
Looks like the white bar is there even for an AppCompat `AlertDialog`. Reproduced with the following (`androidx.appcompat.app.AlertDialog`):

```
        new AlertDialog.Builder(this, R.style.AlertDialogTheme)
            .setPositiveButton("OK", null)
            .show();
```

```
    <style name="AlertDialogTheme" parent="ThemeOverlay.AppCompat.Dialog.Alert">
        <item name="android:colorBackground">@android:color/transparent</item>
    </style>
```

![image](https://user-images.githubusercontent.com/1420597/88881797-4e132f80-d1fe-11ea-888f-5935dea69ee9.png)

So this should be filed as an AppCompat issue:

https://issuetracker.google.com/issues/new?component=460343&template=1422420

**Comment by ridwan-aswan** [comment]
I have not found a solution, this is what I use in my code :

Objects.requireNonNull(new MaterialAlertDialogBuilder(RegisterActivity.this, R.style.AlertDialogTheme)
                        .setTitle("Dialog")
                        .setMessage("Lorem ipsum dolor ....")
                        .setPositiveButton("OK", null)
                        .setCancelable(true)
                        .show());




style.xml

<resources>


    
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="AlertDialogTheme" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="colorSurface">#C1121212</item>
        <item name="elevation">0dp</item>
        <item name="materialAlertDialogTitleTextStyle">@style/TitleTextStyle</item>
        <item name="materialAlertDialogBodyTextStyle">@style/BodyTextStyle</item>
        <item name="buttonBarPositiveButtonStyle">@style/PositiveButtonStyle</item>
        <item name="buttonBarNegativeButtonStyle">@style/NegativeButtonStyle</item>
        <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.MyApp.Dialog.Rounded</item>
    </style>
    <style name="TitleTextStyle" parent="MaterialAlertDialog.MaterialComponents.Title.Text">
        <item name="android:textColor">#fafafa</item>
        <item name="android:textStyle">bold</item>
        <item name="android:textSize">20sp</item>
    </style>
    <style name="BodyTextStyle" parent="MaterialAlertDialog.MaterialComponents.Body.Text">
        <item name="android:textColor">#c7c7c7</item>
        <item name="android:textSize">14sp</item>
    </style>
    <style name="PositiveButtonStyle" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="android:textColor">#d81b60</item>
        <item name="rippleColor">#ad1457</item>
    </style>
    <style name="NegativeButtonStyle" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="android:textColor">#757575</item>
        <item name="rippleColor">#a4a4a4</item>
    </style>
    <style name="ShapeAppearanceOverlay.MyApp.Dialog.Rounded" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">14dp</item>
    </style>
</resources>

**Comment by PembaTamang** [comment]
I am also going through the same issue anyone found a fix to this ?

**Comment by WonkiJo** [comment]
I resolved this problem 

<item name="android:background">@color/background</item>


`
   <style name="Material.Dialog" parent="ThemeOverlay.Material3.MaterialAlertDialog">
        <item name="android:background">@color/background</item>
        <item name="elevation">0dp</item>
        <item name="alertDialogStyle">@style/CustomStyle</item>
        <item name="materialAlertDialogTitleTextStyle">@style/Material3.TextAppearance.Dialog.Title</item>
        <item name="materialAlertDialogBodyTextStyle">@style/Material3.TextAppearance.Dialog.Body</item>
        <item name="buttonBarPositiveButtonStyle">@style/Material3.TextButton.Default</item>
        <item name="buttonBarNegativeButtonStyle">@style/Material3.TextButton.Default</item>
    </style>
`

**Comment by Geekince** [comment]
> I resolved this problem
> 
> `<item name="android:background">@color/background_color</item>`

Yes，This works fine.

So, Why colorSurface is not woking ?
