### ISSUE TITLE
[MaterialCardView] Elevation shadow doesn't fit in

### ISSUE THREAD

**Issue by b0r1s** [material-components/material-components-android#1543]
Hi, I updated to material 1.3.0-alpha02 (API 29) and I can see the new elevation shadow, but I think the shadow is a bit moved downwards (?): it seems that there is less shadow behind the top of the card (and more behind the bottom of the card) while the animation is running vs at the beginning or the end of the animation.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/36534836/88845466-7db53e00-d1e4-11ea-867f-fd0d865c5e37.gif)

GIF's project: [MyApplication - shadow.zip](https://github.com/material-components/material-components-android/files/4997106/MyApplication.-.shadow.zip)

_Originally posted by @b0r1s in https://github.com/material-components/material-components-android/issues/1126#issuecomment-665868284_

**Comment by dsn5ft** [comment]
Thanks @b0r1s, this is because we approximate native shadows during the transition, and they don't match exactly. We'll look into making our shadow vertical offset more dynamic.
