### ISSUE TITLE
[SwitchMaterial] Replace SwitchCompat with SwitchMaterial

### ISSUE THREAD

**Issue by lupajz** [material-components/material-components-android#1555]
**Is your feature request related to a problem? Please describe.**
MaterialComponentsViewInflater doesn't replace SwitchCompat with SwitchMaterial even though SwitchCompat is declared in XML layout.

**Describe the solution you'd like**
SwitchCompat to be replaced with SwitchMaterial

**Additional context**
Or is there reason, that I'm overlooking as why this is not supported ?

**Comment by dsn5ft** [comment]
Hi @lupajz, this is because [`AppCompatViewInflater`](https://developer.android.com/reference/androidx/appcompat/app/AppCompatViewInflater), which `MaterialComponentsViewInflater` is built on top of, does not auto-inflate `SwitchCompat` for the framework `Switch`. The reason for that is due to the AppCompat `SwitchCompat` not actually extending from the framework `Switch` class, so one cannot be replaced with the other.

**Comment by lupajz** [comment]
Yes @dsn5ft you are right about that. But in [AppCompatViewInflater](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:appcompat/appcompat/src/main/java/androidx/appcompat/app/AppCompatViewInflater.java;l=113?q=AppCompatViewInflater&ss=androidx%2Fplatform%2Fframeworks%2Fsupport)
you would receive a `androidx.appcompat.widget.SwitchCompat` request that could be transformed in `MaterialComponentsViewInflater` overriding `createView(Context context, String name, AttributeSet attrs)`. Would that be a problem ? I see how that diverges from AppCompat which doesn't replace Switch, since it's custom implementation of platform one, but on the other hand Material library elements extend from AppCompat ones and this way the usages of SwitchCompat would be replaced by the Material version using LayoutInflater.Factory.

**Comment by dsn5ft** [comment]
Correct, but we also have a rule not to automatically replace any fully qualified widget paths, like `androidx.appcompat.widget.SwitchCompat`, with something else, as that could be misleading.

Also, that `createView` in `AppCompatViewInflater` is final so I'm not sure we could do it even if we wanted to.

**Comment by lupajz** [comment]
Didn't know about that rule, thanks for the info.

I wasn't refering to the final quilified method, but [the one](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:appcompat/appcompat/src/main/java/androidx/appcompat/app/AppCompatViewInflater.java;l=272?q=AppCompatViewInflater&ss=androidx%2Fplatform%2Fframeworks%2Fsupport) that is called in default branch of that switch statement.
