### ISSUE TITLE
[ShapeableImageView] Cut shape doesn't have elevation

### ISSUE THREAD

**Issue by alorma** [material-components/material-components-android#1562]
**Description:** When using `ShapeableImageView` with `shapeAppearance.cornerFamily` set to `cut` it not have any shadow when using elevation

<img width="185" src="https://user-images.githubusercontent.com/887462/89297174-bda47700-d663-11ea-82f9-cd8698a260e1.png">

**Expected behavior:** Any shape corner family should have elevation

**Source code:** Demo sample: https://github.com/alorma/SampleCode_ShapeableImageView_elevation_Bug

**Android API version:** 29

**Material Library version:** 1.2.0-rc01)

**Device:** Emulator / ANY

**Comment by alorma** [comment]
Related with #1329

**Comment by wcshi** [comment]
Resolved in https://github.com/material-components/material-components-android/commit/fbefa5a0ec6af754a278810845c9b0df296b0bc6
