### ISSUE TITLE
[BottomNavigationView] How to clip to a background?

### ISSUE THREAD

**Issue by luis-cortes** [material-components/material-components-android#1565]
I'd like to have a `BottomNavigationView` where only the top left and right corners are rounded. 

```
// nav_bar_bg
<?xml version="1.0" encoding="utf-8"?>
<shape
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:shape="rectangle">
  <solid android:color="?colorSurface" />
  <corners
    android:topLeftRadius="@dimen/corner_size"
    android:topRightRadius="@dimen/corner_size" />
</shape>
```
```
  <com.google.android.material.bottomnavigation.BottomNavigationView
    android:id="@+id/bottom_nav_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@drawable/nav_bar_bg"
    app:menu="@menu/bottom_nav_menu"
    />
```

Using this method, the rounded corners are visible, but the bottom nav view continues to draw all the way to the corners. [
![corner_issue](https://user-images.githubusercontent.com/16602090/89324910-05240680-d656-11ea-97f5-6be32cae11c0.png)
](url)

1 is the area I'd like to be transparent, 2 is the bottom nav view, and 3 is the color that I'd like to show up where 1 is.

The clipping to outline API...
```
layout.outlineProvider = ViewOutlineProvider.BACKGROUND
layout.clipToOutline = true
```
 is of no help because `Outline.canClip()` returns false

Is what I'd like to do possible?

**Comment by gabrielemariotti** [comment]
You can apply a `MaterialShapeDrawable`:


        val cornerRadius = resources
                .getDimensionPixelOffset(R.dimen.default_corner_radius).toFloat()

        val bottomNavigationView : BottomNavigationView = findViewById(R.id.bottomnav)
        val bottomBarBackground = bottomNavigationView.background as MaterialShapeDrawable
        bottomBarBackground.shapeAppearanceModel = bottomBarBackground.shapeAppearanceModel
                .toBuilder()
                .setTopRightCorner(CornerFamily.ROUNDED, cornerRadius)
                .setTopLeftCorner(CornerFamily.ROUNDED, cornerRadius)
                .build()
        bottomBarBackground.fillColor = ContextCompat.getColorStateList(this, R.color.....)
        ViewCompat.setBackground(bottomNavigationView, bottomBarBackground)


<img width="295" alt="Schermata 2020-08-04 alle 20 08 55" src="https://user-images.githubusercontent.com/2583078/89328885-564fec80-d68e-11ea-904d-cb47ada24a15.png">

**Comment by luis-cortes** [comment]
Thanks for taking the time to respond. 

I understand the issue a little better now and I don't think `BottomNavigationView` is responsible for what I'm seeing.

The problem I'm actually having is that the activity's background color is coming through where the corners used to be. 
What I want is for the content of my fragment to come through. However, this doesn't seem possible because the `FragmentContainerView` is a sibling of the `BottomNavigationView`. 

Side note, setting the background in xml yields the exact same results as doing it programmatically, however my minSdk is 24.

**Comment by luis-cortes** [comment]
For anyone curious, I solved this by putting the `BottomNavigationView` and the `FragmentContainerView` in a `FrameLayout` like this:

```
<FrameLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:id="@+id/mainContainer"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  tools:context=".MainActivity"
  >

  <androidx.fragment.app.FragmentContainerView
    android:id="@+id/navHostFragment"
    android:name="androidx.navigation.fragment.NavHostFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:defaultNavHost="true"
    app:navGraph="@navigation/nav_graph"
    />

  <com.google.android.material.bottomnavigation.BottomNavigationView
    android:id="@+id/bottomNavView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom"
    android:background="@drawable/nav_bar_bg"
    app:menu="@menu/bottom_nav_menu"
    />
</FrameLayout>
```

This may not work for everyone and it won't be free for me. As an example, views with `app:layout_anchor`s that previously relied on the bottom of the `FragmentContainerView` meeting the top of the `BottomNavigationView` are now broken.
