### ISSUE TITLE
[Doubt] From 1.3.0-alpha02 to 1.20 ??

### ISSUE THREAD

**Issue by ubarua123** [material-components/material-components-android#1569]
Should I upgrade or not?

**Comment by MGaetan89** [comment]
Do you need something from [1.3.0-alpha01](https://github.com/material-components/material-components-android/releases/tag/1.3.0-alpha01) or [1.3.0-alpha02](https://github.com/material-components/material-components-android/releases/tag/1.3.0-alpha02)?

**Comment by wcshi** [comment]
If you are already using 1.3.0-alpha02, you do not need to switch to 1.2.0 stable release. The alpha versions generally have all the changes in the beta / stable releases + new changes whose API may not be finalized.
