### ISSUE TITLE
[BottomSheetDialogFragment] Since Ver. 1.2.0 different dismiss behavior

### ISSUE THREAD

**Issue by bobekos** [material-components/material-components-android#1570]
**Description:**
Since Version 1.2.0 and above the dismiss gesture detection is working differently then in 1.1.0.
Where I could easily dismiss the dialog in version 1.1.0, i cannot do it since version 1.2.0. First I thought about the new attribute "gestureInsetBottomIgnored" but that seems to have nothing to do with it. In version 1.2.0 the callback "close the dialog" seems to depend on a certain length of the dismiss (swipe down) gesture. Difficult to describe, best take a look at the video below.

**Expected behavior:**
Dismiss gesture is working like in the Version 1.1.0.

Video Version 1.1.0 https://we.tl/t-DOOuTP8TbB
Video Version 1.2.0 https://we.tl/t-w4fyZ8OjMo

[video_demo.zip](https://github.com/material-components/material-components-android/files/5033200/video_demo.zip)

**Source code:**
You must do nothing, no special themes or other settings. This simple thing is already working differently between the two versions.

```


//just normal dialog (no special theme)
class BottomSheetTest : BottomSheetDialogFragment() {

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? = inflater.inflate(R.layout.fragment_test, container, false)

}

//default show
BottomSheetTest().show(supportFragmentManager, TAG)
```

**Android API version:**
Android 10

**Material Library version:**
1.1.0 and 1.2.0

**Device:**
Pixel 3a

**Comment by bobekos** [comment]
It seems like this method here pass other peekHeight to the result:

```
boolean shouldHide(@NonNull View child, float yvel) {
    if (skipCollapsed) {
      return true;
    }
    if (child.getTop() < collapsedOffset) {
      // It should not hide, but collapse.
      return false;
    }
    int peek = calculatePeekHeight();
    final float newTop = child.getTop() + yvel * HIDE_FRICTION;
    return Math.abs(newTop - collapsedOffset) / (float) peek > HIDE_THRESHOLD;
  }
```

In the Version 1.1.0 the peek was always 0 when peek_height was set to auto. So this means that the result was always true.

**Comment by dsn5ft** [comment]
Hi @bobekos, thanks for sharing the code snippet, but I'm unable to reproduce this. Can you share a minimal sample app with the full setup that reproduces the issue?

**Comment by bobekos** [comment]
Hi @dsn5ft 

as said before you do not need a specific setup. You must just compare the "dismiss gesture" of the two versions. I have now created a project where you can set the version 1.1.0 or the version 1.2.0 based on the buildtype (material110 and material120).

Just start first the material110 version and dismiss the bottomsheet with a gesture. Then start the material120 version and make the same. You will see the behavior is different. The version 1.1.0 is just smoother. With version 1.2.0 i often need to repeat the dismiss gesture until the dialog closed.

[MaterialBottomSheet.zip](https://github.com/material-components/material-components-android/files/5141374/MaterialBottomSheet.zip)

**Comment by dsn5ft** [comment]
Just discovered it's because of this commit: https://github.com/material-components/material-components-android/commit/c47e6a4e3f44b8768446fbac5ec5697ab62223a8.

We'll try to figure out a fix.

**Comment by ymarian** [comment]
@bobekos  Can you try on the new release?

https://github.com/material-components/material-components-android/releases/tag/1.2.1

**Comment by bobekos** [comment]
@dsn5ft @ymarian 
fixed! thank you very much
