### ISSUE TITLE
[ExposedDropdownMenu] inputType="none" removes padding below lollipop

### ISSUE THREAD

**Issue by jmartingit** [material-components/material-components-android#1573]
**Description:**

Setting inputType="none" in an AutoCompleteTextView inside an ExposedDropdownMenu removes the whole padding of the input layout (vertically and horizontally) **below** Android 5.0,

**Expected behavior:**

The padding of the input layout should be preserved, as it happens when inputType="text".

**Source code:**

                <com.google.android.material.textfield.TextInputLayout
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:hint="@null"
                    >
                    <AutoCompleteTextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:hint="@null"
                        android:inputType="none"
                        />
                </com.google.android.material.textfield.TextInputLayout>

**Android API version:** 

Tested on APIs 16 to 19 (where the problem happens)
Tested on APIs 21 to 29 (where the problem doesn't happen)

**Material Library version:**

com.google.android.material:material:1.2.0

**Device:**

Android Studio emulators

**Question:**

Is there a workaround for this issue?

**Comment by jmartingit** [comment]
I discovered that when I set the input type programmatically the problem doesn't happen, so I guess that's the workaround:

    autoCompleteView.setInputType(InputType.TYPE_NULL);

**Comment by drchen** [comment]
Is this still happening with the latest library version?

**Comment by drchen** [comment]
Thanks for your quick response! If that's the case I'll close the issue for now. Feel free to reopen it if you are still seeing similar issues. : )
