### ISSUE TITLE
[RangeSlider] theming of valueLabel applies only to unselected label

### ISSUE THREAD

**Issue by NoyaD9** [material-components/material-components-android#1578]
**Description:**  After theming a label using the following attributes:

```
  <com.google.android.material.slider.RangeSlider
      ...
      app:labelStyle="@style/Filters.Style.Criteria.SliderSectionItem.SliderLabel"
      />
```

in styles.xml:

```
  <style name="Filters.Style.Criteria.SliderSectionItem.SliderLabel" parent="Widget.MaterialComponents.Tooltip">
    <item name="backgroundTint">?cosmaColorFloatingButtonSecondaryVariantBackground</item>
    <item name="android:textAppearance">@style/Filters.TextAppearance.Criteria.SliderSectionItem.SliderLabel</item>
  </style>

  <style name="Filters.TextAppearance.Criteria.SliderSectionItem.SliderLabel" parent="TextAppearance.MaterialComponents.Tooltip">
    <item name="android:textColor">?colorSurface</item> 
    <item name="fontFamily">@font/cosma_make_it_sans</item>
    <item name="android:fontFamily">@font/cosma_make_it_sans</item>
  </style>
```
I see only the currently unselected item of the range being styled properly:

![sliderbug](https://user-images.githubusercontent.com/25151005/89536834-bfec0a00-d7f8-11ea-8904-4454ea0ce519.png)

**Expected behavior:** both value label are having the same style (black with white text)

**Source code:**  see above

**Android API version:** 28

**Material Library version:** 1.2.0

**Device:** Samsung Galaxy S10

**Comment by NoyaD9** [comment]
FYI: I was also able to reproduce it on an Emulator with API 29 and by hardcoding the colors instead of using the attributes

```
  <style name="Filters.Style.Criteria.SliderSectionItem.SliderLabel" parent="Widget.MaterialComponents.Tooltip">
    <item name="backgroundTint">@color/cosma_charcoal</item>
    <item name="android:textAppearance">@style/Filters.TextAppearance.Criteria.SliderSectionItem.SliderLabel</item>
  </style>

  <style name="Filters.TextAppearance.Criteria.SliderSectionItem.SliderLabel" parent="TextAppearance.MaterialComponents.Tooltip">
    <item name="android:textColor">@color/cosma_white</item>
    <item name="fontFamily">@font/cosma_make_it_sans</item>
    <item name="android:fontFamily">@font/cosma_make_it_sans</item>
  </style>
```

**Comment by cketcham** [comment]
@NoyaD9 I tested with our catalog on an Emulator with API 29 and I wasn't able to reproduce this problem. Is it possible the theme on the activity is changed somehow? That's the only thing I can think that could be happening. It will create new labels on demand (depending on the number of values). So it's possible that when one of the labels is created it has lost the theming info some how. How are you setting the values?

Can you create a clean sample project that demonstrates this bug and send that to me?

**Comment by NoyaD9** [comment]
@cketcham thanks for the reply! I will create a project from scratch and try to reproduce. I will contact you as soon as it's ready

**Comment by sebastianharder** [comment]
Same issue when I don't set `sliderStyle` on the theme, but only set the `style` for a single Slider.

Slider version: 1.3.0-rc01

**Comment by MdMahaboobKhan** [comment]
I realize that I encounter this error only when I'm setting initial values for my rangeslider from code. How can I fix this?

**Comment by JasonHaulynx** [comment]
> @cketcham I realize that I encounter this error only when I'm setting initial values for my rangeslider programmatically. It works as expected when I set initial values for my RangeSlider using "app:values". I'm loading the initial values for the range slider from sharedPreferences initially. How can I fix this?

I found that as long as you initially set the values in XML, programatically updating wont effect changing the selected color any longer.

**Comment by Moonglasses** [comment]
Can confirm this is still happening in library version 1.4.0

**Comment by OlehHaidaienko** [comment]
As a temporary solution, you can try to set `materialThemeOverlay` attribute for `Widget.MaterialComponents.Slider` with the required tooltip background color like:
```
<style name="ThemeOverlay.App.Slider" parent="">
     <item name="colorOnBackground">@color/purple_700</item>
 </style>
```

**Comment by evgeny34563** [comment]
Hi. Error when using RangeSlider along with BottomSheetDialogFragment and app:labelBehavior="visible". If you raise and lower the BottomSheetDialogFragment, then the labelBehavior hangs on the screen without moving along with the BottomSheetDialogFragment

**Comment by drchen** [comment]
Can you provide a screen recording of the issue you described?

**Comment by bruno-caetano** [comment]
> @cketcham I realize that I encounter this error only when I'm setting initial values for my rangeslider programmatically. It works as expected when I set initial values for my RangeSlider using "app:values". I'm loading the initial values for the range slider from sharedPreferences initially. How can I fix this?

I see this issue as well and was able to reproduce in the catalog. You can find the minimal reproducible sample attached and a video of it.

[MaterialExampleSlider.zip](https://github.com/material-components/material-components-android/files/9288407/MaterialExampleSlider.zip)
[rangeslider.webm](https://user-images.githubusercontent.com/738961/183596788-b2ffbb41-7115-4acd-b4f4-3bbbb14de2a2.webm)

**Comment by CarloskHard** [comment]
It has been more than a year and I still have this bug :(
