### ISSUE TITLE
[Slider] Padding doesn't work

### ISSUE THREAD

**Issue by bobvse** [material-components/material-components-android#1579]
The "padding" does not work, which is why the "thumb" is not nicely drawn in extreme positions on a white background.

![1](https://user-images.githubusercontent.com/36969567/89551110-38f85b00-d813-11ea-9c82-074160da2d7e.JPG)
![2](https://user-images.githubusercontent.com/36969567/89551113-3990f180-d813-11ea-8b88-d1209a514291.JPG)
![3](https://user-images.githubusercontent.com/36969567/89551114-3990f180-d813-11ea-91af-afbe5bf10527.JPG)

Android 10

1.3.0-alpha02

OnePlus 7, Android Emulator

**Comment by matpag** [comment]
Have you tried using `android:marginStart` and `android:marginEnd` instead?

**Comment by gabrielemariotti** [comment]
I think it is an expected behavior.

In the implementation there is a `trackSidePadding` which is set internally (`16dp`).

**Comment by bobvse** [comment]
> Have you tried using `android:layout_marginStart` and `android:layout_marginEnd` instead? (or marginLeft and right if you have minSDK below API 17)

Yes, the attributes android:layout_marginStart and android:layout_marginEnd does not exist outside, but not inside. This can be seen in the second and third screenshots.

**Comment by matpag** [comment]
@bobvse Can you post the related XML?

**Comment by bobvse** [comment]
> @bobvse Can you post the related XML?

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        tools:context=".ui.MainActivity">

    <com.google.android.material.slider.Slider
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="16dp"
            android:padding="8dp"
            android:textAppearance="@style/TextAppearance.MaterialComponents.Button"
            android:theme="@style/SliderTheme"
            app:haloRadius="0dp"
            app:labelBehavior="gone"
            app:thumbColor="#FFFFFF"
            app:thumbElevation="4dp"
            app:thumbRadius="16dp"
            app:tickColorActive="@color/colorAccent"
            app:tickColorInactive="#E2E5EB"
            app:trackColorActive="@color/colorAccent"
            app:trackColorInactive="#E2E5EB"
            app:trackHeight="4dp" />
</LinearLayout>

![1212121](https://user-images.githubusercontent.com/36969567/89624168-866dda00-d89e-11ea-93e6-b8f4c4c6b2dd.JPG)
![photo_2020-08-07_11-09-23](https://user-images.githubusercontent.com/36969567/89624170-87067080-d89e-11ea-8356-4154db55c189.jpg)

**Comment by gabrielemariotti** [comment]
The real issue to report is that the there is a problem with `app:thumbRadius="16dp"` or higher.
It is due to the internal `trackSidePadding`= `16dp`

**Comment by ryandt** [comment]
It looks like a similar issue happens for vertical padding on the thumb as well. Here's a screenshot of an example with "Show layout bounds" turned on:

![Screenshot_20201211-152421](https://user-images.githubusercontent.com/4073952/101956689-a5220b80-3bc5-11eb-8c1f-0816bf64df05.png)

Relevant code:
```
class CustomSlider @JvmOverloads constructor(
    context: Context,
    defStyleRes: Int = 0,
    attributeSet: AttributeSet
) : Slider(context, attributeSet, defStyleRes) {
    
    init {
        initTrack()
        initThumb()
    }

    private fun initTrack() {
        valueFrom = 0f
        valueTo = 2500f
        stepSize = valueTo / 25
        trackHeight = resources.getDimensionPixelSize(R.dimen.slider_track_height) // 40dp
        isTickVisible = false
        ContextCompat.getColorStateList(context, R.color.selector_slider_track_active)?.let {
            trackActiveTintList = it
        }
        ContextCompat.getColorStateList(context, R.color.selector_slider_track_inactive)?.let {
            trackInactiveTintList = it
        }
    }

    private fun initThumb() {
        thumbRadius = resources.getDimensionPixelSize(R.dimen.slider_thumb_radius) // 57dp
        thumbStrokeWidth = resources.getDimensionPixelSize(R.dimen.slider_thumb_stroke_width).toFloat() // 4dp
        thumbStrokeColor = ContextCompat.getColorStateList(context, R.color.selector_slider_thumb_stroke)
        ContextCompat.getColorStateList(context, R.color.selector_slider_thumb)?.let {
            thumbTintList = it
        }
    }
}
```
