### ISSUE TITLE
[MaterialAlertDialogBuilder] Title textSize cannot be greater then 50sp

### ISSUE THREAD

**Issue by rusanov-vladimir** [material-components/material-components-android#1586]
**Description:** 
I'm implementing custom theme for MaterialAlertDialogBuilder as described [here](https://material.io/develop/android/components/dialogs#theming-dialogs).
Setting font size of the Title above 50sp resets it's back to default value.
![title](https://user-images.githubusercontent.com/3341799/89643503-94cbee00-d8be-11ea-9b22-9c3713971d0f.gif)

**Expected behavior:**
TextSize should allow values above 50sp.

**Source code:** 
```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="materialAlertDialogTheme">@style/ThemeOverlay.App.MaterialAlertDialog</item>
    </style>

    <style name="ThemeOverlay.App.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="materialAlertDialogTitleTextStyle">@style/MaterialAlertDialog.App.Title.Text</item>
    </style>

    <style name="MaterialAlertDialog.App.Title.Text" parent="MaterialAlertDialog.MaterialComponents.Title.Text">
        <item name="android:textSize">50sp</item>
    </style>
</resources>
```
Sample app
[MyApplication.zip](https://github.com/material-components/material-components-android/files/5041165/MyApplication.zip)

**Android API version:** 
Any, tested on API 29

**Material Library version:**
'com.google.android.material:material:1.2.0'
Same problem occurs with AppCompat from support v7 library

**Device:** 
Emulator

**Comment by wcshi** [comment]
Are you saying that Android Studio resets `<item name="android:textSize">50sp</item>`? If it's happening with AppCompat from support v7 library and is not unique to the Material lib, then please file a bug with Android Studio:

https://developer.android.com/studio/report-bugs.html#studio-bugs

**Comment by rusanov-vladimir** [comment]
Yes, that's what I'm saying, it's also in the gif above..
But it has nothing to do with Android Studio, I've originally had this issue in Xamarin Android application developed in totally different IDE.
The theme Theme.MaterialComponents.Light.Dialog comes from v7 library I believe, but it's not AppCompat theme.

**Comment by rusanov-vladimir** [comment]
@wcshi Probably I missread your question first time.
No, the change is done by me manually in Android Studio.
Text size of the title of the AlertDialog is being reset to some default value it seems. In the gif you can see that dialog has big title when the font is 49sp, but becomes small when the font size is changed to 50sp.

**Comment by wcshi** [comment]
Sorry I misunderstood the initial problem. I'm not able to reproduce the bug in our catalog, i added the following:
```
  <style name="Theme.Catalog" parent="Theme.MaterialComponents.DayNight.NoActionBar">
    <item name="catalogToolbarStyle">@style/Widget.Catalog.Toolbar</item>
    <item name="catalogToolbarWithCloseButtonStyle">@style/Widget.Catalog.Toolbar.WithCloseButton</item>
    <item name="textInputSignInStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>
    <item name="windowActionModeOverlay">true</item>
    <item name="materialAlertDialogTheme">@style/ThemeOverlay.App.MaterialAlertDialog</item>
</style>


<style name="ThemeOverlay.App.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
<item name="materialAlertDialogTitleTextStyle">@style/MaterialAlertDialog.App.Title.Text</item>
</style>

<style name="MaterialAlertDialog.App.Title.Text" parent="MaterialAlertDialog.MaterialComponents.Title.Text">
<item name="android:textSize">80sp</item>
</style>
```

![Screenshot_1596834676](https://user-images.githubusercontent.com/38438920/89688972-555acd00-d8d1-11ea-9b3a-87cf463cbf5f.png)

**Comment by gabrielemariotti** [comment]
Tried with `1.2.0 `and `1.3.0-alpha02` with `50sp` and `75sp` without any issue.

<img width="264" alt="Schermata 2020-08-07 alle 23 59 06" src="https://user-images.githubusercontent.com/2583078/89691874-6542d300-d90a-11ea-95f1-50663188240c.png">

**Comment by rusanov-vladimir** [comment]
Thank you for checking! Maybe it's some kind of glitch of the emulator on my machine. But I'll check it on the real device before closing the issue.

**Comment by rusanov-vladimir** [comment]
I've tested my sample application on a real device and it's also happens there, so it's not an emulator glitch after all. From @wcshi screenshot I assume you're testing it on small screen device, but I'm testing it on a ldpi tablet: `15.6"` screensize with resolution `768x1366`. Maybe that's the reason you couldn't reproduce it?

**Comment by rusanov-vladimir** [comment]
I'm able to reproduce this also with the code @wcshi posted. It's seems to be matter of screen/size, with 80sp it works as expected, with 180sp - resets back to some default value.
![2020-08-08_13h44_51](https://user-images.githubusercontent.com/3341799/89708940-fa35e280-d983-11ea-9711-627ec6b4aacb.gif)

**Comment by rusanov-vladimir** [comment]
It seems to be related to project setup, and not to component: it works as expected in a different project.

**Comment by rusanov-vladimir** [comment]
The difference that made it work in another project was the length of the title. With short title like: "Title" it works as expected, with something like "An unexpected error has appeared" it behaves as described above. But I'm not sure anymore that this is related to the the material component or it's an issue in Android AlertDialog, so not reopening...
