### ISSUE TITLE
MaterialButton textAllCaps text lower case

### ISSUE THREAD

**Issue by jeffreyliu8** [material-components/material-components-android#159]
I am trying to make com.google.android.material.button.MaterialButton text lower case, I tried textAllCaps = false, still not working.

**Comment by firatkarababa** [comment]
May be due to a styling overriding `textAllCaps = false` setting. Try to do it programmatically, i.e
`button.transformationMethod = null` (kotlin) or `button.setTransformationMethod(null);` (java)

**Comment by jeffreyliu8** [comment]
just do        app:textAllCaps="false" , not    android:textAllCaps="false" .   Android studio did not auto-complete for me so I thought no such attribute. my bad.

**Comment by ohzono** [comment]
Currently I confirmed `android:textAllCaps` is working in Android Studio preview.
Android Studio version is `Android Studio Chipmunk | 2021.2.1`.
