### ISSUE TITLE
[BottomAppBar] Fab is displaying incorrectly

### ISSUE THREAD

**Issue by verNANDo57** [material-components/material-components-android#1591]
**Description:** Fab is displaying incorrectly after library update

**Expected behavior:** Screenshots are attached

**Source code:** <androidx.coordinatorlayout.widget.CoordinatorLayout
          android:layout_width="fill_parent"
          android:layout_height="fill_parent">
        <com.google.android.material.bottomappbar.BottomAppBar
            android:layout_gravity="bottom"
            android:id="@+id/bar_in_theme_preview"
            android:focusable="false"
            android:clickable="false"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            app:fabAlignmentMode="center"
            app:layout_scrollFlags="exitUntilCollapsed|scroll" />
        <com.google.android.material.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab_in_theme_preview"
            android:focusable="false"
            android:clickable="false"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_home_black"
            app:layout_anchor="@id/bar_in_theme_preview"
            app:layout_insetEdge="right" />
      </androidx.coordinatorlayout.widget.CoordinatorLayout>

**Android API version:** From SDK21 to SDK29

**Material Library version:** Latest 1.2.0

**Device:** tested on MI 6X(wayne), MI A2(jasmine_sprout), Samsung Galaxy Tab S 8.4(klimtlte) [ALSO TESTED ON Android EMU)

![image](https://user-images.githubusercontent.com/49901327/89704070-239e4080-d97b-11ea-92fd-a49f4d38e8fe.png)
![image](https://user-images.githubusercontent.com/49901327/89704079-387ad400-d97b-11ea-9ed1-6fb7d1afabbd.png)
![Screenshot_20200808-133726](https://user-images.githubusercontent.com/49901327/89704244-644a8980-d97c-11ea-854f-e5e307113516.png)

**Comment by matpag** [comment]
In catalog app on master, is working fine.
You can find the layout [here](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/bottomappbar/res/layout/cat_bottomappbar_fragment.xml)
Maybe you are doing something wrong because if I copy-paste your XML in my project, is working fine. Check if you changed some parent theme or styles

**Comment by verNANDo57** [comment]
> In catalog app on master is working fine, you can find the layout [here](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/bottomappbar/res/layout/cat_bottomappbar_fragment.xml)
> Maybe you are doing something wrong because if I copy-paste your XML in my project is working. Check if you changed some parent theme or styles

I have removed my custom bottomappbar style. Also, I have recreated Bottomappbar with default settings and attributes. I can say, it's no use. After research, I realized, bug appears only on very small and very big dpi's (320-340 and 420-...)

P.s Bug does not appear on 1.1.0 version of library

**Comment by verNANDo57** [comment]
> In catalog app on master is working fine, you can find the layout [here](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/bottomappbar/res/layout/cat_bottomappbar_fragment.xml)
> Maybe you are doing something wrong because if I copy-paste your XML in my project is working. Check if you changed some parent theme or styles

@matpag 

I have removed my custom bottomappbar style. Also, I have recreated Bottomappbar with default settings and attributes. I can say, it's no use. After research, I realized, bug appears only on very small and very big dpi's (320-340 and 420-...)

P.s Bug does not appear on 1.1.0 version of library

**Comment by wcshi** [comment]
I'm confused, is the bug that the fab is off centered from the bottom app bar's cradle?

**Comment by verNANDo57** [comment]
> I'm confused, is the bug that the fab is off centered from the bottom app bar's cradle?

@wcshi , yes it is

**Comment by cketcham** [comment]
@verNANDo57 I can't reproduce it. Could you export the hardware profile you are using for the emulator and send it to me so I can try that?

**Comment by verNANDo57** [comment]
Hello there! Umm... The problem disappeared after updating the library. Anyway, thank you for your help.
