### ISSUE TITLE
[MaterialTextView] Typeface.Normal does not work

### ISSUE THREAD

**Issue by HardcodeCoder** [material-components/material-components-android#1594]
**Description:** `textView.setTypeface(textView.getTypeface(), Typeface.NORMAL);` does not work if `textView` previously had `android:textStyle` set to `bold` in xml.

**Expected behavior:** TextView should revert from `Bold` style to `Normal` style after a call to `textView.setTypeface(textView.getTypeface(), Typeface.NORMAL);` 

**Source code:** 
### simple_layout.xml
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:gravity="center_vertical"
    android:orientation="horizontal">

    <ImageView
        android:layout_width="@dimen/colored_icon_width"
        android:layout_height="@dimen/colored_icon_height"
        android:layout_centerVertical="true"
        android:background="@drawable/plain_circle"
        android:padding="@dimen/colored_icon_padding" />

    <com.google.android.material.textview.MaterialTextView
        android:id="@+id/text_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textStyle="bold"
        android:layout_marginStart="16dp"
        android:layout_toEndOf="@id/settings_list_item_icon"
        android:textAppearance="@style/TextViewSubtitle1" />

</RelativeLayout>
```

### MainActivity.java
```@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    
    setContentView(R.layout.simple_layout);
    
    MaterialTextView textView = findViewById(R.id.text_view);
    textView.setTypeface(textView.getTypeface(), Typeface.NORMAL);
}
```

**Android API version:** 29

**Material Library version:** Material Android Library version 1.2.0

**Device:** Xiaomi Redmi Note 8 (ginkgo)

**Comment by wcshi** [comment]
MaterialTextView is a thin wrapper on top of AppCompatTextView, I can reproduce your bug using AppCompatTextView, please file bug in the AndroidX core public issue tracker: https://b.corp.google.com/issues?q=componentid:460834%20status:open
