### ISSUE TITLE
[MaterialCardView] Setting isClickable to false clears active ripple

### ISSUE THREAD

**Issue by ajalt** [material-components/material-components-android#1596]
**Description:** When setting `isClickable` to false while a ripple animation is running, the ripple is immediately removed.

**Expected behavior:** The ripple animation should complete. This would match `Button`'s behavior.

**Source code:** 

If you click the button, you can see that the ripple animation completes, and further clicks don't trigger more ripples. 

If you click the card, the ripple animation aplys for a few frames, then dissapears. Further clicks don't trigger more ripples, as expected.

### activity_main.xml

```xml
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <Button
        android:id="@+id/button"
        android:layout_width="match_parent"
        android:layout_height="64dp"
        android:layout_margin="16dp"/>

    <com.google.android.material.card.MaterialCardView
        android:id="@+id/card"
        android:layout_width="match_parent"
        android:layout_height="64dp"
        android:layout_margin="16dp"
        android:clickable="true"/>
</LinearLayout>
```

### Activity

```kotlin
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        findViewById<Button>(R.id.button).setOnClickListener {
            it.isClickable = false
        }
        findViewById<MaterialCardView>(R.id.card).setOnClickListener {
            it.isClickable = false
        }
    }
}
```

**Android API version:** 29

**Material Library version:** 1.2.0 and 1.3.0-alpha02

**Device:** API 29 Emulator

**Comment by ymarian** [comment]
Hi, you can use `it.isEnabled = false` instead
