### ISSUE TITLE
[AppBarLayout] Setting background colour

### ISSUE THREAD

**Issue by MuntashirAkon** [material-components/material-components-android#1597]
**Description:** It seems background colour in AppBarLayout is not working as expected in night mode (at least not according to the documentation): There is a slight tint added to the background colour. This behaviour is not visible if only Toolbar or CollapsingToolbarLayout is used. Since AppBarLayout is a linear layout, adding another `invisible` component can verify the issue. For instance, I've added a ProgressIndicator inside the AppBarLayout. The screenshot below was taken after the component was hidden (ie. invisible).

![Screenshot_App_Manager_0](https://user-images.githubusercontent.com/8176128/89717759-511ad680-d9db-11ea-8772-4f1be5d95148.png)

**Expected behaviour:** The background colour of the invisible component should be the same as colorPrimary (with `Widget.MaterialComponents.AppBarLayout.Primary`) or colorSurface (with `Widget.MaterialComponents.AppBarLayout.Surface`) as displayed in the screenshot below.

![Screenshot_App_Manager_1](https://user-images.githubusercontent.com/8176128/89717775-727bc280-d9db-11ea-8e20-bd1839b5063a.png)

**Workaround:** Disabling background tint solves the issue. An example is given below:

```xml
    <style name="AppTheme.AppBarLayout" parent="Widget.MaterialComponents.AppBarLayout.Primary">
        <item name="android:backgroundTintMode">add</item>
        <item name="android:backgroundTint">#000</item>
    </style>
```

**Android API version:** 29

**Material Library version:** 1.3.0-alpha02

**Comment by gabrielemariotti** [comment]
It happens because the `Toolbar` and the `AppBarLayout` have different elevation.
In dark mode there is a different elevation overlay which is displayed as in your first screen.

Try to apply the same elevation:

```
    <com.google.android.material.appbar.AppBarLayout
        app:elevation="@dimen/design_appbar_elevation"   //4dp used by default in the Toolbar
```

With same elevation:

<img width="322" alt="Schermata 2020-08-09 alle 00 27 35" src="https://user-images.githubusercontent.com/2583078/89720875-3f373480-d9d7-11ea-9211-c945e8700437.png">

Without:

<img width="321" alt="Schermata 2020-08-09 alle 00 27 51" src="https://user-images.githubusercontent.com/2583078/89720876-43fbe880-d9d7-11ea-8463-3b17e111f75f.png">

**Comment by MuntashirAkon** [comment]
@gabrielemariotti I haven't noticed it earlier: Setting elevation removes the shadow below the AppBarLayout in light mode. Therefore, my workaround works better.

**Comment by drchen** [comment]
I think as @gabrielemariotti said this is kind of WAI. Since we are trying to get rid of shadows with Material 3, I'll close the issue for now. Let me know if you have more thoughts on this.

**Comment by MuntashirAkon** [comment]
@drchen: I've already upgraded to M3 and it looks more consistent than MD2. So, I am satisfied with the new design. Thanks!
