### ISSUE TITLE
Update the namespace for BottomNavigationView documentation

### ISSUE THREAD

**Issue by yprabhu** [material-components/material-components-android#16]
### Reproduction steps
Using `xmlns:design="http://schema.android.com/apk/res/android.support.design"` and `design:menu` as mentioned in the documentation of [BottomNavigationView](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html) over `xmlns:app="http://schemas.android.com/apk/res-auto"` and `app:menu` does not show the bottom nav view. The documentation can be misleading. 

```
 <android.support.design.widget.BottomNavigationView
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:design="http://schema.android.com/apk/res/android.support.design"
     android:id="@+id/navigation"
     android:layout_width="match_parent"
     android:layout_height="56dp"
     android:layout_gravity="start"
     design:menu="@menu/my_navigation_items" />
``` 
![image](https://cloud.githubusercontent.com/assets/2046641/21436141/086b7b2e-c84b-11e6-865a-c5b008ce8a4c.png)

The documentation should show this instead

```
 <android.support.design.widget.BottomNavigationView
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     android:id="@+id/navigation"
     android:layout_width="match_parent"
     android:layout_height="56dp"
     android:layout_gravity="start"
     app:menu="@menu/bottom_navigation_menu" />
```

### Version number
 - Found in latest documentation of  [BottomNavigationView](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html)

**Comment by tec27** [comment]
Fixed with b66b8c778539938ace0b44c8ad1775844a26bec7.
