### ISSUE TITLE
google play service conflict 

### ISSUE THREAD

**Issue by mohammad-rababah** [material-components/material-components-android#160]
Hi 
I try to use this Library along with google play services it keeps conflict how can I  use both?
is there specific version I can use to remove it.

note I use google maps and places in my project 

thanks in advance

**Comment by dsn5ft** [comment]
Can you check if this is the same issue as #103?

**Comment by dsn5ft** [comment]
Have you tried running with the latest [Preview build of Android Studio](https://developer.android.com/studio/preview)?

**Comment by mohammad-rababah** [comment]
I fixed by add 
`   <android.support.design.widget.TextInputLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                    android:textColorHint="@color/light_white">`

I remove the library in the end because I only need it for this style thank you for helping and for your time 
I will use this again when everything is stable and running well
