### ISSUE TITLE
[Exposed Dropdown Menu] Scroll always to top instead of selected item

### ISSUE THREAD

**Issue by EliuTimana** [material-components/material-components-android#1600]
**Description:** I've implemented an exposed dropdown menu following the material docs [material.io](https://material.io/develop/android/components/text-fields) and [this](https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md#exposed-dropdown-menus) everything is working fine, but every time I want to select another item that is at the end of the list I have to scroll down, again and again, that's not the normal behavior of the **Spinner** widget, ¿is that possible?

**Expected behavior:** Vertical scroll should be set to the selected item, this can improve accessibility when the list contains a lot of elements.
![img](https://i.imgur.com/G05F909.gif)
**Source code:** 
```xml
...
<LinearLayout
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   android:layout_marginStart="16dp"
   android:layout_marginTop="8dp"
   android:layout_marginEnd="16dp"
   android:orientation="vertical"
   tools:context=".ui.filter.FilterFragment">
   <com.google.android.material.textfield.TextInputLayout
      android:id="@+id/dropdown_department"
      style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox.ExposedDropdownMenu"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:hint="@string/department"
      app:data="@{viewModel.departments}">
      <AutoCompleteTextView
         android:layout_width="match_parent"
         android:layout_height="wrap_content"
         android:inputType="none"
         android:overScrollMode="always" />
   </com.google.android.material.textfield.TextInputLayout>
   <Spinner
      android:id="@+id/spinner_province"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_marginTop="8dp"
      app:data="@{viewModel.departments}"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      app:layout_constraintTop_toBottomOf="@+id/textViewProvince" />
</LinearLayout>
...
```

```kt
val adapterProv = SpinnerUbigeoAdapter(requireContext(), OnItemSelected {
    viewModel.onSelectProvincia(it)
})
(binding.dropdownProvince.editText as? AutoCompleteTextView)?.setAdapter(adapterProv)
binding.spinnerProvince.adapter = adapterDep
```

**Android API version:** 29

**Material Library version:** 1.2.0

**Device:** Emulator or real device

**Comment by cappee** [comment]
How did you solve?

**Comment by cappee** [comment]
@EliuTimana how did you solve?

**Comment by EliuTimana** [comment]
> @EliuTimana how did you solve?

I was no able to solve this, I am using the classic spinner instead.

**Comment by brunopiovan** [comment]
I solved this by adding setOnClickListener on the AutoCompleteTextView and then setting listSelection to the index of the item.
ex:
```
autoCompleteTextView.setOnClickListener {
    autoCompleteTextView.listSelection = viewModel.selectedVoiceIndex
}
```
