### ISSUE TITLE
[Theme] colorAccent not working anymore

### ISSUE THREAD

**Issue by extreamsd** [material-components/material-components-android#1604]
**Description:** Since com.google.android.material:material:1.2.0, the colorAccent attribute in the AppTheme style does not work anymore:

<style name="AppTheme" parent="Theme.MaterialComponents.NoActionBar">
        <item name="colorAccent">@color/orange_selected</item>
        <item name="android:colorEdgeEffect">@color/orange_selected</item>
    </style>

With:
<color name="orange_selected">#EAB254</color>

Gives a purple color on buttons in AlertDialog's.
This was not the case for com.google.android.material:material:1.1.0 and hasn't been fixed in 1.3.0-alpha02.
The orange color is still used on checkboxes, sliders, etc.

**Expected behavior:** Buttons should be in orange as styled.

**Android API version:** Several, but at least Android 9

**Material Library version:** 1.2.0

**Device:** Samsung Tab S3 (but present on more)
![AreYouSure](https://user-images.githubusercontent.com/19303781/89792259-9696eb00-db24-11ea-8c4c-28e892dcc484.png)

**Comment by wcshi** [comment]
@extreamsd your code snippet is malformed, could you please share a small sample app? thanks!

**Comment by MuntashirAkon** [comment]
Newer versions of Material Components use `colorPrimary` instead of `colorAccent` for buttons. You can test it by changing the primary colours or using custom dialog style like this:

```xml
<style name="AppTheme" parent="Theme.MaterialComponents.NoActionBar">
    ...
    <item name="materialAlertDialogTheme">@style/AppTheme.AlertDialog</item>
</style>

<style name="AppTheme.AlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
    <item name="colorPrimary">@color/orange_selected </item>
</style>
```

**Comment by extreamsd** [comment]
That works, thanks!

**Comment by extreamsd** [comment]
Actually, not completely. I add the colorPrimary to my AppTheme and that works for my main activity, including a RadioGroup. However, in the PreferenceActivity, which is also styled with the same AppTheme, the button is orange, but the radio grop is default blue-ish. See screenshot.
![settings](https://user-images.githubusercontent.com/19303781/89889159-7ec97080-dbd1-11ea-99ce-79901fde30ac.png)

**Comment by wcshi** [comment]
The Material lib has its own version of Radio buttons (MaterialRadioButtons) that understands colorPrimary, unclear if the PreferenceActivity uses it.

I think this may be a bug or intentional behavior in PreferenceActivity which is owned by another team and has been deprecated since api 29 in favor of androidx.Preference. Please file here: https://b.corp.google.com/issues?q=componentid:460913%20status:open

**Comment by extreamsd** [comment]
Thank link points to some MOMA site which seems internal to Google

**Comment by MuntashirAkon** [comment]
> However, in the PreferenceActivity, which is also styled with the same AppTheme, the button is orange, but the radio group is default blue-ish.

You should migrate to AndroidX to prevent this behaviour. PreferenceActivity is deprecated anyway.

**Comment by extreamsd** [comment]
I remember that causing other issues for me in the past, but I'll try, thanks.

**Comment by MuntashirAkon** [comment]
> I remember that causing other issues for me in the past, but I'll try, thanks.

Preference implementation in AndroidX is a bit different than the original one. There's no PreferenceActivity in AndroidX, unfortunately and the migration is a bit difficult for that reason. That's being said, if you're using different fragments in your activity that holds the preference fragments, you may face some issues.

**Comment by wcshi** [comment]
@extreamsd sorry I updated the link
