### ISSUE TITLE
[MaterialCardView] Setting shapeAppearanceModel overrides default behavior

### ISSUE THREAD

**Issue by skovacevic96** [material-components/material-components-android#1606]
**Description:** I have material card view that has all four edges rounded. What I want is to change this on click so I can expand other view below it. By removing rounding of two bottom edges child views start overlapping card view. Is there any way to solve this?

**Expected behavior:** Ideally, child views should still fit material card view.

**Source code:** 
```
holder.view.questionCardView.shapeAppearanceModel = 
                holder.view.questionCardView.shapeAppearanceModel
                .toBuilder()
                .setAllCorners(CornerFamily.ROUNDED, radius)
                .setBottomRightCornerSize(floatingZero)
                .setBottomLeftCornerSize(floatingZero)
                .build()
```

Layout:

<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

        <variable
            name="faq"
            type="me.gov.mrt.objects.faq.Faq" />
    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/background">

        <com.google.android.material.card.MaterialCardView
            android:id="@+id/questionCardView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:backgroundTint="@color/winter"
            android:theme="@style/Theme.MaterialComponents"
            app:shapeAppearanceOverlay="@style/QuestionAppearanceOverlay"
            app:cardPreventCornerOverlap="false"
            app:cardElevation="0dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_goneMarginTop="0dp">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/questionCardViewHolder"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent">

                <View
                    android:id="@+id/faqLineView"
                    android:layout_width="4dp"
                    android:layout_height="0dp"
                    android:background="@color/quill"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

                <TextView
                    android:id="@+id/faqQuestion"
                    style="@style/HeadingOpenSansBold16ThunderStroke"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="16dp"
                    android:layout_marginTop="14dp"
                    android:layout_marginEnd="16dp"
                    android:layout_marginBottom="14dp"
                    android:text="@{faq.translation.title}"
                    android:textColor="@color/thunderStroke"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toEndOf="@+id/faqLineView"
                    app:layout_constraintTop_toTopOf="parent"
                    tools:text="Why do I need to submit my information" />
            </androidx.constraintlayout.widget.ConstraintLayout>
        </com.google.android.material.card.MaterialCardView>

        <net.cachapa.expandablelayout.ExpandableLayout
            android:id="@+id/expandable_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:el_duration="1000"
            app:el_expanded="true"
            app:el_parallax="0.5"
            app:layout_constraintEnd_toEndOf="@+id/questionCardView"
            app:layout_constraintStart_toStartOf="@id/questionCardView"
            app:layout_constraintTop_toBottomOf="@+id/questionCardView">

            <com.google.android.material.card.MaterialCardView
                android:id="@+id/answerCardView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:backgroundTint="@color/winter"
                app:cardElevation="0dp"
                app:shapeAppearanceOverlay="@style/AnswerAppearanceOverlay"
                android:theme="@style/Theme.MaterialComponents"
                app:cardPreventCornerOverlap="false"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                >

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    >

                    <View
                        android:id="@+id/faqAnswerLineView"
                        android:layout_width="4dp"
                        android:layout_height="0dp"
                        android:background="@color/quill"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent" />

                    <TextView
                        android:id="@+id/faqAnswer"
                        style="@style/HeadingOpenSansLight14ThunderStroke"
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="16dp"
                        android:layout_marginEnd="16dp"
                        android:layout_marginBottom="14dp"
                        android:text="@{faq.translation.description}"
                        android:textColor="@color/thunderStroke"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toEndOf="@+id/faqAnswerLineView"
                        app:layout_constraintTop_toTopOf="parent"
                        tools:text="We need your information, in order to generate a unique QR code for you, which is required to authorise your stay. You will need to show this code at border control, both when entering, and leaving the country." />

                </androidx.constraintlayout.widget.ConstraintLayout>
            </com.google.android.material.card.MaterialCardView>

        </net.cachapa.expandablelayout.ExpandableLayout>

        <Space
            android:layout_width="match_parent"
            android:layout_height="16dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/expandable_layout" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>

**Android API version:** Android API version here

**Material Library version:** 1.2.0

**Device:** Happens on all devices

Images:

[https://ibb.co/5xLdY2W](url)
[https://ibb.co/cxT8pC3](url)

**Comment by ymarian** [comment]
you can set 
```
app:cardPreventCornerOverlap="false"
app:cardUseCompatPadding="false"
```

And set your own padding. Make sure to test before lollipop if you support that you might need different paddings.
