### ISSUE TITLE
How to set chip selected color? (single selection)

### ISSUE THREAD

**Issue by jeffreyliu8** [material-components/material-components-android#161]
How to set chip selected color? (single selection)

On https://material.io/develop/android/components/chip/, there is only app:chipBackgroundColor, which is when is the color even when it is not selected.

https://stackoverflow.com/questions/51089150/set-com-google-android-material-chip-chip-selected-color

**Comment by Dizarray** [comment]
I answered on StackOverflow, but I will repeat it here just in case.

Set an attribute `app:chipBackgroundColor` and pass a color state list to it:
```xml
<android.support.design.chip.Chip
    android:id="@+id/test"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:checkable="true"
    android:clickable="true"
    android:focusable="true"
    app:chipBackgroundColor="@color/bg_chip_state_list"
    app:chipText="Test" />
```
bg_chip_state_list looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/colorSecondaryLight" android:state_checked="true" />
    <item android:color="@color/colorPrimaryDark" />
</selector>
```
However I also had to set `android:clickable` to `true` to make this work

**Comment by jeffreyliu8** [comment]
Cool, it's working. Thanks. 
https://developer.android.com/guide/topics/resources/color-list-resource

**Comment by jeffreyliu8** [comment]
Now almost the same question, how to do the same with text color?

**Comment by lidkxx** [comment]
also, regarding the original question, I also had to set `android:checkable="true"` to make the color state list work.

**Comment by pranjal012** [comment]
where do i make the file bg color state list file?

**Comment by lebeshev** [comment]
@pranjal012 You can check the official docs about color state list resources: https://developer.android.com/guide/topics/resources/color-list-resource

**Comment by theamanthakur** [comment]
> where do i make the file bg color state list file?

You need to create that in drawable folder in res (Android Studio).

**Comment by mohitkumarsoni** [comment]
> I answered on StackOverflow, but I will repeat it here just in case.
> 
> Set an attribute `app:chipBackgroundColor` and pass a color state list to it:
> 
> ```
> <android.support.design.chip.Chip
>     android:id="@+id/test"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:checkable="true"
>     android:clickable="true"
>     android:focusable="true"
>     app:chipBackgroundColor="@color/bg_chip_state_list"
>     app:chipText="Test" />
> ```
> 
> bg_chip_state_list looks like this:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <selector xmlns:android="http://schemas.android.com/apk/res/android">
>     <item android:color="@color/colorSecondaryLight" android:state_checked="true" />
>     <item android:color="@color/colorPrimaryDark" />
> </selector>
> ```
> 
> However I also had to set `android:clickable` to `true` to make this work

the <selector> will be added on R.drawable, but while setting on background it only accepts from @color . i am frustrated now

**Comment by webprog26** [comment]
What you actually have to do is

1. Create color resources directory
2. Inside the color directory create a file "chip_color.xml"

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/black" android:state_checked="false" />
    <item android:color="#173E92" android:state_checked="true"/>
</selector> 
```

3. In your themes.xml file add a custom style

```
<style name="CustomChipStyle" parent="Widget.MaterialComponents.Chip.Choice">
        <item name="chipBackgroundColor">@color/alarm_day_selected_bg</item>
</style>
```

Use Widget.MaterialComponents.Chip.Choice or Widget.MaterialComponents.Chip.Filter depending on your needs

4. Reference this custom style in your layout file

```
 <com.google.android.material.chip.Chip
     style/CustomChipStyle"
     layout_width="wrap_content"
     layout_height="wrap_content" />
```
