### ISSUE TITLE
[Progress Indicator] Allow sizes different from 48x48

### ISSUE THREAD

**Issue by Sottti** [material-components/material-components-android#1615]
**Is your feature request related to a problem? Please describe.**
At the moment we do have 3 different sizes for the circular progress bar, 2 of them different from 48x48. I'd like to be able to do the same with the circular progress indicator.

**Describe the solution you'd like**
Allow sizes different from 48x48

**Describe alternatives you've considered**
Im using the old ProgressBar at the moment.

**Comment by wcshi** [comment]
Have you tried changing the size following the documentation?

The size of circular types can be set with a combination of `indicatorSize`,
`circularRadius`, and `circularInset`. `indicatorSize` defines the width of the
ring (circular spinner). `circularRadius` defines the radius of the central line
of the ring. `circularInset` gives extra space between the outer boundary to the
bounds of the component.

Note: If half of the `indicatorSize` is greater than the `circularRadius`,
`IllegalArgumentException` will be thrown during initialization.

https://github.com/material-components/material-components-android/blob/master/docs/components/ProgressIndicator.md#size

**Comment by Sottti** [comment]
Sorry my fault, autocomplete wasn't helping me for some reason and I didn't check that documentation page. Works fine now just with `circularRadius`. Thanks!
