### ISSUE TITLE
AlertDialog has filled buttons when using "Theme.MaterialComponents.Light.NoActionBar" theme

### ISSUE THREAD

**Issue by WebTiger89** [material-components/material-components-android#162]
Hi,
I just noticed that AlertDialog has filled buttons with the "Theme.MaterialComponents.Light.NoActionBar" theme. When I use the default "Theme.AppCompat.Light.NoActionBar" theme, AlertDialog has simple text buttons as expected.

Default constructor of AlertDialog says:
> The default alert dialog theme is defined by R.attr.alertDialogTheme within the parent context's theme.

[https://developer.android.com/reference/android/app/AlertDialog.Builder#AlertDialog.Builder(android.content.Context)](url)

Does someone know why the MaterialComponents theme gives me filled buttons in AlertDialog?

**Comment by WebTiger89** [comment]
ok interesting...when I use the "android.support.v7.app.AlertDialog" import, its working as expected

**Comment by BjarnBronsveld** [comment]
Would like to re-open this issue as it still exists and I do not believe that @WebTiger89 his solution is the right one.

Sounds like a bug to me?

**Comment by gholz** [comment]
I'm having the same problem and unfortunately I can't change the imports from third party libraries

**Comment by mathieubugaud** [comment]
I'm having the problem too, it sounds like a bug to me. 
Thanks for your solution but can you re-open this issue please since your solution is not a suitable fix ?

**Comment by dsn5ft** [comment]
Created https://issuetracker.google.com/issues/116861837 to track this.

**Comment by gsajith** [comment]
Hi!

Our recommendation here is that you use android.support.v7.app.AlertDialog whenever possible. An app using an AppCompat theme should be using the AppCompat AlertDialog, as the framework AlertDialog has undefined behavior across several API versions re: custom view inflation.

**Comment by Sloy** [comment]
That's a good recomendation @gsajith, but as @gholz says there are third party libraries that use the system AlertDialog. Maybe the custom inflater could skip it? At least the UI would not break.

**Comment by syrop** [comment]
You should use androidx.appcompat.app.AlertDialog

**Comment by KeyStarr** [comment]
Consider DatePickerDialog (not third party lib!) - it uses android.app.AlertDialog. And there's no alternative for it from androidx. 

It is a real issue and there is no clean solution to it. Currently the only workaround (extracted from the issue-link above) is to add a line below to a style you pass to AlertDialog (or any kind of dialog) on constructing it:

`<item name="materialButtonStyle">@style/Widget.MaterialComponents.Button.TextButton</item>`

**Comment by nestoleh** [comment]
Does anyone know how to fix this bug for DatePickerDialog on API 19? The @KeyStarr solution works only for API 21+. On API 19 button still with background:
![screenshot](https://user-images.githubusercontent.com/10635470/69045311-4a88a100-09ff-11ea-855a-49fe88840c03.png)

**Comment by CoolMind** [comment]
@nestoleh, why don't you use `MaterialDatePicker.Builder.datePicker`? On API 19 it looks like on 29:
![изображение](https://user-images.githubusercontent.com/10630436/82060231-c4a89280-96cf-11ea-8bf7-b51f98844bf0.png)
