### ISSUE TITLE
[MaterialCardView] CardBackgroundColor - val cannot be reassigned

### ISSUE THREAD

**Issue by stevdza-san** [material-components/material-components-android#1621]
When I try to change cardBackgroundColor programmatically (cardView.cardBackgroundColor), I get warning from Android studio telling me that 'val cannot be reassigned'. Is this some kind of bug?

```
<com.google.android.material.card.MaterialCardView
        android:id="@+id/cardView"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:cardBackgroundColor="@color/white"
        app:cardCornerRadius="20dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.5"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:strokeColor="@color/white"
        app:strokeWidth="1dp">
```

**Android API version:** 30

**Material Library version:** material:1.3.0-alpha02

**Device:** Pixel 3a API 29

**Comment by gabrielemariotti** [comment]
It happens because in the `MaterialCardView`:

```
public void setCardBackgroundColor(@Nullable ColorStateList color)
@NonNull public ColorStateList getCardBackgroundColor()
```

It means that the setter method accepts a `ColorStateList?` while the getter returns a `ColorStateList`.
Since they don't match you have to use the setter directly:

`card.setCardBackgroundColor(...)`

**Comment by stevdza-san** [comment]
@gabrielemariotti Oh thank you Gabriel! I'm closing this issue now.
