### ISSUE TITLE
[TextInputLayout] Bottom line no longer respects error color

### ISSUE THREAD

**Issue by dbrant** [material-components/material-components-android#1626]
**Description:** As of version `1.2.0` the TextInputLayout does not update the color of the bottom line under the text, when setting `setErrorTextColor()` dynamically. (version `1.1.0` was doing this properly)

Also, the color of the floating hint text isn't getting updated when `setErrorTextColor()` is called, but instead gets updated only on the next keystroke.

**Android API version:** API 29

**Material Library version:** 1.2.0

**Comment by gabrielemariotti** [comment]
About the color.
The version 1.2.0 introduced the `boxStrokeErrorColor ` attribute.
You can use:

`textInputLayout.boxStrokeErrorColor = `

**Comment by leticiarossi** [comment]
Using `boxStrokeErrorColor` should work to change the underline color as said above. When testing `setErrorTextColor()` it works as expected on my side, can you provide your source code or a sample app with your issue?

**Comment by upseliseev** [comment]
Just in case anyone else comes here in confusion or in case @dbrant didn't resolve their issue: 
make sure that your EditText doesn't have a background. Removing that resolved this issue for me

**Comment by dbrant** [comment]
sorry, this one slipped through my radar -- it's been resolved.
