### ISSUE TITLE
liftOnScroll not working with ViewPager?

### ISSUE THREAD

**Issue by EvoWizz** [material-components/material-components-android#163]
### Overview
When I set `app:liftOnScroll="true"` to my AppBarLayout, and then launch the app, I don't see any shadow, and scrolling down or up doesn't work.

My Layout:
```<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:id="@+id/coordinatorLayoutRoot"
  android:layout_width="match_parent"
  android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
      android:id="@+id/appbar"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      app:liftOnScroll="true">

        <androidx.appcompat.widget.Toolbar
          android:id="@+id/toolbar"
          android:layout_width="match_parent"
          android:layout_height="?android:attr/actionBarSize"
          android:theme="?android:toolbarStyle"
          app:layout_scrollFlags="scroll|enterAlways"
          app:title="@string/app_name"
          app:titleTextAppearance="@style/ToolbarTitleAppearance"/>

        <com.google.android.material.tabs.TabLayout
          android:id="@+id/tabs"
          style="@style/TabLayout.Style"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"/>

    </com.google.android.material.appbar.AppBarLayout>

    <androidx.viewpager.widget.ViewPager
      android:id="@+id/viewPager"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:overScrollMode="always"
      app:layout_behavior="@string/appbar_scrolling_view_behavior"/>
    
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

### Version number

 `com.google.android.material:material:1.0.0-beta01`

### Operating system and device

 - OnePlus 6 with Android 8.1
 - Emulator (Pixel 2 XL) Android P (latest DP)

### Related issues

Someone already posted a similar issue (#140 ) but his issue was fixed by removing the bottom margin of his NestedScrollView. However I'm using a ViewPager, and I don't have any bottom margin in my layout.

**Comment by cketcham** [comment]
Moved this over to buganizer: https://issuetracker.google.com/issues/111634113

**Comment by EvoWizz** [comment]
Thank you! 👍

**Comment by jaysowen** [comment]
Same iusse.How to fix this?

**Comment by dsn5ft** [comment]
Currently `liftOnScroll` expects the scrolling view to be a direct child of the `CoordinatorLayout`. The workaround is to not set `app:liftOnScroll` on your `AppBarLayout` and instead to call `setLiftable(true)` and `setLifted()` based on when your scrolling view is scrolled. Here is an example using a `ListView`:

```
appBarLayout.setLiftable(true);
listView.setOnScrollListener(
    new OnScrollListener() {
      @Override
      public void onScrollStateChanged(AbsListView view, int scrollState) {}

      @Override
      public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount) {
        boolean isAtTop = firstVisibleItem == 0 && (view.getChildCount() == 0 || view.getChildAt(0).getTop() == 0);
        appBarLayout.setLifted(!isAtTop);
      }
    });
```

**Comment by Ioane5** [comment]
It is strange that `AppBarLayout` collapse/expand works with `ViewPager`, but this requires _hack_.

**Comment by seth-gravy** [comment]
You can now set `liftOnScrollTargetViewId` on your `AppBarLayout` to point to your `ViewPager` directly. Or in my case, a `RecyclerView` inside of the `ViewPager` (but make sure each `RecyclerView` has a unique id and you update `liftOnScrollTargetViewId` in the `ViewPager`'s `onTabSelected`).

**Comment by abunayem** [comment]
How to enable liftOnScroll in a fragment?

**Comment by khaykov** [comment]
If by any chance you have multiple fragments with the same layout in ViewPager, having unique IDs for scroll containers and communicating them to AppBar is a whole new can of headache.

While changing ID of view after getting an initial reference to them (using `findViewById` or with KTX view binding) works, I can't help but feel like it's going to come and bite me later, or not me, but another unsuspecting developer who will try to get the view using its original ID for whatever reason.

The safest way to do it, that I'm aware of, is by having an ID for each fragment in ViewPager stored in ids.xml. This adds a lot of manual labor, especially if you have a good number of ViewPager (also, it will not work with dynamically added fragments, if that's your things).

Anything else I'm missing?

**Comment by OxygenCobalt** [comment]
Sorry for reviving this thread, but does anyone know how to get this working with a `TabLayout` within an `AppBarLayout` that collapses on scroll? I'm doing what seth-gravy said, and it works in all cases EXCEPT when switching tabs using a `TabLayout`
when the `AppBarLayout` is collapsed. I have no idea what's going on and it's really annoying.
