### ISSUE TITLE
[Chip] OnClickListener

### ISSUE THREAD

**Issue by yoobi** [material-components/material-components-android#1630]
**Is your feature request related to a problem? Please describe.**
I'm using `closeIcon` attribute to style my chip but I want it to have the same behavior in the event of a click that the actual chip. Now I've got to create 2 onClickListener that do exactly the same thing, which means copy/paste same code

```kotlin
chip1.setOnClickListener {
    Toast.makeText(context, "This is chip1", Toast.LENGTH_SHORT).show()
} 
chip1.setOnCloseIconClickListener {
    Toast.makeText(context, "This is chip1", Toast.LENGTH_SHORT).show()
}

chip2.setOnClickListener {
    Toast.makeText(context, "This is chip2", Toast.LENGTH_SHORT).show()
} 
chip2.setOnCloseIconClickListener {
    Toast.makeText(context, "This is chip2 closeIcon", Toast.LENGTH_SHORT).show()
}
```

**Describe the solution you'd like**
If a `closeIcon` is used and `closeIconVisible == true` and if there is no `setOnCloseIconClickListener` set then the the `closeIcon` click should be the same as `setOnClickListener`

```kotlin
// Will be working for both closeIcon and view click
chip1.setOnClickListener {
    Toast.makeText(context, "This is chip1", Toast.LENGTH_SHORT).show()
} 

chip2.setOnClickListener {
    Toast.makeText(context, "This is chip2", Toast.LENGTH_SHORT).show()
}
chip2.setOnCloseIconClickListener {
    Toast.makeText(context, "This is chip2 closeIcon", Toast.LENGTH_SHORT).show()
}
```
We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by wcshi** [comment]
Have you considered creating an OnClickListener and storing it in a variable so that it can be passed to both click listeners?

**Comment by yoobi** [comment]
Well yeah, but I've a couple of chip (around 10) so creating as many variable isn't a solution either

**Comment by ymarian** [comment]
you can easily create an extension:

```
fun Chip.setOnClickListenerAll(l: View.OnClickListener) {
  setOnClickListener(l)
  setOnCloseIconClickListener(l)
}
```
