### ISSUE TITLE
[TextInputLayout]: Android Talkback incorrect announcement on TextInputLayout

### ISSUE THREAD

**Issue by sanginovs** [material-components/material-components-android#1631]
**Description:**
Talkback announces password twice if we set android:hint inside TextInputLayout to "password".
```
<com.google.android.material.textfield.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="Password"
        app:passwordToggleEnabled="true">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/tiePassword"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textPassword"
            android:selectAllOnFocus="true"
            android:singleLine="true" />

    </com.google.android.material.textfield.TextInputLayout>
```

**Expected behavior:** Screenshots and/or description of expected behavior
While navigating to TextInputLayout TalkBack announces : "password password edit box"

Desired announcement: "password edit box"

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Android API version here

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
latest

**Device:** Device on which the bug was encountered here

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by gabrielemariotti** [comment]
Checking the [code](https://github.com/material-components/material-components-android/blob/1.2.0/lib/java/com/google/android/material/textfield/TextInputLayout.java#L4050) TalkBack announces :  
TextInputEditText inputType keyword: [`password`]  + TextInputLayout hint : [`password`] + [`editbox`].

I don't think that removing the textInputLayout hint can be a general use case.
In any case you can extend the `TextInputLayout.AccessibilityDelegate` or create a custom class and assign to the `TextInputLayout` using:

[`textInputLayout.setTextInputAccessibilityDelegate`](https://github.com/material-components/material-components-android/blob/1.2.0/lib/java/com/google/android/material/textfield/TextInputLayout.java#L3501)

**Comment by sanginovs** [comment]
@gabrielemariotti thanks for your answer. will do so
