### ISSUE TITLE
[ProgressIndicator] add Listener to handle Progress Drawable visibility Change

### ISSUE THREAD

**Issue by Sanlorng** [material-components/material-components-android#1632]
**Description** : I use WebView to load Urls and use ProgressIndicator to show Loading Progress and when progress is 100 ProgressIndicator will call hide() method， but it only animated hide ProgressIndicator，ProgressIndicator still visible

**Expect Behavior** : After ProgressDrawable Hide or Before ProgressDrawable show，ProgressIndicator can call a Listener which I can in preShow and afterHide method to change ProgressIndicator visibility

**Library Version** :1.3.0-alpha02

**Comment by pekingme** [comment]
Hi @Sanlorng,
Thanks for your feedback. It sounds more like a misuse/bug. I can verify on catalog with 1.3.0-alpha02 that after the "hide" animation is done, the component visibility is INVISIBLE. Could you confirm if this is when, in your case, the component visibility is still VISIBLE? If yes, could you provide a simple project to reproduce it?

**Comment by Sanlorng** [comment]
@pekingme Sorry, there is something wrong with my description. The default behavior of ProgressIndicator is set to invisibity, but I need to set it to gone, because setting it to invisibity will leave a height of 4dp.

**Comment by pekingme** [comment]
I see, that makes sense. Thanks for clarifying. We can add an option to define the end visibility at the end of "hide" animation.

**Comment by Sanlorng** [comment]
@pekingme Thanks
