### ISSUE TITLE
[MaterialContainerTransform] Manually specifying sharedElementReturnTransition causes flickering

### ISSUE THREAD

**Issue by JHeikes** [material-components/material-components-android#1633]
I have a Fragment from which I am launching an activity with a `MaterialContainerTransform` transition. When navigating to this activity, the Transition works as expected. Upon returning to the fragment and having the Transition play out in reverse, I ran into the same bug as described below, where the background during the return transition was that of the activity instead of the fragment:

https://github.com/material-components/material-components-android/issues/1601

I applied the workaround described in the same issue and the background is now that of the fragment. Only one issue remains however: After the return Transition has triggered and is at the point where the bounds match that of the origin `RecyclerView` item, the view visibly flickers before dissappearing.

![flicker](https://user-images.githubusercontent.com/47241933/90597318-1f7ee800-e1f1-11ea-9ee6-dc1f317f77b7.gif)

This is how I'm setting the enter and return Transitions:
```
        val materialTransform = MaterialContainerTransform().apply {
            addTarget(android.R.id.content)
            duration = 450
            pathMotion = MaterialArcMotion()
        }

        val returnTransformation = MaterialContainerTransform().apply {
            addTarget(android.R.id.content)
            fadeMode = MaterialContainerTransform.FADE_MODE_CROSS
            duration = 450
        }

        window.sharedElementReturnTransition = returnTransformation
        window.sharedElementEnterTransition = materialTransform
```

**Expected behavior**: When the return Transition is about to finish, I expect it to seamlessly disappear without flickering.

**Android API version**: API 29

**Device**: Oneplus 6T

**Material Library version**: com.google.android.material:material:1.3.0-alpha02

**Comment by hunterstich** [comment]
Hey @JHeikes 

Any chance you'd be able to share a sample that reproduces this so I can look into it?

Off the top of my head, the only thing I can think of to try is using `setHoldAtEndEnabled` on your return `MaterialContainerTransform` and see if that solves your issue.

Let me know if that helps.

**Comment by dsn5ft** [comment]
One more thought/question here. @JHeikes are you using `MaterialContainerTransformSharedElementCallback` at all for the Activity transition? Our callback class should do `setHoldAtEndEnabled(true)` for you, as well as a couple other things that could help with reducing flickers.

**Comment by JHeikes** [comment]
@hunterstich Wow, `setHoldAtEndEnabled` did indeed fix the flicker! I didn't think it would be so easy!
I've another (albeit somewhat unrelated) question whilst I'm here: I've been toying with the idea of turning my detail activity into a fragment. From all that I've seen of fragment transitions is that you need to have the detail fragment be in the same container as the previous one, in order for transitions to work. Do you happen to know if there is a way to work around that limitation?

**Comment by hunterstich** [comment]
@JHeikes Glad that worked! 

**Re: Migrating to a Fragment in a separate container**
There should be a way to get this working. If the standard method of using transition names and a `sharedElementEnterTransition` doesn't work, you can look into configuring a `MaterialContainerTransform` in your detail's fragment that manually finds and sets your start/end views.  We do this in Reply, a Material sample app, when [showing a fragment above MainActivity's primary fragment container](https://github.com/material-components/material-components-android-examples/blob/develop/Reply/app/src/main/java/com/materialstudies/reply/ui/compose/ComposeFragment.kt#L95-L105). Basically, as long as you can manually set your start and end views on `MaterialContainerTransform`, you should be able to get it working. The hard part in your case might be finding the correct list item view in your list fragment (from your details fragment) to set as your `MaterialContainerTransform`'s `startView`. 

Let me know how it goes if you give it a try and I can try to help debug if you run into issues!

**Comment by dsn5ft** [comment]
Awesome! Are you also setting a `MaterialContainerTransformSharedElementCallback` as the `ExitSharedElementCallback` on your first Activity? (the parent Activity that contains the list of cards)

Here are our [docs](https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md#transition-between-activities) that explain the full Activity setup.

And here's our demo code:
- [TransitionContainerTransformStartDemoActivity.java](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/transition/TransitionContainerTransformStartDemoActivity.java)
- [TransitionContainerTransformEndDemoActivity.java](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/transition/TransitionContainerTransformEndDemoActivity.java)
