### ISSUE TITLE
How to create Light and Dark Theme?

### ISSUE THREAD

**Issue by akinfopark** [material-components/material-components-android#1646]
How to create theme with white and black toolbar and status bar (for night mode) as in these & use a specified color for buttons, focused edit texts, etc 
https://lh3.googleusercontent.com/on0sK8ZWF7sQcRzsT4x5nq9Hq1M6NPhHSbxwrwvUhGBqd7pScqz_30cjEaQVxG-wUEkXCxIh84MVwd8wx-vOPZo79Y1EvuMplw-L=w1064-v0
https://lh3.googleusercontent.com/P_zkWhMP_2Qx155YdrGNgy4sGB9dzeFfddy_GIFlWza5c0Zb4hGw9BMMkKv_FPm4S920ZmU6Js3ZifVlwPMotY7N2n1vad-3HiXYQw=w1064-v0
In the theme Theme.MaterialComponents.DayNight the colorPrimary is violet if I do not specify any value but in AppCompatTheme it was white/light grey in not night mode

**Comment by proletarius101** [comment]
>  In your Toolbar you can use:

That's true. Shouldn't it be the default in the tutorial: https://material.io/components/app-bars-top/android#regular-top-app-bar? Only the `PrimarySurface` variant is "Dark theme-ready" to my understanding.
