### ISSUE TITLE
[ChipGroup] `isSingleSelection` does not take into account `chip`s set to checked programmatically

### ISSUE THREAD

**Issue by dlemures** [material-components/material-components-android#1647]
**Description:** For ChipGroup of type choice. When setting a `chip` to checked programmatically using `setChecked(true)` is not taking into account when applying the restrictions for the flag `singleSelection`:

1. Doing `ChipGroup.setSingleSelection(true)`
2. Doing `chip1.setChecked(true)`
3. Click on `chip2`
4. Chip 1 and Chip 2 are selected.
5. No `setOnCheckedChangeListener` is sent for Chip1 for getting deselected.

**Expected behavior:** ChipGroup with `singleselection` should remain single selection and call the listeners accordingly.

**Source code:** 

```kotlin
group.isSingleSelection = true
group.isSelectionRequired = true

private fun addChips() {
        val chip1 = Chip(context)
       chip1.text = "text1"
       chip1.isChecked = true
       chip1.setOnCheckedChangeListener { view, isChecked ->
                Log.wtf("TEST457", isChecked)
      }
      addView(chip1)
  
     val chip2 = Chip(context)
       chip2.text = "text2"
       chip2.setOnCheckedChangeListener { view, isChecked ->
                Log.wtf("TEST457", isChecked)
      }
      addView(chip2)
}
```

**Android API version:** 

```
minSdkVersion 23
targetSdkVersion 29
compileSdkVersion 29
```

**Material Library version:** 1.2.0

**Device:** x86 emulator running SDK 30

**Comment by gabrielemariotti** [comment]
Currently you can't assign `chip1.isChecked = true` before it gets added to the `ChipGroup`.
You can use:

        val chip1 = Chip(context)
        group.addView(chip1)
        chip1.isChecked = true

or:

       val chip1 = Chip(context)
       addView(chip1)
  
       val chip2 = Chip(context)
       addView(chip2)
       group.check(chip1.id)

**Comment by dlemures** [comment]
Thx for the answer @gabrielemariotti , it works :)
