### ISSUE TITLE
Snackbar duration documentation is out of date

### ISSUE THREAD

**Issue by rock3r** [material-components/material-components-android#165]
### Overview

The javadoc for `Snackbar#make()` says: `duration How long to display the message.  Either {@link #LENGTH_SHORT} or {@link #LENGTH_LONG}` (so, no `LENGTH_INDEFINITE`), but `Snackbar#setDuration()` (from `BaseTransientBottomBar`) says: `either be one of the predefined lengths: {@link #LENGTH_SHORT}, {@link LENGTH_LONG}, or a custom duration in milliseconds.`
and then looking at the actual implementation, in `android.support.design.widget.SnackbarManager#scheduleTimeoutLocked()` the custom duration is handled just fine as well as `LENGTH_INDEFINITE` is

### Reproduction steps

Docs issue

### Version number

Master as of today (1.0.0-beta01)

### Operating system and device

Irrelevant

### Related issues

#164 fixes this issue

**Comment by cketcham** [comment]
fixed in 2cb77c9331cc3c6a5034aace0238b96508acf47d
