### ISSUE TITLE
setting background to Button has no effect 

### ISSUE THREAD

**Issue by MahmoudMabrok** [material-components/material-components-android#1650]
after i fix my issue here #1649 and changing themr, my <Button> can not change his background 
![Screenshot from 2020-08-24 17-50-50](https://user-images.githubusercontent.com/13488900/91070577-341b1000-e637-11ea-94cb-cc91d48f361f.png)

when i change **Theme** of design tool to **AppCompat** i can see my new **backgound** 

after search i found that i should change` <Button>` into` <android.widget.Button>`, why we need this

**Comment by MahmoudMabrok** [comment]
@gabrielemariotti if u can help me

**Comment by gabrielemariotti** [comment]
Check the [doc](https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md#container-attributes).

Use the`app:backgroundTint` attribute to apply a color to the button background.

**Comment by fAntel** [comment]
I have this issue too and use of `app:backgroudTint` doesn't help.

I use `Bridge` theme for activity and style for button based on `Widget.MaterialComponents.Button`. It's work for library version 1.1.0 but it doesn't work for 1.2.0 and 1.2.1. If I change back button style to `Widget.AppCompat.Button.Colored`, it's work with 1.2.0 and 1.2.1 but new material styles have different font and it looks ugly to combine this styles.

Styles:
```
<!-- activity theme -->
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge">
    <item name="colorPrimary">#FFFFFF</item>
    <item name="colorPrimaryDark">#FFFFFF</item>
    <item name="colorAccent">#802095</item>
    <item name="android:screenOrientation">portrait</item>
    <item name="android:windowBackground">#FAFAFA</item>
</style>

<!-- button style -->
<style name="MainButton" parent="Widget.MaterialComponents.Button">
    <item name="backgroundTint">#802095</item>
    <item name="android:textColor">#FFFFFF</item>
    <item name="android:fontFamily">sans-serif-medium</item>
    <item name="android:textSize">14sp</item>
    <item name="android:textAllCaps">true</item>
</style>
```

Usage:
```
<Button
    style="@style/MainButton"
    android:id="@+id/button"
    android:layout_width="match_parrent"
    android:layout_height="wrap_content"
    android:layout_marginEnd="16dp"
    android:layout_marginStart="16dp"
    android:text="test"/>
```

material-components-android 1.1.0
![image](https://user-images.githubusercontent.com/10121347/92105611-c2d41d80-edeb-11ea-9b98-aa412ecc5670.png)

material-components-android 1.2.1
![image](https://user-images.githubusercontent.com/10121347/92105743-f44ce900-edeb-11ea-8377-4f6db1bddb05.png)

**Comment by gabrielemariotti** [comment]
@fAntel 
It is a different issue.

You can check in the Layout Inspector:

<img width="210" alt="Schermata 2020-09-03 alle 13 59 27" src="https://user-images.githubusercontent.com/2583078/92112250-cbc5ee80-eded-11ea-846d-3bdd58654ff3.png">

In your case since you are using a `Bridge` Theme, you are working with an `AppCompatButton`.

You can use:

```
<com.google.android.material.button.MaterialButton
    style="@style/MainButton"
    android:id="@+id/button"
    android:layout_width="match_parrent"
    android:layout_height="wrap_content"
    android:layout_marginEnd="16dp"
    android:layout_marginStart="16dp"
    android:text="test"/>
```

or

```
    <style name="AppThemeBridge" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge">
        <item name="viewInflaterClass">com.google.android.material.theme.MaterialComponentsViewInflater</item>
    </style>
```
