### ISSUE TITLE
[RangedSlider] setMinSeperation not working when stepsize > 0

### ISSUE THREAD

**Issue by ranganatha2g** [material-components/material-components-android#1657]
**Description:** setMinSeperation() for ranged slider is not working when stepsize > 0. 

**Expected behavior:** setMinSeperation() should work even when stepSize > 0

**Source code:** 
` private float getClampedValue(int idx, float value) {
    float minSeparation = stepSize == 0 ? getMinSeparation() : 0;
   ....... 
   }`
**Android API version:** 29 but should happen in all versions

**Material Library version:** 1.3.0-alpha02

**Device:** Pixel 3a (emulator)

**Comment by leticiarossi** [comment]
Hi there, we don't have plans to support both cases together for now. You could use an `onChangeListener` to adjust the values manually.

**Comment by ranganatha2g** [comment]
Hi,  can you please let me know how this can be done using onChangeListener without knowing with thumb is being moved? Thanks
