### ISSUE TITLE
[Tablayout] Tab text color not changed

### ISSUE THREAD

**Issue by michalkierasinski** [material-components/material-components-android#1659]
**Description:** Hello,
I trying to change the text color on the tabs but it does not work.

I tried to set up it in style via "tabTextColor", "tabSelectedTextColor" attributes and inside Activity via setTabTextColors method.
But the result was the same, colors stay the same.

**Expected behavior:** Text color should be changed

**Material Library version:** 1.1.0

**Comment by leticiarossi** [comment]
Can you provide a sample app and screenshots of your issue?  `tabTextColor` should be the correct attribute to change text color. By default it's set to [this color state list](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/tabs/res/color/mtrl_tabs_icon_color_selector.xml).

**Comment by michalkierasinski** [comment]
I found that in my project we are using a custom view for the tabs. 
Bug can be closed.

**Comment by nikhil-seth** [comment]
@leticiarossi Does tabLayout.tabTextColors not work with Custom View for tabs ?
Asking because, even in my case its not working & its nowhere mentioned in documentation.
