### ISSUE TITLE
[DatePicker] "Selected date" initial text not translated

### ISSUE THREAD

**Issue by cyb3rko** [material-components/material-components-android#1664]
**Description:** In the DatePicker the text field above the calendar says "Selected date", but it is not translated into the device language.
Everything else gets translated (blue circle), only this is missing (red circle).

<img src="https://user-images.githubusercontent.com/46033730/91494576-5754f200-e8b9-11ea-9a89-9e337c928c7c.jpg" height="600">

**Android API version:** 26

**Material Library version:** 1.2.0

**Device:** Samsung SM-G930F

**Comment by matpag** [comment]
Probably duplicate of #761

**Comment by cyb3rko** [comment]
@matpag Thanks!
