### ISSUE TITLE
[MaterialFadeThrough] Customizable StartScale

### ISSUE THREAD

**Issue by drakeet** [material-components/material-components-android#1668]
Hi, can we customize the `StartScale` of `MaterialFadeThrough`? It is now hardcoded to `0.92`(`com.google.android.material.transition.MaterialFadeThrough#DEFAULT_START_SCALE`).

I think we can provide a new constructor and allow this value to be specified.

Or, is it possible that `MaterialVisibility` can be extended, that is, public it, so that we can customize a new FadeThrough.

Thanks!

**Comment by hunterstich** [comment]
Hey @drakeet,

This is currently possible. You can manipulate/set the secondary `VisibilityAnimatorProvider` on `MaterialFadeThrough`, customizing the incoming start scale to what you need.

```
    MaterialFadeThrough fadeThrough = new MaterialFadeThrough();
    ScaleProvider scaleProvider = new ScaleProvider();
    scaleProvider.setScaleOnDisappear(false);
    scaleProvider.setIncomingStartScale(0.3F);
    fadeThrough.setSecondaryAnimatorProvider(scaleProvider);
```

`MaterialFadeThrough`, `MaterialSharedAxis` and `MaterialFade` all extend `MaterialVisibility`. `MaterialVisibility` is a class that composes an animation built of two parts - a primary and secondary animator provider. The primary animator provider can be manipulated while the secondary animator provider can be completely replaced with either a Material provider (`ScaleProvider`, `FadeProvider`, `SlideDistanceProvider`) or your own implementation of `VisibilityAnimatorProvider`.  

Let me know if this solves your issue!
