### ISSUE TITLE
[TabLayout] Make TabLayout customizable from kotlin

### ISSUE THREAD

**Issue by saket** [material-components/material-components-android#1675]
**Is your feature request related to a problem? Please describe.**
`TabLayout`'s attributes like `tabBackground`, `tabPaddingStart`, etc. can only be set from Xml, making it very difficult to instantiate it from kotlin. We use dynamic themes and it's very hard to theme/style `TabLayout` without resorting to reflection.

**Describe the solution you'd like**
Please consider adding setters for them for all supported attributes. It is sad to treat Android as an Xml-only world.

**Comment by Ygor8686** [comment]
Very good
