### ISSUE TITLE
[NavigationView] padding is broken when placed inside a BottomSheetDialogFragment

### ISSUE THREAD

**Issue by s1ee** [material-components/material-components-android#1677]
When placing a `NavigationView` inside a `BottomSheetDialogFragment`, the background will have weird padding. Downgrading library to `1.1.0-alpha01` fixes this.

<img width="413" alt="Screen Shot 2020-09-01 at 11 11 31 am" src="https://user-images.githubusercontent.com/68889754/91917654-e91e8e00-ed03-11ea-83aa-6cf8c5bbb45e.png">

**Comment by drchen** [comment]
Is this still happening with the latest library version?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
