### ISSUE TITLE
Theme.MaterialComponents had the bug with the NaviagtionView

### ISSUE THREAD

**Issue by kimcy929** [material-components/material-components-android#168]
### Overview
I replaced the Theme.Appcompat to Theme.MaterialComponents But this made the status bar color is transparent when opening the NavigationView. Using Theme.Appcompat or Theme.Appcompat.DayNight hadn't this problem.

### Version number
**com.google.android.material:material:1.0.0-beta01 
 androidx 1.0.0-beta01**

### Operating system and device
Irrelevant

**Theme.AppCompat**

![theme_appcompat](https://user-images.githubusercontent.com/4311848/42500108-9d585fc8-845a-11e8-8cef-61e5aef77a9d.png)

**Theme.MaterialComponents**

![theme_material_components](https://user-images.githubusercontent.com/4311848/42500162-ba38396a-845a-11e8-8e6f-7cf741a1b591.png)

**Comment by wcshi** [comment]
Closing issue since it's tracked here:
https://b.corp.google.com/issues/112390513

**Comment by PaulWoitaschek** [comment]
If someone wonders here is the link to the public bugtracker:
https://issuetracker.google.com/issues/112390513
