### ISSUE TITLE
TextInputLayout

### ISSUE THREAD

**Issue by NotNotMarshall** [material-components/material-components-android#1682]
Please have a look at this, I am sick and have fever so can't focus too much... And my deadline is near so I can't either stop working.
This is my problem that i posted yesterday...

https://stackoverflow.com/questions/63713583/android-material-library-crashes-the-app-when-using-a-password-toggle-drawable-w

**Comment by MoshDev** [comment]
I have the same issue, the weird thing that it happens the first time you run the screen, the 2nd time you run the same screen it works fine.

**Comment by gabrielemariotti** [comment]
@MoshDev 
In the original question on SO the author added the **it works fine in an empty project** and the issue was related to some drawables in the res folder, not to the library.
So this issue can be closed.

If you have a similar issue pls provide more detail to reproduce it.
