### ISSUE TITLE
[MaterialCardView] Ability to change checked icon padding and size

### ISSUE THREAD

**Issue by leinardi** [material-components/material-components-android#1683]
**Is your feature request related to a problem? Please describe.**
The current checked icon works fine if you use a medium `shapeAppearance` but, when using a small or large, may be necessary to use different padding and size for this icon

**Describe the solution you'd like**
Ability to set padding and size for the checked icon via both XML (`app:iconSize` and `app:iconPadding`) and programmatically, in a similar way to what we can already do for the Chips:
![image](https://user-images.githubusercontent.com/273338/92109338-201a9f80-ede9-11ea-8d80-ad69f7bc6d27.png)

**Additional context**
![image](https://user-images.githubusercontent.com/273338/92109791-f2822600-ede9-11ea-9ef7-24764955f19e.png)

**Comment by gabrielemariotti** [comment]
There is a PR #1613 with this implementation.

**Comment by leinardi** [comment]
Nice! Thanks Gabriele :+1:
