### ISSUE TITLE
[Motion] Container Transform Animation not working for BottomSheetDialogFragment

### ISSUE THREAD

**Issue by mehul4795** [material-components/material-components-android#1687]
**Description:** 

Consider two Fragment - FragmentA and FragmentB where FragmentB is a BottomSheetDialogFragment. There is a FAB in the FragmentA and clicking on it shows the FragmentB.

**XML code of FAB in FragmentA**

```
<com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/fabAddSchedule"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_add"
        app:backgroundTint="?attr/colorPrimary"
        android:transitionName="@string/meeting_schedule_container_transform_fab"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:shapeAppearance="@style/FabTopLeftRoundedCornerShapeAppearance"
        app:tint="?attr/colorOnPrimary" />
```

**XML code of the ConstraintLayout (Root View) in FragmentB**

```
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:transitionName="@string/meeting_schedule_container_transform_fab">

<!-- Other Views -->

</androidx.constraintlayout.widget.ConstraintLayout>
```

**onClick() of FAB in FragmentA**

```
binding.fabAddSchedule.setOnClickListener {
            val fabTransitionName = getString(R.string.meeting_schedule_container_transform_fab)
            val extras = FragmentNavigatorExtras(binding.fabAddSchedule to fabTransitionName)
            findNavController().navigate(
                R.id.action_meetingScheduleFragment_to_meetingAddScheduleFragment,
                null,
                null,
                extras
            )
        }
```

**onCreate() of FragmentB**

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        sharedElementEnterTransition = MaterialContainerTransform()
    }
```
**Expected behavior:**

On clicking the FAB, it should transform into the BottomSheet but, the BottomSheet appears from the bottom of the screen without any transformation.

**Android API version:** 29

**Material Library version:** 1.3.0-alpha02

**Device:** OnePlus 5T

**Comment by hunterstich** [comment]
Hey @mehul4795,

I know you've taken time to attach code snippets, which is appreciated. Would it be possible to attach a full sample that I can run and help debug? 

Off the top of my head, I would assume BottomSheetDialogFragment is overwriting your container transform with its own slide transition. Out of curiosity, do you have a mock that you're trying to implement? I would venture to guess that the default sliding animation is a better pattern which helps hint at the user being able to expand the sheet with a gesture.

**Comment by mehul4795** [comment]
Hello,

I think your assumption of BottomSheetDialogFragment overwriting the container transform with its own slide transition is correct. Also, I realized that the BottomSheetDialogFragment slides from the bottom of the screen and so a FAB transitioning into a BottomSheetDialog would look a bit weird.

**Comment by rkoshti** [comment]
Is this fixed ?
