### ISSUE TITLE
MaterialDatePicker callbacks lost on orientation change

### ISSUE THREAD

**Issue by Nailik** [material-components/material-components-android#1688]
Hi,
due to Androids "weird" handling of rotation changes the callbacks of the MaterialDatePicker are "lost" after orientation change.

Because the MaterialDatePicker ist final there is no way to extend it and override it and handle the click in my own code.
A good way would be to change this:

```
confirmButton.setOnClickListener(
        new View.OnClickListener() {
          @Override
          public void onClick(View v) {
            for (MaterialPickerOnPositiveButtonClickListener<? super S> listener :
                onPositiveButtonClickListeners) {
              listener.onPositiveButtonClick(getSelection());
            }
            dismiss();
          }
        });
```

to sth like 

```
confirmButton.setOnClickListener(
        new View.OnClickListener() {
          @Override
          public void onClick(View v) {
               onOkClick();
          }
        });
```

and add a function 

```
public void onOkClick(){
            for (MaterialPickerOnPositiveButtonClickListener<? super S> listener :
                onPositiveButtonClickListeners) {
              listener.onPositiveButtonClick(getSelection());
            }
            dismiss();
}
```

And make MaterialDatePicker **NOT `final`** this way i could extend it and:

```
@Override
public void onOkClick(){
     //save new date to my database
    super.onOkClick();
}
```
I'm pretty sure that's a much more elegant solution than either

- disable orientation changes while dialog is opened
- check in my activity after orientation change if the dialog is opened and reattach my callback

**Comment by ymarian** [comment]
We cannot serialize the listeners to retain them. 

Since the dialog is going to be recreated on a config change, you can find the fragment by the tag set when calling show. 

Just reset the listeners in onResume or when appropriate:

```java
MaterialDatePicker datepicker  = (MaterialDatePicker) supportFragmentManager.findFragmentByTag("tag");
// reset listeners
```

**Comment by Nailik** [comment]
@ymarian I'm not sure if you did understand my solution.

I know that you can't serialize the listeners.
That's the reason why i want to extend the MaterialDatePicker and not use a listener but do my database stuff right in my created class. But MaterialDatePicker is final (for what reason?)... so i can't do this.

Doing a lot such searches with findFragmentByTag is not a nice thing because i have to do it in every Activity that may sometimes show the Dialog or i have to do it in AppCompatDelegate - that's not a nice solution either.

**Comment by VitKap** [comment]
Just set the listener in `OnAttachFragment` or create a `OnFragmentAttachListener` and after rotation the listener will be OK.

```
 if (childFragment instanceof MaterialDatePicker) {
            ((MaterialDatePicker<?>) childFragment).addOnPositiveButtonClickListener(selection -> {
                mTransportationFilterViewModel.setSelection((long) selection);
            });}

```

**Comment by Nailik** [comment]
I would recommend to simply switch to Jetpack compose.

**Comment by Rajarml** [comment]
@Nailik does it resolve the lost listeners issue after a config change like device rotation ?

**Comment by VyacheslavMartynenko** [comment]
> I would recommend to simply switch to Jetpack compose.

It's not the best solution to this particular problem. Unfortunately, switching to Jetpack compose is not easy when we talk about a big project. This library supports fragments and the material date picker is a DialogFragment itself... 

For this particular problem, there is a case that is valid for general AlertDialog. Just give us an opportunity to extend this class or at least a possibility to directly SET the behavior of the buttons. Then we can send the result via modern navigation/communication patterns and we are not forced to implement extra steps for state restoration. 

All modern Google libraries try to follow the new development ideas that will help to limit state restoration handling. I strongly believe that MaterialComponents should be on that list also.

**Comment by vullnetlimani** [comment]
It's disappointing to see that this bug was closed without addressing the underlying issue. This oversight leads to significant inconvenience, as the problem can manifest in various scenarios, such as when changing the device orientation or switching themes.

Currently, I'm resorting to a workaround by setting `datePicker.retainInstance = true`, despite its deprecated status. While this workaround functions across Android versions from 6 to 14, it's not a sustainable or recommended approach.

Google needs to take concrete action to resolve this issue properly. Relying on deprecated fixes isn't the right path forward, and users shouldn't have to deal with these workarounds to make their apps work reliably. The problem is more profound than just one occurrence and could affect many developers and users alike. It's crucial to prioritize a comprehensive solution that addresses this issue from the root.

**Comment by paulfthomas** [comment]
Let me take another look at this

**Comment by vullnetlimani** [comment]
Hey there,

I noticed that this issue has been fixed, but it doesn't seem to be reflected in the library. As you can see, I'm using the latest version (1.13.0-alpha04). However, when I open MaterialDatePicker, I still see the old class. I saw that this class is no longer final, but as shown in the photo, it is still final, and the changes in the click listener are still from the old version.

Even I am using the class from the new updated version.

![image](https://github.com/user-attachments/assets/907edf1d-442b-4a91-b4e0-a76af9dfc085)

**Comment by paulfthomas** [comment]
@vullnetlimani the fix didn't make it to the alpha04 release, it will be part of the next one, probably in a couples weeks.

**Comment by manabu-nakamura** [comment]
How do you improve [DatePickerMainDemoFragment](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/datepicker/DatePickerMainDemoFragment.java) by https://github.com/material-components/material-components-android/commit/6617342f03ba2031a974733e62321aaa67912c04?

**Comment by histogramsquadron** [comment]
https://lnkr.fun/932962e



I suspect this might offer some clarity

**Comment by heysem-useinsider** [comment]
It's somewhat disappointing to see Google engineers make such a rookie mistake in their component design.

This issue can (and probably should) be addressed by introducing a listener interface:
```kotlin
interface MaterialDatePickerListener {
	fun onDatePick(date: LocalDate)
}
```

Then, have the users make the parent fragment or activity implement this interface:
```kotlin
class MainActivity : AppCompatActivity(), MaterialDatePickerListener {
	...

	override fun onDatePick(date: LocalDate) {
		// material date picker callback
	}
}
```

When you need to invoke the callback, simply get the `parentFragment` or `activity` and cast it to the listener interface:
```kotlin
val listener = (parentFragment as? MaterialDatePickerListener) ?: (activity as? MaterialDatePickerListener)
listener?.onDatePick(date)
```

Alternatively, you can resolve this issue by using the modern [FragmentResult](https://developer.android.com/guide/fragments/communicate#fragment-result) API.

Also, I don't see any reason to make `MaterialDatePicker` and `MaterialTimePicker` final. I feel like I should be able to extend these components and add new functionality if I want to.
