### ISSUE TITLE
[Component name] Short description of issue

### ISSUE THREAD

**Issue by elshafeyking** [material-components/material-components-android#1691]
**Description:**
I have problem  into Floting action button

**Expected behavior:** 
It's drawable can.t be appear and show to me that i have 
1_render problem of  
Of floating action button
Path.op() not supported
2_another render problem of java.awt.geom.illegalPathException (missing initial move to in path definition)

**Source code:**
`com.google.android.material.floatingactionbutton.FloatingActionButton
android:id="@+id/fab"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:layout_alignparentBottom="true"
android:layout_alignparentEnd="true"
android:layout_margin="16dp"
android:src"@drawable/ic_add_Pet>

**Android API version:** Android API version here is 29

**Material Library version:** Material Android Library version you are using here (e.g., 1.3.0-alpha02)

**Device:** Device on which the bug was encountered here :android phone pixel

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library. 
(Well)

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).
(Well)

**Comment by ymarian** [comment]
This issue is underspecified. Default FABS render correctly. Please provide a sample app or give instructions for how to repro in the catalog app:

https://github.com/material-components/material-components-android/tree/master/catalog
