### ISSUE TITLE
MaterialDatePicker wiht white theme

### ISSUE THREAD

**Issue by kldMohammed** [material-components/material-components-android#1694]
i tried to use MaterialDatePicker with a white the button doesn't appears and i tried to implement custom theme for it change button color also nothing changed
![photo5963238997742433772](https://user-images.githubusercontent.com/17613367/92512725-84859680-f20f-11ea-8a8d-7e74e2abf907.jpg)

**Comment by ymarian** [comment]
Please provide code snippets or a sample app if this is an issue. 

Also read the theming section:

https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md

**Comment by kldMohammed** [comment]
this is my theme

`	<style name="AppTheme" parent="Theme.MaterialComponents.Light">
		<item name="colorPrimary">@color/white</item>
		<item name="colorPrimaryDark">@android:color/white</item>
		<item name="colorAccent">@color/colorAccent</item>
		
		<item name="colorOnPrimary">@color/colorAccent</item>
		<item name="colorSecondary">@color/colorAccent</item>
		<item name="colorSecondaryVariant">@color/white</item>
		<item name="colorOnSecondary">@color/white</item>
		<item name="colorError">#F44336</item>
		<item name="colorOnError">#FFFFFF</item>
		<item name="colorSurface">#FFFFFF</item>
		<item name="colorOnSurface">#212121</item>
		<item name="android:textColorPrimary">#212121</item>
		<item name="colorControlNormal">#212121</item>
	
		<item name="android:windowLightStatusBar" tools:targetApi="m">true</item>
		<item name="android:statusBarColor" tools:targetApi="lollipop">@android:color/white</item>
		<item name="android:windowDrawsSystemBarBackgrounds" tools:targetApi="lollipop">true</item>
		<item name="android:windowTranslucentNavigation" tools:targetApi="kitkat">false</item>
		<item name="android:navigationBarColor" tools:targetApi="lollipop">#000</item>
		
		
		
		<item name="colorOnBackground">#212121</item>
		
		<item name="shapeAppearanceSmallComponent">@style/AppShapeAppearance.SmallComponent</item>
		<item name="shapeAppearanceMediumComponent">@style/AppShapeAppearance.MediumComponent</item>
		<item name="materialCardViewStyle">@style/AppCard</item>
		
		
		<item name="textInputStyle">@style/AppTextField</item>
		<item name="materialButtonStyle">@style/AppButton</item>
		<item name="buttonStyle">@style/AppButton</item>
		
		
		



	</style>`

**Comment by ymarian** [comment]
All the information needed is in the theming section. 

The provided theme is not well formed. Having colorPrimary be white is what's causing the buttons to not show.
