### ISSUE TITLE
[AppBarLayout] AppBarLayout does not collapse/expand when scrolling vertically over horizontal RecyclerView inside vertical RecyclerView

### ISSUE THREAD

**Issue by MaratTursynbek** [material-components/material-components-android#1695]
**Description:** When vertical `RecyclerView` has a horizontal `RecyclerView` and if user starts scrolling vertically with finger on horizontal `RecyclerView` then **`AppBarLayout`** does not move at all. If finger was on other list items then `AppBarLayout` does change its state.

The problem is still there with `CollapsingToolbarLayout` inside AppBarLayout.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19596530/92520175-7b9ac200-f21b-11ea-816a-d6e54e7a4f59.gif)

**Expected behavior:** AppBarLayout should scroll

**Source code:** I created a test project where you can see the problem. https://github.com/MaratTursynbek/AppBarLayout-bug

Code of CollapsibleToolbar is taken from [this](https://medium.com/google-developers/introduction-to-motionlayout-part-iii-47cd64d51a5) article.

```
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/app_bar_layout"
        android:layout_width="match_parent"
        android:layout_height="76dp"
        android:theme="@style/AppTheme.AppBarOverlay.Light">

        <com.example.notcollapsingappbar.CollapsibleToolbar
            android:id="@+id/motion_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:minHeight="@dimen/actionBarSize"
            app:layoutDescription="@xml/scene_header"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:popupTheme="@style/AppTheme.PopupOverlay" />

            <TextView
                android:id="@+id/toolbar_title"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:gravity="start|center_vertical"
                android:text="Large title"
                android:textColor="@android:color/white"
                android:textSize="30sp"
                app:autoSizeTextType="uniform" />

        </com.example.notcollapsingappbar.CollapsibleToolbar>

    </com.google.android.material.appbar.AppBarLayout>

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:paddingBottom="16dp"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Android API version:** All versions from API 21

**Material Library version:** 1.2.1

**Device:** OnePlus 5t, Pixel 3, Pixel 3 emulator, Samsung A10

**Comment by Sanlorng** [comment]
try to set nestedScrollEnable of Horizontal RecyclerView to false

**Comment by MaratTursynbek** [comment]
setting android:nestedScrollingEnabled="false" solved the issue. @Sanlorng if it is possible could you please explain why this works? Is it because of inner RecyclerView sending overriding parent RV's vertical scroll events with 0 offset to AppBarLayout?

**Comment by Sanlorng** [comment]
> setting android:nestedScrollingEnabled="false" solved the issue. @Sanlorng if it is possible could you please explain why this works? Is it because of inner RecyclerView overriding parent RV's vertical scroll events and sending 0 vertical offset to AppBarLayout?
> 
> 

If NestedScrollingChild as a child View is enabled, NestedScrollingParent as a parent layout will not intercept scrolling events

**Comment by z74rus** [comment]
> > setting android:nestedScrollingEnabled="false" solved the issue. @Sanlorng if it is possible could you please explain why this works? Is it because of inner RecyclerView overriding parent RV's vertical scroll events and sending 0 vertical offset to AppBarLayout?
> 
> If NestedScrollingChild as a child View is enabled, NestedScrollingParent as a parent layout will not intercept scrolling events

Is it possible to solve on Android API below 21?

**Comment by PallabJunior** [comment]
I had the same issue and android:nestedScrollingEnabled="false" does solve it for the nested recyclerviews. But I have a horizontal ViewPager inside a vertical recyclerView which is giving me this same issue and cann't be resolved by use android:nestedScrollingEnabled.

What is the solution for that?

**Comment by araujotadeu** [comment]
What's the solution to this issue? I am having the same problem as [PallabJunior](https://github.com/PallabJunior), not working with a ViewPager2.

**Comment by nathankim0** [comment]
Thanks. But not working with a ViewPager2.

**Comment by wiryadev** [comment]
Still no solution for ViewPager2?

**Comment by wiryadev** [comment]
> I had the same issue and android:nestedScrollingEnabled="false" does solve it for the nested recyclerviews. But I have a horizontal ViewPager inside a vertical recyclerView which is giving me this same issue and cann't be resolved by using android:nestedScrollingEnabled =false.
> 
> What is the solution for that?

Found the answer on another [issue](https://github.com/material-components/material-components-android/issues/2112#issuecomment-1536262991).

`(viewPager2.getChildAt(0) as RecyclerView).isNestedScrollingEnabled = false`
