### ISSUE TITLE
[TextInputLayout] Causing focus issue when error != null

### ISSUE THREAD

**Issue by baggednismo** [material-components/material-components-android#1699]
Using 2 TextInputLayout's with a single TextInputEditText for a recyclerview item layout seems to provide very strange behavior. See video provided for details. I have seen similar behavior when they are in ConstrainLayouts but this appears to be specific to an error.

**Android API version:** target 29
**Material Library version:** 1.3.0-alpha02
**Device:** Pixel API 29 Emulator

See video of behavior
https://drive.google.com/file/d/1I16V-9G9cPNm5DYhZ651XdNN9-wVJX-F/view?usp=sharing

**Comment by drchen** [comment]
Hi I don't have access to the link. Is this still happening?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
