### ISSUE TITLE
Feature Request - Bottom Navigation View doesn't keep selected tab state

### ISSUE THREAD

**Issue by nico-gonzalez** [material-components/material-components-android#17]
### Overview
Current version of the Bottom Navigation View doesn't keep it's view state when a configuration change takes place, instead, it defaults to the first tab. I think the expected behavior would be to keep the current selected tab state without triggering a new **OnNavigationItemSelectedListener::onNavigationItemSelected()**

**Comment by MGaetan89** [comment]
This seem to be fixed in the latest release of the support library.

**Comment by tec27** [comment]
Yep, this was fixed with 9e2c201185365271677f052b31c8681e38d49526.

Thanks for reporting (and also thanks for noting that it was fixed)!

**Comment by MGaetan89** [comment]
It's always easy to complain when something is broken ;)
I guess the related PR #19 can also be closed.

**Comment by r3dm4n** [comment]
This is still not working!
