### ISSUE TITLE
[Catalog App: Bottom App Bar] BottomSheet is Too Light

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#1700]
**Description:** https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/bottomappbar
The BottomSheet (#3b3b3b) is too light (the elevation of BottomSheet is 32dp totally).

![Screenshot_20210908-145455](https://user-images.githubusercontent.com/71050561/132454477-7cd5c134-ce41-4dd2-a847-239b020092cf.png)

**Expected behavior:** The BottomSheet should be #2d2d2d (the elevation of BottomSheet should be 16dp).
https://material.io/design/environment/elevation.html
https://material.io/design/color/dark-theme.html

**Source code:** https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/bottomappbar/res/layout/cat_bottomappbar_fragment.xml#L49
(original)
```
  <FrameLayout
      android:id="@+id/bottom_drawer"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:elevation="16dp"                                                                <=
      app:behavior_hideable="true"
      app:layout_behavior="@string/bottom_sheet_behavior">

    <com.google.android.material.navigation.NavigationView
        android:id="@+id/navigation_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:menu="@menu/demo_primary"/>
  </FrameLayout>
```
(revised)
```
  <FrameLayout
      android:id="@+id/bottom_drawer"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      app:behavior_hideable="true"
      app:layout_behavior="@string/bottom_sheet_behavior">

    <com.google.android.material.navigation.NavigationView
        android:id="@+id/navigation_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:menu="@menu/demo_primary"/>
  </FrameLayout>
```

**Android API version:** 23

**Material Library version:** 1.4.0

**Device:** Nexus 7 (2013)

**Comment by drchen** [comment]
Since it's related to the old Material themes/styles I'll close it for now. Feel free to reopen it if it's still an issue with Material 3.

**Comment by manabu-nakamura** [comment]
I don't think that the elevation of the bottom sheet is 16dp.
https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheet.md

**Comment by drchen** [comment]
It's definitely not with M3. With Material 3 the elevation of bottom sheets is 3dp.
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/res/values/styles.xml#L69
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/res/values/dimens.xml#L25
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/elevation/res/values/tokens.xml#L24

**Comment by manabu-nakamura** [comment]
It should be 3dp.

https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/bottomappbar/res/layout/cat_bottomappbar_fragment.xml#L49
```
  <FrameLayout
      android:id="@+id/bottom_drawer"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:elevation="3dp"
      app:behavior_hideable="true"
      app:layout_behavior="@string/bottom_sheet_behavior">

    <com.google.android.material.navigation.NavigationView
        android:id="@+id/navigation_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:menu="@menu/demo_primary"/>
  </FrameLayout>
```

or

https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/bottomappbar/res/layout/cat_bottomappbar_fragment.xml
```
  <!--FrameLayout
      android:id="@+id/bottom_drawer"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:elevation="16dp"
      app:behavior_hideable="true"
      app:layout_behavior="@string/bottom_sheet_behavior"-->

    <com.google.android.material.navigation.NavigationView
        android:id="@+id/navigation_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:menu="@menu/demo_primary"
        app:layout_behavior="@string/bottom_sheet_behavior"
        style="@style/Widget.Material3.BottomSheet"/>
  <!--/FrameLayout-->
```

https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/bottomappbar/BottomAppBarMainDemoFragment.java#L223
```
    View bottomDrawer = coordinatorLayout.findViewById(R.id.navigation_view);
```
