### ISSUE TITLE
[MaterialTimePicker] Can't customize styling for newly released timePicker

### ISSUE THREAD

**Issue by zoubarry** [material-components/material-components-android#1703]
**Description:** 

Hi, I'm testing out the newly released MaterialTimePicker and trying couple ways to customize styling without any success,

I tried something like following:

item name="materialTimePickerTheme">@style/MyTimePickerDialogStyle</item>  // in app theme

`
    <style name="MyTimePickerDialogStyle" parent="@style/Widget.MaterialComponents.TimePicker">
        <item name="colorControlActivated">?attr/colorSecondary</item>
        <item name="colorAccent">?attr/colorPositiveButton</item>
  </style>
`

Wondering if customize styling is supported or not, where can I find a doc for the attributes I can use to customize? 

Thank you!

**Expected behavior:** Screenshots and/or description of expected behavior

**Android API version:** Any

**Material Library version:** 1.3.0-alpha02

**Device:** Any

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ymarian** [comment]
Hi there, Material Theme doesn't really use colorAccent. 

https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md

The documentation should be coming. 

In the meantime these are the colors that we're supposed to be using. Notice it's `primary`, `onSurface`, `surface`, `onPrimary` and others.  

![Screen Shot 2020-09-10 at 2 15 47 PM](https://user-images.githubusercontent.com/38727469/92779698-4a7fd600-f370-11ea-9525-2954e4696591.png)

**Comment by zoubarry** [comment]
@ymarian thanks for the quick reply and that helps. Couple follow-up questions:
1. Is there a way to customize the background color, e.g. the clock (change onSurface will also affect the hour text color)
2. Is there a way to hide the title? `SELECT TIME`
3. I assume no, but want to confirm is there a way to take out am/pm boarders?

**Comment by ymarian** [comment]
No problem!

1. Not for now, I'll check with design if that should be supported.

2. I was just working on that, so it should be coming soon. 

3. I'm not sure. Adding a dimen resource `mtrl_btn_stroke_size` with 0dp value or a color resource `material_timepicker_button_stroke` with value transparent to your App could work. The stroke is important for Accessibility so I'm not convinced we should have an easy to remove it. Let get back to you on that one.

**Comment by abhimuktheeswarar** [comment]
With this, you should be able to change almost everything.
```Kotlin
<style name="TimePicker" parent="ThemeOverlay.MaterialComponents.TimePicker">
        <item name="colorPrimary">@color/primaryMonoDarker</item>
        <item name="fontFamily">@font/poppins</item>
        <item name="materialTimePickerTitleStyle">@style/Picker.TitleTextAppearance</item>
        <item name="materialClockStyle">@style/TimePicker.Clock</item>
        <item name="materialButtonOutlinedStyle">@style/TimePicker.Button</item>
        <item name="chipStyle">@style/TimePicker.Chip</item>
        <item name="imageButtonStyle">@style/TimePicker.ImageButton</item>
        <item name="borderlessButtonStyle">@style/Picker.TextButton</item>
    </style>

    <style name="TimePicker.Clock" parent="Widget.MaterialComponents.TimePicker.Clock">
        <item name="clockFaceBackgroundColor">@color/primaryColor</item>
        <item name="clockHandColor">@color/primaryDarker</item>
        <item name="clockNumberTextColor">@color/color_state_clock_text</item>
    </style>

    <style name="TimePicker.Button" parent="Widget.MaterialComponents.TimePicker.Button">
        <item name="backgroundTint">@color/color_state_clock_chip_bg</item>
        <item name="android:textColor">@color/color_state_clock_chip_text</item>
        <item name="strokeWidth">0dp</item>
    </style>

    <style name="TimePicker.Chip" parent="Widget.MaterialComponents.TimePicker.Display">
        <item name="chipBackgroundColor">@color/color_state_clock_chip_bg</item>
        <item name="android:textColor">@color/color_state_clock_chip_text</item>
        <item name="android:textAppearance">@style/MyTitleTextAppearance</item>
    </style>

    <style name="TimePicker.ImageButton" parent="Widget.MaterialComponents.TimePicker.ImageButton">
        <item name="iconTint">@color/primaryDarker</item>
    </style>
```
