### ISSUE TITLE
[BottomNavigationView] Provide horizontal positioning for items (icon + label)

### ISSUE THREAD

**Issue by aleksandra-majchrzak** [material-components/material-components-android#1708]
**Is your feature request related to a problem? Please describe.**
Material Design specification describes that in the lanscape mode or for tablets it is fine to show item label next to the item icon:

<img width="761" alt="Zrzut ekranu 2020-09-11 o 17 00 31" src="https://user-images.githubusercontent.com/10994089/92941296-7d010000-f450-11ea-8503-0aa066f235ed.png">

**Describe the solution you'd like**
Currently `BottomNavigationView` does not provide any option for changing item label positioning. It would be great to have an attribute like `labelOrientation="horizontal|vertical"` or `labelGravity="start|top|end|bottom"`

**Comment by wcshi** [comment]
Thank you for reaching out, I asked the design team to provide detailed spec so we can implement this feature.

**Comment by aleksandra-majchrzak** [comment]
Hi! Is there any update on this topic?

**Comment by llama-0** [comment]
Hi all! Really waiting for this feature to be added. @aleksandra-majchrzak Alexandra, could you share what you did with this case for a time being?

**Comment by aleksandra-majchrzak** [comment]
I informed the client that it's not natively provided, and that would increase our estimate :D All after all, we're doing it the same way for both orientations.

**Comment by llama-0** [comment]
Oh, I see. Thanks for the reply)

**Comment by SDILogin** [comment]
> Hi all! Really waiting for this feature to be added. @aleksandra-majchrzak Alexandra, could you, please, share what you did with this case for a time being?

While there is no support of such UI in this lib, you can just create a custom view group with 4 text views. If you need to support only simple cases like switching tabs and observing selection changes, it won't be very challenging or time consuming

**Comment by llama-0** [comment]
I will try this approach, Dmitry. Thanks)

**Comment by Poopooracoocoo** [comment]
@wcshi any updates? the design team has had a year to make a spec for this

**Comment by Poopooracoocoo** [comment]
@drchen @wcshi *ahem* no updates? This'd really make a lot of sense to release now given the focus on better support on larger screens.

**Comment by drchen** [comment]
Hi sorry I just noticed this. I'll raise this to our design team again and check their feedback.

**Comment by drchen** [comment]
I haven't heard any updates so far. Will keep tracking it.

**Comment by heybradharris** [comment]
LETS GOOOOOOO

**Comment by Poopooracoocoo** [comment]
@drchen um please just check that the design team are alive. Two years without response of a once-featured design is a long time.

**Comment by sergpetrov** [comment]
I was going to work on the issue but it's unclear how to place the label because M3 navigation bar's active destination can be indicated with a pill shape.
It seems they don't need it since Material Design 3 doesn't contain guidelines for this. 
They forgot about this or refused it.

<img width="1127" alt="Screen Shot 2022-08-07 at 23 09 50" src="https://user-images.githubusercontent.com/1522823/183309706-5829793e-b073-492f-97c3-94cba014ee4e.png">

**Comment by drchen** [comment]
Hi sorry for no update of this for a while. 

Yeah I think in the new guidelines designers discarded the horizontal positioning of icon and text. Instead, I think we are going to encourage people using navigation rail/drawer in landscape mode. (You can refer to the adaptive demo in Catalog.)

We may have a more integrated navigation component coming in the future, but it's not decided yet and the timeline is unknown now. 

I'll close the issue as obsolete.
