### ISSUE TITLE
Test resources are being included in the AAR

### ISSUE THREAD

**Issue by andrefrsousa** [material-components/material-components-android#1709]
**Description:** After integrating version 1.2.1 in a work project, I find out that multiple test-related resources are being included in the AAR and therefore in the final APK.

**Expected behavior:**  Test resource should not be included in the final AAR

**Source code:** As an example, the following layouts are included in version 1.2.1 of the AAR:
![Screenshot 2020-09-11 at 18 06 54](https://user-images.githubusercontent.com/1705943/92953556-d0c41700-f459-11ea-9497-5f7878dd6834.png)

**Android API version:** N/A

**Material Library version:** 1.2.1

**Device:** N/A

**Comment by drchen** [comment]
They are part of the unit tests associated with the library. 

I'll check if we should exclude them.
