### ISSUE TITLE
Marked as private @string/appbar_scrolling_view_behavior

### ISSUE THREAD

**Issue by AagitoEx** [material-components/material-components-android#171]
The resource @string/appbar_scrolling_view_behavior is marked as private in com.google.android.material:material

is this lint expected or not??
using AS 3.1.3 with Android X / Material Components 1.0.0-beta01

**Comment by pedrovarela86** [comment]
I reported that somewhere, it is still private though, but just ignore it.

**Comment by cketcham** [comment]
which version of the library are you using?

**Comment by AagitoEx** [comment]
@cketcham com.google.android.material:material:1.0.0-beta01

**Comment by cketcham** [comment]
This should be fixed in the next release. You can ignore the warning for now.
