### ISSUE TITLE
[Button] Button styles have inconsistent drawable padding

### ISSUE THREAD

**Issue by pedronveloso** [material-components/material-components-android#1714]
**Description:** Full description of issue here

<img width="1074" alt="Screen Shot 2020-09-12 at 8 46 00 PM" src="https://user-images.githubusercontent.com/416941/93007699-82864500-f539-11ea-9b31-1b5ba1f55bf1.png">

As you can see on the image above, the padding between text and drawable isn't always the same. I've tried multiple things, such as playing around with `textAlignment` and `gravity`, and `drawablePadding`, but none seemed to produce a desired effect. Changing the left padding on the Button with the Google logo shifted both text and drawable so that wasn't a solution either.

Facebook and Kakao styled buttons are using:
`Widget.MaterialComponents.Button.UnelevatedButton`

And Google button is using:
`Widget.MaterialComponents.Button.OutlinedButton`

**Expected behavior:** All Button styles should have consistent padding, or at least allow for the drawable padding to be overwritten.

**Android API version:** Android 10

**Material Library version:** 2.0.1

**Device:** Samsung S20 and Emulators.

**Comment by gabrielemariotti** [comment]
`Widget.MaterialComponents.Button.UnelevatedButton` and `Widget.MaterialComponents.Button.OutlinedButton` use different `iconPadding` = padding between icon and button text.

The `Widget.MaterialComponents.Button.UnelevatedButton` use (`8dp`)

`<item name="iconPadding">@dimen/mtrl_btn_icon_padding</item>`

and the `Widget.MaterialComponents.Button.OutlinedButton`  use (`4dp`)

`<item name="iconPadding">@dimen/mtrl_btn_text_btn_icon_padding</item>`

**Comment by pedronveloso** [comment]
That fixes it, thanks a bunch! 
I missed this on the docs, was probably too fixated on looking for "drawable" as a keyword.
