### ISSUE TITLE
[MaterialDatePicker] Date range direction is reversed for RTL locales

### ISSUE THREAD

**Issue by HusseinElFeky** [material-components/material-components-android#1716]
**Description:**

When the user selects a date range on different rows using `MaterialDatePicker.Builder.dateRangePicker()`, the highlighted range is reversed if the app locale is RTL.

![MaterialDatePicker (RTL Layout Direction)](https://user-images.githubusercontent.com/20887574/93028395-001e8380-f614-11ea-8b79-59f681e1f0c5.jpg)

**Expected behavior:**

Date range direction should be reversed, selecting the appropriate dates, when the app locale is RTL.

**Source code:**

    MaterialDatePicker.Builder.dateRangePicker()
        .build()
        .show(childFragmentManager, TAG_DATE_PICKER)

**Android API version:** 29

**Material Library version:** 1.2.1

**Device:** Samsung Galaxy A70

**Comment by MhmoudAlim** [comment]
@HusseinElFeky I'm still facing the same issue, have you managed to fix it?

**Comment by HusseinElFeky** [comment]
@MhmoudAlim It has already been fixed by @gabrielemariotti. You can see it merged above.

**Comment by MhmoudAlim** [comment]
@HusseinElFeky Thank you for your reply.
I can see that it has been fixed, but it seems that the problem still occurs in some cases with Huawei and Honor devices.

**Comment by HusseinElFeky** [comment]
@MhmoudAlim I'm not sure why. If you could probably attach screenshots along with some data about the devices you used, it might help us debug the issue.

**Comment by MhmoudAlim** [comment]
@HusseinElFeky the issue only occurs when you choose a Start and End dates in two different months 

Configuration:
- API version: 29
- Material version: 1.3.0
- Device: Honor 10 Lite

**However, it seems that resetting the device language fixed the issue somehow!**

![Screenshot_20210506_120403](https://user-images.githubusercontent.com/23269839/117281968-82d6a600-ae64-11eb-9910-6bfdf63d366f.jpg)
