### ISSUE TITLE
[ShapeableImageView] should be renamed to ShapableImageView

### ISSUE THREAD

**Issue by alorma** [material-components/material-components-android#1722]
Creating a custom component (`ShapeabaleMaterialToolbar`) on my tem, someone raised a comment about the word `Shapeable`:

`ShapeableImageView` should be renamed to `ShapableImageView`

Right adjective is Shapable, not shapeable
check https://www.merriam-webster.com/dictionary/shapable

**Comment by ymarian** [comment]
Hi, both spellings are accepted, your link includes the one we are using too.  `variants: or shapeable` 

We also cannot change the name of classes released in stable since we would break binary compatibility.
