### ISSUE TITLE
[Release] make new snapshot of 1.3.0-alpha03

### ISSUE THREAD

**Issue by zx2c4** [material-components/material-components-android#1728]
1.3.0-alpha02 is starting to feel a bit old now, with all the recent improvements. What about making a new snapshot, 1.3.0-alpha03?

**Comment by ymarian** [comment]
Hi we'll release as soon as we're ready. No need to file bugs for that. 

You can use the daily snapshots if you need a feature immediately 

https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md

**Comment by zx2c4** [comment]
> Hi we'll release as soon as we're ready. No need to file bugs for that.
> 
> You can use the daily snapshots if you need a feature immediately
> 
> https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md

Those snapshots haven't been updated since July. Something is apparently broken with the process?

**Comment by ymarian** [comment]
Github UI is broken, the packages have still been updating almost daily if there are new commits

**Comment by zx2c4** [comment]
Good to know, thanks.

**Comment by ymarian** [comment]
you can use this query and check for the versions in the GraphQL explorer:

https://developer.github.com/v4/explorer/

```
{
  node(id: "MDE0OlBhY2thZ2VWZXJzaW9uMjMyNDc2OQ==") {
    ... on PackageVersion {
      id
      version
      files(last: 12, orderBy: {field: CREATED_AT, direction: ASC}) {
        nodes {
          name
        }
      }
    }
  }
}
```

**Comment by shekibobo** [comment]
How often does the snapshot build get run? I'm seeing the last one available on is from almost two weeks ago.

**Comment by dsn5ft** [comment]
It should be nightly. We are working on fixing it now.

**Comment by dsn5ft** [comment]
Should be fixed now!
