### ISSUE TITLE
[BottomSheetBehavior] Broken hidden->collapsed animation, setPeekHeight animation

### ISSUE THREAD

**Issue by emakar** [material-components/material-components-android#1729]
**Description:** Changing BottomSheet state when one is laid out should lead to state change animation.
However changing state from hidden to collapsed breaks animation totally in certain cases (makes it appear as expanded -> collapsed). `setPeekHeight` is affected as well due to the same reason (leads to no visible animation, peek height is changed due to layout)

**Source code:** 

```
// Issue for hidden -> collapsed
behavior.isHideable = true
behavior.state = BottomSheetBehavior.STATE_HIDDEN
// await layout

behavior.isHideable = false // animates only if no onLayoutChild happens between setHideable and settleToState
```

```
// The same issue for setPeekHeight
behavior.isHideable = true
behavior.state = BottomSheetBehavior.STATE_HIDDEN
// await layout

setPeekHeight(123, true) // animates only if no onLayoutChild happens between setPeekHeight and settleToState
```

Possible workaround for both is ugly as hell:
```
if (view.parent.isLayoutRequested) {
    view.post(animateCollapse)
    return
}
behavior.isHideable = false
behavior.state = BottomSheetBehavior.STATE_COLLAPSED
```

**Thoughts:**

This seem to work correctly prior to 46366ad4356b57180eac048cec9994c796a5ca66 (`onLayoutChild` change with `hideable` check)
There are several culprits to me:
- `hideable` is set prior to layout (whereas `state` - once view is actually laid out)
- `peekHeight` is set prior to layout as well
- `settleToStatePendingLayout` awaits parent being laid out, however `onLayoutChild` could pass several times affecting `child`'s `mTop`
- `onLayoutChild` affect `child`'s `mTop` and startSettlingAnimation either won't animate or animate incorrectly

**Android API version:** any

**Material Library version:** 1.2.1

**Device:** any

**Comment by emakar** [comment]
ping?

**Comment by headsvk** [comment]
I just came across this issue and it looks really bad when it goes from hidden to collapsed through the expanded state. Any workaround?

Also the runnable in `BottomSheetBehavior.settleToStatePendingLayout()` throws an exception if you call `setHideable(false)` before the runnable is executed with a saved `STATE_HIDDEN`. The previous runnable should be removed when a new state is set.

**Comment by paulfthomas** [comment]
We do unfortunately have race condition issues in `BottomSheetBehavior` and we're looking into them (btw the exception mentioned in https://github.com/material-components/material-components-android/issues/1729#issuecomment-801880373 should be gone).

I haven't been able to reproduce this specific issue though with the latest code, just so I understand, the animation is broken even after calling `setHideable(false)` while the sheet has settled to `STATE_HIDDEN`?

This code works fine for me:
```
bottomSheetBehavior.setHideable(true);
bottomSheetBehavior.setState(BottomSheetBehavior.STATE_HIDDEN);
postDelayed(() -> bottomSheetBehavior.setHideable(false), 500);
```

**Comment by richardortiz84** [comment]
The issue mentioned still exists today.

> This code works fine for me:
> 
> ```
> bottomSheetBehavior.setHideable(true);
> bottomSheetBehavior.setState(BottomSheetBehavior.STATE_HIDDEN);
> postDelayed(() -> bottomSheetBehavior.setHideable(false), 500);
> ```

The logic here is backwards, you are setting the bottom sheet to be hideable, hiding it, then setting it back to not hideable, which will make it reappear. The desired behaviour is that the sheet starts hidden, on condition it shows in a collapsed state (animating from the bottom), and when shown it is set back to not be hideable. Looking at your code example I was able to get the desired effect with the following.

```
        if (condition to be hidden is true) {
            bottomSheetBehavior.isHideable = true
            bottomSheetBehavior.state = STATE_HIDDEN
        } else {
            bottomSheetBehavior.isHideable = true
            if (bottomSheetBehavior.state == STATE_HIDDEN) {
                bottomSheetBehavior.state = STATE_COLLAPSED // show it, if it wasn't showing before
            }
            postDelayed({ bottomSheetBehavior.isHideable = false }, 500)
        }
```
