### ISSUE TITLE
[MaterialTimePicker] Crash in Material Button okButton

### ISSUE THREAD

**Issue by jalalkun** [material-components/material-components-android#1735]
**Description:** i'm try use MaterialTimePicker and follow from this [stackoverflow](https://stackoverflow.com/a/62884789/6279574) 

my material version is 1.3.0-alpha02

but i got this crash

`java.lang.ClassCastException: androidx.appcompat.widget.AppCompatButton cannot be cast to com.google.android.material.button.MaterialButton
        at com.google.android.material.timepicker.MaterialTimePicker.onCreateView(MaterialTimePicker.java:194)`

**Android API version:** Android API 29

**Material Library version:** Material Android Library version you are using here (1.3.0-alpha02)

**Device:** Device on which the bug was Samsung A50s

**Comment by gabrielemariotti** [comment]
Are you using a Bridge theme?

**Comment by jalalkun** [comment]
> 
> 
> Are you using a Bridge theme?

this my style

```
<style name="AppTheme.NoActionBar" parent="Theme.MaterialComponents.DayNight.NoActionBar.Bridge">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="materialCalendarFullscreenTheme">@style/ThemeMaterialCalendar</item>
        <item name="colorSurface">#ffffff</item>
        <item name="colorOnSurface">#212121</item>
    </style>
```
my manifest

`        android:theme="@style/AppTheme.NoActionBar"
`

**Comment by Milszym** [comment]
@gabrielemariotti Do you know when we can expect a release with the fix for this crash?

**Comment by gabrielemariotti** [comment]
The PR is merged, I think the issue can be closed.
