### ISSUE TITLE
Failed to resolve: coordinatorlayout-1.1.0

### ISSUE THREAD

**Issue by miladsalimiiii** [material-components/material-components-android#1738]
**Description:** I work on a project in a system and its OK but when i import it in another system i faced with this error :

`Failed to resolve: coordinatorlayout-1.1.0`

**Expected behavior:** Gradle sync successful.

**Source code:**   
` classpath 'com.android.tools.build:gradle:4.0.1'`

`   implementation "androidx.coordinatorlayout:coordinatorlayout:1.1.0"`

**Material Library version:**` 'com.google.android.material:material:1.2.1'`

**Comment by kirill-grouchnikov** [comment]
Did you follow the instructions on how to add the correct repository at https://developer.android.com/studio/build/dependencies#google-maven ?

**Comment by drchen** [comment]
I'll close the issue since it actually not related to our library.
