### ISSUE TITLE
[Floating Action Button] Changing color programmatically with backgroundTintList is not working

### ISSUE THREAD

**Issue by franzandel** [material-components/material-components-android#1740]
**Description:** 
I tried to change FAB color programmatically with this code
`fabTest.backgroundTintList = ColorStateList.valueOf(toColor(R.color.mycolor))`
It is working well when I set it from xml with this code
`android:backgroundTint="@color/mycolor"`
But I need to change the color programmatically.

I even tried to change Extended FAB color programmatically with the exact same code as above and it is working well.

**Expected behavior:**
Setting FAB color programmatically works.

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:**
API 28

**Material Library version:**
1.3.0-alpha02 (I even tried with the latest stable version which is 1.2.1 and it is still not working)

**Device:**
Google Pixel

**Comment by gabrielemariotti** [comment]
Tried without issues with `1.2.1` and latest `1.3.0`:

`fab.backgroundTintList = AppCompatResources.getColorStateList(this, R.color.xxxx)`

where xxxx is a selector like:

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:color="....." android:state_enabled="true"/>
  <item android:alpha="0.12" android:color="...."/>
</selector>
```
What is your issue?

Just a note:
>I even tried to change Extended FAB color programmatically with the exact same code as above and it is working well.

The` ExtendedFloatingActionButton` extends a `MaterialButton` and not a` FloatingActionButton`. They are different.

**Comment by franzandel** [comment]
Hi Gabriele,

Thanks for your information. Unfortunately, I tried with your code and it is not changing my fab background color :(

My issue is I need to change the fab background color programmatically
But, it doesn't behave correctly.

<img width="53" alt="Screen Shot 2020-09-18 at 18 50 12" src="https://user-images.githubusercontent.com/46681812/93594373-e7c9b280-f9df-11ea-9343-e73c10f8a8b2.png">

E.g.
I need to change this FAB background color from Black to Blue, but I need to do it programmatically.

**Comment by matpag** [comment]
If you have a single color and not a `ColorStateList` have you tried with this?

`fabTest. backgroundColor = ContextCompat.getColor(this, R.color.mycolor)`

**Comment by franzandel** [comment]
Hi matpag,

I have tried that too, and still no luck.
`fabTest.setBackgroundColor(ContextCompat.getColor(context, R.color.myColor))`

**Comment by matpag** [comment]
I suggest you to create a new fresh project with material theme and the FAB only, to test the various method we have suggested.
If the problem is still there after this, upload the fresh project on github and put the link here

**Comment by franzandel** [comment]
Hi matpag,

I followed your suggestion and found something here.

I created a test project [here](https://github.com/franzandel/FABTester)
I added material dependencies only there.
After several tests, I found out that 

1. `setBackgroundColor` is not working
I used this code, `fabTest.setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary))`.
So, in the end I used code which was suggested by Gabriele and it is working.
`fabTest.backgroundTintList = AppCompatResources.getColorStateList(this, android.R.color.black)`
`fabTest.backgroundTintList = AppCompatResources.getColorStateList(this, R.color.fab_selector)`
Both works.

2. `android:backgroundTint` in XML is the culprit
if I specify `android:backgroundTint` in XML then wanted to change color programmatically with 
`fabTest.backgroundTintList = AppCompatResources.getColorStateList(this, android.R.color.black)`
FAB background color won't change. But if I take out `android:backgroundTint` in XML, then changing color programmatically works.

So, I solve this by not specifying `android:backgroundTint` in XML and set the initial color programmatically.

I'm thinking of this as a bug because normally we can set initial color in XML. Please have a look at my newly created test project.

**Comment by matpag** [comment]
Have you tried using `app:backgroundTint` instead?

**Comment by franzandel** [comment]
Wow that worked.

**Comment by lonewolf73** [comment]
I am using fab over a Fragment FrameLayout in an app with `compileSdkVersion 33` , `targetSdkVersion 33` , `implementation 'androidx.appcompat:appcompat:1.5.1'` , plus I settled last version of Material component `implementation 'com.google.android.material:material:1.7.0'` , and in fragment xml I settled as :

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fr_myfragment"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

<com.google.android.material.floatingactionbutton.FloatingActionButton
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/fab"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom|end"
    android:layout_margin="16dp"
    app:srcCompat="@android:drawable/ic_popup_sync"
    app:tint="@color/white"
    app:backgroundTint="@color/fab_enabled"/>

</FrameLayout>
```

and in code I tried various ways, as you can see on commented code lines, but seems fab doesn't change background color as disabled even the state corresponds as disabled in debugging :

```
FloatingActionButton fab = (FloatingActionButton) view.findViewById(R.id.fab);
fab.setOnClickListener(new View.OnClickListener() {
	@Override
	public void onClick(View view) {
		fab.setEnabled(false);
		//fab.setElevation(0);
		//fab.setVisibility(view.GONE);
		//fab.hide();
		//fab.getBackground().set(getContext().getColor(R.color.fab_disabled));
		//fab.setBackgroundTintList(ColorStateList.valueOf(getContext().getColor(R.color.fab_disabled)));
		fab.setBackgroundColor( getContext().getColor(R.color.fab_disabled) );
		//fab.getBackground().mutate().setTint(getContext().getColor(R.color.fab_disabled));
		//fab.setVisibility(View.GONE);
		//fab.setCompatElevation(0);
```

I tried also to use a selector :

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/fab_enabled" android:state_enabled="true"/>
    <item android:color="@color/fab_disabled"/>
</selector>
```

but while debugging I see in Debugger the attribute `mColor` before to call `setBackgroundTintList` method it contained value `-8934372` which should correspond to enabled state color and after called `setBackgroundTintList` it was `-2763307` so that should mean it has changed the color but on the interface it didn't changed visually.... does it maybe depend to this latest SDK version that doesn't execute correct behavior on interface? Or do you have some alternative suggestion? Thanks!!!
