### ISSUE TITLE
[TextInputLayout] TextInputLayout with TextInputEditText drastically slowing down inflation.

### ISSUE THREAD

**Issue by amethystant** [material-components/material-components-android#1745]
**Description:** When inflating a layout, the presence of a TextInputLayout makes the inflation noticably slower. It's enough to add two TILs to a layout to start noticing a lag on my device (nokia 7.1, which is not high-end but not the worst phone either). It happens even when I put them in a simple linearlayout with no other views. On the other hand, if I inflate a layout with even 10 EditTexts, there is no lag whatsoever.

You can reproduce it on this basic sample (the dashboard fragment contains a few TILs and the notifications one contains normal EditTexts): https://drive.google.com/file/d/1DwvxzHM74TChIJGuttkRF6SRPcb8fEGd/view?usp=sharing

Here is a screenrecord using the sample I provided. First I navigate to the fragment with basic EditTexts and there is no lag, then I navigate to the one with TILs and there's the lag. It might not look that severe, but in a layout with other widgets the inflation times add up and it's enough to have a single TIL to get a bad UX.
https://drive.google.com/file/d/12P-XErDnZjSuhIwSqV6f9ydzYHQGUDZU/view?usp=sharing 

previously filed at https://issuetracker.google.com/issues/168869410 , was told to refile here

**Expected behavior:** TextInputLayout should inflate much faster, at least so that it doesn't cause any lags in fragment transitions when you have a few of them in your layout

**Source code:** https://drive.google.com/file/d/1DwvxzHM74TChIJGuttkRF6SRPcb8fEGd/view?usp=sharing

**Android API version:** Tested with API 29

**Material Library version:** 1.3.0-alpha02

**Device:** reproduced on Nokia 7.1 with Android 10 (physical device), and a virtual Pixel 3 XL with A10

**Comment by slavonnet** [comment]
Ohhh.... Wre full rework TextInputLayout in some case
1. All set text use futuretextset
2. Images of icon are atatic
3. Elements innflates in background and igone state. Change ibGroupVisibilityChanged
4. TextInputLayout init as FrameLayoit. All other layouts adds only if visible becouse need less three for speed.

PS. Change NavigationView to gone after its moved from screen also give big speed up! ;)

**Comment by sissergio** [comment]
I'm experiencing the same performance issue. Inflation takes too long, I'm using three TILs with AutoCompleteTextView and two TLIs with TextInputEditText and it takes 2 secs approx. to inflate. This cause a bad user experience and fragment transitions cannot be seen due to this lag.

**Comment by aeroxavier** [comment]
I'm also experiencing the same issue. Inflation takes too long and it causes lag in switching between fragments

**Comment by farfromrefug** [comment]
I am experiencing the same thing. Could we have some feedback from the dev team?

**Comment by Berki2021** [comment]
TextInputLayout is still slow as hell. Putting One TextInputLaylout in Combination with TextInputEdittext takes me about 80ms, which is very noticable..

**Comment by luisventura** [comment]
still experimenting this issue as well. tried removing all textinputlayout and it inflated much faster

**Comment by yamin8000** [comment]
I tried micro-optimizing different parts of the app until using profiler I found out TextInputLayout inflation is one of the bottlenecks! I don't understand why inflation of such thing could be that slow.

**Comment by slavonnet** [comment]
@yamin8000 try my fix

**Comment by yamin8000** [comment]
> 
> 
> @yamin8000 try my fix

Where's your fix?

**Comment by agent10** [comment]
Have the same experience. I use several TILs in BottomSheetDialog and opening this dialog is slow..

**Comment by leticiarossi** [comment]
We've made some changes to improve the inflate/measure performance time in https://github.com/material-components/material-components-android/commit/26d862bc5433eb50ba0875e136ff937d4e5ae617
