### ISSUE TITLE
[TextInputLayout] can't apply customtypeface 

### ISSUE THREAD

**Issue by mashazavolnyuk** [material-components/material-components-android#1751]
class AppTextInputLayout @JvmOverloads constructor (context: Context,attrs: AttributeSet?,defStyleAttr: 
Int =R.attr.textInputStyle) : TextInputLayout (context, attrs, defStyleAttr)  {
        init {  typeface = ResourcesCompat.getFont(context, R.font.name_font)  }
}

I want to apple custom typeface. I didn't see any results and can't apply bold text style. Why? I don't understand how to apply custom font to label TextInputLayout. Please provide actual example. 

**Android API version:** Android 10

**Material Library version:** 1.2.1

**Device:** xiaomi a3

**Comment by drchen** [comment]
You will need to override text appearance attributes in the TextInput style you are using. 

Please refer: https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md
