### ISSUE TITLE
[TextInputEditText] When using EditText in recycler view, focus doesn't behave as expected

### ISSUE THREAD

**Issue by simonsickle** [material-components/material-components-android#1755]
**Description:** An empty edit text is not focusable at all when a user clicks on it. Further, when the user clicks the view the keyboard gains pseudo focus and will accept input into the edit text without any cursor showing. When the user clicks on the view with text inside it, focus will be gained and cursor will show. If the user deletes all contents, focus is lost.  Also, when the keyboard shows, focus is lost even if text is in the view requiring 2 clicks by the user.

**Expected behavior:** Focus should be gained and kept when a user clicks on an edit text, until keyboard dismissed or focus cleared. Further, edit text should be focusable when contents are empty.

**Source code:** https://github.com/simonsickle/android_material_TextInput_focus_bug/tree/main

**Android API version:** 29,30 (tested, might be more/all)

**Material Library version:** 1.2.1

**Device:** Pixel 4 Simulator, Note 10 on android 10

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by simonsickle** [comment]
Aha! This appears to be a bug with constraint layout, perhaps. When my `TextInputLayout` is set to the following constraints and width, the focus is not retained possibly due to a re-measure?

```xml
android:layout_width="0dp"
android:layout_height="wrap_content"
app:layout_constraintEnd_toEndOf="parent"
app:layout_constraintStart_toStartOf="parent"
```

However, if I remove the constraints and set the width to match the parent, focus works!

```xml
android:layout_width="match_parent"
```


So, if you are suffering from this issue this is the workaround... If you do not want the entire width, I am not sure how to handle this but it works for us as we will just change our recycler's width. I would still like someone on the components team to look and give feedback as well so I am leaving the issue open.

**Comment by francisnovotny** [comment]
It seems to be same bug as described in issue 1730 [github.com/material-components/material-components-android/issues/1730](https://github.com/material-components/material-components-android/issues/1730)

**Comment by RuiRoque** [comment]
This also happens with "com.google.android.material:material:1.4.0-alpha01" in API 30.

In my case this forces the adapter to invoke the 'onBindViewHolder' in the adapter for all visible items in the Recycler View, which has side effects on the entire view.

The workaround doesn't work in my case. I still lose focus. And each time I try to regain focus on the TextInput, that focus is lost, the keyboard flashes for an instant while the onBindViewHolder is invoked, rebuilding the entire view.

**Comment by simonsickle** [comment]
This turned out to be a constraint layout bug in my case, also. Closing this bug as it wasn't actually with this library
