### ISSUE TITLE
[MaterialCheckBox] Indeterminate state

### ISSUE THREAD

**Issue by Anigif** [material-components/material-components-android#1762]
**What?**
The indeterminate state is mentioned as a fetaure both in the [common component documentation](https://material.io/components/selection-controls#checkboxes) and in the [specific Android documentation](https://material.io/develop/android/components/checkboxes), but it's not mentioned in any way how to actually use it. I tried looking in the source code and documentation for MaterialCheckBox, but it does not seem to be implemented anywhere.

**Why?**
It is quite confusing that it's stated in the Android app but not possible to use with the official library. So far I've been usin a 3rd party library, [Tri-State-Checkbox](https://github.com/sephiroth74/Tri-State-Checkbox).

**How?**
A simple solution could be to just add an extra boolean property representing if the the checkbox is indeterminate or not. This is how it looks like it's done in both the web and flutter implementation.

**Comment by gabrielemariotti** [comment]
Duplicate of #857

**Comment by Anigif** [comment]
@gabrielemariotti True, that wasn't too easy to find - thanks. Closing this issue.
