### ISSUE TITLE
Manifest merger failed !!

### ISSUE THREAD

**Issue by gaiththewolf** [material-components/material-components-android#177]
i tried implementing this library but the same error every time :(
i tried the guide steps but the same error.

the error message : 

```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-alpha3] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0-beta01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.
```

![alt text](https://image.ibb.co/iCmx1y/material_io.png)

any solution please !
thanks

**Comment by gaiththewolf** [comment]
it's working after removing : 

com.android.support:appcompt-v7
com.android.support.constraint:constraint-layout

:+1:

**Comment by amitkr936** [comment]
Compilation failed; see the compiler error output for details.


the above Error Occurs when I run the app

**Comment by zoro238** [comment]
same erro
Compilation failed; see the compiler error output for details.
