### ISSUE TITLE
[MaterialTimePicker] Not visible parts of a time picker.

### ISSUE THREAD

**Issue by Milszym** [material-components/material-components-android#1774]
**Description:** Hey, I have an issue with the newest **alpha03** release. When I open a time picker it looks like on the attached image. The selected part of time (either hour or minute) is not visible enough for the user. Odd hours in a CLOCK_24 format are not visible as well.

<img width="448" alt="Screenshot 2020-10-05 at 10 33 12" src="https://user-images.githubusercontent.com/12632186/95058494-e8f52200-06f7-11eb-8967-2fcac8d2ff76.png">

**Expected behavior:** I would expect more visible parts of a time picker. Selected state of hour and minute should be more prominent to the user. I would also expect that 24 hour format of the clock will have either more prominent odd hours or have a separate "circle" inside of a clock with hours from 12 to 24 like on a default Android time picker.

**Source code:** 
Picker initialization:
```
val materialPicker = MaterialTimePicker.Builder()
            .setHour(12)
            .setMinute(0)
            .setInputMode(MaterialTimePicker.INPUT_MODE_CLOCK)
            .setTimeFormat(TimeFormat.CLOCK_24H)
            .build()
        materialPicker.addOnPositiveButtonClickListener {
            onTimePicked(materialPicker.hour, materialPicker.minute)
        }
        materialPicker.show(parentFragmentManager, null)
```

Style for the activity:
```
    <style name="DialogActivity" parent="Theme.MaterialComponents.Light.Dialog.Bridge">
        <item name="windowNoTitle">true</item>
        <item name="android:windowBackground">#ffffff</item>
        <item name="materialTimePickerTheme">
            @style/ThemeOverlay.MaterialComponents.Light
        </item>
    </style>
```

**Android API version:** Android 10 (SDK 29), also tested on Android Emulator with Android 5.1.1 (SDK 22)

**Material Library version:** Material Android Library version **1.3.0-alpha03**

**Device:** Samsung Tab A 10,1 2019 (Android 10, SDK 29)

**Comment by ymarian** [comment]
Hi please set 

`<item name="colorPrimary">@color/...</item>` All the invisible items use that.

**Comment by Milszym** [comment]
@ymarian thanks, it helped 👍
