### ISSUE TITLE
[TabLayout] TabLayout's wrap_content coerses to hardcoded values

### ISSUE THREAD

**Issue by mateuszkwiecinski** [material-components/material-components-android#1785]
**Description:** When using TabLayout tabs with custom views I'd like TabLayout to respect my custom view's height not to limit it to hardcoded 48dp. 

**Expected behavior:** Assuming my custom view measured takes 150dp the TabLayout respects that and fully displays it.

**Source code:** 
```
<TabLayout
   id="@+id/tabLayout
  android:layout_width="match_parent"
   android:layout_height="wrap_content"/>
```
\+ then
```
tabLayout.addTab(tabLayout.newTab(myCustomViewThatHas150dp))
```
If needed I can provide separate repro project

**Android API version:** All

**Material Library version:** 1.2.1

**Device:** Android Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by hunterstich** [comment]
Hey @mateuszkwiecinski,

If you could provide the separate repro project you mentioned, that would be amazing! 

Thanks for reporting.

**Comment by mateuszkwiecinski** [comment]
Huh, I'm not able to reproduce the issue anymore 🤔 My suspicion is it was related to usage of `ConstraintLayout` which sometimes seem to block layout passes for its children. 
I'll reopen the issue if I'm able to provide a working repro project. Thanks for reply and sorry for the confusion
