### ISSUE TITLE
[BottomSheetBehavior.BottomSheetCallback] - never reports reaching `STATE_HIDDEN` when set in code

### ISSUE THREAD

**Issue by chrisahill1** [material-components/material-components-android#1789]
I have a simple persistent bottom sheet design that uses a `FragmentContainerView` to swap the contents inside a bottom sheet. When the bottom sheet is already expanded with another fragment loaded and a new fragment needs to be swapped into the bottom sheet. The design is to animate the bottom sheet to hidden, swap the fragments, then animate the bottom sheet back to expanded. However, I noticed that when the state of bottom sheet is set to hidden `bottomSheetBehavior.state = BottomSheetBehavior.STATE_HIDDEN` the callback reports the state changed of `STATE_SETTLING` when the animation starts, but when the bottom sheet finishes animating the state changed callback never reports `STATE_HIDDEN`

XML
```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

    ... other UI content ...

    <androidx.fragment.app.FragmentContainerView
        android:id="@+id/bottom_sheet_container_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:behavior_peekHeight="60dp"
        app:behavior_hideable="true"
        app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

Kotlin
```kotlin
private fun swapBottomSheet(fragment: Fragment) {
    val bottomSheetCallback = object : BottomSheetBehavior.BottomSheetCallback() {
        override fun onStateChanged(bottomSheet: View, newState: Int) {
            Log.i("BottomSheetBehavior.state","$newState")
            when (newState) {
                BottomSheetBehavior.STATE_HIDDEN -> {
                    bottomSheetFragment.showInBottomSheet(fragment)
                    bottomSheetBehavior.state = BottomSheetBehavior.STATE_HALF_EXPANDED
                    bottomSheetBehavior.removeBottomSheetCallback(this)
                }
            }
        }

        override fun onSlide(bottomSheet: View, slideOffset: Float) {

        }
    }
    bottomSheetBehavior.addBottomSheetCallback(bottomSheetCallback)
    bottomSheetBehavior.state = BottomSheetBehavior.STATE_HIDDEN
}
```

Gradle
```
implementation "com.google.android.material:material:1.3.0-alpha03"
```

**Comment by hunterstich** [comment]
Hey @chrisahill1,

Thanks for reporting! I know you've posted the majority of the code, but would you mind putting up a sample that reproduces this? It really helps us debug and fix issues more quickly so we don't have to spin up new projects for every issue. 

Thanks!

**Comment by chrisahill1** [comment]
@hunterstich sure, I'll cleanup my sample and push it to a public github repository this weekend and link it here.

**Comment by chrisahill1** [comment]
@hunterstich Made a simplified sample and the bug does not show up in the simplified sample, closing issue.

**Comment by hunterstich** [comment]
Cool. Thanks for taking the time to make a sample @chrisahill1. I like your pastel BottomSheet colors 👌
