### ISSUE TITLE
[MaterialShapeDrawable] Does not override getAlpha()

### ISSUE THREAD

**Issue by andrew8er** [material-components/material-components-android#1796]
**Description:** `MaterialShapeDrawable` does not override `getAlpha()`, so it will always report `255` regardless of its actual state. This is especially a problem with animations, where an `ObjectAnimator` cannot correctly determine the current alpha value.

**Expected behavior:** `MaterialShapeDrawable` should override `getAlpha()` to return `drawableState.alpha`

**Android API version:** 29

**Material Library version:** 1.3.0-alpha03

**Device:** Pixel 3a

**Comment by pekingme** [comment]
Closed in PR https://github.com/material-components/material-components-android/pull/2479
