### ISSUE TITLE
Incorrect Test Task in Documentation

### ISSUE THREAD

**Issue by commonsguy** [material-components/material-components-android#18]
[The documentation](https://github.com/material-components/material-components-android#running-tests) states that `androidConnectedTest` is the Gradle task for instrumentation tests. When I run it, Gradle says that there is no such task, and indeed I cannot find one with that name:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'androidConnectedTest' not found in root project 'material-components-android'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

There is a `connectedAndroidTest` task, in addition to the standard Android `connectedCheck` task. Both seem to run the instrumentation tests. I assume that one of these is the proper task.

**Comment by tec27** [comment]
Thanks for catching that!
