### ISSUE TITLE
When I use TextInputLayout (whose hintEnabled is false and style is OutLinedBox ), it seems to be clipped

### ISSUE THREAD

**Issue by ung8023** [material-components/material-components-android#180]
When I use TextInputLayout (whose hintEnabled is false and style is OutLinedBox ), it seems to be clipped

### Requirement
I want TextInputLayout's height is same as When it's hintEnabled is true, but don't show the lable(hint) on TextInputLayout, and the hint be shown in EditText

### code in xml
```
<android.support.design.widget.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:hintEnabled="false"
        >
        <android.support.design.widget.TextInputEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="12312312312"
            />
    </android.support.design.widget.TextInputLayout>
```

### result

![2018-07-31 8 47 44](https://user-images.githubusercontent.com/12079626/43431027-8e5dac54-949e-11e8-854d-b1988dfc0d2c.png)

it seems that the Input's bound clipped

### result I want
![2018-07-31 8 49 32](https://user-images.githubusercontent.com/12079626/43431046-abdfdee6-949e-11e8-9e02-7116a6e8b4f7.png)

**Comment by amiyo-biswas** [comment]
Read https://material.io/develop/android/components/text-input-layout/

**Comment by ung8023** [comment]
@amiyo-biswas it doesn't work, I had already followed it

**Comment by nasahapps** [comment]
Looking at the source code, the layout adds additional top margin if `hintEnabled` is `true`, else it completely ignores adding any top margin.

Don't know why they coded it like that, the top edge of the view is still there regardless if the hint is enabled or not.

**Comment by Cherubyx** [comment]
+1 Having this issue as well.

**Comment by WaideShery** [comment]
In my case, if set hint for TextInputEditText programmatically then floating label not showing.

**Comment by ldjcmu** [comment]
This issue is being looked at with  https://issuetracker.google.com/issues/111959880

**Comment by abhishekBansal** [comment]
Also error text looses its top margin int his scenario

**Comment by ikim24** [comment]
Closing this issue, please follow https://issuetracker.google.com/issues/111959880 instead.

**Comment by bhaveshaks** [comment]
@ung8023 do you have found any solution for this problem?

**Comment by manideepl** [comment]
> [Looking at the source code](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/TextInputLayout.java#L1268), the layout adds additional top margin if `hintEnabled` is `true`, else it completely ignores adding any top margin.
> 
> Don't know why they coded it like that, the top edge of the view is still there regardless if the hint is enabled or not. If that method (and the methods that call that method) weren't private, it'd be a simple fix to just ignore checking if `hintEnabled` is true or not, but those methods being private complicates things for us end-users.

You saved my life! 4 years+, still wonder why Android development has to be this hard!

**Comment by AtulSalgaonkar** [comment]
if you have used app:hintEnabled="false" then also set android:paddingTop="8dp" and boom top hint space is gone, this worked for me hope this works for you too

**Comment by yashovardhan99** [comment]
> if you have used app:hintEnabled="false" then also set android:paddingTop="8dp" in EditText and boom top hint space is gone, this worked for me hope this works for you too

Wow thank you so much!
