### ISSUE TITLE
Toolbar - CircularReveal: background is black while animating

### ISSUE THREAD

**Issue by rustamsmax** [material-components/material-components-android#1800]
**Description:** I'm having issue with reveal animation on dark theme

**Expected behavior:**Dark theme bug: https://t.me/UzDroidDevelopers/39584 and light theme normal: https://t.me/UzDroidDevelopers/39585

**Source code:**
<img width="642" alt="Screen Shot 2020-10-16 at 02 06 50" src="https://user-images.githubusercontent.com/36570577/96186040-47ba6700-0f54-11eb-8828-189766fa8846.png">

**Android API version:** Android 10

**Material Library version:**  1.2.1

**Device:** Samsung S10

**Comment by rustamsmax** [comment]
When I override design_dark_default_color_surface color to toolbar color (primary color) it was fixed
But it is not a solution.

**Comment by hunterstich** [comment]
Hey @rustamsmax,

Are you able to post a sample that reproduces this?

**Comment by rustamsmax** [comment]
https://gist.github.com/rustamsmax/1e2bcad8a04e579eda6824c440329562

**Comment by rustamsmax** [comment]
When I override surfaceColor of the dark theme to toolbar color(primary color) the bug is fixed.
But the surface color is used in other places too. For example, cardview, recylceview. This fix affect
 these views too which is not desired solution

**Comment by rustamsmax** [comment]
Here you can see similar issue https://stackoverflow.com/questions/44748155/circular-reveal-shows-black-background
I tried this solution (setting clipChildren property) too but it didn't help

**Comment by hunterstich** [comment]
Hmm. 

The two possible suggestions I have would be 

A) 
This might have something to do with dark theme elevation overlays. If you're setting your toolbar background to be `android.R.attr.colorBackground` during the animation, this might not apply an elevation overlay that is used to "lightened" the color of elevated components like `Card` and `Toolbar` in dark theme.

What if you instead did something like:
```
val color = ElevationOverlayProvider(context)
            .compositeOverlayWithThemeSurfaceColorIfNeeded(ViewCompat.getElevation(toolbar))
toolbar.setBackgroundColor(color)
```

B)
If you can override `surfaceColor` to get what you need, could you create a theme overlay and set it as your toolbar's style? Your light theme overlay could basically do nothing and your dark theme overlay could override `surfaceColor`?

Thoughts?

If you want to post a full repository that I can run and debug myself, I can maybe help look into this further.

**Comment by rustamsmax** [comment]
Hi any news?

**Comment by hunterstich** [comment]
Hey @rustamsmax. Sorry for the delay and thanks for the sample.

I think what's happening is as you're revealing the `SearchView`, the `AppBarLayout` beneath your `RevealToolbar` is visible, which either doesn't have a background or has the incorrect background color. 

In your GitLab repo, adding `android:backgroundTint="?attr/colorPrimary"` to your `AppBarLayout` in `layout_toolbar_base.xml` works for me and gives the following result: 

<img src="https://user-images.githubusercontent.com/7459254/97014832-d6148700-1518-11eb-8e58-07de47fe5730.gif" width="250" />

**Comment by rustamsmax** [comment]
Hi thank you @hunterstich 
You saved my days . Thank you very much 🙈. Now it animates as expected

**Comment by hunterstich** [comment]
Glad that worked!
