### ISSUE TITLE
[Motion] MaterialContainerTransform crashes when used with Compose

### ISSUE THREAD

**Issue by ansman** [material-components/material-components-android#1801]
**Description:** 
`MaterialContainerTransform` draws the start view without it being attached which is not allowed with Compose views (https://issuetracker.google.com/issues/170316859)

It feels dangerous to draw views that are not attached, regardless of Compose. Instead perhaps the view could be added to the view overlay?

**Expected behavior:** `MaterialContainerTransform` should not crash when used with Compose.

**Source code:** 
To reproduce this simply create a view that contains a Compose view and use MaterialContainerTransform with this view as the start view.

**Android API version:** All

**Material Library version:** `1.3.0-alpha03`
**Compose version:** `1.0.0-alpha04`

**Comment by hunterstich** [comment]
Thanks Nick.

Seems like there's some more work to be done on the Compose side to decide if this is an issue on their side or ours. Or both...

I'll try to keep an eye on https://issuetracker.google.com/issues/170316859 and follow up when there's more info.

**Comment by hunterstich** [comment]
Hey @ansman, looks like https://issuetracker.google.com/issues/170316859 was fixed.

I'm going to close this, but if you test and find that it still crashes, please re-open!

Also, I'd be really curious to see a sample that mixes compose and container transforms. Have any more info about architecture or details on what you're working on that you'd be willing to share?

**Comment by ansman** [comment]
Yeah, I saw that too.

It might sound like we're doing something super fancy with compose and material motion but we're simply using regular fragment transitions with a fragment that contains a compose view.

**Comment by hunterstich** [comment]
Oh cool!
