### ISSUE TITLE
[Button] Warning when setting background programmatically

### ISSUE THREAD

**Issue by ansman** [material-components/material-components-android#1803]
**Is your feature request related to a problem? Please describe.**
I want to animate the size of the background for a Button without changing the Button's size. This is temporarily while showing a progress bar.

Since `View` will overwrite any bounds so set for the background I wrap the background in my own drawable that allows me to manually set the button background size.

While doing so I get a warning saying:
```plain
Do not set the background; MaterialButton manages its own background drawable.
```

It's unclear if this warning is still valid since MaterialButton seems to handle it just fine and it allows setting a custom background in XML.

**Describe the solution you'd like**
Ideally I would like some way to wrap the background without getting any behavior changes but since this is a pretty niche request it might not be something you want to consider.

At the very least I would like some clarification on setting custom backgrounds. If it's allowed then the warning should probably be removed.

**Describe alternatives you've considered**
None

**Additional context**
Material Version: `1.3.0-alpha03`

**Comment by gabrielemariotti** [comment]
Now you can set the `background` for the MaterialButton. However using it the `MaterialButton` doesn't use its own `MaterialShapeDrawable` for the background. This means that features like insets, shape appearance, stroke, elevation overlay... will be ignored.

Maybe the text of the warning could be improved.

**Comment by hunterstich** [comment]
Agreed that some sort of warning is helpful, but maybe an updated message could make things more clear
