### ISSUE TITLE
[AutoCompleteTextView] setOnItemSelectedListener listener never called 

### ISSUE THREAD

**Issue by OndrejMalek** [material-components/material-components-android#1804]
**Description:** When using as dropdown list, when setting listener with `android.widget.AutoCompleteTextView#setOnItemSelectedListener` , listener is newer called. It seems this is leftover or duplicate of `android.widget.AutoCompleteTextView#setOnItemClickListener` which works. 

**Expected behavior:** listener called when dropdown list item clicked as in `android.widget.AutoCompleteTextView#setOnItemClickListener`

**Android API version:** 29

**Material Library version:** 1.2.1 ,1.3.0-alpha03, current master 0afcb48f14a7af3db3712be44d7984c8d89e25fb 

**Device:** emulator Android 10.0

**Comment by OndrejMalek** [comment]
OK `setOnItemSelectedListener` is not duplicate. 
I would expect it to be called: 
`OnItemClickListener` - only on click/ only by user
`OnItemSelectedListener` - everytime and in `setListSelection` especialy

**Comment by henningBunk** [comment]
For me both listeners aren't working. On selection only the selected value is taken for the AutoCompleteTextView but no callbacks to the listeners.
