### ISSUE TITLE
[Snapshots] Snapshot builds haven't been been built since June

### ISSUE THREAD

**Issue by shekibobo** [material-components/material-components-android#1810]
**Description:** 

Snapshot builds haven't been built since June 19th, 2020 as far as I can tell based on the [all versions](https://github.com/material-components/material-components-android/packages/81484/versions) link provided in the documentation.

**Expected behavior:**

More recent/frequent snapshot builds available. Probably nightly?

**Source code:** 

N/A

**Android API version:** 

N/A

**Material Library version:** 

*-SNAPSHOT

**Device:** 

Any browser or consumer of a maven repository.

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by dsn5ft** [comment]
Thanks for reporting this. It should be fixed now, as of https://github.com/material-components/material-components-android/commit/bea697804d09a06b84ed7ef2e14394ff22df2e74.

**Comment by brunopiovan** [comment]
latest one is still from June 20
