### ISSUE TITLE
Tabindicator gradient drawable not working

### ISSUE THREAD

**Issue by nucleons** [material-components/material-components-android#1815]
This is my code 

**activity.xml**

<com.google.android.material.tabs.TabLayout
        android:layout_width="match_parent"
        android:layout_height="56dp"
        app:tabGravity="center"
        app:tabIndicator="@drawable/tabbar_indicator_gradient_blue"
        app:tabIndicatorFullWidth="true"
        app:tabIndicatorHeight="10dp"
        app:tabMode="fixed"
        android:id="@+id/tab"/>

**tabbar_indicator_gradient_blue.xml**

` <shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:endColor="#00b0eb"
        android:startColor="#0086b3"/>
    <corners android:topLeftRadius="3dp" android:topRightRadius="3dp"/>
</shape>`

 TabIndicator is not showing up the gradient colour.

**Comment by hunterstich** [comment]
Hey @nucleons ,

Can you add 
`app:tabIndicatorColor="@andorid:color/transparent"`
to your TabLayout and see if that solves the issue?

**Comment by adityabyjus** [comment]
Tried this no change in behaviour.

**Comment by nucleons** [comment]
Tried this, no change in behaviour

**Comment by dsn5ft** [comment]
@nucleons how about `app:tabIndicator="@null"` or `app:tabIndicator="@empty"`? Also, what version of the Material Android library are you using? I think we fixed this in https://github.com/material-components/material-components-android/commit/84fd465ceaac369f80dd1a8b82da142dba7f98a2 which is available in `1.3.0-alpha03`.

**Comment by nucleons** [comment]
@dsn5ft I need custom app:tabIndicator, if I set it to null that wont server my purpose. I need custom gradient colour tabindicator.

**Comment by dsn5ft** [comment]
@nucleons sorry I meant `app:tabIndicatorColor="@null"` or `app:tabIndicatorColor="@empty"` with using version `1.3.0-alpha03`.

**Comment by nucleons** [comment]
@dsn5ft 1.3.0-alpha03 fixes the issue. Thanks for your support:)
