### ISSUE TITLE
ProgressIndicator invisible in BottomSheetDialog

### ISSUE THREAD

**Issue by brunopiovan** [material-components/material-components-android#1816]
**Description:** If you add a ProgressIndicator to a BottomSheetDialog it will be hidden the second time you show the BottomSheetDialog.

**Expected behavior:** Keep it visible

**Material Library version:** >= 1.3.0-alpha02 (this issue is not present in 1.3.0-alpha01)

I believe this is related to https://github.com/material-components/material-components-android/issues/1662.

**Comment by pekingme** [comment]
Sorry for the late response, @brunopiovan. ProgressIndicator has been refactored to LinearProgressIndicator and CircularProgressIndicator recently with several fix related to visibility. I added one LinearProgressIndicator in the BottomSheetDemo in catalog. It shows every time. Could you please check with the latest snapshot version? Feel free to reopen the issue if the bug still persists. Thanks.
