### ISSUE TITLE
[TextInputLayout] Filled corner treatment doesn't cut box stroke

### ISSUE THREAD

**Issue by sedestrian** [material-components/material-components-android#1817]
When changing the shape of the bottom corners, the line under the text doesn't get changed as well

![photo_2020-10-23_10-42-18](https://user-images.githubusercontent.com/1345755/96976945-b7b08a80-151c-11eb-8843-2c7f28f23e7b.jpg)

I feel like the line shouldn't go outside the background

API version is 30

Library version is 1.2.1 but also on 1.3.0-alpha03

The bug is on Galaxy S20

**Comment by hunterstich** [comment]
Hey @sedestrian,

I'm not sure if this is something design wants to support. Let me ask them and get back to you

**Comment by hunterstich** [comment]
@sedestrian, design got back to me and said that the rounding of the bottom corners is not something we want to support for text fields.
