### ISSUE TITLE
Any documentation for all the themes' color definition?

### ISSUE THREAD

**Issue by jsun28** [material-components/material-components-android#1819]
This may not be a bug, just a question of mine, I am just curious about how those themes are composed. 

1. Is there any documentation or demo to showcase what colors those themes are using? 
Theme.MaterialComponents
Theme.MaterialComponents.NoActionBar
Theme.MaterialComponents.Light
Theme.MaterialComponents.Light.NoActionBar
Theme.MaterialComponents.Light.DarkActionBar
Theme.MaterialComponents.DayNight
Theme.MaterialComponents.DayNight.NoActionBar
Theme.MaterialComponents.DayNight.DarkActionBar

2. I trace down the `Theme.MaterialComponents.DayNight.NoActionBar` in your repo, try to figure out what colors it is using, looks like it inherits from `Base.V14.Theme.MaterialComponents`, in which the primary color is #BA86FC, but it turns out that the primary color in `Theme.MaterialComponents.DayNight.NoActionBar` is #BA86FC

**Comment by gabrielemariotti** [comment]
@jsun28  You can check the [doc](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md)

**Comment by hunterstich** [comment]
@jsun28 

Thanks for the question. @gabrielemariotti's link to our [color theming doc](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md) should point you in the right direction. There's also additional information in our [getting-started theming](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#material-components-themes) section and our [dark theme documentation](https://github.com/material-components/material-components-android/blob/master/docs/theming/Dark.md).

Let me know if you have any specific questions I can help answer!
