### ISSUE TITLE
[TextInputEditText] not able to center hint and to keep input value moved to bottom

### ISSUE THREAD

**Issue by nikolasamardzija** [material-components/material-components-android#1823]
**Description:** 
On https://material.io/components/text-fields there is an interactive demo for Filled TextField.

**Expected behavior:**
Label hint is centered inside input field and when you click on it and enter some text, label moves up and text that you inputed is slightly below center(below where hint previously was)

Problem is that I am not able to reproduce this behaviour on Android as text that I input stays in the same position as a placeholder. 

Not centered hint and icon, but they should be
[![enter image description here][1]][1]

This is correct, as the label is moved up and password is below center line
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/VWPzf.png
  [2]: https://i.stack.imgur.com/7d14h.png
**Source code:**:
```        
   <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/et_password"
            style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox.Dense"
            android:layout_width="0dp"
            android:layout_height="65dp"
            android:layout_marginTop="16dp"
            android:background="@drawable/edittext_bg"
            android:hint="@string/password"
            app:boxStrokeWidth="1dp"
            app:passwordToggleEnabled="true">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/tiet_password"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="#00000000"
                android:inputType="textPassword"
                android:textSize="17sp" />
        </com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** All, tested on API 27

**Material Library version:** All versions including 1.3.0-alpha03

**Device:** All devices, tested on Pixel 3a

**StackOverflow Question:** https://stackoverflow.com/questions/64499266/material-textinputedittext-not-able-to-center-hint-and-to-keep-input-value-moved

**Comment by hunterstich** [comment]
Hey @nikolasamardzija,

I would assume this has something to do with either your `TextInputLayout`s `andoird:background` drawable and/or `android:layout_height`. 

I don't think you should need either of these if you just want a white background and a larger height for your text field. Could you try:

```
 <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/et_password"
            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            android:hint="@string/password"
            app:boxBackgroundColor="@android:color/white"
            app:boxStrokeWidth="1dp"
            app:passwordToggleEnabled="true">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/tiet_password"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:minHeight="65dp"
                android:inputType="textPassword"
                android:textSize="17sp" />
        </com.google.android.material.textfield.TextInputLayout>
```
 
The above removes the explicit height on `TextInputLayout` for `minHeight` in `TextInputEditText`, which will keep your hint text centered when unfocused. Also, this removes your `background` from `TextInputLayout` and replaces it with `app:boxBackgroundColor`.

Let me know how this works.

**Comment by nikolasamardzija** [comment]
Thanks, that helped together with an update of the library version
