### ISSUE TITLE
[Swipe to refresh] Docs: spinner no longer fades in while rotating

### ISSUE THREAD

**Issue by Poopooracoocoo** [material-components/material-components-android#1824]
**Description:** Docs: the circular spinner on a refresh indicator no longer fades in while rotating and 

**Expected behavior:** It now fades in when it reaches the point where when you let go, it'll refresh. 

**Source code:** um. idk? https://material.io/design/platform-guidance/android-swipe-to-refresh.html#behavior-placement

**Android API version:** 30

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

**Device:** Device on which the bug was encountered here

dude look. i came here from the material.io website. I clicked on the feedback button but I saw the typical Google feedback dialogue and realised that it just goes to a virtual dump and that no one looks at it. https://github.com/material-components/material-components is for "all common documentation for Material Components projects across the different platforms." oh and are there no compiled builds of the catalogue app? :( i may very well be wrong. i've just seen this behaviour in the android apps i use day to day :/

feel free to point me in the right direction for material.io doc issues as i'm lost.

**Comment by hunterstich** [comment]
Hey @Poopooracoocoo,

Are you talking about a video on the material.io site? Or are you talking about when using a `SwipeRefreshLayout` during development of an Android app?

**Comment by Poopooracoocoo** [comment]
sup @hunterstich 

I'm referring to this: 
![image](https://user-images.githubusercontent.com/51363864/97297279-e7a5b800-18a5-11eb-9e59-2014144c6610.png)

https://material.io/design/platform-guidance/android-swipe-to-refresh.html#behavior-placement

**Comment by hunterstich** [comment]
Oh okay,

It looks like the [demo video](https://kstatic.googleusercontent.com/files/327b57850a9283ed6ff7af86d242a34626e959e71fcc991fbcc15b360b527329e2f37a06e3d5a233ab15e7d8a998d1d9879393f3b6e29aca8d0f663210222d98) on material.io does exactly that.

As far as the Android component goes - `SwipeRefreshLayout` - that component is provided by AndroidX and is not in our library. It looks like the circular progress in that component doesn't fade in, but it does gradually appear as it grows to form a semi-circle. If you want this behavior changed to match the fading on material.io, you'd need to file a bug with AndroidX.

**Comment by Poopooracoocoo** [comment]
@hunterstich So let me get this straight.

So that description is in fact accurate because AndroidX's SwipeRefreshLayout still fades in _while_ rotating and that video is for AndroidX (I watched that really intently lol. I just assumed that you all replaced that old one). And there's no swipe to refresh control in Material Components?

How would I file a bug with AndroidX?

What do apps like Gmail use with their nice swipe to refresh spinner?

God, this is confusing. Sorry for being a total noob.

**Comment by hunterstich** [comment]
Not a problem! Glad you reached out with questions.

Gmail and other apps use the `androidx.swiperefreshlayout.widget.SwipeRefreshLayout` widget. 

If you're developing an Android app with a recycler view, you can wrap your `RecyclerView` in a `SwipeRefreshLayout` and you should get the swipe-to-refresh behavior out of the box. Something like:

```
  <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
    android:id="@+id/swipe_refresh_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.recyclerview.widget.RecyclerView
      android:id="@+id/recycler_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent" />

  </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>
```

should give you pretty much the same behavior apps like Gmail and Chrome have.

**Comment by Poopooracoocoo** [comment]
Thanks for being understanding :) 

If Gmail uses AndroidX's SwipeRefreshLayout and has the new style spinner (where it fades in when it reaches a point as opposed to fading in _while rotating_), then what's that material.io document and video about? You can see where I'm getting confused, right? :3

**Comment by hunterstich** [comment]
The material.io video is just a mockup, not an actual video of an implementation.

**Comment by Poopooracoocoo** [comment]
So the mockup video and documentation _are_ outdated/wrong then? argh.
