### ISSUE TITLE
[BottomAppBar] FloatingActionButton With Navigation Component

### ISSUE THREAD

**Issue by jsdeyro** [material-components/material-components-android#1826]
**Is your feature request related to a problem? Please describe.** 
I don't know if there is a way to implement a FloatingActionButton inside a bottomAppBar that can be use in navigation component like the menus.

**Describe the solution you'd like**
It is much better if the FloatingActionButton and expanded items of it can be added in the Navigation component. or Instead of using activity with bottomappbar with navigationview, add a possibility to use it as fragment for it use the navigation component. If this is already implemented, please let me know where to look.

**Describe alternatives you've considered**
For now I create a fragment that holds all floatingActionButton items just to use the navigation component to transfer from one fragment to another, but still it im able to make it work.

**Additional context**
![image](https://user-images.githubusercontent.com/66674372/97282490-aeefe980-1879-11eb-9a6e-c6dc1fafb5e0.png)

Also added a question in stackoverflow:
https://stackoverflow.com/questions/64551841/bottomappbar-navigationview-floatingactionbutton-navigation-component-kotl

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by hunterstich** [comment]
Hi @jsdeyro,

This is a feature request that we've heard from a few people. However, the BottomNavigationView with FAB support isn't a component/pattern that's included in the Material Design spec and we therefore can't add it as a standard component. 

Related https://github.com/material-components/material-components-android/issues/98

You could create something like this yourself using a custom bottom navigation, [shape theming](https://github.com/material-components/material-components-android/blob/master/docs/theming/Shape.md) and a FAB. 

Closing for now, but let me know if you have questions when creating your own implementation.

**Comment by hunterstich** [comment]
For your [StackOverflow question](https://stackoverflow.com/questions/64551841/bottomappbar-navigationview-floatingactionbutton-navigation-component-kotl), it looks like you need to create a [global action](https://developer.android.com/guide/navigation/navigation-global-action) for your FAB items instead of using an action tied to your HomeFragment.

**Comment by jsdeyro** [comment]
It's working now thanks, I used `this@NavigationActivity.findNavconrtoller.navigate()`

**Comment by jsdeyro** [comment]
Its working now thanks for the reply. I used `this@NavigationActivity.findNavconrtoller.navigate()`
