### ISSUE TITLE
[TextInputLayout]persian hint text not showing in api 17

### ISSUE THREAD

**Issue by mrzbn** [material-components/material-components-android#1833]

**Comment by mrzbn** [comment]
farsi(persian) hint text is not showing in api 17
![Screenshot_1603889173](https://user-images.githubusercontent.com/58802944/97437691-1751d000-1939-11eb-9d2a-d21e11eb45de.png)

**Comment by Pourqavam** [comment]
https://github.com/material-components/material-components-android/issues/1454

**Comment by drchen** [comment]
Closing this as a duplicate for better tracking.
