### ISSUE TITLE
Please add options: do not draw ticks if stepSize > 0.0f in BaseSlider.java

### ISSUE THREAD

**Issue by goodandrewsoft** [material-components/material-components-android#1835]
**Is your feature request related to a problem? Please describe.**
Always draws tick in BaseSlider.java  if stepSize > 0.0f

**Describe the solution you'd like**
Please add options: do not draw ticks if stepSize > 0.0f in BaseSlider.java

**Describe alternatives you've considered**
Via style attributes

**Additional context**

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by gabrielemariotti** [comment]
You can use[ `app:tickVisible`](https://github.com/material-components/material-components-android/pull/1545) to show/hide the tick in discrete slider.

It is available starting from `1.3.0-alpha03`

**Comment by dsn5ft** [comment]
See https://github.com/material-components/material-components-android/pull/1545 and https://github.com/material-components/material-components-android/commit/5fb796437291ce6b7d43b3beba13a42256db6eac.
