### ISSUE TITLE
[MaterialContainerTransform] OvershootInterpolator has no effect on container transform

### ISSUE THREAD

**Issue by jkarlsson** [material-components/material-components-android#1838]
**Description:** OvershootInterpolator has no effect on container transform

**Expected behavior:** When OvershootInterpolator is set on the container transform I would expect the view to grow slightly larger or smaller than the target and then shrink/grow to the target dimensions (depending on the transition direction of course).
However, setting an OvershootInterpolator seems to have no effect at all.

Reproduced in the catalog app on master 191a48bd8ab54ef9ba94449d4b473a53d45c32e0
By applying this small change:
```
diff --git a/catalog/java/io/material/catalog/transition/TransitionContainerTransformViewDemoFragment.java b/catalog/java/io/material/catalog/transition/TransitionContainerTransformViewDemoFragment.java
index 1a2b3f0e..42ceb049 100644
--- a/catalog/java/io/material/catalog/transition/TransitionContainerTransformViewDemoFragment.java
+++ b/catalog/java/io/material/catalog/transition/TransitionContainerTransformViewDemoFragment.java
@@ -28,6 +28,7 @@ import android.view.MenuInflater;
 import android.view.MenuItem;
 import android.view.View;
 import android.view.ViewGroup;
+import android.view.animation.OvershootInterpolator;
 import android.widget.FrameLayout;
 import androidx.annotation.IdRes;
 import androidx.annotation.NonNull;
@@ -151,6 +152,7 @@ public class TransitionContainerTransformViewDemoFragment extends DemoFragment
     transform.setScrimColor(Color.TRANSPARENT);
     transform.setDrawingViewId(root.getId());
     configurationHelper.configure(transform, entering);
+    transform.setInterpolator(new OvershootInterpolator());
     return transform;
   }
```

**Android API version:** Tested on API 29

**Material Library version:** 191a48bd8ab54ef9ba94449d4b473a53d45c32e0

**Device:** Google Pixel

**Comment by dsn5ft** [comment]
Hey @jkarlsson, thanks for reporting this. I'm looking into it.
