### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by TdevM** [material-components/material-components-android#184]
Can't install this by adding to build.gradle. 

Fails with `Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-rc01] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0-rc01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.
`

tried solution given above, still no luck.

**Comment by TdevM** [comment]
solved. sorry. thanks.

**Comment by TdevM** [comment]
solved. sorry. thanks.

**Comment by vcapra1** [comment]
How did you solve this?

**Comment by TdevM** [comment]
@vcapra1  if you are installing material design components by adding 
`    implementation 'com.google.android.material:material:1.0.0-beta01'
`

you should be removing all `com.android.support `dependencies 

You should not use the `com.android.support` and `com.google.android.material` dependencies in your app at the same time.

See #177 

See Getting started
[https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md](url)
