### ISSUE TITLE
[MaterialTextView] applies line height from appearance but doesn't apply firstBaselineToTopHeight & lastBaselineToBottomHeight

### ISSUE THREAD

**Issue by nic-bell** [material-components/material-components-android#1848]
**Description:** 
`MaterialTextView` supports the ability to read and apply line height from TextAppearance but it doesn't apply firstBaselineToTopHeight & lastBaselineToBottomHeight.

**Expected behavior:**
I noticed the height of my view was only `16dp` when I had a single line of text but `36dp` when I had two lines and plus `20dp` for each line after. After some debugging I noticed that `firstBaselineToTopHeight` and `lastBaselineToBottomHeight` are only ever applied if you use them as styles and `lineHeight` is the distance between two baselines so it does nothing if there is only a single line of text. 

When using the following code.

```xml
// Styles
<style name="MyApp.AppTheme" parent="Theme.MaterialComponents.DayNight">
  ..
  <item name="textAppearanceBody2">@style/TextAppearance.MyApp.Body2</item>
</style>

<style name="TextAppearance.MyApp.Body2" parent="TextAppearance.MaterialComponents.Body2">
  <item name="android:textColor">?colorOnBackground</item>
  <item name="android:textSize">14sp</item>
  <item name="lineHeight">20sp</item>
  <item name="firstBaselineToTopHeight">15sp</item>
  <item name="lastBaselineToBottomHeight">5sp</item>
</style>

// View
<com.google.android.material.textview.MaterialTextView
  android:textAppearance="?textAppearanceBody2"  .. />
```

The whole purpose of the `MaterialTextView` is to have more elegant looking text but it's pretty much useless unless that text is multi-line.

It should be fairly easy to apply `firstBaselineToTopHeight` and `lastBaselineToBottomHeight` as there is already logic to add the line height by reading it from the text appearance.

https://github.com/material-components/material-components-android/blob/f945a0649b9cddc13afafeb80df7218f1aa85ef8/lib/java/com/google/android/material/textview/MaterialTextView.java#L103

**Comment by drchen** [comment]
Hi given that `firstBaselineToTopHeight` and `lastBaselineToBottomHeight` are not part of standard text appearance attributes and Material typography system is not using them, I'm afraid that we will be very reluctant to add them. (We did add the support of `lineHeight` with text appearance but `lineHeight` is much more frequently used and we need to consider about the maintenance cost of adding more non-standard attributes.)

You can still use `firstBaselineToTopHeight` and `lastBaselineToBottomHeight` in your component style or by overriding `?attr/textViewStyle`. So I'll close this issue as won't do.
