### ISSUE TITLE
Uh...I am new here

### ISSUE THREAD

**Issue by zb2947244682** [material-components/material-components-android#185]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

too many details problems...
not easy to use
Is there any other good android Material Design UI Component Frame???...

**Comment by wcshi** [comment]
Hi zb2947244682 and welcome to MDC Android. Are there specific painpoints or suggestions for improvements you'd like to share with us?

**Comment by wcshi** [comment]
Closing this issue due to lack of details, please create new issues with details on specific problems or feature requests, thank you!
