### ISSUE TITLE
[MaterialDatePicker] Calender should show last selected date and month instead of current date and month.

### ISSUE THREAD

**Issue by asiimwedismas** [material-components/material-components-android#1850]
The calendar view shows the current month and not the date selection set by setSelection() IF you supply setSelection() with a time that is not in the current month.

               `MaterialDatePicker.Builder builder = MaterialDatePicker.Builder.datePicker();

                builder.setSelection(Objects.requireNonNull(mMyViewModel
                        .getLastSelectedDate()
                        .getValue())
                        .getTimeInMillis());

                MaterialDatePicker picker = builder.build();

                picker.show(getSupportFragmentManager(), TAG);`

![Very bad for user experience](https://user-images.githubusercontent.com/51087315/98015125-7cac3200-1e0d-11eb-989e-a32d09e74eab.png)
**Very bad for user experience**; Device date is Nov 3, 2020. Pass any date that is outside of the **current month**  to setSelection() and you get that (passed Oct 13, 2020). 🤷‍♂️

![Default expectation](https://user-images.githubusercontent.com/51087315/98015005-62725400-1e0d-11eb-8671-8474b88ee66a.png)
**Default expectation**. Make Calendar view in picker show the setSelection() date just like the picker header does.

**Comment by gabrielemariotti** [comment]
With `1.3.0-alpha03` this behavior should be changed with the PR #1651.
The selection value is used as the default `openAt`.

With the previous release you have to use the `openAt` in the `CalendarConstraints`.

**Comment by asiimwedismas** [comment]
Also include an action that lets a user select/jump to the current date if the currently displayed date is in a different month.
