### ISSUE TITLE
[MaterialButton] DrawableStart does not work

### ISSUE THREAD

**Issue by kymahi** [material-components/material-components-android#1851]
**Description:** [MaterialButton] android:drawableStart doesn't work. However, android:drawableLeft does work, but gives an RTL error.

**Expected behavior:** Drawable expected to be drawn at the start of the MaterialButton.

I'm aware of app:icon, but I feel like this should still work.

**Comment by VincentJoshuaET** [comment]
Why not use app:iconGravity?

**Comment by wcshi** [comment]
Thank you for your feedback, please use app:icon and app:iconGravity
