### ISSUE TITLE
Chip doesn't pass setTextSize call to ChipDrawable

### ISSUE THREAD

**Issue by s-ilnar** [material-components/material-components-android#1855]
Chip is created programmatically (in the code I tried to get rid of the trailing indentation)

```
fun createChip(): Chip {
    val chip = Chip(context)
    chip.text = "sgds vsdgty bsd df g"
    chip.setTextSize(TypedValue.COMPLEX_UNIT_SP, 10F)
    chip.chipBackgroundColor = Color.RED
    chip.setTextColor(Color.WHITE)
    chip.chipStartPadding = 0F
    chip.chipEndPadding = 0F
    chip.textStartPadding = 0F
    chip.textEndPadding = 0F
    chip.closeIconStartPadding = 0F
    chip.closeIconEndPadding = 0F
    return chip
}
```
here is the result (it's not clear where the indentation at the end comes from)

![k3fal 1](https://user-images.githubusercontent.com/8873972/98337487-be112d00-2019-11eb-8590-4b9306409c4a.png)

How do I make the same indentation?

**Comment by s-ilnar** [comment]
The reason is chip.setTextSize(TypedValue.COMPLEX_UNIT_SP, 10F)

**Comment by wcshi** [comment]
Could you please try setting the closeIconStartPadding and closeIconEndPadding to be 0 as well?

**Comment by s-ilnar** [comment]
> Не могли бы вы также установить для closeIconStartPadding и closeIconEndPadding значение 0?

I tried this, it didn't work for me!

**Comment by s-ilnar** [comment]
> Чип создается программно (в коде я пытался избавиться от конечного отступа)
> 
> ```
> fun createChip(): Chip {
>     val chip = Chip(context)
>     chip.text = "sgds vsdgty bsd df g"
>     chip.setTextSize(TypedValue.COMPLEX_UNIT_SP, 10F)
>     chip.chipBackgroundColor = Color.RED
>     chip.setTextColor(Color.WHITE)
>     chip.chipStartPadding = 0F
>     chip.chipEndPadding = 0F
>     chip.textStartPadding = 0F
>     chip.textEndPadding = 0F
>     return chip
> }
> ```
> 
> вот результат (непонятно откуда берется отступ в конце)
> 
> ![k3fal 1](https://user-images.githubusercontent.com/8873972/98337487-be112d00-2019-11eb-8590-4b9306409c4a.png)
> 
> Как сделать такой же отступ?

**Comment by wcshi** [comment]
What do you mean "The reason is chip.setTextSize(TypedValue.COMPLEX_UNIT_SP, 10F)"? If you do not set it, does the trailing padding get removed?

**Comment by wcshi** [comment]
Weird, can confirm that i am able to reproduce the behavior when setting chip.setTextSize(TypedValue.COMPLEX_UNIT_SP, 10F) in code but not in xml

**Comment by s-ilnar** [comment]
If you remove `chip.setTextSize (TypedValue.COMPLEX_UNIT_SP, 10F)`, then the wrong indents disappear.


**The problem reason is** `chip.setTextSize(TypedValue.COMPLEX_UNIT_SP, 10F)`

**Comment by wcshi** [comment]
ah, i suspect the problem is that chip's custom background (chipdrawable) is not aware of this change in text size. This is a bug in the library. As a quick workaround, could you create a textappearance with the desired text size and call that instead?

e.g. 
   chip.textAppearance = R.style.TextAppearance_MaterialComponents_Chip_small

  <style name="TextAppearance.MaterialComponents.Chip.small" parent="TextAppearance.MaterialComponents.Chip">
    <item name="android:textSize">10sp</item>
  </style>

**Comment by s-ilnar** [comment]
as a quick solution I use [this option]( https://stackoverflow.com/questions/56266649/android-chips-taking-extra-spacesunable-to-wrap/57397345#57397345).
 Thx
