### ISSUE TITLE
[Dialogs] Full screen dialog

### ISSUE THREAD

**Issue by eric-labelle** [material-components/material-components-android#1862]
The [full screen dialog ](https://material.io/components/dialogs#full-screen-dialog)described on material design website is not available and does not seem to be on [the roadmap](https://github.com/material-components/material-components-android/issues/1768) either.

Do you have any plans on adding this in a near future or is it expected for us to use the `setView()` with a custom DialogFragment?

**Comment by dsn5ft** [comment]
The animation there can be achieved with the new `MaterialContainerTransform` transition class ([docs](https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md#container-transform)), using either a full-screen Fragment or Activity. That might be easier than trying to get a full-screen `DialogFragment` or `Dialog` working. Can you give that a try and let us know if you have any more specific questions about that potential setup?

**Comment by VincentJoshuaET** [comment]
```
open class FullScreenDialogFragment : DialogFragment() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setStyle(STYLE_NORMAL, R.style.FullScreenDialog)
    }

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        val dialog = super.onCreateDialog(savedInstanceState)
        dialog.requestWindowFeature(Window.FEATURE_NO_TITLE)
        return dialog
    }

    override fun onStart() {
        super.onStart()
        dialog?.window?.setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
    }
}
```

```
<style name="FullScreenDialog" parent="Theme.MaterialComponents.DayNight.Dialog">
        <!-- Customize your theme here. -->
        <item name="android:windowBackground">@android:color/white</item>
        <item name="android:windowIsFloating">false</item>
    </style>
```
