### ISSUE TITLE
[MaterialDatePicker] Renders incorrectly on Android 11 - Pixel 2XL

### ISSUE THREAD

**Issue by rbenza** [material-components/material-components-android#1864]
The MaterialDatePicker renders incorrectly on a Pixel 2XL device with Android 11. Using version 1.3.0-alpha03. This does not happen on a Pixel 3 device or Android Studio emulators.

**Pixel 2XL running Android 11**
<img src="https://user-images.githubusercontent.com/47558082/98668439-2d578b80-2350-11eb-9862-3d953c4cb14d.png" width=250)>

**Pixel 3/Emulators running Android 11**
<img src="https://user-images.githubusercontent.com/47558082/98668468-39434d80-2350-11eb-8789-af28bfa35daa.png" width=250)>

**Comment by matpag** [comment]
This is the catalog app on current master, with Pixel 2XL API 30 emulator and it seems fine

![Screenshot_1605229381_2](https://user-images.githubusercontent.com/4432213/99015269-e4bcef80-2554-11eb-8a1f-4bd431135754.png)

**Comment by rbenza** [comment]
The screenshots from the emulator, pixel 3 (real device) and pixel 2XL (real device) posted above are running the exact same code, so unlikely padding/margins/insets are off.

**Comment by matpag** [comment]
Can you perform a check with layout inspector to see if there are some differences on those values in Pixel 2XL?

**Comment by drchen** [comment]
I'll close the issue due to no further info available. Also it doesn't seem like something we can fix on the library side.
