### ISSUE TITLE
[MaterialDatePicker + MaterialTimePicker] How to style the shape?

### ISSUE THREAD

**Issue by Zeliret** [material-components/material-components-android#1870]
Hello,

Can someone help me to find how to change the shape of new picker dialogs in styles? 
I tryed to look into the source code but it is unclear. 

Maybe there is a unified method to do that?

**Comment by wcshi** [comment]
@Zeliret could you please share a mock of what you are trying to achieve? Are you trying to customize the shape of the selection?

**Comment by drchen** [comment]
I'll close the issue due to no further info available. Feel free to reopen it if you have more details to provide.
