### ISSUE TITLE
[MaterialContainerTransform] Bounces when using AppbarScrollingViewBehavior

### ISSUE THREAD

**Issue by AxelBlaz3** [material-components/material-components-android#1873]
**Description:** MaterialContainerTransform seems to bounce when `app:layout_behavior="@string/appbar_scrolling_view_behavior"` is set.

**Expected behavior:** When `app:layout_behavior="@string/appbar_scrolling_view_behavior"` is removed from `FragmentContainerView`, everything works as expected, animations are smooth and doesn't bounce.

I'm sure it's happening because `MaterialContainerTransform` cannot calculate the precise height when animating and that's where this bounce is appearing. Is there any workaround for this? 

**Source code:** https://github.com/AxelBlaz3/ContainerTransformBounce

**Android API version:** 29

**Material Library version:** 1.2.1

**Device:** Poco F1

**Comment by dsn5ft** [comment]
@AxelBlaz3 thanks for providing the repo! Can you also attach a video of the issue here?

**Comment by AxelBlaz3** [comment]
@dsn5ft I've resolved the issue by moving the `TabLayout` from `activity_main.xml` to `fragment_home.xml`. Thanks for your time. I'll close the issue now.
