### ISSUE TITLE
Add a public API for BottomAppBar in order to show/hide it programmatically

### ISSUE THREAD

**Issue by brainail** [material-components/material-components-android#188]
Could you please add some simple public API for **BottomAppBar** in order to _show/hide_ it programmatically.

For now, I've created the following [workaround](https://gist.github.com/brainail/3681d73d25102f8a3949d1befe776bdc) but I think it will be more logical to have it officially 👨‍💼 

Thanks!

**Comment by firatkarababa** [comment]
I am just curious, why do you need to show or hide BottomAppBar programmatically since show/hide on scroll already works when you set `app:hideOnScroll="true"` attribute in xml?

**Comment by brainail** [comment]
**hideOnScroll** works well of course. But in my case, I want to show controls again when a user is about to start searching and it's not related to scrolling at all so that's why I need it. Also, I can imagine a case with some immersive-kinda manual mode when you want to show/hide all distracting details. 

In a case of **AppBarLayout**, I am able to use its layout params and modify `ScrollFlags` in order to achieve such result.

**Comment by firatkarababa** [comment]
Oh, I see it, you are right. It should be nice to have such an API.

**Comment by ymarian** [comment]
This was added in 
https://github.com/material-components/material-components-android/commit/43bdfac37b4b0e0e66ee0dc3c16ec99c6973f28f
Thanks!

**Comment by ftibi93** [comment]
Are these changes available?
I am using com.google.android.material:material:1.0.0 but the mentioned methods' visibility are still protected both in BottomAppBar and HideBottomViewOnScrollBehavior classes.

**Comment by dsn5ft** [comment]
That change will be available in the next release.

**Comment by zbigniewfr** [comment]
@dsn5ft was it released? What's the name of the method? I can't find it.
