### ISSUE TITLE
The content description of TextInputLayout character counter ist a mixture of English and local language.

### ISSUE THREAD

**Issue by qffan** [material-components/material-components-android#1881]
Artifact used: com.google.android.material:material:1.2.0
Version used:
Theme used:
Devices/Android versions reproduced on: Pixel 4, Android 11

- Relevant code to trigger the issue:

<com.google.android.material.textfield.TextInputLayout                
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="Message"
                app:counterEnabled="true"
                app:counterMaxLength="90">

                <TextInputEditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:maxLength="90"
                    android:text="123" />

- A screenrecord or screenshots showing the issue (if UI related):
none

I have change the system language to English, German and Chinese, and TalkBack reads out a mixture of English and the system language on the TextInputLayout/TextInputEditText character counter.

English:    Characters entered one of ninety
Germen:   Character entered eins of neunzig
Chinese:   Chracters entered 一 of 九十

**Comment by wcshi** [comment]
The strings should be properly translated in newer versions of the library. Could you please upgrade 1.3.0-alpha03

"Added string translations for to Date Picker, Time Picker, Bottom Sheet, TextField, Chip, Badge, Dialog (af375eb, c1a290e, 9d1d977, 467bb88, 0845dfe, 23018e1, cf3c091)"

e.g. https://github.com/material-components/material-components-android/blob/b163458a3a7919d7b7c76de81a7a9b5c940c8def/lib/java/com/google/android/material/textfield/res/values-zh-rCN/strings.xml#L18

**Comment by qffan** [comment]
Hello @wcshi , thank you for the answer. I have updated the library to the new version.
The Chinese version is well translated. But the German version is not so good.

<string name="character_counter_content_description">Eingegebene Zeichen: **%1$d/%2$d**</string>

Here the two numbers were read as a mathematical fraction: 18/100 -> achtzehn einhundertstel
"18 von 100" is the property and expected translation from our Team. 
Thank you again.

**Comment by wcshi** [comment]
Thank you for reporting the issue, we'll follow up with our translation team.

**Comment by wcshi** [comment]
Updated here: https://github.com/material-components/material-components-android/commit/725d78deb58d297cf9625b6f0c7c528ea25a23e4#diff-4a092f86b89c66ef58c536cba07bd2c37e00a7cfa6ab113d9633a81cf4d70ab4
