### ISSUE TITLE
Migrating from ViewPager to ViewPager2 with FragmentStateAdapter causes visible screen yank and StrictMode to be triggered

### ISSUE THREAD

**Issue by JimClermonts** [material-components/material-components-android#1883]
**Description:** 

I've followed the [Android documentation](https://developer.android.com/training/animation/vp2-migration) and [this](https://www.raywenderlich.com/8192680-viewpager2-in-android-getting-started) tutorial to migrate to ViewPager2. When swiping the 4 screens from left to right, there is a visible screen yank.

The documentation explicitly mentions that `createFragment` must provide a new `Fragment` each time so the implementation seems to be implemented correct.

**Expected behavior:** 
The same performance as with the old `ViewPager` and `PagerAdapter`.

I've written down the details in this [SO thread](https://stackoverflow.com/questions/64892174/migrating-from-viewpager-to-viewpager2-with-fragmentstateadapter-causes-visible).

**Source code:** 
View the SO Thread for up to date, I've also added the original code there.

**Android API version:** 
compileSdk 30

**Material Library version:** 
tried `1.3.0-alpha03` and `1.2.1`

**Device:** 
Samsung S8, A51.

https://stackoverflow.com/questions/64892174/migrating-from-viewpager-to-viewpager2-with-fragmentstateadapter-causes-visible

**Comment by JimClermonts** [comment]
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:viewpager2/viewpager2/src/main/java/androidx/viewpager2/adapter/FragmentStateAdapter.java

it seems the adapter caches fragments but does not pre-init views. forward scroll is janky, backward works fine. 1-> 2 -> 3 slow, 3 ->2 ->1 fine

**Comment by wcshi** [comment]
This sounds like a Viewpager2 bug, which is not part of the Material-Android library (it is a dependency), could you please file your an issue at https://issuetracker.google.com/issues/new?component=561920&template=1422419
