### ISSUE TITLE
[Snackbar/BaseTransientBottomBar] NPE in shouldAnimate

### ISSUE THREAD

**Issue by klemzy** [material-components/material-components-android#1885]
**Description:** We are seeing a growing number of crashes due to:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.view.accessibility.AccessibilityManager.getEnabledAccessibilityServiceList(int)' on a null object reference

which happen at

 com.google.android.material.snackbar.BaseTransientBottomBar.shouldAnimate(BaseTransientBottomBar.java:1060)

**Source code:** 
        Snackbar.make(
                    view,
                    getString(R.string.oops_something_went_wrong),
                    Snackbar.LENGTH_SHORT
                ).show()

**Android API version:** 9 and 10
**Material Library version:** 1.2.0

**Device:** Device on which the bug was encountered here
HUAWEI P30 lite
P20
P20 Pro
Galaxy S8
Galaxy S8+
etc

**Comment by matpag** [comment]
We probably should check that we were able to get a non-null reference to `AccessibilityManager` before calling `getEnabledAccessibilityServiceList` here
https://github.com/material-components/material-components-android/blob/5ff62d30982cea552946b06ffd30207d73a9fd6e/lib/java/com/google/android/material/snackbar/BaseTransientBottomBar.java#L1100-L1105
