### ISSUE TITLE
Constant cell flicker when scrolling lists

### ISSUE THREAD

**Issue by manuelpaulo** [material-components/material-components-android#1889]
**Is your feature request related to a problem? Please describe.**
The constant radial darker color/scrim fill animation of the list container cell element when dragging lists is annoying as hell, almost unbearable. Tapping a list to scroll it IS NOT a selection press gesture! This behavior creates a constant flicker. Makes one afraid of touching it in order not to trigger it again. Mostly noticed when browsing social networks news feeds. 

**Describe the solution you'd like**
An option for disabling it. I've tried changing it on developer options, but all I could do was changing the animation duration.

**Describe alternatives you've considered**
Triggering it after a much longer tap!

**Additional context**
This is a **very serious** issue for people with photosensitive epilepsy spending hours on social networks. I am surprised no one raised this problem before. Please take my advice seriously, I know what I am talking about. I see this behaviour on Facebook, Twitter, Reddit, and other apps. It gets worst on dark mode. And yes, you guess it right, I have just migrated from iOS to Android.

**Comment by wcshi** [comment]
Hi @manuelpaulo could you please share a video of the behavior you are describing to help us understand and identify the problem.

**Comment by manuelpaulo** [comment]
> Hi @manuelpaulo could you please share a video of the behavior you are describing to help us understand and identify the problem.

Sure. Here it is: https://www.dropbox.com/s/jm36onjlml8j9oq/

Thanks!

**Comment by manuelpaulo** [comment]
Someone else complaining about the same thing: https://www.reddit.com/r/RelayForReddit/comments/i05bk5/is_there_a_way_to_disable_this_touch_animation_i/

**Comment by wcshi** [comment]
@manuelpaulo thank you for sharing the video. Based on your video, it it looks like the "flickering effect" is likely a ripple effect on the selectable items in your Reddit app's recyclerview. This is an effect that each app developer sets via ?attr/selectableItemBackground ( see https://suragch.medium.com/adding-a-ripple-effect-to-an-android-recyclerview-item-61249eb382b0) and not something that is controlled by this library.

Please provide feedback to the apps that you are experiencing this issue with or use Android's recyclerview issuetracker:

https://issuetracker.google.com/issues/new?component=460887&template=1422600

**Comment by manuelpaulo** [comment]
> @manuelpaulo thank you for sharing the video. Based on your video, it it looks like the "flickering effect" is likely a ripple effect on the selectable items in your Reddit app's recyclerview. This is an effect that each app developer sets via ?attr/selectableItemBackground ( see https://suragch.medium.com/adding-a-ripple-effect-to-an-android-recyclerview-item-61249eb382b0) and not something that is controlled by this library.
> 
> Please provide feedback to the apps that you are experiencing this issue with or use Android's recyclerview issuetracker:
> 
> https://issuetracker.google.com/issues/new?component=460887&template=1422600

Thanks. Maybe this is an old bug? https://github.com/ozodrukh/RippleDrawable/issues/4

https://stackoverflow.com/questions/36655739/android-card-view-ripple-effect-starts-right-after-a-click/
https://stackoverflow.com/questions/32102669/ripple-effect-weird-behavior-in-listview

Thanks @wcshi
