### ISSUE TITLE
Library versioning?

### ISSUE THREAD

**Issue by colinrtwhite** [material-components/material-components-android#189]
Does this library follow the same versioning as the other Android X libraries? `rc-02` has been released for the other Android X libraries, but `rc-01` is the latest version of this library.

**Comment by dsn5ft** [comment]
This library will transition to 1.0.0 stable at the same time as the other Android X libraries, but it's not guaranteed to have the same number of `rc` releases as the other libraries. Also, there shouldn't be any compatibility issues when using two different `rc` versions at the same time (e.g., `rc-02` Android X + `rc-01` Material). Post 1.0.0 release, Material will be on its own versioning schedule, as will all of the individual Android X libraries.
