### ISSUE TITLE
[TextInputLayout] FilledBox without rounded corners at top

### ISSUE THREAD

**Issue by crowneed** [material-components/material-components-android#1890]
**Description:** My designer wants to use this component by material guide. But when i use it in a new empty project, i get a problem with rounded corners at top of TextInputLayout.

**Expected behavior:** 
![image](https://user-images.githubusercontent.com/40777036/99784691-3ead4e80-2b2d-11eb-9613-2ba51785c138.png)

**Source code:** 
![image](https://user-images.githubusercontent.com/40777036/99784800-60a6d100-2b2d-11eb-93de-8537bf892831.png)

**Android API version:** 29-30

**Material Library version:** 1.2.1. But when i'm searching to resolve this issue, i checked all versions from 1.0.0, and saw that the problem didn't reproduce on 1.0.1-alpha(02,03,04). Look at screenshot 
![image](https://user-images.githubusercontent.com/40777036/99785774-a9ab5500-2b2e-11eb-9044-0183d6c14da6.png)

**Device:** Pixel 3a, Pixel 4 and probably on any other devices, cause i see it at xml preview.

**Comment by wcshi** [comment]
Is the problem only with the preview in Android Studio or do you see the problem when you install an app on an emulator or physical device?

**Comment by crowneed** [comment]
if it was problem only with preview... yeah, main problem is it reproduced on devices

**Comment by wcshi** [comment]
Please share a sample project that can reproduce this bug, thanks!

**Comment by crowneed** [comment]
you can create a new project from android studio, only with import material lib and the same xml at top

**Comment by crowneed** [comment]
Is there any problem? I can send zip project, if it helps

**Comment by leticiarossi** [comment]
We cannot reproduce the issue on our side, so please provide a sample project that reproduces it so we can better investigate.

**Comment by crowneed** [comment]
resolved, the problem remained only for preview
