### ISSUE TITLE
[TextInputLayout] Invisible box outline on empty text and Suffix ruining box

### ISSUE THREAD

**Issue by Doomski99** [material-components/material-components-android#1893]
**Description:** Box outline doesn't appear when focused with empty text :
Unfocused
![Screenshot 2020-11-22 113239](https://user-images.githubusercontent.com/45564681/99900363-b6a78000-2cb7-11eb-9d17-4ef0b6f13e7a.jpg)
Focused
![Screenshot 2020-11-22 113326](https://user-images.githubusercontent.com/45564681/99900384-c9ba5000-2cb7-11eb-988a-241d447eeafe.jpg)
Focus with text
![Screenshot 2020-11-22 115504](https://user-images.githubusercontent.com/45564681/99900645-95e02a00-2cb9-11eb-815f-8d922a2048e1.jpg)
Also in errors
![Screenshot 2020-11-22 113452](https://user-images.githubusercontent.com/45564681/99900388-ddfe4d00-2cb7-11eb-9e3f-6a9822c76047.jpg)

Another issue is that suffixes and trailing icons overlap the stroke:
![Screenshot 2020-11-22 113503](https://user-images.githubusercontent.com/45564681/99900428-2d447d80-2cb8-11eb-983f-dbc12f071bb7.jpg)
And my calendar's trailing icon disappears on error even though it's still clickable
![Screenshot 2020-11-22 115121](https://user-images.githubusercontent.com/45564681/99900594-0dfa2000-2cb9-11eb-8caa-df0a0e3ea979.jpg)

**Expected behavior:** For the outline to appear even with empty text and errors. And my trailing icon to still be visible on error.

**Source code:** A snippet of one of my fields:
```
            <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/add_diameter_lay"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="16dp"
                android:layout_marginEnd="16dp"
                android:layout_marginTop="16dp"
                android:hint="@string/tree_diameter"
                style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toBottomOf="@id/add_height_lay"
                app:suffixText="@string/meter">
                <com.google.android.material.textfield.TextInputEditText
                    android:id="@+id/add_diameter"
                    android:textAlignment="center"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:inputType="numberDecimal"
                    android:textSize="14sp"
                    android:imeOptions="actionDone"/>
            </com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** API 29

**Material Library version:** 'com.google.android.material:material:1.2.1'

**Device:** Pixel 2 api 30 emulator and my HTC 10 android 8.0

**Comment by leticiarossi** [comment]
could you provide a sample app that reproduces the issue?

**Comment by LukaKit** [comment]
@Doomski99 I had the same issue and fixed it with the help of this answer: https://stackoverflow.com/questions/64596156/boxstroke-with-material-outline-box-doesn%C2%B4t-work

**Comment by Doomski99** [comment]
THANK YOU SO MUCH! @LukaKit 
All is fixed !!

**Comment by ChaseApptentive** [comment]
Is this fixed? 

It doesn't seem correct that the TextInputLayout is using the app's style background color as its focused textless box stroke color. Any reason it's not the same color as the focused with text box stroke color?

If I can get a workaround without having to remove the app's style background (kinda need it), that would work, but I can't figure out how to make that stoke color NOT the app's inherited style ("android:background") color.

**Comment by offvanHooijdonk** [comment]
Really, is that a "Fixed" ??
I need to have a black background, and now my TextInoutLayout is invisible without text just because.. WHY? And no way to override this color, are you serious?
