### ISSUE TITLE
[TextInputLayout] Auto-scrolling to the bottom of TextInputLayout whenever cursor is placed on TextInputEditText

### ISSUE THREAD

**Issue by jinyanliu** [material-components/material-components-android#1897]
**Description:** On material lib version 1.2.1, 1.3.0-alpha03(latest), whenever a cursor is placed on TextInputEditText, it autoscrolls to the bottom of the TextInputLayout. So when the text is very long, and cursor is placed on the first few lines, it autoscrolls to the bottom of the TextInputLayout, user can no longer see the cursor, and cannot continue editing where the cursor is pointing at. 

**Expected behavior:** On material lib version 1.1.0, this bug doesn't exist. Whenever a cursor is placed, the cursor is always visible to the user.

**Source code:** https://github.com/jinyanliu/Bug-MaterialLibTextInputLayoutAutoScrollingIssue (You can read README for how to reproduce this issue.)

**Android API version:** API 30

**Material Library version:** 1.2.1, 1.3.0-alpha03(latest)both have this bug (And this bug doesn't exist on 1.1.0)

**Device:** Pixel 3a, Pixel 4 XL

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
Does setting `app:textInputLayoutFocusedRectEnabled` to `false` in your TextInputEditText solve that issue?

**Comment by jinyanliu** [comment]
@leticiarossi Yes, it does solve this issue. Thank you.
