### ISSUE TITLE
[ConstraintLayout] layout_constraintHeight_max works incorrectly

### ISSUE THREAD

**Issue by Xen4n** [material-components/material-components-android#1904]
**Description:** After transfer from "material:1.3.0-alpha01" to "material:1.3.0-alpha02..alpha04" style argument `layout_constraintHeight_max` from the code below breaks layout height.

**Expected behavior:** the height of the component must be 0.3 from the parent and must not exceed the maximum. But component height is 0. After problem argument (layout_constraintHeight_max) removing the component height is perfectly 30% of parent size. On `1.3.0-alpha01` version the code below works correctly.

**Source code:** I have this code in style:
`<item name="android:layout_width">0dp</item>`
 `<item name="android:layout_height">0dp</item>`
`<item name="layout_constraintHeight_percent">0.3</item>`
`<item name="layout_constraintHeight_default">percent</item>`
 `<item name="layout_constraintHeight_max">240dp</item>`

**Android API version:** API 16

**Material Library version:** 1.3.0-alpha04
**Constraint layout version:** 1.1.3

**Device:** Nexus One 3.7 API 16 emulator

**Comment by Xen4n** [comment]
You upgrade constraintLayout from stable 1.1.3 to 2.0.1 where this bug exists :(

**Comment by karan4c6** [comment]
Facing a similar issue with Material Design library 1.3.0 version. Looks like the Constraint Layout also needs to be updated to v2.
