### ISSUE TITLE
[MaterialDatePicker] Range validators

### ISSUE THREAD

**Issue by jeroen1007** [material-components/material-components-android#1905]
Hello,

Is there a way to set a max span for the date range picker?
So, I basically want to set a max end date based on the start date input.

**Comment by wcshi** [comment]
One option is to create a custom date validator which implements [DateValidator](https://github.com/material-components/material-components-android/blob/1f76fcc70f17e88c54baf41a8bc675d94f9c9695/lib/java/com/google/android/material/datepicker/CalendarConstraints.java#L50) that takes in the user's selected date and keeps track of the valid end date.

**Comment by jeroen1007** [comment]
@wcshi is there a way to access the first selected date from within the DateValidator?

**Comment by wcshi** [comment]
No, the DateValidator is a simple interface that doesn't know the selected date, but you can get the selected date via: 
https://github.com/material-components/material-components-android/blob/074ed18255789c199183c79f2e860b0bd8645ee6/lib/java/com/google/android/material/datepicker/RangeDateSelector.java#L94-L96

**Comment by jeroen1007** [comment]
@wcshi Thanks!
