### ISSUE TITLE
[BottomNavigationView] Unnecessary space is added after setting hide-navigation flags and rotates the screen.

### ISSUE THREAD

**Issue by hokar** [material-components/material-components-android#1907]
**Description**: 
If you set the SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION and SYSTEM_UI_FLAG_HIDE_NAVIGATION flags when landscape mode, and then remove those flags when portrait mode, the unnecessary space (window inset) is added.

**Expected behavior**: Does not be added unnecessary space.

**Source code**: 
I guess the cause of this issue is the following commit.
https://github.com/material-components/material-components-android/commit/5889993bb30ef210969b1dd284ec503b36b2ac8b

**Android API version**: Android 8, 10

**Material Library version**: 1.3.0-alpha01~04

**Device**: Sony Xperia XZs, Sony Xperia 5

**Comment by wcshi** [comment]
Please share a video of the behavior you are describing and a sample app, thanks!

**Comment by hokar** [comment]
![device-2020-12-01-185035](https://user-images.githubusercontent.com/5677376/100727097-25e44900-3409-11eb-9455-1b7b59471141.gif)

Hi, thank you for your reply.
I attached a gif file of the behavior.
Please check it.

Thanks!

**Comment by hokar** [comment]
Hi, 
Thank you for your reply!
I attached a part of my sample code and some screenshots.
The key point is NOT to set up gesture navigation
This problem does not occur when the setting gesture navigation.

``` activity_main.xml
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/black"/>

        <FrameLayout
            android:id="@+id/fragment_container"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"/>

        <com.google.android.material.bottomnavigation.BottomNavigationView
            android:id="@+id/bottom_navigation"
            android:layout_width="match_parent"
            android:layout_height="?actionBarSize"
            app:labelVisibilityMode="labeled"
            app:menu="@menu/bottom_navigation_item"/>

    </LinearLayout>
```

```MainActivity.kt
override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        window?.decorView?.systemUiVisibility = if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
                    View.SYSTEM_UI_FLAG_IMMERSIVE or
                    View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY or
                    View.SYSTEM_UI_FLAG_FULLSCREEN or
                    View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or
                    View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
                    View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
        } else {
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
                    View.SYSTEM_UI_FLAG_IMMERSIVE
        }
    }
```

![device-2020-12-01-233759](https://user-images.githubusercontent.com/5677376/100758398-d286f080-3432-11eb-9a11-289c91c4048d.png)
![device-2020-12-01-234959](https://user-images.githubusercontent.com/5677376/100758423-d87cd180-3432-11eb-9c9d-4aa3780b9910.png)
![device-2020-12-01-233955](https://user-images.githubusercontent.com/5677376/100758445-dc105880-3432-11eb-8ad3-f2c545d1d557.png)

Thanks!

**Comment by riteshmahajan47** [comment]
Facing the Same issue on a tablet in landscape mode after hiding system UI.

**Comment by itsandreramon** [comment]
Still happening

**Comment by jimmymorales** [comment]
I was having the same issue as @riteshmahajan47. I was able to fix it by using the WindowInsetsControllerCompat instead of setting `systemUiVisibility` flags.
So instead of having this:
``` kotlin
fun Activity.hideSystemUi() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        window?.decorView?.windowInsetsController?.apply {
            hide(WindowInsets.Type.navigationBars() or WindowInsets.Type.systemBars())
            systemBarsBehavior = WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
        }
    } else {
        @Suppress("DEPRECATION")
        window?.decorView?.systemUiVisibility =
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
            View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or
            View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or
            View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
            View.SYSTEM_UI_FLAG_FULLSCREEN or
            View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
    }
}
```
it got replaced for this:
``` kotlin
fun Activity.hideSystemUi() {
    WindowInsetsControllerCompat(window, window.decorView).apply {
        hide(WindowInsetsCompat.Type.systemBars())
        systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
    }
}
```
_Note: The issue was only happening for Android Q or lower, so it could be related to one of the flags that were set._

**Comment by drchen** [comment]
I think it has been fixed and also the above suggestion should work in certain cases as well. 

I'll close the issue for now. Feel free to reopen it if it's still happening with the latest library version.

**Comment by Nephys222** [comment]
@drchen @jimmymorales Issue still persists in latest versions. Reopened the issue #2851. @jimmymorales workaround is only for higher versions (API > 29). 

> Note: The issue was only happening for Android Q or lower, so it could be related to one of the flags that were set.
was right. But in order to support lower API  (min> 21) how this issue could be solved.

**Comment by drchen** [comment]
Will get someone to take a look. Thanks for the report!!
