### ISSUE TITLE
[TextInputLayout] Added an option to achieve the collapsed hint with an empty background in outline box

### ISSUE THREAD

**Issue by ntphuc** [material-components/material-components-android#1908]
Dear teams, 

I have a problem like this issue https://github.com/material-components/material-components-android/pull/1660. I see that the issue is closed.

I downloaded the latest version 1.3.0-alpha04, but it is not fixed. 

Please help me to clarify this. 

Thanks so much. 

@gabrielemariotti

**Comment by gabrielemariotti** [comment]
@ntphuc the pr #1660 is open.

**Comment by ntphuc** [comment]
@gabrielemariotti It seems that the issue is solved by yourself, but I dont know why it is not merge to the master. Currenly, I have a problem with that and I dont know how to solve it. Maybe I have to wait for it merge to the master brand?
Thanks.
