### ISSUE TITLE
[MaterialDatePicker] Dialogue height should wrap contents when toggling between "Calendar" and "Text" input modes

### ISSUE THREAD

**Issue by awat-langoe** [material-components/material-components-android#1911]
**Description:**
Height of MaterialDatePicker dialogue in "Text" input mode is larger than in the Material guideline documentation. The consequence of this is the dialogue obstructs more of the view below, and all the blank space does not look good IMO.

**Screenshots from catalogue app:**
![device-2020-12-02-160628](https://user-images.githubusercontent.com/9946975/100890661-c2195900-34b8-11eb-8d7c-9526b5d8588e.png) ![device-2020-12-02-160639](https://user-images.githubusercontent.com/9946975/100890665-c34a8600-34b8-11eb-90ac-f5b7e07506ba.png)

**Video from Material.io:**
https://kstatic.googleusercontent.com/files/f7cbf55d79f5aad34e80b48b174c9fc3f30d05fef0653c08f8e53e023c9754e4be2dc1ebc9822425e8560f2b37a082a76b0913533283939f6485f00787f9efbd
_The video is from "Components → Date pickers → [Mobile pickers](https://material.io/components/date-pickers#mobile-pickers) → Behavior"_

**Expected behavior:**
Dialogue should wrap its height when toggling between "Calendar" and "Text" input modes.

**Android API version:** 11

**Material Library version:** 1.3.0-alpha04

**Device:** Emulator in Android Studio

**Comment by es0329** [comment]
Issue is also present in `1.3.0-rc01`.

**Comment by awat-langoe** [comment]
Related issues: #2161 #939 

Related pull request: #2162

**Comment by awat-langoe** [comment]
Closed in #2162.
