### ISSUE TITLE
Material Outlined Button[Label/Text Color not changing]

### ISSUE THREAD

**Issue by vivek-modi** [material-components/material-components-android#1915]
**Description:** Hi I am working in Material Outline Button. I Tried to set label color in material button with enable and disable state. But its not taking color from my style. Instead it taking my accent color.

**Source code:** 
```
 <com.google.android.material.button.MaterialButton
        android:id="@+id/detail"
        style="@style/secondaryStyle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Show Details"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent" />
```
**Styles**
```
<style name="secondaryStyle" parent="Widget.MaterialComponents.Button.OutlinedButton">
        <item name="android:elevation">1dp</item>
        <item name="strokeColor">@color/strokeSelector</item>
        <item name="strokeWidth">2dp</item>
        <item name="cornerRadius">2dp</item>
        <item name="android:backgroundTint">@color/backgroundSelector</item>
        <item name="android:textAppearance">@style/secondaryTextApperance</item>
    </style>

    <style name="secondaryTextApperance">
        <item name="android:textColor">@color/textSelector</item>
    </style>

```
**TextSelector Color**
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/red" android:state_enabled="true" android:state_pressed="true" />
    <item android:color="@color/white" android:state_pressed="false" />
</selector>
```

**Android API version:** 30

**Material Library version:** com.google.android.material:material:1.2.1

I am getting this result.

<img width="121" alt="Screenshot 2020-12-03 at 11 51 43" src="https://user-images.githubusercontent.com/24395678/101039460-c22a5f00-3573-11eb-916b-6b26d3e722d1.png">

**Comment by leticiarossi** [comment]
Looking at the colors that the button uses, for [stroke color ](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/color/mtrl_btn_stroke_color_selector.xml)the color state list has  `android:state_checked` instead of `android:state_pressed`.  For [text color](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/color/mtrl_btn_text_color_selector.xml), it uses `android:state_enabled`

Can you try using CSLs that follow those formats?

**Comment by vivek-modi** [comment]
Hi @leticiarossi thanks for reply. I don't know about CSLs.

**Comment by leticiarossi** [comment]
The parent style of the button [sets android:textColor](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/values/styles.xml#L30). Can you try overriding that value in your style? So something like
```
<style name="secondaryStyle" parent="Widget.MaterialComponents.Button.OutlinedButton">
    <item name="android:textColor">@color/textSelector</item>
    ...
</style>
```
If that doesn't work could you post screenshots of the behavior you're trying to achieve? You can find more info about states and color state lists (CSLs) [here](https://stackoverflow.com/questions/9335279/change-button-text-color-when-pressed).

**Comment by leticiarossi** [comment]
Will close this but feel free to comment if you're still having issues
