### ISSUE TITLE
Programmatically change the font style of the Textinputlayout hint

### ISSUE THREAD

**Issue by Nextgen-Webservice** [material-components/material-components-android#1918]
Hello,

On Material Design, currently there is no option to **programmatically change the font style of the Textinputlayout hint**. We are unable to change the Roboto style to Bold, Italics programmatically.

Client requires this feature as a priority. Please guide us on how we can achieve it in Material design. If not possible to achieve it now, please advise if these features will be available in the near future.

Thank you in advance. Looking forward to a quick response.

**Comment by leticiarossi** [comment]
There is a `setHintTextAppearance` method you can call on the `TextInputLayout` to change the collapsed hint's text appearance, and you can also call `setTextAppearance` on the edit text (the expanded hint uses the edit text's text appearance). Does that help you?
