### ISSUE TITLE
[CircularProgressIndicator] Make class non final

### ISSUE THREAD

**Issue by TurKurT656** [material-components/material-components-android#1919]
**Describe the solution you'd like**
I'm trying to make a custom view (CountDownView) based on CircularProgressIndicator but I can't extend from it.

**Comment by Mygod** [comment]
Agree with this.

**Comment by pekingme** [comment]
Hi @TurKurT656, a CoundDownView sounds achievable by composing a CPI and TextView in a layout. Can you elaborate your use case, if that's not suitable? Thanks.

**Comment by Mygod** [comment]
I have a separate use case where I want to add an on end listener to progress drawable: https://github.com/shadowsocks/shadowsocks-android/blob/e04350fccb6963878cc1f264ca7d4ee705178dda/mobile/src/main/java/com/github/shadowsocks/widget/ServiceButton.kt#L103

**Comment by pekingme** [comment]
Feel free to add another feature request or reopen this for any reason to make CPI (or LPI) non-final.

**Comment by TurKurT656** [comment]
@pekingme Yes it is achievable but I'm not happy with that solution (compound view). I want to draw a text in center of this CircularProgressIndicator like this:

```
class CountDownView : CircularProgressIndicator {
    override fun onDraw(canvas: Canvas?) {
        super.onDraw(canvas)
        canvas?.drawText(...)
    }
}
```
