### ISSUE TITLE
Еllipsize text if the setMaxWidth is specified in ChipDrawable

### ISSUE THREAD

**Issue by elephant-cf** [material-components/material-components-android#192]
Еllipsize long text if the setMaxWidth is specified in ChipDrawable

**Comment by ymarian** [comment]
Closing this, you can track the status on https://b.corp.google.com/issues/113595665. Please 
use the public buganizer for issues in the future!

**Comment by wcshi** [comment]
elephant-cf, could you please provide some code snippet on https://b.corp.google.com/issues/113595665 of how to reproduce the issue?

**Comment by elephant-cf** [comment]
I don't see the issue changes in the version Revision 28.0.0 Production 
https://developer.android.com/topic/libraries/support-library/revisions

**Comment by wcshi** [comment]
@elephant-cf could you you please respond with reproducible steps on https://b.corp.google.com/issues/113595665 ?

**Comment by elephant-cf** [comment]
I added a comment in https://issuetracker.google.com/issues/113595665
