### ISSUE TITLE
Handle switching to ProgressIndicator indeterminate state without requiring visibility changes

### ISSUE THREAD

**Issue by dknchris** [material-components/material-components-android#1921]
The following exception is seen when we do a ProgressIndicator.setIndeterminate(true) while the ProgressIndicator is visible. Here's how you reproduce the issue:
```
progressIndicator.isVisible = true
progressIndicator.setProgressCompat(50, true)
progressIndicator.isIndeterminate = true

Output:
IllegalStateException: Cannot switch to indeterminate mode while the progress indicator is visible.
        at com.google.android.material.progressindicator.BaseProgressIndicator.setIndeterminate(BaseProgressIndicator.java:504)
```
This is clearly a new and unexpected behavior not documented in the changes list. 

The workaround is to do the below:
```
progressIndicator.isVisible = false
progressIndicator.isIndeterminate = true
progressIndicator.isVisible = true
```

Shouldn't this be handled within the implementation of the BaseProgressIndicator? The benefit would be that the developers do not need to additionally add visibility handling when switching from legacy ProgressBar implementations (Eg. AOSP ProgressBar)

**Comment by master-bytes-krafter** [comment]
Being bitten by this at this very moment !

**Comment by sipersso** [comment]
Same here. Didn't expect this.

**Comment by ytheekshana** [comment]
same here.

**Comment by iSWORD** [comment]
The solution is very silly, why is this a thing?
