### ISSUE TITLE
[Slider] Slider thumb top and bottom clipped

### ISSUE THREAD

**Issue by ryandt** [material-components/material-components-android#1923]
**Description:**
The `Slider` thumb is clipped at the top and bottom. Here's a screenshot of an example with "Show layout bounds" turned on:

![Screenshot_20201211-152421](https://user-images.githubusercontent.com/4073952/101956689-a5220b80-3bc5-11eb-8c1f-0816bf64df05.png)

It looks like the issue is a non-configurable `widgetHeight` property defined in a material dimens file. The dimen is called `mtrl_slider_widget_height`. This value determines the height of the rectangle that's clipping the thumb in the screenshot above. It'd be nice if either this property could be set by a style attribute or if the height could instead be calculated based on the `trackHeight`, `thumbRadius`, and any other relevant properties.

**Expected behavior:** 
The thumb is not clipped.

**Source code:**
```
class CustomSlider @JvmOverloads constructor(
    context: Context,
    defStyleRes: Int = 0,
    attributeSet: AttributeSet
) : Slider(context, attributeSet, defStyleRes) {
    
    init {
        initTrack()
        initThumb()
    }

    private fun initTrack() {
        valueFrom = 0f
        valueTo = 2500f
        stepSize = valueTo / 25
        trackHeight = resources.getDimensionPixelSize(R.dimen.slider_track_height) // 40dp
        isTickVisible = false
        ContextCompat.getColorStateList(context, R.color.selector_slider_track_active)?.let {
            trackActiveTintList = it
        }
        ContextCompat.getColorStateList(context, R.color.selector_slider_track_inactive)?.let {
            trackInactiveTintList = it
        }
    }

    private fun initThumb() {
        thumbRadius = resources.getDimensionPixelSize(R.dimen.slider_thumb_radius) // 57dp
        thumbStrokeWidth = resources.getDimensionPixelSize(R.dimen.slider_thumb_stroke_width).toFloat() // 4dp
        thumbStrokeColor = ContextCompat.getColorStateList(context, R.color.selector_slider_thumb_stroke)
        ContextCompat.getColorStateList(context, R.color.selector_slider_thumb)?.let {
            thumbTintList = it
        }
    }
}
```

**Android API version:** 
29

**Material Library version:** 
1.3.0-alpha04

**Device:** 
Google Pixel 3

**Related issue:**
#1579

**Comment by jishincreo** [comment]
Any plans on fixing this soon?

**Comment by drchen** [comment]
Is this still an issue?

**Comment by ryandt** [comment]
@drchen Yeah, I believe so

**Comment by HannesGitH** [comment]
height of slider is still not settable via layoutParams, right?
