### ISSUE TITLE
[MaterialTimePicker] Cannot resolve symbol 'MaterialTimePicker'

### ISSUE THREAD

**Issue by SergiiM** [material-components/material-components-android#1932]
**Description:** Cannot resolve symbol 'MaterialTimePicker'

**Expected behavior:** Able to use MaterialTimePicker from material lib

**Source code:** MaterialTimePicker materialTimePicker = new MaterialTimePicker.Builder()
                .setTimeFormat(clockFormat)
                .setHour(hour)
                .setMinute(minute)
                .build();

**Android API version:** 29

**Material Library version:** 1.2.1

**Device:** Samsung S7

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by SergiiM** [comment]
With 1.3.0-beta01 version it works ok, but I'd like to use stable lib version in my app, not alpha or beta.

**Comment by leticiarossi** [comment]
The time picker component was first introduced in version [1.3.0-alpha02](https://github.com/material-components/material-components-android/releases/tag/1.3.0-alpha02). It will become available on a future 1.3.0 stable release, so in the meantime you can only use it if you use 1.3.0-alpha02 or a higher version of the library.

**Comment by SergiiM** [comment]
hi @leticiarossi, ok thank you I don't know this info.
