### ISSUE TITLE
[MaterialDatePicker] Wrong month title for April 1981-1984

### ISSUE THREAD

**Issue by priittiidla** [material-components/material-components-android#1935]
**Description:**
Datepicker is showing title March instead of April. 
Issue a is for years 1981 - 1984.
Issue seems to be only the title. Values selected from calendar are correct.

<img width="302" alt="Screenshot 2020-12-18 at 10 39 03" src="https://user-images.githubusercontent.com/40997691/102593352-6b995500-411d-11eb-95e8-b3e160ee2418.png">
<img width="301" alt="Screenshot 2020-12-18 at 10 38 48" src="https://user-images.githubusercontent.com/40997691/102593360-6e944580-411d-11eb-989a-c78098e81ff7.png">

**Expected behavior:** 
Month title for April should be "April"

**Material Library version:** 
 1.3.0-beta01

**Comment by drchen** [comment]
Is this still reproducible? I cannot reproduce it on my end.

**Comment by originx** [comment]
@drchen  we can confirm we see the same bug. One way  to reproduce it:
Pixel 5 Android 12

- Set timezone to region Poland
- Open date time picker
- Pick year 1979
- Navigate the months back or towards March/April

Expected:
Months are switched properly March, April etc

Actual:
March is shown twice

hope this helps in the fix, cheers!

**Comment by drchen** [comment]
Hi @originx thanks for the info.

Are you using the latest library version?

**Comment by originx** [comment]
Hi drchen,

the issue occurs on:
1.4.0
1.5.0-beta01
1.6.0-alpha01
