### ISSUE TITLE
[BaseTransientBottomBar] why must  style on this component requires your app theme to be AppCompat ?

### ISSUE THREAD

**Issue by yuqiyich** [material-components/material-components-android#1936]
if   style on this component is not  “AppCompat”  style,but component also works ，only some experience problem，if  my style not extends “AppCompat”  style， your code will throw exception and crash our app， actully i don't check style also work for my app. so why must check sytle and if not will throw exception crash our App ？

**Comment by Sanlorng** [comment]
Because some components's default style and default attributes use Appcompat attributes，if you don't use Appcompat thme，it maybe cause UI Crashed

**Comment by drchen** [comment]
It requires certain AppCompat-only theme attributes to render itself correctly. Please notice that Material is a "design library". We will have some hard design requirements applied on the library which we should not break (intentionally.)
