### ISSUE TITLE
Documentation about CircularReveal components.

### ISSUE THREAD

**Issue by agustinsivoplas** [material-components/material-components-android#194]
How to create a circular reveal animation with this components?

```
android.support.design.circularreveal.CircularRevealFrameLayout
android.support.design.circularreveal.CircularRevealGridLayout
android.support.design.circularreveal.CircularRevealLinearLayout
android.support.design.circularreveal.CircularRevealRelativeLayout
android.support.design.circularreveal.cardview.CircularRevealCardView
android.support.design.circularreveal.coordinatorlayout.CircularRevealCoordinatorLayout
```

Please could you provide any documentation/example ?

Thanks in advance.

**Comment by ldjcmu** [comment]
Please take a look at the documentation on material-components-android/lib/java/com/google/android/material/circularreveal/CircularRevealWidget.java.

**Comment by agustinsivoplas** [comment]
@ldjcmu a .java file is not enough to understand how the components works. Also there is a stackoverflow question with same doubts https://stackoverflow.com/questions/51432581/circular-reveal-android-compat-with-design-library-28

**Comment by ldjcmu** [comment]
Sorry, I'll try to clarify a bit more.

The documentation for that java class states "To modify the circular clip, use {@link CircularRevealCompat}." CircularRevealCompat has methods with the signature 'Animator createCircularReveal(CircularRevealWidget ...)'. The classes you listed above (e.g., CircularRevealLinearLayout) implement CircularRevelWidget, so you can use those in the create call.

This call combined with android documentation on creating circular reveals (https://developer.android.com/training/animation/reveal-or-hide-view#Reveal) should get you what you need.

I hope that's a bit more clear.
