### ISSUE TITLE
[TextInputLayout] Activating the error state without error text

### ISSUE THREAD

**Issue by tamtom** [material-components/material-components-android#1942]
**Description:** sometimes we need to activate the error state of the  TextInputLayout but sending an empty text is not activating it, so we have to send a space as a text to activate the error state, this is causing an empty space below the TextInputLayout.
is there a way to activate the error state without sending a text? 
or to hide the error text view?

**default state:** 
<img width="363" alt="Screen Shot 2020-12-20 at 5 26 54 PM" src="https://user-images.githubusercontent.com/7765381/102714628-5ec95c80-42e9-11eb-90a8-5a19c52c9035.png">

**error state:** 
<img width="359" alt="Screen Shot 2020-12-20 at 5 27 02 PM" src="https://user-images.githubusercontent.com/7765381/102714632-625ce380-42e9-11eb-8aac-bff6b6038ccb.png">

**check empty space since the error text is visible:** 
<img width="369" alt="Screen Shot 2020-12-20 at 5 28 31 PM" src="https://user-images.githubusercontent.com/7765381/102714634-6557d400-42e9-11eb-8280-f82d5067e0c8.png">

**Material Library version:** 1.3.0-alpha01

**Comment by drchen** [comment]
I think it's working as intended. 

We encourage you to provide meaningful error messages to users. : )

**Comment by messenger63** [comment]
@drchen in a case described here, if user enter incorrect combination of login+password, we can't show user what field was wrong as it will be security breach. In a same time there is no reason to show 2 errors with same message in both fields. So ideal solution would be to highlight both fields, but show single error somewhere else, like in snack bar, etc. 
So for this case we can't handle it nicely without possibility to show error without text.

**Comment by fletz** [comment]
I am of the same opinion as @messenger63 . I think there are use cases where you want to show a validation without an explicit error message. I do have a form in which the only problem that can exist is if it's empty. So the error message would always be "this is a required field". Since this is obvious I would like to not show the message, because it makes my form "jump".
