### ISSUE TITLE
[MaterialTimePicker] Design Issues (API 15)

### ISSUE THREAD

**Issue by mwrod** [material-components/material-components-android#1945]
**Description:**
I found some design issues when I was testing on an Emulator with API 15. I don't know exactly if this API Version is supported, but this are the flaws I found:
- No left margin/padding on title
- Minutes are not centered inside its rectangle background
- No left margin/padding on AM/PM Toggle
- Text of initial selected hour is not visible (only on first start)

![image](https://user-images.githubusercontent.com/9077206/102783608-76f9b400-439b-11eb-83b4-239a5049463e.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/9077206/102783766-bc1de600-439b-11eb-8392-9dee12a16f9c.png)

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** API 15

**Material Library version:** 1.3.0-beta01

**Device:** Galaxy Nexus Emulator

**Comment by drchen** [comment]
Is this still an issue?

API 14 & 15 are deprecated for emulators so I'm not able to test.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
