### ISSUE TITLE
[CircularProgressIndicator] White/transparent lines on progress indicator ends when using rounded track

### ISSUE THREAD

**Issue by ubuntudroid** [material-components/material-components-android#1947]
**Description:** When enabling rounded ends on the progress indicator using `trackCornerRadius` there are fine white/transparent lines at the beginning and end of the actual progress indicator as well as in the middle of the round corners. See this screenshot:

![image](https://user-images.githubusercontent.com/519867/102804631-4b39f680-43ba-11eb-82c1-ddf45ca748ed.png)

**Expected behavior:** No white/transparent lines on progress indicator.

**Source code:** 

```xml
        <com.google.android.material.progressindicator.CircularProgressIndicator
            android:id="@+id/progressIndicator"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            app:indicatorColor="@color/blue"
            app:indicatorSize="168dp"
            app:trackThickness="20dp"
            app:trackCornerRadius="10dp"
            app:trackColor="@color/blue_light" />
```

**Android API version:** Tested on API level 30

**Material Library version:** 1.3.0-beta01

**Device:** Pixel 2, Android 11

**Comment by jose-araujo-ifood** [comment]
This same bug happens to LinearProgressIndicator. 

![20210120_181511](https://user-images.githubusercontent.com/75990563/105238959-78113300-5b4b-11eb-83fe-f6a708d52c76.jpg)

**Comment by enginegl** [comment]
Same issue here! Any updates?

**Comment by pekingme** [comment]
Hi, sorry for the latency. It's on my list. I'll take a look at it soon. It's either the rounding issue of the sizes used in drawing the rounded corners or the anti-aliasing effect. Should be straightforward to fix or find a workaround. While I'm finishing my work on my hands, PRs are very welcome :)

**Comment by stepanzalis** [comment]
Hi! Any update on this? 👍

**Comment by ubuntudroid** [comment]
Whohooo! 😍  Many thanks @dsn5ft!

**Comment by agustinsivoplas** [comment]
In my case is more visible when you use odd values like 3,5,7...

<img width="865" alt="Screen Shot 2022-06-09 at 23 26 22" src="https://user-images.githubusercontent.com/1648539/172978678-6e7fb9e0-31a8-4fe7-aed3-63563258b98d.png">
<img width="1133" alt="Screen Shot 2022-06-09 at 23 29 45" src="https://user-images.githubusercontent.com/1648539/172978685-be654bb6-e866-4a9c-8c10-554fa588616b.png">
