### ISSUE TITLE
[MaterialDatePicker] Mix of locales below API 26

### ISSUE THREAD

**Issue by jmartingit** [material-components/material-components-android#1948]
**Description:** In my app I allow the user to select a locale different from the device's locale. On Android 8.0 (API 26) and above, the date picker shows everything correctly, using the locale selected by the user. However, below API 26 the picker shows a mix of the user's locale and the device's locale, like this:

![date_picker](https://user-images.githubusercontent.com/10224766/102884261-9eab5380-4451-11eb-84b5-e184f6fcaff5.png)

In this screenshot, the device's locale was English and the user's locale was Spanish. As the screenshot shows, the title of the picker and the buttons appear correctly (in Spanish, the user's locale), but day names and month names appear incorrectly (in English, the device's locale).

**Expected behavior:** All strings should appear using the selected user's locale in all API's, instead of only API 26+.

**Source code:** Not relevant, as the locale is not selectable in date picker.

**Android API version:** Tested on APIs 16 through 30 with Android Studio emulators.

**Material Library version:** 1.3.0-beta01

**Device:** Tested on APIs 16 through 30 with Android Studio emulators.

**Note:** I don't know if you have this on your plans, but it could be useful to have the option to force the locale when building the picker.

**Comment by abdallahalaraby** [comment]
I'd like to add that in Arabic, the calendar days initials are localized but their integer values are not.

<img width="248" alt="Screen Shot 2020-12-31 at 6 07 27 PM" src="https://user-images.githubusercontent.com/4281191/103417453-6b746d00-4b93-11eb-8916-c944ab14accd.png">
