### ISSUE TITLE
FAB icon tinting

### ISSUE THREAD

**Issue by ViHtarb** [material-components/material-components-android#195]
Hi i found the bug with src image tinting in FAB. 
Case:
Implement in xml FAB with icon and set tint for icon. In code use FAB.setImageDrawable(Drawable) method
and in result for new drawable(icon) tinting not be applied

**Comment by ldjcmu** [comment]
Can you clarify your issue by providing the XML for your FAB as well the code where you modify the FAB? As you have currently described, we would expect the drawable to override the tint.

**Comment by ViHtarb** [comment]
xml
```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_error"
        app:tint="@color/colorPrimary"/>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```
in code in simple main activity
```java
final FloatingActionButton fab = findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                fab.setImageDrawable(ResourcesCompat.getDrawable(getResources(), R.drawable.ic_image, null));
            }
        });
```
And in result for ic_image tint not be applied

**Comment by dsn5ft** [comment]
Thanks for the clarification, created https://issuetracker.google.com/issues/116862250 to track this.

**Comment by Grayforever** [comment]
Setting the tint mode to either add or screen really does the tinting.
