### ISSUE TITLE
[MaterialCardView] Support clipToOutline in a general way

### ISSUE THREAD

**Issue by yogeshpaliyal** [material-components/material-components-android#1950]
**Currently in MaterialCardView I want my card to be cut from all corners without clipping the content, but it is not possible because if I use shape appearance then my card will get default clip if I remove that then my content will be over the corners**

**Comment by daeni01** [comment]
> **Currently in MaterialCardView I want my card to be cut from all corners without clipping the content, but it is not possible because if I use shape appearance then my card will get default clip if I remove that then my content will be over the corners**

**Comment by ikim24** [comment]
Can you elaborate what you mean by "without clipping the content"? If you'd like the content to be padded so that it is within the bounds of the card, you can set the CardView attribute `cardPreventCornerOverlap` to true.

Currently, MaterialCardView is limited to clipping shapes where [`Outline.canClip`](https://developer.android.com/reference/android/graphics/Outline#canClip()) would return true.

**Comment by yogeshpaliyal** [comment]
> Can you elaborate what you mean by "without clipping the content"? If you'd like the content to be padded so that it is within the bounds of the card, you can set the CardView attribute `cardPreventCornerOverlap` to true.
> 
> Currently, MaterialCardView is limited to clipping shapes where [`Outline.canClip`](https://developer.android.com/reference/android/graphics/Outline#canClip()) would return true.

Assume I have a card with a cover image on top and some text below that and the card is cut shape, In material design card view it automatically add clip from all side i want to remove that from card, if I use cardPreventCornerOverlap  then my image will go outside of card from corners

**Comment by drchen** [comment]
I think it's a bug that we only set clip-to-outline when the corner is round.

**Comment by drchen** [comment]
Hi after I double checking, I think this is a limitation of Android framework:
https://developer.android.com/training/material/shadows-clipping#Clip

Only round or rectangle corners can clip the view. 
Unfortunately we are restricted by that and I'll close the issue as infeasible.

**Comment by yogeshpaliyal** [comment]
@drchen It is working great, like this.
https://github.com/android/sunflower/blob/main/app/src/main/java/com/google/samples/apps/sunflower/views/MaskedCardView.kt
