### ISSUE TITLE
[TextInputLayout] Add method(s) to change CornerFamily

### ISSUE THREAD

**Issue by maxkeppeler** [material-components/material-components-android#1957]
**Is your feature request related to a problem? Please describe.**
CornerFamily can only be applied through a style, but it should be programmatically available as well.

**Describe the solution you'd like**
A way to set the ```CornerFamily``` programmatically or to set a custom boxBackground ```ShapeAppearanceModel``` that calls automatically ```applyBoxAttributes``` (just like the method ```setBoxCornerRadii```).

**Additional context**
I want to be able to dynamically set the CornerFamily like the CornerRadius for all corners and each corner individual. I want to offer this flexibility for this component in a programmatic way, as it is possible for other components. In my bottom-sheets library, I allow developers to choose the corner family of their preference. If one wants to use a bottom sheet with the corner family cut, they likely want to have the same corner family look for the TextInputLayout.

**Comment by drchen** [comment]
You can override ?attr/shapeAppearanceOverlay in TextInput styles to achieve that.

**Comment by maxkeppeler** [comment]
I know, but I asked for a dynamic & programmatically way to do this.
