### ISSUE TITLE
[Theme.MaterialComponents] Activity background color not set

### ISSUE THREAD

**Issue by Paget96** [material-components/material-components-android#1958]
**Description:**
Issue started since 1.3.0-alpha04, but not affect all the devices. I personally don't have issue, neither I am possible to reproduce it, while some of the users have it. I have attached video of the issue. Background should be dark as I set in theme.
I'm using the same approach for years without issues.

This is the line used for the background

```
<style name="AppTheme.Dark" parent="Theme.MaterialComponents">
        <item name="colorPrimary">@color/dark_color_primary</item>
        <item name="colorPrimaryVariant">@color/dark_color_primary_dark</item>
        <item name="colorAccent">@color/dark_color_accent</item>

        <item name="overflowLayoutBackground">@color/dark_overflow_layout_background_color</item>
        <item name="cardOverflowBackground">@color/dark_card_overflow_background_color</item>
        <item name="android:windowBackground">@color/dark_background_color</item>
        <item name="infoCircleBackground">@color/dark_overflow_layout_background_color</item>
</style>
```

https://user-images.githubusercontent.com/10515077/103436796-d4a1c200-4c1f-11eb-969e-954ed969e914.mp4

**Android API version:** 29

**Material Library version:** 1.3.0-alpha04 - 1.3.0-beta01

**Device:** Samsung Note 10+

**Comment by Paget96** [comment]
> Is this still an issue? Activity background color is not handled by the Material library so I'm not sure what happened with your activity. It will be helpful if you can provide more info like the code sections about how you set the activity theme and activity background.

Still an issue, I have "fixed" it with creating a drawable

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <gradient
        android:angle="90"
        android:endColor="#ffffff"
        android:startColor="@color/md_theme_light_background" />
</shape>
```

And then apply it to **android:windowBackground**

**Comment by drchen** [comment]
If don't override android:windowBackground in your custom theme at all, will that work?

**Comment by Paget96** [comment]
> If don't override android:windowBackground in your custom theme at all, will that work?

If I go without it, then I have issue with animations from constraint layout.

**Comment by drchen** [comment]
I'm wondering if it's an issue only happens on certain devices? Since android:windowBackground is totally beyond our control and if you already have a working solution for this, I'll close the issue. : )

**Comment by Paget96** [comment]
> I'm wondering if it's an issue only happens on certain devices? Since android:windowBackground is totally beyond our control and if you already have a working solution for this, I'll close the issue. : )

Solution is to use a drawable as the reference for windowBackground. :)

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <gradient
        android:angle="90"
        android:endColor="#ffffff"
        android:startColor="@color/md_theme_light_background" />
</shape>
```
