### ISSUE TITLE
Where are the Kotlin samples for DatePicker

### ISSUE THREAD

**Issue by IgorGanapolsky** [material-components/material-components-android#1959]
**Is your feature request related to a problem? Please describe.**
The problem is that the sample for DatePicker is all in Java, and is all hard-coded boilerplate implentation.  It doesn't resemble real-world coding in Kotlin and Material Components.

**Describe the solution you'd like**
I'd like a Kotlin solution and using modern Material components in layout files, instead of hard-coding everything in Java.

**Describe alternatives you've considered**
Tried to plug these classes into XML layout files.

**Additional context**
In 2021 we want Kotlin.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Can you explain more about what Kotlin samples you are looking for? Java and Kotlin are interoperable so I'm wondering what makes you unable to use Material components?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with more explanations.
