### ISSUE TITLE
 [TabLayout] TextSize changes when interacts with Fragment elements

### ISSUE THREAD

**Issue by Geck0x86** [material-components/material-components-android#196]
Description: When switch state or checkbox state of Fragment inside Tab changes textSize of tab title changes too. Changing it for single line to multiline and vice versa.

Expected behavior:
Before
![Before](https://image.ibb.co/iyDmqU/ab.png)

After
![After](https://preview.ibb.co/dRvGqU/abc.png)

Design Library Version: 'com.google.android.material:material:1.0.0-rc02'

Android API version: All version

Device: All devices

**Comment by shivam2702** [comment]
> private fun getSelectedText(chipGroup: ChipGroup, id: Int): String {
        val mySelection = chipGroup.findViewById<Chip>(id)
        return mySelection?.text?.toString() ?: ""
    } 

You can use this `val mySelection = chipGroup.findViewById<Chip>(id)` to get the selectedChip and the complete fuction will look like

> filterChips.setOnCheckedChangeListener { chipGroup, i ->
              getSelectedText(chipGroup, i)
            }

**Comment by Geck0x86** [comment]
Hello, I have prepared a repository on GitHub with an example of behavior.

When doing it step by step, I have noticed that this unexpected behavior occurs when the TabLayout and the Viewpager are inside a NestedScrollView.

Example project link: https://github.com/Geck0x86/TabLayoutIssue


    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fillViewport="true"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <com.google.android.material.tabs.TabLayout
                android:id="@+id/tabLayout"
                style="@style/Theme.HA.TabLayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:tabGravity="fill"
                app:tabIndicatorHeight="2dp" />

            <androidx.viewpager.widget.ViewPager
                android:id="@+id/viewPager"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                app:layout_behavior="@string/appbar_scrolling_view_behavior" />
        </LinearLayout>
    </androidx.core.widget.NestedScrollView>

**Comment by Geck0x86** [comment]
Some news about this?
I upgraded to com.google.android.material:material:1.1.0-alpha02 but the problem keeps happening

**Comment by ikim24** [comment]
Closing this and tracking in https://issuetracker.google.com/issues/115396609
