### ISSUE TITLE
[Date Picker] Selected date text not aligned vertically when running in fragment scenario

### ISSUE THREAD

**Issue by sampengilly** [material-components/material-components-android#1960]
**Description:** 

This issue is somewhat minor since it only affects testing, but when doing screenshot testing and manual screenshot reviews for content and layout correctness by non-devs it becomes a bit more of an issue.

When opening the Material Date Picker inside a fragment scenario test (overriding the theme with the app's theme), the selected date text is incorrectly aligned. This only occurs in fragment scenario tests and not when the app is run normally. It is also the only difference I can spot between the app theme running in an app versus the same app theme running in a fragment scenario.

Screenshot from layout inspector showing border, from what I can tell the view appears to be missing its `paddingTop` property when run in a fragment scenario test:
![image](https://user-images.githubusercontent.com/1129772/103495978-47ad7180-4e88-11eb-8935-71ba61bd5a33.png)

**Expected behavior:** 

Calendar should have the correct text alignment
![image](https://user-images.githubusercontent.com/1129772/103496128-c7d3d700-4e88-11eb-84b4-5a1653b9d731.png)

**Android API version:** 29

**Material Library version:** 1.3.0-alpha04

**Device:** Samsung Galaxy S10, though I've seen it occur on other devices and in the emulator

**Comment by drchen** [comment]
Is this still happening with Material 3 themes/styles?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Comment by WolandPL** [comment]
@drchen Yes, still happening on Material 1.6.1 Material3.Light.NoActionBar
![image](https://user-images.githubusercontent.com/29288691/189705464-869b97c0-1c34-4a53-874e-c40f268d901a.png)
