### ISSUE TITLE
[TextInputLayout] [TextInputEditText] Setting the background to transparent doesn't render outlinedbox or filledbox

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#1980]
**Description:**
Perhaps this issue is more about NOT relying on setting either the `TextInputLayout` or `TextInputEditText` background to be transparent in order to use the no-background text field (neither outlinedbox nor filledbox).

The following causes not to render the outlinedbox or filledbox:
```
<com.google.android.material.textfield.TextInputLayout
   ...
   android:background="@android:color/transparent"
   ...
</com.google.android.material.textfield.TextInputLayout>

OR

<com.google.android.material.textfield.TextInputEditText
   ...
   android:background="@android:color/transparent"
   ...
</com.google.android.material.textfield.TextInputLayout>
```

**Expected behavior:**
If the **style** hasn't been specified, then the component should default to the no-background text field (neither outlinedbox nor filledbox).

android:background="@android:color/transparent" should do the same as android:background="@null". Setting the background to `null` renders properly the `TextInputLayout`.

<details>
<summary> Background Null Screen</summary>

<img src="https://user-images.githubusercontent.com/1494577/104361616-8e721b80-54c7-11eb-9c56-56034c349d49.png" width="400"/>
</details>

**Source code:**
```
    <com.google.android.material.textfield.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:id="@+id/text_input_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="@{item.title}"
        app:errorEnabled="true"
        app:counterEnabled="@{item.maxLength != null}"
        app:counterMaxLength="@{item.maxLength}"
        app:helperText="@{item.helperTextString}">
<!--  android:background="@android:color/transparent" -->

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/text_input_edit_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/transparent"
            android:maxLength="@{item.maxLength}"
            android:text="@={item.valueString}"/>
    </com.google.android.material.textfield.TextInputLayout>
```

<details>
<summary> Background Transparent Screen</summary>

<img src="https://user-images.githubusercontent.com/1494577/104361402-3e935480-54c7-11eb-8720-7c0e2c7716b2.png" width="400"/>
</details>

**Android API version:**
30

**Material Library version:** 
com.google.android.material:material:1.3.0-alpha04

**Device:** 
Pixel 4XL

**Comment by drchen** [comment]
Please use boxBackgroundMode="none" to achieve what you need. TextInputLayout doesn't really support android:background attribute.
