### ISSUE TITLE
[TextInputLayout] Placeholder gravity not working as expected 

### ISSUE THREAD

**Issue by AlaaZarifa** [material-components/material-components-android#1981]
**Description:** 
I set the gravity inside `placeholderTextAppearance` as **center**  to match the text alignment of the `TextInputEditText` but it did not center. I've also centered the placeholder `textAlignment` and still no effect. 

**Expected behavior:** The text gravity of the placeholder should be as set in `placeholderTextAppearance`.

**Source code:** 

**style**
```
<style name="PlaceholderTextStyle" parent="TextAppearance.Design.Placeholder">
        <item name="android:textColor">@color/blueGeryLight</item>
        <item name="android:textSize">@dimen/text_medium</item>
        <item name="android:gravity">center</item>
        <item name="android:textAlignment">center</item>
    </style>
```

**TextInputLayout code**
```
    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/inputMobile"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginHorizontal="20dp"
        android:layout_marginVertical="5dp"
        android:clipToPadding="false"
        android:hint="Passengers Limit"
        android:paddingVertical="0dp"
        android:textColorHint="@color/blueGery"
        app:boxBackgroundColor="@color/white"
        app:boxBackgroundMode="filled"
        app:boxCollapsedPaddingTop="12dp"
        app:boxCornerRadiusBottomEnd="12dp"
        app:boxCornerRadiusBottomStart="12dp"
        app:boxCornerRadiusTopEnd="12dp"
        app:boxCornerRadiusTopStart="12dp"
        app:boxStrokeWidth="0dp"
        app:boxStrokeWidthFocused="0dp"
        app:expandedHintEnabled="false"
        app:hintTextAppearance="@style/FloatingHintTextStyle"
        app:placeholderText="01"
        app:placeholderTextAppearance="@style/PlaceholderTextStyle">

        <com.google.android.material.textfield.TextInputEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="number"
            android:textAlignment="center"
            android:textColor="@color/blueGeryLight"
            android:textSize="@dimen/text_medium" />

    </com.google.android.material.textfield.TextInputLayout>
```

**Picture**

![image](https://user-images.githubusercontent.com/18426012/104440627-458b9700-559b-11eb-9138-b86cb698d942.png)

**Android API version:** 29

**Material Library version:** 1.3.0-beta01

**Device:** Xiaomi Pocophone F1

**Comment by pekingme** [comment]
Thanks for reporting this! It's not working because neither `android:gravity` nor `android:textAlignemnt` is an attribute of [`textApperance`](https://developer.android.com/guide/topics/ui/look-and-feel/themes#textappearance). I think the ideal fix is to add an new attribute for the placeholder `TextView`'s gravity. But the quick workaround is to use `android:hint` and `android:textColorHint` within `TextInputEditText` instead of `placeholderText`.

**Comment by AlaaZarifa** [comment]
@pekingme I see the issue. The workaround did work just fine for now, but I had to use `textAlignment="center"` instead of `gravity="center"` inside the `TextInputEditText` because gravity centers the TextInputLayout hint as well. Anyhow, thanks for the tip.

**Comment by drchen** [comment]
I'll close the issue since it looks like WAI. Not sure if there's a good solution to add a new attribute to support placeholder's gravity, but feel free to file a feature request if you think it can be helpful.
