### ISSUE TITLE
TextInputLayout AutoCompleteTextView not showing correctly

### ISSUE THREAD

**Issue by ranco980** [material-components/material-components-android#1989]
I created a spinner using `TextInputLayout ` `AutoCompleteTextView ` and `OutlinedBox.ExposedDropdownMenu` style but the hint is not showing correctly. 

See image 

![WhatsApp Image 2021-01-15 at 17 16 59](https://user-images.githubusercontent.com/45541006/104745962-54b74400-5757-11eb-878a-0270639cc33b.jpeg)

You can see how `gender `hint is overlapping the `OutlinedBox ` 

This is the code

```
    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".screens.profile.ProfileFragment">

        <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/profile_sp_gender_layout"
            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
            android:layout_width="wrap_content"
            android:layout_height="0dp"
            android:layout_marginStart="16dp"
            android:hint="@string/profile_gender_hint"
            android:minWidth="120dp"
            app:layout_constraintBottom_toBottomOf="@+id/profile_et_name_layout"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="@+id/profile_et_name_layout">

            <AutoCompleteTextView
                android:id="@+id/profile_sp_gender"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="?attr/colorSurface"
                android:backgroundTint="?attr/colorSurface"
                android:inputType="none" />
        </com.google.android.material.textfield.TextInputLayout>

        <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/profile_et_name_layout"
            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="8dp"
            android:layout_marginTop="16dp"
            android:layout_marginEnd="16dp"
            android:hint="@string/sign_name_hint"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@+id/profile_sp_gender_layout"
            app:layout_constraintTop_toTopOf="parent">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/sign_et_name"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="text"
                android:text="@={viewModel.displayName}" />
        </com.google.android.material.textfield.TextInputLayout>
```

**Material Library version:** I used `material:1.2.1` but also tried the latest `material:1.3.0-rc01'`

**Device:** Samsung galaxy s8 SM-G950F API 28

**Comment by ikim24** [comment]
If you remove these two lines from the `AutoCompleteTextView` the hint should show appropriately. The outlined style for TextInputLayout works when the child view (e.g. AutoCompleteTextView or TextInputEditText) doesn't have its own background.

```
android:background="?attr/colorSurface"
android:backgroundTint="?attr/colorSurface"
```

**Comment by ranco980** [comment]
It is no show correctly but that is still a bug. If the `AutoCompleteTextView` cannot work well with `android:background`, it should not be available

**Comment by rmirabelle** [comment]
I can confirm that setting `android:background="@null"` on the `AutoCompleteTextView` restores proper outline style to the `TextInputLayout`.  

I definitely consider this a bug, as I expect no developer on earth to be forced to remember to manually set a `@null` background on the child `AutoCompleteTextView` in order to get the `TextInputLayout` to function as expected.

**Comment by notmyHubG** [comment]
Using `android:background="@null"` does not work for my dropdown. Not background is set elsewhere. Any other possible causes?

**Comment by Ekalips** [comment]
Seems like this issue is fully fixed in the `com.google.android.material:material:1.9.0`
