### ISSUE TITLE
AlertDialog has filled buttons when using "Theme.MaterialComponents.Light.NoActionBar"

### ISSUE THREAD

**Issue by BjarnBronsveld** [material-components/material-components-android#199]
This is a duplicate of issue #162 as it was closed but I do not believe it is the right solution, but a workaround.

Sounds like a bug to me?

**Comment by dsn5ft** [comment]
Created https://issuetracker.google.com/issues/116861837 to track this.

**Comment by gsajith** [comment]
Hi!

Our recommendation here is that you use android.support.v7.app.AlertDialog whenever possible. An app using an AppCompat theme should be using the AppCompat AlertDialog, as the framework AlertDialog has undefined behavior across several API versions re: custom view inflation.

**Comment by kimcy929** [comment]
Even, the android.support.v7.app.AlertDialog is a big size(wrong size). Please improve. I reported this for a long time on the issuestracker but the version 1.0.0 only rc02. No improvement no fix anymore.
