### ISSUE TITLE
[SearchView] RTL doesn't apply to R.id.search_src_text

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#1990]
**Description:** When changing the layout direction, the `SearchView` hint text or input text are not honoring the setting.

Hint/Input text look **incorrect** when RTL:
<details>
<summary>RTL Screens</summary>

| Hint Text | Input Text |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1494577/104783100-3262fd80-573a-11eb-987a-875c9731ae20.png" width="300"/> | <img src="https://user-images.githubusercontent.com/1494577/104783136-4149b000-573a-11eb-9a1d-2100368f1efd.png" width="300"/> | 
</details>

Hint/Input text look correct when LTR:
<details>
<summary>LTR Screens</summary>

| Hint Text | Input Text |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1494577/104783242-7229e500-573a-11eb-96b0-1402a3bef15c.png" width="300"/> | <img src="https://user-images.githubusercontent.com/1494577/104783369-bae19e00-573a-11eb-8116-044e95ca6d0f.png" width="300"/> | 
</details>

**Expected behavior:** To honor the setting

**Source code:** 

**Android API version:** 29

**Material Library version:** com.google.android.material:material:1.2.1

**Device:** Pixel 4XL

**Comment by pekingme** [comment]
Hi @sabinebarrera, I believe this is the nature of `SearchView`. If you try to enter some digits or letters of language in RTL fashion, it should align to the right side.

**Comment by pekingme** [comment]
Feel free to reopen if I misunderstood the issue.

**Comment by sabinebarrera** [comment]
Hi @pekingme, the `SearchView` is not aligning to the right side... that is the issue.
