### ISSUE TITLE
[MaterialCardView] Check Icon could not be tinted on Android < 21

### ISSUE THREAD

**Issue by avianey** [material-components/material-components-android#1993]
**Description:** 

When using a checkable MaterialCardView
When checking the MaterialCardView
The CheckIcon is black whatever the tint of the set drawable or drawable resource

**Expected behavior:** 

The check icon is tinted as specified

**Source code:** 

All of those solutions are not working :

When using plain XML :

```
<com.google.android.material.card.MaterialCardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:cardBackgroundColor="?android:attr/colorBackground"
    app:cardCornerRadius="6dip"
    app:cardForegroundColor="@android:color/transparent"
    app:strokeColor="?colorSecondary"
    app:strokeWidth="@dimen/stroke_width"
    android:checkable="true"
    app:checkedIcon="@drawable/check"
    app:checkedIconTint="?colorOnBackground"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
```

When using plain code :

```
            MaterialCardView.isChecked = true
            MaterialCardView.checkedIconTint = ColorStateList.valueOf(colorOnBackground)
            MaterialCardView.checkedIcon = DrawableCompat.wrap(resources.getDrawable(R.drawable.lock))
                    .apply {
                        DrawableCompat.setTint(this, colorOnBackground)
                    }
```

Not that setting a wrapped / tinted DrawableCompat drawable everywhere else workes as expected (ImageView, View Background, etc...) but not the checked drawable of MaterialCardView

```
DrawableCompat.wrap(resources.getDrawable(R.drawable.lock))
                   .apply {
                        DrawableCompat.setTint(this, colorOnBackground)
                    }
```

**Android API version:** 16, 17, 18, 19, 20

**Material Library version:** 1.2.1 AND 1.3.0-rc01

**Device:** Emulators

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
We are investigating it. For now please try to use a color state list as checkedIconTint to workaround the issue, which should work. : )
