### ISSUE TITLE
[MaterialButton] Text misalignment with icon with viewStart alignment

### ISSUE THREAD

**Issue by bmc08gt** [material-components/material-components-android#1996]
**Description:** 
TextAlignment is being offset based on the icon intrinsicWidth when set as `viewStart` causing the button text to not be properly centered. This is more prominently seen when the button's width is set at match_constraints as opposed to wrap_content.

**Expected behavior:** 
Button text to remain horizontally centered regardless of icon placement.

**Android API version:** 
API 29 and 30 tested so far

**Material Library version:** 
'com.google.android.material:material:1.2.1'

**Device:** 
Pixel 3 XL and Pixel 4 XL (so far)

**Comment by bmc08gt** [comment]
Adjusted the iconPadding based on the intrinsicWidth of the icon is a way to resolve this: 
```
fun MaterialButton.adjustForIconIntrinsicWidth() {
    iconPadding = -(icon?.intrinsicWidth ?: 0)
}
```.
I'll look into PR'ing this as well.

**Comment by pekingme** [comment]
Thanks for reporting and opening a PR, @bmc08gt. If I understand correctly, icons should be placed next to text labels to clarify an action and call attention to a button. In case that the button is much wider than the content (icon and text label), the whole content should be centered. Could you elaborate your use case with screenshots a bit more?

**Comment by bmc08gt** [comment]
the current usecase/requirement is to align the icon to `viewStart` via `iconGravity` with the button width being constrained to 80% of width of the screen. With these attributes setup the button's text isn't properly centered like it is if you use `textStart` for the `iconGravity`. Does that make sense?

**Comment by pekingme** [comment]
Thanks for clarifying. Here's the screenshot of two icon buttons respectively using `app:iconGravity="textStart"` and `app:iconGravity="start"`. The button's text are aligned. 
![image](https://user-images.githubusercontent.com/8545955/105392744-63c34980-5bd0-11eb-9f54-5151845315ed.png)
Not sure if I fully understand what you meant "properly centered". For `app:iconGravity="start"` case, the text is not centered with respect to the whole button, but the space left between icon and the other side. Setting the `iconPadding` to a negative value is the workaround to move the text to the center of the whole button. But I think it's more like the solution for a special use case. Besides, it can potentially make text and icon overlap on each other when the text is long enough.

**Comment by omer-jan** [comment]
> app:iconGravity="textStart"

thank you so much it works for me 
```
<Button
                android:layout_marginStart="15dp"
                android:layout_marginEnd="15dp"
                android:layout_marginTop="5dp"
                android:paddingStart="6dp"
                android:paddingEnd="6dp"
                android:id="@+id/btn_about_checkForUpdate"
                android:layout_width="match_parent"
                android:gravity="center"
                app:iconGravity="textStart"
                android:layout_height="wrap_content"
                android:backgroundTint="@color/light_blue_900"
                app:icon="@drawable/ic_sync"
                android:text="Check for update"
                tools:ignore="MissingPrefix" />
```

**Comment by gnovakovski** [comment]
Since the -(icon?.intrinsicWidth ?: 0) approach leads to overlapping of text and icon when in wrap_content, a better solution is to add a paddingRight with the icon + normal padding. Something like 

```
paddingEnd = padding + (icon?.intrinsicWidth ?: 0) 

setPaddingRelative(padding, 0, paddingEnd, 0)
```
