### ISSUE TITLE
Enhancement - Add selected menu item to BottomNavigationView

### ISSUE THREAD

**Issue by jotaemepereira** [material-components/material-components-android#20]
### Overview

In the BottomNavigationView, there is no method to explicitly select a menu item.

Sometimes we need to move to another menu item when some action is done, is like moving to a particular tab like using ViewPager and TabLayout.

It also helps to click on a tab when doing espresso tests.

I worked on a PR to add this.

**Comment by MGaetan89** [comment]
This is possible since at least version 1.0.0: https://github.com/material-components/material-components-android/blob/1.0.0/lib/java/com/google/android/material/bottomnavigation/BottomNavigationView.java#L402
