### ISSUE TITLE
[MaterialDatePicker] days of the week not colored correctly

### ISSUE THREAD

**Issue by larabear** [material-components/material-components-android#2002]
I'm trying to apply custom theming to date picker by overriding colorPrimary to a blue shade, colorSurface to a dark gray shade and colorOnSurface to a light gray shade for dark mode.
Though most parts of the UI are colored correctly, the days of the week are not.

[Screenshot](https://photos.app.goo.gl/N39nWJumUfFWcijo9) (Notice how days of the week are black).

**Expected behavior:** Days of the week use colorOnSurface

**Source code:** I think DaysOfWeekAdapter.java isn't applying styling to the text like MonthAdapter.java or YearGridAdapter.java do, which I suspect is a bug.

**Android API version:** 10

**Material Library version:** 1.2.0

**Device:** Pixel3

**Comment by larabear** [comment]
Similar to [this issue](https://github.com/material-components/material-components-android/issues/1966) where part of the UI is not properly colored

**Comment by pekingme** [comment]
Thanks for reporting this! Unfortunately, the "days of week" is not a part of the `DatePicker`'s style. We currently don't have any near plan to update it. A possible workaround to customize that text's color is to add a `materialThemeOverlay` to override `android:textColorPrimary`.

**Comment by larabear** [comment]
Hi @pekingme, thanks for the suggestion for the workaround. I tried the overlay approach but it didn't work
Here are what I've tried
1.
```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
    <item name="materialCalendarStyle">@style/DatePickerThemeDark</item>
</style>
<style name="DatePickerThemeDark"
         parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar"
      >
    <item name="colorPrimary">@color/blue</item>
    <item name="colorSurface">@color/surface</item>
    <item name="colorOnSurface">@color/on_surface</item>
    <item name="android:textColorPrimary">@color/white</item>
</style>
```
2.
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
    <item name="materialCalendarStyle">@style/DatePickerThemeDark</item>
</style>
<style name="DatePickerThemeDark"
         parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar"
      >
    <item name="colorPrimary">@color/blue</item>
    <item name="colorSurface">@color/surface</item>
    <item name="colorOnSurface">@color/on_surface</item>
    <item name="materialThemeOverlay">@style/DatePickerThemeDarkOverlay</item>
</style>
<style name="DatePickerThemeDarkOverlay" parent="">
    <item name="android:textColorPrimary">@color/white</item>
</style>
```

**Comment by larabear** [comment]
@pekingme ah "android:textColor" worked!

**Comment by drchen** [comment]
BTW the issue has been fixed recently.

Now you can override ?attr/materialCalendarDayOfWeekLabel to customize day of week label style.
