### ISSUE TITLE
[LinearProgressIndicator] LinearProgressIndicator does not show when using AndroidX Fragment 1.3.0-rc01

### ISSUE THREAD

**Issue by wbervoets** [material-components/material-components-android#2004]
**Description:**

LinearProgressIndicator in Material components 1.3.0-rc01 does not show when using AndroidX Fragment 1.3.0-rc01
The same code works correctly with Fragment 1.2.5

**Expected behavior:** 
LinearProgressIndicator should also work with AndroidX Fragment 1.3.0-rc01

**Android API version:**

Android 10

**Material Library version:**

1.3.0-rc01

**Device:** 

Emulator API 30

**Comment by pekingme** [comment]
Duplicate of #1972
