### ISSUE TITLE
[CircularProgressIndicator] Error inflating class CircularProgressIndicator with API 19

### ISSUE THREAD

**Issue by renaudmathieu** [material-components/material-components-android#2005]
**Description:** Problem using themed CircularProgressIndicator with **API 19**

**Expected behavior:** No crash

**Source code:** 

Having the following main theme : 
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <!-- Base theme, all common styling here -->
    <style name="Base.IO" parent="@style/Theme.MaterialComponents.Light.NoActionBar">
            ...
            <item name="circularProgressIndicatorStyle">@style/Widget.IO.CircularProgressIndicator
        </item>
    </style>

</resources>
```

and this styles: 
```xml
<resources>
    <style name="Widget.IO.CircularProgressIndicator" parent="Widget.MaterialComponents.ProgressIndicator">
        <item name="materialThemeOverlay">@style/ThemeOverlay.IO.ProgressIndicator</item>
        <item name="trackThickness">20dp</item>
    </style>

    <style name="ThemeOverlay.IO.ProgressIndicator" parent="">
        <item name="colorPrimary">@color/watermelon</item>
    </style>
</resources>

```

I got the following crash:
```
Binary XML file line #46: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
```

Reason seems to be : `trackThickness`

**Android API version:** 19

**Material Library version:** `1.3.0-rc01`

**Device:** Simulator Pixel 2 API 19

**Comment by ronbarrera** [comment]
I'm getting the same error: Error inflating class CircularProgressIndicator

Any idea how to resolve it?

**Comment by renaudmathieu** [comment]
Which version are you using @ronbarrera ? It works fine now since the fix was pushed

**Comment by ronbarrera** [comment]
@renaudmathieu I'm using

'com.google.android.material:material:1.4.0'

However, I was inflating a view like this: 

`  
val inflater = LayoutInflater.from(application.applicationContext)
val binding = DataBindingUtil.inflate(inflater, R.layout.item_view, null, false)`

and then later adding that view in recyclerview. 

For some reason, ProgressBar works but not CircularProgressIndicator.
