### ISSUE TITLE
[<TextInputLayout>] How to change underline color programatically?

### ISSUE THREAD

**Issue by Kerooker** [material-components/material-components-android#201]
How can I change the underline color from the text input layout?

In Material Design guidelines, it's referred as "Activation indicator" https://material.io/design/components/text-fields.html#anatomy

But I couldn't find any way to change it's color consistently.

Using setBackgroundTint changed the color, but once it's focused the color resets to default. How am I able to change the underline color?

**Comment by csbenz** [comment]
Need this too. Do you know how to set the underline color in xml? Internet says to use 'colorControlNormal' theme attribute, but it's not working for me.

**Comment by Kerooker** [comment]
I'm sorry for writing this code. I'm very ashamed of it, but it works :P

**Comment by csbenz** [comment]
That's... actually impressive.

Thanks for the solution, I'll try it out and hopefully the library opens an official API for changing it more easily.

**Comment by dsn5ft** [comment]
We are currently working on color system updates for all of the components, which should make things like underline color more configurable.

However, for now you should also be able to use a Theme Overlay that sets the colorControlActivated attribute.

**Comment by dsn5ft** [comment]
Sure, closing now.

**Comment by nvvasilescu** [comment]
we need to be able to get rid of the boxUnderline when the state is BOX_BACKGROUND_FILLED. There's absolutely no way to hide this line if we need to use BOX_BACKGROUND_FILLED.

**Comment by emathew80** [comment]
Any more updates on this functionality? I really want to programmatically change the underline text color without having to update the entire app theme...

**Comment by jrcacd** [comment]
When will this be fixed?

**Comment by zeroarst** [comment]
Looking for the solution as well....

**Comment by shalbert94** [comment]
Using version `1.1.0-alpha09`. Learned that the Activation Indicator's color is set by 
`<item name="colorOnSurface">[color]</item>`
If you cannot change the value of this `<item/>` in your `AppTheme`, then 
1. Create a `<style/>` with `<item name="colorOnSurface">[color]</item>` set the the color of your background.
2. Add `android:theme="@style/[name of the style created in step 1]"` to your `TextInputLayout` 

That made it disappear for me

**Comment by deathofshit** [comment]
bug is still there with alpha-10. when i change the colorOnSurface, hint color changes. @Kerooker 's fix seems to be only solution for now.
