### ISSUE TITLE
[Toolbar] How to center title of MaterialToolbar? 

### ISSUE THREAD

**Issue by lencetanaskoska** [material-components/material-components-android#2011]
I am trying to center the title of the MaterialToolbar, tried to add android: gravity but it doesn't work. There is no info in the documentation on how to center it 

```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout  xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

        <com.google.android.material.appbar.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:liftOnScroll="true"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            android:focusable="false"
            app:liftOnScrollTargetViewId="@id/brokers_recycler_view"
            app:expanded="false">

            <com.google.android.material.appbar.MaterialToolbar
                android:id="@+id/material_toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:gravity="center_horizontal"
                android:elevation="0dp"
                app:layout_scrollFlags="scroll|enterAlways|snap|exitUntilCollapsed"
                app:contentInsetLeft="@dimen/margin_16"
                app:contentInsetStart="@dimen/margin_16"
                app:menu="@menu/toolbar_menu"
                app:titleTextAppearance="@style/TextAppearance.App.CollapsingToolbar.Collapsed"/>


        </com.google.android.material.appbar.AppBarLayout>
              
        ....
         
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Comment by pekingme** [comment]
I'm a bit confused. The toolbar has `match_parent` layout width. What do you mean it's not centered? Could you explain with a screenshot which part you want to center?

**Comment by lencetanaskoska** [comment]
The title is aligned to the start as in the screenshot:

![Screen Shot 2021-01-28 at 08 24 27](https://user-images.githubusercontent.com/17854276/106104119-49deb500-6142-11eb-83f8-75b999ca3811.png)

And I am trying to align into the center of the MaterialToolbar without using a custom layout, so the title will look like this:
![Screen Shot 2021-01-28 at 08 26 36](https://user-images.githubusercontent.com/17854276/106104637-0173c700-6143-11eb-908e-17837764036c.png)

**Comment by pekingme** [comment]
I see. Sorry, I missed the "title" part. Unfortunately, `MaterialToolbar` on Android doesn't support title centering. It's more like an iOS style. The workaround is to not set title in `MaterialToolbar` but add a `TextView` in its embed body (with `android:layout_gravity="center_horizontal"`).

**Comment by lencetanaskoska** [comment]
Can we expect that MaterialToolbar's title alignment will be added in a future version?

**Comment by pekingme** [comment]
I'll leave it open in our backlog. But I don't think it will be prioritized in the near future.

**Comment by luisventura** [comment]
@pekingme thanks for that workaround, it does the job, but makes styling a little harder. I've search for this for a long time, almost everyone suggest to add padding, because layout breaks when adding navigation/menu icon. Clearer documentation could be enough.

**Comment by dsn5ft** [comment]
Hi @luisventura, we recently added support for centered titles to `MaterialToolbar` via the new `app:titleCentered` and `app:subtitleCentered` attributes, in the commit linked above (cbf528e3a6deaa2bc39d0836b3a850b27c2ada49). That's why this issue was closed.

It will be included in our next alpha release, but in the meantime you can try it out with our [snapshot release](https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md).

**Comment by abhatnagar03** [comment]
@dsn5ft app:titleCentered is not working for me. My code:

<com.google.android.material.appbar.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="128dp"
            app:liftOnScroll="true">

            <com.google.android.material.appbar.CollapsingToolbarLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:collapsedTitleTextAppearance="@style/TextAppearance.App.CollapsingToolbar.Collapsed"
                app:contentScrim="?attr/colorPrimary"
                app:expandedTitleMarginBottom="28dp"
                app:expandedTitleTextAppearance="@style/TextAppearance.App.CollapsingToolbar.Expanded"
                app:layout_scrollFlags="scroll|exitUntilCollapsed|snap"
                app:statusBarScrim="?attr/colorPrimaryVariant">

                <com.google.android.material.appbar.MaterialToolbar
                    android:id="@+id/topAppBar"
                    style="@style/Widget.MaterialComponents.Toolbar.Primary"
                    android:layout_width="match_parent"
                    android:layout_height="?attr/actionBarSize"
                    android:elevation="0dp"
                    app:layout_collapseMode="pin"
                    app:menu="@menu/top_app_bar"
                    app:title="@string/app_name"
                    app:titleCentered="true">
                </com.google.android.material.appbar.MaterialToolbar>
            </com.google.android.material.appbar.CollapsingToolbarLayout>
        </com.google.android.material.appbar.AppBarLayout>

I am implementing the "prominent top app bar" and using material library version "1.4.0-alpha02".

Can you please help me here?

**Comment by dsn5ft** [comment]
Hi @abhatnagar03, by default CollapsingToolbarLayout will hide the nested Toolbar's title and draw its own title text, which it needs to do for the collapsing text animation. That's why setting `app:titleCentered="true"` on the nested MaterialToolbar has no effect in this case.

Can you try either setting `app:titleEnabled="false"` on the CollapsingToolbarLayout to make it use the MaterialToolbar's title (not sure how well that will work as it may break the look of the collapsing text animation). Or can you try setting `app:expandedTitleGravity="bottom|center_horizontal"` on your CollapsingToolbarLayout? (there's also an `app:collapsedTitleGravity` attribute for when the title is collapsed).

**Comment by abhatnagar03** [comment]
app:collapsedTitleGravity ="bottom|center_horizontal" works, thanks!

**Comment by Sandylaha** [comment]
app:titleCentered="true"
Add it in MaterialToolbar.

**Comment by arnold-wafula** [comment]
Worked for me. Thanks

**Comment by mostafaElkadiri** [comment]
app:titleCentered="true"
Add it in MaterialToolbar.
Worked for me. Thank you so much.

**Comment by Ttoml33** [comment]
and how do I modify the tittle font...I have tried adding style attribute and implmented in the resources files but it didn't chnge

**Comment by sagar-aecor** [comment]
Hi @Ttoml33  Answering to your query:

add this in MaterialToolbar--
app:titleTextAppearance="@style/ToolbarTextViewStyle"

and add this in themes.xml--
<style name="ToolbarTextViewStyle">
        <item name="android:fontFamily">@font/Roboto_Medium</item>
        <item name="android:textSize">20sp</item>
</style>

**Comment by sagar091** [comment]
Hi @Ttoml33 
Answering to your query:

add this in MaterialToolbar--
app:titleTextAppearance="@style/ToolbarTextViewStyle"

and add this in themes.xml--
<style name="ToolbarTextViewStyle">
        <item name="android:fontFamily">@font/Roboto_Medium</item>
        <item name="android:textSize">20sp</item>
</style>

**Comment by sagar091** [comment]
@dsn5ft  can you please tell me is this feasible to put icon and title in material toolbar without adding any control other than material toolbar. pls check the attached image for reference.

![Home](https://github.com/material-components/material-components-android/assets/6604346/cb655682-6b87-4427-8659-bcc0bd42dcd8)
