### ISSUE TITLE
[transition] strictmode.LeakedClosableViolation on Android 11

### ISSUE THREAD

**Issue by adityashri7** [material-components/material-components-android#2021]
**Description:**
 When Strict Mode `.detectLeakedClosableObjects()` is enabled,  when doing a shared element transition using the Material Transition library, it is observed that after a few trials it crashes on Android 11 devices

**Expected behavior:** 
No crash even after doing the Shared Element Transition many times.

**Steps to reproduce:** 
This can be reproduced by adding 

`
 StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder()
              .detectAll()
              .penaltyLog()
              .build())
`
`
StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder()
              .detectLeakedSqlLiteObjects()
              .detectLeakedClosableObjects()
              .penaltyLog()
              .penaltyDeath()
              .build())
`

to the DisneyApplication onCreate, for example in the [Disney Motions demonstration of the Material Transitions.](https://github.com/skydoves/DisneyMotions)

And then after running the app, open and close a Disney card multiple times on an android 11 device until it crashes. We have been noticing a crash after about every 15-16 times.

**Stacktrace:**
`
D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. Callsite: readFromParcel
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1929)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:305)
        at android.view.SurfaceControl.finalize(SurfaceControl.java:1104)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
        at java.lang.Daemons$Daemon.run(Daemons.java:139)
        at java.lang.Thread.run(Thread.java:923)
`

**Comment by consp1racy** [comment]
It's crashing because you told it to using `penaltyDeath`.

**Comment by drchen** [comment]
Thanks @consp1racy for the explanation. I'll close the issue since it seems not like something we can fix.
