### ISSUE TITLE
[TextInputLayout] Add custom counter property

### ISSUE THREAD

**Issue by alorma** [material-components/material-components-android#2027]
**Describe the solution you'd like**
An option on `TextInputLayout` that allows to customize the `counter` param, not by the size of text but a custom property defined by code implementation.

Our use case is:

* We have a `TextInputLayout` that is an AutoComplete.
* When we select an item from the autocomplete list, we ad it as a chip on a `ChipGroup`
* We want to provide the `counter` param as a counter for number of chips added, as we have a max number of chups.

**Describe alternatives you've considered**
I can create a custom `TextView` and using  the material styles for it:

```xml
    <item name="counterTextAppearance">@style/TextAppearance.Design.Counter</item>
    <item name="counterOverflowTextAppearance">@style/TextAppearance.Design.Counter.Overflow</item>
```

**Additional context**

**Current**
![](https://user-images.githubusercontent.com/887462/106611733-9a05af00-6568-11eb-9c1c-553cd9948bee.png)

**Expected**
![](https://user-images.githubusercontent.com/887462/106611737-9a9e4580-6568-11eb-9c63-cce3cba70a67.png)

**Comment by drchen** [comment]
Hi, I think you can just add another text view under the text input layout and update it with the chip count?

Since the functionality is not directly related to text editing and it can be easily implemented by clients, I'll close the request.
