### ISSUE TITLE
[Circular progress indicator] Does not work on API 22 only

### ISSUE THREAD

**Issue by Massi-X** [material-components/material-components-android#2028]
**Description:** Inflate and put an indeterminate circular spinning indicator programmatically in a layout and try to start the app. For the record I've set it as the actionview for a menu, but I bet it's the same for every other case.

**Expected behavior:** The progress indicator should be visible and spinning. This is not the case on API 22, where the progress indicator doesn't spin at all. From my tests it works on API 19,21,23,24,29 and doesn't work on API 22 only.

**Source code:**
loading.xml:
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

<com.google.android.material.progressindicator.CircularProgressIndicator
        android:layout_width="20dp"
        android:layout_height="20dp"
        android:layout_margin="10dp"
        android:indeterminate="true"
        app:indicatorColor="@color/zero_one_state"
        app:indicatorSize="20dp"
        app:trackThickness="3dp" />
</LinearLayout>
```
Main class:
```
@Override
public boolean onCreateOptionsMenu(Menu menu) { 
    menu.findItem(R.id.item).setActionView(R.layout.loading);
}
```

**Android API version:** 22

**Material Library version:** 1.3.0-rc01 - 1.3.0 stable - 1.4.0-alpha02 - 1.4.0 stable - ... - 1.6.0 alpha01 - 1.7.0-alpha01

**Device:** Emulator x86 or x86_64

**Comment by Massi-X** [comment]
Updated to reflect the new release

**Comment by kroegerama** [comment]
Same error on 1.4.0-alpha02. I guess @pekingme is the one who did the most work on this component. Are there any plans to fix this?

**Comment by khukuh123** [comment]
I have the same issue on API 22 and I'm using version 1.4.0

**Comment by sebkur** [comment]
I can reproduce this with 1.5.0 stable and 1.7.0-alpha01
