### ISSUE TITLE
When to expect Backdrop Component?

### ISSUE THREAD

**Issue by SahajRana** [material-components/material-components-android#203]
Hi, Could you please let us know when should we expect backdrop component to android? Thanks!

**Comment by afohrman** [comment]
We don't currently have plans to implement a backdrop component on Android. Please refer to our [roadmap](https://github.com/material-components/material-components/blob/develop/ROADMAP.md) for our release plans. 

In the meantime, I recommend checking out the backdrop example implemented in the [MDC Android codelabs](https://github.com/material-components/material-components-android-codelabs).

**Comment by Ornolfr** [comment]
@afohrman so the page for backdrop component is actually misleading and it's not under development?
https://material.io/design/components/backdrop.html#implementation
