### ISSUE TITLE
[BadgeDrawable] Text color does not update if badge reused when switching dark mode

### ISSUE THREAD

**Issue by jackmichalak** [material-components/material-components-android#2032]
**Description:** 

I want the text color of my badges to be different depending on whether dark mode is enabled. When the badge is originally created the text color is successfully set, but subsequent attempts to update the color (e.g. if you switch modes and come back in the attached sample app) everything except the badge text color updates; badge text color does not change.

Interestingly, you can see from the log lines that the stored value (retrieved from `badge.getBadgeTextColor()`) has already been updated to reflect the change in dark mode, but the color drawn does not; perhaps the color appearing not to change is preventing a redraw? I wasn't familiar enough with the code to follow this line of inquiry.

The attached zip contains a recording demonstrating the issue with the provided sample app.

**Expected behavior:** 

Switching dark mode and calling `badge.setBadgeTextColor(color)` should actually update the text color shown on screen.

**Source code:** 

I added the following to the bottom of MainActivity's onCreate of the Bottom Navigation Activity template in Android Studio:

```java
        int flags = navView.getContext().getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
        boolean darkMode = flags == Configuration.UI_MODE_NIGHT_YES;
        int color = darkMode ? Color.BLACK : Color.WHITE;

        BadgeDrawable badge = navView.getOrCreateBadge(R.id.navigation_dashboard);
        Log.d("TEST", "Badge text color before: " + badge.getBadgeTextColor());
        badge.setBadgeTextColor(color);
        Log.d("TEST", "Badge text color after: " + badge.getBadgeTextColor());
        badge.setNumber(1);
```

The attached zip file contains the actual project used.

**Android API version:** 30

**Material Library version:** The included sample app uses 1.2.1, but I also tested on [the latest RC](https://github.com/material-components/material-components-android/releases/tag/1.3.0-rc01) and that also did not work.

**Device:** Pixel 3a emulator

The zip with sample app and recording can be downloaded from [here](https://drive.google.com/file/d/10EWO6x5PCERXJY-ONBKz9KS3tfZfnLoD/view?usp=sharing).

**Comment by drchen** [comment]
The badge text color set in onCreate() will be overwritten by saved instance state. (It's not a right behavior and we should fix it though.)

If you want to workaround it you can set the color in activity's onResume() instead, which will be called after onRestoreInstanceState().

**Comment by dsn5ft** [comment]
Had to roll back (hopefully temporarily) in https://github.com/material-components/material-components-android/commit/c52b95d4d5cba6eb68d046eafb28c75be8536b9d.

**Comment by drchen** [comment]
The fix has been rolled forward again. Let's close the issue.
