### ISSUE TITLE
[TextInputLayout] Content description of icon is not read by the screen reader

### ISSUE THREAD

**Issue by JJdeGroot** [material-components/material-components-android#2035]
**Description:** The content description of the icon is not read by the screen reader.

**Expected behavior:** "The content description will be read via screen readers or other accessibility systems to explain the action of the icon." 
Reference: https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout#setEndIconContentDescription(java.lang.CharSequence)

**Source code:** 
```
fun TextInputLayout.setCompleted(completed: Boolean) {
    if (completed) {
        endIconMode = TextInputLayout.END_ICON_CUSTOM
        setEndIconDrawable(R.drawable.ic_valid_small)
        setEndIconContentDescription(R.string.completed)
        setEndIconTintList(ContextCompat.getColorStateList(context, R.color.green))
        isEndIconVisible = true
    } else {
        endIconMode = TextInputLayout.END_ICON_NONE
        endIconDrawable = null
        endIconContentDescription = null
        setEndIconTintList(null)
        isEndIconVisible = false
    }
}
```

**Android API version:** 29

**Material Library version:** 1.2.1

**Device:** Nokia 7 Plus with Android 10

**Comment by leticiarossi** [comment]
Hi there, the text field icons are considered decorative elements if they don't work as buttons (so if there's not a click listener or a long click listener set on it). In that case they are ignored/skipped by screen readers.

It seems like you're using a custom icon as a visual indication that an action was completed. I suggest also adding something else, like changing your helper text to indicate the text field's new status, for example.
