### ISSUE TITLE
The style on this component requires your app theme to be Theme.AppCompat (or a descendant). |BottomNavigationView

### ISSUE THREAD

**Issue by ermanishks** [material-components/material-components-android#2039]
**Description:**

Crash in  inflate of com.google.android.material.bottomnavigation.BottomNavigationView
started to come on **SOME DEVICES** .
there has no change in theme of application or activity.

Crash log :
Caused by java.lang.IllegalArgumentException
The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
com.google.android.material.internal.ThemeEnforcement.checkTheme (ThemeEnforcement.java:243)
com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme (ThemeEnforcement.java:213)
com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme (ThemeEnforcement.java:148)
com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes (ThemeEnforcement.java:115)
com.google.android.material.bottomnavigation.BottomNavigationView.<init> (BottomNavigationView.java:160)
com.google.android.material.bottomnavigation.BottomNavigationView.<init> (BottomNavigationView.java:133)

**Expected behavior:**
app should not crash.

**Source code:**
        <com.google.android.material.bottomnavigation.BottomNavigationView
                android:id="@+id/navView"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                app:elevation="8dp"
   <..            app:itemIconTint and itemTextColor colors are set >
                app:labelVisibilityMode="labeled"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent" />

  **themes defined :**
 my app theme is extended by Theme.MaterialComponents.Light . Document (https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#bridge-themes) says that you should use 
bridge theme to support material components. 
I can't change my base app theme.
is this reason for crash ? 

so my question is -
1. can i define custom theme just for BottomnavigationView which would extend Theme.MaterialComponents.Light.Bridge ..
    <style name="bottomNav" parent="Theme.MaterialComponents.Light.Bridge">
    </style>
like this and use this style in bottomNavigationView 
     <com.google.android.material.bottomnavigation.BottomNavigationView
                android:id="@+id/navView"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
               style="@style/bottomNav"
/>
will this fix my issue ? and why?
2. any other approach 

**Android API version:** 
Android 10 api 29 android 9

**Material Library version:** 1.2.0

**Device:** 
Xiaomi, (86  %),  samsung(10 %) and others ( real me , one plus)

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
You don't need to change your base app theme. Can you check if the context you are using to create BottomNavigationView is correctly themed with your app theme? For example by setting a theme attribute to a specific value?

**Comment by drchen** [comment]
I'll close the issue with the assumption that the issue has been solved. Feel free to leave further info if that's not the case.
