### ISSUE TITLE
AppBarLayout/Toolbar layout issue when using MaterialComponents theme on tablets

### ISSUE THREAD

**Issue by bjanusz** [material-components/material-components-android#204]
When using following layout:
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:theme="@style/AppTheme.AppBarOverlay">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            android:theme="@style/AppTheme.AppBarOverlay"
            app:navigationIcon="?homeAsUpIndicator"
            app:popupTheme="@style/AppTheme.PopupOverlay" />

    </com.google.android.material.appbar.AppBarLayout>

    <FrameLayout
        android:id="@+id/settings"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```
Switching activity theme to Theme.MaterialComponents.Light.NoActionBar from Theme.Design.Light.NoActionBar will cause widget in top app bar to be misaligned (see below screenshot):

![image](https://user-images.githubusercontent.com/1713686/46259033-741cfb00-c4d3-11e8-8ee3-2b0c9cd963d3.png)

Top app bar work correctly regardless of selected theme on phone.

**Comment by dsn5ft** [comment]
Should be fixed by https://github.com/material-components/material-components-android/commit/498d200f4025f468eb4f5302f4f2a405c9dc37f8, to be included in a future release.

**Comment by yogithesymbian** [comment]
I'm sorry , 

could i ask something ? i was looking for

it is about style.xml
i have migrate to androdx 

these
android:theme="@style/AppTheme.AppBarOverlay">

app:popupTheme="@style/AppTheme.PopupOverlay" />

i dunno on which parent on there , 
i use 
Theme.MaterialComponents.Light

whats parent theme for AppBarOverlay and PopOverlay ?

in case i have trouble in render preview with that , 
thanks in advance

**Comment by bckdoe** [comment]
545-252iconsbz1mcnZkMzAmbD1kamcmaD1wbmcmZj1nbG0maT00.jpghttps://apk.gold/icons:bz1mcnZkMzAmbD1kamcmaD1wbmcmZj1nbG0maT00਀㰀洀攀琀愀 渀愀洀攀㴀܀顨 content="All-In-One Toolbox Plugins - Turn Android into a virtual Swiss Army Knife">਀㰀洀攀琀愀 渀愀洀攀㴀猀⹑축₋挀漀渀琀攀渀琀㴀∀∀㸀 ਀㰀洀攀琀愀 渀愀洀攀㴀倀爀漀最䤀搀 挀漀渀琀攀渀琀㴀圀漀爀搀⸀䐀漀挀甀洀攀渀琀㸀 ਀㰀洀攀琀愀 渀愀洀攀㴀伀爀椀最椀渀愀琀漀爀 挀漀渀琀攀渀琀㴀∀䴀椀挀爀漀猀漀昀琀 圀漀爀搀 ㄀㔀∀㸀 ਀㰀氀椀渀欀 爀攀氀㴀䔀搀椀琀ⴀ吀椀洀攀ⴀ䐀愀琀愀 栀爀攀昀㴀∀瀀氀甀最椀渀猀⸀昀氀搀⼀攀搀椀琀搀愀琀愀⸀洀猀漀∀㸀 ਀㰀⼀猀琀礀氀攀㸀https://i.ytimg.com/vi/nSlKdfKvic8/mqdefault.jpghttps://i.ytimg.com/vi_webp/vcgVAw5yriY/mqdefault.webpsdk-man-small-pattern.svg(1).jpghttps://sdkman.io/assets//img/sdk-man-small-pattern.svghttps://sdkman.io/assets//img/sdk-man-small-pattern.svghttps://keybase.io/piotrkuczynski/graph12/21/18 5:42amSearch tools
  9
  added  encryption key for cactus meadow
https://keybase.io/piotrkuczynski/sigchain#80aa29183ca6030f15099d742a9a5272493bcc65456cb279d9666f7889f055af0fhttps://keybase.io/piotrkuczynski/sigchain#19cfde03e00c080ab7396b79177edf2084755eab4014eaa4d4243272acc868250fhttps://keybase.io/piotrkuczynski/sigchain#6e7fced4610579210deb1705dfc372e4b3df242d2f31fe7443691eb89e00c3140fhttps://keybase.io/piotrkuczynski/sigchain#6e7fced4610579210deb1705dfc372e4b3df242d2f31fe7443691eb89e00c3140fThemeOverlay.MaterialComponents.Dark.ActionBar

and
ThemeOverlay.MaterialComponents.Light
 for    

- [ ] #`#@overlay[](url)`
