### ISSUE TITLE
[LinearProgressIndicator] When setting indicator color programatically track color doesn't change 

### ISSUE THREAD

**Issue by mak1nt0sh** [material-components/material-components-android#2040]
Is it a bug or feature? 

When setting indicator color in xml: `app:indicatorColor="@color/someColor"` 
the track color displays with disabledAlpha of indicator color.

When setting color programmatically: `progress_bar.setIndicatorColor(ContextCompat.getColor(context,R.color.somecolor))`
the track color doesn't change.

**Material Library version:** 1.3.0

**Comment by enricocid** [comment]
Don't know if it is related, but I failed to set indicator color to multi-color progress. Had to set them via XML

I've got this exception:
https://github.com/material-components/material-components-android/blob/da2d8264d1644e85aa29ef1c1a37f306bc67d3ac/lib/java/com/google/android/material/progressindicator/LinearProgressIndicatorSpec.java#L107

It seems like indicatorColors is not being applied.

**Comment by mak1nt0sh** [comment]
@enricocid Probably not related. For me the indicator color changes, but track color stays the same. Waiting for a confirmation that it's a feature. Then I'll have to separately change track colors.

**Comment by pekingme** [comment]
Sorry for the late response. Basically what you observed is an intended behavior. If `app:trackColor` is not defined in xml, it will take the (first, if there's multiple,) indicator color and apply `disabledAlpha`. Once it's instantiated, it's not safe to automatically update track color while setting indicator color. It cannot tell how the current track color is obtained.

**Comment by mak1nt0sh** [comment]
Intended behavior
