### ISSUE TITLE
[Progress indicator] improve docs for multi-color indeterminate progress

### ISSUE THREAD

**Issue by enricocid** [material-components/material-components-android#2043]
**Description:** The documentation is lacking some info when it comes to multi-color progress.
It is only specified that You can choose between disjoint and contiguous modes, but not how to set them and that there's a mininum requirement of 3 colors or exception will be thrown

**Expected behavior:** Add a snippet like this

```
<com.google.android.material.progressindicator.LinearProgressIndicator
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:indeterminate="true"
    app:indicatorColor="@array/progress_colors" <!-- no less than 3 colors or an exception will be thrown -->
    app:indeterminateAnimationType="contiguous" />
```

**Source code:** na

**Android API version:** na

**Material Library version:** 1.3.0

**Device:** na

**Comment by dbrgn** [comment]
Example for the color array definition:

```xml
<array name="progress_colors">
        <item>@color/colorPrimaryDark</item>
        <item>@color/colorAccent</item>
        <item>@color/colorBackground</item>
    </array>
```

**Comment by Gidde-Abhishek** [comment]
> Example for the color array definition:
> 
> ```
> <array name="progress_colors">
>     <item>@color/colorPrimaryDark</item>
>     <item>@color/colorAccent</item>
>     <item>@color/colorBackground</item>
> </array>
> ```

This array needs to be declared inside an xml file named "arrays.xml" which is in the res>values directory. 
the final arrays.xml for me looks like : 
(The colors mentioned are declared inside colors.xml you can also use hex values directly)
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <array name="progress_colors">
        <item>@color/blue</item>
        <item>@color/green</item>
        <item>@color/black</item>
    </array>
</resources>
```
