### ISSUE TITLE
Not component-related: Provide better Release Notes

### ISSUE THREAD

**Issue by carstenhag** [material-components/material-components-android#2044]
The 1.3.0 release notes only say:

>**What's New Since 1.2.0?**
>Time Picker (docs)
>Progress Indicator (docs)
and that ConstraintLayout was updated to 2.0.1.

But the difference between 1.2.1 and 1.3.0 are **557 commits and 1632 changed files**! I am pretty sure more than two components and one lib changed.

One has to manually dig into alpha, beta and rc build release notes to see the release notes of the *stable* version.  
This is pretty insane, also, there could be changes in alpha builds which did not make it to the stable version, so that's not reliable either.

To compare, the [1.2.0](https://github.com/material-components/material-components-android/releases/tag/1.2.0) and [1.1.0](https://github.com/material-components/material-components-android/releases/tag/1.1.0) release notes actually contain helpful summaries.

**Comment by dsn5ft** [comment]
We added some more highlights to [1.3.0](https://github.com/material-components/material-components-android/releases/tag/1.3.0).

**Comment by carstenhag** [comment]
Thanks a lot ;)
