### ISSUE TITLE
[Slider] Slider.OnChangeListener is being called even when slider's value is not set

### ISSUE THREAD

**Issue by bhavinmdesai** [material-components/material-components-android#2052]
**Description:** 

At the time of coming back to fragment with Slider from other fragments, Slider.OnChangeListener is getting called even if the Slider's value is not set

**Expected behavior:** 

Slider.OnChangeListener should only be called when Slider's value is set

**Source code:** 

https://github.com/bhavinmdesai/Slider-OnChangeListener-Bug

**Android API version:** Android 29

**Material Library version:** 1.3.0

**Device:** Motorola One Fusion+

**Comment by drchen** [comment]
So basically a slider without any values set is an illegal state.

A default value (=valueFrom) will always be set during the view creation.
