### ISSUE TITLE
Unnecessary margin in TabLayout.Tab for custom view

### ISSUE THREAD

**Issue by ImKoRn** [material-components/material-components-android#206]
Component add bottom margin when Tab icon end text present but when Tab created with custom view where defined andorid.R.id.text1 and android.R.id.icon views it's unnecessary and make bad affect for custom layout.

[https://github.com/material-components/material-components-android/blob/48a07e1df9d89a17044c8d24762513c0360ca172/lib/java/com/google/android/material/tabs/TabLayout.java#L2355](url)

**Comment by cketcham** [comment]
https://issuetracker.google.com/issues/117662942
