### ISSUE TITLE
[TextInputLayout] app:expandedHintEnabled="true" doesn't occupy the input area when empty & idle

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#2065]
**Description:** Using app:expandedHintEnabled="true" attribute to show the `TextInputLayout` when empty and idle but it doesn't take effect. I tried `1.3.0-alpha03` and `1.3.0-rc01`. I using:
```
        android:hint="@{item.title}"
        app:expandedHintEnabled="true"
```

**Expected behavior:** To show the `TextInputLayout` expanded

<details>
<summary>Design Screen</summary>

<img src="https://user-images.githubusercontent.com/1494577/107721445-83aad200-6c91-11eb-8fd1-eb3fca83e514.png" width="400"/>
</details>

**Source code:** 

**Android API version:** 29

**Material Library version:** `1.3.0-alpha03` and `1.3.0-rc01`

**Device:** Pixel 4XL

**Comment by leticiarossi** [comment]
Can you provide a screenshot of the behavior you're seeing vs the expected one? Not sure what the issue is. 
Also, `true` is the default value of `app:expandedHintEnabled`

**Comment by sabinebarrera** [comment]
Thanks @leticiarossi please see screens below.

<details>
<summary>App Screens</summary>

**I was expecting to see the `TextInputLayout` expanded like when it is in focused state. Perhaps I am mistaken the purpose of `app:expandedHintEnabled="true"`**

| Idle | Focused |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1494577/107832970-b19e1e00-6d46-11eb-9a45-d4a8aa6380bd.png" width="400"/> | <img src="https://user-images.githubusercontent.com/1494577/107832898-7dc2f880-6d46-11eb-9f5a-5edd978e1b51.png" width="400"/> |
</details>

**Comment by leticiarossi** [comment]
Ah I think you want to set `app:expandedHintEnabled` to `false` then! That will make the hint always be collapsed and floating, so if you have `placeholderText` set that will always show.

**Comment by sabinebarrera** [comment]
@leticiarossi Thanks so much... an oversight from my side. TextInputLayout with `app:expandedHintEnabled=false` works like a charm.

<details>
<summary>Screen</summary>

<img src="https://user-images.githubusercontent.com/1494577/108890118-04d36480-75c2-11eb-990a-4a2b2a0d0393.png" width="300"/>
</details>
