### ISSUE TITLE
[CollapsingToolbarLayout] Add subtitle

### ISSUE THREAD

**Issue by JorisBodin** [material-components/material-components-android#2067]
**Is your feature request related to a problem? Please describe.**
You can't easily add a subtitle, like what's app for example.

**Describe the solution you'd like**
Like this lib: https://github.com/HendraAnggrian/collapsingtoolbarlayout-subtitle

![example_light](https://github.com/hendraanggrian/collapsingtoolbarlayout-subtitle/raw/master/art/example_light.gif)

**Comment by hunterstich** [comment]
Hey @JorisBodin,

Thanks for filing a feature request. 

This isn't something we're planning on supporting at the moment. 
Have you looked in to using an `AppBarLayout` containing your title+subtitle layout and animate both on scroll using an `OnOffsetChangeListener`?

Closing, but let me know if I can help if you decide to create your own solution.

**Comment by JorisBodin** [comment]
Hello @hunterstich 

I use a custom `layout_behavior`, I was inspired by this git : https://github.com/anton46/WhatsApp-ProfileCollapsingToolbar
In the end I don't use `OnOffsetChangeListener`

Thanks you :)

**Comment by JorisBodin** [comment]
@dsn5ft
Subtitles exist in MaterialToolbar, so I don't understand why they wouldn't exist in CollapsingToolbarLayout.
Do you have a reason for this choice?

Thanks :)

![image](https://user-images.githubusercontent.com/2796439/111288165-392bc500-8644-11eb-8646-0a463fee6106.png)
