### ISSUE TITLE
[AppBarLayout] No way to set lifted state

### ISSUE THREAD

**Issue by MasterOfTouch** [material-components/material-components-android#2068]
**Description:** 
I need to lift AppBarLayout ones when view created, and keep forever in this state. 
So no matter which setup i will try (
setLifted(true), setLiftOnScroll(false)) - behavior will always be as intended by code

**Expected behavior:** Expecting that by my command (setLifted(true)) will move AppBarLayout to lifted state, and will not be automatically reseted by internal lift state resolving logic on next invalidate.

**Source code:** 
In my opinion the next line cause the problem:
`final boolean changed = layout.setLiftedState(lifted);`
(1854 line in guthub, inside `updateAppBarLayoutDrawableState` method)
that will be invoked by onNestedPreScroll callback

Code inside `onNestedPreScroll` also looks weird.
(1315 line in guthub, inside updateAppBarLayoutDrawableState method)
So lifting will be changed insde 
`if (min != max) {
          consumed[1] = scroll(coordinatorLayout, child, dy, min, max);
        }`
but also will be changed again in next line, but at least here we have some logic, and it looks like it could be prevented by `isLiftOnScroll` flag

**Android API version:**  i guess any 21+

**Material Library version:** 1.2.1+

**Device:** ZTE Axon 7

**Comment by aberaud** [comment]
I confirm that setLifted() doesn't work at all with my app, no matter the state of liftOnScroll.

**Comment by drchen** [comment]
It looks like this has been fixed by the introduction of setLiftableOverrideEnabled(true).
