### ISSUE TITLE
[TextInputLayout] Background color for outlined text field

### ISSUE THREAD

**Issue by GerardPaligot** [material-components/material-components-android#2069]
**Is your feature request related to a problem? Please describe.**
Compared to filled text field, it isn't always obvious to see when an outlined text field is disable.

**Describe the solution you'd like**
Create a selector with a default color for the background (not necessary Transparant) and a color when the text field is disabled.

```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="COLOR_DISABLE" android:state_enabled="false" />
    <item android:color="COLOR_DEFAULT" />
</selector>
```

Then we can use it in `boxBackgroundColor` property in the theming:

```xml
<style name="Widget.App.TextInputLayout" parent="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox">
    <item name="boxBackgroundColor">@color/vtmn_outlined_background_color</item>
</style>
```

**Describe alternatives you've considered**
Use a filled text field but this component isn't always adapted for all cases.

Thanks!

**Comment by hunterstich** [comment]
Hey @GerardPaligot,

I think you should be able to do this by creating your own ColorStateList following the format used in the default CSL for `boxBackgroundColor` - https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/color/mtrl_filled_background_color.xml

Also see the [Anatomy and key properties](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/color/mtrl_filled_background_color.xml) section of the documentation which mentions the above CSL.

Does this not work for you?

**Comment by GerardPaligot** [comment]
Hey @hunterstich,

Yes, it works when you apply a `ColorStateList` on a filled text field but here, I'm trying to do it for an outlined text field.

It doesn't work because the disable background color state is only applied when you are in filled mode: https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/TextInputLayout.java#L4108-L4118

I don't know if there is any reason for that but that could be great if the `boxBackgroundColor` property could be applied for Filled and Outlined text fields.

**Comment by hunterstich** [comment]
Oh okay. Thanks for the additional details. 

I'll bring this up with the team and get back to you.

**Comment by GerardPaligot** [comment]
@hunterstich I made a pull request about this if you want. :)

**Comment by hunterstich** [comment]
I see that, thank you!

https://github.com/material-components/material-components-android/pull/2084

**Comment by paulfthomas** [comment]
See https://github.com/material-components/material-components-android/pull/2084 for additional info.
