### ISSUE TITLE
FloatingActionButton BUG

### ISSUE THREAD

**Issue by mvasi90** [material-components/material-components-android#207]
Impossible to change the fab icon if it previously has been hidden and shown.
Before invoking `fab.hide()` and `fab.show()` the new icon is showing correctly.
After invoking those methods the fab icon is empty on change.

**Comment by cketcham** [comment]
This is fixed, but not released yet. It will be included in the next release.

**Comment by GuanacoDevs** [comment]
Thanks to this [SO Answer](https://stackoverflow.com/a/54663687/5482999) was able to fix it in my app, after a good couple of hours of trying everything else...
