### ISSUE TITLE
[TextInputLayout] Add success state

### ISSUE THREAD

**Issue by GerardPaligot** [material-components/material-components-android#2070]
**Is your feature request related to a problem? Please describe.**
When I create a form and need to give a feedback to my user, I can give a feedback for each text field in error but I can't give a visual feedback when the text field is in success.

**Describe the solution you'd like**
Can customize a success state for my text field from styles or directly in my layout xml file:

```xml
<style name="Widget.App.TextInputLayout" parent="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox">
    <item name="sucessTextColor">...</item>
    <item name="sucessIconTint">...</item>
    <item name="sucessIconDrawable">...</item>
    <item name="sucessContentDescription">...</item>
    <item name="sucessTextAppearance">...</item>
    <item name="sucessEnabled">true</item>
</style>
```

**Describe alternatives you've considered**
No visual change on my text field but I'm limited in my user experience.

Thanks!

**Comment by hunterstich** [comment]
Hi @GerardPaligot,

Thanks for the FR!

This isn't something we plan to support at the moment. 

I know it's not as ideal as built-in library support, but have you tried any workarounds like programmatically changing the error icon/tint/message to support your use case? 

Closing this, but let me know if I can help in coming up with your own solution.

**Comment by GerardPaligot** [comment]
Yes, I figured it wouldn't be accepted.

> I know it's not as ideal as built-in library support, but have you tried any workarounds like programmatically changing the error icon/tint/message to support your use case?

I'm building a design system and I'm trying to use official XML properties from styles to build native components. But yes, I think I'll create a `ThemeOverlay` for success state, a custom `TextInputLayout` and apply the switch between error state, success state and normal state internally when my consumer want to change state of the text field.

Not an ideal solution because it forces my consumer to use my custom component but acceptable if well documented from my side. :)
