### ISSUE TITLE
[MaterialCardView] Checked icon is not displayed when card is not clickable or not enabled

### ISSUE THREAD

**Issue by avianey** [material-components/material-components-android#2072]
**Description:** 

Checked MaterialCardView displays a checked icon
The checked icon is not displayed if the MaterialCardView is not checked or not enabled

**Expected behavior:** 

As long as the state has the checked flag, the checked icon should be displayed

**Source code:** 

```
<com.google.android.material.card.MaterialCardView
    android:id="@+id/card"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:clickable="true"
    android:focusable="true"
    android:checkable="true">
    ...
```

Checked icon NOT displayed :
```
findViewById<MaterialCardView>(R.id.card).let {
    it.clickable = false
    it.isEnabled = true
    it.checkable = true
    it.checked = true
}
```
Checked icon NOT displayed :
```
findViewById<MaterialCardView>(R.id.card).let {
    it.clickable = true
    it.isEnabled = false
    it.checkable = true
    it.checked = true
}
```
Checked icon displayed :
```
findViewById<MaterialCardView>(R.id.card).let {
    it.clickable = true
    it.isEnabled = true
    it.checkable = true
    it.checked = true
}
```

**Android API version:** Android 10 / 9

**Material Library version:** 

`implementation 'com.google.android.material:material:1.3.0'`

**Device:** 

Samsung Galaxy S10e
Samsung Galaxy A42

**Comment by drchen** [comment]
It's an intended design.
