### ISSUE TITLE
[TextInputLayout] custom style crashes with "The style on this component requires your app theme to be Theme.AppCompat (or a descendant)" error

### ISSUE THREAD

**Issue by tMarenzi** [material-components/material-components-android#2073]
**Description:**
 Defining a custom style for the `TextInputLayout ` crashes the app during Fragment inflation with the following error:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.textinputlayout.style.crash/com.textinputlayout.style.crash.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```

I've experienced this issue in a project I'm working on and was able to reproduce the crash with a sample project (see _Source code_ section)

The sample project has just three components:

- `MainActivity`
- `MainFragment`
- `MainViewModel`

The fragment has the following simple layout

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.main.MainFragment">

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/nickname_til"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="24dp"
        android:hint="NickName"
        app:endIconMode="clear_text"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/nickname_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textPersonName" />
    </com.google.android.material.textfield.TextInputLayout>
</androidx.constraintlayout.widget.ConstraintLayout>
```

While the main `theme.xml` is the following

```
<resources xmlns:tools="http://schemas.android.com/tools">
    <!-- Base application theme. -->
    <style name="Theme.TestMaterialComponents" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
        <!-- Primary brand color. -->
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorOnPrimary">@color/white</item>
        <!-- Secondary brand color. -->
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        <!-- Status bar color. -->
        <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
        <!-- Customize your theme here. -->
        <item name="textInputStyle">@style/Widget.App.TextInputLayout</item>
    </style>

    <style name="Widget.App.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.FilledBox">
        <item name="materialThemeOverlay">@style/ThemeOverlay.App.TextInputLayout</item>
        <item name="shapeAppearance">@style/ShapeAppearance.App.SmallComponent</item>
        <item name="hintTextColor">?attr/colorPrimary</item>
    </style>

    <style name="ThemeOverlay.App.TextInputLayout" parent="">
        <item name="colorPrimary">?attr/colorPrimary</item>
        <item name="colorOnSurface">?attr/colorOnSurface</item>
        <item name="colorError">@color/red_600</item>
        <item name="boxBackgroundColor">@color/transparent</item>
        <item name="editTextStyle">@style/Widget.MaterialComponents.TextInputEditText.FilledBox
        </item>
    </style>

    <style name="ShapeAppearance.App.SmallComponent" parent="ShapeAppearance.MaterialComponents.SmallComponent">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">8dp</item>
    </style>
</resources>
```

**Expected behavior:** 
The Fragment should inflate correctly and display the `TextInputLayout` with the style set in the `themes.xml`

**Source code:** 
Please find attached a minimal sample project that can reproduce the issue by just running it on a device along with a crashlog.

[TextInputLayoutStyleCrash.zip](https://github.com/material-components/material-components-android/files/5989322/TextInputLayoutStyleCrash.zip)

[TextInputLayout_style_crash_log.txt](https://github.com/material-components/material-components-android/files/5989332/TextInputLayout_style_crash_log.txt)

**Android API version:** 

`targetSdkVersion 30` 

**Material Library version:** 
`1.3.0`

**Device:** 
Google Pixel XL running Android 10

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by hunterstich** [comment]
Hey @tMarenzi,

It looks like you have two different themes in `values` and `values-night`.

Your `AndroidManifest.xml` has its theme set to `theme="@style/TextInputLayoutStyleCrash"` which only exists in your `values-night/theme.xml` file. If you change the name of your `values/theme.xml` to `Theme.TextInputStyleLayoutCrash` (to match that in your manifest and night qualified theme file), I think you should be fine.

Feel free to re-open if that doesn't work for you.

**Comment by tMarenzi** [comment]
Hi @hunterstich ,
thank you for the quick reply.
Indeed I had an issue with the theme names.

Unfortunately, aligning the theme names did not solve the issue.
The crash I have now is exactly the same one I have in the original project.
I've updated both the description and the attached sample code.

Can you please reopen this issue (I don't have the required permissions since I didn't close it myself)? 
Or do you prefer I open a new one?

**Comment by hunterstich** [comment]
Oh okay.

In your textInputStyle's materialThemeOverlay, I think you need to remove the colorPrimary attribute:

```
    <style name="ThemeOverlay.App.TextInputLayout" parent="">
        <!-- FIX: Remove setting colorPrimary to itself -->
        <!-- <item name="colorPrimary">?attr/colorPrimary</item> -->
        <item name="colorOnSurface">?attr/colorOnSurface</item>
        <item name="colorError">@color/red_600</item>
        <item name="boxBackgroundColor">@color/transparent</item>
        <item name="editTextStyle">@style/Widget.MaterialComponents.TextInputEditText.FilledBox</item>
    </style>
```

**Comment by tMarenzi** [comment]
Hi @hunterstich ,
Thank you again.

Your suggestion does fix the issue, but I don't understand exactly why.

I get that the issue may be caused by the `colorPrimary  item` referencing itself.
But why the `colorOnSurface` item does not trigger a crash even if it set in the same way?

Another thing I don't understand, which was my original goal, is why the `booxBackgroundColor` attribute does not work if it specified inside the `ThemeOverlay.App.TextInputLayout` style, but it does work if I specify it inside the `Widget.App.TextInputLayout` style?

**Comment by leticiarossi** [comment]
Hi @tMarenzi ! I'm not sure why the `colorOnSurface` referencing itself is also not causing a crash, but I feel like you shouldn't be setting it like that if you don't intend to change its value to something else.

The `boxBackgroundColor` is not a theme attribute, it's specific to the `TextInputLayout`, so that's why it should be set in the style instead of on the theme overlay (differently from `colorPrimary` and `colorOnSurface` which are both theme attributes).
