### ISSUE TITLE
[com.google.android.material.textfield.TextInputLayout] text language is not updated after locale update and activity recreate

### ISSUE THREAD

**Issue by jannepanda** [material-components/material-components-android#2075]
**Description:** 
The android:hint/app:helperText text language in TextInputLayout is not updated after activity is recreated with new locale.
This issue has been present since 1.3.0-alpha03. 1.3.0-alpha02 was the last release in which it worked to my knowledge.

**Expected behavior:**
Expected texts language to be updated with new set locale, like it does for other components, for example: MaterialButton.

**Source code:** 
Please find a small sample project attached which shows the behavior
[MaterialLocaleChangeTest.zip](https://github.com/material-components/material-components-android/files/5995033/MaterialLocaleChangeTest.zip)

. Switch between com.google.android.material:material 1.3.0 and 1.3.0-alpha02 to see the difference.

**Android API version:** Android API version here
API 23, API 29

**Material Library version:**
1.3.0

**Device:**
Tested on emulator and custom tablets

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by matpag** [comment]
I got the same.
I suppose the problem is in this commit: https://github.com/material-components/material-components-android/commit/076ff693432a3bdafc42dd2aa64b51c9510eb93f
The SavedState is saving the current text values, then when the device language is changed (and the app is in the recent list or `recreate()` is called) those values are restored as they were before the configuration change

**Comment by hunterstich** [comment]
Thanks for reporting @jannepanda. And thank you for attaching a sample.

I'll take a look.

**Comment by xxfast** [comment]
Can confirm the issue can be replicated

**Comment by mohsenoid** [comment]
Any update regarding this issue??!!!

**Comment by TheKrushik** [comment]
I have this problem to

**Comment by matpag** [comment]
I added a temporary workaround here: https://stackoverflow.com/a/68529867/2910520

**Comment by wbervoets** [comment]
any update on this issue?

**Comment by mohsenoid** [comment]
Any updates?
