### ISSUE TITLE
Make anything and everything you can do in xml directly reflect java code

### ISSUE THREAD

**Issue by FreddyJohn** [material-components/material-components-android#2078]
An Image button for example
in xml lets set the LayoutMargins, Hm notice how there are 7 parameters here. 

in java lets set the LayoutMargins, okay well 
LayoutParams foo = new LayoutParams(1,1,);
foo.setMargin(1,1,1,1) hm only 4 parameters
okay then lets use 
MarginLayoutParams params = (MarginLayoutParams) getLayoutParams();
params.setMarginStart(1);
params.setMarginEnd(1);
okay this is getting to be ridiculous.
Im sure a lot of devs would love if you guys cleaned this up instead of working on stuff like bloaty apis fragments and valueanimators

**Comment by hunterstich** [comment]
Hi @FreddyJohn,

Thanks for reporting. MarginLayoutParams is a class in Android. The appropriate place to file this bug can be found here - https://source.android.com/setup/contribute/report-bugs

**Comment by FreddyJohn** [comment]
This is not one bug, this is a lot of bugs. Not only is there not a direct correspondence between function naming and the parameters of those functions between java and xml there is also not a direct one to one relationship between the functions and their behaviors. For example, SeekBar.setEnabled in xml has the effect of well... setting the SeekBar enbaled or not. In java you get that + you also make the SeekBar invisible.
