### ISSUE TITLE
The ability to change the size of the text and the whole chip dynamically

### ISSUE THREAD

**Issue by elephant-cf** [material-components/material-components-android#208]
Ability to change text size and chip size dynamically.
Necessary when increasing or decreasing it when scaling the surrounding text

**Comment by cketcham** [comment]
https://issuetracker.google.com/issues/117663136

**Comment by wcshi** [comment]
@elephant-cf could you please clarify your use case in the bug?

Have you tried using setTextAppearance to change the text size? The chip's height should automatically grow to accommodate the text size. There's a minChipHeight, and it will not shrink if the text is smaller.
