### ISSUE TITLE
[TextField] Add ability to set icon size

### ISSUE THREAD

**Issue by Mathbl** [material-components/material-components-android#2080]
**Is your feature request related to a problem? Please describe.**
That would be useful if there was a way to set the icon size of a `TextInputLayout` like there is for `MaterialButton`.

**Describe the solution you'd like**
`app:endIconSize` / `app:startIconSize`

**Comment by Mathbl** [comment]
@imhappi @paulfthomas I'm testing the new properties using `1.8.0-beta01`: is there a minimum size we can use? 

I'm using a vector drawable icon named ic_angle_down (original size of 32dpx32dp) and try to set the size to 18dp using the new `endIconMinSize` property:
<img width="1526" alt="CleanShot 2022-12-13 at 14 05 59@2x" src="https://user-images.githubusercontent.com/906656/207423085-da4d0e28-58f0-4b21-bfbc-26d9fc629d1f.png">
If I set a size of 64dp, for example, it changes the size correctly: 
<img width="1515" alt="CleanShot 2022-12-13 at 14 07 01@2x" src="https://user-images.githubusercontent.com/906656/207423230-e5c48b8b-7456-4d72-b8ab-fb0cfdd60516.png">

Thanks

**Comment by imhappi** [comment]
Hi! Unfortunately icon min size is just that; it's the minimum size that the icon tries to achieve. The icon min size sets the minimum width of the underlying image button, so if the drawable is bigger it'll still wrap the drawable size. I recall there were some issues with trying to set the size directly, so we went with the next best option of the minimum size

**Comment by Mathbl** [comment]
Ok, I see 🥲

**Comment by MuntashirAkon** [comment]
Here's a utility function to achieve this since they refused to do it for some unknown reason:

```java
    public static void setEndIconSize(@NonNull TextInputLayout layout, @Px int size) {
        int width = layout.getContext().getResources().getDimensionPixelOffset(R.dimen.mtrl_min_touch_target_size);
        int maxWidth = Math.max(width, size);
        // AppCompatImageButton errorIconView = layout.findViewById(R.id.text_input_error_icon);
        AppCompatImageButton endIconView = layout.findViewById(R.id.text_input_end_icon);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(maxWidth, size);
        layoutParams.gravity = Gravity.CENTER_VERTICAL | Gravity.END;
        endIconView.setLayoutParams(layoutParams);
        endIconView.setScaleType(ImageView.ScaleType.CENTER_INSIDE);
    }
```

This only covers the default end icon and not the error icon because I didn't need it, but you can manipulate it by uncommenting 4th line. If you need to set it using XML, you might want to consider extending `TextInputLayout` and adding `endIconSize` as a new property.
