### ISSUE TITLE
[ExtendedFloatingActionButton] Hide() / Show() animation broken

### ISSUE THREAD

**Issue by teresch-a** [material-components/material-components-android#2086]
**Description:** Unlike regular FloatingActionButton, ExtendedFAB has a bug with no animation for show() and hide() . I made a sample project reproducing the bug as well as to show that regular FAB has no problems.

**Expected behavior:** https://github.com/teresch-a/ExtendedFloatingActionButton-Animation-Workaround

**Source code:** https://github.com/teresch-a/ExtendedFloatingActionButton-Animation-Workaround

**Android API version:** 28

**Material Library version:** 1.3.0

**Device:** Pixel 4 AVD  / Samsung Galaxy S8 both with Android Pie

**Comment by hunterstich** [comment]
Hey @teresch-a,

Thanks for filing an issue!

Just to confirm, when you say "ExtendedFAB has a bug with no animation for show() and hide()" do you mean "ExtendedFAB's show and hide animation is slightly different than a regular FAB's animation"?
