### ISSUE TITLE
[FloatingActionButton] Hide() and Show() troubles with MotionLayout

### ISSUE THREAD

**Issue by AndreiRoze** [material-components/material-components-android#2087]
**Description:** Incorrect behavior of FAB. fab.hide() - FAB hides, but if I click on FAB position fab.clickListener will be called.
fab.show() - doesn't show FAB.

https://user-images.githubusercontent.com/53582576/108585918-76ee4400-734b-11eb-833c-290bd1c68f27.mp4

**Expected behavior:** when click on notification item - hide FAB, when click on home or dashboard item - show FAB.

**Source code:** https://github.com/AndreiRoze/fabAndMotionLayout

**Android API version:** minSdkVersion 23, targetSdkVersion 30

**Material Library version:** 1.3.0

**Device:** OnePlus 3 and tested on emulator

**Comment by Airsaid** [comment]
Hi, I'm having the same problem now, how did you solve it?

**Comment by Airsaid** [comment]
I did some research and found that it has something to do with `MotionLayout`. By default `MotionLayout` controls the visibility of all views within it. But we can opt out child views by using the `app:visibilityMode="ignore"` attribute and defining the view in the `<ConstraintSet>`. for example:
```xml
  <ConstraintSet android:id="@+id/start">
    <Constraint
      android:id="@id/fab">
      <PropertySet
        motion:visibilityMode="ignore"/>
    </Constraint>
  </ConstraintSet>
```
