### ISSUE TITLE
[MaterialDatePicker] prevent date range selection of more than specified date range

### ISSUE THREAD

**Issue by GautamChibde** [material-components/material-components-android#2090]
**Is your feature request related to a problem? Please describe.**
I need a feature where i can disable confirm button or disable selection of dates which are more than 30 days from selected start date

**Describe the solution you'd like**
solution can be either disabling confirm button or disabling the dates above certain range specified.

**Describe alternatives you've considered**
I have a though initially where i can show alert dialog when selected date range exceeds the required limit. but MaterialDatePicker gets auto dismissed when clicking confirm button (as disscued in issue #1125)

**Comment by hunterstich** [comment]
Hey @GautamChibde,

We've had similar questions and the short answer is that you can use the [DateValidator](https://github.com/material-components/material-components-android/blob/1f76fcc70f17e88c54baf41a8bc675d94f9c9695/lib/java/com/google/android/material/datepicker/CalendarConstraints.java#L50) class for this.

See https://github.com/material-components/material-components-android/issues/1905

Marking as closed, but if this doesn't solve your issue feel free to re-open.
