### ISSUE TITLE
[MaterialTimePicker] Expose `setTheme` api in `MateriaTimePicker.Builder` like MaterialDatePicker does

### ISSUE THREAD

**Issue by anoop44** [material-components/material-components-android#2093]
**Is your feature request related to a problem? Please describe.**
MaterialTimePicker Builder is missing a `setTheme` api to pass theme to customize/theme the component. MaterialDatePicker already has it. Only way to do this for MaterialTimePicker is now via the app/activity theme. This method makes it difficult to pass a theme at runtime based on some condition. 

**Describe the solution you'd like**
Expose `setTheme` api in `MateriaTimePicker.Builder` like MaterialDatePicker does. 

**Describe alternatives you've considered**
Can't think of any alternatives

**Comment by drchen** [comment]
The pull request has been merged. Closed the feature request.
