### ISSUE TITLE
[MaterialButton] IndeterminateDrawable not showing when used as Icon of a MaterialButton

### ISSUE THREAD

**Issue by leinardi** [material-components/material-components-android#2095]
**Description:** If I add a `IndeterminateDrawable` to a `MaterialButton`, the same way it is done in the Catalog app for the `Chip`s, it will not show/animate and only an empty space will be added.

**Expected behavior:** The `IndeterminateDrawable` should be shown and play the animation the same way it does when used in a `Chip` (see `ProgressIndicatorStandaloneDemoFragment` of the Catalog app).

**Source code:** 
[Repro project](https://github.com/leinardi/material-components-android/tree/issue-%232095): https://github.com/material-components/material-components-android/commit/f25909b74963c74c544816998e45c44bf249f60c

![image](https://user-images.githubusercontent.com/273338/108877983-0facea00-7600-11eb-8376-49144007ecd2.png)

**Android API version:** Tested on API 24 and 30.

**Material Library version:** 1.3.0 and 1.4.0-alpha01

**Device:** Android Emulator API 24 and 30

**Comment by leinardi** [comment]
Any news on this bug? It is at least confirmed or am I doing something wrong?

**Comment by leinardi** [comment]
Could we get at least an confirmation that this is a real issue?

**Comment by gringofe** [comment]
I'm having the same issue
