### ISSUE TITLE
Cardview resources are not being packaged up in aar

### ISSUE THREAD

**Issue by groverankush** [material-components/material-components-android#2099]
Hi,

I am trying to use material components in an AAR. When I try to build the aar, the card view resources i.e cardBackgroundColor and cardCornerRadius are not being included in the final aar's values file. Is this a known issue or there exists any workaround for the same?

**Comment by drchen** [comment]
Can you provide more detailed info? Like what error message you saw?

**Comment by drchen** [comment]
Closing the issue due to no further info. Feel free to reopen the issue if this is still a problem.
