### ISSUE TITLE
[MaterialCheckBox] Wrong touch targets for links in text

### ISSUE THREAD

**Issue by Steppschuh** [material-components/material-components-android#2100]
**Description:** When using a checkbox description text that contains a link that has a line break, touch targets for the clickable text are messed up and can prevent the checkbox from being checkable.

https://user-images.githubusercontent.com/1711417/108989032-73352700-7695-11eb-8503-4828265db9be.mp4

**Expected behavior:** Only actually tapping on the underlined text should open the link.

**Source code:** Create a layout that causes the checkbox text to wrap in a way that causes a line break between words that are part of a link. Example text with a link:

```xml
<string name="welcome_privacy_description">I have read and agree to the <a href="https://luca-app.de/app-privacy-policy">privacy policy</a></string>
```

**Android API version:** `28`, reproducible on older and newer SDK versions.

**Material Library version:** `1.3.0`, reproducible on older versions.

**Device:** AVD using the Pixel 2 preset, reproducible on different devices.

**Comment by josefigueroa168** [comment]
This issue of overlapping touch targets is unfortunately inherited from android checkbox widget. You can report a bug on this here: https://source.android.com/setup/contribute/report-bugs

In the meantime, I'd recommend using a constrained textview beside an empty text checkbox for this specific use case to enable more consistent touch targeting.

**Comment by Kisty** [comment]
@Steppschuh  I'm sorry this was ages ago but did you manage to report it to https://b.android.com? Encountering the same issue

**Comment by vvinogra** [comment]
Hey folks, I was able to make it work by using `LinkMovementMethodCompat`. Something like this:
```kotlin
binding.yourCheckbox.movementMethod = LinkMovementMethodCompat.getInstance()
```

From the `LinkMovementMethodCompat` doc:
```java
/**
 * Backwards compatible version of {@link LinkMovementMethod} which fixes the issue that links can
 * be triggered for touches outside of line bounds before Android V.
 */
```
