### ISSUE TITLE
[MaterialButtonToggleGroup] Rounded outline badly rendered

### ISSUE THREAD

**Issue by novotnyfra** [material-components/material-components-android#2102]
**Description:**
Buttons in `MaterialButtonToggleGroup` are not rendered correctly for the full rounded corners (when `cornerRadius` > height / 2)

![image](https://user-images.githubusercontent.com/26295670/109152061-09437d00-777c-11eb-9b80-39314fc7f06e.png)

**Expected behavior:** 
Fully rounded outline

**Source code:**

    <com.google.android.material.button.MaterialButton
        android:id="@+id/button_month"
        style="?attr/materialButtonOutlinedStyle"
        app:cornerRadius="@dimen/rounding_medium"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:text="Month" />

**Android API version:** Android API 29

**Material Library version:** 1.3.0

**Comment by drchen** [comment]
To change corner size, please override app:shapeAppearance in the style instead. 

You can do something like:

<com.google.android.material.button.MaterialButton
    android:id="@+id/button_month"
    style="?attr/materialButtonOutlinedStyle"
    app:shapeAppearance="@style/Your.ShapeAppearance"
    ... />

And define the shapeAppearance as:

<style name="Your.ShapeAppearance">
  <item name="cornerSize">50%</item>
</style>
