### ISSUE TITLE
[MaterialTimePicker] AM/PM position incorrect

### ISSUE THREAD

**Issue by bsanehi** [material-components/material-components-android#2108]
The AM/PM location is on the wrong side and the width is incorrect.

![image](https://user-images.githubusercontent.com/914014/109844334-f03b4000-7c43-11eb-9aa1-d7c865018c30.png)

**Expected behavior:** It should be on the right hand side.

**Source code:**
```
val picker =
                    MaterialTimePicker.Builder()
                            .setTimeFormat(TimeFormat.CLOCK_12H)
                            .setHour(HOUR_OF_DAY)
                            .setMinute(MINUTE)
                            .setTitleText("Select time")
                            .build()

            picker.show(this.supportFragmentManager, "SelectStartTime")
```

**Android API version:** API 28 and API 29

**Material Library version:** 1.4.0-alpha01

**Device:** Emulator Pixel 3 and Emulator Pixel 3a XL

**Comment by yashovardhan99** [comment]
Could this be due to a RTL layout?

**Comment by bsanehi** [comment]
I'm not using a RTL layout.

**Comment by bsanehi** [comment]
I upgraded my Android studio to version 4.2 from 3.2 and upgraded my android gradle plugin and version, and I no longer see the issue.

Will close this.
