### ISSUE TITLE
[Chip] Click Listener for ChipDrawable

### ISSUE THREAD

**Issue by rygalang** [material-components/material-components-android#2111]
**Is your feature request related to a problem? Please describe.**
The [Standalone ChipDrawable](https://github.com/material-components/material-components-android/blob/master/docs/components/Chip.md#standalone-chipdrawable) is missing `setOnCloseIconClickListener`(which exists in Chip).

**Describe the solution you'd like**
Provide a way to handle the close icon click.

**Comment by dsn5ft** [comment]
Hi @rygalang, I believe this is a general limitation of Drawables, in that they don't handle clicks directly. The Chip view handles clicks and figures out of the location of the click is within the bounds of the close icon. You might be able to do something similar by adding your own touch listener to the view where you're using the standalone ChipDrawable, and on touch checking if the touch is within the bounds of the close icon by using [ChipDrawable#getCloseIconTouchBounds](https://github.com/material-components/material-components-android/blob/1f6ebe9e7bb224cc3adc60de3944adfb9e8eaacb/lib/java/com/google/android/material/chip/ChipDrawable.java#L481).
