### ISSUE TITLE
[TabLayout] TabLayout doesnt scroll to selected tab without ViewPager

### ISSUE THREAD

**Issue by spartanmarty** [material-components/material-components-android#2113]
When I have TabLayout with tabMode scrollable, then selecting a tab doesnt cause view to scroll to selected tab, like it happens after i manually click on tab. The selected tab indicator moves fine. There is a possible workaround - use it with view pager and selecting item in ViewPager does the job. But if i dont need ViewPager, then I dont like doing workarounds to make it fine.

**Comment by drchen** [comment]
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.
