### ISSUE TITLE
[Chip] Setting current drawable state for updated icons

### ISSUE THREAD

**Issue by ViHtarb** [material-components/material-components-android#2118]
**Description:** When chipIcon updates and that icon is not stateful the current state of the view(checked etc) is ignored but chip can have chipIconTint and in result we can have icon without actual tint state

**Expected behavior:**
before icon update
![before icon update](https://user-images.githubusercontent.com/8938207/110528538-ebcdc600-8120-11eb-9322-aafa257666cf.png)
after icon update
![after icon update](https://user-images.githubusercontent.com/8938207/110528595-fd16d280-8120-11eb-94fc-7a4b58f416d3.png)

**Source code:** 
ChipStyle
```xml
<style name="Widget.Chip.Choice" parent="Widget.MaterialComponents.Chip.Choice">
        <item name="chipIconVisible">true</item>
        <item name="chipIconTint">@color/choice_chip_icon_tint</item>
</style>
```
choice_chip_icon_tint
```xml
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="?colorOnPrimary" android:state_enabled="true" android:state_selected="true"/>
    <item android:color="?colorOnPrimary" android:state_enabled="true" android:state_checked="true"/>
    <item android:color="?colorPrimary" android:state_enabled="true"/>
    <item android:alpha="0.35" android:color="?colorOnSurface"/>
</selector>
```
Chip in layout
```xml
<com.google.android.material.chip.Chip
      android:id="@+id/choice"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:text="Choice"
      app:chipIcon="@drawable/abc_vector_test"/>
````
And simply need change icon in code

**Material Library version:** 1.4.0-alpha01 and less

**Comment by debugmoov** [comment]
happens to me too. the above solution doesn't work for me, what does is resetting the chip icon tint
`chip.chipIconTint = null`
`chipIconTint = AppCompatResource.getColorStateList(context, colorResId)`
