### ISSUE TITLE
[BadgeDrawable] clearNumber() doesn't resize the badge to original blank size

### ISSUE THREAD

**Issue by shekibobo** [material-components/material-components-android#2123]
Using version 1.3.0, I've added a badge drawable to a toolbar menu item. When the badge number gets large, the size of the badge increases, and when it's small it decreases. However, when the badge number is cleared, there is no more number, but the badge size remains the size that fit the number before it was cleared.

Starting with no number:
![Screen Shot 2021-03-11 at 3 20 02 PM](https://user-images.githubusercontent.com/293858/110850113-6b70a780-827d-11eb-84ad-595f85a67425.png)
After clearing a number:
![Screen Shot 2021-03-11 at 3 19 47 PM](https://user-images.githubusercontent.com/293858/110850110-6ad81100-827d-11eb-877d-dc7d14de1145.png)

**Comment by wangzs** [comment]
face the same issue, i find not call updateCenterAndBounds in clearNumber, then cornerRadius is still using badgeWithTextRadius

call setMaxCharacterCount(0) after call clearNumber can solver the problem
