### ISSUE TITLE
Failing to Sync Material Components 1.3.0 with Android Studio 4.1.2

### ISSUE THREAD

**Issue by emmanuellmhango** [material-components/material-components-android#2125]
Android Studio 4.1.2 is Syncing forever when I use the new Material Components 1.3.0. I don't know if it's only me. until I changed and used Material Components material:1.2.0-alpha03

**Comment by drchen** [comment]
Is this still reproducible with the latest library?

**Comment by drchen** [comment]
I'll close the issue for now. Feel free to reopen it if it's still reproducible with the latest library. 

However I strongly suggest you report the issue to Android Studio instead. : )
