### ISSUE TITLE
[TextInputLayout] Hint text overlaps outline

### ISSUE THREAD

**Issue by RohitKhanduri04** [material-components/material-components-android#2127]
This same issue is getting replicated in the latest material component release 1.4.0-alpha01

_Originally posted by @RohitKhanduri04 in https://github.com/material-components/material-components-android/issues/597#issuecomment-797241216_

**Comment by pesjak** [comment]
Same problem. This is on Widget.MaterialComponents.TextInputLayout.OutlinedBox. 

`  
  <style name="Widget.TextInput.OutlinedBox" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="android:textColor">?attr/colorOnPrimary</item>
        <item name="boxStrokeColor">@color/color_outlined_box</item>
        <item name="hintTextColor">?attr/colorOnPrimary</item>
        <item name="android:textColorHint">@color/color_on_primary_unfocused</item>
    </style>

   <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/text_input_layout"
            style="@style/Widget.TextInput.OutlinedBox"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="48dp"
            android:layout_marginTop="16dp"
            android:layout_marginEnd="48dp"
            android:hint="@string/title_hint"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/text_input_title_edit_text"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:imeOptions="actionDone"
                android:inputType="textCapSentences"
                android:maxLength="20"
                android:textColor="?attr/colorOnPrimary"
                android:textSize="24sp" />

        </com.google.android.material.textfield.TextInputLayout>
`

**Comment by riggaroo** [comment]
We are also experiencing this 😢 When upgrading to the latest 1.4.0-alpha02, the strikethrough appears
![image](https://user-images.githubusercontent.com/9973046/116859619-8cf86a80-ac00-11eb-81cd-d45b0bdd3b35.png)

**Comment by pesjak** [comment]
I've read somewhere that this is a problem, if you have a custom font in the app.

**Comment by leticiarossi** [comment]
could someone provide a sample app with the issue happening? I'm not able to reproduce it

**Comment by pesjak** [comment]
Here you go:
https://github.com/pesjak/BugApplication

**Comment by AravinthSri** [comment]
> I am also seeing this in 1.4.0-alpha01 (on a Pixel 3). This is my xml:
> 
> ```
> <com.google.android.material.textfield.TextInputLayout
>     android:id="@+id/til_email"
>     style="@style/FormInputLayoutStyle"
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content"
>     android:layout_below="@id/header_layout"
>     android:layout_marginTop="@dimen/margin_large"
>     android:hint="@string/email_address">
> 
>     <com.google.android.material.textfield.TextInputEditText
>         android:id="@+id/et_email"
>         style="@style/FormInputTextStyle"
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"
>         android:imeOptions="actionDone"
>         android:inputType="textEmailAddress"
>         android:maxLines="1"
>         android:text="@={viewModel.email}" />
> 
> </com.google.android.material.textfield.TextInputLayout>
> ```
> 
> This is how it appears:
> <img alt="Screen Shot 2021-03-30 at 2 32 46 PM" width="343" src="https://user-images.githubusercontent.com/5865054/113052800-cd2d7e80-9164-11eb-8e28-9df68db38377.png">

Same issue appear in 

Device Tested : oneplus 7t
Android Version : 11
Build number : Oxygen OS 11.0.0.2.HD65AA

**Comment by stephen-mojo** [comment]
I am experiencing a very similar issue with v1.4.0-rc01.

![example](https://user-images.githubusercontent.com/69835692/123336676-0e7ec180-d4fb-11eb-8a90-09af6713e00a.png)

Here is an example repository using Material Components v1.4.0-rc01 that exhibits the issue:
https://github.com/stephen-mojo/overlap-example
