### ISSUE TITLE
[BadgeUtils] Detachment from Toolbar Menu Item does not remove offset added during attachment

### ISSUE THREAD

**Issue by shekibobo** [material-components/material-components-android#2129]
**Description:**

When a `BadgeDrawable` is attached to a Toolbar menu item, it adds horizontal and vertical offset. These offsets are not removed when a `BadgeDrawable` is removed. Therefore, adding and removing the drawable multiple times will add an additional 12dp offset to the left and down. Additionally, if a badge is present on a menu item, and an adjacent menu item has its visibility toggled, the badge will disappear and will not come back, even after adding or removing the badge.

**Expected behavior:** 

A badge should maintain its position when attached to or detached from a Toolbar. Ideally, attaching a badge would be idempotent, and would not have a cumulative side-effect on the badge, but if detachment is required before re-attachment, that requirement should be documented.

**Source code:** 

1. In a layout, create a `MaterialToolbar` with two menu items. 
2. Attach a `BadgeDrawable` to one of the menu items. 
3. Hide the first menu item. 
4. Observe that the badge attached to the other item disappears.

1. In a layout, create a `MaterialToolbar` with a menu item.
2. Create a `BadgeDrawable`.
3. Add a menu item click listener to detach and attach the badge drawable.
4. Observe that the badge on the menu item is shifted each time it is clicked.

**Android API version:** API 30

**Material Library version:** 1.3.0

**Device:** Pixel 3A API 30 Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by shekibobo** [comment]
I've gotten some code written in Kotlin that seems to solve the problem of keeping badges on toolbar menu items in the right place as the toolbar is redrawn and the action menu items change:


```kotlin
// AKA ToolbarUtils.getActionMenuView
fun Toolbar.getActionMenuView(): ActionMenuView? {
    return children.find { it is ActionMenuView }?.let { it as ActionMenuView }
}

@SuppressLint("RestrictedApi")
// AKA ToolbarUtils.getActionMenuItemView
fun ActionMenuView.getActionMenuItemView(@IdRes menuItemId: Int): ActionMenuItemView? {
    return children.find { it is ActionMenuItemView && it.itemData?.itemId == menuItemId }
        ?.let { it as ActionMenuItemView }
}

@SuppressLint("UnsafeExperimentalUsageError")
fun Toolbar.attachMenuItemBadge(@IdRes menuItemId: Int, badgeDrawable: BadgeDrawable) {
    // If you don't detach first, strange things will happen, like the badge being put on the wrong action item.
    detachMenuItemBadge(badgeDrawable)
    getActionMenuView()?.getActionMenuItemView(menuItemId)?.also { actionMenuItemView ->
        // Doing this on `post` doesn't seem to draw it if set when the view is first set up - it must be in doOnLayout.
        doOnLayout {
            BadgeUtils.attachBadgeDrawable(badgeDrawable, actionMenuItemView)

            // Must be done after attachment because intrinsic width either isn't set or isn't
            // measured yet before.
            badgeDrawable.horizontalOffset =
                actionMenuItemView.totalPaddingEnd + badgeDrawable.intrinsicWidth / 2
            badgeDrawable.verticalOffset = actionMenuItemView.totalPaddingTop
        }
    }
}

fun Toolbar.detachMenuItemBadge(badgeDrawable: BadgeDrawable) {
    doOnLayout {
        // If you don't remove it from every menu item, it could still stick around in a detached state.
        getActionMenuView()?.children
            ?.filter { it is ActionMenuItemView }
            ?.map { it as ActionMenuItemView }
            ?.forEach { actionMenuItemView -> actionMenuItemView.overlay.remove(badgeDrawable) }
    }
}
```

The issue seems to be that the toolbar redraws its menu in ways that don't really maintain the state of views that you'd expect. It seems to reuse some action item views if one is hidden, so your badge will end up in the wrong place if it's not cleared from every item's overlay.

This could all theoretically be rewritten in Java, but it'll be much more complicated.

**Comment by wcshi** [comment]
Thanks for reporting the issues.
As a temporary workaround for the badge shifting when it is attached and detached from the toolbar, have you tried changing the visibility of the badge instead of detaching it?

**Comment by shekibobo** [comment]
I will give it a try, but the detach appears to need to run on all `ActionMenuItemView` instances because those views get recycled by the toolbar in unexpected ways if they toggle visibility. If you don't remove it, it can be attached to multiple overlays.

**Comment by wcshi** [comment]
Quick update, I started working on a fix, hope to get it reviewed next week.
