### ISSUE TITLE
[BottomNavigationItemView] From 1.4.0-alpha01 how add custom item programaticaly ?

### ISSUE THREAD

**Issue by JorisBodin** [material-components/material-components-android#2131]
Now in 1.4 BottomNavigationItemView is private 😢 

My code :

    private fun setBottomNavigationUserAvatar(context: Context) {
        lifecycleScope.launch(Dispatchers.IO) {
            val menuItemView = (bottomNavigation.getChildAt(0) as BottomNavigationMenuView)[4] as BottomNavigationItemView
            val imageLoader = Coil.imageLoader(context)
            val request = ImageRequest.Builder(context)
                .data(AccountUtils.currentUser?.avatar)
                .transformations(CircleCropTransformation())
                .fallback(R.drawable.ic_account)
                .listener { _, _ ->
                    menuItemView.setIconTintList(null)
                }.build()
            val userAvatar = imageLoader.execute(request).drawable

            userAvatar?.let {
                val selectedAvatar = generateSelectedAvatar(userAvatar)
                val stateListDrawable = StateListDrawable()
                stateListDrawable.addState(intArrayOf(android.R.attr.state_checked), BitmapDrawable(resources, selectedAvatar))
                stateListDrawable.addState(intArrayOf(), userAvatar)

                withContext(Dispatchers.Main) {
                    menuItemView.setIcon(stateListDrawable)
                    bottomNavigation.menu.findItem(R.id.menuFragment).icon = stateListDrawable
                }
            }
        }
    }
    
What is the solution now with 1.4 to customize an item?
    
Thanks

**Comment by dsn5ft** [comment]
Hi @JorisBodin, I believe `BottomNavigationItemView` has always been private. Is there something else about 1.4 that made this more difficult to do?

Does `bottomNavigation.menu.findItem(R.id.menuFragment).icon = stateListDrawable` work?

**Comment by JorisBodin** [comment]
> Hi @JorisBodin, I believe `BottomNavigationItemView` has always been private. Is there something else about 1.4 that made this more difficult to do?
> 
> Does `bottomNavigation.menu.findItem(R.id.menuFragment).icon = stateListDrawable` work?

No, doesn't work :(

In 1.3 it was an lib restriction, with _@SuppressLint("RestrictedApi")_ it's worked:
![image](https://user-images.githubusercontent.com/2796439/111195789-ebb84500-85bc-11eb-8ae4-60f3433b1214.png)

But with 1.4:
![image](https://user-images.githubusercontent.com/2796439/111195667-c7f4ff00-85bc-11eb-92a7-98547f1113cb.png)

It must have changed with this:
> NavigationRail 
> Extracted common logic from bottom navigation component into navigation package. (aca5bfb)
https://github.com/material-components/material-components-android/releases/tag/1.4.0-alpha01

**Comment by dsn5ft** [comment]
Hmm @raajkumars can you look into this more?

**Comment by raajkumars** [comment]
@JorisBodin is correct. The class BottomNavigationItemView used to restricted to library, but otherwise marked as a public class. This was changed to  package protected during the refactor. While we look into this, please see consider casting the object to NavigationBarItemView instead of BottomNavigationItemView to solve the issue in your code.

**Comment by JorisBodin** [comment]
@raajkumars  Thank you for your reply

I use BottomNavigationItemView instead of NavigationBarItemView, because i am custom this for show a fab like this:
![image](https://user-images.githubusercontent.com/2796439/111201404-055c8b00-85c3-11eb-95d4-a805f34c5996.png)

When I had searched at the beginning of my project, I had not found a solution with NavigationBarItemView :/

**Comment by raajkumars** [comment]
@JorisBodin Thanks for the clarification. The methods that used in BottomNavigationItemView before have been moved to NavigationBarItemView during the refactor. Looking at the code you shared, casting the object to NavigationBarItemView should work. Have you tried this?

As for the customization you mentioned, if you can share the relevant code sections, it may help me provide a workaround to unblock you.

**Comment by JorisBodin** [comment]
Oh is just a rename 😍
It's perfect with _ NavigationBarItemView_

I push my application the next week, I will share the code here at this time 👯‍♀️
