### ISSUE TITLE
[TextInputLayout] `floating label` background problem with custom font

### ISSUE THREAD

**Issue by JorisBodin** [material-components/material-components-android#2135]
**Description:** 
This commit https://github.com/material-components/material-components-android/commit/6015a4e901dc55a02f86e12703820d520684f95e fix a old problem, but now it's not working with custom font :(
![image](https://user-images.githubusercontent.com/2796439/111356939-225b9180-8689-11eb-8139-4b9f13044eca.png)

Without custom font :
![image](https://user-images.githubusercontent.com/2796439/111357729-d9f0a380-8689-11eb-9abf-d6e98800d6aa.png)

**Source code:**

    <com.google.android.material.textfield.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="4dp"
        android:hint="@string/cat_textfield_label"
        app:boxBackgroundColor="@android:color/white"
        app:boxBackgroundMode="outline"
        app:counterEnabled="true"
        app:counterMaxLength="10"
        app:errorEnabled="true"
        app:helperText="@string/cat_textfield_outlined_helper_text"
        app:helperTextEnabled="true"
        app:placeholderText="@string/cat_textfield_placeholder_text">
      <com.google.android.material.textfield.TextInputEditText
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:fontFamily="@font/suisseintl_regular" />
    </com.google.android.material.textfield.TextInputLayout>

https://github.com/material-components/material-components-android/blob/201ec6241cec4cc590dd806fd0896da5fa3140f0/catalog/java/io/material/catalog/textfield/res/layout/cat_textfield_outlined_content.xml#L38

**Android API version:** 30

**Material Library version:** 1.4.0-alpha01

**Comment by JorisBodin** [comment]
In 1.4.0-alpha02 it's same :/

**Comment by SashaCube** [comment]
On version 1.4.0-beta01 this issue seems to be fixed
[related issue](https://github.com/material-components/material-components-android/issues/2127)

**Comment by JorisBodin** [comment]
On version 1.4.0-beta01 is fixed !
