### ISSUE TITLE
[TabLayout] Selected tab indicator color is not applied instantly at runtime

### ISSUE THREAD

**Issue by Artman12** [material-components/material-components-android#2136]
**Description:** I need to change color of `tabIndicatorColor `at runtime. When I use setSelectedTabIndicatorColor the color is not applied until I change tab. calling TabLayout.invalidate() does not help. 

**Expected behavior:** Tab indicator color is changed instantly

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** 30

**Material Library version:** 1.4.0-alpha01

**Device:** Pixel 3a

**Comment by vegesm** [comment]
In addition to this, setSelectedTabIndicatorColor does not work properly with Color.TRANSPARENT. Once setSelectedTabIndicatorColor is called with another color, it is impossible to set it back to the drawable default tint via `setSelectedTabIndicatorColor(Color.TRANSPARENT)`.
