### ISSUE TITLE
Request: Update BottomSheet edge to edge style api names

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android#2137]
Bottom sheets now apparently adhere to these theme styles: 

>On API 21 and above the BottomSheet will be rendered fullscreen (edge to edge) if the navigationBar is transparent, and enableEdgeToEdge is true. It can automatically add insets if any of paddingBottomSystemWindowInsets, paddingLeftSystemWindowInsets, paddingRightSystemWindowInsets, or paddingTopSystemWindowInsets are set to true in the style, either by updating the style passed to the constructor, or by updating the default style specified by the bottomSheetDialogTheme attribute in your theme.

Which is a little misleading in my opinion because it seems like setting paddingBottomSystemWindowInsets will enable padding throughout the whole app.

```
   <style name="RollerToasterTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <!-- Window decor -->
        <item name="android:statusBarColor">@color/transparent</item>
        <item name="android:navigationBarColor">@color/navcolor</item>
        <item name="enableEdgeToEdge">true</item>
        <item name="paddingBottomSystemWindowInsets">true</item>
    </style>
```

Am I applying the attributes in the wrong place? Wouldn't a better name be `bottomSheetEnableEdgeToEdge` and `bottomSheetPaddingBottomSystemWindowInsets`?

**Comment by AfzalivE** [comment]
Is that style your `bottomSheetDialogTheme`? Or the theme for your whole app?

It should be set like this in your app's theme:

https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/application/theme/res/values/themes.xml#L23

```
<style name="Theme.Catalog" parent="Theme.MaterialComponents.DayNight.NoActionBar">
    <item name="catalogToolbarStyle">@style/Widget.Catalog.Toolbar</item>
    <item name="catalogToolbarWithCloseButtonStyle">@style/Widget.Catalog.Toolbar.WithCloseButton</item>
    <item name="textInputSignInStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>
    <item name="bottomSheetDialogTheme">@style/ThemeOverlay.Catalog.BottomSheetDialog</item>
    <item name="windowActionModeOverlay">true</item>
</style>
```

Where `ThemeOverlay.Catalog.BottomSheetDialog` is like this:

```
<style name="ThemeOverlay.Catalog.BottomSheetDialog" parent="ThemeOverlay.MaterialComponents.BottomSheetDialog">
        <item name="paddingBottomSystemWindowInsets">true</item>
</style>
```

At least that's my understanding.

**Comment by drchen** [comment]
Well it's meant to be set in the bottom sheet styles. (Setting it in themes of course also works though...)

So I think the name is fine. And since it's a public API we can't really to change it either...
