### ISSUE TITLE
[MaterialShape] Elevation Shadow color

### ISSUE THREAD

**Issue by dovahkiin98** [material-components/material-components-android#2140]
As of Android 28 (aka, Android 9 Pie), new functions were added to change the color of the shadow of a View.

Since Material Components is made to help accomplish compatibility and consistent behaviour between platform versions.
What is the possibility of adding the `setAmbientShadowColor` and shadow coloring in general to Material Components?

**Comment by drchen** [comment]
"""Material Components is made to help accomplish compatibility and consistent behaviour between platform versions."""

Basically it's AppCompat's goal, not Material's. (Usually we have no way to achieve that at all. We need to rely on AppCompat instead.)

I'll close the feature request as infeasible. : )
