### ISSUE TITLE
[RangeSlider] 'if' branch in OnChangeListener always faster than 'else' branch

### ISSUE THREAD

**Issue by shmueldabomb441** [material-components/material-components-android#2142]
**Description:** 
There is no built-in way that I have found to tell which slider is being moved in the OnChangeListener, so I do:
```
slider.apply {
//set valueFrom and valueTo and default values
    this.addOnChangeListener {_,value,_ ->
        value.myTransform().let {
            if(value == values[0]) startValueTextView.text = it
            else endValueTextView.text = it
        }
    }
}
```
**Expected behavior:** 
The textview in the 'else' branch (in this case the endValueTextView) will be a random number when the user slides the  corresponding slider rapidly back and forth between touching the start slider thumb and anywhere behind the start slider thumb (e.g. if valueFrom is 0 and valueTo is 100, and the start slider is at 20, sliding the end slider between 20 and 100 rapidly will result in the endValueTextView displaying a random value every time the end slider meets the start slider at 20). Swapping the endValueTextView and startValueTextView will move the bug from the endValueTextView to the startValueTextView; hence, whichever textview is being updated in the 'else' branch will result in a random number, and the one in the 'if' branch will be the same/correct number every time.
**Source code:** See above.

**Android API version:** 28 (Android 9)

**Material Library version:** 1.3.0
**Device:** Samsung Galaxy S8

**Comment by kroegerama** [comment]
Not really a fix, but why don't you just write something like this?

```kotlin
slider.addOnChangeListener {_,_,_ ->
    val (a,b) = slider.values //shorthand for val a = slider.values[0]; val b = slider.values[1]
    val left = minOf(a, b)
    val right = maxOf(a, b)
    //TODO: Add transform to left/right here and write to label
}
```

Another tip for you: Don't overuse `apply` `let` `run` and `also`. They are nice to use, but can lead to quite ugly/unreadable code :)

**Comment by shmueldabomb441** [comment]
Clever idea!

**Comment by drchen** [comment]
Your  """if(value == values[0])""" check results in the bug you describe I think.

When you move the end thumb to the same position of the start thumb, you get two values with the same value, so it will always be the startValueTextView to be updated (and leave endValueTextView with its previous value, or "random" in your words.)

What kroegerama suggests is the right solution btw. : )
