### ISSUE TITLE
[MaterialToolbar] No attribute app:titleCentered

### ISSUE THREAD

**Issue by beneventolorenzo** [material-components/material-components-android#2143]
**Description:** There is no attribute app:titleCentered but it should be present according to material.io documentation.

**Expected behavior:** The attribute should be present.

**Source code:** I think there is no need for sample code, but I'm absolutely available to provide some code if needed.

**Android API version:** R

**Material Library version:** 1.3.0

**Device:** Can't compile.

**Comment by dsn5ft** [comment]
Hi @beneventolorenzo, app:titleCentered on MaterialToolbar is a brand new feature (cbf528e), so it's not part of 1.3.0. It will be in the next 1.4 alpha release coming soon, and in the meantime you can try it out with our [snapshot release](https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md).

**Comment by beneventolorenzo** [comment]
Oh okay, I'm sorry for the inappropriate issue then, I figured something in the documentation would be in the current release, my bad.
