### ISSUE TITLE
[RangeSlider] Thumb highlight animation (ripple) on the wrong thumb

### ISSUE THREAD

**Issue by kroegerama** [material-components/material-components-android#2150]
**Description:** When I move one thumb and then start moving the other thumb, the ripple animation starts from the first last touched thumb instead of the current one. See the following gif:
![range-slider-bug](https://user-images.githubusercontent.com/1519044/112446657-ba740d80-8d50-11eb-9614-161e8271d830.gif)

**Expected behavior:** The ripple effect always starts on the correct thumb.

**Android API version:** Android 11, API 30

**Material Library version:** `1.4.0-alpha01` and `1.3.0`

**Device:** `Pixel 4a 5G` and `Pixel 3 XL`

**Comment by drchen** [comment]
Fixed by https://github.com/material-components/material-components-android/commit/8431bd43ebd8978ff8ed2862fd715fd6072d0b98

**Comment by SamShouman** [comment]
hello, is there a way to disable the ripple color?
tried  `pp:itemRippleColor="@null"` did not work
