### ISSUE TITLE
[BottomSheetDialogFragment] Shadow animation is wierd

### ISSUE THREAD

**Issue by ashley-figueira** [material-components/material-components-android#2151]
**Description:** 
When the bottom sheet comes up the shadow animation is wierd

**Expected behavior:** 
Smooth shadow animation

**Source code:** 
```
class SomeNamedFragment : BottomSheetDialogFragment() {

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return inflater.inflate(R.layout.fragment_random_layout, container, false)
    }

    companion object {
        fun newInstance(): SomeNamedFragment = SomeNamedFragment()
    }
}
```

```
SomeNamedFragment.newInstance().show(parentFragmentManager, "dialog")
```

**Material Library version:** 1.4.0-alpha01

**Device:** 
Any device

https://user-images.githubusercontent.com/9158910/112500541-c380d100-8d88-11eb-86b7-8b204a89e02d.mp4

**Comment by drchen** [comment]
I can't reproduce the issue. Are you setting any fragment transitions?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
