### ISSUE TITLE
[TextInputLayout] TextInputLayout with TextInputEditText drastically slowing down inflation

### ISSUE THREAD

**Issue by victoraap** [material-components/material-components-android#2160]
Description: When inflating a layout, the presence of a TextInputLayout makes the inflation noticably slower. It's enough to add two TILs to a layout to start noticing a lag on my device (nokia 7.1, which is not high-end but not the worst phone either). It happens even when I put them in a simple linearlayout with no other views. On the other hand, if I inflate a layout with even 10 EditTexts, there is no lag whatsoever.

You can reproduce it on this basic sample (the dashboard fragment contains a few TILs and the notifications one contains normal EditTexts): https://drive.google.com/file/d/1DwvxzHM74TChIJGuttkRF6SRPcb8fEGd/view?usp=sharing

Here is a screenrecord using the sample I provided. First I navigate to the fragment with basic EditTexts and there is no lag, then I navigate to the one with TILs and there's the lag. It might not look that severe, but in a layout with other widgets the inflation times add up and it's enough to have a single TIL to get a bad UX.
https://drive.google.com/file/d/12P-XErDnZjSuhIwSqV6f9ydzYHQGUDZU/view?usp=sharing

previously filed at https://issuetracker.google.com/issues/168869410 , was told to refile here

Expected behavior: TextInputLayout should inflate much faster, at least so that it doesn't cause any lags in fragment transitions when you have a few of them in your layout

Source code: https://drive.google.com/file/d/1DwvxzHM74TChIJGuttkRF6SRPcb8fEGd/view?usp=sharing

Android API version: Tested with API 29

Material Library version: 1.3.0-alpha02

**Comment by yamin8000** [comment]
same problem

**Comment by ArcherEmiya05** [comment]
It just not slowing down the inflation, but also slowing down the whole screen which is very visible when you have multiple TextInputLayout with TextInputEditText field and trying to switch focus on each of them. The hint animation was lagging.

**Comment by leticiarossi** [comment]
We've made some changes to improve the inflate/measure performance time in https://github.com/material-components/material-components-android/commit/26d862bc5433eb50ba0875e136ff937d4e5ae617

**Comment by yamin8000** [comment]
> We've made some changes to improve the inflate/measure performance time in [26d862b](https://github.com/material-components/material-components-android/commit/26d862bc5433eb50ba0875e136ff937d4e5ae617)

Noice.
