### ISSUE TITLE
Error inflating class com.google.android.material.tabs.TabLayout, The style on this component requires your app theme to be Theme.AppCompat (or a descendant).

### ISSUE THREAD

**Issue by MasonTModea** [material-components/material-components-android#2164]
**Description:** When navigating to a page with TabLayout, I get: `Error inflating class com.google.android.material.tabs.TabLayout, The style on this component requires your app theme to be Theme.AppCompat (or a descendant).`

**Expected behavior:** App does not crash.

**Source code:** 
```java
Intent nextScreen = WidgetFactory.getWidgetIntent(widget, this.bridge.getActivity());
            if (WidgetFactory.canAccessWidget(widget) && nextScreen != null) {
                getActivity().startActivity(nextScreen);
            } else {
                success = false;
                showAccessDialog();
            }
```

**Android API version:** 29

**Material Library version:** 'com.google.android.material:material:1.0.0'

**Device:** Google Pixel 4, Google Pixel 3

**Comment by afohrman** [comment]
Hi there, what theme are you using?

**Comment by MasonTModea** [comment]
This was due to other issues. The error log was incorrect. Closing.
