### ISSUE TITLE
[TextInputLayout] the space between hint and text is so small

### ISSUE THREAD

**Issue by ONVETI** [material-components/material-components-android#2167]
**Description:** TextInputLayout the space between hint and text is so small

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** 

`<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/emailTextInputLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:endIconMode="clear_text"
            app:boxBackgroundColor="@color/white_dark"
            app:boxStrokeColor="@color/divider"
            android:hint="@string/email"
            app:hintTextColor="@color/text_grey"
            app:layout_constraintTop_toBottomOf="@+id/divider3"
            android:theme="@style/TextInputLayoutAppearance">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/emailTextView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="@={viewModel.email}"
                android:inputType="textEmailAddress"
                android:maxLines="1"/>

        </com.google.android.material.textfield.TextInputLayout>`

**Android API version:** 29

**Material Library version:**     implementation 'com.google.android.material:material:1.4.0-alpha02'

**BUG VERSION** 
**Material Library version:**     implementation 'com.google.android.material:material:1.4.0-alpha02'
Android 29 api
device: pixel 2
![pixel 2 library 1 4 0-alpha02](https://user-images.githubusercontent.com/70847827/113823420-1189d180-9798-11eb-9e7c-856728bb71ba.png)

**NOT BUG VERSION**  
**Material Library version:**         implementation 'com.google.android.material:material:1.1.0-rc01'
Android 29 api
device: pixel 2
![pixel 2 library 1 1 0-rc01](https://user-images.githubusercontent.com/70847827/113823430-13539500-9798-11eb-844b-f95257fcfa43.png)

**Device:** Pixel 2

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by afohrman** [comment]
It looks like you're setting the TextInputLayout style as a theme overlay rather than a style, by using `android:theme` instead of `style="?attr/textInputStyle"` or `style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox`. It's important to set the style using `style=` because setting it as a theme overlay can cause some attributes to be dropped or be set incorrectly. 

Please try changing the style to be set as a style instead of a theme overlay and see if it fixes the issue.

**Comment by darktheft** [comment]
@@@@
@@@@
@@@@

**Comment by drchen** [comment]
Close the issue since no further update from the reporter. Assuming the solution works.
