### ISSUE TITLE
Is there any due date for those not implemented components?

### ISSUE THREAD

**Issue by guangyya** [material-components/material-components-android#217]
I have seen plenty of components labeled as "Planed" but no due date or clear release plan for this.

I am quite doubt when we could use these in our production codes.

**Comment by csbenz** [comment]
I'm wondering this as well and unfortunately I think the team has no dates for releasing new components, they'll just be coming as they advance with the library  🙄

**Comment by afohrman** [comment]
Please refer to the [Material Components roadmap](https://github.com/material-components/material-components/blob/develop/ROADMAP.md) for our release plan.

**Comment by Thomas-Vos** [comment]
What about the Extended FAB? The roadmap says it was planned for July but the Android column says "--". What does that mean?
