### ISSUE TITLE
[Mobile input picker] hint date format change when the language is changed

### ISSUE THREAD

**Issue by alianikaydin** [material-components/material-components-android#2170]
**Description:** hint date format change when the language is changed

**Expected behavior:** the date format should be the same in all languages

![Screenshot_20210407-144217](https://user-images.githubusercontent.com/6616473/113912291-9fd77500-97e3-11eb-9726-282d273a8c3e.jpg)
![Screenshot_20210407-144309](https://user-images.githubusercontent.com/6616473/113912355-afef5480-97e3-11eb-8150-6025f0681377.jpg)
![Screenshot_20210407-144527](https://user-images.githubusercontent.com/6616473/113912372-b4b40880-97e3-11eb-8956-7eecfd965836.jpg)

**Android API version:** 30

**Material Library version:** 1.3.0-alpha03

**Device:** samsung SM-A715F

**Comment by drchen** [comment]
Hi, we consulted our localization team and we do believe this is working as intended, considering that different countries can actually have different generally used date formats.
