### ISSUE TITLE
[ExposedDropDownMenu ] Can't use OutlineBox

### ISSUE THREAD

**Issue by darktheft** [material-components/material-components-android#2175]
Unable to use [ExposedDropDownMenu] style Widget.MaterialComponents.TextInputLayout.*.ExposedDropdownMenu
when 
implementation 'com.google.android.material:material:1.0.0'// ExposedDropDownMenu is not showing 

when 
implementation 'com.google.android.material:material:1.++'// showing style ExposedDropDownMenu but in this case i'm unable to use @style/ThemeOverlay.MaterialComponents.TextInputEditText.OutlinedBox =>
please help me,

thanks,

**Comment by afohrman** [comment]
Hi there, can you provide some more information about the issue? `ExposedDropDownMenu` was not included in 'com.google.android.material:material:1.0.0', so it's expected that it would not be available in `1.0.0`. What's going wrong when trying to use `ExposedDropdownMenu` in later versions?

Please provide a code sample, error logs and a screenshot if applicable.

**Comment by darktheft** [comment]
yeah  same version of material design 1.0.0.
