### ISSUE TITLE
Widgets not clickable on Android 12

### ISSUE THREAD

**Issue by PavelDolbik** [material-components/material-components-android#2178]
**Description:** After the scroll, widgets are not clickable, but the delay in a few seconds allows do this.

**Expected behavior:** Widgets clickable immediately after scroll.

**Android API version:** Android 12 developer preview 2

**Material Library version:** Material Android Library version 1.4.0-alpha02

**Device:** Google Pixel 4

https://user-images.githubusercontent.com/10083521/114721333-7f5a6e00-9d41-11eb-8c2e-78f51dbfc51d.mp4

**Comment by afohrman** [comment]
Interesting bug, thank you for reporting. Are you seeing this with other components, as well? Can you test this with an earlier version of the Material library on the same API level? It's possible that this is an issue with System UI so this would help isolate the source of the bug.

**Comment by PavelDolbik** [comment]
Version `1.3.0` has the same problems. 
It looks like the elements inside the `ScrollView` widget don't clickable immediately after the scroll. 


https://user-images.githubusercontent.com/10083521/114989111-c65e7580-9e9f-11eb-9a4b-e83f3ad54afd.mp4

**Comment by PavelDolbik** [comment]
The problem is gone after the update to the new version (SPP3.210325.010).
