### ISSUE TITLE
[AppBarLayout] ScrollingViewBehavior doesn't work properly with NestedScrollView

### ISSUE THREAD

**Issue by Dosssik** [material-components/material-components-android#2180]
Hi there ✌️

I faced an issue with nested scrolling and as far as I can see - the problem is somewhere inside `AppBarLaoyut.ScrollingViewBehavior`. 

**Description:** 

I have a fragment with `AppBarLayout` and `NestedScrollView` inside a `CoordinatorLayout`. It worked pretty good until I added the trivial onClickListener for the view, which locates deep down inside the NestedScrollView child (`NestedScrollView`->`ConstraintLayout`->`ViewPager2`->`RecyclerView`->**`FrameLayout` (view holder)**).

After this, the scroll behavior became broken - the `NestedScrollView` scrolls independently of `AppBarLayout`. There are 2 videos to compare: 

_Without click listener:_

https://user-images.githubusercontent.com/12698708/114872281-737eb280-9dfa-11eb-9340-a2ca7e9de7f2.mp4

_With click listener:_

Just to make it clear - the only differences between 2 videos above is `frameLayout.setOnClickListener(...)`

https://user-images.githubusercontent.com/12698708/114872341-84c7bf00-9dfa-11eb-98f7-957493330092.mp4

Looks like if there are some views that handle touch event (e.g. for handle clicks) inside the NestedScrollView then the nested scroll works unproperly. I double-checked which view is scrolling - it's not a RecyclerView, it's NestedScrollView, which actually should pass the touch event to the parent (Coordinator) according to the `AppBarLaoyut.ScrollingViewBehavior`.

**Expected behavior:** 

https://user-images.githubusercontent.com/12698708/114872281-737eb280-9dfa-11eb-9340-a2ca7e9de7f2.mp4

**Source code:** 
I omitted some irrelevant details (like colors, ids, etc) to reduce code amount:

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout >

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:clipChildren="false"
            android:minHeight="@dimen/series_collapsing_toolbar_min_height"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <FrameLayout
                    ...
                    />

            </androidx.constraintlayout.widget.ConstraintLayout>

            <FrameLayout
                app:layout_collapseMode="pin">

                <TextView/>

            </FrameLayout>

            <ImageView/>

            <ImageView />


        </com.google.android.material.appbar.CollapsingToolbarLayout>

        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/tabsContainer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/background">

            <View  />

            <View  />

            <com.google.android.material.tabs.TabLayout  />

        </androidx.constraintlayout.widget.ConstraintLayout>

    </com.google.android.material.appbar.AppBarLayout>

    <androidx.core.widget.NestedScrollView
        android:id="@+id/nestedScrollContainer"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/background">

            <!--  there is a recycler view on each page of view pager  -->

            <androidx.viewpager2.widget.ViewPager2
                android:id="@+id/viewpager"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/modules"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="35dp"
                app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/viewpager" />

        </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.core.widget.NestedScrollView>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Android API version:** 30

**Material Library version:** 1.3.0

**Device:** Google Pixel 4 XL

**Comment by pedrodimoura** [comment]
I am facing the same issue but when I use this approach inside the BottomSheetDialogFragment

**Comment by Dosssik** [comment]
Well, for some seekers who will be stuck with the same issue - here is my solution.

I checked every view in the hierarchy and found out it was ViewPager2 who make the mess. It intercepts touch events and handles them the wrong way. So, it's not related to the material components, I'm sorry for the irrelevant issue here.
My final fix was to disable this behaviour of the ViewPager2 - `viewpager.isUserInputEnabled = false`.

Happy coding 🤓
