### ISSUE TITLE
MaterialStyledDatePickerDialog can only be called from tests

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2181]
Why is this class restricted?

`MaterialStyledDatePickerDialog can only be called from within the same library group (groupId=com.google.android.material)`

What is the purpose of this as I wanted to use MaterialDatePicker with this constructor?

```

public MaterialStyledDatePickerDialog(
      @NonNull Context context,
      int themeResId,
      @Nullable OnDateSetListener listener,
      int year,
      int monthOfYear,
      int dayOfMonth)
```

**Comment by drchen** [comment]
Please just use MaterialDatePicker to create a date picker.

I believe this class is obsolete and should be removed.
