### ISSUE TITLE
[ShapeableImageView] Badge attached to ShapeableImageView is cut

### ISSUE THREAD

**Issue by mar3kk** [material-components/material-components-android#2182]
**Description:**
Trying to attach a `BadgeDrawable` to a `ShapeableImageView` results in the part of the badge that exceeds the ShapeableImageView bounds to be cut. 
I guess I understand this is due to how the shape is being rendered and the fact that the Badge becomes a part (layer) of the actual View it is attached to. But is there any plan for fixing it on a library level or should developers just wrap `ShapeableImageView` with `FrameLayout` and attach the badge to the FrameLayout instead?

![image](https://user-images.githubusercontent.com/3756427/115074323-d86d0200-9ef9-11eb-8501-7a7119f51b07.png)

**Expected behavior:** 
Badge should be completely visible as in case of regular ImageView

![image](https://user-images.githubusercontent.com/3756427/115074502-11a57200-9efa-11eb-96b5-298fb404aa98.png)

**Source code:**

```kotlin
package com.threekkapps.badge

import android.os.Bundle
import android.view.ViewTreeObserver
import androidx.appcompat.app.AppCompatActivity
import com.google.android.material.badge.BadgeDrawable
import com.google.android.material.badge.BadgeUtils
import com.google.android.material.imageview.ShapeableImageView

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val imageView = findViewById<ShapeableImageView>(R.id.imageView)
        val badge = BadgeDrawable.create(this@MainActivity).apply { number = 8 }
        imageView.viewTreeObserver.addOnGlobalLayoutListener(
            object : ViewTreeObserver.OnGlobalLayoutListener {
                override fun onGlobalLayout() {
                    BadgeUtils.attachBadgeDrawable(badge, imageView, null)
                    imageView.viewTreeObserver.removeOnGlobalLayoutListener(this)
                }
            }
        )
    }
}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.google.android.material.imageview.ShapeableImageView
        android:id="@+id/imageView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@android:drawable/ic_media_play"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Android API version:**
28

**Material Library version:** 
1.4.0-alpha02

**Device:**
Huawei P20Pro

**Comment by drchen** [comment]
Badges won't automatically expand the layout of the anchor view but will just set its clipChildren and clipToPadding to false. 

Therefore, please ensure your upper level layout has enough margins to include the badge.  For example, in your case, setting layout_margin to your ShapeableImageView should work.
