### ISSUE TITLE
Spinner : A decent one

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2184]
**Is your feature request related to a problem? Please describe.**
Will there be any Material Spinner that provides best and neat practices to follow?

**Describe the solution you'd like**
The current bloody Spinner has been around since the dawn of Android OS, yet until now it is not being updated even its name. As I recall before during introduction of AndroidX they says that they will rename some of ambiguous widget name like Spinner
https://www.xda-developers.com/android-engineering-team-reddit-ama-recap/  yet nothing change until this day.

**Describe alternatives you've considered**
A MaterialSpinner that is very friendly to work with without relying too much on custom or programmatic approach, just a simple set of styling or theming should be enough.

**Additional context**
Styling spinner item list and its dialog pop up also rely on custom too much.

**Comment by Zoro38** [comment]
Is this what you are looking for?

https://github.com/material-components/material-components-android/blob/master/docs/components/ProgressIndicator.md#circular-progress-indicators

**Comment by matpag** [comment]
This is a legit request IMO.

Currently your only option is to use a `TextInputLayout` with the `ExposedDropDownMenu` style, check the [catalog](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/textfield/res/layout/cat_textfield_exposed_dropdown_menu_content.xml#L26-L41) for an example.

**Comment by ymarian** [comment]
Yes `ExposedDropDownMenu` is an alternative to the native spinner
