### ISSUE TITLE
Material Components is missing a "colorOnPrimaryVariant"

### ISSUE THREAD

**Issue by Digipom** [material-components/material-components-android#2187]
On the dark theme, Material Design uses a different color for drawing over colorPrimaryVariant than it does for drawing on colorPrimary, but there is no colorOnPrimaryVariant exposed in the code.

Please see this screenshot:

![image](https://user-images.githubusercontent.com/2005192/115603927-c18a2f00-a2ae-11eb-8ef5-53bfd90532ad.png)
(source: https://material.io/design/color/dark-theme.html#ui-application)

Please add a theme attribute for colorOnPrimaryVariant (and related) to better support this.

Also see this screenshot for a theme that has a primary, primary variant, and secondary color, and where the colorOnPrimary doesn't match up with the text color actually used against the primary / primary variant (it's specified as #000000, but #FFFFFF is used against the primary variant):

![image](https://user-images.githubusercontent.com/2005192/115609124-234d9780-a2b5-11eb-82c5-f40e4d898566.png)

**Comment by paulkugaev** [comment]
@Digipom I suppose there is also `colorOnSecondaryVariant` missing

**Comment by drchen** [comment]
Hi, thanks for reporting the issue. 

We have a plan to deprecate colorPrimaryVariant/colorSecondaryVariant in the upcoming Material version at the end of 2021. 
Close the bug as obsolete.

**Comment by ArcherEmiya05** [comment]
> Hi, thanks for reporting the issue.
> 
> We have a plan to deprecate colorPrimaryVariant/colorSecondaryVariant in the upcoming Material version at the end of 2021. Close the bug as obsolete.

is there a replacement?

**Comment by benedictcontawe** [comment]
> is there a replacement?

Follow up please

**Comment by pekingme** [comment]
Please refer to the new [color system](https://m3.material.io/styles/color/overview) in Material 3 and this [page](https://material.io/blog/migrating-material-3) for migrating from M2 to M3. My best guess is the new colorPrimaryContainer and colorOnPrimaryContainer is corresponding to the usage of those variant colors.
