### ISSUE TITLE
[AppBarLayout] Dimension not updated after setting MaterialToolbar's visibility to GONE

### ISSUE THREAD

**Issue by chanteckwei** [material-components/material-components-android#2192]
**Description:**
`AppBarLayout` does not change its dimension automatically after setting `MaterialToolbar`'s visibility to `GONE`. Currently, the workaround is to call `AppBarLayout.requestLayout()` right after setting `MaterialToolbar`'s visibility.

```kotlin
binding.toolbar.isVisible = false
binding.appbarLayout.requestLayout()
```

![1](https://user-images.githubusercontent.com/34728894/116499821-a8513600-a8df-11eb-93ea-940ecc86af11.png)

**Expected behavior:**

![2](https://user-images.githubusercontent.com/34728894/116499879-d171c680-a8df-11eb-9011-3c4c5359fb74.png)

**Source code:**
```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar_layout"
        style="@style/Widget.MaterialComponents.AppBarLayout.PrimarySurface"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:liftOnScroll="true">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </com.google.android.material.appbar.AppBarLayout>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Android API:** 30
**Material Library:** 1.4.0-alpha02
**Device:** Any devices, built-in emulators, Oppo Reno5 5G

**Comment by drchen** [comment]
Hi I cannot really reproduce the issue. Can you confirm if this is still reproducible with the latest library?

**Comment by chanteckwei** [comment]
Unfortunately, no. And kinda have forgotten about this issue since then. I have since migrated to using Jetpack Compose for the past few months now.
