### ISSUE TITLE
[Shape] Bug when referencing a color file with alpha in a gradient shape.

### ISSUE THREAD

**Issue by Airomeo** [material-components/material-components-android#2193]
**Description:** 

Create a new project, only change the background of the main activity to shape gradient xml file, where the gradient `android:centerColor` refers to the `?attr/colorAccent` with alpha value. The problem appears. No matter what color you set, it will become pink

But if the `android:centerColor` value in the gradient is hard code, the problem will not occur.

The color in the middle turns to pink when running on the device or AVD.
![problem](https://i.stack.imgur.com/I31RA.png)

**Expected behavior:** 

The editor interface of mask.xml can be displayed correctly.
![problem](https://i.stack.imgur.com/YTG6v.png)

**Source code:** 

activity_main.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:background="@drawable/mask"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

@drawable/mask.xml

```xml
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:angle="90"
        android:centerColor="@color/alpha_95"
        android:endColor="?attr/colorOnPrimary"
        android:startColor="?attr/colorOnPrimary"
        android:type="linear" />
</shape>
```

@color/alpha_95.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:alpha="0.95" android:color="?attr/colorAccent" />
</selector>
```

**Android API version:** 

Known in 30. Not test other version.

**Material Library version:** 

v1.3.0

**Device:** 

I think it should be all devices. It's on my OnePlus 6 and on the Moto Z2F and AVD.

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ymarian** [comment]
Hi GradientDrawable is not part of the material library. 

https://source.android.com/setup/contribute/report-bugs
