### ISSUE TITLE
Feature Request - Bottom Navigation View to provide api to set the shifting mode

### ISSUE THREAD

**Issue by akoufatzis** [material-components/material-components-android#22]
The mShiftingMode field controls the shifting behaviour of the Bottom Navigation View. The Design Support Library does not provide at this time an API to set this field as the behaviour is hard coded to be enabled when the count of menu items exceeds the number 3. I understand that this is according to the material design specs. Nevertheless I think the library should not force this on the developers. I found one possible solution to this but it feels more like a hack. http://stackoverflow.com/questions/40176244/how-to-disable-bottomnavigationview-shift-mode

**Comment by pranayairan** [comment]
@tec27 Do you know when your changes will make it to release ?

**Comment by JustinHoUMD** [comment]
@tec27 Are there plans of including this change in the design support library?

**Comment by andrerinaldi** [comment]
It's a pity there's no kind of interest in this request. It would make the BottomNavigationView widget more useful and appetible.

**Comment by AidanLaing** [comment]
You can now use app:labelVisibilityMode="[labeled, unlabeled, selected, auto]" in 28-alpha

**Comment by joaoluizn** [comment]
how!?!?! I'm using 28 stable and it keeps saying the same error :(
