### ISSUE TITLE
[Slider] Cannot set step size when valueTo is a Prime number ( valueFrom = 0 )

### ISSUE THREAD

**Issue by arjun1194** [material-components/material-components-android#2201]
**Description:** 
I am not able to set a stepSize other than 1 when valueTo = 0 and valueFrom = Prime Number  

**Expected behavior:** must be able to set Some steps regardless of valueTo and valueFrom, 
for e.g. when valueFrom  = 0 and valueTo = 17, i must be able to set a region where i can select values for e.g.,
step size should be able to be set to 5 and i should be able to scroll from 0 to 15 and beyond 17 i shouldn't be able to scroll
**Source code:** 
`binding.slider.apply {
            valueTo = 17f
            valueFrom = 0f
            stepSize = 10f
        }`
**Android API version:** Android API version here
 All Androd
**Material Library version:** 
material:1.3.0

**Device:** Pixel 3a , but is on all the devices
To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ymarian** [comment]
Hi this wasn't accounted for in the API. 

One possible solution is to 0 to 20f, step size 5f. Use the LabelFormatter to transform the range from 10f to 20f 10f to 17f. 

```kt
slider.setLabelFormatter { value: Float ->
    if (value <= 15f) return value
    
    return 17f;
}
```

Or use the onValueChange callback to coerce the value to 17 if it goes over.
