### ISSUE TITLE
[TextInputLayout] Letter spacing of child TextInputEditText is not respected when rendering expanded hint

### ISSUE THREAD

**Issue by OmGodse** [material-components/material-components-android#2202]
**Description** 

TextInputLayout doesn't respect the letter spacing of it's child TextInputEditText when rendering the hint in the expanded state.
However, other attributes such as `android:textSize` and `android:typeface` are respected.

**Current behavior** 

![Text size and no letter spacing](https://user-images.githubusercontent.com/64728411/116882148-ba193d00-ac41-11eb-8dc9-f046b83ca92e.png)

**Source code**

```XML
<?xml version="1.0" encoding="utf-8"?>
<com.google.android.material.textfield.TextInputLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:focusableInTouchMode="true"
    android:hint="Hint"
    android:padding="16dp"
    app:hintEnabled="true">

    <!-- letterSpacing has no effect -->

    <com.google.android.material.textfield.TextInputEditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:letterSpacing="2"
        android:textSize="20sp" />

</com.google.android.material.textfield.TextInputLayout>
```

**Android API version :** 25 (7.1.1 Nougat)

**Material Library version :** 1.3.0
**Device :** Motorola Moto G4 Play

**Comment by OmGodse** [comment]
Any updates?

**Comment by drchen** [comment]
Thanks for the reminder, it's on my task queue. : )
