### ISSUE TITLE
[MaterialTimePicker] Allow to hide the icon button to switch to time input

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#2203]
Please allow to hide the accessory to switch the time picker to time input. I don't want users to use the `time input`.

<details>
<summary>Screen</summary>

<img src="https://user-images.githubusercontent.com/1494577/116907013-de4f2c80-abf5-11eb-9ed7-bff33e359842.png" width="300"/>
</details>

**Describe the solution you'd like**
Either able to set the `app:keyboardIcon` to null or to hide/show or a xml attribute with setter/getter methods.

**Describe alternatives you've considered**
1. app:keyboardIcon="@null". This has no effect
2. Setting the `textColorSecondary` to transparent or null but other pieces of the UI get impacted by this.

**Android API version:** 
* defaultCompileSdkVersion = 29
* defaultBuildToolsVersion = '29.0.2'
* defaultMinSdkVersion = 26
* defaultTargetSdkVersion = 29

**Material Library version:** 
* material_version = '1.3.0'

**Device:** 
* Tablet Pixel C
* OS: 8.1

**Comment by ymarian** [comment]
Hi that time picker isn't the MaterialTimePicker. Please refer to the docs:

https://github.com/material-components/material-components-android/blob/master/docs/components/TimePicker.md
