### ISSUE TITLE
[MaterialTimePicker] Time input causes the dialog to expand full width

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#2204]
Switching from `time picker` to `time input` changes the width of the dialog fragment to full width. Switching back to `time picker` it resizes the dialog fragment back. 

**Expected behavior:**
The `time input` shouldn't resize the dialog fragment. 

<details>
<summary>Impl Video</summary>

<img src="https://user-images.githubusercontent.com/1494577/117173314-7e858c80-ad81-11eb-8cce-71f745d000c3.gif" width="400"/>
</details>

**Android API version:** 
* defaultCompileSdkVersion = 29
* defaultBuildToolsVersion = '29.0.2'
* defaultMinSdkVersion = 26
* defaultTargetSdkVersion = 29

**Material Library version:** 
* material_version = '1.3.0'

**Device:** 
* Tablet Pixel C
* OS: 8.1

**Comment by Example111** [comment]
Hi the framework timepicker is not part of this library. Please use MaterialTimePicker instead

**Comment by ymarian** [comment]
Hi that time picker isn't the MaterialTimePicker. Please refer to the docs:

https://github.com/material-components/material-components-android/blob/master/docs/components/TimePicker.md
