### ISSUE TITLE
[CoordinatorLayout] CoordinatorLayout leaves empty blank space at bottom of the screen. 

### ISSUE THREAD

**Issue by AnandSaran** [material-components/material-components-android#2205]
<androidx.coordinatorlayout.widget.CoordinatorLayout
        android:id="@+id/layoutCoordinator"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.appbar.AppBarLayout
            android:id="@+id/layoutAppBar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.google.android.material.appbar.CollapsingToolbarLayout
                android:id="@+id/layoutCollapseToolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_scrollFlags="scroll|exitUntilCollapsed">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">

                    <androidx.recyclerview.widget.RecyclerView
                        android:id="@+id/rvTopDisplay"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent" />

                    <include
                        android:id="@+id/layoutTitleList"
                        layout="@layout/item_title_list"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/rvTopDisplay" />
                </androidx.constraintlayout.widget.ConstraintLayout>
            </com.google.android.material.appbar.CollapsingToolbarLayout>
        </com.google.android.material.appbar.AppBarLayout>

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rvBottomDisplay"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="@dimen/activity_vertical_margin"
            android:layout_marginEnd="@dimen/activity_vertical_margin"
            android:clipToPadding="false"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
    
    
If Second RecyclerView (rvBottomDisplay) contain more item, then blank space is not showing.
If  RecyclerView contain 1 or 2 items then blank space is showing,
  
  Kindly advice me to fix this.
Thanks

**Comment by AnandSaran** [comment]
Is any one there to help ?

**Comment by drchen** [comment]
CoordinatorLayout is not part of Material library so we are not able to provide too much advice here.

But isn't space left at the bottom an expected behavior if you don't have enough content to show?
