### ISSUE TITLE
[TabLayout] Tab Text colors don't change when using Custom Tabs in Tablayout

### ISSUE THREAD

**Issue by nikhil-seth** [material-components/material-components-android#2206]
**Description:** When using custom layout in tabs. If we set color, it does not change color of custom tab text.
```
        tabLayout.setTabTextColors(Color.parseColor("#FF0000"), Color.parseColor("#00FF00"))
```

**Expected behavior:** Color should change when tab gets switched.

**Source code:** 
* TabLayout initialization
``` 
        TabLayoutMediator(tabLayout, vp) { tab: TabLayout.Tab, i: Int ->
            tab.customView =
                this.layoutInflater.inflate(R.layout.tab_custom, null, false)
            tab.text = "Tab$i"
        }.attach()
        tabLayout.setTabTextColors(Color.parseColor("#FF0000"), Color.parseColor("#00FF00"))
```
* Tab Custom View layout
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@android:id/text1"
        />

</FrameLayout>
```

**Current Behaviour:** 
<img src=https://user-images.githubusercontent.com/32011091/126896588-aedd1d91-02f1-4b14-9016-4c825d4539ed.gif width=200 />
**Expected Behaviour:** 
<img src=https://user-images.githubusercontent.com/32011091/126896594-341c4c09-a085-4e7c-988c-1bb95d4106c3.gif
width=200 />

**Android API version:** 30

**Material Library version:** 1.3.0, on latest library also.

**Device:** All Devices.

**Comment by drchen** [comment]
Can you provide info we request in the template? So we can help identify the issue. Thanks!

**Comment by alishari** [comment]
Make sure you used android.R.id.text1 for your custom view TextView.

**Comment by drchen** [comment]
Hi, can you provide your code snippet and screenshot? We cannot assist without useful info available.

**Comment by nikhil-seth** [comment]
@drchen I have updated the description.
Also, idk why, but the gif have some flickering issue while showing here. but you can still get reference.

**Comment by nikhil-seth** [comment]
@alishari I have used custom text View with R.id.text1, still it persists.
Ideally, we can handle this case when we are having custom text views with R.id.text1

**Comment by drchen** [comment]
Cool. Will take a look. Thanks for providing the info!
