### ISSUE TITLE
[material.button.MaterialButton] Broken german letter 'ß'

### ISSUE THREAD

**Issue by Pansebert** [material-components/material-components-android#2208]
**Description:** When using the standard Theme button text gets capitalized. When setting following text via android:text="Schließen" it displays:
![image](https://user-images.githubusercontent.com/69163449/118152639-387d9800-b415-11eb-84d0-66bcc6ffdbd4.png)

**Expected behavior:** display "SCHLIEßEN" or maybe even the correct capital form "SCHLIEẞEN"

**Source code:** 
```xml
<com.google.android.material.button.MaterialButton
        android:id="@+id/detail_close"
        style="@style/Widget.MaterialComponents.Button.TextButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="12dp"
        android:layout_marginBottom="@dimen/button_margin_bottom"
        android:text="Schließen"
        android:textSize="12sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toStartOf="@+id/detail_contextButton" />
```

**Android API version:** 29

**Material Library version:** material:1.3.0

**Device:** Pixel 5

**Comment by ymarian** [comment]
I don't think you can use those characters in xml. You'll have to use the unicode representation 

&#0023;

Schlie&#0023;en

This has nothing to do with MaterialButton
