### ISSUE TITLE
setOnNavigationItemSelectedListener is deprecated?

### ISSUE THREAD

**Issue by Robotxm** [material-components/material-components-android#2211]
After upgrade to 1.4.0-beta01, the `setOnNavigationItemSelectedListener` method is marked as deprecated. So what is the alternate?

**Comment by msasikanth** [comment]
Based on the documentation, it seems like you can call the listener interface directly and it will set the listeners internally since it's supported by both bottom navigation and navigation rail now.

https://github.com/material-components/material-components-android/blob/95a769c373792d2fce70d7ee21f3857f65e9d74e/docs/components/NavigationRail.md

```kt
NavigationBarView.OnItemSelectedListener { item ->
    when(item.itemId) {
        R.id.item1 -> {
            // Respond to navigation item 1 click
            true
        }
        R.id.item2 -> {
            // Respond to navigation item 2 click
            true
        }
        else -> false
    }
}
```

**Comment by icarapovic** [comment]
Is it just me or is the official documentation still showing the deprecated methods as the one to use? In the library itself its just marked as deprecated without any info why or what is the alternative. Can someone update the documentation?

**Comment by felipeajc** [comment]
it's a big shit!!! Official documentation explain the BottomNavigationView with a deprecated methods. WTF!!!

**Comment by myaasiinh** [comment]
create SelectedItemListener utils function

**Comment by seharbat00l** [comment]
> Based on the documentation, it seems like you can call the listener interface directly and it will set the listeners internally since it's supported by both bottom navigation and navigation rail now.
> 
> https://github.com/material-components/material-components-android/blob/95a769c373792d2fce70d7ee21f3857f65e9d74e/docs/components/NavigationRail.md
> 
> ```kotlin
> NavigationBarView.OnItemSelectedListener { item ->
>     when(item.itemId) {
>         R.id.item1 -> {
>             // Respond to navigation item 1 click
>             true
>         }
>         R.id.item2 -> {
>             // Respond to navigation item 2 click
>             true
>         }
>         else -> false
>     }
> }
> ```

I'm using the same method but it's not implementing the conditions, not changing the fragments.

**Comment by seharbat00l** [comment]
> Based on the documentation, it seems like you can call the listener interface directly and it will set the listeners internally since it's supported by both bottom navigation and navigation rail now.
> 
> https://github.com/material-components/material-components-android/blob/95a769c373792d2fce70d7ee21f3857f65e9d74e/docs/components/NavigationRail.md
> 
> ```kotlin
> NavigationBarView.OnItemSelectedListener { item ->
>     when(item.itemId) {
>         R.id.item1 -> {
>             // Respond to navigation item 1 click
>             true
>         }
>         R.id.item2 -> {
>             // Respond to navigation item 2 click
>             true
>         }
>         else -> false
>     }
> }
> ```

`override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        replaceFragment(homeFragment)
        
//oldMethodDeprecated->nav.setOnNavigationItemSelectedListener
        NavigationBarView.OnItemSelectedListener{
            when (it.itemId){
                R.id.add -> replaceFragment(addFragment)
                R.id.home -> replaceFragment(homeFragment)
                R.id.chats -> replaceFragment(chatFragment)
                R.id.profile -> replaceFragment(profileFragment)
                R.id.search -> replaceFragment(searchFragment)
            }
            true

        }
    }
    private fun replaceFragment(fragment: Fragment){
        if (fragment!=null){
            val transaction = supportFragmentManager.beginTransaction()
            transaction.replace(R.id.fragmentContainer, fragment)
            transaction.commit()
        }
    }`
