### ISSUE TITLE
TextInputEditTextLayout have no shadow options. 

### ISSUE THREAD

**Issue by Attique033** [material-components/material-components-android#2213]
How to add shadow to the outlinedTextInputLayout? I've rounded the corners by using custom style but not able to add drop shadow to it. Any help?

    <style name="OutlinedRoundedBox" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.MyApp.TextInputLayout.Rounded</item>
    </style>

    <style name="ShapeAppearanceOverlay.MyApp.TextInputLayout.Rounded" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">10dp</item>
    </style>
Above is how style is customised to change radius of ourlinedTextInputLayout.

**Comment by drchen** [comment]
Outline borders are not actually the view border of the whole text input layout so adding shadows may result in weird visual experience. If you really want it, will set edit text's elevation work?
