### ISSUE TITLE
[TextInputLayout] End icon not centered and error icon changes height

### ISSUE THREAD

**Issue by krobert** [material-components/material-components-android#2214]
**Description:**
i have an Input field using FilledBox style and a custom shapeAppearanceOverlay, which is just rounded corners.
I removed the hint with the following attributes in styles:

The edittext layouts height is much bigger then it should be, when it has an end icon enabled.
Normal state is 57 dp and with end icon its 60 dp and as you can see the end icon is not centered in the layout
![textinput_1](https://user-images.githubusercontent.com/6197932/119117855-f44c5200-ba29-11eb-840d-56b8dfbf5078.png)

When i set an error this becomes much more bigger.
![textinput_2](https://user-images.githubusercontent.com/6197932/119117734-d41c9300-ba29-11eb-9e3f-3276e8faa186.png)

**Expected behavior:** 
The end icon should be centered.
Size of the edit text should not change

```
<com.google.android.material.textfield.TextInputLayout
        android:id="@+id/layoutUserName"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        style="@style/Authentication.TextInput">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/editTextUserName"
            style="@style/Authentication.EditText"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:contentDescription="@string/signup_value_email"
            android:inputType="textEmailAddress">
            
            <requestFocus />
            
        </com.google.android.material.textfield.TextInputEditText>
    </com.google.android.material.textfield.TextInputLayout>
```

Styles:

```
<style name="Authentication.EditText" parent="Base.Widget.MaterialComponents.TextInputEditText"/>
 
<style name="Authentication.TextInput" parent="Widget.MaterialComponents.TextInputLayout.FilledBox">
   <item name="boxStrokeWidth">0dp</item>
   <item name="boxStrokeWidthFocused">0dp</item>
   <item name="hintAnimationEnabled">false</item>
   <item name="hintEnabled">false</item>
   <item name="android:hint">@null</item>
   <item name="materialThemeOverlay">@style/ThemeOverlay.TextInputLayout</item><!-- just overriding color and text appereance  -->
   <item name="shapeAppearance">@style/ShapeAppearance</item>
   <item name="shapeAppearanceOverlay">@style/ShapeAppearance</item> 
</style>

<style name="ShapeAppearance" parent="ShapeAppearance.MaterialComponents.SmallComponent">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSizeBottomLeft">@dimen/radius_shape_corner</item>
        <item name="cornerSizeBottomRight">@dimen/radius_shape_corner</item>
        <item name="cornerSizeTopLeft">@dimen/radius_shape_corner</item>
        <item name="cornerSizeTopRight">@dimen/radius_shape_corner</item>
 </style>
```

**Android API version:** 
Its affecting all android versions, the screenshot is from the layout inspector from an api 29 android one device.

**Material Library version:** 
1.3.0

**Device:** Device on which the bug was encountered here
Nokia 7.1

**Comment by drchen** [comment]
The frame layout wrapping the TextInputEditText you add will inherit the layout params you set on TextInputEditText, which, in your case, has its android:layout_height set to wrap_content, therefore the layout height changes according to icon's height.
