### ISSUE TITLE
[MaterialTimePicker] Allow using the time picker for selecting a duration

### ISSUE THREAD

**Issue by Digipom** [material-components/material-components-android#2218]
Material Time Picker can currently be used for picking a time of day. It can't be used for selecting an elapsed time or duration, but it would be nice to be able to use it that way as well.

Here's what would enable this:
- Allow selecting hours beyond 24; i.e. a range of 0-50 hours.
- Allow optionally specifying seconds.
- Allow specifying a max value (i.e. specify that values can't be set to greater than 2h and 30m).

**Comment by drchen** [comment]
Wouldn't it be better to just show the time-picker twice, considering that there's actually no good UX to show a time span on the current visual design?

I think there's a low chance for us to implement this. Will close the issue for now.

**Comment by Gustl22** [comment]
@drchen can we reconsider adding such a picker for material. I provided an implementation for flutter (https://github.com/flutter/flutter/pull/145698, https://github.com/flutter/flutter/issues/144536) but it's dependent on what the Material team is proposing.

> there's actually no good UX to show a time span on the current visual design

I think this should do it:
![Duration Picker](https://github.com/material-components/material-components-android/assets/18537755/deb52ee4-4a4a-4223-bb8c-6cb37fd01bfd)

**Comment by Gustl22** [comment]
FYI: I published the package for Flutter here: https://pub.dev/packages/material_duration_picker, if the material team might want to pick that up in the future.

**Comment by michael-winkler** [comment]
Would be really cool to have that feature.
