### ISSUE TITLE
MaterialTimePicker. attr/colorSurface attribute to be set in your app theme

### ISSUE THREAD

**Issue by geraa1985** [material-components/material-components-android#2220]
java.lang.IllegalArgumentException: com.google.android.material.timepicker.MaterialTimePicker requires a value for the xxx:attr/colorSurface attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).

implementation 'com.google.android.material:material:1.3.0'

This error always occurs, no matter what style is selected... and even if you write this attribute with your hands everywhere, this error still occurs.

**Comment by drchen** [comment]
What's your app theme settings?

**Comment by drchen** [comment]
You will need to declare colorSurface in your app theme. Close this for now.
