### ISSUE TITLE
[MaterialTextView] Text appearance doesn't seem to work as expected, but Style does

### ISSUE THREAD

**Issue by pedronveloso** [material-components/material-components-android#2225]
**Description:**

So I've defined this style 

```
<style name="TextAppearance.Studio.Header4" parent="TextAppearance.MaterialComponents.Headline4">
        <item name="android:textSize">16sp</item>
        <item name="android:fontFamily">sans-serif-medium</item>
        <item name="fontFamily">sans-serif-medium</item>
    </style>
```

And then on my main theme defined this:

```
<style name="BaseTheme" parent="@style/Theme.MaterialComponents.Light.NoActionBar.Bridge">
...
<item name="TextAppearanceHeader4">@style/TextAppearance.Studio.Header4</item>
....
</style>
```

When I use my style on a TextView as a `textAppearance` property, the fontFamily doesn't get selected accordingly.

```
<com.google.android.material.textview.MaterialTextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="@string/typography_text"
                android:textAppearance="?attr/TextAppearanceHeader4" />
```

![image](https://user-images.githubusercontent.com/416941/120033187-1dcc2700-bfb0-11eb-9e40-d503500137b1.png)

But if I change it to `style`, it does:

```
<com.google.android.material.textview.MaterialTextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="@string/typography_text"
                style="@style/StudioTypography.Header4" />
```

![image](https://user-images.githubusercontent.com/416941/120033032-e8273e00-bfaf-11eb-8943-e1bbcf41cc5c.png)

**Expected behavior:**

It seems from the documentation that `textAppearance` is a recommended approach for TextViews, so would like to know if that's the case, and if so why does it render differently than expected.

**Source code:** 

**Android API version:** 
Tested on Android 11.

**Material Library version:** 
Latest Material Android Library: 1.3.0

**Device:**
Able to repro on Samsung S20 and Pixel 3 .

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Hi,

Can you double check if ?attr/TextAppearanceHeader4 is correctly pointing to TextAppearance.Studio.Header4 when you inflating the view?

Or just try to replace ?attr/TextAppearanceHeader4 with TextAppearance.Studio.Header4 in the XML file and see if it works?

**Comment by drchen** [comment]
I'll close the bug for now due to no further info. Please feel free to reopen it if you still have the issue.
