### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/widget/AppCompatEditText;

### ISSUE THREAD

**Issue by songtao542** [material-components/material-components-android#2227]
05-31 11:36:35.770 11975 11975 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/widget/AppCompatEditText;
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper.supportsAutoSizeText(AppCompatTextViewAutoSizeHelper.java:932)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper.loadFromAttributes(AppCompatTextViewAutoSizeHelper.java:205)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:247)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:110)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:93)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:88)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:83)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.theme.MaterialComponentsViewInflater.createTextView(MaterialComponentsViewInflater.java:61)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1563)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1614)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarItemView.<init>(NavigationBarItemView.java:95)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:34)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.bottomnavigation.BottomNavigationMenuView.createNavigationBarItemView(BottomNavigationMenuView.java:197)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarMenuView.getNewItem(NavigationBarMenuView.java:492)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarMenuView.buildMenuView(NavigationBarMenuView.java:421)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarPresenter.updateMenuView(NavigationBarPresenter.java:72)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarView.inflateMenu(NavigationBarView.java:358)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.navigation.NavigationBarView.<init>(NavigationBarView.java:226)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:103)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:98)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:93)
05-31 11:36:35.771 11975 11975 E AndroidRuntime: 	... 28 more

appcompat version:
androidx.appcompat:appcompat:1.3.0-rc01

**Comment by drchen** [comment]
Can you check the generated jars in your intermediate jar folder to see if the class is correctly included?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
