### ISSUE TITLE
TextInputLayout password toggle can be used when View in disabled state

### ISSUE THREAD

**Issue by ImKoRn** [material-components/material-components-android#223]
When TextInputLayout in disabled state no restriction for password toggle clicks. 
It's lead to security problem when disabling view used in some app progress with user password also it not common for using View or nested Views in disabled state.

I suggest disable this feature when View is disabled and hide password (for security reason)

**Comment by gsajith** [comment]
Filed https://issuetracker.google.com/issues/118838415 to track this issue, and for future communications.
