### ISSUE TITLE
[TextInputLabel] Bug with centered text in EditText

### ISSUE THREAD

**Issue by ptrNine** [material-components/material-components-android#224]
Hint looks like that when gravity attribute of EditText is 'center' or 'end':
![screenshot_2018-10-31-20-33-54-969_io material catalog](https://user-images.githubusercontent.com/43387405/47807400-028fd100-dd4d-11e8-844d-2f6890712c29.png)

**Comment by dsn5ft** [comment]
Center gravity isn't supported for text fields - https://material.io/design/components/text-fields.html.
