### ISSUE TITLE
[BadgeDrawable] BadgeDrawable appears clipped when used with a Toolbar

### ISSUE THREAD

**Issue by karllindmark** [material-components/material-components-android#2246]
**Description:** 
I've been trying to use a `BadgeDrawable` on a `MenuItem` in our `Toolbar`, but it can't really get it to work as expected. It appears as if the value gets visually clipped due to exceeding the menu item view bounds, and I think it's due to the positioning of the badge being too far right.

number = 99, too far to the right:
![image](https://user-images.githubusercontent.com/979152/121743290-6da70400-cb01-11eb-90ca-de3fb8dbf2a5.png)

number = 300, actual visible clipping going on here:
![image](https://user-images.githubusercontent.com/979152/121743189-418b8300-cb01-11eb-819c-a0548cb5839c.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/979152/121743366-89aaa580-cb01-11eb-8cd5-808d127bd5a7.png)

**Source code:** 
https://github.com/karllindmark/MaterialBadgeDrawableInToolbar (more precisely [in MainActivity.kt](https://github.com/karllindmark/MaterialBadgeDrawableInToolbar/blob/main/app/src/main/java/re/ntz/materialbadgedrawableintoolbar/MainActivity.kt))

**Android API version:**
Tested on 23, 29 and 30 - all of them display the badge incorrectly

**Material Library version:**
1.4.0-rc01

**Device:**
Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by karllindmark** [comment]
The problem is visible in the `catalog` app if you hide the following two menu items in `cat_topappbar_menu.xml`:

![image](https://user-images.githubusercontent.com/979152/121752411-5ae7fb80-cb10-11eb-81f0-746a78f3e3d5.png)

That renders the menu item as follows (after 100 taps):

![image](https://user-images.githubusercontent.com/979152/121752439-6804ea80-cb10-11eb-9275-8b0f1710e52d.png)

**Comment by nienienienie** [comment]
what's new about this?

**Comment by hunterstich** [comment]
Definitely a good design issue to consider. In the meantime, you could set [BadgeDrawable.setBadgeGravity](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/badge/BadgeDrawable.java#L546) to a different location if you need a workaround.

**Comment by Tgo1014** [comment]
Was this forgotten? Unfortunately still happens for me.

**Comment by drchen** [comment]
Hi, it's not forgotten.

We have the new design and plan to work on this in the next Material version (1.9).

**Comment by imhappi** [comment]
Unfortunately the new design will still have this issue; there's no way around this issue without increasing padding on the menu items or moving the badge gravity to not be at 'END'. As Hunter mentioned, a workaround would be moving the badge to a different location using the gravity, or simply using a small badge.

The guidelines do say "Use a small badge when spaces are tightly constrained, such as top app bars."
https://m3.material.io/components/badges/guidelines#92c9d4f0-e787-48ad-a9ad-d1830d4bffc1
