### ISSUE TITLE
Publish release notes

### ISSUE THREAD

**Issue by technoir42** [material-components/material-components-android#225]
I saw that version 1.1.0-alpha01 came out but I couldn't find release notes for it and even for older non-support versions anywhere.
Please publish the release notes and make them easily accessible from [developer.android.com](developer.android.com) and/or [https://www.material.io/develop/android/](https://www.material.io/develop/android/).

**Comment by dsn5ft** [comment]
Updated https://github.com/material-components/material-components-android/releases, we are also considering cross posting to the other sites you mentioned.
