### ISSUE TITLE
[NavigationRailView] Navigation Rail uses BottomNavigationView specific insets

### ISSUE THREAD

**Issue by ianhanniballake** [material-components/material-components-android#2252]
**Description:** When `NavigationBarView` was made the base class for both `NavigationRailView` and `BottomNavigationView`, the inset handling from `BottomNavigationView` in its [`applyWindowInsets()`](https://github.com/material-components/material-components-android/blob/48a58262a55a16934ef0a7a49541a15f27dbf69d/lib/java/com/google/android/material/navigation/NavigationBarView.java#L307) was moved to `NavigationBarView`. However, this meant that `NavigationRailView`, which is a vertically oriented layout, now only applies the **bottom** inset padding (and never the top) and symmetrically applies the left and right padding (rather than only the left/start padding).

**Expected behavior:** `NavigationRailView` should have vertical orientation specific inset handling and `NavigationBarView`'s copy of `applyWindowInsets()` should be moved back to `BottomNavigationView`.

**Source code:**

```
<!-- Note that app:menuGravity="center" won't actually center the NavigationRailView
     on a tablet due to bottom insets -->
<com.google.android.material.navigationrail.NavigationRailView
        android:id="@+id/nav_bar"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:background="@color/nav_bar_background"
        android:fitsSystemWindows="true"
        app:menuGravity="center"
        app:menu="@menu/main"/>
```

**Android API version:** All API 21+ devices

**Material Library version:** 1.4.0-beta01 and higher

**Device:** all

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by dsn5ft** [comment]
Closed by https://github.com/material-components/material-components-android/commit/501ef8ea2a742739e3fcf4eb2dfc030509316da6.

Released in [1.5.0-alpha01](https://github.com/material-components/material-components-android/releases/tag/1.5.0-alpha01).
