### ISSUE TITLE
[MaterialDatePicker] days of week not appear correctely in arabic 

### ISSUE THREAD

**Issue by tarek13** [material-components/material-components-android#2254]
**Description:** 
days of week not appear correctely in arabic the name of  day of week is written in two line 
if the version of android less than Android Oreo

![Capture](https://user-images.githubusercontent.com/7283032/122215471-8cafe800-ceab-11eb-931e-0926b105790a.PNG)

**Android API version:** API 25

**Material Library version:** 
com.google.android.material:material:1.4.0-rc01

**Device:** PIXEL 2 EMULATOR

**Comment by paulfthomas** [comment]
`MaterialDatePicker` relies on [Calendar.NARROW_FORMAT](https://developer.android.com/reference/java/util/Calendar#NARROW_FORMAT) for getting the display name for the days of the week on Android >= Oreo. Unfortunately, it is not available on earlier versions for which it uses [Calendar.SHORT](https://developer.android.com/reference/java/util/Calendar#SHORT) which is not as compact.
