### ISSUE TITLE
[MaterialTextView] Extensive icon support like MaterialButton

### ISSUE THREAD

**Issue by hbb20** [material-components/material-components-android#2255]
**Is your feature request related to a problem? Please describe.**
Material Button provides a great and clean support for icons like iconPadding, iconGravity, iconSize. With current implementation of `MaterialTextView` some work can be doing using drawableStart/EndCompat. This works well except for the icon size.

**Describe the solution you'd like**
Similar icon options as `MaterialButton`. At least for icon size.

**Describe alternatives you've considered**
Use traditional drawableStart/End option but can not control size of icon from xml.

**Comment by drchen** [comment]
MaterialTextView is just a simple wrapper of AppCompatTextView, in both of which we can only follow Android TextView's restrictions...  

Please consider other alternative options if you really need this.

**Comment by mtrakal** [comment]
@drchen why it's closed, if it's a valid feature request?

Why don't add it the same way as it's on button - it's too just (not so simple/dummy) wrapper around Button... 
Add app:iconSize app:iconGravity etc?

Next really wanted is position of icon (top|start or center|start gravity). It's two most cases when it's not possible to use standard TextView and you must add ImageView for it.
