### ISSUE TITLE
[NavigationBarView] Badge just support Number , not support String , such as display 99+

### ISSUE THREAD

**Issue by 309152665** [material-components/material-components-android#2259]
such as : 
NavigationBarView.getOrCreateBadge(R.id.*).number = "99+"
but now , only support NavigationBarView.getOrCreateBadge(R.id.*).number = 99

**Comment by drchen** [comment]
Hi, thanks for the suggestion. This has been under discussion with our designers for a long while but there are several design challenges we don't know the best answer yet. For example, the badge offset relative to the anchorView (and its adjacent view can be very tricky.)

I'll close this for now given that we are already tracking this internally and we are not sure if we will do it yet.

**Comment by 309152665** [comment]
> Hi, thanks for the suggestion. This has been under discussion with our designers for a long while but there are several design challenges we don't know the best answer yet. For example, the badge offset relative to the anchorView (and its adjacent view) can be very tricky.
> 
> I'll close this for now given that we are already tracking this internally and we are not sure if we will do it yet.

ok , thanks , i think the library will be bester.
