### ISSUE TITLE
[MaterialButtonToggleGroup] Incorrect check state when combining XML / programmatically

### ISSUE THREAD

**Issue by rbenza** [material-components/material-components-android#2263]
When a MaterialButtonToggleGroup has set `app:selectionRequired="true"` and `app:singleSelection="true"` in XML, and you also change the checked button in code at run time with `.check(R.id.newCheckedButton)` on the group, multiple button become selected incorrectly.

Seems like this fix is not fully working: https://github.com/material-components/material-components-android/commit/ffb2ad14ffaeb82901ff31ec79051f3c1ac068a3

This issue does only appear in 1.4.0-rc01. In 1.3.0 behavior is normal.

**Comment by somesh-basicx** [comment]
This bug is present in stable version 1.4.0 of the library. We can't ship our app with this version because of this issue. Please look into it as setting `app:selectionRequired="true"`, `app:singleSelection="true"` and checking the button programmatically is very common practice.

**Comment by gabrielemariotti** [comment]
It seems fixed with 1.5.0-alpha01

**Comment by drchen** [comment]
I actually have a pending fix under review for a while. Hope it can be merged soon.
