### ISSUE TITLE
[TabLayout] TabLayout cannot be made shorter that it's default height

### ISSUE THREAD

**Issue by mohand1993** [material-components/material-components-android#2268]
**Description:** When trying to decrease the textSize in TabLayout's tabs, their height is not getting any smaller even though it's height has been set to `WRAP_CONTENT`

**Expected behavior:** The TabLayout to get smaller and match the size of its content
![image](https://user-images.githubusercontent.com/5392493/123082969-e2dad900-d41f-11eb-903e-822a21ecca67.png)

**Source code:** The issue can be observed in the viewpager2 sample app, when the text size is set to be smaller (see [diff](https://github.com/mohand1993/material-components-android/commit/1fdc3f107dc63f5c63d41264d5bce67394f689e8)) or checkout this branch https://github.com/mohand1993/material-components-android/tree/wrap-content-height-bug

**Android API version:** 30

**Material Library version:** 1.4.0-rc01 also reproducible with 1.2.1

**Device:** Pixel3

**Comment by hunterstich** [comment]
Hi @mohand1993,

Using `wrap_content` will use either [DEFAULT_HEIGHT](https://github.com/material-components/material-components-android/blob/b0558dc006ac60f1c33cff4706bef109a6f77e07/lib/java/com/google/android/material/tabs/TabLayout.java#L188)  (48dp) if all labels and icons are inline and [DEFAULT_HEIGHT_WITH_TEXT_ICON](https://github.com/material-components/material-components-android/blob/b0558dc006ac60f1c33cff4706bef109a6f77e07/lib/java/com/google/android/material/tabs/TabLayout.java#L182) (72dp) if there are stacked icons.

If you want to decrease the `TabLayout` height, using an explicit dp value should work. For example:

```
<com.google.android.material.tabs.TabLayout
          android:layout_height="32dp"
          android:layout_width="match_parent">
 ```

**Comment by mohand1993** [comment]
@hunterstich 
Thanks for your feedback.
Is it a limitation by definition? what if the text is being set to be scaled up/Down by the user? you will always end up having more/less padding than intended.
Having a fixed height is in my opinion not the proper solution

**Comment by MuntashirAkon** [comment]
Here's a utility function to achieve this since they refuses to do it for some unknown reason:

```
    public static void setEndIconSize(@NonNull TextInputLayout layout, @Px int size) {
        int width = layout.getContext().getResources().getDimensionPixelOffset(R.dimen.mtrl_min_touch_target_size);
        int maxWidth = Math.max(width, size);
        // AppCompatImageButton errorIconView = layout.findViewById(R.id.text_input_error_icon);
        AppCompatImageButton endIconView = layout.findViewById(R.id.text_input_end_icon);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(maxWidth, size);
        layoutParams.gravity = Gravity.CENTER_VERTICAL | Gravity.END;
        endIconView.setLayoutParams(layoutParams);
        endIconView.setScaleType(ImageView.ScaleType.CENTER_INSIDE);
    }
```

This only covers the default end icon and not the error icon because I didn't need it, but you can manipulate it by uncommenting 4th line. If you need to set it using XML, you might want to consider extending `TextInputLayout` and adding `endIconSize` as a new property.
