### ISSUE TITLE
[TextInputLayout] Allow to place label above the outline box

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#2270]
**Is your feature request related to a problem? 
Yes. Field aliases in a database table can has a long text. This long name get ellipsized but there is no option to specify if you want the `label` for outline TextInputLayout` to be above the box.

**Describe the solution you'd like**
Provide style for `floating` labels: XML attribute(s) and setter/getter (s). 
* floatingLabel: true/false
* floatingLabelPaddingBottom
* floatingLabelPaddingStart
* floatingLabelPaddingEnd
It will be nice to separate the `hintText` from the `floatingLabel`.

**Describe alternatives you've considered**
Adding a textView above the `TextInputLayout` but we don't want to deviate from what it is provided by the Android API. It is an overkill and it should be supported.

**Additional context**
This is the design we are trying to achieve.

<details>
 <summary>Design Artboard</summary>

<img src="https://user-images.githubusercontent.com/1494577/123151192-131e7980-d418-11eb-86cd-96953f4a4cbe.png"/>
</details>

Screens below show the comparison between our iOS vs Android app:

<details>
 <summary>Implementation Screens</summary>

| iOS | Android |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1494577/123152589-99878b00-d419-11eb-86ec-1c3e78109dbd.png" width="300"/> | <img src="https://user-images.githubusercontent.com/1494577/123152985-0d299800-d41a-11eb-8fa4-fa160f962ac4.png" width="300"/> |
| Check marks show the UI piece for the field alias name | X show the UI piece for the field alias name that is ellipsized |
</details>

**Comment by drchen** [comment]
Can't it be easily done by wrapping TextInputLayout in another layout?

Can you provide more use cases so we can evaluate if this is a valuable feature to add?

**Comment by sabinebarrera** [comment]
@drchen yes, you could wrapped a `MaterialTextView` and `TextInputLayout` within `ConstraintLayout` but is this efficient? the `TextInputLayout` already has this label. As shown in the images I shared above, the use case is when you have a form fields (with many of those) that the user needs to fill when collecting data on the field.

**Comment by drchen** [comment]
It won't be less efficient than whatever approaches we may need to adopt on the library side. 

The existing label behavior is kind of complicated - it collapses and expands according to the focus state. I will be hard to support more flexible positioning of it, and, more importantly, it's not the design intention of it. 

Since clients can easily do this on their own, and it's not part of the Material design. I'll close the issue as won't go.
