### ISSUE TITLE
[TabLayout] first time , tab position in 0 ,next select position > 1 , create more than one fragment

### ISSUE THREAD

**Issue by 309152665** [material-components/material-components-android#2271]
the TabLayout after the init(OffscreenPageLimit = -1) , position in 0 , when select position 2 , will create  two new fragment , the true is create one fragment in position 2 , not create position in 1 and 2 fragment.

**Comment by drchen** [comment]
Can you provide more details? Like what fragments are being created?  Also I don't think we have an `init(OffscreenPageLimit)` method in `TabLayout`. 

Would you mind to provide your sample app so we can understand your issue better?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
