### ISSUE TITLE
[Feature Request] Change the 24h mode of TimePicker to use a double clock-face like Android TimePicker

### ISSUE THREAD

**Issue by fgubler** [material-components/material-components-android#2284]
The 24h mode of MaterialTimePicker puts all 24 hours into a single clock-face.

![_20210704_141511](https://user-images.githubusercontent.com/1478872/124385858-e1d76080-dcd7-11eb-83cf-4f546967325c.JPG)

Unfortunately, this is crazily counter-intuitive because no analog clock-face **ever** shows all 24 hours.
The standard Android TimePicker solved this issue very elegantly with a double clock-face:

![2021-07-04 14_13_32-Startpage Search results](https://user-images.githubusercontent.com/1478872/124385809-96bd4d80-dcd7-11eb-8aca-af10b244c826.png)

It would be very nice for everyone using the 24h format (i.e. pretty much all of Europe) to get this kind of double clock-face in MaterialTimePicker as well.

**Comment by josefigueroa168** [comment]
This issue is similar in nature to issue #1450.

**Comment by fgubler** [comment]
It is indeed about the exact same thing. Thanks for pointing it out :-).
