### ISSUE TITLE
When will `colorOnPrimaryDisabled` be used?

### ISSUE THREAD

**Issue by b95505017** [material-components/material-components-android#229]
I can't find any internal widget style using this attribute, just wondering any recommend way to use this/these attribute(s)? I could see there are some widgets using `colorOnPrimary` as  `android:textColorPrimary`, why doesn't declare a color state list with enable/disable color and reference to colorOnPrimary/colorOnPrimaryDisabled respectively?

**Comment by dsn5ft** [comment]
We had to introduce those 6 variants of on_primary and on_surface for compatibility reasons. See [here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/color/res/values/colors.xml#L56-L68) for more explanation.

We added all 6 variants even if some of them are not used, and we plan on removing them once the AppCompat fix is available.
