### ISSUE TITLE
[MaterialButton] Don't toggle checked state automatically

### ISSUE THREAD

**Issue by lwasyl** [material-components/material-components-android#2291]
**Is your feature request related to a problem? Please describe.**
I want to have several `MaterialButton`s for which I want to control whether they're checked or not. This involves listening to the buttons' `onClick` events and setting proper checked state for each of them. However, sometimes I want a button that's checked to stay checked after being clicked. This is now not possible because the `MaterialButton` will automatically uncheck the button in its `performClick()` method.

**Describe the solution you'd like**
I'd like any option to suppress automatic toggling of the button's checked state.

**Describe alternatives you've considered**
`MaterialButtonToggleGroup` does similar thing with `selection required` option, but it's a linear layout so doesn't allow layouting views in any other way. Also, the logic to keep the button checked or not can vary between buttons

**Comment by lwasyl** [comment]
@drchen 
> I think you can set the button as not checkable by setCheckable() method?

If I read the code well, then if I set the button as not checkable then I won't be able to check it programmatically either:

```java
public void setChecked(boolean checked) {
  if (isCheckable() && isEnabled() && this.checked != checked) {
```

The point of this issue is that I want to check the button programmatically, but not have it toggle the checked state automatically when pressed.

> I'm afraid we cannot make this as a default settings because it will break existing usages.

I don't necessarily want a change in the default behavior, that's why I wrote _I'd like **any option to suppress automatic toggling** of the button's checked state._

**Comment by drchen** [comment]
In that case, you can use OnCheckedChangeListener() and reset the checked state in the listener, similar to what MaterialButtonTogglerGroup is doing.

**Comment by lwasyl** [comment]
This is not that simple because it requires storing some state similar to `skipCheckedStateTracker` if I understand correctly, otherwise I can't check the button programmatically. And since checking the button usually happens from some external place, storing this tracker gets annoying

https://user-images.githubusercontent.com/3951580/125500296-cf548558-9d0d-4bf1-810e-b6505d2a2e30.mov

It's really unfortunate that `MaterialButton` insists on manipulating its state internally instead of letting the user opt-in to external state management

**Comment by drchen** [comment]
Hi, since this already has a solution (doing something like MaterialButtonTogglerGroup is doing), I'm afraid that there's a little chance this will get prioritized among our team.

But we are welcome to any pull requests if you think this feature will be greatly helpful to you. Feel free to author one and I will be glad to review it. : )
