### ISSUE TITLE
[MaterialButton] Default style (contained) not shown

### ISSUE THREAD

**Issue by gregor** [material-components/material-components-android#2292]
**Description:** Button on BottomSheetDialogFragment does not default to Contained style

**Expected behavior:** 
![Screenshot_1625743809](https://user-images.githubusercontent.com/10243309/124914585-d09c9580-dff0-11eb-9c69-05c1e9ccda07.png)
![Screenshot_1625743837](https://user-images.githubusercontent.com/10243309/124914594-d3978600-dff0-11eb-97cc-c92939b32e7c.png)

**Source code:**
```
<Button
  android:id="@+id/btn_submit"
  android:layout_width="match_parent"
  android:layout_height="56dp"
  android:layout_marginStart="16dp"
  android:layout_marginEnd="16dp"
  android:layout_marginTop="16dp"
  android:layout_marginBottom="16dp"
  android:text="@string/bottom_sheet_manual_action"
  android:textAllCaps="true" />
```

**Android API version:** 30

**Material Library version:** 1.4.0

**Device:** Emulator, Gigaset GS110

**Comment by drchen** [comment]
Hi can you check if your themes is correctly set? Or it will be helpful if you can provide a reproducible sample.

**Comment by gregor** [comment]
![Bildschirmfoto 2021-07-10 um 13 37 13](https://user-images.githubusercontent.com/10243309/125161692-09b93f00-e184-11eb-8963-8bf294832161.png)

1. Yes, the theme is set correctly.
2. It works fine with other buttons in the app
3. It works fine with 1.3.0. As soon as I switch to 1.4.0 the behavior of this particular button changes.

I need to see if I find the time to create a sample. Small startup, busy schedule. I quickly found a workaround by explicitly setting the style on that button but wanted to report so you can fix it.

**Comment by gregor** [comment]
I did check with the intermediary release builds. The breaking change was already introduced by 1.4.0-alpha01.

**Comment by drchen** [comment]
Seems a duplicate issue of https://github.com/material-components/material-components-android/issues/2283.

Will keep track there.

**Comment by drchen** [comment]
After some more investigation, this is WAI. 

Bottom sheet dialogs will apply the styles depicted in ?attr/bottomSheetDialogTheme, which points to ThemeOverlay.MaterialComponents.BottomSheetDialog by default, which use Widget.MaterialComponents.Button.TextButton.Dialog.Flush as the default button style.

If you want a different button style, you can either:

1. Set button style explicitly, like what you did; or
2. Extend ThemeOverlay.MaterialComponents.BottomSheetDialog, override ?attr/materialButtonStyle, and override ?attr/bottomSheetDialogTheme in your app theme.
