### ISSUE TITLE
MinTime for Material Time Picker

### ISSUE THREAD

**Issue by HardikLohogaonkar** [material-components/material-components-android#2294]
It's a request to provide setMinTime or similar method to Material TimePicker. In older TimePicker Dialog we can easily set the time validation with the help of setMinTime() with Calendar Instance. It will be helpful to give such validation in newly introduced Material Time Picker.

**Comment by cyb3rko** [comment]
Yeah, would be awesome.
Because atm you have to manually check on button click if the selected time is im the time intervall you want it to be.

**Comment by drchen** [comment]
Let's move to #2299 to continue the discussion for housekeeping purpose. : )
