### ISSUE TITLE
[MaterialAlertDialogBuilder] AlertDialog does not follow Material specs

### ISSUE THREAD

**Issue by StefMa** [material-components/material-components-android#2295]
**Description:** 
Our designer just pointed out, that the "default"/"standard" `MaterialAlertDialog` (created with the `MaterialAlertDialogBuilder`) does not follow the Material specification from [material.io](https://material.io/components/dialogs#specs).

According to the specs, the "button container" should have a size of 52dp.
Which is given.
But between this container and the message, there should be a spce of 28dp.
See 
<img width="377" alt="Screenshot 2021-07-09 at 13 49 10" src="https://user-images.githubusercontent.com/10229883/125073560-71a45280-e0bc-11eb-85b5-29188d07b320.png">
But this is not given.
This is what my desigern sends me:
<img width="464" alt="Screenshot 2021-07-09 at 13 50 04" src="https://user-images.githubusercontent.com/10229883/125073647-926ca800-e0bc-11eb-9eef-eac5ddeed31d.png">
The "gray" area is the "button container" area.
The "red" area is the 28dp.
As you can see, it overlaps roughly halfy over into the "button container".
Which is, again, wrong according to the material spec.

**Expected behavior:** 
I would expect that the `MaterialAlertDialog` follows the material.io guidelines in detail!
in this case, there is more space between the message and the buttons.

**Source code:** 
```kotlin
MaterialAlertDialogBuilder(it.context)
  .setTitle(R.string.credit_card_list_deletion_dialog_title)
  .setMessage(
     it.context.getString(
       R.string.credit_card_list_deletion_dialog_body,
       text.resolve(it.context)
     )
  )
  .setPositiveButton(R.string.common_delete, null)
  .setNegativeButton(R.string.common_cancel, null)
  .show()
```

Nothing face 👆 

**Android API version:** 
I discovered on API 30.. But I guess this doesn't matter.

**Material Library version:** 
👉 com.google.android.material:material:1.4.0

**Device:** Device on which the bug was encountered here
Emulator, Pixel 3, Android API Level 30 📱

**Comment by consp1racy** [comment]
Note that in the docs the 28dp starts at the message baseline, not TextView bottom.

**Comment by drchen** [comment]
Just FYI our designers are having a discussion around this.

**Comment by drchen** [comment]
Since we are going to launch Material 3 soon, with which dialogs will have different paddings, I'll close the issue. 

But still thanks for the report, we will pay more attention on the implementation/doc review to make sure a consistent implementation with the spec.
