### ISSUE TITLE
[BottomNavigationView] return incorrect view height after measured

### ISSUE THREAD

**Issue by Sanlorng** [material-components/material-components-android#2296]
**Description:** BottomNavigationView will return incorrect view height after measured

**Expected behavior:** BottomNavigationView return the correct view height afater measured

**Source code:** 
` 
bottomNavigationView.measure(View.MeasureSpec.UNSPECIFIED, View.MeasureSpec.UNSPECIFIED) 
view.updatePadding(bottom=bottomNavigationView.measuredHeight)
`

**Android API version:** Android API 30

**Material Library version:** 1.5.0-alpha01

**Device:** OnePlus 7 Pro

**Comment by drchen** [comment]
Can you provide more details?

Like, is it returning 0, or larger/smaller than the actual value?

**Comment by Sanlorng** [comment]
> Can you provide more details?
> 
> Like, is it returning 0, or larger/smaller than the actual value?

the return value is 0 and BottomNavigationView can't preview in the Android Studio layout editor

**Comment by illuzor** [comment]
The same in 1.6.0

**Comment by hunterstich** [comment]
Hi @Sanlorng,

When are you trying to get the height of the view? Are you able to wait until the view has been laid out until trying to get it's height?

**Comment by hunterstich** [comment]
@Sanlorng any more info on this? Is this still an issue?

**Comment by Sanlorng** [comment]
> @Sanlorng any more info on this? Is this still an issue?

I need confirm again，I make a workaround code，which work fine at these months.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if you confirm this is still happening.

**Comment by mateuszkwiecinski** [comment]
@drchen 👋 I think I faced the same issue, when trying to upgrade from 1.4.0 to latest stable (1.6.1 at this point)

This change: https://github.com/material-components/material-components-android/commit/7eea2b25bc47553c9b11b7ec5268257588601c76 changed the behavior how [onMeasure](https://github.com/material-components/material-components-android/blob/eb54d6a51a494ab51ae6fe4708c1db2c60fec541/lib/java/com/google/android/material/bottomnavigation/BottomNavigationView.java#L167) works. 

When trying to manually measure the view with `makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)`, the requested measure spec gets overridden with `0, MeasureSpec.EXACTLY` which then results in unwanted behavior. 

Answering one previous questions: my usecase is to manually measure the view to later capture it with https://github.com/facebook/screenshot-tests-for-android and store as a screenshot for later comparison.
