### ISSUE TITLE
Please provide separate dependency to each component

### ISSUE THREAD

**Issue by SaurabhDhage** [material-components/material-components-android#2298]
provide dependency for each component it will reduce the size of the app install all material libraries.
eg. instead  of `  implementation 'com.google.android.material:material:1.4.0'`  provide seprate dependancy for tablayout,floating action button etc.

**Comment by drchen** [comment]
Hi this is under discussion for a long while but we are having some challenges that we need to overcome.

Please refer to the same feature request in the past:
https://github.com/material-components/material-components-android/issues/178

And I'll close this for now.
