### ISSUE TITLE
BottomAppBar elevation not showing

### ISSUE THREAD

**Issue by JamieKalloe** [material-components/material-components-android#230]
For the BottomAppBar (com.google.android.material.bottomappbar.BottomAppBar) there doesn't seem to be an option to achieve elevation as shown in the material.io examples.

This is specifically about elevation on top of the bottom app bar.
I'm using material components verison 1.0.0 and setting 'android:elevation="8dp"' doesn't seem to do anyhting.

Is there a way to achieve this desired behaviour? 
Some guidance would be greatly appreciated!

Kind regards,

Jamie Kalloe

**Comment by wcshi** [comment]
Hi Jamie, 

Thank you for the question. We responded to the Google Issuetracker ticket with an explanation. Please continue the discussion there.

**Comment by JamieKalloe** [comment]
@wcshi Thank you for your reply.

For reference, it seems this is fixed in the 1.1.0 (alpha) release.

> This was fixed in
https://github.com/material-components/material-components-android/commit/560c9822844608da6ea16c0c4815eb437d819fc1

which is part of the 1.1.0 alpha release.

**Comment by binaryKarmic** [comment]
Is this fixed for "compile 'com.android.support:design:28.0.0'" implementations too?
