### ISSUE TITLE
[MaterialTextView] Change the Text Color of a Substring

### ISSUE THREAD

**Issue by Avishek1989** [material-components/material-components-android#2301]
To change the text color of a sub string is a very lengthy process in Android by using SpannableString or any other methods. So it will be better if there is a xml attribute to do that who did that job.

like an attribute app:normalTextColor and another app:substringTextColor and also able to change the style of normal text and substring text. though it done by string tag still if anyone wants the normal text as normal and substring text as underlined.

**Comment by consp1racy** [comment]
What do you call a "sub string" here?

You can make custom theme attributes for your project's needs.

* How do you intend to use and maintain this in a dynamic UIs that are widely used today?
* How do you imagine distilling the rich `SpannableStringBuilder` API into a single XML attribute?
* Do you see this as a widely used feature?
* If you want everything in XML, have you considered DataBinding to implement custom attributes?

**Comment by Avishek1989** [comment]
Imagine if the text design looks like
![image](https://user-images.githubusercontent.com/17877338/125741925-a9aa1ccd-ba16-4ff9-b93d-dbcfb4b23e5f.png)

Yes this can be achieved by SpannableStringBuilder which I already mentioned, but maybe if there is any predefined xml attributes for that that will be useful also.
