### ISSUE TITLE
[MaterialToolbar] Error of subtitle alignment

### ISSUE THREAD

**Issue by zsemen** [material-components/material-components-android#2303]
Issue:

The subtitle is aligned to the left if text strings of the title and the subtitle are identical.

Steps:
1) Use MaterialToolbar for toolbar..
2) Set both titleCentered and subTitleCentered to true
3) Set both tile and subTitle to the same vale, for example "aaa".

Example:

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.appbar.MaterialToolbar
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:titleCentered="true"
            app:subtitleCentered="true"
            app:subtitle="aaa"
            app:title="aaa" />

    </com.google.android.material.appbar.AppBarLayout>

Root cause is in the code line `if (TextUtils.equals(textView.getText(), text))` that results in always returning the TextView of the title and the subTitle is not centered:
```
private void maybeCenterTitleViews() {
    ...
    TextView subtitleTextView = ToolbarUtils.getSubtitleTextView(this);
    ...
}

public class ToolbarUtils {
...
@Nullable
  public static TextView getSubtitleTextView(@NonNull Toolbar toolbar) {
    return getTextView(toolbar, toolbar.getSubtitle());
  }

  @Nullable
  private static TextView getTextView(@NonNull Toolbar toolbar, CharSequence text) {
    for (int i = 0; i < toolbar.getChildCount(); i++) {
      View child = toolbar.getChildAt(i);
      if (child instanceof TextView) {
        TextView textView = (TextView) child;
        if (TextUtils.equals(textView.getText(), text)) {
          return textView;
        }
      }
    }
    return null;
  }
}
```
![Error_subtitle_alignment](https://user-images.githubusercontent.com/37803241/125911079-f0d35144-ad70-47ed-a2eb-ac7d05111cf5.jpg)

**Comment by matpag** [comment]
@dsn5ft I could work on this but what should be the proper way to fix this?
MaterialToolbar has 2 hidden methods for grabbing the correct [TextView](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:appcompat/appcompat/src/main/java/androidx/appcompat/widget/Toolbar.java;l=2317-2330?q=androidx.appcompat.widget.Toolbar&ss=androidx%2Fplatform%2Fframeworks%2Fsupport)

Most reliable option could be to try to call those hidden methods with reflection and fallback to the current logic if something goes wrong, what do you think?
