### ISSUE TITLE
[BottomSheet] BottomSheetDialogFragment not occupying whole width on tablets

### ISSUE THREAD

**Issue by VincentJoshuaET** [material-components/material-components-android#2307]
I have MATCH_PARENT everywhere I can.

Version: 1.4.0

![Screenshot_20210719-080749_GeoViewer Mobile Debug](https://user-images.githubusercontent.com/19756326/126086486-cdab6f63-5861-41ea-9b07-f98180995df6.png)

**Comment by josefigueroa168** [comment]
The maxWidth parameter you are encountering is expected behavior with release [1.4.0](https://github.com/material-components/material-components-android/releases/tag/1.4.0). You can override this by setting `android:maxWidth="@empty"` on the xml or calling setMaxWidth.
