### ISSUE TITLE
[TextInputEditText] Chnage hint gravity to top

### ISSUE THREAD

**Issue by burhankhanzada** [material-components/material-components-android#2308]
**Description:**
i have `TextInputEditText` with `minHeight="250dp"` inside `TextInputEditText` and have setted hint on it but intial hint is showing in center vertically i want to show on start or top right side of TextInputEditText

**Android API version:** API 29

**Material Library version:** 1.5.0-alpha01

**Device:** Device on which the bug was encountered here

**Comment by drchen** [comment]
Hint text is meant to be aligned with the input text. Closing the issue as WAI.
