### ISSUE TITLE
TextInputLayout Error Image

### ISSUE THREAD

**Issue by volsahin** [material-components/material-components-android#231]
Is there a built in way to set error icon to the component or we need to create it ?

**Comment by abalta** [comment]
Yes, I have same issue. I'm trying to set custom error icon.

**Comment by wcshi** [comment]
This is currently not supported, could you please file a feature request at: 
https://issuetracker.google.com/issues/new?component=439535

**Comment by wcshi** [comment]
http://issuetracker.google.com/issues/117087371
