### ISSUE TITLE
[NavigationRail] Missing predefined styles for NavigationRail when using as unelevated

### ISSUE THREAD

**Issue by SupasinTatiyanupanwong** [material-components/material-components-android#2310]
**Is your feature request related to a problem? Please describe.**
As per this section in the specs, https://material.io/components/navigation-rail#behavior. We should have the predefine styles of it.  Also, in the specs we also have a screenshot where NavigationRail is flat and having nicer greyish divider on the right.

I think it is pretty common use cases for this kind of usages and we should have a predefined one for it, just like what we have for MaterialButton.

**Describe the solution you'd like**
Having two more main predefined styles for NavigationRail containing zero elevation, and transparent backgrounds with and without divider, e.g. _**Widget.MaterialComponents.NavigationRailView.Unelevated**_ and _**Widget.MaterialComponents.NavigationRailView.Unelevated.WithDivider**_

**Additional context**
From the specs in https://material.io/components/navigation-rail:

1. Unelevated NavigationRail without divider on the right _**could be**_ _Widget.MaterialComponents.NavigationRailView.Unelevated_
![image](https://user-images.githubusercontent.com/14759073/126485844-f52f1be6-4b16-47da-9a3a-e576d804f720.png)

2. Unelevated NavigationRail with greyish divider on the right _**could be**_ _Widget.MaterialComponents.NavigationRailView.Unelevated.WithDivider_
![image](https://user-images.githubusercontent.com/14759073/126485812-26be8078-fdc4-4523-a935-c5c58de3628f.png)

**Comment by hunterstich** [comment]
Hi @SupasinTatiyanupanwong,

Our Material3 styles now set NavigationRail's elevation to 0dp by default. I'm going to go ahead and close this issue as no longer relevant.
