### ISSUE TITLE
[BottomSheetBehavior] flickering BottomSheetDialog width when expand in large screen

### ISSUE THREAD

**Issue by ekoo** [material-components/material-components-android#2313]
**Description:** related to [this commit](https://github.com/material-components/material-components-android/commit/63d01aa2686d56b165e9131265a449d810359695) , i have BottomSheetDialogFragment, after upgrade to 1.4.0 , when bottomsheet expand, it's look flickering from full width ( previous behavior, in 1.3.0 ) to new default max width, i think this is race condition issue

**Expected behavior:** bottomsheet expand without flickering size

**Source code:** i'm using navigation component to show dialog

**Android API version:** 28

**Material Library version:** 1.4.0

**Device:**  10 inch chinese tablet

**Comment by drchen** [comment]
Do you have a screen recording?

**Comment by ekoo** [comment]
https://user-images.githubusercontent.com/35864865/127105069-fc911bf5-90e4-442d-b1eb-6aa64861c268.mp4

**Comment by paulfthomas** [comment]
This should be resolved, see https://github.com/material-components/material-components-android/commit/9fb73b50ff97d897b4716a733ce22bfed9c67b12
