### ISSUE TITLE
How can I not find a functional dialogue?

### ISSUE THREAD

**Issue by alirezabashi98** [material-components/material-components-android#2314]
dialog = MaterialAlertDialogBuilder(this)
        dialog.setCancelable(false)
                .setTitle("لطفا صبر کنید...")
                .show()

How can I not find a functional dialogue?

**Comment by drchen** [comment]
Can you elaborate?

**Comment by cyb3rko** [comment]
What does not work for you?

**Comment by drchen** [comment]
Closing the issue due to no further info.
