### ISSUE TITLE
[MaterialCardView] cardMaxElevation not works

### ISSUE THREAD

**Issue by agustinsivoplas** [material-components/material-components-android#2316]
**Description:** I have a recyclerview (vertical layout manager) with multiple cards, I would like to each card have the same shadow, for that I set the cardElevation and cardMaxElevation with the same value, but the cards have differents shadows (cards at bottom have darker shadows). I tried to set app:cardUseCompatPadding to true but does not have any effect.

**Expected behavior:** All the cards have the same shadow

**Source code:** 

```
<com.google.android.material.card.MaterialCardView
        android:id="@+id/learningLibraryItemCardView"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_marginTop="5dp"
        android:clickable="true"
        android:focusable="true"
        app:cardBackgroundColor="@color/white"
        app:cardCornerRadius="8dp"
        app:cardElevation="4dp"
        app:cardMaxElevation="4dp"
        app:cardPreventCornerOverlap="false"
        app:cardUseCompatPadding="false"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

// ....
    </com.google.android.material.card.MaterialCardView>
```

**Android API version:** Android API 30

**Material Library version:** 1.3.0-alpha02

**Device:** Nexus 10

![Screenshot_1627489510](https://user-images.githubusercontent.com/1648539/127360318-4f87d6a0-8ee4-4f1d-b377-47271af50981.png)

**Comment by josefigueroa168** [comment]
I am not sure if it is super clear in your screenshot that shadows are darker below. I believe there may be less of a perception of shadow when cards are compact compared to open space below. Have you checked layout inspector to confirm elevation renders to different values as well as shadow colors?

**Comment by agustinsivoplas** [comment]
> I am not sure if it is super clear in your screenshot that shadows are darker below. I believe there may be less of a perception of shadow when cards are compact compared to open space below. Have you checked layout inspector to confirm elevation renders to different values as well as shadow colors?

As you mention, the elevation value is the same for all cards, but the shadow is different (the second card shadows looks bigger), probably is how works the lights in android to create the shadow. Do you know if is possible to make all the cards with the same shadow perception?

https://material.io/design/environment/light-shadows.html#light

![Screenshot_1628089055](https://user-images.githubusercontent.com/1648539/128204112-07d5d113-7482-48e5-b6ce-9b914f098d67.png)

**Comment by josefigueroa168** [comment]
I see, based on the documentation and conversations with the team I'd say this slight change in perception is an intentional part of material design and not a bug, and there is not a way to interact with the shadow property through card (aside from changing elevation. That said, maybe you could use a drawable for a custom shadow property as described here: https://developer.android.com/training/material/shadows-clipping#Shadows ?

**Comment by agustinsivoplas** [comment]
> I see, based on the documentation and conversations with the team I'd say this slight change in perception is an intentional part of material design and not a bug, and there is not a way to interact with the shadow property through card (aside from changing elevation. That said, maybe you could use a drawable for a custom shadow property as described here: https://developer.android.com/training/material/shadows-clipping#Shadows ?

Thanks for the advice I will research
