### ISSUE TITLE
[MaterialDatePicker] Showing month of constrained startDate when current month is after month of setSelection date

### ISSUE THREAD

**Issue by nevardreik** [material-components/material-components-android#2321]
**Description:** Full description of issue here
When `setSelection` is called on the `MaterialDatePicker` builder with a date in a previous month than the current month, **and calendar constraints are set**, the calendar shows the month of the `startDate`, but the selected date is what was passed into `setSelection`.

![image](https://user-images.githubusercontent.com/20432300/127956140-d32586ee-4258-4dcb-85fa-b9bb6cd5a2d7.png)

**Expected behavior:** Screenshots and/or description of expected behavior
When launching the date picker, it should be showing the month of the selected month as per below.
![image](https://user-images.githubusercontent.com/20432300/127955859-440f619e-194b-4bd3-ab04-f4c93e155448.png)

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

```
// dateRange.first = 2020-10-31T00:00:00.00Z
// dateRange.second = 2021-07-30T00:00:00.00Z
val validators = listOf(
    DateValidatorPointForward.from(dateRange.first.toEpochMilliseconds()),
    DateValidatorPointBackward.before(dateRange.second.toEpochMilliseconds())
)
calendarConstraints = CalendarConstraints.Builder()
    .setStart(dateRange.first.toEpochMilliseconds())
    .setEnd(dateRange.second.toEpochMilliseconds())
    .setValidator(CompositeDateValidator.allOf(validators))
```

```
// selectedDate = 2021-07-30T00:00:00.00Z
val datePicker = MaterialDatePicker.Builder.datePicker()
    .setCalendarConstraints(calendarConstraints.build())
    .setSelection(selectedDate.toEpochMilliseconds())
    .build()

datePicker.show(requireActivity().supportFragmentManager, TAG_DATE_PICKER)
```

**Android API version:** Android API version here
API 30

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.4.0

**Device:** Device on which the bug was encountered here
Android Pixel 4 emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
If you set the second date range to dateRange.second = 2021-07-31T00:00:00.00Z, will that work correctly?

**Comment by josefigueroa168** [comment]
Closing the issue due to no further info available, please feel free to reopen it with more details
