### ISSUE TITLE
[FloatingActionButton] When pressed mini fab has excess shadow on bottom and right side

### ISSUE THREAD

**Issue by ablenesi** [material-components/material-components-android#2323]
**Description:** Using FloatingActionButton mini variant has rendering issue when pressed on Android 12
![issue full scale](https://user-images.githubusercontent.com/10282350/128045459-7467c45d-b05e-4d9c-8195-98a41fd3236f.png)

**Expected behavior:** Screenshots and/or description of expected behavior
|Expected - Pixel 3A - Android 11| Actual - Pixel 5 Android 12 Beta 3|
|-|-|
|![Android Pixel 3A - API 30](https://user-images.githubusercontent.com/10282350/128045262-b35edff8-3b67-4d83-83fb-4d501f31ded5.png)|![127221029-3c98b8bf-22d5-410a-a8a9-53bccee30f39](https://user-images.githubusercontent.com/10282350/128043940-19228884-c887-4fa4-b575-5993f50aff2e.png)|

**Source code:** 
```
app:fabSize="mini"
```

**Android API version:** Android 12 Beta 3

**Material Library version:** reproduced on 1.3.0, 1.5.0-alpha01 

**Device:** Pixel 5

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by Toubap** [comment]
Encountered the same issue, actually it seems to happen when fabSize is low (~40dp and lower)

**Comment by loshine** [comment]
Same problem, mini size and custom size below 48dp will happen.

**Comment by alan-camilo** [comment]
Looks like there is nothing to do except waiting for the next Android version according to this comment [https://github.com/material-components/material-components-android/issues/2617#issuecomment-1084681821](https://github.com/material-components/material-components-android/issues/2617#issuecomment-1084681821)
