### ISSUE TITLE
Components with Dark Themes

### ISSUE THREAD

**Issue by costular** [material-components/material-components-android#233]
Hello,

I have some issues with dark themes in my app and TextInputLayout (even other components). Even when I am using Dark Material Theme colors can't be seen properly in dark backgrounds. Also, I only found color attributes for focus state so when the component is not focused it can't be seen. Screenshot here:

<img width="328" alt="screenshot 2018-11-22 at 01 04 02" src="https://user-images.githubusercontent.com/7817039/48875768-dd91f980-edf2-11e8-9b49-a3c4b1f4a607.png">

Thanks!

**Comment by dsn5ft** [comment]
Responded here - https://issuetracker.google.com/issues/119884011
