### ISSUE TITLE
[BottomSheetDialog] MaterialButton in BottomSheetDialog will be forced to single-line

### ISSUE THREAD

**Issue by Back4fire** [material-components/material-components-android#2333]
MaterialButton in BottomSheetDialog will be forced to single-line. With the Layout Inspector, I found singleLine==ture and maxLines==1. But I never set these values explicitly. The bug starts from Material 1.4.0. And still exists in 1.5.0-alpha02. 

The following is a very simple layout, a Button in a FrameLayout.

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="300dp">

    <Button
        android:id="@+id/button"
        android:layout_width="150dp"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:text="I will be forced to be single-line in Bottom Sheet Dialog with Material Lib 1.4.0+" />
</FrameLayout>

![device-2021-08-15-165518](https://user-images.githubusercontent.com/20295792/129473378-ce404f5f-9a2c-46ea-83c3-716f5ec2a33f.png)
This screenshot is compiled with Material 1.3.0. Everything is correct.

![device-2021-08-15-165609](https://user-images.githubusercontent.com/20295792/129473392-dc6061ee-5989-49ed-beaa-80b38d2ed40e.png)
This screenshot is compiled with Material 1.4.0. The Button is single-line.

[SourceCode.zip](https://github.com/material-components/material-components-android/files/6987845/SourceCode.zip)

The layouts in my project related to this bug are broken. If there is any workaround before it can be fixed, please let me know.

**Comment by Back4fire** [comment]
Thanks.

**Comment by sds100** [comment]
> Thanks.

how come you closed this? I haven't fixed it 😄

**Comment by Back4fire** [comment]
I thought the MD team doesn't treat it as a bug.😁 But it's unreasonable to make the style of MaterialButton in BottomSheetDialog like that in AlertDialog. We usually put complicated UI in BottomSheetDialog.

**Comment by sds100** [comment]
> I thought the MD team doesn't treat it as a bug.😁 But it's unreasonable to make the style of MaterialButton in BottomSheetDialog like that in AlertDialog. We usually put complicated UI in BottomSheetDialog.

Yeah, I agree

**Comment by drchen** [comment]
Yes, it's working as designed.

If you want to change the button style, you can extend ThemeOverlay.MaterialComponents.BottomSheetDialog and override ?attr/MaterialButtonStyle to the style you like, and set your main theme's ?attr/bottomSheetDialogTheme to the custom theme.
