### ISSUE TITLE
[MaterialDatePicker] Touch target for selectable dates is 40dp, should be at least 48dp according to Google Play pre-launch reports

### ISSUE THREAD

**Issue by peterhav** [material-components/material-components-android#2344]
**Description:** Google Play pre-launch reports complain that the touch target for various UI elements is to small. When looking into the reports; most of the warnings are from the material date picker dialog.

**Expected behavior:** Screenshot of the pre launch report warning:

![image](https://user-images.githubusercontent.com/1724223/130436129-cbca5f67-2534-448f-a747-a7e0d6b0f977.png)

**Source code:** Nothing specific, just launching the dialog is enough to trigger these warnings.

**Android API version:** All

**Material Library version:** com.google.android.material:material:1.4.0'

**Device:** Pixel 3, running Android 9 - but happens on more devices

**Comment by drchen** [comment]
That's unfortunately a limitation of the calendar layout. (We have to fit 7 days in a row.) 

On a device wider than 480dp, the touch target size will be 48x48dp. But on devices narrower than 480dp we have to reduce the day view size to 40x40dp or the calendar will be wider than the screen.

Closing the issue as WAI.
