### ISSUE TITLE
[CircularProgressIndicator] Lines outside indicator circle

### ISSUE THREAD

**Issue by kikasik** [material-components/material-components-android#2345]
**Description:** Indicator has 2 lines inside and outside the circle. These lines have color from trackColor attribute. The colors I use in XML have no alpha.
Screenshots:
![photo_2021-08-23_21-12-49](https://user-images.githubusercontent.com/26849835/130489009-4ca1b62d-960d-43a0-87b9-c84e6673e958.jpg)
![photo_2021-08-23_21-12-58](https://user-images.githubusercontent.com/26849835/130489024-570ce823-257d-486b-b1f1-e5d816e97280.jpg)

**Expected behavior:** No lines of track color outside indicator circle.

**Source code:** 
```xml
<com.google.android.material.progressindicator.CircularProgressIndicator
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:indeterminate="true"
        app:indicatorSize="@dimen/_60dp"
        app:indicatorColor="@color/lightBlue"
        app:trackColor="@color/blue"
        app:trackThickness="5dp" />
```

**Android API version:** 30

**Material Library version:** 1.4.0

**Device:** Samsung Galaxy s10e and Lenovo TB-X606F

**Comment by pekingme** [comment]
Thanks for reaching out! The two thin lines should be the artifacts of anti-aliasing. I noticed that you are setting the `indicatorColor` the same as the background and leaving the `trackColor` more distinguished. Attempting to hide the indicator part is probably the only way to emphasize this artifact. Any reason to configure your CPI in this way?

**Comment by kikasik** [comment]
How I can hide track background in another way?

**Comment by kikasik** [comment]
@pekingme Sorry, my bad, track and indicator are easy to mix up. After applying the color of the track to the indicator and vice versa all works perfectly.
