### ISSUE TITLE
[Divider] Divider with custom drawable resource

### ISSUE THREAD

**Issue by sanisloandras** [material-components/material-components-android#2349]
I would like to use the divider with a custom drawable resource, which has a gradient effect, which fades into my primary background color. For example:

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">

    <gradient
        android:startColor="@color/colorToolbarGradientStart"
        android:centerColor="@color/colorToolbarGradientStart"
        android:endColor="?attr/colorBackgroundPrimary"
        android:type="linear" />

</shape>
```

The problem I have is when I set the dividerInsetStart attribute. For some reason, some other color is visible at the start of the divider, and after app:dividerInsetStart="@dimen/_16sdp", my custom drawable is visible on top of it. Please check the attached photo.

[https://ibb.co/tLRLZhB](url)

```
<com.google.android.material.divider.MaterialDivider
            android:id="@+id/vDivider"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/_12sdp"
            android:background="@drawable/divider_horizontal"
            app:dividerInsetEnd="@dimen/_16sdp"
            app:dividerInsetStart="@dimen/_16sdp"
            app:layout_constraintTop_toBottomOf="@+id/search" />
```

I found a workaround by removing app:dividerInsetStart and adding marginStart, but it just does not feel right...

```
<com.google.android.material.divider.MaterialDivider
            android:id="@+id/vDivider"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/_12sdp"
            android:layout_marginStart="@dimen/_16sdp"
            android:background="@drawable/divider_horizontal"
            app:dividerInsetEnd="@dimen/_16sdp"
            app:layout_constraintTop_toBottomOf="@+id/search" />
```

Here is a photo of what I want to achieve:
https://ibb.co/47G5PPH

And another problem is that my custom drawable is not displayed in total length, it get's cropped even if the insets and margins are set to 0. It's noticable because the divider should fande into my primaryBackgroundColor, but fore some reason it does not. Please see the attached photos:
Wrong: https://ibb.co/C8jVPcj
Correct: https://ibb.co/gPz1B79

**Comment by drchen** [comment]
Hi, MaterialDivider is actually a super simple class mostly implemented for design consistency. If you need a custom design, maybe it will be better to just use a plain view with background image? Another option is you can extend MaterialDivider and override onDraw() method to implement your own draw logic. 

I'll close the issue. : )
