### ISSUE TITLE
[M3] [Catalog] Dynamic Colors preference always disabled

### ISSUE THREAD

**Issue by paulkugaev** [material-components/material-components-android#2353]
**Description:** Dynamic Colors preference always disabled even though running on Android 12 Beta 4.2.

**Expected behavior:** Dynamic Colors preference enabled

**Source code:** The source of the issue is in method of `androidx.core.os.BuildCompat`:

```
    @ChecksSdkIntAtLeast(codename = "S")
    public static boolean isAtLeastS() {
        return VERSION.CODENAME.equals("S");
    }
```
Which actually returns false (the actual value is "REL")

**Android API version:**  `Android 12 Beta 4.2`

**Material Library version:** `1.5.0-alpha03`

**Device:** `Google Pixel 3`

**Comment by drchen** [comment]
Hi, thanks for reporting this, we will fix it soon. For now can you add the following dependency to your build.gradle and see if it works?

androidx.core:core:1.6.0

**Comment by paulkugaev** [comment]
@drchen yes, it does, but the actual feature doesn't work for some reason. gonna investigate further later today

**Comment by Yan679** [comment]
> **Description:** Dynamic Colors preference always disabled even though running on Android 12 Beta 4.2.
> 
> **Expected behavior:** Dynamic Colors preference enabled
> 
> **Source code:** The source of the issue is in method of `androidx.core.os.BuildCompat`:
> 
> ```
>     @ChecksSdkIntAtLeast(codename = "S")
>     public static boolean isAtLeastS() {
>         return VERSION.CODENAME.equals("S");
>     }
> ```
> 
> Which actually returns false (the actual value is "REL")
> 
> **Android API version:** `Android 12 Beta 4.2`
> 
> **Material Library version:** `1.5.0-alpha03`
> 
> **Device:** `Google Pixel 3`
