### ISSUE TITLE
[Material3] Which api styles your app icon

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android#2357]
I'm using material3 on my android 12 device and it's working great. The last thing I want to do is allow my app icon to be styled by material you like all of googles apps do on android 12. Is that available somewhere?

**Comment by OxygenCobalt** [comment]
AFAIK, you can't. You have the use the android system-defined colors manually. [This table will probably help.](https://github.com/material-components/material-components-android/blob/d4436fe136b5b3570a885c438f28437e1c5bd80e/docs/theming/Color.md).

**Comment by RikkaW** [comment]
This is not related to MaterialComponents, you only need to use `@android:color/system_` colors.

An example:
https://github.com/RikkaApps/WADB/blob/v5.1.1/app/src/main/res/drawable-nodpi-v26/ic_launcher.xml
https://github.com/RikkaApps/WADB/blob/v5.1.1/app/src/main/res/values-v31/colors.xml#L17-L18

**Comment by ColtonIdle** [comment]
@RikkaW awesome. Thank you! Do you know if there's a way to have a fallback color (aka my usual colors) if the launcher doesn't support this? The way you have it setup, it looks like the only "check" is whether its api 31

**Comment by RikkaW** [comment]
@ColtonIdle There is no launcher that does not support this, since the icon is loaded through framework codes. Also, it's just a color reference, using color reference in drawable is available from very old versions of the Android system.

**Comment by ColtonIdle** [comment]
If I turn off themed icons though... all of googles apps turn back to their original color... but my app icon stays the same material you color, instead of changing to the api 30 and lower colors.

<img width="212" alt="Screen Shot 2021-09-05 at 12 26 11 AM" src="https://user-images.githubusercontent.com/31751141/132115255-66211a3f-0650-478b-abd2-c8c6e28690f5.png">

**Comment by RikkaW** [comment]
You have to learn how things work first. Apps can only provide one icon, there is no API for the app to provide a "themed icon". The "Themed icons" from Pixel launcher is its private implementation, the themed icon is provided by Pixel launher itself rather than the app.

**Comment by ColtonIdle** [comment]
I understand that you can only provide a single icon, but I thought that maybe there was a new resource qualifier like `values-material3` or something, and if you were using a material3 compatible launcher, then it would choose that instead. The way you stated your answer originally seemed like this was the api to do it where it would use material you colors when available, and use the default colors when it wasn't available.

**Comment by paulkugaev** [comment]
@ColtonIdle the trick is that google's apps themed icons are embedded into pixel launcher. so there is not API for that and probably won't be

**Comment by drchen** [comment]
Unfortunately there's no plan to have something like values-dynamicColors, at least in Android S. 
(It's a framework decision and beyond Material library's control, btw.)

Also I don't think there will be a reliable way (not mentioning a system API) to check if the device is support dynamic colors in S. 

On a S device that's not supporting dynamic colors, it will provide a default palette instead, which may differ from brand to brand.

**Comment by OxygenCobalt** [comment]
Just to let future people know, Android 13 added an API for themed icons. You have to specify a `<monochrome>` drawable resource within your adaptive icon. More information is [here](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add_your_adaptive_icon_to_your_app)

**Comment by ColtonIdle** [comment]
Yeah. I added it and it works super great now. thanks for the heads up
