### ISSUE TITLE
[ProgressIndicator] Make possible to extends Linear or Circular progress indicator

### ISSUE THREAD

**Issue by GerardPaligot** [material-components/material-components-android#2361]
**Is your feature request related to a problem? Please describe.**
In my Android Design System, I'm creating a subclass for all material classes to extend the material implementation but `CircularProgressIndicator` and `LinearProgressIndicator` are final classes.

**Describe the solution you'd like**
Just remove the `final` keyword on these classes.

**Describe alternatives you've considered**
Create my own custom view to configure a circular or linear progress view but I would like to avoid this solution.

**Comment by drchen** [comment]
Makes sense to me. Thanks for your explanation. I'll raise this to the team. Feel free to just create a PR, which will make things move faster I guess. : )

**Comment by ekager** [comment]
We have the same issue. We are trying to build custom components built around Material Components and need to be able to extend these classes to do so.
