### ISSUE TITLE
[MaterialButton] iconGravity not working correct for CircularProgressIndicator

### ISSUE THREAD

**Issue by Wirling** [material-components/material-components-android#2364]
**Description:** I've created a custom view that extends MaterialButton that replaces the drawable with a CircularProgressIndicator when it's loading.

However when I replace the drawable with the CircularProgressIndicator the iconGravity doesn't work anymore.

**Expected behavior:** 
correct behaviour
![delete_correct](https://user-images.githubusercontent.com/17887888/132671674-0ed04f46-d597-491d-bf3c-57a525cdf168.png)

incorrect behaviour
![delete_incorrect](https://user-images.githubusercontent.com/17887888/132671686-f312d77b-200c-44fa-971f-72cc49aa3864.png)

**Source code:**

    class LoadingButton constructor(context: Context) : MaterialButton(context) {

        private val progressIndicatorDrawable by lazy {
            val progressIndicatorSpec = CircularProgressIndicatorSpec(context, null, 0, R.style.Widget_MaterialComponents_CircularProgressIndicator_ExtraSmall)
            progressIndicatorSpec.indicatorColors = intArrayOf(getColor(context, R.color.white))
            IndeterminateDrawable.createCircularDrawable(context, progressIndicatorSpec).apply {
                setVisible(true, true)
            }
        }

        init {
            // the following drawable is aligned to the start of the view (incorrect).
            icon = progressIndicatorDrawable
            // the following drawable is aligned to the start of the text (correct).
            // icon = DrawableUtil.getDrawable(context, R.drawable.icon_delete)
            text = "Delete"
            iconGravity = ICON_GRAVITY_TEXT_START
        }
    }

**Android API version:** Android 10

**Material Library version:** com.google.android.material:material:1.3.0, also tried 1.5.0-alpha02

**Device:** OnePlus 6T

**Detailed description of the problem with possible work-around:** https://stackoverflow.com/questions/69032458/android-icongravity-not-working-for-materialbutton-with-circularprogressindicato

**Comment by zs1973** [comment]
+1
