### ISSUE TITLE
[MaterialDatePicker] OnSelectionChangedListener is not accessible.

### ISSUE THREAD

**Issue by saoudiabderraouf** [material-components/material-components-android#2366]
Description: Trying to implement custom DateSelector. but it shows error as

"com.google.android.material.datepicker.OnSelectionChangedListener' is not public in 'com.google.android.material.datepicker'. Cannot be accessed from outside package"

**Comment by drchen** [comment]
Hi, can you provide more details about why you need a custom DateSelector? 

It is intended that DataSelector interface is not public. We may need to evaluate the use case before we decide if we should open it or not.

**Comment by drchen** [comment]
I'll close the feature request since there's no further info. Feel free to reopen it with more info so that we can evaluate the impact of the request. Thanks!
