### ISSUE TITLE
[ShapeableImageView] Background color with alpha is not rendered correctly

### ISSUE THREAD

**Issue by ChristianoBolla-Appwise** [material-components/material-components-android#2367]
**Description:**

When using the ShapeableImageView with a color that has a certain transparency the transparency is less than when we use the same color on another view i.e. TextView. See image as a reference.
This is only the case when I use it like this in a list item.

![20210910_120526](https://user-images.githubusercontent.com/36888232/132837627-ace42923-8c72-44f3-909d-e856629b3572.jpg)

**Expected behavior:**
I expect that the colors are the same on both Views. 

**Source code:** 
The issue can be easily reproduce by using this snippet in a list.

```
<com.google.android.material.card.MaterialCardView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="10dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_vertical"
            android:orientation="horizontal"
            android:padding="10dp">

            <com.google.android.material.imageview.ShapeableImageView
                android:id="@+id/ivAbsenceType"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:background="#33028093"
                android:src="@drawable/ic_vacation"
                app:contentPadding="10dp"
                app:shapeAppearance="@style/Shape.Circle" />

            <TextView
                android:id="@+id/tvSpanOfDays"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginHorizontal="10dp"
                android:background="#33028093"
                android:text="01 augustus - 04 augustus" />
        </LinearLayout>
</com.google.android.material.card.MaterialCardView>
```

Circle Shape
```
    <style name="Shape.Circle" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">50%</item>
    </style>
```

**Android API version:**
29

**Material Library version:** 
1.4.0

**Device:** Device on which the bug was encountered here
Samsung Galaxy S20 (SM-G965F)

**Comment by josefigueroa168** [comment]
I am unable to replicate this issue on API 30:

![Screen Shot 2021-09-21 at 1 46 35 PM](https://user-images.githubusercontent.com/25285010/134221592-14772e88-af1a-44f5-812a-fd555a17aa88.png)

Sample Code: 
```
<com.google.android.material.imageview.ShapeableImageView
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_marginEnd="8dp"
            android:layout_marginRight="8dp"
            android:background="#33028093"
            android:src="@drawable/ic_components_24px"/>

  <TextView
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:background="#33028093"
      android:text="Title goes here."/>
```

My assumption would be that the drawable in use is not fully transparent. I will attempt this on API 29 and edit if I can replicate.

**Comment by josefigueroa168** [comment]
Update: Could not replicate this on API 29 so I will close this for now. Try this with another transparent drawable and feel free to let us know if the problem persists.
