### ISSUE TITLE
[Material3-BottomSheet] BottomSheetDialogFragment does not perform slide animation when it appears

### ISSUE THREAD

**Issue by serbelga** [material-components/material-components-android#2368]
**Description:** 
On Material3 theme, `BottomSheetDialogFragment` does not perform slide animation when it appears and it's defined as `<dialog/>` in an Android Navigation Graph.
I've updated my app theme from `Theme.MaterialComponents` to `Theme.Material3` and now, this slide animation is not performed when BottomSheet dialog is expanded.

**Expected behavior:** 
BottomSheetDialog must perform a slide animation when application navigates to this dialog as it is done in `Theme.MaterialComponents`.

**Source code:** 
https://github.com/serbelga/ToDometer/tree/feature/material3

**Android API version:** 
Android 11 (API level 30)

**Material Library version:** 
1.5.0-alpha03

**Device:** 
OnePlus 7T

| Theme.MaterialComponents (Works as expected) | Theme.Material3 |
|---|---|
| <img width=320 src="https://user-images.githubusercontent.com/26246782/132953047-630eb1e8-84fd-46f0-81d3-f8d0a659e8b9.gif" /> | <img width=320 src="https://user-images.githubusercontent.com/26246782/132953116-ac5c712a-3ad8-4c19-a299-a41a0ee013fb.gif" /> |

**Comment by drchen** [comment]
Hi, bottom sheet styles were not implemented in 1.5.0-alpha03. They will be included in the next version. : )
