### ISSUE TITLE
[TimePicker] Usable 24-hour format

### ISSUE THREAD

**Issue by blueglyph** [material-components/material-components-android#2373]
The current TimePicker has a broken 24-hour format, in which there is only one circle to contain 24 values. As a result, the designer was forced to hide very other number, which is most confusing for the user.

The TimePickerDialog has a more user-friendly double-circle solution, but unfortunately there is little control on some elements like the initial input mode, the colours, and so on.

What is TimePickerDialog based on? TimePicker? Something else?

=> It would be good to reintegrate the improvement into the base component TimePicker.

Here is an image showing the problem with the current TimePicker:
![image](https://user-images.githubusercontent.com/31706195/133268320-7c1329c0-6890-419d-9560-e20d739ecb3f.png)

Here is what the TimePickerDialog looks like (it is not explained on the material.io site, unfortunately):
![image](https://user-images.githubusercontent.com/31706195/133268714-58a96c15-152b-4913-82ff-5be4a8c02304.png)

**Comment by josefigueroa168** [comment]
This issue is similar in nature to issue #1450. Many active conversations on this topic.
