### ISSUE TITLE
Change AppBarLayout Elevation Overlay Tint

### ISSUE THREAD

**Issue by prathameshmm02** [material-components/material-components-android#2375]
Is it possible to change tint of AppBarLayout when scrolled? Currently it uses ColorSurface from themes, I am not sure though. This is just to support Apps with Accent Color theming.

**Comment by OxygenCobalt** [comment]
Re-define `elevationOverlayColor` in your app's theme, like this:

```
<style name="Theme.MyApp>
    <item name="elevationOverlayColor"><!-- Your color here, presumably colorPrimary if you want to follow system accents--></item>
</style>
```

**Comment by prathameshmm02** [comment]
Thanks, I was trying if I can add an accent to the color of the elevated app bar, according to the app accent color. But I guess I'll settle for this. And great app btw Auxio.
