### ISSUE TITLE
[ExtendedFloatingActionButton] background clip animation does not work

### ISSUE THREAD

**Issue by Azbesciak** [material-components/material-components-android#2381]
**Description:** When custom background is set to clip drawable, or any containing like below
````xml
<clip
    android:clipOrientation="horizontal"
    android:gravity="start">
    <shape android:shape="rectangle">
          <corners
                android:bottomLeftRadius="?attr/progressingButtonCornerRadius"
                android:bottomRightRadius="?attr/progressingButtonCornerRadius"
                android:topLeftRadius="?attr/progressingButtonCornerRadius"
                android:topRightRadius="?attr/progressingButtonCornerRadius" />
           <solid android:color="?attr/progressingButtonBackground" />
    </shape>
</clip>
````
cliping does not work; setting the same for normal button does work.

**Expected behavior:**
With `ExtendedFloatingActionButton`
![image](https://user-images.githubusercontent.com/17334466/133883697-1b752e1e-d54b-4ea0-91ea-3d070d4e3589.png)

With simple `Button`
![image](https://user-images.githubusercontent.com/17334466/133883767-bd48db1a-8ff9-4c63-85b1-6a772b4d95fb.png)

**Source code:**
background drawable
````xml
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <corners
                android:bottomLeftRadius="25dp"
                android:bottomRightRadius="25dp"
                android:topLeftRadius="25dp"
                android:topRightRadius="25dp" />
            <solid android:color="@color/white" />
            <stroke android:width="4dp" android:color="#D81B60"/>
        </shape>
    </item>
    <item android:id="@+id/clipItem">
        <clip
            android:clipOrientation="horizontal"
            android:gravity="start">
            <shape android:shape="rectangle">
                <corners
                    android:bottomLeftRadius="25dp"
                    android:bottomRightRadius="25dp"
                    android:topLeftRadius="25dp"
                    android:topRightRadius="25dp" />
                <solid android:color="#D81B60" />
            </shape>
        </clip>
    </item>
</layer-list>
````
background replacement
``` kotlin
val drawable = prepareDrawable(R.drawable.extended_progressive_bg, R.style.ProgressingButton_Cancel) as LayerDrawable
clipDrawable = drawable.findDrawableByLayerId(R.id.clipItem)
ext_btn.background = drawable
```
`ext_btn` is either `Button` or `com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton`. Please notice that `Button` != `com.google.android.material.button.MaterialButton`; (when I replaced `Button` with it, it also did not work)

animation
````kotlin
val animator = TimeAnimator()
val maxTime = 10 * 1000
animator.setTimeListener { _, totalTime, _ ->
    clipDrawable.level = (totalTime.toDouble() / maxTime * 10000).toInt()
    f (totalTime > maxTime) {
         animator.cancel()
     }
}
animator.start()
````

**Android API version:** 30

**Material Library version:** 1.4.0

**Device:** Pixel 4

**Comment by drchen** [comment]
The default Material button style has backgroundTint set to implement background color. Therefore if you need a different color than the default one, you will need either to:

1. Override  the default button style to remove the backgroundTint attribute; or
2. Call ViewCompat.setBackgroundTintList() to remove background tint programmatically.

**Comment by Azbesciak** [comment]
@drchen I did it very before I created this ticket, none of this worked. Please, read my ticket once again.

**Comment by drchen** [comment]
Ah ok. So the issue is only about clipping levels are not updated, right?

**Comment by Azbesciak** [comment]
Yes, exactly - when the background drawable is set, and it contains `clip`, this `clip` is not refreshed after the change, in contrast to the situation when you operate on the simple `Button`.

**Comment by drchen** [comment]
I think you need to get the clip drawable "after" you set the background. 

I didn't know the exact reason but it seems after you set the view background the returned clip drawable changes.

**Comment by Azbesciak** [comment]
Yeah... Thank you.
For all with the same problem, below works:
```
val drawable = prepareDrawable(R.drawable.extended_progressive_bg, R.style.ProgressingButton_Cancel) as LayerDrawable
ext_btn.background = drawable
clipDrawable = drawable.findDrawableByLayerId(R.id.clipItem)
```

I tried with stacking backgrounds to have the ripple effect from the original one, but it did not work at the first time, I did not go deeper; I suppose it is needed to add ripple by yourself.
