### ISSUE TITLE
[How to keep material.slider label visible? ] Label of slider should not be gone even while it is not interacting.

### ISSUE THREAD

**Issue by kamaal4** [material-components/material-components-android#2385]
**Material slider label.**
How the value or the label of material slider kept visible while not interaction?

**This is how I want show lable, slider design attached**
Please find slider design screen shot.

<img width="620" alt="Screenshot 2021-09-23 at 12 10 54 PM" src="https://user-images.githubusercontent.com/38549664/134464394-bd6fc30d-17ae-4840-90c5-6f83200a52af.png">
We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Hi, it's working as designed so we don't currently have a way to keep label visible when there's no interaction.

From the UX perspective I'll suggest you create a separate"fixed" text view to show the updated values, which is a general practice throughout different apps I think.
