### ISSUE TITLE
Animation transition problem when using Theme.MaterialComponents.NoActionBar

### ISSUE THREAD

**Issue by doums** [material-components/material-components-android#239]
Hi,

I use the material component theme for my layout. I followed [this](https://developer.android.com/topic/performance/vitals/launch-time#themedl) to implement a splash screen.
I have two activities. The main activity call the SignInActivity when it starts like so:

    import android.app.Activity
    import android.content.Intent
    import android.os.Bundle
    
    class MainActivity : Activity() {
    
        override fun onCreate(savedInstanceState: Bundle?) {
            setTheme(R.style.AppTheme)  //here I replace the splash theme by the normal one
            super.onCreate(savedInstanceState)
            setContentView(R.layout.activity_main)
        }
    
        override fun onStart() {
            super.onStart()
            Thread.sleep(1000)
            val token = TokenStore.getToken(this)
            if (token == null) {
                val intent = Intent(this, SignInActivity::class.java)
                startActivity(intent)
            }
        }
    }

In `AndroidManifest.xml` I have set the splash screen background through a style

    <activity android:name=".MainActivity"
        android:theme="@style/LauncherTheme">
The splash screen theme

       <style name="LauncherTheme" parent="Theme.MaterialComponents.NoActionBar">
            <item name="android:windowBackground">@drawable/launch_screen</item>
            <item name="android:colorPrimaryDark">@color/colorBackground</item>
        </style>

Ok so I have two problems:

1. even if I use `Thread.sleep(1000)` the splash screen keep showing during the sleep. And it disappears only after. I don't understand why.
2. If the code to launch the SignInActivity is present, the fade animation repeats itself one time when the SignInActivity is launched and this breaks the fade transition: I can clearly see the splash screen "flickers" and the animation is jerky.

Have you any idea about how to fix this ?

**Comment by ldjcmu** [comment]
Hi Pierre,

What happens if you use an AppCompat theme or other non-material theme?

**Comment by doums** [comment]
Ok it seems to be an emulator bug -_-, because on a real device their is no problem at all..
