### ISSUE TITLE
Cannot find Material3 themes

### ISSUE THREAD

**Issue by githubcatw** [material-components/material-components-android#2395]
**Description:** AAPT can't find the Material3 themes, resulting in this error at build time:

```
ERROR:AAPT: error: resource style/Theme.Material3.DayNight.DarkActionBar (aka com.example.test:style/Theme.Material3.DayNight.DarkActionBar) not found.
error: resource style/Theme.Material3.DayNight.DarkActionBar (aka com.example.test:style/Theme.Material3.DayNight.DarkActionBar) not found.
error: failed linking references.
```

`Theme.Material3`  also doesn't offer any autocomplete options, but `Theme.MaterialComponents` does.

I tried invalidating caches and resetting Studio.

**Expected behavior:** The app compiles fine.

**Source code:** [test.zip](https://github.com/material-components/material-components-android/files/7245298/test.zip)

**Android API version:** 31

**Material Library version:** 1.5.0-alpha03

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by githubcatw** [comment]
Update: using `Theme.Material3.DayNight.NoActionBar` let me build the app, but I still don't understand why auto completion shows no results.

**Comment by drchen** [comment]
There's no Theme.Material3.DayNight.DarkActionBar so it's WAI. (We encourage people to use "NoActionBar" themes as our guidelines point out.)

Regarding auto completion - that seems an Android Studio issue. : )
