### ISSUE TITLE
[BottomNavigationView] Could not set background to white color

### ISSUE THREAD

**Issue by jackvt93** [material-components/material-components-android#2398]
**Description:** I can set the BottomNavigationView's background to any colors except white color.

**Expected behavior:** Able to set background to white.

**My bottomNav style:**
```
    <style name="DtBottomNavigationStyle" parent="@style/Widget.MaterialComponents.BottomNavigationView">
        <item name="android:background">@color/google_white</item>
    </style>
```

**Android API version:** 30
**Material Library version:** 1.5.0-alpha03 (the problem happens so in 1.5.0-alpha04)

**Device:** Samsung s20+

**Comment by drchen** [comment]
Hi, BottomNavigationView will be applied with the elevation overlay if you set a white background. 

To acquire a white background you have several options:
1. Set BottomNavigationView's elevation to 0dp;
2. Disable the elevation overlay by setting materialThemeOverlay in the custom widget style, and in the theme overlay you set, set elevationOverlayEnabled to false; or
3. Just use a slightly tinted color like #FEFEFE

I'll close the issue as WAI and let me know if you have any further questions. Thanks!
