### ISSUE TITLE
Program type already present: android.support.v4.app.INotificationSideChannel

### ISSUE THREAD

**Issue by dheerajsinghrathore** [material-components/material-components-android#240]
Please resolve my issues

**Comment by dheerajsinghrathore** [comment]
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'


android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.smartsocityuser"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    dataBinding {
        enabled = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])
//    implementation 'com.android.support:appcompat-v7:28.0.0-alpha1'
//    implementation 'com.android.support:design:28.0.0-alpha1'
//    implementation 'com.android.support:support-v4:28.0.0-alpha1'
    implementation 'com.google.android.material:material:1.0.0'
    //noinspection GradleCompatible
//    implementation 'com.android.support:appcompat-v7:28.0.0'
//    implementation 'com.android.support:support-v4:28.0.0'
    //noinspection GradleCompatible,GradleCompatible
//    implementation 'com.android.support:design:28.0.0'
//    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    implementation 'com.intuit.sdp:sdp-android:1.0.6'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'com.github.HITGIF:TextFieldBoxes:1.4.4'
    implementation 'com.chaos.view:pinview:1.4.2'
    //noinspection GradleDependency
    implementation 'com.squareup.okhttp3:okhttp:3.4.1'
    implementation 'noman.weekcalendar:weekcalendar:1.0.6'
    //noinspection GradleDependency
    implementation 'com.squareup.okhttp3:logging-interceptor:3.4.1'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    //noinspection GradleDependency
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.github.d-max:spots-dialog:1.1@aar'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.google.firebase:firebase-core:16.0.5'
    implementation 'com.journeyapps:zxing-android-embedded:3.5.0@aar'
    implementation 'com.journeyapps:zxing-android-legacy:2.0.1@aar'
//    implementation 'com.journeyapps:zxing-android-integration:2.0.1@aar'
    implementation 'com.google.zxing:core:3.3.2'
    implementation 'com.theartofdev.edmodo:android-image-cropper:2.8.0'
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    implementation 'com.google.android.gms:play-services-vision:17.0.2'
//    implementation 'com.google.maps.android:android-maps-utils:0.4.4'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'

}

**Comment by dsn5ft** [comment]
Should be the same as #103. You can try setting android.enableJetifier=true in your gradle.properties file.

https://developer.android.com/jetpack/androidx/migrate

**Comment by ideepdave** [comment]
Added 
`android.enableJetifier=true` 
`android.useAndroidX=true`
And it worked. Thanks @dsn5ft

**Comment by Toqeer12** [comment]
Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
android {
compileSdkVersion 28
defaultConfig {
applicationId "dspl.com.myapplication"
minSdkVersion 19
targetSdkVersion 28
versionCode 1
versionName "1.0"
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}
packagingOptions {
exclude 'META-INF/atomicfu.kotlin_module'
exclude 'META-INF/proguard/androidx-annotations.pro'
}
buildTypes {
release {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
}

}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

implementation 'com.google.android.material:material:1.0.0-beta01'
implementation 'com.google.android.gms:play-services-maps:16.1.0' // After Adding this Line
implementation "androidx.lifecycle:lifecycle-extensions:$rootProject.archLifecycleVersion"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$rootProject.archLifecycleVersion"
kapt "androidx.lifecycle:lifecycle-compiler:$rootProject.archLifecycleVersion"

// Room components
implementation "androidx.room:room-runtime:$rootProject.roomVersion"
implementation "androidx.room:room-ktx:$rootProject.roomVersion"
kapt "androidx.room:room-compiler:$rootProject.roomVersion"

implementation 'com.google.code.gson:gson:2.8.5'
//https://github.com/square/okhttp
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
// https://github.com/square/retrofit
implementation 'com.squareup.retrofit2:retrofit:2.3.0'
implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
implementation 'com.squareup.retrofit2:converter-scalars:2.3.0'
// https://github.com/ReactiveX/RxAndroid
implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
implementation 'io.reactivex.rxjava2:rxjava:2.1.7'
}Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
android {
compileSdkVersion 28
defaultConfig {
applicationId "dspl.com.myapplication"
minSdkVersion 19
targetSdkVersion 28
versionCode 1
versionName "1.0"
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}
packagingOptions {
exclude 'META-INF/atomicfu.kotlin_module'
exclude 'META-INF/proguard/androidx-annotations.pro'
}
buildTypes {
release {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
}

}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

implementation 'com.google.android.material:material:1.0.0-beta01'
implementation 'com.google.android.gms:play-services-maps:16.1.0' // After Adding this Line
implementation "androidx.lifecycle:lifecycle-extensions:$rootProject.archLifecycleVersion"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$rootProject.archLifecycleVersion"
kapt "androidx.lifecycle:lifecycle-compiler:$rootProject.archLifecycleVersion"

// Room components
implementation "androidx.room:room-runtime:$rootProject.roomVersion"
implementation "androidx.room:room-ktx:$rootProject.roomVersion"
kapt "androidx.room:room-compiler:$rootProject.roomVersion"

implementation 'com.google.code.gson:gson:2.8.5'
//https://github.com/square/okhttp
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
// https://github.com/square/retrofit
implementation 'com.squareup.retrofit2:retrofit:2.3.0'
implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
implementation 'com.squareup.retrofit2:converter-scalars:2.3.0'
// https://github.com/ReactiveX/RxAndroid
implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
implementation 'io.reactivex.rxjava2:rxjava:2.1.7'
}

**Comment by Toqeer12** [comment]
> Added
> `android.enableJetifier=true`
> `android.useAndroidX=true`
> And it worked. Thanks @dsn5ft

Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
android {
compileSdkVersion 28
defaultConfig {
applicationId "dspl.com.myapplication"
minSdkVersion 19
targetSdkVersion 28
versionCode 1
versionName "1.0"
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}
packagingOptions {
exclude 'META-INF/atomicfu.kotlin_module'
exclude 'META-INF/proguard/androidx-annotations.pro'
}
buildTypes {
release {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
}

}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

implementation 'com.google.android.material:material:1.0.0-beta01'
implementation 'com.google.android.gms:play-services-maps:16.1.0' // After Adding this Line
implementation "androidx.lifecycle:lifecycle-extensions:$rootProject.archLifecycleVersion"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$rootProject.archLifecycleVersion"
kapt "androidx.lifecycle:lifecycle-compiler:$rootProject.archLifecycleVersion"

// Room components
implementation "androidx.room:room-runtime:$rootProject.roomVersion"
implementation "androidx.room:room-ktx:$rootProject.roomVersion"
kapt "androidx.room:room-compiler:$rootProject.roomVersion"

implementation 'com.google.code.gson:gson:2.8.5'
//https://github.com/square/okhttp
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
// https://github.com/square/retrofit
implementation 'com.squareup.retrofit2:retrofit:2.3.0'
implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
implementation 'com.squareup.retrofit2:converter-scalars:2.3.0'
// https://github.com/ReactiveX/RxAndroid
implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
implementation 'io.reactivex.rxjava2:rxjava:2.1.7'
}

**Comment by Toqeer12** [comment]
> Should be the same as #103. You can try setting android.enableJetifier=true in your gradle.properties file.
> 
> https://developer.android.com/jetpack/androidx/migrate

**Hye  I have same issue here is my gradle please help me where i am doing wrong i am stuck from 3 days**
**Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
apply plugin: 'com.android.application'**

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
android {
compileSdkVersion 28
defaultConfig {
applicationId "dspl.com.myapplication"
minSdkVersion 19
targetSdkVersion 28
versionCode 1
versionName "1.0"
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}
packagingOptions {
exclude 'META-INF/atomicfu.kotlin_module'
exclude 'META-INF/proguard/androidx-annotations.pro'
}
buildTypes {
release {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
}

}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

implementation 'com.google.android.material:material:1.0.0-beta01'
### **implementation 'com.google.android.gms:play-services-maps:16.1.0' // After Adding this Line**
implementation "androidx.lifecycle:lifecycle-extensions:$rootProject.archLifecycleVersion"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$rootProject.archLifecycleVersion"
kapt "androidx.lifecycle:lifecycle-compiler:$rootProject.archLifecycleVersion"

// Room components
implementation "androidx.room:room-runtime:$rootProject.roomVersion"
implementation "androidx.room:room-ktx:$rootProject.roomVersion"
kapt "androidx.room:room-compiler:$rootProject.roomVersion"

implementation 'com.google.code.gson:gson:2.8.5'
//https://github.com/square/okhttp
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
// https://github.com/square/retrofit
implementation 'com.squareup.retrofit2:retrofit:2.3.0'
implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
implementation 'com.squareup.retrofit2:converter-scalars:2.3.0'
// https://github.com/ReactiveX/RxAndroid
implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
implementation 'io.reactivex.rxjava2:rxjava:2.1.7'
}

**Comment by Yathousen** [comment]
I recently made an article to address this AndroidX situation, you may find it useful.

https://medium.com/@yathousen/the-day-google-decided-to-shake-the-react-native-community-4ba5cdd33388

**Comment by hamzabintariq123** [comment]
Were you guys able to solve it .. un fortunately i was not. 
even by adding these lines :

android.enableJetifier=true
android.useAndroidX=true

i even posted a question on stack-overflow can anyone look back .

https://stackoverflow.com/questions/57001516/how-to-fix-execution-failed-for-task-app-guesttransformclasseswithjarmerging
