### ISSUE TITLE
What is Material 3?

### ISSUE THREAD

**Issue by hansemannn** [material-components/material-components-android#2402]
Please excuse me for taking up space in the `Issues` here, but I am very interested to know more about the `Material 3` epic that's currently being developed. Are there any examples or designs that should the difference to the current Material design? Or is Material 3 = Material You (the Android 12+ UI concept)? Thanks in advance!

**Comment by OxygenCobalt** [comment]
From what I've been able to gather, Material 3 is kind of like "Material 2 + Material You" with some extra tweaks here and there.

Material 2 was the minor refresh that occurred around Android Oreo, it:
- Phased out colorful AppBars in favor of neutral AppBars.
- Partially phased out all-caps text in buttons and other UI components
- Encouraged the use of dividers in certain places

Material 3 seems to do the following:
- Applies Material You support
- Makes elevation overlays colored
- Extends elevation overlays to the light theme as well
- Favors color differences and dividers over elevation shadows
- Deprecates some color roles [ex. `colorPrimaryDark`] and adds new color roles [ex. `colorPrimaryContainer`]
- Prefers lower-contrast/"pastel" coloring
- Phases out all-caps text everywhere
- Discourages circles in favor of squircles and pill shapes
- [Maybe] Adds translucency in some places?
- [Maybe] Adds shape animations? The Android 12 phone app seems to show circles expanding into squircles when pressed, so it's not out of the question.

This is mostly observations/speculation from the alpha builds. The actual devs will probably have a better explanation than I do.

**Comment by dsn5ft** [comment]
@OxygenCobalt that is a solid summary. The term "Material You" is more focused on the personalization features coming in Android 12 (e.g., dynamic wallpaper color), while "Material 3" is more for the update to the design system as a whole. E.g., the FAB's shape has been changed from a circle to a rounded rectangle - changes like this to the library's components and themes are not tied to Android 12 and are supported on older API levels.

Some more detail can be found in the [1.5.0-alpha03](https://github.com/material-components/material-components-android/releases/tag/1.5.0-alpha03) and [1.5.0-alpha04](https://github.com/material-components/material-components-android/releases/tag/1.5.0-alpha04) release notes, and in the [updated developer documentation](https://github.com/material-components/material-components-android/tree/master/docs).

Additionally, there will be a higher level summary and more detail from the design side coming soon, so stay tuned.
