### ISSUE TITLE
[MaterialAlertDialogBuilder] Wrong Dialog bounds after orientation change

### ISSUE THREAD

**Issue by thinhlai** [material-components/material-components-android#2408]
**Description:** 
Dialog bounds is not correct after orientation change without activity recreation (activity has configChanges=orientation attribute)

![screenshot-1633432645336](https://user-images.githubusercontent.com/46520128/136013020-3b6dd83c-1908-4c41-a715-a025d318d8f8.png)
![screenshot-1633429718933](https://user-images.githubusercontent.com/46520128/136010287-fe7526f0-a4ae-4149-a5ef-0d1ffe157549.png)

**How to reproduce it**

1 . Start app at portrait -> then click button to show alert dialog.
2. Then rotate device to landscape
3. Press physical home button to exit app
4. Then rotate device again to portrait
5. Press physical task manager button
6. Select and resume app on task manager
7. The issue appears

**Expected behavior:** Dialog bounds is showed correctly after orientation change

**Source code:** 
[TestDialog.zip](https://github.com/material-components/material-components-android/files/7285271/TestDialog.zip)

**Android API version:** Any Android API versions

**Material Library version:** 1.5.0-alpha04

**Device:** Any devices

**Comment by drchen** [comment]
Hi, I think this is a bug of Android dialog implementation and the recommended solution will be using DialogFragment instead. : )

I checked with our demo app and replace the implementation with AppCompatDialogFragment did fix the issue. : )

**Comment by thinhlai** [comment]
Hi @drchen Thanks for your support.

I changed to AppCompatDialogFragment to show dialog in my demo but it's not working on my side (I attached the source code). Could you please send me your demo source code to double check ?

**Source code:**

[TestDialog_ AppCompatDialogFragment.zip](https://github.com/material-components/material-components-android/files/7290642/TestDialog_.AppCompatDialogFragment.zip)
