### ISSUE TITLE
[Range Slider] label not transparent

### ISSUE THREAD

**Issue by yeo-da** [material-components/material-components-android#2409]
Hi.
I need help your.
If you look at the last image, You will see a white line like a border.
I want to make that line transparent.

style.xml
![image](https://user-images.githubusercontent.com/69666433/136011218-8b7c95d1-5a99-4221-b313-0fdac960c659.png)

xml
![image](https://user-images.githubusercontent.com/69666433/136011382-7658c537-13b0-4543-9871-d07d2cba2256.png)

not transparent.. white line like a border
![image](https://user-images.githubusercontent.com/69666433/136011585-cd7e626d-07a7-44bd-a394-de8035c95e0a.png)

**Comment by drchen** [comment]
Hi, the tooltip drawable has a default stroke color using ?attr/colorSurface. 

Unfortunately I don't think we have a good way to workaround this behavior for now. 
I'll try to push a fix so that the stroke color can be customized or at least be consistent with the background tint.

**Comment by drchen** [comment]
Awesome! Happy to hear that.  : )
