### ISSUE TITLE
BottomAppBar Has a high shadow in my application view

### ISSUE THREAD

**Issue by gitzsj** [material-components/material-components-android#241]
This is my BottomAppBar
![qq_pic_merged_1544206282345](https://user-images.githubusercontent.com/20274957/49665072-ae37e980-fa8e-11e8-8fcc-1b5513db3c7a.jpg)
This is Material Components's BottomAppBar
![qq_pic_merged_1544206293658](https://user-images.githubusercontent.com/20274957/49665156-fb1bc000-fa8e-11e8-91b6-d272eeca9a0a.jpg)
My App's BottomAppBar shadow is obviously higher!!!!

This is my layout code

> 

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity">
        <com.google.android.material.bottomappbar.BottomAppBar
            android:id="@+id/bar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom"
            app:hideOnScroll="true">
        </com.google.android.material.bottomappbar.BottomAppBar>
        <com.google.android.material.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_anchor="@id/bar">
        </com.google.android.material.floatingactionbutton.FloatingActionButton>
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
> 
This is my style
> 
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
> 
Does the question come from Style or layout?
Thanks to much!!!!
My project is migrated from appcompat to androidX

**Comment by cketcham** [comment]
I think the shadow intensity is fixed in our catalog because we've reduced it in the component and included a fix for that in our library. You should get the same fix in your library with 1.1.0-alpha02 which will be released soon.
