### ISSUE TITLE
[TabLatout] Ignoring tabGravity fill when tab mode is auto

### ISSUE THREAD

**Issue by lencetanaskoska** [material-components/material-components-android#2414]
**Description:** I am setting tabMode to auto and tabGravity to fill but the TabLayout seams to ignore the tabGravity when the tabs fit the screen and they are centered instead of spreaded.
![Screenshot 2021-10-06 at 13 10 14](https://user-images.githubusercontent.com/17854276/136193102-b010fc13-7990-4777-8380-5aae8f93a083.png)

**Expected behavior:** 
When the tabs fit the screen it is supposed to look like fixed mode with fill gravity, but the library is ignoring the tabGravity property
![Screenshot 2021-10-06 at 13 06 29](https://user-images.githubusercontent.com/17854276/136191873-6498b57c-86c1-42ba-88c9-e215cb5fc4a7.png)

**Source code:**
<com.google.android.material.tabs.TabLayout
                                android:id="@+id/examples_assets_tabs"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:background="?attr/colorB"
                                app:tabPaddingStart="@dimen/margin_16"
                                app:tabPaddingEnd="@dimen/margin_16"
                                app:tabMinWidth="90dp"
                                app:tabIndicatorColor="?attr/colorD"
                                app:tabSelectedTextColor="?attr/colorD"
                                app:tabIndicatorHeight="3dp"
                                app:tabMode="auto"
                                app:tabGravity="fill"
                                app:tabContentStart="0dp"
                                app:tabTextAppearance="@style/TabBar"/>

**Android API version:** API 30, API 28,

**Material Library version:**  Last stable version 1.4.0

**Device:** Android Emulator API30, Samsung Tab 3  API 28

**Comment by drchen** [comment]
It's duplicate to #650.
