### ISSUE TITLE
Typography Theming is only applicable to English-like languages.

### ISSUE THREAD

**Issue by Sourav-21** [material-components/material-components-android#242]
## Typography Theming is only applicable to English-like languages.
Here is example of new Material Typography Theming for **English text**.
![Screenshot of Typography Theming](https://i.ibb.co/qkvMpDg/Screenshot-20181210-214854.png)

Now I am appling same styles to **Bengali Text** and here is the result-
![Bengali Text Example](https://i.ibb.co/cFk75J7/Screenshot-20181210-215414.png)
TextStyle for **Headline 6**, **Subtitle 2** and **Button** should be ***Bold*** or ***Medium*** but here it is just Normal. Because Roboto Medium font isn't available for other languages.

Here is the example of expected result-
![Expected result](https://i.ibb.co/DRwXr4y/Screenshot-20181210-220010.png)

**Comment by leticiarossi** [comment]
I filled this: http://issuetracker.google.com/issues/120852969 to keep track of this issue and for future communication.
