### ISSUE TITLE
[AppBarLayout] The background color cannot be set to #121212

### ISSUE THREAD

**Issue by onlymash** [material-components/material-components-android#2421]
**Description:** 

As shown in the picture, the wrong color is displayed when the color value is #121212, and the color is displayed correctly when #121211

edit: After comparison, it is not a specific color problem, but the night theme background color of ApppBarLayout cannot be the same as the android:colorBackground of AppTheme

**Expected behavior:** 

![image](https://user-images.githubusercontent.com/5838634/136679147-63746bd0-21cd-47bf-b335-a511dc9e06ec.png)

![image](https://user-images.githubusercontent.com/5838634/136679105-474bb3ec-a397-4473-99dd-6790858ad458.png)

**Source code:** 
```
<com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#121212">
</com.google.android.material.appbar.AppBarLayout>
```
**Android API version:** 
31

**Material Library version:** 
1.5.0-alpha04

**Comment by drchen** [comment]
Hi, thanks for the report. Unfortunately that's an intended behavior - when we detect the background color is colorSurface, the elevation overlay will be applied on your background. To override this you can either set ?attr/elevationOverlayEnabled to false in your context theme, or set the view elevation to 0.
