### ISSUE TITLE
[TimePicker] Support different styling for the Ok/Cancel buttons #2091

### ISSUE THREAD

**Issue by giovanniPolatoO** [material-components/material-components-android#2445]
The DatePicker allows you to set different styles for the two buttons "OK" and "Cancel". The TimePicker no, how can it be done? 
Make a layout similar to this for the two buttons.
![Screenshot_20211026-161456](https://user-images.githubusercontent.com/39946580/139023183-1263c7d5-b45a-4067-a6dc-ded9652c61e8.png)

**Comment by drchen** [comment]
Hi, so you can override ?attr/borderlessButtonStyle in a theme overlay extends from ThemeOverlay.Material3.MaterialTimePicker and set it as your ?attr/materialTimePickerTheme.

Hope that helps you. : )
