### ISSUE TITLE
MaterialButton's background invisible

### ISSUE THREAD

**Issue by IlimbekNarmatov** [material-components/material-components-android#2450]
**Description:** Material Button's background is invisible
[https://drive.google.com/file/d/132eyoFJupZ5YX4it3SDUz76wtSImp1Ko/view?usp=sharing](url)
It becomes visible if I manually set theme to app's theme
**Expected behavior:**
[https://drive.google.com/file/d/1ckBzMjzXUi1ATr02WrfPbpZKnspswqpd/view?usp=sharing](url)

**Source code:**
`    <com.google.android.material.button.MaterialButton
        android:id="@+id/btn_update"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginHorizontal="20dp"
        android:layout_marginTop="24dp"
        android:text="Lorem ipsum"
        app:layout_constraintTop_toBottomOf="@id/tv_description" />
`

App theme:
`    <style name="Theme.Ayugrand" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        
        <item name="colorPrimary">@color/dark_blue</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorOnPrimary">@color/white</item>
        <item name="colorOnSurface">@color/gray</item>
        
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        <item name="materialButtonStyle">
            @style/Widget.MaterialComponents.Button.NoInsets
        </item>
        <item name="materialButtonOutlinedStyle">
            @style/Widget.MaterialComponents.Button.OutlinedButton.NoInsets
        </item>
`
Button style:
`    <style name="Widget.MaterialComponents.Button.NoInsets">
        <item name="cornerRadius">12dp</item>
        <item name="android:insetBottom">0dp</item>
        <item name="android:insetTop">0dp</item>
    </style>
`

**Android API version:** API 21+

**Material Library version:** com.google.android.material:material:1.4.0

**Device:**Huawei p30 lite

**Comment by drchen** [comment]
The default background of @style/Widget.MaterialComponents.Button is @empty. You will need to set the android:background in your custom style to have different colors than transparent.
