### ISSUE TITLE
[Docs] `MaterialDivider` links go to a 404 page

### ISSUE THREAD

**Issue by zmdominguez** [material-components/material-components-android#2451]
**Description:** 
The class definition links in the [`MaterialDivider` Android implementation page](https://material.io/components/dividers/android) lead to a 404 page on developer.android.com

`MaterialDivider` link - https://developer.android.com/reference/com/google/android/material/divider/MaterialDivider
<img width="414" alt="Screen Shot 2021-10-31 at 18 53 13" src="https://user-images.githubusercontent.com/410969/139573630-d16f74c7-2fa6-4b2f-9805-ece4994d7502.png">

`MaterialDividerItemDecoration` link - https://developer.android.com/reference/com/google/android/material/divider/MaterialDividerItemDecoration

<img width="411" alt="Screen Shot 2021-10-31 at 18 53 31" src="https://user-images.githubusercontent.com/410969/139573637-ce13bba2-d272-49e2-813d-37cf76af91ca.png">

**Expected behavior:** 
Links in documentation should go to a valid page

**Comment by leticiarossi** [comment]
Thanks for reporting! We removed the broken links in https://github.com/material-components/material-components-android/commit/3b6c804f6731c88166f14454c47e83e61e4a0cf5 (it's not yet reflected in [material.io](material.io)).
We should have Divider docs available in the developer.android.com website in our next stable release, then we can add the proper links back to the doc
