### ISSUE TITLE
[TextInputLayout] Hint does not fit in the OutlinedBox when cornerRadius is defined

### ISSUE THREAD

**Issue by ViktorScaletta** [material-components/material-components-android#2453]
**Description:** You can see it in the screenshot

**Android API version:** Doesn't matter

**Material Library version:** 1.4.0

**Screenshot:**
![Screenshot_5](https://user-images.githubusercontent.com/37725444/139792464-26ec84d4-aed9-4c5e-ba78-c0e4221ebf2a.png)

**Comment by drchen** [comment]
Hi, this has been fixed in the latest library version. Feel free to reopen it if this still happens with the latest library version.
