### ISSUE TITLE
[Popup] elevationOverlayEnabled doesn't apply to Popups

### ISSUE THREAD

**Issue by claytongreen** [material-components/material-components-android#2456]
**Description:** Using the new Material3 theme, I've disabled elevation overlay and it seems to apply to everything _except_ Popups. The "solution" I have now is setting `elevationOverlayColor` to transparent.

**Expected behavior:**
I expect disabling elevation overlay would apply to popups (Maybe I'm mistaken).

App themed with:
`<item name="elevationOverlayEnabled">true</item>`
Notice the slight blue tinting on the toolbar and the popup.
![enabled](https://user-images.githubusercontent.com/3336370/139922176-e7489296-dbd1-4ffd-bb6e-afa5e26b0746.png)

App themed with:
`<item name="elevationOverlayEnabled">false</item>`
Notice the toolbar is no longer tinted but the popup still is.
![disabled](https://user-images.githubusercontent.com/3336370/139922303-2910453b-a40e-4d86-a38b-4598413a4c16.png)

App themed with:
`<item name="elevationOverlayEnabled">false</item>` and
`<item name="elevationOverlayColor">@color/transparent</item>`
Now both the toolbar and the popup don't have a _visible_ elevation overlay.
![disabled+transparent](https://user-images.githubusercontent.com/3336370/139922390-21da0462-d97d-498c-9170-9e6c81836aa0.png)

**Android API version:** 12

**Material Library version:** 1.5.0-alpha05

**Device:** Emulator

**Comment by drchen** [comment]
Hi, due to the limitation of the current implementation, there's no reliable way to disable menu's elevation overlay by setting the flag in the theme. As an alternative you can override ?attr/popupMenuBackground instead. Hope this works for your case!
