### ISSUE TITLE
[blog] typo in URL on `Migrating to Material Design 3` page

### ISSUE THREAD

**Issue by ElectricMagic** [material-components/material-components-android#2458]
**Description:** At the bottom of the page <https://material.io/blog/migrating-material-3>, the `Start building with Material You` link is incorrect. It's currently <https://material.io/blog/start-building-with-Material-You> and should be <https://material.io/blog/start-building-with-material-you>

**Comment by dsn5ft** [comment]
@ElectricMagic thanks! Filed an internal bug to the material.io team.
