### ISSUE TITLE
[CollapsingToolbarLayout] ignores expandedTitleMarginEnd when both collapsed and expanded text sizes are the same

### ISSUE THREAD

**Issue by katrinrudisch** [material-components/material-components-android#2459]
**Description:** The `expandedTitleMarginEnd` is not applied when the expanded and collapsed title textSize is the same.
Even if the textSize only differs by 0.001sp it works and the marginEnd is correctly applied.

**Expected behavior:** `CollapsingToolbarLayout` is correctly applying the `expandedTitleMarginEnd` even if the expanded and collapsed title textSize is the same.

![collapsingToolbar_expanded-collapsed-same-textSize](https://user-images.githubusercontent.com/7893128/140481355-23d259de-d1ed-4c10-90ea-8b4b2c2b134b.png) ![collapsingToolbar_expanded-collapsed-different-textSize](https://user-images.githubusercontent.com/7893128/140481384-1ad1e0e9-aef1-4f32-b717-bde122207c21.png)

**Source code:** 

Layout file:
```
<com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/collapsingToolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:collapsedTitleTextAppearance="@style/TextAppearance.Toolbar.Title"
            app:expandedTitleMarginEnd="100dp"
            app:expandedTitleMarginTop="?attr/actionBarSize"
            app:expandedTitleTextAppearance="@style/TextAppearance.AppBar.Title.Expanded"
            app:layout_scrollFlags="scroll|exitUntilCollapsed|snap"
            app:maxLines="2"
            app:title="This is a very long title to test the collapsing toolbar">

            <com.google.android.material.appbar.MaterialToolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:layout_collapseMode="pin" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>

 </com.google.android.material.appbar.AppBarLayout>
```
 
 Expanded and collapsed textAppearance:
```
 <style name="TextAppearance.AppBar.Title.Expanded" parent="TextAppearance.MaterialComponents.Headline5">
      <item name="android:textSize">16sp</item>
      <item name="android:textColor">@color/white</item>
  </style>
```
```
  <style name="TextAppearance.Toolbar.Title" parent="TextAppearance.MaterialComponents.Headline5">
      <item name="android:textSize">16sp</item>
      <item name="android:textColor">@color/white</item>
  </style>
```

**Android API version:** API 30

**Material Library version:** 1.4.0

**Device:** Emulator Pixel XL API 30

**Sampe project:**
[CollapsingToolbarIssue.zip](https://github.com/material-components/material-components-android/files/7481700/CollapsingToolbarIssue.zip)

**Comment by Back4fire** [comment]
It seems this fix cannot work. The bug still exists in all versions of 1.6.0 and 1.7.0-alpha01.

**Comment by drchen** [comment]
Do you have a screenshot/screen recording? The settings of your CollapsingToolbarLayout will also be helpful.

**Comment by Back4fire** [comment]
The sample project attached by the creator of this issue is a good test case. But please note that the "TextAppearance.AppBar.Title.Expanded" and "TextAppearance.Toolbar.Title" are not the same in the source code. The sample project actually is a workaround. If you change the two text sizes to the same, you will find the issue.

I have also reported this issue in another thread [https://github.com/material-components/material-components-android/issues/2240](url)

**Comment by drchen** [comment]
I managed to reproduce it. Besides text size, the type face needs to be the same as well to reproduce the issue. Will work on a fix.
