### ISSUE TITLE
[PreferenceFragmentCompat] doesn't inflates using the M3 theme

### ISSUE THREAD

**Issue by rares45** [material-components/material-components-android#2460]
**Description:** PreferenceFragmentCompat doesn't use the m3 theme (switches, dialogues, etc..). 
Note that the dialogues are made by the fragment and I cannot use MaterialAlertDialogBuilder.

**Expected behaviour:** 
Right now the fragment widgets and dialogs look like this:
![Screenshot_20211105-113032~2](https://user-images.githubusercontent.com/42469755/140489365-0eae9a46-2560-411b-b959-d0266896df7a.png)
![Screenshot_20211105-112851~2](https://user-images.githubusercontent.com/42469755/140489371-314eebd1-9b55-4d9c-a45a-639807931941.png)

And I expect them to look more like this:
![image](https://user-images.githubusercontent.com/42469755/140489824-1ddc57ed-b39f-4d00-bb63-4005e560f9e4.png)
![image](https://user-images.githubusercontent.com/42469755/140489996-959e164f-e0eb-4e96-9dfc-aa1891f0c8b8.png)

**Source code:** 
App theme:
```xml
<style name="AppTheme" parent="Theme.Material3.DayNight">
    <item name="android:statusBarColor">#3E000000</item>
</style>
```
The fragment code looks like this:
```java
public static class SettingsFragment extends PreferenceFragmentCompat {
        @Override
        public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
            setPreferencesFromResource(R.xml.root_preferences, rootKey);
```

**Android API version:** 31

**Material Library version:** 1.5.0-alpha05

**Device:** Emulator Pixel 5 API 31

**Comment by drchen** [comment]
Hi the screenshots you attached do look like Material themes. (The ones you expected are not.)
 
Please check https://m3.material.io/ for the expected look and feel of Material 3.

**Comment by rares45** [comment]
@drchen Hi. I'm sorry but the expected ones are taken from the latest Google Apps, and that dialogue is a system one on the Pixel 6.

The switches I attached look exactly like the switches from https://m3.material.io/
![image](https://lh3.googleusercontent.com/jW2Qbm_nwdr7y6MxH6hs_HzibbQD1N_mO931aVJrkUUoOeToDHWlfRFs_PN-grj_D3HbOxxCFP-UiF6MqWKUTTPMULb6HPXMd5jkOsqx3nAgv_FfyQ=w1064-v0) (bottom right corner)

And here is a dialogue picture from the website:
![image](https://lh3.googleusercontent.com/HujrRgTyWZJ1d9NmQ3dCdkWwLYUMOi8dJxGVY1yCWX-5bDKTHDbDQmLK60L4auvtemWY81VTFQ8MpT4B6e-7iM4208n3zPBa77_e5651oqaI=s0)

Switches from the settings apps on Android 12:
![image](https://user-images.githubusercontent.com/42469755/140531031-0bf3fcb2-10af-4b1d-a467-85d61c5bdd01.png)

And this is a dialog created using the MaterialAlertDialogBuilder:
![image](https://user-images.githubusercontent.com/42469755/140532086-4afae707-203f-44c9-b3b9-73de3b2951d5.png)

So why the pictures I attached aren't Material 3 themes?

**Comment by drchen** [comment]
So they are actually two separate cases - 

1. For dialogs, since PreferenceFragmentCompat is part of AndroidX instead of Material library, it can't use MaterialAlertDialogBuilder but can only show AndroidX alert dialogs with Material themes. The nice round corners you see is only supported by MaterialAlertDialogBuilder. 

2. For switches - we don't really have a final UX design yet. And I believe system apps are currently using customized track drawables. (The color combination being used is correct, though.)

Hope that answers your questions!

**Comment by rares45** [comment]
Yes, it answers my questions. Thank you.

**Comment by jacklroberts** [comment]
Hi if it's any use, I've been having this issue with dialogs in preferences and whilst it's not perfect it's close to the android 12 dialog design with Dynamic Color


    

    <style name="AppTheme.Light" parent="Theme.Material3.DynamicColors.Light">

        <item name="alertDialogTheme">@style/Dialog.Light</item>

    </style>

    <style name="Dialog.Light" parent="ThemeOverlay.Material3.MaterialAlertDialog">
        <item name="android:dialogCornerRadius">@dimen/m3_alert_dialog_corner_size</item>
        <item name="android:colorBackground">?attr/colorSurface</item>
        <item name="android:layout">@layout/m3_alert_dialog</item>
        <item name="android:windowElevation">@dimen/m3_alert_dialog_elevation</item>
        <item name="elevationOverlayEnabled">true</item>
    </style>

    

    <style name="AppTheme.Dark" parent="Theme.Material3.DynamicColors.Dark">

        <item name="alertDialogTheme">@style/Dialog.Dark</item>

    </style>

    <style name="Dialog.Dark" parent="ThemeOverlay.Material3.MaterialAlertDialog">
        <item name="android:dialogCornerRadius">@dimen/m3_alert_dialog_corner_size</item>
        <item name="android:colorBackground">?attr/colorSurface</item>
        <item name="android:layout">@layout/m3_alert_dialog</item>
        <item name="android:windowElevation">@dimen/m3_alert_dialog_elevation</item>
        <item name="elevationOverlayEnabled">true</item>
    </style>


Hope it's helpful to you, it's not a 100% perfect in regards to color elevation, but it's got the layout, padding, buttons and corner radius of the Material3 dialogs
