### ISSUE TITLE
[MaterialAlertDialog] can't set full-width buttons

### ISSUE THREAD

**Issue by oheyadam** [material-components/material-components-android#2461]
**Description:** 

According to the [docs](https://material.io/components/dialogs/android#using-dialogs), you can use `R.style.ThemeOverlay_MaterialComponents_MaterialAlertDialog_FullWidthButtons` to use full width buttons, but this theme overlay can't be resolved

**Expected behavior:** being able to resolve this theme overlay

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** 30

**Material Library version:** 1.4.0

**Device:** IDE, never got to run

**Comment by drchen** [comment]
Hi thanks for the report. We did miss the implementation of the theme overlays. However with Material 3 being released soon, we are stop supporting the old Material styles.

If you need ThemeOverlay_MaterialComponents_MaterialAlertDialog_FullWidthButtons before you can adopt Material 3, you may need to implement it on your own, by:

1. Declare a full width button style, like:
```
  <style name="Button.FullWidth" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
    <item name="android:layout_width">0dp</item>
    <item name="android:layout_weight">1</item>
    <item name="android:maxWidth">@null</item>
  </style>
```
2. Declare the theme overlay with full-width button styles:
```
  <style name="ThemeOverlay.MaterialComponents.MaterialAlertDialog.FullWidthButtons">
    <item name="materialAlertDialogButtonSpacerVisibility">2</item>
    <item name="buttonBarPositiveButtonStyle">@style/Button.FullWidth</item>
    <item name="buttonBarNegativeButtonStyle">@style/Button.FullWidth</item>
    <item name="buttonBarNeutralButtonStyle">@style/Widget.Button.FullWidth</item>
  </style>
```

Hope this helps!

**Comment by oheyadam** [comment]
Hey, thanks a lot for the quick response. Unfortunately, `materialAlertDialogButtonSpacerVisibility` doesn't seem to be publicly exposed either

**Comment by oheyadam** [comment]
So I found [this](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/res/layout/mtrl_alert_dialog_actions.xml) layout for the dialog buttons. It's included in the material alert dialog [layout](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/res/layout/mtrl_alert_dialog.xml#L94), so I figured I could do this: `requireDialog().findViewById<Space>(R.id.spacer)?.visibility = GONE`, but it didn't work either. Any ideas?

**Comment by drchen** [comment]
Hi, it looks like materialAlertDialogButtonSpacerVisibility is a public attribute you can use:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/res-public/values/public.xml#L52

Can you double check?

**Comment by oheyadam** [comment]
Seems to only be part of the version [1.5 alphas](https://github.com/material-components/material-components-android/commit/cd9e6204d88ae07111a9a0eff0714241c91a2910) unfortunately. [Here's](https://github.com/material-components/material-components-android/blob/release-1.4/lib/java/com/google/android/material/dialog/res-public/values/public.xml) the same file under the release-1.4 branch

**Comment by drchen** [comment]
Ah. Ok.

Regarding findViewById(), it should work. Maybe the method is called too early? The dialog needs to be shown before you can grab the view.

**Comment by oheyadam** [comment]
Yea maybe it was too early? I was doing it in `onViewCreated()` because I was also calling `setView` on the dialog creator. Ended up having to adapt [ButtonBarLayout](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:appcompat/appcompat/src/main/java/androidx/appcompat/widget/ButtonBarLayout.java;l=40?q=ButtonBarLayout&sq=) because we also wanted to be the buttons to be centered when they're laid out vertically anyway. Thanks a lot for your help, I'll close this
