### ISSUE TITLE
[BadgeDrawable] Cannot set locale to badgedrawable. Taking application locale for default translation of number

### ISSUE THREAD

**Issue by hiteshsarsava** [material-components/material-components-android#2465]
**Description:** When change the language of the App. The number format also gets translated into that selected language. I have issue where i want to keep the language of app in Arabic but number on badgeDrawable want to in English. As in below snippet, the `NumberFormat.getInstance().format(getNumber()) `taking the default locale. Developer can not set there any locale.

**Expected behavior:** Expected behavior is keep in english as that are numbers

**Source code:** 
```
@NonNull
  private String getBadgeText() {
    // If number exceeds max count, show badgeMaxCount+ instead of the number.
    if (getNumber() <= maxBadgeNumber) {
      return NumberFormat.getInstance().format(getNumber());
    } else {
      Context context = contextRef.get();
      if (context == null) {
        return "";
      }

      return context.getString(
          R.string.mtrl_exceed_max_badge_number_suffix,
          maxBadgeNumber,
          DEFAULT_EXCEED_MAX_BADGE_NUMBER_SUFFIX);
    }
  }
```

**Android API version:** Android API 29

**Material Library version:** com.google.android.material:material:1.5.0-alpha05

**Device:** Pixel

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by hiteshsarsava** [comment]
![Screenshot_20211202-130710](https://user-images.githubusercontent.com/16486943/144378549-c7041fb8-f0fb-4175-a181-52c749d3a8b4.png)

@drchen As you can see the above screenshot. I want badge count in English Number. But when I change the language of my app in arabic it is automatically changes the number in arabic language number. How to restrict that ? As there is no option to set locale in badgeDrawable.

**Comment by drchen** [comment]
Gotcha. Thanks. I'll push a fix.

**Comment by hiteshsarsava** [comment]
@drchen Thanks for the solve issue.
