### ISSUE TITLE
[Material3 Theme] Cannot find Material3 themes

### ISSUE THREAD

**Issue by rezadarvishian** [material-components/material-components-android#2475]
Android studio can't find Material3 themes when using last version of library
note : also doesn't offer any autocomplete like Theme.Material3
```
 <style name="AppTheme" parent="Theme.Material3.Dark.NoActionBar">
     
 </style>
```

lib version = 1.5.0-beta01

target sdk = 31
min sdk = 23
android studio : 2020.3.1

**Comment by cyb3rko** [comment]
Have you tried to "Invalidate Caches and Restart" Android Studio?
