### ISSUE TITLE
[CalendarDatePicker] how to include calendarDatePicker using appTheme="Theme.AppCompat.NoActionBar"

### ISSUE THREAD

**Issue by kondlada** [material-components/material-components-android#2476]
**Description:** We are not planning to migrate AppTheme from AppCompat to MaterialComponents Theme but we are ok to inherit same theme in AppCompat and use "MaterialDatePicker" . When I run the application calendar cell text is not aligned to center.

**Expected behavior:** please find attached 
![calendarViewError](https://user-images.githubusercontent.com/2006768/143201277-7a1909d1-64ac-4901-9156-51cbaf48e7de.png)
where cell text is not in center and extra additional ui distortion.

**Source code:** I have used below style as my apptheme
    <style name="Theme.App" parent="@style/Theme.AppCompat.NoActionBar">
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorOnPrimary">@color/white</item>
        
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        <item name="materialCalendarTheme">@style/materialcalendarcomponent</item>
    </style>

and invoked material calendarDatepicker to select range of dates.

Please find attached sourceCode:
[DateRange.zip](https://github.com/material-components/material-components-android/files/7593959/DateRange.zip)

**Android API version:** 26

**Material Library version:** 1.4.0
**Device:** Nexus 6P

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Can you clean-up your sample source code for a little bit? It looks like a WIP to me.

Despite that, it looks like your application theme is still using AppCompat themes, and this can cause problem if you try to open a date picker with Material themes.

**Comment by kondlada** [comment]
Hi drchen,
                    In our application we declare AppCompat themes in manifiest but in that themes I am extending material components themes in styles.xml to use material calendar range widget. 
We don't want to declare or completely migrate to material theme but instead we would like to use this widget.

Hope this explanation will help you understand the problem. 

Thanks
Karthik K

**Comment by drchen** [comment]
Hi, MaterialDatePicker is supposed to work with Material themes. Unfortunately we don't have the full support of it with non-Material themes. I'll suggest you to play with the style to tweak some settings for a little bit and see if it helps.
