### ISSUE TITLE
[NavigationRail] Vertical scrolling support for the Rail

### ISSUE THREAD

**Issue by SupasinTatiyanupanwong** [material-components/material-components-android#2477]
**Is your feature request related to a problem? Please describe.**

Our Android app is targeting small tablets and/or embedded Android devices for UAV remote control. We are make use of the Rail as the primary navigation method for the Settings screen due to the screen size contraint.

Right now, we are almost at the limit of the vertical height and the Rail does not support for vertical scrolling.  This issue also exist in the Google Photos app when opening on 7-8 inch tablets on landscape orientation. 

**Describe the solution you'd like**

It would be nice if the Rail does support for vertical scrolling thru some kind of flags or by default as if we have more menu items we can displayed vertically.

**Describe alternatives you've considered**

Swtiching to TabLayout instead is not a good idea based on our UX experiment as it also reduce the screen real estate for the content, so we have switched back to the Rail.

** Additional context **

Googling for the solution to this problem also resulting in similar thing on SO:
https://stackoverflow.com/questions/61874835/scrollable-navigation-rail-in-flutter

**Comment by ArcherEmiya05** [comment]
Any update on this? This behavior/feature should be available out of the box without us needing to explicitly handle it with ScrollView since this is such a common use case and scenario.

**Comment by imhappi** [comment]
Hi @ArcherEmiya05 this is currently on the roadmap

**Comment by ArcherEmiya05** [comment]
> Hi @ArcherEmiya05 this is currently on the roadmap

May I ask if this is expected to be included in `1.13.x`?

**Comment by imhappi** [comment]
Hi @ArcherEmiya05 this was submitted in https://github.com/material-components/material-components-android/commit/cc09ce8d556a3a5d4db056bb19317fc8afe36007 and will be included in our next alpha release
