### ISSUE TITLE
[MaterialDatePicker] Can't use arabic numbers to enter the date

### ISSUE THREAD

**Issue by mazenrashed** [material-components/material-components-android#2486]
**Description:** When the app language is Arabic, I can't use the Arabic numbers to enter the date.

![device-2021-11-30-191900](https://user-images.githubusercontent.com/7754410/144097151-a5557cfa-58e8-4c41-bced-2d8d253b230c.png)

**Expected behavior:** Use Arabic and Indian numbers to enter the date.

**Source code:** 
` val datePicker =
            MaterialDatePicker.Builder.datePicker()
                .setCalendarConstraints(constraintsBuilder.build())
                .setTheme(R.style.AppTheme_DatePicker)
                .build()`

**Android API version:** 31

**Material Library version:** material:1.6.0-alpha01

**Device:** Pixel 2

**Comment by drchen** [comment]
Hi, can you provide more details about your use case? I think it's a bit uncommon to input numbers in different locales. (There may also be system restrictions, I'm not sure.)

**Comment by mazenrashed** [comment]
Hi, We write the numbers in Arabic using the Arabic numbers (123..), but in some countries, they use the Indian numbers(١,٢,٣..), in most of the keyboards, when you switch the language to Arabic, the numbers will be the Arabic numbers (123..).
So, I think that the view should accept any of these alphabets.

**Comment by mazenrashed** [comment]
@drchen Does the information in the previous comment is enough?

**Comment by drchen** [comment]
Hi Mazen, yeah it does. I need to raise this to our localization team to check their opinion. Thanks for the report!

**Comment by paulfthomas** [comment]
We don't really do anything particular on the Material side regarding what numbers should be used for dates. We just set `android:inputType="date"` on the EditText. I successfully selected a date with an Arabic locale so closing this ticket for now. Please reopen if it is still an issue.

<img src="https://user-images.githubusercontent.com/8482544/234110388-7a9171c9-2b2d-414f-902e-ad3d1bb10b4b.png" width="300">
