### ISSUE TITLE
[BottomNavigationView] Item Padding Top - Bottom & ActiveIndicator Not Working 

### ISSUE THREAD

**Issue by LRCD** [material-components/material-components-android#2494]
**Description:** Full description of issue here
Material3 BottomNavigationView Indicator Not Showing and Title text and icons are messed up.

The Indicator Is not showing and Padding top and bottom doesn't work

![Screenshot_20211205-124513_Test_NavBar](https://user-images.githubusercontent.com/45685096/144734063-f68c2ffa-8514-4ebb-810c-c049d5653e72.png)

Even if i Override The Styles, It still doesn't work.

![Screenshot_20211205-110105_Sketchware_Pro~2](https://user-images.githubusercontent.com/45685096/144734073-967c82d3-2f9d-40e9-b4fe-10eb078950f2.png)

**Expected behavior:** Screenshots and/or description of expected behavior

This is my Expected Behavior from Google Material Catalog App
![IMG_20211205_105944](https://user-images.githubusercontent.com/45685096/144734047-c620a20b-6e17-4805-a1fd-db400a810289.jpg)

**Android API version:** Android API version here
My API version is Android 11 (SDK 30).

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
The version I've used is the latest one 1.5.0-beta01

**Device:** Device on which the bug was encountered here
On my Device

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by hunterstich** [comment]
What does the BottomNavigationView look like in your layout file? Are you setting any styles on it? Can you try setting it's style to `Widget.Material3.BottomNavigationView` directly in the layout?

**Comment by LRCD** [comment]
> What does the BottomNavigationView look like in your layout file? Are you setting any styles on it? Can you try setting it's style to `Widget.Material3.BottomNavigationView` directly in the layout?

I've Tried too. But Never Mine, I'm going to close this issue. Updating to Latest AndroidX core libraries fixed it.

**Comment by mwshubham** [comment]
I migrated from com.google.android.material:material:1.4.0 to com.google.android.material:material:1.5.0 and Now, I am getting the same issue. I didn't understand which androidx core libraries update you are talking about. Can you please refer to which stable release should be used along with material 1.5.0 to fix this? TIA
