### ISSUE TITLE
[Bottom Navigation View] Height increase after destroying the foreground app and reopening

### ISSUE THREAD

**Issue by abhishekds94** [material-components/material-components-android#2496]
**Description:** Full description of issue here
I am working on a sample app that uses Material 3 bottom navigation view, everything looks good on the first launch but when you destroy the app and reopen it again, it increases the height of the bottom nav view when height is set to wrap parent

**Expected behavior:** Screenshots and/or description of expected behavior
On First Launch - 
![Screenshot_1639023876](https://user-images.githubusercontent.com/13012026/145334608-c0745ec7-9427-410e-ac66-6055fb3941aa.png)

After - 
![Screenshot_1639023885](https://user-images.githubusercontent.com/13012026/145334624-237919bf-7dad-4f06-8142-f32fbdf899c2.png)

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.
   ```
 <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.5"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/bottom_navigation_menu"/>
```

**Android API version:** Android API version here
Target - 31
Compile - 31

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.6.0-alpha01

**Device:** Device on which the bug was encountered here
1. Emulator running on API 31
2. Pixel 4XL running on Android 12

**Comment by abhishekds94** [comment]
This happens when we are using the Splash Screen API with a custom exit animation. Below is the code that is being used to test,
`
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {

            //For dynamic colors in MaterialYou
            DynamicColors.applyToActivitiesIfAvailable(application);

            installSplashScreen()
            // Add a callback that's called when the splash screen is animating to
            // the app content.
            splashScreen.setOnExitAnimationListener { splashScreenView ->
                // Create your custom animation.
                val slideUp = ObjectAnimator.ofFloat(
                    splashScreenView,
                    View.TRANSLATION_X,
                    0f,
                    -splashScreenView.height.toFloat()
                )
                slideUp.interpolator = AnticipateInterpolator()
                slideUp.duration = 1000L

                // Call SplashScreenView.remove at the end of your custom animation.
                slideUp.doOnEnd { splashScreenView.remove() }

                // Run your animation.
                slideUp.start()
            }
        }
`

**Comment by hunterstich** [comment]
Hi @abhishekds94,

Thanks for filing an issue! Would you be able to attach your sample? I tried re-creating your scenario but wasn't able to reproduce the issue you've described.

**Comment by abhishekds94** [comment]
https://github.com/abhishekds94/MaterialUI/tree/materialOld

@hunterstich the above repo has the code that can be used to see the issue mentioned.
Steps to follow,
1. Run the app on API 31 based emulator/device - notice the standard height on the bottom nav bar
2. Now, kill the app from the foreground
3. Open the app again - notice the increase in the height on the bottom nav bar

Another bug that I am seeing (could be a known one) - When you run the app for the first time, the logo on the splash screen will not be displayed but the second time onwards it is seen.

**Comment by hunterstich** [comment]
@abhishekds94 I'm getting a 404 on that repo page

**Comment by abhishekds94** [comment]
> @abhishekds94 I'm getting a 404 on that repo page

Ooops!
Had made it private, changed it to public now - should be able to access

**Comment by robertlevonyan** [comment]
```
class NoPaddingBottomNavigation @JvmOverloads constructor(
  context: Context, attrs: AttributeSet? = null
) : BottomNavigationView(context, attrs) {

  init {
    setOnApplyWindowInsetsListener(null)
    setPadding(0)
  }
}
```

this works for me

**Comment by abhishekds94** [comment]
> ```
> class NoPaddingBottomNavigation @JvmOverloads constructor(
>   context: Context, attrs: AttributeSet? = null
> ) : BottomNavigationView(context, attrs) {
> 
>   init {
>     setOnApplyWindowInsetsListener(null)
>     setPadding(0)
>   }
> }
> ```
> 
> this works for me

Thanks, @robertlevonyan. Looks like it is a bug to me if we have to set the padding explicitly to 0
