### ISSUE TITLE
[DynamicColors] manufacturer list blocks using dynamic color

### ISSUE THREAD

**Issue by Jongchul-Yang** [material-components/material-components-android#2498]
**Description**: From 1.5.0-beta01, manufacturere list is added to check if dynamic color is available or not.
                          This condition blocks using dynamic color on some devices even thought it runs on Android 12.
                    
**Expected behavior:** 
(1) Sufficient explanation about the manufacturer list is needed on Material Component home page.
(2) The way to add new manufacturer to the list must be guided.
(3) What is the contact point to discuss adding new manufacturer to the list?

**Source code:** 
```
  private static final Set<String> DYNAMIC_COLOR_SUPPORTED_MANUFACTURERS =
      new HashSet<>(Arrays.asList(
          "oppo", "realme", "oneplus", "vivo", "xiaomi", "motorola", "itel", "tecno mobile limited",
          "infinix mobility limited", "hmd global", "sharp", "sony", "tcl", "lenovo", "google",
          "robolectric"));

  public static boolean isDynamicColorAvailable() {
    return VERSION.SDK_INT >= VERSION_CODES.S
        && DYNAMIC_COLOR_SUPPORTED_MANUFACTURERS.contains(Build.MANUFACTURER.toLowerCase());
  }
```
**Android API version:** 31

**Material Library version:** 1.5.0-beta01 or later

**Device:** Devices of manufacturers except for the DYNAMIC_COLOR_SUPPORTED_MANUFACTURERS list

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by jbingham** [comment]
In order to ensure a consistent developer and user experience, manufacturers are added to the list when they integrate the official Android dynamic color algorithm. 

If you work for a manufacturer and believe your company should be included, contact your Android Partner Engineer.

Thanks!
