### ISSUE TITLE
[MaterialDatePicker] When using dateRangePicker, is it possible to validate the selection range, like only allow within 7 days.

### ISSUE THREAD

**Issue by yzhang108** [material-components/material-components-android#2499]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
You can implement [your own validator](https://github.com/material-components/material-components-android/blob/master/docs/components/DatePicker.md#adding-calendar-constraints). In the MDC catalog we have this example of a custom validator: [DateValidatorWeekdays](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/datepicker/DateValidatorWeekdays.java). You can change the `isValid` method for your specific needs.
