### ISSUE TITLE
TextInputLayout.getTypeface incorrectly annotated with @NonNull

### ISSUE THREAD

**Issue by lisawray** [material-components/material-components-android#25]
### Overview

[The setter for typeface is annotated](https://github.com/material-components/material-components-android/blob/master/lib/src/android/support/design/widget/TextInputLayout.java#L290) with `@Nullable`, and [the getter is](https://github.com/material-components/material-components-android/blob/master/lib/src/android/support/design/widget/TextInputLayout.java#L307) `@NonNull`.  One or the other is wrong.  

Currently, the getter does return null.

You can see the problem pretty easily ...

```
  public void setTypeface(@Nullable Typeface typeface) {
    if (typeface != mTypeface) {
      mTypeface = typeface;

      mCollapsingTextHelper.setTypefaces(typeface);
      if (mCounterView != null) {
        mCounterView.setTypeface(typeface);
      }
      if (mErrorView != null) {
        mErrorView.setTypeface(typeface);
      }
    }
  }

  /**
   * Returns the typeface used for the hint and any label views (such as counter and error views).
   */
  @NonNull
  public Typeface getTypeface() {
    return mTypeface;
  }
```

### Version number

 - 25.1.0

**Comment by jotaemepereira** [comment]
I added a PR for this (#26)
