### ISSUE TITLE
Time Picker UI Bug in negative button 

### ISSUE THREAD

**Issue by Berkavc** [material-components/material-components-android#2500]
**Description:** In Time Picker i have encountered that design of positive and negative buttons is different from expected default value. In addition negative button prevents click of keyboard icon in the layout.

**Expected behavior:** button design must be same as expected design.

**Source code:** 
```
   binding.editTextDialogTime.clickWithThrottle {
            val timePicker =
                MaterialTimePicker.Builder()
                    .setHour(gatherHourFromDate(calendarEvent.timeInMillis))
                    .setMinute(gatherMinuteFromDate(calendarEvent.timeInMillis))
                    .setTitleText(context?.resources?.getString(R.string.dialog_group_page_event_time_picker_title))
                    .setTheme(com.hms.referenceapp.eventtracker.common.R.style.CustomTimePicker)
                    .build()
            timePicker.addOnPositiveButtonClickListener {
                calendarEvent.set(Calendar.HOUR_OF_DAY, timePicker.hour)
                calendarEvent.set(Calendar.MINUTE, timePicker.minute)
                binding.textInputLayoutDialogTime.placeholderText =
                    convertLongToTimeWithDot(calendarEvent.timeInMillis)
            }

            timePicker.show(this.parentFragmentManager, "")
        }
```

```
 <style name="CustomTimePicker" parent="@style/ThemeOverlay.MaterialComponents.TimePicker">
        <item name="colorPrimary">@color/figma_explore_filter_selected_color</item>
        <item name="colorOnPrimary">@color/white</item>
    </style>
```

Hms device (Problematic Behaviour):
https://user-images.githubusercontent.com/64521873/146182989-9ee3d103-4581-49a8-9a9a-ae24a0204d1c.mp4

Gms device (Expected Behaviour):
https://user-images.githubusercontent.com/64521873/146183198-61ef25cb-a9b0-4b05-a67c-a1e404c9d05b.mp4

**Android API version:** 29

**Material Library version:** 'com.google.android.material:material:1.4.0'

**Device:** HUAWEI P40 LITE JNY-LX1

Have a nice day :)

**Comment by drchen** [comment]
Hi, can you help check if this is still happening on 1.5.0, after migrating to Material3?

We are stopping support of Material2 theme/styles so I'm not sure if it will be prioritized if it's an M2-only issue.

**Comment by Berkavc** [comment]
Hello, it's fixed in newer versions thank you for your feedback.
