### ISSUE TITLE
[TextInputLayout] I use errorEnable="true" but it not show red border

### ISSUE THREAD

**Issue by tampro9x92** [material-components/material-components-android#2501]
![image](https://user-images.githubusercontent.com/55266330/146715995-21ee2da8-b131-4d04-9ba8-49fb87e53e6e.png)
![image](https://user-images.githubusercontent.com/55266330/146716043-74769d36-8e59-4cb3-b0a5-b11c69432ced.png)

**Comment by tampro9x92** [comment]
oh so I can't make it like this 
![image](https://user-images.githubusercontent.com/55266330/146797231-938f59b1-a618-48fd-aa00-d9a6f18759dd.png)

**Comment by tampro9x92** [comment]
in my phone it only show this like what you say 
![image](https://user-images.githubusercontent.com/55266330/146797363-71278894-50a5-4d70-99a6-8e19fe9b20b1.png)

**Comment by leticiarossi** [comment]
So is it working for you? Can you specify what issue you're having?

**Comment by tampro9x92** [comment]
I want to remove the icon error

**Comment by drchen** [comment]
If you just want change the color, you will need to customize the style and override the proper attributes you want. Please refer to the doc here: 
https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md
