### ISSUE TITLE
[TextInputLayout] setBoxBackgroundColor(#FFFFFFFF) but auto change color to violet my gallery color <color name="gallery">#EFEFEF</color>

### ISSUE THREAD

**Issue by tampro9x92** [material-components/material-components-android#2503]
![image](https://user-images.githubusercontent.com/55266330/146723470-57bc34c3-46b6-4d82-aabf-c16cdc52a08d.png)
![image](https://user-images.githubusercontent.com/55266330/146722611-a707bc1b-5ceb-4827-bd57-6880e702295c.png)

**Comment by leticiarossi** [comment]
Can you specify what issue are you running into? And include source code with the problem

**Comment by tampro9x92** [comment]
(https://paste.ofcode.org/38aqBVEGi2HXMxrtkLBa94t)

**Comment by tampro9x92** [comment]
here my code
