### ISSUE TITLE
How to add text on FloatingAction

### ISSUE THREAD

**Issue by SwordBearer** [material-components/material-components-android#251]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

**Comment by SwordBearer** [comment]
please ignore last comment :)
Just like https://material.io/design/components/buttons-floating-action-button.html#extended-fab ，I want to add text on FAB, but don't know how

**Comment by leticiarossi** [comment]
Hi, this should be possible once the extended fab component is implemented, which is currently being worked on (tracking issue for it: https://github.com/material-components/material-components-android/issues/79)

**Comment by ymarian** [comment]
dup of https://github.com/material-components/material-components-android/issues/79
