### ISSUE TITLE
[MaterialToolbar] get the background color of the AppBar

### ISSUE THREAD

**Issue by Se-Lyan** [material-components/material-components-android#2512]
I saw that there was no way to retrieve the color from the toolbar, MaterialShapeDrawable does not allow me to retrieve the color.

**Comment by afohrman** [comment]
Hi @Se-Lyan, you should be able to get the background color of the toolbar using MaterialShapeDrawable's `getFillColor()` method: https://developer.android.com/reference/com/google/android/material/shape/MaterialShapeDrawable#getFillColor().

Please reopen this issue if this method does not provide what you're looking for.
