### ISSUE TITLE
[Slider] Ripple is drawn underneath the Slider

### ISSUE THREAD

**Issue by Netherquark** [material-components/material-components-android#2513]
**Description:** This issue occured while using [Wavelet](https://github.com/Pittvandewitt/Wavelet) ([Play Store](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet)). It is a mirror of [this](https://github.com/Pittvandewitt/Wavelet/issues/124) issue, which I encountered using the app. However, I am not the developer, so I doubt I will be able to properly address this issue and cite specifics. The app is open source, so that might be helpful in diagnosis.

**Expected behavior:** The ripple is rendered over the slider

**Android API version:** Tested and observed on API version 30 (Android 11)

**Material Library version:** Not sure?

**Device:** This bug was observed on a Curtana/Miatoll (Redmi Note 9 Pro India/Redmi Note 9S) running Lineage OS official.

**Comment by afohrman** [comment]
Hi @Netherquark, thanks for reporting this issue. From the description, it's not clear what the issue is. Is the bug that the ripple is missing from the slider? Is it rendered underneath the slider?

Could you please provide a screen recording of the bug and a more detailed description of what you see that's wrong?

**Comment by Netherquark** [comment]
https://user-images.githubusercontent.com/65618735/148180454-ed7b6f1c-ddef-446d-b0ac-e9d5bf2d5c04.mp4

As you can see in this screen recording, when the slider is being moved, the ripple is rendered below the slider, causing the gap in the ripple. This is also visible in the following screenshot:

**Comment by afohrman** [comment]
Thanks so much for the explanation and video, that really helped explain the bug. I changed the issue title to more clearly explain the bug.

I tried to reproduce the issue in our catalog but I'm not seeing the issue on our end (see video attached). It's possible that the Wavelet code modifies the Material slider, resulting in this bug. It's also possible that the slider is not a Material slider or that there is an underlying issue with the Material slider that the Wavelet code somehow triggers. I recommend reaching out to the Wavelet developers to let them know about the bug. If they'd like, they can update this issue with their code and we can help them troubleshoot the bug.

**Comment by Pittvandewitt** [comment]
Hello, I'm the author of the application in question. I can confirm that the slider component is used, without further modifications being applied.
After compiling the catalog application and trying to reproduce the reported issue, I can also confirm that the ripple is indeed drawn below track: 
![image](https://user-images.githubusercontent.com/1721405/148689827-081a4054-067e-4413-82d6-21a5606c16b7.png)

**Comment by Poopooracoocoo** [comment]
@afohrman Any chance of reopening?

**Comment by kendrickumstattd** [comment]
Hi @Pittvandewitt and @Poopooracoocoo. I took a look at this. The ripple is removed by default with Material 3, so I'm going to close out this issue. Feel free to reopen if you still need this fixed.
