### ISSUE TITLE
[ChipDrawable] setText method seems not applicable with SpannableString

### ISSUE THREAD

**Issue by samuelchou** [material-components/material-components-android#2522]
**Description:** 

As title, `ChipDrawable.setText` seems not working with `SpannableString`.

**Expected behavior:**

Expecting `ChipDrawable.setText` is applicable with `SpannableString`.
Or, given more chip-text-style-setting method like PR #1165 requested.

**Source code:** 

Make a `chip.xml` in res/xml.

```XML
<?xml version="1.0" encoding="utf-8"?>
<chip xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:textAppearance="@style/TextAppearance.AppCompat.Small"
    app:closeIconEnabled="false" />
```

```Kotlin
val chipDrawable = ChipDrawable.createFromResource(context, R.xml.chip)
val chipText = "TEXT"

// start setting span
val textColorSpan = ForegroundColorSpan(getColor(android.R.color.holo_red_light))
chipDrawable.text = SpannableStringBuilder(chipText).apply {
    setSpan(textColorSpan, 0, chipText.length, 0) // not working!
}
```

Unlike any other component, such as `TextView`, above code will work.

**Android API version:** 11

**Material Library version:** `1.4.0`. I tried it in `1.5.0` too, the problem still exists.

**Device:** Any.

**Comment by drchen** [comment]
Hi we just submit #1165, does it work for your purpose?

To support displaying spannable strings on drawables (and to maintain it) is not trivial, comparing to the impact it can bring. I'm afraid that we won't have a plan to support it in the near future. 

If #1165 works for you, I'll close the issue.

**Comment by samuelchou** [comment]
Thanks for replying! I'll test it if I have a chance in future. Good to know that the component is still being cared! 🥳

**Comment by samuelchou** [comment]
Hello, just back here to let you know, I tested `setTextColor` and now it works fine.
using:

```
implementation 'com.google.android.material:material:1.6.0'
```

below code works:

```Kotlin
val chipDrawable = ChipDrawable.createFromResource(this, R.xml.my_chip)
chipDrawable.apply {
    setTextColor(Color.GREEN)
    text = "CHIP"
    setBounds(0, 0, intrinsicWidth, intrinsicHeight)
}
val span = ImageSpan(chipDrawable)

val spannableString = SpannableString(textView.text)
spannableString.setSpan(
    span, 0, spannableString.length, Spannable.SPAN_EXCLUSIVE_INCLUSIVE
)
textView.text = spannableString
```

Although the `SpannableString` is still not functional in `ChipDrawable.setText`, as mentioned above:

```Kotlin
chipDrawable.apply {
    text = SpannableString("CHIP").also {
        val colorSpan = ForegroundColorSpan(Color.RED)
        it.setSpan(colorSpan, 0, it.length, Spannable.SPAN_EXCLUSIVE_INCLUSIVE)
    } // won't actually be red though
    setBounds(0, 0, intrinsicWidth, intrinsicHeight)
}
```

But I guess it doesn't really matter now, as you can achieve text-color-changing with `setTextColor`, or in Custom View when the span go too much complex.
