### ISSUE TITLE
[MaterialTextField] Add dense modifier

### ISSUE THREAD

**Issue by shaqaruden** [material-components/material-components-android#2523]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
I would like the ability to have a dense TextField with a label. Add a .dense() modifier to do so.

**Describe alternatives you've considered**
I tried creating this myself but ran into multiple hurdles along the way and was not able to successfully implement a fully featured DenseTextField.

**Additional context**
Follow Material Design guidelines

**Comment by dsn5ft** [comment]
Hi, MaterialTextField is not part of this repo / library. Is this maybe intended for the Material Compose library?

https://developer.android.com/jetpack/androidx/releases/compose-material

https://issuetracker.google.com/issues/new?component=742043&template=1346811
