### ISSUE TITLE
[NavigationRailView] FAB shadow is on the left instead of bottom

### ISSUE THREAD

**Issue by PomepuyN** [material-components/material-components-android#2524]
**Description:** When setting a `NavigationRailView` `headerLayout` containing a `FloatingActionButton`, it's shadow is cast on the wrong side (left instead of bottom).

**Expected behavior:** The shadow is cast on the bottom side

![Screenshot_1642580893](https://user-images.githubusercontent.com/371298/150092700-c2146a19-16f9-479f-8c5f-ba7655bbc65b.png)

**Source code:** 

Small sample: 
[NavigationRailIssue.zip](https://github.com/material-components/material-components-android/files/7895325/NavigationRailIssue.zip)

**Android API version:** 12L

**Material Library version:** 1.5.0 / 1.6.0-alpha02

**Device:** Emulator

**Comment by dsn5ft** [comment]
This is the intended behavior, as the virtual "light source" in the Android framework should be somewhere towards the center / top of the screen, so UI elements towards the left of the screen would cast a shadow to the left.
