### ISSUE TITLE
[NavigationBarItem] NavigationBarItem cannot set indication

### ISSUE THREAD

**Issue by choristery** [material-components/material-components-android#2529]
**Description:** NavigationBarItem cannot set indication

**Android API version:** 12

**Material Library version:** material3:1.0.0-alpha03

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by wcshi** [comment]
@choristery please file your bug at https://issuetracker.google.com/issues?q=status:open%20componentid:742043

this is the wrong library
