### ISSUE TITLE
[MaterialCardView] Keyboard focus color is based on rippleColor

### ISSUE THREAD

**Issue by seaweeddol** [material-components/material-components-android#2533]
**Description:** 
When a MaterialCardView component has the `app:rippleColor` style applied, the overlay color of a keyboard focused element uses the rippleColor. This can have unintended consequences since it also changes the keyboard focus color. In particular, if using `app:rippleColor="@color/transparent"` to remove the ripple effect, there is no visual indication of keyboard focus which is an accessibility issue.

**Expected behavior:** I would expect the rippleColor to not have any effect on the keyboard focus color.

**Source code:** 
`app:rippleColor="@color/transparent"`

**Android API version:** 30

**Material Library version:** 1.3.0

**Device:** Pixel 4 emulator

**Comment by pekingme** [comment]
@seaweeddol I have change this from a bug to feature request. IIUC, your concern is using `rippleColor` for both screen touch focus and keyboard focus. Is this only happening on a card view or other components?

**Comment by drchen** [comment]
I think it's a very standard practice to implement focus indicator with ripple on Android. 

If you want to disable ripple color other than the focus state, you can use a CSL to set transparent color for other states.

I'm going to close the issue as WAI for now, but feel free to reopen it if you have different suggestions. We will evaluate the effort and impact it may take to split the implementation of focused and other states. Thanks!
