### ISSUE TITLE
Bottom NavigationBar ICons getting reversed with latest update

### ISSUE THREAD

**Issue by likhitha-utu** [material-components/material-components-android#2535]
implementation 'com.google.android.material:material:1.6.0-alpha02'
From 1.5.0 bottom navigation icons getting reversed title getting on top of image

![Screenshot_1643097186](https://user-images.githubusercontent.com/58801964/150935006-af4f84fd-f3b1-414c-a249-a81293925204.png)

**Comment by hunterstich** [comment]
Hi @likhitha-utu,

Thanks for filing a bug!
Are you able to reproduce this in a small sample that you can send? I can't seem to get this to happen on my end.

**Comment by likhitha-utu** [comment]
Yes i am able to reproduce this issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by likhitha-utu** [comment]
I will share a screenrecording before and after the version increase and will share more details about the mobile i tested and the versions i used to test

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by likhitha-utu** [comment]
@drchen @pekingme @hunterstich @cketcham please find the below screenshots and version that i have used to check this bug.
when used this  library version    implementation 'com.google.android.material:material:1.5.0'

![home1](https://user-images.githubusercontent.com/58801964/153209555-c21e4b46-47c6-4b84-af2c-7f864c8d78f8.png)

when used this  library version    implementation 'com.google.android.material:material:1.4.0' getting the icons and text properly.
![home2](https://user-images.githubusercontent.com/58801964/153209778-e811341e-bf9b-4afd-b3d7-ef1fc08e1fb2.png)
 Tested Device: Pixel 3a(emulator), API version(30),Android 11

**Comment by dhritzkiv** [comment]
I had the same behaviour, until I commented out the `android:theme` attribute on BottomNavigationView. The theme value was referencing was a custom one that extended `Widget.Design.BottomNavigationView`, and the only entry in the theme was a font family value.

**Comment by hunterstich** [comment]
@dhritzkiv, @likhitha-utu Would you all be able to attach samples that reproduce these issues?

**Comment by likhitha-utu** [comment]
@drchen @pekingme @hunterstich @cketcham

  <style name="Widget.BottomNavigationView" parent="Widget.Design.BottomNavigationView">
        <item name="fontFamily">@font/notosans_regular</item>
        <item name="android:textSize">10sp</item>
    </style>

   <com.google.android.material.bottomnavigation.BottomNavigationView
            android:id="@+id/bottomBar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:background="@color/expiryDateColor"
            android:theme="@style/Widget.BottomNavigationView"
            app:itemTextAppearanceActive="@style/BottomNavigationView.Active"
            app:itemTextAppearanceInactive="@style/BottomNavigationView.Active"
            app:itemTextColor="@drawable/nav_item_color_state"
            app:labelVisibilityMode="labeled"
            app:menu="@menu/bottom_bar" />

this is the code that i used  for this library implementation 'com.google.android.material:material:1.5.0'

**Comment by hunterstich** [comment]
```
<style name="Widget.BottomNavigationView" parent="Widget.Design.BottomNavigationView"> @font/notosans_regular 10sp </style>
```
The above doesn't look like a valid style. What does this do/what are you trying to achieve?

Can you remove the `android:theme="@style/Widget.BottomNavigationView` attribute? Unless you need to set a theme overlay and change theme-level attributes (color, type, etc) used by BottomNavigationView, this line shouldn't be necessary. 

Can you also post the contents of `@style/BottomNavigationView.Active` and details about `@font/notosans_regular`?

**Comment by hunterstich** [comment]
Ah gotcha. You're setting a theme overlay on your BottomNavigationView to a widget style, which isn't ideal.

There are a couple of approaches to using your custom font in a bottom nav view. The best would be to use Material's [typography system](https://github.com/material-components/material-components-android/blob/master/docs/theming/Typography.md). If your app is using a `Material3` theme, you can customize the "Type scale" in your theme, setting each scale to use your custom font, and Bottom Navigation View will, by default, use your theme's `textAppearanceTitleSmall` scale. 

This would look like:
```
// theme.xml
// YOUR APP'S THEME

<style name="Theme.MyApp" parent="Theme.Material3.DayNight.NoActionBar">
  ...
  <item name="textAppearanceTitleSmall">@style/TextAppearance.MyApp.TitleSmall</item>
  ...
</style>
```

```
// styles.xml
// YOUR CUSTOM TEXT APPEARANCE

<style name="TextAppearance.MyApp.TitleSmall" parent="TextAppearance.Material3.TitleSmall">
  ...
  <item name="fontFamily">@font/MYFONT</item>
  ...
</style>
```

```
// activity_main.xml
// YOUR LAYOUT

<com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:labelVisibilityMode="labeled"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/bottom_menu" />
```


If you're not using a `Material3` or `MaterialComponents` theme, you can directly set `app:itemTextAppearanceActive` and `app:itemTextAppearanceInactive` on your BottomNavigationView to your custom TextAppearace (like the one in the above block - `TextAppearance.MyApp.TitleSmall`):

```
// activity_main.xml
// YOUR LAYOUT

<com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:itemTextAppearanceActive="@style/TextAppearance.MyApp.TitleSmall"
        app:itemTextAppearanceInactive="@style/TextAppearance.MyApp.TitleSmall"
        app:labelVisibilityMode="labeled"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/bottom_menu" />
```

Does this help?

**Comment by hunterstich** [comment]
Going to go ahead and close this but feel free to re-open if none of the above is able to fix the issue

**Comment by dhritzkiv** [comment]
Thanks for taking the time! This is very helpful and helps me better understand how it should've been done. I'll try it out later this week.

**Comment by likhitha-utu** [comment]
@drchen @pekingme @hunterstich @cketcham

    <style name="BottomNavigationView.Active" parent="@style/TextAppearance.AppCompat.Caption">
        <item name="android:textSize">10sp</item>
    </style>

<img width="1440" alt="Screenshot 2022-02-16 at 12 02 07 PM" src="https://user-images.githubusercontent.com/58801964/154209368-5fe5d251-bc8e-4ed8-a08f-ef3c9a69ad5a.png">

This is the font that we are using in our app

**Comment by hunterstich** [comment]
Try adding 
`<item name="fontFamily">@font/notosans_regular</item>`
to your `BottomNavigationView.Active` TextAppearance

**Comment by likhitha-utu** [comment]
@hunterstich this fixed the issue thankyou.
