### ISSUE TITLE
[Transition] MaterialContainerTransition not following child scroll

### ISSUE THREAD

**Issue by evowizz** [material-components/material-components-android#2540]
**Description:**
When using a MaterialContainerTransition on Fragments, going back and scrolling immediately causes the shared element to stick in its original position instead of scrolling with the content it belongs to.

**Expected behavior:**
Scrolling on a child should cause the shared element to follow the scrolled child as if it was already part of it. 

**Source code:**
The Catalog can be used to reproduce this issue. More specifically, the branch `master` was used to reproduce this bug with the Catalog. The commit 3cf23e4 is the latest at the time I'm writing this issue. In the video included below, the bug is produced by the MaterialContainerTransform used here: https://github.com/material-components/material-components-android/blob/3cf23e4bf151bf37ff81859ae83301926c3b0dc1/catalog/java/io/material/catalog/feature/FeatureDemoUtils.java#L71-L75

**Android API version:** Android 12 (SDK 31)

**Material Library version:** Master (v1.6.0-alpha02 + all commits until 3cf23e4)

**Device:** Pixel 6 Pro

**Additional information:**
Here's a video of the bug in action using the M3 Catalog:

https://user-images.githubusercontent.com/9381261/151666859-73e0207a-ed20-419f-a299-efda5ea910b3.mp4

**Comment by hunterstich** [comment]
Hi @evowizz,

This is a limitation of shared element transitions. When the transition is triggered, the position of the shared elements is captured, the animations is started, and a `Drawable` that draws both shared elements is added to the view hierarchy. Since the transition is "fire and forget" it doesn't have a way to watch for changes in its end view position.

**Comment by evowizz** [comment]
Thank you for your reply @hunterstich !

I was expecting this answer quite frankly. It's sad that the shared elements haven't really progressed on Android.

I understand that this is a limitation of Android. Meaning that there's nothing else to do about it. However, i also believe this impacts users as this can easily be considered as a bug from the app. Because of that, I'll have to forget about having this transition in my own app.

Thanks a lot for your help, though!
