### ISSUE TITLE
adjustResize no longer works in 1.6.0-alpha02 when activity has transparent navigationBarColor

### ISSUE THREAD

**Issue by ParticleCore** [material-components/material-components-android#2543]
In version 1.5.0 this used to work with no problem, but in 1.6.0-alpha02 it no longer works.

Steps:
Run the below project with material 1.5.0, click on the "Click here" to open the dialog and then click on the "Click here to open the keyboard". When the keyboard opens, the entirety of the dialog is moved above the keyboard correctly, this is the intended behavior.

When repeating the above with 1.6.0-alpha02, the dialog will no longer move above the keyboard, causing the entire dialog to be covered by the keyboard, making it impossible to see what is being entered.

As far as I could find, the issue only happens in 1.6.0-alpha02 when I use `<item name="android:navigationBarColor">@android:color/transparent</item>` if I remove that then the issue no longer occurs.

Sample project files below:

`MainActivity.kt`
````java
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }

    fun show(view: View) {
        RoundedBottomSheetDialogFragment().show(supportFragmentManager, "tag")
    }

}
````

`activity_main.xml`
````xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:onClick="show"
        android:padding="16dp"
        android:text="Click here"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

</androidx.constraintlayout.widget.ConstraintLayout>
````

`RoundedBottomSheetDialogFragment.kt`
````java
class RoundedBottomSheetDialogFragment : BottomSheetDialogFragment() {

    override fun getTheme(): Int = R.style.BottomSheetDialogThemeNoFloating

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setStyle(STYLE_NORMAL, R.style.BottomSheetDialogThemeNoFloating)
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return inflater.inflate(R.layout.dialog, container, false)
    }

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        val bottomSheetDialog = BottomSheetDialog(requireContext(), theme)
        bottomSheetDialog.behavior.isDraggable = false
        return bottomSheetDialog
    }

}
````

`themes.xml`
````xml

    <style name="AppTheme"
        parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <add your styles here>
        <item name="android:navigationBarColor">@android:color/transparent</item> <-- the important part
    </style>

    <style name="BottomSheetDialogThemeNoFloating" parent="ThemeOverlay.MaterialComponents.BottomSheetDialog">
        <item name="android:windowIsFloating">false</item>
        <item name="android:windowSoftInputMode">adjustResize|stateAlwaysVisible</item>
    </style>
````

`dialog.xml`
````xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:minHeight="128dp">

    <EditText
        android:id="@+id/test"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:padding="16dp"
        android:hint="Click here to open keyboard"
        android:textColor="@color/black"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

</androidx.constraintlayout.widget.ConstraintLayout>
````

**Comment by pekingme** [comment]
Thanks for the sample project! That helps a lot. I have found the issue. Caused by 022a05f, IME bottom padding is not found. Fix will be synced out this week.

**Comment by pekingme** [comment]
The fix above is not correct. It has been reverted. After trying the sample project, it seems that not just BottomSheetFragment doesn't respect to `adjustResize`, but also DialogFragment. It seems setting `android:windowSoftInputMode` as `adjustResize` works fine with Activity. I'm wondering if this is a known issue or intended behavior in DialogFragment. If the problem is only about not being able to see the input view while typing, I'll suggest set `android:windowSoftInputMode` as `adjustPan` or as default in `ThemeOverlay.MaterialComponents.BottomSheetDialog`. If the whole bottom sheet layout needs to be visible while typing, then we may need to use the deprecated method used in 1.5.0 for getting the bottom inset. Will take another look next week.

**Comment by ParticleCore** [comment]
sorry, but I do not agree with the option of adjustResize not working at all being an intended behavior. It is for all intents and purposes an Activity skinned as a DialogFragment fragment, it should follow the same design expectations, and I have not seen any official update confirming this is an intended change. In fact, the api usage outside this library remains the same, it is only the latest version of this library that is killing the inset.

the option to use adjustPan is not acceptable because there are other requirements that expect that screen to resize for difference use cases, and adjustPan would not work for that.

let me remind that this issue is only occurring when the navigationBarColor is set to transparent, if it really was an intended change then I expect it would not be bound to just this scenario, and if it was then it would affect the entire app as well since my app does have that set for every single screen, and no issues are occurring for those screens.
