### ISSUE TITLE
CollapsingToolbarLayout: Title shadow does not respect maxLines in expanded state

### ISSUE THREAD

**Issue by bazinac** [material-components/material-components-android#2545]
When adding shadow to the Title text of CollapsingToolbarLayout like
```
 <com.google.android.material.appbar.CollapsingToolbarLayout
    (...)
    app:expandedTitleTextAppearance="@style/CustomToolbarTheme"
    app:maxLines="2">

<style name="CustomToolbarTheme" parent="@style/ThemeOverlay.AppCompat.Dark.ActionBar">
   <item name="android:shadowColor">@color/colorBlack</item>
   <item name="android:shadowDx">1</item>
   <item name="android:shadowDy">1</item>
    <item name="android:shadowRadius">2</item>
</style>
```
The title does not respect the multiline nature of the tile and behaves weirdly (rendering shadow like text was in one line only). See below.

![Screenshot_20220203-090359_Mushrooms app](https://user-images.githubusercontent.com/19685528/152304063-a6e6c984-bc44-4c08-8859-31ad82ca7b61.jpg)

Using _com.google.android.material:material:1.6.0-alpha02_, but happens with 1.5 as well. Not sure when this stopped working correctly, but it used to in the past.

**Comment by pekingme** [comment]
Thanks for reporting the issue. Could you provide a sample project for reproducing the bug? I have put a simple CollapsingToolBar with as the attributes you shared. But cannot reproduce the shadow issue shown in the screenshot. I assume it happens in a very corner use case.

**Comment by bazinac** [comment]
Hi sorry for the late reply, I was away for the weekend.

I have extracted described behaviour here:
[(https://github.com/bazinac/CollapsingToolbarLayoutShadowSample)
](https://github.com/bazinac/CollapsingToolbarLayoutShadowSample)

![Screenshot_20220206-212534](https://user-images.githubusercontent.com/19685528/152700020-72974158-ce00-44c4-bb27-ca26146811a8.jpg)

**Comment by bazinac** [comment]
Actually, in the example I have shared, the shadow is drawn incorrectly right away when displaying expanded states (as you can see on the screenshot above. Once you start scrolling and thus collapsing the toolbar, the shadow is visible as well on the second line once the actual text gets collapsed into one line. See below:
![Screen_Recording_20220208-204206 (2)](https://user-images.githubusercontent.com/19685528/153064119-f910d96f-84ec-4caf-be30-0c1d1ead1ad0.gif)

**Comment by pekingme** [comment]
Interesting, could you share some details about the APIs and devices (emulators) tested?

**Comment by bazinac** [comment]
I have tested it on Samsung Galaxy S20 and Huawei P30, both manifest the same behavior...

**Comment by bazinac** [comment]
Quick idea - if you cannot reproduce the same behaviour, does "East African Hippopotamus" label fit onto your screen in the collapsed state? If so, could you pls try to replace the string "East African Hippopotamus" (in main activity) with something longer that would cause the text to be split into two lines in the expanded state?

**Comment by pekingme** [comment]
What was the API level you testing on?

**Comment by bazinac** [comment]
31

**Comment by bazinac** [comment]
31
