### ISSUE TITLE
[Chips] Layout preview broken for chips

### ISSUE THREAD

**Issue by michael-winkler** [material-components/material-components-android#2546]
**Description:** The layout preview (xml) inside android studio is broken for all chips.

**Expected behavior:** Show the chips in the layout preview of android studio

**Material Library version:** com.google.android.material:material:1.6.0-alpha02

**Comment by pekingme** [comment]
Could you share more details about your setup? Which version of Android Studio you are using? Could you share your layout file? Does this observed with other versions of the library, e.g., 1.5.0?

**Comment by Mika-89** [comment]
As example it works with implementation 'com.google.android.material:material:1.6.0-alpha01'
On 1.6.0-alpha02 it's broken.

Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40)

### XML

`<com.google.android.material.chip.Chip
                        android:id="@+id/hilfe_chip1"
                        style="@style/Widget.MaterialComponents.Chip.Choice"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:checked="true"
                        android:text="@string/toolbar_titel_dokumente"
                        android:textColor="@color/color_state_list_chip_text"
                        android:textSize="@dimen/font_size_default"
                        app:chipBackgroundColor="@color/color_state_list_chip_background"
                        app:chipStrokeColor="@color/color_stroke_v2" />`


### Images
'com.google.android.material:material:1.6.0-alpha01'
![1 6 01](https://user-images.githubusercontent.com/29900947/152532745-9f8dad95-5c2d-48a7-aedb-35f045872bca.png)

'com.google.android.material:material:1.6.0-alpha02'
![1 6 02](https://user-images.githubusercontent.com/29900947/152532772-00641e37-37a9-4daf-9704-96c318ce0a1d.png)

**Comment by veganafro** [comment]
hey @Mika-89, could you also share the color state lists used for `app:chipBackgroundColor` and `app:chipStrokeColor`?

**Comment by Mika-89** [comment]
`android:textColor`

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/color_white" android:state_checked="true" />
    <item android:color="#1e1e1e" android:state_checked="false" />
</selector>
```

<hr>

`app:chipBackgroundColor`

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/color_primary" android:state_checked="true" />
    <item android:color="@color/color_white" android:state_checked="false" />
</selector>
```

<hr>

`app:chipStrokeColor` = #AFB1B3 (normal color reference)

**Comment by dsn5ft** [comment]
Is this still an issue with the latest version of Android Studio?

**Comment by michael-winkler** [comment]
Hi,

it looks like working now. 😊
