### ISSUE TITLE
[M3/Top App Bar] Top app bar continues to display drop shadow when elevated

### ISSUE THREAD

**Issue by OxygenCobalt** [material-components/material-components-android#2552]
**Description:** The top app bar continues to cast a drop shadow when using the `Material3`, against what the design guidelines say.

**Expected behavior:** The intended behavior should be for the top app bar not to cast a shadow, as the Material Design 3 guidelines state.

This is how the top app bar should look [note the lack of drop shadow]:
![image](https://user-images.githubusercontent.com/65370175/152649737-bcb89347-897a-49f7-8bed-310c921abf3e.png)

This is how the top app bar [with `AppBarLayout`] looks in my app right now [note the drop shadow but pastel elevation]:
![Screenshot_20220205-091803](https://user-images.githubusercontent.com/65370175/152649704-d21962e7-b96f-48a1-9e47-609880361313.png)

**Source code:** I generally use this setup when making a top app bar:
```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout
    android:id="@+id/coordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/colorSurface"
    android:orientation="vertical">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorSurface"
        android:clickable="true"
        android:focusable="true"
        app:liftOnScroll="true">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:navigationIcon="@drawable/ic_back"
            app:title="Title" />

    </com.google.android.material.appbar.AppBarLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Android API version:** API 32

**Material Library version:** 1.5.0 [tested with 1.6.0-alpha02 as well, same thing occurs]

**Device:** Pixel 5 running Android 12

**Comment by dsn5ft** [comment]
@OxygenCobalt thanks for reporting this issue. Currently shadows are only removed from `Widget.Material3.AppBarLayout` and `Widget.Material3.Toolbar.Surface`, but I think we may remove them from the default toolbar style (`Widget.Material3.Toolbar`) as well.

However, I am sort of curious because you are using `AppBarLayout` and `MaterialToolbar` without setting any styles, which means they should be inheriting the default styles. The default styles don't set any elevation, so I'm wondering where that is coming from. Are you using an M3 app theme? Are you setting the elevation programmatically?

**Comment by OxygenCobalt** [comment]
@dsn5ft Looking into this, I don't see `Widget.Material3.AppBarLayout` being applied by default *at all*. Instead I see the M2 primary-color style used instead. That's why I have `android:background="?attr/colorSurface"` set on the `AppBarLayout` so I could get around that issue.

Removing that attribute and explicitly setting the style to `Widget.Material3.AppBarLayout` seems to work. This is likely a shortcoming with the library.

**Comment by dsn5ft** [comment]
Can you confirm what app / activity theme you are using?

**Comment by OxygenCobalt** [comment]
`Theme.Material3.DayNight.NoActionBar`
