### ISSUE TITLE
[M3/DynamicColors] Dynamic Colors not applied when SplashScreen API is used

### ISSUE THREAD

**Issue by serbelga** [material-components/material-components-android#2555]
**Description:**

When application or activity launcher theme inherits from `Theme.SplashScreen` and we set `postSplashScreenTheme` to a theme that inherits from Material3, it does not apply Dynamic Colors when we call `DynamicColors.applyToActivitiesIfAvailable(this)` on the Application class.
 
**Expected behavior:** Apply Dynamic colors.

**Source code:** https://github.com/serbelga/ToDometer/tree/feature/dynamicColors

**Android API version:** Android SDK 31 (Android 12)

**Material Library version:** 1.5.0

```xml
    <!-- Base application theme. -->
    <style name="Theme.ToDometer" parent="Theme.Material3.DayNight">
    ...
    </style>

    <style name="Theme.ToDometer.NoActionBar">
    ...
    </style>

    <style name="Theme.ToDometer.Starting" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/navy</item>

        <item name="windowSplashScreenAnimatedIcon">@drawable/ic_launcher_foreground</item>
        <item name="windowSplashScreenAnimationDuration">2000</item>

        <item name="postSplashScreenTheme">@style/Theme.ToDometer.NoActionBar</item>
    </style>
```

AndroidManifest.xml

```diff
    <application
        android:name=".App"
        ...
-       android:theme="@style/Theme.ToDometer.NoActionBar">
+       android:theme="@style/Theme.ToDometer.Starting">
```

**Comment by serbelga** [comment]
I really don't want to apply Dynamic colors in Splash Screen. The problem is that specifying a Material3 as the postSplashScreenTheme won't apply Dynamic colors.

**Comment by drchen** [comment]
I don't have access to your github link but from the snippet you provided. Where do you call DynamicColors.applyToActivitiesIfAvailable(this) and installSplashScreen()?

You may want to avoid using postSplashScreenTheme since I guess it will override the dynamic color theme overlay we set. Or you can also try to set postSplashScreenTheme to ThemeOverlay.Material3.DynamicColors.DayNight and see if it works in your case?

**Comment by serbelga** [comment]
Here is the link: https://github.com/serbelga/ToDometer/tree/develop

> You may want to avoid using postSplashScreenTheme since I guess it will override the dynamic color theme overlay we set. Or you can also try to set postSplashScreenTheme to ThemeOverlay.Material3.DynamicColors.DayNight and see if it works in your case?

I will try this

**Comment by axiel7** [comment]
I solved this issue by calling `DynamicColors.applyToActivityIfAvailable(this)` after `installSplashScreen()`.
Don't use `DynamicColors.applyToActivitiesIfAvailable(this)` in your Application class. 

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        installSplashScreen()
        DynamicColors.applyToActivityIfAvailable(this)
        
}
```

**Comment by woheller69** [comment]
> I solved this issue by calling `DynamicColors.applyToActivityIfAvailable(this)` after `installSplashScreen()`. Don't use `DynamicColors.applyToActivitiesIfAvailable(this)` in your Application class.
> 
> ```kotlin
> override fun onCreate(savedInstanceState: Bundle?) {
>         installSplashScreen()
>         DynamicColors.applyToActivityIfAvailable(this)
>         
> }
> ```
If I apply that solution the status bar at the top still does not get the correct dynamic color

**Comment by axiel7** [comment]
@woheller69 try this
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        installSplashScreen()
        DynamicColors.applyToActivityIfAvailable(this)
        super.onCreate(savedInstanceState)
        WindowCompat.setDecorFitsSystemWindows(window, false)
}
```

**Comment by woheller69** [comment]
This also does not solve the problem.
In light mode I get a white status bar with white text on it and in dark mode the status bar is black and does not have the theme color.

**Comment by woheller69** [comment]
Cleanest solution is probably to simply remove SplashScreen API...

**Comment by woheller69** [comment]
I found a solution:

In Activity:

        @Override
        protected void onCreate(Bundle savedInstanceState) {
          SplashScreen.installSplashScreen(this);
          if (SETTINGS.getDynamicColors()) DynamicColors.applyToActivityIfAvailable(this);
          getWindow().setStatusBarColor(getThemeColor(this,R.attr.colorPrimaryDark));
          super.onCreate(savedInstanceState);


        public static int getThemeColor(Context context, int colorResId) {
          TypedValue typedValue = new TypedValue();
          TypedArray typedArray = context.obtainStyledAttributes(typedValue.data, new int[] {colorResId});
          int color = typedArray.getColor(0, 0);
          typedArray.recycle();
          return color;
        }

**Comment by the-rebooted-coder** [comment]
> 

`getWindow().setStatusBarColor(getThemeColor(this,android.R.attr.colorPrimaryDark)); `
this worked for me
