### ISSUE TITLE
MaterialAutoCompleteTextView: IME obscures dropdown list

### ISSUE THREAD

**Issue by andre-artus** [material-components/material-components-android#2556]
Whether I choose 
`android:windowSoftInputMode="adjustPan"` or `adjustResize` on the main activity (AndroidManifest.xml) the dropdown window (listing the completion options) is obscured by the IME (Input Method Editor) keyboard pop-up.

This is most prevalent on controls within a bottom dialog or at the bottom of a screen (fragment/activity).

When the dropdown is opened by clicking the open/close icon the lookup window opens towards the top on controls near the bottom of the screen, but when the lookup window is activated as a response to keypresses (via IME) then it opens to the bottom and is hidden by the keyboard.

I can see the lookup window appear for brief moment before it is obscured by the IME pop-up.

```
com.google.android.material:material:1.5.0
com.android.tools.build:gradle:7.1.0
org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10

Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: wu.seal.tool.jsontokotlin (3.7.2), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40)
```

**Comment by drchen** [comment]
Can you provide a screenshot/screen-recording?

**Comment by andre-artus** [comment]
I'll make an example app and screenshots over the weekend.

**Comment by andre-artus** [comment]
Sorry, was too inundated, I'll see about doing it soon.

**Comment by andre-artus** [comment]
I made an example but it does not show the failure as intended. I'm going to have to see if it is device specific.

**Comment by andre-artus** [comment]
It happens on and Android 6 device, will see if same on emulator so I can make a video.

**Comment by andre-artus** [comment]
It happens on the device, but I cannot get the same behavior on the emulator.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with a repro.
