### ISSUE TITLE
MaterialCardView first child

### ISSUE THREAD

**Issue by dovahkiin98** [material-components/material-components-android#256]
Is it normal that MaterialCardView has a FrameLayout child now? Is there anyway to delete it? It will save memory, especially when using many MaterialCardViews

**Comment by ymarian** [comment]
Yes, although this is solving an issue that might not be worth the cost.
I created https://b.corp.google.com/issues/122304308 to track. We'll follow up there with whatever we decide.

**Comment by okarakose** [comment]
I think there is no development on this issue. `1.1.0-alpha08` is released but there is still FrameLayout child inside MaterialCardView.
