### ISSUE TITLE
[MaterialCardView] NullPointerException when applying setOnClickListener

### ISSUE THREAD

**Issue by sinnerthesaint** [material-components/material-components-android#2565]
**Description:** 
When I attach a setOnClickListener to a MaterialCardView inside a recycler view, I get a nullpointerexception. This issue happens in release version 1.5.0 and 1.6.0 alpha and in Android api versions 26,27 and 28. (I've not tried it on versions below 26)

When using release 1.4.0, It works as expected on all api versions tested up to 30 (haven't tested on 31 yet).

The error I get is:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
        at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:141)
        at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:119)
        at com.google.android.material.card.MaterialCardViewHelper.getClickableForeground(MaterialCardViewHelper.java:634)
        at com.google.android.material.card.MaterialCardViewHelper.updateClickable(MaterialCardViewHelper.java:274)
        at com.google.android.material.card.MaterialCardView.setClickable(MaterialCardView.java:365)
        at android.view.View.setOnClickListener(View.java:6107)

**Expected behavior:** No exception gets thrown and the recycler view builds fine.

**Source code:** 
Inside a RecyclerView Adapter I have:
inner class RestaurantViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        var restaurantname: TextView
        private val onMenuItemClickListener: MenuItem.OnMenuItemClickListener = MenuItemClickListener(this, onContextMenuItemClickListener)
        init {
            Log.d(TAG, "Creating RestaurantViewHolder")
            restaurantname = itemView.findViewById(R.id.restaurant_name)
            itemView.setOnClickListener {** _//this is where the error happens_**
.
.
.
                }
            }
}
**Android API version:** 26 - 28

**Material Library version:** 1.5.0 and 1.6.0 alpha

**Device:** Tested on Several emulators and phones (Pixel Mi etc).

**Comment by drchen** [comment]
It's fixed by https://github.com/material-components/material-components-android/commit/b4cab87015fa29e23460f4f47d4d06adfe3a9e9a and should be included in the next alpha version, i.e., 1.6.0-alpha03
