### ISSUE TITLE
[MaterialButtonToggleGroup] OnButtonCheckedListener called multiple times

### ISSUE THREAD

**Issue by patzly** [material-components/material-components-android#2569]
**Description:** It seems like the commit 747bcf25fffb3d3e3b6ec0ef52e884255f144bb4 (simplification of the checking logic) broke my `MaterialButtonToggleGroup` implementation when I upgrade to `1.6.0-alpha02`. When I downgrade to `1.6.0-alpha01` it works correctly.
I let the user change the app theme (light/dark/auto) with a toggle group. After the user selects an option, the app programmatically restarts to apply the new theme to the whole app. Because the containing fragment is restored from saved instance, the toggle group is initialized again with the new theme selected.
Since the last alpha when I tap on a button of the group, the app restarts infinitely and never changes the theme, because the toggle group always goes back to the previous selection. Logs have shown that the `OnButtonCheckedListener` is called once with the new selection of the user and again(!) with the previous selection (all before restart of the app), probably causing the infinite loop.
When I force-stop the app during this loop and open the fragment again, the toggle group is initialized with its old state, meaning the selected option was never written to SharedPreferences, instead the old one was again.

In simple words and without the restart behavior: the `OnButtonCheckedListener` is called twice and the second call contains the previously selected button, so in the end the group and the variables in the listener stay unchanged.

**Expected behavior:** The `OnButtonCheckedListener` should be called exactly once with the correct arguments when I click on a button in a group. It should not matter if I am restarting the app programmatically after that, for example to apply the selected theme.

**Source code:**

``` xml
<com.google.android.material.button.MaterialButtonToggleGroup
  android:id="@+id/toggle_theme"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  app:singleSelection="true"
  app:selectionRequired="true">

  <Button
    android:id="@+id/button_theme_auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="@string/theme_auto" />

  <Button
    android:id="@+id/button_theme_light"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="@string/theme_light" />

  <Button
    android:id="@+id/button_theme_dark"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="@string/theme_dark" />

</com.google.android.material.button.MaterialButtonToggleGroup>
```

``` java
int id;
switch (sharedPrefs.getString(PREF.MODE, MODE.AUTO)) {
  case MODE.LIGHT:
    id = R.id.button_theme_light;
    break;
  case MODE.DARK:
    id = R.id.button_theme_dark;
    break;
  default:
    id = R.id.button_theme_auto;
    break;
}
binding.toggleTheme.check(id);
Log.i(TAG, "get " + sharedPrefs.getString(PREF.MODE, MODE.AUTO));

binding.toggleTheme.addOnButtonCheckedListener((group, checkedId, isChecked) -> {
  String pref;
  if (checkedId == R.id.button_other_theme_light) {
    pref = MODE.LIGHT;
  } else if (checkedId == R.id.button_other_theme_dark) {
    pref = MODE.DARK;
  } else {
    pref = MODE.AUTO;
  }
  sharedPrefs.edit().putString(PREF.MODE, pref).apply();
  Log.i(TAG, "set " + pref);
  restartToApply();
});
```

In logcat I can see that since `1.6.0-alpha02` the `OnButtonCheckedListener` is called infinitely:
```
On fragment creation:
  get auto

On single button click:
  set dark
  set auto
(app restart)
  get auto (caused by fragment recreation)
  set dark
  set auto
(app restart)
  get auto (caused by fragment recreation)
...and so on
```

The correct logs should be:
```
On fragment creation:
  get auto

On single button click:
  set dark
(app restart)
  get dark (caused by fragment recreation)
```

**Android API version:** 31

**Material Library version:** 1.6.0-alpha02

**Device:** Pixel 6

**Comment by drchen** [comment]
You need to add 
```
if (!isChecked) {
 return;
}
```
In the listener you add. (A button get unchecked will also trigger the listener.)

I'm not sure why it worked before but it looks like an issue uncovered by a fix.

**Comment by patzly** [comment]
@drchen That absolutely makes sense, thanks a lot! Now it works correctly.
Maybe it worked with the previous versions because the order of checking has probably changed with the commit containing the rewritten checking logic.

**Comment by drchen** [comment]
Glad to hear it works! 

Yeah I guess it's caused by the invocation order of the callback has been changed. : )
