### ISSUE TITLE
Project not syncing when download as archive (works when git cloned)

### ISSUE THREAD

**Issue by bernaferrari** [material-components/material-components-android#257]
I just downloaded project as archive and got several errors, from lint to catalog app missing compileSdk version. Weirdly, the iOS MDC had kind of a similar issue a few months ago (issue 2497). When using git clone, everything worked fine.

**Comment by ikim24** [comment]
I am not seeing any issues when downloading the project and opening it in Android Studio 3.2.1. Can you provide any more information on how to reproduce these errors?

**Comment by bernaferrari** [comment]
I was going to say something from 3.4 canary was broken, but I tested again and it worked fine now.. so.. even better.. no issue! Thanks!
