### ISSUE TITLE
[MaterialToolbar] Elevation resets to 0dp in Dark Theme

### ISSUE THREAD

**Issue by KdB13** [material-components/material-components-android#2578]
**Description:** When using `MaterialToolbar` with the `Theme.MaterialComponents.DayNight.NoActionBar` theme, the toolbar's elevation resets to `0dp` during the **Night mode**. As a result, the background color of toolbar (which it gets from `?attr/colorSurface`) is the same as the activity's background color. So, we cannot differentiate between the toolbar and the activity's background. This happens because at `0dp` elevation, the **Dark Theme** sets the `colorSurface` to the same value as the `colorBackground`.

The expected behavior should be that the Toolbar's elevation is still `4dp` in the Night mode as well.

Please reply if anybody else is having this same problem, or am I the only victim. 😅

**Expected behavior:**

[Material Dark theme](https://material.io/design/color/dark-theme.html)

![image](https://user-images.githubusercontent.com/36751623/155291142-ac8d6419-dd13-44b4-87c4-d674240b7055.png)

**Source code:**
Here's the [link](https://github.com/material-components/material-components-android/blob/bdbf052aaf1e824f221057ca3c3acae80d1a521d/lib/java/com/google/android/material/appbar/res/values/styles.xml#L70) to file.

As you can see, in the following style, the `android:elevation` is not set to the **Toolbar**. And, this style gets applied in Night mode.

```
<style name="Widget.MaterialComponents.Toolbar.Surface">
    <!-- This line is missing from the style -->
    <item name="android:elevation" tools:ignore="NewApi">@dimen/design_appbar_elevation</item>

    <item name="android:background">?attr/colorSurface</item>
    <item name="titleTextColor">@color/material_on_surface_emphasis_high_type</item>
    <item name="subtitleTextColor">@color/material_on_surface_emphasis_medium</item>
    <!-- Note: this theme overlay will only work if the style is applied directly to a Toolbar. -->
    <item name="android:theme">@style/ThemeOverlay.MaterialComponents.Toolbar.Surface</item>
</style>
```

**Android API version:** Android 11 (API 30)

**Material Library version:** 1.5.0

**Device:** Samsung Galaxy A50s

**Comment by KdB13** [comment]
The current workaround is to explicitly set the Toolbar's elevation to `4dp` in a custom style override inside `values-night` folder. Like this:
```
<style name="Widget.App.Toolbar" parent="Widget.MaterialComponents.Toolbar.PrimarySurface">
    <item name="android:elevation">@dimen/design_appbar_elevation</item>
</style>
```

**Comment by KdB13** [comment]
I've updated the issue to specify the exact part in source code which results in this problem. Check out the updated **Source code** section in the issue.

**Comment by dsn5ft** [comment]
Hi @KdB13, thanks for filing your issue. By default the `Toolbar` styles are meant to not come with an elevation, because a common use case and recommendation is to embed a `Toolbar` within an `AppBarLayout`, which will provide the elevation and the background color, as well as more Material behavior like hide-on-scroll or lift-on-scroll. So setting the elevation manually like you found is actually correct, if using a standalone `Toolbar`.

**Comment by KdB13** [comment]
Thanks, @dsn5ft. I though this was a bug. As in older versions of Material Design Components, there was an elevation provided by default.

**Comment by KdB13** [comment]
The [style](https://github.com/material-components/material-components-android/blob/bdbf052aaf1e824f221057ca3c3acae80d1a521d/lib/java/com/google/android/material/appbar/res/values/styles.xml#L61) for standalone MaterialToolbar has a default elevation of `4dp`. So, the docs are indeed right.

**Comment by KdB13** [comment]
@dsn5ft I got it now. Thank you for clearing this confusion. 🙂

**Comment by KdB13** [comment]
> Technically `Widget.MaterialComponents.Toolbar` is the default style, not `Widget.MaterialComponents.Toolbar.Primary`. The reason why the `Widget.MaterialComponents.Toolbar.Surface` doesn't have the elevation is because Surface Toolbars are meant to be flush with the rest of the screen, without a shadow (until scroll which is what the AppBarLayout is for).

As per your advice now I'm using an `AppBarLayout` to wrap the Toolbar as shown below:
```
<com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:liftOnScroll="true">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/top_app_bar"
            style="@style/Widget.MaterialComponents.Toolbar.PrimarySurface"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:title="@string/app_name" />

</com.google.android.material.appbar.AppBarLayout>
```

Now, the problem is that when my content moves behind the Toolbar in Dark Mode, the Toolbar's background color is not changing to a lighter shade due to the elevation change. It stays the same as `colorBackground`. I can see that the elevation has indeed changed due to a black shadow on my list items. See the screenshot below:

![Screenshot_20221003-142902_Jotter](https://user-images.githubusercontent.com/36751623/193540105-ec8bc99a-fb07-4b57-89c9-d216540c9c49.png)
