### ISSUE TITLE
Disable dynamic color

### ISSUE THREAD

**Issue by Otang45** [material-components/material-components-android#2579]
How to disable the dynamic color when button click

**Comment by hunterstich** [comment]
Hi, 

When you use `DynamicColors.applyToActivitiesIfAvailable`, you can provide a `Precondition` that can keep track of whether you want dynamic colors to be on or off depending on whether your button is pressed. 

You can see this in the catalog app here: https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/preferences/DynamicColorPreference.java#L78
