### ISSUE TITLE
How to make range date selection multiple and edit back this

### ISSUE THREAD

**Issue by hafiz013** [material-components/material-components-android#2583]
Hi there do you know how to make range date multiple selection and can back edit this value?

**Comment by hunterstich** [comment]
Hi @hafiz013,

Do you mind elaborating? I don't quite understand what you're asking. 

You want to be able to select a date range and then change the selected dates?

**Comment by hafiz013** [comment]
You want to be able to select a date range and then change the selected dates?
Answer: Yes but only for one time range date can't do multiple date range.

Do you mind elaborating?
Answer: If possible can do multiple date range plus can edit back these multiple date range (suggestion: rodiobutton/check),
Do you understand?

**Comment by hunterstich** [comment]
Ah!

I think so. So you want the date picker to be able to select multiple ranges in the same UI?

This isn't something on our roadmap. I would suggest designing around the fact that a date picker can only select a single range and offer the "radiobutton/check" interface separately—on your own. Maybe a screen that launches separate range pickers for for each range that needs selection? 

If you have more details on the UX flow your trying to create, we might be able to provide more guidance.

**Comment by hunterstich** [comment]
Going to go ahead and close this, @hafiz013. If I've misunderstood or there's anything else we can help with, feel free to re-open.

**Comment by hafiz013** [comment]
Owh i see. Maybe you could do this in the future.Thank you
