### ISSUE TITLE
Appbarlayout

### ISSUE THREAD

**Issue by SudoDios** [material-components/material-components-android#2587]
Hi.
How to change lift on scroll color?

**Comment by hunterstich** [comment]
Hey @SudoDios ,

The color of "lift on scroll" is determined by taking the AppBarLayout's background (colorSurface by default in Material3), and applying an elevation overlay (a gradually more opaque version of `?attr/elevationOverlayColor` which points to `?attr/colorPrimary` in Material3) as its elevation increases when scrolling up.  

The easiest way to change the overlay color would be to apply a theme overlay to your AppBarLayout where you override either the `?attr/elevationOverlayColor` or `?attr/colorPrimary` theme attribute:

```
  <com.google.android.material.appbar.AppBarLayout
      android:id="@+id/appbarlayout"
      android:theme="@style/ThemeOverlay.MyApp.AppBarLayout"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      ...
      />
```

```
<style name="ThemeOverlay.MyApp.AppBarLayout" parent=""/>
    <item name="elevationOverlayColor">@color/my_app_bar_layout_elevation_color</color>
</style>
```

The color you use for  `@color/my_app_bar_layout_elevation_color` will have it's alpha changed to be fairly faint, so you might have to choose a pretty dark/saturated color.

If you want all of your elevated components to have a different elevated color (components like FAB and BottomNaivigationView), you can set `?attr/elevationOverlayColor` in your App's main theme to have this color change apply to all elevated surfaces. 

Let me know if this answers your question.

**Comment by hunterstich** [comment]
Closing this for now but feel free to re-open if this doesn't answer your question

**Comment by SudoDios** [comment]
Thanks
