### ISSUE TITLE
[CollapsingToolbarLayout] Add stretch Overscroll effect 

### ISSUE THREAD

**Issue by heybradharris** [material-components/material-components-android#2594]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Hi, can you provide more detailed description about the effect you are looking for?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with more info.
