### ISSUE TITLE
[NavigationView] Error inflating class since upgrading to version 1.5.0+

### ISSUE THREAD

**Issue by adil-hussain-84** [material-components/material-components-android#2595]
**Description:** The [NavigationView](https://developer.android.com/reference/com/google/android/material/navigation/NavigationView) class fails to inflate after upgrading the Material Components library from version `1.4.0` to `1.5.0+`.

**Expected behavior:** The [NavigationView](https://developer.android.com/reference/com/google/android/material/navigation/NavigationView) class inflates with versions `1.5.0+` like it does with versions `1.4.0` and earlier.

**Android API version:** My project's `compileSdkVersion` and `targetSdkVersion` values are set to 31.

**Material Library version:** `1.5.0+` (including `1.6.0-alpha03`)

**Device:** Reproduced on an Android 12 emulator and an Android 9 device.

**Cause:** Set the [NavigationView](https://developer.android.com/reference/com/google/android/material/navigation/NavigationView)'s `app:itemIconTint` value to a style attribute like `"?android:attr/textColorSecondary"` and assign an unnamed color resource to the `android:textColorSecondary` style value, as follows:

```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
    <item name="android:textColorSecondary">#000000</item>
</style>
```

**Comment by adil-hussain-84** [comment]
There workaround for this issue is to assign a named color resource to the `android:textColorSecondary` style value, as follows:

```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
    <item name="android:textColorSecondary">@color/some_color</item>
</style>
```

**Comment by drchen** [comment]
Can you post the error message you got here? Also what style are you using to render the NavigationView?

Does it happen if you set your theme to Material3 themes?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
