### ISSUE TITLE
[BottomSheetDialog] Navigation bar transparency ignored when the bottom sheet reaches the top

### ISSUE THREAD

**Issue by spun** [material-components/material-components-android#2596]
### Description:
If a bottom sheet is scrollable, the content will be shown **behind** the bottom navigation bar (system) until the bottom sheet reaches the top (correct behavior).  [Video](https://i.imgur.com/dmANSJ6.mp4)

Once the bottom sheet is fully expanded, the behavior will switch to display the content **above** the navigation bar. [Video](https://i.imgur.com/QgObnJ9.mp4)

When the content is a block of text, the user can see how it begins to disappear from the bottom. [Video](https://i.imgur.com/vW19JA5.mp4)

### Expected behavior:
The bottom sheet should always display the content behind the navigation bar when edge to edge is enabled.

### Minimal sample app repro:
The "Bottom Sheet" section in the catalog app has an example of scrollable content with this behavior.

### Android API version:
Any version that can go edge to edge should have this issue.

### Material Library version:
master branch, commit 6a4fa0b (Mar 10, 2022)

### Device:
Emulator API 29 and another device running Android 11

**Comment by drchen** [comment]
Hi, so this is working as intended. When a bottom sheet is in the default edge-to-edge mode, it will add bottom paddings to consume the system insets occupied by the navigation bar. Note that the bottom paddings will be  below the content and can only be seen when the bottom sheet is expanded. 

Therefore, when the content is scrollable, it will create an illusion that the navigation bar suddenly becomes non-translucent - it's actually because the bottom paddings start showing when the bottom sheet is expanded.

Unfortunately I don't think there's a good way for bottom sheet to handle the case of scrolling content automatically. It involves correctly adding paddings to the bottom of the actual content inside the scroll view, which is unknown to the bottom sheet. 

If you want to achieve the visual effect you want, you can set `app:paddingBottomSystemWindowInsets` to false in your custom bottom sheet style, and add the required paddings to the proper content view.

**Comment by Emplexx** [comment]
I have a question, as you said applying a style with `app:paddingBottomSystemWindowInsets` set to false to bottom sheets lets you handle the navbar padding yourself, but after trying (what I'm assuming are) equivalent options for removing the status bar padding (`paddingTopSystemWindowInsets`, `forceApplySystemWindowInsetTop`, `marginTopSystemWindowInsets`) in various combinations I cannot find the one that works without issues - the main two I've encountered are either 1. when the bottom sheet is opened it will be "moved" down by exactly the height of my status bar (you can still slide it up to reveal it in full, however this is annoying for small menus that would fit on the screen) or 2. if it is as tall as the screen, it will not go under the status bar, meaning that a bottom portion of it is cut off, and so if there is any scrollable content inside of it, it cannot be scrolled to the bottom (as it is also cut off) 

So what I'm asking is, what is the correct way to disable the padding added by default for both the status and nav bar? (one that would also not cause issues like not allowing the sheet to go under the status bar like what I described above)

**Comment by Lingviston** [comment]
Last comment touches my feelings.

I expect the following combination
`
app:paddingBottomSystemWindowInsets="true"
app:paddingTopSystemWindowInsets="false"
`

To work in a way that content is shifted at the bottom by the bottom inset, at the top content ends right under the status bar. However with the scrollable content it doesn't work:

- If content is too small then top margin is added anyway, making the content scrollable by the same measure
- If the content is big then at the top it ends right before the status bar, however at the bottom the added padding is cut, making part of the content still appear under the nav bar!

Here's the layout, which you can use with any activity that enables e2e mode:
`
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:id="@+id/bottomSheet"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        app:behavior_hideable="false"
        app:behavior_peekHeight="120dp"
        app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior"
        app:paddingBottomSystemWindowInsets="true"
        app:paddingTopSystemWindowInsets="false">

        <androidx.core.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <View
                    android:layout_width="match_parent"
                    android:layout_height="1280dp"
                    android:background="#FF00FF"
                    android:scaleType="centerCrop" />
            </LinearLayout>
        </androidx.core.widget.NestedScrollView>
    </LinearLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
`

**Comment by Lingviston** [comment]
Status bar padding handling indeed seems to work incorrectly. I reported another issue for this https://github.com/material-components/material-components-android/issues/3375
