### ISSUE TITLE
I would like to add a close BottomNavigationView LongClick Toast ，Thanks。

### ISSUE THREAD

**Issue by houkhan** [material-components/material-components-android#2598]

**Comment by hunterstich** [comment]
Hi @houkhan,

Can you elaborate? I don't understand what you mean.

**Comment by houkhan** [comment]
The BottomNavigationView has the LongClick Toast  function, I need a way to turn it off

**Comment by houkhan** [comment]
I want to open this question, but I can't. Please follow up.
