### ISSUE TITLE
Chips with AutocompleteTextView

### ISSUE THREAD

**Issue by ranjan-technoexponent** [material-components/material-components-android#2603]
* How to add 'Chips' in 'AutocompleteTextView'?
* How to implement a TextWatch or Tokenizer for adding and removing chips under 'AutoCompleteTextView'?

* How to define a 'clickListener' or 'closeIconClickListener'

**Comment by drchen** [comment]
You can create a custom view that extends AutoCompleteTextView, and override showDropDown() method to show whatever you want when the autocomplete list should be shown. To add/remove autocomplete candidates you can create a Filterable ListAdapter and call setAdapter() to  apply it.

You can use TextInputLayout.setEndIconMode(END_ICON_CUSTOM) to create a close (or whatever custom) icon and call TextInputLayout.setEndIconOnClickListener() to set a custom onClickListener. (It has a known bug but it should work in most cases. We are working on a fix to it.)

Please check the dev doc for more information regarding custom icons:
https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md
