### ISSUE TITLE
[TextInputLayout] Prefix spacing is shown when field is not in focused

### ISSUE THREAD

**Issue by imkhalid** [material-components/material-components-android#2612]
**Description:** Recently I Updated Material Lib for android from 1.3.0 to current (1.5.0)
but after updating i am facing issue of Prefix spacing displayed(not prefix text) in TextInputLayout and hint moves ahed
Which was working fine in 1.3.0, now i am unable to find solution to this problem  

**Expected behavior:** it should not have taken space when not focused.

**Source code:** The code snippet which is causing this issue

**Android API version:** Android API version here

**Material Library version:** 1.5.0

**Device:** All 
![sdfds](https://user-images.githubusercontent.com/40037273/159857808-8a5434b6-672b-474d-a382-a5ee8c874630.png)

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
Thanks for reporting! I identified the bug being introduced in 1.6.0-alpha02 in https://github.com/material-components/material-components-android/commit/26d862bc5433eb50ba0875e136ff937d4e5ae617 so the 1.5.0 version should still work as expected. I'm currently working on a fix.

**Comment by imkhalid** [comment]
@leticiarossi i have encounter this issue in version 1.5.0
