### ISSUE TITLE
[CollapsingToolbarLayout] How to set ellipsize to middle to Title in CollapsingToolBar 

### ISSUE THREAD

**Issue by venugopalraog** [material-components/material-components-android#2614]
CollapsingToolbar is setting the Title truncation to End. But as per our requirement we need to set the ellipsize in middle since the last chars in the Title are important we can't ignore or truncate it. Is there any way to achieve it?

**Comment by drchen** [comment]
Unfortunately we are not supporting that in our current implementation. Feel free to file a feature request if you really need it and we will see if we can get it prioritized. Also feel free to make a PR to add the support of it. : )

I'll close the issue for now.
