### ISSUE TITLE
[MaterialToolbar] child view layout after a title width even if set titleCentered true

### ISSUE THREAD

**Issue by qq549631030** [material-components/material-components-android#2616]
**Description:** when MaterialToolbar set titleCentered true, the child view still layout after a title width 

**Expected behavior:** the child view should layout at the start

**Source code:** 
```
    <com.google.android.material.appbar.MaterialToolbar
        android:layout_width="match_parent"
        android:layout_height="?actionBarSize"
        app:navigationIcon="@null"
        app:title="title"
        app:titleCentered="true">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="start"
            android:text="text" />
    </com.google.android.material.appbar.MaterialToolbar>
```

**Minimal sample app repro:**N/A

**Android API version:** all

**Material Library version:** 1.6.0-beta01

**Device:** all

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Can you elaborate? Do you mean the child text view is also centered? 

A screenshot will explain the issue better. Thanks!

**Comment by qq549631030** [comment]
the child view layout at the same place no matter titleCentered is true or false
![image](https://user-images.githubusercontent.com/7122715/160729245-25c5336d-3b26-4cbe-b6a5-302680b0d063.png)

**Comment by drchen** [comment]
Got it. Thanks for the info. The cause is that positioning of custom child views is done in the AppCompat class (Toolbar) but centering of titles is done in the Material library so they are not really coordinated. I'm not sure if it's even possible to fix but I'll see what we can do.
