### ISSUE TITLE
[FloatingActionButton] Artifact shown when pressing the FAB on API 31+

### ISSUE THREAD

**Issue by leinardi** [material-components/material-components-android#2617]
**Description:** On API level 31+ a strange artifact is shown when pressing the FAB. The artifact is especially visible on dark/black background and is bigger when `app:useCompatPadding` is `true`.

![image](https://user-images.githubusercontent.com/273338/160237502-4638f538-4cb1-4a72-8deb-bf606b6b1fc0.png)

**Expected behavior:** The artifact should not be shown, like on API 30 or lower.

![image](https://user-images.githubusercontent.com/273338/160237553-23d73f65-2848-4c99-9962-64204697773f.png)

**Source code:** The code snippet which is causing this issue

```xml
    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:clipChildren="false"
        android:clipToPadding="false"
        android:layout_gravity="center">

        <com.google.android.material.floatingactionbutton.FloatingActionButton
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:srcCompat="@drawable/ic_add_white_24dp"
            app:useCompatPadding="true" />
    </LinearLayout>
```

**Minimal sample app repro:** https://github.com/leinardi/FloatingActionButtonSpeedDial/tree/issue-2617

**Android API version:** Android API version 31+

**Material Library version:** 1.5.0

**Device:** Android emulator

**Comment by fernandomantoan** [comment]
I can confirm the issue, the following snippet is working without any issue:

```
<com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/fab_new_command"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:contentDescription="@string/command_form"
        app:tint="@color/white"
        app:backgroundTint="@color/color_primary"
        app:fabSize="normal"
        app:layout_anchorGravity="bottom|end"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        android:layout_margin="16dp"
        app:srcCompat="@drawable/ic_add_white_24" />
```

But if I set `app:useCompatPadding="true"` I also get a squared shadow on touch.

**Comment by fernandomantoan** [comment]
Setting `fabSize` to `mini` will also show a weird shadow when pressing the button.

```
<com.google.android.material.floatingactionbutton.FloatingActionButton
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:fabSize="mini"
    app:srcCompat="@drawable/ic_add_white_24dp" />
```

<img width="148" alt="Screen Shot 2022-03-28 at 15 01 50" src="https://user-images.githubusercontent.com/210359/160459048-2bebec62-aa3f-4087-a2d9-555ead6a5a88.png">

**Comment by dsn5ft** [comment]
Hello, this is an issue with the new framework ripple in Android S. I believe it has been fixed for future versions of Android.

**Comment by yys730** [comment]
I take this approach for the time being
`<com.google.android.material.floatingactionbutton.FloatingActionButton
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:scaleX="0.75"
            android:scaleY="0.75"
            android:src="@drawable/xxx"
            app:borderWidth="0dp"
            app:maxImageSize="@dimen/dp_32" />`
