### ISSUE TITLE
MaterialDatePicker very slow

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2618]
**Description:** 
Migrating from DatePickerDialog to MaterialDatePicker but encounter a noticeable lag. Receiving `Skipped 87 frames!  The application may be doing too much work on its main thread.` every time we call `.show(fragmentManager, tag)`. Additionally it seems there is a memory leak happening but will still check it. Btw we are using it inside a Fragment.

**Expected behavior:** No lag and no skipped frames. 

**Source code:** 

```
private lateinit var datePickerFrom: MaterialDatePicker<Long>

datePickerFrom = it.showMaterialDatePicker(
                    R.style.AppDatePicker,
                    calendarConstraints
                ).apply {
                    addOnPositiveButtonClickListener { time ->

                    }
                }

datePickerFrom.show(parentFragmentManager, "From DatePicker")

/**
 * Extension for Material DatePicker
 * */
fun Context.showMaterialDatePicker(
    @StyleRes id: Int? = null,
    calendarConstraints: CalendarConstraints? = null
) = MaterialDatePicker.Builder.datePicker().apply {

    setTitleText("Select date")

    id?.let {
        setTheme(it)
    }

    calendarConstraints?.let {
        setCalendarConstraints(it)
    }

}.build()
```
Tried to remove theme but not working as well.

https://user-images.githubusercontent.com/38008900/160278560-edf3c5f5-bcba-43c1-bfab-6c3670eb7f55.mp4

**Minimal sample app repro:** N/A

**Android API version:** 21

**Material Library version:** 1.5.0

**Device:** Samsung J1

**Comment by wangjianxiang** [comment]
I have the same problem

**Comment by alexeyVh** [comment]
We had the issue and it turned out that root cause was in Lokalise, this smelly code: 

```
override fun attachBaseContext(newBase: Context) {
        super.attachBaseContext(LokaliseContextWrapper.wrap(newBase))
}
```

**Comment by drchen** [comment]
Let's track the issue under the same topic here: #1910
