### ISSUE TITLE
[BottomNavigationView] getOrCreateBadge not using Dynamic Colors

### ISSUE THREAD

**Issue by jordyamc** [material-components/material-components-android#2621]
**Description:** When using getOrCreateBadge on BottomNavigationView the generated BadgeDrawable is not using the system dynamic colors

![Screenshot_20220330_224131](https://user-images.githubusercontent.com/6831873/160978600-515965b0-9968-4577-8b6e-41f7cf4805da.png)

**Expected behavior:** The badge using dynamic colors

**Source code:**
`binding.bottomNav.getOrCreateBadge(R.id.nav_downloaded)`

**Android API version:** Android 12 SDK 31

**Material Library version:** 1.6.0-beta01

**Device:** Android Emulator 31.2.9-8316981 with Android 12.0 (S) - API 31

**Comment by drchen** [comment]
It's working as intended. In the default style the badge color is set to `?attr/colorError`, which is not dynamic. 

If you want badges with dynamic colors, please override `?attr/badgeStyle` in your theme and set the `?attr/backgroundColor` you like to a color role/resource with dynamic color enabled.
