### ISSUE TITLE
[AppBarLayout] Attribute "app:expanded" does not work in 1.6.0-beta01

### ISSUE THREAD

**Issue by Back4fire** [material-components/material-components-android#2629]
Simply set app:expanded="false" in the layout XML file but the AppbarLayout is not collapsed. It works well in 1.5.0.

**Comment by dsn5ft** [comment]
@Back4fire are you using an AppBarLayout with a CollapsingToolbarLayout or just a standalone AppBarLayout?

**Comment by Back4fire** [comment]
AppBarLayout is used with a CollpasingToolbarLayout.
If there is no CollpasingToolbarLayout, I think AppBarLayout will not have the expanded/collapsed state actually.
