### ISSUE TITLE
Error in documentation for TabLayout

### ISSUE THREAD

**Issue by bernaferrari** [material-components/material-components-android#263]
> You should set a listener via ERROR(/#setOnTabSelectedListener(OnTabSelectedListener)) to be notified when any tab's selection state has been changed.

https://developer.android.com/reference/com/google/android/material/tabs/TabLayout

https://github.com/material-components/material-components-android/blob/6c70169e8d4ae77429a9c57785e443b2a18b4aa3/lib/java/com/google/android/material/tabs/TabLayout.java#L113

**Comment by ymarian** [comment]
Thanks for reporting. This has been fixed and it will be updated once we release a new stable version with the new version of the docs.
