### ISSUE TITLE
BottomNavigationMenuView Crashing on Adding menus

### ISSUE THREAD

**Issue by hussein-yassine** [material-components/material-components-android#2630]
**Description:** I'm Adding the bottom bar items programmatically and there's a crash happening that I'm not able to reproduce the crash but I do have the stack trace available.

**Stack trace:** Fatal Exception: java.lang.IllegalStateException
The specified child already has a parent. You must call removeView() on the child's parent first.

```
android.view.ViewGroup.addViewInner (ViewGroup.java:6065)
android.view.ViewGroup.addView (ViewGroup.java:5884)
android.view.ViewGroup.addView (ViewGroup.java:5824)
android.view.ViewGroup.addView (ViewGroup.java:5796)
com.google.android.material.bottomnavigation.BottomNavigationMenuView.buildMenuView (BottomNavigationMenuView.java:589)
com.google.android.material.bottomnavigation.BottomNavigationPresenter.updateMenuView (BottomNavigationPresenter.java:67)
androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate (MenuBuilder.java:292)
androidx.appcompat.view.menu.MenuBuilder.onItemsChanged (MenuBuilder.java:1063)
androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged (MenuBuilder.java:1090)
com.google.android.material.bottomnavigation.BottomNavigationMenu.addInternal (BottomNavigationMenu.java:57)
androidx.appcompat.view.menu.MenuBuilder.add (MenuBuilder.java:476)
com.sportsmax.ui.main.MainActivity.setBottomBarData (MainActivity.java:400)
```

**Source code:** 

```
binding.bottomNav.menu.clear()
.
.
.

val menuItem = binding.bottomNav
                .menu
                .add(Menu.NONE, fragmentId, Menu.NONE, bottomBarItem.getTitle())
```

**Android API version:** 

- 50% on Android 11
- 25% on Android 7
- 25% on Android 10

Material Android Library version is 1.3.0

**Device:** 

- 75% of devices are Samsung devices, 50% of them on Galaxy A02, and 25% are Galaxy J7 Pro

**Comment by drchen** [comment]
Hi the implementation of BottomNavigationMenuView has been refactored a lot since 1.3.0. Can you try with the latest library version and see if you can still reproduce the issue?
