### ISSUE TITLE
MaterialToolbar on Material3 DayNight still using Material2 default coloring

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2632]
**Description:** 
Using `Theme.Material3.DayNight` as base theme. Styling the `MaterialToolbar` like title and action menu icon color still uses the Material2 default value like `android:textColorPrimary` for the title and `colorControlNormal` for navigation/action menu icon.

**Expected behavior:** 
`colorOnSurface` for title color and `colorOnSurfaceVariant` for icons should work based on the documentation.
However background color works perfectly fine, even I define `colorPrimary` it won't work until I set `colorOnSurface` .

**Source code:** 
```
<!-- Base application theme -->
    <style name="Theme.Cryptonian" parent="Theme.Material3.DayNight">
  <!-- Toolbar navigation icon tint -->
        <item name="android:textColorPrimary">@android:color/holo_red_dark</item>
        <item name="colorControlNormal">@android:color/holo_red_dark</item>
</style>
```

![image](https://user-images.githubusercontent.com/38008900/162358691-873f2fb4-f38e-4a69-9e82-d5c2e94fd948.png)

```
<!-- Base application theme -->
    <style name="Theme.Cryptonian" parent="Theme.Material3.DayNight">
  <!-- Toolbar navigation icon tint -->
        <item name="colorOnSurface">@android:color/holo_green_dark</item>
        <item name="colorOnSurfaceVariant">@android:color/holo_green_dark</item>
</style>
```

![image](https://user-images.githubusercontent.com/38008900/162358924-19e79c34-f685-487c-bdaa-d1adb07c373c.png)

**Minimal sample app repro:** 
N/A

**Android API version:** SDK 21

**Material Library version:** 1.6.0-beta01

**Device:** Samsung J1

**Comment by ArcherEmiya05** [comment]
Worth mentioning that the background color does not work as well when using `colorSurface` and `colorOnSurface` as stated in the documentation

**Comment by dsn5ft** [comment]
The [default toolbar style](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/lib/java/com/google/android/material/appbar/res/values/styles.xml#L193-L201) is not really a "surface" toolbar (it's a transparent as per the initial design of AppCompat toolbars which can be embedded within other containers), so that's why none of those surface colors are having an effect.

If you use the [Surface](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/lib/java/com/google/android/material/appbar/res/values/styles.xml#L213-L218) or [OnSurface](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/lib/java/com/google/android/material/appbar/res/values/styles.xml#L203-L211) style then it should work more as you expect.

**Comment by ArcherEmiya05** [comment]
> The [default toolbar style](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/lib/java/com/google/android/material/appbar/res/values/styles.xml#L193-L201) is not really a "surface" toolbar (it's transparent as per the initial design of AppCompat toolbars which can be embedded within other containers), so that's why none of those surface colors are having an effect.
> 
> If you use the [Surface](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/lib/java/com/google/android/material/appbar/res/values/styles.xml#L213-L218) or [OnSurface](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/lib/java/com/google/android/material/appbar/res/values/styles.xml#L203-L211) style then it should work more as you expect.

I tried to change the parent to `Widget.Material3.Toolbar.OnSurface` still doesn't work. I also tried to change from `toolbarStyle` to `toolbarSurfaceStyle` but no luck. Can you show a sample? Thanks

**Comment by ArcherEmiya05** [comment]
I am having similar issue setting `materialThemeOverlay` on other component as well like Chips

**Comment by dsn5ft** [comment]
Re: a sample, if I add the following to our [Catalog demo app theme](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/catalog/java/io/material/catalog/application/theme/res/values/themes.xml#L19), then the surface colors get applied as expected to the [`toolbarSurfaceStyle` `MaterialToolbar`s](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/catalog/java/io/material/catalog/topappbar/res/layout/cat_topappbar_toolbar_fragment.xml#L39-L54):

    <item name="colorSurface">@android:color/holo_red_dark</item>
    <item name="colorOnSurface">@android:color/holo_blue_dark</item>
    <item name="colorOnSurfaceVariant">@android:color/holo_green_dark</item>

![image](https://user-images.githubusercontent.com/1420597/162509357-ec4756d5-db5b-4515-be06-a30fd7f754ea.png)

**Comment by ArcherEmiya05** [comment]
> Re: a sample, if I add the following to our [Catalog demo app theme](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/catalog/java/io/material/catalog/application/theme/res/values/themes.xml#L19), then the surface colors get applied as expected to the [`toolbarSurfaceStyle` `MaterialToolbar`s](https://github.com/material-components/material-components-android/blob/2544c1f243969d4fb6ae4cc97d60d8d41fa27835/catalog/java/io/material/catalog/topappbar/res/layout/cat_topappbar_toolbar_fragment.xml#L39-L54):
> 
> ```
> <item name="colorSurface">@android:color/holo_red_dark</item>
> <item name="colorOnSurface">@android:color/holo_blue_dark</item>
> <item name="colorOnSurfaceVariant">@android:color/holo_green_dark</item>
> ```
> 
> ![image](https://user-images.githubusercontent.com/1420597/162509357-ec4756d5-db5b-4515-be06-a30fd7f754ea.png)

Thanks I already made it work but having last issue with Action items icon (showAsAction).

![image](https://user-images.githubusercontent.com/38008900/162588814-59306c1b-9bce-4b44-a454-93d98a3cc4cb.png)
![image](https://user-images.githubusercontent.com/38008900/162588823-2665b693-de42-4de5-95b0-cea338bd5548.png)

When an Action item is showed as action, the drawable XML icon is not following the `colorOnSurfaceVariant` and stuck to its own color.

**Comment by dsn5ft** [comment]
It should follow the color as long as the icon is a theme-able vector drawable, e.g. like the ones created by Android Studio and [the one in my sample above](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/assets/res/drawable/ic_favorite_vd_theme_24px.xml). These types of drawables usually use `colorControlNormal` internally, and then in the Material styling we remap `colorControlNormal` to `colorOnSurfaceVariant`.

**Comment by ArcherEmiya05** [comment]
> It should follow the color as long as the icon is a theme-able vector drawable, e.g. like the ones created by Android Studio and [the one in my sample above](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/assets/res/drawable/ic_favorite_vd_theme_24px.xml). These types of drawables usually use `colorControlNormal` internally, and then in the Material styling we remap `colorControlNormal` to `colorOnSurfaceVariant`.

For some reason it does not work, as you can see above they are XML drawable and the Toolbar navigation icon works fine and follows `colorOnSurface` but the action item search that set `showAsAction="collapseActionView|ifRoom"` is not following `colorControlNormal` nor `colorOnSurfaceVariant`. Only the 3 dot action item icon does follow.

**Comment by dsn5ft** [comment]
It's hard to say why - can you try comparing your code to our demo code in the sample I linked above? And pasting our demo code into your app to see if it works, and vice versa?

**Comment by ArcherEmiya05** [comment]
> It's hard to say why - can you try comparing your code to our demo code in the sample I linked above? And pasting our demo code into your app to see if it works, and vice versa?

Alright will check it

**Comment by ArcherEmiya05** [comment]
> It's hard to say why - can you try comparing your code to our demo code in the sample I linked above? And pasting our demo code into your app to see if it works, and vice versa?

This one?

https://github.com/material-components/material-components-android/tree/master/lib/java/com/google/android/material

**Comment by dsn5ft** [comment]
This one: https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/topappbar

**Comment by ArcherEmiya05** [comment]
Is there a way to apply `toolbarSurfaceStyle` globally together with `toolbarStyle`? The toolbar title and subtitle padding went crazy after applying `toolbarSurfaceStyle`.

**Comment by ArcherEmiya05** [comment]
> It should follow the color as long as the icon is a theme-able vector drawable, e.g. like the ones created by Android Studio and [the one in my sample above](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/assets/res/drawable/ic_favorite_vd_theme_24px.xml). These types of drawables usually use `colorControlNormal` internally, and then in the Material styling we remap `colorControlNormal` to `colorOnSurfaceVariant`.

Sorry but I just wanted to reiterate this, specifically the part where `colorControlNormal` is being remapped to `colorOnSurfaceVariant` as it seems that still not the case for version `1.13.x`.

<img width="1878" alt="Image" src="https://github.com/user-attachments/assets/50e05fc1-278f-4771-848e-61edd6be080f" />

<img width="288" alt="Image" src="https://github.com/user-attachments/assets/a3aaf9dd-c00d-49fc-b8b1-0921e4dbeaa1" />

Theme
```
    <!-- Toolbar style on both light and night mode -->
    <style name="MDCToolbar" parent="Widget.Material3.Toolbar.Surface" tools:keep="@style/MDCToolbar">
        <item name="contentInsetStart">0dp</item>
        <item name="contentInsetEnd">0dp</item>
        <item name="contentInsetStartWithNavigation">0dp</item>
        <item name="materialThemeOverlay">@style/ThemeOverlay.MDC.Toolbar</item>
    </style>

    <style name="ThemeOverlay.MDC.Toolbar" parent="" tools:keep="@style/ThemeOverlay_MDC_Toolbar">
        <!-- Background color -->
        <item name="colorSurface">@color/mdc_colorWhite_Primary</item>
        <!-- Title and Navigation icon color -->
        <item name="colorOnSurface">@color/mdc_colorPrimaryDark_White</item>
        <!-- Subtitle and Action item color -->
        <item name="colorOnSurfaceVariant">@color/orange</item>
    </style>
```


Application
```
    <style name="Theme.Cryptonian" parent="Theme.Material3.DayNight">
          <item name="toolbarStyle">@style/MDCToolbar</item>
   </style>
```

As you can see the `colorOnSurfaceVariant` was set to orange and the drawable tint was set to `?attr/colorControlNormal` yet there is no mapping happening on both preview and actual app.
