### ISSUE TITLE
FAB is missing

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2634]
**Description:**
The documentation shows that there is `Widget.Material3.FloatingActionButton` but when tried to use it as parent, no such component exist.
![image](https://user-images.githubusercontent.com/38008900/162507580-c693cbcf-e568-4d7f-9e3c-66285ecc83ce.png)

**Source code:** 
![image](https://user-images.githubusercontent.com/38008900/162507658-fe87cf3b-448d-4ebd-a532-cad86c8cc54f.png)

**Material Library version:** 1.6.0-beta01

**Comment by drchen** [comment]
Ah I think our dev doc is incorrect. You should use Widget.Material3.FloatingActionButton.Primary instead.

**Comment by ArcherEmiya05** [comment]
> Ah I think our dev doc is incorrect. You should use Widget.Material3.FloatingActionButton.Primary instead.

Unfortunately still doesn't work

**Comment by drchen** [comment]
It should. Can you elaborate what you mean by "doesn't work"? What's the compilation error if any?

**Comment by ArcherEmiya05** [comment]
> It should. Can you elaborate what you mean by "doesn't work"? What's the compilation error if any?

Sorry, nothing happens even after using `Widget.Material3.FloatingActionButton.Primary` as a parent

**Comment by pradie-charlotte** [comment]
@ArcherEmiya05 , same issue encountered.
Widget.Material3.FloatingActionButton isn't available, you need to use Widget.Material3.FloatingActionButton.Primary. This implies to set the color "colorOnPrimaryContainer" and not "colorOnContainer" as planned. I guess you'll have to do the same for "colorContainer"

**Comment by ArcherEmiya05** [comment]
It works now.

```
<style name="AppFab" parent="Widget.Material3.FloatingActionButton.Primary">
        <item name="materialThemeOverlay">@style/ThemeOverlay.App.FloatingActionButton</item>
        <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.Material3.FloatingActionButton</item>
    </style>
    <style name="ThemeOverlay.App.FloatingActionButton" parent="">
        <!-- Background color -->
        <item name="colorContainer">@color/accentPrimary</item>
        <!-- Icon color -->
        <item name="colorOnContainer">@color/primaryDarkAccent</item>
</style>
```

Use it on theme like this

`<item name="floatingActionButtonStyle">@style/AppFab</item>`

**Comment by ArcherEmiya05** [comment]
> @ArcherEmiya05 , same issue encountered. Widget.Material3.FloatingActionButton isn't available, you need to use Widget.Material3.FloatingActionButton.Primary. This implies to set the color "colorOnPrimaryContainer" and not "colorOnContainer" as planned. I guess you'll have to do the same for "colorContainer"

It weird, `colorPrimaryContainer` is not working but `colorContainer` does.
