### ISSUE TITLE
[BottomNavigationView] Title is blinking when change tab

### ISSUE THREAD

**Issue by vladislav-t** [material-components/material-components-android#2637]
Hi, we try to disable change tab animation and doesn't succeed, can you explain how can we do it?

'com.google.android.material:material:1.6.0-beta01' - dependency version

NavigationView implementation:

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:background="@color/colorWhite"
        android:visibility="gone"
        app:itemTextAppearanceActive="@style/BottomNavigationView"
        app:itemTextAppearanceInactive="@style/BottomNavigationViewInactive"
        app:labelVisibilityMode="labeled"
        app:menu="@menu/navigation" />

https://user-images.githubusercontent.com/13637332/163186306-65d2b330-8e36-4ae2-815d-6484b1a8a905.mp4

**Comment by drchen** [comment]
Can you post your definition of `@style/BottomNavigationView` and `@style/BottomNavigationViewInactive` as well?

**Comment by NTPaa** [comment]
> Hi, we try to disable change tab animation and doesn't succeed, can you explain how can we do it?
> 
> 'com.google.android.material:material:1.6.0-beta01' - dependency version
> 
> NavigationView implementation:
> 
>     <com.google.android.material.bottomnavigation.BottomNavigationView
>         android:id="@+id/navigation"
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:layout_alignParentBottom="true"
>         android:background="@color/colorWhite"
>         android:visibility="gone"
>         app:itemTextAppearanceActive="@style/BottomNavigationView"
>         app:itemTextAppearanceInactive="@style/BottomNavigationViewInactive"
>         app:labelVisibilityMode="labeled"
>         app:menu="@menu/navigation" />
> 
> https://user-images.githubusercontent.com/13637332/163186306-65d2b330-8e36-4ae2-815d-6484b1a8a905.mp4
> 
>

**Comment by vladislav-t** [comment]
> Can you post your definition of `@style/BottomNavigationView` and `@style/BottomNavigationViewInactive` as well?

    <style name="BottomNavigationView" parent="@style/TextAppearance.AppCompat.Caption">
        <item name="android:textSize">12sp</item>
        <item name="android:fontFamily">@font/roboto_regular</item>
        <item name="android:textColor">@color/colorViolet</item>
    </style>

    <style name="BottomNavigationViewInactive" parent="@style/TextAppearance.AppCompat.Caption">
        <item name="android:fontFamily">@font/roboto_regular</item>
    </style>
