### ISSUE TITLE
strokeColor not working for MaterialCardView

### ISSUE THREAD

**Issue by imecstamas** [material-components/material-components-android#264]
Hi! 
I wanted to add a border to a MaterialCardView from the dependency: com.google.android.material:material:1.0.0, but the strokeColor isn't applied.

**Comment by bernaferrari** [comment]
Any screenshots or code?

**Comment by imecstamas** [comment]
Hi!
Sorry, it is working now, I'm not sure what I missed. My bad. You can close this issue.
Thanks,
Tamas

**Comment by consp1racy** [comment]
The theme has to be a material theme. MaterialCardView didn't enforce that in 1.0.0.

**Comment by iSpri** [comment]
I had the same problem: the stroke color was always white. I noticed that this behavior was triggered by the `app:cardUseCompatPadding="true"` property. By removing it, the stroke color should be working as expected. Not sure if it's a bug or if I missunderstood what "compat padding" is.

**Comment by consp1racy** [comment]
Compat padding is always enabled on Android 4. Can you test how it behaves there?

**Comment by lucferbux** [comment]
Hi, i have the same issue when I apply a white color as stroke color, the rest colors are great.

**Comment by grvgoel81** [comment]
stroke color is not working foe me. see below example :
<com.google.android.material.card.MaterialCardView
            android:id="@+id/profileCardLayout"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:cardCornerRadius="@dimen/margin_4"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:rippleColor="@android:color/holo_orange_dark"
            app:strokeColor="@color/primaryOrange"
            app:cardUseCompatPadding="true"
            app:strokeWidth="1dp">

let me know if I am doig something wrong.

**Comment by anshugarva** [comment]
@grvgoel81 I guess you need to remove 
app:cardUseCompatPadding="true"

**Comment by niranjandawadi** [comment]
Hi, I think there is an issue related to stroke color. I have written a code to deselect the card view but it isn't working.

**Comment by ornolisvt** [comment]
Use invalidate() on Material CardView after setting the strokeColor programmatically. This works for me

**Comment by ahmed7official** [comment]
> Use invalidate() on Material CardView after setting the strokeColor programmatically. This works for me

worked with me

**Comment by drchen** [comment]
Hi @ilyassesalama, the fix was pushed after 1.4.0 is released. 

If you can't use 1.5.0 alpha versions, calling invalidate() after setting stroke color will be the workaround.

**Comment by Dennis6022** [comment]
<com.google.android.material.card.MaterialCardView
            android:id="@+id/card_lifetime"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="16dp"
            android:layout_columnWeight="1"
            app:cardElevation="0dp"
            app:cardCornerRadius="20dp"
            style="@style/Widget.Material3.CardView.Elevated"
            app:strokeWidth="1dp">  


Use this .
