### ISSUE TITLE
Chip materialThemeOverlay is not working

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2641]
**Description:** 
The implementation with Chip in Material 3 is not working after following the [documentation](https://m3.material.io/components/chips/implementation)

**Expected behavior:** 
Should apply the styling based on what was stated in the documentation.

**Source code:** 

Not working, incorrect color.
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Chip style on both light and night mode -->
    <style name="AppChip" parent="Widget.Material3.Chip.Input">
        <item name="closeIconVisible">false</item>
        <item name="checkedIconVisible">false</item>
        <item name="materialThemeOverlay">@style/ThemeOverlay.App.Chip</item>
        <item name="shapeAppearanceOverlay">@style/ShapeAppearance.App.SmallComponent</item>
    </style>
    <style name="ThemeOverlay.App.Chip" parent="">
        <item name="colorOnSurfaceVariant">@color/chip_state_list</item>
        <item name="colorOnSurface">@color/background_color_chip_state_list</item>
    </style>
</resources>
```

Working correct color
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Chip style on both light and night mode -->
    <style name="AppChip" parent="Widget.Material3.Chip.Input">
        <item name="closeIconVisible">false</item>
        <item name="checkedIconVisible">false</item>
        <item name="android:textColor">@color/chip_state_list</item>
        <item name="chipStrokeColor">@android:color/transparent</item>
        <item name="chipBackgroundColor">@color/background_color_chip_state_list</item>
        <item name="shapeAppearanceOverlay">@style/ShapeAppearance.App.SmallComponent</item>
    </style>
    <!--TODO theme overlay-->
</resources>
```

Usage in main theme
`<item name="chipStyle">@style/AppChip</item>`

**Android API version:** SDK 21

**Material Library version:** 1.6.0-beta-01

**Device:** Samsung J1

Is it just me or the Material 3 components and its documentations are not yet finish or finalize? I keep having this issue where the documentation and the behavior is not correct.

**Comment by danielwilson1702** [comment]
I have a[ similar issue on SO](https://stackoverflow.com/q/71887041/1866373) - a very simple button trying to migrate from M2 to M3. So maybe you can tell me if your setup is also not working for Buttons?

I am wondering how this a beta release if the `materialThemeOverlay` is broken?!

**Comment by ArcherEmiya05** [comment]
> I have a[ similar issue on SO](https://stackoverflow.com/q/71887041/1866373) - a very simple button trying to migrate from M2 to M3. So maybe you can tell me if your setup is also not working for Buttons?
> 
> I am wondering how this a beta release if the `materialThemeOverlay` is broken?!

Yes button is working on my side

**Comment by drchen** [comment]
@ArcherEmiya05 the color attributes you are overriding in your theme overlay is not correct, if your intention is to change the background color of your chips. (You should override `?attr/colorSurface`, not `?attr/colorOnSurface`.)

@danielwilson1702 I apologize for the confusion, [the answer on SO](https://stackoverflow.com/a/71898927) is right - you need to extend your theme overlay from `ThemeOverlay.Material3.Button` to make it work.

**Comment by ArcherEmiya05** [comment]
> @ArcherEmiya05 the color attributes you are overriding in your theme overlay is not correct, if your intention is to change the background color of your chips. (You should override `?attr/colorSurface`, not `?attr/colorOnSurface`.)
> 
> @danielwilson1702 I apologize for the confusion, [the answer on SO](https://stackoverflow.com/a/71898927) is right - you need to extend your theme overlay from `ThemeOverlay.Material3.Button` to make it work.

It is not working properly with check state.

```
<resources>
    <!-- Chip style on both light and night mode -->
    <style name="AppChip" parent="Widget.Material3.Chip.Input">
        <item name="closeIconVisible">false</item>
        <item name="checkedIconVisible">false</item>
        <item name="chipStrokeColor">@android:color/transparent</item>
        <item name="android:textColor">@color/chip_state_list</item>
        <item name="materialThemeOverlay">@style/ThemeOverlay.App.Chip</item>
        <item name="shapeAppearanceOverlay">@style/ShapeAppearance.App.SmallComponent</item>
    </style>

    <style name="ThemeOverlay.App.Chip" parent="">
        <item name="colorSurface">@color/background_color_chip_state_list</item>
    </style>
</resources>
```

RESULT

![image](https://user-images.githubusercontent.com/38008900/163880516-9027ba80-17bc-455d-bf90-45cca009a735.png)

The old style code that works 

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Chip style on both light and night mode -->
    <style name="AppChip" parent="Widget.Material3.Chip.Input">
        <item name="closeIconVisible">false</item>
        <item name="checkedIconVisible">false</item>
        <item name="android:textColor">@color/chip_state_list</item>
        <item name="chipStrokeColor">@android:color/transparent</item>
        <item name="chipBackgroundColor">@color/background_color_chip_state_list</item>
        <item name="shapeAppearanceOverlay">@style/ShapeAppearance.App.SmallComponent</item>
    </style>
    <!--TODO theme overlay-->
</resources>
```

RESULT

![image](https://user-images.githubusercontent.com/38008900/163880843-373488af-e9d8-42a7-b7fa-beaac9f35b4d.png)

**Comment by drchen** [comment]
I doesn't work because chipBackgroundColor doesn't directly point to colorSurface. 

The default value is a CSL which switches its color between colorSurface and colorSecondaryContainer.
To make it work with materialThemeOverlay, you will need to override colorSurface and colorSecondaryContainer separately, instead of overriding colorSurface with an CSL.

**Comment by ArcherEmiya05** [comment]
> I doesn't work because chipBackgroundColor doesn't directly point to colorSurface.
> 
> The default value is a CSL which switches its color between colorSurface and colorSecondaryContainer. To make it work with materialThemeOverlay, you will need to override colorSurface and colorSecondaryContainer separately, instead of overriding colorSurface with an CSL.

It works!  Thanks. How about for its text color?

**Comment by drchen** [comment]
I think it's using colorOnSecondaryContainer (selected) and colorOnSurfaceVariant (unselected.)
