### ISSUE TITLE
[Color] HarmonizedColorsOptions.Builder#setColorAttributes is marked as nullable

### ISSUE THREAD

**Issue by RikkaW** [material-components/material-components-android#2650]
https://github.com/material-components/material-components-android/blob/788866e4483621e2222f649e617ee95f7aa9caa6/lib/java/com/google/android/material/color/HarmonizedColorsOptions.java#L105-L109

This should be marked as `NonNull`.

**Comment by dsn5ft** [comment]
https://github.com/material-components/material-components-android/commit/824a12b7c80703d59a909496f3dbe0126d0dd899
