### ISSUE TITLE
slider widget bug

### ISSUE THREAD

**Issue by langyangyangzzZ** [material-components/material-components-android#2665]
After the Slider component slides, there will be a bug, and the display bar will not disappear

**Comment by dsn5ft** [comment]
@langyangyangzzZ can you provide more explanation and screenshots?

**Comment by langyangyangzzZ** [comment]
I remember the 1.5 version I downloaded, there will be residues after the slide is completed

![9E6BFA5AC56BB55DA0470E277A365C33](https://user-images.githubusercontent.com/54341625/165203650-6d7814a7-287b-4528-962c-63bc05ddfbcb.gif)

**Comment by dsn5ft** [comment]
What API level and device type are you using? I don't see this happening on my emulator running API level 32.

Also can you try with [1.7.0-alpha01](https://github.com/material-components/material-components-android/releases/tag/1.7.0-alpha01)?

**Comment by langyangyangzzZ** [comment]
I have tried android api26 and api30 without any problem, my device is Huawei TNY-AL00 HarmonyOS 2.0 Is it related to HarmonyOS?

**Comment by langyangyangzzZ** [comment]
sorry i tried most android studio devices and found no problem, i'm trying it thanks

**Comment by dsn5ft** [comment]
Thanks for checking - it does seem like it could be an OS bug, so I'm going to close the issue here (unless we can reproduce it easily on other devices). Maybe you could try filing a bug to HarmonyOS?
