### ISSUE TITLE
[Snackbar] Each `show()` call adds an extra bottom indent

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#2666]
**How to reproduce:** 
- Create a `Snackbar` object
- Call `show()` on this object
- Wait for the snackbar to disappear
- Call `show()` on this object again
- Notice that the snackbar appeared higher than the previous time

Here's how it can be reproduced in `DatePickerMainDemoFragment`:

https://user-images.githubusercontent.com/82187521/165288976-6cbe2ab8-e8cd-45c5-af3e-55b9d8ec4c53.mp4

**Material Library version:** 1.6.0-rc01

**Comment by dsn5ft** [comment]
@drchen can you check if this is a regression caused by https://github.com/material-components/material-components-android/commit/d5856fd0365b4daeb27f07c8864d88618884dfb8? I remember handling this case in the original implementation of Snackbar margins.
