### ISSUE TITLE
[MaterialDatePicker] Broken ripple

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#2668]
This is how ripple looks in DatePicker on my device (circled in red, click to open picture in large size):

<img src="https://user-images.githubusercontent.com/82187521/165321081-90d8f23e-dd56-47c1-b5ad-858b567d89fe.png" width="300" />

This is how it looks on the video:
<details>
<summary>Open video (don't forget to expand to fullscreen)</summary>
<video src="https://user-images.githubusercontent.com/82187521/165321940-5a1d89d2-cd22-49c6-a99e-23be1e9fd5a7.mp4" />
</details>

**Material Library version:** 1.6.0-rc01

**Device:** Pixel 4a 5G
**Android API version:** Android 12 (Build SP2A.220405.003)

**Comment by pubiqq** [comment]
I also observe this issue on the emulator (Pixel 4 API 31):
<img src="https://user-images.githubusercontent.com/82187521/165331627-8faee26d-5383-45c4-addf-d2932718211d.png" />

**Comment by dsn5ft** [comment]
This was a framework ripple issue (similar to https://github.com/material-components/material-components-android/issues/2617) which has been fixed for future versions of the OS.
