### ISSUE TITLE
[CircularProgressIndicator] The circular indicator is incorrectly aligned inside the chip

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#2669]
This can be observed in `ProgressIndicatorStandaloneDemoFragment`:
<table>
<tr><td width="504"><video src="https://user-images.githubusercontent.com/82187521/165346886-d24c3f68-59c1-44ab-ac4d-09aeb7c12eac.mp4" loop /></td></tr>
<table>

**Material Library version:** 1.6.0-rc01

**Comment by drchen** [comment]
Duplicate of https://github.com/material-components/material-components-android/issues/2364 (fixed.)
