### ISSUE TITLE
Android minifyEnabled true TextInputLayout runtime crash

### ISSUE THREAD

**Issue by kecoli2** [material-components/material-components-android#2671]
**Description:** Hello
When I set minifyEnabled to true, the program gives an error during execution. Could you help me find the cause of the error?
.Gradle version 7.4.2 Gradle plugin version 7.1.3

**Source code:**  minifyEnabled true

**Android API version:** 31

**Material Library version:**  1.5.0
**Error:**   **java.lang.VerifyError: Rejecting class com.univera.components.UniveraTextInputLayout that attempts to sub-type erroneous class com.google.android.material.textfield.TextInputLayout (declaration of 'com.univera.components.UniveraTextInputLayout' appears in /data/app/~~l4F8bR8FWe8-GWkOvvXIIw==/com.univera.android-3jAsHCcz7uWysEdLbKVf5w==/base.apk!classes3.dex)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)**

My proguard.prof 

# Panorama Mobile classes - many of them loaded via class loader

-libraryjars libs/bixolon_printer_V2.1.2P02.jar
-libraryjars libs/DataCollection.jar
-libraryjars libs/libcommon_V1.0.9P01.jar
-libraryjars libs/libcommon_V1.1.1.jar
-libraryjars libs/mpandroidchartlibrary-2-1-0.jar
-libraryjars libs/PatchServices.jar
-libraryjars libs/platform_sdk_v2.3.602.jar

-keep class com.univera.** { *; }
-keep class  android.widget.** {*;}
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keepattributes InnerClasses
-dontwarn java.util.concurrent.**
-dontwarn com.google.errorprone.annotation

# Moshi Configuration
-dontwarn okio.**
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault

# HTTP OK Moshi
-dontwarn com.squareup.okhttp.**

# google
-keep class com.google.**
-dontwarn com.google.**

## https://developer.android.com/google/play-services/setup.html#Proguard ##

-keep class com.google.android.gms.internal.** { *; }
-dontwarn com.google.android.gms.internal.**

-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
    public static final *** NULL;
}

-keepnames @com.google.android.gms.common.annotation.KeepName class *

-keepclassmembernames class * {
    @com.google.android.gms.common.annotation.KeepName *;
}

-keep class **$Properties

-keepnames class * implements android.os.Parcelable {
    public static final ** CREATOR;
}

# FireBase
-keep class com.google.firebase.quickstart.database.java.viewholder.** {*;}
-keepclassmembers class com.google.firebase.quickstart.database.java.models.** {*;}
-keepclassmembers class com.google.firebase.quickstart.database.kotlin.models.** {*;}

#Zing.Core Lib Bos Gecildi

#EverNote Configuration

-dontwarn com.evernote.android.job.gcm.**
-dontwarn com.evernote.android.job.GcmAvailableHelper
-dontwarn com.evernote.android.job.work.**
-dontwarn com.evernote.android.job.WorkManagerAvailableHelper

-keep public class com.evernote.android.job.v21.PlatformJobService
-keep public class com.evernote.android.job.v14.PlatformAlarmService
-keep public class com.evernote.android.job.v14.PlatformAlarmReceiver
-keep public class com.evernote.android.job.JobBootReceiver
-keep public class com.evernote.android.job.JobRescheduleService
-keep public class com.evernote.android.job.gcm.PlatformGcmService

#RetRofit 2
-keep class com.google.gson.** { *; }
-keep public class com.google.gson.** {public private protected *;}
-keep class com.google.inject.** { *; }
-keep class org.apache.http.** { *; }
-keep class org.apache.james.mime4j.** { *; }
-keep class javax.inject.** { *; }
-keep class javax.xml.stream.** { *; }
-keep class retrofit.** { *; }
-keep class com.google.appengine.** { *; }
-dontwarn rx.**
-dontwarn javax.xml.stream.**
-dontwarn com.google.appengine.**
-dontwarn java.nio.file.**
-dontwarn org.codehaus.**
-dontwarn retrofit2.**
-dontwarn org.codehaus.mojo.**
-keep class retrofit2.** { *; }
-keepattributes Exceptions
-keepattributes RuntimeVisibleAnnotations
-keepattributes RuntimeInvisibleAnnotations
-keepattributes RuntimeVisibleParameterAnnotations
-keepattributes RuntimeInvisibleParameterAnnotations
-keepattributes EnclosingMethod

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
-keepclasseswithmembers interface * {
    @retrofit2.* <methods>;
}
# Platform calls Class.forName on types which do not exist on Android to determine platform.
-dontnote retrofit2.Platform
# Platform used when running on Java 8 VMs. Will not be used at runtime.
-dontwarn retrofit2.Platform$Java8
# Retain declared checked exceptions for use by a Proxy instance.
-keepattributes Exceptions

-optimizationpasses 5
#-allowaccessmodification
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-verbose

#your package path where your gson models are stored
-keep class com.jutt.example1.model.** { *; }

# Retrofit, OkHttp, Gson

-dontwarn com.squareup.okhttp.**
-dontwarn rx.**
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

# OkHttp3
-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# Rxjava-promises

-keep class com.darylteo.rx.** { *; }

-dontwarn com.darylteo.rx.**

# RxJava 0.21

-keep class rx.schedulers.Schedulers {
    public static <methods>;
}
-keep class rx.schedulers.ImmediateScheduler {
    public <methods>;
}
-keep class rx.schedulers.TestScheduler {
    public <methods>;
}
-keep class rx.schedulers.Schedulers {
    public static ** test();
}
## Retrolambda specific rules ##

# as per official recommendation: https://github.com/evant/gradle-retrolambda#proguard
-dontwarn java.lang.invoke.*

**Comment by dsn5ft** [comment]
This doesn't look very specific to the Material library, can you repost on StackOverflow?
