### ISSUE TITLE
DynamicColors device support check excludes Samsung devices not using OneUI

### ISSUE THREAD

**Issue by xeals** [material-components/material-components-android#2677]
**Description:** The `DeviceSupportCondition`-based behaviour of `DynamicColors.isDynamicColorAvailable()` introduced in https://github.com/material-components/material-components-android/commit/817dc124bbde8801dcd4b9f7b6f4c0be944f8bfd excludes Samsung devices supporting SDK version S but do not have the OneUI build property available. This impacts popular third-party ROMs such as LineageOS, based on AOSP 12.1, which otherwise support dynamic colours.
**Expected behavior:** Devices not running OneUI are not excluded.

[Here](https://user-images.githubusercontent.com/21125058/166131381-c6512ef5-ed7f-4f71-bfb8-031bc1126459.png) is a contrast of two applications which support dynamic colours and use the library in the same way: the top is [Tachiyomi v0.13.4](https://github.com/tachiyomiorg/tachiyomi/blob/v0.13.4/app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt#L74=), built with Material Library v1.6.0-alpha1 (which does not have the offending commit); and the bottom is [TachiyomiJ2K v1.5.0](https://github.com/Jays2Kings/tachiyomiJ2K/blob/v1.5.0/app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt#L105=), built with Material Library v1.5.0 (which does). Note that the bottom application does not offer the dynamic theme. When used on a Google device using the same ROM, [the option is available](https://user-images.githubusercontent.com/21125058/166131521-52cdcba4-a12f-4d54-83ef-90e7dd6e6524.png).

**Source code:** https://github.com/material-components/material-components-android/commit/817dc124bbde8801dcd4b9f7b6f4c0be944f8bfd

**Material Library version:** Affects v1.5.0, v1.6.0-alpha2, v1.7.0-alpha1, and all later versions.

**Device:** Samsung Galaxy Tab S5e

**Comment by dsn5ft** [comment]
Hi @xeals, unfortunately we don't have all of the information we would need to put together a scalable allow-list based on OS/ROM - this was specifically meant as a short-term solution for Android S.

In Android T the Dynamic Color support will be more built-in to the core Android OS, and at that point we are planning on updating our utility class to not use an allow-list so that Dynamic Color will be enabled for all devices running T.

**Comment by TheLastProject** [comment]
> In Android T the Dynamic Color support will be more built-in to the core Android OS, and at that point we are planning on updating our utility class to not use an allow-list so that Dynamic Color will be enabled for all devices running T.

Any update on this @dsn5ft? If I understand https://github.com/material-components/material-components-android/blob/ed77ab36ccac98df24e55060d58406c5981a9062/lib/java/com/google/android/material/color/DynamicColors.java#L55-L72 correctly the latest development branch seems to still exclude all Samsung devices that lack OneUI (aka: LineageOS and other custom ROM users).
