### ISSUE TITLE
Fling conflict with AppbarLayout.Behavior

### ISSUE THREAD

**Issue by pan-haos** [material-components/material-components-android#268]
Hi,I use AppbarLayout and CollapsingToolbarLayout with it nested layout , the layout has long height so when I fling the layout to bottom quickly and drag it to top at the same time , there is a fling conflict happend , Now I only resolve it by reflect the field "scroller",but it's really not a good way to solve it ,when we upgrade the lib ,it may useless. so did I have a elegant way to solve it ,or will the official fix this bug in a subsequent version?

**Comment by ymarian** [comment]
Can you add a video with the behavior you are seeing?

**Comment by paradise0love** [comment]
https://user-images.githubusercontent.com/11945199/111982039-6f38df80-8b43-11eb-8bf5-d169fcdc699c.MP4

**Comment by paradise0love** [comment]
![image](https://user-images.githubusercontent.com/11945199/111982213-a909e600-8b43-11eb-994f-43cd6a5aefea.png)
![image](https://user-images.githubusercontent.com/11945199/111982444-f0907200-8b43-11eb-9207-28d0433f450b.png)
