### ISSUE TITLE
chipGroup.getCheckedChipIds() does not seem to update

### ISSUE THREAD

**Issue by NLLAPPS** [material-components/material-components-android#2691]
I don't have time to create a sample app to show the bug but chipGroup.getCheckedChipIds() does not seem to return up to date list of checked chips.

My use case is doing search as user taps and checks/unchecks filters. I used to rely on getCheckedChipIds to filter search results. Just noticed that it does not return up to date list of checked items. Cannot say which version broke it.

chipGroup.children.filter { (it as? Chip)?.isChecked ?: false }.map { it.id } works fine

Version I am using is 1.6.0

**Comment by NLLAPPS** [comment]
In my case I simply call getCheckedChipIds() once user checks/unchecks one of them

**Comment by m-melis** [comment]
Confirmed with version 1.6, was fine in 1.5.*

**Comment by dsn5ft** [comment]
@drchen this seems like a change in behavior due to https://github.com/material-components/material-components-android/commit/f3c6430f94bb7f82afc740e5545fd6302e9bf3aa which first made it into 1.6.0?

**Comment by drchen** [comment]
I'll take alook.

**Comment by drchen** [comment]
Hi so I think the root cause is that OnCheckedChangeListener.onCheckedChanged() is called before ChipGroup's internal data structure is updated. 

I'll work on a fix of this. In the meantime I'll suggest you to use ChipGroup.OnCheckedStateChangeListener instead, which should work correctly.
