### ISSUE TITLE
[ModalBottomSheetLayout] Scrim gets dismissed upon swiping 

### ISSUE THREAD

**Issue by aaleksievcmc** [material-components/material-components-android#2693]
**Description:** Bottom sheet scrim gets dismissed upon swiping even when confirmStateChange returns false and this makes the content behind the bottom sheet tappable 

**Expected behavior:** Scrim gets dismissed when bottom sheet is dismissed

**Source code:** 
val bottomSheetState: ModalBottomSheetState = rememberModalBottomSheetState(
    initialValue = Hidden,
    skipHalfExpanded = true,
    confirmStateChange = { false },
  )

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** Android API 30

**Material Library version:** 1.2.0-alpha05

**Comment by drchen** [comment]
Can you update to the latest library version and see if it's still happening?

A screen recording will help us to identify the issue, too!

**Comment by aaleksievcmc** [comment]
Updated to latest androidx.compose.material:material:1.2.0-beta02 but this is still the case. As will see at the attached video though the ModalBottomSheet is not dismissible the scrim gets removed at some point and the content behind the bottom sheet becomes tappable   


https://user-images.githubusercontent.com/98051026/169500948-a6ec3905-5943-45cc-856c-e526d9966466.mp4

**Comment by drchen** [comment]
Ah, so you are using Compose, right? Sorry that I didn't notice it when I first replied.

Here's the instruction how you file a Compose bug: https://source.android.com/setup/contribute/report-bugs

Let me know if this helps. I'll close the bug. : )

**Comment by aaleksievcmc** [comment]
That's the most useless response. Compose is not even listed on that page, you should've checked before just bluntly pasted a useless link

**Comment by drchen** [comment]
Did you read the instruction in the page carefully and follow the steps under "Filing a bug"? It shouldn't be too hard to click the link, open the page, and search for "Compose". : )

If you still can't find it, please try this link:
https://issuetracker.google.com/issues?q=status:open%20componentid:612128&s=created_time:desc

Fyi, I'm not working on Compose, and I also need to follow the above steps to get the link.
