### ISSUE TITLE
[BottomNavigationView] Overlapped menu names and icons.

### ISSUE THREAD

**Issue by unaisulhadi** [material-components/material-components-android#2694]
**Description:** When I updated material version to 1.5.0, BottomNavigationView in my project, found menu and icons are overlapped each other. (screenshots attached below).

**Real behavior:** 

![WhatsApp Image 2022-05-09 at 3 36 10 PM](https://user-images.githubusercontent.com/28825858/167390114-1d4e0d1d-a405-4bd1-a951-bdf45d02e165.jpeg)

**Expected behavior:** 

![WhatsApp Image 2022-05-09 at 3 44 42 PM](https://user-images.githubusercontent.com/28825858/167390128-9fd73491-7150-45ad-bd65-674be4d41e38.jpeg)

**Source code:**  
Layout XML
```
<com.google.android.material.bottomnavigation.BottomNavigationView
                android:id="@+id/bottom_navbar"
                android:layout_width="match_parent"
                android:layout_height="@dimen/_55sdp"
                android:theme="@style/Widget.BottomNavigationView"
                app:background="@android:color/transparent"
                app:itemIconTint="@drawable/bottom_icon_color_selector"
                app:itemTextColor="@drawable/bottom_icon_color_selector"
                app:labelVisibilityMode="labeled"
                app:menu="@menu/navigation" />
```
bottom_icon_color_selector.xml
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/colorPrimaryDark"
        android:state_checked="true" />
    <item android:color="@color/md_grey_400" />
</selector>
```
navigation.xml
```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">

    <item
        android:id="@+id/navigation_home"
        android:icon="@drawable/ic_home_primary"
        android:title="@string/home" />

    <item
        android:id="@+id/navigation_services"
        android:icon="@drawable/ic_services_grey"
        android:title="@string/services" />

    <item
        android:id="@+id/navigation_contact"
        android:icon="@drawable/ic_contact_grey"
        android:title="@string/contact" />
    <item
        android:id="@+id/navigation_machine"
        android:icon="@drawable/ic_machine_primary"
        android:title="@string/my_device" />

</menu>

```
Style : Widget.BottomNavigationView
```
<style name="Widget.BottomNavigationView" parent="Widget.Design.BottomNavigationView">
        <item name="fontFamily">@font/poppins_medium</item>
        <item name="android:textSize">@dimen/_10ssp</item>
    </style>
```

**Android API version:** 32

**Material Library version:** 1.5.0

**Device:** Reported on Redmi Note 10 Pro Max and Samsung Note 9

PS: by swithing back material version to 1.4.0 fixed the bug.

**Comment by leticiarossi** [comment]
Hi, this looks similar to https://github.com/material-components/material-components-android/issues/2535 could you try one of the suggestions given there? like [this comment](https://github.com/material-components/material-components-android/issues/2535#issuecomment-1040707976) or [this one](https://github.com/material-components/material-components-android/issues/2535#issuecomment-1043289269). Also consider switching to using the Material 3 Bottom Navigation style and M3 themes

**Comment by drchen** [comment]
Do suggestions in #2535 help solve the issue?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still an issue.
