### ISSUE TITLE
[AppBarLayout] AppBarLayout not accounting for left and right insets when android:fitsSystemWindows="true"

### ISSUE THREAD

**Issue by RoiEXLab** [material-components/material-components-android#2696]
**Description:** When using translucent mode, the property `android:fitsSystemWindows="true"` can be used to fix the alignment in normal portrait mode. When turning the device and looking at it it landscape mode it turns out that the padding that got successfully applied to the top of the toolbar didn't get applied correctly to the sides as seen in this screenshot:

![Screenshot](https://user-images.githubusercontent.com/8350879/167758509-889af9fa-0f97-411f-a91f-18708dcb3fc7.png)

As you can see the control is hidden behind the navigation bar, which is really not supposed to happen.

The same is true for the other side (when turning the device 180°):

![Screenshot 2](https://user-images.githubusercontent.com/8350879/167758843-ac84da75-4793-4315-bc96-cf2e15836c41.png)

I tried finding a workaround by using `ViewCompat.setOnApplyWindowInsetsListener`, but I couldn't get it working, presumably because I'm trying to adjust the wrong values. In any case the default behaviour should handle this correctly.

**Expected behavior:** Any actual content of the Toolbar should be inside the usable screen space, not behind the navigation bar.

**Source code:** My XML basically boils down to this:

```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        app:liftOnScroll="true">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/top_app_bar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize" />

    </com.google.android.material.appbar.AppBarLayout>

    <!-- actual content here -->
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Android API version:** 31 (probably others too, didn't check)

**Material Library version:** 1.6.0

**Comment by drchen** [comment]
We have another more general bug reported here: https://github.com/material-components/material-components-android/issues/2750

Let's track the issue there and I'll close this one for now.
