### ISSUE TITLE
[BottomAppBar] Upgrade from MD2 to MD3

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#2698]
- [Overview](https://m3.material.io/components/bottom-app-bar/overview)
- [Specs](https://m3.material.io/components/bottom-app-bar/specs)
- [Guidelines](https://m3.material.io/components/bottom-app-bar/guidelines)
<img src="https://user-images.githubusercontent.com/82187521/171907918-c5a2b640-e075-459b-9c12-70dc760cac1e.png">

**Comment by manabu-nakamura** [comment]
Don't you remove the shadow?

**Comment by imhappi** [comment]
What shadow are you referring to?

The shadow on the FAB should be removed. As for the container, there is a slight elevation according to the specs: https://m3.material.io/components/bottom-app-bar/specs

**Comment by manabu-nakamura** [comment]
The BottomAppBar still casts a shadow like a divider.
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomappbar/BottomAppBar.java#L355
FYI: screenshots of https://github.com/material-components/material-components-android/issues/2852

**Comment by imhappi** [comment]
Yes, it is expected. As I mentioned in my previous comment, the container (ie. the body of the bottom app bar) has a slight elevation according to the specs.

**Comment by manabu-nakamura** [comment]
The top app bar (MaterialToolbar) casts no shadow.
[Test2.zip](https://github.com/material-components/material-components-android/files/9466976/Test2.zip)
```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <com.google.android.material.appbar.MaterialToolbar
        android:id="@+id/appBar"
        android:layout_width="match_parent"
        android:layout_height="?actionBarSize"
        android:background="?colorSurface"
        android:elevation="3dp" />
    <com.google.android.material.appbar.MaterialToolbar
        android:id="@+id/appBar2"
        android:layout_width="match_parent"
        android:layout_height="?actionBarSize"
        android:background="?colorSurface"
        android:elevation="3dp" />
</LinearLayout>
```
![Screenshot_20220901_134546](https://user-images.githubusercontent.com/71050561/187834421-5e3c0551-a72b-4e2a-b586-021ba03d82bb.png)
I can't understand the difference between the specs of BottomAppBar and MaterialToolbar.
The app bar casts no shadow?
https://m3.material.io/components/bottom-app-bar/overview
https://m3.material.io/components/top-app-bar/overview

**Comment by imhappi** [comment]
Yes, looking at the top app and specs, the elevation level is 0. For bottom app bar it’s level 2

**Comment by manabu-nakamura** [comment]
Why the elevated (on scroll) MaterialToolbar  cast no shadow?  The elevated BottomAppBar casts a shadow.

**Comment by imhappi** [comment]
The top app bar is not the material toolbar. The material toolbar is the toolbar contained within the top app bar.

You can create a top app bar following the example here: https://github.com/material-components/material-components-android/blob/master/docs/components/TopAppBar.md#using-top-app-bars

**Comment by manabu-nakamura** [comment]
I use the MaterialToolbar...

**Comment by manabu-nakamura** [comment]
Why does the BottomAppBar cast no shadow?
https://m3.material.io/components/bottom-app-bar/guidelines
![unnamed--](https://user-images.githubusercontent.com/71050561/187850574-a9dbddfe-8e0b-4a3c-ade8-de072e54ec03.png)

**Comment by imhappi** [comment]
Those images are just mocks…
they may have forgotten to add elevation in the mocks. 

I will confirm with them about whether or not there is supposed to be elevation on the bottom app bar, and if they should replace the mocks, but for now the specs page clearly state that there is a slight elevation in the bottom app bar. It’s working as intended.

**Comment by manabu-nakamura** [comment]
Please confirm. Thank you.

It says "Elevation: No shadow."
https://m3.material.io/components/bottom-app-bar/overview
It's very confusing for me.

**Comment by manabu-nakamura** [comment]
P.S.
The drop shadow of top app bar is gone.
https://github.com/material-components/material-components/issues/108

**Comment by imhappi** [comment]
Where does it say elevation: no shadow in the overview you linked? I only see that it talks about no elevation for the FAB, which is the floating action button.

I will mention to the designers about the difference in specs between the bottom app bar and top bar, but again: _everything is working as intended_. The specs for the bottom app bar clearly state that there’s a slight elevation.

Please file a new bug instead of replying if you want to discuss this further as I don’t think this discussion is relevant to this closed issue.

**Comment by manabu-nakamura** [comment]
https://m3.material.io/components/bottom-app-bar/overview
![a](https://user-images.githubusercontent.com/71050561/187860525-d3b21c2a-7924-44a5-8816-227b3187dbd6.png)

Thank you.
I will file a new bug.
