### ISSUE TITLE
[TopAppBar] Toolbar becomes transparent for some reason

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#2699]
**How to reproduce:** 
- Open `BottomAppBarMainDemoFragment`
- Scroll down the page
- Open menu from bottom app bar
- Go to "Recent Apps" and back
- Pay attention to the toolbar - it becomes transparent

And the video:

https://user-images.githubusercontent.com/82187521/167892075-b4319142-6794-4aa7-b501-4766750f6a29.mp4

<br>

**Material Library version:** 1.6.0
**Device:** Pixel 4a 5G (Android 12)

**Comment by pekingme** [comment]
Thanks for the PR. I'm trying to repro the issue but not succeed. Could you confirm this on your end? If still reproducible, could you share the details about your testing device/sdk?

**Comment by pubiqq** [comment]
Fixed in https://github.com/material-components/material-components-android/commit/c22eb0d31bbd1e87b244100b8ae7d5d7995394a6.

**Comment by pubiqq** [comment]
I can't reproduce it either. It looks like it was fixed by https://github.com/material-components/material-components-android/commit/c22eb0d31bbd1e87b244100b8ae7d5d7995394a6.
