### ISSUE TITLE
[MaterialButton] app:iconGravity="textEnd" not working properly with multiline text

### ISSUE THREAD

**Issue by miikahameenaho** [material-components/material-components-android#2701]
**Description:**
When creating a MaterialButton that has an icon and is android:layout_width="wrap_content"
and has app:iconGravity="textEnd" and has a multiline text inluded
seems to place the icon incorrectly when comparing to MaterialButton with single line text

<img width="414" alt="Screenshot 2022-05-13 at 16 12 32" src="https://user-images.githubusercontent.com/9018923/168291110-604b7d21-94b4-486f-bfd2-9875b8405192.png">

**Expected behavior:** 
Expecting that with same length text (meaning longest line within the button), icons are aligned between buttons with single line and multiline texts

**Source code:** 

In layout:

        `<com.google.android.material.button.MaterialButton
                                    style="@style/TextButtonInternalLink"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                                    app:icon="@drawable/icon_navigation_linkinternal"/>`

        `<com.google.android.material.button.MaterialButton
                        style="@style/TextButtonInternalLink"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="incididunt ut labore et dolore magna aliqua."
                        app:icon="@drawable/icon_navigation_linkinternal"/>`

Styles:

        `<style name="TextButtonInternalLink" parent="TextButton">
                            <item name="icon">@drawable/icon_navigation_linkinternal</item>
                            <item name="iconGravity">textEnd</item>
          </style>`

        `<style name="TextButton" parent="Widget.MaterialComponents.Button.TextButton.Icon">
                            <item name="android:paddingTop">@dimen/space_xxs</item>
                            <item name="android:paddingBottom">@dimen/space_xxs</item>
                            <item name="android:paddingLeft">0dp</item>
                            <item name="android:paddingRight">0dp</item>
                            <item name="rippleColor">?attr/colorControlHighlight</item>
                            <item name="iconSize">@dimen/size_icon_small</item>
                            <item name="android:gravity">start</item>
                            <item name="android:textAppearance">@style/TextAppearance.TextButton</item>
          </style>`

           
**Android API version:** API level 31

**Material Library version:** Material 1.6.0

**Device:** Pixel 5, Android 12

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
It think it's fixed by https://github.com/material-components/material-components-android/commit/19d05000bcc273f781a85ce41530f604fead268e, which is included in 1.7.0-alpha01.

**Comment by drchen** [comment]
It's duplicate issue of #2007  btw.

**Comment by miikahameenaho** [comment]
Yep, this is now fixed and working correctly
