### ISSUE TITLE
Material3 CircularProgressIndicator not working in Mi11x Pro

### ISSUE THREAD

**Issue by BoltUIX** [material-components/material-components-android#2704]
The progress indicator is not showing in mi 11x pro but it is working on other devices

the app does not show a progress indicator
the app does not show any error or crash - issue happens only mi 11 x pro

**Source code:** The code snippet which is causing this issue

```
<com.google.android.material.progressindicator.CircularProgressIndicator
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:indeterminate="true" />
```

 implementation 'com.google.android.material:material:1.7.0-alpha01'

**Device:** MI 11 XPRO (os android 11)

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).](https://stackoverflow.com/questions/72236725/material3-circularprogressindicator-not-working-in-mi11x-pro)

**Comment by drchen** [comment]
Does this happen on older library versions?

**Comment by BoltUIX** [comment]
> Does this happen on older library versions?

I checked older and newer library versions, it is replicating.

**Comment by drchen** [comment]
Thanks for the info. It looks very like a device issue but I'm not sure.

I don't have a Mi 11x pro to test.
Will you be able to play around with [the drawing code](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/progressindicator/CircularDrawingDelegate.java) and see if anything may cause this on the device?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with more details.
