### ISSUE TITLE
MaterialButton style does not support only Icon

### ISSUE THREAD

**Issue by zishanj** [material-components/material-components-android#272]
With the use of style `Widget.MaterialComponents.Button.Icon` I was expecting the layout to format according to icon only but it works just like `Widget.MaterialComponents.Button.TextButton.Icon` with requirement of adding text also along with icon.

**Comment by ymarian** [comment]
Hi, are you talking about the icon only buttons in the catalog demo? 
Yes that was a somewhat contentious decision but the reason we have two styles named like that is because the spec defines different paddings for buttons with and without icons.
https://material.io/design/components/buttons.html

 We don't provide a style at the moment for Icon Only but you can easily create your own:

eg: 
     ```
<style name="IconOnlyButton" parent="Widget.MaterialComponents.Button.OutlinedButton">
   <item name="iconPadding">0dp</item>
   <item name="iconGravity">textStart</item>
</style>

```

**Comment by MahmoudAymann** [comment]
some useful  adding to @ymarian answer :
```
<style name="IconOnlyButton" parent="Widget.MaterialComponents.Button.OutlinedButton">
        <item name="iconPadding">0dp</item>
        <item name="iconGravity">textStart</item>
        <item name="rippleColor">@android:color/transparent</item>
        <item name="android:shadowColor">@android:color/transparent</item>
        <item name="strokeColor">@android:color/transparent</item>
    </style>
```

**Comment by sandrocsimas** [comment]
Is there a way to remove o decrease the padding? I tried setting the padding in the element and style but it does not work.

**Comment by dviecas** [comment]
@sandrocsimas I believe what you were looking for is called inset:

```
<item name="android:insetBottom">0dp</item>
<item name="android:insetTop">0dp</item>
<item name="android:insetLeft">0dp</item>
<item name="android:insetRight">0dp</item>

**Comment by sandrocsimas** [comment]
@dviecas, it's not working:
````
<com.google.android.material.button.MaterialButton
          android:id="@+id/save_first_name_button"
          style="@style/IconButton"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"/>
````
````
<style name="IconButton" parent="Widget.MaterialComponents.Button.OutlinedButton.Icon">
    <item name="android:insetBottom">0dp</item>
    <item name="android:insetTop">0dp</item>
    <item name="android:insetLeft">0dp</item>
    <item name="android:insetRight">0dp</item>
    <item name="iconPadding">0dp</item>
    <item name="iconGravity">textStart</item>
    <item name="iconSize">@dimen/icon_md</item>
  </style>
````

**Comment by MatthewTighe** [comment]
I believe the issue is that there is no way to make the button any smaller than this:

![image](https://user-images.githubusercontent.com/10427470/64306191-b900ab80-cf46-11e9-9982-0ddfd9543be5.png)


This is using:
```
    <style name="IconOnlyButton" parent="Widget.MaterialComponents.Button.OutlinedButton">
        <item name="backgroundTint">@color/colorPrimary</item>
        <item name="iconTint">@color/colorIcon</item>
        <item name="iconPadding">0dp</item>
        <item name="iconGravity">textStart</item>
        <item name="rippleColor">@android:color/transparent</item>
        <item name="android:shadowColor">@android:color/transparent</item>
        <item name="strokeColor">@android:color/transparent</item>
        <item name="android:insetBottom">0dp</item>
        <item name="android:insetTop">0dp</item>
        <item name="android:insetLeft">0dp</item>
        <item name="android:insetRight">0dp</item>
        <item name="android:paddingBottom">0dp</item>
        <item name="android:paddingTop">0dp</item>
        <item name="android:paddingLeft">0dp</item>
        <item name="android:paddingRight">0dp</item>
    </style>
```

There seems to be a real need for small, self-contained icon buttons. Just two of them takes up easily a third of the screen. I think I can make precise enough clicks that the buttons could comfortably be just larger than the icon itself.

**Comment by Dem0n13** [comment]
I've found it more useful

```
<style name="Widget.AppTheme.Button.IconButton" parent="Widget.MaterialComponents.Button.TextButton">
    <item name="android:minWidth">0dp</item>
    <item name="android:insetLeft">0dp</item>
    <item name="android:insetTop">0dp</item>
    <item name="android:insetRight">0dp</item>
    <item name="android:insetBottom">0dp</item>
    <item name="iconGravity">textStart</item>
    <item name="iconPadding">0dp</item>
    <item name="iconTint">@drawable/mtrl_btn_text_color_selector</item>
    <item name="rippleColor">?colorOnPrimary</item>
</style>
```

I reset `minWidth` to make button square, set `rippleColor` to show click effect and use `mtrl_btn_text_color_selector` as `iconTint` to add disabled state ([got from here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/color/mtrl_btn_text_color_selector.xml).

You can set `cornerRadius` to `layout_width/2` and finally get this result:
![photo_2019-09-20_13-28-59](https://user-images.githubusercontent.com/1087430/65320559-cf477200-dbaa-11e9-8bf7-2b0d1464b996.jpg)
