### ISSUE TITLE
Styling new MaterialSwitch component

### ISSUE THREAD

**Issue by drmrbrewer** [material-components/material-components-android#2720]
I'm playing with the new MaterialSwitch component introduced in [1.7.0-alpha02](https://github.com/material-components/material-components-android/releases/tag/1.7.0-alpha02)... out of the box my switches look like this:

![SmartSelect_20220526-101120_Meteogram Dev Pro](https://user-images.githubusercontent.com/9009792/170457856-d37179d5-46ee-435d-b2f3-3a42a0c7565e.jpg)

... which doesn't look much like the [guidelines](https://m3.material.io/components/switch/overview) (particularly for the selected state).

How can we style this via XML?  The [implementation guide](https://m3.material.io/components/switch/implementation) says "MDC-Android not available"... what is that supposed to mean?  Can this only be implemented properly via Jetpack Compose, which is not possible if we're using a Java codebase?

**Comment by drchen** [comment]
Hi, the implementation guide is not updated yet.

The commit that adds a default switch style to M3 themes is not included in 1.7.0-alpha02. To use the correct style you will need to manually set the view style to `Widget.Material3.CompoundButton.MaterialSwitch`. Or you can also add `?attr/materialSwitchStyle` in your custom theme and make it point to `Widget.Material3.CompoundButton.MaterialSwitch`.

Hope you enjoy the new Switch. : )

**Comment by drmrbrewer** [comment]
@drchen thanks, that's a bit more like it, and a bit less like it too:

![SmartSelect_20220526-220544_Meteogram Dev Pro](https://user-images.githubusercontent.com/9009792/170580393-00cf525c-1a7b-46d2-a7b1-1058c6756471.jpg)

... still doesn't look quite the same (longer, more "pointy", no outline in the deselected state)... may be jumping the gun a bit, but where can I find some the XML attributes I can use to change the styling?

**Comment by drchen** [comment]
That.... is not a styling issue. ^^;

To have the correct width we need to depend on appcompat 1.6.0, which is not released yet.

In the current implementation we use reflection to "hack" the width for now. This may not work if you have set up obfuscation in your app. (Or can be broken by any reasons...)

**Comment by drmrbrewer** [comment]
> To have the correct width we need to depend on appcompat 1.6.0, which is not released yet.

My own app has an appcompat dependency of `1.6.0-alpha04` so we should be good to go?

And *d'oh*... when trying it again after your comment, I switched the style as you said just above, but I forgot to change the actual components back from `com.google.android.material.switchmaterial.SwitchMaterial` to `com.google.android.material.materialswitch.MaterialSwitch` ... :-)

It's looking much more like it now (didn't like to say, but the "pointy" version just above looks uuugggly... now it doesn't ;-) ... just need to tweak the layout to allow for more space:

![SmartSelect_20220526-223328_Meteogram Dev Pro](https://user-images.githubusercontent.com/9009792/170584171-bc8e7552-662f-4fec-9a35-55319e304d64.jpg)

**Comment by drchen** [comment]
Great! (AppCompat 1.6.0-alpha04 is good, but for some reason we cannot use it in our library for now... We will remove the hack/workaround before our 1.7.0-rc is released.)

**Comment by drmrbrewer** [comment]
@drchen I'm puzzled as to why my current layout isn't already reserving enough height for the switch in the case where it's on a line with just a single line of text (see screenshot)... my `android:layout_height` is set to `wrap_content`... seems to be reserving enough height for the sliding handle but not the enclosure?  Where there are two lines of text, that forces enough height, but with a single line of text it squeezes too tightly down on the switch.

**Comment by drchen** [comment]
Regarding the layout height - I'm not entirely sure what's going wrong here. In a recent change we set the min height of the default style to 48dp to enforce the accessibility standard so I didn't really see the issue internally. Maybe you can workaround it for now by setting `android:minHeight`?

Regarding the thumb icon - it's working as designed - when icon is presented, the thumb size will be kept the same. 
To override this behavior, (at least in this version) you will need to sort of replicate [the thumb icon drawable XML](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/materialswitch/res/drawable/mtrl_switch_thumb.xml) and remove all `with_icon` section from it. 

We will consider making this behavior customization easier. : )

**Comment by drmrbrewer** [comment]
OK thanks for the explanations.  Setting an `android:minHeight` of `48dp` is a better solution than my top/bottom padding, and indeed it works well.

Out of interest (just asking for a friend) is there any "legal" way of reducing the overall size of the switch?  I found that it's possible to override the `mtrl_switch_track_width`, `height` and `mtrl_switch_thumb_size` in `dimens.xml` but these are marked as "private".  I find that it fits better with the rest of my UI if I just knock the size back by a fraction (1/8).

**Comment by drchen** [comment]
You can provide custom thumb and track drawables with whatever size you like. : )

**Comment by drmrbrewer** [comment]
but then you lose the animation effects etc and the transition from large to small?

**Comment by drchen** [comment]
Well the animation comes with the drawable. (It's implemented as [AnimatedStateListDrawableCompat](https://developer.android.com/reference/androidx/appcompat/graphics/drawable/AnimatedStateListDrawableCompat), so yes. 

If you just want to change the drawable size, you can copy the default drawables and change their width/height. That should be the easiest way. : )
