### ISSUE TITLE
[Slider] Labels don't disappear when slider with LABEL_VISIBLE behavior is set to View.GONE

### ISSUE THREAD

**Issue by chenxiaolong** [material-components/material-components-android#2726]
**Description:**

When a slider has `LABEL_VISIBLE` or `android:labelBehavior="visible"` set, the labels do not disappear when the visibility of the slider itself is set to `View.GONE`.

**Expected behavior:**

The labels should disappear along with the slider. It's possible to make this happen in a hacky way by calling `BaseSlider.ensureLabelsRemoved()` with reflection.

Screenshot of initial slider: [Screenshot_20220529-162716](https://user-images.githubusercontent.com/646253/170890425-5c2f627e-0618-4ded-a853-a15a6fcb182e.png)
After setting visibility to `View.GONE`: [Screenshot_20220529-162724](https://user-images.githubusercontent.com/646253/170890439-a53f2690-da40-4392-a95c-3dcdcf4e21cb.png)
After setting visibility to `View.GONE` and calling `ensureLabelsRemoved` with reflection: [Screenshot_20220529-163308](https://user-images.githubusercontent.com/646253/170890461-8793d441-203b-400c-9cdf-c6a88d93ad6b.png)

**Source code:**

```xml
<com.google.android.material.slider.Slider
    android:id="@+id/slider"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:labelBehavior="visible" />
```

```kotlin
val slider: Slider = findViewById(R.id.slider)
slider.isVisible = false
```

**Minimal sample app repro:** https://github.com/chenxiaolong/SliderGone

**Android API version:** Reported as 32 in `ro.build.version.sdk`, but this is on Android 13 Beta 2.1

**Material Library version:** Tested on both `1.6.0` and `1.7.0-alpha02`

**Device:** Google Pixel 6 Pro

**Comment by therealsujitk** [comment]
@drchen, I'd like to try resolving this issue, can I be assigned to it?

**Comment by drchen** [comment]
Absolutely. Thanks for the PR!!
