### ISSUE TITLE
AAPT:  error: resource android:color/system_neutral1_xxx not found.

### ISSUE THREAD

**Issue by sxlideal** [material-components/material-components-android#2729]
**Description:** 
Recently I upgrade material from 1.4.0 up to 1.5.0.And also changed the compileSDKVersion from 30 to 31. But still cannot build the project.
I checked local android sdk.31 has installed. and also all the missing colors can be found in it.

Can I get any help?

**Expected behavior:** 
build success and can run my project

**Material Library version:** 
com.google.android.material:material:1.5.0
I tried 1.6.1  and get the same error.

gradle version: 6.5

sdkVersions:
 minSdkVersion    : 21,
 targetSdkVersion : 31,
 compileSdkVersion: 31,
 buildToolsVersion: "31.0.0",

**Comment by drchen** [comment]
It sounds like some issues regarding local dev environment setup. Will you be able to send a minimal repro app so we can help verify it?
