### ISSUE TITLE
[PreferenceFragmentCompat] Dialogs are not shown in Material Design M3 style

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#2732]
**Description:** Dialogs in [PreferenceFragmentCompat] are not shown in Material Design M3 style. Instead, for example, wrong colors and dialog outlines are used as shown below. The issue is especially visible when using the DynamicColors feature.
![Screenshot_20220602_190913](https://user-images.githubusercontent.com/7906165/171685952-750917d8-28bc-490b-aee7-2d46919734ab.png)

**Expected behavior:** I expected that [PreferenceFragmentCompat] shows dialogs in Material Design M3 style, i.e. about as shown below (I've tried to rebuild the expected M3 design by using a ThemeOverlay, but didn't manage e.g. to get the correct backgrounc color).
![Screenshot_20220602_191920](https://user-images.githubusercontent.com/7906165/171687794-a5dc2e69-deaa-40cd-98ba-7a3a6a989a4c.png)

**Source code:** Here are some code snippets...

**PreferenceFragmentCompat**
```
public class SettingsFragment extends PreferenceFragmentCompat implements SharedPreferences.OnSharedPreferenceChangeListener {

    private Context mContext;

    @Override
    public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
        // Load the preferences from an XML resource
        setPreferencesFromResource(R.xml.settings, rootKey);
    }
```

**themes.xml**
```
<resources xmlns:tools="http://schemas.android.com/tools">

    <!-- Base application theme -->
    <style name="AppTheme" parent="AppTheme.Base" />
    <style name="AppTheme.Base" parent="Theme.Material3.Light">
```

**Android API version:** 32 & 33 (Tiramisu)

**Material Library version:** com.google.android.material:material:1.7.0-alpha02

**Device:** Pixel 5 Emulator

**Comment by patrickfrei** [comment]
Thank you for your reply. 

Are there any plans to introduce a preferences settings screen including dialogs in Material Design M3 in the future?

**Comment by patrickfrei** [comment]
OK, yes, that would be great 😃 I think in the meantime, the easiest workaround is probably using a theme overlay as suggested by you. Overriding onDisplayPreferenceDialog() will probably require to copy a lot of code...

**Comment by patrickfrei** [comment]
Hi @drchen,

Sorry to ask you again, but I've now managed to create a dialog for `PreferenceFragmentCompat` quite similar to the M3 dialog. See below code.

The only thing is that the dialog's background color is not correct when using the dynamic colors feature (`DynamicColors.applyToActivitiesIfAvailable(this);`) in the app's `Application` class. In accordance with the [design guidelines](https://m3.material.io/components/dialogs/implementation) I've used `?attr/colorSurface` for the dialog's background. This color is also applied when using the dynamic colors feature instead of the automatically adjusted one.

Do you have any idea or hint what the reason could be that the dynamic color is not applied to the background in my code approach? Many thanks!

```
<resources xmlns:tools="http://schemas.android.com/tools" xmlns:android="http://schemas.android.com/apk/res/android">
    <style name="AppTheme" parent="AppTheme.Base" />
    <style name="AppTheme.Base" parent="Theme.Material3.Light">
        <!-- snip -->
        <item name="colorSurface">@color/md_theme_surface</item>
        <!-- snip -->
        <item name="alertDialogTheme">@style/AppTheme.MyOldAlertDialog</item>
    </style>

    <style name="AppTheme.MyOldAlertDialog" parent="ThemeOverlay.Material3.MaterialAlertDialog">
        <item name="dialogCornerRadius">28dp</item>
        <item name="cornerFamily">rounded</item>
        <item name="android:colorBackground">?attr/colorSurface</item>
        <item name="android:layout">@layout/m3_alert_dialog</item>
    </style>

</resources>
```

**Comment by drchen** [comment]
By "not applied" you mean the background is just white or...? Do you have some screenshots?

**Comment by drchen** [comment]
Oh gotcha. So with MaterialAlertDialogBuilder the surface color is calculated on-the-fly (for now) - a small percentage of `?attr/colorPrimary` is overlaid upon the pure `?attr/colorSurface`. We have no control over the framework alert dialog, so the color you see will be pure `?attr/colorSurface`. 

To achieve the same color, the easiest way might be setting the color programmatically after the dialog is created - by using [SurfaceColors.SURFACE_3.getColor()](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/elevation/SurfaceColors.java#L50).

Another approach is overriding `?android:attr/windowBackground` and manually overlaying the color with layer-list. Here's an example to refer to:
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/menu/res/drawable-v23/m3_popupmenu_background_overlay.xml

**Comment by patrickfrei** [comment]
All right! Many thanks for your help!

**Comment by drchen** [comment]
No problem. Let us know if you have other questions. : )

**Comment by ytheekshana** [comment]
Could any one give me a full code on this. I also have a list-preference which I need to support m3
