### ISSUE TITLE
[MaterialSwitch] colorOutline themes both outline and thumb

### ISSUE THREAD

**Issue by airplanesmode** [material-components/material-components-android#2739]
I can see that the new MaterialSwitch is using colorOutline for both outline and thumb color (at least when not enabled). I tried setting to @null, but in that case I cannot theme thumb color.

Is it currently possible (or planned) to not have outline but still theme thumb?

**Comment by airplanesmode** [comment]
Also there seems to be a visual bug when the colorOutline is the same color as the backround (in this case both are white)

![Screenshot_20220608-005538](https://user-images.githubusercontent.com/100050926/172496796-d2a8f5b1-d18f-45f6-9967-377408661805.png)

**Comment by drchen** [comment]
You can set `app:trackDecoration` in the component style to `@null` to remove the outline.
