### ISSUE TITLE
Is there a way to place chipIcon from Chip view(action type) to the right side? 

### ISSUE THREAD

**Issue by jianjonathanyang** [material-components/material-components-android#274]
<com.google.android.material.chip.Chip
        android:id="@+id/action_chip"
        style="@style/Widget.MaterialComponents.Chip.Action"
         app:chipIcon="@drawable/ic_android_24dp"
        app:iconStartPadding="5dp"/>

The chipIcon is always placed on the left side of Chip? Is there an attribute which allows us to move the icon to the right side?

**Comment by ymarian** [comment]
I think we won't support that because it doesn't appear in the spec:
https://material.io/design/components/chips.html

However you could set android:layoutDirection="rtl" or the opposite of your current direction to put the icon on the right

**Comment by j-mateo** [comment]
Even though it doesn't appear in this specific spec, isn't bidirectionality a global concept of material design?

https://material.io/design/usability/bidirectionality.html

**Comment by niketkn** [comment]
android:layoutDirection="rtl"  worked! thanks @ymarian
