### ISSUE TITLE
Corner cut for drawable XML 

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2741]
Can you apply corner cut instead of rounded corner on a XML drawable?

```
<?xml version="1.0" encoding="UTF-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@color/colorWhiteDark_Primary"/>
    <corners android:radius="10dp"/>
</shape>
```

**Comment by ArcherEmiya05** [comment]
I am planning to apply cut corner shape on action menu dialog. Either I could use a custom drawable or there is a native way to do this with M3.

![image](https://user-images.githubusercontent.com/38008900/172765088-aee8ba10-9640-4c10-9a17-6cc9f4a82eb0.png)

**Comment by drchen** [comment]
Unfortunately I don't think you can. It's not supported by the Android framework and you'll have to create your own custom drawable.
