### ISSUE TITLE
[MaterialDatePicker] Soft input not showing when picker is shown with INPUT_MODE_TEXT

### ISSUE THREAD

**Issue by mialkan** [material-components/material-components-android#2747]
**Description:** 

When I try to show MaterialDatePicker with input mode text its not showing the soft input keyboard. But If I switch between text and calendar mode it shows soft input. It works for some android devices that I tested. (Android 6, Android 7).

**Expected behavior:**  Soft Input should be shown when MaterialDatePicker opened with input mode text. 

**Source code:** 

https://github.com/material-components/material-components-android/blob/eb54d6a51a494ab51ae6fe4708c1db2c60fec541/lib/java/com/google/android/material/internal/ViewUtils.java#L87

InputMethodManager logs the following:

 **W/InputMethodManager: Ignoring showSoftInput() as view=com.google.android.material.textfield.TextInputEditText{5e38b94 VFED..CL. .F...... 0,0-770,153 aid=1073741824} is not served.**

If you can add a delay to post its working.

**Minimal sample app repro:** 

https://github.com/mialkan/fragment-keyboard 

**Android API version:**
 30-31

**Material Library version:** 
1.6.0-1.6.1

**Device:** 
Samsung Galaxy A71, Android 11 (30)
Pixel 4XL, Android 12 (31)
Samsung Galaxy M31, Android 12 (31)
Samsung Galaxy S20+,  Android 12 (31)

**Comment by chanakin** [comment]
As a corollary to this issue, switching from INPUT_MODE_TEXT to INPUT_MODE_CALENDAR via the toggle does not hide the keyboard if it has been opened. Could we also get a fix for this please? I think these issues may be related or the same issue showing up in different ways. Let me know if I need to create a new issue for this.

**Comment by paulfthomas** [comment]
@chanakin can you create a separate bug with the steps to reproduce? Thanks!
