### ISSUE TITLE
[Material Theme] Contrast of Status Bar Background & Icons when using M3 Dynamic Color

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#2748]
**Description:** My app uses M3 Dynamic Color plus a light and dark theme. When I'm using the light theme, there is not enough contrast between status bar background and status bar icons. Reason: In accordance with a sample app screenshot on the [M3 website](https://m3.material.io/components/top-app-bar/overview), I'm using `colorSurface` for the status bar background. However, the status bar icons appear in white color. Therefore, I've set `android:windowLightStatusBar` to `true` in the light theme and to `false` in the dark theme (see code below). 

That works fine as you can see from below screenshots. But that behavior is now hard-coded and as I'm using Dynamic Color, I'm not sure if that's a sustainable solution. What happens e.g. if `colorSurface` suddenly contains a significantly darker color when using the light theme? Then the contrast would probably be too low.

Do you have some guidance / best practice concerning the handling of the status bar background / icon contrast in M3 when using Dynamic Color? Is there an automated solution (planned) to ensure enough contrast between status bar background and status bar icons?

**Expected behavior:** Contrast between status bar background and status bar icons is (automatically) ensured when using M3 with Dynamic Color.

- Before setting `android:windowLightStatusBar` to `true`:
![Screenshot_20220610_093521](https://user-images.githubusercontent.com/7906165/173021088-f77dbbed-44c4-4ad7-92f2-b3da751963c8.png)

- After setting `android:windowLightStatusBar` to `true`:
![Screenshot_20220610_094641](https://user-images.githubusercontent.com/7906165/173021107-1be1f555-35d7-4ce5-b41a-46bc971a0ab8.png)

**Source code:** 
- Light theme:
```
<resources xmlns:tools="http://schemas.android.com/tools">
    <style name="AppTheme" parent="AppTheme.Base">
        <item name="android:windowLightStatusBar">true</item>
        <item name="android:statusBarColor">?attr/colorSurface</item>
        <item name="android:navigationBarColor">@android:color/transparent</item>
    </style>
</resources>
```

- Dark theme:
```
<resources xmlns:tools="http://schemas.android.com/tools">
    <style name="AppTheme" parent="AppTheme.Base">
        <item name="android:windowLightStatusBar">false</item>
        <item name="android:statusBarColor">?attr/colorSurface</item>
        <item name="android:navigationBarColor">@android:color/transparent</item>
    </style>
</resources>
```

**Android API version:** API 32 & 33

**Material Library version:** 1.7.0-alpha02

**Device:** Pixel 5 emulator

**Comment by drchen** [comment]
colorSurface in light theme is guaranteed to have a tone > 90 so the contrast should be guaranteed as well as long as `android:windowLightStatusBar` is set.

**Comment by patrickfrei** [comment]
Great! Many thanks!
