### ISSUE TITLE
why all material popup menu in android app bar to slow for open

### ISSUE THREAD

**Issue by umardev500** [material-components/material-components-android#2752]

**Comment by drchen** [comment]
Can you provide more details? Like which app bar and popup menu are you referring to? How do you set up those components? What do you mean by "slow"? Which library and framework version and what device are you using?

Some screen recordings will be helpful as well.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
