### ISSUE TITLE
[MaterialAutoCompleteTextView] dropdown selected item background color

### ISSUE THREAD

**Issue by agustinsivoplas** [material-components/material-components-android#2754]
I am using the MaterialAutoCompleteTextView component. I would like if possible to set a different background color for selected item.

This is the current UI:

<img width="450" alt="Screen Shot 2022-06-13 at 12 05 13" src="https://user-images.githubusercontent.com/1648539/173385616-a5266a9a-62d0-47ef-9d2c-6e1dee6fb040.png">

I would like to achieve this:

![Screen Shot 2022-06-13 at 12 05 29](https://user-images.githubusercontent.com/1648539/173385688-2456f488-9259-4001-abf8-f0575dce0bb2.png)

Maybe is already possible but I didn't found a way of do it.

**Comment by agustinsivoplas** [comment]
@drchen I will check, thanks!

**Comment by softsan** [comment]
i am trying this but it didn't work. My version is 1.9.0 of material component. 
My dropdown is inside a bottom sheet view. is that make any difference?
