### ISSUE TITLE
[List] Different text styles when using M3 compared to M2

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#2756]
**Description:** My app is using a list with two lines wherease the XML definitions initially follow the ones defined in Material Design [M2](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/lists/res/layout/material_list_item_two_line.xml). 

In order to use the new M3 text properties, I've exchanged `?attr/textAppearanceSubtitle1` by `?attr/textAppearanceTitleMedium` and `?attr/textAppearanceBody2` by `?attr/textAppearanceBodyMedium` as shown in the [mapping table](https://material.io/blog/migrating-material-3) for `textAppearance`.

However, the text styles are not exactly the same as the one in Gmail. I'm using that app as reference, as it has been migrated to Material Design M3.

**Expected behavior:** In below screenshot B, on the left of the red vertical line you can see the original list from below XML (my app) and on the right I've copy/pasted some text from the Gmail app (screenshot A) as reference. As you can see, the text styles are different. In my app, the text on the first line seems to be narrower and less bold while the text on the second line seems to be wider.

Unfortunately, I didn't find a list component with M3 design guidelines or screenshots on the [M3 website](https://m3.material.io/), but shouldn't the above approach in my app show the same result as in the Gmail app if it has really been migrated to M3?

- A) Snippet from the Gmail app list:
![Screenshot_20220613_221834](https://user-images.githubusercontent.com/7906165/173447681-2571e140-47c8-44bd-a453-fa19f867a1f1.png)

- B) snippet from the list in my app:
![Screenshot_20220613_225458](https://user-images.githubusercontent.com/7906165/173447730-732f5f83-91ed-438d-9193-b1a56d679c78.png)

**Source code:** 
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layoutDirection="locale"
    android:textDirection="locale"
    android:foreground="?android:attr/selectableItemBackground">

    <com.google.android.material.textview.MaterialTextView
        android:id="@+id/titleTxt"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        android:paddingStart="15dp"
        android:paddingLeft="15dp"
        android:paddingEnd="15dp"
        android:paddingRight="15dp"
        android:text="@string/list_item_title"
        android:textAppearance="?attr/textAppearanceTitleMedium"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.textview.MaterialTextView
        android:id="@+id/contentTxt"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        android:paddingStart="20dp"
        android:paddingLeft="20dp"
        android:paddingEnd="15dp"
        android:paddingRight="15dp"
        android:text="@string/list_item_content"
        android:textAppearance="?attr/textAppearanceBodyMedium"
        android:textColor="@color/list_item_tint"
        app:layout_constraintTop_toBottomOf="@id/titleTxt" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Android API version:** API version 33

**Material Library version:** 1.7.0-alpha02

**Device:** Pixel 5 emulator

**Comment by drchen** [comment]
Hi, I think our product deliberately separate the fonts used by 1p and 3p. (I don't have knowledge about the reason behind the decision either.) But yeah I don't really think you can use the same font as what Gmail is using. The font itself is proprietary if I understand correctly.

**Comment by patrickfrei** [comment]
Hi @drchen , thank you for your explanations!

Does that mean that my approach is the correct one for the official M3? I.e. taking the settings from [M2](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/lists/res/layout/material_list_item_two_line.xml) under consideration of the above mentioned adjustments of `android:textAppearance` and `android:textColor`?

**Comment by drchen** [comment]
Yeah I believe what you are doing is basically right in your use case. : )

(In fact `mtrl_list_item_tint.xml` is not a public resource and I think we encourage people to use `@layout/material_list_item_two_line`. But this shouldn't cause too much troubles in your use case.)

**Comment by patrickfrei** [comment]
🙂 well, my use case is a little bit special because I'm currently using a custom adapter implementation for my `RecyclerView`... I'll verify how I can implement the solution that you propose. Will look out for an example.

Concerning the non-public resource: Thank you for that hint! I'll go for `@layout/material_list_item_two_line`
