### ISSUE TITLE
[TextInputLayout + AutoCompleteTextView] Spinner replacement does not handle outside popup clicks correctly (as expected)

### ISSUE THREAD

**Issue by MFlisar** [material-components/material-components-android#2757]
**Description:** If you check out the behaviour of the old `Spinner` class you can see, that the spinner consumes the touches outside of the popup and simply closes the popup. This is not the case with the material replacement by `TextInputLayout`+ `AutoCompleteTextView`. In this case, if you click outside the opened popup window, the view underneath the touch gets the click AND the `AutoCompleteTextView` closes its popup.

**Expected behavior:** If the popup of the `AutoCompleteTextView` is opened, I would expect that touches outside the popup would simple close the popup - currently if you try to close the popup and accidently click a button in the background, a list item in the background or anything clickable, the popup is closes AND the clickable item in the background gets the click event => this is unexpected, I would expect the popup to consume the outside click as well.

**Source code:** -

**Minimal sample app repro:** -

**Android API version:** Android API version here

**Material Library version:** 1.6.1, latest release (but has been like this in previous versions as well)

**Device:** -

**Comment by drchen** [comment]
The MaterialAutoCompleteTextView is just a styled version of the AppCompatAutoCompleteTextView, so we basically follow the behavior of it (and thus the framework's AutoCompleteTextView's behavior.)

There is probably no easy way for us to override the behavior and I think we need to maintain the consistency with the appcompat and framework class as well. AutoCompleteTextView is not Spinner, after all. : )

I'll close this as WAI.
