### ISSUE TITLE
[BottomNavigationView] Icon generates a weird backgroundColor

### ISSUE THREAD

**Issue by samansamadi** [material-components/material-components-android#2760]
**Description:** I recently migrated from MD2 to MD3 and my BottomNavigationView has been encountering issues when I try to set my fonts on it

**Photo of the problem:** 
In dark mode:
![Screenshot (10)](https://user-images.githubusercontent.com/76772343/173767078-9eaa6d73-72e1-40fc-a2d4-28e6c6f9090e.png)

In light mode:
![Screenshot (11)](https://user-images.githubusercontent.com/76772343/173767153-5c70994b-baf9-4348-96bc-1b5b70040d82.png)

**Source code:** 
My style declaration:
`  <style name="Base.Widget.BottomNavigationView" parent="Widget.Material3.BottomNavigationView">
    <item name="fontFamily">@font/medium</item>
    <item name="android:fontFamily">@font/medium</item>
    <item name="itemIconTint">@drawable/bottom_nav_tint</item>
    <item name="itemTextColor">@drawable/bottom_nav_tint</item>
    <item name="android:minHeight">0dp</item>
  </style>`
bottom_nav_tint.xml
`<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_checked="true" android:color="?attr/colorPrimary" />
    <item android:state_pressed="true" android:state_enabled="true" android:color="?attr/colorPrimary" />
    <item android:color="?colorGray" />
</selector>`
BottomNavigationView usage:
`  <com.google.android.material.bottomnavigation.BottomNavigationView
    android:id="@+id/bottom_nav"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:theme="@style/Base.Widget.BottomNavigationView"
    app:menu="@menu/bottom_nav"/>`

minSdk 23
targetSdk 32

**Android API version:** Andorid 8 (Oreo)

**Material Library version:** com.google.android.material:material:1.6.1

**Device:** Google Pixel but mainly my Samsung J7 2016

**Comment by hunterstich** [comment]
Hey there.

I'm assuming this is because your icons (the actual drawable files), have a background color. It looks like it might have gone unnoticed in M2 since the background color matches the bottom navigation's background color and now that the icon is being drawn atop the inidicator that differs in color, you are seeing the background.

Can you paste the xml for one of the icon?

**Comment by hunterstich** [comment]
Hi @samansamadi,

Going to close this due to inactivity and the likelihood that this is coming from the icons being used and not the bottom navigation bar itself.
