### ISSUE TITLE
Why isn't Chip RTL friendly by default?

### ISSUE THREAD

**Issue by LouisCAD** [material-components/material-components-android#277]
This is confusing: https://github.com/material-components/material-components-android/blob/d36c500c45c6673193e38452a36cc1acba2c9bb5/docs/components/Chip.md#rtl-friendly-chip-layout

**Comment by wcshi** [comment]
Hi LouisCAD, we originally called 
CharSequence unicodeWrappedText = BidiFormatter.getInstance().unicodeWrap(text); when a user set the chip's text, however, this was causing Talkback to not speak the text properly. 

Here's the commit that made the change:
https://github.com/material-components/material-components-android/commit/0c8dd4f121c6da36e148ad5ebbeea9c6eff9d11c#diff-517b28ba515355e7ccfece81507a8cc1
