### ISSUE TITLE
Request: offer API to tell us if Material You (Monet) is supported on the current device or not

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#2772]
**Is your feature request related to a problem? Please describe.**
Yes, because some devices don't support it, so we could offer alternative UI and also warn about it not being supported.

**Describe the solution you'd like**
To have a boolean being returned to us, to see if the current device supports it.

**Describe alternatives you've considered**
I don't think there is a way...

**Additional context**
Requested here too:
https://issuetracker.google.com/issues/234050622

**Comment by dsn5ft** [comment]
Hi @AndroidDeveloperLB, I think the [DynamicColors. isDynamicColorAvailable()](https://github.com/material-components/material-components-android/blob/3fdfb6e230767138849edf858c13da1bf1d3f90b/lib/java/com/google/android/material/color/DynamicColors.java#L339) method should be what you are looking for?

**Comment by dsn5ft** [comment]
All Android devices from T+ will be required to support it!

**Comment by AndroidDeveloperLB** [comment]
@dsn5ft Even far-east ones?
Even Samsung, Xiaomi, OnePlus, Vivo,... ? 
They will all have to have the Material-You , that affects the OS ?

**Comment by AndroidDeveloperLB** [comment]
@dsn5ft Populated based on the wallpaper colors (including from both image wallpapers and live-wallpaper apps) , right?
Meaning that all apps could benefit them if the developers wish it, right?
But again, will this be for all OEMs, including all I've mentioned?

**Comment by dsn5ft** [comment]
> Populated based on the wallpaper colors (including from both image wallpapers and live-wallpaper apps) , right?

I'm not sure about live-wallpapers but I would think so. Also, it doesn't have to be a wallpaper, it could be a color palette choice by the user.

> Meaning that all apps could benefit them if the developers wish it, right?
> But again, will this be for all OEMs, including all I've mentioned?

Yes, I believe so.

**Comment by AndroidDeveloperLB** [comment]
@dsn5ft I see.
Is there an Intent too, to reach the wallpaper settings to choose the color-palette and also choose that it will be based on the live wallpaper?
Is there also an API to check what is the source of the dynamic colors (chosen by user, chosen from image-wallpaper, or chosen by live wallpaper) ?  

If not, can you please add such APIs ?

**Comment by dsn5ft** [comment]
I don't think those APIs exist, and we can't add them since they would have to be in the OS, not the Material library.

Feel free to file a "Framework" feature request here:

https://source.android.com/setup/contribute/report-bugs

**Comment by AndroidDeveloperLB** [comment]
Meaning here:
https://issuetracker.google.com/issues/new?component=192705&template=845803

ok thanks

**Comment by AndroidDeveloperLB** [comment]
@dsn5ft For the Intent, I actually requested here:

https://issuetracker.google.com/issues/216364001

For querying of the source of the dynamic colors, requested now:

https://issuetracker.google.com/issues/236994615

And for querying about whether the current live wallpaper is the source:

https://issuetracker.google.com/issues/236994616
