### ISSUE TITLE
Bug: DynamicColors.isDynamicColorAvailable() isn't reliable as it says it's supported on devices that it's not

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#2775]
**Description:** Full description of issue here
I requested to be able to check whether the current device has dynamic colors being generated from the wallpaper (or live wallpaper such as [here ](https://play.google.com/store/apps/details?id=com.lb.lwp_plus) and [here](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei)) or not:
https://github.com/material-components/material-components-android/issues/2772
I was told that DynamicColors.isDynamicColorAvailable() can be used for that.
So I made a sample app that just prints to the log if it's available or not.

**Expected behavior:** Screenshots and/or description of expected behavior
For these devices, it says it's supported, but I know for a fact that it's not, because setting a live wallpaper that sends the colors or setting a simple all-green/red/yellow wallpaper won't affect the OS and won't affect other apps (such as Gmail).

For example, for this device&Android-version it says that it's supported, yet it's not (check the code to understand the extra info) :

- Samsung Galaxy A32 with Android 12 : MODEL:SM-A325F;BRAND:samsung;DISPLAY:SP1A.210812.016.A325FXXU2BVD6;DEVICE:a32;BOARD:a32;HARDWARE:mt6769t;MANUFACTURER:samsung;ID:SP1A.210812.016;PRODUCT:a32xx;RELEASE:12;SDK_INT:31;INCREMENTAL:A325FXXU2BVD6;CODENAME:REL;architecture:aarch64;MEDIA_PERFORMANCE_CLASS:0

In fact, it has no option in the "wallpapr and style" to apply the colors based on the wallpaper:

[screenshots.zip](https://github.com/material-components/material-components-android/files/8971703/screenshots.zip)

**Source code:** The code snippet which is causing this issue
```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val isSupported = DynamicColors.isDynamicColorAvailable()
        Log.d("AppLog", "isSupported?$isSupported")
        val arch = getArchitecture()
        val performanceClass = getPerformanceClassValue()
        val deviceInfo =
            "MODEL:${Build.MODEL};BRAND:${Build.BRAND};DISPLAY:${Build.DISPLAY};DEVICE:${Build.DEVICE};BOARD:${Build.BOARD};HARDWARE:${Build.HARDWARE};MANUFACTURER:${Build.MANUFACTURER};ID:${Build.ID}" +
                    ";PRODUCT:${Build.PRODUCT};RELEASE:${Build.VERSION.RELEASE};SDK_INT:${Build.VERSION.SDK_INT};INCREMENTAL:${Build.VERSION.INCREMENTAL};CODENAME:${Build.VERSION.CODENAME};architecture:$arch" +
                    ";MEDIA_PERFORMANCE_CLASS:${performanceClass}"
        Log.d("AppLog", "deviceInfo:$deviceInfo")
    }

    companion object {
        fun getArchitecture() =
            kotlin.runCatching { System.getProperty("os.arch") }.getOrNull() ?: ""

        fun getPerformanceClassValue(): Int {
            return try {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S)
                    Build.VERSION.MEDIA_PERFORMANCE_CLASS
                else -1
            } catch (e: Throwable) {
                e.printStackTrace()
                -1
            }
        }
    }
}
```

Sample app (check logs and/or UI):
[My Application.zip](https://github.com/material-components/material-components-android/files/8971741/My.Application.zip)

**Android API version:** Android API version here
Already wrote above : API 31

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

```
implementation 'com.google.android.material:material:1.7.0-alpha02'
```

**Device:** Device on which the bug was encountered here
Already mentioned: Galaxy A32.

**Comment by dsn5ft** [comment]
> won't affect the OS and won't affect other apps (such as Gmail)

Checking the OS and other apps such as Gmail is not the best way to determine whether dynamic color is available on a device. As I mentioned in #2772, `DynamicColors.isDynamicColorAvailable()` should just be related to whether the dynamic system colors like `@android:color/system_accent1_600` are valid. It's then up to the OS and other apps such as Gmail to decide whether they are using those colors.

Re: Samsung Galaxy A32 with Android 12, as long as the device is running Samsung OneUI 4.1 or above ([source](https://github.com/material-components/material-components-android/blob/3fdfb6e230767138849edf858c13da1bf1d3f90b/lib/java/com/google/android/material/color/DynamicColors.java#L53-L72)), then the dynamic color system resources should be working.

Instead of looking at the OS/apps as the signal, I think you should put a dynamic color like `@android:color/system_accent1_600` in your sample app to see if it updates as you expect when the wallpaper is changed.

**Comment by drchen** [comment]
> The sample app here ("catalog") shows the same exact colors for the "Demo" and "Dynamic Palette Demo" under "color" . All changes to wallpapers lead to the same blue system accent colors, including the one you've mentioned, of course ("system_accent1_600" ). Tested pure yellow, pure green, and pure red.

This feels a bit suspicious to me. Can you attach both screenshots of the two demos?

I agree it will be nice if Android framework can provide an API to indicate if dynamic colors are supported but unfortunately it doesn't. 

If a certain Samsung OS version with OneUI 4.1+ doesn't have dynamic colors support, it probably be a Samsung OS issue. (But please be aware of that there's actually no way to really "fix" such issue. Users will have to update the OS version anyways.)

**Comment by AndroidDeveloperLB** [comment]
@drchen Please explain the full steps you want me to test it.
Would this be ok to take a video of this:

1. Set a red-only wallpaper, turn off&on the display (to let the OS be in sync with this), go to the sample app on both places that it shows the colors (the one with the small rectangles and the one with the list of colored-rows)
2. Set a green-only wallpaper, turn off&on the display (to let the OS be in sync with this), go to the sample app and do the same.

?

About the function, what's the point in having this function, then, if it's unreliable? 
I also requested that instead of a boolean, we would have a new function to return us what's really supported. 
Why shouldn't it be possible for Google to require OEMs to tell what's exactly supported?

**Comment by drchen** [comment]
> Please explain the full steps you want me to test it.

Just open Catalog and go to "Demo" and "Dynamic Palette Demo" under "Color". 
Video or screenshots both work.

**Comment by AndroidDeveloperLB** [comment]
@drchen OK here. And I tested using the app "Wallpapers" by Google. Weird that it lacks some basic colors, though.

[studio64_1jZuT7FsLI.zip](https://github.com/material-components/material-components-android/files/8993280/studio64_1jZuT7FsLI.zip)

**Comment by drchen** [comment]
Are you using an emulator? (I don't know there's Samsung emulators...)

Regarding #2779, as I explained, there's really nothing better we can do on the library side than the current implementation.

**Comment by drchen** [comment]
Because we don't have the info either. : )

There's just no reliable way to know if OEMs on S actually support dynamic colors or not (or to which level.)
It's also impossible for us to audit all versions from all OEMs to check their support level.

I'll let the relevant team know that some Samsung versions with OneUi 4.1 may not really support dynamic colors and discuss with them about what we can do.

Thanks for your reporting, though.

**Comment by AndroidDeveloperLB** [comment]
@drchen So get the info. Have it on the license tests if needed.
Now is the time to do it, before Android 13 is out. 
Otherwise it will stay fragmented and OEMs will again break the default behavior, as they have done many times (see [here](https://issuetracker.google.com/issues/122098785) ). 

You say "partners", but it doesn't seem like they collaborate with Google enough. Things break all the time. How could Google license OEMs like Xiaomi which breaks things by default. I alone found at least 3 ways they break behavior, including explicit documentation on Android's website.

**Comment by drchen** [comment]
I understand what you said. I suggest you report the issue you saw to the framework team. The Material library is not part of the framework and there's very few things we can do as for this part.

**Comment by AndroidDeveloperLB** [comment]
@drchen The thing is that the library's dynamic colors feature can't be used if OEMs don't support it. 
:(

**Comment by AndroidDeveloperLB** [comment]
@drchen I've tested more on this device, and it seems that it's just buggy.
Sometimes it does offer the color pallete and sometimes it is stuck on what you've chosen.
This is true especially for live wallpapers (Muzei and LWP+). 
Note that I turn off&on the display.

**Comment by drchen** [comment]
If it's buggy that's totally beyond our control.... ^^;

I'll close this issue since there's really nothing we can do at the moment. The Material library is providing helper functions to let clients be able to integrate dynamic colors in an easier way. Unfortunately we can't guarantee and have no control over OEM's behavior.

However I'll raise your report to the relevant person who work with OEMs and framework supports so they will be better aware of the situations you are concerned with. Thanks for your report!

**Comment by AndroidDeveloperLB** [comment]
@drchen Can you please let me know about updates of this?

**Comment by drchen** [comment]
Will let you know if they have any updates. But I doubt there will be any real actions on this given that T is going to be released soon and all OEMs are supposed to fully support dynamic colors on T.

**Comment by AndroidDeveloperLB** [comment]
@drchen Including this device and all devices out there that have Android 12?

**Comment by drchen** [comment]
In theory, I think. But again I can't represent product team to guarantee that. It's just my personal understanding.

**Comment by AndroidDeveloperLB** [comment]
@drchen I always wished all devices would have updates to new Android versions for a long time.
