### ISSUE TITLE
i have no response from the databaze when i use volley in android studio

### ISSUE THREAD

**Issue by Mohamed1033** [material-components/material-components-android#278]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

**Comment by afohrman** [comment]
This is unrelated to MDC Android. Please ask a question on StackOverflow, and if it's a bug in volley, file an issue here: https://github.com/google/volley/issues.
