### ISSUE TITLE
Support for Vertical Orientation in Chipgroup

### ISSUE THREAD

**Issue by itsniaz** [material-components/material-components-android#279]
Currently, there seems to be no workaround to lay out the chip items vertically. It'd be great to see support for orientation in future versions.

**Comment by wcshi** [comment]
@itsniaz Could you share a mock of the desired behavior? 
Currently, child chips within a chipgroup wrap to the next time (in reflow mode) if there's not enough horizontal space. Are you requesting for a layout that shows one chip per line, even when there is additional horizontal space?

**Comment by afohrman** [comment]
Thanks for the feature request! I've filed an issue in our issue tracker to evaluate the feature request and gather design input. Please share your mocks or other information about this feature request in https://issuetracker.google.com/124911638.

**Comment by itsniaz** [comment]
Desired behaviour
<img src="https://i.stack.imgur.com/Qwabu.png"
     alt="Markdown Monster icon"
     style="float: left; margin-right: 10px;" />

**Comment by anjanaps** [comment]
@itsniaz  Did you get the right way to arrange the chips vertically one after the other?
