### ISSUE TITLE
[Gradient] Would like to see how to handle a gradient in M3.

### ISSUE THREAD

**Issue by SanketDaware01** [material-components/material-components-android#2793]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Can you provide more details?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with more details.
