### ISSUE TITLE
[TabLayout] setSelectedTabIndicatorColor change other component's colors

### ISSUE THREAD

**Issue by safu9** [material-components/material-components-android#2794]
**Description:**
`TabLayout#setSelectedTabIndicatorColor(int)` and its xml attribute `app:tabIndicatorColor` change tint colors of other components which use the same drawable as the tab indicator.

I think this is because `Drawable#mutate()` is not called for tab indicator drawable in TabLayout.

**Expected behavior:**
`TabLayout#setSelectedTabIndicatorColor(int)` and `app:tabIndicatorColor` should not change other component colors.

**Source code:**

First, open an activity with this layout.
```first.xml
<com.google.android.material.tabs.TabLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:tabIndicator="@drawable/red"
    app:tabIndicatorColor="@color/blue" />
```
Then open this, and button color changes to blue.
```second.xml
<Button
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@drawable/red" />
```

**Minimal sample app repro:** [TabLayoutReproduction.zip](https://github.com/material-components/material-components-android/files/9008330/TabLayoutReproduction.zip)
**Android API version:** 31
**Material Library version:** 1.7.0-alpha02
**Device:** Pixel 4 emulator

**Comment by drchen** [comment]
I think in most cases you should avoid using the same drawable in multiple places when you know its state will be changed (like tint, bounds, etc.) As far as I know, even with `mutate()` called, most types of drawables are still sharing the same instance and will affect each other...

Will put a fix to add `mutate()` call, though. This is our common practice no matter what.
