### ISSUE TITLE
[MaterialToolbar] Change scrim of statusBar when scrolling

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#2797]
**Description:** In my app, I'm using `AppBarLayout`, including `MaterialToolbar` and `TabLayout` (see code below). The app looks as follows: https://github.com/patrickfrei/test_coding/blob/main/issue.webm

When I'm scrolling up and down the list, I'd like to dynamically change the color of the statusBar. Example: https://github.com/patrickfrei/test_coding/blob/main/statusBar_dyn_color.mp4

`CollapsingToolbarLayout` provides a feature called `app:statusBarScrim` to achieve that goal. However, `MaterialToolbar` doesn't offer that.

**Expected behavior:** Is there any chance to change the color of the `statusBar` dynamically when using `MaterialToolbar`?

**Source code:** Code of `activity_main.xml`:
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:layoutDirection="locale"
    android:textDirection="locale"
    tools:context=".MainActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            app:layout_scrollFlags="scroll|enterAlways"
            app:title="@string/app_name" />

        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="scroll|enterAlways"
            app:tabMode="scrollable" />

    </com.google.android.material.appbar.AppBarLayout>

    <androidx.viewpager2.widget.ViewPager2
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Minimal sample app repro:** https://github.com/patrickfrei/test_coding/blob/main/issue.webm

**Android API version:** Android API 33

**Material Library version:** 1.7.0-alpha02

**Device:** Pixel 5 emulator

**Comment by hunterstich** [comment]
Hey @patrickfrei,

This is possible without a CollapsingToolbarLayout.

Looking through your sample app, I think you should:

1) Set your theme's `statusBarColor` to `@android:color/transparent`;
2) Remove the `setOnApplyWindowInsetsListener` from MainActivity;
3) let AppBarLayout handle the top window inset by setting activity_main's CoordinatorLayout and AppBarLayout to `fitsSystemWindows=true`;
4) and finally, in MainActivity, set the AppBarLayout's statusBarForeground to a MaterialShapeDrawable with

```
        abl.setStatusBarForeground(MaterialShapeDrawable.createWithElevationOverlay(this));
```

We have a demo in our catalog that does this:
https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/topappbar/TopAppBarScrollingDemoFragment.java#L55-L56
https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/topappbar/res/layout/cat_topappbar_scrolling_fragment.xml#L17-L29

I'm going to go ahead and close this. Let me know if this works for you.

**Comment by patrickfrei** [comment]
Hi @hunterstich,

Thank you very much for your explanations! They helped me a lot! Now, the scroll effect is working perfectly. But unfortunately, another problem arised: At the bottom, the last list item is getting partially covered by the bottom system navigation bar.

If I'm using the gestures with three buttons, it looks even worse. In that case, the last list item is getting fully covered by the system navigation bar. It looks as follows:
- Video: https://github.com/patrickfrei/test_coding/blob/main/issue_2.mp4
- Code https://github.com/patrickfrei/test_coding/blob/main/MyApplication.zip

Is there also a workaround for this issue? Many thanks!!

**Comment by hunterstich** [comment]
Hi,

You can still use an onApplyWindowInsetListener to set your RecyclerView's end padding to the bottom inset. Make sure not to mark the top inset as consumed so AppBarLayout will be able to handle that for you. 

I would highly recommend these articles which go over handling visual overlaps/conflicts within system areas:
https://medium.com/androiddevelopers/gesture-navigation-handling-gesture-conflicts-8ee9c2665c69
https://developer.android.com/training/gestures/edge-to-edge#handle-overlaps

**Comment by patrickfrei** [comment]
Hi @hunterstich,

Many thanks for your help. As suggested, I've read the articles and added  `setOnApplyWindowInsetsListener` and the margins are now correctly set. There are no overlaps anymore. I've implemented below code snippet to achieve that (also see the complete code [here](https://github.com/patrickfrei/test_coding/blob/main/MyApplication.zip)). 

Is this code also best practice from your point-of-view?
```
View view = findViewById(R.id.main_content);
            setOnApplyWindowInsetsListener(view, (v, windowInsets) -> {
                Insets insets = windowInsets.getInsets(WindowInsetsCompat.Type.systemGestures());

                View scrollable = mViewPager; /* R.id.container */
                scrollable.setPadding(
                        scrollable.getPaddingLeft(),
                        scrollable.getPaddingTop(),
                        scrollable.getPaddingRight(),
                        insets.bottom
                );

                return windowInsets;
            });
```

**Comment by hunterstich** [comment]
That all looks good to me, @patrickfrei

**Comment by patrickfrei** [comment]
Great. Many thanks, @hunterstich
