### ISSUE TITLE
[OutlinedButton] colorOnSurface does not apply to the text color

### ISSUE THREAD

**Issue by almr0** [material-components/material-components-android#2810]
The documentation clearly states that colorOnSurface is responsible for the color of the text. In the theme, the attribute is declared and has a white color. But the color of the text is completely different. Most likely, it becomes so from the colorPrimary attribute

**Comment by hunterstich** [comment]
Hi @almr0,

Are you referring to Material2 or Material3? What style is your button using? Widget.MaterialComponents.Button.* or Widget.Material3.Button.*? What version of the documentation are you looking at?

From our styles, Material3 text buttons are using colorOnSurface. However, that color will be altered if you're using dynamic colors.

**Comment by almr0** [comment]
> Hi @almr0,
> 
> Are you referring to Material2 or Material3? What style is your button using? Widget.MaterialComponents.Button.* or Widget.Material3.Button.*? What version of the documentation are you looking at?
> 
> From our styles, Material3 text buttons are using colorOnSurface. However, that color will be altered if you're using dynamic colors.

I'm using Material 3 and the style is Widget.Material3.Button.Outlined. As I said before, the colorOnSurface attribute doesn't work in this button. This attribute contains the #FFFFFFFF color, but for some reason the blue color is applied to the text, and it's only in the colorPrimary attribute. Setting textColor=?attr/colorOnSurface works properly. But why do I have to do this? The documentation says that colorOnSurface applies itself by default.
Переведено с помощью DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
