### ISSUE TITLE
Bottom Navigation View colors not updating based on dynamic theme

### ISSUE THREAD

**Issue by backslashV** [material-components/material-components-android#2814]
I have a bottom navigation view in my app. I also have dynamic coloring enabled by extending the Application class like so:

```
public class BottomNavBarApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        DynamicColors.applyToActivitiesIfAvailable(this);
    }
}
```

And modifying AndroidManifest to have android:name=".BottomNavBarApplication". All elements including buttons, top app bar, ... update with dynamic theme change. However, the buttom nav view background color stays the same color I defined in themes.xml (reddish tint).

Here's my layout XML:

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@+id/bottom_navigation"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">
    </FrameLayout>

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:itemBackground="@android:color/transparent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:menu="@menu/bottom_nav_menu" />

</androidx.constraintlayout.widget.ConstraintLayout>
```
and my build.gradle dependecies:

```
dependencies {
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.navigation:navigation-fragment:2.5.0'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'com.google.code.gson:gson:2.9.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
```
I am not modifying the background color in Java code either. My theme is also extending from _Theme.Material3.DayNight.NoActionBar_.

[Example screenshots](https://imgur.com/a/mPPs3BH) with three different dynamic theme colors. Note the bottom nav view has a reddish tint. Any ideas?

[Example](https://imgur.com/a/ZrmsKt8) of how it should look like (from the Google Contacts app).

Also, I am not sure how to achieve the same [bouncy animation](https://imgur.com/a/06hL9eu) Google Contacts app has when selecting an item from the bottom nav view.

**Comment by drchen** [comment]
> However, the buttom nav view background color stays the same color I defined in themes.xml (reddish tint).

How do you set it in your themes.xml?

**Comment by drchen** [comment]
Can you create a minimal reproducible sample? I don't see anything strange in the code you've provided. 

If you call `DynamicColors.applyToActivitiesIfAvailable(this);` before `super.onCreate();`, will it wotk?

**Comment by backslashV** [comment]
> Can you create a minimal reproducible sample? I don't see anything strange in the code you've provided.
> 
> If you call `DynamicColors.applyToActivitiesIfAvailable(this);` before `super.onCreate();`, will it wotk?

Sure, please see [here](https://github.com/backslashV/issuewithbottomnavbarcolor). Calling DynamicColors.applyToActivitiesIfAvailable(this); before super.onCreate(); didn't make a difference.

**Comment by drchen** [comment]
So I think the issue is that you are overriding:

"""
 <item name="elevationOverlayColor">@color/md_theme_dark_surfaceTint</item>
"""

But not overriding it in the dynamic color theme overlay as well. 
I agree it's a bit confusing that you will have to do that but don't have to override normal color roles like colorPrimary. 
The reason behind this is that elevationOverlayColor is supposed to be colorPrimary by design - once you break the link you will have to take the responsibility to decide what elevationOverlayColor should be under the dynamic color scenario, since in theory it should not be colorPrimary anymore.

Hope this makes sense. 

#2829 is more or less a duplicate issue of this. You can refer to it for more info as well.
