### ISSUE TITLE
Release notes for 1.7.0-alpha03?

### ISSUE THREAD

**Issue by drmrbrewer** [material-components/material-components-android#2823]
I note that `1.7.0-alpha03` is available for use in Android Studio but I can't see anything about this release in [the release notes](https://github.com/material-components/material-components-android/releases).

**Comment by drchen** [comment]
Can you try to refresh your webpage? I'm pretty sure the release note is published yesterday (and several users already interacted with it.)

**Comment by drmrbrewer** [comment]
It's definitely not there on the main releases page, even after refreshing / hard-refreshing / clearing cache / etc:

![image](https://user-images.githubusercontent.com/9009792/179245929-e1ce704a-e46b-4745-a6b0-01d2ebf076cf.png)

But it is visible if (on the main releases page) I click on Tags, then 1.7.0-alpha03:

![image](https://user-images.githubusercontent.com/9009792/179245800-22beaa03-19af-4892-bf44-cc52595dce60.png)

So it has been tagged, but not released?

**Comment by drchen** [comment]
Can you clear your browser cache and try again? It definitely shows on the releases page when I open it....

**Comment by drmrbrewer** [comment]
I've cleared cache several times already.  I've tried accessing it with Dev Tools open Network tab open and Disable Cache ticked, re-loaded with Ctrl-F5... all the time I get a releases page that has no mention of 1.7.0-alpha03.  I can see from the Network tab that all resources are being fetched, not from cache.

For the avoidance of doubt, I'm talking about this page:

https://github.com/material-components/material-components-android/releases

**Comment by drchen** [comment]
It's weird because it's definitely there....

Are you able to use VPN to open the page from a different region or via a different route? 
I really have no idea on top of my head.

**Comment by drmrbrewer** [comment]
I tried via mobile Chrome browser over cellular data rather than WiFi... I assume this would be via a different route than WiFi.  Still the same.  Never mind, it's not critical, just strange!

**Comment by drmrbrewer** [comment]
@patzly I'm glad it's not just me!  I too can see alpha03 on the releases page in the Android GitHub app, but still not on the web page.  It's odd that the web page is showing alpha03 for some though, like @drchen... possibly browser/version dependent (mine is Windows Chrome Version 103.0.5060.114).

**Comment by drchen** [comment]
Hmm... that's very odd. Let me ask my team if anyone is also seeing this issue. : )

**Comment by drchen** [comment]
It looks like the page indeed has some problem. I'll reopen the issue until it's solved. : (

**Comment by drchen** [comment]
It should be fixed now. Please try it again. (Seems like a weird github issue.)

**Comment by drchen** [comment]
Awesome! Sorry for the confusions and inconvenience!
