### ISSUE TITLE
Splash Screen with DynamicColor issue 

### ISSUE THREAD

**Issue by imandaliya** [material-components/material-components-android#2824]
Main theme : Theme.Material3.DayNight.NoActionBar
Splash theme : Theme.SplashScreen

Dynamic color not set on post theme while using DynamicColors.applyToActivitiesIfAvailable(this) in Application Class

Testing Emulator : Resizable Emulator, API Version 33

**Comment by drchen** [comment]
yeah unfortunately it's a framework limitation. 

If you need to use dynamic colors in your splash screen theme, the easiest way is directly use system dynamic color resources in your splash screen theme.

`@color/system_accent1_0`...`system_accent1_1000`
`@color/system_accent2_0`...`system_accent2_1000`
`@color/system_accent3_0`...`system_accent3_1000`
`@color/system_neutral1_0`...`system_neutral1_1000`
`@color/system_neutral2_0`...`system_neutral2_1000`
