### ISSUE TITLE
Material3 -  Transition Animation Problem Day Night Mode

### ISSUE THREAD

**Issue by vimalcvs** [material-components/material-components-android#2826]
**How to fix .. Transition Animation Problem Day Night Mood** 

**Expected behavior:** Screenshots and/or description of expected behavior check back animation 

Night Mode is good work but Light Mode 👎

<img src="https://raw.githubusercontent.com/vimalcvs/Material3-Bug/main/gif.gif" alt="J" width="300"/>

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)and (:material:1.6.1)

<img src="https://raw.githubusercontent.com/vimalcvs/Material3-Bug/main/image-bug.png" alt="J" width="500"/>

**Device:** All device

**Code** https://github.com/vimalcvs/Material3-Bug

**Comment by drchen** [comment]
It looks more like an AppCompat issue with local night mode. 
I checked the code and there doesn't seem having something to do with the Material library. 

Please file a bug to AndroidX instead:
https://source.android.com/setup/contribute/report-bugs
