### ISSUE TITLE
[Button] Ripple and icon colors do not match M3 specs

### ISSUE THREAD

**Issue by OxygenCobalt** [material-components/material-components-android#2827]
**Description:** According to the [Material Design 3 specs](https://m3.material.io/components/icon-buttons/specs), unselected normal (`Widget.Material3.Button.IconButton`) and outlined (Widget.Material3.Button.IconButton.Outlined) icon buttons should have a ripple and icon tint based on `colorOnSurfaceVariant`   Instead, since they are based on `Widget.Material3.Button.TextButton`, they actually have tints based on `colorPrimary`. This makes sense if the button was selected, but not when it is unselected.

**Expected behavior:** For icon and ripple tints in the said themes to be based on `colorOnSurfaceVariant` when unselected.

**Source code:** Any `MaterialButton` applying this theme will have the issue.

**Material library version:** 1.7.0-alpha03

**Comment by drchen** [comment]
`?attr/materialThemeOverlay` will override the color you mentioned. 

I don't see there's an issue in the current color settings. (They are based on colorOnSufaceVariant correctly.)

**Comment by OxygenCobalt** [comment]
Can you provide an example of how I'm supposed to be using that in XML? @drchen

**Comment by drchen** [comment]
Are you trying to override the colors or?

**Comment by OxygenCobalt** [comment]
Oh. Looking into the code, I know see what you mean. I can just override `colorContainer` and `colorOnContainer`. I just find it strange that the default button style is seemingly the *checked* style (`colorPrimary`) and not the *unchecked* style. @drchen

**Comment by drchen** [comment]
Yes, you are right. : )

**Comment by OxygenCobalt** [comment]
Okay, cool. Is there any reason for why the checked style is the default though? If one set `android:checkable` to `false`, shouldn't that imply they want to have an unchecked style? @drchen

**Comment by drchen** [comment]
I think designers want to view "uncheckable" and "checkable" icon buttons as different styles. : )

**Comment by OxygenCobalt** [comment]
Oh, okay then.
