### ISSUE TITLE
[Switch] MaterialSwitch is not applied to SwitchPreferenceCompat

### ISSUE THREAD

**Issue by OxygenCobalt** [material-components/material-components-android#2828]
**Description:** I leverage `SwitchPreferenceCompat` in the preference screen of my app. Even though MDC has released the new switch component in an unstable version, the new switches will not appear on the preference screen.

This can be traced back to the preference implementation inflating a `Switch`, but `MaterialComponentsViewInflater` not intercepting that inflation and replacing it with an analogous `MaterialSwitch`. 

**Expected behavior:** The preference screen should leverage `MaterialSwitch`.

**Source code:** Occurs with any `SwitchPreferenceCompat` instance.

**Android API version:** Any API version

**Material Library version:** 1.7.0-alpha03

**Device:** Pixel 5

**Comment by drchen** [comment]
This is the right way to do that. 

We are still discussing if we should include the support by default in the Material themes. However we are not sure if we should make the Material library depend on the androidx preference library, which is actually more "high-level" in a sense.

I'll close the issue for now since the solution mentioned in the above comment is more or less the "right" way to make androidx preference render Material switches.

We also have an internal action item to track this, once we know the decision we will update here as well.

**Comment by OxygenCobalt** [comment]
Okay, no problem.

**Comment by IMG-BrandonIceberg** [comment]
@bubbleguuum using this worked, however I noticed the behavior when you select the preference (not the switch itself) does not toggle the switch. Did you ever find a way around this?

**Comment by bubbleguuum** [comment]
@IMG-BrandonIceberg 

I do not remember the specifics since it was a long time ago, but I have `@layout/view_preference_switch` defined like this:

```
<com.google.android.material.materialswitch.MaterialSwitch xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/switchWidget"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:focusable="false"
    android:clickable="false"
    android:background="@null" />
```

it might be sufficient to fix your issue but in case it doesn't I also have this:

styles.xml:

```
    <style name="MaterialPreferenceThemeOverlay" parent="PreferenceThemeOverlay">
        <item name="switchPreferenceCompatStyle">@style/App.Preference.SwitchPreferenceCompat</item>
    </style>

    <style name="App.Preference.SwitchPreferenceCompat" parent="Preference.SwitchPreferenceCompat.Material">
        <item name="android:widgetLayout">@layout/view_preference_switch</item>
    </style>

```

in my theme definition in `themes.xml`:

```
    <!-- replace SwitchCompat with MaterialSwitch in prefs -->
        <item name="preferenceTheme">@style/MaterialPreferenceThemeOverlay</item>

   <!-- Optional: add a check icon when a switch is enabled -->
        <item name="materialSwitchStyle">@style/Widget.App.CompoundButton.MaterialSwitch.Check</item>
```
