### ISSUE TITLE
[MaterialToolbar] Dynamic color not applied

### ISSUE THREAD

**Issue by ozgurg** [material-components/material-components-android#2829]
**Description:** If a custom color is applied, the dynamic color is not applied to the `MaterialToolbar`, but is applied to all other components.

**Expected behavior:** Background color of `MaterialToolbar` should be brown (chosen system color) like other components.

**Minimal sample app repro:** [MaterialToolbarColorBug.zip](https://github.com/material-components/material-components-android/files/9128735/MaterialToolbarColorBug.zip)

**Android API version:** 32

**Material Library version:** 1.7.0-alpha03

**Device:** Resizable emulator

Explanation of the video:
1) I showed that brown is selected as the system color
2) I showed that I enabled dynamic colors in App.kt
3) I started the app and I showed that FAB, Next button and MaterialToolbar are brown
4) I enabled the theme definitions in themes.xml and restarted the app (I created the theme in Material Theme Builder)
5) FAB and Next button are still brown but the MaterialToolbar is blue. That's the issue

https://user-images.githubusercontent.com/6717356/179428816-866254f2-a825-4081-830f-d98dbb180a71.mp4

**Comment by imandaliya** [comment]
There is bug in Material theme with Dynamic color, because attribute "elevationOverlayColor" added recently and dynamic color library not updated with it, so elevationOverlayColor not converted in Dynamic color.

You can solve this error by removing "elevationOverlayColor" in your style.

![Screenshot 2022-07-18 at 11 15 19 AM](https://user-images.githubusercontent.com/971804/179451920-b3e82211-211e-44c5-a7dc-a6f0b3a85b73.png)

**Comment by ozgurg** [comment]
> There is bug in Material theme with Dynamic color, because attribute "elevationOverlayColor" added recently and dynamic color library not updated with it, so elevationOverlayColor not converted in Dynamic color.
> 
> You can solve this error by removing "elevationOverlayColor" from your style.
> 
> ![Screenshot 2022-07-18 at 11 15 19 AM](https://user-images.githubusercontent.com/971804/179451920-b3e82211-211e-44c5-a7dc-a6f0b3a85b73.png)

It worked, thank you. I hope this bug will be fixed soon.

**Comment by ashutoshgngwr** [comment]
> Once you customize elevationOverlayColor, i.e., break the link between colorPrimary and it, you will need to take your own responsibility to assign the elevationOverlayColor in your custom ?attr/dynamicColorThemeOverlay.

@drchen In that case, the theme builder shouldn't explicitly set its value.

**Comment by drchen** [comment]
That's a good point. I'll raise this to the owner of the theme builder.

**Comment by drchen** [comment]
The theme builder should be fixed now. : )

**Comment by imandaliya** [comment]
> That's a good point. I'll raise this to the owner of the theme builder.

Thank you
