### ISSUE TITLE
FloatingActionButton warning in logcat: Setting a custom background is not supported

### ISSUE THREAD

**Issue by adil-hussain-84** [material-components/material-components-android#283]
I'm using the latest version of the `com.google.android.material:material` library (i.e. `1.1.0-alpha03`) and I have an app theme defined as follows...

```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
    <item name="colorAccent">@color/green</item>
    <item name="colorControlHighlight">@color/green</item>
    <item name="colorPrimary">@color/green</item>
    <item name="colorPrimaryDark">@color/dark_green</item>
    <item name="colorOnPrimary">@color/white</item>
    <item name="colorSecondary">@color/green</item>
    <item name="colorOnSecondary">@color/white</item>
</style>
```

... and a `FloatingActionButton` defined as follows...

```
<com.google.android.material.floatingactionbutton.FloatingActionButton
    android:id="@+id/floatingActionButton"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:fabSize="normal"
    app:srcCompat="@drawable/icon_plus" />
```

... the `FloatingActionButton` is displaying perfectly fine in my app but I'm seeing the following message in Logcat...

```
I/FloatingActionButton: Setting a custom background is not supported.
```

... I'm not setting a background on the `FloatingActionButton` anywhere in my app.

Is it something I've done incorrectly in setting up the `FloatingActionButton` to trigger this message or is it a bug?

**Comment by ymarian** [comment]
Hi good catch, this is because we are setting a background in Widget.Design.FloatingActionButton.
you can add android:background="@null" to your fab or safely ignore this warning. I'll see if we can set that in the default style.
