### ISSUE TITLE
[TextField] editText onTouchListener should be onClickListener

### ISSUE THREAD

**Issue by kelvinwatson** [material-components/material-components-android#2840]
**Description:** DropdownMenuEndIconDelegate sets a touch listener on the autocomplete `editText` in DropdownMenuEndIconDelegate.java. The `return false` results in this touch listener being triggered twice, once for `MotionEvent.ACTION_UP` and once for the subsequent `MotionEvent.ACTION_DOWN`.

<img src="https://user-images.githubusercontent.com/11381360/179859269-708ec174-0c1a-42df-9d90-92d0f0ce0cc1.gif" width="350">

**Expected behavior:** Observe in the video the double ripple effect due to onTouchListener being triggered twice. It should only be a single ripple effect.

**Source code:** 

```
  private void setUpDropdownShowHideBehavior(@NonNull final AutoCompleteTextView editText) {
    // Set whole layout clickable.
    editText.setOnTouchListener( // this should be a click listener
        new OnTouchListener() {
          @Override
          public boolean onTouch(@NonNull View v, @NonNull MotionEvent event) {
            if (event.getAction() == MotionEvent.ACTION_UP) {
              if (isDropdownPopupActive()) {
                dropdownPopupDirty = false;
              }
              showHideDropdown(editText);
              updateDropdownPopupDirty();
            }
            return false;
          }
        });
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 31

**Material Library version:** 1.6.1

**Device:** Pixel 4 API 31 xxhdpi emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
I don't see the double ripple effect happening in our MDC catalog, are you doing anything else to the menu?

The code in the touch listener is only triggered if the event is `MotionEvent.ACTION_UP` so it's ignored for any other motion events. Unfortunately, we can't switch that to be a click listener because it would break the current behavior, as a click listener is only triggered if the text input layout has focus.
