### ISSUE TITLE
[TextInputLayout] Error message padding/margin how to change?

### ISSUE THREAD

**Issue by gongxh13** [material-components/material-components-android#2843]
**Is your feature request related to a problem? Please describe.**
I am using TextInputLayout, but found error text can not change padding or margin,  

**Describe the solution you'd like**
Want to change error text padding or margin.

**Comment by Ongnon1990** [comment]
https://user-images.githubusercon![20230311_043755.jpg](https://user-images.githubusercontent.com/121402703/224521355-4f3263e6-11c2-41df-9334-7f986535c277.jpg)

cd85-487a-bbbf-e0c9352cf58c.mp4

![Uploading 20230311_043755.jpg …]()
