### ISSUE TITLE
[Tooltip] TooltipCompat.setTooltipText is using platform Tooltips on API >= 26

### ISSUE THREAD

**Issue by malloth** [material-components/material-components-android#2844]
**Description:**

When calling `TooltipCompat.setTooltipText()` method I expect to always get a compatible tooltip (using `TooltipCompatHandler` class) no matter which version of Android I'm running on. This is because only the compat version allows to change the tooltip look through `tooltipStyle`, `tooltipForegroundColor` and `tooltipFrameBackground` theme attributes - system ones are private and can not be changed. I also expect other views like: tabs, toolbars etc. to show my custom tooltips instead of the default platform ones.

**Expected behavior:**

`TooltipCompat.setTooltipText()` to always use `TooltipCompatHandler` class no matter which Android version it's running on.

**Source code:**

```java
public class TooltipCompat  {
    /**
     * Sets the tooltip text for the view.
     * <p> Prior to API 26 this method sets or clears (when tooltip is null) the view's
     * OnLongClickListener and OnHoverListener. A toast-like subpanel will be created on long click
     * or mouse hover.
     *
     * @param view the view to set the tooltip text on
     * @param tooltipText the tooltip text
     */
    public static void setTooltipText(@NonNull View view, @Nullable CharSequence tooltipText) {
        if (Build.VERSION.SDK_INT >= 26) {
            view.setTooltipText(tooltipText);
        } else {
            TooltipCompatHandler.setTooltipText(view, tooltipText);
        }
    }

    private TooltipCompat() {}
}
```

**Minimal sample app repro:** N/A

**Android API version:** N/A

**Material Library version:** 1.6.1

**Device:** Any

**Comment by drchen** [comment]
TooltipCompat is not part of the Material library. 

As far as I know it's a standard practice that AppCompat will fallback to the framework implementation whenever its available (and stable).

If you think this is a bug, please file it against the AndroidX/AppCompat:
https://source.android.com/setup/contribute/report-bugs
