### ISSUE TITLE
Dynamic themes

### ISSUE THREAD

**Issue by DeMoss15** [material-components/material-components-android#285]
Hi! 

I've just started to learn dynamic theme. My current project is based on andoidx and material components. So I've decided to try this on it. After following [articles from Medium](https://medium.com/mindorks/mastering-android-themes-chapter-4-591e03320182). I found that this approach doesn't work with material components. Of cource I've also reviewed official [documentation](https://developer.android.com/guide/topics/ui/look-and-feel/themes)

The issue is I can't change theme in the Runtime. I'm trying to do it this way:
```
// code from TestsFragment
    private val themes = listOf(
        R.style.AppTheme_Red,
        R.style.AppTheme_Blue,
        R.style.AppTheme_Green,
        R.style.AppTheme
    )
    private var currentTheme = 0

    override fun onFabPressed() {
        activity?.setTheme(themes[currentTheme++ % themes.size])
        activity?.recreate()
        // TODO: Uncomment when dynamic theme issue will be resolved
    }
```
But after changing theme in the Manifest and recompile new theme is applied.

[Here](https://github.com/DeMoss15/EasyToTest/tree/dynamic_themes) you can see my implementation. I may be wrong...
If it's not a library issue it will be great to get some useful advices or links :)

**Comment by ymarian** [comment]
Hi, I believe you just have to call setTheme in the onCreate method of the activity. The way we implement something similar to what you have is by setting the theme in static state, having the activity read that onCreate. That way when you call recreate the activity will set the right thing. 

Checkout https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/themeswitcher/ThemeOverlayUtils.java

**Comment by DeMoss15** [comment]
Thank you for answer. I've tried again and now it works when I call setTheme before `super.onCreate(savedInstanceState)` call.
