### ISSUE TITLE
[BottomAppBar] children are not laid out correctly

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#2852]
**Description:** The children of BottomAppBar are not laid out correctly when app:menuAlignmentMode is start (The children of BottomAppBar are laid out correctly when app:menuAlignmentMode is auto).
https://github.com/material-components/material-components-android/commit/397e48f2790a95878caf7523a026eabfac286c07
![Screenshot_20220722_125942](https://user-images.githubusercontent.com/71050561/180359724-25751a28-3757-45b5-8b06-88ac6bb92b48.png)

**Expected behavior:** The children of BottomAppBar are laid out correctly when app:menuAlignmentMode is start.
![Screenshot_20220720_142926](https://user-images.githubusercontent.com/71050561/180358809-388597c3-fbc3-437c-a0a9-36d4294ca306.png)

**Source code:**
```
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.google.android.material.bottomappbar.BottomAppBar
        android:layout_width="match_parent"
        android:layout_height="?actionBarSize"
        android:layout_gravity="bottom"
        android:layout_marginBottom="?actionBarSize"
        app:menu="@menu/main"
        app:menuAlignmentMode="auto">
        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="@string/auto" />
    </com.google.android.material.bottomappbar.BottomAppBar>
    <com.google.android.material.bottomappbar.BottomAppBar
        android:id="@+id/appBar"
        android:layout_width="match_parent"
        android:layout_height="?actionBarSize"
        android:layout_gravity="bottom">
<!--        app:menuAlignmentMode="start"-->
        <Button
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="@string/start" />
    </com.google.android.material.bottomappbar.BottomAppBar>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```
The default value of app:menuAlignmentMode (Widget.Material3.BottomAppBar) is not auto but start.
https://m3.material.io/components/bottom-app-bar/implementation
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomappbar/res/values/styles.xml#L64
<s>https://github.com/material-components/material-components-android/blob/master/docs/components/BottomAppBar.md
https://github.com/material-components/material-components-android/commit/397e48f2790a95878caf7523a026eabfac286c07</s>
https://github.com/material-components/material-components-android/commit/276a0a3c5132a54ac9f1d7fafbd2ebbb084ac7d1

**Minimal sample app repro:** [Test1.zip](https://github.com/material-components/material-components-android/files/9164553/Test1.zip)

**Android API version:** 32

**Material Library version:** 1.7.0-alpha03

**Device:** Emulator 31.2.10

**Comment by imhappi** [comment]
This is working as intended

The intended usage of the M3 bottom app bar is to use it with a end-aligned floating action button in a coordinator layout;
menuAlignment simply moves the menu items to the 'start' or 'auto' (which always moved the menu item to the 'end', unless the fab alignment mode was 'end' in which case it moved it to 'start'). The menu alignment does not have any knowledge or care about the placement of the bottom app bar's children, because it doesn't expect children

Also, according to M3 specs, the menu items should always be start-aligned. `auto` is an option just to accommodate the M2 behavior.

**Comment by manabu-nakamura** [comment]
It is very disappointing. When the BottomAppBar has children, I will adjust the position manually with android:paddingEnd="-40dp" and app:contentInsetStart="44dp".
