### ISSUE TITLE
[TopAppBar] TopAppBar is flickering when changing tabs and using app:liftOnScrollTargetViewId

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#2856]
**Description:** I've created an app with different tabs whereas each tab contains a separate fragment with separate id's. Each fragment contains a `RecyclerView`. The main activity setup consists of `AppBarLayout`, `MaterialToolbar` and `TabLayout` followed by a `ViewPager2`. In order to control the color effect when lifting the AppBar, I'm using `app:liftOnScrollTargetViewId` in `addOnTabSelectedListener` of the `TabLayout`. The list is updated in the background by a handler.

I've noticed the following behavior when two adjacent tabs are in different states:
1) The AppBar of the first tab (called "Alpha") is in lifted state whereas the AppBar of the second tab (called "Beta") is not in lifted state. That means that the AppBar of tab "Alpha" has a darker color (light-grey) than the one from tab "Beta" (white).
2) When switching between the tabs, the AppBar is flickering. See video: https://github.com/patrickfrei/test_coding/blob/main/issue.mp4
3) Looking closely at that video you can see the following effects (you have to scroll manually and very slowly through the video):
   ==> When switching from tab "Alpha" to "Beta", the AppBar color is changing from light-grey to white, then again to light-grey and is then fading to white.
   ==> When switching from tab "Beta" to "Alpha", the AppBar color is changing from white to dark-grey (for the AppBar only) and then to light-grey (for status bar and AppBar; seems to be adapting to the status bar color).

I was debugging the code and modified different parameters of the `AppBarLayout`. I couldn't find the exact reason for the flickering but it seems to me that the logic behind `app:liftOnScrollTargetViewId` somehow interferes with the default elevation-parameter of the `AppBarLayout`. They seem to have different colors in different layout states.

**Expected behavior:** The AppBar doesn't flicker when switching from one tab to another.

**Source code:** 
```
tabLayout.addOnTabSelectedListener(
                new TabLayout.OnTabSelectedListener() {
                    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
                    @Override
                    public void onTabSelected(TabLayout.Tab tab) {
                        int recyclerviewId;
                        switch (tab.getPosition()) {
                            case 0:
                                recyclerviewId = R.id.tab1ListView;
                                break;
                            case 1:
                                recyclerviewId = R.id.tab2ListView;
                                break;
                            default:
                                recyclerviewId = R.id.tab1ListView;
                        }
                        AppBarLayout appBarLayout = findViewById(R.id.appbar);
                        appBarLayout.setLiftOnScrollTargetViewId(recyclerviewId);
                    }
                    @Override
                    public void onTabUnselected(TabLayout.Tab tab) {
                        // no-op
                    }
                    @Override
                    public void onTabReselected(TabLayout.Tab tab) {
                        // no-op
                    }
                }
        );
```
**Minimal sample app repro:** For the whole code, a sample app and a video, see here: https://github.com/patrickfrei/test_coding

**Android API version:** 33

**Material Library version:** 1.7.0-beta01

**Device:** Pixel 5 emulator and various real devices such as e.g. Nokia 7.2

**Comment by patrickfrei** [comment]
Hi @dsn5ft & @paulfthomas ,

I've found the cause of the flickering: The issue occurs in `AppBarLayout` in `startLiftOnScrollElevationOverlayAnimation` (see below). More precisely, `onAnimationUpdate` is processed multiple times with `fromElevation` (10.5), `toElevation` (0.0) and `fromElevation` (10.5) and vice versa. Everytime, `background.setElevation(elevation);` is set with these different elevation values and this makes the AppBar flickering.

I hope that this helps you to fix the issue.

```
private void startLiftOnScrollElevationOverlayAnimation(
      @NonNull final MaterialShapeDrawable background, boolean lifted) {
    float appBarElevation = getResources().getDimension(R.dimen.design_appbar_elevation);
    float fromElevation = lifted ? 0 : appBarElevation;
    float toElevation = lifted ? appBarElevation : 0;

    if (elevationOverlayAnimator != null) {
      elevationOverlayAnimator.cancel();
    }

    elevationOverlayAnimator = ValueAnimator.ofFloat(fromElevation, toElevation);
    elevationOverlayAnimator.setDuration(
        getResources().getInteger(R.integer.app_bar_elevation_anim_duration));
    elevationOverlayAnimator.setInterpolator(AnimationUtils.LINEAR_INTERPOLATOR);
    elevationOverlayAnimator.addUpdateListener(
        new AnimatorUpdateListener() {
          @Override
          public void onAnimationUpdate(@NonNull ValueAnimator valueAnimator) {
            float elevation = (float) valueAnimator.getAnimatedValue();
            background.setElevation(elevation);
            if (statusBarForeground instanceof MaterialShapeDrawable) {
              ((MaterialShapeDrawable) statusBarForeground).setElevation(elevation);
            }
            for (LiftOnScrollListener liftOnScrollListener : liftOnScrollListeners) {
              liftOnScrollListener.onUpdate(elevation, background.getResolvedTintColor());
            }
          }
        });
    elevationOverlayAnimator.start();
  }
```

**Comment by paulfthomas** [comment]
@patrickfrei thank you for the detailed info! We will take a look into it as soon as we can.

**Comment by patrickfrei** [comment]
@paulfthomas 
You're welcome. Now, I've added a potential solution and a temporary workaround to above message. Basically, you could just remove `refreshDrawableState()` in `setLiftedState`. I've modified your library accordingly and didn't observe any issues from that change (at least not in my app). Don't know if that code is really required...

**Comment by OxygenCobalt** [comment]
Just chiming in that I have a very similar issue, although it only appears when fast-scrolling from/to the top of a list. Not sure if it's caused by the same issue, but hoping that this might be the cause too.

**Comment by aberaud** [comment]
We have the same issue as @OxygenCobalt : the AppBar is flickering when fast scrolling the list, but also while other animations occur - for instance while the `ExtendedFloatingActionButton` is shrinking or expanding.

Adding `<integer name="app_bar_elevation_anim_duration" tools:override="true">0</integer>` to value resources doesn't fix the issue (it flickers but without fading).

**Comment by patrickfrei** [comment]
@aberaud 
You could also try to remove `refreshDrawableState()` in `setLiftedState` as mentioned above. This fixed the flickering in my use case while keeping the fading.

**Comment by aberaud** [comment]
@patrickfrei Thanks for the suggestion, unfortunately, this requires forking the Material library which is not an option for us at the moment for our production builds.

**Comment by imhappi** [comment]
This seems to be a bug that is caused by having both the state list animator and the elevation overlay animator

I'm not sure if the state list animator is safe to remove and will require some more investigation as it's legacy code, but if you have a color background on the app bar layout (which the material styling does, unless it was manually overridden), I think it'll be fine as a temporary workaround to add `android:stateListAnimator="@null"` to the app bar layout like so:

```
  <com.google.android.material.appbar.AppBarLayout
    android:id="@+id/appbar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:stateListAnimator="@null">
...
```

**Comment by OxygenCobalt** [comment]
Can confirm that this seemingly resolves my issue regarding fast scrolling. @aberaud

**Comment by patrickfrei** [comment]
@imhappi 
That workaround has also resolved the issue in my use case. Many thanks!
