### ISSUE TITLE
[MaterialDateRangePicker] Focus Color is not aligned for numbers when set theme to Dynamically

### ISSUE THREAD

**Issue by GChakrapani** [material-components/material-components-android#2858]
Numbers are not aligned  properly when set theme to Dynamically.

Used "@style/Theme.AppCompat.NoActionBar" in application in ANdroidManifest file and Applied Material theme for DateRangeCalendar using setTheme API dynamically

android:name="com.testapp.android.TestApplication"
        android:theme="@style/Theme.AppCompat.NoActionBar"

**Code Snippet :**

		MaterialDatePicker.Builder<Pair<Long, Long>> materialDateBuilder = MaterialDatePicker.Builder.dateRangePicker();
		materialDateBuilder.setTitleText("Select Dates");
		int calTheme = KonyMain.getAppContext().getResources().getIdentifier("DateRangeCal1", "style", MyActivity.getAppContext().getPackageName());
		materialDateBuilder.setTheme(calTheme);
		final MaterialDatePicker materialDatePicker = materialDateBuilder.build();
		materialDatePicker.show(KonyMain.getActContext().getSupportFragmentManager(), "MATERIAL_DATE_PICKER");

**Style :**
    <style name="DateRangeCal1" parent="Theme.MaterialComponents.NoActionBar">
    </style>
	
Note : Not able to attach image

**Comment by drchen** [comment]
You will need to use Material themes as your app/activity theme to have the correct Date Picker styles. : )

It's a bit confusing but `Builder.setTheme()` is used to set an overriding theme to override the themes specified by the app/activity theme's `?attr/materialCalenderTheme` and `?attr/materialCalenderFullScreenTheme` attributes.

**Comment by GChakrapani** [comment]
I am using the ApppCompat theme for Activity/Application and set material theme to DataRangeCalendar using setTheme API.

**Comment by drchen** [comment]
That won't work. I don't really think we support using Date Picker with AppCompat themes but you can try to call setTheme() with `ThemeOverlay.Material3.MaterialCalendar` and see if it works. If not, unfortunately you will have to use Material themes as your app/activity theme...
