### ISSUE TITLE
[MaterialDatePicker] How to achieve Month pagination in Date Range Calendar

### ISSUE THREAD

**Issue by GChakrapani** [material-components/material-components-android#2859]
Month pagination is not enabled for DateRangeCalendar by default.  How to achieve Month pagination in Date Range Calendar to navigate next and previous months  instead  of scrolling for previous/next months.

Used "Theme.MaterialComponents.DayNight.DarkActionBar" for application.

**Code Snippet :**
            val constraints = CalendarConstraints.Builder()
                .setStart(MaterialDatePicker.thisMonthInUtcMilliseconds())
                .setValidator(DateValidatorPointForward.now())
                .build()
            val datePickerBuilder: MaterialDatePicker.Builder<Pair<Long, Long>> = MaterialDatePicker
                .Builder
                .dateRangePicker()
                .setInputMode(MaterialDatePicker.INPUT_MODE_CALENDAR)
                .setTitleText("Select a date")
                .setCalendarConstraints(constraints)
            val datePicker = datePickerBuilder.build()
            datePicker.show(supportFragmentManager, "DATE_PICKER_RANGE")

**Comment by drchen** [comment]
You can use `Builder.setTheme(R.style.ThemeOverlay.Material3.MaterialCalendar);`

(Or `Builder.setTheme(R.style.ThemeOverlay. MaterialComponents.MaterialCalendar);` if you are still using M2 themes; but I strongly recommend you to update to M3 to have the full support.)
