### ISSUE TITLE
How to disable Chip backgrounds & surfaces to avoid overdraw problem?

### ISSUE THREAD

**Issue by egogg** [material-components/material-components-android#286]
Developer tool shows that an Action Chip overdraw at least 3x, is there a way to improve this situation? Thanks a lot!

**Comment by afohrman** [comment]
Thanks for bringing this to our attention. This is something that we should be able to fix on our end. I've filed an issue in our Issue Tracker; you can follow https://issuetracker.google.com/124911626 for updates.
