### ISSUE TITLE
[MaterialTimePicker] Control Field Focus on Open

### ISSUE THREAD

**Issue by jbh6gc** [material-components/material-components-android#2862]
**Is your feature request related to a problem? Please describe.**
My app opens the MaterialTimePicker dialog into text input mode. When this happens the hour field is focused. Since the hour field is focused the user can't see the current value of that field. It is a little confusing for the user not to have the context of what the current value is. 

**Describe the solution you'd like**
The behavior of this scenario in the 1.6.1 version of the component is that the hour field is not focused when the dialog is first opened. This worked well for us. It looks like 72abed042f7577a6e24219742d0a5ac860adcb56 which was added in 1.7.0-alpha02 changed this behavior so that it focuses on open. It seems from #1511 that the intent was to focus the field when switching from clock mode to text mode so I was thinking it might make sense to only focus a field if it has been focused by the user already in any mode, but if opening directly in text input mode it would not focus anything right away. 

**Describe alternatives you've considered**
I tried to just stick with version 1.6.1 for my app which has the desired behavior, but #2788 is big enough that we needed to upgrade to 1.7.0 to get the fix for it. I did not see any attributes or settings on the builder or picker itself that would flex this behavior for us either. 

**Additional context**
Here's a screenshot of what the Time Picker looks like when we first open it in text input mode:
![Screenshot_20220726-100208](https://user-images.githubusercontent.com/6208356/181041437-4d9518f3-11d4-464f-b65b-e34061b6d74f.png)

**Comment by drchen** [comment]
Let's probably add and option to opt in/out this behavior?

**Comment by jbh6gc** [comment]
Yeah, being able to opt in/out would definitely work for us. Thanks for the quick response!

**Comment by Shusek** [comment]
I get invalid reports from users that while they edit time the hour is always erasing (this is not true but for user it is not transparent). Will this optional flag be introduced or i should explain to users that this is normal behavior?

**Comment by paulfthomas** [comment]
Hi, we reviewed this issue with our designers and made a change, now the hour/minute edit texts are pre-filled and the text gets automatically replaced once the user starts typing (so no extra interaction required). See https://github.com/material-components/material-components-android/commit/56ea071320719b438ba2e0d40ab74e38dc474b07.

<img src="https://user-images.githubusercontent.com/8482544/194089690-c96eeeee-07fa-40f3-b0ba-bede30e076ce.png" width="300">
