### ISSUE TITLE
[Theme] Make `colorControlHighlight` use Material3 state layers

### ISSUE THREAD

**Issue by OxygenCobalt** [material-components/material-components-android#2866]
**Is your feature request related to a problem? Please describe.**
Despite their legacy nature, many components (like the Toolbar) rely on `?attr/colorControlHighlight` and it's derivatives like `?attr/selectableItemBackground` However, since `colorControlHighlight` is not overridden in the Material3 theme, they continue to use the old material state layers, and thus don't match up with other components.

**Describe the solution you'd like**
For the Material3 theme to override `colorControlHighlight` with a new color selector that uses the new Material3 opacity and color values.

**Describe alternatives you've considered**
I implemented my own version of this already by doing this:

`values-v23/themes.xml`
```xml
<style name="Theme.MyApp" ...>
    <item name="colorControlHighlight">@color/sel_compat_ripple</item>
</style>
```

`color/sel_compat_ripple.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:alpha="@dimen/m3_ripple_selectable_pressed_alpha"
      android:color="?attr/colorOnSurfaceVariant"
      android:state_pressed="true"/>
  <item android:alpha="@dimen/m3_ripple_focused_alpha"
      android:color="?attr/colorOnSurfaceVariant"
      android:state_focused="true"/>
  <item android:alpha="@dimen/m3_ripple_hovered_alpha"
      android:color="?attr/colorOnSurfaceVariant"
      android:state_hovered="true"/>
  <item android:alpha="@dimen/m3_ripple_default_alpha"
      android:color="?attr/colorOnSurfaceVariant"/>
</selector>
```

Note that this is scoped to API 23 and above, as API 21 and below doesn't support overriding `colorControlHighlight` like this.

**Comment by drchen** [comment]
Hi thanks for the report. Our guideline is doing remapping component by component when there's a need, instead of a global overriding. Can you file separate bugs if you see incorrect ripple colors with Material components? I'll close this issue as a no-go.
