### ISSUE TITLE
Unable to save settings: Failed to save settings. Please restart Android Studio

### ISSUE THREAD

**Issue by Morons** [material-components/material-components-android#2867]
I do get this on 2 versions of Android Studio, **BUT** in no other project
### Error
`Unable to save settings: Failed to save settings. Please restart Android Studio`
## Reproduction
I have checked if indeed it is Android Studio by opening many other apps and never seen this in them.
to produce I just have to open the project, it even crashes 1/2 way and I need to re-open it

It will also happen when I do explicitly open settings and close it etc..

## Versions tested
```kotlin
Android Studio Dolphin | 2021.3.1 Beta 5
Build #AI-213.7172.25.2113.8774922, built on June 28, 2022
Runtime version: 11.0.14.1+1-b1751.46 amd64
```
and
```kotlin
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+7-b1504.27 amd64
```

**Comment by drchen** [comment]
You should report the bug to Android Studio, I'm not sure what we can help you here. : )
