### ISSUE TITLE
Outline Box not working in Version 1.1.0-alpha03

### ISSUE THREAD

**Issue by KJGohel** [material-components/material-components-android#287]
I am creating TextInputLayout programmatically. Below code working in 
 implementation 'com.google.android.material:material:1.1.0-alpha02'

But not working in 
 implementation 'com.google.android.material:material:1.1.0-alpha03'
outline box not showing.

`<style name="MaterialTheme" parent="Base.Theme.MaterialComponents.Light.DarkActionBar">`
        `<item name="colorPrimary">@color/colorPrimary</item>`
        `<item name="colorPrimaryDark">@color/colorPrimaryDark</item>`
        `<item name="colorAccent">@color/colorAccent</item>`
        `<item name="TextLayoutStyle">@style/MaterialTheme.TextLayout</item>`
        `<item name="textAppearanceSubtitle1">@style/MaterialTheme.ActionBar.SubTitleTextStyle</item>`
    `</style>`
 `<style name="MaterialTheme.TextLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">`
        `<item name="android:paddingStart">@dimen/size_4dp</item>`
        `<item name="boxStrokeColor">@color/colorAccent</item>`
        `<item name="hintTextColor">@color/colorAccent</item>`
        `<item name="materialThemeOverlay">
            @style/ThemeOverlay.MaterialComponents.TextInputEditText.OutlinedBox
        </item>`
    `</style>`

public class FormInputField extends TextInputLayout {
         
        public FormInputField(Context context) {
		super(context, null, R.attr.TextLayoutStyle);
		init();
	}
}

**Comment by afohrman** [comment]
What error are you encountering? Can you attach screenshots and/or a stacktrace?

I'm not sure what the custom `TextLayout` theme attribute does, but why not use `textInputStyle`? Also, why does `MaterialTheme.TextLayout` set `materialThemeOverlay` to the same value that the parent sets it to?

Please file an issue on our [issue tracker](https://issuetracker.google.com/issues/new?component=439535) with the requested information.

**Comment by KJGohel** [comment]
can you help me to create outline box textinputlayout programatically.

**Comment by KJGohel** [comment]
textInputStyle not working with alpha03 version
