### ISSUE TITLE
[MaterialTimePicker] New input mode defaults for `TimeFormat.CLOCK_24H`

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#2877]
Along with the new old 24h clock, [the commit](https://github.com/material-components/material-components-android/commit/cbc0711ca34bf42af1ac3e6bb2e0587195b63b86) also introduced a change to the default behavior:
https://github.com/material-components/material-components-android/blob/686bf5cb5e300493c347d269466abcca93483402/docs/components/TimePicker.md?plain=1#L62-L63

Could you please indicate a reason for this change? Was it worth breaking behavioral compatibility because of it?

**Comment by paulfthomas** [comment]
Hi @pubiqq, our user research indicated a preference for text input mode with the 24H format.

You can still open the 24H picker in clock mode by using:
```
MaterialTimePicker.Builder()
    .setTimeFormat(CLOCK_24H)
    .setInputMode(INPUT_MODE_CLOCK)
    ...
```
