### ISSUE TITLE
MaterialAlertDialogBuilder not Found

### ISSUE THREAD

**Issue by jjimenez0611** [material-components/material-components-android#288]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

Hi 
I was added the library to my project  implementation 'com.google.android.material:material:1.0.0'
I use kotlin, and I try to call  MaterialAlertDialogBuilder(context)
                                .setTitle("Title")
                                .setMessage("Message")
                                .setPositiveButton("Ok", null)
                                .show()

But the MaterialAlertDialogBuilder is never imported.....

**Comment by ymarian** [comment]
MaterialAlertDialog was introduced in 
https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha02
as you can see in https://github.com/material-components/material-components-android/releases

**Comment by markymark1988** [comment]
For anyone that's having problems importing this in `1.1.0-alpha02` or later the import is 
`import com.google.android.material.dialog.MaterialAlertDialogBuilder`

Current dependency 
`implementation "com.google.android.material:material:1.1.0-alpha08"`
