### ISSUE TITLE
Bug not Compile library

### ISSUE THREAD

**Issue by Arashvscode** [material-components/material-components-android#2882]
![Screenshot_20220802-171001_Sketchware Pro](https://user-images.githubusercontent.com/101287880/182377258-73db799f-4f77-45b0-a4bf-c369af167c38.jpg)
![Screenshot_20220802-170959_Sketchware Pro](https://user-images.githubusercontent.com/101287880/182377276-7d03cbe5-98e7-4033-9f74-4ee23e1b4491.jpg)
![Screenshot_20220802-170955_Sketchware Pro](https://user-images.githubusercontent.com/101287880/182377283-9cde29e9-b954-4cf3-8e07-4bdbc4588031.jpg)

Not found macro

**Comment by pekingme** [comment]
duplicate with #2722 and #2838
