### ISSUE TITLE
Transparency in com.google.android.material.textfield.TextInputLayout

### ISSUE THREAD

**Issue by jjimenez0611** [material-components/material-components-android#289]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

I try to apply Transparent background to TextInputLayout but looks like it does not works. 
And is really important for the project apply transparent color to the TextInput...

**Comment by afohrman** [comment]
Thanks for reporting this. We'll need more information before we're able to address this. What version text field are you trying to use with a transparent background? What version of the library are you using? Do you have any mocks of the desired text field look?

Please file an issue in our [issue tracker](https://issuetracker.google.com/issues/new?component=439535) with as much information as you have so that we can take a deeper look.

**Comment by jjimenez0611** [comment]
Hi 

I tried different ways, and the only way it worked was added the line:
app:boxBackgroundMode="outline"
 or
app:boxBackgroundMode="none"

**Library version:** 
 implementation 'com.google.android.material:material:1.1.0-alpha03'

**TextInputLayout:**

    <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/text_input_layout_name"
            android:layout_width="0dp"
            style="@style/Widget.TSA.OutlinedTextLayout"
            android:theme="@style/Widget.TSA.OutlinedTextLayout"
            **app:boxBackgroundMode="outline"**
            app:layout_constraintTop_toBottomOf="@+id/imageView_logo"
            app:layout_constraintBottom_toTopOf="@+id/text_input_layout_password"
            app:layout_constraintVertical_chainStyle="packed"
            app:layout_constraintEnd_toEndOf="@+id/guidelineEnd"
            app:layout_constraintStart_toStartOf="@+id/guidelineStart"
            android:layout_height="@dimen/textLayout_height">

        <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/text_input_name"
                style="@style/EditText.Login"
                android:theme="@style/EditText.Login"
                android:layout_width="match_parent"
                android:layout_height="@dimen/textLayout_height"
                android:hint="@string/username"
                android:inputType="textPersonName"
                android:maxLines="1"
                android:singleLine="true"
                android:paddingStart="10dp"
                android:paddingEnd="10dp"
                android:textStyle="bold"/>

    </com.google.android.material.textfield.TextInputLayout>


**Style:**
    <style name="Widget.TSA.OutlinedTextLayout" parent="Widget.MaterialComponents.TextInputLayout.FilledBox">
        <item name="boxBackgroundColor">@android:color/transparent</item>
        <item name="errorTextAppearance">@style/ErrorTextAppearance</item>>
        <item name="android:textColorHint">@android:color/white</item>
    </style>

**Comment by j-ns** [comment]
I was able to make the background transparent, by adding the corresponding background to the `TextInputEditText`:

```
<com.google.android.material.textfield.TextInputLayout
         ...            
         style="@style/Widget.TSA.OutlinedTextLayout"

            <com.google.android.material.textfield.TextInputEditText
                ....
                android:background="@android:color/transparent" />
            
</com.google.android.material.textfield.TextInputLayout>
```

**Comment by jjimenez0611** [comment]
Hi @j-ns 
Thanks, yes I could do it.. The problem was the version of the library, I used a alpha version and that version still has a lot of bug. So I downgrade to the 1.0.0, this is the stable version, and I don't think that I update until have a stable version on 1.1.0
