### ISSUE TITLE
ExperimentalBadgeUtils cannot be opt-in

### ISSUE THREAD

**Issue by kokeroulis** [material-components/material-components-android#2892]
`ExperimentalBadgeUtils` is broken and it cannot be `opt-in`.

code to reproduce 

```kotlin
import androidx.annotation.IdRes
import androidx.appcompat.widget.Toolbar
import com.google.android.material.badge.BadgeDrawable
import com.google.android.material.badge.BadgeUtils
import com.google.android.material.badge.ExperimentalBadgeUtils

@OptIn(ExperimentalBadgeUtils::class)
class Foo {

    fun bar(toolbar: Toolbar, @IdRes menuItemId: Int) {
        val drawable = BadgeDrawable.create(toolbar.context)
        BadgeUtils.attachBadgeDrawable(drawable, toolbar, menuItemId)
    }
}
```

<img width="1158" alt="Screenshot 2022-08-03 at 17 28 15" src="https://user-images.githubusercontent.com/470064/182661199-a2b1c7d2-8b87-443e-8e2b-5273167bdab1.png">
<img width="1292" alt="Screenshot 2022-08-03 at 17 28 07" src="https://user-images.githubusercontent.com/470064/182661207-3389923a-a52d-48c9-ad60-d5971a6fa11d.png">

**Comment by drchen** [comment]
I think you should us @ExperimentalBadgeUtils instead?
