### ISSUE TITLE
[NavigationBar] button color on light navigation bar refusing to have darker tint

### ISSUE THREAD

**Issue by fre-berhane** [material-components/material-components-android#2896]
**Description:** Full description of issue here
The navigation bar for API 31 on Pixel 5 doesn't pick up the contrast rules set in style.xml

**Expected behavior:** Screenshots and/or description of expected behavior
The expected behavior should be white background and darker buttons 
**Source code:** 
```
<item name="android:navigationBarColor">@android:color/white</item>
 <item name="android:windowLightNavigationBar">true</item>
```
**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** Android API version here
API 31
**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

**Device:** 
Pixel 5

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Can you provide a screenshot and your full theme/style file? Like where do you set `android:navigationBarColor` and `android:windowLightNavigationBar`?

**Comment by fre-berhane** [comment]
```
![navigation](https://user-images.githubusercontent.com/5528736/183451009-df8bef54-83af-40cd-928d-3a57d8ca3eee.PNG)
```

**Comment by fre-berhane** [comment]
<style name="custom_theme" parent="Theme.AppCompat.Light.NoActionBar">
<item name="android:navigationBarColor" >@color/white</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowLightNavigationBar">true</item>
</style>

**Comment by drchen** [comment]
The system navigation bar is not relevant to the Material library (especially when you are not using Material themes). I'm afraid that we can provide little help here. I'll close the issue as irrelevant.
