### ISSUE TITLE
[CollapsingToolbarLayout] Elevation bug when using SwipeRefreshLayout and titleCollapseMode="scale"

### ISSUE THREAD

**Issue by ViHtarb** [material-components/material-components-android#2900]
**Description:** Look on Toolbar in attached video

**Expected behavior:** 
https://user-images.githubusercontent.com/8938207/183736724-a2ea57f4-79f1-4ca7-bc0f-94d9fed8502b.mp4

**Source code:** Based on code from Catalog demo app -> cat_topappbar_collapsing_medium_fragment.xml
Was added app:titleCollapseMode="scale" attribute to CollapsingToolbarLayout and SwipeRefreshLayout
```xml

<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/coordinator"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

  <com.google.android.material.appbar.AppBarLayout
      android:id="@+id/appbarlayout"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:fitsSystemWindows="true">

    <com.google.android.material.appbar.CollapsingToolbarLayout
        style="?attr/collapsingToolbarLayoutMediumStyle"
        android:id="@+id/collapsingtoolbarlayout"
        android:layout_width="match_parent"
        android:layout_height="?attr/collapsingToolbarLayoutMediumSize"
        app:titleCollapseMode="scale"
        app:layout_scrollFlags="scroll|exitUntilCollapsed|snap">

      <androidx.appcompat.widget.Toolbar
          android:id="@+id/toolbar"
          style="?attr/catalogToolbarWithCloseButtonStyle"
          android:layout_width="match_parent"
          android:layout_height="?attr/actionBarSize"
          android:elevation="0dp"
          app:layout_collapseMode="pin"
          app:title="@string/cat_topappbar_collapsing_demo_toolbar_title"/>
    </com.google.android.material.appbar.CollapsingToolbarLayout>
  </com.google.android.material.appbar.AppBarLayout>

  <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
    android:id="@+id/swipe"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <androidx.core.widget.NestedScrollView
      android:id="@+id/list"
      android:layout_width="match_parent"
      android:layout_height="wrap_content">

      <include layout="@layout/cat_topappbar_filler_text_view"/>
    </androidx.core.widget.NestedScrollView>
  </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>
</androidx.coordinatorlayout.widget.CoordinatorLayout>

```
**Minimal sample app repro:** It can be reproduced in Catalog demo app with little changes in cat_topappbar_collapsing_medium_fragment.xml
**Android API version:** 32 and below

**Material Library version:** latest from repo(on issue created date)

**PS:** It can be fixed with `app:liftOnScrollTargetViewId="@id/list"` attribute but anyway its a bug

**Comment by dsn5ft** [comment]
Hi @ViHtarb, this is a known limitation of AppBarLayout/CollapsingToolbarLayout + SwipeRefreshLayout, due to the way SwipeRefreshLayout intercepts nested scrolling events.

Setting `app:liftOnScrollTargetViewId` when using a AppBarLayout/CollapsingToolbarLayout + SwipeRefreshLayout combo is a requirement, in order for the AppBarLayout to be able to find the correct scrolling view:

https://github.com/material-components/material-components-android/blob/master/docs/components/TopAppBar.md#applying-scrolling-behavior-to-the-top-app-bar
