### ISSUE TITLE
Cannot access CalendarConstraints' properties like getStart, getEnd, etc.

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2907]
In latest MDC version getting properties like `getStart` or `getEnd` seems no longer available. You can only get the date validator.

Using `1.7.0-alpha03`

```
 val x = CalendarConstraints.Builder()
            .setStart(oldestDate)
            .setEnd(minDate)
            .setOpenAt(minDate)
            .setValidator(DateValidatorPointBackward.before(minDate)) // Disable future days
            .build()
        
            x.dateValidator
```

**Comment by ArcherEmiya05** [comment]
> I don't think they are ever available.
> 
> Can you elaborate why you want to access them?

We are using Dagger 2 for Dependency Injection and we are using `CalendarConstraints` with `MaterialDatePicker`.

```
datePickerBirthdate = showMaterialDatePicker(constraints, setSelection = constraints.getEnd()).apply {
                addOnPositiveButtonClickListener { time ->

                  // Do your work here

                }
            }
```
            
It seems accessible within the MDC component, and I think its not bad to expose them.
https://programtalk.com/vs3/?source=java/material-components/material-components-android/lib/java/com/google/android/material/datepicker/MonthsPagerAdapter.java

**Comment by ArcherEmiya05** [comment]
> > I don't think they are ever available.
> > Can you elaborate why you want to access them?
> 
> We are using Dagger 2 for Dependency Injection and we are using `CalendarConstraints` with `MaterialDatePicker`.
> 
> ```
> datePickerBirthdate = showMaterialDatePicker(constraints, setSelection = constraints.getEnd()).apply {
>                 addOnPositiveButtonClickListener { time ->
> 
>                   // Do your work here
> 
>                 }
>             }
> ```
> 
> It seems accessible within the MDC component and I think its not bad to expose them. https://programtalk.com/vs3/?source=java/material-components/material-components-android/lib/java/com/google/android/material/datepicker/MonthsPagerAdapter.java

Since `minDate` from the sample `CalendarConstraints` was used in `setEnd()` and `setOpen()`, we should be able to access them using getter so we no longer need to provide the `mindDate` again in the UI part.

**Comment by drchen** [comment]
Makes sense to me. : )

**Comment by ArcherEmiya05** [comment]
Can we expect this in the next release? Thanks!

**Comment by drchen** [comment]
I will probably be included in 1.8 alpha releases. (1.7 is going to RC so there shouldn't be new API changes)

**Comment by ArcherEmiya05** [comment]
@drchen maybe we can also expose `openAt`?

**Comment by ArcherEmiya05** [comment]
I was wrong, there should be a `getStart`, `getEnd`, and `getOpenAt` from the builder itself and not the `CalendarConstraints`

**Comment by ArcherEmiya05** [comment]
Thanks a lot, is this expected to be included on next release?

**Comment by imhappi** [comment]
it should be included in the next alpha release

**Comment by ArcherEmiya05** [comment]
> it should be included in the next alpha release

Thanks a lot, just curious is there a concrete schedule of release in MDC? Like every first week of the month?

**Comment by imhappi** [comment]
The release schedule is based around a factor of various things, such as design reviews and timelines around events; the next alpha release is slated to be a few days before ADS

**Comment by ArcherEmiya05** [comment]
> The release schedule is based around a factor of various things, such as design reviews and timelines around events; the next alpha release is slated to be a few days before ADS

Just curious, what does ADS means?

**Comment by drchen** [comment]
Android Dev Summit: https://developer.android.com/events/dev-summit

Not sure where is this year's announcement though....
