### ISSUE TITLE
[TabLayout] Extra padding in custom tabs

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#2909]
**How to reproduce:**
Set `custom_tab.xml` as a view for tabs.
<details>
  <summary>custom_tab.xml</summary>
  
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  android:orientation="vertical">

  <ImageView
    android:id="@android:id/icon"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"/>

  <TextView
    android:id="@android:id/text1"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content" />

</LinearLayout>
  ```
</details>

**Result:**
<img src="https://user-images.githubusercontent.com/82187521/184855439-c6feec9e-6f8e-4cdc-8410-01b4c33176c9.png" />

**Expected behavior:**
No padding between the icon and the text.

**Actual behavior:**
Extra padding between the icon and the text.

**Material Library version:** 1.7.0-beta01

**Comment by imhappi** [comment]
Resolved in https://github.com/material-components/material-components-android/commit/d68c0f8dc598fc7449d001c53b9972d22fc85fe7
