### ISSUE TITLE
Missing release notes 1.1.0-alpha04

### ISSUE THREAD

**Issue by mtrakal** [material-components/material-components-android#291]
https://github.com/material-components/material-components-android/releases

no release notes for: 1.1.0-alpha04

**Comment by MGaetan89** [comment]
You can check https://github.com/material-components/material-components-android/compare/1.1.0-alpha03...master until they are released.

**Comment by dsn5ft** [comment]
We will be adding release notes for `1.1.0-alpha04` today.
