### ISSUE TITLE
[MaterialSwitch] SwitchPreference is still showing the old switch. Can we change that too?

### ISSUE THREAD

**Issue by ytheekshana** [material-components/material-components-android#2912]
Hi. I am using the mdc latest 1.7.0-beta01 release and appcompat 1.6.0-beta01
But still I am seeing the old switch styles on my Settings Fragment. Do the preference library guys need to update that or can I know a way to get the new style on preferences.

**Comment by drchen** [comment]
It's a duplicate to https://github.com/material-components/material-components-android/issues/2828

Please refer to the solution and the issue status there. : )
