### ISSUE TITLE
Cannot change the default font in Material 3

### ISSUE THREAD

**Issue by droid112** [material-components/material-components-android#2913]
In Material 2, the default font can be changed by overriding the `defaultFontFamily` property

Material 2 Compose

```
val Typography2 = Typography(
    defaultFontFamily = MyFont
)
```

But after upgrading to Material 3 it is not possible because there is no `defaultFontFamily` property

Are there certain reasons ?

**Comment by drchen** [comment]
Hi it seems like a Compose question. Please report an issue [here](https://issuetracker.google.com/issues?q=status:open%20componentid:742043&pli=1) instead. : )
