### ISSUE TITLE
[Snackbar] Round corners

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#2914]
**Is your feature request related to a problem? 
No.

**Describe the solution you'd like**
In the [M3 catalog example](https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog), Snackbars have rounded corners similar to the ones of M3 buttons:
<img src="https://user-images.githubusercontent.com/7906165/185086278-6b9fac25-5cb0-4508-ad24-0aac9120120a.png" width="60%"> 

In [my sample app](https://github.com/patrickfrei/test_coding/blob/main/MyApplication.zip), I'm also using M3 Snackbars, but they look like the ones in [your documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/Snackbar.md), i.e. with almost square corners:
<img src="https://user-images.githubusercontent.com/7906165/185086938-3de21b35-5487-4072-8ea7-7992ee35ecef.png" width="60%"> 

I was looking into the M3 catalog example styles & themes but couldn't find a hint on how make the Snackbar corners being round. 

Could you please shed some light into the changes that you have made to achieve that design? Many thanks!

**Comment by drchen** [comment]
You can extend `@style/Widget.Material3.Snackbar` and override `?attr/shapeAppearance` with `@style/ShapeAppearance.Material3.Corner.Full`. : )

**Comment by patrickfrei** [comment]
@drchen, thank you very much!
