### ISSUE TITLE
[AppBarLayout] match status bar color - liftOnScroll

### ISSUE THREAD

**Issue by postfixNotation** [material-components/material-components-android#2919]
**Is your feature request related to a problem? Please describe.**
As seen in the screenshot below, the appbar does not match the status bar color in the liftOnScroll case.

**Describe the solution you'd like**
The statusBarColor matches the appBarLayout color and gets concurrently updated while liftOnScroll. I could achieve this with the hack below. This behavior could be specified by an XML flag to also match both colors initially.

```kotlin
findViewById<AppBarLayout>(R.id.appbar).addLiftOnScrollListener { _, backgroundColor ->
   (context as Activity).window.statusBarColor = backgroundColor
}
```

**Additional context**
![appbarlayout](https://user-images.githubusercontent.com/33238163/185459138-dbf67064-9f4b-45a2-b16d-2a6c8ef42901.jpg)

**Comment by imhappi** [comment]
Hi! I think the best way to achieve this would be to go edge-to-edge so that the status bar is transparent and the Top App Bar color fill shows underneath it:

https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e

**Comment by postfixNotation** [comment]
Thanks for the article. I followed the advices but unfortunately it didn't solve the problem.

![appbarlayout_edge_to_edge](https://user-images.githubusercontent.com/33238163/186884210-b99227fa-449f-4f30-bf01-e1a3db155879.jpg)

**Comment by imhappi** [comment]
What do you mean it doesn't solve the issue?

It looks like the status bar is the same colour, just overlapping with the view, which you must take care of if you go edge-to-edge

https://developer.android.com/develop/ui/views/layout/edge-to-edge (see step 3 in particular)

**Comment by postfixNotation** [comment]
> What do you mean it doesn't solve the issue?
> 
> It looks like the status bar is the same colour, just overlapping with the view, which you must take care of if you go edge-to-edge
> 
> https://developer.android.com/develop/ui/views/layout/edge-to-edge (see step 3 in particular)

Thanks again for helping me out!
I adjusted the appBarLayout to have a lift on scroll behavior with `app:liftOnScroll="true"` and `app:layout_behavior="@string/appbar_scrolling_view_behavior"`. In light theme this is no problem since there's simply a shadow drawn below the layout where the content scrolls. In darkmode however the elevation is emulated by changing the appBarLayout color, I guess, by changing the opacity. And this dynamic behavior isn't synced with the statusBarColor.

I might get the articles wrong, I probably did, but I tried the code shown there and I can't achieve the desired outcome. The following code snippets show what yields the behavior according to my expectations.

```xml
<resources>
    <declare-styleable name="AppBarLayout">
        <attr name="adjustStatusBarColorOnLift" format="boolean" />
    </declare-styleable>
</resources>
```
```kotlin
package com.some.package

import android.app.Activity
import android.content.Context
import android.util.AttributeSet
import com.shapeganic.R

class AppBarLayout : com.google.android.material.appbar.AppBarLayout {
    constructor(context: Context, attrs: AttributeSet, defStyleAttr: Int) : super(
        context,
        attrs,
        defStyleAttr
    ) {
        adjustStatusBarColor(context, attrs)
    }

    constructor(context: Context, attrs: AttributeSet) : super(context, attrs) {
        adjustStatusBarColor(context, attrs)
    }

    constructor(context: Context) : super(context)

    private fun adjustStatusBarColor(context: Context, attrs: AttributeSet) {
        val window = try {
            (context as Activity).window
        } catch (e: ClassCastException) {
            return
        }

        val styledAttributes = context.theme.obtainStyledAttributes(
            attrs, R.styleable.AppBarLayout, 0, 0
        )

        try {
            val adjustStatusBarColor =
                styledAttributes.getBoolean(
                    R.styleable.AppBarLayout_adjustStatusBarColorOnLift, false
                )
            if (adjustStatusBarColor) {
                addLiftOnScrollListener { _, backgroundColor ->
                    window.statusBarColor = backgroundColor
                }
            }
        } finally {
            styledAttributes.recycle()
        }
    }
}
```
```xml
<com.some.package.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:adjustStatusBarColorOnLift="true"
        app:liftOnScroll="true">

        ...
    </com.some.package.AppBarLayout>
```

And this is the result which could be better visualized with a gif but I hope this is somehow unambiguous:

![appbarlayout_statusbar_color_adjustment](https://user-images.githubusercontent.com/33238163/187033680-b5261227-dd5b-4bb7-84e4-25a3f88a666e.jpg)

**Comment by imhappi** [comment]
Unfortunately, I don't think changing the top app bar colour to the status bar colour manually is something we want to do since it will likely result in many edge cases; what would happen if the app theme changed? Or someone is using dynamic colours and changes their wallpaper?

The edge-to-edge solution is the solution that we encourage

**Comment by postfixNotation** [comment]
> Unfortunately, I don't think changing the top app bar colour to the status bar colour manually is something we want to do since it will likely result in many edge cases; what would happen if the app theme changed? Or someone is using dynamic colours and changes their wallpaper?
> 
> The edge-to-edge solution is the solution that we encourage

Sounds absolutely reasonable to me! Thx!
Btw is there a good resource that describes how to change the app's theme at runtime?

**Comment by vimalcvs** [comment]
use this in appbar

`app:liftOnScroll="false"`
