### ISSUE TITLE
Android JetPack (Android X)

### ISSUE THREAD

**Issue by tprochazka** [material-components/material-components-android#292]
I'm curious why it is not part of Jetpack (Android X).
According to the description, it is a replacement for legacy `com.android.support:design`.
What is the reason?

**Comment by dsn5ft** [comment]
Since Material is a cross-platform design system by Google, we felt that the `com.google.android.material` namespace was more appropriate. We still work closely with the androidx library teams to develop APIs, coordinate releases, etc.
