### ISSUE TITLE
[BottomNavigationView] navigationBarColor should match BottomNavigationView's container color

### ISSUE THREAD

**Issue by postfixNotation** [material-components/material-components-android#2920]
**Is your feature request related to a problem? Please describe.**
I recently replaced my OnePlus 3T with an 8T which is why there's some space and a handle below the BottomNavigationView. Especially in dark theme these both colors don't match. The display is rounded around the corners.

**Describe the solution you'd like**
I expect the library to set navigationBarColor to be the same value as BottomNavigationView's container color which isn't straight forward since there's an elevation with respect to BottomNavigationView, so simply setting navigationBarColor doesn't solve the issue client side.

**Additional context**
![bottomnavigationview](https://user-images.githubusercontent.com/33238163/185460803-dcb06f01-6647-47e1-99d2-459ecf7a559b.jpg)

**Comment by imhappi** [comment]
Hi! This is really difficult for us to test since it looks like you need a OnePlus device? I'm unable to repro this on my devices, but in any case, I expect this to be similar to #2919 in that we recommend edge-to-edge solution and don't want to be manually changing the navigation bar color

**Comment by vimalcvs** [comment]
Code in Kotlin
```
DynamicColors.applyIfAvailable(this) // After this
window.navigationBarColor = SurfaceColors.SURFACE_2.getColor(this)
```

Code in Java
```
getWindow().setNavigationBarColor(SurfaceColors.SURFACE_2.getColor(this));

```
