### ISSUE TITLE
BottomSheetBehavior speed animation on state

### ISSUE THREAD

**Issue by SudoDios** [material-components/material-components-android#2925]
Hi.
How to set speed animation for bottomsheetbehavior on state hiden and expand or collapse??

**Comment by imhappi** [comment]
I believe that you can set the `android:windowEnterAnimation` or `android:windowExitAnimation` attributes to override with a custom animation for the bottom sheet expand/collapse

See here for details on how to set these attributes in a theme/style: https://material.io/develop/android/components/bottom-sheet-dialog-fragment
