### ISSUE TITLE
MaterialAlertDialog style cut corners with backgroundcolor in title breaks corners

### ISSUE THREAD

**Issue by nbelley** [material-components/material-components-android#2935]
When styling a MaterialAlertDialog, theming for cut corners is working. But if I style the title and add a background color to the title, the cut corner around the title disappears. 

Working code without the problem: 

	<style name="CustomTheme.AlertDialogTheme"
		   parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
		<item name="shapeAppearanceMediumComponent">@style/CutShapeAppearance</item>
		<item name="shapeAppearanceOverlay">@style/CutShapeAppearance</item>
		<item name="materialAlertDialogTitlePanelStyle">@style/CustomTheme.Title.Panel.Center</item>
		<item name="materialAlertDialogTitleTextStyle">@style/CustomTheme.MaterialAlertDialog.App.Title.Text</item>
		<item name="materialAlertDialogBodyTextStyle">@style/CustomTheme.Message.Center</item>
		<item name="colorPrimary">@color/HotPink</item>
		<item name="colorSecondary">@color/BlueViolet</item>
		<item name="colorSurface">#f0fbff</item>
		<item name="colorOnSurface">@color/OrangeRed</item>
		<item name="materialAlertDialogButtonSpacerVisibility">2</item>
		<item name="buttonBarPositiveButtonStyle">@style/Button.FullWidth</item>
		<item name="buttonBarNegativeButtonStyle">@style/Button.FullWidth</item>
		<item name="buttonBarNeutralButtonStyle">@style/Button.FullWidth</item>
	</style>	

	<style name="Button.FullWidth"
		   parent="Widget.MaterialComponents.Button.TextButton.Dialog">
		<item name="android:layout_width">0dp</item>
		<item name="android:layout_weight">1</item>
		<item name="android:maxWidth">@null</item>
	</style>

	<style name="CustomTheme.Title.Panel.Center"
		   parent="MaterialAlertDialog.MaterialComponents.Title.Panel">
		<item name="android:gravity">center_horizontal</item>
                
		
	</style>

	<style name="CustomTheme.Message.Center"
		   parent="MaterialAlertDialog.MaterialComponents.Body.Text">
		<item name="android:gravity">center_horizontal</item>
	</style>
	
	<style name="CutShapeAppearance"
		   parent="ShapeAppearance.MaterialComponents.MediumComponent">
		<item name="cornerFamily">cut</item>
		<item name="cornerSize">10dp</item>
	</style>

	<style name="CustomTheme.MaterialAlertDialog.App.Title.Text"
		   parent="MaterialAlertDialog.MaterialComponents.Title.Text">
		<item name="android:textColor">@color/HoloOrangeLight</item>
	</style>

Screenshot of working alert dialog cut corners:
![workingcutcorners](https://user-images.githubusercontent.com/4919080/186733282-84cdd9f2-77ac-4725-9201-f55888c8daf1.jpg)

Now uncommenting the <item name="android:background">@color/LightBlack</item> line:
![notworkingcutcorners](https://user-images.githubusercontent.com/4919080/186733699-8c84eac3-caf9-40aa-b108-bf3fa86d1304.jpg)

Am I not styling correctly or it's really a bug? Or a limitation and an impossibility?

**Comment by imhappi** [comment]
Hi! This is unfortunately intentional, as the background is a drawable and will override the corner drawable; you could try setting the background tint to change the colour
