### ISSUE TITLE
[LinearProgressIndicator] Adding track radius causes incorrect progress in the start of the indicator

### ISSUE THREAD

**Issue by OxygenCobalt** [material-components/material-components-android#2940]
**Description:**

Say I set a `LinearProgressIndicator` to have the following traits:

```
progressIndicator.progress = positionInMs / 100 // Deci-seconds
progressIndicator.max = durationInMs / 100
```

This results in a very fine position for the progress indicator.

When there is no track radius set, very low progress amounts (say, `10`) look fine:

![image](https://user-images.githubusercontent.com/65370175/187244493-ae3d17b4-8e35-4667-826d-cd0d74b46246.png)

When there is a track radius however, the shown progress is much larger than it should be, presumably to accommodate the track radius (In this example, the track radius is 16dp):

![image](https://user-images.githubusercontent.com/65370175/187244448-9bcc5a1b-96f5-4eab-8d8c-3b32672f47af.png)

**Expected behavior:** 

The progress when there is a track radius should be the same as the progress when there is no track radius. If the progress extent cannot contain the whole track radius, just clip the drawn progress a bit so that it does correctly fit.

I've attached a picture below of what I want:

![image](https://user-images.githubusercontent.com/65370175/187245897-8714a756-2732-4e31-b629-f12d21e9fd65.png)

**Source code:** See above.

**Android API version:** 33

**Material Library version:** 1.7.0-beta01

**Device:** OnePlus 7T running LineageOS

**Comment by pekingme** [comment]
In the current implementation, the rounded corners are draw as "decoration". The "real" progress is the rectangle between the left corners and the right corners. The clipping way was also considered. But it becomes tricky for circular progress indicator, since there are no "ends" on the track. 

What's your use case? Why do you need the progress look comparatively in the same length between indicators with and without rounded corners?

**Comment by OxygenCobalt** [comment]
I just think it looks nicer @pekingme. Since my progress indicator progresses with the playback of audio, it looks strange to have that initial "jump" from 0 to the corner radius, and then have the typical small increments afterwards.

If this is not possible, could it at least be possible to round the track background, but not round the track progress? Sort of like what occurs in the the media notification.

**Comment by pubiqq** [comment]
Coincidentally, I wanted to create the same issue 😄:

https://user-images.githubusercontent.com/82187521/187311869-c30ffbf3-4335-4e2a-a159-0dea4f21c12c.mp4

**Comment by OxygenCobalt** [comment]
Theoretically, couldn't you add a parameter to the base progress class that determines whether to clip like this? That way, the circular indicator can still work properly, while the linear indicator can progress smoother. @pekingme @pubiqq.

**Comment by pubiqq** [comment]
I guess it's a design flaw and it just needs to be fixed, no additional parameters need to be introduced.
