### ISSUE TITLE
Question: How to use shapeAppearanceOverlay with ExtendedFloatingActionButton and TextInputLayout?

### ISSUE THREAD

**Issue by Zeliret** [material-components/material-components-android#295]
Hi there. 
I was trying to change the form of my input field and fab with the "shapeAppearanceOverlay" attribute.
I used the same style for a card and it works. But for the input field and extended fab it is just ignored I suppose. 
What's the trick?

**Comment by ymarian** [comment]
Hi @Zeliret  
These are bugs. On ExtendedFab we are setting corner radius onMeasure. I opened a bug for that.
For TextInputLayout it looks like a bug too, this is an ok workaround though:
```
        app:boxCornerRadiusTopStart="-1px"
        app:boxCornerRadiusTopEnd="-1px"
        app:boxCornerRadiusBottomEnd="-1px"
        app:boxCornerRadiusBottomStar="-1px"
```



Bugs for you to track:
https://issues.google.com/issues/127956749
https://issues.google.com/issues/127954794
