### ISSUE TITLE
When I use navigation, I need to set materialcontainertransform in the target fragment, but I can't use setallcontainercolors, which will cause errors

### ISSUE THREAD

**Issue by a1782680475** [material-components/material-components-android#2954]
![image](https://user-images.githubusercontent.com/32875468/188052721-6eb7782f-f06a-453b-9408-c4f88c311bce.png)
Now I want to use setallcontainercolors to solve the problem in # 1704, because I also encountered the same bug

**Comment by a1782680475** [comment]
![image](https://user-images.githubusercontent.com/32875468/188055053-32060289-a43a-4f65-b504-64c539c3ce50.png)
I solved this problem in this way. Is there a way to directly obtain the color value without judging whether it is a dark mode?

**Comment by drchen** [comment]
You need to getColor inside your apply clause. : )

Otherwise colorSurface will be whatever day/night version your day/night mode was when onCreate() is called.
