### ISSUE TITLE
How to resolve the exitTransition conflicts in the same fragment？

### ISSUE THREAD

**Issue by a1782680475** [material-components/material-components-android#2955]
I have a fragmentA, in which there is a nested fragmentB（In viewpager2） and a search button. I want to jump from fragmentB to fragmentC. I set exittransition and reentertransition in fragmentA and fragmentC respectively. It works very well. But I still need to jump from fragmentA to fragmentD when I click the search button. At this time, the exittransition and reentertransition in fragmentA will conflict with another transition effect. How can I solve it?
![Screenshot_20220902-145813](https://user-images.githubusercontent.com/32875468/188077746-4c510f97-eea8-4603-a6be-96b4b0aea90f.jpg)
my english so bad,sorry.i holp you understand my mean

**Comment by drchen** [comment]
Hunter, do you have any insights regarding this?

**Comment by hunterstich** [comment]
Hey @a1782680475 ,

It seems like you should be able to just clear the existing transitions in Fragment A? 

How are you setting the transitions if Fragment C and Fragment D? Could you pass arg into Fragment C and Fragment D from Fragment A the determine which type of transition, if any, those fragments should use?

If you're able to attach a sample that reproduces the issue you're having and a screen recording, that would make things much easier to debug!

Hunter

**Comment by hunterstich** [comment]
@a1782680475,

Going to close this due to inactivity. If you are still running into this issue, feel free to re-open.
