### ISSUE TITLE
I have a xml file.I am using there BottomAppBar and programatically using  bottomAppBar.cradleVerticalOffset and it is not working only cradleRadius is getting change.

### ISSUE THREAD

**Issue by stAyushJain** [material-components/material-components-android#297]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

**Comment by dsn5ft** [comment]
Thanks for filing, I've converted this to https://issuetracker.google.com/issues/127946637, so you can follow updates there.
