### ISSUE TITLE
[Jetpack Compose Documentation] Add implementation code in website m3.material.io

### ISSUE THREAD

**Issue by ekoo** [material-components/material-components-android#2973]
Currently I'm learning Jetpack Compose with Material 3. When I'm looking for sample code in Official Material 3 Website m3.material.io that will be reference to https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary and load all documentation which is take a lot of time.

I think it's better if Jetpack Compose Sample added to official Material 3 website if someone else looking for quick example.

**Comment by drchen** [comment]
Hi thanks for reporting the issue. This repository is for Views implementation only. I'll rely the message to the Compose team but let me close the issue for now.
