### ISSUE TITLE
[DrawerLayout] I found unintentional error inside NavigationView.setSubheaderInsetEnd function (It is pointing to incorrect function)

### ISSUE THREAD

**Issue by tahasami2500** [material-components/material-components-android#2976]
_[According to this issue](https://github.com/material-components/material-components-android/issues/2975), I tried `app:subheaderInsetEnd="28dp"` inside XML, Also I tried `navigation.setSubheaderInsetEnd(84)` programmatically but all of these not solve the problem._

**I found unintentional error inside `NavigationView.setSubheaderInsetEnd` function, It is pointing to incorrect function:**

![Untitled](https://user-images.githubusercontent.com/24863605/190969682-2d054bae-f20b-4833-a97f-24d4f540e6e2.png)

**Also to make sure the problem is from there, I tried this:**

```
Log.w("...", String.valueOf(navigation.getSubheaderInsetStart())); -> The output is 84
navigation.setSubheaderInsetEnd(400);
Log.w("...", String.valueOf(navigation.getSubheaderInsetStart())); -> The output is 400
```

_Thank you for your efforts._

**Comment by drchen** [comment]
Ah...that's a dumb mistake. Thanks @pubiqq for pushing a fix!
