### ISSUE TITLE
Error inflating com.google.android.material.button.MaterialButton

### ISSUE THREAD

**Issue by houdayec** [material-components/material-components-android#298]
Hi everyone.

I'm trying to dynamically inflate a button layout into a recycler view item from my item adapter.
Here is how it looks : 

`LayoutInflater factory = LayoutInflater.from(mContext);
        View buttonView = factory.inflate(buttonsList.get(position).getLayout(), null);
        holder.buttonContainer.addView(buttonView);`

Basically, my getLayout attribute returns the layout id of the corresponding button item.

Layout looks like this : 

`<com.google.android.material.button.MaterialButton
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/material_button"
    style="@style/Widget.MaterialComponents.Button"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:backgroundTint="@color/colorPrimary"
    android:text="Search"
    android:textSize="14sp"
    android:textAllCaps="true"
    android:fontFamily="@font/raleway_semibold" />`

I can inflate basic buttons from the old AppCompat library, but not from the Material Design.

I get the following error : 

```
android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class com.google.android.material.button.MaterialButton
    Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.google.android.material.button.MaterialButton
```

Do you have any idea where the problem comes from ? Is it a library bug ?

Thanks in advance,

Corentin

**Comment by gothamite** [comment]
Try to update your app theme to inherit from Theme.MaterialComponents (or a descendant)

**Comment by cketcham** [comment]
If you are still having an issue that you think is a bug, please submit it at https://issuetracker.google.com/issues/new?component=439535

**Comment by m-Samhoury** [comment]
@houdayec I faced this issue before and it was because the `android:textAppearance` attribute was missing.

Just add the below attribute and your problem should be fixed.

`android:textAppearance="@style/TextAppearance.MaterialComponents.Button"`

**Comment by martinKindall** [comment]
@m-Samhoury I had to add yours plus another line to MaterialButton attributes:

android:theme="@style/FormButton"
android:textAppearance="@style/TextAppearance.MaterialComponents.Button"

----------

Had to create my own style

<style name="FormButton" parent="Theme.MaterialComponents">
        <item name="colorOnPrimary">@android:color/holo_red_light</item>
        <item name="colorPrimary">@android:color/holo_orange_dark</item>
        <item name="colorOnSurface">@android:color/holo_orange_light</item>
 </style>

Then it worked.

**Comment by Twibap** [comment]
Change your AppTheme parent to Theme.MaterialComponents

Before
```xml
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
    </style>
```

After
```xml
    <!-- Material application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <!-- Customize your theme here. -->
    </style>
```

[More](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#4-change-your-app-theme-to-inherit-from-a-material-components-theme)

**Comment by YasserElgammal** [comment]
> Change your AppTheme parent to Theme.MaterialComponents
> 
> Before
> 
> ```
>     
>     <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
>         
>     </style>
> ```
> 
> After
> 
> ```
>     
>     <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
>         
>     </style>
> ```
> 
> [More](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#4-change-your-app-theme-to-inherit-from-a-material-components-theme)

Thank you Twibap 
This worked for me

**Comment by zawawimanja** [comment]
change in gradle not work for me. but adding in xml

  android:theme="@style/FormButton"
                android:textAppearance="@style/TextAppearance.MaterialComponents.Button"
              

work for me

**Comment by NirmalanSindujan** [comment]
check your style file whether is it define as AppCompa or MaterialComponents.
`<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">`
if it is AppCompat yo are  trying material but your global one is set to Material. Thatswhy error is showing

**Comment by MatheusMesquita** [comment]
Issue still happening even after setting all the properties commented above. Using `com.google.android.material:material:1.1.0`

**Comment by conteluca** [comment]
Try to change theme attribute into application node inside manifest file!!!

**Comment by Willemsmit99** [comment]
Changed the style and it works perfectly!
Old = <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
New = <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">

**Comment by sumsuddin** [comment]
On the `AndroidManifest.xml` change `android:theme="@style/AppTheme">` to `android:theme="@style/Theme.MaterialComponents">`

Solved my problem!

**Comment by thadikari** [comment]
The one liner version of @m-Samhoury's solution is to add `android:theme="@style/Theme.MaterialComponents.Light"` to the widget. No need to interfere with the `AppTheme`. See [this SO question](https://stackoverflow.com/a/66751467/1551308).
e.g.,:
```
    <com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton
        android:id="@+id/fabMenu"
        android:icon="@drawable/menu_48px"
        android:text="Menu"
        android:theme="@style/Theme.MaterialComponents.Light" />
```
