### ISSUE TITLE
[Bottom sheet] elevation is inconsistent

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#2983]
**Description:**
https://m3.material.io/components/bottom-sheets/specs:
```0
Element      | Design attribute | Role    | Token or value
1. Container | Elevation        | Level 1 | md.sys.elevation.level1
```
https://m3.material.io/components/bottom-sheets/implementation:
```
Element   | Attribute         | Related method(s) | Default value
Elevation | android:elevation | N/A               | 3dp
```
But, md.sys.elevation.level1 is not 3dp but 1dp.

https://m3.material.io/components/bottom-sheets/specs:
Modal bottom sheets are above a scrim while standard bottom sheets don't have a scrim. Besides this, **both types of bottom sheets have the same specs**.
But, the elevation is different in the implementation (standard bottom sheet: 3dp, modal bottom sheet: 6dp):
```
  <style name="Widget.Material3.BottomSheet" parent="Widget.MaterialComponents.BottomSheet">
    <item name="android:elevation" tools:ignore="NewApi">@dimen/m3_bottom_sheet_elevation</item>
    ...
  </style>

  <style name="Widget.Material3.BottomSheet.Modal">
    <item name="android:elevation" tools:ignore="NewApi">@dimen/m3_bottom_sheet_modal_elevation</item>
  </style>

  <dimen name="m3_bottom_sheet_elevation">@dimen/m3_sys_elevation_level2</dimen>
  <dimen name="m3_bottom_sheet_modal_elevation">@dimen/m3_sys_elevation_level3</dimen>

  <dimen name="m3_sys_elevation_level2">3dp</dimen>
  <dimen name="m3_sys_elevation_level3">6dp</dimen>
```
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/res/values/styles.xml#L69
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/res/values/styles.xml#L82
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/res/values/dimens.xml#L25-L26
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/elevation/res/values/tokens.xml#L24-L25

**Expected behavior:** Match the spec and the implementation.

**Android API version:** 32

**Material Library version:** 1.7.0-rc01

**Device:** Emulator 31.3.10

**Comment by manabu-nakamura** [comment]
Does the standard bottom sheet have sufficient contrast with surfaces beneath?
https://github.com/material-components/material-components-android/commit/6cf56a5ebebe6e1caa39a0460997b8e536e14c9f
https://m3.material.io/styles/elevation/applying-elevation
![Screenshot_20221024_111039](https://user-images.githubusercontent.com/71050561/197436300-a1723787-5107-4c08-80ea-2669de5ead8b.png)

**Comment by imhappi** [comment]
Will reach out to the designer to confirm; marking this as closed for now since elevation now matches the specs
