### ISSUE TITLE
[Snackbar] The button in the Snackbar became not clickable after changing z-index

### ISSUE THREAD

**Issue by tahasami2500** [material-components/material-components-android#2991]
I tried to make `Snackbar` appear behind the `DrawerLayout` and I did that successfully but the install button became not clickable.

Is this a bug or have I missed something?

`.getRoot()` will return `DrawerLayout`

```
Snackbar snackbar = Snackbar.make(activityMainBinding.getRoot(), R.string.youtube_not_installed, BaseTransientBottomBar.LENGTH_LONG);
snackbar.getView().setZ(activityMainBinding.getRoot().getZ() - 1); //The button will be clickable if I remove this line
snackbar.setAction(R.string.install, view -> startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id=" + packageName))));
snackbar.show();
```

![untitled](https://user-images.githubusercontent.com/24863605/191819839-cb130763-1f44-4f70-baad-06beac4af697.jpg)

**Comment by pekingme** [comment]
I assume that the DrawerLayout doesn't block the Snackbar but is still over it. Does the DrawerLayout consume your client event?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still an issue.
