### ISSUE TITLE
[Checkbox] Indeterminate state

### ISSUE THREAD

**Issue by p-dmitriy** [material-components/material-components-android#2992]
**Description:** Indeterminate state not showing with Material2 theme. With Material3 works fine.
With Material2 theme:
![telegram-cloud-photo-size-2-5292126512084008818-y](https://user-images.githubusercontent.com/82445071/192006216-99a8b81a-2e68-4204-acd8-5579d3c04272.jpg)
With Material3 theme:
![telegram-cloud-photo-size-2-5292126512084008819-y](https://user-images.githubusercontent.com/82445071/192006271-20dba43d-365f-40c2-a580-8f53af4157dd.jpg)
I fixed this manually set `buttonDrawable` and `buttonIconDrawable`:
```kotlin
with(binding.cbSelection) {
    buttonDrawable = context.getDrawableById(RMaterial.drawable.mtrl_checkbox_button)
    buttonIconDrawable = context.getDrawableById(RMaterial.drawable.mtrl_checkbox_button_icon)
}
```

**Expected behavior:** Indeterminate state renders correctly for all themes. 

**Source code:** 
```xml
<CheckBox
        android:id="@+id/checkbox"
        android:theme="@style/Theme.Material3.DayNight" // With MaterialComponents.DayNight not working
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:checkedState="indeterminate" />
```

**Android API version:** 30

**Material Library version:** 1.7.0-beta01/rc01

**Device:** Emulator/Mi 9 Lite

**Comment by leticiarossi** [comment]
Hi there, the addition of the indeterminate state support for the checkbox was intended as part of our Material 3 updates. We don't plan on adding that for pre-M3 themes at the moment
