### ISSUE TITLE
MaterialTimePicker: Bring back inner circle for CLOCK_24H format

### ISSUE THREAD

**Issue by ridcully99** [material-components/material-components-android#2997]
As of now, when the timepicker is shown in CLOCK_24H format, all 24 hours are shown in a single circle. This puts 12h at the bottom of the circle and is totally confusing for every user, as the whole widget's idea is to resemble a watch face. And believe me, also in countries with a 24h time format, 12 is at the top of each clock.
So please change the design so that the outer circle shows the hours from 1 to 12 and an inner circle shows 13 to 24. 
For reference just check Google's own Calendar app on Android.

![image](https://user-images.githubusercontent.com/485060/192238597-8a8dc5e1-3883-4aad-a7bf-5f4cac8c5447.png)
![image](https://user-images.githubusercontent.com/485060/192238952-6f0dfca0-4207-4711-816e-bb932d94ee25.png)

**Comment by paulfthomas** [comment]
Hi @ridcully99, the 24H dual ring version will be available in v1.8.0, see https://github.com/material-components/material-components-android/issues/1450 for more details.

**Comment by cxobaidullah** [comment]
how to implement this please provede a code for implementation in project

**Comment by paulfthomas** [comment]
https://developer.android.com/reference/com/google/android/material/timepicker/MaterialTimePicker.Builder#setInputMode(int)
