### ISSUE TITLE
Feature Request - BottomNavigation onItemReselected

### ISSUE THREAD

**Issue by andhie** [material-components/material-components-android#30]
In the Material Design specs for BottomNavigation Behavior, it described a behavior to scroll to top when the same active tab is selected again.

Refer:
https://material.google.com/components/bottom-navigation.html#bottom-navigation-behavior
 the 1st video with caption "Tapping on the active action in the bottom navigation bar will navigate the user to the top of the view."

In the current BottomNavigationView#OnNavigationItemSelectedListener only notified when any item has been clicked. it does not distinct if its the same item or not. It would be better if there is a similar onItemReselected callback. Even better, if the BottomNavigationBehavior can take care of the "scroll to top" of any scrollable view

Copied from the same issue: https://code.google.com/p/android/issues/detail?id=228456

**Comment by tec27** [comment]
Added in 6cbee8658b0a529ec624a8e96b4a3bcdf24abc4c (and available in the 25.2.0 release)
