### ISSUE TITLE
[MaterialButton] paddingTop and paddingBottom are increased

### ISSUE THREAD

**Issue by nininea** [material-components/material-components-android#3000]
**Description:**  after rendering on the screen material button  height is 48dp instead of 40dp, because paddingTop and paddingBottom are 10dp. No custom overloads for those attributes. 

**Expected behavior:** 
<img width="651" alt="Screenshot 2022-09-27 at 20 07 56" src="https://user-images.githubusercontent.com/82098854/192578723-9c9909ae-b905-4645-8a56-aa6fbe054f58.png">
<img width="779" alt="Screenshot 2022-09-27 at 20 10 27" src="https://user-images.githubusercontent.com/82098854/192578948-f6df6960-6031-4ce9-93b4-76454adffd6e.png">

**Source code:** `
    <item name="android:paddingBottom">@dimen/m3_btn_padding_bottom</item>`

**Android API version:**  Android 12, API 32

**Material Library version:**  1.6.1

**Device:** Pixel 3a

**Comment by pekingme** [comment]
Thanks for reporting this. The height of the button's bound is 48dp. The height of the pill shape is actually 40dp by applying 4dp top and bottom inset. Let me dig a bit see why we actually need this inset though.

**Comment by nininea** [comment]
it seems insect and padding are summed up
![Screenshot 2022-09-29 at 16 06 34](https://user-images.githubusercontent.com/82098854/193028428-dd701190-2f4c-4a86-b3b9-985230e3b68f.png)

**Comment by drchen** [comment]
Yes the actual padding will be the sum of of the inset and the user padding set in the component style, so the visual padding (between the text and the edge of the button) will be the value set in the style.
