### ISSUE TITLE
[MaterialButtonToggleGroup] Setting CornerRadius for all of the buttons

### ISSUE THREAD

**Issue by h4jahmad** [material-components/material-components-android#3008]
Hi.
I wanted to have the buttons of the MaterialButtonToggleGroup, have rounded corners in all 4 corners of them, but it didn't matter how much I tried different options using XML ShapeAppearance and ShapeAppearanceOverlay or setting the related attributes to the buttons directly(either in the XML layout or throw kotlin), I couldn't make it happen because of the `updateChildShapes` method that's being called in the `onMeasure` method in the MaterialButtonToggleGroup source code:

```java
void updateChildShapes() {
    int childCount = getChildCount();
    int firstVisibleChildIndex = getFirstVisibleChildIndex();
    int lastVisibleChildIndex = getLastVisibleChildIndex();
    for (int i = 0; i < childCount; i++) {
      MaterialButton button = getChildButton(i);
      if (button.getVisibility() == GONE) {
        continue;
      }

      ShapeAppearanceModel.Builder builder = button.getShapeAppearanceModel().toBuilder();
      CornerData newCornerData = getNewCornerData(i, firstVisibleChildIndex, lastVisibleChildIndex);
      updateBuilderWithCornerData(builder, newCornerData);

      button.setShapeAppearanceModel(builder.build());
    }
  }
```

The solution that I implemented for the sake of time was that I created a class that extends MaterialButtonToggleGroup class, overwritten the `onMeasure` method, called the super method so I'll be sure all the default implementations are done, and then added my custom settings like below.

```kotlin
override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
	super.onMeasure(widthMeasureSpec, heightMeasureSpec)
	for (i in 0 until childCount) {
		val button = getChildAt(i) as MaterialButton
		if (button.visibility == GONE) {
			continue
		}
		val builder = button.shapeAppearanceModel.toBuilder()
		val radius = resources.getDimension(R.dimen.my_radius_size)
		button.shapeAppearanceModel = builder.setTopLeftCornerSize(radius)
			.setBottomLeftCornerSize(radius)
			.setTopRightCornerSize(radius)
			.setBottomRightCornerSize(radius).build()
	}
}

```

So I would really like to have this option that I could have to decide whether I want those ShapeAppearances to be overwritten or not. whether it's an XML attribute or just a flag that you can switch it.

**ButtonsGroup that I want:**
![ButtonsGroup that I want](https://i.ibb.co/Jq5Lzqd/Screen-Shot-2022-10-09-at-00-03-24.png "ButtonsGroup that I want")

**ButtonsGroup that Material library provides by default:**
![ButtonsGroup that Material library provides by default](https://i.ibb.co/NZQZZhm/Screen-Shot-2022-10-08-at-23-56-36.png "ButtonsGroup that Material library provides by default")

**Comment by khmaies5** [comment]
In Googles [MaterialButtonToggleGroup](https://developer.android.com/reference/com/google/android/material/button/MaterialButtonToggleGroup) reference page they  stated :

> MaterialButtonToggleGroup also overrides any shapeAppearance, shapeAppearanceOverlay, or cornerRadius attribute set on MaterialButton children such that only the left-most corners of the first child and the right-most corners of the last child retain their shape appearance or corner size.

but what if don't like this behaviour and want to disable it ?
