### ISSUE TITLE
Access RecyclerView EditTexts

### ISSUE THREAD

**Issue by manishprp** [material-components/material-components-android#3011]
I am creating the recyclerview with Edittexts as the row items.
Now, When I am done with creating this, I needto access those edittextx to set text inside them to edit further. 
But, not able to do this.

**Comment by paulfthomas** [comment]
Hi,

This doesn't seem like an issue related to the Android Material library, please refer to RecyclerView documentation like this one https://developer.android.com/develop/ui/views/layout/recyclerview#implement-adapter for more information.
