### ISSUE TITLE
Getting always 24 hour format after selecting time

### ISSUE THREAD

**Issue by jayeshmohan94** [material-components/material-components-android#3013]
**Description:** I implemented MaterialTimePicker and strange issue observed. I have configured time picker with 12 H time format and keyboard as input mode. I choose 4 hour and 30 min with AM . But after click ok, Iam getting 16 as time picker hour. I expected 4.

**Expected behavior:** After selecting  4hour 30 min with AM, Hours should print as 4 now I am getting 16 

**Source code:**  

   val materialTimePicker: MaterialTimePicker = MaterialTimePicker.Builder()
        .setTitleText("SELECT TIME")
        .setInputMode(MaterialTimePicker.INPUT_MODE_KEYBOARD)
        .setTimeFormat(TimeFormat.CLOCK_12H)
        .setHour(12)
        .setMinute(30)
        .build()

    materialTimePicker.show(supportFragmentManager, "MainActivity")

    materialTimePicker.addOnPositiveButtonClickListener {
        val pickedHour: Int = materialTimePicker.hour
        val pickedMinute: Int = materialTimePicker.minute
    }

**Android API version:** Andriod 29 API

**Material Library version:**  'com.google.android.material:material:1.6.1'

**Device:** Emulator with 29 API level

**Comment by paulfthomas** [comment]
Hi @jayeshmohan94, this is the expected behavior, [getHour()](https://developer.android.com/reference/com/google/android/material/timepicker/MaterialTimePicker#getHour()) returns the hour of day in the range [0, 23] regardless of the TimeFormat.

**Comment by jayeshmohan94** [comment]
Then how I find out that its AM or PM ??

**Comment by paulfthomas** [comment]
0 -> 11 = AM
12 -> 23 = PM
See this [article](https://en.wikipedia.org/wiki/24-hour_clock) for more information.

**Comment by jayeshmohan94** [comment]
Its always coming 16 on hours after I selected 4 AM.
