### ISSUE TITLE
MaterialShapeDrawable treatment elevation issue

### ISSUE THREAD

**Issue by Shusshu** [material-components/material-components-android#302]
Bug reported here: https://issuetracker.google.com/issues/128350851

Description: Elevation on a custom MaterialShapeDrawable does not draw properly as expected by the different corner treatments applied to that drawable

- Expected behaviour: see attached screenshot

- Source code: https://github.com/Shusshu/MaterialShapeDrawable-Treatments-ShadowIssue

- Design Library Version: com.google.android.material:material:1.1.0-alpha04

- Android API version: 9

- Device: Emulator

**Comment by ymarian** [comment]
Will reply in internal bug thanks for the detailed report!
