### ISSUE TITLE
[Button] Cannot get background color int using Kotlin (btn.background as ColorDrawable cast fails)

### ISSUE THREAD

**Issue by mvidaldp** [material-components/material-components-android#3020]
**Description:** When trying to get the background color int of a button via casting the background property as ColorDrawable (to finally get the color property), the cast into ColorDrawable fails. It tries to convert a RippleDrawable into ColorDrawable.

**Expected behavior:** To work as in Java: https://stackoverflow.com/a/8089242

**Source code:** `val color = (btn.background as ColorDrawable).color`

**Error:** `java.lang.ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.ColorDrawable`

**Android API version:** 32

**Material Library version:** from SDK 32

**Device:** Xiaomi Mi A3

**Comment by paulfthomas** [comment]
Hi @mvidaldp, the comment you're linking is from 2011, there is no guarantee the code works in Java either. I'm closing as this is not an issue directly related to the Android Material library.

**Comment by mvidaldp** [comment]
Hi @paulfthomas, the comment is from 2011 but it is the actual way to get the background color. I could have picked a recent example and the code would have been the same.

**Comment by mvidaldp** [comment]
But anyways, could you point me out where should I put the issue if it's not related to the Android Material library?
