### ISSUE TITLE
[Extended Floating Action Button] elevation not respected in ExtendedFloatingActionButton

### ISSUE THREAD

**Issue by kyleholmberg** [material-components/material-components-android#3021]
**Description:**
When using the ExtendedFloatingActionButton view, app:elevation is not respected like it is on the regular FloatingActionButton. 

**Expected behavior:**
This is what elevation 0 looks like on a regular FloatingActionButton with a transparent background:
![image](https://user-images.githubusercontent.com/104792297/195724236-2325550d-1a82-4935-bc8b-2a3ae88121b9.png)

vs elevation 4dp (notice the red sub-circle):
![image](https://user-images.githubusercontent.com/104792297/195724357-1359dc0d-2f9c-4d6c-a250-95e92a18419c.png)

However, with app:elevation set to 0dp with the ExtendedFloatingActionButton, it looks the same as the second picture with 4dp elevation. I want the look of picture one, so I expect setting app:elevation to 0dp to give the same look.

Additionally, setting the text on the ExtendedFloatingActionButton gives inconsistent elevation results:
![image](https://user-images.githubusercontent.com/104792297/195724699-7bee3da8-0576-4bf4-aee2-539d0d57fb0c.png)
![image](https://user-images.githubusercontent.com/104792297/195724720-76f329e3-849e-45d2-855b-8dc5a937bc66.png)

**Source code:**
ExtendedFloatingActionButton xml:
```
<com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton
        style="@style/Theme.MyApp.FloatingActionButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:elevation="0dp"
        app:icon="@drawable/ic_location"
        app:fabSize="mini"/>
```

Style xml:
```
<style name="ThemeOverlay.MyApp.QuickCaptureFloatingActionButton" parent="ShapeAppearance.MaterialComponents.SmallComponent">
    <item name="cornerSize">100%</item>
    <item name="cornerFamily">rounded</item>
</style>

 <style name="Theme.MyApp.FloatingActionButton" parent="Widget.MaterialComponents.FloatingActionButton">
    <item name="shapeAppearanceOverlay">@style/ThemeOverlay.MyApp.FloatingActionButton</item>
    <item name="backgroundTint">#99000000</item>
    <item name="color">#99000000</item>
    <item name="android:hapticFeedbackEnabled">true</item>
 </style>
```

**Minimal sample app repro:** 
[efabbug.zip](https://github.com/material-components/material-components-android/files/9781213/efabbug.zip)

**Material Library version:** 1.6.1, but also tested on 1.8.0-alpha01

**Comment by imhappi** [comment]
From my testing, it seems to be only an issue with the background tint values of form `#aarrggbb`...

Will continue to dig into this, but as a workaround, could you use hex values instead?

**Comment by kyleholmberg** [comment]
Yeah I think we have two temporary workarounds, either:
1. Use a non-transparent color
2. Use FloatingActionButton without the text for now

But the end design we would like to be able to use the ExpandableFloatingActionButton with transparent values. Thanks for looking into this!

**Comment by imhappi** [comment]
I did some more testing; I'm still able to repro this with transparent color with the regular FAB. Unfortunately I poked around and it looks like this is also an existing bug with transparent colours and material components that also use MaterialShapeDrawable. 

At the crux of it, I'm not sure why the native shadows are still being drawn when elevation is set to 0, but one good workaround is to set the shadow attributes on the fab

```
android:outlineAmbientShadowColor="@color/transparent
android:outlineSpotShadowColor="@color/transparent
```

**Comment by kyleholmberg** [comment]
I apologize, I forgot to reply to this, but setting the shadow colors to transparent is a great workaround, I am able to use the extended floating action button now. Thank you!!

**Comment by imhappi** [comment]
Awesome! Going to close this bug since there is a workaround and there's an existing bug (filed internally - b/132323220)

**Comment by Burak-Tasci** [comment]
Since this solution will not work under API 28, how can we consider it as a valid solution?
