### ISSUE TITLE
[BottomAppBar] the overflow menu icon button is on the right of the icon buttons

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3029]
**Description:**
https://m3.material.io/components/bottom-app-bar/guidelines:
<img width="676" alt="a" src="https://user-images.githubusercontent.com/71050561/196113813-29c59026-2423-40ba-9dc3-9c26f41e9c30.png">
The overflow menu icon button (three dots) is on the **left** of the icon buttons.

Editor5:
![Screenshot_20221017_160016](https://user-images.githubusercontent.com/71050561/196114023-036b117c-38c5-4f7d-9afe-2749a06a934a.png)
The overflow menu icon button is on the **right** of the icon buttons.

**Expected behavior:** The overflow menu icon button is on the **left** of the icon buttons.

**Source code:**
```
<menu
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <item
        android:title="@string/undo"
        android:icon="@drawable/ic_outline_undo_24"
        app:showAsAction="ifRoom" />
    <item
        android:title="@string/redo"
        android:icon="@drawable/ic_outline_redo_24"
        app:showAsAction="ifRoom" />
    <item
        android:title="@string/copy"
        android:icon="@drawable/ic_outline_content_copy_24"
        app:showAsAction="ifRoom" />
    <item
        android:title="@string/paste"
        android:icon="@drawable/ic_outline_content_paste_24"
        app:showAsAction="ifRoom" />
</menu>
```

**Minimal sample app repro:** [Editor5.zip](https://github.com/material-components/material-components-android/files/9797880/Editor5.zip)

**Android API version:** 32

**Material Library version:** 1.7.0-rc01

**Device:** Emulator 31.3.12

**Comment by imhappi** [comment]
Unfortunately this is intended; the bottom app bar is extended off of the toolbar, and uses its menu system. We looked into this and it wasn't feasible to have the icon on the left side without strange behavior; we discussed with the designer who was ok with the overflow icon on the right side.

Assets here are reflected with the overflow menu icon on the right:
https://github.com/material-components/material-components-android/blob/master/docs/components/BottomAppBar.md

Looks like the material site was not updated to reflect this :( I'll ping the designer, but closing this issue

**Comment by manabu-nakamura** [comment]
Thank you very much. I understood.
