### ISSUE TITLE
Feature request - Fixed tab indicator width for TabLayout

### ISSUE THREAD

**Issue by peerless2012** [material-components/material-components-android#303]
Like the title，sometimes we need the tab indicator with to be fixed, hope can add a attr to set the fixed value.

**Comment by MGaetan89** [comment]
Isn't that already possible by using a custom drawable and passing it to `app:tabIndicator`?

**Comment by peerless2012** [comment]
> Isn't that already possible by using a custom drawable and passing it to `app:tabIndicator`?

Not work for me.

**Comment by cketcham** [comment]
tracked at http://issuetracker.google.com/issues/128641683

**Comment by peerless2012** [comment]
That's me.
