### ISSUE TITLE
Add java code

### ISSUE THREAD

**Issue by Arashvscode** [material-components/material-components-android#3034]
Can you add Java code in addition to Kotlin's useless code, because this library is written with Java, so Java code should be added in the component introduction section.

**Comment by Arashvscode** [comment]
> Kotlin is the official Android developing language. It has nothing to with in which language the library is written. : )
> 
> Also I believe converting kotlin examples in our dev doc to java is pretty straightforward if you need that.


It's a bitter truth, but I hate Kotlin. Anyway, add the Java code, it's not too much to ask

**Comment by drchen** [comment]
I understand your feeling. We currently don't have spare resources to update java examples (and to figure out a way to make it switchable between java/kotlin like the Android dev site does), but we welcome volunteers to help create them if there's a need in the community. : )
