### ISSUE TITLE
[Release Notes] Wrong `BottomAppBar` link in `1.7.0` release notes

### ISSUE THREAD

**Issue by mateuszkwiecinski** [material-components/material-components-android#3036]
**Description:** 
>BottomAppBar has been redesigned! Check out the updated [documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/Checkbox.md)

link in [1.7.0 release notes](https://github.com/material-components/material-components-android/releases/tag/1.7.0) leads to `Checkbox` component documentation 

**Expected behavior:** I'm guessing it should link to https://github.com/material-components/material-components-android/blob/master/docs/components/BottomAppBar.md or https://github.com/material-components/material-components-android/blob/1.7.0/docs/components/BottomAppBar.md?

**Comment by hunterstich** [comment]
Ah! Thanks for catching this @mateuszkwiecinski. Fixed
