### ISSUE TITLE
Release notes 1.7.0 has a hyperlink issue 

### ISSUE THREAD

**Issue by mtwalli** [material-components/material-components-android#3037]
Release notes [1.7.0](https://github.com/material-components/material-components-android/releases/tag/1.7.0) has an issue  in
> BottomAppBar has been redesigned! Check out the updated [documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/Checkbox.md) 

it leads to checkbox documentation

**Comment by MGaetan89** [comment]
Already reported in #3036
