### ISSUE TITLE
[Update] This issue reference to last closed issue #3015

### ISSUE THREAD

**Issue by MML-Pro** [material-components/material-components-android#3038]
> Hi @MML-Pro,
> 
> Thanks for filing an issue!
> 
> If I understand correctly, I think the main issue you're running into is the fact that app bars and contextual action bars in Material3 use `colorSurface` as their background color.
> 
> If you want just your app bar and contextual action bar to be dark, you could apply a theme overlay to your app bar layout:
> 
> ```
>         <com.google.android.material.appbar.AppBarLayout
>             android:theme="@style/ThemeOverlay.Material3.Dark" =====> apply a dark theme to app bar and its descendants
>             android:id="@+id/appBarLayout"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             app:liftOnScroll="true">
> 
>              <com.google.android.material.appbar.MaterialToolbar
>                 android:id="@+id/toolbar"
>                 android:layout_width="match_parent"
>                 android:layout_height="?attr/actionBarSize"
>                 app:layout_scrollFlags="scroll|enterAlways|snap"
>                 app:title="Post details" />
> 
>         </com.google.android.material.appbar.AppBarLayout>
> ```
> 
> If you want to further customize what colors things are, you could create your own theme overlay instead of using `ThemeOverlay.Material3.Dark` and specify things like `colorSurface`, `colorOnSurface`, `actionModeStyle`, etc.
> 
> Going to close this for now but please re-open if this isn't clear, you have questions, or want to keep discussing!

**Hi @hunterstich**

Unfortunately, you misunderstood my explanation of the issue, I don't wanna to change the appbar color to dark, I want to use my custom colors which is is **"GREEN COLOR"** and for the title is white color I alreasy used `colorSurface` for background color and `colorOnSurface` for the title  to applyit in all appbars in my app but it didn't implemented

I've create demo app showing the problem please check it  and **my notes in app_bar_main.xml** and re open the issue, I don't have permission to do that, I'll added the other component  **CONTEXTUAL ACTION BAR** details once this issue is confirmed

https://github.com/MML-Pro/Material3DemoApp

**Comment by hunterstich** [comment]
Re-opening the original issue
