### ISSUE TITLE
DatePickerDialog and TimePickerDialog are not themed when using dark theme

### ISSUE THREAD

**Issue by Pramod-sj** [material-components/material-components-android#304]

**Comment by dsn5ft** [comment]
Hello, what version of the MDC-Android library are you using? And what theme are you inheriting from? I think this might have been fixed at some point.

**Comment by Pramod-sj** [comment]
1.1.0-alpha04 
And "Theme.MaterialComponents.NoActionBar" is the parent theme

**Comment by ldjcmu** [comment]
Hey,

The Picker APIs are still in flux so the names aren't final, but you should be able to get a date picker that works with dark theme using R.style.ThemeOverlay_MaterialComponents_MaterialAlertDialog_Picker_Date_Calendar or by using MaterialStyledDatePickerDialog.

Again these APIs are being actively worked and are not where we want them yet; you'll see some updates to them over the next month.
