### ISSUE TITLE
Java → Kotlin

### ISSUE THREAD

**Issue by nachtien** [material-components/material-components-android#3040]
Hi there! 

I'd like to revert this [PR](https://github.com/material-components/material-components-android/pull/2947), and start to convert components to Kotlin.

Based on the response in that PR, I feel like Java is the go-to language for Material. Is this project open to converting to Kotlin? Can I work on the date picker and slowly start to convert that to Kotlin?  

Happy Thursday/Friday (or whatever day you guys look at this)!

**Comment by hunterstich** [comment]
Hi Nick!

We've had related questions in the past. (see https://github.com/material-components/material-components-android/issues/2088)

Thank you so much for being interested in contributing but we currently don't have plans to move to Kotlin. If that's a change we do decide to make as a team I imagine we would keep existing components in Java and only consider Kotlin for new components. If this happens I'll be sure to come back and update this issue.
