### ISSUE TITLE
Outlined `MaterialAutoCompleteTextView` in `TextInputLayout` shows its hint incorrectly

### ISSUE THREAD

**Issue by MrTheGood** [material-components/material-components-android#3041]
**Description:** When you have a `MaterialAutoCompleteTextView` in a `TextInputLayout` with the `styles` `Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu` the hint is overlapped by the outline. 
Example: 
<img width="826" alt="Screenshot 2022-10-21 at 13 44 16" src="https://user-images.githubusercontent.com/23239376/197188413-953c78f9-5675-42d2-846c-3571c3d4d66a.png">

**Expected behavior:** The outline to not be present under the label just like other `TextInputLayout`s
<img width="488" alt="Screenshot 2022-10-21 at 13 45 59" src="https://user-images.githubusercontent.com/23239376/197188678-d93fbcf9-62df-4d30-bad2-2bfbdf30dd97.png">

**Source code:** 
```xml
<com.google.android.material.textfield.TextInputLayout
    android:id="@+id/cityExposedDropDownMenu"
    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginHorizontal="16dp"
    android:layout_marginTop="4dp"
    android:enabled="@{viewModel.isCityTextFieldEnabled}"
    android:hint="@{viewModel.cityTextFieldLabel}"
    app:layout_constraintTop_toBottomOf="@id/countryExposedDropDownMenu"
    tools:hint="City"
    >

    <com.google.android.material.textfield.MaterialAutoCompleteTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="@{viewModel.cityTextFieldText}"
        android:textColor="?textColorHighEmphasis"
        />

</com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** `32`

**Material Library version:** `1.7.0`

**Device:** Google Pixel 1, several Android Emulators

**Comment by hunterstich** [comment]
Hi @MrTheGood,

Thanks for filing an issue.

I can't reproduce this in our catalog. Would you be able to upload a sample that reproduces the issue?

**Comment by MrTheGood** [comment]
@hunterstich 

Thanks for your quick response!

I was able to narrow it down to the usage of `android:backgroundTint="@color/transparent"` in the `MaterialAutoCompleteTextView`. 
This is used in our app so to not overlap some background image. [I have created a sample here as per request](https://github.com/MrTheGood/issue2041)

**Comment by hunterstich** [comment]
Ah, interesting. Thanks for the sample! 

I'll look into this.

**Comment by bczhc** [comment]
I experienced the same issue, and found it may be related to `android:gravity` on `TIL`. Here's the layout:
```xml
<?xml version="1.0" encoding="utf-8"?>
<com.google.android.material.textfield.TextInputLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center_vertical"
>
    <com.google.android.material.textfield.TextInputEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="Hint Text"
    />
</com.google.android.material.textfield.TextInputLayout>
```
![image](https://user-images.githubusercontent.com/49330580/207835484-6afce79e-49cf-4b44-8566-00302936d3cd.png)

After removing the line `android:gravity="center_vertical"`, it gets okay:
![image](https://user-images.githubusercontent.com/49330580/207836016-ba97adbf-8c8f-49c5-901a-36ec017680e7.png)

Library version: 1.8.0-beta01. But with version 1.5.0-alpha04, this issue won't happen.

**Comment by drchen** [comment]
@bczhc I cannot reproduce the issue you mentioned. I think it's different from the original one which I can reproduce easily. If this is still happening can you create a separate issue?

**Comment by bczhc** [comment]
@drchen OK I will. I just tried and this is also reproducible with material library 1.8.0 and 1.9.0-alpha01. I began to put this here because at least the issue fact (hint is overlapped by outline) is the same.
