### ISSUE TITLE
[MaterialDatePicker] INPUT_MODE_TEXT - the text 11/11/41 returns the year 1941 but 11/11/42 returns the year 2042

### ISSUE THREAD

**Issue by nachtien** [material-components/material-components-android#3044]
**Description:** Full description of issue here

I am reproducing this in the catalog app on master (df9fdaf77 or tag 1.8.0-alpha02). If #3042 is resolved, it could close this issue if users are forced to enter in mm/dd/yyyy.

Entering in 11/11/**41** renders the date at Nov 11, **2041**
Entering in 11/11/**42** renders the date as Nov 11, **1942**

Best described via video

![Kapture 2022-10-24 at 14 03 58](https://user-images.githubusercontent.com/116726/197605391-ae93c4e6-bb3e-41e8-9a8a-26f123ff9dc8.gif)

**Expected behavior:** 
In our case, we are entering in users' birthdays so we would prefer it to be 1941.  

**Android API version:** All versions

**Material Library version:** This occurs on 1.7.0

**Device:** Emulator - API 33

**Comment by nachtien** [comment]
This appears to be fixed in master.

**Comment by nachtien** [comment]
I incorrectly marked this as closed. This is reproducible in master. Make sure you enter in 11/11/41 and 11/11/42

**Comment by hunterstich** [comment]
Hey @nachtien,

I think closing this is the right move. From Java's SimpleDateFormat documentation:

> For parsing with the abbreviated year pattern ("y" or "yy"), SimpleDateFormat must interpret the abbreviated year relative to some century. It does this by adjusting dates to be within 80 years before and 20 years after the time the SimpleDateFormat instance is created.


It makes sense that `42` would be converted to `2042`. If this is a problem for your use case, it looks like you could use the new `MaterialDatePicker.setTextInputFormat` from https://github.com/material-components/material-components-android/commit/276c1171b08ac3d9f6a188f4bb90345a0d5b5a17 and pass in either a `SimpleDateFormat` with `yyyy` or create a `SimpleDateFormat` and call [set2DigitYearStart](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#set2DigitYearStart%28java.util.Date%29)
