### ISSUE TITLE
PopupMenu & ListPopupWindow not following MaterialTheme coloring

### ISSUE THREAD

**Issue by pavlospt** [material-components/material-components-android#305]
### Issue
I am trying to style a `ListPopupWindow` with MaterialComponents coloring, but it seems that it does not respect the `colorSurface` attribute which is the one used as the solid color of the custom drawable referenced from the MaterialTheme for PopupMenu. 

### Possible workaround
If I use `android:popupBackground` it works properly but I am reluctant on duplicating the drawable from MaterialTheme just to workaround that.

### Relevant issues
I could not find any relevant issues.

### Material Design Library
Version: `1.1.0-alpha04`

**Comment by cketcham** [comment]
tracking here: http://issuetracker.google.com/issues/128813889
