### ISSUE TITLE
[Date Picker] ContentDescription for "DayName" is not properly getting read by talkback for the german language

### ISSUE THREAD

**Issue by kavitamp** [material-components/material-components-android#3050]
**Description:** The content description(Talkback) for the "day-name" is not properly getting read in the German language for the date picker dialog, for English, it is working fine but not for the German language.
For example: Sometimes dates are getting read as:
- **Mi, Zweite November** instead of **Mittwoch, zweite November**
- **Du, drei, N.O.V.** instead of **Donnerstag, dritte November**
- **Frau, vier, N.O.V** instead of **Freitag, vierte November**
- **S.A, fünf, N.O.V** instead of **Samstag, fünfte November**
- **So. sechs, N.O.V** instead of **Sonntag. sechste November**
- **Mo, sieben, N.O.V** instead of **Montag, siebte November**

**Bug screen recording:**

https://user-images.githubusercontent.com/20037228/197534185-acb6188b-dd01-4e8a-83e9-a3f7fdd2e9f0.mp4

**Expected behavior:**
Dates should be getting read as:
- **Mittwoch, zweite November**
- **Donnerstag, dritte November**
- **Freitag, vierte November**
- **Samstag, fünfte November**
- *Sonntag. sechste November**
- **Montag, siebte November**

**Source code:**

```@TargetApi(VERSION_CODES.N)
  static android.icu.text.DateFormat getAbbrMonthWeekdayDayFormat(Locale locale) {
    return getAndroidFormat(android.icu.text.DateFormat.ABBR_MONTH_WEEKDAY_DAY, locale);
  }
```
And

```@TargetApi(VERSION_CODES.N)
  static android.icu.text.DateFormat getYearAbbrMonthWeekdayDayFormat(Locale locale) {
    return getAndroidFormat(android.icu.text.DateFormat.YEAR_ABBR_MONTH_WEEKDAY_DAY, locale);
  }
```

**Minimal sample app repro:**
https://github.com/kavitamp/material-components-android

**Android API version:** Android 12, API 31

**Material Library version:** 1.8.0-alpha02

**Device:** OnePlus, Pixel

**Comment by paulfthomas** [comment]
Fixed https://github.com/material-components/material-components-android/commit/35bd1fc98ffd449d11400ae040c3b43a24dea43b
