### ISSUE TITLE
CalendarConstraints return milliseconds from getter is different from the provided at its setter

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#3052]
**Description:** getStartMs, getEndMs, and getOpenAtMs is different from what is provided to CalendarConstraints Builder setters.

**Expected behavior:** 
Getter milliseconds should be the same as the one that is provided using its setter.

**Source code:** 

```
val currentDate = MaterialDatePicker.todayInUtcMilliseconds()

        val oldestDate: Long
        val previousMonth: Long

        TimeZone.getTimeZone(ZoneId.systemDefault()).also {

            Calendar.getInstance(it).let { cal ->
                cal.timeInMillis = currentDate // Set calendar date today
                cal.add(Calendar.MONTH, -1) // Set month to previous
                previousMonth = cal.timeInMillis
            }

            Calendar.getInstance(it).let { cal ->
                cal.timeInMillis = currentDate // Set calendar date today
                // Get current year
                val year = cal[Calendar.YEAR]
                cal.add(Calendar.YEAR, 2009 - year) // Set oldest supported year
                oldestDate = cal.timeInMillis
            }

        }

        val fromConstraints =
            CalendarConstraints.Builder()
                .setStart(oldestDate)
                .setEnd(currentDate)
                .setOpenAt(previousMonth)
                .setValidator(DateValidatorPointBackward.now()) // Disable days beyond current date
                .build()

        Log.wtf("OLDEST", oldestDate.toString())
        Log.wtf("CURRENT", currentDate.toString())
        Log.wtf("OPEN AT", previousMonth.toString())

        Log.wtf("CONSTRAINT OLDEST", fromConstraints.startMs.toString())
        Log.wtf("CONSTRAINT CURRENT", fromConstraints.endMs.toString())
        Log.wtf("CONSTRAINT OPEN AT", fromConstraints.openAtMs.toString())

```
![image](https://user-images.githubusercontent.com/38008900/197623297-96bdd379-e17e-4564-b15b-e8636676104c.png)

**Android API version:** Any

**Material Library version:** 1.8.0-alpha02

**Device:** Any

**Comment by ArcherEmiya05** [comment]
Hello, any update on this?

**Comment by paulfthomas** [comment]
Hi, as described in the [documentation](https://developer.android.com/reference/com/google/android/material/datepicker/MaterialDatePicker.Builder#setCalendarConstraints(com.google.android.material.datepicker.CalendarConstraints)), `CalendarConstraints` allow to set the first, last, and starting month. The getters will return the UTC timestamp of the first day of the selected months. You can see that with the timestamps you shared.

**Comment by ArcherEmiya05** [comment]
> Hi, as described in the [documentation](https://developer.android.com/reference/com/google/android/material/datepicker/MaterialDatePicker.Builder#setCalendarConstraints(com.google.android.material.datepicker.CalendarConstraints)), `CalendarConstraints` allow to set the first, last, and starting month. The getters will return the UTC timestamp of the first day of the selected months. You can see that with the timestamps you shared.

So we only need to adjust the zone right?

**Comment by ArcherEmiya05** [comment]
Hello, just want to know what exactly we need to perform to get the timestamp of getters similar to what was passed to setter? Thanks

**Comment by ArcherEmiya05** [comment]
> Hi, as described in the [documentation](https://developer.android.com/reference/com/google/android/material/datepicker/MaterialDatePicker.Builder#setCalendarConstraints(com.google.android.material.datepicker.CalendarConstraints)), `CalendarConstraints` allow to set the first, last, and starting month. The getters will return the UTC timestamp of the first day of the selected months. You can see that with the timestamps you shared.

I just realized that you mistakenly close this without fully understanding the issue. The getters was recently added from this [issue ]([url](https://github.com/material-components/material-components-android/issues/2907))that I reported before. Now this new getters are not included in any documentation yet from the link that you sent. Please reopen this issue. Thanks

**Comment by ArcherEmiya05** [comment]
Will file a new one since there is not enough detail and clarification for this one. Thanks
