### ISSUE TITLE
Slider value label is out of sync with Slider when labelBehavior=visible

### ISSUE THREAD

**Issue by abed-roid** [material-components/material-components-android#3057]
I deliberately extended the bottom padding to replicate the bug and mimic the slider's behavior when it's in a long scrollview and a scroll to the bottom happens, the slider is out of sync with the value label as shown below:

![Screenshot_20221101_205105 - Copy](https://user-images.githubusercontent.com/82813615/199314750-f58d89d2-3648-4ccc-9ecd-dbd73a2d4ae2.png)

Also, the value label overlaps other views:
![Screenshot_20221101_205513](https://user-images.githubusercontent.com/82813615/199315275-365a06ee-de37-4411-837e-251011b5e2e7.png)

_Originally posted by @abed-roid in https://github.com/material-components/material-components-android/issues/3055#issuecomment-1298969948_

Sample repository: https://github.com/abed-roid/Slider-Sample

**Comment by drchen** [comment]
I'm not sure if there's an easy fix on our end. : (

Slider labels are drawn in a view overlay, which just won't be scrolled with the view (because it's a separate layer...)

**Comment by abed-roid** [comment]
I hope there will be a fix to this, the slider's label would be unusable in most use cases otherwise...

**Comment by drchen** [comment]
It seems like we have a PR to fix this: https://github.com/material-components/material-components-android/pull/3027

Haven't taken a close look to it yet. Will do very soon. 
Also let me close this issue as a duplicate to #2869
