### ISSUE TITLE
When using AnimatorListenerAdapter to listen to ObjectAnimator, it will fail on Android 6.0 machines.

### ISSUE THREAD

**Issue by a1782680475** [material-components/material-components-android#3059]
**Description:** Full description of issue here
When using AnimatorListenerAdapter to listen to ObjectAnimator, it will fail on Android 6.0 machines.I will not be able to listen to animation events.When I change to Animator.AnimatorListener, it will work normally.When I use Animator AnimatorListener works normally on my galaxy note 10+.
**Source code:** The code snippet which is causing this issue
`private fun playFadeOutAnimation(view: View, callback: () -> Unit) {
        val fadeOutAnimator = ObjectAnimator.ofFloat(view, View.ALPHA, 1f, 0.3f).apply {
            duration = 300
            interpolator = AccelerateInterpolator()
        }
        fadeOutAnimator.start()
        
        fadeOutAnimator.addListener(object : AnimatorListenerAdapter() {
            override fun onAnimationEnd(animation: Animator, isReverse: Boolean) {
                callback()
            }
        })
    }`
**Android API version:** Android API version here
31
**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.8.0-alpha02
**Device:** Device on which the bug was encountered here
galaxy note 7（android 6.0）

**Comment by imhappi** [comment]
This is the incorrect place to file this bug, this is the material components library. Please file the bug in the appropriate avenues
