### ISSUE TITLE
[FloatingActionButton] `fabSize="mini"` is not applied

### ISSUE THREAD

**Issue by stefan-niedermann** [material-components/material-components-android#3060]
**Description:** When using a `FloatingActionButton` the property `fabSize="mini"` is not always applied since version `1.7.0` (also tested `1.8.0-alpha02`). It worked on `1.6.x`. This seems to be independent of the parent view type (tested with `LinearLayout` and `CoordinatorLayout`.

**Expected behavior:**

## `1.6.0`
![image](https://user-images.githubusercontent.com/4741199/199748733-6d8ce780-58ec-4a3f-b13c-147e8d593e7a.png)

## `1.7.0`
![image](https://user-images.githubusercontent.com/4741199/199748861-c4f548eb-0e98-49e7-8a45-04fc34e839f6.png)

**Source code:** The code snippet which is causing this issue

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/miniFabStart"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:fabSize="mini" />

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/normalFab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/miniFabEnd"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:fabSize="mini" />
</LinearLayout>
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

https://github.com/stefan-niedermann/nextcloud-deck/tree/material-bug

See `activity_take_photo.xml`

If you need help for building and / or running please feel free to contact me. The app requires a running Nextcloud instance with enabled Deck app as well as the Nextcloud Androd app to be installed on the smartphone. The setup is a bit tricky. But it is also visible in the Android Studio dev tools, so I guess no need to actually build the app.

**Android API version:** Confirmed with API level 31

**Material Library version:** `1.7.0`, `1.8.0-alpha02`

**Device:** Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by pekingme** [comment]
`fabSize` has been deprecated in M3 FAB. Instead, you can use the "Small" sized style. Please refer to this [section](https://github.com/material-components/material-components-android/blob/master/docs/components/FloatingActionButton.md#sizing-fabs) for the migration.
