### ISSUE TITLE
[Range Slider] IllegalStateException: The stepSize(500.0) must be 0, or a factor of the valueFrom(20.0)-valueTo(10990.0) range

### ISSUE THREAD

**Issue by idrisov01** [material-components/material-components-android#3063]
The failure occurs if the maximum and minimum values are set, which are not divisible by the step value without remainder.
My application receives the minimum and maximum values from the server, and the step value is sewn into the application and is always 500

No crash 
<img width="281" alt="image" src="https://user-images.githubusercontent.com/49280461/199977282-714709c7-0a47-4c90-8c81-565a6848dcf2.png">

There is a crash

<img width="317" alt="image" src="https://user-images.githubusercontent.com/49280461/199977916-637edbc4-da5a-4563-b7bd-a1eb6a52a26c.png">
<img width="261" alt="image" src="https://user-images.githubusercontent.com/49280461/199978057-906a5c74-dac1-40eb-84dc-83f4251a9f95.png">

Expected implementation:

For the minimum value -If a minimum value comes that is less than the step value, then the first one is calculated using the formula `step - the minimum value`

For the maximum value - the first step is reduced to the first value, which is divided by the step value without remainder

Android API version 31

Material Android Library version 1.7.0

Does not depend on the device

**Comment by drchen** [comment]
I think https://github.com/material-components/material-components-android/issues/3082 is a more general request regarding this. Let's move the discussion there.
