### ISSUE TITLE
[MaterialAutoCompleteTextView] setText() clears dropdown list items (1.8.0-alpha02)

### ISSUE THREAD

**Issue by noirtier-villefort** [material-components/material-components-android#3066]
**Description:** MaterialAutoCompleteTextView setText() clears his items in dropdown list and show only given value to that setText().
**Expected behavior:** setting text without clear dropdown list items.
 I use setText() because MaterialAutoCompleteTextView has different setSelection() method logic then android.widget.Spinner and i dont know how to set item from dropdown list programmatically. 

**Android API version:** 30
**Material Library version:** 1.8.0-alpha02
**Device:** Pixel 4a API 30 (Emulator)

**Source code:** 
```
autocompletetextview = view.findViewById(R.id.autocompletetextview);
autocompletetextview.setSimpleItems(R.array.languages);
autocompletetextview.setText(autocompletetextview.getAdapter().getItem(3).toString());
```

_Now as fast fix i use setSimpleItems() after every setText() call, but i dont think that best way_

**Comment by leticiarossi** [comment]
Hi, if you can use `setText(CharSequence text, boolean filter)` instead: `autocompletetextview.setText(autocompletetextview.getAdapter().getItem(3).toString(), /* filter= */ false)` and that should prevent the filtering from happening

**Comment by noirtier-villefort** [comment]
> Hi, you can use `setText(CharSequence text, boolean filter)` instead: `autocompletetextview.setText(autocompletetextview.getAdapter().getItem(3).toString(), /* filter= */ false)` and that should prevent the filtering from happening

nothing changed :(
