### ISSUE TITLE
[TabLayout] Tab indicator gets stuck in an intermediate position

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3069]
[The fix](https://github.com/material-components/material-components-android/commit/f9a37c5077feaa6e00607adf0005671d0efd390b) brought a new problem:
- Open `TabsControllableDemoFragment`
- Double-click on an unselected tab

<video src="https://user-images.githubusercontent.com/82187521/200586111-924bee37-818b-44e3-a753-405506cd0bc0.mp4" />

**Comment by imhappi** [comment]
Hi! I took a look, I think the bug existed before that fix. It looks like double tapping the tab always cancelled the indicator animation. A quick fix will be out for this shortly :)
