### ISSUE TITLE
FloatingActionButton styling not working

### ISSUE THREAD

**Issue by fonix232** [material-components/material-components-android#307]
Ever since the first 1.1.0 alpha, my customized FABs have decided to not follow the styling - specifically the `android:tint` (for foreground/icon tinting) and `android:backgroundTint` properties. However I could not find an open ticket about it.

**Comment by ryzhovl** [comment]
Try using `xmlns:app` namespace for both properties.

**Comment by cketcham** [comment]
Can you please file a bug at https://issuetracker.google.com/issues/new?component=439535 and include any code required to reproduce the issue.
