### ISSUE TITLE
Splashscreen displays very large on devices lower than Android 12. And on individual models, the mask appears as a rectangle.

### ISSUE THREAD

**Issue by a1782680475** [material-components/material-components-android#3072]
**Description:** Full description of issue here
Splashscreen displays very large on devices lower than Android 12. And on individual models, the mask appears as a rectangle.
**Expected behavior:** Screenshots and/or description of expected behavior
![Screenshot_20221109-131028](https://user-images.githubusercontent.com/32875468/200744278-efa5b265-0157-4cc0-8c9f-82aafa32d33f.jpg)
![Screenshot_20221109-130821](https://user-images.githubusercontent.com/32875468/200744294-5626251c-ff8e-4b8b-9d96-789c81048a94.png)
![Screenshot_2022-11-09-10-59-32-106_com xktech ixueto](https://user-images.githubusercontent.com/32875468/200744311-4771286e-08d1-418a-89a6-54cccc0239ef.jpg)

**Android API version:** Android API version here
33
**Material Library version:** Material Android Library version you are using here 
1.8.0-alpha02
**Device:** Device on which the bug was encountered here
galaxy note 10+ (android 12)
galaxy note 7 (android 6.0)
redmi k40 (android 11)

**Comment by a1782680475** [comment]
Sorry, but I don't know where to submit the bug of Splashscreen API.

**Comment by imhappi** [comment]
https://issuetracker.google.com/hotlists/3373391

**Comment by a1782680475** [comment]
> https://issuetracker.google.com/hotlists/3373391

thank u.
