### ISSUE TITLE
[MaterialCalendar] dayTodayStyle not applied

### ISSUE THREAD

**Issue by danielstr** [material-components/material-components-android#3073]
**Description:** I am trying to remove today's date style (non-filled circle) modifying dayTodayStyle style

**Expected behavior:** After modifying the styles like itemStrokeWidth, itemStrokeColor or itemTextColor I expect to see this changes reflected in the datePicker but these changes are ignored
![Screenshot_20221109_174841](https://user-images.githubusercontent.com/13631149/200938810-79a20f11-9b2c-48e0-99af-95e99dbc9ef3.png)

**Source code:** 

    <style name="DayTodayStyle" parent="Widget.Material3.MaterialCalendar.Day.Today">
        <item name="itemTextColor">@color/black_100</item>
        <item name="itemStrokeColor">@color/black_100</item>
        <item name="itemStrokeWidth">0dp</item>
    </style>

    <style name="ThemeOverlay.Pebblebee.MaterialCalendar" parent="ThemeOverlay.Material3.MaterialCalendar">
        <item name="materialCalendarHeaderTitle">@style/DateTextAppearance</item>
        <item name="materialCalendarHeaderToggleButton">@style/HeaderToggleButton</item>
        <item name="buttonBarPositiveButtonStyle">@style/MaterialCalendar.Button</item>
        <item name="buttonBarNegativeButtonStyle">@style/MaterialCalendar.Button</item>
        <item name="dayTodayStyle">@style/DayTodayStyle</item>
    </style>

**Android API version:** tested it on android API 32 and 30

**Material Library version:** 1.7.0

**Device:** Tested on a xiaomi pocophone m3 pro 5g

**Comment by drchen** [comment]
I think you need to extend Widget.Material3.MaterialCalendar and override ?attr/materialCalendarStyle in your theme instead. : )

**Comment by danielstr** [comment]
I apply my style when creating the MaterialDatePicker and It is working fine, except for dayTodayStyle parameter. It is not taking the changes applied for that particular parameter.

If I have some time I will create a repository with an example. It might be helppful

**Comment by drchen** [comment]
Yeah unfortunately `?attr/dayTodayStyle` doesn't work at the same level as other styles you are overriding. 

You will need to do it like this:

```
<style name="DayTodayStyle" parent="Widget.Material3.MaterialCalendar.Day.Today">
    <item name="itemTextColor">@color/black_100</item>
    <item name="itemStrokeColor">@color/black_100</item>
    <item name="itemStrokeWidth">0dp</item>
</style>

<style name= "CalendarStyle" parent="Widget.Material3.MaterialCalendar">
    <item name="dayTodayStyle">@style/DayTodayStyle</item>
</style>

<style name="ThemeOverlay.Pebblebee.MaterialCalendar" parent="ThemeOverlay.Material3.MaterialCalendar">
    <item name="materialCalendarHeaderTitle">@style/DateTextAppearance</item>
    <item name="materialCalendarHeaderToggleButton">@style/HeaderToggleButton</item>
    <item name="buttonBarPositiveButtonStyle">@style/MaterialCalendar.Button</item>
    <item name="buttonBarNegativeButtonStyle">@style/MaterialCalendar.Button</item>
    <item name="materialCalendarStyle">@style/CalendarStyle</item>
</style>
```
