### ISSUE TITLE
Trying to build existing .swb to sw rc05 then material-1.6.1 error: invalid file

### ISSUE THREAD

**Issue by jeremyaltares** [material-components/material-components-android#3076]
![Screenshot_2022-11-11-08-13-15-69_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/73113951/201232520-3ae8cccf-7ed8-4233-8f10-0b307f4a7448.jpg)
![Screenshot_2022-11-11-08-13-18-99_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/73113951/201232529-0a3c1a69-9b97-434f-97f3-52c2989db859.jpg)
**Description:** Full description of issue here

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The code snippet which is causing this issue

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** Android API version here

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

**Device:** Device on which the bug was encountered here

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Can you provide more info here? Like what's your building environment and how did you get the zip file?

**Comment by leticiarossi** [comment]
Closing this due to no further info available. Please feel free to reopen with more info it if this is still happening.
