### ISSUE TITLE
[Sample] Request: publish sample on the Play Store, and keep it up-to-date with each release

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#3078]
**Is your feature request related to a problem? Please describe.**
Feature request, kinda.

**Describe the solution you'd like**
This can be useful to distribute how things are done on Android, and let it be visible to people who are not directly in the development team, meaning project manager, UI/UX designer, etc...

It could be nice to also mark what's new, or have a list of recent updates, or a link to the "what's new" section here on Github.

**Describe alternatives you've considered**
Currently I need to prepare the APK myself, and send them. 

**Additional context**
Ummmm... This is a link to the Play Store:
https://play.google.com/store/apps
:)

**Comment by cyb3rko** [comment]
At least you don't have to "prepare" the apk by yourself, you can find the latest M3 catalog apk in every release.

**Comment by drchen** [comment]
I don't think we have a plan to publish Catalog to Playstore. 

As @cyb3rko said, it's easy to download the apk from the release link:
https://github.com/material-components/material-components-android/releases
And install it yourself. : )

**Comment by AndroidDeveloperLB** [comment]
@drchen Too bad. Anyway thank you for at least considering.
