### ISSUE TITLE
[Checkbox] Uncheck transition doesn't match M3 specs

### ISSUE THREAD

**Issue by Ejimax** [material-components/material-components-android#3080]
**Description:** The border color of the button doesn't change until the end of the uncheck animation

https://user-images.githubusercontent.com/30945217/201575242-24bbda85-3c49-4d08-a6cd-a7b8d56cb1a2.mp4

M3 specs:

https://user-images.githubusercontent.com/30945217/201575319-9868a8c0-c682-45ff-b052-c33026f68d7f.mp4

**Expected behavior:** The border color of the button changes as soon as it is unchecked

https://user-images.githubusercontent.com/30945217/201575286-1f4233f4-0c4b-484d-ac85-e8d79ea1bdfe.mp4

**Android API version:** API level 33

**Material Library version:** 1.7.0

**Comment by drchen** [comment]
I'm not sure if it's a spec issue or an implementation issue. 

Leticia can you help confirm that?

**Comment by leticiarossi** [comment]
It looks like the videos on https://m3.material.io/ are different from the checkbox specs. will close this as WAI and report internally

**Comment by Ejimax** [comment]
Could you please check this again?
The videos in the guidelines don't seem to be fixed.

I agree that the current implementation follows the specs, but the unchecking transition where the border color changes after the delay looks strange to me. I'm using my own class with this lingering border color disabled and it's working as per the guidelines.
