### ISSUE TITLE
[DrawerLayout] Screen flickers when closed DraverLayout

### ISSUE THREAD

**Issue by TAlkogolik** [material-components/material-components-android#3081]
**Description:** Followed the guide material 3, did not change anything in the code. When changing the fragment, when you click on the menu item NavigationView, the screen flickers (blinking), that is, the screen becomes darker for a moment. Checked using OnNavigationItemSelectedListener, when calling DrawerLayout.close() this flicker occurs. How to fix it?

**Expected behavior:** Attached a video with a sample of undesirable behavior

**Android API version:** 29

**Material Library version:** Material Android Library version 1.8.0-alpha02

https://user-images.githubusercontent.com/66673992/201576139-a81e6118-3318-4ca2-9826-9d862e7babcc.mp4

**Comment by TAlkogolik** [comment]
I believe that this is due to the fact that the fragments are changed faster than completely closing the DriverLight. When trying to fix this setNavigationItemSelectedListener , there was a huge delay between closing the DriverLight and changing the fragment

**Comment by drchen** [comment]
Can you provide how you implement your OnNavigationItemSelectedListener?

Do you try to close the drawer there?

**Comment by TAlkogolik** [comment]
> Можете ли вы предоставить, как вы реализуете свой OnNavigationItemSelectedListener?
> 
> Вы пытаетесь закрыть ящик там?

Initially, I did not use OnNavigationItemSelectedListener and used the standard navigation listener. When I noticed this error, I tried to first call DriverLyout.close() and then call the navigation in the NavController, but this also did not help

**Comment by TAlkogolik** [comment]
> Можете ли вы предоставить, как вы реализуете свой OnNavigationItemSelectedListener?
> 
> Вы пытаетесь закрыть ящик там?

For now, I've reverted back to the default implementation

`setSupportActionBar(binding.appBarMain.appToolbar)
        val drawerLayout: DrawerLayout = binding.appDrawerLayout
        val navView: NavigationView = binding.appNavView
        val navController = findNavController(R.id.app_nav_fragment)
        appBarConfiguration = AppBarConfiguration(
            setOf(
                R.id.nav_home
            ), drawerLayout
        )
        setupActionBarWithNavController(navController, appBarConfiguration)
        navView.setupWithNavController(navController)`

**Comment by TAlkogolik** [comment]
Looks like I solved the problem, DriverLayout has a public void closeDrawer(@EdgeGravity int gravity, boolean animate) method. With it, you can turn off the closing animation and the blinking will disappear
