### ISSUE TITLE
[TabLayout] Tab indicator bitmap drawable with tileModeX="repeat" cannot be aligned to bottom of a tab

### ISSUE THREAD

**Issue by pvokilam** [material-components/material-components-android#3083]
**Description:** 
I use custom tab indicator with a complex shape

**drawable/waves.png**
![waves](https://user-images.githubusercontent.com/106242514/201907428-e773974a-7fb1-4972-b31a-e552e2b9e6f2.png)

My idea is to make a repeatable bitmap from this drawable and set it as a tab indicator.

**tab_indicator.xml**
```
<bitmap xmlns:android="http://schemas.android.com/apk/res/android"
    android:src="@drawable/waves"
    android:tileModeX="repeat"
    android:gravity="bottom"/>
```
Tab layout setup is as follows
```
<com.google.android.material.tabs.TabLayout
    android:id="@+id/tabs"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:tabIndicator="@drawable/tab_indicator"
    app:tabIndicatorGravity="stretch"
    app:tabIndicatorFullWidth="false"/>
```

Resulting behavior: tab indicator is always on top. `gravity` attr of bitmap drawable is ignored.
![expected](https://user-images.githubusercontent.com/106242514/201907788-426f6f28-ef87-42d3-b290-cb34b848091d.gif)

I also tried with no luck
- Place a bitmap drawable inside a layer list and set gravity or top offset to an `item`
- Make a 9-patch with stretching area above the wave

**Expected behavior:** 
Expected animation is like on a screenshot above. The wave itself should be at the bottom.

**Minimal sample app repro:** 
[testtabindicator.zip](https://github.com/material-components/material-components-android/files/10012217/testtabindicator.zip)

**Android API version:** n/a

**Material Library version:** 1.7.0, 1.8.0-alpha02

**Device:** Pixel 4a (5G)

**Comment by drchen** [comment]
I think you should set `app:tabIndicatorGravity` to `bottom`?

**Comment by pvokilam** [comment]
When I set `app:tabIndicatorGravity` to `bottom` and `android:tileModeX="repeat"` for my bitmap drawable, indicator is not shown. When I remove tile mode, indicator slides which is not a desired behavior. That is why I set `app:tabIndicatorGravity` to `stretch`.

![actual](https://user-images.githubusercontent.com/106242514/202534917-e579fdc6-b91f-46c3-a100-c4db511e3a1a.gif)

**Comment by pvokilam** [comment]
Yes, like this

```
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:gravity="bottom">
        <bitmap
            android:src="@drawable/waves"
            android:tileModeX="repeat"
            />
    </item>
</layer-list>
```

With `android:gravity="bottom"` indicator is not shown. Without gravity it is at top. Without `android:tileModeX="repeat"` it is at bottom.

**Comment by drchen** [comment]
Hmm...  interesting.... seems like a bug of `android:tileModeX` but I'm not sure. 

Can you do more experiments with layer-list parameters? Like if we set `android:bottom` instead of `android:gravity` on `<item>`, will that work? Sorry we don't have extra resources at the moment to dig into this, as it seems like beyond the Material library's control.

**Comment by pvokilam** [comment]
| setup | screenshot |
|-------|------------|
| android:bottom="20dp"| <img width="368" alt="bottom20dp" src="https://user-images.githubusercontent.com/106242514/202579218-be92ce0b-7f91-4681-a24e-a5a2e767f35c.png"> |
| android:bottom="20dp", android:tileModeX="disabled"| <img width="374" alt="bottom20dptilexdisabled" src="https://user-images.githubusercontent.com/106242514/202579790-60833618-c056-4d36-b415-0d76b00ae5af.png">|
| android:top="4dp" | <img width="372" alt="top4dp" src="https://user-images.githubusercontent.com/106242514/202579476-553b64cf-432d-4414-a4d8-13193bc947c5.png">|

`app:tabIndicatorGravity="stretch"` is for all experiments
