### ISSUE TITLE
Docs or example regarding custom colors for TextInputLayout

### ISSUE THREAD

**Issue by Gelassen** [material-components/material-components-android#3087]
Hello dev team,

Thank you for all your work on this library. I have a question regarding custom colors which is not obvious to implement due rapid change in library versions. 

What I need to do is customize colors of text selection cursors from left and right like on this picture: 

![image](https://user-images.githubusercontent.com/426382/202396657-f2ad84c2-fbb9-4e68-81e6-5c25f0e53af5.png)

Also I need a custom color for label (or hint?) in both modes: when user input text into the field and when it stops enter the text. 

![image](https://user-images.githubusercontent.com/426382/202397016-0f1dfa86-5c10-4b63-a6fc-8be70bfc14dc.png)
("Enter something" text in the first EditText)

Customisation of colors is not covered well on docs&samples of this library. If it is not correct, please share link to the right place where this issue is covered. 
Help from the community is not helpful too as there are many places where devs points on different versions of ```EditText``` and ```TextInputEditText``` which doesn't give enough information about issue with current evolution of InputField. 

My current code is below: 

```
        <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/toTranslateEditTextContainer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="@string/to_translate_field">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/toTranslateEditText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/base_margin"
                android:layout_marginTop="@dimen/base_margin"
                android:layout_marginEnd="@dimen/base_margin"
                android:backgroundTint="@color/white"
                android:nextFocusRight="@+id/translateEditText"
                android:singleLine="true"
                android:textCursorDrawable="@drawable/bg_edit_text_cursor"
                android:text="@={model.wordToTranslate}"
                />

        </com.google.android.material.textfield.TextInputLayout>
```
```
    <!-- Base application theme. -->
    <style name="Theme.WordInMemory" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
        <!-- Primary brand color. -->
        <item name="colorPrimary">@color/blue_light</item>
        <item name="colorPrimaryVariant">@color/blue_dark</item>
        <item name="colorOnPrimary">@color/white</item>
        <item name="colorAccent">@color/blue_light</item>
        <!-- Secondary brand color. -->
        <item name="colorSecondary">#ffffff</item>
        <item name="colorSecondaryVariant">@color/blue_dark</item>
        <item name="colorOnSecondary">@color/black</item>
        <!-- Status bar color. -->
        <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
        <!-- Customize your theme here. -->
        <item name="colorOnSurface">@color/blue_light</item>

        <item name="hintTextColor">@color/blue_light</item>

    </style>
```
```
implementation("com.google.android.material:material:1.7.0")
```

**Comment by drchen** [comment]
Leticia, can you help with that?

**Comment by leticiarossi** [comment]
Hi there, for the label colors you can find information about the attrs in the [text field doc](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#label-attributes); in the TextInputLayout you can set `android:textColorHint` to change the expanded label color and `app:hintTextColor` to change the collapsed (floating) label color.

For the text selection cursors, we don't set it our styles as we inherit it from AppCompat, so there's no specific info about it on the doc. However, they are drawables set to these edit text attrs: `android:textSelectHandle`, `android:textSelectHandleLeft`, and `android:textSelectHandleRight` which you can override and customize as needed.

**Comment by Gelassen** [comment]
Thank you for recommendations, unfortunately this changes didn't help. 

I pushed experiments with this material components into a separate branch in case you will be interested to reproduce the issue on your side: https://github.com/Gelassen/words-in-memory/tree/feature/add-new-item-style

It is WIP and therefore a bit messy, but enough to reproduce the issue.

**Comment by leticiarossi** [comment]
for the `android:textSelectHandle*` attrs you'll have to create custom drawables (they are drawable attrs not just color attrs). Forgot to mention that you could also change the value of the theme color attr `colorControlActivated` that [we set here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/values/styles.xml#L487), however that will also change the cursor color.

**Comment by Gelassen** [comment]
Thank you for your help with issue, sadly any of this option didn't help to solve it. Also I might not done something correctly on my side. 

Anyway, I think it would be good to stop invest more efforts in this issue as we all should migrate to Material Components 3 https://developer.android.com/jetpack/androidx/releases/compose-material3 which should bring new changes and possible challenges. 

Thank you.
