### ISSUE TITLE
Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu not showing box

### ISSUE THREAD

**Issue by manumathew17** [material-components/material-components-android#3088]
**Description:** recently updated to com.google.android.material:material:1.7.0

**Expected behavior:** It should show the border to the exposed dropdown 

`<com.google.android.material.textfield.TextInputLayout
                    android:id="@+id/dropdown_criteria"
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:boxStrokeWidth="2dp"
                    app:boxStrokeColor="@color/textBlack"
                    android:clickable="true"
                    android:focusable="true"
                    android:hint="Select criteria">
                    <AutoCompleteTextView
                        android:id="@+id/autotxt_criteria"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:background="@color/white"
                        android:enabled="false"
                        android:inputType="none"
                        android:textColor="@color/textBlack" />
                </com.google.android.material.textfield.TextInputLayout>`

This was working fine in the previous version of  material library without,  app:boxStrokeColor="@color/textBlack"  app:boxStrokeWidth="2dp

**Comment by drchen** [comment]
Is this reproducible with Material3 styles?

**Comment by manumathew17** [comment]
Sharing the style
`<style name="MaterialTheme" parent="Theme.Material3.DayNight.NoActionBar">
        <item name="colorPrimary">#1C9D45</item>
        <item name="colorPrimaryVariant">#1C8741</item>
        <item name="android:colorPrimaryDark">#1C8741</item>
        <item name="colorOnPrimary">#FFFFFF</item>
        <item name="colorSecondary">#1C9D45</item>
        <item name="colorSecondaryVariant">#1C8741</item>
        <item name="colorOnSecondary">#0E0E0E</item>
        <item name="colorError">#F44336</item>
        <item name="colorOnError">#FFFFFF</item>
        <item name="colorSurface">#191919</item>
        <item name="colorOnSurface">#212121</item>
        <item name="android:colorBackground">#FAFAFA</item>
        <item name="colorOnBackground">#000000</item>
        <item name="colorControlHighlight">@color/rippleColor</item>
        <item name="chipStyle">@style/ThinnerChip</item>
        <item name="fontFamily">@font/karla</item>
        <item name="android:datePickerDialogTheme">@style/ThemeOverlay.App.DatePicker</item>
        <item name="switchStyle">@style/Widget.App.Switch</item>
        <item name="materialCardViewStyle">@style/cardStyle</item>
        <item name="autoCompleteTextViewStyle">@style/MyAutoCompleteTextView</item>
        <item name="bottomSheetDialogTheme">@style/ModalBottomSheetDialog</item>
        <item name="bottomNavigationStyle">@style/Widget.App.BottomNavigationView</item>
        <item name="selectableItemBackground">@color/rippleColor</item>
</style>`

**Comment by drchen** [comment]
Are you using M3 themes with M2 styles?

Can you change your component style to `style="@style/Widget.Material3.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu` and see if that fixes the issue?
