### ISSUE TITLE
[TextInputLayout] Error icon takes up entire hight of TextInputEditText

### ISSUE THREAD

**Issue by 3efischer** [material-components/material-components-android#3089]
**Description:** I added an TextInputLayout to my fragment which includes a TextInputEditText. The error icon drawable that appears when the textfield doesn't contain any input is for some reason taking up the entire height of the TextInputEditText.

<img src="https://user-images.githubusercontent.com/9017005/202596505-8f33f906-ce90-4694-95da-7708bbec429a.jpeg" width=50% height=50%>

**Expected behavior:** Error icon drawable is centered vertically inside the TextInputEditText as can be seen in the documentation [here](https://m3.material.io/components/text-fields/specs#fbe66c7f-75ea-4f0d-bce0-7b7a36c735eb).

**Source code:** 

```
<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/text_input_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:errorEnabled="true">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/user_input"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_weight="0.7"
                android:inputType="text"
                android:autofillHints="@null" />

        </com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** 33

**Material Library version:** 1.8.0-alpha02

**Device:** Samsung S22

**Comment by drchen** [comment]
I could not reproduce the issue. Does this happen on older Android APIs or the Material library version?

**Comment by 3efischer** [comment]
I did go down to material version 1.6.0, but I'm still getting the same error. I haven't tested it on older Android APIs since my app won't build anymore on older devices, but I do remember that I have seen this behavior before.

**Comment by leticiarossi** [comment]
The text field icons use [CheckableImageButton](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/internal/CheckableImageButton.java#L52) which uses the `imageButtonStyle`. We inherit the style from AppCompat so it's likely that your style was overriding the default dimensions. You should be able to adjust the height in that style as you need
