### ISSUE TITLE
1.1.0-alpha05 misses changes for tab package

### ISSUE THREAD

**Issue by hrach** [material-components/material-components-android#309]
Hi, the new released version 1.1.0-alpha05 misses mentioned changes in release notes/commit-range for tab package:

- Add TabLayoutMediator to MDC tabs library (af15a5f)

I have checked this also in direct-downloaded package from maven.google.com

**Comment by b95505017** [comment]
+1 
Also wondering what release flow makes this issue happened. Is there any commit also being skipped too?

**Comment by wcshi** [comment]
Thanks for reporting the issue. Sorry we had to [rollback](https://github.com/material-components/material-components-android/commit/0ce688ddf2c94c2012efd32621f275320a61d793) the change due to an internal bug, updated the release notes to remove that line.

**Comment by b95505017** [comment]
@wcshi Is there any plan add `TabLayoutMediator` back?

**Comment by wcshi** [comment]
Yes, we plan to bring it back once the internal bug has been fixed. It's currently in progress.

**Comment by vikas0** [comment]
i have using the latest version which is :
com.google.android.material:material:1.3.0-alpha02
and I can't use tablayoutmediator.
Is there any other simple way to implement dot seperator for view pager
