### ISSUE TITLE
[BottomAppBar] Bottom Padding broken

### ISSUE THREAD

**Issue by 1552980358** [material-components/material-components-android#3093]
**Description:** With setting bottom insets as padding to `BottomAppBar`, no any change to BottomAppBar's bottom padding, causing the status bar covering `BottomAppBar`

![image](https://user-images.githubusercontent.com/36123961/203060043-bf5d7d2e-9b37-4435-acf5-47afff02e931.png)

**Expected behavior:** It is expected to be like `BottomNavigationView`, wishing to have edge-to-edge effect with the system navigation bar, which letting the backgroud of the system navigation bar same as `BottomAppBar`'s as overview image at [material.io](material.io), i.e. [https://m3.material.io/components/bottom-app-bar/overview](https://m3.material.io/components/bottom-app-bar/overview). I had tested the value obtained from `setOnApplyWindowInsetsListener` with `BottomNavigationView`, and the padding set worked with it correctly, but not worked with `BottomAppBar`

![image](https://user-images.githubusercontent.com/36123961/203060156-dfe40a31-83ef-4507-a7d8-079e13f3c260.png)

**Source code:** 
```xml
<androidx.coordinatorlayout.widget.CoordinatorLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    ....>
    <!-- Views -->
    <com.google.android.material.bottomappbar.BottomAppBar
        android:id="@+id/bottom_app_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        app:hideOnScroll="true"
        style="@style/Widget.Material3.BottomAppBar" />

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/floating_action_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_round_account_24"
        android:transitionName="@string/account_transition"
        app:layout_anchor="@id/bottom_app_bar"
        tools:ignore="ContentDescription" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

```kotlin
// At Activity onCreate()
WindowCompat.setDecorFitsSystemWindows(window, false)

// At Fragment onViewCreated()
val bottomAppBarPaddingBottom = binding.bottomAppBar.paddingBottom
ViewCompat.setOnApplyWindowInsetsListener(requireActivity().window.decorView) { _, insets ->
    binding.bottomAppBar.updatePadding(
        bottom = bottomAppBarPaddingBottom + insets.getInsets(Type.systemBars()).bottom
    )
    WindowInsetsCompat.CONSUMED
}
```

**Android API version:** API 33 and API 32

**Material Library version:** 1.8.0-alpha02

**Device:** Emulator API 33 and XiaoMi Mi 12 Pro

**Comment by drchen** [comment]
Hi, 

The bottom inset is supposed to be handled by the BottomAppBar automatically.

Can you try if you *don't* consume the inset by yourself, will that work?

**Comment by 1552980358** [comment]
> Hi,
> 
> The bottom inset is supposed to be handled by the BottomAppBar automatically.
> 
> Can you try if you _don't_ consume the inset by yourself, will that work?

I tried, and achieve the expected UI effect in static state, but there is a jitter of the FAB after the completion of container transform. I don't know the cause of the jitter is due to BottomAppBar or the FAB itself, and is there is any solution to this issue?

https://user-images.githubusercontent.com/36123961/203127393-b12e23f5-37c1-4260-a39e-372b5c2b7558.mp4

**Comment by drchen** [comment]
Hmm...  Can you file a separate issue for better tracking? I'll ask someone in our team to take a look. : )

**Comment by 1552980358** [comment]
> Hmm... Can you file a separate issue for better tracking? I'll ask someone in our team to take a look. : )

Sure
