### ISSUE TITLE
[Component name] Short description of issue

### ISSUE THREAD

**Issue by jplauber** [material-components/material-components-android#3094]
**Description:** When using  app:textFormat="password" the password is visible by default since Material Version 1.7.0 and the attribute app:passwordToggleEnabled is ignored. In 1.6.1 everything works as expected

**Expected behavior:** By default password should not be readable. There should be stars covering it

**Source code:** The code snippet which is causing this issue

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 33

**Material Library version:** 1.7.0

**Device:** Samsung Galaxy S21 Ultra

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
I'm not sure what you mean by `app:textFormat="password"`.

I think you are supposed to use `android:inputType="textPassword"` for password input.
