### ISSUE TITLE
[MaterialContainerTransform] Jitter of FloatingActionButton

### ISSUE THREAD

**Issue by 1552980358** [material-components/material-components-android#3097]
**Description:** Jittering of return animation of FloatingActionButton

https://user-images.githubusercontent.com/36123961/203135886-a415a225-0344-4ec8-b74d-f804dc79d0fe.mp4

**Source code:** 
```xml
<!-- FragmentA layout -->
<androidx.coordinatorlayout.widget.CoordinatorLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <!-- views -->
     
    <com.google.android.material.bottomappbar.BottomAppBar
        android:id="@+id/bottom_app_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:fitsSystemWindows="true"
        app:hideOnScroll="true"
        style="@style/Widget.Material3.BottomAppBar" />

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/floating_action_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_round_account_24"
        android:transitionName="transition_name"
        android:fitsSystemWindows="true"
        app:layout_anchor="@id/bottom_app_bar"
        tools:ignore="ContentDescription" />
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

```kotlin
// FragmentA
// onCreated
exitTransition = Hold()

// onViewCreated
floatingActionButton.setOnClickListener {
    navController.navigate(
        AFragmentDirections.actionAToB(),
        FragmentNavigatorExtras(floatingActionButton to floatingActionButton.transitionName)
    )
}
```

```xml
<!-- FragmentB layout -->
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/colorSurface"
    android:transitionName="transition_name">
    <!-- views -->
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

```kotlin
// FragmentB
// onCreate
sharedElementEnterTransition = MaterialContainerTransform()
```

**Android API version:** API 33, API 32

**Material Library version:** 1.8.0-alpha02

**Device:** Emulator API 33, Xiaomi Mi 12 Pro

**Comment by drchen** [comment]
Naomi, can you take a look?

**Comment by 1552980358** [comment]
Another Problem is the location of FAB, if a higher system navigation bar applied, the location of FAB will be lower than the correct location, and jitter back to normal location

https://user-images.githubusercontent.com/36123961/203187778-0c05aa0f-4819-45ca-85ab-4e5c6e71c37d.mp4

**Comment by imhappi** [comment]
Looking into the first issue

For the second issue (system nav bar issue), can you tell me what emulator device/API level the last video is at? I'm unable to repro that issue on any emulators/devices with the 3 button system navigation. The FAB vertical alignment reads the system insets, is there anything to do with overriding system insets in your app?

**Comment by 1552980358** [comment]
> Looking into the first issue
> 
> For the second issue (system nav bar issue), can you tell me what emulator device/API level the last video is at? I'm unable to repro that issue on any emulators/devices with the 3 button system navigation. The FAB vertical alignment reads the system insets, is there anything to do with overriding system insets in your app?

The second issue applied the same API level as the first one, i.e., API 33, difference between them is just different in resolution. There is no any action done to the system insets, and the code is fully the same as the first issue

**Comment by imhappi** [comment]
Ah calling `setOnApplyWindowInsetsListener` is probably what's causing the strange behavior

What view is setOnApplyWindowInsetsListener called on? BottomAppBar has its own setOnApplyWindowInsetsListener so maybe it is overriding it

**Comment by 1552980358** [comment]
> Ah calling `setOnApplyWindowInsetsListener` is probably what's causing the strange behavior
> 
> What view is setOnApplyWindowInsetsListener called on? BottomAppBar has its own setOnApplyWindowInsetsListener so maybe it is overriding it

The setOnApplyWindowInsetsListener called on window.decorView, but if I remove the setOnApplyWindowInsetsListener, the same issue still exist

**Comment by 1552980358** [comment]
> Ah calling `setOnApplyWindowInsetsListener` is probably what's causing the strange behavior
> 
> What view is setOnApplyWindowInsetsListener called on? BottomAppBar has its own setOnApplyWindowInsetsListener so maybe it is overriding it

But I found that if I add margins to the FAB, this issue is solved
