### ISSUE TITLE
[MaterialSwitch] How can I change the size of this component? 

### ISSUE THREAD

**Issue by jiwangyihao** [material-components/material-components-android#3099]
I have met with problems when I was styling the MaterialSwitch component, especially when I was trying to change the size of it. 
I've found that in https://github.com/material-components/material-components-android/issues/2720 suggestions have been given to copy  the default drawables and change their width/height. But, ... , where are them? 
These files was removed nearly a year ago, so, now how can I change the size? 
I'd appreciate it if anyone could do me a favor.

**Comment by drchen** [comment]
All drawables used by MaterialSwitch are here:
https://github.com/material-components/material-components-android/tree/master/lib/java/com/google/android/material/materialswitch/res/drawable
