### ISSUE TITLE
[MaterialTimePicker & MaterialDatePicker] Margin is not the same

### ISSUE THREAD

**Issue by michael-winkler** [material-components/material-components-android#3100]
**Description:**
The start and end (left and right) margin is different as you can see in the pictures.
The margin is smaller on datepicker as on timepicker.

I reported the bug already here https://github.com/material-components/material-components-android/issues/2987 too.

**Expected behavior:**
The margin should be the same.

**Source code:**
App theme uses M3

**Minimal sample app repro:** 
![d1](https://user-images.githubusercontent.com/29900947/191434991-d0115c55-8317-457e-9edb-5d73364cdc89.png)

![t1](https://user-images.githubusercontent.com/29900947/191435006-7df81afc-32f3-4d73-abcf-a7236ef892cb.png)

As you can see the margin is not the same but it should be the same.

**Android API version:**
Android 13

**Material Library version:**
com.google.android.material:material:1.8.0-alpha03

**Device:** 
Every device

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by paulfthomas** [comment]
By start/end margins, are you talking about what's inside the dialog or the space between the dialog and the screen (basically the width of the dialog)?

**Comment by Mika-89** [comment]
The space between the dialog and the screen.
