### ISSUE TITLE
[SearchBar] Weird contrast between SearchBar and AppBarLayout

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3102]
I don't know what it should actually look like, but I doubt it should look like this:

<img src="https://user-images.githubusercontent.com/82187521/203602105-4eb6270b-9461-45d1-82e6-5800ef094a7d.png" width="270px" />

**Material Library version:** 1.8.0-alpha03

**Comment by raajkumars** [comment]
This issue has been fixed already. T

**Comment by dsn5ft** [comment]
Fixed by https://github.com/material-components/material-components-android/commit/90d658357760ae62111f10fe2da49041ae42f193
