### ISSUE TITLE
[BottomSheet] Navigation bar icons are hard to see

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3106]
**Description:** When we open a modal bottom sheet with light theme on Android 12L (32), the navigation bar icons are white and hard to see.
![Screenshot_20221124_155459](https://user-images.githubusercontent.com/71050561/203717926-643298e9-7183-440e-ab48-5b63c0a614aa.png)

**Expected behavior:** Make the navigation bar icons more visible like this (on Android 13 (33)).
![Screenshot_20221124_163122](https://user-images.githubusercontent.com/71050561/203723644-09f093da-bc60-4840-9313-f7114f65b21b.png)

**Source code:** https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/bottomsheet

**Minimal sample app repro:** Catalog app

**Android API version:** 32 (and 33)

**Material Library version:** 1.8.0-alpha03

**Device:** Emulator 31.3.13

**Comment by drchen** [comment]
Unfortunately I think it's a framework bug and I couldn't find a good workaround to solve it...

No matter we set he navigation bar to light or dark, it always shows light icons on dialog windows...

I'll close this issue as infeasible. If anyone has any good ideas how this can be worked around it will be greatly appreciated!

**Comment by manabu-nakamura** [comment]
Sorry, I have no idea, too.

**Comment by manabu-nakamura** [comment]
This seems to have been fixed in Google APIs Intel x86 Atom_64 System Image: API level 32 revision 5.

**Comment by drchen** [comment]
Great to hear that!! Thanks for the report and the update. : )
