### ISSUE TITLE
Android studio error on 1.8.0-alpha03

### ISSUE THREAD

**Issue by Narinc** [material-components/material-components-android#3107]
This error occurred on Android Studio Dolphin | 2021.3.1
Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

**Comment by drchen** [comment]
Can you provide more details? 

Like how/where the Android Studio shows the error?

**Comment by Narinc** [comment]
FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeUatFeatureDebugResources'.
> /Users/PersonalMac/.gradle/caches/transforms-2/files-2.1/1739489df35976f4528679e1e8e8e496/material-1.8.0-alpha03/res/values/values.xml: Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':akbankx:mergeUatFeatureDebugResources'.
> /Users/PersonalMac/.gradle/caches/transforms-2/files-2.1/1739489df35976f4528679e1e8e8e496/material-1.8.0-alpha03/res/values/values.xml: Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':akbankx:kaptUatFeatureDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by john990** [comment]
@drchen I also encountered this problem, it is already an old problem, don't know why it hasn't been solved yet. If you search online, there will be many similar questions.

E.g:
https://stackoverflow.com/questions/74191324/cant-determine-type-for-tag-macro-name-m3-comp-bottom-app-bar-container-colo

They all suggested lowering the version, but lowering the version will cause some components to be unusable, and hope to solve it as soon as possible, thank you.

**Comment by john990** [comment]
Finally I solved this problem.

Update Android Studio to the latest version, then click the Gradle upgrade prompt button to upgrade the Gradle version to 7.3.1.

Then it worked successfully.

**Comment by drchen** [comment]
It seems like upgrading Android Studio version should solve the problem?

I'll close this issue as an Android Studio issue. Feel free to reopen it if this is still reproducible on the latest version of Android Studio.
