### ISSUE TITLE
[MaterialSwitch] How can I create a MaterialSwitch Widget with a label and a description?

### ISSUE THREAD

**Issue by jiwangyihao** [material-components/material-components-android#3113]
I see an example of label text in the guideline of the widget MaterialSwitch just like this:

![picture of the example](https://i.stack.imgur.com/VX5Pf.png)

However I can't find any methods to realise such effects in an Android app. It seems that I can only define the label text in the property "android:text", without the description.

So could anyone lend me a hand? I'd appreciate it if anyone could do me a favor.

Besides, it seems that material.io has only limited explanation and demos (I can't even find demo for example showed in the guideline picture), so is there a place where I can find them?

Thanks again for your help!

**Comment by drchen** [comment]
It's not something supported by MaterialSwitch itself. But you can easily create the layout on your own with a frame layout and a linear layout.
