### ISSUE TITLE
[RangeSlider] Label got stuck when used in BottomSheet

### ISSUE THREAD

**Issue by mhettig** [material-components/material-components-android#3124]
**Description:**
When adding a RangeSlider to a BottomSheet with the labels always visible (= `app:labelBehavior="visible"`) the labels will not move together with the slider when the bottom sheet is dragged. They get stuck:

https://user-images.githubusercontent.com/2598617/205148343-5c6cf634-ac8a-4805-836c-6b8815e8b9a3.mp4

**Expected behavior:**
Labels stay fixed at the top of the RangeSlider and will be in sync with the bottom sheet movement.

**Source code:**
To provide a simple and reproducible example I used the Catalog App from this repository.

There I added the following code snippet to `cat_bottomsheet_fragment.xml`. It was included at the bottom of the BottomSheet so below the last MaterialSwitch.

```
<com.google.android.material.slider.RangeSlider
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:layout_below="@id/cat_bottomsheet_enabled_switch"
  app:labelBehavior="visible" />
```

**Android API version:** 33

**Material Library version:** 1.7.0 - Bug is also visible with  version 1.6.0 when label behavior "visible" was firstly introduced

**Device:** Xiaomi Mi 11 Ultra (with xiaomi.eu firmware)

**Comment by leticiarossi** [comment]
Thank you for reporting, this looks like the same issue as https://github.com/material-components/material-components-android/issues/2869 so will add this to there and close it here as duplicate
