### ISSUE TITLE
[Slider] label not showing when `android:hardwareAccelerated="false"` added

### ISSUE THREAD

**Issue by bczhc** [material-components/material-components-android#3127]
**Description:** When `android:hardwareAccelerated="false"` is added to `<activity>` in the manifest file, the floating label of Slider in that activity will not show.

Also I tested adding `android:layerType="software"` to both the slider and its parent layout, and this bug doesn't happen.

See https://stackoverflow.com/questions/63453139/android-materil-slider-no-label. But I cannot find any further explanation about this, like why this happens, and should this be considered as a bug?

**Expected behavior:** The label shows

**Android API version:** 32

**Material Library version:** 1.8.0-alpha03

**Device:** Android 10 emulator API 29 x86, and my physical Huawei

**Comment by leticiarossi** [comment]
I'm not sure about the exact cause of the issue but since `android:hardwareAccelerated` is true by default for APIs 14+ it could be better to have android:hardwareAccelerated false for the specific situations where you need it. For example, do you have any custom views that require `android:hardwareAccelerated` to be false? If so you could try following [this](https://stackoverflow.com/a/18614289)

**Comment by bczhc** [comment]
In fact I have, it's related to the `BlurMaskFilter`, dealing with using `.setLayerType(View.LAYER_TYPE_SOFTWARE, null)`, but it's in another activity in my App and has nothing to do with this issue.

But for this, it's that I just found the issue by accident, and want to know the reason. I don't even know why I put `android:hardwareAccelerated="false"` before in my manifest file (maybe just for a temporary test on how the hardware acceleration affects the render performance idk). Anyway just removing that line makes it work, not a bit deal for me.

**Comment by leticiarossi** [comment]
I see, I'll close this issue then! I'm not sure, but `hardwareAccelerated` might be required to use ViewOverlay, which might be why the issue happens
