### ISSUE TITLE
[MaterialCardView] Generates NumberFormatException

### ISSUE THREAD

**Issue by brh** [material-components/material-components-android#3129]
**Description:** Using a Material 3 Card causes a NumberFormatException, seems to be related to animation but I am not doing any specific animation. 

Caused by: java.lang.NumberFormatException: For input string: "?2130969380"
                                                            	at java.lang.Integer.parseInt(Integer.java:615)
                                                            	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:139)
                                                            	at android.content.res.TypedArray.getInt(TypedArray.java:433)
                                                            	at android.animation.AnimatorInflater.parseAnimatorFromTypeArray(AnimatorInflater.java:412)
                                                            	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:1053)
                                                            	at android.animation.AnimatorInflater.loadObjectAnimator(AnimatorInflater.java:1011)
                                                            	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:667)
                                                            	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:642)
                                                            	at android.animation.AnimatorInflater.createStateListAnimatorFromXml(AnimatorInflater.java:237)
                                                            	at android.animation.AnimatorInflater.loadStateListAnimator(AnimatorInflater.java:170)
                                                            	at android.view.View.<init>(View.java:5574)
                                                            	at android.view.ViewGroup.<init>(ViewGroup.java:675)
                                                            	at android.widget.FrameLayout.<init>(FrameLayout.java:99)
                                                            	at android.widget.FrameLayout.<init>(FrameLayout.java:94)
                                                            	at androidx.cardview.widget.CardView.<init>(CardView.java:121)
                                                            	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:164)
                                                            	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:160)
                                                            	... 72 more

**Expected behavior:** I should be able to display a Card without a crash. It works if I downgrade to 1.7.0 version of the material library

**Source code:** Try to run the attached app in Android Studio Dolphin or Elec Eel.

**Minimal sample app repro:** [app.zip](https://github.com/material-components/material-components-android/files/10158555/app.zip)

**Android API version:** 29

**Material Library version:** 1.8.0-alpha03

**Device:** Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by hunterstich** [comment]
Hi @brh,

I'm looking into this issue. I've downloaded your sample and am running the app on API 29 and don't see a crash happening. Are there steps to take to reproduce the issue in your sample?

**Comment by brh** [comment]
@hunterstich As soon as I load the app it crashes. I transferred to my work laptop and I run into this issue #3107

**Comment by brh** [comment]
When I roll the version back to 1.8.0-alpha01 it works.

**Comment by hunterstich** [comment]
@brh, When you transfer your app to your laptop, did you keep the version at 1.8.0-alpha03? You then can run the app but you see a different crash related to shape appearance theme attributes?

What do you mean when you roll back to 1.8.0-alpha01 when you say the Material3 themes and styles aren't being used?

**Comment by brh** [comment]
Yes, when I went to the other laptop it gave me that new error (I stayed at 1.8.0-alpha03). When I downgraded to 1.8.0-alpha01 it compiles, but look of the carded isn't as expected, the shapeAppearance in the themes for instance is not right.

**Comment by drchen** [comment]
Hi @pekingme can this be related to tokens?

@hunterstich it seems like you've fixed a similar issue before. Do you think they are caused by the same reason?

**Comment by drchen** [comment]
@brh 

Can you check if this still happens if you use the latest version of Android Studio / Gradle / Material library?

After some discussion internally, we think this looks very like an issue caused by (maybe outdated) environment settings.

**Comment by brh** [comment]
Seems to be working, thanks.

**Comment by nicbell** [comment]
I got this same crash. 
I was using `Widget.Material3.CardView.Outlined` with a MaterialComponents (M2) theme as I'm not yet able to upgrade themes. It worked fine in `1.7` but crashes in `1.8` due to some motion changes.

Back-porting the following to me theme fixes it.

```xml
<!-- Motion attributes used internally by M3 cards, added to prevent crashes -->
<item name="motionEasingEmphasizedInterpolator" tools:ignore="PrivateResource">@interpolator/m3_sys_motion_easing_emphasized</item>
<item name="motionDurationMedium1" tools:ignore="PrivateResource">@integer/m3_sys_motion_duration_medium1</item>
<item name="motionDurationMedium4" tools:ignore="PrivateResource">@integer/m3_sys_motion_duration_medium4</item>
<item name="motionDurationLong2" tools:ignore="PrivateResource">@integer/m3_sys_motion_duration_long2</item>
```

**Comment by R0rt1z2** [comment]
I seem to be experiencing a similar problem, if not the same. I'm trying to use `Widget.Material3.CardView.Outlined` (version `1.11.0`) and I get the following crash:
```
01-18 22:39:38.732  4377  4377 E AndroidRuntime: Caused by: java.lang.NumberFormatException: For input string: "?2130903863"
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at java.lang.Integer.parseInt(Integer.java:747)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:347)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.content.res.TypedArray.getInt(TypedArray.java:435)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.animation.AnimatorInflater.parseAnimatorFromTypeArray(AnimatorInflater.java:412)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:1053)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.animation.AnimatorInflater.loadObjectAnimator(AnimatorInflater.java:1011)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:667)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:642)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.animation.AnimatorInflater.createStateListAnimatorFromXml(AnimatorInflater.java:237)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.animation.AnimatorInflater.loadStateListAnimator(AnimatorInflater.java:170)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.view.View.<init>(View.java:5934)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.view.ViewGroup.<init>(ViewGroup.java:703)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.widget.FrameLayout.<init>(FrameLayout.java:99)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at android.widget.FrameLayout.<init>(FrameLayout.java:94)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at androidx.cardview.widget.CardView.<init>(CardView.java:121)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:169)
01-18 22:39:38.732  4377  4377 E AndroidRuntime:        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:165)```

**Comment by davidmak2709** [comment]
In my case switching from a direct style reference like:

```xml
<com.google.android.material.card.MaterialCardView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/my_card_view"

    style="@style/Widget.Material3.CardView.Outlined"

    android:layout_width="match_parent"
    android:layout_height="wrap_content">

```

To an attribute reference:

```xml
<com.google.android.material.card.MaterialCardView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/my_card_view"

    style="?materialCardViewOutlinedStyle"

    android:layout_width="match_parent"
    android:layout_height="wrap_content">
```

Solved the problem (on `com.google.android.material:material:1.11.0`) or downgrade to `com.google.android.material:material:1.7.0`.

**Comment by R0rt1z2** [comment]
> In my case switching from a direct style reference like:
> 
> ```
> <com.google.android.material.card.MaterialCardView 
>     xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:app="http://schemas.android.com/apk/res-auto"
>     android:id="@+id/my_card_view"
> 
>     style="@style/Widget.Material3.CardView.Outlined"
> 
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content">
> ```
> 
> To an attribute reference:
> 
> ```
> <com.google.android.material.card.MaterialCardView 
>     xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:app="http://schemas.android.com/apk/res-auto"
>     android:id="@+id/my_card_view"
> 
>     style="?materialCardViewOutlinedStyle"
> 
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content">
> ```
> 
> Solved the problem (on `com.google.android.material:material:1.11.0`) or downgrade to `com.google.android.material:material:1.7.0`.

Thank you, that fixed it!
