### ISSUE TITLE
[Chip] background doesn't change color while being checked.

### ISSUE THREAD

**Issue by Gowsky** [material-components/material-components-android#313]
ColorStateList set as background for Chip inside ChipGroup doesn't work. The background color used is always from unchecked state. The text color however gets updated upon state change.

**Comment by Anjula** [comment]
With the new update, the background colour is not getting changed when the chip is checked.

`<com.google.android.material.chip.Chip
                    android:id="@+id/general_feedback_chip_idea"
                    style="@style/AppTheme.ChoiceChips"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:checkable="true"
                    android:clickable="true"
                    android:focusable="true"
                    android:text="Idea"
                    app:chipStrokeColor="@color/colorPrimaryDark"
                    app:chipStrokeWidth="1dp" />`

------------------------------------------

`<style name="AppTheme.ChoiceChips" parent="@style/Widget.MaterialComponents.Chip.Choice">
        <item name="chipBackgroundColor">@color/feedback_chip_state_list</item>
        <item name="android:textColor">@color/feedback_chip_text_state_list</item>
    </style>`

------------------------------------------

**feedback_chip_state_list**

`<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/colorPrimaryDark" android:state_checked="true"/>
    <item android:color="@color/white" />
</selector>`

![image](https://user-images.githubusercontent.com/842061/55702193-77012700-59f3-11e9-8670-5b86cb6e7d1c.png)

**Comment by TadejZupancic** [comment]
It works with state_selected though. Is this a bug or does a click on chip now select it instead of check it?

**Comment by wcshi** [comment]
https://github.com/material-components/material-components-android/commit/b544530ac0d9e1e1741de4f16ea77da13449fd92 added support for checked state in addition to selected state. Could you please try adding android:enabled="true" in your CSL on the state_checked line?

**Comment by TadejZupancic** [comment]
Adding enabled does not work.

**Comment by wcshi** [comment]
Could you please share repo steps / code.

**Comment by TadejZupancic** [comment]
ok, done. [https://issuetracker.google.com/issues/130207069](https://issuetracker.google.com/issues/130207069)

**Comment by wcshi** [comment]
Responded on bug. Closing issue, please comment on the public bug in the future, thanks!
