### ISSUE TITLE
[Catalog] Applied edge-to-edge to modal side sheet

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3133]
**Is your feature request related to a problem? Please describe.**
The edge-to-edge preference does not apply to the modal side sheet.
![Screenshot_20221208_122759](https://user-images.githubusercontent.com/71050561/206351126-480a718b-f202-48b3-a3f6-13dcb82ce6c4.png)

**Describe the solution you'd like**
The edge-to-edge preference applies to the modal side sheet.
![Screenshot_20221208_124002](https://user-images.githubusercontent.com/71050561/206351176-287ef269-9fdb-4148-9372-a30cf3eae574.png)

**Comment by afohrman** [comment]
Closed in https://github.com/material-components/material-components-android/pull/3155.
