### ISSUE TITLE
[TextInputEditText] Cursor color doesn't honor colorControlActivated

### ISSUE THREAD

**Issue by alashow** [material-components/material-components-android#3139]
**Description:** TextInputEditText doesn't use the color provided in AppTheme colorControlActivated & `android:colorControlActivated`. 
I tried setting `colorControlActivated` on the view itself or it's parent textInputLayout. Nothing is working and white cursor color is set for some reason.

**Expected behavior:** Correct cursor color set via colorControlActivated.

I was upgrading from 1.5.0-beta01 where it was working as expected. 1.8.0-beta01 doesn't work as described above, but 1.7.0 has correct behavior

**Android API version:** Android 12

**Material Library version:** 1.8.0-beta01

**Device:** Sm-700x

**Comment by alashow** [comment]
Minimal sample app repro: 
[cursor-color-bug.zip](https://github.com/material-components/material-components-android/files/10213108/cursor-color-bug.zip)
app-17.0.0 - correctly has Red as cursor color
app-18.0.0-beta01 - doesn't have Red color. I saw brown color (coming from dynamic wallpaper)

**Comment by leticiarossi** [comment]
hey there! the cursor color is controlled by the `colorControlActivated` set in the text field's [theme overlay](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/res/values/styles.xml#L487). since 1.7 we've made some changes like setting an error color on the cursor, so we now dynamically get the cursor color via `colorControlActivated` in `TextInputLayout.java`. My guess is that it gets the value from the theme overlay which takes precedence over what you've set in theme.

Since it's a theme attr, you'd need to have your custom color set in a custom theme overlay, doing something like this:

```
<style name="MyApp.TextField" parent="Widget.Material3.TextInputLayout.OutlinedBox">
      <item name="materialThemeOverlay">@style/ThemeOverlay.MyApp.TextInputEditText</item>
</style>

<style name="ThemeOverlay.MyApp.TextInputEditText" parent="ThemeOverlay.Material3.TextInputEditText.OutlinedBox">
      <item name="colorControlActivated">#FF0000</item>
</style>
```

and set the `MyApp.TextField` style on your TextInputLayout!

**Comment by alashow** [comment]
Why is global theme colors set not picked up by components? Why was it workig on 1.7 and not 1.8? What's the alternative for 1.8  to change globally or without having to change/apply styles to every textfield components theme overlay?

**Comment by leticiarossi** [comment]
Like I said above, the color set in the theme overlay style must be taking precedence, I'm not sure why that was not happening in 1.7 though. You can set the `textInputStyle` or `textInputOutlinedStyle` etc [theme attributes](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L160-L164) to your custom text field style that has your theme overlay so you don't have to specify the style on each text field component.

**Comment by alashow** [comment]
>  Like I said above, the color set in the theme overlay style must be taking precedence

Where exactly this theme overlay would be coming from if I'm not setting it? If it's the default theme overlay for textfield component, why is it taking precedence over non-default value set in theme attribute? 

Also shouldn't this behavior change be mentioned in the changelog?
Is this change affecting other components too? It would be cumbersome to style every available component by having to create custom theme & overlays to override default material colors.

https://github.com/material-components/material-components-android/blob/2465192173eabaebc8a8f5dcd1b0f5ca9330c1cb/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L99-L164

If it's only a change affecting `com.google.android.material.textfield.TextInputEditText`, then that's only questionable...
