### ISSUE TITLE
CalendarConstraints getter is different from the provided at its setter

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#3146]
**Description:** getStartMs, getEndMs, and getOpenAtMs is different from what is provided to CalendarConstraints Builder setters.

**Expected behavior:** 
Getter milliseconds should be the same as the one that is provided using its setter.

**Source code:** 

```
val currentDate = MaterialDatePicker.todayInUtcMilliseconds()

        val oldestDate: Long
        val previousMonth: Long

        TimeZone.getTimeZone(ZoneId.systemDefault()).also {

            Calendar.getInstance(it).let { cal ->
                cal.timeInMillis = currentDate // Set calendar date today
                cal.add(Calendar.MONTH, -1) // Set month to previous
                previousMonth = cal.timeInMillis
            }

            Calendar.getInstance(it).let { cal ->
                cal.timeInMillis = currentDate // Set calendar date today
                // Get current year
                val year = cal[Calendar.YEAR]
                cal.add(Calendar.YEAR, 2009 - year) // Set oldest supported year
                oldestDate = cal.timeInMillis
            }

        }

        val fromConstraints =
            CalendarConstraints.Builder()
                .setStart(oldestDate)
                .setEnd(currentDate)
                .setOpenAt(previousMonth)
                .setValidator(DateValidatorPointBackward.now()) // Disable days beyond current date
                .build()

        Log.wtf("OLDEST", oldestDate.toString())
        Log.wtf("CURRENT", currentDate.toString())
        Log.wtf("OPEN AT", previousMonth.toString())

        Log.wtf("CONSTRAINT OLDEST", fromConstraints.startMs.toString())
        Log.wtf("CONSTRAINT CURRENT", fromConstraints.endMs.toString())
        Log.wtf("CONSTRAINT OPEN AT", fromConstraints.openAtMs.toString())

```
![image](https://user-images.githubusercontent.com/38008900/197623297-96bdd379-e17e-4564-b15b-e8636676104c.png)

**Android API version:** Any

**Material Library version:** 1.8.0-alpha02

**Device:** Any

Note: This new API was made from this [issue](https://github.com/material-components/material-components-android/issues/2907), however the returned date in milliseconds is not the same to what has been passed to its setter.

**Comment by imhappi** [comment]
Hello,
As mentioned in https://github.com/material-components/material-components-android/issues/3052, this seems to be working as intended. We'll add documentation for the newly added public getters to avoid confusion, but CalendarConstraints takes the set time and converts it into the month for its bounds (eg. see documentation for the setters: `A UTC timeInMilliseconds contained within the latest month the calendar will page to.`
https://developer.android.com/reference/com/google/android/material/datepicker/CalendarConstraints.Builder)

This is why all of the constraints values are always the 1st of the month of the time that was passed to `setStart`, etc
