### ISSUE TITLE
[Slider] Vaule tip does not disappear

### ISSUE THREAD

**Issue by Super12138** [material-components/material-components-android#3147]
**Description:** 
After sliding the slider, the progress prompt box has not disappeared

![bug](https://user-images.githubusercontent.com/70494801/208841160-e1525e14-ff77-45b1-9120-ca7ad68fad58.jpg)

**Expected behavior:** 
Remove any remaining blocks from above (to see that picture ⬆️)

**Source code:** 
`<com.google.android.material.slider.Slider
        android:id="@+id/slider"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="127dp"
        android:layout_marginBottom="72dp"
        android:stepSize="10.0"
        android:valueFrom="0.0"
        android:valueTo="100.0"
        app:layout_constraintBottom_toTopOf="@+id/elevatedButton"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/slider2" />`

**Android API version:** 
Android 10 (API29)

**Material Library version:** 
1.8.0-beta01

**Device:** 
Mi

**Comment by imhappi** [comment]
I'm unable to repro this bug; can you provide what the full layout looks like?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
