### ISSUE TITLE
TextInputLayout hint bound binded edittext bound

### ISSUE THREAD

**Issue by andasl** [material-components/material-components-android#315]
I want intput bound is under the center line，hint when no input is in the center line,
 like MD guide: no input hint in the center,  when input something , the input content and top label will be moved symmetrically.
but the TextInputLayout can not do this，hint bound is binding with edittext
I see the code,
in function onLayout()
DescendantOffsetUtils.getDescendantRect() will set rect to editText bound
and next line offsetDescendantRect() call ,it seems about editText scroll, and also binding with editText.
I tried change setting ,like modify padding ,but content and label symetrically or hint in center can not co-exist. 
Is my something used wrong ?

**Comment by andasl** [comment]
set EditText padding to make input area in bottom , but expand hint also use this padding. so it will be show in the same place

**Comment by andasl** [comment]
I want…… like this https://www.material.io/design/components/text-fields.html#anatomy
come in this web site and find keyword "Label text", a video exist in here.
but I run this project demo in my phone, no case like this.
I modified the project code in class TextInputLayout.java,
`private Rect calculateExpandedTextBounds(Rect rect) {
    if (editText == null) {
      throw new IllegalStateException();
    }
    Rect bounds = tmpBoundsRect;
    bounds.left = rect.left + editText.getCompoundPaddingLeft();
    bounds.top = rect.top; //+ editText.getCompoundPaddingTop(); // this
    bounds.right = rect.right - editText.getCompoundPaddingRight();
    bounds.bottom = rect.bottom ;//- editText.getCompoundPaddingBottom(); // this
    return bounds;
  }
`
I'm not sure the modify is right, although it seems good.(maybe some other influence)
and the style is @style/Widget.MaterialComponents.TextInputLayout.FilledBox.Dense

**Comment by afohrman** [comment]
Is the problem that the hint text in the filled box text field is not vertically centered?

**Comment by andasl** [comment]
> Is the problem that the hint text in the filled box text field is not vertically centered?

yes

**Comment by afohrman** [comment]
This issue was resolved in https://github.com/material-components/material-components-android/commit/4476564820ff7a12f94ffa7fc8d9e10221b18eb1.
