### ISSUE TITLE
[TextInputLayout] Support for boxBackgroundErrorColor in outline and filed mode

### ISSUE THREAD

**Issue by priyanka-rani** [material-components/material-components-android#3151]
**Is your feature request related to a problem? Please describe.**
In one of the project I needed the box in textinputLayout to have different color in error state. But as there was no such method for tat I ended up using custom background in edittext and manually changing the background onError. 

**Describe the solution you'd like**
A method and XML attribute `boxBackgroundErrorColor` to set box background color in error state

**Describe alternatives you've considered**

**Additional context**

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Hi, I believe it's the design intention not to affect background color on error, and the internal logic has also been built around that assumption. 

Or in other word, it's deliberately *discouraged* to do so. 

Given that there's a workaround if you really want to implement that behavior. I'll close this as a no-go.
