### ISSUE TITLE
[Catalog] Use MaterialSwitch instead of SwitchCompat

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3153]
**Is your feature request related to a problem? Please describe.**
SwitchCompat is used.
![Screenshot_20221226_104057](https://user-images.githubusercontent.com/71050561/209489535-bf445bb6-4322-4f71-a48a-68e01043c0a3.png)

**Describe the solution you'd like**
Use MaterialSwitch instead of SwitchCompat.
![Screenshot_20221226_104905](https://user-images.githubusercontent.com/71050561/209489492-618222b3-bab8-45b6-8fbf-3a5b04e05cd0.png)

**Comment by afohrman** [comment]
This issue was fixed in https://github.com/material-components/material-components-android/pull/3154.
