### ISSUE TITLE
[Button] The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

### ISSUE THREAD

**Issue by vanniktech** [material-components/material-components-android#3164]
The Layout Preview does not work with my custom class:
```
class OutlineButton @JvmOverloads constructor(
  context: Context,
  attrs: AttributeSet? = null,
) : MaterialButton(context, attrs, com.google.android.material.R.attr.materialButtonOutlinedStyle)
```

when using material 1.7.0:

```
The following classes could not be instantiated:
com.vanniktech.ui.OutlineButton (Open Class, Show Exception, Clear Cache)
Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).   at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)   at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:216)   at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:144)   at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)   at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:230)   at com.vanniktech.ui.OutlineButton.<init>(OutlineButton.kt:13)   at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)   at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)   at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)   at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)   at java.lang.reflect.Constructor.newInstance(Constructor.java:480)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)   at android.view.LayoutInflater.inflate(LayoutInflater.java:686)   at android.view.LayoutInflater.inflate(LayoutInflater.java:505) Copy stack to clipboard 
 ```

**Comment by afohrman** [comment]
Hi @vanniktech, thanks for reporting. What theme does your project use? Material components need to use `Theme.MaterialComponents` or later (ex: `Theme.Material3.*`).

**Comment by vanniktech** [comment]
I'm in a library module where I don't have a style / theming available.

**Comment by drchen** [comment]
I think even as a library module, you can still define a default application theme in your AndroidManifest.xml?

I'll close this as WAI. If that doesn't work, please file a bug to Android Studio instead:
https://developer.android.com/studio/report-bugs.html

**Comment by vanniktech** [comment]
Why would I want to do this though? It'll only get merged and then consumers need to override this.

**Comment by drchen** [comment]
Because you want to see it in preview? 

Material components are styled by Material themes, which carries the subsystem values Material components are using (for example, color attributes). Without Material themes (or, actually, any themes that implement those required attributes), how do you want Android Studio to render it?

**Comment by vanniktech** [comment]
Would not it be possible to check here https://github.com/material-components/material-components-android/blob/2e7979b60bb22b57a070f0ad46abee17ec97e634/lib/java/com/google/android/material/internal/ThemeEnforcement.java#L246 if we're in edit mode? And if so, don't throw.

Currently the entire preview is broken and this is not something AS can fix since you are the one throwing an exception. Android Studio also advices this:

<img width="747" alt="Screen Shot 2023-02-06 at 09 03 16" src="https://user-images.githubusercontent.com/5759366/216917104-c16c01b0-0148-4478-bc0a-cbb708d3189b.png">

**Comment by 5peak2me** [comment]
Any progress, I'm having the same problem and can only add the `isInEditMode` sample code in place of each customized view now!

**Comment by maexsp** [comment]
Change the custom Theme of the Android styles.xml to be parent of E.g. Theme.Material3.Light.NoActionBar or Theme.Material3.Light, etc. See also https://github.com/material-components/material-components-android/blame/master/docs/getting-started.md
