### ISSUE TITLE
Material slider's setTickActiveTintList is not working

### ISSUE THREAD

**Issue by aryangupta24** [material-components/material-components-android#3169]
Material slider's setTickActiveTintList is not working. the color doesn't change

I have asked on StackOverFlow
https://stackoverflow.com/questions/75035547/material-sliders-settickactivetintlist-is-not-working

**Android API version:** 31

**Material Library version:** 1.0.0

**Device:** Redmi Y2

**Comment by afohrman** [comment]
Thanks for reporting. Does the active tick color work when you use `app:tickColorActive`? Also, are you using `setTickInactiveTintList` to set the active tick tint color? To set the active tick tint color, you'd need to use `setTickActiveTintList`.

**Comment by aryangupta24** [comment]
Any update ?

**Comment by drchen** [comment]
Please update your Material library version to the latest one. 

I don't think either methods are available on 1.0.0.
