### ISSUE TITLE
MaterialCardView setOnclickListener not calling

### ISSUE THREAD

**Issue by manumathew17** [material-components/material-components-android#3170]
**Description:** Material card view not listening to onClickListener

**Expected behavior:** on clicking card onClickListener should call

**Source code:** 
`<?xml version="1.0" encoding="utf-8"?>
<com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/generalCardView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:clickable="true"
    android:focusable="true"
    app:cardBackgroundColor="@color/white"
    app:cardCornerRadius="8dp"
    app:cardElevation="5dp">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:duplicateParentState="true"
        android: orientation="vertical">
        <LinearLayout
            android:id="@+id/header"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/headerBg"
            android:orientation="horizontal"
            android:paddingHorizontal="12dp"
            android:paddingVertical="10dp"
            android:weightSum="2">
            <TextView
                android:id="@+id/text_cardHeader1"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:text="Card header 1"
                android:textColor="@color/blue"
                android:textStyle="bold" />
            <TextView
                android:id="@+id/text_cardHeader2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:drawablePadding="2dp"
                android:gravity="center_vertical"
                android:text="Card header 2"
                android:textColor="@color/blue"
                android:textStyle="bold" />
        </LinearLayout>
        <TableLayout
            android:id="@+id/tableCardDetailLayout"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="12dp"
            android:paddingTop="5dp"
            android:paddingBottom="10dp">
        </TableLayout>
    </LinearLayout>
</com.google.android.material.card.MaterialCardView>`

Java code
`        MaterialCardView generalCardView;
        generalCardView = findViewById(R.id.generalCardView);
        generalCardView.setClickable(true);
        generalCardView.setFocusable(true);
        generalCardView.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.e("clicked","called");
            }
        });`

**Android API version:** Android API version here

**Material Library version:**  1.7.0

**Device:**  all device

**Comment by cyb3rko** [comment]
When I've had a similar problem I found out that instead of clicking the CardView you click the content of it.
So in your example you probably call the onClick of the TextView in the CardView, as the TextView is not explicitely non-clickable here.

**Comment by drchen** [comment]
I think @cyb3rko's comment is probably the case.

@manumathew17 can you check if that's your situation?

**Comment by hunterstich** [comment]
Hi @manumathew17, 

I'm going to close this due to inactivity and the likelihood that this is something related to your layout/other click listeners. Feel free to re-open if you're still running into this and are able to attach a sample that reproduces the issue.
