### ISSUE TITLE
[Material Floating Action Button] change background color doesn't work on latest sdk

### ISSUE THREAD

**Issue by lonewolf73** [material-components/material-components-android#3171]
I am implementing an app with a floating action button;

My gradle:

```
compileSdkVersion 33

defaultConfig {
	applicationId "com.area.areahotspot"
	minSdkVersion 24
	targetSdkVersion 33
	versionCode 1
	versionName "1.0"

dependencies {

    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
```

In my fragment I put :

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fr_myfragment"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context=".MyFragment">
	
	<!-- TODO: Update blank fragment layout -->
	<ListView xmlns:android="http://schemas.android.com/apk/res/android"
		xmlns:tools="http://schemas.android.com/tools"
		android:id="@+id/myfragment_list"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:layout_weight="1"
		android:layout_margin="5dp"
		android:descendantFocusability="blocksDescendants"/>

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:id="@+id/cl_fab"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.google.android.material.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            android:layout_margin="16dp"
            app:borderWidth="0dp"
            app:srcCompat="@android:drawable/ic_popup_sync"
            app:backgroundTint="@color/fab_enabled"
            android:background="@null" />

    </androidx.coordinatorlayout.widget.CoordinatorLayout>
</FrameLayout>

```
so I settled my setOnClickListener for fab various ways as in commented lines to make change backgroundColor to show as like as it's disabled:

```
FloatingActionButton fab = (FloatingActionButton) view.findViewById(R.id.fab);
fab.setOnClickListener(new View.OnClickListener() {
	@Override
	public void onClick(View view) {
		fab.setEnabled(false);

		fab.setBackgroundColor( getContext().getColor(R.color.fab_disabled) );

		//fab.setElevation(0);
		//fab.setVisibility(view.GONE);
		//fab.hide();
		//fab.getBackground().set(getContext().getColor(R.color.fab_disabled));
		//fab.setBackgroundTintList(ColorStateList.valueOf(getContext().getColor(R.color.fab_disabled)));
		//fab.getBackground().mutate().setTint(getContext().getColor(R.color.fab_disabled));
		//fab.setCompatElevation(0);

```
In the Debugger I see the attribute `mColor` before to call `setBackgroundTintList` it contained value `-8934372` which should be the enabled color state and after called `setBackgroundTintList` it was `-2763307` so that should mean it has changed the color. 
Just the button was correctly disabled ( that `.setEnabled(false)` ) but didn't change the aspect....I tried to use a selector too but didn't worked:

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/fab_enabled" android:state_enabled="true"/>
    <item android:color="@color/fab_disabled"/>
</selector>
```

I tried also to hide it setting visibility as GONE but it didn't hided. 
Is that maybe related to latest SDK version or some version of dependencies that doesn't work well with? Or is there an alternative I haven't found anywhere to make the fab disabled ? Any direction would be really appreciated...

Thanks!
Cheers

**Comment by imhappi** [comment]
Hi @lonewolf73 ! 
See https://stackoverflow.com/questions/60642329/why-does-the-material-fab-not-change-colors-when-disabled

Using a selector should work, make sure to set the selector on the background tint.

Also what do you mean by 'setting visibility as GONE but it didn't hided.'? It looks like setting the visibility as GONE works for me.

For your other question, you are probably seeing that it doesn't update any UI elements until after exiting onClick because the `draw` method has not yet been called after the UI updates. You probably would only want to use a waiting spinner if you were incurring some long task in the onClick, which you shouldn't do on the main thread anyways (that is to say, you don't want to hide the waiting spinner until the task is done so the hiding would also not be done on the main thread execution). That is to say, this is working as intended.

**Comment by lonewolf73** [comment]
Hello imhappi ,

I already seen previously that https://stackoverflow.com/questions/60642329/why-does-the-material-fab-not-change-colors-when-disabled and I followed that question to implement `selector` as I said in main first post which it should change aspect itself once I call `.setEnabled(true/false)` but it didn't worked. And yes, I tried also to s`etVisibility(view.GONE);` but it didn't disappeared to recall as visible again once I finish all operations I call inside FAB's onClick.... 

That's why I am here asking because it's really weird behavior like this I am having... In fact I was asking if maybe that depends I am using FrameLayout when maybe I should use something else like LinearLayout or something else.... actually I am using FrameLayout because I am using it as tab fragment....

**Comment by imhappi** [comment]
Using a selector works for me; are you making sure to use `backgroundTint`, not `backgroundColor`? And I'm not sure what you mean by "it didn't disappeared to recall as visible again once I finish all operations I call inside FAB's onClick"

As I mentioned before, any UI updates may not occur _immediately_ when the method is called (as in, if you are using a debugger to step through, you won't see UI updates until the canvas is redrawn). But it should happen pretty much immediately as experienced in real-time.

**Comment by lonewolf73** [comment]
At the end I figured out it was because I was executing a runnable thread from fab's onClick event , so I moved the code inside another thread called from fab's onClick button where I passed fab to the thread so in the meanwhile the thread was working I could exit from fab's onClick and let it calling redraw then once the thread was finished I could re-enable the button.... thanks anyway to all!! Cheers
