### ISSUE TITLE
BadgeDrawable TextAppearance

### ISSUE THREAD

**Issue by SudoDios** [material-components/material-components-android#3175]
Hi.
how to change badge textAppearance ??
this Method is private : 
[setTextAppearanceResource(resId)](https://github.com/material-components/material-components-android/blob/d5a37010309c5d1a98c02d0fd22e63e1217d6ee0/lib/java/com/google/android/material/badge/BadgeDrawable.java#L829)
and in style file (badgeStyle) not working textAppearance.

**Comment by drchen** [comment]
We don't currently support this. 

Naomi can you take a look? Maybe we can add this while you are working on updating the style.
