### ISSUE TITLE
[MaterialDatePicker] Description sample is broken after update

### ISSUE THREAD

**Issue by smelfungus** [material-components/material-components-android#3179]
**Description:**

It seems like `MaterialDatePicker` `description` sample is broken for `1.9.0-alpha01`:
https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/datepicker

![image](https://user-images.githubusercontent.com/3989453/213483175-c31f7f47-5c58-457c-841f-cc0306f00270.png)

**Comment by dummyco** [comment]
Apparently, the issue is related to the recent layout changes here:
https://github.com/material-components/material-components-android/blob/f2269bcd85dcbecab6c74168efa3c36ed549cee6/lib/java/com/google/android/material/datepicker/res/layout/mtrl_picker_header_dialog.xml#L26
