### ISSUE TITLE
MaterialAlertDialogBuilder requires a colorSurface attribute

### ISSUE THREAD

**Issue by raxden** [material-components/material-components-android#318]
I'm trying to use MaterialAlertDialogBuilder, but application launch the following error when dialog is launched:

`MaterialAlertDialogBuilder requires a value for the com.core.app.dev:attr/colorSurface attribute to be set in your app theme.`

This is my theme with attribute colorSurface, What are I doing wrong?:

`    <style name="BaseTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        ...
        <item name="colorOnBackground">@color/colorOnBackground</item>
        
        <item name="colorSurface">@color/colorSurface</item>
        
        <item name="colorOnSurface">@color/colorOnSurface</item>
     ...
    </style>`

1.1.0-alpha05 used.

Thanks!

**Comment by wcshi** [comment]
Created https://issuetracker.google.com/issues/130345782
