### ISSUE TITLE
[SearchBar] Binary XML file line #23 in com.example.myapplication:layout/fragment_first: Binary XML file line #23 in com.example.myapplication:layout/fragment_first: Error inflating class com.google.android.material.search.SearchBar

### ISSUE THREAD

**Issue by Dante313** [material-components/material-components-android#3185]
I'm trying to implement new SearchBar and getting error.

My actions:

1) create new empty project in Electric Eel studio version.

2) add dependency:

`implementation "com.google.android.material:material:1.9.0-alpha01"`

3) in first fragment's XML layout change views to presented in:
https://github.com/material-components/material-components-android/blob/master/docs/components/Search.md#putting-it-all-together

4) in FirstFragment class remove button's click

5) run the app. After that it's crashing. 

What i'm doing wrong? :(

**Comment by Dante313** [comment]
P.S. it's working only when using `Material3` theme for project. But we are using `MaterialComponents` theme. Is there a chance to use this component with previous theme version?

**Comment by JabirDev** [comment]
I used the Material3 theme but still have the same problem, how to fix this?

**Comment by raajkumars** [comment]
@Dante313 Search components are supported only in M3 themes. Please consider upgrading your project's them to M3.

@JabirDev Please provide detailed stacktrace/logs and if possible a simple code sample to help us diagnose the issue.

**Comment by dsn5ft** [comment]
Closing for now. Please provide more information if this is still happening when using the M3 theme (required) and either 1.8.0 or 1.9.0 where the Search components are available.
