### ISSUE TITLE
Design Preview is lost when upgrading to version 1.8

### ISSUE THREAD

**Issue by durgeshrjkumar** [material-components/material-components-android#3186]
when upgrading with this library my design preview was lost. I wasted my 3 hours googling and searching for error. thenI removed new libraries one by one and found this library was the culprit.

**Comment by nicetomytyuk** [comment]
Having the same issue, for example with TabLayout, after upgrading to version 1.8.0 the preview just got broken like this:

![image](https://user-images.githubusercontent.com/30237552/214881181-8b24287d-e56a-4ddc-be62-8c734b185b5c.png)

The only way I found to solve it is to downgrade the material to 1.7.0

**Comment by cyb3rko** [comment]
Same here with AppBarLayout + MaterialToolbar.

**Comment by zalexdev** [comment]
same with MaterialCardView _"Missing some classes"_. Only downgrade to 1.7.0 helps

**Comment by imhappi** [comment]
Not sure if this is the same design preview issue, but there's a comment thread on design preview errors in 1.8: https://github.com/material-components/material-components-android/issues/3007

Have you tried a newer version of Android studio?

**Comment by durgeshrjkumar** [comment]
Yes I am working on latest version

**Comment by cyb3rko** [comment]
It seems that it only works with Canary build atm.

**Comment by nicetomytyuk** [comment]
@imhappi I'm working w/ Android Studio 2022.1.1, that should be the latest:
![image](https://user-images.githubusercontent.com/30237552/215695512-4035a0a5-892e-41c1-a14f-6d9ba5f2ab72.png)

OS: Windows 10

**Comment by dsn5ft** [comment]
The Canary build of Android Studio can be downloaded [here](https://developer.android.com/studio/preview). Closing this issue for now since the Android Studio team has already included the fix, and it's not really a library bug.

**Comment by jens1o** [comment]
Is there a public bug tracker to subscribe so one is notified when the bugfix in Android Studio hits the stable release?

**Comment by cyb3rko** [comment]
@jens1o I think it already has. I have no problems anymore with Version 1.8.0 with the current stable Android Studio release.
