### ISSUE TITLE
FAB goes down after attenuation of the screen

### ISSUE THREAD

**Issue by Babich-anton** [material-components/material-components-android#319]
Steps:
1. Input any letters in Search field
2. Erase and repeat step 2
3. Wait until the phone locks
4. Unlock phone
5. Check button '+' for creating a document

Screenshots:
![bug](https://user-images.githubusercontent.com/29468003/56280925-f8ec0100-6113-11e9-9fac-8c2b55b2f4e4.png)
![feature](https://user-images.githubusercontent.com/29468003/56280926-f8ec0100-6113-11e9-98cc-e7fdceb2a14a.png)

Layout:
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/fragment_documents"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".fragments.DocumentsFragment">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/documents_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/background_light"
        tools:ignore="MergeRootFrame">

        <androidx.appcompat.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/document_top_toolbar"
            style="@style/Base.TextAppearance.Widget.AppCompat.Toolbar.Title"
            android:layout_width="match_parent"
            android:layout_height="?android:actionBarSize"
            android:background="@color/colorPrimary"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
            app:title="@string/app_name"
            app:titleMarginStart="16dp"
            app:titleTextColor="@color/colorWhite" />

        <androidx.coordinatorlayout.widget.CoordinatorLayout
            android:id="@+id/documents_coordinator_bottom_app_bar"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/document_top_toolbar">

            <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
                android:id="@+id/documents_swipe_refresh"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <TextView
                        android:id="@+id/documents_empty_view"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_margin="8dp"
                        android:gravity="center"
                        android:text="@string/loading"
                        android:textColor="@color/colorPrimary"
                        android:textSize="24sp"
                        android:visibility="visible"
                        tools:layout_editor_absoluteX="8dp"
                        tools:layout_editor_absoluteY="8dp" />

                    <androidx.recyclerview.widget.RecyclerView
                        android:id="@+id/documents_recycler_view"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layoutAnimation="@anim/layout_animation_fall_down"
                        android:clipToPadding="false"
                        android:paddingBottom="100dp"
                        android:visibility="visible"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        tools:listitem="@layout/row_document_list" />

                </androidx.constraintlayout.widget.ConstraintLayout>

            </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>

            <com.google.android.material.bottomappbar.BottomAppBar
                android:id="@+id/documents_bottom_app_bar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:layout_gravity="bottom"
                app:backgroundTint="@color/colorPrimary"
                app:fabAlignmentMode="end" />

            <com.google.android.material.floatingactionbutton.FloatingActionButton
                android:id="@+id/add_new_document"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_add_primary_24dp"
                app:fabSize="normal"
                app:layout_anchor="@id/documents_bottom_app_bar"
                app:layout_anchorGravity="center" />

        </androidx.coordinatorlayout.widget.CoordinatorLayout>

    </androidx.constraintlayout.widget.ConstraintLayout>

</FrameLayout>

- Design Library Version: com.google.android.material:material:1.1.0-alpha05
- Android API version: 23
- Device: Android  6.0 (HTC One_M8)

**Comment by MGaetan89** [comment]
Could this be the same as #310?

**Comment by Babich-anton** [comment]
This is similar, but we do not use Snackbar at the moment, it arises in other cases. In any case, we will wait for the fix of one of these two problems in the next release.

**Comment by wcshi** [comment]
We're transitioning from github issues to a public issue tracker, I added a comment at https://issuetracker.google.com/issues/129765383#comment2, please post comments or check progress there.
