### ISSUE TITLE
Google Pay

### ISSUE THREAD

**Issue by genaldo1** [material-components/material-components-android#3192]
https://pay.google.com/ui/pay#__WA__=%7B%22requestId%22%3A%22GPAY%22%2C%22returnUrl%22%3A%22https%3A%2F%2Flivecoins.com.br%2Fhackers-criaram-contas-no-github-para-minerar-criptomoedas%2F%22%2C%22args%22%3A%7B%22apiVersion%22%3A1%2C%22allowedPaymentMethods%22%3A%5B%22CARD%22%5D%2C%22environment%22%3A%22PRODUCTION%22%2C%22playEnvironment%22%3A%22PROD%22%2C%22swg%22%3A%7B%22skuId%22%3A%22SWGPD.3092-8829-9137-77117%22%2C%22publicationId%22%3A%22CAowy4OGCw%22%2C%22swgVersion%22%3A%222%22%7D%2C%22i%22%3A%7B%22startTimeMs%22%3A1674755050870%2C%22googleTransactionId%22%3A%22EF2CD71C-B0DD-48E5-9F3F-428E188DDF57.swg%22%2C%22productType%22%3A%22UI_CONTRIBUTION%22%2C%22disableNative%22%3Atrue%2C%22redirectVerifier%22%3A%22GymAAZgoyRWKnPFg5KzlrQDAfyPrnj8HCCipI9GxUNyLEiFZxpXNxGKfUNffHuI%2F%22%7D%7D%7D

**Comment by cyb3rko** [comment]
Please don't click the link above.

And mods: Please delete this
