### ISSUE TITLE
BottomSheetDialog -  Overridden themes doesn't work after rotation

### ISSUE THREAD

**Issue by ValBasova** [material-components/material-components-android#3195]
**Description:** BottomSheetDialog's overridden theme doesn't work after rotation - swiping up - and rotation to back. 

**Expected behavior:** Specifically, I have added to attribute "cornerFamily" = "cut" of ShapeAppearance.App.LargeComponent (source is here: https://m2.material.io/develop/android/components/bottom-sheet-dialog-fragment#theming-bottom-sheets) and it appears as expected, then after rotation to landscape layout, swipe up animation and rotation back, the "cut" shape is gone. Please have a look at the screenshots: 

![photo1_2023-01-27_21-51-3](https://user-images.githubusercontent.com/58528549/215238730-05b72fea-ffb4-4026-b730-06385cb250c8.jpg)

![photo2_2023-01-27_21-52-06](https://user-images.githubusercontent.com/58528549/215238747-2b79ed53-e2e1-4756-ad63-0f8ae2ce00d9.jpg)

![photo3_2023-01-27_21-52-33](https://user-images.githubusercontent.com/58528549/215238752-d1dec018-471b-4135-9e99-cfb2589d4aee.jpg)

![photo4_2023-01-27_21-52-58](https://user-images.githubusercontent.com/58528549/215238759-49e39ae4-e02e-4322-bcca-1de7488d54ac.jpg)

**Minimal sample app repro:** https://github.com/ValBasova/BottomSheetDialogSample

**Android API version:** 30

**Material Library version:** 1.8.0

**Device:** pixel

**Comment by drchen** [comment]
Is the bottom sheet in the expanded state in the last two screenshots? If you use Material 3 theme/style, does the issue still happen?

**Comment by ValBasova** [comment]
Hi, yes, expanded state in the last two pics. 
In fact, I have switched to Material 3 theme and it works as expected. Thanks.

**Comment by drchen** [comment]
Thanks for the update. Given that it works with Material 3 themes and the old Material themes are deprecated, let me close this as obsolete. : )

**Comment by dtavnn** [comment]
<style name="Base.Theme.Test" parent="Theme.Material3.DayNight.NoActionBar">
        
        
    </style>
i use Material 3 theme/style, but bottomsheetdialog doesn't work after rotation. help me.
