### ISSUE TITLE
[onCreateContextMenu webView] Crash with dynamic colors theme

### ISSUE THREAD

**Issue by GreenSnakeLinux** [material-components/material-components-android#3196]
**Description:** 

I'm using DynamicColors.applyToActivitiesIfAvailable during onCreate on myApplication.
The theme used is parent of "Theme.Material3.DynamicColors.DayNight"
When I enter onCreateContextMenu on a webView it is crashing short after (contextMenu.add ...setOnMenuItemClickListener)
(All my activities inherit AppCompatActivity)

For the moment I have replace the theme with "ThemeOverlay.Material3.DynamicColors.DayNight"
and it works just by changing Theme. by ThemeOverlay.

See the log at the end

**Android API version:** 33

**Material Library version:** 1.8

**Device:** Simulator and Samsung S22

**Minimal sample app repro:** https://github.com/GreenSnakeLinux/TestOnCreateContextMenu

Log:
W/System.err: android.view.InflateException: Binary XML file line #80 in android:layout/alert_dialog_material: Binary XML file line #37 in android:layout/alert_dialog_button_bar_material: Error inflating class Button
W/System.err: Caused by: android.view.InflateException: Binary XML file line #37 in android:layout/alert_dialog_button_bar_material: Error inflating class Button
W/System.err: Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
W/System.err:     at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
W/System.err:     at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:216)
W/System.err:     at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:144)
W/System.err:     at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
W/System.err:     at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:231)
W/System.err:     at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:222)
W/System.err:     at com.google.android.material.theme.MaterialComponentsViewInflater.createButton(MaterialComponentsViewInflater.java:43)
W/System.err:     at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:156)
W/System.err:     at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1678)
W/System.err:     at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1729)
W/System.err:     at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
W/System.err:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
W/System.err:     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:469)
W/System.err:     at com.android.internal.app.AlertController.installContent(AlertController.java:269)
W/System.err:     at android.app.AlertDialog.onCreate(AlertDialog.java:439)
W/System.err:     at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
W/System.err:     at android.app.Dialog.show(Dialog.java:325)
W/System.err:     at com.android.internal.view.menu.MenuDialogHelper.show(MenuDialogHelper.java:89)
W/System.err:     at com.android.internal.view.menu.ContextMenuBuilder.showDialog(ContextMenuBuilder.java:90)
W/System.err:     at com.android.internal.policy.DecorView.showContextMenuForChildInternal(DecorView.java:858)
W/System.err:     at com.android.internal.policy.DecorView.showContextMenuForChild(DecorView.java:828)
W/System.err:     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:979)
W/System.err:     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:979)
W/System.err:     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:979)
W/System.err:     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:979)
W/System.err:     at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:979)
W/System.err:     at android.view.View.showContextMenu(View.java:7661)
W/System.err:     at android.view.View.performLongClickInternal(View.java:7590)
W/System.err:     at android.view.View.performLongClick(View.java:7544)
W/System.err:     at android.webkit.WebView.access$501(WebView.java:113)
W/System.err:     at android.webkit.WebView$PrivateAccess.super_performLongClick(WebView.java:2435)
W/System.err:     at com.android.webview.chromium.WebViewChromium.performLongClick(chromium-TrichromeWebViewGoogle6432.apk-stable-495157434:2051)
W/System.err:     at android.webkit.WebView.performLongClick(WebView.java:2935)
W/System.err:     at org.chromium.content.browser.GestureListenerManagerImpl.filterTapOrPressEvent(chromium-TrichromeWebViewGoogle6432.apk-stable-495157434:424)
W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:161)
W/System.err:     at android.os.Looper.loop(Looper.java:288)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7898)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by dsn5ft** [comment]
Hi @GreenSnakeLinux, can you provide a minimal sample app GitHub repo that reproduces this crash?

**Comment by GreenSnakeLinux** [comment]
> Hi @GreenSnakeLinux, can you provide a minimal sample app GitHub repo that reproduces this crash?

Done: https://github.com/GreenSnakeLinux/TestOnCreateContextMenu
During doing the sample app, it appear that the crash happen when "colorPrimaryVariant" is missing in main Theme :( 
(I put a comment in the sample)

**Comment by dsn5ft** [comment]
Ah I see. So yeah it seems this is due to your main app theme inheriting from `Theme.AppCompat.Light.DarkActionBar` instead of a Material theme like `Theme.MaterialComponents.*` or `Theme.Material3.*`.

The reason why adding `colorPrimaryVariant` avoids the crash is because our theme enforcement uses the presence of the `colorPrimaryVariant` as a proxy for whether the app is using a Material theme, in some cases:

https://github.com/material-components/material-components-android/blob/23dc14ca3a35b0194a169ea53563862c2a67cbc5/lib/java/com/google/android/material/internal/ThemeEnforcement.java#L47

Can you update your main app theme to use `Theme.MaterialComponents.*` or `Theme.Material3.*`?

**Comment by GreenSnakeLinux** [comment]
> Can you update your main app theme to use `Theme.MaterialComponents.*` or `Theme.Material3.*`?
Yes, it works with this update. I was using Theme.AppCompat for older android version.
So there will be no correction ? If it's not possible to mix theme between android version, at least a better error text will be appreciate. Also the exception was catched but the activity has crash anyway :(

**Comment by dsn5ft** [comment]
> Yes, it works with this update. I was using Theme.AppCompat for older android version.
> So there will be no correction ?

Unfortunately a Material theme is required when using Material components/features, because the components/features are dependent on attributes like `colorPrimaryVariant` and many more which are only set up by the Material themes, not AppCompat.

> at least a better error text will be appreciate.

The stacktrace you posted shows this, which is the explanation that you need to use a Material theme when using Material components/features:

```
W/System.err: Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
```

**Comment by GreenSnakeLinux** [comment]
The theme used when the crash occurs is the material theme set in DynamicColors.applyToActivitiesIfAvailable
So why it take the AppCompat theme set only in the manifest ?

**Comment by dsn5ft** [comment]
> For the moment I have replace the theme with "ThemeOverlay.Material3.DynamicColors.DayNight"
> and it works just by changing Theme. by ThemeOverlay.

Not sure exactly what you mean by this. By default DynamicColors.applyToActivitiesIfAvailable uses a theme overlay internally, which will not set up all of the component attributes as a full theme.

> So why it take the AppCompat theme set only in the manifest ?

My guess is that the WebView context is not exactly the same as the Activity context.

**Comment by GreenSnakeLinux** [comment]
> My guess is that the WebView context is not exactly the same as the Activity context.
Is it possible to update the WebView context to take the theme from activity context ? For me it's a bug.

**Comment by dsn5ft** [comment]
It's hard for me to say, we (Material) don't own WebView or the related infrastructure around Activity context/theming.
