### ISSUE TITLE
[CircularProgressIndicator] background proerty missing in jetpack compose

### ISSUE THREAD

**Issue by Chandu4221** [material-components/material-components-android#3206]
**Description:** 
CircularProgressIndicator `backgroundColor` propert missing.
[CircularProgressIndicator Docs](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#CircularProgressIndicator(androidx.compose.ui.Modifier,androidx.compose.ui.graphics.Color,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.StrokeCap))

**Source code:**
![image](https://user-images.githubusercontent.com/17278323/216374331-06ea2a1c-9d16-45dc-93c8-c61979eae41a.png)
![image](https://user-images.githubusercontent.com/17278323/216374493-1d4200a9-80ad-49b5-8b94-f09c584d2d0f.png)

Source Code of the CircularProgressIndicator

**Android API version:** Android API version here

**Material Library version:** 
```

    def composeBom = platform('androidx.compose:compose-bom:2023.01.00')
    implementation composeBom
    androidTestImplementation composeBom

    // COMPOSE UI
    implementation 'androidx.compose.ui:ui'

    // MATERIAL 2
    implementation 'androidx.compose.material:material'
```

**Comment by dsn5ft** [comment]
Hi, thanks for filing this feedback but this GitHub repo is for the Material View-based library.

You can file the request for Material Compose at https://issuetracker.google.com/issues/new?component=742043&template=1346811.
