### ISSUE TITLE
`TextInputLayout` hint is overlapped by outline

### ISSUE THREAD

**Issue by bczhc** [material-components/material-components-android#3225]
This may be related to `android:gravity` on `TIL`. Here's the layout:
```xml
<?xml version="1.0" encoding="utf-8"?>
<com.google.android.material.textfield.TextInputLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center_vertical"
>
    <com.google.android.material.textfield.TextInputEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="Hint Text"
    />
</com.google.android.material.textfield.TextInputLayout>
```
![image](https://user-images.githubusercontent.com/49330580/207835484-6afce79e-49cf-4b44-8566-00302936d3cd.png)

After removing the line `android:gravity="center_vertical"`, it gets okay:
![image](https://user-images.githubusercontent.com/49330580/207836016-ba97adbf-8c8f-49c5-901a-36ec017680e7.png)

Library version: 1.8.0-beta01. But with version 1.5.0-alpha04, this issue won't happen.

Update: still reproducible with material library 1.8.0 and 1.9.0-alpha01.

_Originally posted by @bczhc in https://github.com/material-components/material-components-android/issues/3041#issuecomment-1352862909_

**Comment by dsn5ft** [comment]
Hi, can you try setting the gravity on the TextInputEditText instead of the TextInputLayout?

**Comment by bczhc** [comment]
Hello. Setting `gravity` on TextInputEditText can let the issue gone, but setting this on TIET seems to be nonsense because it's `wrap_content`, and it makes the view go to the top of the screen.

I want to create a vertically centered TextInputEditText, so first I made the TextInputLayout's height fit the parent (say it's the screen) and set its `gravity` to let the child centered.

For now my goal can be achieved without experiencing this issue by setting `wrap_content` both on TIET and TIL, and then wrapping a parent view outside:
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout android:layout_width="match_parent"
             android:layout_height="match_parent"
             xmlns:android="http://schemas.android.com/apk/res/android"
>
    <com.google.android.material.textfield.TextInputLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
    >
        <com.google.android.material.textfield.TextInputEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="Hint Text"
        />
    </com.google.android.material.textfield.TextInputLayout>
</FrameLayout>
```
![Screenshot](https://user-images.githubusercontent.com/49330580/217838926-6f237343-18ea-491b-8a50-5571ee77aea7.png)

**Comment by dsn5ft** [comment]
@bczhc maybe I'm misunderstanding exactly what you're trying to achieve, but if I use `match_parent` for the height of both the `TextInputLayout` and the `TextInputEditText` then I get a full screen text field with the text centered:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1420597/217878326-63bcb13b-4906-472b-9aee-b66e0dcca013.png">

Is that what you want?

**Comment by bczhc** [comment]
Nope. What I need is just a text field with `wrap_content` height, centered on the screen, which is the result in my screenshot. Not the text centered.

The issue is, if I achieve this using https://github.com/material-components/material-components-android/issues/3225#issue-1577125448, overlapping issue occurs; If by https://github.com/material-components/material-components-android/issues/3225#issuecomment-1424269455, issue has gone.

**Comment by dsn5ft** [comment]
Oh, ok. Yes `android:layout_gravity` is correct in this case, because that's how a View will tell its parent how it wants to be aligned. Whereas `android:gravity` will affect the child Views:

https://stackoverflow.com/questions/3482742/what-is-the-difference-between-gravity-and-layout-gravity-in-android

**Comment by bczhc** [comment]
Yes I know the difference between them. So I think in this comment https://github.com/material-components/material-components-android/issues/3225#issue-1577125448 I'm doing the right thing to created a view like the screenshot in https://github.com/material-components/material-components-android/issues/3225#issuecomment-1424269455 (TextInputEditText is the child of TextInputLayout). But the key here is that it has the overlapping issue. Should this be considered as a bug?

**Comment by dsn5ft** [comment]
I don't think so. `android:layout_gravity` is more correct here because you are trying to center the entire `TextInputLayout` in the screen.

**Comment by dsn5ft** [comment]
Right, I think you still need the root `FrameLayout`.
