### ISSUE TITLE
[Material Date range picker] Preventing locale change

### ISSUE THREAD

**Issue by PranavMalayil** [material-components/material-components-android#3228]
one of my application supports multiple languages. But on a module i want to prevent it to English language only. and i have used material date range picker. but it goes to Arabic number when Arabic locale set to app. i don't want this. i have to show it English language.
how can i achieve the same

**Comment by dsn5ft** [comment]
@PranavMalayil can you try doing something like this within your module to force it to English?

https://stackoverflow.com/questions/4985805/set-locale-programmatically
