### ISSUE TITLE
Unresolved class '@string/appbar_scrolling_view_behavior' in 1.1.0-alpha05

### ISSUE THREAD

**Issue by Maxwell6635** [material-components/material-components-android#323]
After updated from 1.1.0-alpha04 to 1.1.0-alpha05 , xml show error Unresolved class '@string/appbar_scrolling_view_behavior' in 1.1.0-alpha05 for child in Coordinator Layout, but
if put the code App Bar layout its working fine.

Android Studio 3.4
Builds tools 28.0.3

Kindly refer image below :
[https://drive.google.com/file/d/1-pUwFkBGy0JAHrz_JQl__vHEmkJFQZlO/view?usp=sharing](url)

**Comment by ItzNotABug** [comment]
seeing the same error but it doesn't crash the app..

**Comment by cwalcott** [comment]
I'm seeing it with version 1.0.0, it started when I updated to Android Studio 3.4

**Comment by dscoppelletti** [comment]
The App runs properly, so I think the bug is new in Android Studio 3.4.0: I have opened an issue http://issuetracker.google.com/issues/131403371.

**Comment by ldjcmu** [comment]
Closing for the design project as Android Studio tracks.
