### ISSUE TITLE
[MaterialButton] Not selectable in Android Studio editor when included

### ISSUE THREAD

**Issue by Slion** [material-components/material-components-android#3231]
**Description:** 
Have a GridLayout containing a bunch of items. Add some MaterialButtons through `<include>` and noticed they can't be selected in the editor.

Ok now it seems to happen with every includes somehow, though in some circumstances includes works just fine. Maybe an issue with Gridlayout or include or both. The thing is I did not have such issue before I switched to MDC, added the library and switched the app theme parent.

**Expected behavior:** 
Included MaterialButton should be selectable in editor.

**Source code:**
```
<GridLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:columnCount="8"
    android:rowCount="8"
    android:orientation="horizontal">

    <Button android:text="1"
        android:layout_columnSpan="1"
        android:layout_rowWeight="1"
        android:layout_gravity="fill"
        />

    <Button

        android:layout_columnSpan="2"
        android:layout_gravity="fill_horizontal"
        android:text="2" />


    <include
        android:id="@+id/CantBeSelected"
        android:layout_width="60dp"
        android:layout_height="60dp"
        layout="@layout/button"
         />

<!-- Just copy that in the layout file you include above -->
    <com.google.android.material.button.MaterialButton
        android:id="@+id/CanBeSelected"
        style="@style/Widget.Material3.Button.ElevatedButton"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:layout_margin="0dp"
        android:padding="0dp"
        android:textStyle="bold|italic"
        android:contentDescription="A"
        android:hapticFeedbackEnabled="true"
        app:cornerRadius="12dp"
        />

    <Button
        android:layout_columnSpan="3"
        android:layout_gravity="fill"
        android:layout_rowSpan="2"
        android:text="4" />

    <Button
        android:layout_columnSpan="3"
        android:layout_gravity="fill_horizontal"
        android:text="5" />

    <Button
        android:layout_columnSpan="2"
        android:layout_gravity="fill_horizontal"
        android:text="6" />

</GridLayout>
```

**Minimal sample app repro:** 
None

**Android API version:** 
Android Studio 2022.1.1

**Material Library version:**
1.8.0

**Device:**
Windows PC

**Comment by dsn5ft** [comment]
Hi @Slion, thanks for reaching out. Unfortunately we (the Material Android team) have little control these types of Android Studio Preview Editor issues. The Preview Editor has its own layout engine and the Studio team, from what I understand, has to somewhat carefully make sure that themes, styles, symbols, etc are wired up correctly in order for everything to work.

Can you file a bug for them following these instructions?

https://developer.android.com/studio/report-bugs
