### ISSUE TITLE
[TextInputEditText] Cursor color doesn't honor colorControlActivated

### ISSUE THREAD

**Issue by alashow** [material-components/material-components-android#3238]
**Description:** TextInputEditText doesn't use the color provided in AppTheme colorControlActivated & `android:colorControlActivated`. 
I tried setting `colorControlActivated` on the view itself or it's parent textInputLayout. Nothing is working and white cursor color is set for some reason.

**Expected behavior:** Correct cursor color set via colorControlActivated.

I was upgrading from 1.5.0-beta01 where it was working as expected. 1.8.0-beta01 doesn't work as described above, but 1.7.0 has correct behavior

**Android API version:** Android 12

**Material Library version:** 1.8.0-beta01

**Device:** Sm-700x

Duplicating #3139 because according to https://github.com/material-components/material-components-android/issues/3139#issuecomment-1349693877 it seems like now it's required to set overlay colors to each component just to override colors, instead of just setting colorControlActivated in the theme.

**Comment by drchen** [comment]
This is working as intended. Please notice that the Material library is a design library coming with an opinionated, default design. 

We have an opinionated design on the text field cursor color, so if you want to override that, you will have to create the theme overlay on your own to override colorControlActivated "back".
