### ISSUE TITLE
[MaterialTimePicker] Wrong layout when preciseShrinking enabled

### ISSUE THREAD

**Issue by asuka-mio** [material-components/material-components-android#3239]
**Description:** Wrong layout when preciseShrinking enabled

**Expected behavior:** 

Expected:
![Screenshot_20230216-150021](https://user-images.githubusercontent.com/43900799/219291865-7dc8d8bc-8682-4191-a941-d6b7b332b716.png)

preciseShrinking enabled:
![Screenshot_20230216-150004](https://user-images.githubusercontent.com/43900799/219291957-55b0b36c-dcb3-4f32-ba77-f5f0e365b2d0.png)

**Source code:** android.experimental.enableNewResourceShrinker.preciseShrinking=true

**Android API version:** 33

**Material Library version:** 1.8.0

**Device:** Any

**Comment by drchen** [comment]
Hi, I think the tool and the relevant flag is still under development and might not be stable enough. There's not much we can do on the Material side. Can you file an issue to the Android Gradle Plug-in's issue tracker?
https://issuetracker.google.com/components/192709

I'll close the bug as infeasible.
