### ISSUE TITLE
Marked as private @string/appbar_scrolling_view_behavior

### ISSUE THREAD

**Issue by calmmycode** [material-components/material-components-android#324]
Still private, as mentioned in  #171.

**Comment by gsajith** [comment]
Are you using our 1.1.0-alpha05 release? This string should be marked public by now.

**Comment by ldjcmu** [comment]
There appears to be an issue with Android Studio as referenced in http://issuetracker.google.com/issues/131403371 and https://github.com/material-components/material-components-android/issues/323.
