### ISSUE TITLE
24hour wheel with 2hour steps in Signal App

### ISSUE THREAD

**Issue by haldi4803** [material-components/material-components-android#3240]
Greetings,

The Signal App uses Time Picker for their delayed Messages.
But apparently the library doesn't have the newest version so the 24h wheel doesn't have 2 wheels but one wheel with 2hour steps.

See here:
https://github.com/signalapp/Signal-Android/issues/12792
 

Must be some kind of early beta version for testing that shows up there.

**Comment by hunterstich** [comment]
Hi @haldi4803,

It looks like they're using an older version of the Material library. The time picker was updated to use the 2-ring design for 24hr input in library version 1.8, which is now stable (https://github.com/material-components/material-components-android/releases/tag/1.8.0).

Closing as this is a matter of Signal updating their library version.
