### ISSUE TITLE
[TextField] When implementing a drop down menu text field, the text gets cut off and doesn't wrap in the menu item. Please add a feature to support that?

### ISSUE THREAD

**Issue by anirudhlath** [material-components/material-components-android#3242]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
It looks like a duplicate to https://github.com/material-components/material-components-android/issues/3218

Please refer to that issue for the suggestions.

If that doesn't solve your problem please feel free to reopen the request with more detailed info.
