### ISSUE TITLE
[Menu] Typography styling overridden by android:textViewStyle

### ISSUE THREAD

**Issue by jkarlsson** [material-components/material-components-android#3243]
**Description:** 
According to the documentation, the typography in a Menu popup can be styled by specifying textAppearance{Large,Small}PopupMenu in your theme.

However, if your theme specifies an android:textViewStyle, this style will trump whatever style is set for textAppearance...PopupMenu, making it impossibly to style the menu items.

**Expected behavior:** In my minimal sample, I've set the popup menu style to use a red textColor and the default textViewStyle to use a blue color. I would expect the menu items to be red but they get the default blue color.

**Source code:** 
```
<resources xmlns:tools="http://schemas.android.com/tools">
    <!-- Base application theme. -->
    <style name="Base.Theme.Material3Sample" parent="Theme.Material3.DayNight.NoActionBar">
        <!-- Customize your light theme here. -->
        <!-- <item name="colorPrimary">@color/my_light_primary</item> -->

        <item name="textAppearanceLargePopupMenu">@style/TextAppearance.App.Popup</item>
        <item name="textAppearanceSmallPopupMenu">@style/TextAppearance.App.Popup</item>

        <!-- Removing this line makes the styling for popup menu work -->
        <item name="android:textViewStyle">@style/TextAppearance.App.DefaultTextViewStyle</item>
    </style>

    <style name="TextAppearance.App.Popup" parent="TextAppearance.Material3.BodyMedium">
        <item name="android:textColor">#f00</item>
    </style>

    <style name="TextAppearance.App.DefaultTextViewStyle" parent="TextAppearance.Material3.BodyMedium">
        <item name="android:textColor">#00f</item>
    </style>

    <style name="Theme.Material3Sample" parent="Base.Theme.Material3Sample" />
</resources>
```

**Minimal sample app repro:** The sample is just the new project scaffold in AS (Electric Eel) with the above changes to the theme and updating the material dependency to 1.8.0.

**Android API version:** 33

**Material Library version:** 1.8.0

**Device:** Pixel 6

**Comment by drchen** [comment]
This is caused by setting a "text appearance" as the "style" of the text view - therefore, you are setting `android:textColor` directly to the text views, which will override the text color set in the text appearance. 

The right away to provide your own text style's text appearance is wrapping the text appearance in a custom text style like:

```
 <style name="App.DefaultTextViewStyle" parent="Widget.MaterialComponents.TextView">
    <item name="android:textAppearance">@style/TextAppearance.App.DefaultTextViewStyle</item>
  </style>

  <style name="TextAppearance.App.DefaultTextViewStyle" parent="TextAppearance.Material3.BodyMedium">
    <item name="android:textColor">#00f</item>
  </style>
```

And set the custom text style as `android:textViewStyle` instead:

```
    <item name="android:textViewStyle">@style/App.DefaultTextViewStyle</item>
```
