### ISSUE TITLE
[TextInputEditText] Make text cursor color customizable

### ISSUE THREAD

**Issue by vanniktech** [material-components/material-components-android#3255]
For the following code:

```kotlin
binding.editText.textCursorDrawable = GradientDrawable(
        BOTTOM_TOP, intArrayOf(android.graphics.Color.RED, android.graphics.Color.RED)
      )
        .apply { setSize(20, binding.editText.textSize.toInt()) }
```

using Material 1.8.0, the Cursor drawable stays unchanged. This used to work with Material 1.7.0

**Comment by vanniktech** [comment]
Version 1.8.0 shows the incorrect color:

<img width="518" alt="Screen Shot 2023-02-21 at 19 45 02" src="https://user-images.githubusercontent.com/5759366/220432290-86c52709-fd13-4655-9122-5e0e8a2d9c2f.png">

With 1.7.0 this works:

<img width="518" alt="Screen Shot 2023-02-21 at 19 45 27" src="https://user-images.githubusercontent.com/5759366/220432492-a9d1eb27-bdd0-48c3-841b-37e53b589c59.png">

**Comment by drchen** [comment]
This is working as intended. 

If you want a custom cursor color, please set the value of `?attr/colorControlActivated` in the theme you use to create the text field to the custom color.

**Comment by vanniktech** [comment]
This isn't really viable for me since I need to have dynamic theming at runtime. I can't use a theme.

**Comment by drchen** [comment]
What's your actual use case? You can still use a contextThemeWrapper at runtime to create the text field. Does that work for you?

**Comment by vanniktech** [comment]
I'm having a B2B app where the entire app can be branded with their own color palette. Creating the text field isn't the problem, but I want to set the cursor color. Nonetheless, do you have an example regarding contextThemeWrapper?

**Comment by drchen** [comment]
I see. So the color you want to use cannot be known until runtime. Unfortunately I don't think there's a good solution to that - Android doesn't allow you to override theme attributes' value at runtime. 

To support your case we probably need to expose APIs to set up custom cursor colors. Let me reopen this and change it to a feature request.

**Comment by drchen** [comment]
Leticia, can you take a look when you have time?

**Comment by vanniktech** [comment]
> I see. So the color you want to use cannot be known until runtime.

Exactly.

> To support your case we probably need to expose APIs to set up custom cursor colors.

There is an API (starting 29) for this on TextView: https://developer.android.com/reference/android/widget/TextView#setTextCursorDrawable(android.graphics.drawable.Drawable). This is also the one I've been using with previous versions.

**Comment by vanniktech** [comment]
> I see. So the color you want to use cannot be known until runtime.

Exactly.

> To support your case we probably need to expose APIs to set up custom cursor colors.

There is an API (starting 29) for this on TextView: https://developer.android.com/reference/android/widget/TextView#setTextCursorDrawable(android.graphics.drawable.Drawable). This is also the one I've been using with previous versions.

**Comment by drchen** [comment]
With the framework API you can set a custom drawable. But TextInputLayout will tint it so the color you set won't be preserved. 

One workaround you can do for now is extending GradientDrawable and making setTintList() method a no-op.

**Comment by vanniktech** [comment]
This does work: https://github.com/vanniktech/ui/pull/9 - I'd still prefer a proper API for this though.

**Comment by drchen** [comment]
Yeah I think we can consider adding that. : )

**Comment by projectdelta6** [comment]
A note for anyone else confused when finding this, the `setCursorColor()` method is only available in `com.google.android.material:material:1.10.0-alpha04` or higher (took me a minute to figure that out)
