### ISSUE TITLE
setSelection not working dateRangePicker()

### ISSUE THREAD

**Issue by shubhamtriosoft** [material-components/material-components-android#3263]
I want change dateRangePicker set default date like last date before

**Comment by hunterstich** [comment]
Hi @shubhamtriosoft,

I'm not sure I understand the issue or question. Do you mind elaborating on what your trying to accomplish?

**Comment by shubhamtriosoft** [comment]
i want add validation from 1  date before like today in 27 FEB but validation start with 26

**Comment by leticiarossi** [comment]
Hi there, on our [docs](https://github.com/material-components/material-components-android/blob/master/docs/components/DatePicker.md#adding-calendar-constraints) you can find more info about setting calendar constrainsts, and our catalog also has examples where you can do something similar, like take today's date and do a roll operation to subtract one day for example
