### ISSUE TITLE
TabLayout doesn't keep selected Tab position

### ISSUE THREAD

**Issue by Sourav-21** [material-components/material-components-android#327]
The current version of the TabLayout doesn't keep it's view state when a configuration change takes place, instead, it defaults to the first tab. I think the expected behaviour would be to keep the current selected tab state without triggering the first tab.

**Comment by gsajith** [comment]
Hello, I believe this issue is already tracked at http://issuetracker.google.com/issues/124589439
Please follow that issue for updates, and feel free to comment there if you have additional context.
