### ISSUE TITLE
[Dialog] Background should be tinted (API 19)

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3276]
<table>
  <tr>
    <th>Actual behavior</th>
    <th>Expected behavior</th>
   </tr> 
   <tr>
    <td><img src="https://user-images.githubusercontent.com/82187521/221992947-d7c1e575-62df-472c-8cc8-76fc1895eaf8.png" width="270px"></td>
    <td><img src="https://user-images.githubusercontent.com/82187521/221993091-75cd21f1-5843-45ef-b86d-7d63fba1c1d1.png" width="270px"></td>
  </tr>
</table>

**Material Library version:** 1.8.0
**Device:** API 19 Emulator

**Comment by drchen** [comment]
It's working as intended as we never backported elevation overlay to pre-21 devices. (The background tint is done via the elevation overlay.)

FYI we are going to deprecate elevation overlay soon and introduce more "tinted" surface color roles - and the new solution will work on all API levels.

**Comment by pubiqq** [comment]
Well, let's hope so.

**Comment by Ongnon1990** [comment]
https://github.com/material-components/material-components-android/issues/3276?notification_referrer_id=NT_kwDOBzx1T7Q1NzM5OTEwODg3OjEyMTQwMjcwMw#issue-1605260217
