### ISSUE TITLE
[Icons] No longer visible in https://fonts.google.com/icons

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#3283]
**Description:** Icons are not showing up in https://fonts.google.com/icons page

**Expected behavior:** To show

![Screen Shot 2023-03-02 at 9 49 21 AM](https://user-images.githubusercontent.com/1494577/222510859-d7d46f76-cc1a-47fb-b7f7-749da8931e34.png)

**Comment by drchen** [comment]
It's not related to the Material Android library so I'll close it.

BTW I can see the icons normally. Maybe a temporary server issue and you can try that later?
