### ISSUE TITLE
[material-color-utilities] MaterialColors should be available in Compose v3 

### ISSUE THREAD

**Issue by ber4444** [material-components/material-components-android#3287]
**Is your feature request related to a problem? Please describe.**
For Compose, we need to use `com.google.android.material.color.MaterialColors` to generate tonal values for our theme. The problem is that requires the legacy `com.google.android.material:material" artifact (which copied the class from https://github.com/material-foundation/material-color-utilities, by the way).

**Describe the solution you'd like**
Make the same class available in the `androidx.compose.material3:material3` artifact.

**Comment by paulfthomas** [comment]
This is not the right repo for Material Compose, closing.
