### ISSUE TITLE
[Button] Wrong colors guide in documentation

### ISSUE THREAD

**Issue by PabloJuice** [material-components/material-components-android#3291]
**Description:** Buttons actually use colorContainer & colorOnContainer and instead of colorPrimary & colorOnPrimary like documentation says.

https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md - search "Primary"

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/values/styles.xml - search name="ThemeOverlay.Material3.Button"

![Capture1](https://user-images.githubusercontent.com/48531000/222978419-0a5dbacf-b8e0-422a-82c2-9091aaeaa574.PNG)
![Capture2](https://user-images.githubusercontent.com/48531000/222978423-a7368ccb-1237-41f2-8d18-34036044ecdb.PNG)

**Comment by PabloJuice** [comment]
Found it by exident:
    
    <style name="view.button.primary" parent="Widget.Material3.Button">
         ....
        <item name="materialThemeOverlay">@style/ThemeOverlay.App.Button.Primary</item>
    </style>

    <style name="view.button.secondary" parent="Widget.Material3.Button">
         ....
        <item name="materialThemeOverlay">@style/ThemeOverlay.App.Button.Secondary</item>
    </style>

<style name="ThemeOverlay.App.Button.Primary" parent="">
        <item name="colorContainer">@android:color/black</item>
        <item name="colorOnContainer">@android:color/white</item>
    </style>

    <style name="ThemeOverlay.App.Button.Secondary" parent="">
        <item name="colorContainer">@android:color/white</item>
        <item name="colorOnContainer">@android:color/black</item>
    </style>
    
    <Button
      style="@style/view.button.primary"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:text="Button" />
    
    <Button
      style="@style/view.button.secondary"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:text="Button" />
    
![image](https://user-images.githubusercontent.com/48531000/222978942-efbae9b1-16b2-45b2-9fae-248418063843.png)

**Comment by drchen** [comment]
I agree it's a bit confusing. But if you check the definition of `@macro/m3_comp_filled_button_label_text_color` and `@macro/m3_comp_filled_button_container_color`, you will find they will actually be replaced by `?attr/colorOnPrimary` and `?attr/colorPrimary` during the compile time. : )

**Comment by Ongnon1990** [comment]
<style name="ThemeOverlay.App.Button.Primary" parent="">
    <item name="colorContainer">@android:color/black</item>
    <item name="colorOnContainer">@android:color/white</item>
</style>

<style name="ThemeOverlay.App.Button.Secondary" parent="">
    <item name="colorContainer">@android:color/white</item>
    <item name="colorOnContainer">@android:color/black</item>
</style>
