### ISSUE TITLE
[Jetpack Compose - Buttons] contentColor should also be applied to the text 

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#3304]
**Description:**
I have created a theme using the MD Builder, but I noticed that for components such as buttons, elevated buttons, and filled tonal buttons, the **label text** in the button doesn't use the contentColor color to render the **label text**, but the icon does. The image below illustrates this issue. This is problematic b/c we have to provide the text color for every single instance of buttons in our app UI and rely on the new HCT color system to handle this.

<details>
<summary>App and Code Images</summary>

Notice how the text is tinted correctly, but the **label text** isn't. Also, if the button is disabled, the **label text** is NOT colored correctly, either.

![Screen Shot 2023-03-14 at 12 15 44 PM](https://user-images.githubusercontent.com/1494577/225113195-4ebef862-df64-42f5-8bf4-00db49deaa82.png)

<img src="https://user-images.githubusercontent.com/1494577/225113554-5ead8aa4-2c84-42f5-b450-315a14657822.png" width="300"/>
</details>

**Jetpack Compose component(s) used:**
* Filled icon button
* Elevated button
* Icon elevated button
* Filled tonal button
* Filled icon tonal button.

**Expected behavior:** If the entire _colorScheme_ is defined for light and dark themes, the components fully honor these colors. 
* Enabled state icon and label text use the same `onPrimary` color
* Disabled state icon and label text use the same `onSurface.copy(alpha = 0.38f)`
 
Images below compare what Jetpack Compose renders vs what I expect to see. Also, the M3 builder has provided a components page in Figma using my colorScheme but that page doesn't match the component impl.

<details>
<summary>Comparing Images</summary>

| Jetpack Compose | Expected |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1494577/225110865-d7cc0256-09cc-4760-956c-848c1a3cea9e.png"/> | <img src="https://user-images.githubusercontent.com/1494577/225111117-bc14f3eb-97ab-4212-9d20-39b3b1026481.png"/> |
</details>

**Source code:**

<details>
<summary>Button Example</summary>

    Button(
//        colors = ButtonDefaults.buttonColors(), // Uses the right colors defined in the theme, no need to specify here
        onClick = { }
        }) {
         // Icon is rendered using the correct content color for that button
        Icon(
            imageVector = Icons.Outlined.ContentCopy,
            contentDescription = "Icon button",
            modifier = Modifier.size(ButtonDefaults.IconSize)
        )
        Spacer(modifier = Modifier.size(ButtonDefaults.IconSpacing))
        Text(
            text = "With icon",
            color = MaterialTheme.colorScheme.onPrimary // MUST specify, it doesn't use the button's content color
        )
    }
</details>

<details>
<summary>Tonal Button Example</summary>

    ElevatedButton(
//        colors = ButtonDefaults.buttonColors(), // Uses the right colors defined in the theme, no need to specify here
        onClick = { }
        }) {
        Text(
            text = "Elevated",
            color = MaterialTheme.colorScheme.primary // MUST specify, it doesn't use the button's content color
        )
    }
</details>

<details>
<summary>Icon Tonal Button Example</summary>

    ElevatedButton(
//        colors = ButtonDefaults.elevatedButtonColors(), // Uses the right colors defined in the theme, no need to specify here
        onClick = { }) {
         // Icon is rendered using the correct content color for that button
        Icon(
            imageVector = Icons.Outlined.ContentCopy,
            contentDescription = "With icon elevated",
            modifier = Modifier.size(ButtonDefaults.IconSize)
        )
        Spacer(modifier = Modifier.size(ButtonDefaults.IconSpacing))
        Text(
            text = "With icon elevated",
            color = MaterialTheme.colorScheme.primary // MUST specify, it doesn't use the button's content color
        )
    }

</details>

**Jetpack Compose version:** 1.4.0-beta01

**Android Studio Build:** #AI-221.6008.13.2211.9514443, built on January 20, 2023

**Kotlin version:** 1.6.4

**Device:** Any

**Comment by paulfthomas** [comment]
This is not the repo for Compose, please file your bug in the [issue tracker](https://issuetracker.google.com/issues/new?component=742043&template=1590761).
