### ISSUE TITLE
[Jetpack Compose - Outlined Buttons] Neither text nor border honor the theme

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#3305]
**Description:**
Outline buttons are not rendering the border and text according M3 design guidelines. I have a complete _colorScheme_ and _theme_ for my app but when using outline buttons neither text nor border honor the theme. I am relying on the HCT color system to do the right thing and not have to define each for every instance of outline buttons in my app. Also, these buttons are 

<details>
<summary>App and Code Images</summary>

![Screen Shot 2023-03-14 at 12 54 01 PM](https://user-images.githubusercontent.com/1494577/225121463-5a9b0c3e-d48f-4387-a16e-d3a9d816c663.png)
</details>

**Expected behavior:** I expected that if the entire _colorScheme_ is defined for light and dark themes, the components fully honor these colors. Images below compare what Jetpack Compose renders vs what I expect to see. Also, the M3 builder has provided a components page in Figma using my colorScheme but that page doesn't match the component impl.

<details>
<summary>Comparing Images</summary>

| Jetpack Compose | Expected |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1494577/225121972-b904b987-100b-4c58-8271-bd98d968972d.png"/> | <img src="https://user-images.githubusercontent.com/1494577/225122132-692e7760-5911-4d27-bfc9-c8c2879c5c80.png"/> |
| <img src="https://user-images.githubusercontent.com/1494577/225122070-83e5e203-e57a-4843-b146-c939d7f9d0f6.png"/> | <img src="https://user-images.githubusercontent.com/1494577/225122179-ea97e10d-6e4b-4991-807a-19b90de15414.png"/> |
</details>

**Source code:**

<details>
<summary>Outline Button Example</summary>

    OutlinedButton(
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outline), // MUST specify, it doesn't use the button's content color
        onClick = { }
    ) {
        Text(
            text = "Outlined",
            color = MaterialTheme.colorScheme.primary, // MUST specify, it doesn't use the button's content color
        )
    }

    Spacer(modifier = Modifier.width(MaterialTheme.spacing.medium))

    OutlinedButton(
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outline), // MUST specify, it doesn't use the button's content color
        onClick = { }
    ) {
        Icon(
            imageVector = Icons.Outlined.ContentCopy,
            contentDescription = "Outline button",
            modifier = Modifier.size(ButtonDefaults.IconSize)
        )
        Spacer(modifier = Modifier.size(ButtonDefaults.IconSpacing))
        Text(
            text = "Icon outlined",
            color = MaterialTheme.colorScheme.primary, // MUST specify, it doesn't use the button's content color
        )
    }
</details>

<details>
<summary>Disabled Outline Button Example</summary>

  ```
  @Composable
  fun ColorScheme.labelDisabled(): Color  {
      return onSurface.copy(alpha = 0.38f)
  }
  ```

    OutlinedButton(
        enabled = false,
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant), // MUST specify, it doesn't use the button's content color
        onClick = { }
    ) {
        Text(
            text = "Outlined",
            color = MaterialTheme.colorScheme.labelDisabled(), // MUST specify, it doesn't use the button's content color
        )
    }

    Spacer(modifier = Modifier.width(MaterialTheme.spacing.medium))

    OutlinedButton(
        enabled = false,
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant), // MUST specify, it doesn't use the button's content color
        onClick = { }
    ) {
        Icon(
            imageVector = Icons.Outlined.ContentCopy,
            contentDescription = "Outline button",
            modifier = Modifier.size(ButtonDefaults.IconSize)
        )
        Spacer(modifier = Modifier.size(ButtonDefaults.IconSpacing))
        Text(
            text = "Icon outlined",
            color = MaterialTheme.colorScheme.labelDisabled(), // MUST specify, it doesn't use the button's content color
        )
    }
</details>

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Jetpack Compose version:** 1.4.0-beta01

**Android Studio Build:** #AI-221.6008.13.2211.9514443, built on January 20, 2023

**Kotlin version:** 1.6.4

**Device:** Any

**Comment by paulfthomas** [comment]
This is not the repo for Compose, please file your bug in the [issue tracker](https://issuetracker.google.com/issues/new?component=742043&template=1590761).
