### ISSUE TITLE
[MaterialDatePicker] The style named materialCalendarHeaderLayout did not work

### ISSUE THREAD

**Issue by fly2light** [material-components/material-components-android#3306]
**Description:** I want change the head color of calendar, but when I using the style named materialCalendarHeaderLayout, it  did not work well

**Expected behavior:**  ![QQ截图20230315105509](https://user-images.githubusercontent.com/34851343/225196826-f75729da-e890-451f-be85-62487f3c7f4d.png)

**Source code:** 
```
<resources xmlns:tools="http://schemas.android.com/tools">
    <!-- Base application theme. -->
    <style name="Theme.Onetodo" parent="Theme.Material3.Light">
        <item name="colorPrimary">@color/mac13Color</item>
<!--        <item name="materialCalendarTheme"> @style/datepicker</item>-->

        <item name="materialCalendarHeaderLayout">@style/mytitle</item>
    </style>
    <style name="datepicker" parent="ThemeOverlay.Material3.MaterialCalendar">
        <item name="materialCalendarHeaderLayout">
            @style/mytitle
        </item>
    </style>

    <style name="mytitle" parent="Widget.Material3.MaterialCalendar.HeaderLayout">
        <item name="android:background">@color/teal_200</item>
    </style>
</resources>
```

**Android API version:** `android sdk 33`

**Material Library version:**` implementation 'com.google.android.material:material:1.5.0'`

**Device:** Android Studio Emulator with profile pixel 6 pro and api 33

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
