### ISSUE TITLE
The password character appears in string.xml

### ISSUE THREAD

**Issue by qiaomai123** [material-components/material-components-android#3308]
There is a risk of plaintext disclosure in string.xml. Character resource files contain fields named with sensitive information 'password_toggle_content_description'

**Comment by paulfthomas** [comment]
Can you give more info on how this is a security risk? This is used as content description saying "Show password", the password itself is never disclosed.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still a concern.
