### ISSUE TITLE
Allow Extended FAB to shrink/extend without text

### ISSUE THREAD

**Issue by gartesk** [material-components/material-components-android#331]
As seen in https://github.com/material-components/material-components-android/blob/7b72c171ce16d61b01ce4ca71d32802102f9c76f/lib/java/com/google/android/material/floatingactionbutton/ExtendedFloatingActionButton.java#L658 ExtendedFloatingActionButton currently doesn't do anything when you call shrink/extend methods on it without any text supplied. I believe there is no reason for such behavior to be in place since text on extended fab is optional as per material design guidelines.

It currently leads to using workarounds such as setting text before calling shrink and then removing said temporary text.

Btw buganizer does not allow me to create an issue (Component ID 43953 does not exist or you do not have access)

**Comment by gsajith** [comment]
What's your expected behavior when calling shrink/extend with no text? I believe we currently use the text length in order to determine the extended width, so I'm having trouble understanding what an extended version would look like with no text.

**Comment by gartesk** [comment]
That is exactly my point, current behavior is inconsistent. Implementation says that we cannot change extension state for fab if it has no text, but it is possible to make the fab extended without text by simply not setting the text via xml (lloks like fab in attachment). Maybe the right way to do it would be to initialize it as shrunken if it has no text initially (and shrink it automatically each time the text is set to empty or null)
![fab_bug](https://user-images.githubusercontent.com/7261249/56888665-be348200-6a9e-11e9-82ad-5e8ed8b7b112.png)

**Comment by gsajith** [comment]
Could you please provide an XML snippet for the fab in your attachment? An Extended FAB without text set via XML is showing up as shrunk by default when I tried it out.

**Comment by gartesk** [comment]
It appears I was wrong about reproducing it in xml only, you have to set some properties programmatically. I created a minimalistic version of an app for showing this behavior - https://github.com/gartesk/ExtendedFabExtensionBugExample
We have something like this method in our production app: https://github.com/gartesk/ExtendedFabExtensionBugExample/blob/c2d561a037a59ecd81f6b6dcc8ca3e758b090346/app/src/main/java/com/example/playground/MainActivity.kt#L17
The idea is to share the same fab between multiple navigation tabs. Fab can either be hidden or visible on some of them, as well as not have any text, just the icon.
In this simple example we have fab initially hidden, and on click of the button we set icon to it and show it. The result is shown on the screenshot below:
![fab_bug](https://user-images.githubusercontent.com/7261249/56941450-d360ed80-6b3e-11e9-89a7-4b86d16bf1f0.jpg)
I believe this happens because shrink() does not do anything since fab initially does not have any text, I might be wrong though.

**Comment by ldjcmu** [comment]
Thanks for the example. I've created https://issuetracker.google.com/issues/131760451 to track as it seems incorrect to have a FAB with no text display like that.

**Comment by ymarian** [comment]
This works as expected as of latest alpha!
