### ISSUE TITLE
[AppBarLayout] If use with Material Toolbar,the layout editor will not preview certainly.

### ISSUE THREAD

**Issue by shizheng233** [material-components/material-components-android#3314]
**Description:**If Toolbar is surrounded by AppbarLayout, the layout editor will not properly display the preview. It will display nothing.
If  no appbarlayout
![SC01](https://user-images.githubusercontent.com/28999306/226785199-3795bff8-ee6d-4b89-8f08-0c2fd3d28d1e.png)
if have appbarlayout
![SC02](https://user-images.githubusercontent.com/28999306/226785324-54b635f2-dbd7-42e3-8031-b47d483af40e.png)

**Expected behavior:**  The layout editor is properly display the preview.

 Because I have to use the 1.8.0 SearchBar, I can't take steps to downgrade. Is there any urgent measures or something like that?

**Source code:** 
```
<com.google.android.material.appbar.AppBarLayout
        android:id="@+id/info_app_bar_layout"
        style="@style/Widget.Material3.AppBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:liftOnScroll="false">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/info_app_layout"
            style="@style/Widget.Material3.Toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

        <com.google.android.material.progressindicator.LinearProgressIndicator
            android:id="@+id/linear_progress_bar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:indeterminate="true" />

    </com.google.android.material.appbar.AppBarLayout>
```

**Minimal sample app repro:** N/A
**Android API version:**  33

**Material Library version:** 1.8.0
**Device:** N/A

**Comment by michael-winkler** [comment]
Use the latest version of stable Android Studio.

**Comment by pekingme** [comment]
Is your app using a theme extended from a `Material3` theme? I can repro the issue, when the app's theme is M2 `MaterialComponents` then set the MaterialToolbar style to an M3 `Material3` style.

**Comment by pekingme** [comment]
Feel free to reopen if the issue persists when your app using a M3 theme.

**Comment by shizheng233** [comment]
> Feel free to reopen if the issue persists when your app using a M3 theme.

Yes. Here the code:
 ```
<style name="AppTheme" parent="Theme.Material3.DayNight.NoActionBar">
        <item name="colorPrimary">@color/md_theme_light_primary</item>
        <item name="colorOnPrimary">@color/md_theme_light_onPrimary</item>
        <item name="colorPrimaryContainer">@color/md_theme_light_primaryContainer</item>
        ....
    </style>
```

**Comment by shizheng233** [comment]
> Use the latest version of stable Android Stud

I am the lastest version of it.But the newest patch can't install. So l'll try reinstall the Android Studio. Thanks.

**Comment by pekingme** [comment]
Duplicate with #3007 

The new Android Studio fixes the issue. You may need to use beta or canary.
