### ISSUE TITLE
[CollapsingToolbarLayout] When collapse draging with Toolbar, The toolbar is out of position and appear with wrong location.

### ISSUE THREAD

**Issue by XiaocXC** [material-components/material-components-android#3316]
**Description**: When collapse **draging with Toolbar**, The toolbar is out of position and appear with wrong location.
The Toolbar will **move up** and then return to normal.

**Expected behavior:** Expected behavior：the same as **draging with RecyclerView** etc... The Toolbar will not **move up**

**Source code:** Standard example code always happen. [Catalog APP](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/topappbar/TopAppBarCollapsingMediumDemoFragment.java)
[Catalog APP xml](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/topappbar/res/layout/cat_topappbar_collapsing_multiline_fragment.xml)

**Minimal sample app repro:** [Catalog APP](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/topappbar/TopAppBarCollapsingMediumDemoFragment.java)
[Catalog APP xml](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/topappbar/res/layout/cat_topappbar_collapsing_multiline_fragment.xml)

**Android API version:** 31

**Material Library version:** 1.9.0-beta01

**Device:** Any Decives

here is video to show this problem.
https://user-images.githubusercontent.com/39448642/227717183-84ffcb4b-8c26-4f2f-9e2d-638203cca23e.MOV

**Comment by XiaocXC** [comment]
sample code will also happen this bug。
https://user-images.githubusercontent.com/39448642/227717298-67f5e937-232c-447f-839e-7762ad003ead.MOV

**Comment by pekingme** [comment]
Thanks for reporting! I'll take a look the fix.

> sample code will also happen this bug。 https://user-images.githubusercontent.com/39448642/227717298-67f5e937-232c-447f-839e-7762ad003ead.MOV

Could you specify? If this is a different bug, please file as another issue.
