### ISSUE TITLE
i had migrate to androidx and now my problem is i cannot costumize my toolbar

### ISSUE THREAD

**Issue by muhammadariefhidayat** [material-components/material-components-android#332]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

**Comment by gsajith** [comment]
Hello,

It's unclear what your issue is from the context here.
Please file an issue at https://issuetracker.google.com/issues/new?component=439535 with more context.
