### ISSUE TITLE
[MaterialCheckbox] Unchecked container color not updating with custom theming instructions

### ISSUE THREAD

**Issue by ni554n** [material-components/material-components-android#3326]
[As per the spec](https://m3.material.io/components/checkbox/specs#e5e04d30-10bc-4297-a67a-c38bcece5e56), _Unchecked container_ color is supposed to be based on `colorOnSurface`. But it remains unchanged after applying [the custom theming instructions](https://github.com/material-components/material-components-android/blob/master/docs/components/Checkbox.md#implementing-checkbox-theming) or changing the `colorOnSurface` on the main theme altogether. Other states are getting the updated color as expected.

**Android API version:** 33

**Material Library version:** 1.9.0-beta01

**Comment by drchen** [comment]
Can you provide the code snippet you are using to customize the style?

I think `colorOnSurface` is used for the **outline** color of an unchecked checkbox, not the container color.

**Comment by ni554n** [comment]
I wanted to use a custom color on the unchecked checkbox (outline?), just like this:
![image](https://user-images.githubusercontent.com/2310552/229554983-d936a47a-b06d-49c3-be43-120f96da2c65.png)

I directly copy-pasted the [instruction](https://github.com/material-components/material-components-android/blob/master/docs/components/Checkbox.md#implementing-checkbox-theming), and replaced with my custom colors on the style level, then on the theme level. But it didn't change. My base theme is from `Theme.Material3.DayNight.NoActionBar`.

```xml
<style name="ThemeOverlay.App.CheckBox" parent="">
    <!-- Container colors -->
    <item name="colorOnSurface">@color/shrine_on_surface</item>
    <item name="colorPrimary">@color/shrine_primary</item>
    <item name="colorError">@color/shrine_error</item>
    <!-- Icon colors -->
    <item name="colorSurface">@color/shrine_surface</item>
    <item name="colorOnPrimary">@color/shrine_on_primary</item>
    <item name="colorOnError">@color/shrine_on_error</item>
</style>
```

If it isn't too much to ask, can you please confirm that

**Comment by ni554n** [comment]
I wanted to tint the color on the unchecked checkbox (outline? / border?), just like this:

![image](https://user-images.githubusercontent.com/2310552/229554983-d936a47a-b06d-49c3-be43-120f96da2c65.png)

I directly copy-pasted the [instruction](https://github.com/material-components/material-components-android/blob/master/docs/components/Checkbox.md#implementing-checkbox-theming), and replaced with my custom colors on the style level. The outline color didn't change. So I tried changing the color on the theme level. Also didn't change.

I was able to change the color of other attributes, but not the unchecked checkbox border / outline.

```xml
    ...
<style name="ThemeOverlay.App.CheckBox" parent="">
    <!-- Container colors -->
    <item name="colorOnSurface">#FF0000</item>
     ...
</style>
```

```xml
<style name="Theme.App" parent="Theme.Material3.DayNight.NoActionBar">
    ...
    <item name="colorOnSurface">#FF0000</item>
    ...
</style>
```

If it isn't too much to ask, can you please confirm that the theming example is working? Or am I missing something?

**Comment by ni554n** [comment]
I just cross reference the color with a color picker, and the outline seems to be using the `colorOnSurfaceVariant`, which is also the ripple color. Is this intended?

**Comment by drchen** [comment]
Hi I checked the implementation and I believe the spec on m3.material.io is wrong.

I'll ask the corresponding team to update that. Thanks for catching this!

**Comment by drchen** [comment]
They are fixing the doc. It may take a while for it to be online. : )

I'll close the issue for now. Thanks again!!
