### ISSUE TITLE
Toolbar eat touch

### ISSUE THREAD

**Issue by SudoDios** [material-components/material-components-android#3327]
HI.
How to disable eating touch on toolbar ?
`// Toolbars always eat touch events, but should still respect the touch event dispatch`

**Comment by drchen** [comment]
Not sure why you want to do that but I think you can create a custom toolbar class that extends Toolbar and override its onTouchEvent()?

Since it's a behavior implemented by appcompat toolbar, not the Material library, I'll close the issue for now.
