### ISSUE TITLE
CircularRevealCardView and rippleColor

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [material-components/material-components-android#333]
If I change the ripple color via XML, it is working:
```
app:rippleColor="@android:color/holo_green_light"
```

But this is not working:
```
cardViewBackground.rippleColor = ColorStateList.valueOf(ContextCompat.getColor(context, android.R.color.holo_green_light))
```

And this is not working too:
```
cardViewBackground.setRippleColorResource(android.R.color.holo_green_light)
```

Any way to solve this issue?

**Comment by gsajith** [comment]
Hi Javier! It's possible you'll need to invalidate or redraw the CircularRevealCardView in order to see the new ripple color.

Have you tried calling invalidate() on the CircularRevealCardView?

**Comment by JavierSegoviaCordoba** [comment]
Hello @gsajith, I am trying but it doesn't work for me:

````
cardView.rippleColor = ColorStateList.valueOf(ContextCompat.getColor(this, android.R.color.holo_green_light))
//or
cardView.setRippleColorResource(android.R.color.holo_green_light)

cardView.invalidate()
````

**Comment by gsajith** [comment]
Looks like this issue is being tracked in https://issuetracker.google.com/issues/131409509. Please follow that issue for future updates.

**Comment by JavierSegoviaCordoba** [comment]
Yeah I am the owner of that issue
