### ISSUE TITLE
AutoCompleteTextView text is cut off when height is limited

### ISSUE THREAD

**Issue by yazmnh87** [material-components/material-components-android#3339]
**Description:** 
I have a AutoCompleteTextView 'com.google.android.material:material:1.8.0'
<com.google.android.material.textfield.TextInputLayout
                android:id="@+id/ti_type"
                style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu"
                android:layout_width="0dp"
                android:layout_height="35dp"
                android:background="@null"
                app:layout_constraintTop_toBottomOf="@id/ti_incomeName"
                app:layout_constraintStart_toStartOf="parent"
                android:layout_marginTop="5dp"
                app:layout_constraintWidth_percent=".45"
                android:layout_marginRight="5dp"
                >
                
                <AutoCompleteTextView
                    android:id="@+id/tv_auto_incomeType"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:maxHeight="100dp"
                    android:autoSizeMinTextSize="8sp"
                    android:hint="Type"
                    android:textSize="8sp"
                    android:enabled="false"
                    android:inputType="none"
                    android:background="@drawable/border2"
                    android:textColor="@color/black" />
                    
            </com.google.android.material.textfield.TextInputLayout>
            
            However, when an item is selected the TextView inside is cut off, Here is my TextView inside
            <TextView
                 xmlns:android="http://schemas.android.com/apk/res/android"
                 xmlns:app="http://schemas.android.com/apk/res-auto"
                 android:layout_width="match_parent"
                 android:layout_height="match_parent"
                 android:text="Hello"
                 android:textSize="14sp"
              />
             
![ksnip_20230406-102536](https://user-images.githubusercontent.com/25097299/230439556-e7c2f57e-d49f-4186-80b2-4f723718bc0f.png)
 
              But the result when an Item selected is this

**Expected behavior:** Screenshots and/or description of expected behavior

Expected behavior is that the Text rendered would show as the hint does
![ksnip_20230406-102633](https://user-images.githubusercontent.com/25097299/230439749-e981241e-ae92-47e9-9fb4-b842637c7ebf.png)

**Source code:** The code snippet which is causing this issue
<com.google.android.material.textfield.TextInputLayout
                android:id="@+id/ti_type"
                style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense.ExposedDropdownMenu"
                android:layout_width="0dp"
                android:layout_height="35dp"
                android:background="@null"
                app:layout_constraintTop_toBottomOf="@id/ti_incomeName"
                app:layout_constraintStart_toStartOf="parent"
                android:layout_marginTop="5dp"
                app:layout_constraintWidth_percent=".45"
                android:layout_marginRight="5dp"
                >
                <AutoCompleteTextView
                    android:id="@+id/tv_auto_incomeType"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:maxHeight="100dp"
                    android:autoSizeMinTextSize="8sp"
                    android:hint="Type"
                    android:textSize="8sp"
                    android:enabled="false"
                    android:inputType="none"
                    android:background="@drawable/border2"
                    android:textColor="@color/black" />
            </com.google.android.material.textfield.TextInputLayout>

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

https://github.com/yazmnh87/materialDropDownMenuIssue.git

**Android API version:** Android API version here

33

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
'com.google.android.material:material:1.8.0'

**Device:** Device on which the bug was encountered here

emulator pixel 3a

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
It's working as intended as EditText/AutoCompleteTextView has inherited insets. 

You can either remove the insets by following the discussion here: https://stackoverflow.com/questions/32082131/how-can-i-remove-all-default-padding-from-edittext

Or just make your AutoCompleteTextView a bit larger to account for the insets - I think 48dp should work in your case.

**Comment by yazmnh87** [comment]
@drchen Thank you so much for your reply.  I'll try this, thank you again:)
