### ISSUE TITLE
[MaterialSwitch] The animation of the thumb is using incorrect timings

### ISSUE THREAD

**Issue by Emplexx** [material-components/material-components-android#3341]
**Is your feature request related to a problem? Please describe.**
Ever since 1.8.0-beta01 the thumb stretching animation is using incorrect timings. This is because in beta01, the switch animations were updated to use motion theming, according to the changelog. 
Prior to beta01, `mtrl_switch_thumb_pre_morphing_duration` was 100 ms and `mtrl_switch_thumb_post_morphing_duration` was 150 ms, and in beta01 they were assigned `m3_sys_motion_duration_short3` (150ms) and `m3_sys_motion_duration_medium1` (250ms) respectively. Those timings are different, which results in an animation that looks broken and out of sync

**Describe the solution you'd like**
The motion duration tokens used (in [this file](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/materialswitch/res/values/integers.xml)) should be replaced with those that match the old timings, which would be `m3_sys_motion_duration_short2` (100ms) for  `mtrl_switch_thumb_pre_morphing_duration`, and `m3_sys_motion_duration_short3` (150ms) for `mtrl_switch_thumb_post_morphing_duration`. 
Also, ideally there should be a single duration for the entire animation, and the pre and post morphing durations should be using fractions of that duration (2/5 and 3/5 respectively), but I am not sure if that's possible in xml

**Additional context**
The animation I'm talking about occurs not when you interact with the switch directly, but when you change its state through other means (something like `switch.isChecked = !switch.isChecked`). 

Video recordings:

The animation in 1.8.0-alpha03:
https://user-images.githubusercontent.com/64900852/230724952-24d498d7-bc37-49ed-a04a-7576289d275f.mp4

The broken animation in 1.8.0-beta01 and above:
https://user-images.githubusercontent.com/64900852/230725004-5382c034-c817-415a-bd78-88e9b010dd07.mp4

**Comment by drchen** [comment]
Duplicate to #3340
