### ISSUE TITLE
[Top App Bar] Scrolling on Collapsing Title area causes the app bar to over scroll

### ISSUE THREAD

**Issue by ni554n** [material-components/material-components-android#3342]
**Description:** Notice the app bar won't over scroll if the content below is scrolled a little bit.

https://user-images.githubusercontent.com/2310552/230742002-e6b26643-c87a-4146-9eef-a17007022dad.mp4

This is from M3 Catalog app, but the same issue happens on my app too.

**Android API version:** 33

**Material Library version:** 1.9.0-beta01

**Comment by Agonizedcupid** [comment]
Hello,
As an individual who is novel to the realm of open-source contribution, I humbly request your esteemed guidance on how I may embark upon this journey with you. I am fervently passionate about the prospect of making contributions towards open-source endeavors and seek your kind assistance in enabling me to do so. In terms of my personal background, I have consistently engaged in problem-solving exercises and participated in competitions from my academic days until the present time. Additionally, I possess an impressive track record of over five years in the field of Android app development.

**Comment by ni554n** [comment]
Just found out this issue has been fixed in `1.10.0-alpha01`

**Comment by Agonizedcupid** [comment]
https://user-images.githubusercontent.com/20151627/230788835-2adfe28f-ddba-4adf-b49f-0f2329c97746.mp4

I hope it will help you. Let me know if you need further assistance.
Thanks
