### ISSUE TITLE
[TextInputLayout] 1.8.0 ver, cursor color is always white when error situation.

### ISSUE THREAD

**Issue by Rocher0724** [material-components/material-components-android#3345]
When I set an error in textinputlayout in version 1.8.0, the cursor color is always white.

Both outlined and filledbox are applicable and I was able to fix this by lowering the version to 1.6.0.

In version 1.8.0, no setting through style.xml or them.xml could change white.

**Comment by drchen** [comment]
It's fixed in https://github.com/material-components/material-components-android/commit/c598ccd51ec68828f241301455fb3f59369fe467

We added an attribute and a setter to set the cursor color under errors.

The change is supposed to be published with upcoming 1.10.0-alpha02.
