### ISSUE TITLE
[Tabs] Tab item selection animation is cut at the top and bottom

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#3350]
**Description:** When tapping on a tab item, there is an animation that indicated that the user has selected that particular item. M3 shows that animation in form of a small circle that quickly grows and then disappears. However, when the circle reaches the vertical size of the tabs, it gets cut at the top and bottom. See below video captured from the M3 Catalog app ("Tabs" / "Controllable Tabs Demo"): 
https://github.com/patrickfrei/test_coding/blob/main/issue_tab_select_animation.mp4

**Expected behavior:** Animation is not cut at the top and bottom but always shows the whole circle. Is there a possibility to achieve that behavior or is it eventually a bug?

**Source code:** See source code of the M3 Catalog app ("Tabs" / "Controllable Tabs Demo").

**Minimal sample app repro:** See below video captured from the M3 Catalog app ("Tabs" / "Controllable Tabs Demo"): 
https://github.com/patrickfrei/test_coding/blob/main/issue_tab_select_animation.mp4

**Android API version:** Android API 33

**Material Library version:** 1.10.0-alpha01

**Device:** Various emulators (e.g. Pixel 6) and real devices (e.g. Nokia 7.2)

**Comment by drchen** [comment]
I think that's working as intended. (And sort of consistent to other similar situations like list items.)

Letting ripples grows over the tab bounds doesn't seem like a good UX. : )
