### ISSUE TITLE
[SearchBar] Clicking searchbar not showing keyboard

### ISSUE THREAD

**Issue by abdalla19977** [material-components/material-components-android#3351]
**Description:** Clicking searchbar not showing the keyboard

**Expected behavior:** keyboard to appear immediatly after clicking

**Source code:** 
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.google.android.material.search.SearchBar
        android:id="@+id/searchBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="@string/search"
        app:layout_constraintTop_toTopOf="parent" />

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv_companies"
        tools:listitem="@layout/item_company"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/searchBar" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Android API version:** 33

**Material Library version:** 1.8.0 and 1.8.0-alpha03 

**Device:** Samsung and pixel emulator

**Comment by drchen** [comment]
I can't reproduce the issue. Can you check if this is still happening with the latest library version?

**Comment by abdalla19977** [comment]
I was putting trying to type text immediately inside the search bar
I will close the issue

**Comment by codeCasa** [comment]
I am still getting this issue on the following version "com.google.android.material:material:1.10.0-alpha02" with a UI XML not much different from above.

**Comment by green985** [comment]
I have a same problem like this. 

When I implement searchBar without searchView keyboard doesn't open. 
Also If I open keyboard with force (I set clickListener to searchBar and open keyboard) searchBar doesn't get any focus and also not get any text. 

Version 1.12.0-alpha03
