### ISSUE TITLE
[SearchView] backgroundTint can't be set to white

### ISSUE THREAD

**Issue by sheilambadi** [material-components/material-components-android#3355]
**Description:** 

As per the documentation I've assigned the color white to `?attr/colorSurface` but the background color of the search view isn't changing. When I change it to a darker color such as green `#337A35` the background color changes.

**Expected behavior:** 
The background color should be set to white.

**Source code:** 
```
<style name="AppTheme" parent="Theme.Material3.Light.NoActionBar">
    <item name="colorSurface">@color/colorSurface</item>
</style>
```

**Android API version:** 31

**Material Library version:** 1.8.0

**Device:** Pixel 4 (in emulator)

**Comment by drchen** [comment]
It's an expected (yet confusing) behavior. 

Currently the actual background color is calculated by colorSurface + elevation overlay color - and the default color surface value with M3 themes is white. (So if you change it to white it's basically a no-op.)

Good news is this behavior will probably be deprecated soon. (And you will be able to set the background to white directly.)

For now, if you want a white background you can extend `Widget.Material3.SearchView` and override `?attr/materialThemeOverlay` with a custom theme overlay (extending `ThemeOverlay.Material3.Search`) and set `?attr/elevationOverlayEnabled` to `false` in the custom theme overlay. 

Hope this helps.
