### ISSUE TITLE
[ModalBottomSheet] Is there a way to make ModalBottomSheet draggable only by specific view?

### ISSUE THREAD

**Issue by zer0Ambit1on** [material-components/material-components-android#3362]
Just wanna know it is possible to do it? For example, i want dragging to be turn on only when i "drag" top view(Title for example) of my ModaBottomSheet. in other cases it should be turned off.

**Comment by zer0Ambit1on** [comment]
How can I apply the custom behavior to modalbottomsheet? I'm trying to do that, but getting invalidcast exception. Can you pls give example of it?

**Comment by drchen** [comment]
Sorry it's my bad. There seems no direct way to replace the default bottom sheet behavior within a modal bottom sheet, except for resource overriding. 

You can try to provide your own custom value of `@string/bottom_sheet_behavior` and set it to the custom behavior class you create.  

What is the invalid cast exception you are getting? And how do you customize the behavior?

**Comment by zer0Ambit1on** [comment]
Sorry, now I can't show you my example, but I'll do it tomorrow.

**Comment by zer0Ambit1on** [comment]
//customBottomSheetBehavior. with view to drag.
class CustomBottomSheetBehavior<V: View>: BottomSheetBehavior<V> {
    constructor(): super()
    constructor(ctx: Context, attrs: AttributeSet): super(ctx, attrs)

    var draggableView: View? = null

    override fun onInterceptTouchEvent(parent: CoordinatorLayout, child: V, event: MotionEvent): Boolean {
        draggableView?.let {
            isDraggable = parent.isPointInChildBounds(it, event.x.toInt(), event.y.toInt())
        }
        return super.onInterceptTouchEvent(parent, child, event)
    }
}

init behavior and try to cast:
val behavior: BottomSheetBehavior<*> = (dialog as BottomSheetDialog).behavior
val customBehavior: CustomBottomSheetBehavior<*> = behavior as CustomBottomSheetBehavior.//in this place i Can't cast (this cast can never succeed)
Don't know what to do next.

I didn't quite understand what you mean by "provide your own custom value of @string/bottom_sheet_behavior and set it to the custom behavior class". Am I doing something wrong? can you show some example?

**Comment by zer0Ambit1on** [comment]
issue was solved. thanks foк you help.

**Comment by drchen** [comment]
Awesome. : )   Happy to help!
