### ISSUE TITLE
[Table] Will andorid compose support table view?

### ISSUE THREAD

**Issue by jarvis1801** [material-components/material-components-android#3363]
**Is your feature request related to a problem? Please describe.**
Since the table view is easy to read a amount of data for user, and material doesn't have this component in currectly

**Describe the solution you'd like**
Maybe create a composable to do that

**Describe alternatives you've considered**
/

**Additional context**
Please consider it, if yes also please consider to make the fix header and column

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
Hello, please redirect your question to the Material Compose [issue tracker](https://b.corp.google.com/issues/new?component=742043&template=1590761). This is the Material Android View's repository, not the Compose one.
