### ISSUE TITLE
is not support in android 4.4.2？

### ISSUE THREAD

**Issue by huanghaoming** [material-components/material-components-android#337]
my checkbox custom style is no work。。。 
after my test，1.1.0-alpha02 is ok。。。。1.1.0-alpha03 04 05 is no ok。。。。。

  <CheckBox
        android:id="@+id/cb_emoji"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:button="@drawable/bg_smile_face"
        android:clickable="true" />

“android:button”   is  no work

**Comment by ldjcmu** [comment]
Can you please paste your style here with screenshots in alpha02 and alpha03

**Comment by huanghaoming** [comment]
<CheckBox
                    android:id="@+id/cb_emoji"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentLeft="true"
                    android:button="@drawable/bg_smile_face"
                    android:clickable="true" />

**Comment by huanghaoming** [comment]
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/weixin_keyboard" android:state_checked="true"/>
    <item android:drawable="@drawable/weixin_smile" android:state_checked="false"/>
    <item android:drawable="@drawable/weixin_smile"/>
</selector>

**Comment by huanghaoming** [comment]
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/weixin_keyboard" android:state_checked="true"/>
    <item android:drawable="@drawable/weixin_smile" android:state_checked="false"/>
    <item android:drawable="@drawable/weixin_smile"/>
</selector>

**Comment by ldjcmu** [comment]
This snippet from the Checkbox docs might be relevant. It's not clear to me what about the button drawable is not working given the lack of screenshots.

Material Styles
Using a Material Components theme with MaterialCheckBox will match the color of CheckBox views to your theme's palette. If you want to override this behavior, as you might with a custom drawable, set the useMaterialThemeColors parameter to false.

<CheckBox xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  app:useMaterialThemeColors="false"/>
