### ISSUE TITLE
NavigationView Component (Navigation Drawer) is showing completely box edge, instead of a bit rounded corner by default

### ISSUE THREAD

**Issue by RakaDoank** [material-components/material-components-android#3391]
Hello, i'm quite new in Android here who came from a web dev

I'm using the navigation drawer and intended to show permanently on larger screen.

But i didn't see any rounded corner by default like i saw on the [NavigationDrawer.md](https://github.com/material-components/material-components-android/blob/master/docs/components/NavigationDrawer.md) docs. It showed completely like a box edge.
(Just ignore that silly switchs)
![image](https://github.com/material-components/material-components-android/assets/23445738/a8372b3f-11d6-4b3f-84a4-395f1861a7ca)

I actually tried to increase the `drawerLayoutCornerSize`, but it didn't affect at all.

Here the simple of my main activity xml layout
```
<androidx.drawerlayout.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/aColor"
    tools:context=".ActivityMainApp">

    <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <com.google.android.material.navigation.NavigationView
                        android:id="@+id/sidebarNavigationView"
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:layout_gravity="start"
                        app:layout_constraintLeft_toLeftOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        app:menu="@menu/youKnowIt" />

            <androidx.fragment.app.FragmentContainerView
                        android:id="@+id/nav_host_fragment"
                        android:name="androidx.navigation.fragment.NavHostFragment"
                        android:layout_width="0dp"
                        android:layout_height="match_parent"
                        android:layout_marginStart="24dp"
                        app:defaultNavHost="true"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintLeft_toRightOf="@id/sidebarNavigationView"
                        app:layout_constraintRight_toRightOf="parent"
                        app:navGraph="@navigation/nah" />

    </androidx.constraintlayout.widget.ConstraintLayout>

</androidx.drawerlayout.widget.DrawerLayout>
```

and with these dependencies
`androidx.core:core-ktx:1.8.0`
`androidx.appcompat:appcompat:1.6.1`
`com.google.android.material:material:1.9.0`
`androidx.drawerlayout:drawerlayout:1.2.0`

A large half sure, i missed a thing rather than component itself.
Thank you.

**Comment by imhappi** [comment]
Hello!

The rounded corner is only if the drawerlayout is able to be pulled out/dismissed, as the rounded corners indicate that it is 'temporary'. Since you have the NavigationView in a constraint layout, I believe you are using version of the NavigationView that is permanently there, so the corners are not rounded. Hope this helps!
