### ISSUE TITLE
[BottomSheet] Rounded corners when expanded

### ISSUE THREAD

**Issue by genaray** [material-components/material-components-android#3392]
Modal bottom sheets now have rounded corners once expanded #1278 so far.
"Normal" bottom sheets, which are not a dialog or modal, do not have this behavior by default.

Shouldn't that be introduced? 
Is there already a way to make the corners round once expanded for a normal bottomsheet?

**Comment by imhappi** [comment]
Hi @genaray  I'm not sure what you mean by "normal" bottom sheet. Do you mean the standard bottom sheets?

In our m3 style, they are already rounded, but you can set `shouldRemoveExpandedCorners` to false in the bottom sheet style to round the corners
