### ISSUE TITLE
[Localisation] Localisation is not changing with AppCompatDelegate.setApplicationLocales

### ISSUE THREAD

**Issue by shegaa** [material-components/material-components-android#3394]
**Description:**

I have 2 languages in app. I change them with AppCompatDelegate.setApplicationLocales(LocaleListCompat) on dialogue click.
On API version 33 it works as intended, but on API version 28 it works like this: 
when I choose language 1 it sets localisation to language 1, but Material Components strings stay on previous language. 
Starting state: (on first app run it sets AppCompateDelegate language based on phone Locale)
Localisation: language 1, Material Components : language 1
So after first change it will be in a situation like this:
Localisation: language 2, Material Components : language 1
On next change it will be:
Localisation: language 1, Material Components: language 2.
And so on.
It is always one change(or one refresh) behind

**Android API version:** 28

**Material Library version:** 1.6.1, tried it with 1.9.0 and still doesn't work

**Device:** Pixel 3(emulator with API 28) and Samsung Galaxy S8(API 28)

**Comment by imhappi** [comment]
Hi @shegaa 
If you're only experiencing this on API < 33, it makes me think that the issue has to do with https://developer.android.com/guide/topics/resources/app-languages#android12-impl
Have you added the correct tags to your manifest?

**Comment by imhappi** [comment]
Going to close this as I don't believe this is an issue on the Material Library side

**Comment by shegaa** [comment]
Sorry, I have added it to the manifest but forgot to add it to the post. I made a workaround:
AppCompatDelegate logic is done either way but I am updating Locale on API<33. It works but it feels redundant to  update both.
