### ISSUE TITLE
[DatePicker] keyboard in landscape hides content

### ISSUE THREAD

**Issue by Redwid** [material-components/material-components-android#3395]
**Description:** DatePicker for full screen on landscape works incorrectly with keyboard on - it hides "Start date" and "End date' fields. 

![image](https://github.com/material-components/material-components-android/assets/10167374/39db85f8-2bb3-4e1d-848d-36c6d66cfb9a)

**Expected behavior:** "Start date" and "End date' fields should be visible and accessible in landscape mode.
![image](https://github.com/material-components/material-components-android/assets/10167374/09e40056-3c5c-44dd-98ce-5976946f525c)

**Android API version:** Android API 33

**Material Library version:** 1.3.0

**Device:** Pixel 7 Pro

**Comment by imhappi** [comment]
I'm unable to repro this on the Pixel 7 Pro with the latest library version
