### ISSUE TITLE
[MaterialDatePicker] Expose user selected input mode

### ISSUE THREAD

**Issue by mtotschnig** [material-components/material-components-android#3397]
I would like to manage the user preferred mode of using the MaterialDatePicker. So whenever the dialogue is closed, I would store the input mode it was used in, which would allow to open it with the same mode next time. MaterialTimePicker has this affordance by means of method getInputMode.

MaterialDatePicker should update its internal variable inputMode, when the headerToggleButton is toggled, and provide read access to it.

If there is interest in adding this, I'll happily provide a pull request.

**Comment by paulfthomas** [comment]
@mtotschnig feel free to create the PR, thanks for the suggestion!

**Comment by paulfthomas** [comment]
Fixed by https://github.com/material-components/material-components-android/commit/4d8043453e631c36b38ea19c3241b14b7f41b558
