### ISSUE TITLE
[NavigationView] Menu items marked as "checked" appear with bold text since the 1.8.0-alpha03 release

### ISSUE THREAD

**Issue by adil-hussain-84** [material-components/material-components-android#3415]
**Description:** Menu items marked as "checked" appear with bold text since the "1.8.0-alpha03" release.

**Expected behaviour:** Menu items marked as "checked" appear without bold text as in the "1.7.0" and earlier releases.

**Minimal sample app repro:** I've put together a minimal app that demonstrates the issue [here](https://github.com/adil-hussain-84/android-material-experiments/tree/main/app1). Run the app as is and tap on the menu items to toggle them between "checked" and "unchecked" state. You'll see that checked and unchecked menu items appear without bold text, as follows:

![ScreenshotBefore](https://github.com/material-components/material-components-android/assets/17025131/3a0a6e5e-ff36-4897-83d8-82f54de9fdaa)

Then upgrade the "material" library from version "1.7.0" to "1.8.0" or "1.9.0" [here](https://github.com/adil-hussain-84/android-material-experiments/blob/main/app1/build.gradle#L39). This time you'll see that checked menu items appear with bold text, as follows:

![ScreenshotAfter](https://github.com/material-components/material-components-android/assets/17025131/ed54eda9-0c4f-4e75-99d3-92938b451e1f)

**Android API version:** I am seeing this behaviour for apps targeting API Level 33 (i.e. Android 13).

**Material Library version:** I am seeing the change in behaviour since the "1.8.0-alpha03" release.

**Device:** All devices. The issue is agnostic of device.

If the change in behaviour is intentional, I'd appreciate it if somebody can guide me on how to instruct the `NavigationView` to not show checked menu items with bold text 🙏

**Comment by imhappi** [comment]
Hi @adil-hussain-84 this change is intentional for accessibility requirements

Currently there is no option that we support to not bold the checked menu item, and I don't believe that we want to enable this as it is a part of the Google Accessibility Requirements. If you really do not want this, you may be able to get around bolding the text by specifying a custom font, and have the bold font copy the attributes as the regular font: https://developer.android.com/develop/ui/views/text-and-emoji/fonts-in-xml

**Comment by adil-hussain-84** [comment]
@imhappi: Please could you explain what you mean by "this change is intentional for accessibility requirements" 🙏 Why is it an accessibility requirement for the text to be bold? Is not the background colour change and, in the case of checkable menu items which display a checkbox, the tick in the checkbox enough of an indicator that the menu item is selected?

For a concrete example of how this change in behaviour has negatively effected one of my user interfaces, see the following screenshot:

<img src="https://github.com/material-components/material-components-android/assets/17025131/dcf45c76-1572-49b3-ba12-106df854dafd" alt="Screenshot of NavigationView in an app" width="270">

The two menu items near the top which have a checkbox to the left of them are now more prominent than I want them to be. I would like for them to have equal font weighting as the other menu items in the NavigationDrawer.

**Comment by adil-hussain-84** [comment]
To add to my previous message, I see that the behaviour of checkable menu items in an Activity's standard options menu is not consistent with what has been changed in this library. The text of checked menu items is not bold, as follows:

<img src="https://github.com/material-components/material-components-android/assets/17025131/9ef959cd-19ec-4865-9ad3-be2b41c4b350" alt="Screenshot of checked menu items in an Activity's standard options menu" width="270">

**Comment by paulfthomas** [comment]
You can try to use `setItemTextAppearanceActiveBoldEnabled(false)`, see [doc](https://github.com/material-components/material-components-android/blob/022e2177704915eca6b0e7fd104cba98ae38509e/docs/components/NavigationDrawer.md#text-attributes)

**Comment by adil-hussain-84** [comment]
@paulfthomas Thanks a million 👍 That did the trick. I was in the process of a nasty workaround. I'm so glad I don't have to continue down that path.

For anyone else facing this same problem, it's the [NavigationView](https://developer.android.com/reference/com/google/android/material/navigation/NavigationView) that you have to call the `setItemTextAppearanceActiveBoldEnabled(false)` method on. Also, you have to use version `1.11.0-alpha01` or later of the Material Components library and bump up your application's target SDK version to API level 34 or later. I've demonstrated all of this in [this](https://github.com/adil-hussain-84/android-material-experiments/tree/main/app2) sample application.

**Comment by paulfthomas** [comment]
@adil-hussain-84 glad it fixed your issue!
