### ISSUE TITLE
[Bottom Sheet] Insets animation when keyboard is shown should be opt-in

### ISSUE THREAD

**Issue by mr-thierry** [material-components/material-components-android#3424]
**Description:** version 1.9 of the library was recently released and contained this change:
"Added animation for bottom sheet position when keyboard is shown using WindowInsetsAnimationCompat API" (See https://github.com/material-components/material-components-android/commit/697d93a854571a5b70b617654395e04556404fc4)

This breaks our app because we already have a global insets animation that animate every views on the screen. As such, we have to do a special case where we see the insets animator to null with the bottom sheet. 

The line that sets the insets animator is here: https://github.com/material-components/material-components-android/commit/697d93a854571a5b70b617654395e04556404fc4#diff-968577e4c5ac2c623d4d51c388472c0cdd786ae7497f13cf6c26e9e11df655cd

**Expected behavior:** The `BottomSheetBehavior` should set the insets animation only if configured to do so.

**Material Library version:** 1.9

I opened this bug to start the discussion and ask for feedback. I haven't provided source code or minimal sample app repro. I think the description is pretty clear. But I would be happy to provide an example. :)

**Comment by dsn5ft** [comment]
Hi @mr-thierry. In general we do want our bottom sheet component to animate nicely by default when the keyboard is shown. And I don't think there's a great way for us to automatically determine on the library side whether the app has a conflicting WindowInsetsAnimationCallback configuration.

Would you be able to do the following to disable the bottom sheet's default WindowInsetsAnimationCallback?

```
bottomSheetView.post(() -> ViewCompat.setWindowInsetsAnimationCallback(bottomSheetView, null));
```

Or if you have a custom callback you want to apply to the bottom sheet:

```
bottomSheetView.post(() -> ViewCompat.setWindowInsetsAnimationCallback(bottomSheetView, myCustomCallback));
```

**Comment by mr-thierry** [comment]
@dsn5ft Thanks for the answer. I totally agree that having the component animate with the keyboard is nice. That's why we did it for other components in our app. :)

And disabling the animation callback with `bottomSheetView.post(() -> ViewCompat.setWindowInsetsAnimationCallback(bottomSheetView, null));` does work. 

My comment is mostly to make the behavior "opt-in", or at least configurable. Something similar to the current configuration properties, like `expandedOffset` or `hideable`. The component could have a `animateWithKeyboard` property. I wouldn't mind being default to true, but setting it to false would avoid the user of the component to use `ViewCompat.setWindowInsetsAnimationCallback(bottomSheetView, null));`, and would also make the behavior explicit.

**Comment by dsn5ft** [comment]
Thanks for confirming that setting the callback to null on your side works. We can consider adding an attribute, but in general the Android framework pattern is that components add default listeners/callbacks, and then those can be customized or disabled by developers as needed by using the same APIs (as opposed to adding boolean attributes for every setter used like this).

**Comment by dsn5ft** [comment]
And I do think that we would want the attribute to default to true anyway, since this behavior should work for most apps out of the box.
