### ISSUE TITLE
[Carousel] Vertical carousel

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3449]
It would be nice to be able to create a vertical carousel (this would be especially useful for landscape-oriented apps).

**Comment by imhappi** [comment]
This is actually in the works right now :)

**Comment by imhappi** [comment]
Sorry, realized this never got updated. Vertical scrolling capability was implemented in https://github.com/material-components/material-components-android/commit/6b48d3bb80576d649f7218e1bf29d0ecfa14d8f4
