### ISSUE TITLE
[BottomAppBar] Unexpected height increase when IME is shown

### ISSUE THREAD

**Issue by MrHadiSatrio** [material-components/material-components-android#3452]
**Description:** Whenever an IME is shown, `BottomAppBar` would expand its height to cover all other UI elements.

https://github.com/material-components/material-components-android/assets/22863610/0716d586-dcee-46a9-b734-bc0025ba29a8

**Expected behavior:** There should not be any change in height.

**Source code:** https://github.com/MrHadiSatrio/Journal3/blob/c4953b5cab9c1e8e4327d5308af4cd18ef9adcbe/app-android-journal3/src/main/res/layout/activity_edit_a_moment.xml

**Minimal sample app repro:** https://github.com/MrHadiSatrio/Journal3

**Android API version:** API 33

**Material Library version:** 1.9.0

**Device:** Google Pixel (Emulator)

**Comment by imhappi** [comment]
Hi! I'm unable to repro this on a Pixel4A emulator on API 34. Which device can you repro this on? Also, can you repro this on a simpler demo?

**Comment by MrHadiSatrio** [comment]
Thanks for responding @imhappi. After investigating further, I think this is not related to `BottomBar`. The issue persisted even with `Toolbar`.

I think it has to do with `windowSoftInputMode`. This particular activity behaved as if it's told to `adjustResize`. Explicitly stating `adjustPan` fixed the issue. Maybe [this](https://android-developers.narkive.com/hQ2JkGbv/default-adjust-for-android-windowsoftinputmode) has something to do with it, but I couldn't quite grasp why the issue doesn't happen on other activities in that project despite all having a similar layout structure.

**Comment by imhappi** [comment]
Glad you figured it out :) will close this issue
