### ISSUE TITLE
[BottomNavigation]  Bad links in documentation 

### ISSUE THREAD

**Issue by bubbleguuum** [material-components/material-components-android#3455]
In the documentation page for the BottomNavigation, all "(see all states)" links are bad (link to non-existing file).
I have also some doubt about the information in the related table cells being up-to-date: 

https://github.com/material-components/material-components-android/blob/master/docs/components/BottomNavigation.md

**Comment by imhappi** [comment]
Fixed in https://github.com/material-components/material-components-android/commit/1785bbfabeabe747924c13e49050d2e8da585fd4
