### ISSUE TITLE
transition for recreating activity 🌚🌞

### ISSUE THREAD

**Issue by MasterOfTouch** [material-components/material-components-android#346]
or may be some default fade transition when switching between day/night
```
AppCompatDelegate.setDefaultNightMode(MODE_NIGHT_NO/MODE_NIGHT_YES)
 (requireActivity() as AppCompatActivity).delegate.applyDayNight()
```
or may be I need some help in this case

**Comment by dsn5ft** [comment]
Not sure exactly what the request is here, but it seems similar to #345. 

As mentioned there, the AppCompat team recently did some work to improve AppCompatDelegate#setDefaultNightMode, so it now handles recreating your activity and applying DayNight. Very soon I will update our AppCompat version and the Catalog app will correctly transition between day/night.
