### ISSUE TITLE
Snackbar doesn't appear above FAB after FAB rotation (ViewPropertyAnimator)

### ISSUE THREAD

**Issue by postfixNotation** [material-components/material-components-android#347]
I highly appreciate the Snackbar#setAnchorView functionality but there's a bug I just found.
When I press a FAB which is positioned inside a BottomAppbar (centered), I let the FAB rotate 135° using ViewPropertyAnimator like:

ViewPropertyAnimator animator = mFab.animate().rotation(135);

Now if I show a snackbar, anchored to the Fab, it appears behind the FAB at approx. the same height.

If I don't use the animator, everything works as expected. This is most probably due to the top of the FAB being rotated. If the rotation is 360° everything works as expected also. 

Hope you can fix this!
Thanks!

**Comment by ldjcmu** [comment]
We're looking into this at http://issuetracker.google.com/132334480

**Comment by ymarian** [comment]
yeah not sure what we can do about this maybe consider just using a VectorDrawable for your Fab icon and rotate that instead of rotating the entire view.

**Comment by postfixNotation** [comment]
That's actually what I exactly did to work around this issue and it works
perfectly fine!
Thx!

ymarian <notifications@github.com> schrieb am Fr., 28. Feb. 2020, 17:22:
