### ISSUE TITLE
[NestedScrollView] Bug: NestedScrollView doesn't scroll horizontally for chips, yet HorizontalScrollView works fine

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#3474]
**Description:** Full description of issue here
I'm trying to show chips in a horizontal-scrolling container, meaning NestedScrollView with horizontal LinearLayout, and chips inside of the LinearLayout.

**Expected behavior:** Screenshots and/or description of expected behavior
To have it scrollable horizontally.
When I use HorizontalScrollView instead, it works fine.

[studio64_2023-07-11_11-03-43.zip](https://github.com/material-components/material-components-android/files/12012221/studio64_2023-07-11_11-03-43.zip)

[studio64_2023-07-11_11-08-27.zip](https://github.com/material-components/material-components-android/files/12012273/studio64_2023-07-11_11-08-27.zip)

**Source code:** The code snippet which is causing this issue

```
<androidx.core.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" android:fillViewport="true" tools:context=".FirstFragment">

    <LinearLayout
        android:layout_width="wrap_content" android:layout_height="wrap_content"
        android:orientation="horizontal">

        <com.google.android.material.chip.Chip
            android:id="@+id/chip" android:layout_width="wrap_content"
            android:layout_height="wrap_content" android:layout_marginEnd="6dp"
            android:ellipsize="end" android:text="Some text1"
            android:textColor="?android:textColorPrimary" app:chipBackgroundColor="@null"
            app:chipEndPadding="15dp" app:chipIcon="@drawable/ic_launcher_foreground"
            app:chipIconSize="12dp" app:chipIconTint="?android:textColorPrimary"
            app:chipStartPadding="15dp" app:chipStrokeColor="?android:textColorPrimary"
            app:chipStrokeWidth="1dp" app:ensureMinTouchTargetSize="true" />

... - same chips, multiple times
    </LinearLayout>

</androidx.core.widget.NestedScrollView>
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

[My Application.zip](https://github.com/material-components/material-components-android/files/12012222/My.Application.zip)

**Android API version:** Android API version here
Android 13 (API 33)

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
Sadly the new project wizard became a mess and I don't understand why this poor choice of using it this way and no option for us to avoid it, so here:

```
[versions]
agp = "8.2.0-alpha11"
kotlin = "1.8.21"
core-ktx = "1.9.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
navigation-fragment-ktx = "2.6.0"
navigation-ui-ktx = "2.6.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
```

**Device:** Device on which the bug was encountered here
Pixel 6

**Comment by AndroidDeveloperLB** [comment]
It seems that it's only used for vertical scrolling, even though there is mention about horizontal one.

**Comment by paulfthomas** [comment]
This issue seems related to `androidx.core.widget.NestedScrollView` which is not owned by Material, can you file your issue to the right channel?

**Comment by AndroidDeveloperLB** [comment]
@paulfthomas What do you mean? What do you use in material instead of it? Is there a better alternative? I thought that NestedScrollView is the latest one...
When I use the dependency of material, it is being offered to me. When I don't , I have only the Android framework "ScrollView".

Please explain

**Comment by paulfthomas** [comment]
`NestedScrollView` is part of [androidx.core](https://developer.android.com/jetpack/androidx/releases/core) which is not directly maintained by Material. You're probably getting the dependency through the Material dependency in your project.

**Comment by AndroidDeveloperLB** [comment]
@paulfthomas This makes sense now. You say that importing material dependency also imports the rest of android-x , right?

**Comment by paulfthomas** [comment]
Correct

**Comment by paulfthomas** [comment]
We don't always use the latest version of the androidx libraries in Material, so if you have a specific issue like this one, I recommend you to try with the latest version of that specific library separately to see if your issue has been fixed.

**Comment by AndroidDeveloperLB** [comment]
@paulfthomas OK thanks. Please work together though
