### ISSUE TITLE
[Button.IconButton] Theming

### ISSUE THREAD

**Issue by dailylama** [material-components/material-components-android#3480]
guide does not say how to theme icon buttons

[https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md#icon-button](https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md#icon-button)

button takes ripple color from the App `colorPrimary`, but ignores that and any other default `color` property specified in `materialThemeOverlay`. If the `materialThemeOverlay` is used then `backgroundTint` has to be set or it will error with the pink background

```
<Button
	style="@style/Widget.App.IconButton"
	android:layout_width="wrap_content"
	android:layout_height="wrap_content"
/>



<item name="materialIconButtonStyle">@style/Widget.App.IconButton</item>

<style name="Widget.App.IconButton" parent="Widget.Material3.Button.IconButton">
	<item name="materialThemeOverlay">@style/ThemeOverlay.App.IconButton</item>

<!--	<item name="backgroundTint"            >@android:color/transparent</item> -->
<!--	<item name="rippleColor"               >@color/blue</item> -->
</style>

<style name="ThemeOverlay.App.IconButton" parent="">
	<item name="colorSecondaryContainer"   >@color/blue</item>
	<item name="colorOnSecondaryContainer" >@color/blue</item>
	<item name="colorPrimary"              >@color/blue</item>
	<item name="colorOnPrimary"            >@color/blue</item>
	<item name="colorSurface"              >@color/blue</item>
	<item name="colorOnSurface"            >@color/blue</item>
</style>
```

**Comment by pekingme** [comment]
Theming the icon button should has no difference to [theming](https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md#theming-buttons) other button types. By using the default `backgroundTint` and `rippleColor` from M3 styles, you should be able to theme the button by changing `colorPrimary` (enabled), `colorOnPrimary` (ripple overlay), and `colorOnSurface` (disabled). Other colors are not referenced in the CSL of `backgroundTint` and `rippleColor`, unless you specify custom CSLs leveraging the other color roles.
