### ISSUE TITLE
[RangeSlider] lable was Stuck in UI 

### ISSUE THREAD

**Issue by Dhaval990** [material-components/material-components-android#3483]
**Description:** I am using RangeSlider. When I am scrolling the layout RangeSlider labels are stuck to the screen

**Expected behavior:** labels should not be suck

**Source code:** `   <com.google.android.material.slider.RangeSlider
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:stepSize="0.5"
            android:valueFrom="4.5"
            android:valueTo="15"
            app:tickVisible="true"
            app:labelBehavior="visible"
            app:values="@array/initial_slider_values" />`
Screen_recording_20230721_190518.webm
![Screenshot_1689946328](https://github.com/material-components/material-components-android/assets/4997856/f37cabf8-8d68-4236-9537-358fdea673ae)

**Android API version:** 33

**Material Library version:** 1.11.0-alpha01

**Device:** Pixel 6a

**Comment by pekingme** [comment]
Duplicate with #2869
