### ISSUE TITLE
MaterialDividerItemDecoration null pointer issue

### ISSUE THREAD

**Issue by topogps** [material-components/material-components-android#3485]
https://github.com/material-components/material-components-android/blob/81d09fb41150944c2cb185a31452b434227d25bb/lib/java/com/google/android/material/divider/MaterialDividerItemDecoration.java#L327

https://github.com/material-components/material-components-android/blob/81d09fb41150944c2cb185a31452b434227d25bb/lib/java/com/google/android/material/divider/MaterialDividerItemDecoration.java#L362

      View child = parent.getChildAt(i);

These childs might be null, but it seems there is no fallback when that happens. It could cause a NullPointerException in shouldDrawDivider - RecyclerView.getChildAdapterPosition(child), since that expects a NonNull child.

**Comment by pekingme** [comment]
After checking the code in framework, it seems the `null` child case is handled well internally. Do you have a working repo to reproduce this bug? Which API level you are seeing this bug?

**Comment by leticiarossi** [comment]
If the child is null the ReciclerView should return `RecyclerView.NO_POSITION` causing `shouldDrawDivider` to return false, so this condition should be handled
