### ISSUE TITLE
[Carousel] Dividers are not correctly positioned in the vertical carousel when mid-scroll

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3500]
https://github.com/material-components/material-components-android/assets/82187521/16008e7f-4934-40d2-ac7f-1df06e8b9201

**Material Library version:** https://github.com/material-components/material-components-android/commit/a16f180ce7da65107305ba3a8c85db3e149767c1

**Comment by pubiqq** [comment]
The bug is still present.

**Comment by imhappi** [comment]
Hmm I'm not seeing this issue
![divider](https://github.com/material-components/material-components-android/assets/7026277/258fbe29-862f-493a-b334-106a7ffed63b)

Are there specific repro steps on how to see this?

**Comment by pubiqq** [comment]
> Are there specific repro steps on how to see this?

No specific steps are needed, just try scrolling.

You can try making the list items semi-transparent to better track the movement of the dividers.

**Comment by imhappi** [comment]
Ah I think I know what you mean; the dividers disappear (I assume they're not correctly positioned) when you are mid-scroll and re-appear when the items slot into place

Re-opening this issue

**Comment by pubiqq** [comment]
They don't just disappear, they are placed in incorrect places, as you can see in the video (white horizontal lines). And this happens not only during scrolling, but also in an idle state, this can also be seen in the video, so the additional clarification in the issue title was unnecessary.
