### ISSUE TITLE
[Carousel] Hero strategy carousel_alignment not found

### ISSUE THREAD

**Issue by ravithoria** [material-components/material-components-android#3503]
While trying to use material component Carousel with Hero strategy carousel_alignment for xml and setCarouselAlignment programmatically not found

```
 <androidx.recyclerview.widget.RecyclerView
      ...
      app:layoutManager="com.google.android.material.carousel.CarouselLayoutManager"
      app:carousel_alignment="center"
      android:orientation="horizontal"/>

carouselLayoutManager.setCarouselAlignment(CarouselLayoutManager.CENTER);
```
**Material Library version:** 1.11.0-alpha01

**Comment by imhappi** [comment]
Hero strategy carousel alignment was added in 7cfd30f99b0ccb44540d124b9cca201d1b707e3b which will be in the next alpha release
