### ISSUE TITLE
Unable to Build project. Gradle is failing

### ISSUE THREAD

**Issue by prernagp** [material-components/material-components-android#351]
Unable to find method 'org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry.registerPublication(Ljava/lang/String;Lorg/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectPublication;)V'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

**Comment by ldjcmu** [comment]
We can't repro this issue.

**Comment by SubhrajyotiSen** [comment]
@prernagp have you been to build the project?
