### ISSUE TITLE
[BottomSheet] Modal bottom sheet - No dimming (scrim) of content underneath

### ISSUE THREAD

**Issue by kelvinwatson** [material-components/material-components-android#3511]
**Description:** Following the basic description on how to use the modal bottom sheet, there is no dimming of the content underneath the bottom sheet, even though the image in [BottomSheet.md](https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheet.md) clearly shows dimming. This document also describes the dimming as a scrim, but there is no attribute exposed to set the scrim. I created a barebones app using the provided code in that doc, but there is no dimming.

**Expected behavior:** There should be dimming, or the ability to set the scrim of the content underneath the bottom sheet.

**Source code:** 
```
class ModalBottomSheet : BottomSheetDialogFragment() {
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? = inflater.inflate(R.layout.modal_bottom_sheet_content, container, false)

    companion object {
        const val TAG = "ModalBottomSheet"
    }
}

 val modalBottomSheet = ModalBottomSheet()
 modalBottomSheet.show(supportFragmentManager, ModalBottomSheet.TAG)
```

**Minimal sample app repro:** See code snippet.

**Android API version:** 33

**Material Library version:** 1.9.0

**Device:** Pixel 6 emulator

**Comment by imhappi** [comment]
Hi @kelvinwatson the dimming should be automatic by virtue of using a dialog/dialog fragment. I'm unable to reproduce the issue on an API 33 emulator, but there is currently a bug filed where the dim is not working for Android U emulators https://issuetracker.google.com/issues/290975439

Could you double-check that you were on an API 33 emulator, or try testing on another emulator?

**Comment by raanaYavari** [comment]
I have this issue on emulator API 34  and physical devices with android 14.
Could you please recheck it?
