### ISSUE TITLE
[ModalBottomSheet] On API 34 Modal Bottom Sheet does not renders shadow 

### ISSUE THREAD

**Issue by fernandozanutto** [material-components/material-components-android#3517]
**Description:** 
When running on Android API 34, Modal Bottom Sheet is not rendering the shadow on the content below.

When running on Android API 33 and lower, shadow renders as usual.

**Wrong behavior:**
<img width="208" alt="image" src="https://github.com/material-components/material-components-android/assets/15229294/7a5c0af6-e0f8-42f8-a576-5b772cbd3a11">

**Expected behavior:** 
<img width="212" alt="image" src="https://github.com/material-components/material-components-android/assets/15229294/39499413-a46d-4dda-a8d8-27a525da36f5">

**Source code:** 

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        MyBottomSheet().show(supportFragmentManager, MyBottomSheet.TAG)
    }
}


class MyBottomSheet: BottomSheetDialogFragment() {
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? = inflater.inflate(R.layout.modal_bottom_sheet_content, container, false)

    companion object {
        const val TAG = "ModalBottomSheet"
    }
}
```

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="#E4C3C9">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textAlignment="center"
        android:layout_marginTop="8dp"
        android:text="Hello World!" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textAlignment="center"
        android:layout_marginTop="8dp"
        android:text="Hello World!" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textAlignment="center"
        android:layout_marginTop="8dp"
        android:text="Hello World!" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textAlignment="center"
        android:layout_marginTop="8dp"
        android:text="Hello World!" />

</LinearLayout>
```

**Minimal sample app repro:**  https://github.com/fernandozanutto/ModalBottomSheetSample

**Android API version:** Android API 34

**Material Library version:** 1.11.0-alpha01

**Device:** Android Studo Pixel 7 API 34 emulator

**Comment by dsn5ft** [comment]
I think this is just a strange bug in the API 34 emulators, can you try running on a physical API 34 device if you have one?

**Comment by imhappi** [comment]
This is a known issue with Android API 34 emulators https://issuetracker.google.com/issues/290975439

Going to close this bug, feel free to re-open if you are able to repro on a physical API 34 device

**Comment by fernandozanutto** [comment]
Ok, thanks for the info!
