### ISSUE TITLE
Rename SwitchMaterial class to MaterialSwitch to follow naming convention of MaterialButton and MaterialCardView

### ISSUE THREAD

**Issue by LouisCAD** [material-components/material-components-android#352]
Reopening [this issue](https://issuetracker.google.com/issues/123830858).

Naming is important, and `SwitchMaterial` class name is not right because inconsistent with other Material Components.
As it has never been released in a stable, I'm requesting it to be renamed to the more natural name `MaterialSwitch`.

Since @ldjcmu mentioned possible renaming before stable version [in this comment](https://github.com/material-components/material-components-android/issues/79#issuecomment-491088183), I'm putting this back on the table.

**Comment by ldjcmu** [comment]
Tracking over at https://issuetracker.google.com/123830858. The name is based on the AppCompat SwitchCompat component. We have to be inconsistent with either AppCompat or the prefix.

We agree naming is important, but aren't sure the suggestion is better.
