### ISSUE TITLE
[TopAppBar] Manual lifting of app bar not working

### ISSUE THREAD

**Issue by patzly** [material-components/material-components-android#3523]
**Description:** Hi, I think 2b476b3 has broken manual lifting functionality in 1.11.0-alpha02, in alpha01 it's working as expected. With `liftOnScroll` disabled and a custom scroll behavior applied which calls `setLifted()` on specific scroll states, the app bar stays unelevated now:
![Screenshot_20230815-010407](https://github.com/material-components/material-components-android/assets/33599892/ebcd26e0-0baa-40bb-9b41-3ad01b624606)

**Expected behavior:** The app bar should be liftable even without `liftOnScroll` being turned on.

**Source code:**
```java
appBar.setLiftOnScroll(false); // Turn off auto lifting
appBar.setLifted(true); // TopAppBar should be elevated now
```

**Minimal sample app repro:** [test-appbar](https://github.com/patzly/test-appbar)
I've created a demonstration of the issue with a small test app, simply turn off the "Lift on Scroll" switch and notice that it doesn't matter now what state the "Lifted" switch has, the TopAppBar stays unelevated. When you change the MDC version to `1.11.0-alpha01` in [libs.versions.toml](https://github.com/patzly/test-appbar/blob/main/gradle/libs.versions.toml), it works as expected.

**Android API version:** 34

**Material Library version:** 1.11.0-alpha02

**Device:** Pixel 6

**Comment by imhappi** [comment]
Hi @pekingme could you take a look to see if this was caused by the liftOnScroll color change?
