### ISSUE TITLE
Material3 has no Equvalent ?

### ISSUE THREAD

**Issue by Morons** [material-components/material-components-android#3528]
Material 2 had shapes defined in XML in res that was usefull to create for instance an EMPTY drawable like 
```
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@color/color_on_primary_surface_divider" />
</shape>
```
AND 
```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="@color/color_on_primary_surface_divider" />
</shape>
```
where 
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
	<item android:alpha="0.1" android:color="?attr/colorOnPrimarySurface" />
</selector>
```
Those drawables was used when an empty image was needed, is there any replacement for this behavior?

**Comment by imhappi** [comment]
Hi @Morons I'm a bit confused by this question. Could you let me know exactly which shape resources in which xml you are referring to?

All shape resources should be updated to use the m3 style or has an m3 equivalent

**Comment by leticiarossi** [comment]
Closing due to lack of a reply - feel free to comment again with more info as asked. The library doesn't provide a default drawable for the use case of an empty image, but that should be easy to define on the user side.

**Comment by Morons** [comment]
OK It is reaaly very simple look at the following code in M3 Comp[ose
```kotlin
OutlinedTextField(
...
leadingIcon = {
	if (leadingIcon != null) {
		Icon(
			imageVector = leadingIcon,
			contentDescription = null,
			modifier = Modifier.size(size24)
		)
	} else {
		// we need an Drawable that has no size
	}
},
```
If the leadingIcon parameter is NOT  passwd i.e. = null then this will cause a space in front of the `OutlinedTextField` the else condition used to be easy in M2, we could just define a drawable like this in res/drawable
```xml
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@color/color_on_primary_surface_divider" />
</shape>
```
BUT in M3 there is no way to do this
Please advise on how to create an "Empty" Drawable/ImageVector/ImageBitmap or painter that will have no size?
