### ISSUE TITLE
Typography Issue: < instead of &lt; and > instead of /&gt; 

### ISSUE THREAD

**Issue by samsruti** [material-components/material-components-android#353]
https://github.com/material-components/material-components-android/blob/7865481434065a1a9dc8f5ea759f085b2574ddc3/lib/java/com/google/android/material/button/MaterialButtonToggleGroup.java#L52

https://github.com/material-components/material-components-android/blob/7865481434065a1a9dc8f5ea759f085b2574ddc3/lib/java/com/google/android/material/button/MaterialButtonToggleGroup.java#L58

https://github.com/material-components/material-components-android/blob/7865481434065a1a9dc8f5ea759f085b2574ddc3/lib/java/com/google/android/material/button/MaterialButtonToggleGroup.java#L63

https://github.com/material-components/material-components-android/blob/7865481434065a1a9dc8f5ea759f085b2574ddc3/lib/java/com/google/android/material/button/MaterialButtonToggleGroup.java#L68

https://github.com/material-components/material-components-android/blob/7865481434065a1a9dc8f5ea759f085b2574ddc3/lib/java/com/google/android/material/button/MaterialButtonToggleGroup.java#L73

https://github.com/material-components/material-components-android/blob/7865481434065a1a9dc8f5ea759f085b2574ddc3/lib/java/com/google/android/material/button/MaterialButtonToggleGroup.java#L79

**Comment by MGaetan89** [comment]
I think that's on purpose, so it is not treated as HTML when trending the documentation
