### ISSUE TITLE
[AppBarLayout] Status bar color not changing dynamically anymore

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#3530]
**Description:** In my app, I'm using `AppBarLayout` (incl. `MaterialToolbar` and `TabLayout`), and a `Viewpager2` (incl. a `RecyclerView` list). I'm dynamically changing the color of the status bar when the user is scrolling up and down the list and I'm using a compress effect for the toolbar. 

In order to dynamically change the status bar color, I'm using `setStatusBarForeground` together with `createWithElevationOverlay`. See below code snippet and the following complete code example: https://github.com/patrickfrei/test_coding/blob/main/MyApplication.rar

Since I've upgraded from material:1.11.0-alpha**01** to material:1.11.0-alpha**02**, the color of the status bar doesn't dynamically change anymore. In the example app, when scrolling up and down the list, the color of the status bar switches between white and light-grey (material:1.11.0-alpha**01**; expected behavior), but it keeps to be white all the time when using material:1.11.0-alpha**02**.

It seems to me as if the following commit has somehow changed the behavior: https://github.com/material-components/material-components-android/commit/2b476b3a96ef0ab52206ca0cae479a501a0130ff

**Expected behavior:** The color of the status bar should change dynamically when scrolling up and down the list (as in material:1.11.0-alpha**01**).

**Source code:** Code of `MainActivity.java`:
```
AppBarLayout appBarLayout = findViewById(R.id.appbar);
appBarLayout.setStatusBarForeground(MaterialShapeDrawable.createWithElevationOverlay(MainActivity.this));
```

**Minimal sample app repro:** https://github.com/patrickfrei/test_coding/blob/main/MyApplication.rar

**Android API version:** Android API 29-34

**Material Library version:** 1.11.0-alpha02

**Device:** Various Pixel emulators and Nokia 7.2

**Comment by imhappi** [comment]
Hi @pekingme could you take a look at this?
