### ISSUE TITLE
[Page Indicator Dots] Insufficient Touch Target Size

### ISSUE THREAD

**Issue by devchan4188** [material-components/material-components-android#3534]
**Description:** The Page Indicator Dots are by default clickable. The Touch Target Size for the Dots is insufficient.

**Expected behavior:** The Touch Target Size for the Page Indicator should be at least 44 dp x 44 dp.

**Minimal sample app repro:**
![IMG_20230821_150339](https://github.com/material-components/material-components-android/assets/59444071/c245a533-9842-48aa-bf24-86d7e08291be)

**Android API version:** 33

**Material Library version:** 1.9.0

**Device:** Pixel 3a

**Comment by imhappi** [comment]
Hi @devchan4188 can you clarify what component you are using? We do not have a page indicator dot component in our library.

**Comment by leticiarossi** [comment]
Closing due to lack of info and since we don't have a page indicator dot component in the library
