### ISSUE TITLE
[BottomSheetDialogFragment] doesn't have scrim background

### ISSUE THREAD

**Issue by coralinejones1985** [material-components/material-components-android#3549]
**Description:** 
BottomSheetDialogFragments and AlertDialogs don't have scrim background when they appear. 
I also tried same logic using compose: composable ModalBottomSheet has scrim, while AlertDialog has not. 

**Expected behavior:** Both BottomSheet and AlertDialog should have scrim when they appear. 

**Source code:** 
```
private fun AppCompatActivity.showAlert() {
    AlertDialog.Builder(this)
        .setTitle("Alert Title")
        .setMessage("Alert Message")
        .setPositiveButton("OK") { _, _ -> }
        .setNegativeButton("Cancel") { _, _ -> }
        .show()
}

private fun AppCompatActivity.showBottomSheet() {
    BottomSheetDialogFragment(R.layout.fr_bottom_sheet)
        .show(supportFragmentManager, "BottomSheetDialogFragment")
}
```

**Minimal sample app repro:** [GitHub Sample](https://github.com/coralinejones1985/material-scrim-sample)

**Android API version:** 34

**Material Library version:** 1.11.0-alpha02

**Device:** Pixel 2 Emulator

<img src="https://github.com/material-components/material-components-android/assets/8022188/37508380-29eb-4324-93ba-6dab857048aa" width="240" />
<img src="https://github.com/material-components/material-components-android/assets/8022188/141dd2a4-2ed3-4cd4-bd99-7d2efb318b0d" width="240" />

**Comment by manabu-nakamura** [comment]
FYI: https://github.com/material-components/material-components-android/issues/3511#issuecomment-1670298436
It seems that we can't access https://issuetracker.google.com/issues/290975439.

**Comment by coralinejones1985** [comment]
Yes, but I don't have this bug on Emulators with API 33 🤔 
I'm not sure, but can it be API 34 compatibility issue?

**Comment by imhappi** [comment]
It is an API 34 emulator bug. Please refer to the comment by @manabu-nakamura
