### ISSUE TITLE
[MaterialCheckBox] Accessibility info contains only English state description

### ISSUE THREAD

**Issue by v-mas** [material-components/material-components-android#3563]
**Description:** Accessibility info contains only English state description

**Expected behavior:** state description is either used from platform, or is translated to other languages, or is possible to provide own

**Source code:** 
`super.setStateDescription(getButtonStateDescription());`

**Android API version:** 33

**Material Library version:** 1.8.0, 1.9.0

I have the device set to Polish language, and when I use AppCompatCheckBox, it reads state change properly in that language, but when using MaterialCheckbox (default when not specified AppCompat explicitly) it reads sate change only in english
not: I tried to inherit from MaterialCheckBox and in accessibility info I set  `info?.stateDescription = null` - it started to read state in device language somehow, and it reads differently from AppCompat

**Comment by leticiarossi** [comment]
I believe this was fixed in https://github.com/material-components/material-components-android/commit/198e08c
