### ISSUE TITLE
[TopAppBar] Back button different color than overflow menu icon

### ISSUE THREAD

**Issue by mobilekosmos** [material-components/material-components-android#3564]
**Description:**
The back button is colored with colorOnSurface, and the right icons are colored with colorOnSurfaceVariant.

**Expected behavior:** Screenshots and/or description of expected behavior
The material specs are also not clear. The docs state the color should differ (why though?), but on the pictures they are equal:
[M3 docs](https://m3.material.io/components/top-app-bar/specs#14e23895-ac2e-40d8-b0f7-8d016c10a225)

**Source code:**
```
@Composable
private fun AppBarWithBackButton(
    onBackClicked: () -> Unit,
    onMarkAllUserNotificationsAsReadSelected: (() -> Unit)?,
) {
    TopAppBar(
        title = {
            Text(
                text = "My title",
            )
        },
        navigationIcon = {
            IconButton(onClick = onBackClicked) {
                Icon(
                    imageVector = Icons.Default.ArrowBack,
                    contentDescription = "null",
                )
            }
        },
        actions = {
            if (onMarkAllUserNotificationsAsReadSelected != null) {
                DropDownMenu(onMarkAllUserNotificationsAsReadSelected)
            }
        },
    )
}

@Composable
private fun DropDownMenu(onMarkAllUserNotificationsAsReadSelected: () -> Unit) {
    var showMenu by rememberSaveable { mutableStateOf(false) }

    // IconButton to open the menu
    IconButton(onClick = { showMenu = true }) {
        Icon(Icons.Filled.MoreVert, contentDescription = null)
    }
    DropdownMenu(
        expanded = showMenu,
        onDismissRequest = { showMenu = false },
    ) {
        DropdownMenuItem(
            onClick = {
                showMenu = false
                onMarkAllUserNotificationsAsReadSelected()
            },
        ) {
            Text(
                text = "blabla"
            )
        }
    }
}
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 33

**Material Library version:**
"com.google.android.material:material:1.9.0"

**Device:** Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
Hi there, I asked design and the specs are correct - those two icon types have different colors. The image on m3.material.io should be updated (this has been reported internally so will close this issue).
