### ISSUE TITLE
[Catalog][BottomAppBar][BottomSheet][NavigationDrawer][SearchView][SideSheet][Predictive Back] state mismatch between bottom sheet and back callback after restarting activity

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3575]
**Description:** The expanded bottom sheet is still expanded after restarting the activity (e.g. after rotating the device). But, the back callback is **disabled** and the bottom sheet will **not** detach from the left and right edges of the screen.
https://m3.material.io/components/bottom-sheets/guidelines#3d7735e2-73ea-4f3e-bd42-e70161fc1085

***Similar things are happening in other demos (BottomSheetMainDemoFragment, NavigationDrawerDemoActivity, CustomNavigationDrawerDemoActivity, SearchMainDemoActivity, SearchRecyclerDemoActivity, and SideSheetMainDemoFragment) as well.***

(before restarting activity)
![Screenshot_20230913_171952](https://github.com/material-components/material-components-android/assets/71050561/8b9c09fb-75ed-4952-a2e2-fb119a4e049e)
(after restarting activity)
![Screenshot_20230913_172001](https://github.com/material-components/material-components-android/assets/71050561/5b5cd753-115d-4e24-9d8d-6f7ce8f6c277)

**Expected behavior:** The expanded bottom sheet is **hidden** or the back callback is **enabled** after restarting the activity (e.g. after rotating the device).

**Minimal sample app repro:** Catalog app

**Android API version:** 34

**Material Library version:** 1.11.0-alpha02

**Device:** Emulator 32.1.15 (API 34)

**Comment by dsn5ft** [comment]
@manabu-nakamura can you file a separate issue for SearchView (and any others?)
