### ISSUE TITLE
[Carousel] A single item is incorrectly displayed in RTL mode

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3580]
<img src="https://github.com/material-components/material-components-android/assets/82187521/8eed70c6-abb9-410c-abd2-ed37a116ad0e" width="270px" />

**Material Library version:** 1.11.0-alpha02
**Device:** Pixel 4a (5G)

**Comment by hunterstich** [comment]
Hey @pubiqq!

Thanks for filing this! I've actually been working on a fix for https://github.com/material-components/material-components-android/issues/3554, which I think should solve this issue as well. Should be completed soon and we can double check once the change lands!
