### ISSUE TITLE
[TextInputLayout] The label overlaps the text

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3582]
<table>
  <tr>
    <th>Actual result</th>
    <th>Expected result</th>
   </tr> 
   <tr>
    <td><img src="https://github.com/material-components/material-components-android/assets/82187521/04da92af-e9c7-40c9-b0bb-1c0451e1de75" width="270px"></td>
    <td><img src="https://github.com/material-components/material-components-android/assets/82187521/da38b28f-a96c-4366-99cd-df6b815c901e" width="270px"></td>
  </tr>
</table>

**Material Library version:** 1.11.0-alpha02
**Android API version:** 19

**Comment by dsn5ft** [comment]
@pubiqq do you know if this issue was introduced recently or if it has been happening for a while?

**Comment by pubiqq** [comment]
It's a regression from material 1.7.0.
