### ISSUE TITLE
MaterialShapeDrawable  

### ISSUE THREAD

**Issue by tmxdyf** [material-components/material-components-android#359]
MaterialShapeDrawable setShadowColor not work

**Comment by leticiarossi** [comment]
Could you provide more information about your issue? Like your code where the issue is reproducible.

**Comment by ymarian** [comment]
Hi this will only work if you set
setShadowCompatibilityMode(SHADOW_COMPAT_MODE_ALWAYS);

That would make it so that the shadows are not native though, so it's not recommended unless you really need it.
