### ISSUE TITLE
[Carousel] Support initial scroll position

### ISSUE THREAD

**Issue by GuhDoy** [material-components/material-components-android#3590]
**Is your feature request related to a problem? Please describe.**
I created a fork repository to describe my needs. For the `LinearLayoutManager`, I can use `RecyclerView.scrollToPosition()` to [set its initial scroll position](https://github.com/GuhDoy/material-components-android/commit/9ef4f45e3a9230f61ae6490ecce52600598114a2#diff-901f62a3176da0f9b31b05ba1c486a2498363dab2e47b0ec8ea997937ca17956R89). However, when I try to use this method to [set the initial scroll position](https://github.com/GuhDoy/material-components-android/commit/9ef4f45e3a9230f61ae6490ecce52600598114a2#diff-9327dc3c2586b5a0d2db5fc40ff7cd1616925ad3daf63ec0a3451528717146aeR59-R64) of the `CarouselLayoutManager`, it doesn't seem to do anything.

**Describe the solution you'd like**
Supports using `RecyclerView.scrollToPosition()` to set the initial scroll position.

**Describe alternatives you've considered**
By reading the source code, I found that `LinearLayoutManager` respects `mPendingScrollPosition` in `onLayoutChildren`, but `CarouselLayoutManager` [resets](https://github.com/GuhDoy/material-components-android/blob/9ef4f45e3a9230f61ae6490ecce52600598114a2/lib/java/com/google/android/material/carousel/CarouselLayoutManager.java#L271-L272) `scrollOffset`. Maybe removing this line of code will meet my needs?

**Additional context**
Sorry, but I can't create a pull request because I don't know if my alternative will cause other problems.

**Comment by afohrman** [comment]
Thanks for filing and looking into this, @GuhDoy! You can definitely feel free to create a PR and we can test the fix to see whether it will cause any unintended side effects.
