### ISSUE TITLE
[AppBarLayout] Get Tonal Surface Color for Status Bar

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#3597]
**Description:** I've updated my app to Material 1.11.0-alpha03. In MainActivity, I'm already using the Tonal Surface Color system to dynamically change the color of the status bar as follows:

```
if (android.os.Build.VERSION.SDK_INT >= 29) {
  AppBarLayout appBarLayout = findViewById(R.id.appbar);
  appBarLayout.setStatusBarForegroundColor(com.google.android.material.color.MaterialColors.getColor(appBarLayout, R.attr.colorSurface));
}
```

In addition, my app contains some activities (e.g. an AboutActivity) where I'm still using the Surface color approach based on an elevation value as shown in below code. In these activities, I'd also like to switch to the Tonal Surface Color system. However, I'm unable to figure out how to get the color from the action bar in order to apply it to the status bar.

In addition, below approach results in slightly different colors applied to status and app bar on 1.11.0-alpha03.

Do you have an advice for me in this regard?
 
```
public class AboutActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setupActionBar();
        setupStatusBar();
        setContentView(R.layout.about_activity);
    }

    private void setupStatusBar() {
        if (android.os.Build.VERSION.SDK_INT >= 29) {
            Window window = getWindow();
            int color = SurfaceColors.SURFACE_2.getColor(AboutActivity.this);
            window.setStatusBarColor(color);
        }
    }

    private void setupActionBar() {
        ActionBar actionBar = this.getSupportActionBar();
        if (actionBar != null) {
            // Set background color prior API 21 as that doesn't work automatically
            if (android.os.Build.VERSION.SDK_INT <= 22) {
                int color = SurfaceColors.SURFACE_2.getColor(AboutActivity.this);
                ColorDrawable colorDrawable = new ColorDrawable(color);
                actionBar.setBackgroundDrawable(colorDrawable);
            }
        }
    }
}
```

**Source code:** See above.

**Android API version:** 29-34

**Material Library version:** 1.11.0-alpha03

**Device:** Various Pixel 5 emulators

**Comment by pekingme** [comment]
M3 ActionBar is updated for TSC. It uses `colorSurfaceContainer` as the background. Could you try to `setStatusBarColor` to the same color role to keep them aligned?

**Comment by patrickfrei** [comment]
Yes, with `colorSurfaceContainer `in `setStatusBarColor` it works. The colors are now identical. Many thanks for your help @pekingme !

BTW: Even the workaround for setting the background color prior to API level 22 is obviously not necessary anymore. Probably, this has been fixed in the meantime.

**Comment by patrickfrei** [comment]
> M3 ActionBar is updated for TSC. It uses `colorSurfaceContainer` as the background. Could you try to `setStatusBarColor` to the same color role to keep them aligned?

@pekingme: Just a short question: From where did you get the information that the M3 ActionBar uses `colorSurfaceContainer` as the background?
