### ISSUE TITLE
How do I set the angle of a dialog box? Mine is right-angled. 

### ISSUE THREAD

**Issue by snpmyn** [material-components/material-components-android#361]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

**Comment by ldjcmu** [comment]
What do you mean by angle? Are you talking about the corner shape? If so, you'll want to set your ShapeAppearance in your R.attr.materialAlertDialogTheme. https://github.com/material-components/material-components-android/blob/8570f261e39c215943e5440d167c3f9e3a6cc690/docs/theming/Shape.md

**Comment by snpmyn** [comment]
Thanks very mush!
