### ISSUE TITLE
I want to set the corner shape.  But not useful, can you give a example? Thank you!

### ISSUE THREAD

**Issue by snpmyn** [material-components/material-components-android#362]

**Comment by snpmyn** [comment]
Can you help me? Thank you!

**Comment by leticiarossi** [comment]
Hi, you can find detailed information about shape theming (with code examples) here: https://material.io/develop/android/theming/shape/
You can also find design guidelines about it (with visual examples) here: https://material.io/design/shape/#shaping-material
