### ISSUE TITLE
[TabLayout] Tooltip value gets reset to text value

### ISSUE THREAD

**Issue by therealsujitk** [material-components/material-components-android#3621]
**Description:** Despite setting the value of the tooltip, it gets reset to the text value when the tab is selected.

**Expected behavior:** The tooltip should still show the value set programmatically.

**Source code:**

I'm using the `TabLayoutMediator` to change my tooltip text, while this works at first the tooltips get reset when the tab is selected.

```java
new TabLayoutMediator(days, timetable, (tab, position) -> {
    tab.setText(dayStrings[position].substring(0, 1));

    View day = tab.view;

    TooltipCompat.setTooltipText(day, dayStrings[position]);
    day.setContentDescription(dayStrings[position]);
}).attach();
```

**Minimal sample app repro:** NA

**Android API version:** API 34

**Material Library version:** 1.11.0-alpha03

**Device:** Pixel 6 API 34

**Comment by imhappi** [comment]
Hello
Do not use `TabLayoutMediator` to change your tooltip text; you are passing an anonymous `TabConfigurationStrategy` in the constructor, with a method called `onConfigureTab`. This method is `Called to configure the tab for the page at the specified position.` (see javadocs) and should be used to configure the tab contents. This method gets called whenever there may be a change in tab configuration (ie. on tab change) and is not meant to be used to affect any other part of your layout.

You are looking for the behaviour of `TabLayout.addOnTabSelectedListener`

**Comment by therealsujitk** [comment]
@imhappi I tried that too but it doesn't work sometimes, specifically when the tab is changed on page swipe the tooltip text gets reset.

**Comment by imhappi** [comment]
@therealsujitk Could you show some code samples? When I use `addOnTabSelectedListener`, I'm able to change text without it getting reset.

I'm not sure what you mean by it being excessive to register an `onPageChangeCallback` to change the tooltip text; by using a TabLayout with a ViewPager2 and binding it with the TabLayoutMediator, it is already registering an `onPageChangeCallback`, else TabLayout wouldn't be able to interface with the ViewPager2. `addOnTabSelectedListener` itself does not register an `onPageChangeCallback`.

**Comment by therealsujitk** [comment]
So I tried doing it this way, it works as long as the tabs are changed by tapping on them, but if they are changed via a page swipe, the tooltip text gets reset.

```java
new TabLayoutMediator(days, timetable, (tab, position) -> {
    tab.setText(dayStrings[position].substring(0, 1));
    TooltipCompat.setTooltipText(tab.view, dayStrings[position]);
    tab.view.setContentDescription(dayStrings[position]);
}).attach();

days.addOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {
    @Override
    public void onTabSelected(TabLayout.Tab tab) {
        TooltipCompat.setTooltipText(tab.view, dayStrings[tab.getPosition()]);
        tab.view.setContentDescription(dayStrings[tab.getPosition()]);
    }

    @Override
    public void onTabUnselected(TabLayout.Tab tab) {
        TooltipCompat.setTooltipText(tab.view, dayStrings[tab.getPosition()]);
        tab.view.setContentDescription(dayStrings[tab.getPosition()]);
    }

    @Override
    public void onTabReselected(TabLayout.Tab tab) {
        TooltipCompat.setTooltipText(tab.view, dayStrings[tab.getPosition()]);
        tab.view.setContentDescription(dayStrings[tab.getPosition()]);
    }
});
```

[This](https://github.com/therealsujitk/android-vtop-chennai/blob/master/app/src/main/java/tk/therealsuji/vtopchennai/fragments/HomeFragment.java#L182-L189) was my initial code.

**Comment by imhappi** [comment]
You're still setting `TooltipCompat.setTooltipText(tab.view, dayStrings[position])` in your code; see my comment above. Again, you should not be affecting any other part of your layout in `onConfigureTab` which is the code that you are passing into the TabLayoutMediator constructor

**Comment by therealsujitk** [comment]
@imhappi Not calling `TooltipCompat.setTooltipText()` will make the tooltip take the default value since `TabLayout.OnTabSelectedListener` will only be called when a tab is tapped.

**Comment by imhappi** [comment]
Yes, but you can call TooltipCompat.setTooltipText() once for the default value when the layout is created, not inside `onConfigureTab`

**Comment by therealsujitk** [comment]
Sorry, I still don't understand. You're saying I shouldn't be setting the tooltip text inside `onConfigureTab()`, so I should be doing it like this correct?

```java
new TabLayoutMediator(days, timetable, (tab, position) -> {
    tab.setText(dayStrings[position].substring(0, 1));
}).attach();

for (int i = 0; i < days.getTabCount(); ++i) {
    TabLayout.Tab tab = days.getTabAt(i);
    TooltipCompat.setTooltipText(tab.view, dayStrings[i]);
}

days.addOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {
    @Override
    public void onTabSelected(TabLayout.Tab tab) {
        TooltipCompat.setTooltipText(tab.view, dayStrings[tab.getPosition()]);
    }

    @Override
    public void onTabUnselected(TabLayout.Tab tab) {
        TooltipCompat.setTooltipText(tab.view, dayStrings[tab.getPosition()]);
    }

    @Override
    public void onTabReselected(TabLayout.Tab tab) {
        TooltipCompat.setTooltipText(tab.view, dayStrings[tab.getPosition()]);
    }
});
```

This is the issue I'm facing.

https://github.com/material-components/material-components-android/assets/60378235/03d70e20-7a97-4c37-b137-8df0b76ffd67

**Comment by imhappi** [comment]
Hi @therealsujitk sorry, I misread and didn't realize you were setting the tooltip on the tab text itself;

1. Setting the tooltip in `onConfigureTab` in the TabLayoutMediator constructor should be fine, as you are actually dealing with each tab's text
2. Unfortunately, TabLayout itself actually sets its tooltip to correspond to the tab text. This is for accessibility purposes, and it gets set every time `updateTab` is called internally. Setting an `addOnTabSelectedListener` would work if the TabLayout wasn't integrated with the ViewPager since you can overwrite the tooltip _after_ `updateTab`, but in the case of swiping through the pages there's no guarantee that `updateTab` will be called before the tab selected listener is triggered (the tab selected listener is called in `onPageSelected`, and `updateTab` is called in `onPageScrolled`)

Unfortunately we need to keep the current behaviour of setting the tooltip to the tab text for a11y, so if you require the tooltip to be a different text, you will need a workaround:

You can register an onPageChangeCallback to the viewpager after attaching the TabLayout to the TabLayoutMediator, and call

for (int i = 0; i < days.getTabCount(); ++i) {
    TabLayout.Tab tab = days.getTabAt(i);
    TooltipCompat.setTooltipText(tab.view, dayStrings[i]);
}

in onPageScrolled so that it is called after the TabLayout's page change callback that sets the tab tooltip.

**Comment by therealsujitk** [comment]
This is what I did in the end which seems to work, not sure if this is the best method.

```java
public static void mediateTabLayout(TabLayout tabLayout, ViewPager2 viewPager, String[] tabTexts, String[] tabDescriptions) {
    new TabLayoutMediator(tabLayout, viewPager, (tab, position) -> {
        tab.setText(tabTexts[position]);
        tab.view.setContentDescription(tabDescriptions[position]);
        TooltipCompat.setTooltipText(tab.view, tabDescriptions[position]);
    }).attach();

    for (int i = 0; i < tabLayout.getTabCount(); ++i) {
        TabLayout.Tab tab = tabLayout.getTabAt(i);

        if (tab == null) {
            continue;
        }

        int position = i;

        tab.view.addOnLayoutChangeListener((view, i0, i1, i2, i3, i4, i5, i6, i7) -> {
            view.setContentDescription(tabDescriptions[position]);
            TooltipCompat.setTooltipText(view, tabDescriptions[position]);
        });
    }
}
```

> Unfortunately we need to keep the current behaviour of setting the tooltip to the tab text for a11y

I personally think developers should have the freedom to change the tooltip text especially for cases like this one where it doesn't make sense for the tooltip to be the same as the text. Maybe this could be a feature request? Just saying, perhaps there should exist a `TabLayout.Tab.setTooltipText()` method, or maybe the tooltip text should take the value of the content description if present.

**Comment by imhappi** [comment]
Feel free to file a new feature request for `TabLayout.Tab.setTooltipText()`, and we can triage it :)
