### ISSUE TITLE
 [TextInputLayout] Padding removed in 1.1.0-alpha04+

### ISSUE THREAD

**Issue by william-reed** [material-components/material-components-android#363]
## Description
Prior to 1.1.0-alpha04 the TextInputLayout had padding on the top (and or bottom). It's not clear from the change log on the github release what exactly it was previously or what the specific change was. I'm guessing I might need to set padding on my global theme to obtain the previous behavior

## Expected behavior: 
![](https://i.imgur.com/RU2TS0d.png)
## Actual Behavior
![](https://i.imgur.com/P2HNjIt.png)
## Source code: 
```
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:animateLayoutChanges="true"
    android:orientation="vertical"
    android:padding="10dp"
    tools:context=".ui.shared.SettingsFragment">

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/til_first_name"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="@string/first_name"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/first_name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:enabled="false"
            android:inputType="textPersonName"
            android:focusable="false"
            tools:text="John" />

    </com.google.android.material.textfield.TextInputLayout>
...
```

Also created the issue on the google issue tracker [here](https://issuetracker.google.com/issues/132754766), but there seems to be better community responses on GitHub

**Comment by william-reed** [comment]
https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha04 i only notice "Fix padding of TextInputEditText when an icon is present" but since no icon is present I don't think this applies. Not clear what else changed with it

**Comment by leticiarossi** [comment]
Resolved in https://issuetracker.google.com/issues/132754766
