### ISSUE TITLE
[Time picker] Cannot change the size of the TimeSelectorLabelTextFont

### ISSUE THREAD

**Issue by sunnyd-verily** [material-components/material-components-android#3630]
**Description:** Cannot change the size of the TimeSelectorLabelTextFont. TimeSelectorLabelTextFont by default takes the font size as DisplayLarge.
<img width="263" alt="Screenshot 2023-10-12 at 10 30 04 AM" src="https://github.com/material-components/material-components-android/assets/109819608/90862d23-8214-42b0-9de5-1505751343c0">

**Expected behavior:** Allow text styling for ClockDisplayNumbers and time picker content.
<img width="201" alt="Screenshot 2023-10-12 at 12 26 46 PM" src="https://github.com/material-components/material-components-android/assets/109819608/fe565ca2-f5f1-4e01-a41c-277fdc1ab9cc">

**Source code:** The code snippet which is causing this issue. In package androidx.compose.material3.TimePicker, the ClockDisplayNumbers function.
`CompositionLocalProvider(
        LocalTextStyle provides MaterialTheme.typography.fromToken(TimeSelectorLabelTextFont)
    )`

**Android API version:** 31

**Material Library version:** 1.1.0

**Device:** Pixel 4 API 31 Emulator

**Comment by hunterstich** [comment]
Hi @sunnyd-verily,

It looks like this is a Compose issue. Could you please file this bug on the Compose Material [issue tracker](https://issuetracker.google.com/issues?q=status:open%20componentid:742043&s=created_time:desc)?

Thanks!
