### ISSUE TITLE
[TextInputLayout]: The error message's disappearance resulted in excessive spacing between TextInputLayouts.

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [material-components/material-components-android#3633]
https://github.com/material-components/material-components-android/assets/123667347/77d58cce-91a5-4044-883a-a366fe192f05

Material components android version is 1.10.0

**Comment by hunterstich** [comment]
Hi @ArjunaKumarMohanta,

Could you attach a sample that has this issue? Could you also describe what you expect the behavior to be?

**Comment by pekingme** [comment]
This is WAI. If you want to make that space disappear, you should set all `helperTextEnabled`, `errorEnabled`, `counterEnabled` to `false`. Basically, `setError("xxx")` will `setErrorEnabled(true)` before displaying the error message. But `setError(null)` will not `setErrorEnabled(false)`. The goal is to avoid making layout change based on user's input. I think the best practice is to reserve the space by adding `app:errorEnabled="true"`, if you'd like to display some error messages.
