### ISSUE TITLE
[carousel] crash on arrangement null reference

### ISSUE THREAD

**Issue by nijuyonkadesu** [material-components/material-components-android#3634]
**Description:** I have list of images displayed in Carousel. Once navigated to a (settings) fragment, and comming back to main Carousel, my app crashes. When I looked at stacktrace I got: https://bin.utwitch.net/zodineqadi.apache

after `onResume()` callback, app crashes.
I was hopelessly searching on how to use `SavedStateHandle` to fix this and found:
(I absolutely do not understand this code, but it was odd to my eyes)
![image_2023-10-15_23-07-55](https://github.com/material-components/material-components-android/assets/85601344/7f4d4075-bb26-46b1-9c4e-8b276765365b)

**Expected behavior:** Carousel page should resume and show images from where it was before navigation action.

**Source code:** [fragment_carousel.xml](https://github.com/nijuyonkadesu/SAO/blob/settings/app/src/main/res/layout/fragment_carousel.xml), [CarouselFragment.kt](https://github.com/nijuyonkadesu/SAO/blob/settings/app/src/main/java/one/njk/sao/CarouselFragment.kt), [nav_graph.xml](https://github.com/nijuyonkadesu/SAO/blob/settings/app/src/main/res/navigation/nav_graph.xml)
but remove these two to reproduce the issue
```xml
app:launchSingleTop="true"
app:popUpTo="@id/nav_graph"
```

**Minimal sample app repro:** https://github.com/nijuyonkadesu/SAO/tree/settings

**Android API version:** 33

**Material Library version:** 
```
recycler-view = "1.3.1"
m3 = "1.10.0"
nav = "2.7.4"
```

**Device:** Redmi Note 11 [MIUI - Android 12], Redmi Note 9 Pro [Android 13 - Custom ROM]

**Comment by hunterstich** [comment]
Hey @nijuyonkadesu,

Thanks so much for filing an issue and for all the details. I'll take a look and get back to you.
