### ISSUE TITLE
[Predictive Back] Use OnBackPressedCallback in MaterialBackOrchestrator for Android 12-

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3637]
**Is your feature request related to a problem? Please describe.**
Android 12-: The navigation drawer *doesn't* support back behavior *automatically* (after pushing the back button, the opened navigation drawer will not be closed but the activity will be closed).
#3610
https://github.com/material-components/material-components-android/blob/master/docs/foundations/PredictiveBack.md#predictive-back-material-components

**Describe the solution you'd like**
Use the OnBackPressedCallback in the MaterialBackOrchestrator for Android 12-.

**Comment by hunterstich** [comment]
Hi @manabu-nakamura,

Thanks for filing this issue. We've talked about this within our team and with the AndroidX team. The consensus has been to only add automatic back handling on 33+ when the `android:enableOnBackInvokedCallback` manifest flag is set to true. This way we don't break behavior for developers who haven't opted in to the new OnBackInvokedCallback and haven't prepared to support predictive back.

**Comment by manabu-nakamura** [comment]
Thank you for your consideration.
