### ISSUE TITLE
[DatePicker] Add option to pass optional locale

### ISSUE THREAD

**Issue by TheFaithOne** [material-components/material-components-android#3645]
**Is your feature request related to a problem? Please describe.**
When the material date picker dialog is shown it uses phone's default locale which might not be correct for apps with different languages.

**Describe the solution you'd like**
Have an optional parameter on DatePicker composable or DatePickerState  that would allow passing of a desired locale.

**Describe alternatives you've considered**
The only other solution I've come across is setting app-wide locale which seems as a not-so-great workaround. Even while doing so, the year dropdown menu, title and headline seem to stay in the "default" language.

**Additional context**
See provided screenshot, where locale change only affects the names of days, but not the default title and headline or year dropdown menu.
<img width="315" alt="image" src="https://github.com/material-components/material-components-android/assets/19520534/527c911b-b695-4949-851e-dde7614e0468">

**Comment by Jeffwestley** [comment]
@https://youtube.com/channel/UC5wEHsE1eVoNpul_p-7Idng/store``

**Comment by pekingme** [comment]
It doesn't look right to create a DatePicker as your screenshot shows. I see in the code some places use `Locale.getDefault()` whereas other places use `getResources().getConfiguration().locale`. I think we should at least use the latter one for all strings to make it respect to the per-app locale configuration. 

However, I'm not sure if we want to add a new API to set custom locale to a single instance of MaterialDatePicker. It sounds less common to have a date picker dialog with a different locale as the rest of app or system. Please clarify if that's your use case.

**Comment by TheFaithOne** [comment]
Thanks for a swift response. I'm not trying to set the dialog to a different locale than the rest of the app The problem that I'm facing is the incosistency between the translations and the fact that after setting the default locale the change would only be reflected on the second dialog launch. However, I think, your proposed solution should fix the issues I'm having, once the correct locale is set app-wide. Did I understand that correctly?

**Comment by pekingme** [comment]
So how do you set your app-wise locale? I created a vanilla app and set the locale using this. The text in the date picker actually get translated. Do you have a sample code? Also let me know the API level you were running this on?

```
    val appLocale: LocaleListCompat = LocaleListCompat.forLanguageTags("cs-CZ")
    AppCompatDelegate.setApplicationLocales(appLocale)
```

**Comment by TheFaithOne** [comment]
In the project that I'm working on I tried using `AppCompatDelegate.setApplicationLocales(appLocale)` however that didn't change anything. I tried also setting `Locale.setDefault(Locale("cs", "CZ"))` right before showing the picker dialog and that's the state where the days of week are translated but the rest isn't. I'll attach a link to a demo branch where I've tried setting the locale thorough AppCompatDelegate but the picker is still in the phone's locale.

[https://github.com/TheFaithOne/Lets-darts/tree/feature/date-picker-example](url)

**Comment by pekingme** [comment]
You link is broken. Could you update? `AppCompatDelegate.setApplicationLocales(appLocale)` should be enough to set the app's locale. I also put the DatePicker creation code into a button, instead of directly call in the `onCreated`. All texts are shown as translated.

**Comment by TheFaithOne** [comment]
Sorry, I forgot that I created a branch in a private repo. Link has been updated. I'm doing pretty much the same thing in that example. I set the locale thorough `AppCompatDelegate` in app class and then in the activity I show the picker on button click

**Comment by pekingme** [comment]
Ooof, just realized you are using our Material for Android Compose library. This is a different implementation in AndroidX code base. I think you should submit the issue [here](https://developer.android.com/jetpack/androidx/releases/compose-material3#feedback). Closing the issue, since it's out of scope of this library.

Gradle using Material Compose:
```
    implementation("androidx.compose.material3:material3")
```
Gradle using Material Views:
```
    implementation 'com.google.android.material:material:1.11.0-alpha01'
```
