### ISSUE TITLE
[NavigationDrawerItem] Can't set NavigationDrawerItemColors

### ISSUE THREAD

**Issue by Randomboiii03** [material-components/material-components-android#3647]
**Description:**
I don't know if this is the place to send issue for Kotlin - Jetpack Compose but I can't set colors for NavigationDrawerItem in Jetpack Compose

**Expected behavior:** 
This is what the documentation has:
![image](https://github.com/material-components/material-components-android/assets/113816315/bad59862-0d44-4abd-9bed-452ece63c169)

This is what I tried:
![image](https://github.com/material-components/material-components-android/assets/113816315/176b5ded-47c2-4993-8d89-51b3d58da564)

This is what error:
![image](https://github.com/material-components/material-components-android/assets/113816315/54ae4891-1f18-40f9-87de-007a8d3ce743)

**Android API version:** Minimum Android SDK 26

**Material Library version:** androidx.compose.material3:material3:1.2.0-alpha10

**Comment by imhappi** [comment]
Hello, you can file issues for the Material Compose library here: https://issuetracker.google.com/issues/new?component=742043&template=1590761
