### ISSUE TITLE
[MaterialDividerItemDecoration] Divider appears instantly on insertion

### ISSUE THREAD

**Issue by entdark** [material-components/material-components-android#3651]
**Description:** Divider that is drawn with `MaterialDividerItemDecoration` appears or disappears instantly when adding or removing items from `RecyclerView` while items get faded in or out smoothly respectively.

**Expected behavior:** Divider that is drawn with `MaterialDividerItemDecoration` appears or disappears smoothly with the same in or out fading as items when adding or removing items from `RecyclerView`.

**Source code:** Regular code from Docs:
```Kotlin
val divider = MaterialDividerItemDecoration(context!!, LinearLayoutManager.VERTICAL)
recyclerView.addItemDecoration(divider)
```

**Minimal sample app repro:** -

**Android API version:** 29

**Material Library version:** 1.11.0

**Device:** Samsung Galaxy S9

**Extra**: Probably the fix should be somewhere here with setting `dividerDrawable` alpha to `child` alpha: https://github.com/material-components/material-components-android/blob/release-1.11/lib/java/com/google/android/material/divider/MaterialDividerItemDecoration.java#L333

**Comment by entdark** [comment]
Actually I tested myself my idea from the **Extra** part by using reflection and it worked as described in **Expected behavior**. So the fix is basically this:
```Java
dividerDrawable.SetAlpha((int)(child.GetAlpha() * 255));
```
Probably could be done with some value clamping to be safe.

**Comment by pekingme** [comment]
Great! Thanks for trying this out. @entdark Do you want to create a PR for your fix and claim the contribution? 😃

**Comment by entdark** [comment]
> Great! Thanks for trying this out. @entdark Do you want to create a PR for your fix and claim the contribution? 😃

Sure thing. I will try. Thanks.
