### ISSUE TITLE
[Slider] slider label is not scrolled with slider

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3660]
**Description:** The slider label (app:labelBehavior="visible") is not scrolled with the slider.
(before)
![Screenshot_20231102_212702](https://github.com/material-components/material-components-android/assets/71050561/49b06271-0435-4d4c-a65d-45a00d731e42)
(after)
![Screenshot_20231102_212711](https://github.com/material-components/material-components-android/assets/71050561/8845d38c-795b-40c4-b262-35222e584936)

**Expected behavior:** The slider label is scrolled with the slider.

**Minimal sample app repro:** Catalog app (SliderLabelBehaviorDemoFragment)

To scroll the slider, I added the following space to slider/res/layout/cat_slider_demo_label_behavior:
```
<View
  android:layout_width="match_parent"
  android:layout_height="800dp"/>
```

**Android API version:** 34

**Material Library version:** 1.11.0-beta01

**Device:** Emulator 32.1.15 (API 32)

**Comment by pekingme** [comment]
Duplicate with #2869
