### ISSUE TITLE
MaterialToolbar: minHeight not working when inside CollapsingToolbarLayout

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#3661]
**Description:** `android:height`, `android:minHeight` and other styling is not working. The `wrap_content` in `MaterialToolbar` is not using `minHeight` defined in themes/style if it is inside `CollapsingToolbarLayout`, but this is not the case when `MaterialToolbar` is a first child of `AppBarLayout` where `wrap_content` will use the defined `height ` and `minHeight` from style.

**Expected behavior:** 

Should no longer need to define hardcoded height since it is already defined in themes/style

<img width="1114" alt="image" src="https://github.com/material-components/material-components-android/assets/38008900/05d546ac-3cd6-4525-ad3a-18b853e620eb">

**Source code:** 

Layout
```
    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:liftOnScroll="false"
        android:fitsSystemWindows="true">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/collapsingToolbar"
            android:layout_width="match_parent"
            android:layout_height="400dp"
            android:fitsSystemWindows="true"
            app:contentScrim="?attr/colorPrimary"
            app:layout_scrollFlags="scroll|enterAlways|enterAlwaysCollapsed"
            app:maxLines="3">

            <androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/featuredImage"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:adjustViewBounds="true"
                android:fitsSystemWindows="true"
                android:src="@drawable/word_mark"
                android:background="@color/colorPrimaryDark"
                app:layout_collapseMode="parallax" />

            <com.google.android.material.appbar.MaterialToolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_collapseMode="pin"
                app:layout_scrollFlags="scroll|enterAlways|enterAlwaysCollapsed"
                app:title="@string/vwap" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>

    </com.google.android.material.appbar.AppBarLayout>
```

Style/Theme
```
<!-- Toolbar style on both light and night mode -->
    <style name="AppToolbarForCollapsing" parent="Widget.Material3.Toolbar" tools:keep="@style/AppToolbar">
        <item name="android:height">86dp</item>
        <item name="android:minHeight">86dp</item>
        <item name="contentInsetStart">0dp</item>
        <item name="contentInsetEnd">0dp</item>
        <item name="contentInsetStartWithNavigation">0dp</item>
        <!-- Action item color when colorOnSurfaceVariant is not working -->
        <item name="colorControlNormal">@color/colorPrimaryDark_White</item>
    </style>
```

Usage
```
    <!-- Activity theme for CollapsingToolbarLayout -->
    <style name="Theme.App.NoActionBar.TranslucentStatusBar">
        <item name="android:windowTranslucentStatus">true</item>
        <item name="toolbarStyle">@style/AppToolbarForCollapsing</item>
    </style>
```

This issue will cause toolbar to overlaps statusbar and scrolling behavior is just like using regular ScrollView with LinearLayout.

Note: It looks like `MaterialToolbar` turns into a regular`ActionBar` when inside `CollapsingToolbarLayout`

**Android API version:** 21

**Material Library version:** 1.10.0

**Device:** Pixel C Emulator

**Comment by imhappi** [comment]
Hi @ArcherEmiya05!

I took a look, and I believe this is happening due to logic inside CollapsingToolbarLayout that adds a view to toolbar to calculate the space within toolbar in which there can be text:

`toolbar.addView(dummyView, LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);`

If the toolbar height is `wrap_content`, it takes the parent's size which is the CollapsingToolbarLayout

Since this code is very old, please use the workaround (setting the toolbar height instead of 'wrap_content')
