### ISSUE TITLE
[MaterialCheckbox] buttonTint attribute removes checkmark

### ISSUE THREAD

**Issue by shannon-livefront** [material-components/material-components-android#3667]
**Description:** In every stable version since 1.6.1, the `buttonTint` attribute changes the background color of the checkbox (as expected) but also changes the color of the checkmark so that the checkmark is not visible (not expected).

**Expected behavior:** 
| Expected | Error |
| --- | --- |
| <video src="https://github.com/material-components/material-components-android/assets/125921730/c19da89f-dd3a-4e4d-b783-0a60fa735f8f" /> | <video src="https://github.com/material-components/material-components-android/assets/125921730/87e2b98e-fb6c-4ffa-891c-606d73c06dbe" /> |

**Source code:** I do not think the checkbox I'm using has any special customizations that could cause this.
```
                    <com.google.android.material.checkbox.MaterialCheckBox
                        android:contentDescription="@string/check_in_ready_next_content_desc"
                        android:id="@+id/readyNextCheckbox"
                        android:buttonTint="@color/peacock"
                        android:layout_height="wrap_content"
                        android:layout_marginEnd="16dp"
                        android:layout_width="wrap_content"
                        app:layout_constraintBottom_toBottomOf="@id/getAText"
                        app:layout_constraintEnd_toStartOf="@id/getAText"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="@id/getAText" />
```

**Android API version:** 33

**Material Library version:** It works as expected on 1.6.1 but the error occurs on every version after that.

**Device:** The results were the same on every simulator I tried, as well as my physical device (a Galaxy S9).

**Comment by imhappi** [comment]
Please use `buttonIconTint` to set the color of the icon

**Comment by shannon-livefront** [comment]
Thank you for the fast response! However, changing `buttonTint` to `buttonIconTint` on the latest version (1.10.0) still doesn't produce the expected result:

https://github.com/material-components/material-components-android/assets/125921730/e0a2fcee-879d-4f49-add7-35bd5f570e79
