### ISSUE TITLE
[Chip] Transparent background not works.

### ISSUE THREAD

**Issue by ReeMiXeR** [material-components/material-components-android#367]
Hello!
I faced with issue, I can't make chip view background transparent.

`<com.google.android.material.chip.Chip
        style="@style/R12.White"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:chipBackgroundColor="@color/red"
        app:chipIcon="@drawable/ic_gallery"
        app:chipStrokeColor="@color/red"
        app:chipStrokeWidth="2dp"
        app:iconStartPadding="6dp"
        app:textEndPadding="6dp"
        tools:text="23" />`
If I set red text - everything works.
<img width="152" alt="Screenshot 2019-05-16 at 17 24 59" src="https://user-images.githubusercontent.com/18577596/57861865-1211cb80-7800-11e9-8af5-ba0d6de2be0d.png">
 but if I set  `app:chipBackgroundColor="@color/transparent"`
I have this
<img width="152" alt="Screenshot 2019-05-16 at 17 24 33" src="https://user-images.githubusercontent.com/18577596/57861914-248c0500-7800-11e9-977b-65bed9fcc7cb.png">
I use 1.1.0-alpha06 version

**Comment by leticiarossi** [comment]
Hello, chips have a surface layer underneath their background (meaning they are opaque) of value colorSurface, which is by default white in the MaterialComponents theme. So when you set the background color to transparent it reveals that white surface layer.
Chips also have a chipSurfaceColor attribute that you can set to change that surface color.

**Comment by pixnbit** [comment]
chipSurfaceColor is only exposed through a xml property, can you also add one for the Java/Kotlin?

**Comment by liompei** [comment]
chipSurfaceColor is only exposed through a xml property, can you also add one for the Java/Kotlin?

**Comment by Bharath-android** [comment]
app:chipBackgroundColor="@color/transparent"
this xml attribute in chips use for handle chips background color.

**Comment by minas1** [comment]
The accepted solution works only when setting `chipSurfaceColor` on a specific Chip in a layout.
**It does not work for styles.**

**Comment by nishant-iapp** [comment]
<style name="CustomChipStyle" parent="Widget.MaterialComponents.Chip.Filter">
        <item name="chipBackgroundColor">@color/chip_background_color</item>
        <item name="chipSurfaceColor">@color/chip_background_color</item>
        <item name="android:textAppearance">@style/CustomChipText</item>
        <item name="android:textColor">@color/chip_text_color</item>
        <item name="checkedIconTint">@color/chip_text_color</item>
    </style>
