### ISSUE TITLE
Calling BottomAppBar.FabAlignmentMode with an ExtendedFloatingActionButton not working

### ISSUE THREAD

**Issue by HeryLopez** [material-components/material-components-android#369]
Calling `BottomAppBar.FabAlignmentMode` with an `ExtendedFloatingActionButton ` does not execute the change of position

Possible solution : add validation by  `instanceof FloatingActionButtonand` and `instanceof ExtendedFloatingActionButton`

https://github.com/material-components/material-components-android/blob/2130d8655098b26525221ece30b0fef8ef70ea4a/lib/java/com/google/android/material/bottomappbar/BottomAppBar.java#L468

**Comment by ymarian** [comment]
This was resolved.

https://github.com/material-components/material-components-android/commit/9678f62c281c02e048e6e9539f7c56babda5ba5d#diff-9a4137109b1f53073d4dcf5ce4d6a034
