### ISSUE TITLE
(BUG) found in material-components-android The setting option in Regular Title is not working

### ISSUE THREAD

**Issue by facebook-786** [material-components/material-components-android#370]
# Project Information

* Repository: https://github.com/material-components/material-components-android
* Project Name:  material-components-android

# Expected behavior

When I click on the Settings button, all options in the Settings button should have appeared

# Actual behavior

The setting option in Regular Title is not working

# How to reproduce

1-[Download ](https://github.com/material-components/material-components-android/releases)the app and open it
2- Click the Top App Bar at the bottom left-hand side
3- click on Demo
4-At the top right click on three vertical lines
5-Click the setting option
6- see bug

* Browser/App version:  1.1.0-alpha06
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190520_032907](https://user-images.githubusercontent.com/50115498/57989238-aa9c8b80-7a4c-11e9-9756-08259ed74f4a.gif)

# My Github Account
https://github.com/facebook-786

**Comment by leticiarossi** [comment]
Hello! The Top App Bar demo shows examples of how things can look like in an app using that component. The location of the settings button, as well as of the the other buttons, is just for demo purposes. They are not intended to perform actions.

**Comment by facebook-786** [comment]
thank you sir for your positive feedback
