### ISSUE TITLE
Multiple language didn't work after update to 1.1.0-alpha06

### ISSUE THREAD

**Issue by bkhezry** [material-components/material-components-android#371]
I use this tutorial for supporting multiple languages in my app.
https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758
it works. but after update version of my material components to 1.1.0-alpha06, loading resources didn't work anymore.
I fork the project of that tutorial and just add material components version 1.1.0-alpha06 to it. it not work but with alpha05 it works. 

Source code: https://github.com/bkhezry/LanguageTest 
<p float="left">
  <img src="https://user-images.githubusercontent.com/91809/58134691-d8482700-7c3c-11e9-804d-7d0fbe590af5.png" width="300" />
  <img src="https://user-images.githubusercontent.com/91809/58134692-d8482700-7c3c-11e9-8a2f-6abca91db3dd.png" width="300" />
</p>

**Comment by bkhezry** [comment]
I just add this bug to issue tracker
https://issuetracker.google.com/issues/133249125

**Comment by leticiarossi** [comment]
This has been answered in the issue tracker link
