### ISSUE TITLE
FloatingActionButton android:tint not work in 1.1.0-alpha06

### ISSUE THREAD

**Issue by bkhezry** [material-components/material-components-android#372]
I use `Theme.MaterialComponents.Light.NoActionBar` for the style of my app. after update to material components 1.1.0-alpha, `android:tint` of FAB didn't work anymore. It work with `Theme.AppCompat.Light.DarkActionBar` style
source code: https://github.com/bkhezry/FABTest
![Selection_008](https://user-images.githubusercontent.com/91809/58166239-9fd93500-7c9e-11e9-8810-469ce491e417.png)

**Comment by jacklroberts** [comment]
If it's icon tinting you want it's changed to app:tint

**Comment by bkhezry** [comment]
It works. thanks.
