### ISSUE TITLE
TextInputLayout with AppCompatEditText/Edittext padding problem

### ISSUE THREAD

**Issue by kiskunk** [material-components/material-components-android#374]
+Description: When using the new Material Library TextInputLayout (alpha06) with either androidX's AppcompatEditText, or EditText, the TextInputLayout's floating hint is 2-3 times higher than it was in alpha05. Setting paddings to the EditText just make the floating hint to go inside the EditText's text.

- Expected behavior: Hint positioned correctly from the background line, and moves above the EditText's text when its not null

- Source code: 

<com.google.android.material.textfield.TextInputLayout
                android:id="@+id/til_expiry_date"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="16dp"
                android:layout_marginEnd="16dp"
                android:hint="@string/expiry_date_hint"
                android:textColorHint="@color/colorGreyAlternativeDark"
                android:visibility="visible"
                app:counterTextColor="@color/colorGreyAlternativeDark"
                app:errorEnabled="true"
                app:errorTextColor="@color/colorRed"
                app:hintTextColor="@color/colorGreyAlternativeDark">

                <androidx.appcompat.widget.AppCompatEditText
                    android:id="@+id/et_expiry_date"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@android:color/transparent"
                    android:clickable="true"
                    android:drawableEnd="@drawable/ic_date"
                    android:focusable="false"
                    android:focusableInTouchMode="false"
                    android:foreground="?attr/selectableItemBackground"
                    android:inputType="text"
                    android:paddingStart="0dp"
                    android:paddingEnd="0dp"
                    android:paddingBottom="8dp"
                    android:text=""
                    android:textColor="@android:color/black"
                    android:textSize="16sp" />
            </com.google.android.material.textfield.TextInputLayout>

- Design Library Version: alpha06

- Android API version: API 23-29

- Device: Any device + emulators

**Comment by leticiarossi** [comment]
Answered in https://issuetracker.google.com/issues/133280839 you can follow up there
