### ISSUE TITLE
Outlined stroke doesn't work for TextInputEditText

### ISSUE THREAD

**Issue by CeH9** [material-components/material-components-android#377]
Docs says:

> Note: When using a filled text field with an EditText child that is not a TextInputEditText, make sure to set the EditText’s android:background to @null. This allows TextInputLayout to set a filled background on the EditText.

Stroke works for **1.0.0** without @null, but for **alpha06** it doesn't

**Comment by leticiarossi** [comment]
What exactly is not working? Can you provide a sample of your code and more details about your issue and expected behavior?

**Comment by CeH9** [comment]
It was my fault. I tried to apply theme inside style instead of directly in layout:
 
``` xml
<style name="OutlinedBox" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
     <item name="android:theme">@style/Theme.MaterialComponents.Light</item>
</style>
```
