### ISSUE TITLE
Elevation overlay doesn't work properly if parent view has some elevation

### ISSUE THREAD

**Issue by Sourav-21** [material-components/material-components-android#381]
Suppose there are Tabs on a Dialog. In dark theme due to elevation the background of Dialog is medium grey. But the background of Tabs are still dark grey. Here the Tabs doesn't use the parent view (dialog) elevation properly.
![Screenshot_20190531-203131](https://user-images.githubusercontent.com/20728734/58714834-3b774d80-83e3-11e9-903d-ed2ec99d4f9d.png)

**Comment by dsn5ft** [comment]
Hi @Sourav-21, thanks for reporting! This sounds like an interesting issue.

Can you clarify what you mean by "Here the Tabs does use the parent view (dialog) elevation properly."?

**Comment by Sourav-21** [comment]
@dsn5ft, I think the problem lies in `MaterialShapeDrawable`. When elevation is 0, `MaterialShapeDrawable` should be transparent. But In dark theme `MaterialShapeDrawable` displays `colorSurface`.

**Comment by dsn5ft** [comment]
Got it, yeah the `colorSurface` layer can be problematic in some cases, but without it it's hard to guarantee that there will be enough contrast between the lightened background and the text/iconography on top of it. Will chat with our designers about what's best here.
