### ISSUE TITLE
About shape theming, is it possible to get the customized shape of the OS?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#382]
In the "catalog" sample, there is "shape theming" part:

![image](https://user-images.githubusercontent.com/5357526/58739406-aee48380-8412-11e9-8f3c-9b8a9a09461d.png)

Is it possible to check on Android Q (and before?) which shape is used, and have a drawable based on it?

I'm talking about this:

![image](https://user-images.githubusercontent.com/5357526/58739444-d76c7d80-8412-11e9-8334-1b3cb700d826.png)

If it's possible, please show how.
If it's not, can you please tell Google to add it? It can be useful for better consistency ...

**Comment by melaniegoetz** [comment]
Currently, no, there is not integration with the operating system default and material theming. However, you can find our documentation for the current shape theming capabilities here : https://material.io/develop/android/theming/shape/ 
Thank you fo the feature request -- we will pass this off to our design team for consideration!

**Comment by melaniegoetz** [comment]
You can follow the issue tracker bug for this feature request: https://issuetracker.google.com/issues/134429165

**Comment by AndroidDeveloperLB** [comment]
What about the other types of customization that can be set on the OS ?
The font, the accent color?

And speaking about colors, is it possible on pre-Q to get the colors of the theme?
On Android 8.1 wallpapers and live wallpapers could give the OS a clue about the colors to use.
Same for 9.0, yet there was such an option for the user to force it.
