### ISSUE TITLE
Bug: in sample "demos-java-io-material-demo-shrine", settings items can't be pressed on the left

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#383]
For some reason the items aren't clickable. Only the right area is clickable:

![image](https://user-images.githubusercontent.com/5357526/58739535-637ea500-8413-11e9-99b9-d4f890fad5ed.png)

How come?

**Comment by ymarian** [comment]
Hi! These are clickable or you mean the colors?  
It's just not up to date I believe, since it's an example. Please check the material catalog for more switches, and checkboxes usage.

**Comment by AndroidDeveloperLB** [comment]
No. I mean that only if I press on the switch/checkbox itself, it does anything.
If I click on the item (entire row), nothing occurs.

This means that if I click on "woman" or on any space between it and the checkbox, nothing occurs.
Same goes for the switch.
