### ISSUE TITLE
[Catalog] Display version of Material Components in Catalog app

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3833]
**Is your feature request related to a problem? Please describe.**
We don't know the version of the Material Components used by the Catalog app.

**Describe the solution you'd like**
Display the version of the Material Components (or the Catalog app itself) in the Catalog app.

**Comment by imhappi** [comment]
Hi @manabu-nakamura !
`Material 3` is already in the main Catalog page toolbar title

If you meant which library version the Catalog app is on, it's always pointing to the head which may have changes that don't correspond to any release yet

**Comment by manabu-nakamura** [comment]
I have several catalog-debug.apks that I downloaded from https://github.com/material-components/material-components-android/releases to confirm the difference of the old and new Material Components. Could you please display the version of the Material Components (1.11.0-beta01 or 20231020) instead of the version of the Material Design (3) in the Catalog app?
