### ISSUE TITLE
Bug: in "catalog" sample, in action-bar demos, popup has black text color on black background

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#384]
Choosing either "action bar demo" or "dark action bar demo", it shows black text on black background:

![image](https://user-images.githubusercontent.com/5357526/58739574-b193a880-8413-11e9-8e69-b00731f55d5c.png)

![image](https://user-images.githubusercontent.com/5357526/58739579-b8222000-8413-11e9-8591-52ddf5a74891.png)

**Comment by abn-volk** [comment]
This is not only a bug in the sample app but a bug in the library as well.

**Comment by AndroidDeveloperLB** [comment]
How come it's a bug on the library?
Can you please show me its bug report on the issue tracker?

**Comment by melaniegoetz** [comment]
Thanks for reporting this! Filing a bug in issue tracker to address this visual issue https://issuetracker.google.com/issues/134406889

**Comment by AndroidDeveloperLB** [comment]
Google says it's not a bug on the library, but on the sample itself:
https://issuetracker.google.com/issues/134406889#comment3
