### ISSUE TITLE
[OutlinedCard] Default BorderStroke uses Outline style instead of OutlineVariant

### ISSUE THREAD

**Issue by mobilekosmos** [material-components/material-components-android#3850]
**Description:** Full description of issue here
As per [material specs](https://m3.material.io/components/cards/specs#80df927a-2997-445d-af10-6012db40c53c) the default border color for should be outline-variant, the implementation uses OutlinedCardTokens.OutlineColor.toColor() which is way darker.

**Expected behavior:** Screenshots and/or description of expected behavior
Docs and impl should match.

**Source code:** The code snippet which is causing this issue
```
        OutlinedCard(
            modifier = modifier
                .weight(1f)
                .wrapContentSize()
                .clickable(
                    enabled = onElementClick != null,
                    onClick = { onElementClick!!.invoke() },
                ),
            border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant)
        )
```

**Android API version:** 34

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
COMPOSE_MATERIAL_3 = "1.1.1"
GOOGLE_MATERIAL_COMPONENTS = "com.google.android.material:material:1.9.0"
(Cannot update to the newest versions till Hilt merges a fix they already have in head)

**Device:** Pixel 6a

**Comment by imhappi** [comment]
Hi! This is the Material Views library; you can file issues for the Material Compose library here: https://issuetracker.google.com/issues/new?component=742043&template=1590761
