### ISSUE TITLE
Request for Assistance: Shared Axis (X) Transition Java Code and Demo APK

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [material-components/material-components-android#3851]
Could you please provide the Java code for a shared axis (x) transition between activities, along with a demo APK?

**Comment by afohrman** [comment]
Hi @ArjunaKumarMohanta, we have code samples for Shared Axis Activity transitions in our [motion documentation](https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md#transition-between-activities-1). You can also find demo code in the Catalog app in the Transitions package, see [`TransitionSharedAxisStartDemoActivity.java`](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/transition/TransitionSharedAxisStartDemoActivity.java) and [`TransitionSharedAxisEndDemoActivity.java`](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/transition/TransitionSharedAxisEndDemoActivity.java).

You can find an APK for the Catalog in any of our [latest releases](https://github.com/material-components/material-components-android/tags), or you can [build it yourself](https://github.com/material-components/material-components-android/blob/master/docs/catalog-app.md#catalog-app) from a cloned repo.
