### ISSUE TITLE
[BottomSheetScaffold] Sheet moves to `PartiallyExpanded` when the content is updated

### ISSUE THREAD

**Issue by HumairaPasha** [material-components/material-components-android#3859]
**Description:** When the sheet is in HIDDEN state, and the sheet content is updated, sheet moves to PartiallyExpanded state.
The following code defined in AnchorChangeHandler (defined in material) seems to map both Hidden & PartiallyExpanded to expanded;

```Kotlin
val newTarget = when (previousTarget) {
        Hidden, PartiallyExpanded -> PartiallyExpanded
        Expanded -> if (newAnchors.containsKey(Expanded)) Expanded else PartiallyExpanded
    }
```

**Expected behavior:** Sheet should retain its state i.e. should stay hidden

**Source code:** 

Use `BottomSheetScaffold` with peek height supplied like so;
```Kotlin
SheetScaffold(
    sheetState = scaffoldState.bottomSheetState,
    sheetPeekHeight = 120.dp,
    sheetContent = {}) {
  }
```
Update the content dynamically changing the sheetContent from a one paragraph text to say a 3 paragraph text.
The sheet will move to partially expanded state. 

**Android API version:** 33

**Material Library version:** material3: 1.1.2

**Device:** PIXEL 4 API 29 (emulator)

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by afohrman** [comment]
Hi @HumairaPasha, thanks for filing! This is the Material Android Views repo, and this appears to be an issue with Material Android Jetpack Compose. Could you please file this issue in [their issue tracker](https://issuetracker.google.com/componentid:742043)?
