### ISSUE TITLE
shouldAnimateCaptionView() returns true even when it shouldn't

### ISSUE THREAD

**Issue by gkylafas** [material-components/material-components-android#386]
Calling `shouldAnimateCaptionView()` with `captionText == null` will return true even when the `captionView` has no text, since `TextView.getText()` returns the empty string, not null, when the field is empty.
See https://github.com/material-components/material-components-android/blob/4bbf385a21e08a7f7a216a2ee8daedda0e7bbe7c/lib/java/com/google/android/material/textfield/IndicatorViewController.java#L195

So perhaps instead of `null`, you should call `shouldAnimateCaptionView()` with `captionText == ""`.

**Comment by melaniegoetz** [comment]
Thanks for reporting this! Filing an issue tracker bug to track this https://issuetracker.google.com/issues/134405407
