### ISSUE TITLE
[BadgeDrawable] Bug: setBadgeGravity being ignored as I want it to be TOP_END

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#3860]
**Description:** Full description of issue here
I'm trying to have the badge shown to the top-end of the FrameLayout container, but for some reason it keeps being at the top-start.

![image](https://github.com/material-components/material-components-android/assets/5357526/855139b0-0c70-49d6-8be5-9265f834f790)

**Expected behavior:** Screenshots and/or description of expected behavior
To have the badge shown on top-end

**Source code:** The code snippet which is causing this issue
```
val itemBinding = ActionViewVerticalBinding.inflate(inflater, binding.frameLayout, false)
binding.frameLayout.addView(itemBinding.root)
itemBinding.actionTitleTextView.text = "text"
itemBinding.actionImageView.setImageResource(android.R.drawable.ic_dialog_email)
val badgeDrawable = BadgeDrawable.createFromResource(context!!, 0)
badgeDrawable.number = 2
badgeDrawable.badgeGravity = BadgeDrawable.TOP_END
BadgeUtils.attachBadgeDrawable(
    badgeDrawable,
    itemBinding.actionImageView,
    itemBinding.badgeContainer
)
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.
Attached. Just run it.

**Android API version:** Android API version here
Android API 34

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.11.0-rc01

**Device:** Device on which the bug was encountered here
Pixel 6 
 
[My Application.zip](https://github.com/material-components/material-components-android/files/13426788/My.Application.zip)

[app-debug.zip](https://github.com/material-components/material-components-android/files/13426792/app-debug.zip)

**Comment by imhappi** [comment]
Hi @AndroidDeveloperLB !
I suspect that this might be happening not because the badge gravity is being ignored, but because you are attaching the badge too early to the action image view that has just been added to a frame layout with `wrap_content` as its dimensions

Could you try calling `badgeDrawable.updateBadgeCoordinates` in a layout listener?

**Comment by AndroidDeveloperLB** [comment]
@imhappi What do you mean? It already has what it needs and it gets attached to the FrameLayout, no?
Why does it need extra listener, and what do you mean in layout listener? 

You mean like this:

```
binding.root.doOnPreDraw {
    badgeDrawable.updateBadgeCoordinates( itemBinding.actionImageView,binding.frameLayout)
}
```

?
But I already used `BadgeUtils.attachBadgeDrawable` with the same parameters...
Is there a sample with this? 
Why can't we have a simple BadgeView and we choose how and where to put it, if it forces us to use FrameLayout as a container anyway...

Anyway, I tried it, and for some reason it moved the badge to the bottom-end, instead of top-end...

![image](https://github.com/material-components/material-components-android/assets/5357526/29c34692-b7fa-481e-bbd0-bddc022fc61b)

[My Application.zip](https://github.com/material-components/material-components-android/files/13430941/My.Application.zip)

**Comment by imhappi** [comment]
Hi @AndroidDeveloperLB 
It looks like you are calling `updateBadgeCoordinates` with passing `binding.frameLayout` as the custom badge parent, but it should be `itemBinding.badgeContainer` as that is what you passed as the custom badge parent in `attachBadgeDrawable`.

As as to why it needs to be called in a layout listener here, the badge positions itself based on the size of the anchor view (actionImageView in this case) which may not have a size yet in onCreateView. If you are attaching the badges before the view has been created, the badge needs to be updated after the anchor view has a size.

**Comment by AndroidDeveloperLB** [comment]
@imhappi Oh sorry for this mistake.

About the requirement:
But for every View you add to some container, you never have to add such a listener, even if it's positioned based on size/gravity of something else. 
See the case of ConstraintLayout and RelativeLayout.

Can't we have a View for the badge instead? This usage is so weird. I call it twice to be aligned to its anchor view and parent...

Is it a Drawable in order to handle special cases that we have no control over the container?

**Comment by AndroidDeveloperLB** [comment]
I created a function to do it instead of this weird duplicate call:

```
@androidx.annotation.OptIn(com.google.android.material.badge.ExperimentalBadgeUtils::class)
fun BadgeDrawable.attachToView(anchor: View, customBadgeParent: FrameLayout?) {
    BadgeUtils.attachBadgeDrawable(this, anchor, customBadgeParent)
    anchor.doOnPreDraw {
        updateBadgeCoordinates(anchor, customBadgeParent)
    }
}
```
