### ISSUE TITLE
[TopAppBar] Regression in 1.12.0-alpha01 due to 'Compress effect' recent commit

### ISSUE THREAD

**Issue by bubbleguuum** [material-components/material-components-android#3873]
Since 1.12.0-alpha01, there is a regression where calling `getSupportActionBar#hide` on an action bar backed by a `MaterialToolbar` having ` app:layout_scrollEffect="compress"` and set as first child of an `AppBarLayout` , will do nothing when this call is made and the toolbar is not visible because it is "compressed". This means that  `getSupportActionBar#hide` did nothing and the when undoing the compress effect, the toolbar will be visible instead of being hidden.

It worked in `1.11.0-beta01` and I believe this regression is caused by 2ac8c1cbf6cb5aea7d60ef5655bed7d014e5f930

It seems in that commit that a check is missing to not make `child` unconditionally visible.

**Comment by dsn5ft** [comment]
@hunterstich can you investigate this one?

**Comment by bubbleguuum** [comment]
Still an issue in `1.12.0-beta01`. If I want to upgrade from `1.11.0` and not be affected by this issue I have to ,anually revert 2ac8c1cbf6cb5aea7d60ef5655bed7d014e5f930 ...

**Comment by bubbleguuum** [comment]
This has been fixed by this recent commit: 17855c116b7ea7d7404ef84a23c2eac36cb958db
