### ISSUE TITLE
[release note] broken link?

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3882]
**Description:** Is [Tonal Surface Color system](https://m3.material.io/styles/color/the-color-system/color-roles#0abbf8b7-61e1-49ee-9f97-4967beb1e4fe) a broken link in https://github.com/material-components/material-components-android/releases?

**Expected behavior:** Update the release note.

**Comment by dsn5ft** [comment]
Thanks! Updated to the blog post https://material.io/blog/tone-based-surface-color-m3 which has more useful information on the change and migration, and also links back to the spec.
