### ISSUE TITLE
getText() always return empty string from dynamically created Chip component

### ISSUE THREAD

**Issue by Kenc44** [material-components/material-components-android#394]
I'm trying to dynamically create some choice chip components based on an ArrayList of String from some computation and following are the code to create the chips and adding them to a ChipGroup created in layout XML file.

```
        if (mChipGroup.getChildCount() == 0 ){
            int i = 0;
            for (Classifier.Recognition res: results){
                Chip resultChip = new Chip(getDialog().getContext());
                ChipDrawable chipDrawable =
                        ChipDrawable.createFromAttributes(
                                getActivity(),
                                null,
                                0,
                                R.style.Widget_MaterialComponents_Chip_Choice);
                resultChip.setId(i++);
                resultChip.setChipDrawable(chipDrawable);
                resultChip.setText(res.getTitle());
                mChipGroup.addView(resultChip);
            }
        }
```
The Chips displayed correctly with the text but when I tried to call getText() on the chips, it always return empty String but not the text contained by the chips. I tested this by setting the OnCheckedChangeListener on the ChipGroup and making a Toast with the text (though it didn;'t work). When I tried to display only the checkedId it works.

```

        mChipGroup.setOnCheckedChangeListener(new ChipGroup.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(ChipGroup group, int checkedId) {
                Chip chip = group.findViewById(checkedId);
                if(chip != null){
                    Toast.makeText(getContext(), chip.getText().toString(),Toast.LENGTH_SHORT).show();
                }
            }
        });
```
My current workaround is to have a variable holding the array results and use `ArrayList.get(selectedChipId.getTitle())`. but don't think it should be that way though

I also found that it is able to get text from Chips added in layout file but not run-time added Chips. Tried with both 1.1.0/alpha06 and 1.1.0/alpha07 release but am having no luck. Would like to have some advice if possible. Thank you very much.

**Comment by ymarian** [comment]
Hi it seems the text will be in the ChipDrawable. 

Does chip.getChipDrawable().getText() work? 

Seems like a bug though, filed this one: 
https://issuetracker.google.com/issues/135180392

**Comment by Kenc44** [comment]
Hi, thanks for the response. Yes it works when getting the text from the ChipDrawable instead. Just to make it more clear, it is `((ChipDrawable) chip.getChipDrawable()).getText()` since `getChipDrawable()` seems to only return `android.graphics.drawable.Drawable` object which does not support `getText()`.

**Comment by wcshi** [comment]
Hi @Kenc44 are programmatically creating a ChipDrawable and setting it on a chip in order to programmatically specify the chip style?

Have you tried creating a theme overlay that can be passed into the chip constructor?

**Comment by Kenc44** [comment]
Hi @wcshi I only create a `ChipDrawable `and setting the `ChipDrawable `using `setChipDrawable()` and didn't  do anything related to theme overlay.

**Comment by wcshi** [comment]
This should fix your issue:
https://github.com/material-components/material-components-android/commit/8c0f6f72c96d502cde11504f02cd5b9042fe25fd#diff-517b28ba515355e7ccfece81507a8cc1

**Comment by Kenc44** [comment]
Yes that fixed the issue. Thanks.
