### ISSUE TITLE
[TextField] TextInputLayout Preview is broken

### ISSUE THREAD

**Issue by PabloJuice** [material-components/material-components-android#3945]
**Description:** TextInputLayout 1.11.0 Preview is broken. Text overflows start icon, if padding is set on EditText - size of it becomes 'wrap_content'. This stuff is only on Preview, on real app screen everything seems ok.

**Expected behavior:** In 1.10.0 version:
![image](https://github.com/material-components/material-components-android/assets/48531000/e1329570-6157-42d3-bf0c-ab4dcbfaca8c)

**Source code:** 
![image](https://github.com/material-components/material-components-android/assets/48531000/39e3dd45-a738-49d7-8e9b-2b8c30212bc9)

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 34

**Material Library version:** 1.11.0

**Device:** Google Pixel 7 34 API Emulator

**Comment by dsn5ft** [comment]
@PabloJuice can you either file a bug in Android Studio or at https://issuetracker.google.com/issues/new?component=192708&template=840533?
