### ISSUE TITLE
[Carousel] We urgently need the Carousel component on the Jatpack Compose side.

### ISSUE THREAD

**Issue by Melendez1209** [material-components/material-components-android#3946]
**Describe the solution you'd like**

I've seen the Jetpack Compose side of the Material Design website in development for a long time, and I'm especially eager to use it in my open source project.

**Describe alternatives you've considered**

I've been replacing Carousel with a streaming layout for a long time in my open source project (unreleased) like this

**Comment by paulfthomas** [comment]
Hi, the Carousel is still in active development on the Compose side and will be released as soon as it's ready, thanks for your interest!
