### ISSUE TITLE
[Surface Colors] Programmatically resolved surface container colors broken on API 31-33

### ISSUE THREAD

**Issue by patzly** [material-components/material-components-android#3954]
**Description:** Hi! I recently migrated a project's surfaces to use the new tone-based surface color roles from `v1.11.0`. This includes setting colors programmatically instead of in the layout xml with the following method:

```java
// Utility method
public static int getColorAttr(Context context, @AttrRes int resId) {
  TypedValue typedValue = new TypedValue();
  context.getTheme().resolveAttribute(resId, typedValue, true);
  return typedValue.data;
}

// Example
view.setBackgroundColor(getColorAttr(context, R.attr.colorSurfaceContainer));
```

Using the new color roles in xml works perfectly. But as soon as I resolve the attributes programmatically, things are getting really weird and unexpected. This is just the case with the new surfaceContainer color roles, all other attributes are behaving normally. On API 31-33, depending on deactivated or activated dark mode, some of the new color roles become transparent!
| ![Screenshot_20231225_184434](https://github.com/material-components/material-components-android/assets/33599892/e7a269c3-c7b0-4e7d-b263-5741f08db62d) | ![Screenshot_20231225_184527](https://github.com/material-components/material-components-android/assets/33599892/39e4a6a7-f4a1-45be-ada1-cebf05917b09) |
| -------- | ------- |

As I said, with `v1.11.0` this only affects themes with dynamic color applied on Android 12-13 (API 31-33), but when I downgrade to `v1.10.0`, this also affects Android 14.  
I couldn't find any reason for this weird, "random" behavior in the library but the system color palette is the same on all plattform versions as the attributes and color roles are fully library-specific...   
Another weird observation: the programmatically resolved colors are not fully transparent (#00000000). Instead, it's some transparent color like #000001B2 (the first two zeros are the alpha channel).  
Hope you can find the reason and a fix quickly!

**Expected behavior:**

| ![Screenshot_20231225_191938](https://github.com/material-components/material-components-android/assets/33599892/81d12b5d-c7d7-45d3-88af-336bc6fe3a57) | ![Screenshot_20231225_191950](https://github.com/material-components/material-components-android/assets/33599892/6704005a-4a61-49f2-b06a-3e18834ac143) |
| -------- | ------- |

**Source code:**

```java
@Override
protected void onCreate(@Nullable Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);

  AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO); // or YES as visible in the screenshots

  DynamicColors.applyToActivityIfAvailable(this);

  binding = ActivityMainBinding.inflate(getLayoutInflater());
  setContentView(binding.getRoot());

  binding.view1.setBackgroundColor(getColorAttr(this, R.attr.colorSurfaceContainerLowest));
  binding.view2.setBackgroundColor(getColorAttr(this, R.attr.colorSurfaceContainerLow));
  binding.view3.setBackgroundColor(getColorAttr(this, R.attr.colorSurfaceContainer));
  binding.view4.setBackgroundColor(getColorAttr(this, R.attr.colorSurfaceContainerHigh));
  binding.view5.setBackgroundColor(getColorAttr(this, R.attr.colorSurfaceContainerHighest));
}

private static int getColorAttr(Context context, @AttrRes int resId) {
  TypedValue typedValue = new TypedValue();
  context.getTheme().resolveAttribute(resId, typedValue, true);
  return typedValue.data;
}
```

I've attached a minimal sample repo with the tiny app from above to reproduce the issue down below.

**Minimal sample app repro:** [test-surface](https://github.com/patzly/test-surface)

**Android API version:** 31-33 (and 34 when using `v1.10.0`)

**Material Library version:** 1.10.0-1.11.0 (not testable with older versions as the color roles are new)

**Device:** API 31-33 emulators and Poco F3 (Android 13), with 1.10.0 also on Pixel 6 (Android 14)

**Comment by pekingme** [comment]
@patzly Please use [MaterialColors.getColor()](https://github.com/material-components/material-components-android/blob/701d5c262715a8593cbbac714e3472e55c4fad59/lib/java/com/google/android/material/color/MaterialColors.java#L80C21-L80C29) to resolve the theme color attributes, especially for tonal surface color.

The rationale is that we leverage the `android:lStar` tag in CSL to achieve some tones, which are not provided in the system neutral palette. The theme attribute is a reference, which has a small number in `.data`, which will be treated as a transparent color. `MaterialColors.getColor()` can give you the proper **color** value regardless.

**Comment by patzly** [comment]
@pekingme Thank you so much! I've looked at the theming docs and didn't found this, maybe this would be a good point there?

**Comment by pekingme** [comment]
Added in Colors doc, will be pushed out soon. Thanks for the suggestion!
