### ISSUE TITLE
[Progress Indicator] Track is almost indistinguishable from the indicator when the monochrome theme is enabled

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3955]
<img width="270"  src="https://github.com/material-components/material-components-android/assets/82187521/3d2baf77-c744-4133-8396-9e575313cb15">

**Material Library version:** [`701d5c2`](https://github.com/material-components/material-components-android/tree/701d5c262715a8593cbbac714e3472e55c4fad59)
**Android API version:** 34

**Comment by pekingme** [comment]
Resolved with dd8f6be
