### ISSUE TITLE
How can I full the ImageView/View when I use cut corner in Material CardView

### ISSUE THREAD

**Issue by ShowMeThe** [material-components/material-components-android#398]
![V1S{$PYXRJ6QS$X1A`5V382](https://user-images.githubusercontent.com/30461332/59548413-97180e00-8f81-11e9-9cf0-bbaeb91be029.png)

  <style name="MediumComponent" parent="ShapeAppearance.MaterialComponents.MediumComponent">
        <item name="cornerFamily">cut</item>
        <item name="cornerSize">10dp</item>
    </style>
Use the cut corner in theme

**Comment by ymarian** [comment]
Hi we have an internal bug tracking this but it's tricky to solve. You could do a workaround like this for now:
Extending MaterialCardView
https://github.com/googlesamples/android-sunflower/pull/437

You will also have to set app:preventCornerOverlap="false" in your cards.
