### ISSUE TITLE
[MaterialAutoCompleteTextView] When focus lost and regained the position of the filtered items are not correct on the setOnItemClickListener

### ISSUE THREAD

**Issue by kelalaka153** [material-components/material-components-android#3982]
**Description:** 

1. Use `android:inputType="textAutoComplete"`
2. set items with  `app:simpleItems="@array/countries"`
3. Select an item (preferably not the first one)
4. tap and start filtering - DO NOT  select an item, preferably leave non-completed.
5. tap somewhere else to lose focus (no need to lose focus, just the popup menu disappears enough)
6. Tap the MaterialAutoCompleteTextView so that the list appears for selection.
7. select an item and print the position
8. The position is not the original position on the non-filtered it is on the filtered position

**Expected behavior:**

Return the position from the non-filtered.

**Source code:** 

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 

Version 30+

**Material Library version:**

material:1.11.0

**Device:**

Emulator and physical device

[AutoCompleteTextViewBug_1.tar.gz](https://github.com/material-components/material-components-android/files/13866295/AutoCompleteTextViewBug_1.tar.gz)

**Comment by kelalaka153** [comment]
Note, when I supplied the MaterialAutoCompleteTextView with a custom ArrayAdapter with filter as

```
override fun getFilter(): Filter = object : Filter() {
        override fun performFiltering(constraint: CharSequence?): FilterResults {
            val filteredItems = if (constraint.isNullOrBlank()) {
                items
            } else {
                items.filter { it.getItemName()?.contains(constraint, ignoreCase = true) ?: false }
            }
            val results = FilterResults()
            results.values = filteredItems
            results.count = filteredItems.size
            return results
        }

        override fun publishResults(constraint: CharSequence?, results: FilterResults?) {
            @Suppress("UNCHECKED_CAST")
            filteredItems = results?.values as List<T>
            notifyDataSetChanged()
        }
    }
```

I've got the same problem. So the core of the problem may no be the filter system.

**Comment by kelalaka153** [comment]
I want to note that, focus loss is not necessary, the video shows the problem. The returned position of the Andorra ( not specific to it) is a relative, not an absolute position. So, we cannot directly map or access the object. Is this somwhow intended behavior?


https://github.com/material-components/material-components-android/assets/46725068/e52d1f3e-a61d-4975-a08b-0e4b8dde8392

**Comment by dsn5ft** [comment]
@kelalaka153 can you check if `countriesAutoCompleteTextView.getAdapter().getItemAtPosition(position)` returns the correct item? That should take into account the current filtering because the adapter keeps and updates it's own internal `mObjects` list, whereas `arrayCountries!![position]` doesn't take into account filtering.

**Comment by kelalaka153** [comment]
@dsn5ft Ok. This solves this issue, though I expected the returned position to be the real one. I suggest adding another position to the listener to make the codes simpler.
