### ISSUE TITLE
How do you set the icon of a Button?

### ISSUE THREAD

**Issue by aljohnston112** [material-components/material-components-android#3996]
In the examples for the icon button here: https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md#icon-button
the most important part (setting the icon of the button) is left out

**Comment by leticiarossi** [comment]
Thanks, will update the documentation. To set an icon it's the same as the other examples where there's one set, you need to set `app:icon`, or programmaticaly via `setIcon`.
