### ISSUE TITLE
Release on JCenter and/or Maven central.

### ISSUE THREAD

**Issue by JakeWharton** [material-components/material-components-android#4]
This library can only be consumed through the Android SDK's 'android' m2repository. Doing so requires accepting a non-standard license despite the fact that all of the contained components are Apache 2-licensed and open source.

Now that this library is on GitHub and new processes are being put in place, getting this library to be available on JCenter or Maven central should be a high priority. **There is no logical legal or business reason why the support libraries are not current there.** Thankfully now you have the power to change this in the migration. If you need prior art, there are _hundreds_ of Google repositories on GitHub whose source of truth is internal but sync'd with MOE or other means to GitHub which are under the same license as this project and are available on Maven central.

Please unburden we Android developers from the current arcane process of obtaining this library from a non-standard source, with a non-standard license, and using non-standard non-incremental massive binary downloads. JCenter and/or Maven central are the de-facto, widely-used, widely-understood, and standard mechanism for distributing artifacts and they should be used by this library.

_(Please **do not** comment with "+1" or similar on this issue. Use [GitHub's reactions][1].)_

 [1]: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by jestelle** [comment]
Thanks Jake! Wholeheartedly agree. We're excited to move Design Lib here to GitHub now as Material Components, which as you point out, helps pave the way for getting this available on JCenter and/or Maven.

This is something we're absolutely interested in and working towards.  We've still got some details to work through to making this happen, but rest assured, we're on it.

Thanks!
Josh

**Comment by Jawnnypoo** [comment]
I suppose this can be closed now 😄

**Comment by dsn5ft** [comment]
Closing this out as we have been releasing to [maven.google.com](https://maven.google.com) with the new `com.google.android.material` namespace for the past several releases 😊
