### ISSUE TITLE
Update Material Code Lab for Android to use the Android Studio Layout Editor

### ISSUE THREAD

**Issue by pedrosax** [material-components/material-components-android#40]
### Overview

https://codelabs.developers.google.com/codelabs/mdc-android/index.html#0

The material design code lab  does not utilize the graphic design tools in Android Studio and the sample tutorial code is not importable in the Samples Browser in Android Studio. 

### Request 

 - Update guide to use design tools built into Android Studio
 - Add sample code to the Samples Browser in Android Studio
 - Also note best practice is not to incline dimensions in a style.xml file ( https://codelabs.developers.google.com/codelabs/mdc-android/index.html#0), but instead but all the dimensions in a dimens.xml

**Comment by ldjcmu** [comment]
Closing as this issue is old and we have updated the codelabs many times since.
