### ISSUE TITLE
[Slider] left side disappears too early

### ISSUE THREAD

**Issue by HotarunIchijou** [material-components/material-components-android#4009]
**Description:** Start (left side) of the slider disappears when handle even doesn't reach the end

**Expected behavior:** It shouldn't disappear that way

**Material Library version:** 1.12.0-alpha03

**Screen record:** 

https://github.com/material-components/material-components-android/assets/113282550/7d099d27-a44e-4322-aaa4-4b939c8cb291

**Comment by leticiarossi** [comment]
I can reproduce it in our catalog for both sides, @paulfthomas is it expected behavior? otherwise could you take a look?

**Comment by HotarunIchijou** [comment]
I don't see this issue for right side. If the slider's value is from 0 to 11, it disappears on ~0.55 at the start, while at the end it disappears in about ~10.75 and there's a dot as well
