### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by Kaisercoding** [material-components/material-components-android#401]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

**Comment by Kaisercoding** [comment]
Hello I get this error message when I downloaded and tried to sync the project:

Unable to find method 'org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry.registerPublication(Ljava/lang/String;Lorg/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectPublication;)V'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by dsn5ft** [comment]
I think this is because we don't support Gradle 5.0 yet for this project, and Android Studio probably prompted you to update Gradle when opening our project. Similar to #375 and #320.

**Comment by tefari** [comment]
I got this to work by reimporting project from git source and choosing the never prompt me again for this project option in android studio when it asks you to upgrade your gradle version.
