### ISSUE TITLE
'error:Resource not found' with ExposedDropdownMenu 

### ISSUE THREAD

**Issue by adityabhaskar** [material-components/material-components-android#402]
I am trying to use ExposedDropdownMenu as described [here](https://material.io/develop/android/components/menu/#exposed-dropdown-menus), but getting a resource not found an error on `@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu`. I am using '`com.google.android.material:material:1.0.0`'. 

Is ExposedDropdownMenu only available in the 1.1.x alpha? If so, the documentation, specially on [this page](https://material.io/develop/android/components/menu/#exposed-dropdown-menus), should specify so.

If not, I'd love any help in resolving the issue.

Cheers!

---

There's also an [unanswered question](https://stackoverflow.com/questions/56557435/cant-resolve-widget-materialcomponents-textinputlayout-exposeddropdownmenu) on this at SO.

**Comment by ymarian** [comment]
Hi you are correct, unfortunately material.io doesn't support versioning. So the docs there will always be the latest ones.

If you need to access docs from 1.0.0, they are actually the same as the github repo, so you can access them through the tagged releases. 

https://github.com/material-components/material-components-android/tree/1.0.0/docs/components

**Comment by adityabhaskar** [comment]
Is it possible to specify the current library version on the material.io pages? A link to the latest stable release's docs would also be helpful. 

Currently, material.io pages give the impression that they are based on the current stable release. 

Since material.io seems to be the primary reference source, it is misleading developers to assume that the latest alpha features are available in stable. Unless we come and check (this) source repository.
