### ISSUE TITLE
Problem Scroll RecyclerView and hideOnScroll with BottomAppBar

### ISSUE THREAD

**Issue by privetr** [material-components/material-components-android#404]
Hi, 

I have encountered a problem using the BottomAppBar and RecyclerView in the same layout. 
At first, the last item of the list is behind the BottomAppBar, and the hideOnScroll attribute seems to don't work with my actual layout. 

If you have any advices it would be great, I tried a lot of different solutions but without any success. 

Here is my layout : 

`<?xml version="1.0" encoding="utf-8"?>
  <androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activityProductListDatabaseLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_height="?android:attr/actionBarSize"
            android:layout_width="match_parent"
            style="@style/Widget.MyApp.ActionBar"/>

    </com.google.android.material.appbar.AppBarLayout>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/errorLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

     

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/productRecyclerView"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"/>

    </androidx.constraintlayout.widget.ConstraintLayout>

    <com.google.android.material.bottomappbar.BottomAppBar
        android:id="@+id/bottomAppBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        app:backgroundTint="@color/colorPrimary"
        app:fabAlignmentMode="center"
        style="@style/Widget.MaterialComponents.BottomAppBar"
        />

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/resetProductListButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_anchor="@id/bottomAppBar"
        app:rippleColor="@color/negative"
        android:src="@drawable/ic_delete"
        android:backgroundTint="@color/colorButtonAction"/>

</androidx.coordinatorlayout.widget.CoordinatorLayout>

`

Here is the wrong result : 
![Screenshot_20190619-084803](https://user-images.githubusercontent.com/8597289/59742941-1e5dce00-926f-11e9-80ec-514d7a523a10.png)

**Comment by paolovalerdi** [comment]
You can get rid of that constraint layout that wraps your recycler view, and add the behavior (`app:layout_behavior="@string/appbar_scrolling_view_behavior"`) directly to the recycler view.
