### ISSUE TITLE
Material Design version 1.1.0-alpha06 does not get built with androidX libraries on v 1.0.0

### ISSUE THREAD

**Issue by imranbaigshortcut** [material-components/material-components-android#405]
Material Design version 1.1.0-alpha06 does not get built with android X libraries on v 1.0.0.
Build-time errors are thrown in the Kotlin code.

**Comment by ymarian** [comment]
can you share your build.gradle and the errors you are getting?

**Comment by MenosGrante** [comment]
As I know, some parts of 1.1.0 alpha depends on new 1.1.0 alphas of Android X libraries, so it won't work with stable Android X dependencies.

**Comment by dsn5ft** [comment]
Correct, we need to depend on some alpha/beta androidx libraries to get the latest fixes:

https://github.com/material-components/material-components-android/blob/master/build.gradle#L27-L42
