### ISSUE TITLE
[Slider] Always visible label still shows up when hiding its fragment

### ISSUE THREAD

**Issue by vikz95** [material-components/material-components-android#4064]
**Description** 
When using version `1.11.0`:
* A slider with `app:labelBehavior="visible"` presents a bug on scroll, the label does not follow the new position of the slider. This bug was documented here https://github.com/material-components/material-components-android/issues/2869
* When moving to a different fragment the slider labels of the former fragment are no longer visible

When using version `1.12.0-alpha03`:
* The https://github.com/material-components/material-components-android/issues/2869 issue is fixed
* But when I hide a fragment and show another one under the same FragmentManager, the slider labels of the first fragment are not hidden and still show up.
* Showing fragment of tab Setup 1, label position follows slider position on scroll as expected: 
![label scroll fixed](https://github.com/material-components/material-components-android/assets/25623862/6b68d132-7c53-4e04-9210-829afcf159ab)
* Showing fragment of tab Setup 2, but also the labels of the Setup 1 fragment are visible: 
![label still visible when changing fragment](https://github.com/material-components/material-components-android/assets/25623862/026526ab-a886-4195-87f3-27e744786d4e)

**Expected behavior:** When hiding a fragment also the slider labels should be hidden.

**Source code:** 
I know that instead of adding all the fragments and hiding/showing them maybe I could use `replace()`, but in version `1.11.0` when hiding a fragment even the label is hidden as expected, so a bug was introduced in the alpha releases.
```
childFragmentManager.commit {
            setReorderingAllowed(true)
            add(R.id.call_setup_fragment_container, callSetupFragments[0], "Setup1")
            add(R.id.call_setup_fragment_container, callSetupFragments[1], "Setup2")
            hide(callSetupFragments[1])
            add(R.id.call_setup_fragment_container, callSetupFragments[2], "Setup3")
            hide(callSetupFragments[2])
            add(R.id.call_setup_fragment_container, callSetupFragments[3], "Setup4")
            hide(callSetupFragments[3])
        }

        binding.callSetupTabs.addOnTabSelectedListener(object : TabLayout.OnTabSelectedListener {
            override fun onTabSelected(tab: TabLayout.Tab?) {
                childFragmentManager.commit {
                    tab?.let { show(callSetupFragments[it.position]) }
                }
            }

            override fun onTabUnselected(tab: TabLayout.Tab?) {
                childFragmentManager.commit {
                    tab?.let { hide(callSetupFragments[it.position]) }
                }
            }

            override fun onTabReselected(tab: TabLayout.Tab?) {
            }

        })
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 34

**Material Library version:** `1.12.0-alpha03`

**Device:** Xiaomi Pad 6 and Samsung Galaxy tabS5e.

**Edit:** I tried also the latest SNAPSHOT version `1.12.0-SNAPSHOT` and can confirm that the issues is still present.

**Comment by manabu-nakamura** [comment]
@vikz95, does the latest 1.13.0-SNAPSHOT (https://github.com/material-components/material-components-android/commit/9bf5eddd8a181793d9818f12a1522c69fd9c1b36) cause this issue?

**Comment by vikz95** [comment]
Yes, I tried the latest snapshot version and when I move to another tab, all the slider labels from the previous tab are visible.

**Comment by manabu-nakamura** [comment]
Hmm... Is it impossible to provide the minimum sample app? I don't understand this issue completely. In order to understand this issue, I created a sample app (which uses a fragment) and [the simplified version](https://github.com/material-components/material-components-android/issues/4319) (which doesn't use a fragment).

**Comment by vikz95** [comment]
I created a [sample app](https://github.com/vikz95/sample-app-android-slider-label-issue) using the latest version of the libraries and the issue was not present. 
Thus I realized that it wasn't `android.material` fault, but it was due to an old version of `androidx.fragment:fragment-ktx`, after updating this library to the latest version (`1.8.4`) everything wotks fine even in my application.

**Comment by vikz95** [comment]
@manabu-nakamura I updated the [sample app](https://github.com/vikz95/sample-app-android-slider-label-issue) adding also scrolling.
So feel free to download the repo and try to debug.

**Comment by manabu-nakamura** [comment]
1.13.0-alpha06 seems to cause this issue, but 1.13.0-SNAPSHOT doesn't seem to cause this issue (https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md). Try it!

**Comment by vikz95** [comment]
I can confirm that `1.13.0-SNAPSHOT ` doesn't cause the issue in my sample app.

But even with the snapshot version the issue is still present in my production app. 

For now we can close this issue, I have no idea how to reproduce it in the sample app.

**Comment by manabu-nakamura** [comment]
Enjoy debugging!
