### ISSUE TITLE
[Dialog] can't apply m3 style dialog to PreferenceFragment

### ISSUE THREAD

**Issue by PangBaiWork** [material-components/material-components-android#4072]
**Is your feature request related to a problem? Please describe.**
I use PreferenceFragmentCompat to save preference,but I find it won't extend m3-style widgets.I try to change alertDialogStyle to some 
dialog styles of material3,then my app crashed.
**Describe the solution you'd like**
add m3-style PreferenceFragment
**Describe alternatives you've considered**
make dialog styles of material3 to be a possible value of alertDialogStyle
**Additional context**

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by Pittvandewitt** [comment]
1 This m3 style is part of the AndroidX preference library
2 The AndroidX preference library is in [maintenance mode](https://issuetracker.google.com/issues/181793702#comment3), so don't expect updates on this topic
3 A solution is available on [StackOverflow](https://stackoverflow.com/a/61424867)
