### ISSUE TITLE
Textinputlayout messing up when setting an height

### ISSUE THREAD

**Issue by dissennatore** [material-components/material-components-android#408]
```
<com.google.android.material.textfield.TextInputLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:id="@+id/username"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintBottom_toTopOf="@+id/password"
            app:layout_constraintVertical_chainStyle="spread_inside"
            app:layout_constraintHeight_default="percent"
            app:layout_constraintHeight_percent="0.2"
            android:hint="ggggggggggggggggg"
            android:background="@color/primaryColor"
            app:boxStrokeColor="@color/secondaryDarkColor"
            app:boxStrokeWidth="10px">
            <com.google.android.material.textfield.TextInputEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                />
        </com.google.android.material.textfield.TextInputLayout>
```

This is part of a constrained layout, and I have the same issue even if I set the `height` of `Textinputedittext` to `match_parent`; the result is [this](https://i.stack.imgur.com/Jv6uX.png)

If I let the `Textinputlayout`'s `height` being `wrap_content` it works without problems, so I think that it has an issue while scaling, and it doesn't do it properly

**Comment by akashmehta** [comment]
facing same issue.

**Comment by abalta-mobven** [comment]
I have same issue when I set fixed dp of TextInputLayout. I think minimum size is 56dp according to TextFields specs.

https://material.io/components/text-fields/#specs

**Comment by IniongunIsaac** [comment]
Facing the same issue. How can it be overcome?

**Comment by VitKap** [comment]
You can customize the TextInputLayout styles to make TextInputLayout smaller.
https://stackoverflow.com/a/57765685/9317258

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Comment by VitKap** [comment]
When you need to make the `TextInputLayout` smaller than 56dp for some reason there is not an easy way to do it. So it is still hapenning but I don't know if this is a bug or a definition by specs.

**Comment by drchen** [comment]
Hi @VitKap, thanks for the info.

Unfortunately I guess it's very difficult for us to keep a complex UX working perfectly when there are too limited spaces for it....
It's not ideal but I would say it's kind of working as intended....

**Comment by J6ey** [comment]
Hi guys I figured it out!
Set `android:padding="0dp"` on `TextInputEditText`. Now you can set the layout height of `TextInputLayout`.

Cheers!

**Comment by hemant-cloudfeather** [comment]
Adding to what @J6ey  already said, you can control the height of `TextInputLayout` by setting its height as `wrap_content` and by playing  with `TextInputEditText`'s padding value.
