### ISSUE TITLE
[BottomSheet] Corner style affects on material buttons inside the bottom sheet

### ISSUE THREAD

**Issue by USisFounderOfISIS** [material-components/material-components-android#4082]
**Description:** Using extended style of `Widget.Material3.BottomSheet` affect on shape of material buttons inside the bottom sheet (see bellow)

![image](https://github.com/material-components/material-components-android/assets/125660596/98869c42-c052-4122-aeef-690c44b47ead)
![image](https://github.com/material-components/material-components-android/assets/125660596/578fea26-c757-4afc-88e0-500537079ab0)

When I use `ThemeOverlay.Material3.BottomSheetDialog` as parent style it doesn't affect on the shape of its child but this has some other issues.

**Expected behavior:** ![image](https://github.com/material-components/material-components-android/assets/125660596/19322d01-1bd3-432d-af25-22251e4cf2fe)

**Source code:** 

```
<style name="Base.Theme.App" parent="Theme.Material3.DayNight.NoActionBar">
       ....
        <item name="bottomSheetDialogTheme">@style/My_Material3_Light_BottomSheetDialog</item>
</style>
```

```
    <style name="My_Material3_Light_BottomSheetDialog" parent="Widget.Material3.BottomSheet">
        <item name="cornerSizeTopLeft">24dp</item>
        <item name="cornerSizeTopRight">24dp</item>
        <item name="behavior_fitToContents">true</item>
        <item name="behavior_draggable">true</item>
        <item name="behavior_hideable">true</item>
        <item name="behavior_saveFlags">none</item>
        <item name="behavior_halfExpandedRatio">0.72</item>
        <item name="enableEdgeToEdge">false</item>
        <item name="behavior_skipCollapsed">true</item>

    </style>
```
And this is a button inside the bottom sheet (for close button/icon of bottom sheet)

```
<com.google.android.material.button.MaterialButton
            android:id="@+id/button"
            style="@style/Widget.Material3.Button.IconButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginEnd="@dimen/space_m"
            android:contentDescription="@null"
            app:icon="@drawable/ic_pen" />
```

**Android API version:** 30,

**Material Library version:** Material Android Library version 1.11.0

**Comment by pekingme** [comment]
`bottomSheetDialogTheme` should set a `ThemeOverlay` instead of a `Widget` style. Please try to update your styles based on [dev doc](https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheet.md).

```
<style name="ModalBottomSheet" parent="Widget.Material3.BottomSheet.Modal">
  <!-- Apply attributes here -->
</style>

<style name="ModalBottomSheetDialog" parent="ThemeOverlay.Material3.BottomSheetDialog">
  <item name="bottomSheetStyle">@style/ModalBottomSheet</item>
</style>

<style name="AppTheme" parent="Theme.Material3.*">
  <item name="bottomSheetDialogTheme">@style/ModalBottomSheetDialog</item>
</style>
```

**Comment by USisFounderOfISIS** [comment]
> `bottomSheetDialogTheme` should set a `ThemeOverlay` instead of a `Widget` style. Please try to update your styles based on [dev doc](https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheet.md).
> 
> ```
> <style name="ModalBottomSheet" parent="Widget.Material3.BottomSheet.Modal">
>   
> </style>
> 
> <style name="ModalBottomSheetDialog" parent="ThemeOverlay.Material3.BottomSheetDialog">
>   <item name="bottomSheetStyle">@style/ModalBottomSheet</item>
> </style>
> 
> <style name="AppTheme" parent="Theme.Material3.*">
>   <item name="bottomSheetDialogTheme">@style/ModalBottomSheetDialog</item>
> </style>
> ```

This also has the same problem in some special cases. For example, set the corner radius to 50dp and display a snackbar at the bottom of the bottomsheet. The upper corners of the snack bar are also 50 dp!

**Comment by pekingme** [comment]
If you set `cornerSizeTopLeft` and `cornerSizeTopRight` in a ThemeOverlay, it will override them in all the `shapeApperance`. Could you show me your updated styles?
