### ISSUE TITLE
[Component name] Color?

### ISSUE THREAD

**Issue by Smeagol2069** [material-components/material-components-android#4086]
**Description:** All google apps have a pink hue to them. From what I could tell its related to the material feature that this repository is for. I tried changing my background multiple times to change the color, but nothing happened. This effects Google Calendar, Contacts, Drive, Gmail, etc.

**Expected behavior:** I would expect the apps to change color based on the background

**Minimal sample app repro:** See images ![Screenshot_20240302_092549_Calendar.jpg](https://github.com/material-components/material-components-android/assets/78649849/5611c479-03f0-4cb5-a5a1-9d36e697eda6) (Google Calendar, most Google apps have the same color, but it never changes based on the wallpaper)

![Screenshot_20240302_092557_One UI Home.jpg](https://github.com/material-components/material-components-android/assets/78649849/a96570fc-8ffa-4a92-be7b-ffd1dc2d07aa) (Current wallpaper)

**Android API version:** I don't know how to check

**Material Library version:** I don't know how to check

**Device:** Samsung S22 , One UI 6.0 , Android 14

I apologize if this is the wrong place to report this. I couldn't find where to go and this repository seemed related to the issue.

**Comment by pekingme** [comment]
There's a known issue with Samsung dynamic color. Duplicate with #3924
