### ISSUE TITLE
[Slider] Stop indicators have the incorrect style near the handles (sometimes)

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#4096]
https://github.com/material-components/material-components-android/assets/82187521/b58ca3d9-fea8-423e-9376-e0e123650a56

**Details:**
- Device resolution: 1080x2400px (411x914dp)
- Slider size: 996x126px (379x48dp)
- Slider configuration:
  - `android:valueFrom="0"`
  - `android:valueTo="100"`
  - `android:stepSize="1"`
  - `app:tickVisible="true"`

**Material Library version:** [`22de817`](https://github.com/material-components/material-components-android/tree/22de817c30a493fb7dda46a8bea784d5bdc1dbdb)

**Comment by paulfthomas** [comment]
Fixed in https://github.com/material-components/material-components-android/pull/4097
