### ISSUE TITLE
[Dynamic colors] Getting custom color palette

### ISSUE THREAD

**Issue by interblitz** [material-components/material-components-android#4098]
Is there any way to get programmatically custom color palette like at https://m3.material.io/theme-builder#/custom? I would like to use with them in code...

![image_1426](https://github.com/material-components/material-components-android/assets/19166985/27f9d536-da7f-4372-bacc-a1669d623318)

**Comment by pekingme** [comment]
I don't see the theme builder generate any palettes. Feel free to reach out for feature requests.

https://github.com/material-foundation/material-theme-builder/issues

One thing you can try is to create your own color XML resources with the seed color and target tone like this and load it programmatically.

[lib/java/com/google/android/material/color/res/color-v31/m3_ref_palette_dynamic_neutral98.xml](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/color/res/color-v31/m3_ref_palette_dynamic_neutral98.xml)
