### ISSUE TITLE
[datepicker] Change of mtrl_picker_range_header_only_start_selected. 

### ISSUE THREAD

**Issue by durgeshrjkumar** [material-components/material-components-android#4099]
<string name="mtrl_picker_range_header_only_start_selected" description="Placeholders for two dates separated by a dash representing a range where start date has been selected [CHAR_LIMIT=60]">%1$s – End date</string>

This is in Datepicker library. 
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/res/values/strings.xml link is here.

I want to change value of End date to something like Return date. 
How it is possible.
Please provide a method so that we can update this text.

**Comment by drchen** [comment]
You can just declare a string resource with the same name in your app, and it's supposed to override the library resource.
