### ISSUE TITLE
Improve docs - what version to use

### ISSUE THREAD

**Issue by PunchyRascal** [material-components/material-components-android#41]
It would be very helpful to expand the docs as to what version one is supposed to put in the brackets in:

>dependencies {
>    compile 'com.android.support:design:[Library version code]'
>}
(https://material.io/components/android/)

I had to do some trial/error figuring, only thanks to compiler/IDE hints.

Information I would have been happy to see there:
- what is meant by "Library"
- what is meant by code (is this word needed there at all - seems confusing)
- what is the list of available versions or where to find them
- what is the logic behind the appropriate process of determining the right version

**Comment by TheCraftKid** [comment]
Yeah, the text replacing the brackets should be the matching the version of the [Android support libraries](https://developer.android.com/topic/libraries/support-library/packages.html) being used in a given app. I think the docs should just use the latest stable version (currently 26.0.0) to avoid confusion:

```
dependencies {
    implementation 'com.android.support:design:26.0.0'
    // ...
}
```

**Comment by dsn5ft** [comment]
Closing as our docs have been updated - https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md
