### ISSUE TITLE
[Menu] Menu needs to be redesigned

### ISSUE THREAD

**Issue by HotarunIchijou** [material-components/material-components-android#4110]
Menu component hasn't been changed since Material Design 2 (exclude colors), so it looks pretty old. Suggesting a redesign for it:
- change shape to medium, which is 12dp corner radius (issue will occur with dropdown menu, because text field has extra small 4dp rounding, but it will look much better for icon button menu)
- change container color to surface container high (menu often appears in header, which has surface container elevation in scrolled state, so it'll be good for contrast)

example of redesigned menu in the most common case (ref palette, appeared from icon button on surface with surface container elevation):
![](https://github.com/material-components/material-components-android/assets/113282550/c2fcde9a-cfbc-44aa-8ac0-c3de7a33c382)

**Comment by hunterstich** [comment]
Hi @HotarunIchijou,

Thanks for filing a feature request! Design is planning on reworking menus. I'm going to close this issue as we're track this internally for the time being.
