### ISSUE TITLE
[Dialog] Icon isn't where the specs say

### ISSUE THREAD

**Issue by beatrizz** [material-components/material-components-android#4121]
**Description:** According to the specs (https://github.com/material-components/material-components-android/blob/master/docs/components/Dialog.md#anatomy-and-key-properties) when a dialog has an icon, it's at the top, above the title. However, when we set an icon in a dialog, we see the icon appear on the left of the title (in English).

![image](https://github.com/material-components/material-components-android/assets/2212284/412cb92a-ac2f-4ad7-99c1-ff22801c38a8)

Looking at the implementation (https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/res/layout/m3_alert_dialog_title.xml) the icon is in the title layout. It's the first component inside a linear layout with horizontal orientation (https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/res/values/styles.xml#L69), so the code puts it on the left (in LTR languages) of the title.

![image](https://github.com/material-components/material-components-android/assets/2212284/7efdb36c-bab0-40a2-9e9d-139a2ad75bbe)

**Expected behavior:** The code and the specs match

**Source code:**
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/res/layout/m3_alert_dialog_title.xml
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/res/values/styles.xml#L69

**Minimal sample app repro:** N/A

**Android API version:** 30

**Material Library version:** 1.11.0

**Device:** Emulator

cc @eartle

**Comment by hunterstich** [comment]
Hi @beatrizz!

Thanks so much for filing an issue.

I'm sure you're aware but you can create the center stacked dialog by either overriding your theme's `materialAlertDialogTheme` attribute to `ThemeOverlay.MaterialComponents.MaterialAlertDialog.Centered` or create one-off centered dialogs by passing in the theme overlay to `MaterialAlertDialogBuilder`'s constructor. 

I doubt we will make the theme use centered dialogs by default as it would be a large breaking visual change at this point, but I will bring it up and see what the team thinks.

**Comment by beatrizz** [comment]
Thanks @hunterstich! I wasn't aware and we'll use that. We were trying to work around it with a custom title view.

From the specs, I thought the centered icon was now the default. If default dialogs stay as they are, I think it'd be useful if you could update the specs to show the default dialog (or both styles!) to avoid confusion, but it's of course up to the team. I see the attribute is documented as "Centered theme overlay" but I wasn't able to work out that it'd put the icon above the title from that description. An image or a more detailed explanation would also help there.

Thanks!
