### ISSUE TITLE
[ProgressIndicator] Track in CircularProgressIndicator doesn't close smoothly

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#4124]
https://github.com/material-components/material-components-android/assets/82187521/b8e7222f-5d47-4ebe-a34f-119815018138

**Material Library version:** 1.12.0-beta01

**Comment by pekingme** [comment]
It looks smooth to me ^^; Could you elaborate more?

**Comment by pubiqq** [comment]
Sure, here's the same video, but trimmed and cropped:

https://github.com/material-components/material-components-android/assets/82187521/40f41a0c-539b-4d52-8cc3-1e9801ca1b03

**Comment by pekingme** [comment]
Ah~ I see. Now I see the "Snap!". Thanks for reporting!
