### ISSUE TITLE
[Slider] The value should only appear on one handle at a time

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#4127]
<img width="328" src="https://github.com/material-components/material-components-android/assets/82187521/53ab84c1-3254-40aa-83d3-9a4717b7e7ea">

[Source](https://m3.material.io/components/sliders/guidelines#1138b466-b985-464f-a1f3-f7ec47dcf1a2)

**Material Library version:** 1.12.0-beta01

**Comment by hunterstich** [comment]
Hey @paulfthomas, would you have a chance to look at this issue?

**Comment by paulfthomas** [comment]
Changing this to a feature request as this code for the labels hasn't been updated in a while, checking with design if it's something we want to do.

**Comment by paulfthomas** [comment]
The guidance is to always show both values unless both are already visible somewhere outside the slider so it's working as intended. Feel free to open a PR if you really want to be able to only show one but it won't be the default behavior.

**Comment by pubiqq** [comment]
Am I somehow misreading the [guideline](https://m3.material.io/components/sliders/guidelines#1138b466-b985-464f-a1f3-f7ec47dcf1a2)?

![](https://github.com/material-components/material-components-android/assets/82187521/90efe7f8-1cd2-472f-85ad-3315b6a55871)

**Comment by pubiqq** [comment]
@paulfthomas, am I somehow misreading [the guideline](https://m3.material.io/components/sliders/guidelines#1138b466-b985-464f-a1f3-f7ec47dcf1a2)?

![](https://github.com/material-components/material-components-android/assets/82187521/90efe7f8-1cd2-472f-85ad-3315b6a55871)
