### ISSUE TITLE
com.google.android.material.navigation.NavigationWidget.initializeActivity

### ISSUE THREAD

**Issue by Mansi79708** [material-components/material-components-android#4134]
![Capture](https://github.com/material-components/material-components-android/assets/73010326/f7880a08-ec7d-4fc1-9097-e1da5cc90bd8)
I'm using library 
   implementation 'com.google.android.material:material:1.6.0'
 
getting crash  
 Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: LbotX/mod/p/ۦۖۧ;
com.google.android.material.navigation.NavigationWidget.initializeActivity

Please check attach image and let me update for this crash

**Comment by hunterstich** [comment]
Hi @Mansi79708. I don't recognize `NavigationWidget` as part of our library. We'd need more information to help debug what you might be facing. Are you able to attach a sample that reproduces the issue?

**Comment by Mansi79708** [comment]
> Hi @Mansi79708. I don't recognize `NavigationWidget` as part of our library. We'd need more information to help debug what you might be facing. Are you able to attach a sample that reproduces the issue?

I already attached crash logs of my application, there is no other way to reproduce the issue.  One more thing, in my whole project I am not using **`NavigationWidget`** . but still, users are facing this crash.

**Comment by Mansi79708** [comment]
Hi, @hunterstich. I already attached crash logs of my application, there is no other way to reproduce the issue. One more thing, in my whole project I am not using NavigationWidget . but still, users are facing this crash.

**Comment by hunterstich** [comment]
@Mansi79708 I don't think we can help here if we have no way to reproduce the issue. Could this be coming from NEWBusinessCardMainActivity?

**Comment by Mansi79708** [comment]
I cleaned, rebuilt, and created the build again from Android Studio, and now not getting this crash.

Thanks @hunterstich for giving your valuable time and support.

**Comment by hunterstich** [comment]
Great! Glad you got it working.
