### ISSUE TITLE
[Color] Update from 1.10.0 to 1.11.0 many components require android:background

### ISSUE THREAD

**Issue by mywalkb** [material-components/material-components-android#4135]
**Description:** I have an activity with more fragments, after the update from 1.10.0 to 1.11.0 or 1.12.0-beta01, the background color of some components is wrong, when I use system colors, while is correct if I force a color.
Some screenshots what happens after update. System color is blue.

<img src="https://i.ibb.co/SrgqMDH/after1.png" width="10%" height="10%" /><img src="https://i.ibb.co/7QJQsCZ/after2.png" width="10%" height="10%" />

As workaround I set `android:background="?android:colorBackground"` to some components in layout, but I understand which a wrong way to solve my issue.

**Expected behavior:** 
Here before update
<img src="https://i.ibb.co/Bt446Hv/before1.png" width="10%" height="10%" /><img src="https://i.ibb.co/KVvqX5s/before2.png" width="10%" height="10%" />

**Source code:** No changes to code

**Android API version:** 34 tested also 33 same result

**Material Library version:** 1.11.0

**Device:** AVD Android 14

**Comment by hunterstich** [comment]
Hi @mywalkb. Thanks for filing an issue.

For some reason I'm unable to see the images you've uploaded. Do you mind re-attaching the screenshots of the issue?

**Comment by mywalkb** [comment]
Hi @hunterstich, thank you for your fast reply and sorry for my bad images and slow fix.
I uploaded to external host, because the images have just become so private that not even I can see them anymore, while I was preparing the issue something else happened to me but I thought it was my fault and how I had pasted the link, but no, it seems they are only valid in session.
However I saw that github has uploaded them to its servers.
When in doubt, also post direct links, to avoid them getting lost again

After update to 1.11.0
https://i.ibb.co/SrgqMDH/after1.png
https://i.ibb.co/7QJQsCZ/after2.png

Before update to 1.11.0 with version 1.10.0
https://i.ibb.co/Bt446Hv/before1.png
https://i.ibb.co/KVvqX5s/before2.png

**Comment by diegobarle-dev** [comment]
The issue also happening with `MaterialDatePicker.Builder.datePicker()` but I'm unable to fix it with styles.
![Screenshot 2024-04-03 at 10 16 48](https://github.com/material-components/material-components-android/assets/59647093/05eb637b-b6c0-4742-a91b-74703413cf5c)

Adding the following partially fixes the problem but there are still gaps
```
    <style name="ThemeOverlay.App.MaterialCalendar" parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar">
        <item name="materialCalendarHeaderSelection">@style/HeaderSelection1</item>
    </style>
    <style name="HeaderSelection1" parent="Widget.MaterialComponents.MaterialCalendar.HeaderSelection">
        <item name="android:background">@color/error_red</item>
    </style>
```

```
    val datePicker = MaterialDatePicker.Builder.datePicker()
            .setTitleText(R.string.date_picker_select_date)
            .setSelection(dateValidator.initialDate)
            .setCalendarConstraints(constraintsBuilder.build())
            .setTheme(R.style.ThemeOverlay_App_MaterialCalendar)
            .build()
```
![Screenshot 2024-04-03 at 10 25 33](https://github.com/material-components/material-components-android/assets/59647093/912b4b2f-0679-453a-98d2-68a52d357df2)

**Comment by mywalkb** [comment]
I'm glad to know I'm not the only one with the issue.
I hope @hunterstich can give us a suggestion.

**Comment by diegobarle-dev** [comment]
Update: After analysing my codebase I realised that some of the styles defined in my project were somehow overriding the ones defined by the material library (still not sure how that was possible if they were not being referenced upon build). After getting rid of the styles defined in my project the MaterialDatePicker UI seems to be displaying correctly on com.google.android.material:material:1.11.0

**Comment by hunterstich** [comment]
@mywalkb do you have dynamic colors enabled? Do you mind attaching a sample that reproduces the issue?

**Comment by mywalkb** [comment]
@hunterstich yes I have dynamic colors enabled. 
I don't have an example to reproduces the issue, but it's an opensource project mywalkb/LSPosed_mod.
Is not only an app, but a more complex project.
The source of app is here mywalkb/LSPosed_mod/tree/main/app/src/main.
In [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/8499373090/artifacts/1372827424) action zip you can find manager.apk which has the issue with version 1.11.0, while in [this](https://github.com/mywalkb/LSPosed_mod/actions/runs/8504881132/artifacts/1373770841) action zip you can find manage.apk which has no issue with version 1.10.0, because I choose to revert the update.

**Comment by hunterstich** [comment]
@mywalkb Are the two different screenshots running on a device with different wallpapers?

**Comment by mywalkb** [comment]
@hunterstich no, is the same AVD without changes. I installed, run, screenshot, no changes.

**Comment by paulfthomas** [comment]
@pekingme any idea regarding this?

**Comment by pekingme** [comment]
@mywalkb Thanks for reporting. Please prepare a simple sample can reproduce the issue. 

I have taken a look at your project. The `AppTheme.Light` inherits from `Theme.Material3.DynamicColors.Light.Rikka`. This is not a default Material3 theme. Are you using another lib wrapping Material? It's impossible to identify the issues with external complexities. Can you try to depend on Material directly and use a default Material theme as parent? 

I'll mark this closed. We'll take another look with a repro sample.
