### ISSUE TITLE
[TextInputLayout] Application crashes when using TextInputLayout with TextInputEditText in some devices.

### ISSUE THREAD

**Issue by dquand91** [material-components/material-components-android#4141]
**Description:** When using TextInputLayout with TextInputEditText, it leads to a crash in some devices.
We are receiving a lot of crashing report from Google Console for using the TextInputLayout with TextInputEditText in some devices. But I can not reproduce the issue in my environment. The log from google console like following:

```
Exception android.view.InflateException: Binary XML file line #301 in layout/fragment_conversation: Binary XML file line #301 in layout/fragment_conversation: Error inflating class com.google.android.material.textfield.TextInputLayout
Caused by: android.view.InflateException: Binary XML file line #301 in layout/fragment_conversation: Error inflating class com.google.android.material.textfield.TextInputLayout
Caused by: java.lang.reflect.InvocationTargetException

Caused by android.view.InflateException: Binary XML file line #29 in layout/design_text_input_end_icon: Binary XML file line #29 in layout/design_text_input_end_icon: Error inflating class com.google.android.material.internal.CheckableImageButton
Caused by: android.view.InflateException: Binary XML file line #29 in layout/design_text_input_end_icon: Error inflating class com.google.android.material.internal.CheckableImageButton
Caused by: java.lang.reflect.InvocationTargetException

Caused by java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f040001 a=-1}, theme={InheritanceMap=[id=0x7f1201f1 style/ThemeOverlay.Design.TextInputEditText], Themes=[style/ThemeOverlay.Design.TextInputEditText, forced, style/AppTheme, forced, style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
  at android.content.res.TypedArray.getDrawableForDensity (TypedArray.java:1007)
```

- My application style is inherited from MaterialComponents
`<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge">`

**Expected behavior:** Do not crash

**Source code:** 
- XML file:
```
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:animateLayoutChanges="true"
    android:background="@color/white"
    android:fitsSystemWindows="true"
>
<com.google.android.material.textfield.TextInputLayout
        android:id="@+id/tilMessageInput"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginHorizontal="16dp"
        android:layout_marginBottom="12dp"
        app:boxBackgroundMode="filled"
        app:boxStrokeWidth="0dp"
        app:boxStrokeWidthFocused="0dp"
        app:errorTextColor="@color/white"
        app:hintEnabled="false"
        app:layout_constraintBottom_toBottomOf="parent">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/etMessageInput"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/white"
            android:ems="10"
            android:hint="Please input something."
            android:inputType="textCapSentences|textMultiLine"
            android:maxHeight="120dp"
            android:maxLength="1000"
            android:minHeight="52dp" />
    </com.google.android.material.textfield.TextInputLayout>
</androidx.constraintlayout.widget.ConstraintLayout>
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:**
- Android 8.0 (API 26)
- Android 8.1 (API 27)
- Android 9 (API 28)
- Android 10 (API 29)
- Android 11 (API 30)
- Android 12 (API 31)
- Android 13 (API 33)
- Android 14 (API 34)

**Material Library version:**
- com.google.android.material:material: **1.11.0**
- 
**Device:** 
- Samsung S20
- Samsung S21
- Samsung S22
- Samsung S22 Plus
- Samsung S22 Ultra
- Samsung S23
- Samsung S23 Plus
- Samsung S23 Ultra
- TECNO SPARK 10 Pro
- Google panther (Pixel 7)
- Infinix Hot 30i

**Comment by paulfthomas** [comment]
@dsn5ft any idea regarding this issue?

**Comment by dsn5ft** [comment]
It's possible this is due to a recent issue where Play Store installations were incomplete, related to apk splits.

If so it shouldn't be happening on devices with the latest version of Play Services.

**Comment by dquand91** [comment]
> It's possible this is due to a recent issue where Play Store installations were incomplete, related to apk splits.
> 
> If so it shouldn't be happening on devices with the latest version of Play Services.

Thanks for your reply @dsn5ft .
Could you share to me more information about the issue "where Play Store installations were incomplete, related to apk splits"?

**Comment by dsn5ft** [comment]
Hmm I can't really find a good link about the problem, but this one seems related:

https://stackoverflow.com/questions/76903497/cannot-find-resource-in-split-apks-of-android-app-bundle

**Comment by dquand91** [comment]
Thanks @dsn5ft ,
I think we need to request the user to check their Play Services and update to the latest version if need.
Besides that, do you have any work around for this issue?

**Comment by dsn5ft** [comment]
Yes I believe updating Play Services to the latest version and reinstalling the app would fix the issue.
