### ISSUE TITLE
[AppBar] AppBar in activity is hiding text on Android 15 (Beta 1)

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#4148]
**Description:** In my app, I'm using an `AboutActivity.class` to shown an "About"-dialog. I'm calling this activity in MainActivity.java. The layout is defined in `about_activity.xml`. Edge-to-edge is already enabled in my app.

1. If I compile the code with SDK 34, the dialog looks as follows, i.e. the text in the `MaterialTextView` is correctly aligned and the `StatusBar` dynamically gets it's color:
<img width="540" alt="android_14" src="https://github.com/material-components/material-components-android/assets/7906165/2f5005fc-81a0-47a9-8bdc-c4ebaeac5e01">

2. If I compile the code with SDK 35 "VanillaIceCream" (Beta 1), the dialog looks as follows, i.e. the text in `MaterialTextView` is partially hidden by the `ActionBar`. Furthermore, the `StatusBar` color is not dynamic anymore as `setStatusBarColor` is deprecated and has no effect on Android 15.
<img width="540" alt="android_15" src="https://github.com/material-components/material-components-android/assets/7906165/02369140-7243-4bb1-ad91-5b78f04261d5">

Questions:
- I know that I'm using `paddingTop="15dp"`, a hardcoded value, but that was never an issue since SDK 16. Is there any chance in M3 to make the distance between `StatusBar` or `ActionBar` dynamic to always get the correct distance?
- Is there an M3 alternative to make the `StatusBar` color dynamic again on Android 15?

**Expected behavior:**  Text in `MaterialTextView` is not partially hidden by the `ActionBar` and `StatusBar` color is still dynamic. 

**Source code:** Here are the relevant code snippets...

**MainActivity.java**
```
Intent aboutIntent = new Intent(this, AboutActivity.class);
startActivity(aboutIntent);
```

**about_activity.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:layoutDirection="locale"
    android:textDirection="locale">

    <androidx.constraintlayout.widget.ConstraintLayout
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        tools:context=".AboutActivity">

        <com.google.android.material.textview.MaterialTextView
            android:id="@+id/aboutTxt"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentStart="true"
            android:layout_alignParentLeft="true"
            android:paddingStart="20dp"
            android:paddingLeft="20dp"
            android:paddingTop="15dp"
            android:paddingEnd="20dp"
            android:paddingRight="20dp"
            android:textSize="17sp"
            app:layout_constraintTop_toTopOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>

</ScrollView>
```

**AboutActivity.java**
```
    private void setupStatusBar() {
        // Set dynamic status bar to action bar color in Material M3 design
        if (android.os.Build.VERSION.SDK_INT >= 29) {
            Window window = getWindow();
            View view = window.findViewById(androidx.appcompat.R.id.action_bar);
            window.setStatusBarColor(MaterialColors.getColor(view, com.google.android.material.R.attr.colorSurfaceContainer));
        }
    }
```

**Android API version:** Android 34 and 35 "VanillaIceCream" (Beta 1)

**Material Library version:** 1.13.0-alpha01

**Device:** Google Pixel 7a Emulator on Android Studio Jellyfish

**Comment by imhappi** [comment]
Hi @patrickfrei !

From the changes listed [here](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge_enforcement) it looks like what's happening is that the status bar space is now being included as a part of layout space and that bumped your layout up by the height of the status bar

As per the [developer docs](https://developer.android.com/reference/android/view/Window#setStatusBarColor(int)), the status bar is always transparent and now needs the background to be drawn behind it: "Draw proper background behind [WindowInsets.Type#statusBars()](https://developer.android.com/reference/android/view/WindowInsets.Type#statusBars())} instead."

It looks like you're using the action bar that comes with one of the default action bar themes. I'm not sure why the default action bar is respecting the status bar inset with the edge to edge enforcement, maybe that is a change that's yet to be made or was a conscious decision in order. In any case, it looks like the recommendation for adding an app bar is to add a toolbar to the layout with a theme without an action bar, which I believe may solve both your issues (but will move the toolbar up): https://developer.android.com/develop/ui/views/components/appbar/setting-up#add-toolbar

If you're using Material, you can replace it with a toolbar inside an AppBarLayout, which will take care of the insets for you: https://github.com/material-components/material-components-android/blob/master/docs/components/TopAppBar.md
