### ISSUE TITLE
[Chip] Although icon sizes are the same but icon sizes is changing

### ISSUE THREAD

**Issue by Narinc** [material-components/material-components-android#417]
I'm adding icons as same size. They are 64x64. But they are appearing different sizes.

**Comment by Narinc** [comment]
![WhatsApp Image 2019-07-06 at 18 56 20](https://user-images.githubusercontent.com/9096116/60758578-43995d00-a021-11e9-8359-354cc3334599.jpeg)

**Comment by wcshi** [comment]
@Narinc could you please share a sample app with the icon you used to reproduce this behavior?

**Comment by Narinc** [comment]
I shared sample code as gist. i hope it will be enough. 
I commented the icons. You can download it.

https://gist.github.com/Narinc/986969972a1cc117f23d1fc87151d306

**Comment by wcshi** [comment]
Thank you for the sample, apologies for the late response, we'll investigate soon.

**Comment by wcshi** [comment]
Could you please provide a complete sample app? The example code is not enough. Also, the spec expects that the chips have text, and it looks like you are trying to create icon only chips?

**Comment by Narinc** [comment]
Hi, I'm sorry for the late reply. I reviewed the icons, again. Problem in icon content. So Chip works fine. 

And yes, I am trying to create icon only chips. But you're saying that chip can't just be an icon. It would be very helpful for me if you support it :(
