### ISSUE TITLE
MaterialCardView and ImageView when animating

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [material-components/material-components-android#418]
The parent of my MaterialCardView has a circle reveal animation. When it is animating (showing or hiding the parent), the MaterialCardView is a circle, but its content (an ImageView) is a square. When the animation ends the ImageView becomes a circle.

Is there any way to solve this bug so the MaterialCardView child has the same radius as the card?

**Comment by JavierSegoviaCordoba** [comment]
Can someone give me feedback about this? Any way to avoid this problem?

**Comment by cketcham** [comment]
Sorry for the delay. It's a little hard to understand the problem you are having. Could you provide a code sample?

**Comment by JavierSegoviaCordoba** [comment]
Public no, but it is simple to replicate.

Imagine you have a view which has inside a circular avatar (64 dp). You can use a MaterialCardView with a border radius of 32 dp to wrap the ImageView so you can get the circle avatar.

Now this avatar (Card with a ImageView) is inside of another view which is hidden. So to show it you use a circle reveal animation (in my case I am using Circle reveal card as parent of my avatar)

When it is animated, the avatar shape is a square, when the animation ends, it becomes a circle. It should be always a circle.

**Comment by JavierSegoviaCordoba** [comment]
Any update about this?

**Comment by kovac777** [comment]
Same issue with reveal animation MaterialCardView

**Comment by cketcham** [comment]
@ymarian Do you think this is related to having an extra FrameLayout, or something else?

**Comment by ymarian** [comment]
Got it seems to be because clipToOutline does not work mid animation. Luckily we have a new ShapeableImageView that handles this! 
in layout.xml 

```xml
<com.google.android.material.imageview.ShapeableImageView
       android:layout_width="match_parent"
       android:layout_height="match_parent"
       app:shapeAppearance="@style/ShapeCircle"
       app:srcCompat="@drawable/boarder"
       android:scaleType="centerCrop" />
```

in styles.xml
```xml
  <style name="ShapeCircle">
    <item name="cornerFamily">rounded</item>
    <item name="cornerSize">50%</item>
  </style>
```
