### ISSUE TITLE
[Motion] Activity to Fragment Transition

### ISSUE THREAD

**Issue by Matthaeus07** [material-components/material-components-android#4182]
**Description:**
There is no documentation about how to create a transition from an Activity to a Fragment.

I specificly tried to create a MaterialSharedAxis transition from an Activity to a Fragment which did not work for me.

**Sample Code:**
```kt
// Activity A

val fragment = Fragment()
fragment.enterTransition = MaterialSharedAxis(MaterialSharedAxis.X, true)
fragment.exitTransition = MaterialSharedAxis(MaterialSharedAxis.X, false)

val fragmentManager = supportFragmentManager
    .beginTransaction()
    .add(R.id.fragment_container_view, Fragment())
    .addToBackStack( "fragment")
    .commit()
```

```kt
// Fragment B

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    enterTransition = MaterialSharedAxis(MaterialSharedAxis.X, true)
    returnTransition = MaterialSharedAxis(MaterialSharedAxis.X, false)
}
```

**Comment by dsn5ft** [comment]
There isn't really such a thing as a transition from an Activity to a Fragment, since Fragment is not a standalone concept and must always be embedded in an Activity. Transitions only work in the following cases:

1. Activity A -> Activity B
2. Fragment A -> Fragment B
3. View A -> View B
