### ISSUE TITLE
Cannot compile aar with new version from com.google.android.material:material: Android resources missing

### ISSUE THREAD

**Issue by theyoz** [material-components/material-components-android#4183]
**Description:** Full description of issue here

Seems that some resources are missing passed com.google.android.material:material:1.10.0

`* What went wrong:
Execution failed for task ':app:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:3: AAPT: error: resource android:color/system_background_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:4: AAPT: error: resource android:color/system_error_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:5: AAPT: error: resource android:color/system_error_container_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:6: AAPT: error: resource android:color/system_on_surface_light not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:7: AAPT: error: resource android:color/system_primary_light not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:8: AAPT: error: resource android:color/system_surface_light not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:9: AAPT: error: resource android:color/system_on_background_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:10: AAPT: error: resource android:color/system_on_error_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:11: AAPT: error: resource android:color/system_on_error_container_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:12: AAPT: error: resource android:color/system_on_primary_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:13: AAPT: error: resource android:color/system_on_primary_container_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:14: AAPT: error: resource android:color/system_on_secondary_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:15: AAPT: error: resource android:color/system_on_secondary_container_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:16: AAPT: error: resource android:color/system_on_surface_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:17: AAPT: error: resource android:color/system_on_surface_variant_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:18: AAPT: error: resource android:color/system_on_tertiary_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:19: AAPT: error: resource android:color/system_on_tertiary_container_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:20: AAPT: error: resource android:color/system_outline_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:21: AAPT: error: resource android:color/system_outline_variant_dark not found.
         
     ERROR: /home/yoram/dev/git/risco/android/handyapp/cs_ui_kit/cs_ui_kit/app/build/intermediates/merged_res/release/mergeReleaseResources/values-v34/values-v34.xml:22: AAPT: error: resource android:color/system_primary_dark not found.
`

**Expected behavior:** Screenshots and/or description of expected behavior

Mssing android colors to be brought back so we can compile

**Source code:** The code snippet which is causing this issue

` implementation 'com.google.android.material:material:1.12.0'`

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.11.0 and 1.12.0

**Device:** Device on which the bug was encountered here

gradlew 

Other: If you stay with v1.10.0 then you can compile

**Comment by dsn5ft** [comment]
Those system color resources are from Android U / API Level 34, so I'm guessing you need to update your `compileSdkVersion` to `34`.

https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#3-android-sdk-compilation

If that's not the case feel free to reopen and provide more info.

**Comment by theyoz** [comment]
thanks it is working!
