### ISSUE TITLE
Navigation Rail like a NavigationView with Jetpack Navigation

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#4188]
**Is your feature request related to a problem? Please describe.**
Is there any plan to support Navigation Rail with behavior like NavigationView with `setupWithNavController`? As of now it seems that handling states and backstack needs to be manual.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dsn5ft** [comment]
@ianhanniballake do you have any thoughts here on what is currently supported and what might be planned for Navigation Rail + Jetpack Navigation?

**Comment by ianhanniballake** [comment]
As per the [Navigation 2.4.0 release notes](https://developer.android.com/jetpack/androidx/releases/navigation#2.4.0) back in January 2022:

> `NavigationUI` methods that took a `BottomNavigationView` have been updated to instead take its superclass introduced in Material 1.4.0, `NavigationBarView`. This allows these methods to be used with the `NavigationRailView`.

**Comment by dsn5ft** [comment]
Thanks Ian!
