### ISSUE TITLE
[SearchView] Undocumented how to actually use it

### ISSUE THREAD

**Issue by rafrafek** [material-components/material-components-android#4189]
There is no documentation on how to use com.google.android.material.search.SearchView.

There is no setOnQueryTextListener, but all tutorials on the internet say it should be there.

There is no information on how to listen to the search input text changes. It's the most basic thing and without it the component is useless.

Google Gemini does not know the answer. ChatGPT4 does not know the answer.

I had to search the entire internet to find the answer:
https://stackoverflow.com/a/78060915/9737275

The answer is that searchView has a secret child editText that you can add a text change listener to. Please mention it in the documentation.

```kotlin
searchView.editText.addTextChangedListener
```

There is also no documentation on how to actually use it, e. g. with RecyclerView. It would be great to have it.

Thank you.

**Comment by dsn5ft** [comment]
This section of the documentation shows an example of how you can do `searchView.getEditText().setOnEditorActionListener(...)`:

https://github.com/material-components/material-components-android/blob/master/docs/components/Search.md#search-view

Since `SearchView` simply exposes the `EditText`, we are not going to repeat all of the EditText APIs in our documentation, but we can make it a little more clear in that section.

And this section of the documentation shows how you can next a `ScrollView`, `RecyclerView`, etc. within a `SearchView` to show search suggestions / history:

https://github.com/material-components/material-components-android/blob/master/docs/components/Search.md#putting-it-all-together

We can make that a little more clear as well.

**Comment by dsn5ft** [comment]
The Material SearchView doesn't have setIconified / setOnQueryTextListener methods.

**Comment by dsn5ft** [comment]
The `app:layout_behavior="@string/searchbar_scrolling_view_behavior"` scroll away mode will make the SearchBar float on top of the scrolling content:

https://github.com/material-components/material-components-android/blob/master/docs/components/Search.md#scroll-away-mode

Try using `app:layout_behavior="@string/appbar_scrolling_view_behavior"` instead if you want the scrolling content to not overlap the SearchBar.

**Comment by rafrafek** [comment]
Thanks!

**Comment by patrickfrei** [comment]
I'm using a `ViewPager2` with fragments. Additionally, a `TabLayout`, whereas I've a fragment for each tab. Each fragment includes a `RecyclerView` list. Basically, the GUI looks like the M3 Catalog app `RecyclerView` Demo.

Looking at the M3 Catalog app and the documentation, I really don't understand how to apply the search string to the `RecyclerView` list of the currently selected tab and transfer the filtered list with the search results back to the `RecyclerView` defined within `SearchView`.

Does someone of you eventually have some sample code that shows the logic?

**Comment by michael-winkler** [comment]
You should ask chat gpt.

You can add a new adapter to the recyclerview with the filtered list.

**Comment by patrickfrei** [comment]
@michael-winkler , thank you, I'll do so. But the problem in my use case is that SearchBar / SearchView are in MainActivity.java, but the RecyclerView lists are fragment-specific. So, I don't know how to access the currently selected adapter out of MainActivity.

**Comment by michael-winkler** [comment]
class MainActivity : AppCompatActivity() {

    private lateinit var viewPager: ViewPager2
    private lateinit var tabLayout: TabLayout
    private lateinit var adapter: ViewPagerAdapter

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        viewPager = findViewById(R.id.viewPager)
        tabLayout = findViewById(R.id.tabLayout)

        // Setup ViewPagerAdapter
        adapter = ViewPagerAdapter(this)
        viewPager.adapter = adapter

        // Connect TabLayout with ViewPager
        TabLayoutMediator(tabLayout, viewPager) { tab, position ->
            tab.text = "Tab $position"
        }.attach()

        // Setup SearchView
        val searchView = findViewById<SearchView>(R.id.searchView)
        searchView.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
            override fun onQueryTextSubmit(query: String?): Boolean {
                return false
            }

            override fun onQueryTextChange(newText: String?): Boolean {
                newText?.let {
                    val fragment = adapter.getFragmentAt(viewPager.currentItem)
                    fragment?.filterList(it)
                }
                return true
            }
        })
    }
}

class ViewPagerAdapter(activity: AppCompatActivity) : FragmentStateAdapter(activity) {

    private val fragments = listOf(
        ListFragment(),
        ListFragment(),
        ListFragment()
    )

    override fun getItemCount(): Int = fragments.size

    override fun createFragment(position: Int): Fragment {
        return fragments[position]
    }

    fun getFragmentAt(position: Int): ListFragment? {
        return fragments[position] as? ListFragment
    }
}

class ListFragment : Fragment() {

    private lateinit var recyclerView: RecyclerView
    private lateinit var adapter: ListAdapter
    private var fullList = listOf("Item 1", "Item 2", "Item 3", "Item 4")
    private var filteredList = fullList

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val view = inflater.inflate(R.layout.fragment_list, container, false)
        recyclerView = view.findViewById(R.id.recyclerView)
        adapter = ListAdapter(filteredList)
        recyclerView.adapter = adapter
        return view
    }

    fun filterList(query: String) {
        filteredList = if (query.isEmpty()) {
            fullList
        } else {
            fullList.filter { it.contains(query, ignoreCase = true) }
        }
        adapter.updateList(filteredList)
    }
}

class ListAdapter(private var items: List<String>) : RecyclerView.Adapter<ListAdapter.ViewHolder>() {

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        val view = LayoutInflater.from(parent.context).inflate(android.R.layout.simple_list_item_1, parent, false)
        return ViewHolder(view)
    }

    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        holder.bind(items[position])
    }

    override fun getItemCount(): Int = items.size

    fun updateList(newItems: List<String>) {
        items = newItems
        notifyDataSetChanged()
    }

    class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        private val textView: TextView = itemView.findViewById(android.R.id.text1)

        fun bind(item: String) {
            textView.text = item
        }
    }
}

**Comment by michael-winkler** [comment]
![Screenshot_20241019-195829.png](https://github.com/user-attachments/assets/51536957-6737-4ecc-9c66-519146297986)

From chat gpt

**Comment by patrickfrei** [comment]
Vielen Dank. Ich schau's mir gerne an!

**Comment by patrickfrei** [comment]
I've had a look at above sample code but `searchView.setOnQueryTextListener` is not part of the M3 `SearchView`. So, I still have the problem that `SearchBar` / `SearchView` are in `MainActivity.java`, but the `RecyclerView` lists are fragment-specific. I would have to define `SearchBar` / `SearchView` in each fragment (doesn't seem to be possible), then access the search string in each fragment by using `SearchView.getText` and then populate the search string into the adapter's `getFilter` method
