### ISSUE TITLE
Crash on BottomSheetBehavior.onMeasureChild on Android (7,8 and 9)

### ISSUE THREAD

**Issue by mahmed1987** [material-components/material-components-android#4193]
We have an application on production which is connected to crashlytics. 

We have been observing quite a number of crashes in the BottomSheet for older android versions. However we are not able to reproduce this on our ends . 

I am attaching some relevant screenshots that might give you folks some hints as to what could be the potential cause of this crash

<img width="850" alt="image" src="https://github.com/material-components/material-components-android/assets/26518062/d2590185-bb37-40a4-8584-fedd1c52b616">

<img width="1226" alt="image" src="https://github.com/material-components/material-components-android/assets/26518062/ffd2d885-9b24-402a-8c35-ddaba4f123c5">

Our compile SDK and targetSDK is 34
minSDK is 23

**Comment by dsn5ft** [comment]
Hi, it looks like this is not really a crash in Bottom Sheet itself, but rather in a child view of the Bottom Sheet.

Can you share what content you have inside the Bottom Sheet. It looks like something related to ConstraintLayout / BoringLayout?

**Comment by mahmed1987** [comment]
Hello @dsn5ft 

yeah the Content of the bottomsheet is indeed a very regular  ConstraintLayout. It has the following structure


```
<androidx.constraintlayout.widget.ConstraintLayout>

    <include
        android:id="@+id/header"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvBankNameLabel"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvBankNameValue"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvBeneficiaryNameLabel"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvBeneficiaryNameValue"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvCountryLabel"/>

    <LinearLayout
        android:id="@+id/llCountry">
      <androidx.appcompat.widget.AppCompatImageView
          android:id="@+id/ivCountry"/>
      <androidx.appcompat.widget.AppCompatTextView
          android:id="@+id/tvCountryValue"/>
    </LinearLayout>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvBankAddressLabel"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvBankAddressValue"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvSwiftCodeLabel"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvSwiftCodeValue"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvAccountNumberLabel"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvAccountNumberValue"/>

    <androidx.appcompat.widget.AppCompatTextView
        android:id="@+id/tvAccountCurrencyLabel"/>

    <LinearLayout
        android:id="@+id/llCurrency">
      <androidx.appcompat.widget.AppCompatImageView
          android:id="@+id/ivCurrency"/>
      <androidx.appcompat.widget.AppCompatTextView
          android:id="@+id/tvCurrencyValue"/>
    </LinearLayout>

    <com.google.android.material.button.MaterialButton
        android:id="@+id/btnDelete"/>
</androidx.constraintlayout.widget.ConstraintLayout>
`

**Comment by mahmed1987** [comment]
Was an issue with the transformationMethod that we were using in one of the views.  Fixed it . Thanks for the hints

**Comment by dsn5ft** [comment]
Ah ok! Thanks for following up.
