### ISSUE TITLE
[TextInputLayout] Problem with TextInputLayout counter displaying number 0123456789 in Arabic language

### ISSUE THREAD

**Issue by magic0908** [material-components/material-components-android#4214]
**Description:** TextInputLayout counter does not display the number 0123456789 in Arabic language. How to display it correctly？

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** in xml resources R.string.character_counter_pattern

**Android API version:** Android API version 13

**Material Library version:** Material Android Library version 1.9.0

**Device:** Samsung A51

picture1：in English language
![shot_20240701172248](https://github.com/material-components/material-components-android/assets/23170601/0f275c50-264f-4831-8a0b-9a96d30fcc70)

picture2：in Arabic language
![shot_20240701172327](https://github.com/material-components/material-components-android/assets/23170601/6b8e1fb3-2f21-47b2-af00-e2bf2eade042)

last：I want to keep the numbers "0123456789" in any language, including English and Arabic. like picture1. What should I do？thanks！

**Comment by kendrickumstattd** [comment]
Hey there! I took a look at our components catalog, and although we're adding translatable="false" to the character_counter_pattern string [[link](https://github.com/material-components/material-components-android/blob/20f92dfb513916d0df6c38bfd630dfc41aff484e/lib/java/com/google/android/material/textfield/res/values/strings.xml#L19)] , the translation will still happen in Android API Version 13 but not Android API Version 15 and on.

Could you provide a pointer to where your repository is?

**Comment by Huangweijia100** [comment]
The main problem is that %d will use localized numbers for display, which has nothing to do with “translatable="false"”.

**Comment by magic0908** [comment]
@kendrickumstattd I find the solution. The material components character_counter_pattern resource is Int [[link](https://github.com/material-components/material-components-android/blob/20f92dfb513916d0df6c38bfd630dfc41aff484e/lib/java/com/google/android/material/textfield/res/values/strings.xml#L19)], I changed it to String.

Under the main app module：app/string.xml
![shot_20240702104325](https://github.com/material-components/material-components-android/assets/23170601/dd44ddd9-ebab-42c4-90d1-99db40f63a3f)

The result (in Arabic language)：
![shot_20240702104607](https://github.com/material-components/material-components-android/assets/23170601/77d5ca40-55d0-46bc-9261-bb55ab42cf86)

But I don't know if this writing is correct.
Can the material component library be opened in the later stage for users to customize display?

**Comment by kendrickumstattd** [comment]
Sounds good -- if there is a space somewhere in the text field where "night" is written, that looks good to me.

What type of display customizations would you be requesting?

**Comment by magic0908** [comment]
@kendrickumstattd 
For TextInputLayout counterView, I would like the counterView to be able to set the margin or padding, and of course, I can also freely setText.
For now, there are only these.
Thanks!

**Comment by kendrickumstattd** [comment]
Thanks, @magic0908, I'll make note of that in an internal feature request for our team to keep in mind! Going to mark this as "closed" but please reopen if any other issues arise. Cheers!
