### ISSUE TITLE
[TabLayout] Design Preview Will Not Load

### ISSUE THREAD

**Issue by askkerr** [material-components/material-components-android#4216]
**Description:** This seems to be related to previous issues where design preview was breaking for older versions of Android studio after upgrading from Material 1.7 to 1.8, however the parameters for this issue are different.

**Expected behavior:** Design preview should load while having a TabLayout in the XML.

**Android API version:** Android API 34

**Material Library version:** Material Android Library version 1.12.0

**Other Settings Used**
Android Studio Koala 2024.1.1
BuildToolsVersion 30.0.3
androidx.constraintlayout:constraintlayout:2.1.4

***Note: This occurs regardless if the TabLayout is in a ConstraintLayout or any other parent layout ***

**Comment by kendrickumstattd** [comment]
Hey hey @askkerr -- do you have additional details about the notice/error that you're getting?

**Comment by askkerr** [comment]
@kendrickumstattd looking more into it, it may be a conflict with some of my styles. I'm about 90% sure that is what is occurring. Given that, if you would like to close the issue, I think it should be fine to do so. If the issue persists, I will let you know.

**Comment by kendrickumstattd** [comment]
Sounds good, @askkerr. I'll close this issue, but please don't hesitate to reach back out if the issue persists or a new one arises.
