### ISSUE TITLE
Menu item shows as disabled even though it is enabled...

### ISSUE THREAD

**Issue by davidlehrian** [material-components/material-components-android#4220]
Recently updated from material 1.11.0 to 1.12.0 and I noticed my menu items were not being enabled. I downgraded to 1.11.0 and they worked as expected. 

To recreate this issue I created a new project using the "Navigation Drawer Views Activity". Then I did the following modifications:

In MainActivity.kt add the following line as the last line of onCreate
` 
     navView.menu.findItem(R.id.nav_gallery).setEnabled(false)
`

Then add the fun to MainActivity.kt
`
     fun enableGallery(){
        navView.menu.findItem(R.id.nav_gallery).setEnabled(true)
    }
`
Then add the following as the last line of fun onCreateView in SlideshowFragment.kt
`
     (activity as MainActivity?)!!.enableGallery()
`

To save you the above steps I have attached a project that recreates this issue. 

When you run the app and open the menu the  "Gallery" menu item will be disabled as it is disabled in the onCreate fun. It appears as grayed out and you can't click on it.

Then select "Slideshow" which, as the last thing in its "onCreateView" fun will enable the "Gallery" menu item. Now look at the menu. "Gallery" will still be grayed out BUT you can click on it and it will take you to the "Gallery". Also, once you click on it it will no longer be grayed out. 

I would expect the menu item to not be grayed out once it has been enabled (as soon as the menu is displayed) since it otherwise gives the appearance that it is disabled. 

Android API version 34

Material Android Library version 1.12.0

Device Google Pixel 4
[MyApplication2.zip](https://github.com/user-attachments/files/16154477/MyApplication2.zip)

**Comment by imhappi** [comment]
Hello, this should be fixed by https://github.com/material-components/material-components-android/commit/20f92dfb513916d0df6c38bfd630dfc41aff484e
