### ISSUE TITLE
Multiple language didn't work with dark mode in 1.1.0-alpha07

### ISSUE THREAD

**Issue by bkhezry** [material-components/material-components-android#423]
**Description:** Multiple language App work fine. After adding the dark mode option to it and use 
```
getDelegate().setLocalNightMode(
                        AppCompatDelegate.MODE_NIGHT_YES);
```
to change the theme to dark, `strings.xml` didn't load from `values-uk` folder and load from `values` folder.

**Expected behavior:**
In the dark mode, `strings.xml` should be load from the selected language.

<p float="left">
  <img src="https://user-images.githubusercontent.com/91809/60970773-ead70680-a337-11e9-8bed-cc997f7c5b47.png" width="300" />
  <img src="https://user-images.githubusercontent.com/91809/60970778-edd1f700-a337-11e9-8d7d-673777add855.png" width="310" />
</p>

**Source code:** https://github.com/bkhezry/LanguageTest 

**Android API version:** 28

**Material Library version:**  1.1.0-alpha07

**Appcompat version:**  1.1.0-rc01

**Device:** Xiaomi Redmi Note 7

**Comment by dsn5ft** [comment]
Hello! The setLocalNightMode() functionality is part of AppCompat as opposed to the Material library. You can file a bug here instead : http://issuetracker.google.com/issues/new?component=460343

Also, you might want to try using `AppCompatDelegate#setDefaultNightMode` instead, which will recreate the Activity for you.

**Comment by chhota89** [comment]
@bkhezry  did you find any solution. I am also facing the same issue

**Comment by bkhezry** [comment]
@chhota89 The solution will be release in `appcompat 1.2.0-alpha01` soon

**Comment by chhota89** [comment]
After long waiting appcompat 1.2.0-alpha01 is released but  after setting
```
getDelegate().setLocalNightMode(
                        AppCompatDelegate.MODE_NIGHT_YES);
```

multi-language translation still not working. I have checked the release notes but I didn't found what exact change I have to do to make it work.

**Comment by bkhezry** [comment]
@chhota89 `appcompat 1.2.0-alpha01` did NOT release yet.

**Comment by Ireristible** [comment]
@bkhezry Is there a SNAPSHOT version that we can try in the meantime? Do you know where I could find it if it exists? I've been checking here for the past few weeks https://mvnrepository.com/artifact/androidx.appcompat/appcompat

**Comment by bkhezry** [comment]
@Ireristible unfortunately no. We are waiting too for this release.

**Comment by Ireristible** [comment]
@bkhezry appCompat 1.2.0-SNAPSHOT exists! I found it here. https://ci.android.com/builds/submitted/5920449/androidx_snapshot/latest/repository/

**Comment by bkhezry** [comment]
@Ireristible did you try to add it to Gradle?

**Comment by Ireristible** [comment]
@bkhezry Yes and it seems to work! 😲Try it for yourself.

**Comment by bkhezry** [comment]
@Ireristible No. it NOT works.

**Comment by Ireristible** [comment]
@bkhezry Oh that's a shame it didn't work for you. If it helps, `targetSdkVersion = 29` in the app I tested this on.

**Comment by raghavsatyadev** [comment]
This is still a problem on 1.2.0-alpha02 release

**Comment by UdiOshi85** [comment]
Don't know why someone closed this but this is still happening. any updates ?

**Comment by ikim24** [comment]
Please see the comment from when this was closed:

> Hello! The setLocalNightMode() functionality is part of AppCompat as opposed to the Material library. You can file a bug here instead : http://issuetracker.google.com/issues/new?component=460343
> 
> Also, you might want to try using AppCompatDelegate#setDefaultNightMode instead, which will recreate the Activity for you.

**Comment by hamidAslami** [comment]
Hello for fix this error you must use this code :
`                delegate.localNightMode = AppCompatDelegate.MODE_NIGHT_YES;
`
