### ISSUE TITLE
[Chip Group] Doesn't support rtl direction 

### ISSUE THREAD

**Issue by sepehr-alipour** [material-components/material-components-android#425]
How we can fill chipgroup from right

![image](https://user-images.githubusercontent.com/6023851/61050984-7797c800-a3fd-11e9-9429-f2f6a234a76c.png)

**Comment by wcshi** [comment]
ChipGroup starts align its children, so when the layout direction is RTL, the children are right aligned. 
It sounds like you are making a feature request to expand ChipGroup to support specifying a layout direction?

**Comment by sepehr-alipour** [comment]
yes, i want to set attribute for change direction of chips to right

**Comment by brightest-dazes** [comment]
My suggestion would be to part in the middle and have run both sides

**Comment by HamidZandi** [comment]
a tricky way is set android:scaleX = "-1" for both chipgroup and chip items

**Comment by drchen** [comment]
Hi, 

ChipGroup is not officially supported in our spec but more like a convenient class we provide. 
Due to the effort/maintenance concern, we don't have a plan to prioritize the feature request in the foreseeable future.

But please feel free to make a pull request, we will be glad to review and accept it.

**Comment by MuntashirAkon** [comment]
It's not that difficult to modify ChipGroup/FlowLayout to support RTL layout. An example can be found here: https://github.com/MuntashirAkon/AppManager/blob/0c8f3724b0ddb3815d5b370f87e5fcf33cbfa160/libcore/ui/src/main/java/io/github/muntashirakon/widget/FlowLayout.java (**Bonus:** it also supports `android:gravity: center` option.)

_[Maybe one of the CLAed contributors can work on this.]_
