### ISSUE TITLE
material:1.1.0-alpha08 update request desugaring

### ISSUE THREAD

**Issue by GuanacoDevs** [material-components/material-components-android#426]
Hi

When trying to update `alpha07` to `alpha08`, the build breaks asking to enable desugaring. I  had it in place because of Twitter Kit, but that broke my app in production, had to downgrade Twitter Kit to 3.1.1.
Was planning to remove Twitter from my app, but now Material design?

I even updated my androix dependencies to alpha and beta as listed [here](https://github.com/material-components/material-components-android/blob/master/build.gradle#L27-L42) as mentioned in #405
Any workaround other than remaining in `alpha07`?

**Comment by dsn5ft** [comment]
Hi @GuanacoDevs, thanks for reporting. We will actually be reverting back to Java 7 in `1.1.0-alpha09`, likely coming within the next few weeks. For now I recommend staying with `1.1.0-alpha07` if you can't update your app to compile with Java 8 via:

```
android {
  ...
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}
```

https://developer.android.com/studio/write/java8-support
