### ISSUE TITLE
[ExtendedFloatingActionButton] width is larger than necessary for short text

### ISSUE THREAD

**Issue by josinaldobarbosa** [material-components/material-components-android#4263]
**Description:** width is larger than necessary for short text, I tried a fixed width at first and it works but after using shrink() and extend() it goes back to the default width.
![image](https://github.com/user-attachments/assets/b7bb434a-652e-47f4-98ad-3311bb2d544c)

**Expected behavior:** 
I resolved with `android:minWidth="0dp"`
![image](https://github.com/user-attachments/assets/c236ce7f-6b88-4afa-934c-a777ce2bc493)

**Source code:** 
  ```
      <com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            tools:text="1"
            android:textColor="@color/text_icons"
            app:iconTint="@color/text_icons"
            app:icon="@drawable/ic_refresh"
            app:backgroundTint="@color/colorPrimary"
            android:layout_marginEnd="@dimen/fab_margin"
            android:layout_marginBottom="26dp" />
```

**Android API version:** 34

**Material Library version:** 1.12.0 (same result on last version 1.13.0-alpha05)

**Device:** Pixel 7 pro (emulator)

**Comment by drchen** [comment]
For now just overriding the minWidth setup is the right way to fix this.

Internally we are having a discussion around making the default minWidth the same value as the height and that should solve this issue as well.

**Comment by kendrickumstattd** [comment]
This has been updated in our codebase, and the change will rollout in a later release. Thanks for bringing this concern up, marking as closed.
