### ISSUE TITLE
[MaterialDatePicker] (Compose) _Today_ is not visually disabled even if it's outside of selectable range

### ISSUE THREAD

**Issue by lwasyl** [material-components/material-components-android#4264]
**Description:** If I build a material date picker with selectable range of `today+1 day, whatever`, then _today_ day on the picker has no indication that it's not selectable. Here, Aug 19 is not selectable as per picker range, and `disabledDayContentColor` is red:
![image](https://github.com/user-attachments/assets/5b29c2df-fc2b-4461-8c28-669f88d289a5)

**Expected behavior:** Not clickable elements are visually disabled

**Source code:** 
```kotlin
    @Composable
    internal fun dayContentColor(
        isToday: Boolean,
        selected: Boolean,
        inRange: Boolean,
        enabled: Boolean
    ): State<Color> {
        val target =
            when {
                selected && enabled -> selectedDayContentColor
                selected && !enabled -> disabledSelectedDayContentColor
                inRange && enabled -> dayInSelectionRangeContentColor
                inRange && !enabled -> disabledDayContentColor
                isToday -> todayContentColor
                enabled -> dayContentColor
                else -> disabledDayContentColor
            }

        return if (inRange) {
            rememberUpdatedState(target)
        } else {
            // Animate the content color only when the day is not in a range.
            animateColorAsState(target, tween(durationMillis = MotionTokens.DurationShort2.toInt()))
        }
    }
```

In the source the first two clauses are false because today is not `selected`, following two are also false because it's not in selectable range either. But `isToday` is true so the picked color is `todayContentColor` even though the day is also not enabled.

![image](https://github.com/user-attachments/assets/871259a2-f1e7-488a-a4dc-69d606c7f09d)

![image](https://github.com/user-attachments/assets/930ef3c1-fb24-4a76-802d-b822250337b8)

![image](https://github.com/user-attachments/assets/f374ea76-8b60-47ef-81ae-eb80365c8a94)

**Minimal sample app repro:** trivially reproducible

**Android API version:** Api 34

**Material Library version:** Compose `dev.chrisbanes.compose:compose-bom:2024.08.00-alpha01`

**Device:** emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by RivanParmar** [comment]
Seems like you opened the issue in the wrong repository. This repository is for Material Components for Views and not for Compose. The Compose code is contained at [androidx](https://www.github.com/androidx/androidx). Please refer to the docs there for submitting your issue.

**Comment by dsn5ft** [comment]
Here is the link for Material Compose issues:

https://issuetracker.google.com/issues/new?component=742043&template=1346811
