### ISSUE TITLE
[LoadingIndicator] Blurry indicators

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#4265]
https://github.com/user-attachments/assets/7ce13446-bea5-4ac7-a64c-ef5ed8e8f5e0

**Material Library version:** [`544180a`](https://github.com/material-components/material-components-android/tree/544180ae295b7ede68dfac5d986d8cc64f9f5c15)

**Devices:**
- API 21 Emulator
- API 23 Emulator
- API 26 Emulator

**Comment by drchen** [comment]
@pekingme can you take a look?
