### ISSUE TITLE
[Docs][Slider] remove or revise the note

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#4268]
**Is your feature request related to a problem? Please describe.**
https://github.com/material-components/material-components-android/blob/master/docs/components/Slider.md
https://github.com/material-components/material-components-android/commit/6c85b59a5810db57139195b061e4c8a23b99af2a
https://github.com/material-components/material-components-android/commit/967dcd5e071773c2d54ab499065b6690524b5752
> Note: there's a known issue where the label doesn't scroll along with the screen
> when the slider is in a scrollable container and `app:labelBehavior=visible`. To
> work around that you should either use a different mode or hide the label on
> scroll.

**Describe the solution you'd like**
remove or revise the note:
> Note: *as of version 1.13.0-alpha05 and below,* there's a known issue where the label doesn't scroll along with the screen
> when the slider is in a scrollable container and `app:labelBehavior="visible"`. To
> work around that you should either use a different mode or hide the label on
> scroll.

**Comment by imhappi** [comment]
Going to close this issue and related PR. These docs will be updated once fixed instead, we don't want to have to update this doc upon every release
