### ISSUE TITLE
Error with gradle file while connecting Firebase to android studio.

### ISSUE THREAD

**Issue by Kartikeya26** [material-components/material-components-android#427]
i was trying to connect my android studio with Firebase and had followed all steps given in their document but i am getting this error when i am trying to sync my gradle file.

ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.

![Capture](https://user-images.githubusercontent.com/24594252/61063629-e9800980-a41d-11e9-8139-a5e7d54b56cb.PNG)
![Capture1](https://user-images.githubusercontent.com/24594252/61063634-eb49cd00-a41d-11e9-8751-007e42e08082.PNG)

**Comment by ldjcmu** [comment]
AndroidX should function correctly with the current alpha.
