### ISSUE TITLE
[Search] Content to be searched (RecyclerView list) is not shown 

### ISSUE THREAD

**Issue by patrickfrei** [material-components/material-components-android#4272]
**Description:** I currently have below structure in my `activity_main.xml`. What I've additionally included for testing purpose is a `SearchBar` and a `SearchView`, similar to the [documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/Search.md). I'm using a `ViewPager2` with fragments (one for each tab of the `TabLayout`, including each a `RecyclerView` list).

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:layoutDirection="locale"
    android:textDirection="locale"
    tools:context=".MainActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:stateListAnimator="@null"
        android:fitsSystemWindows="true">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:minHeight="?attr/actionBarSize"
            app:layout_scrollFlags="scroll|enterAlways|snap"
            app:layout_scrollEffect="compress" />

        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/transparent"
            android:contentDescription="@string/app_name"
            app:layout_scrollFlags="scroll|enterAlways"
            app:tabMode="scrollable" />

        <com.google.android.material.search.SearchBar
            android:id="@+id/search_bar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="searchbar_hint" />

    </com.google.android.material.appbar.AppBarLayout>

    <com.google.android.material.search.SearchView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:hint="searchbar_hint"
        app:layout_anchor="@id/search_bar">

    <androidx.viewpager2.widget.ViewPager2
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipChildren="false"
        android:clipToPadding="false"
        app:layout_behavior="@string/searchbar_scrolling_view_behavior" />

    </com.google.android.material.search.SearchView>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Expected behavior:** When starting the app, the `RecyclerView` list is not shown. But if I'm clicking on the `SearchView`, the list appears. In my opinion, when I'm starting the app, the content of the `RecyclerView` list should appear. Then, when clicking on the `SearchView`, the list should still be visible and searchable. 

Is the `SearchBar` / `SearchView` maybe not intended to be used with a `ViewPager2` or do I have to implement these components differently when using a `ViewPager2`?

**Source code:** See above XML code.

**Android API version:** Tested on Android API 30-35

**Material Library version:** 1.13.0-alpha05

**Device:** Pixel 8 emulators, Nokia 7.2

**Comment by imhappi** [comment]
Hi @patrickfrei ! SearchView is a view that only shows up when the SearchBar is tapped to display search results. Please see our catalog app if you want to see a demo and some [code samples](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/search/res/layout/cat_search_recycler_fragment.xml)

**Comment by patrickfrei** [comment]
Hi @imhappi ! What I still do not understand is how to transfer the search string over to a RecyclerView for filtering. In the example that you've added above, entering a search string has unfortunately no effect on the RecyclerView (result is static). Do you have some hints for me about that requirement?

**Comment by imhappi** [comment]
Hi @patrickfrei , you can use `SearchView.getText` to get the search string. You can also use `SearchView.getEditText` to get the search EditText so that you can filter when the text is changed with the EditText text changed listeners

**Comment by patrickfrei** [comment]
Hi @imhappi , many thanks. I understand, but how can I then transfer the search string over to a RecyclerView for filtering?

**Comment by patrickfrei** [comment]
Hi @imhappi , thank you, I've set-up SearchBar and SearchView with getText as you have proposed and it's working. 

However, I'm still struggling with the following use case: 
- My app has a TabLayout that consists of multiple fragments, having each a RecyclerView
- SearchBar and SearchView are defined in activity_main.xml (MainActivity.java)
- RecyclerView has a filterable implementation
- I'd like to filter on the RecyclerView of the currently selected fragment

Problem is that if I define SearchView.getText either in...
- MainActivity.java, the currently relevant fragment / RecyclerView adapter is unknown, i.e. I cannot pass the search string from SearchView over the ,
...or in...
- each fragment, the SearchBar and SearchView IDs are unknown within the fragment as they are defined in activity_main.xml.

Do you see any solution for that use case? In the catalog demo, the fragment contents are hard-coded, i.e. I cannot use them as reference.
