### ISSUE TITLE
[Color] BadColor

### ISSUE THREAD

**Issue by HanzoDev1375** [material-components/material-components-android#4274]
### Demo app version 1.13.0 Al... 
![Screenshot_2024-08-30-16-08-03-676_io material catalog](https://github.com/user-attachments/assets/e692939b-f8f2-43ad-b60e-ca6e06c4953c)

### Myapp version 1.12.0

![Screenshot_2024-08-30-16-08-19-799_Ninja coder Ghostemane code](https://github.com/user-attachments/assets/735796f6-3c63-4f80-b568-94dbe5d29ad3)

Hello, I wanted to ask why the colors were so badly shaped in the new version of the Google Material library. I am using the stable version 1.12.0 and the colors are not so bad.

**Comment by imhappi** [comment]
Hello @HanzoDev1375 , in 1.13-alpha04 we updated some colors in Android V to match system dynamic colors (change was made here: https://github.com/material-components/material-components-android/commit/a2b9322d88894d61a9589a6332afe33d9dcfa0c1)
