### ISSUE TITLE
ExposedDropdownMenu recreated in the open state when it was just focused

### ISSUE THREAD

**Issue by niqueco** [material-components/material-components-android#428]
**Description:** ExposedDropdownMenu recreated in the open state when it was just focused

**Expected behavior:** If I select an item the dropdown closes, but the component remains focused. If I rotate the phone the component should be recreated in that same state.

**Current behavior:** If I rotate the phone the component gets recreated with the dropdown open.

**Material Library version:** 1.1.0-alpha08

**Comment by wondering639** [comment]
I have the same issue. Any workaround for that?

**Comment by drchen** [comment]
Is this still an issue?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
