### ISSUE TITLE
[Badge] Increase the font size of badge

### ISSUE THREAD

**Issue by mariaiffonseca** [material-components/material-components-android#4283]
**Description:** If I increase the default font size of the badge, the shape of this material becomes oval instead of rounded. I think that happens because the badge is built using `RoundedShapeCorner`. That makes sense, but it could be interesting to be possible to increase the font size, not affecting the default (and expected) behavior. You can see in the following image the actual result:
<img width="70" alt="Screenshot 2024-09-05 at 17 23 48" src="https://github.com/user-attachments/assets/15740131-1e1d-478b-b7b6-a6f264ebe32a">

**Expected behavior:** The expected behavior is increase the font size and keep the circle shape 

**Source code:** After analyzing the function `Badge` in `androidx.compose.material`, I think that what is causing this behavior is this line (137):
`val radius = if (content != null) BadgeWithContentRadius else BadgeRadius`

**Android API version:** I tested on 34.

**Material Library version:** [1.12.0](https://github.com/material-components/material-components-android/releases/tag/1.12.0)

**Device:** I only tested on Pixel 7 and 8, and the result was the same. So, I believe that happens in most devices

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by imhappi** [comment]
Hello, you can file issues for the Material Compose library here: https://issuetracker.google.com/issues/new?component=742043&template=1590761

This issue does not exist for badges for this library as it asserts that a badge is at least as wide as it is tall
