### ISSUE TITLE
BottomNavigationView itemIconTint  set null is invalid in  Theme.Material3.Light.NoActionBar

### ISSUE THREAD

**Issue by kiss2sky** [material-components/material-components-android#4288]
BottomNavigationView itemIconTint  set null is invalid in  Theme.Material3.Light.NoActionBar

**Comment by imhappi** [comment]
Hi there, this is WAI. If app:itemIconTint is null, we will fall back to the default value (?attr/textColorSecondary).

https://github.com/material-components/material-components-android/issues/2597#issuecomment-1154028573

If you want to remove the tint, please do so programmatically

**Comment by kiss2sky** [comment]
demo中的例子

private void addBottomNavsToList(View view) {
    bottomNavigationViews = DemoUtils.findViewsWithType(view, BottomNavigationView.class);
    for (BottomNavigationView bottomNavigationView : bottomNavigationViews) {
        bottomNavigationView.setItemIconTintList(null);
    }
  }

设置了没有效果
