### ISSUE TITLE
[Bottom Navigation - Sample] "+Badge Number" feature isn't working 

### ISSUE THREAD

**Issue by mitchware-cfa** [material-components/material-components-android#429]
**Description:** The "+Badge Number" button in the sample for Bottom Navigation doesn't always add badge numbers to the current tab

**Expected behavior:** Pressing "+Badge Number" would increment the badge for the selected tab

**Source code:** The sample app in the repo demonstrates this behavior.

**Android API version:** Tested on 9.0

**Material Library version:** Whatever is declared in the sample repo

**Device:** Pixel 2 XL Image on emulator

**Comment by mitchware-cfa** [comment]
It seems to work immediately when launching the sample, but the badge functionality breaks when adding more tabs to the navigation view

**Comment by wcshi** [comment]
Hi @mitchware-cfa thanks for reporting this issue, we discovered it this morning and submitted a fix internally, it will be synced out soon.

**Comment by mitchware-cfa** [comment]
Awesome! Thank you for the response and all the work you guys are doing :)

**Comment by raquezha** [comment]
Can I use the BadgeDrawable in an ImageViews aside from BottomNavigationView or TabLayout?

**Comment by wcshi** [comment]
@raquezha could you please file a new feature request, thank you!
