### ISSUE TITLE
[Color] background color of components is slightly incorrect in Android 13

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#4293]
**Description:** The background color of components is slightly incorrect in Android 13.
colorSurface is #FFF8F5 and colorSurfaceContainerLow is #FFF1E7:
![Screenshot_20240913_210012](https://github.com/user-attachments/assets/5c925172-2b2e-42dc-8df1-81a2c986a1f1)
The background color of the standard side sheet is not #FFF8F5 but #FFF8F3:
![Screenshot_20240913_232350](https://github.com/user-attachments/assets/178bc48e-485f-406a-b9b6-1ae59fecd7b7)
The background color of the modal side sheet is not #FFF1E7 but #FFF1E5:
![Screenshot_20240913_232444](https://github.com/user-attachments/assets/4fe69872-6dec-4fa9-aa72-fdb052e9c540)
The background color of the standard bottom sheet is not #FFF1E7 but #FFF1E5 (the background color of the drag handle view is not #FFF1E7 but #FFF1E5 and the background color of the navigation view is #FFF1E7):
![367347092-b38fba2e-8dd3-4445-b4b2-1c10b627417b](https://github.com/user-attachments/assets/d9533c26-c8ec-49c8-8ba4-262a8a55db97)
The background color of the bottom sheet is not #FFF1E7 but #FFF1E5:
![Screenshot_20240913_232927](https://github.com/user-attachments/assets/04aa5d66-c712-4475-bb9b-99e292ac47f9)
![Screenshot_20240913_232936](https://github.com/user-attachments/assets/c8a67798-c7d7-4444-a58f-b7ff854839fd)
The background color of the elevated button is not #FFF1E7 but #FFF1E5:
![Screenshot_20240913_232839](https://github.com/user-attachments/assets/768e7037-cb48-426f-bf0c-f97ff0e160a2)
...
It seems that MaterialResources.getColorStateList() causes this issue.
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/sidesheet/SideSheetBehavior.java#L145-L147:
```
      this.backgroundTint =
          MaterialResources.getColorStateList(
              context, a, R.styleable.SideSheetBehavior_Layout_backgroundTint);
```
The background color of components is correct in Android 12L, 14, and 15.

**Expected behavior:** The background color of components is correct in Android 13.

**Minimal sample app repro:** Catalog app

**Android API version:** 33

**Material Library version:** 1.11.0+

**Device:** Emulator 32.1.15

**Comment by leticiarossi** [comment]
I'm not sure I fully understand but when I test in an API 33 emulator I see the same # values in the colors demo and in the components colors. Same thing for when I test for API 32, although I do see a slight difference of like a hex letter at the end compared to the api 33 emulator, but still the colors demo and components have the same corresponding color values. I'm guessing these values differences depend on the emulator/device? But visually the colors are still correct

**Comment by manabu-nakamura** [comment]
Write the following code in BottomSheetMainDemoFragment.onCreateDemoView().
```
    try {
      Method method = BottomSheetBehavior.class.getDeclaredMethod("getMaterialShapeDrawable");
      method.setAccessible(true);
      MaterialShapeDrawable materialShapeDrawable = (MaterialShapeDrawable)method.invoke(persistentBottomSheetBehavior);
      TextView textView = view.findViewById(R.id.textView);
      textView.setText(String.format("%X, %X\n", MaterialColors.getColor(bottomSheetPersistent, R.attr.colorSurfaceContainerLow), materialShapeDrawable.getResolvedTintColor()));
    } catch (Exception e) {
    }
```
The background color of the bottom sheet is slightly different from colorSurfaceContainerLow in Android 13.
The background color of the bottom sheet is colorSurfaceContainerLow in Android 12L, 14, and 15.
![Screenshot_20240920_094241](https://github.com/user-attachments/assets/e29fdcaf-4a6e-44f1-91b1-b6880a2b6086)
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/BottomSheetBehavior.java#L1734-L1736
```
  MaterialShapeDrawable getMaterialShapeDrawable() {
    return materialShapeDrawable;
  }
```
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/BottomSheetBehavior.java#L360-L361
```
      this.backgroundTint = MaterialResources.getColorStateList(
          context, a, R.styleable.BottomSheetBehavior_Layout_backgroundTint);
```
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/BottomSheetBehavior.java#L1725
```
      materialShapeDrawable.setFillColor(backgroundTint);
```
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomsheet/BottomSheetBehavior.java#L565
```
        ViewCompat.setBackgroundTintList(child, backgroundTint);
```

**Comment by manabu-nakamura** [comment]
The background color of the standard bottom sheet is not #FFF1E7 but #FFF1E5 (the background color of the drag handle view is not #FFF1E7 but #FFF1E5 and the background color of the navigation view is #FFF1E7):
![367347092-b38fba2e-8dd3-4445-b4b2-1c10b627417b](https://github.com/user-attachments/assets/d9533c26-c8ec-49c8-8ba4-262a8a55db97)

**Comment by dsn5ft** [comment]
I'm guessing the bug / difference here is in `AppCompatResources.getColorStateList()` (used by components) vs `view.setBackgroundResource()` (used by the color demo with the tiles).

**Comment by manabu-nakamura** [comment]
- `ContextCompat.getColor()`:
```
    void bind(ColorItem colorItem) {
      int value = ContextCompat.getColor(context, colorItem.getColorRes());
```
![Screenshot_20240926_140919](https://github.com/user-attachments/assets/f4366adb-f51f-4a6c-892c-30de696d74b4)
- `AppCompatResources.getColorStateList()`:
```
    void bind(ColorItem colorItem) {
      int value = AppCompatResources.getColorStateList(context, colorItem.getColorRes()).getDefaultColor();
```
![Screenshot_20240926_141048](https://github.com/user-attachments/assets/826c4b4b-08bc-42c6-a834-26c97df35c01)
I think that MaterialResources.getColorStateList() (AppCompatResources.getColorStateList()) causes this issue, too.

**Comment by manabu-nakamura** [comment]
Is it possible to add workarounds to [MaterialResources.getColorStateList()](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/resources/MaterialResources.java#L58) and so on?
```
  @Nullable
  public static ColorStateList getColorStateList(
      @NonNull Context context, @NonNull TypedArray attributes, @StyleableRes int index) {
    if (attributes.hasValue(index)) {
      int resourceId = attributes.getResourceId(index, 0);
      if (resourceId != 0) {
//        ColorStateList value = AppCompatResources.getColorStateList(context, resourceId);
        ColorStateList value;                                                               //
        if (Build.VERSION.SDK_INT == VERSION_CODES.TIRAMISU) {                              //
          value = context.getResources().getColorStateList(resourceId, context.getTheme()); //
        } else {                                                                            //
          value = AppCompatResources.getColorStateList(context, resourceId);                //
        }                                                                                   //
        if (value != null) {
          return value;
        }
      }
    }

    return attributes.getColorStateList(index);
  }
```
