### ISSUE TITLE
[Splash Screen] Short description of issue

### ISSUE THREAD

**Issue by trindadedev13** [material-components/material-components-android#4304]
Hello, in my app's SplashScreen, the background color does not follow the highlight color of my cell phone. See:

https://github.com/user-attachments/assets/eea7756a-2407-443d-af17-1e4fad9503dd

Library Version: 1.13.0-alpha06
Device: Motorola Moto g34
Source: [App Source](https://github.com/robok-inc/Robok-Engine)

**Comment by RivanParmar** [comment]
This is likely happening because you are setting a background for your splash screen [here](https://github.com/robok-inc/Robok-Engine/blob/dev/app%2Fsrc%2Fmain%2Fres%2Fvalues%2Fthemes.xml#L20) and [here](https://github.com/robok-inc/Robok-Engine/blob/dev/app%2Fsrc%2Fmain%2Fres%2Fvalues-night%2Fthemes.xml#L19). Moreover, you're trying to set a drawable image as a background, which isn't supported. The `windowSplashScreenBackground` only accepts colors.

**Comment by trindadedev13** [comment]
> This is likely happening because you are setting a default background for your splash screen [here](https://github.com/robok-inc/Robok-Engine/blob/dev/app%2Fsrc%2Fmain%2Fres%2Fvalues%2Fthemes.xml#L20) and [here](https://github.com/robok-inc/Robok-Engine/blob/dev/app%2Fsrc%2Fmain%2Fres%2Fvalues-night%2Fthemes.xml#L19). Moreover, you're trying to set a drawable image as a background, which isn't supported. The `windowSplashScreenBackground` only accepts colors.

nan, I just put ?colorSurface to get the surface color and it keeps using the default red.

**Comment by mgustina19888** [comment]
Maaf saya tidak paham ini apa karena dulu saya tidak sekolah

Pada Kam, 19 Sep 2024, 22.10, Aquiles Trindade ***@***.***>
menulis:

**Comment by RivanParmar** [comment]
> > This is likely happening because you are setting a default background for your splash screen [here](https://github.com/robok-inc/Robok-Engine/blob/dev/app%2Fsrc%2Fmain%2Fres%2Fvalues%2Fthemes.xml#L20) and [here](https://github.com/robok-inc/Robok-Engine/blob/dev/app%2Fsrc%2Fmain%2Fres%2Fvalues-night%2Fthemes.xml#L19). Moreover, you're trying to set a drawable image as a background, which isn't supported. The `windowSplashScreenBackground` only accepts colors.
> 
> nan, I just put ?colorSurface to get the surface color and it keeps using the default red.

Your `colorSurface` seems to be the brown color that can be seen in the video. Try using some other color instead.

**Comment by mgustina19888** [comment]
Nanti saya tekan tekan salah tekan bagai mana malah tambah rusak sekarang
akun bank saya juga rusak

Pada Kam, 19 Sep 2024, 22.18, Rivan Parmar ***@***.***>
menulis:

**Comment by mgustina19888** [comment]
Gara gara update Google semua jadi rusak

Pada Kam, 19 Sep 2024, 22.23, MARIA AGUSTINA ***@***.***>
menulis:

**Comment by trindadedev13** [comment]
> > > Isso provavelmente está acontecendo porque você está definindo um plano de fundo padrão para sua tela inicial [aqui](https://github.com/robok-inc/Robok-Engine/blob/dev/app%2Fsrc%2Fmain%2Fres%2Fvalues%2Fthemes.xml#L20) e [aqui](https://github.com/robok-inc/Robok-Engine/blob/dev/app%2Fsrc%2Fmain%2Fres%2Fvalues-night%2Fthemes.xml#L19) . Além disso, você está tentando definir uma imagem desenhável como plano de fundo, o que não é suportado. O `windowSplashScreenBackground`aceita apenas cores.
> > 
> > 
> > nan, acabei de colocar ?colorSurface para obter a cor da superfície e ele continua usando o vermelho padrão.
> 
> A sua `colorSurface`parece ser a cor marrom que pode ser vista no vídeo. Tente usar outra cor em vez disso. Além disso, como você quer usar uma cor de fundo dinâmica, então você precisa simplesmente remover essa linha, o que deve fazer com que ele use a cor do seu telefone.

Yes, the colorSurface is brownish, however, the colorSurface is replaced by the device colors, if Monet is available, but this does not happen in Splash.

**Comment by RivanParmar** [comment]
Did you try removing that line from both the themes? Also, you need to call `installSplashScreen()` before the `super.onCreate` in your MainActivity.

**Comment by trindadedev13** [comment]
@RivanParmar no, it doesn't work.

**Comment by RivanParmar** [comment]
@trindadedev13 So after looking around for a bit, I found that you need to use `Theme.SplashScreen` as your parent theme as shown [here](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate#migrate). I tried it in your code and it works perfectly fine. However, another issue arises when you use `postSplashScreenTheme`. If the theme defined in `postSplashScreenTheme` uses a Material3 themes as a parent, then dynamic colors don't get applied to it. Here are the issues related to it: [Issue1](https://github.com/material-components/material-components-android/issues/2555) and [Issue2](https://github.com/material-components/material-components-android/issues/2824). Therefore, the best solution for you would be to use one of the system dynamic color resources in the `windowSplashScreenBackground` as pointed out in the second issue.

**Comment by dsn5ft** [comment]
@RivanParmar thanks for linking to those other issues, closing this one out as there are limitations and workarounds listed there.
