### ISSUE TITLE
[Loading Indicator] When playing the rotation animation, the rotation center of the pentagon does not coincide with the geometric center of the pentagon.

### ISSUE THREAD

**Issue by ArcticFoxPro** [material-components/material-components-android#4306]
**Description:** When playing the rotation animation, the rotation center of the pentagon does not coincide with the geometric center of the pentagon.

**Screenshot:** 

![Screenshot_2024-09-19-21-19-22-292_io.material.catalog-edit.jpg](https://github.com/user-attachments/assets/c84eeafc-7009-4a3f-a925-51fc104128d2)

**Source code:** No need to provide, the M3 Catalog Application can be reproduced

**Minimal sample app repro:** No need to provide, the M3 Catalog Application can be reproduced

**Android API version:** 34 (Android 14)

**Material Library version:** 1.13.0-alpha06

**Device:** Xiaomi 14 Pro with Android 14

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment]
@pekingme can you take a look, is this expected?
