### ISSUE TITLE
[ModalNavigationDrawer] Opening by default on start

### ISSUE THREAD

**Issue by criticalAY** [material-components/material-components-android#4311]
**Description:** Full description of issue here
Using the drawerState i.e. here
```
val drawerState = rememberDrawerState(initialValue = DrawerValue.Closed)

ModalNavigationDrawer(
....
drawerState = drawerState,
)
```

But on every startup, the app opens the drawer by default though I never toggled the drawer via code i.e. on start

This started happening after M3 dep update 

from `material3 = "1.2.1" to material3 = "1.3.0"`

**Expected behavior:** 
The drawer stays closed

**Android API version:** 35

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by dsn5ft** [comment]
Hello! This GitHub repo is for the Material Android library for Views. For Material Compose issues please file at https://issuetracker.google.com/issues/new?component=742043&template=1346811.
