### ISSUE TITLE
[ BottomNavigationView] BottomNavigationView.setItemIconTintList(null) invalid

### ISSUE THREAD

**Issue by kiss2sky** [material-components/material-components-android#4313]
Catalog   demo

private void addBottomNavsToList(View view) {
    bottomNavigationViews = DemoUtils.findViewsWithType(view, BottomNavigationView.class);
    for (BottomNavigationView bottomNavigationView : bottomNavigationViews) {
        bottomNavigationView.setItemIconTintList(null);
    }
  }

How to set it up

**Comment by dsn5ft** [comment]
@kiss2sky can you provide more information about what you are trying to achieve and what is not working?

**Comment by dsn5ft** [comment]
Feel free to reopen with more info.
