### ISSUE TITLE
[CollapsingToolbarLayout] Provide the style for CollapsingToolbarLayout via theme attribute

### ISSUE THREAD

**Issue by giem** [material-components/material-components-android#432]
Currently the `CollapsingToolbarLayout` has a hardcoded style:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/appbar/CollapsingToolbarLayout.java#L166

It would be useful to provide it via theme attribute, so we could have a different scrim colour provided by the theme.

**Comment by drchen** [comment]
You can override ?attr/collapsingToolbarLayoutStyle to customize the CollapsingToolbarLayout now. : )
