### ISSUE TITLE
[PopupMenu] PopupMenu styles only work with appcompat version

### ISSUE THREAD

**Issue by UweTrottmann** [material-components/material-components-android#4332]
**Description:** The set PopupMenu styles (via the `popupMenuStyle` attribute) only work with `androidx.appcompat.widget.PopupMenu`. [But the menu docs](https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md#dropdown-menus) link to/suggest using `android.widget.PopupMenu`.

**Expected behavior:**
I guess there are two options:
- set `android:popupMenuStyle` (in addition to `popupMenuStyle`, e.g [like for the light theme](https://github.com/material-components/material-components-android/blob/8f5a04c62b23aee01fa68aae8b467d7eb7c5e6ed/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L203)) in the Material themes so the platform PopupMenu is styled as well (but maybe there is a reason why this was not done?),
- update the docs to link to/suggest using `androidx.appcompat.widget.PopupMenu` instead.

**Material Library version:** master

**Device:** Android 15 emulator

**Comment by dsn5ft** [comment]
Ah thank you, will update the doc links for both PopupMenu and ListPopupWindow
