### ISSUE TITLE
[Height & width for DatePicker] Customise width & height for the material3 date picker

### ISSUE THREAD

**Issue by ashishg656** [material-components/material-components-android#4339]
**Description:**
I want to customize the height & the width for the material3 date picker, but unable to do so.
Also, when switching to year selection UI, the height of date picker dialog changes as well - is it possible to keep the height of the dialog same when switching to year selection UI.

So there are 3 issues in total - 
1. The width of date picker - I want to increase the width of date picker so that the date picker occupy full width of screen but have a padding of 16dp from the edge of the screen.
2. Height of date picker - when switching from date selection to year selection, the height of date picker increases. How to keep the height same when switching between date & year selection?
3. Padding between the action buttons (OK and Cancel buttons) and the dates is too high - how to reduce the padding between the last row of dates and the action buttons.

**Expected behavior:** 
<img width="635" alt="Screenshot 2024-10-10 at 5 26 59 PM" src="https://github.com/user-attachments/assets/02849f98-76c7-435c-a5c0-31b7e631bae3">

**Android API version:**  Android 21

**Material Library version:**  1.8.0

**Device:** Pixel 8 Pro & other android devices

**Comment by afohrman** [comment]
Thanks for reporting! Could you please file a separate issue for each feature request?
