### ISSUE TITLE
[TextInputLayout] Please expose an api for end icon animation disabling

### ISSUE THREAD

**Issue by creati8e** [material-components/material-components-android#434]

**Comment by gabrielemariotti** [comment]
@creati8e Can you provide more details?

**Comment by creati8e** [comment]
@gabrielemariotti end icon automaticaly animated on appearing. I am talking about providing an option to disable this animation

**Comment by drchen** [comment]
Not sure what benefit this can bring by disabling the animation. Can you elaborate more?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with more details.
