### ISSUE TITLE
[CardView] rippes on click do not fill the corner

### ISSUE THREAD

**Issue by hardysim** [material-components/material-components-android#435]
**Description:** I've changed the `shapeAppearance` of a `CardView` to a style which alters the edges. When clicking the card, the ripples do not reach the very edge anymore. It's ending in a rectangle without any shaped corners.

![image](https://user-images.githubusercontent.com/3737512/61125199-7c19ba80-a4a9-11e9-8b1e-934f85faf384.png)

**Expected behavior:** The ripples should reach the edges just like they do when I don't change the `shapeAppearance`.

![image](https://user-images.githubusercontent.com/3737512/61125270-b8e5b180-a4a9-11e9-9915-f750b0b3be5b.png)

**Source code:** 
```xml
<com.google.android.material.card.MaterialCardView
    style="@style/NoCornerBottom"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
```

```xml
<style name="NoCornerBottom" parent="">
        <item name="shapeAppearance">@style/ShapeAppearance.NoCornerBottom</item>
    </style>

<style name="ShapeAppearance.NoCornerBottom" parent="ShapeAppearance.MaterialComponents.MediumComponent">
    <item name="cornerSizeBottomRight">0dp</item>
    <item name="cornerSizeBottomLeft">0dp</item>
</style>
```

**Android API version:** `minSdkVersion 21`, `targetSdkVersion 28`

**Material Library version:** `1.1.0-alpha08`

**Device:** Pixel 3 with Android Q Beta 4

**Comment by kibotu** [comment]
doesn't like cardView attributes

[- cornerSizeTopLeft
- cornerSizeTopRight
- cornerSizeBottomLeft
- cornerSizeBottomRight](https://material.io/develop/android/theming/shape/)

are supported for atm

**Comment by hardysim** [comment]
@kibotu There are even examples to change the shape of a CardView on the page you've linked. And it's mentioned on the very bottom under "Supported Components". So I think it *is* supported.

I found `shapeAppearanceOverlay` on this page but this doesn't work either (it's applied, but the ripples don't reach the edges.

![image](https://user-images.githubusercontent.com/3737512/61211950-23dcf580-a701-11e9-9d6c-04ab40a65417.png)

**Comment by kibotu** [comment]
you are correct it is supposed to be supported but it doesn't work atm

**Comment by kibotu** [comment]
here is a workaround: https://github.com/googlesamples/android-sunflower/pull/437/files (basically [overriding onDraw in MaterialCardView](https://github.com/googlesamples/android-sunflower/blob/5a1d360da858b020ed9a830c7e8a343d10715596/app/src/main/java/com/google/samples/apps/sunflower/views/CustomCardView.kt) and then [setting the style](https://github.com/googlesamples/android-sunflower/blob/5a1d360da858b020ed9a830c7e8a343d10715596/app/src/main/res/values/styles.xml#L38-L45)

**Comment by hardysim** [comment]
Nice! This works **when adding `app:cardPreventCornerOverlap="false"` as well**.

It looks like `app:cardPreventCornerOverlap="false"` draws the ripples outside the card-content and therefore reaches the edges. So we need this and `CustomCardView` to get it working.


#### with `app:cardPreventCornerOverlap="false"` and `MaterialCardView`
![image](https://user-images.githubusercontent.com/3737512/61216558-e92d8a00-a70d-11e9-8123-d56cb3b1e2f0.png)

#### with `app:cardPreventCornerOverlap="false"` and `CustomCardView`
![image](https://user-images.githubusercontent.com/3737512/61216467-b6839180-a70d-11e9-90d7-c76098f76ce6.png)

---

It should be enough to add those changes in `onDraw()` to `MaterialCardView` to get it working, right? Or is there anything standing against a PR for this? We'll need `app:cardPreventCornerOverlap="false"` either way.

**Comment by ymarian** [comment]
Can we take a step back none of that should be necessary for ripples. 

Can you share a sample app with a repro of the issue?

**Comment by hardysim** [comment]
> Can we take a step back none of that should be necessary for ripples.

True. Here's a demo project: https://github.com/hardysim/CardViewRippleTest
I've just added a `MaterialCardView` with `cornerFamily = cut` and it works out of the box.

---

Let me check what I'm doing different in my actual project and reach back.

**Comment by hardysim** [comment]
Ok, no changes needed - `MaterialCardView ` works just fine.

It was my fault of having the actual clickable item inside the card with its own background (which was the plain rectangle on the screenshots). Removing this and just let the card do it's thing resolves my problem.

Thank you.

**Comment by ymarian** [comment]
Awesome that was my guess, If you ran into problems with images or something inside the card you will have to implement the suggested workarounds until we bake the fixes into CardView
