### ISSUE TITLE
[Docs] What are GM2 and GM3?

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#4354]
**Is your feature request related to a problem? Please describe.**
What are [GM2](https://m3.material.io/search.html?q=GM2) and [GM3](https://m3.material.io/search.html?q=GM3)? What is the difference between M2 and GM2? What is the difference between M3 and GM3?

![b](https://github.com/user-attachments/assets/0417c07f-ff55-41c5-8e98-4e795a35ef80)

**Describe the solution you'd like**
Add the description.
https://m3.material.io/foundations/glossary

**Comment by pekingme** [comment]
Thanks for reporting! Those should be scrubbed on release. Basically, "GM3" == "M3"; "GM2" == "M2". Have reported to internal teams. Closing this bug.
