### ISSUE TITLE
 error: attribute trackCornerSize not found.

### ISSUE THREAD

**Issue by Ilya193** [material-components/material-components-android#4390]
I'm using with com.google.android.material.slider.Slider
In documentation there is a property app:trackCornerSize
(https://github.com/material-components/material-components-android/blob/master/docs/components/Slider.md#track-attributes)

My code gives me an error 

Android resource linking failed
ru.ikom.everything.app-mergeDebugResources-3:/layout/activity_main.xml:27: error: attribute trackCornerSize not found.
error: failed linking file resources.

    <com.google.android.material.slider.Slider
        android:id="@+id/slider"
        android:layout_width="300dp"
        android:layout_height="wrap_content"
        android:value="20.0"
        app:tickVisible="false"
        app:trackColorActive="@android:color/holo_orange_light"
        app:trackColorInactive="@android:color/darker_gray"
        app:labelBehavior="gone"
        android:stepSize="1"
        app:trackInsideCornerSize="0dp"
        app:trackStopIndicatorSize="0dp"
        android:valueFrom="4"
        android:valueTo="100"
        app:trackCornerSize="0dp"
        android:valueType="intType"
        app:thumbWidth="30dp"
        app:thumbHeight="20dp"
        app:trackHeight="15dp"
        app:thumbColor="@android:color/holo_red_dark"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintStart_toStartOf="parent" />
        
in the build.gradle.ktx 
implementation("com.google.android.material:material:1.12.0")

**Comment by imhappi** [comment]
Hello, trackCornerSize was an attribute that was introduced recently and will be in the 1.13.0-alpha08 release
