### ISSUE TITLE
[Slider] `android:orientation="vertical"` and `app:labelBehavior="visible"` slider is broken

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#4391]
**Description:** `android:orientation="vertical"` and `app:labelBehavior="visible"` slider is broken.
- `android:orientation="vertical"` and `app:labelBehavior="visible"`
![Screenshot_20241122_150535](https://github.com/user-attachments/assets/d7d9c214-9d9a-4f76-824e-cc455d0c6716)
- `android:orientation="vertical"`
![Screenshot_20241122_150444](https://github.com/user-attachments/assets/f79d95f3-f0d7-420e-9dd3-b87722956d77)

**Expected behavior:** `android:orientation="vertical"` and `app:labelBehavior="visible"` slider is not broken.

**Source code:** https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/slider/SliderVerticalDemoFragment.java
https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/slider/res/layout/cat_slider_demo_vertical.xml

**Android API version:** 35

**Material Library version:** 1.13.0-alpha08

**Device:** Emulator 35.2.10

**Comment by imhappi** [comment]
@paulfthomas could you take a look at this issue?
