### ISSUE TITLE
[BottomNavigation] Support Large, Small Label Font weight.

### ISSUE THREAD

**Issue by Nanamare** [material-components/material-components-android#4393]
Title: How to Use Custom Font Weights (e.g., 500, 600) for Large and Small Labels?

Description:

I’m trying to set a font weight other than Normal (400) or Bold (700) for large and small labels, such as 500 or 600. However, I couldn’t find a clear way to achieve this.

Is there a way to apply these intermediate font weights? If so, could you provide some guidance or examples?

<img width="596" alt="스크린샷 2024-11-22 오후 10 36 45" src="https://github.com/user-attachments/assets/53ef1efe-1670-4f74-843b-ab434c84949b">

Thank you!

**Comment by imhappi** [comment]
Hello, you can set the text appearance for an unselected and selected item label through the itemTextAppearanceActive vs itemTextAppearanceInactive attributes. 

Note that all selected items will still be bolded/keep the same weight even if itemTextAppearanceActive is set to something else if itemTextAppearanceActiveBoldEnabled is true (true by default)
