### ISSUE TITLE
AS Preview doesn't match TextInputLayout actual appearance on device

### ISSUE THREAD

**Issue by samcackett** [material-components/material-components-android#443]
**Description:** Full description of issue here
The layout preview in Android Studio doesn't match how the Material Components `TextInputLayout` actually appears on an Android device. It just displays a very simple layout with a grey baseline.
![image](https://user-images.githubusercontent.com/5948635/61225480-8a214280-a718-11e9-9a0f-bafa018e8ab0.png)

**Expected behavior:** Screenshots and/or description of expected behavior
#### Expected
Looks the same as on a real device

#### Actual
Looks very basic (see screenshot) and nothing like the real Material component

### Reproduction steps
 - Add a `com.google.android.material.textfield.TextInputLayout` to any layout
 - Open the Android Studio layout preview

**Android API version:** 
Makes no difference

**Material Library version:** 
1.1.0-alpha07

**Device:**
 N/A

**Comment by drchen** [comment]
Is this still happening with the latest library/AS version?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
