### ISSUE TITLE
[NavigationDrawer] [PredictiveBack] Back navigation takes precedence over closing the drawer

### ISSUE THREAD

**Issue by philips77** [material-components/material-components-android#4449]
**Description:**
I have the following design:
```kotlin
val navController = rememberNavController()
val drawerState = rememberDrawerState(DrawerValue.Closed)

ModalNavigationDrawer(
   drawerState = drawerState,
   drawerContent = {
      ModalDrawerSheet(drawerState = drawerState) {
         // list of NavigationDrawerItems using navController
      }
) {
   Scaffold(
      topBar = { ... }
   ) {
      NavHost(navController) {
         // list of composables
      }
   }
}
```
When I'm on top-most screen, the predictive back collapsing the drawer works fine.
However, **when I navigate to another screen using the drawer (which has the drawer also available) and open drawer FROM that other screen - then back goes back to the main screen even with the drawer open**. Second back collapses the drawer. `NavHost` is lower in the hierarchy and it is its back handler that if checked first, not the drawer that takes 90% of the screen.

If I put a custom `BackHandler` inside the `Scaffold` content:
```kotlin
Scaffold(
      topBar = { ... }
   ) {
      BackHander(
         enabled = drawerState.isOpen
         onBack = { scope.launch { drawerState.close() } }
      )
      NavHost(navController) {
         // list of composables
      }
   }
```
then drawer is closer first, before navigation. But the predictive back of course doesn't work.

**Expected behavior:** 
If drawer is open, back gesture should first close the nav drawer and use predictive back animation.

**Android API version:** Android API 35

**Material Library version:** Material 3 Android Library BOM 2024.11.0 (1.3.1)

**Device:** Pixel 7, Android 15

**Comment by hunterstich** [comment]
Hey @philips77,

I think this should be filed under the Material Compose issuetracker - https://issuetracker.google.com/issues?q=componentid:742043

Closing this as this is the Material Components Views library.

**Comment by philips77** [comment]
For reference: https://issuetracker.google.com/issues/383356848
