### ISSUE TITLE
[BadgeDrawable] capability to add badges on custom views, image view, etc.

### ISSUE THREAD

**Issue by raquezha** [material-components/material-components-android#445]
**Description.**
Add badge on ImageViews, or other custom views.

**Comment by wcshi** [comment]
Hi @raquezha thank you for your interest in the badging feature, as noted in the javadoc, this feature is currently under development.

Could you please explain your intended use case?

**Comment by raquezha** [comment]
I have a framlelayout which simulates the toolbar, inside it I have:

1. Back button (ImageButton)  [Left]
2. Logo (ImageView) [Center] 
3. Cart icon (ImageView)[Right].
4. Clear Cart Icon (ImageVIew) [Left of Cart Icon]

Use Case:  Every time a user pick an item want to put:

1. A _**Badge with Number_** on the upper right part of the Cart Icon,
2. When the user click the clear cart button then Remove the _**Badge with Number**_
3. When the user adds another item, just increment the current badge number.


Also does this include adding badge on menu items or I should create another request? or just edit the title?

**Comment by wcshi** [comment]
What kind of menu items?

**Comment by raquezha** [comment]
I'm refering to this menu https://developer.android.com/guide/topics/ui/menus

**Comment by wcshi** [comment]
There are multiple types of menus in that link: options menu, popup menu, contextual menus, based o your comment, I assume you mean option menu?

**Comment by raquezha** [comment]
Sorry about that. Yes I'm referring to Option Menu. 

thank you!

**Comment by xsxkair** [comment]
when can i use the badge,

**Comment by wcshi** [comment]
@xsxkair what's your use case?

**Comment by kobe-anacoimbra** [comment]
Hey, this would be a great feature! I need the excact use case reported by @raquezha for the option menu cart.

**Comment by wcshi** [comment]
There are currently no plans to explicitly support badging on option menus, however, I think you may be able to create a custom layout which contains a badgeDrawable and set it via app:actionLayout

**Comment by danaimset** [comment]
Are there any plans to support drawable background instead of color?
Are there missing customizable strokeWidth/strokeColor attributes? Would be great to have one of the options:
- customize entire badge background with drawable
- set strokeWidth & strokeColor (for internal shape drawable)

What would you recommend?

**Comment by wcshi** [comment]
Similar to https://github.com/material-components/material-components-android/issues/1112

**Comment by guyca** [comment]
Are there any plans to support [BadeDrawable](https://github.com/material-components/material-components-android/blob/master/docs/components/BadgeDrawable.md) in MenuItem views? The docs explicitly mention that only `TabLayout` and `BottomNavigationView` support the badge drawable but It's pretty common use case to add badges toToolBar items.

For some reason, adding the badge to the MenuItem view works with `BadgeUtils.attachBadgeDrawable(this, itemView, null)`, but not with `itemView.overlay.add(this)`.
Where `itemView` is the MenuItem's corresponding view and `this` is a `BadgeDrawable`

**Comment by wcshi** [comment]
See this comment about why it's delayed
https://github.com/material-components/material-components-android/issues/657#issuecomment-679320329

**Comment by wcshi** [comment]
Resolved in 5e35d14

rolledback in 0f717f8, rolled forward in 9487c33

**Comment by raquezha** [comment]
Woah! nice thanks!
