### ISSUE TITLE
[CollapsingToolbarLayout/AppBarLayout] Expand or collapse without animation still animate scrim

### ISSUE THREAD

**Issue by NitroG42** [material-components/material-components-android#446]
**Description:** When we want to start the screen with the AppBarLayout collapsed (without animation), the scrim still animate.

**Expected behavior:** The scrim doesn't animate and we start displaying the screen with the appbarlayout collapsed and the scrim on.

**Source code:** https://github.com/NitroG42/MaterialComponentBugs/tree/master
See activity [ScrimBugActivity](https://github.com/NitroG42/MaterialComponentBugs/blob/master/app/src/main/java/com/nitrog42/materialcomponentbugs/ScrimBugActivity.kt)
In this sample, I trigger an expand/collapse every second. We can see the scrim is animating though the animate property is false :
```
app_bar.setExpanded(expanded, false)
toolbar_layout.setScrimsShown(expanded, false)
```
As I said, I can understand this behavior but if we want to start the screen with a collapsed AppBarLayout (without animation), using `app:expanded="false"` on the AppBarLayout, we can still see the scrim animating. 

Here's a [video](https://streamable.com/20m39)

**Android API version:** Tested on API 28

**Material Library version:** 1.1.0-alpha08

**Device:** Google Pixel Android 9

**Comment by andrelabonte** [comment]
Thanks. We are tracking this here:
https://issuetracker.google.com/issues/69102146
