### ISSUE TITLE
addOnChangeListener doesn't exist in com.google.android.material.slider.BaseSlider in release build

### ISSUE THREAD

**Issue by Joost-Jens-Luminis** [material-components/material-components-android#4460]
**Description:** Full description of issue here
I am trying to get value changes for a slider in Android. However, there is not event for this. The method "addOnChangeListener" is also not available. 

Trying to get the "addOnChangeListener" method from the baseclass does work during debug builds, but during release builds it is not found.

**Expected behavior:** Screenshots and/or description of expected behavior
To be able to listen to changes to the value of a slider using addOnChangeListener (or any othr method, I am not picky on this).
**Source code:** The code snippet which is causing this issue

```
  var methods = Java.Lang.Class.ForName("com.google.android.material.slider.BaseSlider").GetDeclaredMethods();
  Method method = methods.FirstOrDefault(x => x.Name == "addOnChangeListener");
  method?.Invoke(this._tuneSlider, this); // this is implementing IBaseOnChangeListener      
```     

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** Android API version here
Supported OS: 28
Target OS: 34

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.11.0.3

**Device:** Device on which the bug was encountered here
Motorola one action.

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by manabu-nakamura** [comment]
See https://developer.android.com/build/shrink-code.

**Comment by Joost-Jens-Luminis** [comment]
The proguard-rules.pro file wasn't used. Specifying the following in the .csproj worked:

```
	<ItemGroup>
		<ProguardConfiguration Include="proguard-rules.pro" />
	</ItemGroup>
```

**Comment by manabu-nakamura** [comment]
> However, when adding the entire BaseSlider class to progaurd I can see a lot more methods, just not the addOnChangeListener method I am looking for.

```
-keep class com.google.android.material.slider.BaseSlider {
  public void addOnChangeListener(**);
}
```
