### ISSUE TITLE
Can't find startIconDrawable 

### ISSUE THREAD

**Issue by doilio** [material-components/material-components-android#451]
I'm using a drawable as the startIcon. but it doesn't let me compile the code. it says this:

Android resource linking failed
C:\Users\Dowy\Desktop\BrigadaMovel\app\build\intermediates\incremental\mergeDebugResources\stripped.dir\layout\fragment_sign_in.xml:58: error: attribute startIconDrawable (aka com.example.brigadamovel:startIconDrawable) not found.
C:\Users\Dowy\Desktop\BrigadaMovel\app\build\intermediates\incremental\mergeDebugResources\stripped.dir\layout\fragment_sign_in.xml:82: error: attribute startIconDrawable (aka com.example.brigadamovel:startIconDrawable) not found.
error: failed linking file resources.

**Comment by MGaetan89** [comment]
Which version of the library are you using?

**Comment by doilio** [comment]
Version 1.0.0

**Comment by MGaetan89** [comment]
It has been added in version [1.1.0-alpha05](https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha05):
> Adding support for TextInputLayout start icon (2642ff2)

So you either need to use the latest alpha version (currently 1.1.0-alpha08) or wait for the next stable release.

**Comment by doilio** [comment]
Thank you. 
I will see what I can do, because at the moment I cannot use a version above 1.0.0 or else my layouts don't show. but that is being taken care of in another Opened Issue.
Cheers.

**Comment by SCMorgan** [comment]
@doilio 
As a workaround I've found you can use
**android:drawableLeft=""
android:drawableStart=""**

**Comment by doilio** [comment]
Yes @SCMorgan Thank you. 
I ended up installing Android Studio 3.5 RC1 working fine with it
