### ISSUE TITLE
[Dark Theme] Crash WebView api 21

### ISSUE THREAD

**Issue by rodrigmatrix** [material-components/material-components-android#455]
When dark theme is enabled on the app, the app crash when inflating the xml of a webview on api 21 or 22. On light theme, the webview works fine.
 Using the alpha07 version, already tried on alpha08

**Comment by dsn5ft** [comment]
Hello @rodrigmatrix, since webview is not part of the Material Android library, can you file a bug to the AndroidX team at https://issuetracker.google.com/issues/new?component=192731? Make sure to include the stacktrace and information about which androidx dependencies you are using.

**Comment by rodrigmatrix** [comment]
> Hello @rodrigmatrix, since webview is not part of the Material Android library, can you file a bug to the AndroidX team at https://issuetracker.google.com/issues/new?component=192731? Make sure to include the stacktrace and information about which androidx dependencies you are using.

Ok. Thanks for the feedback
