### ISSUE TITLE
Layout Issue when using Material Components

### ISSUE THREAD

**Issue by doilio** [material-components/material-components-android#457]
**Description:** 
The Layout Simply disappears on text Tab, On the Design Tab I can't interact with the Views that I have set(They are not clickable)
![111](https://user-images.githubusercontent.com/38020305/61593789-4a5cce00-abe4-11e9-937e-44452847f448.PNG)
![222](https://user-images.githubusercontent.com/38020305/61593792-53e63600-abe4-11e9-83d2-9e1363058f4c.PNG)

**Expected behavior:** 
I expect the Buttons to appear on my Layout

**Source code:** 
I was following the Material Design Codelab Shrine... As soon as I added this the problem started:
```
            <com.google.android.material.button.MaterialButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/next_button"/>
```

**Android API version:** 
29

**Material Library version:**
 1.1.0-alpha08

**Device:** 
N/A

**Comment by andrelabonte** [comment]
Thanks.
Duplicate being tracked as 
https://issuetracker.google.com/issues/134566530
