### ISSUE TITLE
[ViewPager2] overScrollMode doesn't work

### ISSUE THREAD

**Issue by DavidZXY** [material-components/material-components-android#459]
**Description:** I want to disable fading that a viewPager has scroll to edges. Just like this: [https://stackoverflow.com/questions/27724923/remove-recyclerview-scroll-effects](). But it still exists. Actually, I don't know if it is a bug, maybe it shoule be a new feature.

**Expected behavior:** ViewPager2 looks like ViewPager with overScrollMode="never"

**Source code:**

        <androidx.viewpager2.widget.ViewPager2
            android:orientation="vertical"
            android:overScrollMode="never"
            android:id="@+id/main_container_view_pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        </androidx.viewpager2.widget.ViewPager2>

**Android API version:** Android API 29

**Material Library version:** implementation 'com.google.android.material:material:1.1.0-alpha08'

**Device:** Genymotion custom phone api 24

**Comment by sttimchenko** [comment]
@DavidZXY, why have you closed this bug? Have you found a solution?

**Comment by NikitaFrolovCR** [comment]
I have the same problems!

**Comment by DavidZXY** [comment]
ViewPager2 use RecyclerView to improve the performance，so--
private ViewPager2 mMainContainerViewPager; 
...
((RecyclerView)mMainContainerViewPager.getChildAt(0)).setOverScrollMode(RecyclerView.OVER_SCROLL_NEVER); @sttimchenko @NikitaFrolovCR

**Comment by mxalbert1996** [comment]
This issue should be reopened.
The solution mentioned above is no more than a workaround since it relies on a private member and will not work if there is any changes in the view hierarchy inside ViewPager2.
Disabling over-scroll is a common need and should not be as hacky as this.

**Comment by EhudPla** [comment]
@DavidZXY can you reopen? if not ill open a new issue

**Comment by DavidZXY** [comment]
@EhudPla @mxalbert1996  you are right.

**Comment by ymarian** [comment]
Hi ViewPager is not part of our lib. Please file the bug 

https://issuetracker.google.com/issues/new?component=561920
