### ISSUE TITLE
BaseTransientBottomBar should expose the ability to dismiss as a user action

### ISSUE THREAD

**Issue by SaidinWoT** [material-components/material-components-android#46]
It is presently impossible to dispatch a dismissal as anything other than `BaseCallback.DISMISS_EVENT_MANUAL` from a subclass of `BaseTransientBottomBar`. It makes sense that the `SnackbarManager` should be the sole source of truth for the timeout and consecutive events, and it is reasonable that the Behavior should manage swipe events, but subclasses other than `Snackbar` should be able to indicate that a user took some action.

The status quo forces other subclasses to provide another mechanism for identifying the intent of a manual dismissal, and makes `BaseCallback.DISMISS_EVENT_ACTION` only meaningful for `Snackbar`s, making its presence in the `BaseCallback` API questionable for anything other than backwards-compatibility.

**Comment by drchen** [comment]
Hi, can you provide more details about your use scenario? 

For example an example of the API you expect?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with more details.
