### ISSUE TITLE
MaterialButton Icon

### ISSUE THREAD

**Issue by davisoqt** [material-components/material-components-android#461]
There is some way to set the color of the button icon depending on the state of the button. It would be something like a <selector> but for the color of the icon?

**Comment by hardysim** [comment]
Have you tried a [ColorStateList](https://developer.android.com/reference/android/content/res/ColorStateList.html) as the color on your drawable? It should know about the state of the button automatically and select the corresponding color to tint the drawable.

Also see https://developer.android.com/guide/topics/resources/color-list-resource

**Comment by dsn5ft** [comment]
Agreed a ColorStateList is the right approach here. That's what we use for default Material Buttons:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/values/styles.xml#L42

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/color/mtrl_btn_text_color_selector.xml
