### ISSUE TITLE
Material Button adding spaces between letters on Lollipop

### ISSUE THREAD

**Issue by ahmaducg** [material-components/material-components-android#462]
In API 21, when using a custom font, the MaterialButton seems to be placing spacing between each letter. 

The font is not the problem, as in other Views such as the TextView, the letters are intact.

![image](https://user-images.githubusercontent.com/45195295/61709965-1b1b9d80-ad59-11e9-92c1-b799d8bf0db9.png)

**Comment by andrelabonte** [comment]
Hi,
You can override the MaterialButton letter spacing to achieve the desired result with this font. 
You should set `textAppearanceButton` in your theme to be a `TextAppearance` which sets `android:letterSpacing` to 0.

**Comment by PawankumarPK** [comment]
android:textAppearance=”?attr/textAppearanceBody1”

**Comment by PawankumarPK** [comment]
`android:textAppearance=”?attr/textAppearanceBody1”`

**Comment by aminekarimii** [comment]
Thanks @PawankumarPK, this solution is easier
