### ISSUE TITLE
[bottomsheet] do not remove corners when bottomsheet is not fully expanded

### ISSUE THREAD

**Issue by hrach** [material-components/material-components-android#463]
**Description:** 

Currently, when bottomsheet is in an expanded state and its content is wrapped (fitToContents) then the corners are animated to 0dp. This leads to quite unwanted behavior.

Screenshots attached from catalog app. (large shape corner size in settings required):

<details><summary>Screenshot:</summary>

![device-2019-07-13-121306](https://user-images.githubusercontent.com/284263/61170309-ca8d8e80-a567-11e9-9796-d00e3927c397.png)

</details>

**Expected behavior:** 

<details><summary>Screenshot:</summary>

![device-2019-07-13-121429](https://user-images.githubusercontent.com/284263/61170310-ceb9ac00-a567-11e9-9b18-60509acbda0b.png)

</details>

**Source code:** The catalog app.
**Android API version:** API 29
**Material Library version:** 1.1.0-alpha08
**Device:** Pixel 2

Also pull-requested #437

**Comment by Zeliret** [comment]
Yes, I believe it should not animate corners if fit contents = true but do that if we have fit contents = false only.

**Comment by ldjcmu** [comment]
Design wants this to continue to work as is.

Please see context from the PR here: https://github.com/material-components/material-components-android/pull/437#issuecomment-536668983
