### ISSUE TITLE
[Menu] android:editable is deprecated

### ISSUE THREAD

**Issue by LimeByte** [material-components/material-components-android#465]
**Description:**

In the [Menu docs](https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md#usage) it says to use `android:editable="false"` on the `AutoCompleteTextView` to disable user input which is marked as deprecated. Is there a replacement for this?

**Comment by Pramod-sj** [comment]
You can use this

android:focusable='false'
android:cursorVisible='false'

**Comment by dsn5ft** [comment]
The recommended way according to lint is to use `inputType` instead of `editable`, however we had issues with that approach that I believe are still being worked out. Once `editable` is officially removed, we will update our guidance.

**Comment by vkotovv** [comment]
@dsn5ft There are usages of `android:editable` in [this example](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/textfield/TextFieldExposedDropdownMenuDemoFragment.java) for TextFields also.
