### ISSUE TITLE
[ActionMode] Need to set icon tint

### ISSUE THREAD

**Issue by hardysim** [material-components/material-components-android#466]
How can I style the ActionMode? Especially it's color for the back and overflow-menu icon?

I'm using `Theme.MaterialComponents.DayNight.NoActionBar` which results in a white background with black text and icons at day and black background with gray text and icons at night.

Further investigation shows that the ActionMode uses `colorSurface` and `colorOnSurface` to tint text and icons (which sounds logical) but I need a way to set those colors *only for the ActionMode*.

I'm not able to apply `android:theme` to `actionModeStyle` to change those colors only for the ActionMode because a theme is only working when applies directly to the widget.

---

Is there a way to change the icon tint for the ActionMode? I can set the background and text-styles and even provide a custom back-icon but not the tint for the overflow icon.

It would be great if there is something like `actionModeDrawableTint` (and maybe `actionModeTextTint` as well) which gets applied to the ActionMode just like `actionModeBackground`.

**Comment by dsn5ft** [comment]
Hi @hardysim, ActionMode isn't part of the Material Android library. You can file a bug to the AppCompat team at:

https://issuetracker.google.com/issues/new?component=460343

Maybe they can add an `actionModeTheme`?

**Comment by hardysim** [comment]
I filed a bug some time ago: https://issuetracker.google.com/issues/139013358

It seems that they have finally fixed this and [it will be available in 1.3.0-alpha01](https://issuetracker.google.com/issues/139013358#comment16).
