### ISSUE TITLE
Material Companent Theme with NoActionBar

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [material-components/material-components-android#468]
When you use a NoActionBar, the status bar color is not affected by colorPrimaryVariant, so you have to use the older colorPrimaryDark.

I tried Light and DayNight NoActionBar. Both have the same issue.

**Comment by dsn5ft** [comment]
This is somewhat intentional. Since by default status bars are assumed to be a relatively dark color (the status bar text and icons are light by default),`colorPrimaryDark` is semantically a better fit; whereas `colorPrimaryVariant` could either be lighter or darker than `colorPrimary`.

**Comment by JavierSegoviaCordoba** [comment]
@dsn5ft I think it has no sense to keep using `colorPrimaryDark` if it is not appearing in Material Design guidelines. At least it should be added then in this page: https://material.io/design/color/#color-theme-creation

![image](https://user-images.githubusercontent.com/7463564/62393767-60b34400-b56b-11e9-86ae-4ea1fe9cd990.png)

**Comment by vbuberen** [comment]
Would like to revive the issue. The problem still exists - just today spent ~40 minutes trying to find what is missing in my setup and why `colorPrimaryVariant` is ignored. Please update info on https://material.io/design/color/#color-theme-creation page.
