### ISSUE TITLE
Missing files not added to git

### ISSUE THREAD

**Issue by BrunoVieiraAndrade** [material-components/material-components-android#47]
There are some missing files in the project which were not added to git.
![missing_files](https://user-images.githubusercontent.com/3969714/32571677-6a157896-c4af-11e7-9658-de6197a74489.png)

**Comment by dsn5ft** [comment]
I believe those are AppCompat files, which are not part of this library.

**Comment by BrunoVieiraAndrade** [comment]
You are right. Forgive me for my trivial mistake. By that time I wasn't able to realize that.
Thank you anyway!
