### ISSUE TITLE
[BadgeDrawable] cannot use a custom typeface

### ISSUE THREAD

**Issue by vahid-m** [material-components/material-components-android#471]
I've used the badge drawable for bottom navigation view. unfortunately, the typeface of the number badge cannot be changed and also it does not obey the `fontFamily `attr that was defined in AppTheme. Please add an API to use text appearance or style for it.

**Comment by DanielClayton** [comment]
@dsn5ft @wcshi any updates on this one? Thanks!

**Comment by wcshi** [comment]
This is blocked by a similar issue on Chip, which also doesn't respond to the `fontFamily` attribute. https://issuetracker.google.com/issues/127453566

**Comment by MHKalantarian** [comment]
Changing `android:textAppearance` font family doesn't affect the number text, it only affects the text after the `app:maxCharacterCount` but the textSize applies to both. It's really confusing

   ```
 <style name="Widget.MyTheme.Badge" parent="Widget.MaterialComponents.Badge">
        <item name="android:textAppearance">@style/TextAppearance.MyTheme.Badge</item>
    </style>

    <style name="TextAppearance.MyTheme.Badge" parent="TextAppearance.MaterialComponents.Badge">
        <item name="android:textSize">10sp</item>
        <item name="fontFamily">@font/font_fa</item>
        <item name="android:fontFamily">@font/font_fa</item>
    </style>
```

**Comment by asajadi84** [comment]
I also have a similar problem which I explained more in https://stackoverflow.com/questions/64753364/change-badgedrawable-typeface-in-android but it's basically as you described.

**Comment by KhunHtetzNaing** [comment]
It's still 2022?

**Comment by anthony-fresneau-kiplin** [comment]
This bug is still present, is it planned to be fixe?

**Comment by pokerfaceCmy** [comment]
fuck google

**Comment by imhappi** [comment]
You can now use `app:badgeTextAppearance`
