### ISSUE TITLE
[TabLayout] From 1.1.0-alpha07 · Tab text does not render

### ISSUE THREAD

**Issue by DavidEdwards** [material-components/material-components-android#474]
**Description:** After upgrading to alpha07 / alpha08, the text in my TabLayout does not render any more.

![example-not-working](https://user-images.githubusercontent.com/1585923/62053777-94633680-b218-11e9-9967-6b691d273b12.png)

**Expected behavior:** Text should render

![example-working](https://user-images.githubusercontent.com/1585923/62053784-97f6bd80-b218-11e9-89d1-49ee853ce5f6.png)

**Android API version:** 17 (JB 4.2.2)

**Material Library version:** 1.1.0-alpha07 / 1.1.0-alpha08

**Device:** Emulator of Nexus 5X

**Comment by ldjcmu** [comment]
We'll need a sample app to repro this. Tabs appear to be working on all Android versions for us in alpha10.
