### ISSUE TITLE
[CoordinatorLayout/SwipeRefreshLayout] Scrolling issue with a specific mix of code (notch related?)

### ISSUE THREAD

**Issue by NitroG42** [material-components/material-components-android#478]
**Description:** 
The issue is that the appbar is not scrolling with the content with the following combination :
- A SwipeRefreshLayout
- A CoordinatorLayout with normal behavior
- A translucent status bar
- A Xiaomi Mi8 Phone (might be present on other phones, maybe with notch ?)

With this, the appbar is not scrolling either at the beginining (and never come back), either after a quick scroll.

See the [video](https://streamable.com/t73tr) (you need to download it if the browser doesn't display it).

Without translucent status bar, it works, on other devices, it works, without a swiperefreshlayout, it works.

**Expected behavior:** The scroll shouldn't block the appbar

**Source code:** https://github.com/NitroG42/MaterialComponentBugs see SwipeRefreshBugXiaomiActivity

**Android API version:** 28

**Material Library version:** 1.1.0-alpha09, happened on previous version too

**Device:** The issue was reproduced *ONLY* on the XIaomi Mi8 (which has a notch). It can probably happens on others phone but it's the only one with a notch we have.

**Comment by drchen** [comment]
Hi, I apologize that this issue slipped our attention for a long while. Is this still reproducible?

Also the video link is expired, will you be able to provide a new recording so we can better understand the issue?

**Comment by NitroG42** [comment]
Unfortunatelly It's been a long time, I'll close it for now and maybe I or someone else will reopen if it occurs again. (it was so specific too so... we'll see !)
