### ISSUE TITLE
[DatePicker] No way to setup default date when opening

### ISSUE THREAD

**Issue by hrach** [material-components/material-components-android#481]
**Description:** It seems there is no way to setup default date (date-range) when using new material dialog picker.

**Expected behavior:** Able to setup default date.

**Source code:** 

```kotlin
MaterialDatePicker.Builder.dateRangePicker()
     .build()
     .show(supportFragmentManager)
```

**Material Library version:** `1.1.0-alpha09`

**Comment by ldjcmu** [comment]
We will definitely add this. We're currently deciding what public API we can commit to with the internal DateSelector class. Either we'll support this via the use of that class or we'll add a method directly to the builder.

Thanks for the usage feedback.

**Comment by ldjcmu** [comment]
Fixed in the next release.
