### ISSUE TITLE
[TextInputLayout] Support prefix/suffix text

### ISSUE THREAD

**Issue by thevoiceless** [material-components/material-components-android#482]
**Is your feature request related to a problem? Please describe.**
Per the "Prefix and suffix text" section at https://material.io/design/components/text-fields.html material text fields should be able to display non-editable text before/after the user's input.
![Screen Shot 2019-07-30 at 11 23 05 AM](https://user-images.githubusercontent.com/1574103/62151406-7b609100-b2bd-11e9-9166-29a7aae7f647.png)

**Describe the solution you'd like**
I have no strong opinions on the API, but I would consider the minimum-viable functionality to be setting a start-justified prefix text or end-justified suffix text. It would be nice to have the ability to set the start/end gravity of the user's input text (ex: the "55/100" example in the screenshot above), but I wouldn't consider it essential. I assume that the hint/label animation would be omitted when prefix/suffix text is provided, otherwise the visibility will need to be coordinated.

**Describe alternatives you've considered**
* Using a `TextWatcher` and calculating start/end indices manually, as well as setting spans for text color. Ridiculously tedious and error-prone.
* Setting a `TextDrawable` on the left of the `TextInputEditText`. Causes the label to be misaligned when the field is focused, and also overrides the drawable tint color:
<img width="360" alt="Screen Shot 2019-07-30 at 11 23 51 AM" src="https://user-images.githubusercontent.com/1574103/62151662-148fa780-b2be-11e9-817e-91d8ee0948d0.png">

* Setting a `TextDrawable` as the `startIconDrawable` on the `TextInputLayout`. Does not line up with the user's cursor, padding must be set, and also overrides the drawable tint color:
<img width="353" alt="Screen Shot 2019-07-30 at 11 24 30 AM" src="https://user-images.githubusercontent.com/1574103/62151759-4d2f8100-b2be-11e9-800a-6b442589841f.png">

* Subclassing `TextInputLayout` and using a custom `CollapsingTextHelper`. Tedious and fragile (uses reflection); see https://stackoverflow.com/a/39568320
* Using a custom view and ignore `TextInputLayout` entirely. Doable but would like to avoid trying to duplicate the exact styles and positions of views, since we use `TextInputLayout` in many places and want a uniform experience.

**Comment by charleston10** [comment]
I need this.. pls

**Comment by beckettsimmons** [comment]
@thevoiceless Seems feasible. I wouldn't mind putting the time in to add this feature. But is there any way to double-check that a pull request for it would actually be accepted? (Has it already been rejected? Any other technical issues? Is there a feature roadmap for v1.1.0?)

**Comment by cketcham** [comment]
We currently don't have plans for this, but we would be interested in a PR. It might also be useful to put together a high level proposal of how you think it will work for us to look at before you put a lot of work into it as well.

**Comment by thevoiceless** [comment]
I ended up using https://github.com/HITGIF/TextFieldBoxes for my particular use case, but it has its own peculiarities (rounded boxes, default implementation has a ripple on the view, custom methods for setting text watchers, etc). The prefix/suffix functionality appears to work as desired, though. I haven't delved into the implementation, but perhaps it could be used as inspiration.

@cketcham this is uncharted territory for me personally; what exactly does a "proposal" entail?

**Comment by leticiarossi** [comment]
We've decided to start working on support for suffix/prefix on text fields

**Comment by beckettsimmons** [comment]
Sounds good! Will probably end up cleaner than me mucking around the code.

**Comment by ed-george** [comment]
@leticiarossi Amazing news, is there any eta or projected release this will be a part of?

**Comment by ldjcmu** [comment]
This should be in the current alpha.

**Comment by ed-george** [comment]
I have not see these changes present in 1.1.0-beta01 or the [docs](https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout#attr_TextInputLayout_prefixText) for the changes that were committed

**Comment by ldjcmu** [comment]
Should be this commit 6e5ddcfb0ee4e8fb9ff96a5c818c3f5c0593482b. I don't think it's in the beta, but will be in releases afterwards.

**Comment by shashankpsingh** [comment]
When it gonna be include in alpha or beta. Don't get the update in latest beta.

**Comment by ed-george** [comment]
@ldjcmu can this be re-opened? It might be dev-done but it isn't available within the library

**Comment by jnathania** [comment]
> @ldjcmu can this be re-opened? It might be dev-done but it isn't available within the library

agree

**Comment by artnest** [comment]
Released in [1.2.0-alpha01](https://github.com/material-components/material-components-android/releases/tag/1.2.0-alpha01).

**Comment by devgen90** [comment]
seeing the alignment issues when using the prefixtext. Has this been addressed already?

**Comment by AramKocharyan** [comment]
Can you add the gravity attribute for the suffix? In my case, I need the suffix to be positioned at the end of the typed text, not the view. 
For example: 2,250.00 $

**Comment by AlexRU18** [comment]
> Can you add the gravity attribute for the suffix? In my case, I need the suffix to be positioned at the end of the typed text, not the view.
> For example: 2,250.00 $

Did you solve this?
