### ISSUE TITLE
[Elevation] Provide a utility for getting the parent absolute elevation of a view

### ISSUE THREAD

**Issue by alexjlockwood** [material-components/material-components-android#483]
Currently when creating a custom view w/ elevation, it is required to override `onAttachedtoWindow()` like this:

```
override fun onAttachedToWindow() {
    super.onAttachedToWindow()

    MaterialShapeUtils.setParentAbsoluteElevation(this)
}
```

This only works if your custom view uses a `MaterialShapeDrawable` though. If you can't use `MaterialShapeDrawable` (and want to use `ElevationOverlayProvider` instead), there's no built-in way to get the parent absolute elevation (which you will need to compute the overlay color).

It seems like internally MDC uses the following method to compute parent absolute elevation:

```
  /**
   * Returns the absolute elevation of the parent of the provided {@code view}, or in other words,
   * the sum of the elevations of all ancestors of the {@code view}.
   */
  public static float getParentAbsoluteElevation(View view) {
    float absoluteElevation = 0;
    ViewParent viewParent = view.getParent();
    while (viewParent instanceof View) {
      absoluteElevation += ViewCompat.getElevation((View) viewParent);
      viewParent = viewParent.getParent();
    }
    return absoluteElevation;
  }
```

My current workaround is to copy/paste this method into our own codebase... but was thinking maybe it'd be something that MDC could provide as its own public method instead. 🤷‍♂

**Comment by dsn5ft** [comment]
Thanks for filing, will think about the best way to expose this utility.
