### ISSUE TITLE
[Material Components] No work colors of Style.xml

### ISSUE THREAD

**Issue by Okami-x-Senpai** [material-components/material-components-android#486]
I found the problem: The problem is when I use **implementation 'com.google.android.material:material:1.1.0-alpha09'** and now all my colors stop working, but when I go back to **implementation 'com.google.android.material:material:1.0.0'** my application returns to normal.

Using **com.google.android.material: material:1.1.0-alpha09**

![IMG_20190722_112514](https://user-images.githubusercontent.com/47009141/61651808-e1bd3200-ac73-11e9-9dad-1585846cb78f.jpg)

Using **com.google.android.material: material:1.0.0**

![IMG_20190722_112606](https://user-images.githubusercontent.com/47009141/61651867-fe596a00-ac73-11e9-9686-1981f5d487ce.jpg)

**This is the code of the Style.xml:**

```
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        ........
    </style>
```

**This is the code of the buttons shown in the screenshot:**

```

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="10dp"
                android:orientation="horizontal">

                <com.google.android.material.button.MaterialButton
                    style="@style/Widget.MaterialComponents.Button"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginEnd="5dp"
                    android:layout_weight="5"
                    android:padding="10dp"
                    android:text="@string/main_login_btn_title_register"
                    android:textAppearance="@style/TextAppearance.MaterialComponents.Button"
                    android:textColor="@color/colorTextNormal"
                    app:backgroundTint="@color/colorObjects" />

                <com.google.android.material.button.MaterialButton
                    style="@style/Widget.MaterialComponents.Button"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="5"
                    android:padding="10dp"
                    android:text="@string/main_login_btn_title_log_in"
                    android:textAppearance="@style/TextAppearance.MaterialComponents.Button"
                    android:textColor="@color/colorTextNormal" />

            </LinearLayout>

```

Even create another project and use **com.google.android.material:material:1.1.0-alpha09** and likewise, colors like the colorAccent stop working and among other colors more.

**Comment by dsn5ft** [comment]
Hi @Okami-x-Senpai, I think there are two main issues I see:

1) It looks like your app is dark themed but you are inheriting from a light theme (`Theme.MaterialComponents.Light.DarkActionBar`). Changing that to a dark theme (`Theme.MaterialComponents`) should fix the text colors, as long as there are no other overrides happening in the app.
2) Material Buttons now use `colorPrimary` instead of `colorAccent` by default.

**Comment by Okami-x-Senpai** [comment]
I understand, but for example to some types of buttons the **click effect does not work** .

**How would you change the color of the buttons then?**  **How can I solve the error of the click effect of the buttons?** 

**Could you give me an example of a style.xml please to take a reference**  of how to use the style.xml in the new versions of **Material Components** .
