### ISSUE TITLE
[TextInputLayout] Setting END_ICON_PASSWORD_TOGGLE programmatically does not hide password by default.

### ISSUE THREAD

**Issue by quentin41500** [material-components/material-components-android#491]
**Description:** When using `endIconMode` with `END_ICON_PASSWORD_TOGGLE` programmatically, the password is visible by default, when it should be hidden.

**Expected behavior:** Password should be hidden when using the property programmatically, like it was happening when using `isPasswordVisibilityToggleEnabled`.

**Source code:** 
``` 
// MyCustomEditText.kt
class MyCustomEditText @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : TextInputLayout(context, attrs, defStyleAttr) {

    init {
        inflate(context, R.layout.edit_text, this)
        input.inputType = InputText.TYPE_TEXT_VARIATION_PASSWORD
        endIconMode = END_ICON_PASSWORD_TOGGLE
}
```

```
// edit_text.xml
<com.google.android.material.textfield.TextInputEditText xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/input"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```

**Android API version:** 28

**Material Library version:** 1.1.0-alpha09

**Device:** Pixel 3 XL - Emulator

**Comment by kouthao** [comment]
@quentin41500 So did you find any solution to hide the password by default on **TextInputLayout**?

**Comment by raheemadamboev** [comment]
Have you resolved the issue?
