### ISSUE TITLE
BaseTransientBottomBar shouldAnimate() returns false on Nexus 5 with Accessibility off

### ISSUE THREAD

**Issue by pavlospt** [material-components/material-components-android#5]
### Overview

 - Tried to create a custom Snackbar using the BaseTransientBottomBar. Although the ContentViewCallback had animations for the `animateContentOut()` and `animateContentIn()` methods, the `shouldAnimate()` method was always returning `false` on my Nexus 5. After some debugging I found out that `AccessibilityManager.isEnabled()` was returning true, even though Accessibility settings were off.

### Reproduction steps

 - Extend `BaseTransientBottomBar` and `BaseTransientBottomBar.ContentViewCallback` and add animations for the content inside `animateContentOut()` and `animateContentIn()`, on a Nexus 5.

### Version number

 - Support Library version 25.1.0

### Operating system and device

- Nexus 5, Android Version: 6.0.1, Build Number: M4B30X

**Comment by ataulm** [comment]
`AccessibilityManager.isEnabled()` will return true if any accessibility service (even the ones that implement AccessibilityService as a hack to fix platform specific bugs, e.g. Action Launcher) is enabled, even if currently suspended (e.g. TalkBack).

Can you confirm in Settings > Accessibility that everything is turned off?

**Comment by pavlospt** [comment]
Hello, 

Yes that was my first check, I even enabled Talkback and then re-disabled it, so that I could trigger a stale situation, in case this was what was happening, but it stayed the same. Every Accessibility setting is off.

**Comment by chrisbanes** [comment]
If your device is reporting accessibility as being turned on, then we deal with it as so. Working as intended.

**Comment by pavlospt** [comment]
@chrisbanes Is there any way to check why it reports Accessibility on, when clearly none of the Accessibility settings are on?

**Comment by Anthonyeef** [comment]
My device is the same( `AccessibilityManager.isEnabled()` return true, so SnackBar come out without animation). But I can see that Google Photos still have snackBar with animation. How is that possible? Is there any work around?
