### ISSUE TITLE
Release Design support lib from this repo.

### ISSUE THREAD

**Issue by yogurtearl** [material-components/material-components-android#50]
Design support lib 27.0.2 doesn't appear to contain the changes in this repo.

Design support lib releases should come from the latest stable code in this repo.

**Comment by kenyee** [comment]
+1

**Comment by hzsweers** [comment]
master build has been broken for over a month too

**Comment by derekcz1991** [comment]
any progress?

**Comment by dsn5ft** [comment]
Thanks for checking in. Stay tuned for a release coming in the next couple of months!

**Comment by hzsweers** [comment]
Couple of **months**?? This library is over a year out of date, and the iOS version releases seemingly biweekly.

**Comment by KennyGoers** [comment]
😞

**Comment by hzsweers** [comment]
So it's actually coming up on a couple months now

**Comment by kenyee** [comment]
can I intern for a little while and get a CI/CD pipeline working? ;-)

**Comment by gongshoudao** [comment]
+1

**Comment by dsn5ft** [comment]
The Design Library has been released from this repo as of `28.0.0-alpha1` - https://developer.android.com/topic/libraries/support-library/revisions.html#28-0-0-alpha1
