### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

### ISSUE THREAD

**Issue by piaomiao8179** [material-components/material-components-android#501]
CRASH TYPE SUMMARY
LOCATION
com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal()
EXCEPTION
java.lang.NullPointerException
MESSAGE
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

**Comment by cketcham** [comment]
Hi,

Could you attach a full stacktrace so we can see what's going on?

**Comment by aagrawal2** [comment]
I am seeing this issue quite frequently on Android emulator. 
Here is the bug report attached.
[bugreport-sdk_gphone_x86-OSM1.180201.031-2019-09-11-16-35-11.zip](https://github.com/material-components/material-components-android/files/3603111/bugreport-sdk_gphone_x86-OSM1.180201.031-2019-09-11-16-35-11.zip)

**Comment by cketcham** [comment]
@aagrawal2 I don't see the stacktrace in that report. Could you provide the stacktrace from logcat?

**Comment by ldjcmu** [comment]
I've checked the setStateInternal function and there is no longer any possible place for this NPE to occur since this commit de43cd1eccbc7c2d56f2999fb6b96f7811c86a2c. Assuming you were on 1.0.0-stable and closing. If you're seeing the issue on 1.1.0-beta01 please provide a full stack trace.
