### ISSUE TITLE
[Snackbar] Gradle lint task fails inconsistently: WrongConstant

### ISSUE THREAD

**Issue by erikhuizinga** [material-components/material-components-android#504]
**Description:**

`./gradlew lint` would fail on Material v1.1.0-alpha07 and before, and Android Studio would show a lint error for `Snackbar.make(view, "Replace with your own action", BaseTransientBottomBar.LENGTH_LONG)` with a `WrongConstant` error. (`Snackbar.LENGTH_LONG` should be used instead.)

On v1.1.0-alpha08 and v1.1.0-alpha09 `./gradlew lint` fails sometimes (about half the time) and the Android Studio lint error is no longer shown. This also happens on v1.2.0-alpha03.

**Expected behavior:**

The Gradle lint task fails or succeeds consistently and Android Studio's linter reflects this success/failure.

**Source code:**

```kotlin
Snackbar.make(view, "Replace with your own action", BaseTransientBottomBar.LENGTH_LONG)
```

**Android API version:**

28

**Material Library version:**

OK: v1.1.0-alpha-07 and earlier
Not OK: v1.1.0-alpha08, v1.1.0-alpha09, v1.2.0-alpha03

**Device:**

N/A

**Comment by khaykov** [comment]
I'm experiencing this one with beta01

**Comment by sam4444** [comment]
@erikhuizinga How can I prevent this issue for now until not fixed?

**Comment by erikhuizinga** [comment]
@sam4444 don't use a version greater than v1.1.0-alpha-07.

**Comment by vincent-paing** [comment]
+1

**Comment by vincent-paing** [comment]
Still happening in 1.2.0 alpha-01

```
Error: Must be one of: BaseTransientBottomBar.LENGTH_INDEFINITE, BaseTransientBottomBar.LENGTH_SHORT, BaseTransientBottomBar.LENGTH_LONG or value must be ≥ 1 (was 0) [WrongConstant]
      Snackbar.make(requireView(), errorMessage, Snackbar.LENGTH_LONG).show()
```
                                                 ~~~~~~~~~~~~~~~~~~~~

**Comment by erikhuizinga** [comment]
This is still an issue with Material v1.2.0-alpha03.

**Comment by npike** [comment]
Seems to not be an issue on alpha05.

**Comment by kevinvillalobosGL** [comment]
This seems to be happening during certain builds for alpha05 and alpha06. I found a workaround for these versions, by changing the Build Variant and forcing the project to re-index everything and then run the lint (or assemble) task again.

**Comment by romaopedro** [comment]
@kevinvillalobosGL how did you fix the problem? I already did: Refresh Gradle Dependencies, Reimport Gradle Project, Clear cache and restart, delete build folder, clear project, rebuild project. The problem persists.

**Comment by kevinvillalobosGL** [comment]
> @kevinvillalobosGL how did you fix the problem? I already did: Refresh Gradle Dependencies, Reimport Gradle Project, Clear cache and restart, delete build folder, clear project, rebuild project. The problem persists.

The issue persists, especially on our CI, changing the Build Variant is only a workaround to force the the re-index and clean build, but still could happen. So we decided to disable the abortOnError:

`  android {
      lintOptions {
          abortOnError false
      }
  }`

We do have a custom Lint check on our UnitTest so we are keeping this disabled until we get a working solution from the Material Library.

**Comment by romaopedro** [comment]
@kevinvillalobosGL I forgot to mention that I did that as well, didn't work either.

Didn't remind to use the abortOnError, it will work, thanks. 
Meanwhile, I'm using a different workaround. I add this annotation to the method with the crashing code. 
`@SuppressLint("WrongConstant")`

The suppress can be added to the lint.xml file, but in my case, I use the Snackbar.LENGTH_INFINITE in just one place of the project.

**Comment by dsn5ft** [comment]
Hello all, what versions of Android Studio and the Android Gradle Plugin are you using to reproduce these errors?

**Comment by romaopedro** [comment]
@dsn5ft using AS 3.6.2. Didn't test with 3.6.3 that I've just updated. Gradle plugin 3.6.2.

**Comment by azaricstefan** [comment]
Issue is still present in material library version 1.3.0* and 1.2.0* (* means all minor versions).

Android API version 29|28
Gradle version: 4.0.1

Solved it by disabling the warning WrongConstant, but this is not good.

Please resolve this issue.

**Comment by josephyanks** [comment]
+1 we are also experiencing this issue on v1.2.0

Target: 29, Gradle 4.0.1

**Comment by chiel99** [comment]
+1 same issue
material version: 1.2.0
API: 29
Gradle 4.0.1

**Comment by ataraxus** [comment]
+1 same issue
material version: 1.1.0, 1.2.0
API: 29
Gradle 4.0.1

**Comment by LokmaneKrizou** [comment]
Any updates to resolve this issue?

**Comment by nmhung** [comment]
Same here.
Looking forward to updating on this issue.

**Comment by drchen** [comment]
This seems only happening on a certain gradle version? 

We removed @IntDef from the @Duration definition in https://github.com/material-components/material-components-android/commit/3cf23e4bf151bf37ff81859ae83301926c3b0dc1

Can you help check if this also solves the lint issue reported here?

**Comment by erikhuizinga** [comment]
I can't reproduce this in my old project, back when I had this issue and reported it. That project had too many dependencies back then that are now obsolete, which makes it impossible to build it at all. Currently the project depends on Material 1.4.0 and that doesn't seem to have this issue. I tried 20 builds without suppressing the lint error and they all passed.

**Comment by drchen** [comment]
Thank you so much for the confirmation. If that's the case I guess the issue was solved even before the commit I linked. : )

**Comment by azaricstefan** [comment]
I confirm that issue is not present in 1.5.0 version. Hope this info helps someone.
