### ISSUE TITLE
[CoordinatorLayout] Snackbar not shown above FAB

### ISSUE THREAD

**Issue by hardysim** [material-components/material-components-android#505]
### Edit

Just found out that `Snackbar` is now supposed to be shown **above** the FAB. See https://material.io/design/components/snackbars.html#placement

![image](https://user-images.githubusercontent.com/3737512/62530817-84171100-b841-11e9-8cf8-6baf1575c106.png)

---

### Original Issue

**Description:**
I'm using a FAB and went edge-to-edge. To have the FAB respect the window insets, I've updated its margin with `systemWindowInsetBottom`. So far, so good.

Now, when showing a snackbar, the FAB moves up thanks to `CoordinatorLayout`. But because it now has much more margin now, it moves up too much.

**Expected behavior:**
When the snackbar is showing, `systemWindowInsetBottom` need to be `0` because the snackbar becomes the new bottom anchor for the FAB.

**Source code:**
I'm using the following function to update the margin of the FAB (`fab.addSystemWindowInsetToPadding(bottom = true)`):

```kotlin
fun View.addSystemWindowInsetToMargin(
    left: Boolean = false,
    top: Boolean = false,
    right: Boolean = false,
    bottom: Boolean = false
) {
    val (initialLeft, initialTop, initialRight, initialBottom) =
        listOf(marginLeft, marginTop, marginRight, marginBottom)

    ViewCompat.setOnApplyWindowInsetsListener(this) { view, insets ->
        view.updateLayoutParams {
            (this as? ViewGroup.MarginLayoutParams)?.let {
                updateMargins(
                    left = initialLeft + (if (left) insets.systemWindowInsetLeft else 0),
                    top = initialTop + (if (top) insets.systemWindowInsetTop else 0),
                    right = initialRight + (if (right) insets.systemWindowInsetRight else 0),
                    bottom = initialBottom + (if (bottom) insets.systemWindowInsetBottom else 0)
                )
            }
        }

        insets
    }
}
```

**Screenshots:**
With the insets respected for the margin of the FAB, it looks like this (content flows behind the navigation bar, FAB is correctly above it):

![image](https://user-images.githubusercontent.com/3737512/62526975-93df2700-b83a-11e9-8a1f-e79b869e9ef4.png)

With the snackbar showing, the FAB gets moved up / anchored to the top of the snackbar instead of the bottom of the screen.

![image](https://user-images.githubusercontent.com/3737512/62527058-be30e480-b83a-11e9-8660-2e8cf598a196.png)

**Android API version:**
Android Q Beta 5

**Material Library version:**
1.1.0-alpha09

**Device:**
Pixel 3

**Comment by hardysim** [comment]
Just found out that `Snackbar` is now supposed to be shown **above* the FAB:

**Comment by hardysim** [comment]
I found some other issues mentioning this:

- https://issuetracker.google.com/issues/122163315
- https://issuetracker.google.com/issues/122450686

As well as an API to anchor the snackbar. Seems like this is what `CoordinatorLayout` should use:

- https://github.com/material-components/material-components-android/blob/master/docs/components/Snackbar.md#anchoring-a-snackbar

**Comment by gabrielemariotti** [comment]
Just use the method `setAnchorView()`.  
For example:
`snackbar.setAnchorView(fab);`

**Comment by drchen** [comment]
Yes, please use  setAnchorView(fab) to make fab be the anchor view of snackbar. 

CoordinatorLayout is not part of Material library and it should not have dependency on Material library.
