### ISSUE TITLE
[MaterialButtonToggleGroup] cannot contain 5 Buttons or more

### ISSUE THREAD

**Issue by AnneBullert** [material-components/material-components-android#510]
**Description:** 
If I add more than four Buttons to MaterialButtonToggleGroup, not all of them are shown, even if the space is sufficient. Instead in the end I see three dots.
I'm not sure, if this is the desired behaviour, if so, it would be necessary to add an option to turn it off.
[Screenshot](https://drive.google.com/open?id=1dn3Hn6l6LOnEOac2Yr3MhpbP_3N5CNCp)

**Expected behavior:** 
I need to add and display more than four buttons.
[Screenshot](https://drive.google.com/open?id=1dc52uzKcGgqZHL5mtK7rc4lIMrjSk0BN)

**Material Library version:** 1.1.0-alpha09

**Device:** Pixel 2, Pixel, Nexus 10, Nexus S

**Comment by ymarian** [comment]
I don't expect this to happen anymore. MaterialButtonToggleGroup now behaves like a LinearLayout. Feel free to re-open attaching a sample app if this is still an issue.

**Comment by surajpheudin** [comment]
Have you solved this problem? I am getting the same issue.
![image](https://user-images.githubusercontent.com/78244892/168538274-af93b24e-152e-48df-a940-6b552bc630f5.png)

![image](https://user-images.githubusercontent.com/78244892/168538447-e6d7b237-1e99-4f5c-aabe-d51297b7bf6e.png)
