### ISSUE TITLE
MaterialButton (and other), make it possible to change inset programmatically.

### ISSUE THREAD

**Issue by RoarGronmo** [material-components/material-components-android#512]
**Is your feature request related to a problem? Please describe.**
Trying to add materialbuttons on a gridlayout programmatically, where button appearance should not have any spaces. As the button layout is appearing (as default when creating a buttom programmatically) the inset on top/bottom can't be changed after creation, there aren't any methods to change the insets.

**Describe the solution you'd like**
Make it possible to change the insets programmatically, the same way like iconPadding, cornerRadius etc...

**Describe alternatives you've considered**
Copy paste the source code of material button and change it there (it isn't preferable at all).

**Additional context**
Added a screenshot to clarify problem
![Screenshot_1565340562](https://user-images.githubusercontent.com/11217296/62767317-b2405f00-ba94-11e9-9469-55d7b05271e8.png)

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

RG

**Comment by MGaetan89** [comment]
Can't you change those values with the `insetLeft`, `insetTop`, `insetRight` and `insetBottom` attributes?

**Comment by RoarGronmo** [comment]
in XML ofcourse, but if you add those buttons dynamically (inside the code) there are no insetLeft, insetTop, insetRight and insetBottom member functions. There is cornerRadius though.

Like:

      
        for(i in 0 until total)
        {
            
            val button = MaterialButton(this.context)

            button.cornerRadius=0

            button.setAutoSizeTextTypeUniformWithConfiguration(
                5,
                40,
                1,
                TypedValue.COMPLEX_UNIT_SP)


            val j=i+1

            button.text = "$j"
            button.setTag(i)

            button.setOnClickListener {
                Toast.makeText(this.context,"${it.tag} clicked",Toast.LENGTH_LONG).show()

                it.visibility = View.INVISIBLE
            }
           
            buttons.add(button)

            gridLayout?.addView(button)

        }

There are simply no `setInsets`, `leftInset`, `rightInset`, `startInset` or `topInset` i.e.   

RG

**Comment by LouisCAD** [comment]
I'm affected by this as well.

**Comment by nevdokimof** [comment]
Any updates on this?

**Comment by ymarian** [comment]
f837cb76abebd9a53642e8798c7e4b4bc8da2eca

**Comment by LouisCAD** [comment]
Can we get this backportes to version 1.2.0 as it's currently in RC?

**Comment by ymarian** [comment]
@LouisCAD unfortunately not, we cannot add features/APIs. Next alpha or snapshot releases only for now

**Comment by keyboardr** [comment]
The referenced commit only adds vertical inset support and doesn't support setting horizontal insets.
