### ISSUE TITLE
What's the differences between androidx and material-components-android?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [material-components/material-components-android#513]
I had use androidx for a few months.Now I find the library.I have a question:

What's the differences between androidx and material-components-android?

I use androidx, that means I can use androidx to replace all support libraries,and what's the features of the current library?

**Comment by EdricChan03** [comment]
This library is Material Components for Android, replacing the now-deprecated Android Design Support Library.

AndroidX is the newer version of the now-deprecated Android Support Libraries.
