### ISSUE TITLE
[TextInputLayout] Disabled widget state doesn't use color from ColorStateList

### ISSUE THREAD

**Issue by tluksa** [material-components/material-components-android#515]
**Description:** Setting ColorStateList for TextInputLayout attributes "android:textColorHint" or "hintTextColor" doesn't set color in disabled state.

**Expected behavior:** These attributes should utilize different colors from ColorStateList.

**Material Library version:** 1.1.0-alpha09

**Comment by maxkolotilin** [comment]
Observe the same issue

**Comment by ldjcmu** [comment]
We agree we want to fix this. Duplicate of #593.
