### ISSUE TITLE
[CollapsingToolbarLayout] The Toolbar not stop scrolling when collapsed

### ISSUE THREAD

**Issue by rcaceiro** [material-components/material-components-android#517]
**Description:** After change the Scrolling Activity project that Google provides in Android Studio and updating the package com.google.android.material:material to version 1.1.0-alpha09 I noticed that when I scroll the toolbar after collapsed it bounces.

**Expected behaviour:** I made a little video here https://youtu.be/57QKM4-9NFc

**Source code:** 
`<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        tools:context=".ScrollingActivity">

    <com.google.android.material.appbar.AppBarLayout
            android:id="@+id/app_bar"
            android:fitsSystemWindows="true"
            android:layout_height="@dimen/app_bar_height"
            android:layout_width="match_parent"
            android:theme="@style/AppTheme.AppBarOverlay">

        <com.google.android.material.appbar.CollapsingToolbarLayout
                android:id="@+id/toolbar_layout"
                android:fitsSystemWindows="true"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:toolbarId="@+id/toolbar"
                app:layout_scrollFlags="scroll|exitUntilCollapsed"
                app:contentScrim="?attr/colorPrimary">

            <androidx.appcompat.widget.Toolbar
                    android:id="@+id/toolbar"
                    android:layout_height="?attr/actionBarSize"
                    android:layout_width="match_parent"
                    app:layout_collapseMode="pin"
                    app:popupTheme="@style/AppTheme.PopupOverlay"/>

        </com.google.android.material.appbar.CollapsingToolbarLayout>
    </com.google.android.material.appbar.AppBarLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>`

**Android API version:** Minimun: 27, target:29, Android Emulator: 28

**Material Library version:** com.google.android.material:material:1.1.0-alpha09 

**Device:** Pixel 3XL Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ArturKnaus** [comment]
This issue is still present in version `1.1.0-beta01`. It looks like it only happens when the toolbar is dragged, because the collapsing works fine if the content is scrolled.

I also provided two short gifs to illustrate this behavior.


**Toolbar dragging** 
![20191009_144613](https://user-images.githubusercontent.com/3846729/66483982-687cf080-eaa6-11e9-830a-b02e8cfd621d.gif)

--------
**Content**
![20191009_144550](https://user-images.githubusercontent.com/3846729/66484077-9c581600-eaa6-11e9-8063-002a56ccb2b2.gif)

**Comment by frolovpv** [comment]
<com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="scroll|exitUntilCollapsed|snap">

**Comment by G-ManiX** [comment]
Hi, 

Was this issue resolved?

Seems the bug is still there.

Thanks & Regards

**Comment by drchen** [comment]
I think this has been fixed. Please check with the latest library version. Feel free to reopen the issue if it's still reproducible.
