### ISSUE TITLE
[FloatingActionButton] Translucent background visual bug

### ISSUE THREAD

**Issue by josephbnb** [material-components/material-components-android#518]
**Description:** I can't find a way to set a translucent background color to either FloatingActionButton or ExtendedFloatingActionButton.

Setting `app:backgroundTint` to a translucent color will show a weird shape in the middle (or behind) the button.

Setting `android:alpha` to the button itself will result in making the inner icon (or text) translucent, which is not the intended behaviour.

**Code and screenshots:** 

```
app:backgroundTint="#4DFFFFFF"
```

![tint alpha](https://user-images.githubusercontent.com/40384699/63014352-a090fa00-be8e-11e9-9b60-b4aad212cf7c.png)

```
app:backgroundTint="#FFFFFF"
android:alpha="0.3"
```

![fab alpha](https://user-images.githubusercontent.com/40384699/63014365-a8e93500-be8e-11e9-959a-3e9748895254.png)

**Comment by ymarian** [comment]
This is the way native shadows work. They are known to not play nicely if the content that has a shadow has is not opaque.
