### ISSUE TITLE
[Dark theme] System defined default font size not respected in Dark Theme

### ISSUE THREAD

**Issue by kenshin171** [material-components/material-components-android#522]
When switching to dark theme, the font sizes all textViews are not adjusted according to the system default font size.

Steps to reproduce
Step 1) Go into system settings -> display and change the font size to be the largest size
Step 2) Go to app, current in light mode, font size is reflected in UI correctly respecting the enlarged default font size set in system settings
Step 3) Call ```AppcompatDelegate.setdefaultnightmode(AppCompatDelegate.MODE_NIGHT_YES)```
Step 4) Observed that the font size is not the correct size as per system settings. The size is the size set in the display settings.

Expected behavior: Font size should be the same as in light theme.

Source code: AppcompatDelegate.setDefaultNightMode()

Android API version: <= Android 7.1.1 (api level 25)

Material Library version: 1.1.0-alpha09

Device: 
Asus zenfone 2 (Andorid 5.0)
nexus 6 (Android 7.1.1)
nexus 5 (Android 6.0.1)

Remarks:
I do not know if this is an androidx appcompat issue or a material components issue, i have filed a similiar bug report here https://issuetracker.google.com/issues/139327209

**Comment by jgbirk** [comment]
@kenshin171 we are running into the same issue. Got any workaround for the problem?

**Comment by keneliar** [comment]
@kenshin171 @jgbirk It's the problem with AppCompat 1.1.0
Downgrading version to 1.1.0-rc01 solves the problem

**Comment by jgbirk** [comment]
Weird, I downgraded to 1.1.0-rc01 and the same problem was happening. The only way to solve was to override applyOverrideConfiguration.

```
override fun applyOverrideConfiguration(overrideConfiguration: Configuration) {
        if (VERSION.SDK_INT in 21..25) {
            resources.configuration.setTo(overrideConfiguration)
        }

        super.applyOverrideConfiguration(resources.configuration)
    }```

**Comment by ldjcmu** [comment]
Closing as it appears related to AppCompat
