### ISSUE TITLE
[DatePicker] Allow for a string to be specified for the title text

### ISSUE THREAD

**Issue by EdricChan03** [material-components/material-components-android#523]
**Is your feature request related to a problem? Please describe.**

Currently, `MaterialDatePicker.Builder` only has support for specifying a string resource for the title text. However, some may prefer to provide a hardcoded string instead.

**Describe the solution you'd like**

Add a `setTitleText` method which allows for a `String` to be specified.

**Describe alternatives you've considered**

Currently, the only other method is to use `setTitleTextResId` which allows for a string resource ID to be specified.

**Additional context**

Context: I was looking around in the source code of the date picker and discovered that a String could not be specified for the picker's title.

**Comment by ldjcmu** [comment]
This is being added within the week and will be in the next release.

**Comment by ldjcmu** [comment]
Fixed in the next release.
