### ISSUE TITLE
[TextInputLayout] Hiding already hidden error causes helper text to be hidden

### ISSUE THREAD

**Issue by chantw** [material-components/material-components-android#525]
**Description:** Calling `TextInputLayout.setError(null)` without checking `TextInputLayout.getError()` for **null** will cause the helper text to show only for a brief amount of time (< 1s) before disappearing again.

**Expected behavior:** Calling `TextInputLayout.setError(null)` consecutively is expected to only hide the error only and not the helper text as well.

**Source code:**
```java
final TextInputLayout inputLayout = findViewById(R.id.input_email);
inputLayout.setHelperText("Email");
inputLayout.setError("Email required");
inputLayout.setError(null);
inputLayout.setError(null);
```

**Android API version:** 28

**Material Library version:** 1.1.0-alpha09

**Device:** Asus Zenfone Max Pro (M1)

**Comment by AlessandroAgneti** [comment]
I had the same problem and I found as solution this one:
- don't set the error to null but set helperText directly
 I did so in kotlin:
- textInputLayoutPassword.error = null
and i solved with:
- textInputLayoutPassword.helperText = resources.getText(R.string.login_error_lower_length_password)

**Comment by chantw** [comment]
@AlessandroAgneti I haven't tried this yet, I will give it a try soon. ;)

**Comment by azol** [comment]
I have the same issue. Seems lake a bug to me. As for me -- should be reopened. I expect that currently displayed helper text is not affected by setting error to null in any way. Simply do nothing Don't even animate. It's not ok that the result of setting error to null is hiding currently displayed helper text. Material Library version: 1.1.0-beta01

**Comment by chantw** [comment]
Let's hear what the team has for this as well.

**Comment by VictorHarry** [comment]
Having this problem too, don't know how to solve it...

**Comment by surajnavkudkar** [comment]
Having the same problem. Any update on the same?

**Comment by matpag** [comment]
I've the same problem. 
This is definitely a bug, I will take a look at this ASAP

**Comment by leticiarossi** [comment]
Currently looking into this! Seems like it's something happening in the IndicatorViewController logic

**Comment by matpag** [comment]
@leticiarossi I've pushed a WIP PR
