### ISSUE TITLE
[MaterialButton] Change button insets programmatically especially since they don't default to 0dp

### ISSUE THREAD

**Issue by quentin41500** [material-components/material-components-android#526]
**Is your feature request related to a problem? Please describe.**
This might be more of question than a request, but I'm not sure why we would want inset at the top and bottom by default. I understand that the property could be of use, but I end up removing the inset by default in all my apps through a style like so:

```
<item name="android:insetTop">0dp</item>
<item name="android:insetBottom">0dp</item>
```

- Could you provide more info for having inset having a value greater than `0dp` by default?
- Is the inset related to elevation and shadow?

**Describe the solution you'd like**
Set the default inset of buttons to `0dp`.

**Describe alternatives you've considered**
As an alternative, and if the inset is related to the shadow from the elevation, maybe the `UNELEVATED` style could reset the inset to 0dp?.

**Comment by simekadam** [comment]
I +1 this. It's especially inconvenient to have default nonzero insets when it's impossible to adjust it at runtime. Either remove the default values, or allow us adjust it from code.

**Comment by ldjcmu** [comment]
The insets exist as part of ensuring the touch targets are large enough for mobility impaired users with the default style, so we're unlikely to change them. We recommend at least 48dp as a minimum touch target.

That said, it seems completely reasonable to want to change them programmaticly, so I'll update the issue to reflect that.

**Comment by quentin41500** [comment]
Another option I could think of is to default `minHeight` to `48dp`, if that's an accessibility requirement. I understand this might be a breaking change, but I'm curious about the rational for this.

**Comment by ldjcmu** [comment]
You're right that we could have done that approach (it is what we do with checkboxes for example), but - as you mentioned - it is breaking, so we're unlikely to do so at this point. Definitely good to consider as an option especially if other breaking changes come up.

**Comment by SubhrajyotiSen** [comment]
Has there been any progress on this?

**Comment by tunjid** [comment]
👋 Please this is still and issue

**Comment by egorikftp** [comment]
Any updates?

**Comment by ueen** [comment]
+1

**Comment by mehdi-satei** [comment]
+1

**Comment by LouisCAD** [comment]
It seems this issue is not actually resolved since only vertical insets can be set in version 1.3 alpha for now.

Asked why on the commit here: https://github.com/material-components/material-components-android/commit/f837cb76abebd9a53642e8798c7e4b4bc8da2eca#commitcomment-42116013

**Comment by LouisCAD** [comment]
Can you address my comment @ymarian and/or @dsn5ft, please?

**Comment by dsn5ft** [comment]
@LouisCAD as you can see in the description, this issue was mainly talking about vertical insets, because those are the ones that we have to set to non-zero values by default for `MaterialButton`:

https://github.com/material-components/material-components-android/blob/3178b9d540725dc1cab6b5b4194a88659cbde0d7/lib/java/com/google/android/material/button/res/values/styles.xml#L37-L38

If you are interested in setting horizontal insets programmatically, please file a separate issue.

**Comment by LouisCAD** [comment]
Done, feature requested in #1770.
