### ISSUE TITLE
how to set round corners for popup menu?

### ISSUE THREAD

**Issue by Zed-Rustam** [material-components/material-components-android#529]
I want to make the rounded corners for the popup menu, but I can’t find how to do it

**Comment by paolovalerdi** [comment]
You have to override the `<item name="popupMenuStyle">@style/Popup.Theme</item>`.
Adding the following: 
`<style name="Popup.Theme">
<item name="android:popupBackground">@drawable/popup_menu_background</item>    </style>
`  
popup_menu_background.xml
`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">

    <solid android:color="?colorBackgroundFloating" />
    <corners android:radius="@dimen/corner_radius_medium" />

</shape>
`

But I'm pretty sure that corner family will affect this as well.

**Comment by phamquocdai123** [comment]
I have faced the same issue, I tried to implement it as instructed https://m2.material.io/components/menus/android#theming-menus but these corners are not working. Does anyone have any suggestions?
