### ISSUE TITLE
[MaterialButton] Icon animated selector doesn't play if setting text

### ISSUE THREAD

**Issue by samruston** [material-components/material-components-android#531]
**Description:** If an animated state selector is used as the icon on the MaterialButton then the animation will play between states, but only if not also setting the text on the button (or anything that triggers updateIconPosition).

**Expected behavior:** The animation of the icon should play whether or not the text is set. This is the behaviour of AppCompatButton/Button.

**Source code:** Attached sample app demonstrating the issue.
[issue.zip](https://github.com/material-components/material-components-android/files/3531136/issue.zip)

**Android API version:** 28

**Material Library version:** 1.1.0-alpha09

**Device:** Emulator

**Comment by wcshi** [comment]
Hi @samruston i ran your sample, there's only one MaterialButton, could add an AppCcompatButton/Button to demonstrate your expected behavior?

**Comment by samruston** [comment]
@wcshi Sure thing. Attached with another button.

[issue 2.zip](https://github.com/material-components/material-components-android/files/3535536/issue.2.zip)

**Comment by wcshi** [comment]
Could not pull in https://github.com/material-components/material-components-android/pull/533 because of the following cases:
icon size changing
iconLeft changing

Suggestion: adding a flag, `needsIconUpdate`,  to `updateIcon()`

**Comment by samruston** [comment]
Sorry for the delay. Added suggested needsIconUpdate flag. Tested changing gravity, size, tint and icon. All working fine
