### ISSUE TITLE
[TextInputLayout] Feature Request: set boxStrokeColor with ColorStateList by code

### ISSUE THREAD

**Issue by scholt** [material-components/material-components-android#534]
**Is your feature request related to a problem? Please describe.**
We want to have an outline field visualize an error independently from the build in error display handling. The outline of the field should change from grey to red.

**Describe the solution you'd like**
I want to set the boxStrokeColor by code but it only accepts a Color which is not used when the field doesn't have focus. It seems to be possible to set a ColorStateList by xml but not by code.

**Describe alternatives you've considered**
Optimally it would be possible to define an error Color (or ColorStateList) and enable the error just for the field outline.

**Comment by krossovochkin** [comment]
Probably related to #524

**Comment by ldjcmu** [comment]
We're tracking these changes at #593
