### ISSUE TITLE
I have problem with my android gradle

### ISSUE THREAD

**Issue by ialanoudk** [material-components/material-components-android#538]
Android resource linking failed
C:\Users\ialan\Downloads\Countmedoun\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
C:\Users\ialan\Downloads\Countmedoun\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
C:\Users\ialan\Downloads\Countmedoun\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:3988: error: resource android:attr/fontVariationSettings not found.
C:\Users\ialan\Downloads\Countmedoun\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:3989: error: resource android:attr/ttcIndex not found.
error: failed linking references.

**Comment by ymarian** [comment]
For reference this is an issue setting an older compileSdkVersion. Setting to 28/29 should work
