### ISSUE TITLE
[MaterialDialog] Use MaterialDialog with Navigation Component

### ISSUE THREAD

**Issue by seanghay** [material-components/material-components-android#540]
As far as I know, we only have `MaterialAlertDialogBuilder` for creating a new `MaterialDialog`. However, when I want to add `MaterialDialog` to navigation by using XML 

```kotlin
class MyDialogFragment: DialogFragment() {
   ....
}
```

```xml
<navigation>
    <dialog name=".MyDialogFragment" />
</navigation>
``` 
The dialog that I get is not a new `MaterialDialog`, it is the old one.

Is there any way I can have something like `MaterialDialogFragment`?

**Comment by MiSikora** [comment]
Yeah, actually `MaterialAlertDialogBuilder` returns regular `androidx.appcompat.app.AlertDialog`. It would be great to have inheritable `MaterialDialog`. And I guess fragment version as well.

**Comment by shlusiak** [comment]
I second this wish. Right now an `AppCompatDialogFragment` creates a normal `AppCompatDialog`, but only the shiny new `MaterialAlertDialogBuilder` sets the background to a `MaterialShapeDrawable` while the normal `Dialog` only gets the colorSurface.

As a result, the dialog in dark theme will be plain black, because it doesn't get the elevation overlay. 

Any chance we can get a `MaterialDialog`, which sets the background to a `MaterialShapeDrawable` and then possibly `MaterialDialogFragment`? I assume the latter is trivial.

It seems a bit odd that only AlertDialogs are supported, but not normal Dialogs. Are they becoming deprecated?

**Comment by seanghay** [comment]
> I second this wish. Right now an `AppCompatDialogFragment` creates a normal `AppCompatDialog`, but only the shiny new `MaterialAlertDialogBuilder` sets the background to a `MaterialShapeDrawable` while the normal `Dialog` only gets the colorSurface.
> 
> As a result, the dialog in dark theme will be plain black, because it doesn't get the elevation overlay.
> 
> Any chance we can get a `MaterialDialog`, which sets the background to a `MaterialShapeDrawable` and then possibly `MaterialDialogFragment`? I assume the latter is trivial.
> 
> It seems a bit odd that only AlertDialogs are supported, but not normal Dialogs. Are they becoming deprecated?

Well, I think there should be a way that we can extend `AppCompatDialogFragment` and override some several methods to achieve it.

I do have my own way of achieving it but it doesn't seem to be right at all. It would be nice if the team gives us some ideas on how to get it done and why it is not done in the beginning.

**Comment by Bhullnatik** [comment]
I wrote a blog post about the solution I used for this issue: https://dev.to/bhullnatik/how-to-use-material-dialogs-with-dialogfragment-28i1

I'm not sure my implementation is valid and cover all cases, but I'd be happy to submit a PR and correct it if there is some interest ✌️

**Comment by seanghay** [comment]
This is how I achieved it.
```kotlin
abstract class BaseDialogFragment : AppCompatDialogFragment() {

    private var dialogView: View? = null

    @LayoutRes
    abstract fun dialogLayout(): Int


    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return dialogView
    }

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        val v = LayoutInflater.from(context).inflate(dialogLayout(), null, false)
        this.dialogView = v
        return MaterialAlertDialogBuilder(context)
            .setView(v)
            .create()
    }
}
```

**Comment by seanghay** [comment]
There is my new solution to this:
https://gist.github.com/seanghay/7e5dfab6bdf1f23d7cf394cfa7d067be

**Comment by drchen** [comment]
I think wrapping MaterialAlertDialogBuilder in a DialogFragment is the right way to achieve this. : )

I'll close the issue. Feel free to reopen it if you have more questions regarding this.
