### ISSUE TITLE
[BottomNavigationView] Allow to set more then 5 menu items

### ISSUE THREAD

**Issue by palatin** [material-components/material-components-android#543]
Hello, I understand that for correct displaying, limitation of items in bottom navigation view were set. But why is it hardcoded and final? For example, for tablet in landscape mode I want to have 7 items. Can you please allow to override max menu items.

**Comment by antonkovalyov351** [comment]
Up

**Comment by rmasarovic** [comment]
Hi i have same problem and only one way how to do it is fork code...

**Comment by drchen** [comment]
We have design concerns around allowing more items than 5. If you really need that, you can extend BottomNavigationView and override getMaxItemCount() to provide a different value than 5.

**Comment by NoorTech98** [comment]
same problem in bottom navigation view 
solved the solution item code
