### ISSUE TITLE
[MaterialCardView] High Memory usage on MaterialShapeDrawable

### ISSUE THREAD

**Issue by kenshin171** [material-components/material-components-android#545]
**Description:** OOM exception will happen when using MaterialCardview which uses MaterialShapeDrawable under the hood on lower api level devices. Has this issue been addressed in the latest alpha09 version? here is the corresponding issue in the issuetracker https://issuetracker.google.com/issues/122413115

**Expected behavior:** no OOM

**Android API version:** api 19

**Material Library version:** 1.1.0-alpha09

**Device:** LG g2

**Comment by wcshi** [comment]
thank you for reporting this issue, as you stated, it's already in public issue tracker, so I will be closing this as a duplicate.

**Comment by wcshi** [comment]
Hi @kenshin171 
Are you able to reproduce the OOM consistently? Does your app have one or many instances of MaterialCardview?

**Comment by wcshi** [comment]
Please comment on the public issue tracker so all debugging information is in one place, thank you!
