### ISSUE TITLE
[Catalog] Theme Switcher overrides black status bar color in night mode

### ISSUE THREAD

**Issue by guillaume-tgl** [material-components/material-components-android#547]
**Is your feature request related to a problem? Please describe.**
The status bar and navigation bar colors are not changed when switching to dark mode.

**Describe the solution you'd like**
Both colors should be set to black.

**Describe alternatives you've considered**
I can manually set these colors in my code but I feel like this should be handled by the DayNight theme.

If that sounds reasonable, I can draft a PR.

**Comment by wcshi** [comment]
Could you please provide a screenshot of what you seeing?

**Comment by dsn5ft** [comment]
Also can you let us know which version of the library you are using?

**Comment by guillaume-tgl** [comment]
I used the Catalog app, set the primary color to purple, the secondary color to yellow and here is what I have for Day and Night modes:

![Screenshot_20190830-115120_Material Components Catalog](https://user-images.githubusercontent.com/2244170/64011863-cf5cd080-cb1c-11e9-96a1-2d1ad08b3fd7.jpg)
![Screenshot_20190830-115131_Material Components Catalog](https://user-images.githubusercontent.com/2244170/64011864-cf5cd080-cb1c-11e9-90c3-390a513845b2.jpg)

I think it would be nicer to have a black status and navigation bar in Night mode.

**Comment by dphans** [comment]
@guillaume-tgl You are right! I don't know next version solve this issue or not. Currently, I'm following manual way:

I've call method below in `onCreate` of activity:

```kotlin
private fun negotiateDeviceDarkMode() {
    val isNightMode = this@BaseActivity.resources.configuration.uiMode
        .and(Configuration.UI_MODE_NIGHT_MASK) == Configuration.UI_MODE_NIGHT_YES
    val typedValue = TypedValue()

    this@BaseActivity.window.addFlags(
        WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS
    )

    if (isNightMode) {
        this@BaseActivity.theme
            .resolveAttribute(android.R.attr.colorBackground, typedValue, true)
        window.statusBarColor = typedValue.data
        window.navigationBarColor = typedValue.data
    } else {
        this@BaseActivity.theme
            .resolveAttribute(android.R.attr.colorBackground, typedValue, true)
        window.navigationBarColor = typedValue.data
        this@BaseActivity.theme
            .resolveAttribute(R.attr.colorPrimaryDark, typedValue, true)
        window.statusBarColor = typedValue.data
    }
}
```

**Comment by dsn5ft** [comment]
The Material DayNight themes in the library itself do switch to use black for the status bar in night mode.

- [Light Theme](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L92) (`design_default_color_primary_dark`)
- [Dark Theme](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L27) (`design_dark_default_color_primary_dark`)
- DayNight Theme inherits from Light or Dark Theme depending on night mode

This issue is only with how the [Catalog's theme switcher](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/themeswitcher/res/values/themes_overlays_primary.xml) works by overriding the baseline `colorPrimaryDark`.

**Comment by guillaume-tgl** [comment]
Okay for the status bar. I didn't see that the status bar color referenced `colorPrimaryDark` by default.
But what about the navigation bar: wouldn't it be nice to have it black in the Dark theme and white in Light Theme?

**Comment by dsn5ft** [comment]
Material's opinion, and the Android Framework/AppCompat behavior, is that the navigation bar should be black by default, regardless of Light or Dark Theme. But I think this could also vary depending on the device manufacturer.

It's up to the client developer to further customize the `android:navigationBarColor` if it makes sense for the app's brand, color scheme, and content.

**Comment by kyze8439690** [comment]
Below code solve my problem

```xml
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
        <!-- Customize your theme here. -->
        <item name="android:navigationBarColor">?attr/colorSurface</item>
</style>
```

**Comment by drchen** [comment]
Will close the issue as WAI, as @dsn5ft explained above.
