### ISSUE TITLE
[CheckBox] Ripple should be the opposite color when pressed

### ISSUE THREAD

**Issue by naropf** [material-components/material-components-android#554]
The default behavior of an Android ripple component is: When a check box is checked, the ripple is gray.  When a check box is cleared, the ripple is blue.

The expected behavior is when the user is activating an action, the color must be the activator color (blue), and when the user is deactivating an action, the color must be gray.

Material Design shows the following video with the second behavior: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F11blol1QWU53hulHKMeS7qi4Cc_FJxOdy%2Fbehavior-selected-user-order.mp4

Which behavior (from UX view) is correct, the default of the component or the video?

**Comment by ikim24** [comment]
The second (expected and shown in the Material Design spec) is correct from a Material Design UX view.

The color should be (using the colors you provided)
checked + pressed = grey (to match the resulting unchecked color)
checked + focused = blue (activator color)
checked + hovered = blue (activator color)
unchecked + pressed = blue (activator color)
unchecked + focused = grey
unchecked + hovered = grey

**Comment by drchen** [comment]
Closing the issue as WAI.
