### ISSUE TITLE
[MaterialCardView] invisible CardView's body when long press on bottomNavigationView's items

### ISSUE THREAD

**Issue by RezaKardoost** [material-components/material-components-android#555]
**Description:**

![device-2019-08-30-195219](https://user-images.githubusercontent.com/15872932/64032648-246e0600-cb60-11e9-98f9-4f25212659c9.png)

this is a simple app with :

"material bottomNavigationView"
"material CardView with an ImageView in its Body"
"ImageView"

after long press one of  bottomNavigationView's items , body of CardView become invisible!!!
I test it with 2 devices "android Oreo and P" and only in android P this bug occurred

![device-2019-08-30-195331](https://user-images.githubusercontent.com/15872932/64033425-b62a4300-cb61-11e9-915c-7b022069d503.png)

**Source code:** 

```
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity">

        <com.google.android.material.bottomnavigation.BottomNavigationView
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:menu="@menu/bottom_nav_menu"
            app:labelVisibilityMode="labeled"/>

        <ImageView
            android:id="@+id/imageView"
            android:layout_width="200dp"
            android:layout_height="200dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/photo" />

        <com.google.android.material.card.MaterialCardView
            android:layout_width="200dp"
            android:layout_height="200dp"
            android:layout_marginTop="24dp"
            app:cardCornerRadius="20dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.502"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/imageView" >

            <ImageView
                android:layout_width="200dp"
                android:layout_height="200dp"
                app:srcCompat="@drawable/photo" />
        </com.google.android.material.card.MaterialCardView>
    </androidx.constraintlayout.widget.ConstraintLayout>
```

**Android API version:**  28

**Material Library version:** 1.1.0-alpha9

**Device:** Google Pixel 3XL (android P - genymotion device)

**Comment by wcshi** [comment]
Please provide a sample app that we can use to reproduce this behavior.

**Comment by RezaKardoost** [comment]
https://github.com/RezaKardoost/CardView-Bug

**Comment by RezaKardoost** [comment]
> Please provide a sample app that we can use to reproduce this behavior.

https://github.com/RezaKardoost/CardView-Bug

**Comment by wcshi** [comment]
Hi @RezaKardoost i ran your code using a Pixel 3XL emulator running 28 in AS and was not able to reproduce your bug. Are you able to reproduce it using a non-genmotion device?

**Comment by RezaKardoost** [comment]
Hi @wcshi .
I test it again with AS virtual device and a real device running 28 . fortunately I could not reproduce it again. It is genymotion device bug
