### ISSUE TITLE
[Chip] Expandable chips from material specs

### ISSUE THREAD

**Issue by rafid059** [material-components/material-components-android#557]
From the [specs][4] (Chips > Input Chips > Behaviour > Expandable):

>Input chips can expand to show more information or options

![][3]

Is there any plans to add this for android? Or is there any way to currently implement it?

Related stackoverflow posts: [1][1] [2][2]

  [1]: https://stackoverflow.com/questions/53485498/morph-chip-to-dialogfragment-in-android
  [2]: https://stackoverflow.com/questions/54417854/how-to-create-expandable-entry-chips
  [3]: https://i.stack.imgur.com/8cM5l.gif
  [4]: https://material.io/components/chips/

**Comment by andrelabonte** [comment]
Hi,  Thanks for the request. 
We are currently planning future work and a potential solution to this request is being considered. 
No timeline to share at the moment.

**Comment by guger** [comment]
This does probably not directly concern MDC but such a "expanded chip" can be achieved with a `DialogFragment`. The problem here is that this animation is not possible using a `DialogFragment`.

**Comment by k0shk0sh** [comment]
@guger this could be achieved using PopupWindow.

**Comment by wcshi** [comment]
We support this "expandable" behavior using Material transitions. Please see the exactly behavior in Reply. 

https://github.com/material-components/material-components-android-examples/blob/develop/Reply/app/src/main/java/com/materialstudies/reply/ui/compose/ComposeFragment.kt#L141-L195
Here's a codelab that walks you through it:
https://codelabs.developers.google.com/codelabs/material-motion-android#7

We have no plans to update Chip to support this behavior out of the box.
