### ISSUE TITLE
TextInputLayout not respecting defined colors

### ISSUE THREAD

**Issue by KelvinPac** [material-components/material-components-android#566]
**Description:** 
The TextInputLayout does not respect defined colors. I am using a filled text input layout but the floating label, underline and cursor colors, when focused is always the colorPrimary even after trying to change it. I have tried setting the color of choice using colorControlActivated but it doesn't work

**Android API version:** Android API version 28

**Material Library version:** Material Android Library version1.1.0-alpha09

**Device:** Samsung Galaxy A52

**Comment by ldjcmu** [comment]
Add this to the things for #593. Dup #593
