### ISSUE TITLE
Missing release note 1.1.0-alpha10 

### ISSUE THREAD

**Issue by b95505017** [material-components/material-components-android#567]
https://github.com/material-components/material-components-android/compare/1.1.0-alpha09...bf8b3e9337b86dbffb4b7dfbf59ece555991feb6

**Comment by dsn5ft** [comment]
We will be writing these soon =)

**Comment by afohrman** [comment]
Good catch :)

Release notes can now be found [here](https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha10).
