### ISSUE TITLE
[CardView] Deprecate the Android X card view library

### ISSUE THREAD

**Issue by alexjlockwood** [material-components/material-components-android#569]
I assume that the Android X card view library will never support elevation overlays and that all card view related development will go into material-components-android instead.

Would be good to erase any confusion between the two and deprecate the existing Android X card view library: https://developer.android.com/jetpack/androidx/releases/cardview

Alternatively, if for some reason there is a need to keep the two separated, it would be good to document the differences between the two somewhere since I don't think beginning Android developers will understand the difference.

**Comment by okarakose** [comment]
So, in this case `cardViewStyle` attribute can be removed and we can only need to use `materialCardViewStyle`. Am I correct ?

**Comment by ldjcmu** [comment]
This isn't really realistic for a lot of uses. Thanks for believing ours is the best!

**Comment by ldjcmu** [comment]
We might be able to add a lint check to encourage users of the library to use the Material version.

**Comment by alexjlockwood** [comment]
@ldjcmu I posted one here that you could use as a starter: https://github.com/material-components/material-components-android/issues/550#issuecomment-530463270
