### ISSUE TITLE
[DatePicker] landscape doen't have ok/cancel buttons

### ISSUE THREAD

**Issue by hrach** [material-components/material-components-android#571]
**Description:** I can't see any ok/cancel buttons in datepicker dialog in landscape.

![image](https://user-images.githubusercontent.com/284263/64441013-52f26080-d0cd-11e9-860d-5940d4a3f946.png)

**Expected behavior:** See ok/cancel buttons.
**Source code:** Compiled Catalog demo.
**Android API version:** Android 29
**Material Library version:**  1.1.0-alpha10
**Device:** Pixel 2

**Comment by ldjcmu** [comment]
Hi hrach, thanks for the note.

We're currently looking into how we want to fix this; whether we make the middle pane scrollable or change some of the dimensions of resources so it all squeezes to fit. The difficult part is that we're not currently taking variable system inset sizes into account.

I'll update as soon as we have a fix.

**Comment by ldjcmu** [comment]
We have a fix for this that makes the middle pane scrollable. It should be in the next release.
