### ISSUE TITLE
[Menus] Exposed Dropdown Menu cut off in dialog

### ISSUE THREAD

**Issue by TheBrokenRail** [material-components/material-components-android#575]
**Description:**
When a a Exposed Dropdown Menu is displayed in a dialog, parts of it are cut off, and are therefore unselectable.

**Expected behavior:**
This is the highest you can scroll:
![Screenshot_1567900652](https://user-images.githubusercontent.com/17478432/64481434-09c40e80-d1aa-11e9-8a8b-4f302da2f42c.png)

**Source code:**
```java
AlertDialog.Builder builder = new MaterialAlertDialogBuilder(context);
...
@SuppressLint("InflateParams") View layout = inflater.inflate(R.layout.dialog_name_program, null);
...
ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(context, R.array.file_types, android.R.layout.simple_spinner_dropdown_item);
spinner.setAdapter(adapter);
```
```xml
    <com.google.android.material.textfield.TextInputLayout
            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="@string/file_type_str">

        <AutoCompleteTextView
                android:id="@+id/spinner"
                android:editable="false"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                tools:ignore="Deprecated,LabelFor" />

    </com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** 28

**Material Library version:** 1.1.0-alpha10

**Device:** Android Emulator

I found this while transitioning my app to material Components.

**Comment by TheBrokenRail** [comment]
Any updates or workarounds?

**Comment by ldjcmu** [comment]
Hi TheBrokenRail,

No updates on a fix, but you may be able to work around the issue by changing R.attr.backgroundInsetTop to a smaller value. My guess is that the inset, which design asked to be larger, is clipping the dialog. You may also be able to wrokaround this issue by limiting the maxHeight of the Exposed Dropdown menu.

**Comment by TheBrokenRail** [comment]
I have tried setting backgroundInsetTop to 0 in both my main theme and popupTheme, yet the issue persists. Also the issue does not occur on my Galaxy S7 running Oreo.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by leticiarossi** [comment]
testing out today on version 1.7.0-beta01 I do not observe any cutting off of the popup list of the dropdown menu. Will close this issue, but if any problems are still observed please reopen and provide a sample app where the issue can be seen. Thanks!
