### ISSUE TITLE
[Action Bar] Menus have black text on grey background

### ISSUE THREAD

**Issue by abn-volk** [material-components/material-components-android#576]
**Description:** When using the Material dark theme, action bar menus have black text on grey background.

![Screenshot_1567911872](https://user-images.githubusercontent.com/1829147/64482715-ce692480-d229-11e9-8b45-2f215a933021.png)

This is  IMO the same bug as #384, and definitely a bug in the library itself.

**Expected behavior:** This is the behaviour when using `Theme.AppCompat`.

![Screenshot_1567911944](https://user-images.githubusercontent.com/1829147/64482716-d0cb7e80-d229-11e9-85d3-d86763790099.png)

**Source code:** https://github.com/abn-volk/md-action-bar-bug. All I did was:
* Create a sample app from the Empty Activity template in Android Studio 3.5
* Add MDC: `implementation 'com.google.android.material:material:1.1.0-alpha10'`
* Add a menu file
* Change the theme to `Theme.MaterialComponents`:
```
<style name="AppTheme" parent="Theme.MaterialComponents">
```

**Android API version:** Any version

**Material Library version:** 1.1.0-alpha10 (has been this way for several versions, I think from alpha07)

**Device:** Android Emulator

**Comment by ikim24** [comment]
resolved by https://github.com/material-components/material-components-android/commit/7bcd5f606e3c6ffe912204b4e35fc1b75d023a0b
