### ISSUE TITLE
[ExtendedFloatingActionButton] Should not doge snackbars

### ISSUE THREAD

**Issue by PaulWoitaschek** [material-components/material-components-android#578]
According to the material design guide lines, the `ExtendedFloatingActionButton` should not doge a snackbar. Instead the snackbar should be shown above the `ExtendedFab`.
See https://material.io/components/snackbars/#behavior

https://github.com/material-components/material-components-android/blob/bf8b3e9337b86dbffb4b7dfbf59ece555991feb6/lib/java/com/google/android/material/floatingactionbutton/ExtendedFloatingActionButton.java#L807-L809

**Comment by ldjcmu** [comment]
You should use the setAnchorView API on the snackbar to do this for now. We're looking into trying to build this by default.
