### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by Winghin2517** [material-components/material-components-android#58]
Hello

The current build is failing. Here is the error message when I load this into Android Studio. Please can you fix. Thanks

Error:Project with path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/bottomsheet' could not be found in project ':lib'.

Consult IDE log for more details (Help | Show Log)

**Comment by coofeeing** [comment]
me too...did you solved?

**Comment by YmlMark** [comment]
Also having this problem.

**Comment by SheepYang1993** [comment]
add code in setting.gradle
```include ':lib:java:android:support:design:bottomsheet'
include ':lib:java:android:support:design:dialog'
include ':lib:java:android:support:design:floatingactionbutton'
include ':lib:java:android:support:design:typography'
include ':lib:java:android:support:design:color'
include ':lib:java:android:support:design:card'

**Comment by PrashantShendage** [comment]
Okay Thanks

**Comment by dsn5ft** [comment]
Closing as duplicate of #51
