### ISSUE TITLE
[Tabs] Make Tab's view public

### ISSUE THREAD

**Issue by guger** [material-components/material-components-android#581]
**Description:** Material Design Study "Rally" shows the following customized `TabLayout`:
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1SkeVD6imJA_MwjipNR-DbNh1xw4au9yy%2F02-rally-tabs.mp4

**Expected behavior:** Customizing the tabs is only possible if the tab's `view` is public.

**Source code:** https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/tabs/TabLayout.java#L1888

**Material Library version:** 1.1.0-alpha10

**Comment by ldjcmu** [comment]
The TabView being public is in the public API, so it will stay public as desired.

**Comment by guger** [comment]
But it's package public, so I cannot access it even when subclassing TabLayout.

Android Studio Error: 

> Type TabLayout.TabView is inaccessible in this context due to: public/*package*/ open inner class TabView : LinearLayout defined in com.google.android.material.tabs.TabLayout

**Comment by ldjcmu** [comment]
Oh I see, I thought you were talking about the view field (which is public) not the TabView class (which is package). I'll see if we plan to make any changes here.

**Comment by guger** [comment]
Great, thanks!
