### ISSUE TITLE
[Menu] ListPopupWindow doesn't respect the Elevation overlay

### ISSUE THREAD

**Issue by Sourav-21** [material-components/material-components-android#585]
## Description ##
ListPopupWindow doesn't use any dynamic elevation overlay. Instead of this, it uses a absolute 11% alpha overlay. So if the parent view already has elevation, it doesn't respect that elevation.

![Screenshot_20190911-081823](https://user-images.githubusercontent.com/20728734/64668435-319dc580-d47b-11e9-944c-b54db3a2487d.png)

## Expected behaviour ##
ListPopupWindow should use MaterialShapeDrawable as background. But ListPopupWindow doesn't have any exposed getElevation or setElevation method. So we are unable to get the Elevation value and can't implement proper background for listPopupWindow.

**Comment by dsn5ft** [comment]
Unfortunately `ListPopupWindow` is not part of the MDC-Android library and we can't theme its default background to a `MaterialShapeDrawable` in XML, so at this time we can't update it to support absolute elevation overlays.

For now I'm wondering if you can create a `MaterialShapeDrawable` with absolute elevation factored in:

```
    ElevationOverlayProvider elevationOverlayProvider = new ElevationOverlayProvider(context);
    MaterialShapeDrawable background = MaterialShapeDrawable.createWithElevationOverlay(context, menuElevation);
    background.setParentAbsoluteElevation(elevationOverlayProvider.getParentAbsoluteElevation(menu));
```

And set that as the `ListPopupBackground` via `ListPopupBackground#setBackgroundDrawable` (you may need to wrap the `MaterialShapeDrawable` in an `InsetDrawable` and set some corners on the `MaterialShapeDrawable`).

**Comment by Sourav-21** [comment]
> Unfortunately `ListPopupWindow` is not part of the MDC-Android library and we can't theme its default background to a `MaterialShapeDrawable` in XML, so at this time we can't update it to support absolute elevation overlays.
> 
> For now I'm wondering if you can create a `MaterialShapeDrawable` with absolute elevation factored in:
> 
> ```
>     ElevationOverlayProvider elevationOverlayProvider = new ElevationOverlayProvider(context);
>     MaterialShapeDrawable background = MaterialShapeDrawable.createWithElevationOverlay(context, menuElevation);
>     background.setParentAbsoluteElevation(elevationOverlayProvider.getParentAbsoluteElevation(menu));
> ```
> 
> And set that as the `ListPopupBackground` via `ListPopupBackground#setBackgroundDrawable` (you may need to wrap the `MaterialShapeDrawable` in an `InsetDrawable` and set some corners on the `MaterialShapeDrawable`).

![Screenshot_20191218-202031](https://user-images.githubusercontent.com/20728734/71096329-16f28f80-21d4-11ea-9a4f-b1e351cca8a4.png)
Thanks a lot. I am now quite satisfied by the result.

**Comment by khaykov** [comment]
Another alternative is to use `ColorDrawable` with color provided by `MaterialOverlayProvider`,
 eg: `popupListWindow.setBackgroundDrawable(new ColorDrawable(elevatedColor));`

**Comment by cristiannancu** [comment]
Is there a reason for not exposing the `setElevation(float)` method of the 'PopupWindow mPopup;' member in `ListPopupWindow`? Are there concerns around older APIs that might not support it?

**Comment by cristiannancu** [comment]
@Sourav-21  Is there a reason for not exposing the `setElevation(float)` method of the `PopupWindow mPopup;` member in `ListPopupWindow`? Are there concerns around older APIs that might not support it?

**Comment by cristiannancu** [comment]
Yes that's what I meant - expose it in `ListPopupWindow`. I only mentioned the mPopup member because that's the View being used by `ListPopupWindow`.

**Comment by Sourav-21** [comment]
@cristiannancu yes. Possible.
But I recommend not to set elevation when `popupWindow` is visible.

**Comment by Sourav-21** [comment]
@cristiannancu In my custom `listPopupWindow` class, I changed lot of things. I completely ditched `listView` and embraced `RecyclerView`.
