### ISSUE TITLE
[TextInputLayout] HintTextAppearance with textAllCaps doesn't work

### ISSUE THREAD

**Issue by gabrielemariotti** [material-components/material-components-android#586]
**Description:** 

Using:
```

        <com.google.android.material.textfield.TextInputLayout
            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
            app:hintTextAppearance="@style/allcapsTA"
            ...>
```
with this style:
```
  <style name="allcapsTA" parent="TextAppearance.MaterialComponents.Caption">
    <item name="android:textAllCaps">true</item>
  </style>
```
or using:

        <com.google.android.material.textfield.TextInputLayout
            style="@style/OutlinedColorBox"
            ...>
```
  <style name="OutlinedColorBox" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
    <item name="hintTextAppearance">@style/allcapsTA</item>
  </style>

```
The ` textAllCaps` doesn't work for the hint text.

<img width="139" alt="" src="https://user-images.githubusercontent.com/2583078/64678810-a3294400-d47a-11e9-9b8b-2a5f0f5f6c44.png">
<img width="134" alt="" src="https://user-images.githubusercontent.com/2583078/64678823-a8868e80-d47a-11e9-849c-aaa94df7b1a6.png">

It is not related to the style of the `TextInputLayout`. Also the FilledBox style has the same behavior.

**Expected behavior:** 

Hint text with all caps letters.

**Android API version:** Android P/Q

**Material Library version:**  1.1.0-alpha10

**Comment by ldjcmu** [comment]
Collapsing to #584 as related.
