### ISSUE TITLE
Feature request: Add metrics for alert dialogs with a text field

### ISSUE THREAD

**Issue by sabinebarrera** [material-components/material-components-android#59]
### Overview
There are a few examples in MDG that show alert dialog with text field. These dialog's metrics seem off compare to the metrics provided in [dialog specs](https://material.io/guidelines/components/dialogs.html#dialogs-specs). Please provide a spec'ed example of an alert dialog with a text field.

### Reproduction steps
Some Material Design - Alert dialog with text field(s) examples:
– Example #1 It can be found [here](https://material.io/guidelines/components/text-fields.html#text-fields-field-variations) but no metrics/specs are provided.
– Example #2 It can be found [here](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsakx4QjdTSnV2d2c/patterns-errors-state4.png). This screenshot can be found in [Error patterns - Permission requested](https://material.io/guidelines/patterns/errors.html#errors-incompatible-state-errors)

**Comment by ymarian** [comment]
The catalog demo now has dialogs
