### ISSUE TITLE
[SwitchMaterial] Progress display for Switch

### ISSUE THREAD

**Issue by scholt** [material-components/material-components-android#591]
**Is your feature request related to a problem? Please describe.**
The Material Guideline states how to show progress when a switch state can't be immediately applied: https://material.io/components/selection-controls/#switches

Unfortunately this seems not to be possible with the MaterialSwitch component, and as the Designers in our company rely on the Documentation they now want this.

**Describe the solution you'd like**
A `setProgress` Method which shows a ProgressBar like in the Guideline

**Describe alternatives you've considered**
It seems that the current thumb only can be modified with drawables but not with custom views to insert a Progress bar by myself.

**Comment by pepos** [comment]
This would be great to have. Is basic for preferences which sync with backend.

**Comment by luxiliu** [comment]
I think it's not suggested to show process like that, because it clearly says

![Screen Shot 2021-06-17 at 9 22 22 pm](https://user-images.githubusercontent.com/22950288/122387356-206bdc00-cfb2-11eb-9326-42160fc7c462.png)

**Comment by wcshi** [comment]
fyi, this is a deprecated (Material) design of switch. For usability reasons, there should be no pending state for each switch. If pending is needed, please use a large Circular Progress Indicator with scrim. Pending state on multiple switches may result in unexpected ending states.
