### ISSUE TITLE
[MaterialDatePicker] Setting a start CalendarConstraint breaks date display

### ISSUE THREAD

**Issue by danielwilson1702** [material-components/material-components-android#592]
**Description:** If I wish to constrain the datepicker to any time from today to 10 years ago, I used the following code:

```
val builder = MaterialDatePicker.Builder.datePicker()
val now = ZonedDateTime.now().toInstant().toEpochMilli()
val tenYearsAgo = ZonedDateTime.now().minusYears(10).toInstant().toEpochMilli()

builder.setCalendarConstraints(CalendarConstraints.Builder()
           .setStart(Month.create(tenYearsAgo))
           .setEnd(Month.create(now)).build())
```

**Expected behavior:** 
While this does prevent a selection from before 2009:
![image](https://user-images.githubusercontent.com/5859421/64782263-aa288300-d55c-11e9-9e5f-fdfb23a8e06b.png)

It breaks the days in the current month by producing the following:
![image](https://user-images.githubusercontent.com/5859421/64782105-6766ab00-d55c-11e9-9f28-ee8d5640c877.png)

September 2019 starts on Sunday, so my guess is it is pulling September days from 2009 now perhaps. 

**Android API version:** 23

**Material Library version:** 1.1.0-alpha10

**Device:** Marshmallow emulator

**Comment by ldjcmu** [comment]
We'll take a look at this for the next release. Thanks for the report.

**Comment by ldjcmu** [comment]
Hi danielwilson1702,

I think the calendar is actually showing August 2019. This is a bug we've fixed since alpha10 related to timezone handling (we now communicate and force timezones in UTC as opposed to using the system default so that device level timezone changes don't affect the calendar).

I re-created your setup using the new APIs and cannot repro. 
Thanks for the report. This is fixed in the next release!

```
builder = MaterialDatePicker.Builder.datePicker();
long now = LocalDateTime.of(2009, 1, 1, 0, 0).atZone(ZoneId.ofOffset("UTC", ZoneOffset.UTC)).toInstant().toEpochMilli();
long tenYearsAgo = now - 315576000000L;
builder.setCalendarConstraints(new CalendarConstraints.Builder()
                .setStart(tenYearsAgo)
                .setEnd(now).build());
MaterialDatePicker<?> picker = builder.build();
```

**Comment by danielwilson1702** [comment]
Nice work!
