### ISSUE TITLE
 [MaterialCardView] Setting EdgeTreatment on shapeAppearanceModel of MaterialCardView hides the card view content

### ISSUE THREAD

**Issue by muthuraj57** [material-components/material-components-android#594]
**Description:** Adding EdgeTreatment (using setLeftEdge/setRightEdge/setTopEdge/setBottomEdge/setAllEdges) on shapeAppearanceModel of the MaterialCardView hides the content of that card view

**Expected behavior:** 
![Expected](https://user-images.githubusercontent.com/10187654/64797288-cf3de580-d59e-11e9-9430-d2268aa5ebc6.png)

**Actual behavior:**  
![Actual](https://user-images.githubusercontent.com/10187654/64797357-f09ed180-d59e-11e9-8a05-c25c05774810.png)

**Source code:** https://github.com/muthuraj57/MaterialCardView_Render_Issue

**Android API version:** Android 10 (29)

**Material Library version:** 1.1.0-alpha10

**Device:** Google Pixel 2 xl

**Comment by ymarian** [comment]
Note: 

After https://github.com/material-components/material-components-android/commit/0f8fa7e6c9f7e44407c4bde0a6e800c17c2781e6

The work around now is:

`cardView.clipToOutline = false`

We should get this addressed soon though.

**Comment by wcshi** [comment]
Resolved in https://github.com/material-components/material-components-android/commit/d09ac034816a4eb86b49b254f45aed9daa8ca1b6
