### ISSUE TITLE
BottomAppBar with FloatingActionButton - Programmatically, non-XML

### ISSUE THREAD

**Issue by tormentous** [material-components/material-components-android#595]
Hi, I tried to create a UI without using XML.
The fab isn't anchored correctly because it is showing in the Left side of the BottomAppBar, or is there something wrong with my code? thanks!

//------Manifest--------//
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.myapplication">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:configChanges="orientation|screenSize"
        android:hardwareAccelerated="true"
        android:theme="@style/Theme.MaterialComponents.Light.NoActionBar.Bridge">
    <activity android:name=".MainActivity">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
    </application>
</manifest>

//-----Activity----//
package com.example.myapplication;

import android.annotation.SuppressLint;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.view.View;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.view.ContextThemeWrapper;
import androidx.coordinatorlayout.widget.CoordinatorLayout;

import com.google.android.material.bottomappbar.BottomAppBar;
import com.google.android.material.floatingactionbutton.FloatingActionButton;

public class MainActivity extends AppCompatActivity {

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR1)
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(null);
        CoordinatorLayout cl = new CoordinatorLayout(this);
        CoordinatorLayout.LayoutParams clp = new CoordinatorLayout.LayoutParams(CoordinatorLayout.LayoutParams.MATCH_PARENT, CoordinatorLayout.LayoutParams.MATCH_PARENT);
        cl.setLayoutParams(clp);

        FloatingActionButton fab = new FloatingActionButton(this);
        fab.setImageResource(android.R.drawable.ic_menu_more);
        fab.setUseCompatPadding(true);
        fab.setCompatElevation(0f);
        fab.setLayoutParams(clp);

        BottomAppBar bap = new BottomAppBar(new ContextThemeWrapper(this, R.style.Widget_MaterialComponents_BottomAppBar));
        bap.setLayoutParams(clp);
        bap.setId(View.generateViewId());
        CoordinatorLayout.LayoutParams clpp = ((CoordinatorLayout.LayoutParams)fab.getLayoutParams());
        clpp.setAnchorId(bap.getId());
        fab.setLayoutParams(clpp);
        bap.getMenu().add("test");
        bap.addView(fab);
        bap.setFabAlignmentMode(BottomAppBar.FAB_ALIGNMENT_MODE_CENTER);
        cl.addView(bap);
        setContentView(cl);
    }
}

**Comment by ldjcmu** [comment]
setting an anchor for FABs does work, so I believe the issue is not in the library

**Comment by tormentous** [comment]
Sir, the fab is overlapping navigation icon "hamburger" on the left corner. I am unsure if really is overlapping but prior to as what the documentation stated as long as setAchorId is called it will auto position (fab in the middle, nav icon in left corner) give it a try
