### ISSUE TITLE
[MaterialButtonToggleGroup] Add an option to spread MaterialButtons

### ISSUE THREAD

**Issue by MGaetan89** [material-components/material-components-android#596]
Currently, `MaterialButtonToggleGroup` adds each `MaterialButton` one after another on a single line, each having its own width.

I'd like to have an option to evenly distribute the `MaterialButton` so they fill the whole space available for the `MaterialButtonToggleGroup`.

**Comment by ymarian** [comment]
I changed MaterialButtonToggleGroup  to be a linear layout. So you could use weights in the child button for this now.

https://github.com/material-components/material-components-android/commit/a405dd9664731e128323595e2934827f838d2e9f
