### ISSUE TITLE
[TextInputLayout] Hint text overlaps outline when paddingTop is set

### ISSUE THREAD

**Issue by muthuraj57** [material-components/material-components-android#597]
**Description:** TextInputLayout with `Widget.MaterialComponents.TextInputLayout.OutlinedBox` as style has overlapped hint on the outline when `paddingTop` is used

**Expected behavior:** 
![Expected](https://user-images.githubusercontent.com/10187654/64867659-784a1600-d65b-11e9-9689-45f2036567d2.png)

**Actual behavior:** 
![Actual](https://user-images.githubusercontent.com/10187654/64867688-826c1480-d65b-11e9-8828-f858fe5f4458.png)

**Source code:** https://github.com/muthuraj57/TextInputLayout_Padding_Issue

**Android API version:** Android 10 (29)

**Material Library version:** 1.1.0-alpha10

**Device:** Google Pixel 2 xl

**Comment by RohitKhanduri04** [comment]
This same issue is getting replicated in the latest material component release 1.4.0-alpha01
