### ISSUE TITLE
[Themes] Theme Enforcement errors are too vague when upgrading from version 1.0.0 to version 1.1.0-alpha10

### ISSUE THREAD

**Issue by kphillisjr** [material-components/material-components-android#600]
**Description:** when I upgraded the Material Design project from version 1.0.0 (stable) to version 1.1.0-alpha10, the runtime of the application fails when I enter the the view taking advantage of material design components.

**Expected behavior:** For the theme to not throw a validation error on a previously working project.

**Source code:**
This project triggers compile problems simply by changing which version of the material design library is used:
https://github.com/kphillisjr/MaterialButtonDrawableBug

**Android API version:** 19 ( as per android 4.4 emulator) and 26 ( as per android 8.0 emulator)

**Material Library version:** 
1.1.0-alpha 10 ( broken version)
1.0.0 ( stable, working version)

**Device:** 
Emulated Devices: 
Android 8.0 x86 device with google api's installed.
Android 4.4 x86 device without google api's installed.

**Comment by gabrielemariotti** [comment]
It seems you are using an `AppCompat` theme in your app.
`<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">`

You should use a [Material Theme ](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#material-components-themes) or if you want to continue to use an `AppCompat` theme you must add the following [new theme attributes](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#appcompat-themes-app-compat-themes) as described in the [Getting Started](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#getting-started-with-material-components-for-android) page or you will encounter `ThemeEnforcement` error.

**Comment by kphillisjr** [comment]
Thank you for the response, and the document did help with the crashing. However, There is still a few major notes which probably should be implemented to help reduce issues with developers changing from a stock android application to material themed applications.

- The ```ThemeEnforcer``` error message is too vague. The message for this sort of error really should mention which xml file caused the error, and even better, add the line number/element name that caused the error.

- The ```ThemeEnforcer``` is applies to all elements of the theme. This means that if I have custom theme elements not tied to any of the MaterialDesign classes, the themenforcer will throw errors on that as well.

- The simple change of replacing the base theme from ```AppCompat``` to ```MaterialComponents``` causes the stock android buttons to loose the rendered icon placement. See the attached screenshots for comparison

Screenshot with ```AppCompat``` Theme base:
![AppCompatTheme](https://user-images.githubusercontent.com/1205559/64916289-b2d9ae80-d740-11e9-8422-94dfb3a18d00.png)


Screenshot of the same screen with simply changing ```AppCompat``` to ```MaterialComponents```:

![MaterialDesign_AndroidButtons](https://user-images.githubusercontent.com/1205559/64916354-0698c780-d742-11e9-8ee6-e0ad876acf86.png)

**Note:** The above Screenshots where generated using Material Design release 1.1.0-alpha10 on an The android 8.0.0 operating system with google play store installed, and the emulated device being the Pixel 2.
