### ISSUE TITLE
how to set background for FAB?

### ISSUE THREAD

**Issue by Zed-Rustam** [material-components/material-components-android#601]
I want to set the background with the form on FAB, but I can’t do it

**Comment by MGaetan89** [comment]
Which version are you using?

From the [doc](https://github.com/material-components/material-components-android/blob/1.1.0-alpha10/docs/components/FloatingActionButton.md#attributes) of the latest version (1.1.0-alpha10), you should be able to use `app:backgroundTint`.

**Comment by Zed-Rustam** [comment]
> Which version are you using?
> 
> From the [doc](https://github.com/material-components/material-components-android/blob/1.1.0-alpha10/docs/components/FloatingActionButton.md#attributes) of the latest version (1.1.0-alpha10), you should be able to use `app:backgroundTint`.
> The same one seems to exist in the stable version (1.0.0) as well ([doc](https://github.com/material-components/material-components-android/blob/1.0.0/docs/components/FloatingActionButton.md#attributes)).

but it only changes the background color, and if I need the button to be of a different shape (for example, a square) or I need to set the background with a border

**Comment by ymarian** [comment]
We support the Shapeable interface on Fab. 

https://github.com/material-components/material-components-android/blob/master/docs/theming/Shape.md

Currently no plans to add back support for background.
