### ISSUE TITLE
[Library] NoClassDefFoundError

### ISSUE THREAD

**Issue by JonathanImperato** [material-components/material-components-android#605]
**Description:** Since the alpha 9 included the app crashes with this error:

> 
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** In my case I am using the [AltBeacon Library](https://altbeacon.github.io/android-beacon-library/), when I start ranging beacons in Region the app crashes.

**Material Library version:**  1.1.0-alpha09 to alpha10

**Device:** Any that has BLE support

**Comment by ldjcmu** [comment]
We have no plans to test and verify the AltBeacon Library behavior. If you can narrow the problem to a stacktrace including something from the Material Components Android Library, please re-open.
