### ISSUE TITLE
[DatePicker] Null pointer exception in mobile date picker 

### ISSUE THREAD

**Issue by bediaz** [material-components/material-components-android#608]
**Description:**
1. Launch Material Date Picker in Catalog (Pickers -> Demo -> Launch Material Date Picker)
2. Select any day in the view so that it's highlighted
3. Press the edit icon to switch to the TextInput field.
4. The TextInput field should be populated with the selected date.
5. Press the backspace key to erase the text.
6. The app will immediately crash after erasing the last character from the field.

**Expected behavior:**
Erasing the last character in the TextInput field should be erased.

**Source code:**
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
        at com.google.android.material.datepicker.SingleDateSelector$1.onValidDate(SingleDateSelector.java:113)
        at com.google.android.material.datepicker.DateFormatTextWatcher.onTextChanged(DateFormatTextWatcher.java:64)
```

**Android API version:**
  compileSdkVersion = 29
  minSdkVersion = 14
  targetSdkVersion = 27

**Material Library version:**
1.1.0-alpha10

**Device:**
Samsung S8 and Pixel 3 XL

**Comment by ldjcmu** [comment]
We'll take a look for fixing this in the next release. Thanks for the report.

**Comment by ldjcmu** [comment]
This is already fixed at head and will be in the next release. Thanks again for the report.

**Comment by mcastagnolo** [comment]
@ldjcmu If this is fixed can a hotfix release be cut?

**Comment by ldjcmu** [comment]
We're planning on releasing a version with the fix next week.

**Comment by mcastagnolo** [comment]
@ldjcmu But in the meantime since this is a pretty easy crash to stumble into, might that warrant a hotfix release containing this fix? If it's being released next week then that's 2+ weeks the fix has been held up.

**Comment by ldjcmu** [comment]
We're planning a release for late Tuesday / early Wednesday next week with several important fixes. We not in a place to do a hotfix any sooner.

**Comment by mcastagnolo** [comment]
@ldjcmu Is the next release with this fix still planned for this week?

**Comment by ldjcmu** [comment]
Yes. We're preparing it over at https://github.com/material-components/material-components-android/tree/release-1.1

**Comment by mcastagnolo** [comment]
@ldjcmu Great!

**Comment by mcastagnolo** [comment]
@ldjcmu Should have specified, is it planned for this week EOD today Friday or is it being released before the end of Sunday?

**Comment by dsn5ft** [comment]
@mcastagnolo EOD it is 😄

https://github.com/material-components/material-components-android/releases/tag/1.1.0-beta01
