### ISSUE TITLE
[TextInputLayout] setEndIconOnClickListener doesn't exit

### ISSUE THREAD

**Issue by JoaoPint0** [material-components/material-components-android#610]
**Description:** When Trying to implement a com.google.android.material.textfield.TextInputLayout with a endIcon I coulnd't find/import listener on the icon.

**Expected behavior:** Should be able to listen to the event

**Code:** (comment_input_layout as TextInputLayout).setEndIconOnClickListener()

**Android API version:** 28

**Material Library version:** 1.1.0-alpha10 

**Error:** None of the following functions can be called with the arguments supplied: 
public final fun setEndIconOnClickListener(@Nullable p0: ((View!) -> Unit)?): Unit defined in com.google.android.material.textfield.TextInputLayout
public open fun setEndIconOnClickListener(@Nullable p0: View.OnClickListener?): Unit defined in com.google.android.material.textfield.TextInputLayout

**Comment by gabrielemariotti** [comment]
The method [exists](https://github.com/material-components/material-components-android/blob/1.1.0-alpha10/lib/java/com/google/android/material/textfield/TextInputLayout.java#L2404).

**Comment by MGaetan89** [comment]
> **Code:** (comment_input_layout as TextInputLayout).setEndIconOnClickListener()

If that's your actual code, you forgot to pass an argument to `setEndIconOnClickListener8OnClickListener)`.

**Comment by JoaoPint0** [comment]
![Screenshot 2019-09-19 at 14 50 00](https://user-images.githubusercontent.com/33725185/65250039-d1e39200-daec-11e9-9e96-223b2e56d2f3.png)

It works, but it was some visual bug don't know if it's from the library but seems to be the only one it occurs to me
