### ISSUE TITLE
ResourcesNotFoundException design_ic_visibility

### ISSUE THREAD

**Issue by AnastasiaRainMaker** [material-components/material-components-android#611]
My app has encountered a crash on some devices with ResourcesNotFoundException. My test devices don't have such a problem, the devices that suffer the crash are Pixel 1 and Nexus 5X. OS versions are 6, 7, 8, 9.

The resource ID in the message from the crash log points to design_ic_visibility in my project R file. I don't have that resource in my project and it  looks like design_ic_visibility is part of material component library edittext component.

Using material components version 1.1.0-alpha09

Event trail:

`

android....rcesImpl | ResourcesImpl.java line 228 in android.content.res.ResourcesImpl.getResourceName()
-- | --
android....rcesImpl | ResourcesImpl.java line 687 in android.content.res.ResourcesImpl.loadDrawableForCookie()
android....rcesImpl | ResourcesImpl.java line 571 in android.content.res.ResourcesImpl.loadDrawable()
android....esources | Resources.java line 858 in android.content.res.Resources.loadDrawable()
android....pedArray | TypedArray.java line 928 in android.content.res.TypedArray.getDrawable()
android....pedArray | XResources.java line 1363 in android.content.res.XResources$XTypedArray.getDrawable()
android....Drawable | AnimatedStateListDrawable.java line 504 in android.graphics.drawable.AnimatedStateListDrawable.parseItem()
android....Drawable | AnimatedStateListDrawable.java line 453 in android.graphics.drawable.AnimatedStateListDrawable.inflateChildElements()
android....Drawable | AnimatedStateListDrawable.java line 385 in android.graphics.drawable.AnimatedStateListDrawable.inflate()
android....Inflater | DrawableInflater.java line 130 in android.graphics.drawable.DrawableInflater.inflateFromXml()
android....Drawable | Drawable.java line 1227 in android.graphics.drawable.Drawable.createFromXmlInner()
android....Drawable | Drawable.java line 1200 in android.graphics.drawable.Drawable.createFromXml()
android....rcesImpl | ResourcesImpl.java line 715 in android.content.res.ResourcesImpl.loadDrawableForCookie()
android....rcesImpl | ResourcesImpl.java line 571 in android.content.res.ResourcesImpl.loadDrawable()
android....esources | Resources.java line 771 in android.content.res.Resources.getDrawable()
android....esources | XResources.java line 790 in android.content.res.XResources.getDrawable()
android.....Context | Context.java line 525 in android.content.Context.getDrawable()
androidx...ontent.a | line 2 in androidx.core.content.a.c()
androidx...idget.l0 | line 15 in androidx.appcompat.widget.l0.a()
androidx...idget.l0 | line 11 in androidx.appcompat.widget.l0.a()
a.a.k.a.a | line 1 in a.a.k.a.a.c()
com.goog...Delegate | line 2 in com.google.android.material.textfield.PasswordToggleEndIconDelegate.initialize()
com.goog...utLayout | line 5 in com.google.android.material.textfield.TextInputLayout.setEndIconMode()
com.goog...utLayout | line 184 in com.google.android.material.textfield.TextInputLayout.<init>()

`

**Comment by ldjcmu** [comment]
Thanks for the crash report, we'll take a look.

**Comment by AnastasiaRainMaker** [comment]
hey, any updates?

**Comment by ldjcmu** [comment]
Yes. The design_ic_visibility appears missing from an unqualified folder (right now it only exists in APIs >21 and dpis >= mdpi). We haven't tested a fix yet, but expect that adding the resource to an unqualified folder version should solve the problem.

**Comment by ldjcmu** [comment]
Hey 	AnastasiaRainMaker,

We're currently unable to repro this issue. Can you provide a small sample app that successfully repros the problem? Does it occur in the catalog app text field demo for password fields on those devices?

The only thought we've had is that proguard or multidex is somehow affecting the resource availability, but since we can't repro, we've no way to tell.

**Comment by ldjcmu** [comment]
Source-code from other ticket:
- Source code:
```
 <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/password"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginEnd="@dimen/activity_horizontal_margin"
                android:layout_marginStart="@dimen/activity_horizontal_margin"
                android:layout_marginTop="16dp"
                android:hint="@string/password"
                app:error="@{viewModel.passwordErrorText}"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/email"
                app:passwordToggleEnabled="true">
```

**Comment by AnastasiaRainMaker** [comment]
Hey. That is also my ticket and the source code, I am not able to reproduce it myself either but I see crashes coming from Mountain View, CA on emulator devices Motorola nexus recently on I actually thought you were able to reproduce it :)). 

So the important two pieces of information:
1. I am using proguard 
2. I am using app-bundle

So this resource might be removed at the build  type by bundling or. the proguard. Any thought on that?

**Comment by ldjcmu** [comment]
Yes. I'm trying to see what we can do based on https://developer.android.com/studio/build/shrink-code.html#shrink-resources. I'm wondering if something in the https://developer.android.com/studio/build/shrink-code.html#keep-resources section can help you while we debug this.

**Comment by ldjcmu** [comment]
Are you using tools:shrinkMode="strict" ? Any proguard or shrink settings files and configs you have would be helpful if you can share.

**Comment by AnastasiaRainMaker** [comment]
no I am using strict mode. here is my pro guard rules

# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
-dontwarn java.lang.invoke.LambdaMetafactory

#-keep class com.google.** { *; }

-keep class android.** {*;}

 ##---------------Begin: proguard configuration for Gson  ----------
 # Gson uses generic type information stored in a class file when working with fields. Proguard
 # removes such information by default, so configure it to keep all of it.
 -keepattributes Signature

 # For using GSON @Expose annotation
 -keepattributes *Annotation*

 # Gson specific classes
 -keep class sun.misc.Unsafe { *; }
 -keep class com.google.gson.stream.** { *; }

 # Application classes that will be serialized/deserialized over Gson
 -keep class com.heb.sng.webservices.interceptor.** { *; }
 -keep class com.heb.sng.webservices.models.** { *; }

 -keep class androidx.core.app.CoreComponentFactory { *; }

**Comment by AnastasiaRainMaker** [comment]
and it has -keep class android.** {*;}

**Comment by ldjcmu** [comment]
Our packages are com.google.android.material so those wouldn't be included in android.**

Perhaps try an edit there? Sorry, I still don't have a repro.

**Comment by ldjcmu** [comment]
Other things that might help us are your gradle build file for things like your shrinkResources and your multidex settings.

**Comment by AnastasiaRainMaker** [comment]
the only thing I have for shrinking is 

```
 minifyEnabled true
shrinkResources true
```

I don't have any specific settings for multiple, I believe now it is enabled by default

**Comment by AnastasiaRainMaker** [comment]
I can try adding this resource id to the keep file for the proguard, but it might be the app bundle too

**Comment by ldjcmu** [comment]
Did specifying keep for the resources help?

**Comment by AnastasiaRainMaker** [comment]
not yet released the app to check the effect, we are going to target at least a couple of weeks from now for the prod release + some time to monitor. I will update here on the results.

**Comment by fkirc** [comment]
This sounds like a very similar bug to my #670 crash report.

**Comment by AnastasiaRainMaker** [comment]
@fkirc indeed looks like the same issue, I see the repo change, but I would like to get an explanation of the root cause of the issue that Google identified to better understand if the fix covers it

**Comment by ldjcmu** [comment]
We think this is due to minifyEnabled and shrinkResources stripping out a necessary file. We've updated those drawables to have implementations in the unqualified drawable folder and use the generation functions for APIs earlier than 21 instead of several dpi and version qualified folders with no base implementation.

**Comment by ldjcmu** [comment]
Please do re-open if the issue persists on 1.1.0-beta02.

**Comment by AnastasiaRainMaker** [comment]
when is the target release for beta02?

**Comment by ldjcmu** [comment]
Beta will likely be end of month because we want some bake time. We expect to have a new alpha before then (I believe next week, and will verify that is true).
