### ISSUE TITLE
[TextInputLayout] Set icon with one tag and position with other

### ISSUE THREAD

**Issue by luisenricke** [material-components/material-components-android#612]
The problem with the current icon manipulation is that it has to start or end with some tag like startIcon or endIcon. 

If it were implemented as an src and position tag like the other views, it would be perfect and easy to identify where it is, because the truth is that it doesn't make sense if it has two icons at the same time in the same view. 

The other problem is that the image doesn't have an ID and this doesn't allow me to program its different states or other things that occur to me.

For your attention, thank you 😄

**Comment by gabrielemariotti** [comment]
>The other problem is that the image doesn't have an ID and this doesn't allow me to program its different states 

Did you check all `textInputLayout.setStartIcon*` methods?

    textInputLayout.setStartIconDrawable();
    textInputLayout.setStartIconTintList();
    textInputLayout.setStartIconCheckable();
    textInputLayout.setStartIconOnClickListener();
    textInputLayout.setStartIconOnLongClickListener();
    textInputLayout.setStartIconTintMode();
    textInputLayout.setStartIconVisible();

They should be enough.

**Comment by luisenricke** [comment]
Thanks 👍
