### ISSUE TITLE
[BottomSheetBehavior] Shape corners behavior question and possible bug

### ISSUE THREAD

**Issue by Zeliret** [material-components/material-components-android#614]
If a bottom sheet has rounded courners it will animate its to sharp state if the sheet is fully expanded. 
But I believe it should keep rounded corners if it height is smaller than the screen height and fit contents is true. 
So we can see a nice rounded bottom sheet with a small menu for example.

**Comment by hrach** [comment]
https://github.com/material-components/material-components-android/pull/437

**Comment by Zeliret** [comment]
@hrach When it will be merged?

**Comment by hrach** [comment]
No idea. Just linking pr. :-)

**Comment by Zeliret** [comment]
I have found a nice method `BottomSheetBehavior::disableShapeAnimations()` which is marked as `LIBRARY_GROUP`. It can do the trick as well but we need to get it as public.

**Comment by ldjcmu** [comment]
Marking this as a dup of #463. I'll check-in on the PR status.
