### ISSUE TITLE
[SwipeRefreshLayout] Source not exists

### ISSUE THREAD

**Issue by chirag-ji** [material-components/material-components-android#615]
**Description:** Package could not be resolved after upgrading to 1.1.0-alpha10

**Expected behavior:** This package might be present

**Android API version:** 29
![androidx-error1](https://user-images.githubusercontent.com/35477634/65372616-14919f80-dc90-11e9-8605-a81b2a1025c8.png)
![gradle-dependencies](https://user-images.githubusercontent.com/35477634/65372621-2a06c980-dc90-11e9-9163-c03a8c099d38.png)

**Material Library version:** 1.1.0-alpha10

If above class is renamed then please let me know, as updating to latest version is breaking the code of my application.

**Comment by Zeliret** [comment]
@chirag-ji try this:
`androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02`

**Comment by chirag-ji** [comment]
@Zeliret Thanks for your response, it is solved now.

**Comment by devsparkles** [comment]
Hello Beautiful people,

Could you please add it to the 1.1.0-beta02 ?
I also want to know if it will be released in the final 1.1.0 
Because my code actually have some SwipeToRefreshLayout.
What is the plan?
What's going on?

Regards,
Xavier

**Comment by devsparkles** [comment]
Even if you closed that you must know that the SwipeToRefreshLayout is still not available inside the beta02 version of the material components for android. People are using that component.
I am using it. Please try to make it into the beta03

**Comment by EdwardvanRaak** [comment]
Why on earth is this being deleted and added randomly between version. Seriously...?

**Comment by chirag-ji** [comment]
Looks they are trying to separate different components in different packages, available at demand. Like they separated SwipeRefreshLayout from androidx package, As I know so far,previously it was the part of android support package.
