### ISSUE TITLE
[TextInputLayout] Error and HelperText clash

### ISSUE THREAD

**Issue by Antimonit** [material-components/material-components-android#621]
**Description:**

If we set `error` followed by setting `helperText` of `TextInputLayout`, the helper text will replace error text. This behavior is questionable but not the point of this PR.
```kotlin
textInputLayout.error = "Error"
textInputLayout.helperText = "Helper"
```
At this moment, the `TextInputLayout` will be showing the helper text.

The problem will manifest when we reset the `error` by setting it to null. Resetting error will cause helper text to hide.

If we change the ordering of the first two assignments like:
```kotlin
textInputLayout.helperText = "Helper"
textInputLayout.error = "Error"
```
then `TextInputLayout` will be displaying an error message and resetting the error will restore helper text as expected.

**Expected behavior:** Helper text should not hide after setting error to null.

**Source code:** 
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="16dp"
    android:theme="@style/Theme.MaterialComponents.Light">

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/textInputLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/editText"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </com.google.android.material.textfield.TextInputLayout>

</FrameLayout>
```
```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        textInputLayout.error = "Error"
        textInputLayout.postDelayed({
            textInputLayout.helperText = "Helper"
        }, 2000)
        textInputLayout.postDelayed({
            textInputLayout.error = null
        }, 4000)
    }
}
```

**Android API version:** compile 29, min 21, target 29

**Material Library version:** Tested both `1.1.0-alpha07` and `1.1.0-alpha10`

**Device:** Tested on `Pixel 2 Emulator (API 28)` and `Huawei INE-LX2 (API 27)`

**Comment by Antimonit** [comment]
Actually this:

> If we set error followed by setting helperText of TextInputLayout, the helper text will replace error text.

might be the explanation for the bug.

It does not make much sense to me why it should replace the error message. I believe the error message should have higher priority than helper text.

To work around the issue we are using:
```kotlin
textInputLayout.helperText = text
textInputLayout.error = textInputLayout.error
```
whenever changing the helper text.

**Comment by Antimonit** [comment]
The fix from the previous comment:
```kotlin
textInputLayout.helperText = text
textInputLayout.error = textInputLayout.error
```
fixes the scenario given in the original issue but for slightly different scenario:
```kotlin
setError("Error")
textInputLayout.postDelayed({
    setError(null)
}, 2000)
textInputLayout.postDelayed({
    setHelper("Helper")
}, 4000)
```
it breakes again.

---

I have found that checking for the nullability of the error text will solve the second scenario while also maintaining the fix for the first scenario.

Currently, we use something like this:
```kotlin
fun setError(text: CharSequence?) {
    if (textInputLayout.error != text) {
        textInputLayout.error = text
    }
}

fun setHelper(text: CharSequence?) {
    if (textInputLayout.helperText != text) {
        textInputLayout.helperText = text
        if (textInputLayout.error != null) {
            textInputLayout.error = textInputLayout.error
        }
    }
}
```

---

This:
```kotlin
if (textInputLayout.error != text)
    textInputLayout.error = text
```
is a fix of another problem where if you set an error/helper text for the second time while it is still being animated from the first call, the animation will be interrupted in the middle.

Do we really have to do these crazy workarounds? 🙄

**Comment by leticiarossi** [comment]
This should have been fixed in https://github.com/material-components/material-components-android/commit/816f080be22345bc200acfe268fd808b654cc938 which will be included in upcoming releases.
