### ISSUE TITLE
[BottomNavigationView] Button Behaviour with Constraint Layout

### ISSUE THREAD

**Issue by aggarwalpulkit596** [material-components/material-components-android#622]
There should be the support of buttons/fab/extended fab with bottom navigation and constraint layout with fab behavior so that fab adjust itself on the hiding of bottom navigation currently there is no option to do this and moreover if we try to add a button with bottom navigation and constraint layout the fab goes behind the bottom navigation

**Comment by killvetrov** [comment]
This is what CoordinatorLayout and corresponding Behaviors are designed for. It's mentioned in the docs: https://material.io/develop/android/components/floating-action-button/

> Note: If the FloatingActionButton is a child of a CoordinatorLayout, you get certain behaviors for free. It will automatically shift so that any displayed Snackbars do not cover it, and will automatially hide when covered by an AppBarLayout or BottomSheetBehavior.

**Comment by aggarwalpulkit596** [comment]
I need to achor floating action button to bottoms navigation view but it doesn't work especially if bottom navigation behaviour is set to hide on scroll

**Comment by killvetrov** [comment]
@aggarwalpulkit596 did you look into `BottomAppBar`? https://material.io/components/app-bars-bottom

**Comment by drchen** [comment]
Closing the issue since I think BottomAppBar is the right answer to this.
