### ISSUE TITLE
[MaterialDatePicker] MaterialDatePickerTestUtil should be made public

### ISSUE THREAD

**Issue by mcastagnolo** [material-components/material-components-android#624]
I want to replace the default Android DatePicker with the new MaterialDatePicker, but testing it is difficult compared to the normal DatePicker. Can the MaterialDatePickerTestUtil class and all of the underlying properties/classes it references be made public so that it's easier to do UI integration tests with this component?

**Comment by ldjcmu** [comment]
I will check, but I think it's very unlikely we'll open the class. That said, some of the tags are much more likely. 

Are there specific tags you need and are unable to test via id or other view hierarchy attributes? I'm not sure what our API review process will think about this, but I'll certainly see what we can do to help.

**Comment by bohsen** [comment]
@ldjcmu I know this is still in alpha, but have you considered adding a test module to the project? with support for Instrumentation testing.

**Comment by ldjcmu** [comment]
We had not considered this yet, but I can see where thoughts are.

**Comment by bohsen** [comment]
@mcastagnolo You can use this:

```kotlin
private val currentLocale: Locale = ConfigurationCompat.getLocales(Resources.getSystem().configuration)[0]

/**
 * Picks a specific date from a [MaterialDatePicker][com.google.android.material.datepicker.MaterialDatePicker].
 * 
 * Takes the current locale into account.
 */
private fun pickBirthDate(birthdate: Date) {
    // Click year selector button to open year selection view
    onView(withId(R.id.month_navigation_fragment_toggle)).perform(click())

    // Scroll to year
    val yearGrid = onView(withRecyclerView(R.id.mtrl_calendar_year_selector_frame)).check(matches(isDisplayed()))
    yearGrid.perform(scrollTo<RecyclerView.ViewHolder>(withText(SimpleDateFormat("y", currentLocale).format(birthdate))))

    // Click the year
    onView(withText(SimpleDateFormat("y", currentLocale).format(birthdate))).perform(click())

    // Scroll to month
    val monthGrid = onView(withRecyclerView(R.id.mtrl_calendar_months))
    monthGrid.perform(scrollTo<RecyclerView.ViewHolder>(
        withChild(withText(SimpleDateFormat("MMMM, y", currentLocale).format(birthdate))))
    )

    onView(
        allOf(
            withParent(withClassName(equalTo("com.google.android.material.datepicker.MaterialCalendarGridView"))),
            withClassName(equalTo("com.google.android.material.textview.MaterialTextView")),
            isDescendantOfA(withRecyclerView(R.id.mtrl_calendar_months)),
            withText(SimpleDateFormat("d", currentLocale).format(birthdate)),
            isDisplayed()
        )
    ).perform(click())

    onView(withId(R.id.confirm_button)).perform(click())
}
```
Depends on this this utility class:

```kotlin
class RecyclerViewMatcher private constructor(@IdRes private val recyclerViewId: Int)
    : BoundedMatcher<View, RecyclerView>(RecyclerView::class.java) {

    override fun describeTo(description: Description?) {
        description?.appendText("with Recyclerview with id: $recyclerViewId ")
    }

    override fun matchesSafely(item: RecyclerView): Boolean {
        return item.id == recyclerViewId
    }

    companion object {
        @JvmStatic fun withRecyclerView(@IdRes recyclerViewId: Int): RecyclerViewMatcher {
            return RecyclerViewMatcher(recyclerViewId)
        }
    }
}

**Comment by bohsen** [comment]
The above is broken since release 1.2.0-alpha02. Haven't found an alternative solution.

**Comment by bismarabia** [comment]
Any updates on this? when are you planning on making this public?

**Comment by drchen** [comment]
Hi, since MaterialDatePickerTestUtil was written specifically for the internal test cases we created, opening it to public may incur unnecessary dependency and maintenance efforts to us.

If you really need it for your tests, probably just copy the code in your codebase and tailor it according to your needs.

Will close the issue for now.
