### ISSUE TITLE
[MaterialButton] does or will support 50% rounded corners?

### ISSUE THREAD

**Issue by nick-fedesna** [material-components/material-components-android#626]
**Is your feature request related to a problem? Please describe.**
It seems the [Crane](https://material.io/design/material-studies/crane.html#shape) design study makes it seem like the Button pattern supports 50% rounded corners.  After trying everything and then looking at the code, it looks like only `ExtendedFloatingActionButton` supports this via the `ShapeAppearanceModel.PILL`

**Describe the solution you'd like**
I would like to know if there is a plan to support 50% rounded "pill" corners in anything other than `ExtendedFloatingActionButton` or if I'm missing something.

**Describe alternatives you've considered**
In the meantime, it seems possible to use `ExtendedFloatingActionButton` everywhere but this could be hard to sell on the greater team to use for all our buttons.
It also seems possible to set a `cornerRadius` to a large value (bigger than half the height of the button) which overrides the `cornerSize` and will be clamped to half the height of the button.  This seems non-intuitive and to support with various buttons sizes you must choose a size larger than your biggest button.

**Additional context**
![Screenshot 2019-09-24 11 08 39](https://user-images.githubusercontent.com/2512460/65529447-bd701280-debb-11e9-8363-9f6ddb96d87b.png)

**Comment by ldjcmu** [comment]
It currently does not. We plan to support this soon as part of the shape subsystem.

**Comment by pumpkinpie65** [comment]
For future reference: as of [this commit](https://github.com/material-components/material-components-android/commit/c831ecc99d6d08cd3dfd3b9e90dc8d61222afb41) all `cornerSize` attributes on `ShapeAppearance` accept fraction values. This means you can create a style like 
`<style name="PillShapeAppearance">
    <item name="cornerFamily">rounded</item>
    <item name="cornerSize">50%</item>
</style>`
and set it on your MaterialButton with `app:shapeAppearanceOverlay="@style/PillShapeAppearance"`
