### ISSUE TITLE
[NavigationView] Logic error when drawing nav bar scrim

### ISSUE THREAD

**Issue by consp1racy** [material-components/material-components-android#629]
**Description:**

`NavigationView` tries to apply a scrim behind navigation bar when the navigation bar color is *not* transparent. It doesn't scrim at all when there's no window-provided scrim.

Also, if the `NavigationView` is inflated with a `ContextThemeWrapper` the logic wouldn't work. The `Activity` would need to be unwrapped to get access to a `Window`.

**Expected behavior:**

`NavigationView` tries to apply a scrim behind navigation bar only when the navigation bar color *is* transparent. There's no reason to scrim twice.

This should apply to any color with zero alpha, not just #00000000.

For discussion, should this be enabled on API 29 with target API 29 when the system is in charge of coloring navigation?

**Source code:** 

```
  private void setupInsetScrimsListener() {
    getViewTreeObserver()
        .addOnGlobalLayoutListener(
            new OnGlobalLayoutListener() {
              @Override
              public void onGlobalLayout() {
                getLocationOnScreen(tmpLocation);
                boolean isBehindStatusBar = tmpLocation[1] == 0;
                presenter.setBehindStatusBar(isBehindStatusBar);
                setDrawTopInsetForeground(isBehindStatusBar);

                Context context = getContext();
                if (context instanceof Activity && VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
                  boolean isBehindSystemNav =
                      ((Activity) context).findViewById(android.R.id.content).getHeight()
                          == getHeight();
                  boolean systemNavNotFullyTransparent =
/* >>>>>>>> */        ((Activity) context).getWindow().getNavigationBarColor() == Color.TRANSPARENT;
                  setDrawBottomInsetForeground(isBehindSystemNav && !systemNavNotFullyTransparent);
                }
              }
            });
  }
```

**Android API version:** 21+

**Material Library version:** 1.1.0-alpha10

**Device:** Sony Xperia X Compact, any

**Comment by ldjcmu** [comment]
Thanks for the detailed explanation and report. We'll take a look.

**Comment by consp1racy** [comment]
@ymarian The described logic error remains.

NavigationView draws a scrim... if there's already a non-transparent navigation bar color.

To me that doesn't make sense. Shouldn't it draw its own scrim if there's *none* provided by the window?
