### ISSUE TITLE
Unable to use Material Card view

### ISSUE THREAD

**Issue by MeiyappanKannappa** [material-components/material-components-android#63]
Hi,

I have been trying to add material card view to my preoject. When I add as shown in documentation, it shows class not found exception. I have the below dependencies in my build.gradle. Can you help me

 implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    compile "com.android.support:appcompat-v7:26.1.0"
    compile 'com.android.support:design:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:0.5'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:2.2.2'
    implementation 'com.android.support:cardview-v7:26.1.0'

**Comment by shadowsheep1** [comment]
I've got the same issue. Did you find any solution?

**Comment by MeiyappanKannappa** [comment]
No I havent. I started using Native android material view

**Comment by gabrielittner** [comment]
You need to use version 28.0.0-alpha1

**Comment by shadowsheep1** [comment]
That's true, but so it should be better to tell that in docs. Ain't it?

![mdc-android](https://user-images.githubusercontent.com/16268789/37398619-60d62626-277f-11e8-8580-b74614da3173.png)

**Comment by debswinney** [comment]
Gah! I've just spent two hours trying to work out what I did wrong, and this is the answer. Update to P (28). The docs really need to say this.

**Comment by dsn5ft** [comment]
I believe this is covered by our Getting Started guide - https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md
