### ISSUE TITLE
[BadgeDrawable] add margin for Badge

### ISSUE THREAD

**Issue by Chaoyang0201** [material-components/material-components-android#630]
I'm using badge with `BottomNavigationView` ,  
but the badge position only change  by  `gravity` ,
so I can't  control the position of badge 

Is there any plan to add  something like `margin`  to control the position of badge?

**Comment by wcshi** [comment]
Hi @Chaoyang0201 could you please explain how you'd like to position the badge and why `gravity` is not sufficient?

**Comment by Chaoyang0201** [comment]
Hi @wcshi 

for example,

I want let a badge could cover the top right corner of the button icon like this 
![image](https://user-images.githubusercontent.com/22463627/65698885-d0e3cf00-e0af-11e9-9251-0aa4d57998de.png)

but  using `gravity` can't let badge over the icon .

**Comment by wcshi** [comment]
I checked with our designers and they agree with supporting your use case, will add this to our next sprint.

**Comment by Chaoyang0201** [comment]
> sprint

Glad to hear this : )

**Comment by wcshi** [comment]
The associated PR has been pulled in internally, waiting for the changes to be synced out.

**Comment by aznj** [comment]
I saw the commit. How to use it to reposition the badge?

**Comment by Chaoyang0201** [comment]
> I saw the commit. How to use it to reposition the badge?

if you are using BottomNavigationView, you can reposition the badge like this 
```java
BadgeDrawable badge = bottomNavigationView.getOrCreateBadge(YOUR_MENU_ITEM_ID);
badge.setHorizontalOffset(px);
badge.setVerticalOffset(px);
```

**Comment by miladsalimiiii** [comment]
@dsn5ft  , Did you add this feature?

**Comment by Chaoyang0201** [comment]
> > I saw the commit. How to use it to reposition the badge?
> 
> if you are using BottomNavigationView, you can reposition the badge like this
> 
> ```java
> BadgeDrawable badge = bottomNavigationView.getOrCreateBadge(YOUR_MENU_ITEM_ID);
> badge.setHorizontalOffset(px);
> badge.setVerticalOffset(px);
> ```

@miladsalimiiii  have a try

**Comment by miladsalimiiii** [comment]
> > > I saw the commit. How to use it to reposition the badge?
> > 
> > 
> > if you are using BottomNavigationView, you can reposition the badge like this
> > ```java
> > BadgeDrawable badge = bottomNavigationView.getOrCreateBadge(YOUR_MENU_ITEM_ID);
> > badge.setHorizontalOffset(px);
> > badge.setVerticalOffset(px);
> > ```
> 
> @miladsalimiiii have a try

Thank you this work on alpha and beta version.
