### ISSUE TITLE
[BottomSheetDialog] Crash when call dimiss()

### ISSUE THREAD

**Issue by Maxwell6635** [material-components/material-components-android#632]
**Description:** 
Implemented BottomSheetDialogFragment and when tried to dimiss the BottomSheetDialogFragment by calling dismiss() its throw error

**Expected behavior:** its shouldn't crash

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.
Crash log :
java.lang.ClassCastException: androidx.appcompat.app.AlertDialog cannot be cast to com.google.android.material.bottomsheet.BottomSheetDialog at com.google.android.material.bottomsheet.BottomSheetDialogFragment.getDialog(BottomSheetDialogFragment.java:64)

**Android API version:** 23

**Material Library version:** 1.1.0-alpha10

**Device:** Huawei P9 Plus

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by Maxwell6635** [comment]
Tested in working fine in 1.1.0-alpha09 version.

**Comment by ldjcmu** [comment]
Hi Maxwell6635,

I've verified on our up-to-date implementation of BottomSheetDialogFragment, that

1. creating a BottomSheetDialogFragment
2. showing the fragment
3. dismissing the fragment

does not cause an exception. Can you share your implementation of BottomSheetDialogFragment, so that we can understand the issue a bit better?

**Comment by Maxwell6635** [comment]
@ldjcmu 

Here are my implementation of BottomSheetDialogFragment class.

`public class UnitSelectionBottomSheetDialogFragment extends BottomSheetDialogFragment {
    private static final String UNIT_LIST = "unitList";

    private FragmentUnitSelectionBottomSheetDialogBinding mBinding;
    private GroupAdapter adapter;
    private Section section;
    private ProgressSectionItem progressSectionItem;
    private List<Unit> list;
    private String json;
    private OnItemClick itemClick;

    public static UnitSelectionBottomSheetDialogFragment newInstance(String json) {
        UnitSelectionBottomSheetDialogFragment f = new UnitSelectionBottomSheetDialogFragment();
        Bundle args = new Bundle();
        args.putString(UNIT_LIST, json);
        f.setArguments(args);
        return f;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        json = getArguments().getString(UNIT_LIST);
    }

    public interface OnItemClick {
        void onItemClick(Unit unit);
    }


    public void setItemClick(OnItemClick itemClick) {
        this.itemClick = itemClick;
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        ContextThemeWrapper wrapper = new ContextThemeWrapper(getContext(), R.style.AppTheme_Dialog_NoTitle);
        mBinding = DataBindingUtil.inflate(LayoutInflater.from(wrapper), R.layout.fragment_unit_selection_bottom_sheet_dialog, null, false);
        mBinding.btnNegative.setText(android.R.string.cancel);
        mBinding.btnNegative.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                dismissAllowingStateLoss();
            }
        });

        adapter = new GroupAdapter();
        adapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(Item item, View view) {
                if (item instanceof UnitItem) {
                    Unit unit = ((UnitItem) item).getItem();
                    if (unit != null)
                        itemClick.onItemClick(unit);
                }
            }
        });

        section = new Section();
        adapter.add(section);
        progressSectionItem = new ProgressSectionItem(new ProgressItem());
        adapter.add(progressSectionItem);
        EmptyViewObserver.attach(mBinding.recyclerview, mBinding.empty, adapter);
        mBinding.recyclerview.setAdapter(adapter);

        list = Unit.toList(json);

        if (list != null && !list.isEmpty()) {
            List<UnitItem> items = new ArrayList<>(list.size());
            for (int i = 0; i < list.size(); i++) {
                UnitItem item = new UnitItem(list.get(i));

                items.add(item);
            }
            section.update(items);
        }

        return new AlertDialog.Builder(wrapper)
                .setView(mBinding.getRoot())
                .create();
    }

}
`

Here are the calling method.
`
UnitSelectionBottomSheetDialogFragment bottomSheetDialogFragment = UnitSelectionBottomSheetDialogFragment.newInstance(Util.getGson().toJson(project.getOwnedUnits()));
bottomSheetDialogFragment.show(getSupportFragmentManager(), bottomSheetDialogFragment.getTag());
bottomSheetDialogFragment.dismiss(); 
`

I am using this version androidx.appcompat:appcompat:1.1.0 library.

**Comment by Maxwell6635** [comment]
@ldjcmu 

Hey thanks for the update. Alright thanks for the willing changing the code to make it work for the moment. 

Noted, I will check that in future. If this out-of-support, I might rewrite it again the code to make it works.
