### ISSUE TITLE
[ChipDrawable] ChipDrawable Bitmap

### ISSUE THREAD

**Issue by arangob** [material-components/material-components-android#634]
I need a Bitmap image of a`ChipDrawable` that retains the textAttribute (font) I want. When I assign the `ChipDrawable` to an `ImageView` by calling...

`imageView.setImageDrawable(chipDrawable)`

... I get the desired "look". But what I need for my use case, is a Bitmap. When calling...

```
val chipDrawableBitmap = chipDrawable.toBitmap(); 
imageView.setImageBitmap(chipDrawableBitmap)
```

...it looses the textAttribute (font). Is there anything to fix this?

![chips](https://user-images.githubusercontent.com/23018595/65792776-4cc63180-e119-11e9-92a7-bb07590d1504.png)

fragment.kt
```
        val view = findViewById<LinearLayout>(R.id.test_space)
        val chip = ChipDrawable.createFromResource(context, R.xml.standalone_chip)
        chip.text = "Alexander Wang"
        chip.setBounds(0, 0, chip.getIntrinsicWidth(), chip.getIntrinsicHeight())
        view.findViewById<ImageView>(R.id.test_image).setImageDrawable(chip)

        var chipBitmap = chip.toBitmap()
        view.findViewById<ImageView>(R.id.test_image_2).setImageBitmap(chipBitmap)
```

styles.xml
```
    <style name="MyChip" parent="Widget.MaterialComponents.Chip.Choice">
        <item name="fontFamily">@font/gotham</item>
        <item name="android:fontFamily">@font/gotham</item>
        <item name="android:textSize">22dp</item>
    </style>

```

standalone_chip.xml
```
<chip
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:closeIconVisible="false"
    android:text="Alexander Wang"
    android:layout_width="wrap_content"
    android:lineSpacingExtra="4sp"
    android:padding="8dp"
    android:textColor="@color/textColorWhite"
    app:chipBackgroundColor="@color/brand_chip_bg"
    android:layout_height="wrap_content"
    app:chipSurfaceColor="@color/brand_chip_bg"
    android:textAppearance="@style/MyChip"/>
```

layout.xml
```
        <LinearLayout
            android:id="@+id/test_space"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <ImageView 
                android:id="@+id/test_image" 
                android:layout_width="wrap_content" 
                android:layout_height="wrap_content"/>
            <ImageView 
                android:id="@+id/test_image_2"
                android:layout_width="wrap_content" 
                android:layout_height="wrap_content"/>
        </LinearLayout>
```

**Android API version:** 
'minSdk'             : 21,
'targetSdk'          : 28

**Material Library version:** 
'1.1.0-alpha10'

**Device:** 
Pixel 2

**Comment by ldjcmu** [comment]
Hi arangob,

We expect this difference is due to the font loading. setImageDrawable sets the Drawable but doesn't draw to canvas until the view is displayed. toBitMap will instantly draw to canvas and return. Because of this difference, you're seeing the difference above.

You'll need to update your code to force a load of the font or wait for the font to load.

**Comment by ldjcmu** [comment]
You may get some mileage out of com.google.android.material.resources.TextAppearanceConfig and ResourcesCompat.getFont which has onFontRetrievalFailed / onFontRetrieved callbacks.

**Comment by wcshi** [comment]
@arangob could you please explain why you want to get the chipdrawable's bitmap? Are you post-processing it in some way before setting it on the imageview?
