### ISSUE TITLE
[TextInputEditText] [TextInputLayout] Add property to indicate field is required

### ISSUE THREAD

**Issue by CACuzcatlan** [material-components/material-components-android#635]
**Is your feature request related to a problem? Please describe.**
The screenreader (TalkBack) does not tell users that a field is required. There is no way to indicate that information _only_ to the screen reader without changing the UI (hint text).

**Describe the solution you'd like**
A way to indicate to screen readers (such as TalkBack) via XML that an input field is required.
A new XML field `app:isRequired=[boolean]` that would default to false.

**Describe alternatives you've considered**
We have tried using `onInitializeAccessibilityNodeInfo` from `View.AccessibilityDelegate` and it worked for adding additional info to the screen reader without changing the UI, but it also stopped announcing errors  - a bigger problem than what we're solving for

**Additional context**
We could add the word "Required" to the hint text on the `TextInputLayout` and it'll be read by the screen reader, but we are trying to do this without changing our UI.

**Comment by ldjcmu** [comment]
Hi CaCuzcatlan,

One clarifying question: How does a user know the field is required without a screen reader? Are you using color or some other designation?

In general, our accessibility (a11y) team asks us to avoid special attributes for screen readers; they are likely to recommend a UI change - which I know you're trying to avoid. I don't expect we're likely to make a change here on any relevant time frame, but I will get the proposal checked and would love to know the information above.

**Comment by CACuzcatlan** [comment]
Non-screen reader users know it's required the same way screen reader users do: the `Next` button to continue is disabled until the user enters a value in the `TextInputEditText`. 

This request for explicitly stating the field is required comes from our a11y testing. The situational context indicates that it is required since the button to continue is disabled until values are entered, but we were told it should say it's required for accessibility. We'd like to do this without adding the word "required" to our UI everywhere.

**Comment by ldjcmu** [comment]
Can you modify the contentDescription to do this? I don't expect we want to add the attribute as described to our library.

**Comment by Cliabhach** [comment]
@CACuzcatlan For what it's worth, my team was given a very similar task not too long ago. The solution we agreed upon had us change the **helper** text, not the hint. I know that the helper text is still part of the visual UI, but perhaps that approach would be acceptable?

**Comment by vick08** [comment]
Just to clarify...
There is currently no attribute in Android Accessibility framework that would allow expressing the "required" state semantically. Presently, the only way to communicate to a screen reader user that the field is required is through UI treatment, e.g. marking up with a "*" sign or the word "required" (if feasible).
The above suggestion that a "disabled"  "next" button is a good signal is not entirely accurate because it does not tell the user which of the fields is a culprit.

**Comment by drchen** [comment]
I think there's a very low chance for us to add this support. The reason is as stated above by @ldjcmu. 
Please consider other workarounds like using hint or helper text.

Will close the issue for now.
