### ISSUE TITLE
[TextInputLayout] Cursor doesn't follow user typing at the end of the view

### ISSUE THREAD

**Issue by luisfelipeas5** [material-components/material-components-android#636]
**Description:**

User starts to type a long text and when the cursor "hits" the end of the view, the EditText not scroll horizontally and all the letters typed by user after that is not shown. To see the text typed, user needs to scroll the EditText manually.

In others words, the cursor is not following the end of the text that user types as normal.

**Source code:**

On XML:
```xml
<com.google.android.material.textfield.TextInputLayout android:id="@+id/tilEmail"
        android:layout_width="0dp"
        android:layout_height="wrap_content">
        <EditText android:id="@+id/etEmail"
            android:inputType="textEmailAddress"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>
</com.google.android.material.textfield.TextInputLayout>
```

On gradle
```groovy
api 'androidx.legacy:legacy-support-v4:1.0.0'
api 'androidx.appcompat:appcompat:1.1.0'
api 'androidx.core:core-ktx:1.0.2'
api "com.google.android.material:material:1.0.0"
```

**Android API version:** Tested on API 28

**Device:** Pixel 3

**Comment by Paulonuh** [comment]
Using **TextInputEditText**.

Try `android: scrollbars="vertical"`. 
Version api `"com.google.android.material: material: 1.0.0"`

**Comment by luisfelipeas5** [comment]
This worked solved my solution partially, because when I use `android:windowSoftInputMode="adjustPan"`, the problem keep happening

**Comment by parohy** [comment]
Ok so I'm confused. Some one asks for advice or explanation. Some one gives an answer. Then, some one else just closes the issue without a comment. After closing some one comments this solved his problem. What? Nothing above works for me.
