### ISSUE TITLE
What version of library to use post androidX?

### ISSUE THREAD

**Issue by apexkid** [material-components/material-components-android#639]
Hi, I have upgraded to androidX. However on some devices i am facing this error:
```
Binary XML file line #120: Binary XML file line #120: Error inflating class com.google.android.material.textfield.TextInputLayout
```

Based on SO, i need to upgrade this library. I am currently using `1.0.0`. What is the right stable version to use post androidx upgrade?

**Comment by ldjcmu** [comment]
Hi apexkid,

There are currently no stable versions after 1.0.0. We are planning to release a beta this week based on 1.1.0-alpha10 with several bug fixes and updates. If you can wait the week, I'd recommend waiting for that update. If you can't, the 1.1.0-alpha10 will be very close to what you need.

Stable should follow the beta "soon," but I don't have a definitive time frame on that.
