### ISSUE TITLE
[FAB] FAB layout (not FAB itself) does not resize with fabCustomSize

### ISSUE THREAD

**Issue by tranquoctrungcntt** [material-components/material-components-android#640]
I would like to resize my fab to 24dp but the fabCustomSize just resize the Fab itself, not resize the layout surrounds it.

```
 <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/floating_action_button"
        style="@style/Widget.MaterialComponents.FloatingActionButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|right"
        android:layout_margin="16dp"
        app:fabCustomSize="24dp"
        app:layout_anchor="@+id/linear_to_anchor"
        app:layout_anchorGravity="end|top"
        app:srcCompat="@drawable/ic_xcross_red" />

```

![Annotation 2019-09-29 124725](https://user-images.githubusercontent.com/33772899/65826961-6bfac580-e2b7-11e9-9ab0-acde22aa8b23.png)

**Comment by ymarian** [comment]
This is because touch targets should be at least 48dp to ensure they are accessible. 

https://material.io/design/usability/accessibility.html#layout-typography

You can disable this by setting 

app:ensureMinTouchTargetSize="false"
