### ISSUE TITLE
[Chip] Why do you prevent developers from setting the gravity on chips?

### ISSUE THREAD

**Issue by egemenhamutcu** [material-components/material-components-android#641]
I want to use Chips with Choice style working like RadioButton. For example, I put 4 chips in a LinearLayout horizontally and set each of their width as the quarter of the screen. I wanted to set text gravity as center but you give a log with this message:

> Chip text must be vertically center and start aligned

I figured out that you prevented developers from setting the gravity on chips in this commit:
[Prevent users from setting the gravity on chips, chip text must be vertically center and start aligned.](https://github.com/material-components/material-components-android/commit/aedfc1cf7c13e7e7005a0dd40e7f8b3918268f6c)

My opinion is that this prevention is too much for us. This also decreases the usage rate of this component. Chip would be a great competitor against `SegmentedControl` in iOS.

**Comment by wcshi** [comment]
Hi @egemenhamutcu 

Thank you for the question. This is intentional to comply with spec guidance. For a component similar to `SegmentedControl` in iOS, please try [`MaterialButtonToggleGroup`](https://material.io/develop/android/components/material-button-toggle-group/)

**Comment by sindicly** [comment]
I don't think it's easy to set the gravity of the chip. It's not scalable at all. I don't want to center the text.
