### ISSUE TITLE
[BottomNavigationView] BottomNavigationView.md references removed method

### ISSUE THREAD

**Issue by firekesti** [material-components/material-components-android#642]
**Is your feature request related to a problem? Please describe.**
Outdated documentation

**Describe the solution you'd like**
Updated documentation

**Describe alternatives you've considered**
n/a

**Additional context**
https://github.com/material-components/material-components-android/blob/master/docs/components/BottomNavigationView.md still references the `showBadge` method which was renamed (and behaviour changed?) back in June: https://github.com/material-components/material-components-android/commit/ee913784dcca06c5778267f569c3733612bf3b72#diff-3e5579d62b299857e3a67168b5fac1c9

**Comment by wcshi** [comment]
Thank you for reporting the issue. This has been updated internally and will be synced out shortly.
