### ISSUE TITLE
[BadgeDrawable] badge to close to bottom navigation view border

### ISSUE THREAD

**Issue by addyi** [material-components/material-components-android#643]
**Description:** I updated from version 1.1.0-alpha08 to version 1.1.0-alpha10. If I now add a badge to a bottom navigation view entry it touches the border of the bottom navigation view.
 
![image](https://user-images.githubusercontent.com/7873672/65974371-241d9f00-e46d-11e9-88e0-aafdabd77c56.png)

I assume @Chaoyang0201 got the same or a related problem and thus opened this "related" issue https://github.com/material-components/material-components-android/issues/630 with this PR https://github.com/material-components/material-components-android/pull/638.

**Expected behavior:** Bevor I updated to 1.1.0-alpha10 the bedge was a little bit lower

![image](https://user-images.githubusercontent.com/7873672/65974196-d012ba80-e46c-11e9-861e-2f74cf5ded11.png)

**Source code:** I forked this repo and added a badge in the bottom navigation view and got the same result. You can find my changes here https://github.com/addyi/material-components-android/commit/de4a2d011cf6cfe02e751117d43c79a0591def0c and can also clone this repo to get the same result.

![image](https://user-images.githubusercontent.com/7873672/65973916-61356180-e46c-11e9-816c-bdb93b566a18.png)

**Android API version:** Android 10.0 (Q) API 29 also tested on Android 8.1.0

**Material Library version:** Before "Bug" 1.1.0-alpha08, with "Bug" 1.1.0-alpha10

**Device:** Pixel 3 and Nexus 6P

**Comment by firekesti** [comment]
<img width="1128" alt="bottom-nav-badge-change" src="https://user-images.githubusercontent.com/599624/66161072-81465b80-e5f9-11e9-800d-fb2bc9f9c687.png">

Seeing the same issue, introduced in alpha10.

**Comment by wcshi** [comment]
Hi @addyi the visual delta you observed is an expected behavior caused by new design guidance to avoid overlapping the anchor.
PR #638 has been pulled in and #630 is closed, please use the newly introduced setters to adjust the badge's position w.r.t. the anchor.
