### ISSUE TITLE
[Theme.MaterialComponents] Theme.MaterialComponents crashes on devices < 8.1

### ISSUE THREAD

**Issue by zishanj** [material-components/material-components-android#645]
I am using stable version of Material components 1.0.0. I am receiving this error on devices < 8.1:

> java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

In my `AndroidManifest.xml`, I am using:
> android:theme="@style/AppTheme"

and in styles:
> <style name="BaseAppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">

Android versions 8.1 and above are working fine. My app supports minimum SDK 21.

**Comment by gabrielemariotti** [comment]
In which way `AppTheme` and `BaseAppTheme` are related?

**Comment by zishanj** [comment]
This is in my `v26/Styles`:
> <style name="AppTheme" parent="BaseAppTheme">

My `MainActivity` extends from `AppCompatActivity` and it crashes on < 8.1 devices.

**Comment by zishanj** [comment]
My bad... I was missing this line from `styles.xml` and it fixed:
> <style name="AppTheme" parent="BaseAppTheme"/>

**Comment by gabrielemariotti** [comment]
It means that it inherits the MaterialTheme **only** for API 26+.  
Then for API< 26 if you are using an AppCompat Theme the message
> `java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`

seems correct.
