### ISSUE TITLE
Chip: dark theme support

### ISSUE THREAD

**Issue by gabrielittner** [material-components/material-components-android#65]
It would be great if Chip's could adapt to dark themes. Currently they still have their light grey background, dark text, and dark ripple. While it kind of works it's far from perfect and looks a bit of.

### Reproduction steps

 - Use `Theme.MaterialComponents` or any other dark theme
 - add some chips to a layout

### Version number

 - 28.0.0-alpha1

### Operating system and device
 
 - Emulator API 27 and P

**Comment by kptlronyttcna** [comment]
It would also be great if it was possible to set custom background for different states. For example if I want to use the primary color for selected state.

**Comment by wcshi** [comment]
@kptlronyttcna you can set a custom background for different states by using a CSL and using app:chipBackgroundColor.

@gabrielittner chip now supports dark theme.
