### ISSUE TITLE
[Many] Lack of elevation on pre-Lollipop cause major color issues

### ISSUE THREAD

**Issue by henrik-lindqvist** [material-components/material-components-android#652]
**Description:** 
`MaterialShapeDrawable` is used everywhere as background drawable to support material shapes and fake shadows, its "elevation" is important as it seems to affect its color/shade, i.e. becoming brighter with increased elevation on a dark theme.

But lots of components have no default elevation, ignores any `app:elevation` attribute, or incorrectly gets it from some other view using `ViewCompat.getElevation()` which always returns zero on pre-Lollipop devices.

This has major consequences on pre-Lollipop, especially when using a dark theme, e.g. DayNight, where the `AppBarLayout` and dialog backgrounds become black at zero elevation. For screenshorts, see my related issue report: https://issuetracker.google.com/issues/142127327

`AppBarLayout` rely on a `StateListAnimator` which is only available/set on Lollipop:
https://github.com/material-components/material-components-android/blob/release-1.1/lib/java/com/google/android/material/appbar/AppBarLayout.java#L238

`MaterialAlertDialogBuilder` and `MaterialDatePicker` get their elevation from decorView, which is always zero on pre-Lollipop:
https://github.com/material-components/material-components-android/blob/release-1.1/lib/java/com/google/android/material/dialog/MaterialAlertDialogBuilder.java#L147
https://github.com/material-components/material-components-android/blob/release-1.1/lib/java/com/google/android/material/datepicker/MaterialDatePicker.java#L169

Some components like `NavigationView` do the right thing, honoring `app:elevation` attribute, and thus work as expected:
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/navigation/NavigationView.java#L155

More components are probably affected by this bug/oversight. It seems few components have been properly tested on pre-Lollipop with a dark theme.

**Expected behavior:**
Toolbars and dialogs having the same/similar colors both pre and post Lollipop. On pre-Lollipop i'd expect the components to get (fallback) elevation from their respective theme/style, i.e. an `app:elevation` attribute, or in some other way,

**Android API version:**
Android 4.0 thru 4.4

**Material Library version:** 
com.google.android.material:material:1.1.0-beta01

**Device:**
Emulator

**Comment by dsn5ft** [comment]
Thanks for the report. This is a known issue that we will likely prioritize for an upcoming beta release.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
