### ISSUE TITLE
[FloatingActionButton] Missing "speed dial" feature from material spec

### ISSUE THREAD

**Issue by Raenar4k** [material-components/material-components-android#656]
**Is your feature request related to a problem? Please describe.**
The speed dial (menu of three to six related actions) is in material guidelines, but it is not implemented in FAB component.

**Describe the solution you'd like**
Implementation of material dial from design spec.
As material guidelines state:
https://material.io/components/buttons-floating-action-button/#types-of-transitions
> When pressed, a FAB can display three to six related actions in the form of a speed dial. This transition can occur in one of the following ways:
> 
> Upon press, the FAB can emit related actions
> Upon press, the FAB can transform into a menu containing related actions (Android only)

**Describe alternatives you've considered**
Using third party library.

**Additional context**
The other mention of this was in this issue, that is marked as closed:
https://issuetracker.google.com/issues/37072655

**Comment by MGaetan89** [comment]
This is also requested in #12

**Comment by drchen** [comment]
Duplicate to https://github.com/material-components/material-components-android/issues/12
