### ISSUE TITLE
[BadgeUtils] RestrictTo(Scope.LIBRARY)

### ISSUE THREAD

**Issue by gabrielemariotti** [material-components/material-components-android#657]
Currently the `BadgeUtils` class can be called from within the same library since it is marked with `@RestrictTo(Scope.LIBRARY)`.

Are you planning to remove the restriction in the next releases?

**Comment by ymarian** [comment]
We will open up the class when we have the API finalized you can suppress the warning of using it if you need it in the meantime.

We use this annotation to give us some room to make breaking API changes.

**Comment by gabrielemariotti** [comment]
Thanks for the feedback

**Comment by wcshi** [comment]
Discussed this with them, seems reasonable to us. Before we open this, we'd like to switch badge to use ViewOverlayImpl so that it can use OverlayApi14 for pre-api 18 instead of setting the badge as the anchor's foreground.

**Comment by wcshi** [comment]
After some quick prototyping, discovered that neither `ViewUtils#getOverlay` nor `ViewUtils#getContentViewOverlay` can easily support a badge moving (scrolling) with its anchor (current behavior in bottom nav and tabs).

Next step is to try wrapping the anchor view in a framelayout (which naturally scrolls based on its parent), copy the anchor view's layout params and replace the anchor view with the framelayout in the view hierarchy

**Comment by wcshi** [comment]
Resolved in https://github.com/material-components/material-components-android/commit/5e35d14c187b65b32788cce28d758657f1b5aebb

rolledback in https://github.com/material-components/material-components-android/commit/0f717f8cce9bf669177f7c2fccb1a747b26dfa81, rolled forward in https://github.com/material-components/material-components-android/commit/9487c33b8ab50edbcff46cf728531712ab091a85
