### ISSUE TITLE
[BottomSheetBehavior] Support multiple callbacks

### ISSUE THREAD

**Issue by lwasyl** [material-components/material-components-android#658]
Right now BottomSheetBehavior only supports setting single callback via `setBottomSheetCallback`. Unfortunately this doesn't work well with e.g. data binding, where ideally we'd set a callback for every binding that we want to handle (e.g. one two-way binding to bind expanded state, and one two-way binding to bind expanded percentage). Outside databinding a view might want to set the callback as well.

Ideally `BottomSheetBehavior` would support multiple listeners.

Currently one alternative is to subclass `BottomSheetBehavior`, where the subclass would set single callback and proxy calls to multiple callbacks it would manage. Other alternative would be to hold a composing/proxy callbacks manager in the view's tag and set callbacks there. Both seem like a workaround that shouldn't be necessary.

**Comment by ymarian** [comment]
This was addressed here:

https://github.com/material-components/material-components-android/commit/fd13d162926d2c37f506740d6e5c4bf276425308

Should be available in 1.1.0-beta01

https://github.com/material-components/material-components-android/releases/tag/1.1.0-beta01
