### ISSUE TITLE
Publish FlexboxLayout or add dependency for it

### ISSUE THREAD

**Issue by gabrielittner** [material-components/material-components-android#66]
`ChipGroup` is currently using an internal version of [FlexboxLayout][0] which seems to be the same as this [Google library][1]. I'm already using the latter `FlexboxLayout` directly, so right now I've got it in my app two times. Could you depend on the library directly? If that isn't possible because you're only depending on support libraries, could you publish `FlexboxLayout` either as support library or as material component?

### Version number

 - 28.0.0-alpha1

[0]: https://github.com/material-components/material-components-android/blob/master/lib/java/android/support/design/internal/FlexboxLayout.java
[1]: https://github.com/google/flexbox-layout

**Comment by ymarian** [comment]
We have now removed the FlexboxLayout dependency.

**Comment by cketcham** [comment]
Commit 3c3ac61 should have resolved #661 instead of this one.
