### ISSUE TITLE
[NavigationView] Separators should inherit size of ?android:listDivider

### ISSUE THREAD

**Issue by tadfisher** [material-components/material-components-android#662]
**Is your feature request related to a problem? Please describe.**

The separator view in `@layout/design_navigation_item_separator` is hardcoded to a height of 1dp. Our app uses a different size for the `?android:listDivider` drawable, so our navigation drawer is inconsistent with the rest of our app.

**Describe the solution you'd like**

I would like the separators in `NavigationView` to be consistent with other usages of separators in our app; for example, RecyclerView's `DividerItemDecoration` uses the intrinsic size of the `?android:listDivider` drawable by default.

**Describe alternatives you've considered**

I've considered forking Material Components for Android and changing the height of the separator view to `wrap_content`, as `NavigationMenuPresenter` is hidden and restricted.

**Comment by ymarian** [comment]
see https://github.com/material-components/material-components-android/pull/663
For the suggested alternative
