### ISSUE TITLE
[DatePicker] theme for dialog

### ISSUE THREAD

**Issue by hrach** [material-components/material-components-android#664]
I wonder how to set theme to force picker to be a dialog.

Using `R.attr.materialCalendarTheme` as in catalog app isn't ok because these attrs are private.
```
int dialogTheme = resolveOrThrow(getContext(), R.attr.materialCalendarTheme);
int fullscreenTheme = resolveOrThrow(getContext(), R.attr.materialCalendarFullscreenTheme);
```

**Comment by ldjcmu** [comment]
Those are intended to be used. Making a change to make them public shortly.
