### ISSUE TITLE
[MaterialAlertDialog] Typography not working

### ISSUE THREAD

**Issue by MariusBoepple** [material-components/material-components-android#669]
**Description:** The `MaterialAlertDialogBuilder` is not using the typography which is defined in the app theme.

![Screenshot 2019-10-10 at 15 53 51](https://user-images.githubusercontent.com/11991870/66575436-32a73d00-eb76-11e9-98ba-649d0c4a13f7.png)

**Expected behavior:** The `AlertDialog` is automatically using `textAppearanceHeadline6` for the title, `textAppearanceBody1` for the message and `textAppearanceButton` for the buttons.

**Source code:** This is the theming:

```
<style name="MyTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
    ...
    <item name="textAppearanceHeadline6">@style/Mercedes.TextAppearance.Headline6</item>
    <item name="textAppearanceBody1">@style/MyTheme.TextAppearance.Body1</item>
    ...
</style>

<style name="MyTheme.TextAppearance.Headline6" parent="TextAppearance.MaterialComponents.Headline6">
    <item name="android:textAllCaps">true</item>
    <item name="android:textColor">@color/red</item>
    <item name="android:textSize">46sp</item>
</style>

<style name="MyTheme.TextAppearance.Body1" parent="TextAppearance.MaterialComponents.Body1">
    <item name="android:textAllCaps">false</item>
    <item name="android:textSize">30sp</item>
</style>
```

**Material Library version:** `1.1.0-beta01`

**Comment by MariusBoepple** [comment]
You're right, it's using `subtitle1` for the title - it should be using `headline6` like defined here: https://material.io/components/dialogs/#theming 

The body text is not using `body1` or `body2`, at least it's not working...

**Comment by ldjcmu** [comment]
The use of subtitle1 is intentional, but you're right that the spec needs to be updated.

Body text should be using body2, as defined in Base.V14.ThemeOverlay.MaterialComponents.MaterialAlertDialog via ThemeOverlay.MaterialComponents.MaterialAlertDialog.

Are you overriding the used theme overlay at all?

**Comment by ldjcmu** [comment]
Design has confirmed we should be using subtitle1 and body2. They will update the article so we are in-line.
