### ISSUE TITLE
[MaterialButton] Add support for TOP & BOTTOM icon gravity

### ISSUE THREAD

**Issue by ricard-v** [material-components/material-components-android#671]
**Is your feature request related to a problem? Please describe.**
Up until release `1.1.0-alpha06` back in May 2019, the only way to change the icon position was done using  `TextViewCompat.setCompoundDrawablesRelative`.

After introducing new method `setIconGravity` in release `1.1.0-alpha06`  it was finally possible to properly set the icon position, although only on the right or left, and close to the text or not.

**This now excludes the possibility to place the icon either on top or bottom relative to the text.**

**Describe the solution you'd like**
Please kindly add TOP & BOTTOM gravity as part of `@IconGravity`. 

**Describe alternatives you've considered**
As said at the beginning, before release `1.1.0-alpha06`, the only way to change the icon position was using `TextViewCompat.setCompoundDrawablesRelative`. 

This no longer works, as it triggers a `requestLayout` which, at some point, will trigger `updateIconPosition` and then `updateIcon` where only START/TEXT & END/TEXT are supported.

**Comment by matpag** [comment]
It is not a bad idea but currently the material guideline specs are against this scenario.
At some point here: https://material.io/components/buttons/#contained-button
You will find this image:
![Schermata 2019-10-11 alle 13 16 31](https://user-images.githubusercontent.com/4432213/66647555-83c43900-ec29-11e9-969d-d644c3559c04.png)
Which exactly cover this case

**Comment by hrach** [comment]
Actually, in Gmail, there are buttons which have the icon on the left, but when insufficient width is there, they push the icon on the top. Seems pretty useful.

![image](https://user-images.githubusercontent.com/284263/66648116-08fc1d80-ec2b-11e9-965b-395a6e2ced7c.png)
![image](https://user-images.githubusercontent.com/284263/66648163-27621900-ec2b-11e9-804b-77449535dc03.png)

**Comment by matpag** [comment]
> Actually, in Gmail, there are buttons which have the icon on the left, but when insufficient width is there, they push the icon on the top. Seems pretty useful.

Agree 100%, I think it is a useful feature

**Comment by ricard-v** [comment]
> > Actually, in Gmail, there are buttons which have the icon on the left, but when insufficient width is there, they push the icon on the top. Seems pretty useful.
> 
> Agree 100%, I think it is a useful feature

Yes this is exactly the point. The project's lead designer just told me "top icon is required to provide more flexibility with the text".

**Comment by ymarian** [comment]
We got approval from design to support adding gravity Top. However we'll leave the guideline in material.io since it should be only for edge cases

**Comment by ricard-v** [comment]
That's great news ! Thanks. When could I expect the support ?

**Comment by alex-dokienko** [comment]
Any news on this feature?

**Comment by antonkovalyov351** [comment]
Bump

**Comment by rewgoes** [comment]
Can you make it available on the next alpha version?

**Comment by rewgoes** [comment]
I've sent a PR adding **top** gravity only, let's wait if it is approved!

**Comment by kadaluarsa** [comment]
any update of this gravity top?  ☹️

**Comment by rewgoes** [comment]
The code for gravity top was merged. Should we close this issue? As I understood we are not going to support gravity bottom.

**Comment by rewgoes** [comment]
@ymarian do you know if the designers changed their mind about aligning icon on top?

**Comment by wcshi** [comment]
It was rolled back due to internal breakages, we are still trying to fix them so we can roll the change forward.

**Comment by rewgoes** [comment]
Let me know if I can help with any changes.

**Comment by rewgoes** [comment]
@ymarian can we close this issue?

**Comment by hunterstich** [comment]
Finally landed in b39845a452f547d5844996074ac9aabe911d637f. Thanks @rewgoes!

**Comment by karanjhinga** [comment]
Is it available for use now in any of the versions ?

**Comment by hunterstich** [comment]
@karanjhinga Not yet, no. It should be in the next 1.3.0-alpha02 release

**Comment by gabrielemariotti** [comment]
@karanjhinga you can use the [snapshot release](https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md)

**Comment by gmk57** [comment]
In MDC 1.3.0 I see `app:iconGravity="top"`, but what about `app:iconGravity="bottom"`?
