### ISSUE TITLE
[BottomSheetDialog] Frame with darker lines appears in dim area when minimize app

### ISSUE THREAD

**Issue by MaxCiv** [material-components/material-components-android#672]
**Description:** Frame with darker lines appears in dim area when minimize app.

**Expected behavior:** https://youtu.be/X3dwRpAeffk

**Source code:** https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/bottomsheet

**Android API version:** 27

**Material Library version:** 1.1.0-beta01

**Device:** Xiaomi Mi9T

**Comment by drchen** [comment]
Is this happening on other devices? If this is a Xiaomi-only issue, I'm afraid that is something beyond our control...

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
