### ISSUE TITLE
[Material Toolbar/Action Menu] Material Toolbar action menu incorrect background

### ISSUE THREAD

**Issue by Ezorrio** [material-components/material-components-android#674]
Screenshots of the issue

![image](https://user-images.githubusercontent.com/4018146/66700296-9a38c600-ecf7-11e9-940e-134cfecce063.png)
![image](https://user-images.githubusercontent.com/4018146/66700317-b2104a00-ecf7-11e9-956a-17f604513ade.png)
**Left (correct behavior):** Android 10 / **Right (incorrect behavior):** Android 5.1 
**Component:** Material Toolbar (com.google.android.material:material:1.1.0-beta01)
**Base Theme:** Theme.MaterialComponents.DayNight.NoActionBar

I'm passing app:theme attribute to Material Toolbar xml with following theme
```
<style name="Theme.Toolbar" parent="ThemeOverlay.MaterialComponents.Toolbar.Surface">
        <item name="android:tint">?colorOnSurface</item>
        <item name="actionMenuTextColor">?colorOnSurface</item>
        <item name="android:textColorPrimary">?colorOnSurface</item>
        <item name="android:textColorSecondary">?colorOnSurface</item>
</style>
```

**Comment by Ezorrio** [comment]
Might be related issue #576

**Comment by dsn5ft** [comment]
I think this is because of the `<item name="android:tint">?colorOnSurface</item>` which propagates to the menu background. Can you try removing that?
