### ISSUE TITLE
[Component CardView Sample] LineHeight isn't adjusting

### ISSUE THREAD

**Issue by kingargyle** [material-components/material-components-android#684]
**Description:** 
When making a modification to the line height, it isn't being reflected in the Card components texts.   This is happening because the TextViews in the component_cardview.xml are using the AppCompatTextView instead of the MaterialTextView.   Once I change the component_cardview.xml to use the MaterialTextView everything starts to display as expected.

**Expected behavior:** 
LineHeight adjustments should reflect in any of the textviews.

**Android API version:**
28 (or any of the supported versions)

**Material Library version:** 
1.1.0-beta01

**Device:** 
Samsung S9

If I get some time I'll try and get a pull request to fix the issue.

**Comment by ikim24** [comment]
Fixed in https://github.com/material-components/material-components-android/commit/ce83a9e4dd91c85f334036808cccbb411e9ca38d
