### ISSUE TITLE
Shape Theming crash

### ISSUE THREAD

**Issue by hafiz013** [material-components/material-components-android#685]
Shape Theming crash on android 9 in honor 8 pro.

**Comment by hafiz013** [comment]
> Hi there! Could you please provide your code and more information surrounding the crash?

no code. u just need install sample apk demo material components.

**Comment by ikim24** [comment]
Fixed in https://github.com/material-components/material-components-android/commit/aee272bb416ec56763eea90bc493fd8c8829f17e
