### ISSUE TITLE
[TextInputLayout] Nulling error causes currently displayed helper text to be hidden

### ISSUE THREAD

**Issue by azol** [material-components/material-components-android#687]
**Description:** Having helper text currently shown setting error to null causes helper text to be hidden.

**Expected behavior:** I expect that currently displayed helper text is not affected by setting error to null in any way. Simply do nothing. Having displayed helper text I expect that setting error to null does nothing. Setting error to some text displays error. Setting error to null hides error and shows initial helper text.

**Source code:**

```
textInput.apply {
    helperText = "Helper"
    isErrorEnabled = true
}

button.setOnClickListener(View.OnClickListener {
   textInput.error = null
})
```

**Android API version:** 29

**Material Library version:** 1.1.0-beta01

**Related:** #525

**Comment by VictorHarry** [comment]
Any luck getting around this problem?

**Comment by leticiarossi** [comment]
Closing this as a duplicate since it's due to the same issue in https://github.com/material-components/material-components-android/issues/525
