### ISSUE TITLE
MaterialTimePicker

### ISSUE THREAD

**Issue by jda-tid** [material-components/material-components-android#690]
I would like a `MaterialTimePicker` the same way we already have a `MaterialDatePicker`.

**Describe alternatives you've considered**
I would expect the same color design (current TimePicker does not change all colors) and shape definition

**Additional context**
Attached current `MaterialDatePicker` and default `TimePicker` with same Material Style:

![Screenshot_20191018-111912_2](https://user-images.githubusercontent.com/36664452/67082379-55021180-f199-11e9-94ba-00bc1b898331.png)
![Screenshot_20191018-111921_2](https://user-images.githubusercontent.com/36664452/67082378-55021180-f199-11e9-8b8b-986d4bfc2eb3.png)

**Comment by franciscofranco** [comment]
Is there are advances on implementing this widget?
