### ISSUE TITLE
[MaterialButtonToggleGroup] Corners don't handle visibility changes correctly

### ISSUE THREAD

**Issue by luismierez** [material-components/material-components-android#693]
**Description:** Changing visibility on children of a MaterialButtonToggleGroup does not fix the corners of the views that are now at the edges. 

**Expected behavior:** If the visibility of the outer view is set to `View.GONE` or `View.INVISIBLE` the corners for the inner view should go back to their original shape (i.e they should no longer be square)

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Material Library version:** 1.1.0-beta01

**Comment by ymarian** [comment]
I think GONE makes sense to support. I don't see a case for supporting View.INVISIBLE though.

In the meantime you can remove the views the views you don't need and them back when they are needed.

**Comment by luismierez** [comment]
Agreed on the GONE vs INVISIBLE.
That's what I'm doing now, which works a lot better now that MaterialButtonToggleGroup extends LinearLayout, but can get pretty annoying haha. Is there any eta on that change? I can also try to make a PR for it

**Comment by ymarian** [comment]
Stay tuned!
