### ISSUE TITLE
[Chip] Chip does not support the 4 parameter View constructor

### ISSUE THREAD

**Issue by luky152** [material-components/material-components-android#694]
**Description**
We are using different Styles for the Chips in the application. We have to create the View programmatically and therefore apply the style also programmatically, but this is a little bit tricky without a `defStyleRes` parameter in the constructor.   

**Suggestion**
Please add the `public View (Context context, AttributeSet attrs, int defStyleAttr,  int defStyleRes)` to the Chip. This should no big deal since the underlying ChipDrawable already supports `int defStyleRes`. 

**Workaround**
If anybody has this problem, you can simply create your Chip using the ChipDrawable class and set the ChipDrawable to the Chip view.

**Comment by gabrielemariotti** [comment]
Another possible workaround is to define a layout with a `Chip` and the style.

Example: `layout_chip_choice.xml`
```
<com.google.android.material.chip.Chip
    xmlns:android="http://schemas.android.com/apk/res/android"
    style="@style/Widget.MaterialComponents.Chip.Choice"
    .../>

```

Then use in your code:

```
val chip = inflater.inflate(R.layout.layout_chip_choice, chipGpRow, false) as Chip  
chip.text = ("Chip 1")
chipGpRow.addView(chip)
```

**Comment by wcshi** [comment]
Hi, we don't think it's possible to add a 4 parameter constructor to Chip because AppCompatCheckbox does not support a 4 parameter constructor, if you disagree, please sent a PR :) that works for API 14+

https://developer.android.com/reference/kotlin/androidx/appcompat/widget/AppCompatCheckBox?hl=en#public-constructors
