### ISSUE TITLE
[MaterialDatePicker] Support date display localization for the manual date input

### ISSUE THREAD

**Issue by cbeyls** [material-components/material-components-android#695]
The displayed date format is not localized in the manual date input mode of `MaterialDatePicker`. So far in the code the same string is used for display and to create the `DateFormat` instance, which means only `dd` `MM` and `yyyy` can be used in the pattern and it will always be displayed in English.

**Desired solution**
Be able to provide a String used for date display, in addition to the String used to build the `DateFormat` instance. This String could be stored in resources as well, allowing the developer to override the value easily.

**Considered alternatives**
Using `SimpleDateFormat.toLocalizedPattern()` doesn't work as expected on Android because the Android implementation of `DateFormatSymbols` doesn't support loading localized pattern chars. It looks like they can be set manually on the `DateFormatSymbols` instance, however.

**Comment by Shusshu** [comment]
Same for the manual input it's always MM/dd/yyyy

**Comment by ldjcmu** [comment]
You should be able to override mtrl_picker_text_input_date_format and mtrl_picker_invalid_format on a per locale basis in order to have your desired patterns. For example (Spanish, Spain)
![Screenshot from 2019-11-05 16-48-38](https://user-images.githubusercontent.com/42812180/68249123-23d46e80-ffec-11e9-820f-ce43b413fcc0.png).

We do agree, we'd like to do this automatically for you.

**Comment by ldjcmu** [comment]
You should be able to override mtrl_picker_text_input_date_format and mtrl_picker_invalid_format to get your desired behavior on a per locale basis. We're looking into whether we can do this automatically for you.

**Comment by ldjcmu** [comment]
I also want to add that while those strings work right now, we may switch to DateFormat.getDateInstance(). I'm looking into this option this week.

**Comment by hikkidev** [comment]
@ldjcmu How can I override selected blocks ?
![image](https://user-images.githubusercontent.com/52655010/68523361-b45fc700-02ea-11ea-9e0f-703a9b28f770.png)
![image](https://user-images.githubusercontent.com/52655010/68523364-b9247b00-02ea-11ea-885b-ae5d8c5a159c.png)
