### ISSUE TITLE
[Slider] Floating label not visible

### ISSUE THREAD

**Issue by kaushalyap** [material-components/material-components-android#697]
**Description:** Floating label not visible in the slider

![Screenshot from 2019-10-22 19-43-05](https://user-images.githubusercontent.com/24698778/67295316-93366280-f504-11e9-9032-72df147e3fca.png)

**Expected behavior:** [show floating label](https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1R7E69M9c12aTaQcXnpT8FveOtq3a_GOf%2Fsliders-layout-elements.png)

**Source code:**

```
<com.google.android.material.slider.Slider
        android:id="@+id/slider"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:valueFrom="20f"
        android:valueTo="70f"
        android:stepSize="10"
        app:floatingLabel="true"
        />
```

**Android API version:** 23, 28 (probably not version specific)

**Material Library version:** 1.2.0-alpha01

**Device:** Pixel 2 emulator, LG Zero (probably not device specific)

**Comment by kaushalyap** [comment]
Problem seem that the view is not expanding to contain the floating label

**Comment by kaushalyap** [comment]
Even `tickColor` does not change

**Comment by gabrielemariotti** [comment]
Using something like:

```
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:clipChildren="false"
        android:clipToPadding="false"
        android:orientation="vertical">

        <com.google.android.material.slider.Slider
           android:id="@+id/slider"
           .../>

    </LinearLayout>
```
it works.

<img width="296" alt="Schermata 2019-10-22 alle 09 50 03" src="https://user-images.githubusercontent.com/2583078/67282082-2e154980-f4d1-11e9-9f5f-b6bd11190e03.png">

**Comment by kaushalyap** [comment]
@gabrielemariotti why do I have to modify the container layout?

**Comment by kaushalyap** [comment]
@gabrielemariotti This is what I see even with clipping

![Screenshot from 2019-10-22 19-43-05](https://user-images.githubusercontent.com/24698778/67295099-536f7b00-f504-11e9-8034-935eabca65ab.png)

same thing I saw earlier, sorry for incorrect image, updated the OP.

**Comment by kaushalyap** [comment]
@gabrielemariotti forgive me, my mistake. Although I set both to false, I still get the previous output (top portion of the label is still clipped)

```
<LinearLayout ...>

    <LinearLayout ...
        android:clipToPadding="false"
        android:clipChildren="false">

        <com.google.android.material.slider.Slider
            android:id="@+id/slider"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:valueFrom="20f"
            android:valueTo="70f"
            android:stepSize="10"
            app:floatingLabel="true"
            />

    </LinearLayout>
</LinearLayout>
```

**Comment by somename6668** [comment]
use 
`app:floatingLabel="false" `
to show floating label.

**Comment by brandscill** [comment]
![image](https://user-images.githubusercontent.com/6613504/70161665-59847a00-16b4-11ea-92de-35a4abd199a3.png)
I am getting the issue above where the floating label is slightly clipped.

Any ideas?

 <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginTop="8dp"
        android:layout_marginEnd="16dp"
        android:clipChildren="false"
        android:clipToPadding="false"
        android:gravity="center_vertical"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/rfidPowerLevelLabel">

        <com.google.android.material.slider.Slider
            android:id="@+id/rfidPowerLevel"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:stepSize="10"
            android:valueFrom="10"
            android:valueTo="270"
            android:visibility="invisible"
            app:floatingLabel="false" />

        <TextView
            android:id="@+id/rfidPowerLevelValue"
            android:layout_width="48dp"
            android:layout_height="wrap_content"
            android:visibility="invisible" />
    </LinearLayout>``

**Comment by kaushalyap** [comment]
@somename6668 Strange! setting it to false worked, is not setting it to false should disable the floating label?

@gabrielemariotti  top of the floating label is clipped as @brandscill mentioned

**Comment by cketcham** [comment]
We should have a solution soon which removes the requirement of setting `clipChildren` etc.
