### ISSUE TITLE
[TextInputLayout] Features for prefix and suffix

### ISSUE THREAD

**Issue by ViHtarb** [material-components/material-components-android#698]
**Is your feature request related to a problem? Please describe.**
Phone edit field with country code as prefix

**Describe the solution you'd like**
Implement the possibility to add click listeners and "always visibility" option for prefix and suffix. In my case this needs for show country code picker(dialog).

**Describe alternatives you've considered**
In my implementation i use `SpannableString` with `ClickableSpan` for listening click action on country code.

![Снимок](https://user-images.githubusercontent.com/8938207/67282949-6e79c500-f4db-11e9-9c80-d59d5c4083ec.PNG)

**Comment by gabrielemariotti** [comment]
The prefix and suffix were added in the 1.2.0-alpha01.

Check this [commit](https://github.com/material-components/material-components-android/commit/55f85bcc6ef0f4b49c7cb2972de3c7059a5ff9af).

```
       <com.google.android.material.textfield.TextInputLayout
            app:prefixText="@string/..."
            app:prefixTextColor="@color/..."
            app:suffixText="@string/..."
            app:suffixTextColor="@color/...."
```

<img width="313" alt="Schermata 2019-10-22 alle 10 11 11" src="https://user-images.githubusercontent.com/2583078/67283443-f8259480-f4d3-11e9-878c-c7211437e84c.png">

**Comment by ViHtarb** [comment]
@gabrielemariotti i know. I mean implement additional features. But when i creating feature request i dont seen the getPrefixTextView() and getSuffixTextView() methods. Sorry

**Comment by gabrielemariotti** [comment]
@ViHtarb   For the clickListener you can use the `getPrefixTextView()` and `getSuffixTextView()` methods:

       textinputlayout.prefixTextView.setOnClickListener{
            //.....
        }

**Comment by drchen** [comment]
Is there still a need for this?

**Comment by drchen** [comment]
Thanks. Then I'll close the issue. : )
