### ISSUE TITLE
[Snackbar] Custom snackbar not called to ContentViewCallback 

### ISSUE THREAD

**Issue by rulogarcillan** [material-components/material-components-android#699]
**Description:** I have created a custom snackbar extending from the BaseTransientBottomBar class everything works great except for the com.google.android.material.snackbar.ContentViewCallback callback that is never invoked except if I change animationMode = ANIMATION_MODE_SLIDE, seeing the BaseTransientBottomBar code it seems that the operation is as expected but I think it should be called in both types of animation.

**Source code:** 

https://github.com/material-components/material-components-android/blob/115313c0c05d6fa404cbcdffa256877df8e86606/lib/java/com/google/android/material/snackbar/BaseTransientBottomBar.java

```
if (view.getAnimationMode() == ANIMATION_MODE_FADE) {
       startFadeInAnimation(); //no call to contentViewCallback.animateContentIn
} else {
       startSlideInAnimation(); // yes, call to contentViewCallback.animateContentIn
}
```

**Material Library version:** com.google.android.material:material:1.1.0-beta01

**Comment by rulogarcillan** [comment]
I think the solution would be the following

```

 private void startFadeInAnimation() {
        ValueAnimator alphaAnimator = getAlphaAnimator(0, 1);
        ValueAnimator scaleAnimator = getScaleAnimator(ANIMATION_SCALE_FROM_VALUE, 1);

        AnimatorSet animatorSet = new AnimatorSet();
        animatorSet.playTogether(alphaAnimator, scaleAnimator);
        animatorSet.setDuration(ANIMATION_FADE_IN_DURATION);
        animatorSet.addListener(
                new AnimatorListenerAdapter() {
                    @Override
                    public void onAnimationStart(Animator animator) {
                        contentViewCallback.animateContentIn(
                                ANIMATION_DURATION - ANIMATION_FADE_DURATION, ANIMATION_FADE_DURATION);
                    }

                    @Override
                    public void onAnimationEnd(Animator animator) {
                        onViewShown();
                    }
                });
        animatorSet.start();
    }

    private void startFadeOutAnimation(final int event) {
        ValueAnimator animator = getAlphaAnimator(1, 0);
        animator.setDuration(ANIMATION_FADE_OUT_DURATION);
        animator.addListener(
                new AnimatorListenerAdapter() {
                    @Override
                    public void onAnimationStart(Animator animator) {
                        contentViewCallback.animateContentOut(0, ANIMATION_FADE_DURATION);
                    }

                    @Override
                    public void onAnimationEnd(Animator animator) {
                        onViewHidden(event);
                    }
                });               
        animator.start();
    }
```

**Comment by Neckster** [comment]
Same for me.

**Comment by asaggo** [comment]
same here. no solution yet?

**Comment by dsn5ft** [comment]
Hi @rulogarcillan, this situation is somewhat legacy and unfortunate, but the reason we don't invoke the `contentViewCallback` during `ANIMATION_MODE_FADE` is because the default `contentViewCallback` will fade in the Snackbar's message text and action button. During the legacy `ANIMATION_MODE_SLIDE` this is the desired effect, but during the newer `ANIMATION_MODE_FADE` it doesn't make sense to fade the individual pieces (text/button) when the Snackbar is fading in as a whole.
