### ISSUE TITLE
Feature request - Make it easier to add inset dividers to LinearLayout and RecyclerView

### ISSUE THREAD

**Issue by tadfisher** [material-components/material-components-android#7]
It would be lovely to support inset dividers on LinearLayout and RecyclerView.

For both, fine-grained control would be nice; for example, to inset only the middle dividers in a LinearLayout, or to provide dividers only for specific items in a RecyclerView.

I currently use a couple of modifications to LinearLayout and a custom item decoration to achieve this, which I will submit.

Supporting documentation: https://material.io/guidelines/components/dividers.html#dividers-types-of-dividers

**Comment by ldjcmu** [comment]
We have no plans to implement this.
