### ISSUE TITLE
[Slider] Add a way to prevent the label from being drawn at all

### ISSUE THREAD

**Issue by Dem0n13** [material-components/material-components-android#703]
**Description:** when I set `slider.isFloatingLabel = false` label stills show.

`slider.isFloatingLabel = true` (default)
![Screenshot_1571896439](https://user-images.githubusercontent.com/1087430/67457428-4d7cb580-f63c-11e9-85d4-5cc8671c33c2.png)

`slider.isFloatingLabel = false`
![Screenshot_1571896494](https://user-images.githubusercontent.com/1087430/67457429-4d7cb580-f63c-11e9-895a-bc0a4eee8902.png)

**Expected behavior:** I expected that I can hide floating label.

**Source code:** 
```
<com.google.android.material.slider.Slider
        android:id="@+id/sliderOpacity"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:stepSize="20"
        android:valueFrom="10"
        android:valueTo="90"
        app:floatingLabel="false" />
```

**Android API version:** Android P, Q

**Material Library version:** 1.2.0-alpha01

**Device:** AVD, Google Pixel 3

**Comment by somename6668** [comment]
use 
`app:floatingLabel="true" `
to hide hide floating label.

**Comment by cketcham** [comment]
floating label is supposed to determine if the label is drawn over views outside the bounds of the slider view, or if the label is only drawn inside the slider bounds. Adding a way to hide the label sounds like a good idea. I can add another method to toggle the visibility of the label.

**Comment by erfanegtfi** [comment]
use this
 app:labelBehavior="gone"

**Comment by shtanriverdi** [comment]
**app:labelBehavior="gone"**
