### ISSUE TITLE
[Slider] Cannot set stepSize < 1.0

### ISSUE THREAD

**Issue by Dem0n13** [material-components/material-components-android#704]
**Description:** When I set `stepSize=0.1` I get next error:
```
Caused by: java.lang.IllegalArgumentException: The stepSize must be 0, or a factor of the valueFrom-valueTo range
        at com.google.android.material.slider.Slider.validateStepSize(Slider.java:383)
        at com.google.android.material.slider.Slider.processAttributes(Slider.java:360)
```

**Expected behavior:** I want to set stepSize="0.1" for range 0..1

**Source code:** 
```
<com.google.android.material.slider.Slider
        android:id="@+id/sliderOpacity"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:stepSize="0.1"
        android:valueFrom="0"
        android:valueTo="1" />
```

**Android API version:** Android P, Q

**Material Library version:** 1.2.0-alpha01

**Device:** AVD, Google Pixel 3

**Comment by gabrielemariotti** [comment]
It happens because:

```
} else if (stepSize > 0.0f && (valueTo - valueFrom) % stepSize != 0.0f) {
      Log.e(TAG, EXCEPTION_ILLEGAL_STEP_SIZE);
      throw new IllegalArgumentException(EXCEPTION_ILLEGAL_STEP_SIZE);
```
This works fine with integer values. But using float values in java it is `0.09999999` e not `0.0f`.

**Comment by enricoros** [comment]
Experienced the same issue here. Range from: 0.5, to: 2, step: 0.1.
(2f - 0.5f) % 0.1f  = 0.09999998

This workaround would avoid the falsehood of the check:
((2f - 0.5f) / 0.1f) % 1 = 0

Everything else should work, maybe the test can be modified in something like: 
(((valueTo - valueFrom) / stepSize) % 1) != 0.0f

**Comment by opatry** [comment]
Hi,

I still have this issue with `min=1.2f`, `max=2.0f`, `stepSize=0.1f`.
I'm setting such values through Kotlin code if it matters.
```
val x = (((1.2f - 2.0f) / 0.1) % 1) // = -0.9999995231628418
```
In the Java debugger within `Slider.java` `validateStepSize`, I have: `(((valueTo - valueFrom) / stepSize) % 1) = 0.9999995`

I'm using Material `1.2.0-alpha05`

**Comment by opatry** [comment]
If I use the values used in the test case associated to this fix:
✅ 
```
slider.valueTo = 2.5f
slider.valueFrom = 1.2f
slider.stepSize = 0.01f
```
It works, but with my values (`0.1` as `stepSize` vs `0.01f`)

💥 
```
slider.valueTo = 2.5f
slider.valueFrom = 1.2f
slider.stepSize = 0.1f
```
It throws, but shouldn't.

**Comment by JureSencar** [comment]
I also get following exception:

`java.lang.IllegalStateException: The stepSize(0.1) must be 0, or a factor of the valueFrom(0.3)-valueTo(5.0) range`

on `1.3.0-alpha02`

**Comment by gabrielemariotti** [comment]
@JureSencar 
Check #1587

**Comment by rooton** [comment]
> It happens because:
> 
> ```
> } else if (stepSize > 0.0f && (valueTo - valueFrom) % stepSize != 0.0f) {
>       Log.e(TAG, EXCEPTION_ILLEGAL_STEP_SIZE);
>       throw new IllegalArgumentException(EXCEPTION_ILLEGAL_STEP_SIZE);
> ```
> 
> This works fine with integer values. But using float values as in your case in java it is `0.09999999` and not `0.0f`.

It is annoying. Why I cant set step size I want, why that limitation?

**Comment by az-oolloow** [comment]
I agree with @rooton this check is annoying.
