### ISSUE TITLE
[Snackbar] Snackbar has wrong background if `colorOnSurface` is a attribute reference

### ISSUE THREAD

**Issue by mik9** [material-components/material-components-android#706]
**Description:** Snackbar has wrong background if `colorOnSurface` is a attribute reference

**Expected behavior:** Snackbar resolves reference correctly.

**Source code:** 
```xml
        <item name="android:textColorPrimary">#ffffff</item>
        <item name="colorOnSurface">?android:textColorPrimary</item>
```

**Android API version:** 29

**Material Library version:** 1.1.0-beta01

**Device:** Pixel

[Sample application](https://github.com/material-components/material-components-android/files/3767253/SnackbarAttributeReferenceIssue.zip)

**Comment by dsn5ft** [comment]
So it looks like Snackbar is actually resolving the reference correctly when it reads `colorOnSurface`, but the `android:textColorPrimary` from your top-level theme is being overridden by the theme overlay we apply in the Snackbar layout, which sets `android:textColorPrimary` to `@color/abc_primary_text_material_dark` (`#ffffffff`):

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/snackbar/res/layout/mtrl_layout_snackbar.xml#L24

I'm now thinking about whether we really need to apply the theme overlay anymore, now that we are setting the colors more explicitly on the Snackbar's message text and action button.

**Comment by cmonfortep** [comment]
Hi, after bumping a few versions (from 1.1.0-alpha05 to 1.2.0-alpha05), we've detected that snackbars action buttons aren't using `colorAccent` anymore. I wonder if this behavior is related to change applied to this issue. (I think they are using colorPrimary instead).

In the [docs](https://material.io/develop/android/components/snackbar/), I can read:
Action text color can be customized through the setActionTextColor methods (defaulting to your theme’s accent color).

**Comment by dsn5ft** [comment]
Hi @cmonfortep, I don't think that behavior change is related to this issue/commit, but rather https://github.com/material-components/material-components-android/commit/d03f490740d23a07b70abc454aa86b8d65ee504e. It is intentional, so I will update that doc which is outdated.
