### ISSUE TITLE
[TextInputLayout] Support boxBackgroundColor focused state

### ISSUE THREAD

**Issue by nkotula** [material-components/material-components-android#710]
## Problem Description
You cannot set a different filled `boxBackgroundColor` for when the `TextInputLayout` or the child `TextInputEditText` has focus.

## Proposed Solution Description
We should be able to set a color resource in a Color State List that will change the background color of the `TextInputLayout` when it or its child `TextInputEditText` has focus.  For example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- This is what I would like to do, but it currently does nothing: -->
    <item android:alpha="0.25" android:color="?colorOnSurface" android:state_focused="true" />

    <!-- The following three items are the only states that TextInputLayout respects for boxBackgroundColor: -->
    <item android:alpha="0.16" android:color="?colorOnSurface" android:state_hovered="true" />
    <item android:alpha="0.04" android:color="?colorOnSurface" android:state_enabled="false" />
    <item android:alpha="0.12" android:color="?colorOnSurface" />
</selector>
```

## Possible Alternative Solution
A programmatic approach could add a focus changed listener to each `TextInputLayout` and override the `boxBackgroundColor` when the view or its child gets focus.  This seems really hacky though.

## Additional Context
The default Material Text Field component example (https://material.io/components/text-fields/) shows a darker background color than the hovered color when the text field is focused.  It seems like this feature is simply missing from the Android implementation.

**Comment by nkotula** [comment]
The solution to this seems pretty straightforward to implement (knock on wood).  The constructor for `TextInputLayout` is only checking the provided `boxBackgroundColor` state list for default, `state_enabled` and `state_hovered`:

```java
ColorStateList filledBackgroundColorStateList =
    MaterialResources.getColorStateList(
        context, a, R.styleable.TextInputLayout_boxBackgroundColor);

if (filledBackgroundColorStateList != null) {
  defaultFilledBackgroundColor = filledBackgroundColorStateList.getDefaultColor();
  boxBackgroundColor = defaultFilledBackgroundColor;

  if (filledBackgroundColorStateList.isStateful()) {
    disabledFilledBackgroundColor =
        filledBackgroundColorStateList.getColorForState(
            new int[] {-android.R.attr.state_enabled}, -1);

    hoveredFilledBackgroundColor =
        filledBackgroundColorStateList.getColorForState(
            new int[] {android.R.attr.state_hovered}, -1);

    /* Could simply set a "focusedFilledBackgroundColor" here by checking for
       "state_focused" */

  } else {
    // ...
  }
} else {
  // ...
}
```

It seems like simply adding another color field for the focused state and using that in the `updateTextInputBoxState()` could be a straightforward solution.  Thoughts?

**Comment by leticiarossi** [comment]
See https://github.com/material-components/material-components-android/commit/8ca8e1bbdd6d767660a0fef85b36cdf3bd8b7a39
