### ISSUE TITLE
[TextInputLayout]TextInputLayout.setEndIconOnClickListener not fired

### ISSUE THREAD

**Issue by azzahrah** [material-components/material-components-android#712]
**Description:** TextInputLayout.setEndIconOnClickListener NOT FIRED

**Android API version:** Android 9, compileSdkVersion 28, buildToolsVersion '28.0.3'

**Material Library version:**  implementation 'com.google.android.material:material:1.2.0-alpha01'

**Device:**OPPO A52020

```
TextInputLayout textInputCustomEndIcon = view.findViewById(R.id.custom_end_icon);

// If the icon should work as button, set an OnClickListener to it
textInputCustomEndIcon
    .setEndIconOnClickListener(/* custom OnClickListener */);

setEndIconOnClickListener NOT FIRED
```

**Comment by leticiarossi** [comment]
I'm not able to reproduce this on my end (the setEndIconOnClickListener seems to be working as expected). Could you provide a sample app with the issue?
