### ISSUE TITLE
[colors.xml] Colors are not consistently named.

### ISSUE THREAD

**Issue by Gryzor** [material-components/material-components-android#715]
**Description:** 
When watching the [Developing Themes with Style (Android Dev Summit '19)](https://www.youtube.com/watch?v=Owkf8DhAOSo), Chris Banes, and Nick Butcher mentioned more than once, that we should _name our resources consistently_; it even uses _colors_ as an example: instead of naming them `primary_color`, it's preferred to use a meaningful name, like: `blue_500`. 

This is not the case with this app, oriented at showcasing "the good practices" of working with themes/styles.

**Expected behavior:** 
Colors are consistently and correctly named.

**Source code:** 
https://github.com/material-components/material-components-android/blob/master/material-theme-builder/src/main/res/values/color.xml

**Comment by hunterstich** [comment]
Hey Gryzor, thanks for submitting this issue! 

I'm working on updating the theme builder to be consistent with other guidance we have (https://github.com/material-components/material-components-android-examples) as well as Nick and Chris' talk at ADS.

**Comment by hunterstich** [comment]
Fixed!

https://github.com/material-components/material-components-android-examples/blob/develop/MaterialThemeBuilder/app/src/main/res/values/color.xml
