### ISSUE TITLE
[TextInputLayout] setHint at run-time doesn't set isProvidingHint=true

### ISSUE THREAD

**Issue by henrik-lindqvist** [material-components/material-components-android#717]
**Description:**
Setting android:hint on TextInputLayout in an XML layout correctly cause it to "provide the hint", i.e. isProvidingHint=true, see:
https://github.com/material-components/material-components-android/blob/1.1.0-beta01/lib/java/com/google/android/material/textfield/TextInputLayout.java#L1099

But calling TextInputLayout.setHint() at run-time do not, see:
https://github.com/material-components/material-components-android/blob/1.1.0-beta01/lib/java/com/google/android/material/textfield/TextInputLayout.java#L1194

This cause inconsistent behavior when calling TextInputEditText.getHint() depending on whether the hint was set in XML or at run-time, see:
https://github.com/material-components/material-components-android/blob/1.1.0-beta01/lib/java/com/google/android/material/textfield/TextInputEditText.java#L71

**Expected behavior:**
Consistent behavior when calling TextInputEditText.getHint(), irregardless of it being set in XML or at run-time, i.e. TextInputLayout.setHint() should also set isProvidingHint=true.

**Source code:**
this.<TextInputLayout>findViewById(android.R.id.text1).setHint("foobar");

**Android API version:**
All

**Material Library version:** 
1.1.0-beta01

**Device:**
All

**Comment by leticiarossi** [comment]
TextInputLayout calls `isProvidingHint = true` inside the `setHintEnabled` option [here](https://github.com/material-components/material-components-android/blob/1.1.0-beta01/lib/java/com/google/android/material/textfield/TextInputLayout.java#L1256), and the hint only gets set via `setHint` if `hintEnabled` is true.

Can you explain in more details what issue you're having?

**Comment by leticiarossi** [comment]
Closing this. Feel free to reopen with more info if you're still finding an issue.
