### ISSUE TITLE
[Slider] Slider doesn't invalidate on set value

### ISSUE THREAD

**Issue by xxfast** [material-components/material-components-android#719]
**Description:** Slider doesn't invalidate on set value. `onDraw` to be called when the state changes

**Expected behavior:** Slider to invalidate whenever the state changes

**Source code:** 

```kotlin
fontSizeSlider.value = 0.5f
```

**Android API version:** 28
**Material Library version:** 1.2.0-alpha01
**Device:** Pixel 3 Emulator

**Comment by cketcham** [comment]
Fixed by https://github.com/material-components/material-components-android/pull/720
