### ISSUE TITLE
Is it possible to have the BottomAppBar & FloatingActionButton with menu evenly distributed?

### ISSUE THREAD

**Issue by b95505017** [material-components/material-components-android#72]
Something like the mix concept of BottomNavigationView and BottomAppBar.

![like this](https://github.com/ittianyu/BottomNavigationViewEx/raw/master/read_me_images/center_fab.jpg)

**Comment by lanhuaguizha** [comment]
it is urgly

**Comment by lanhuaguizha** [comment]
I don't think we need this.

**Comment by ymarian** [comment]
Hi I don't think this is part of the spec. So we probably won't implement it. https://material.io/design/components/app-bars-bottom.html#behavior

**Comment by thenotoriousrog** [comment]
While this isn't part of spec, I figured that I would add this in case anyone else wants it. With the bottom app back you can evenly space your icons doing this:

```
if(bottomAppBar.childCount > 0) {
     val actionMenuView = bottomAppBar.getChildAt(0) as ActionMenuView
     actionMenuView.layoutParams.width = android.widget.ActionMenuView.LayoutParams.MATCH_PARENT   
}
```
