### ISSUE TITLE
[TextInputLayout] Error icon is always shown when boxBackgroundMode="none"

### ISSUE THREAD

**Issue by bogdanflorianmihai** [material-components/material-components-android#725]
**Description:** When the boxBackground mode is set to none, the TextInputLayout always shows the error icon at the end. A workaround that I found is to set the errorIconDrawable to null.
<img src="https://i.ibb.co/XC9bfGQ/text-error.jpg"/>
**Expected behavior:** 
<img src="https://i.ibb.co/mSyfSQf/text-error-good.jpg"/>

**Source code:**  
```
<com.google.android.material.textfield.TextInputLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:boxBackgroundMode="none">

                <com.google.android.material.textfield.TextInputEditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="20dp"
                    android:layout_marginEnd="20dp"
                    android:drawablePadding="8dp"
                    android:hint="Password"
                    android:imeOptions="actionDone"
                    android:inputType="textPassword" />

</com.google.android.material.textfield.TextInputLayout>
```
**Android API version:** 28

**Material Library version:** 1.1.0-beta01 (but I tracked the issue back to 1.1.0-alpha09)

**Device:** Doesn't matter

**Comment by leticiarossi** [comment]
Hi, that should've been fixed in https://github.com/material-components/material-components-android/commit/c4f27dc22eec2818ed303a1b0ac72183335dd0cc which will be included in a future 1.2.0-alpha and 1.1.0-beta releases!
