### ISSUE TITLE
[TextInputLayout] Hint text margin incorrect when initially focused

### ISSUE THREAD

**Issue by ed-george** [material-components/material-components-android#727]
**Description:** 

Within the latest 1.2.0 alpha, when initially focussed the hint text for a `TextInputLayout` is not in the correct position and encroaches on the `TextInputEditText`

![android_1_2_alpha01_example](https://user-images.githubusercontent.com/1354568/67845754-efe2e000-faf7-11e9-8e6f-880eaca88dc7.png)

**Expected behavior:** 

This behavior was working on the latest 1.1.0 beta

![android_1_1_beta01_example](https://user-images.githubusercontent.com/1354568/67845756-f07b7680-faf7-11e9-841e-13187be5cb90.png)

**Source code:** Will update issue when available

**Android API version:** Android 10 (API 29)

**Material Library version:** 1.2.0-alpha01

**Device:** Pixel 3a XL

**Comment by leticiarossi** [comment]
Could you provide a sample app/source code? I'm not able to reproduce it on my end

**Comment by rmasarovic** [comment]
Hi simple layout dont work.  android:gravity="bottom" in edittext dont have any effect. In library 1.0.0 work but  version>1.1.0 dont 

> <com.google.android.material.textfield.TextInputLayout
                        android:id="@+id/nameLoginWrapper"
                        android:layout_width="288dp"
                        android:layout_height="wrap_content"
                        android:layout_below="@+id/login_logo"
                        android:layout_centerHorizontal="true"
                        android:layout_marginTop="15dp"
                        android:backgroundTint="@color/white"
                        android:gravity="bottom"
                     >

                    <com.google.android.material.textfield.TextInputEditText
                            android:id="@+id/login_name"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:fontFamily="sans-serif"
                            android:hint="as"
                            android:gravity="bottom"
                            android:inputType="textNoSuggestions"
                            android:singleLine="true"
                            android:textSize="16sp"/>
                </com.google.android.material.textfield.TextInputLayout>

**Comment by wcshi** [comment]
What do you mean "simple layout dont work."

**Comment by leticiarossi** [comment]
Gonna close this issue as there's been no response from the original reporter and we aren't able to reproduce it. Feel free to reopen with a sample app/source code if the issue persists.

@rmasarovic the screenshot you provided looks like the intended behavior of the text field in 1.1.0 and above. See [specs](https://material.io/components/text-fields) and [documentation](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md) for more info.

**Comment by ShaoLongFei** [comment]
why close? Many people have this problem.

**Comment by amirhosenebrahimi** [comment]
why close? Many people have this problem.
