### ISSUE TITLE
[FloatingActionButton] SetVisibility is restricted.

### ISSUE THREAD

**Issue by davidliu** [material-components/material-components-android#728]
**Description:** Calling setVisibility raises an inspection error due to it being overridden inside a `@RestrictTo` annotated class (`VisibilityAwareImageButton`).

**Expected behavior:** SetVisibility should not raise an inspection error, as it's a publicly used method on `android.view.View`.

**Source code:** 

     floatingActionButton.setVisibility(View.VISIBLE)

**Android API version:** Any

**Material Library version:** 1.0.0

**Device:** Android Studio 3.5, Mac.

**Comment by ymarian** [comment]
This has been addressed: https://issuetracker.google.com/118107412
