### ISSUE TITLE
Toggle Button

### ISSUE THREAD

**Issue by b95505017** [material-components/material-components-android#73]
https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons

![toggle button](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3V2JKWk9EbzFaMjg/components-buttons-togglebuttons1.png)

**Comment by KennyGoers** [comment]
The one I use until they figure out it doesn't exist in their library:

https://github.com/rcketscientist/ToggleButtons

**Comment by b95505017** [comment]
I use this one:

https://github.com/savvyapps/ToggleButtonLayout

**Comment by gsajith** [comment]
Hi! Small update on this --

We're in the process of building this component, and the expected delivery date is mid-March.

Thanks for your patience!

**Comment by kyay** [comment]
Hey, there is also another possible way, just use a MaterialCheckBox (or a regular one, doesn't matter) and set the icon to be "@null". Also remember to add a selector as a background

**Comment by Philipp91** [comment]
Seems like this is available in `1.1.0-alpha05` from https://github.com/material-components/material-components-android/commit/cad9d7d5f5d8e27ee2d141c3cdcf67e0e52c99d0.
