### ISSUE TITLE
[MaterialButtonToggleGroup] Issue

### ISSUE THREAD

**Issue by LLSAndroid** [material-components/material-components-android#732]
Clicking on checked Material Button it unchecked. See the video in zip
[material_toggle_issue.zip](https://github.com/material-components/material-components-android/files/3800186/material_toggle_issue.zip)

**Comment by matpag** [comment]
Please add a small code sample with the problem or link a gist.
Most people here will not download a zip with unknown origins

**Comment by ymarian** [comment]
> Clicking on checked Material Button it uncheck

Is expected behavior. 
Follow this bug for the switch behavior: https://github.com/material-components/material-components-android/issues/438
