### ISSUE TITLE
MaterialShapeDrawable ShapePath issue

### ISSUE THREAD

**Issue by VolodyaVechirko** [material-components/material-components-android#736]
It seems that 'quadToPoint' doesn't work properly, but 'addArc' and 'lineTo' work. Maybe I do something in wrong way. Provide please an example of usage quadToPoint.

Screenshot:
https://github.com/VolodyaVechirko/MaterialShapeView/blob/master/screens/Screenshot_20191105-135854.png

// Problem view
view1.shapeAppearanceModel = ShapeAppearanceModel.builder()
            .setAllEdges(QuadEdgeTreatment(40.dp()))
            .build()
// Everything is ok 
view2.shapeAppearanceModel = ShapeAppearanceModel.builder()
            .setAllEdges(ArgEdgeTreatment(24.dp(), true))
            .build()

class QuadEdgeTreatment(val size: Float) : EdgeTreatment() {
        // TODO: 
        override fun getEdgePath(length: Float, center: Float, f: Float, shapePath: ShapePath) {
            shapePath.quadToPoint(center, size * f, length, 0f)
        }
    }

View code:
https://github.com/VolodyaVechirko/MaterialShapeView/blob/master/app/src/main/java/com/vvechirko/materialshapetest/TestView.kt

library version com.google.android.material:material:1.2.0-alpha01

**Comment by ymarian** [comment]
Hi shadows won't work well with quadToPoint if your shape is concave and the API is below Q. 
See https://github.com/material-components/material-components-android/commit/b5c3fecacc5ba65e666302ab4ce8d5b9a608bdcf

For more context
