### ISSUE TITLE
[TextInputLayout] Hint text color state selector

### ISSUE THREAD

**Issue by patrickpilch** [material-components/material-components-android#739]
**Is your feature request related to a problem? Please describe.**
I am not able to set the hint color for an *activated* text input layout specifically.

**Describe the solution you'd like**
Be able to set `hintTextColor` in the `Widget.MaterialComponents.TextInputLayout.OutlinedBox` theme to a color selector where the color defined for `state_activated="true"` is respected.

**Additional context**
[In the documentation for Filled boxes](https://material.io/components/text-fields/#outlined-text-field), the "States" section describes that the **activated** state is when there is non-empty text input. I overrode `com.google.android.material.textfield.TextInputLayout#drawableStateChanged`  and logged the output of `StateSet.dump(getDrawableState())` and noticed that the view gets the focused, pressed, window focused and enabled states, but I did not see anything about the activated state.

**Comment by matpag** [comment]
If you check the documentation here: 
https://developer.android.com/guide/topics/resources/color-list-resource
There is no `state_activated` state available.
You should use `state_focused` which should have the same effect

**Comment by leticiarossi** [comment]
In that "States" section the "activated" state shows a non focused text field with input text. It doesn't refer to a CSL state. The color the hint uses for that state is the **default** color (the same as in the "inactive" state - a non focused text field with no input text) which can be set via the `android:textColorHint` attribute.

**Comment by patrickpilch** [comment]
I clearly had a misunderstanding of how the component works. Allow me to revise the solution I would like for my feature request:

I’d like to be able to set independent hint colors for the *activated* and *inactive* states.
