### ISSUE TITLE
[Theme] 1.2.0-alpha01 breaks Design widget styles in bridge themes

### ISSUE THREAD

**Issue by zhanghai** [material-components/material-components-android#740]
**Description:** b1a6256 moved some component styles from full themes to bridge themes. However, it moved not only the Material-only components, but also components that have a Design style, which broke them in bridge themes.

**Expected behavior:** Design widgets should retain Design styles in bridge themes.

![1.1.0-beta-01_expected](https://user-images.githubusercontent.com/4469895/68275101-9b6fc100-001f-11ea-9575-8c83091ff2b0.jpg)

**Actual behavior:** Design widgets gets Material styles in bridge themes.

![1.2.0-alpha01_actual](https://user-images.githubusercontent.com/4469895/68275115-a3c7fc00-001f-11ea-9823-590bb2287c2e.jpg)

**Analysis:** Taking `TabLayout` as an example, it obtains its styled attributes [here](https://github.com/material-components/material-components-android/blob/7bcd5f606e3c6ffe912204b4e35fc1b75d023a0b/lib/java/com/google/android/material/tabs/TabLayout.java#L474), with `defStyleAttr` (which is `R.attr.tabStyle`) and then `R.style.Widget_Design_TabLayout`. After b1a6256, `defStyleAttr` suddenly gets the Material style `Widget.MaterialComponents.TabLayout` from `tabStyle` in the new bridge themes and the Design style is no longer used, which is changing wdiget appearance after migrating from an AppCompat theme and clearly unexpected for bridge themes. So any widget that has a Design style should not have its Material style moved into bridge theme, and only Material-only widgets should be moved, the same as the commit message claimed.

**Proposed fix:** Move Design widget styles back to full themes from bridge themes. These widgets are, via a search for "Widget_Design" in the codebase:

- `AppBarLayout`
- `BottomNavigationView`
- `CollapsingToolbarLayout`
- `FloatingActionButton`
- `NavigationView`
- `ScrimInsetsFrameLayout`
- `TabLayout`
- `TextInputLayout`

**Android API version:** N/A

**Material Library version:** 1.2.0-alpha01

**Device:** N/A

**Comment by zhanghai** [comment]
Hi Dan, could you let me know if there is any update about this bug? I saw 1.2.0-beta01 released two days ago and this same issue persists.

**Comment by dsn5ft** [comment]
Thanks @zhanghai, I'm currently looking into moving the following back from the Bridge themes to the full themes:

```
    <item name="appBarLayoutStyle">@style/Widget.MaterialComponents.AppBarLayout.Surface</item>
    <item name="bottomNavigationStyle">@style/Widget.MaterialComponents.BottomNavigationView</item>
    <item name="floatingActionButtonStyle">@style/Widget.MaterialComponents.FloatingActionButton</item>
    <item name="navigationViewStyle">@style/Widget.MaterialComponents.NavigationView</item>
    <item name="snackbarStyle">@style/Widget.MaterialComponents.Snackbar</item>
    <item name="snackbarButtonStyle">@style/Widget.MaterialComponents.Button.TextButton.Snackbar</item>
    <item name="snackbarTextViewStyle">@style/Widget.MaterialComponents.Snackbar.TextView</item>
    <item name="tabStyle">@style/Widget.MaterialComponents.TabLayout</item>
    <item name="textInputStyle">@style/Widget.MaterialComponents.TextInputLayout.FilledBox</item>
```

**Comment by zhanghai** [comment]
Thanks, I also did a codesearch again and the list looks good to me.
