### ISSUE TITLE
[Snackbar] Appearing position changes when shown after dismiss

### ISSUE THREAD

**Issue by SYtor** [material-components/material-components-android#741]
**Description:** After dismiss and show again same instance of snackbar it changes appearing height position

**Expected behavior:**  Snackbar should always appear at bottom

**Actual behavior:** [Screenshots](https://imgur.com/a/bqQ9CpK)

**Source code:** [Sample project](https://github.com/SYtor/SnackbarDismissBug/blob/master/app/src/main/java/ua/sytor/snackbarbugtest/MainActivity.kt)

**Android API version:** API 29

**Material Library version:** 1.1.0-beta01, 1.2.0-alpha01

**Comment by migueledgracia** [comment]
I'm having the same issue, the only way around this is by creating a completely new instance of the `Snackbar`

**Comment by dsn5ft** [comment]
Thanks for the report. It looks like this is only an issue with the legacy Snackbar style (`Widget.Design.Snackbar`). I'll look into a way to preserve compatibility, but as a workaround for now you should be able to adopt the new Snackbar style by updating your app theme to `Theme.MaterialComponents` (or a descendant), or by adding the following to your theme:

```
    <item name="snackbarStyle">@style/Widget.MaterialComponents.Snackbar</item>
    <item name="snackbarButtonStyle">@style/Widget.MaterialComponents.Button.TextButton.Snackbar</item>
    <item name="snackbarTextViewStyle">@style/Widget.MaterialComponents.Snackbar.TextView</item>
```
