### ISSUE TITLE
[MaterialDatePicker] How do I parse the data in Java?

### ISSUE THREAD

**Issue by VincentJoshuaET** [material-components/material-components-android#743]
The demo doesn't show how to.

**Comment by hikkidev** [comment]
@VincentJoshuaET  u can cast **Object** *selection* to **Long**

materialCalendarPicker.addOnPositiveButtonClickListener(
       ** selection** -> {
          long timestamp = (Long) selection;
          **Date date = new Date(timestamp);**
          snackbar.setText(date.toString());
          snackbar.show();
        });

**Comment by ldjcmu** [comment]
What hikkidev commented is right. I just want to add  that if you convert to a Calendar or a LocalDate, make sure you treat the long as from the UTC timezone.
