### ISSUE TITLE
MaterialDatePicker Validators

### ISSUE THREAD

**Issue by KelvinPac** [material-components/material-components-android#746]
MaterialDatePicker 

Is there a way to set a validator for the previous days from today? Such that all days after today are invalid. In a scenario where the date picker is used for selecting dates for a report. You can get reports for the future

**Comment by matpag** [comment]
I'm not super familiar with DatePicker component but have you tried with [CalendarConstraint](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/CalendarConstraints.java) class?

In the catalog sample app there is a [DateValidatorWeekDays](https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/datepicker/DateValidatorWeekdays.java) which uses the DateValidator defined inside and it seems customizable for your own logic (check the `isValid` method)

Don't know if this can be helpful to your use case but you could try if you didn't yet

**Comment by leticiarossi** [comment]
That's correct, you should be able to use `isValid` in `CalendarConstraint`

**Comment by bohsen** [comment]
@KelvinPac You can use this:

```kotlin
@Parcelize
class BirthdateSelectionValidator : CalendarConstraints.DateValidator {
    override fun isValid(date: Long): Boolean = date <= System.currentTimeMillis()
}
```

**Comment by jssamsul** [comment]
update build.gradle (app) version as below

`implementation 'com.google.android.material:material:1.4.0'`

code level

```
CalendarConstraints.Builder constraintsBuilderRange = new CalendarConstraints.Builder()
                .setValidator(DateValidatorPointBackward.now());
        builder.setCalendarConstraints(constraintsBuilderRange.build());
        MaterialDatePicker picker = builder.build();
```
