### ISSUE TITLE
TextInputLayout: errorEnabled param in XML is currently useless and causing troubles

### ISSUE THREAD

**Issue by matpag** [material-components/material-components-android#747]
The current param `errorEnabled` can't be used for something useful in its current state.

1. There is no `errorText` property to set in the XML, so only having `errorEnabled=true` defined has no means at all if we can only set the error from code with `setError(..)`. (which automatically enable the error if needed).
We should think about if this makes sense at all, starting with a TextInputLayout already showing a red error probably is not very useful.

2. If we don't want to give the above-mentioned possibility, we should deprecate `errorEnabled` styleable property and make it no-op (as it is now in practice, because it only adds the error view to the captionArea without using it). Otherwise we need to add an errorText property and handle it like we do for helperText.

Moreover in the current state I'm encountering a bug with this XML:
```
<com.google.android.material.textfield.TextInputLayout
      android:id="@+id/textinput_test"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:hint="hint text"
      app:errorEnabled="true"
      app:helperText="helper text"
      app:helperTextEnabled="true">

      <com.google.android.material.textfield.TextInputEditText
          android:layout_width="match_parent"
          android:layout_height="wrap_content" />

  </com.google.android.material.textfield.TextInputLayout>
```

If i write a method like this:
```
private void setErrorToInput() {
   textInput.setHelperTextEnabled(false);
   textInput.setError("I'm an error");
}
```
The first time I call `setErrorToInput()` I get a TextInput in error state without the error text visible. Calling it again shows the error text too.

The problem is that we are calling `setErrorEnabled(true)` during the TextInputLayout construction forcing the creation of an empty `errorView` which is hidden. This breaks the code in `removeIndicator(helperTextView, HELPER_INDEX);` which removes the helperText and leave the TextInput believing there is an error currently showing, but that's not the case.

Simply commenting `setErrorEnabled(..)` from TextInputLayout constructor solved the problem.

Waiting for members advices on how to proceed :)
If you can take a decision I can proceed with a PR.

**Comment by leticiarossi** [comment]
The errorEnabled attribute's function is to properly add spacing so that when the error message eventually shows up there are no visual jumps. I tested calling setHelperTextEnabled(false) then setError in a layout like yours and wasn't able to reproduce the issue (the error appears as expected).
What version of the library are you using?

**Comment by matpag** [comment]
Sorry @leticiarossi, I didn't specify everything in the first post.

By the way to help you speed up the analyzing process I've created a sample project with the reproducible behaviour using 1.1.0-beta02
https://github.com/matpag/material-textinputtest

If you need anything else just ask.

PS: If you figure out the problem and be able to point me in the right direction I can work on the fix

**Comment by leticiarossi** [comment]
I see the issue happening in the sample project, but when I test it with 1.2.0-alpha02 ([released yesterday!](https://github.com/material-components/material-components-android/releases/tag/1.2.0-alpha02)) the issue then goes away. My guess is it was fixed in https://github.com/material-components/material-components-android/commit/816f080be22345bc200acfe268fd808b654cc938

**Comment by matpag** [comment]
Perfect!! So I think we can close the issue 😁
