### ISSUE TITLE
[Typography] Is document textAppearanceHeadline6 font Regular correct?

### ISSUE THREAD

**Issue by takahirom** [material-components/material-components-android#748]
**Description:**

In document

https://github.com/material-components/material-components-android/blob/62a2164f1808a559c0ddb799aff4965f3669f20b/docs/theming/Typography.md#usage

---
![image](https://user-images.githubusercontent.com/1386930/68525592-99a34780-0316-11ea-95d7-735dfdd385c5.png)
---

In xml

https://github.com/material-components/material-components-android/blob/62a2164f1808a559c0ddb799aff4965f3669f20b/lib/java/com/google/android/material/typography/res/values-v21/styles.xml#L21

---
![image](https://user-images.githubusercontent.com/1386930/68525614-d7a06b80-0316-11ea-850a-a475a37aa95d.png)
---

**Expected behavior:**  Probably we should use regular??

**Source code:**
https://github.com/material-components/material-components-android/blob/62a2164f1808a559c0ddb799aff4965f3669f20b/docs/theming/Typography.md#usage
https://github.com/material-components/material-components-android/blob/62a2164f1808a559c0ddb799aff4965f3669f20b/lib/java/com/google/android/material/typography/res/values-v21/styles.xml#L21

**Android API version:** All version

**Material Library version:** 1.1.0-beta01

**Comment by leticiarossi** [comment]
Hi, it should say "medium" on the documentation like it says here https://material.io/design/typography/the-type-system.html#type-scale, will work into updating it. Thank you for reporting!
