### ISSUE TITLE
UI bug in Scrolling demo

### ISSUE THREAD

**Issue by IgorGanapolsky** [material-components/material-components-android#752]
Good day,
your UI setup in Android demo doesn't adhere to the device measurement guidelines.  Please see attached video, the scrolling demo gets jumbled up with the System Bar:

![screenshot](https://user-images.githubusercontent.com/201209/68536103-7fb83380-031b-11ea-8084-ca9947dfd61e.png)

**See video recording:**
[device-2019-11-09-180344.mp4.zip](https://github.com/ricknout/android-mdc-theming/files/3827839/device-2019-11-09-180344.mp4.zip)

**Comment by hunterstich** [comment]
Hey, thank you for reporting this issue! We'll look into what's going on.
