### ISSUE TITLE
[MaterialDatePicker] Selecting year causes displayed month to jump around

### ISSUE THREAD

**Issue by thirstycoda** [material-components/material-components-android#754]
**Description:** With November 2019 shown, when I click the down arrow next to the year, then select a different year, like 2020, the displayed month goes to August 2020, August 2021, December 2021, February 2021, August 2020 then April 2020 

**Expected behavior:** It shows a month in 2020

**Source code:** 

```java
TextInputEditText fromDateLayout = view.findViewById(R.id.from_date);
        fromDateLayout.setOnFocusChangeListener(new View.OnFocusChangeListener() {
            @Override
            public void onFocusChange(View v, boolean hasFocus) {
                if (hasFocus) {
                    MaterialDatePicker.Builder<Long> builder = MaterialDatePicker.Builder.datePicker();
                    builder.setTitleText("Date");
                    MaterialDatePicker<Long> picker = builder.build();

                    picker.show(getFragmentManager(), picker.toString());
                }
            }
        });
```

**Android API version:** 29

**Material Library version:** 1.2.0-alpha01

**Device:** Android Emulator

**Comment by hunterstich** [comment]
Hey, any chance you'd be able to provide a small sample that reproduces this issue? Looking into this in our catalog, I'm not able reproduce what you've described (or I don't fully understand the issue you're running in). It looks like selecting a a different year in the single date picker will smoothly scroll from Nov. 2019 to Nov. 2020.

**Comment by thirstycoda** [comment]
Hi, thanks for looking into it. I should be able to get a small sample to you by Friday. Apologies for not providing one to begin with

**Comment by thirstycoda** [comment]
Hi, I've created a sample project with the issue.

https://github.com/thirstycoda/MaterialCalendarBug

To reproduce:
* run the app in Android Studio using a Nexus 5X, android 10 virtual device
* click on the date field to open the material date picker
* use the down arrow to open the year selection
* select an unselected year
* within 5 seconds you should see the month and year shown being randomly changed

I also noticed one of the months I was shown, the dates were all over the place. I have included a screenshot at the root of the repository

**Comment by ajay-bsoft** [comment]
I am also getting the same issue.

**Comment by paulfthomas** [comment]
Couldn't reproduce using the sample app provided by @thirstycoda and updating the Material lib to version `1.5.0`. Please reopen if you're still having issues.
