### ISSUE TITLE
[MaterialDatePicker] Add feature to disable date in Calendar

### ISSUE THREAD

**Issue by PrathameshKesarkar** [material-components/material-components-android#755]
Current MaterialDatePicker implementation doesn't have the ability to disable certain dates. So when the user tries to select these dates it can't be selected.

A simple solution can be the user can pass an array of CalendarObject with all the dates he wants to disable in the DatePicker dialog.
Here's an abstract code

`fun disableDates( calendar:Calendar[]) `

**Comment by ldjcmu** [comment]
This should be doable via the CalendarConstraints and DateValidator API. Can you take a look at those and see if they fit?

**Comment by PrasadMusini** [comment]
[How to disable certain dates in the Android Date Picker dialog?](https://stackoverflow.com/questions/34727244/how-to-disable-certain-dates-in-the-android-date-picker-dialog)
