### ISSUE TITLE
[TextInputLayout] Prefix text animates to/from wrong position

### ISSUE THREAD

**Issue by thevoiceless** [material-components/material-components-android#756]
**Description:** 
Prerequisite: `TextInputLayout` with `hint` and `prefixText`.
When focusing, the hint animates from the end of the prefix. When un-focusing, the hint animates from the left edge of the view.

**Expected behavior:**
The hint should animate to/from its position at the start of the view. Compare the Material Components behavior to the behavior of [this library](https://github.com/HITGIF/TextFieldBoxes):
![prefix](https://user-images.githubusercontent.com/1574103/68718186-c4370f80-0565-11ea-9c19-8c7ed2d13cfc.gif)
(Visual artifacts are from saving the gif)

**Source code:** 
```
<com.google.android.material.textfield.TextInputLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:hint="Facebook"
    app:prefixText="facebook.com/">

    <com.google.android.material.textfield.TextInputEditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

</com.google.android.material.textfield.TextInputLayout>

<studio.carbonylgroup.textfieldboxes.TextFieldBoxes
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:labelText="Facebook">

    <studio.carbonylgroup.textfieldboxes.ExtendedEditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:prefix="facebook.com/"/>

</com.servicemagic.pros.views.FixedTextFieldBoxes>
```

**Android API version:** 
The gif above was captured on a Pixel 3a emulator running Android 10.0

**Material Library version:** 
1.2.0-alpha01

**Device:** 
The gif above was captured on a Pixel 3a emulator running Android 10.0

**Comment by drchen** [comment]
I think this should've been fixed. Please feel free to reopen the issue if it's still happening.
