### ISSUE TITLE
[MaterialCardView] card corners, leaving a blank space.

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [material-components/material-components-android#757]
**Description:** MaterialCardView stroke color do not follow exactly the card corners, leaving a blank space.
 
**Source code:**

 ```
 <com.google.android.material.card.MaterialCardView
    android:id="@+id/cardView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="12dp"
    android:clipToPadding="true"
    app:cardCornerRadius="8dp"
    app:cardElevation="5dp"
    app:strokeColor="@color/oppiaBrown"
    app:strokeWidth="2dp">
```

 **Android API version:** 29

 **Material Library version:** 1.0.0-alpha1

 This is the output:
 
<img alt="Screen Shot 2019-08-04 at 21 44 22" width="237" src="https://user-images.githubusercontent.com/19560506/62433094-0ba93680-b701-11e9-83ac-d92a2ad244da.png">
when card elivation is set as 0 this problem is getting fixed ,but i need shadow (elivation) . so please fix this or guide the solution.

**Comment by hunterstich** [comment]
Hey! Thanks for reporting.
Any chance you'd be able to add a sample that reproduces this issue? I'm looking into this in our [catalog app](https://github.com/material-components/material-components-android/tree/master/catalog) and am not seeing the issue you've described. This is what I'm seeing on 1.1.0-beta02 on and emulator on API 29.

<img alt="Screenshot_1573671535" width="237" src="https://user-images.githubusercontent.com/7459254/68795110-27c44a00-0605-11ea-9a3e-75789aef6439.png">

**Comment by nikitamarysolomanpvt** [comment]
> Hey! Thanks for reporting.
> Any chance you'd be able to add a sample that reproduces this issue? I'm looking into this in our [catalog app](https://github.com/material-components/material-components-android/tree/master/catalog) and am not seeing the issue you've described. This is what I'm seeing on 1.1.0-beta02 on and emulator on API 29.
> 
> <img alt="Screenshot_1573671535" width="237" src="https://user-images.githubusercontent.com/7459254/68795110-27c44a00-0605-11ea-9a3e-75789aef6439.png">

Iam using  **Material Library version:** 1.0.0-alpha1

**Comment by nikitamarysolomanpvt** [comment]
@hunterstich Please reply

**Comment by hunterstich** [comment]
Do you mind providing a sample app so we have more to work with and help diagnose the issue you're having?

**Comment by nikitamarysolomanpvt** [comment]
> Do you mind providing a sample app so we have more to work with and help diagnose the issue you're having?

https://github.com/nikitamarysolomanpvt/oppia-android/tree/high_fi_topic_review_tab PTAL in this

**Comment by hunterstich** [comment]
That app's theme is [extending from AppCompat](https://github.com/nikitamarysolomanpvt/oppia-android/blob/high_fi_topic_review_tab/app/src/main/res/values/styles.xml#L4). To use Material Components, you need to either use a `Theme.MaterialComponents.*` theme or a `Theme.MaterialComponents.*.Bridge` theme.

See here for more info on migrating to a MaterialComponents theme (recommended) - https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#4-change-your-app-theme-to-inherit-from-a-material-components-theme

See here for more info on Bridge themes if you don't want to migrate from your current AppCompat theme - https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#bridge-themes

Additionally, you don't need to add [two dependencies for Material in your :app module's build.gradle file](https://github.com/nikitamarysolomanpvt/oppia-android/blob/high_fi_topic_review_tab/app/build.gradle#L70-L71). Below are the latest stable, beta and alpha versions of the library. Use a single version, depending on the features vs. stability your app needs.

stable: `com.google.android.material:material:1.0.0`
beta: `com.google.android.material:material:1.1.0-beta02`
alpha: `com.google.android.material:material:1.2.0-alpha02`
