### ISSUE TITLE
[Password_input] What is the right eye-icon behaviour?

### ISSUE THREAD

**Issue by naropf** [material-components/material-components-android#758]
In password inputs, the password is hidden when the eye-icon is closed, and password is showed when the eye-icon is open.

What is the right behaviour? that the icon shows the applied action or the future state at the password will become if you pulse it? I mean, when the eye-icon is closed ¿must to show the password or not?

Thanks!

**Comment by leticiarossi** [comment]
The icon indicates the state of the input. So if the password is hidden the icon will have the eye closed:
<img width="340" alt="Screen Shot 2019-11-13 at 10 36 33 AM" src="https://user-images.githubusercontent.com/9288695/68778760-9c958500-0601-11ea-9e29-3b145e66edc2.png">
while if the password is displayed as plain-text the eye will be open:
<img width="339" alt="Screen Shot 2019-11-13 at 10 37 05 AM" src="https://user-images.githubusercontent.com/9288695/68778769-a0c1a280-0601-11ea-9642-7d0cc27f2fe5.png">
