### ISSUE TITLE
[MaterialDatePicker] Partial localization.  

### ISSUE THREAD

**Issue by viktkurl** [material-components/material-components-android#761]
**Description:** There are no methods for modifying hints, input errors and header selection text. By default, if any language other than English is selected on the device, the text on the dialog is only partially translated (In my case part of the text in English and part in Russian). I was helped by redefinition of resources, but this is a temporary solution and I do not think that it should be so

**Expected behavior:** 
 It is expected that there will be a translation into the local language of the device.
<img width="351" alt="Снимок экрана 2019-11-14 в 01 47 04" src="https://user-images.githubusercontent.com/18272431/68812798-f7bc8b80-0684-11ea-89ec-d10188d6dbcd.png">
<img width="358" alt="Снимок экрана 2019-11-14 в 01 48 29" src="https://user-images.githubusercontent.com/18272431/68813046-ab258000-0685-11ea-8e19-2e45f0e68c46.png">

**Source code:** example app https://github.com/viktkurl/MaterialLibIssue

**Android API version:** 28

**Material Library version:** 1.2.0-alpha01

**Device:** emulator Pixel 2 XL

**Comment by viktkurl** [comment]
If it helps anyone, here are the resources I've redefined:

<resources xmlns:tools="http://schemas.android.com/tools">

    <string name="mtrl_picker_range_header_unselected" tools:override="true">Выберите дату</string>

    <string name="mtrl_picker_range_header_only_start_selected" tools:override="true">%s - Дата окончания</string>

    <string name="mtrl_picker_range_header_only_end_selected" tools:override="true">Дата начала - %s</string>

    <string name="mtrl_picker_text_input_date_range_start_hint" tools:override="true">Дата начала</string>

    <string name="mtrl_picker_text_input_date_range_end_hint" tools:override="true">Дата начала</string>

    <string name="mtrl_picker_text_input_date_format" tools:override="true">dd.MM.yyyy</string>

    <string name="mtrl_picker_out_of_range" tools:override="true">Вы вышли за границу\nдопустимых значений: %1$s</string>

    <string name="mtrl_picker_invalid_format" tools:override="true">Неверный формат даты.\Используйте: %1$s</string>

    <string name="mtrl_picker_save" tools:override="true">Сохранить</string>
</resources>

**Comment by matpag** [comment]
This is not Russian related. The translation is missing for all other countries too as you can see here:
https://github.com/material-components/material-components-android/tree/c097d3d33506be7382d3bda20909d5f08bb1f220/lib/java/com/google/android/material/datepicker/res
there are no values-XX language resource folder with strings inside

**Comment by viktkurl** [comment]
> This is not Russian confined. The translations are missing for all other countries too as you can see here:
> https://github.com/material-components/material-components-android/tree/c097d3d33506be7382d3bda20909d5f08bb1f220/lib/java/com/google/android/material/datepicker/res
> there are no values-XX language resource folder with strings inside

Yes, I wrote about it being for any language in description. But for positive, negative and calendar weekdays uses resources from @android:string and translated normally :)

**Comment by Moonglasses** [comment]
Can confirm, no Czech translations in 1.2.0-alpha05.

**Comment by CoolMind** [comment]
@viktkurl, thanks, but it is only for date range. For single date replace strings found [here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/res/values/strings.xml#L24).

**Comment by wbervoets** [comment]
So when will you add the translations for other languages? I assume Google can hire some translators?

**Comment by alianikaydin** [comment]
in **values-az**, date abbreviations should be changed like this.

```
<string name="mtrl_picker_text_input_year_abbr" tools:override="true">i</string>
<string name="mtrl_picker_text_input_month_abbr" tools:override="true">a</string>
<string name="mtrl_picker_text_input_day_abbr" tools:override="true">g</string>
```

**Comment by SanjarIsaboev** [comment]
thank you sir
