### ISSUE TITLE
[BottomNavigationView] Two long clicks on first button in BottomNavigationView causes mobile restart (API24 and API25)

### ISSUE THREAD

**Issue by prof0021** [material-components/material-components-android#764]
The library com.google.android.material:material:1.1.0-beta02 and com.google.android.material:material:1.2.0-alpha01 contains error which causes mobile restart or freeze on API 24 and API 25. It is very easy to simulate it. Just create the activity with BottomNavigationView and create the menu with two items. The first button will do it.

**Comment by hunterstich** [comment]
Hey thanks for reporting this issue! I'm able to reproduce this in our [catalog](https://github.com/material-components/material-components-android/tree/master/catalog) and will look into it.

**Comment by aradxxx** [comment]
Same issue on 1.2.0-alpha03

**Comment by cketcham** [comment]
This appears to be an issue in androidx. You might want to try following up here http://issuetracker.google.com/issues/118880669, but they've marked this as a low priority. I've commented on the internal bug so they are aware this is a case that can cause this issue.
