### ISSUE TITLE
[Chip] Chip icon drawable is not tinting correctly

### ISSUE THREAD

**Issue by fl0cke** [material-components/material-components-android#767]
**Description:** There is something wrong with the way the Chip component handles drawables, as illustrated by my example below.

**Expected behavior:** 

![grafik](https://user-images.githubusercontent.com/3774918/68982684-52cabb80-0808-11ea-9ef1-086816b50075.png)

Here you can see the same drawable included with a regular ImageView on the left and as the `chipIcon` of a Chip component on the right. Clearly, the chip fails to apply the correct tinting for the icon that is included in the drawable.

**Source code:** 

ic_list_24dp.xml
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:tint="#FF0000"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0">
    <path
        android:fillColor="#FF000000"
        android:pathData="M3,13h2v-2L3,11v2zM3,17h2v-2L3,15v2zM3,9h2L5,7L3,7v2zM7,13h14v-2L7,11v2zM7,17h14v-2L7,15v2zM7,7v2h14L21,7L7,7z"/>
</vector>
```

chip_icon_list.xml 
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:width="24dp"
        android:height="24dp">
        <shape android:shape="oval">
            <solid android:color="#EEEEEE" />
        </shape>
    </item>
    <item
        android:width="20dp"
        android:height="20dp"
        android:drawable="@drawable/ic_list_24dp"
        android:gravity="center">
    </item>
</layer-list>
```

layout.xml (excerpt)
```
<ImageView
    android:layout_marginStart="16dp"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:src="@drawable/chip_icon_list">

</ImageView>

<com.google.android.material.chip.Chip
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginStart="16dp"
    android:text="Stories"
    app:chipIcon="@drawable/chip_icon_list" />
```

**Android API version:** 29

**Material Library version:** 1.2.0-alpha01

**Device:** Pixel 4

**Comment by wcshi** [comment]
Hi, thank you for reporting this issue, this is a known limitation of Chip. As a workaround, could you please try setting app:chipIconTint to #FF0000 ?

**Comment by fl0cke** [comment]
Your proposed solution doesn't work unfortunately. It tints the entire drawable red and not just the list icon inside. Could you explain a little more what is happening here and why this limitation is specific to the Chip component? Thanks!

**Comment by wcshi** [comment]
Ohh, you are right, I forgot about the background oval shape. As part of supporting chipIconTint, we Chip also needs to support removing the tint. Currently Chip doesn't know whether chipIconTint == null because one was never set or because a user set it to null in order to remove then tint.

What's your time line for needing this fix? I will try to prioritize it for the next week or so.

**Comment by fl0cke** [comment]
Thanks for the explanation 👍 This is just a side project of mine, so there is no real timeline. Nevertheless, I am looking forward to a fix!
