### ISSUE TITLE
[Dialog] materialAlertDialogTheme is not public

### ISSUE THREAD

**Issue by ataulm** [material-components/material-components-android#769]
**Description:**

`materialAlertDialogTheme` is not explicitly marked as public, though similar theme attributes are [in this file](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/dialog/res-public/values/public.xml#L48-L50) and the attribute is meant for [public use](https://github.com/material-components/material-components-android/blob/575ee10006813e1b523207c6303822fb08bf9b4e/docs/components/Dialog.md).

This means that Lint will flag its usage in code:

![image](https://user-images.githubusercontent.com/2678555/69020177-bec74280-0a07-11ea-8d04-02cbd6cdf2c8.png)

**Expected behavior:**

I'd expect the attribute to be marked as public too, since it's used in a similar way to the other attributes, so that Lint doesn't flag it.

**Material Library version:**
1.1.0-beta02

**Comment by ataulm** [comment]
Also if this is done, would it make sense to rename this to `materialAlertDialogThemeOverlay` to match `materialThemeOverlay`?

**Comment by chrisonline** [comment]
I have the same problem in XML, but with 1.1.0-alpha01.
In 1.1.0-beta02 it is still working.
