### ISSUE TITLE
Add new `Dialog` component

### ISSUE THREAD

**Issue by sfdexter** [material-components/material-components-android#77]
https://material.io/go/design-dialogs

**Comment by r9software** [comment]
+1

**Comment by friederikewild** [comment]
Any plans for when we might get material dialogues as an Android component? Having the design specs is great, but the "planned" label sounds if developers will be stuck again with having to rely on external libraries or own implementations mimicking the design guide.

Now it's already in release candidate phase, but I really hope it will still be added at some point?

**Comment by rio258k** [comment]
I could really use this in my project....

**Comment by 19lmyers** [comment]
Is this going to happen soon, or am I stuck using AlertDialog / a custom DialogFragment?

**Comment by costular** [comment]
> Is this going to happen soon, or am I stuck using AlertDialog / a custom DialogFragment?

I think it's not going to happen soon. Anyway, you can do great stuff with **[AppCompatDialogFragment](https://developer.android.com/reference/android/support/v7/app/AppCompatDialogFragment)**.

**Comment by ldjcmu** [comment]
A new MaterialAlertDialogBuilder that creates an AlertDialog is currently being worked on; you will start seeing it as a WIP in the next alpha release. The created AlertDialog will adopt themeing (color and shape).

**Comment by sky10p** [comment]
Is this the ideal component to make a prompt asking for an string?

Thanks!

**Comment by costular** [comment]
@sky10p it depends on the case. It could be fair

**Comment by ldjcmu** [comment]
Closing as the component exists. Please feel free to open issues to report issues. There are still plenty of updates coming for the component, but we'll track those as normal bugs.
