### ISSUE TITLE
[Slider] Allow to set color styling attributes in code

### ISSUE THREAD

**Issue by mpost** [material-components/material-components-android#770]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to set the color properties of the new [`Slider`](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/slider/Slider.java) view via xml.

**Describe the solution you'd like**
It should be possible to alter the appearance in code as well.

**Comment by Sourav-21** [comment]
It is very much possible. [These](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/slider/res-public/values/public.xml) are public design attributes for Slider.

**Comment by mpost** [comment]
@Sourav-21 As stated it in the code it should be possible to change these attributes during runtime programmatically. The current solution only allows to change them once on creation.

**Comment by hunterstich** [comment]
Hey there. Adding getters/setters for Slider parameters is something we're aware of and have scheduled as part of the ongoing work that's happening on the component. 

Thanks for filing and helping us prioritize.

**Comment by mpost** [comment]
That is good to hear. Looking forward to the update. :)

**Comment by cketcham** [comment]
fixed by 3e212efdc21dc65b45dcf7276b87e6f5f9d4ff61
