### ISSUE TITLE
[Slider] Allow to distinguish between user and programmatic change events

### ISSUE THREAD

**Issue by mpost** [material-components/material-components-android#771]
**Is your feature request related to a problem? Please describe.**
When using a `com.google.android.material.slider.Slider.OnChangeListener` it is not possibel to distinguish between user made changes or programmatic changes.

**Describe the solution you'd like**
Similar to the app compat slider, it should be possible to be informed whether the change is user triggered or made by an API call.

**Comment by Sourav-21** [comment]
Yes. I need this feature also. Like the `fromUser` boolean from Seekbar's [OnProgressChanged](https://developer.android.com/reference/android/widget/SeekBar.OnSeekBarChangeListener.html#onProgressChanged(android.widget.SeekBar,%20int,%20boolean))

**Comment by Pittvandewitt** [comment]
For the time being you may want to declare a local variable fromUser and set this listener on the slider.

    setOnTouchListener { _, motionEvent ->
        when (motionEvent.action) {
            MotionEvent.ACTION_UP -> fromUser = false
            else -> fromUser = true
        }; false
     }
Then you can call this variable in your OnChangeListener to determine if the change was made programmatically or not.
It's not perfect but it does the job

**Comment by rubensousa** [comment]
I've opened a PR that fixes this: https://github.com/material-components/material-components-android/pull/831

**Comment by cketcham** [comment]
Fixed by cde09d4b4e8a2ad8a6d73e449f8fb09e404ea3ea
