### ISSUE TITLE
[MaterialDatePicker] Setting start and end date should honor days

### ISSUE THREAD

**Issue by mpost** [material-components/material-components-android#772]
**Is your feature request related to a problem? Please describe.**
Currently we can only limit the month with a given start and end date.

**Describe the solution you'd like**
It should be possible to limit start and end to a certain day. Eg three days before and after today.

**Comment by hunterstich** [comment]
Hey @mpost. Thanks for taking the time to file an issue.

Do you mean you'd like to be able to limit the dates that are valid to ±X number of days from the current date? Have you had a chance to look into creating your own [DateValidator](https://github.com/material-components/material-components-android/blob/691b1bdc0674ee9f0a089d3e85a0195fdb1b8d9e/lib/java/com/google/android/material/datepicker/CalendarConstraints.java#L47)? It might be helpful to reference [DateValidatorPointForward](https://github.com/material-components/material-components-android/blob/691b1bdc0674ee9f0a089d3e85a0195fdb1b8d9e/lib/java/com/google/android/material/datepicker/DateValidatorPointForward.java) and create something similar for your specific use case.

**Comment by mpost** [comment]
@hunterstich I have not implemented a custom `DateValidator`. Would it disable invalid days in the picker?

**Comment by hunterstich** [comment]
Yep, it would. A date being enabled/disabled depend on whether `DateValidator.isValid()` returns true or false. 

I'm going to close this issue for now. If you look into `DateValidator` and find that it's not what you need or you have questions, feel free to re-open!
