### ISSUE TITLE
TextInputLayout OutlinedBox not showing

### ISSUE THREAD

**Issue by ABr751** [material-components/material-components-android#776]
**Expected behavior:** need  outlinedbox as in materialcomponents 1.0.0

    <style name="TextInputLayoutStyle" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense">
        <item name="boxStrokeColor">@color/grey_c7c7c7</item>
        <item name="android:textColor">@color/colorAccent</item>
        <item name="android:textColorHint">@color/black_overlay</item>
    </style>

**Android API version:** Android API version here

**Material Library version:** com.google.android.material:material:1.1.0-beta02'
**Device:** Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by hunterstich** [comment]
Hey @ABr751  any chance you'd be able to attach a small sample app that reproduces the issue as well as some additional details around what the expected behavior is vs. what you're actually seeing?

**Comment by ABr751** [comment]
https://github.com/tiper/MaterialSpinner/issues/16#issue-522627983   Please have a look at this.It,s something like this the outline is not showing in studio layout and also the material spinner was working fine with the outlinedBox and which is not working right now

**Comment by hunterstich** [comment]
Running our catalog with the following layout:
```
  <com.google.android.material.textfield.TextInputLayout
      style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_margin="4dp"
      android:hint="@string/cat_textfield_label"
      app:counterEnabled="true"
      app:counterMaxLength="10"
      app:errorEnabled="true"
      app:helperText="@string/cat_textfield_outlined_helper_text"
      app:helperTextEnabled="true">
    <com.google.android.material.textfield.TextInputEditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
  </com.google.android.material.textfield.TextInputLayout>
```
produces an outlined text field as expected:
![Screenshot_1574265063](https://user-images.githubusercontent.com/7459254/69254180-ad4a7b80-0b6a-11ea-980e-baa41075eb29.png)

Are you able to upload a sample that reproduces your issue?

**Comment by mobilekosmos** [comment]
I also had this problem while migrating to this lib and after trying to find the difference with a clean project where it wasn't reproducible I found out that in my TextInputEditText I was setting android:background="@android:color/transparent" which is recommended when using the AppCompat Theme and you want to get rid of the underlying line.

**Comment by sanjay-chawla** [comment]
I faced this too. Error: 

> the style on this component requires your app theme to be theme.materialcomponents (or a descendant)

I was using AppCompat Theme and changing the theme to MaterialComponents theme fixed the outlined box. Source: https://material.io/develop/android/docs/getting-started/
Can you try changing the theme in style.xml?

**Comment by bblackbelt** [comment]
same here, with 1.1.0-rc01. Was working perfectly fine with 1.0.0

**Comment by darkrider1287** [comment]
+1, I am also having this exact issue when upgrading from:

com.google.android.material:material:1.1.0-beta01
to
com.google.android.material:material:1.2.0-alpha03

The issue appears to be in the Android Studio layout preview, but not in the app itself. This is a non-starter for my development, and forcing me to stay on Material library 1.1.0 until it is fixed.

**Comment by Alirezaaraby** [comment]
I solved this problem with replacing any other versions of material design with `1.1.0-alpha09'`

**Comment by pravingaikwad07** [comment]
https://stackoverflow.com/a/58074458/5582162 - Solution

**Comment by darkrider1287** [comment]
> https://stackoverflow.com/a/58074458/5582162 - Solution

The linked fix doesn't work in Material 1.2.x - this is still regressed from Material 1.1.x -> 1.2.x

**Comment by rhlmshr** [comment]
I am still facing the same issue.

Lib Version -> 1.1.0

Using this 
```
<com.google.android.material.textfield.TextInputLayout
  style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:layout_margin="@dimen/d_15dp" >

  <com.google.android.material.textfield.TextInputEditText
      android:layout_width="match_parent"
      android:hint="Filled box dense"
      android:text="advcadv"
      android:layout_height="wrap_content" />

</com.google.android.material.textfield.TextInputLayout>
```

Above code crashes with 

>   Caused by: android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class com.google.android.material.textfield.TextInputLayout
     Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class com.google.android.material.textfield.TextInputLayout
     Caused by: java.lang.reflect.InvocationTargetException

**Comment by felipe-gouveia** [comment]
I'm also experiencing the same issue. Downgrading to com.google.android.material:material:1.0.0 solves it. 1.1.0 and 1.20 were a no go.

**Comment by wcshi** [comment]
Could someone please confirm if this is an issue in an Android app or in Studio preview? Thank you!

**Comment by darkrider1287** [comment]
> Could someone please confirm if this is an issue in an Android app or in Studio preview? Thank you!

this is happening only in the Android Studio preview for me

**Comment by wcshi** [comment]
@darkrider1287 thanks, could you please tell us which version of Android Studio you are using and whether the bug is reproducible in Studio 4.x?

**Comment by wcshi** [comment]
This bug is tracked at Studio's public issue tracker http://issuetracker.google.com/issues/150225404

**Comment by AtifAbbAsi19** [comment]
"Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense" causing inflating bug

**Comment by Vitor238** [comment]
> I am still facing the same issue.
> 
> Lib Version -> 1.1.0
> 
> Using this
> 
> ```
> <com.google.android.material.textfield.TextInputLayout
>   style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
>   android:layout_width="match_parent"
>   android:layout_height="wrap_content"
>   android:layout_margin="@dimen/d_15dp" >
> 
>   <com.google.android.material.textfield.TextInputEditText
>       android:layout_width="match_parent"
>       android:hint="Filled box dense"
>       android:text="advcadv"
>       android:layout_height="wrap_content" />
> 
> </com.google.android.material.textfield.TextInputLayout>
> ```
> 
> Above code crashes with
> 
> > Caused by: android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class com.google.android.material.textfield.TextInputLayout
> > Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class com.google.android.material.textfield.TextInputLayout
> > Caused by: java.lang.reflect.InvocationTargetException

Same problem using Android Studio 4.0. Only works in version 1.0.0

**Comment by ping-devsky** [comment]
<com.google.android.material.textfield.TextInputLayout
                style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/login_edit_password"
                android:textColor="@color/black"
                app:boxStrokeColor="@color/black"
                app:boxStrokeWidthFocused="2dp"
                android:layout_marginTop="10dp"
                app:endIconMode="password_toggle"
                app:endIconTint="@color/black"
                app:hintTextColor="@color/black"
                app:startIconDrawable="@drawable/login_password_icon"
                app:startIconTint="@color/black">

                <com.google.android.material.textfield.TextInputEditText
                    android:id="@+id/login_edit_password"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:fontFamily="@font/muli_black"
                    android:inputType="textPassword" />


            </com.google.android.material.textfield.TextInputLayout>





The above is my code i was facing the same problem but after changing my styles.xml with  <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge"> this tag in place of the existing one it works perfectly fine.

**Comment by ssujr** [comment]
I'm having the same issue using either v1.2.0 or v1.3.0-alpha2. BTW, it is not happening in v1.1.0.

To keep using v1.2.0 with custom background color. Here is my workaround. Move android:background from styles.xml to layout xml.

**Comment by ShreyaJamsandekar** [comment]
One solution that can be mentioned here
please remember that in the XML file 
  android:theme="@style/Theme.MaterialComponents"

this parent theme has to be added otherwise the app crashes

**Comment by MauricioRojasf** [comment]
Any updates on this?, still cant get the outlinebox to work properly. tested on version 1.1.0 , 1.2.x and 1.3.0-alphax. Its only working on version 1.0.0 but downgrading breaks some of my layouts because it doesnt have some attributes i use on those components.

**Comment by ZeroCooL992** [comment]
For me its only working if I add new Style theme with parent " Theme.MaterialComponents.Light.NoActionBar". This is only parent who has shown as convinent, regardless of the MaterialDesign used. I use the latest version right now (1.3.0-alpha03)

**Comment by Prabha10cs** [comment]
i am always used to Theme.MaterialComponents.Light.NoActionBar but outline not showing

**Comment by PLXI-FenilTailor1971** [comment]
i am always used to Theme.MaterialComponents.Light.NoActionBar but outline not showing

**Comment by PLXI-FenilTailor1971** [comment]
**if you used dark theme then only show outline border otherwise not Showing..**

**Comment by rakuishi** [comment]
It seems that `TextInputLayout` uses `colorPrimary` for its outline border in v1.2.1.
I solved this problem with following code:

```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge">
    - <item name="colorPrimary">@android:color/white</item>
    + <item name="colorPrimary">@android:color/black</item>
</style>
```

**Comment by Roshannahak** [comment]
> The above is my code i was facing the same problem but after changing my styles.xml with <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge"> this tag in place of the existing one it works perfectly fine.
> 
> Do take a look
> 
> <com.google.android.material.textfield.TextInputLayout
> style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
> android:layout_width="match_parent"
> android:layout_height="wrap_content">
> 
> ```
>             <com.google.android.material.textfield.TextInputEditText
>                  android:layout_width="match_parent"
>                 android:layout_height="match_parent"  />
>    </com.google.android.material.textfield.TextInputLayout>
> ```

{thanks}

**Comment by AnasMually** [comment]
hello 
i i don't show solve for this problem  
please

**Comment by Roshannahak** [comment]
> i don't found solve for this problem
> can you help me if you solved

use the latest material dependency  implementation 'com.google.android.material:material:1.2.1'
follow code in style.xml :-

```
    <style name="TextInputLayoutStyle" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense">
        <item name="boxStrokeColor">@color/ui_black</item>
        <item name="android:textColor">@color/colorAccent</item>
    </style>
```
use `style` tag inside the **TextInputLayout**
`style="@style/TextInputLayoutStyle"`

**Comment by ranjan-technoexponent** [comment]
<com.google.android.material.textfield.TextInputLayout
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_margin="15dp"
                    app:boxStrokeColor="@color/colorPrimary">

                    <com.google.android.material.textfield.TextInputEditText
                        android:id="@+id/emailText"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:background="@android:color/transparent"
                        android:fontFamily="@font/stolzl_regular"
                        android:hint="Email"
                        android:inputType="textEmailAddress"
                        android:textColor="@color/black"
                        android:textSize="14sp" />
</com.google.android.material.textfield.TextInputLayout>

Outline Box is not working when I am changing my styles to-
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
</style>

**Comment by sabinebarrera** [comment]
@ranjan-technoexponent you don’t see the outline b/c your background is transparent. See [[TextInputLayout] [TextInputEditText] Setting the background to transparent doesn't render outlinedbox or filledbox](https://github.com/material-components/material-components-android/issues/1980).

**Comment by AnasMually** [comment]
> > i don't found solve for this problem
> > can you help me if you solved
> 
> use the latest material dependency  implementation 'com.google.android.material:material:1.2.1'
> follow code in style.xml :-
> 
> ```
>     <style name="TextInputLayoutStyle" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense">
>         <item name="boxStrokeColor">@color/ui_black</item>
>         <item name="android:textColor">@color/colorAccent</item>
>     </style>
> ```
> use `style` tag inside the **TextInputLayout**
> `style="@style/TextInputLayoutStyle"`

Thanks you ❤️

**Comment by harilakkakula** [comment]
> The above is my code i was facing the same problem but after changing my styles.xml with <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge"> this tag in place of the existing one it works perfectly fine.
> 
> Do take a look
> 
> <com.google.android.material.textfield.TextInputLayout
> style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
> android:layout_width="match_parent"
> android:layout_height="wrap_content">
> 
> ```
>             <com.google.android.material.textfield.TextInputEditText
>                  android:layout_width="match_parent"
>                 android:layout_height="match_parent"  />
>    </com.google.android.material.textfield.TextInputLayout>
> ```

this is works after changing the AppTheme parent

**Comment by AbdelMfossa** [comment]
Make sure that in your [AndroidManifest.xml]() file, you have a materialcomponents as theme for your Activity.
Some thing like this: `<activity android:name=".activities.LoginActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.MaterialComponents.Light.NoActionBar">
</activity>`

**Comment by Vikash174** [comment]
> Make sure that in your AndroidManifest.xml file, you have a materialcomponents as theme for your Activity.
> Some thing like this:
> 
> ```
> <activity android:name=".activities.LoginActivity"
>           android:screenOrientation="portrait"
>           android:theme="@style/Theme.MaterialComponents.Light.NoActionBar">
> </activity>
> ```

it worked for me thank you  for version 1.3.0

**Comment by nickthelegend** [comment]
> Make sure that in your AndroidManifest.xml file, you have a materialcomponents as theme for your Activity. Some thing like this:
> 
> ```
> <activity android:name=".activities.LoginActivity"
>           android:screenOrientation="portrait"
>           android:theme="@style/Theme.MaterialComponents.Light.NoActionBar">
> </activity>
> ```

This Helped me thanks a lot
