### ISSUE TITLE
[MaterialDatePicker] todayInUtcMilliseconds strips day information

### ISSUE THREAD

**Issue by renclav** [material-components/material-components-android#778]
**Description:** The static method `MaterialDatePicker.todayInUtcMilliseconds()` returns _today_ in milliseconds whereby the day is always set to the first of the month.

**Expected behaviour:** The returned timestamp correctly reflects the current day as inferred by the method name.

**Source code:** Inside the _com.google.android.material.datepicker.Month_ constructor
```
private Month(@NonNull Calendar rawCalendar) {
    rawCalendar.set(Calendar.DAY_OF_MONTH, 1);
    ...
}
```

**Android API version:** 29 and 24

**Material Library version:** 1.2.0-alpha01

**Device:** Pixel 2 XL on API 29 and official emulator with play store on API 24

**Comment by ldjcmu** [comment]
Just adding some additional information.
This also affects 1.1.0-beta02 and should be fixed before stable.

We should update this method to correctly not strip day information.
Current library usages of this method that depend upon its stripping behavior should be updated to use Month.today().timeInMillis or the UtcDates utility.

**Comment by renclav** [comment]
While the name change makes sense. I still feel like we need a public version of this call that does not strip day information, especially for common uses cases like date validators, where we need the timestamp in the format used by the picker itself.
