### ISSUE TITLE
[SwitchMaterial] showText = true BUG

### ISSUE THREAD

**Issue by solareye** [material-components/material-components-android#787]
**Description:** I'm only trying set `textOn`, `textOff` stringResources with `showText = true` for SwitchMaterial. Nothing special. Result is below.

Switch checked true
![image](https://user-images.githubusercontent.com/2784705/69420989-ec2a2e00-0d30-11ea-88e6-929972eb40ee.png)
Switch checked false
![image](https://user-images.githubusercontent.com/2784705/69421038-095efc80-0d31-11ea-9af2-03f75dd1628a.png)

**Source code:** `<com.google.android.material.switchmaterial.SwitchMaterial
                android:id="@+id/privateSwitch"
                android:layout_width="match_parent"
                android:layout_height="@dimen/item_height_64"
                android:layout_margin="@dimen/margin"
                android:drawableStart="@drawable/ic_private"
                android:drawablePadding="@dimen/padding_half"
                android:textOff="@string/private_switch_off"
                app:showText="true"
                android:textOn="@string/private_switch_on"
                app:drawableTint="@color/colorIconDefault"
                app:layout_constraintTop_toBottomOf="@id/helperDescriptionLabel" />`

also programmatically
`privateSwitch.apply {
            textOn = getString(R.string.private_switch_on)
            textOff = getString(R.string.private_switch_off)
            showText = true
        }`

**Android API version:** 29

**Material Library version:** 1.2.0-alpha02

**Device:** Pixel 1, OnePlus 6

**Comment by drchen** [comment]
According to the androidx team - the text on SwitchCompat is not supported. 

Closing the issue as WAI.
