### ISSUE TITLE
[TextInputLayout] setError does not respect drawables set by setCompoundDrawablesWithIntrinsicBounds

### ISSUE THREAD

**Issue by dryaz** [material-components/material-components-android#788]
**Description:** 
Set start drawable for editText
`input.editText!!.setCompoundDrawablesWithIntrinsicBounds(
                    R.drawable.ic_user_stroker_gray_30dp...`

Then set non `null` error to TextInputLayout:
`input.error = if (value.isNullOrEmpty()) null else getString(errorId)`

Inside TextLayoutInput it calls `updateDummyDrawables` which tries to get RelativeDrawables

`final Drawable[] compounds = TextViewCompat.getCompoundDrawablesRelative(editText);`

And it does not find any start drawable and draw an empty drawable:

<img width="425" alt="errro_ok" src="https://user-images.githubusercontent.com/1395176/69555088-acbf4400-0fb3-11ea-9fe9-8ae9dba25d73.png">
<img width="292" alt="error-bug" src="https://user-images.githubusercontent.com/1395176/69555096-afba3480-0fb3-11ea-8f98-ef5146bdeba2.png">

PS. I use english language on device (icon on left, error on right).

**Expected behavior:** 

If I call `setCompoundDrawablesRelativeWithIntrinsicBounds` instead of `setCompoundDrawablesWithIntrinsicBounds` everything works fine

<img width="240" alt="error_fixed" src="https://user-images.githubusercontent.com/1395176/69555246-ea23d180-0fb3-11ea-9ddf-91ffefb38e12.png">

**Source code:** 
        `input.editText!!.setCompoundDrawablesWithIntrinsicBounds(
            R.drawable.ic_user_stroker_gray_30dp,
            0,
            0,
            0
        )
        input.error = "error"`

**Android API version:** 
targetSdkVersion 28

**Material Library version:** 
implementation "com.google.android.material:material:1.2.0-alpha02"

**Device:** 
OnePlus 7 Pro

**Comment by matpag** [comment]
Have you tried using `textInput.setStartIconDrawable(drawable)` instead of providing it to the `Edittext`?

**Comment by dryaz** [comment]
> Have you tried using `textInput.setStartIconDrawable(drawable)` instead of providing it to the `Edittext`?

Just tried like this 

`input.setStartIconDrawable(R.drawable.ic_user_stroker_gray_30dp)
        input.setEndIconDrawable(R.drawable.ic_done_lime_24dp)

        input.isStartIconVisible = true
        input.isEndIconVisible = valid(value)`

Doesn't work at all in my case. Maybe it because I'm using vector drawable.
Will check your suggestion more carefully later.

**Comment by matpag** [comment]
You are missing the mode parameter. If you don't set it, the icon will not be showed.
Try with this:
```
@SuppressLint("WrongConstant")
input.endIconMode = TextInputLayout.END_ICON_CUSTOM
input.setEndIconDrawable(R.drawable.ic_done_lime_24dp)
```

**Comment by leticiarossi** [comment]
Using `setStartIconDrawable` and `setEndIconMode` to custom mode and `setEndIconDrawable`, as explained above, should work. More info about the icons API usage can be found [here](https://github.com/material-components/material-components-android/blob/master/docs/components/TextInputLayout.md#end-icon-modes). If you still find any problems feel free to reopen this issue.
