### ISSUE TITLE
Add new `Extended FAB` component

### ISSUE THREAD

**Issue by sfdexter** [material-components/material-components-android#79]
https://material.io/go/design-extended-fab

**Comment by mattpeskett** [comment]
An extended FAB was added to material-components-web [here](https://github.com/material-components/material-components-web/issues/2043). Can we expect the same for Android anytime soon?

**Comment by benju69** [comment]
Any news ? Any deadline ?

**Comment by GuiOliveira1995** [comment]
I can't find anything on internet. Hope they include android code soon.

**Comment by firatkarababa** [comment]
Extended FAB component will not be available as a part of Material Components till August at least, based on the [roadmap](https://github.com/material-components/material-components/blob/develop/ROADMAP.md#r18---august-2018).

**Comment by simonesestito** [comment]
@firatkarababa I can't see it in Android roadmap anymore. In July release I see "--" while every other platform has it.
Am I missing anything?

**Comment by simonesestito** [comment]
@firatkarababa What do you mean with "Shape Theme release"?

**Comment by simonesestito** [comment]
I've been able to reproduce a FAB using MaterialButton. If you want to give a look, I've created a public Gist
https://gist.github.com/simonesestito/edf434544ed8bf6ef23ae5e9af625149

@benju69 @firatkarababa @GuiOliveira1995 @mattpeskett

**Comment by friederikewild** [comment]
Any news from the official site, when then Extended FAB will be added to Android? Still nothing on the future Roadmap :(

Great initiative @simonesestito 👍 I'll check that out as work-around since my designer already jumped at the new cool elements

**Comment by donnellycolton** [comment]
@simonesestito I wonder if there's a way to inherit the Extended FAB from the standard FAB as well as Material Button so we can use it anchored to a BottomAppBar...

**Comment by simonesestito** [comment]
@donnellycolton I would like to do that, but I haven't been able to.

**Curiosity:** I've just decompiled Google Tasks app and I was surprised to find a themed MaterialButton to reproduce the extended FAB

**Comment by tunjid** [comment]
I wrote a helper that animates a MaterialButton to a FloatingActionButton and back. 

Full source can be seen [here](https://github.com/tunjid/android-bootstrap/blob/master/view/src/main/java/com/tunjid/androidbootstrap/view/animator/FabExtensionAnimator.java):

If you want to add it as a dependency to your project please see the [readme](https://github.com/tunjid/android-bootstrap) for the project 😊 

Here's a gif of it in action:
 
![alt text](https://camo.githubusercontent.com/e11085afbde93a6c05835fcd752ec9a1b7d68541/68747470733a2f2f63646e2d696d616765732d312e6d656469756d2e636f6d2f6d61782f313630302f312a737854626c4e36596b4c6e47536f4e6a7545664761772e676966 "Logo Title Text 1")

**Comment by AKalloe** [comment]
Hi there, any news on when this feature will be completed?

**Comment by joshfriend** [comment]
@AKalloe google will never comment on when a feature will be done. If the feature does not currently exist, the answer to your question will always be "not yet"

**Comment by nurilyas7** [comment]
Can be achieved like so [here](https://github.com/nurilyas7/sgprayertimes/blob/c5fc0d680cd3ad4669c088164613f3b2f44dd85f/app/src/main/res/values/styles.xml#L34-L45). The output will look something like this.


![screenshot_20181216-224240_2](https://user-images.githubusercontent.com/14259666/50055015-11f39e00-0184-11e9-81e8-f8f2b299e1d6.png)

**Comment by carstenhag** [comment]
Note: @nurilyas7's solution will not work in current projects. 

`android:textAppearance="?android:attr/textAppearanceLargeInverse"` has to be declared too or inflating the xml will fail.

**Comment by judemanutd** [comment]
This worked quite well for me 

```
 <com.google.android.material.button.MaterialButton
        android:id="@+id/fab"
        style="@style/Widget.MaterialComponents.Button"
        android:layout_width="wrap_content"
        android:layout_height="64dp"
        android:layout_gravity="bottom|end"
        android:layout_marginEnd="@dimen/fab_margin"
        android:layout_marginBottom="@dimen/fab_margin"
        android:elevation="@dimen/fab_elevation"
        android:text="@string/fab_text"
        android:textColor="@color/textOnAccent"
        android:textSize="14sp"
        app:backgroundTint="@color/colorAccent"
        app:cornerRadius="32dp"
        app:icon="@drawable/ic_night_mode"
        app:iconTint="@color/textOnAccent" />
```

**Comment by ldjcmu** [comment]
ExtendedFab will land in in the next alpha release (alpha-1.0.4). We'll start tracking individual issues for this component.

**Comment by AnkitPatanaik** [comment]
@ldjcmu when will ExtendedFab make it out of alpha?

**Comment by ldjcmu** [comment]
I unfortunately don't know when we will have a stable release as this is dependent on some other Google teams in our case.

For extended FAB specifically, we have no major plans to change the API, but it is possible that some things such as renamings happen before stable.
