### ISSUE TITLE
[MaterialAlertDialog] Add option to tint icon

### ISSUE THREAD

**Issue by ggajews** [material-components/material-components-android#791]
Currently, there is no way to tint icon, which makes it look bad either on dark or light theme

![Screenshot_1574794763](https://user-images.githubusercontent.com/1298590/69664035-718a4700-107f-11ea-824d-83986609780c.png)

![Screenshot_1574794725](https://user-images.githubusercontent.com/1298590/69664044-76e79180-107f-11ea-817f-c16445258943.png)

Please add an option to set icon tint, or set it to the theme color.

**Comment by gabrielemariotti** [comment]
You can use the `materialAlertDialogTitleIconStyle` attribute in the style.  
Something like:

```
  <style name="CustomMaterialAlertDialog" parent="@style/ThemeOverlay.MaterialComponents.MaterialAlertDialog">
    <item name="materialAlertDialogTitleIconStyle">@style/Icon_Tint</item>
  </style>
```
with:
 ```
 <style name="Icon_Tint" parent="@style/MaterialAlertDialog.MaterialComponents.Title.Icon">
    <item name="android:tint">@color/primaryLightColor</item>
  </style>
```
<img width="237" alt="Schermata 2019-11-27 alle 09 51 53" src="https://user-images.githubusercontent.com/2583078/69708273-94f2d780-10fb-11ea-8ed9-44b0adfb3075.png">
