### ISSUE TITLE
[Theme.MaterialComponents] Dialog.Alert width are not working on DialogFragment

### ISSUE THREAD

**Issue by orteney** [material-components/material-components-android#799]
**Description:** `DialogFragment` does not become the minimum dialog width when using it with `Theme.MaterialComponents.Light.Dialog.Alert`. 

![Screenshot_1574923492](https://user-images.githubusercontent.com/26565071/69783315-de1f5600-11e5-11ea-832e-0e8c3c08685e.png)

When using a `DialogFragment` with `ThemeOverlay.MaterialComponents.Dialog.Alert` or any of AppCompat version (e.g. `Theme.AppCompat.Light.Dialog.Alert`) the dialog width is ok.

The only one different that i found is style declared without `android:` tag:
```
<style name="Base.Theme.MaterialComponents.Light.Dialog.Alert">
    <item name="windowMinWidthMajor">@dimen/abc_dialog_min_width_major</item>
    <item name="windowMinWidthMinor">@dimen/abc_dialog_min_width_minor</item>
</style>

<style name="Base.Theme.AppCompat.Light.Dialog.Alert">
     <item name="android:windowMinWidthMajor">@dimen/abc_dialog_min_width_major</item>
     <item name="android:windowMinWidthMinor">@dimen/abc_dialog_min_width_minor</item>
</style>
```

**Expected behavior:** 
![Screenshot_1574923494](https://user-images.githubusercontent.com/26565071/69783631-7a495d00-11e6-11ea-958e-6fb5891d3d97.png)

**Source code:** 
I'm implemented a simple app with 4 buttons, each of which launch a DialogFragment with one of the following themes:

- Theme.AppCompat.Light.Dialog.Alert
- ThemeOverlay.AppCompat.Dialog.Alert
- Theme.MaterialComponents.Light.Dialog.Alert
- ThemeOverlay.MaterialComponents.Dialog.Alert

Demo app: https://github.com/orteney/MC-Dialog-Theme-Issue

**Android API version:** 29

**Material Library version:** 1.1.0-beta02

**Device:** Any

**Comment by Hospes** [comment]
The same problem here, need manually set `android:windowMinWidthMajor` as extra attributes for theem to make minWidth dialogs workng properly
