### ISSUE TITLE
[Chip] Text alignement is wrong when the text is only one letter and there is no icon

### ISSUE THREAD

**Issue by dzamlo** [material-components/material-components-android#800]
**Description:** When the text of a chip is a single letter and there is no icon or close icon, the text alignment is wrong

![image](https://user-images.githubusercontent.com/2960379/69795099-d488f480-11cb-11ea-8931-2ba0000e0e91.png)

**Expected behavior:** The text on the chip is centered

**Source code:** The bug can be reproduced by modifying the catalog app: 
* set one of the element of `cat_chip_group_text_array` to a single letter
* comment the `chip.setCloseIconVisible(true);` line in `catalog/java/io/material/catalog/chip/ChipGroupDemoFragment.java`
* in the app, open the chip group demo

**Android API version:** 28
**Material Library version:** material:1.2.0-alpha02 and current master

**Device:** Android emulator

**Comment by wcshi** [comment]
Thanks for reporting the bug, I think I found the issue, will work on a fix next week.
