### ISSUE TITLE
[TextInputLayout] Disabling helper text clears it

### ISSUE THREAD

**Issue by xxfast** [material-components/material-components-android#801]
**Description:** Disabling the helper text also clears the helper text
![bug-2](https://user-images.githubusercontent.com/13775137/69840502-ec39a900-12af-11ea-81eb-d53538491845.gif)

**Expected behavior:** Disabling the helper text shouldn't clear the helper text. This should simply hide it.

**Android API version:** 28

**Material Library version:** 1.2.0-alpha01 (latest)

**Device:** Pixel 3 Emulator

**Comment by wcshi** [comment]
This is WAI, updated to feature request because the hint text behaves differently.

**Comment by gabrielemariotti** [comment]
@wcshi 
Disabling the hint should also clear the hint label?

**Comment by drchen** [comment]
Hint behaves kind of differently. By "disabling hint", you are disabling the hint provided by TextInputLayout and turning into using EditText's built-in hint, i.e., no collapsing label support. 

Closing the issue as WAI.
