### ISSUE TITLE
[Slider] Implement OnSeekBarChangeListener support

### ISSUE THREAD

**Issue by Pitel** [material-components/material-components-android#803]
https://developer.android.com/reference/android/widget/SeekBar.OnSeekBarChangeListener

**Is your feature request related to a problem? Please describe.**
* I want to perform some action when user stops dragging and finaly decides which value he wants.
* I don't want to fire any event, when the value is changed programatically (see #771)

None of it is easily doable with Slider, bit SeekBar can handle both.

**Describe the solution you'd like**
I'd like to be able to set `OnSeekBarChangeListener` on `Slider`.

**Describe alternatives you've considered**
Handling all the scanrious described above manually. With all those MotionEvents, it get's pretty messy, and buggy, and should be handled by Slider.

**Comment by rubensousa** [comment]
I've opened a PR that fixes this: https://github.com/material-components/material-components-android/pull/831

**Comment by cketcham** [comment]
fixed by cde09d4b4e8a2ad8a6d73e449f8fb09e404ea3ea
