### ISSUE TITLE
[FloatingActionButton] Not hiding after collapse

### ISSUE THREAD

**Issue by LimeByte** [material-components/material-components-android#805]
**Description:**
Floating action button does not hide when called directly after a collapse

**Expected behavior:**
Floating action button menu collapses and the button is hidden

**Source code:** 

```
floatingActionButton.isExpanded = false
floatingActionButton.hide()
```

**Android API version:**
Min 27, Compile 29

**Material Library version:**
1.1.0-beta01

**Device:**
Zebra TC51

**Comment by wcshi** [comment]
Could you please attach a sample app?

**Comment by LimeByte** [comment]
[FloatingActionButton.zip](https://github.com/material-components/material-components-android/files/3929501/FloatingActionButton.zip)

Expected FAB to hide when clicking FAB -> Collapse & Hide

**Comment by ymarian** [comment]
This is because the fab is hidden until collapse finishes. I suggest this workaround or filing a feature request to support this more easily:

https://gist.github.com/ymarian/e1023d302f85379cc9ff027a3a06792f
