### ISSUE TITLE
Button Toggle Group - Force at least one option to be checked

### ISSUE THREAD

**Issue by nickstamp93** [material-components/material-components-android#806]
It could be handy if the button toggle group can force at least one of the available options to be checked. 
It makes more sense in the singleSelection mode but in many cases, such as forms, it could be useful in both modes.

**Comment by MGaetan89** [comment]
Duplicate of https://github.com/material-components/material-components-android/issues/438.
And implemented here https://github.com/material-components/material-components-android/commit/a4b90321e32e1dbc0414958bea14a28f9fe68e14 for version 1.2.0.

**Comment by nickstamp93** [comment]
You' re right, didn't notice! thanks!
