### ISSUE TITLE
[TextView] text color isn't adapted

### ISSUE THREAD

**Issue by 2beaucoup** [material-components/material-components-android#807]
**Description:** Android 6.1 always shows white text while Android10 shows always black. Im switching between
```xml
<style name="AppTheme" parent="Theme.MaterialComponents">
```
and
```xml
<style name="AppTheme" parent="Theme.MaterialComponents.Light">
```
but the text color of my list view items always stays the same.

The goal would be to use `Theme.MaterialComponents.DayNight` and have the colors adapt accordingly.

**Expected behavior:**
`Theme.MaterialComponents.Light` on API 29
![Theme MaterialComponents Light API 29](https://user-images.githubusercontent.com/243903/70088486-a9acff00-1616-11ea-81e3-abc65f76f3e5.png)
`Theme.MaterialComponents` on API 23
![Theme MaterialComponents API 23](https://user-images.githubusercontent.com/243903/70088506-b0d40d00-1616-11ea-8293-4e33ea2aff93.png)
**Unexpected behavior:**
`Theme.MaterialComponents.Light` on API 23
![Theme MaterialComponents Light API 23](https://user-images.githubusercontent.com/243903/70088539-bc273880-1616-11ea-8ff9-62c66d836b5c.png)
`Theme.MaterialComponents` on API 29
![Theme MaterialComponents API 29](https://user-images.githubusercontent.com/243903/70088552-bf222900-1616-11ea-88b0-a83400368273.png)

**Source code:** 
Style: `<style name="AppTheme" parent="Theme.MaterialComponents">` or `<style name="AppTheme" parent="Theme.MaterialComponents.Light">`

List item view:
```xml
<RelativeLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/two_line_item"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:background="?android:attr/selectableItemBackground"
  android:minHeight="72dp"
  android:paddingEnd="?android:attr/listPreferredItemPaddingRight"
  android:paddingLeft="?android:attr/listPreferredItemPaddingLeft"
  android:paddingRight="?android:attr/listPreferredItemPaddingRight"
  android:paddingStart="?android:attr/listPreferredItemPaddingLeft">

  <ImageView
    android:id="@+id/icon"
    android:layout_width="40dp"
    android:layout_height="40dp"
    android:layout_marginTop="16dp"
    android:scaleType="centerInside"
    android:src="@drawable/ic_launcher"
    android:contentDescription="@string/app_icon_description"/>

  <LinearLayout
    android:id="@+id/lines_container"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_alignParentEnd="true"
    android:layout_alignWithParentIfMissing="true"
    android:layout_centerVertical="true"
    android:layout_marginLeft="16dp"
    android:layout_marginRight="16dp"
    android:layout_toEndOf="@id/icon"
    android:orientation="vertical"
    android:paddingBottom="16dp"
    android:paddingTop="16dp">

    <TextView
      android:id="@+id/firstLine"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:singleLine="true"
      android:textAppearance="@style/TextAppearance.MaterialComponents.Body1" <-- same without
    />

    <TextView
      android:id="@+id/secondLine"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:singleLine="true"
      android:textAppearance="@style/TextAppearance.MaterialComponents.Body2"  <-- same without
    />
  </LinearLayout>
</RelativeLayout>
```

**Android API version:** tested on 23 and 29

**Material Library version:** `1.1.0-beta02`(also tried `1.2.0-alpha02`

**Device:** Emulator running 23 and 29 as well as physical device running 23

**Comment by wcshi** [comment]
Hi @2beaucoup could you please share the code for your sample app?

**Comment by 2beaucoup** [comment]
It’s actually not just a sample but rather large. I tried to extract the relevant bits. Anything in particular that’s relevant?

**Comment by 2beaucoup** [comment]
Never mind. I found the problem. In my `ArrayAdapter.getView` I did
```kt
val inflater = applicationContext.getSystemService(LayoutInflater::class.java)
```
Changing it to
```kt
val inflater = LayoutInflater.from(context)
```
fixed it.

Thanks anyway!
