### ISSUE TITLE
[MaterialDatePicker] Setting MinDate and MaxDate in MaterialDatePicker

### ISSUE THREAD

**Issue by kartikj07** [material-components/material-components-android#808]
**Is your feature request related to a problem? Please describe.**
I am using materialDatePicker in while developing my application and I am finding it difficult in setting the minDate and maxDate properties for the datePicker opened. I am opening date picker to select a start date and an end date in 2 different text fields for adding a particular period.
No, I don't want to select a ranged date. I have looked into this and it does not suit my requirement. I can set a maxDate using `calendarConstraints.setValidator(DateValidatorPointForward.from(startDate))` but I can not select a minDate using the materialDatePicker. 

**Describe the solution you'd like**
I would love to have am an option where I would select a maxDate and a minDate using calendarConstraints. Just like the normal `DatePicker` has `DatePicker.setMaxDate()` and `DatePicker.setMinDate()` methods, I would love the same methods for materialDatePicker. 

**Describe alternatives you've considered**
I had considered using the datePicker provided in the android support library but I am implementing material components for my application and looking at the datePicker component I have decided to go forward with developing using all of the material components available.

**Comment by gabrielemariotti** [comment]
You can use the `CalendarConstraints.DateValidator`.
You can build your custom Validator. Something like:

```
public class MyDateValidator implements DateValidator {
   startDate;
   endDate;

  @Override
  public boolean isValid(long date) {
    return (date >= startDate && date<=endDate);
  }
 

}
```

**Comment by ymarian** [comment]
We also added a few extra validators by default:
https://github.com/material-components/material-components-android/commit/4ccb052d2bb2bc6d261e48b91694464df73a69a9

**Comment by sergiofdomingues** [comment]
> **Is your feature request related to a problem? Please describe.**
> I am using materialDatePicker in while developing my application and I am finding it difficult in setting the minDate and maxDate properties for the datePicker opened. I am opening date picker to select a start date and an end date in 2 different text fields for adding a particular period.
> No, I don't want to select a ranged date. I have looked into this and it does not suit my requirement. I can set a maxDate using `calendarConstraints.setValidator(DateValidatorPointForward.from(startDate))` but I can not select a minDate using the materialDatePicker.
> 
> **Describe the solution you'd like**
> I would love to have am an option where I would select a maxDate and a minDate using calendarConstraints. Just like the normal `DatePicker` has `DatePicker.setMaxDate()` and `DatePicker.setMinDate()` methods, I would love the same methods for materialDatePicker.
> 
> **Describe alternatives you've considered**
> I had considered using the datePicker provided in the android support library but I am implementing material components for my application and looking at the datePicker component I have decided to go forward with developing using all of the material components available.

Same here, still not working.

**Comment by jssamsul** [comment]
update build.gradle (app) version as below
`implementation 'com.google.android.material:material:1.4.0'`

code level 

        ```
CalendarConstraints.Builder constraintsBuilderRange = new CalendarConstraints.Builder()
                .setValidator(DateValidatorPointBackward.now());
        builder.setCalendarConstraints(constraintsBuilderRange.build());


        MaterialDatePicker picker = builder.build();
```

**Comment by FoVlaX** [comment]
If this is still relevant for someone, you can use the CompositeDateValidator for this task. And there is no need to implement your own validator. (The example from the comment above will only set the lower limit)

```
 val validators = listOf(
       DateValidatorPointForward.from(startDate),
       DateValidatorPointBackward.before(endDate)
) 
val calendarConstraintBuilder = CalendarConstraints.Builder()
            .setValidator(CompositeDateValidator.allOf(validators))
            
val datePicker = MaterialDatePicker.Builder
            .datePicker()
            .setCalendarConstraints(calendarConstraintBuilder.build())
            .build()            
```

**Comment by markoeltiger** [comment]
same as @FoVlaX  comment , 
`   val startFromSixMonthsFromNowDateValidator = DateValidatorPointForward.from(sixMonthsFromNowMillis) // Allows dates from a week ahead
        val FromNowBackwardDateValidator = DateValidatorPointBackward.now()
        val combinedValidator = CompositeDateValidator.allOf(listOf(startFromSixMonthsFromNowDateValidator, FromNowBackwardDateValidator))
   val constraintsBuilder =
                CalendarConstraints.Builder()
                        .setValidator(combinedValidator)
   val dateRangePicker = dateRangePickerBuilder
                .setCalendarConstraints(constraintsBuilder.build()).build()`
