### ISSUE TITLE
[PopupMenu/RadioButton] Overflow menu radio buttons are offset due to RadioButton minWidth in MaterialComponents theme

### ISSUE THREAD

**Issue by FaultException** [material-components/material-components-android#809]
**Description:** Due to MaterialComponents theme setting a minWidth for RadioButtons there's an offset with menu radio buttons.

**Material Library version:** Happens on 1.1.0-beta02 and 1.2.0-alpha02

Screenshots:
[Menu radio buttons](https://user-images.githubusercontent.com/1182627/70159193-245d3500-167e-11ea-9ce7-808cde679447.png)
[Menu radio buttons with 0px minWidth set myself](https://user-images.githubusercontent.com/1182627/70159586-c7ae4a00-167e-11ea-91ec-093f6cbd8e23.png)

**Comment by ikim24** [comment]
Hi @FaultException - We aren't planning to remove the minWidth for radio buttons (or checkboxes) as we have added it to ensure sufficiently large tap target sizes.

If you are finding that you do not want the minWidth, you do have the option of creating your own styles and changing the android:minWidth.

**Comment by FaultException** [comment]
Hi @ikim24,

You might misunderstand. The issue reported here is that the radio buttons and check boxes are visually offset in popup menus due to the minWidth. Take a look at the screenshots, you can see that they're pushed over.

Resolving this issue does not necessarily require removing the minWidth globally, you may be able to make the popup theme link to radio button and check box styles without the minWidth.

**Comment by Rolf-Smit** [comment]
@FaultException how exactly did you remove the minWidth from the popup specifically? Which theme/attribute did you override.

@ikim24 I understand the tap target sizes, however in a popup menu isn't the whole menu item itself the tap target? In fact, I see that the checkbox itself has it's own touch ripple effect which overlays with the menu items ripple effect. I can also check any checkbox or radio button by just clicking the menu item not specifically the checkbox or radio button.

I do think it would make sense to remove the minWidth for popupmenu's specifically and keep it elsewhere.
