### ISSUE TITLE
[TextInputLayout] Allow hint to float always

### ISSUE THREAD

**Issue by mauronra** [material-components/material-components-android#810]
**Is your feature request related to a problem? Please describe.**
Currently it is impossible to set a hint to both TextInputLayout and TextInputEditText without both overlapping, in some cases it would be nice to show both hints to the user.

**Describe the solution you'd like**
Create an attribute such as:

`android:hintAlwaysFloat="true"`

Or something like it.

**Describe alternatives you've considered**
The easiest alternative to achieve such design is to set a TextView and an EditText within a container and handle both of them.

I've also [seen](https://stackoverflow.com/a/55270916/3624477) the use of reflection to achieve such behaviour, however this brings undesired problems.

**Additional context**
Actual: 

```
<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/input"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="Name">

            <com.google.android.material.textfield.TextInputEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="e. g. Mauro N."
                android:inputType="text"/>

</com.google.android.material.textfield.TextInputLayout>
```

![image](https://user-images.githubusercontent.com/38300107/70277922-48556f00-1781-11ea-9774-8968a63a79c2.png)

Suggested:

```
<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/input"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="Name"
            android:hintAlwaysFloat="true">

            <com.google.android.material.textfield.TextInputEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="e. g. Mauro N."
                android:inputType="text"/>

</com.google.android.material.textfield.TextInputLayout>
```

![image](https://user-images.githubusercontent.com/38300107/70277961-56a38b00-1781-11ea-9fe1-6031ea6dd06b.png)

**Comment by leticiarossi** [comment]
Can't this be solved by using the `placeholderText` attribute instead?

**Comment by ymarian** [comment]
Hi I think @leticiarossi it's right, the component supports this via placeHolderText

```xml
  <com.google.android.material.textfield.TextInputLayout
      android:id="@+id/text_input_username"
      style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:hint="Name"
      app:placeholderText="e. g. Mauro N.">

    <com.google.android.material.textfield.TextInputEditText
        android:id="@+id/edit_username"
        android:inputType="text"
        android:layout_width="400dp"
        android:layout_height="wrap_content" />
  </com.google.android.material.textfield.TextInputLayout>
```

![image](https://user-images.githubusercontent.com/38727469/75557837-c935a700-5a0e-11ea-937a-d89ea033f7cf.png)

**Comment by zx2c4** [comment]
Afaict, placeholderText only shows both when selected, which is bot what you want. https://github.com/material-components/material-components-android/pull/1163 contains a proper (and trivial) fix to make hints always work as desired.

**Comment by hrach** [comment]
@ymarian @leticiarossi The example works ony partially: the labels do not overlapse, but without a focus only hint is showed. Aren't all these issues about being the hint floating all the time?

**Comment by Benny1007** [comment]
Can this be re-opened. The requested feature was to have the label always at the top floated regardless of being focused or not.

**Comment by dsn5ft** [comment]
We added support for this in https://github.com/material-components/material-components-android/commit/22973ff10305397bfc72fed41684175fee8aeefb via the new `expandedHintEnabled` attribute, available in version `1.3.0-alpha03`.

**Comment by sabinebarrera** [comment]
@dsn5ft I have tried `app:expandedHintEnabled="true"` with the `1.3.0-alpha03` and I don't get the expected behavior of:
```
 <!-- Whether the hint should occupy the input area when the text field is
         unpopulated and not focused. -->
```

I tried `1.3.0-rc01` and I don't get this the `TextInputLayout` expanded to show the placeholder text. What am I missing?

**Comment by dimasamendes** [comment]
> @dsn5ft I have tried `app:expandedHintEnabled="true"` with the `1.3.0-alpha03` and I don't get the expected behavior of:
> 
> ```
>  
> ```
> 
> I tried `1.3.0-rc01` and I don't get this the `TextInputLayout` expanded to show the placeholder text. What am I missing?
> 
> Enter issue [[TextInputLayout] app:expandedHintEnabled="true" doesn't occupy the input area when empty & idle](https://github.com/material-components/material-components-android/issues/2065)

Actually, you should set `app:expandedHintEnabled="false"` if you want it to be always on top
