### ISSUE TITLE
[StatusBar] Status bar not respecting primary color in light theme

### ISSUE THREAD

**Issue by MrCreeper1008** [material-components/material-components-android#811]
**Description:** 
I am overriding `Theme.MaterialComponents.DayNight`, and I set `colorPrimary` like this:
```xml
<item name="colorPrimary">@color/colorPrimary</item>
```  
Every material components respect this, including the top action bar. But the status bar is still in the default purple accent color, like this:  

<img width="384" alt="Screen Shot 2019-12-06 at 4 46 44 PM" src="https://user-images.githubusercontent.com/19359984/70358730-06433080-1848-11ea-8947-0c86ad6639ac.png">  

I tried to manually override `android:statusBarColor` like:
```xml
<item name="android:statusBarColor">@color/colorPrimaryVariant</item>
```
It solved the problem:  

<img width="384" alt="Screen Shot 2019-12-06 at 4 45 34 PM" src="https://user-images.githubusercontent.com/19359984/70358834-42769100-1848-11ea-8f62-70809c79a638.png">  

However, when I switch to dark theme, the color remains:  

<img width="385" alt="Screen Shot 2019-12-06 at 4 50 17 PM" src="https://user-images.githubusercontent.com/19359984/70358934-87022c80-1848-11ea-99e7-906c6c5ef4e9.png">  

I had searched through the entire project to see if there are any color strings that correspond to the default purple accent color, but I didn't find any.

Is this an expected behavior? Or should this be handled automatically by the parent theme, i.e. `DayNight` theme?

**Expected behavior:**  
The status bar should behave like this in light theme:  

<img width="384" alt="Screen Shot 2019-12-06 at 4 45 34 PM" src="https://user-images.githubusercontent.com/19359984/70359067-efe9a480-1848-11ea-8468-ca92bd1effed.png">  

and like this in dark theme:

<img width="384" alt="Screen Shot 2019-12-06 at 4 54 09 PM" src="https://user-images.githubusercontent.com/19359984/70359110-0bed4600-1849-11ea-9b34-12e169cea43a.png">

**Source code:**   

styles.xml:  

```xml
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
    <!-- Customize your theme here. -->
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryVariant">@color/colorPrimaryVariant</item>
    <item name="colorSecondaryVariant">@color/colorSecondary</item>
    <item name="colorSecondary">@color/colorSecondaryVariant</item>
    <item name="android:navigationBarColor">@android:color/transparent</item>
</style>
```  

colors.xml:  

```xml
<resources>
    <color name="colorPrimary">#ff5722</color>
    <color name="colorPrimaryVariant">#c41c00</color>
    <color name="colorSecondaryVariant">#03a9f4</color>
    <color name="colorSecondary">#67daff</color>
</resources>
```

**Android API version:** 29  

**Material Library version:** 1.2.0-alpha02

**Device:** Android Emulator: Nexus 5X API 29 x86

**Comment by MrCreeper1008** [comment]
Same issue occurs when `DayNight.NoActionBar` is overriden. I would expect the status bar color to be transparnt instead of the default purple accent color.

**Comment by wcshi** [comment]
0) create a color resource for your status bar color and point to whatever color you desire in light and dark theme

1) either: 
a) <item name="android:statusBarColor">@color/your resource color name</item>
OR
b) <item name="colorPrimaryDark">@color/your resource color name</item>

**Comment by MrCreeper1008** [comment]
Do I have to override both the light and dark theme? I'm using the `DayNight` theme which respects system theme but there's no separate attributes for light and dark status bar for me to override.

**Comment by flauschtrud** [comment]
What would be the suggested approach for situations where a transparent statusbar is needed but we don't want the blue default bar to appear also? (I posted a stackoverflow question with details about my themes and screenshots: https://stackoverflow.com/questions/68910668/how-to-achieve-a-transparent-statusbar-after-migrating-to-material-design-themes).

The problem arises for instance when

1. I want to use a CollapsingToolbarLayout and need a transparent statusbar when the toolbar is expanded.
2. To achieve a drawer with DrawerLayout that blends nicely under the statusbar.
