### ISSUE TITLE
Launch Screen Animations like material design guidelines

### ISSUE THREAD

**Issue by Mirmuhsin** [material-components/material-components-android#812]
Hi, I am looking for ways to implement the launch screen animation of the apps presented in [Material Studies](https://material.io/design/material-studies/#usage). The launch screen animations here are super awesome. So smooth and so satisfying... But I couldn't find the implementation of it in the source code, or so I think. 
Where can I find it, which package in the repo?

**Comment by wcshi** [comment]
Hi @Mirmuhsin could you be specific about which launch screen animation you were interested in? The link you posted just leads to a top level landing page for Material Studies.

**Comment by Mirmuhsin** [comment]
oh yeah, sorry about that... send the proper specific locations right away...

[**Shrine** launch screen animation and transition](https://material.io/design/material-studies/shrine.html#motion)

[**Reply** launch screen animation and transition](https://material.io/design/material-studies/reply.html#motion)

[**Rally** launch screen animation and transition](https://material.io/design/material-studies/rally.html#motion)

[**Owl** launch screen animation and transition](https://material.io/design/material-studies/owl.html#motion)

[**Crane** launch screen animation and transition](https://material.io/design/material-studies/crane.html#motion)

I am interested in how they combine launch screen logo to the next screen with animation. It is so awesome. I really would like to check out the codes if possible :) On top of that, there is a ton of stuff can be learned in those apps.

**Comment by nameer** [comment]
And what about the splash screen? Creating layout takes time hence we use a splash screen. How does splash screen work here?

**Comment by drchen** [comment]
Hi, so the splash screen animation/transition you saw on the design site is more of a design guide rather than a demo.

Currently we don't have a plan to including this specific transition into Material library yet. But you can probably try to start from the transition Android framework provided:
https://developer.android.com/about/versions/12/features/splash-screen
