### ISSUE TITLE
[TabLayout] disable ViewPager2 smoothScroll with TabLayoutMediator

### ISSUE THREAD

**Issue by manmeet-trantor** [material-components/material-components-android#813]
There is no option to smothScroll = false with TabLayoutMediator.
```
@Override
public void onTabSelected(@NonNull TabLayout.Tab tab) {
        viewPager.setCurrentItem(tab.getPosition(), true);
}

```
Current issue: By default ViewPager2 tab selection displays all in between tabs/screens/views
Expected behavior: on tab selection it should jump direct onto selected tab/screen/view

Version: 1.2.0-alpha01

Solution might be: user/dev can pass OnTabSelectedListener with attach() or with a separate method
```
TabLayoutMediator(tabLayout, viewPager) { tab, position ->
           
}.attach(object: TabLayout.OnTabSelectedListener(){})
```

**Comment by DDihanov** [comment]
Any updates or workarounds for this?

**Comment by ikim24** [comment]
Support for this has been added with https://github.com/material-components/material-components-android/pull/951.
