### ISSUE TITLE
[TextInputEditText] Does not detect click event

### ISSUE THREAD

**Issue by josebraz** [material-components/material-components-android#814]
**Description:** The `com.google.android.material.textfield.TextInputEditText` does not detect the click event when it is used to write a debug message in Logcat (or any other use of `setOnClickListener`)

**Expected behavior:** When click in a TextInputEditText, show debug message in Logcat

**Source code:** 
The layout:
```
<com.google.android.material.textfield.TextInputLayout
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:hint="label">
  
  <com.google.android.material.textfield.TextInputEditText
    android:id="@+id/value"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    android:focusable="false"
    android:inputType="number" />
</com.google.android.material.textfield.TextInputLayout>
```

The activity:
```
val value = findViewById<TextInputEditText>(R.id.value)
value.setOnClickListener  {
    Log.d("LOG", "Clicked")
}
```
**Android API version:** API 28

**Material Library version:** 1.2.0-alpha02

**Device:** Xiaomi Mi A2

**Comment by wcshi** [comment]
1) why is it not focusable but clickable?

2) Could you please provide a sample app?

**Comment by wcshi** [comment]
The onclicklistener is only triggered if the text field has focus (so it triggers first OnFocusChangeListener then if you click again it will trigger the click listener). If you wants to do something when the edit text is first clicked you can use a on focus changed listener instead

**Comment by shwoghk14** [comment]
I also need one click access TextInputEditText.
I hope that possible as soon as possible.

**Comment by francosaudi** [comment]
how to bring pop up list to select item to the textInput field
