### ISSUE TITLE
[NavigationView] Click Effect Enhancement

### ISSUE THREAD

**Issue by PatilShreyas** [material-components/material-components-android#815]
**Description:** I have implemented `NavigationView` as below screenshot. When the item is clicked effect like below takes place.

<img src="https://user-images.githubusercontent.com/19620536/70515627-a99f8880-1b5b-11ea-9988-00f2e5fd7f1f.jpg" height="500"/>

But I can't set that effect when an item is being *pressed*. I tried to use `ColorStateList` `state_pressed` but got no luck. When Clicking on menu item, it's occupying full ripple on menu item as below. 
See below, I clicked *Home* menu, it's occupying full ripple on that item.

<img src="https://user-images.githubusercontent.com/19620536/70515628-a99f8880-1b5b-11ea-8761-e05fb3b76aac.jpg" height="500"/>

**Expected behaviour:** This is Gmail app below, as there ***Starred*** menu is clicked, shaped ripple is formed when on pressing that menu. I want the exact effect in my `NavigationView`.

<img src="https://user-images.githubusercontent.com/19620536/70515867-1155d380-1b5c-11ea-9c6c-0c88c9894cc9.jpg" height="500"/>

**Source code:** I have referred source code of [**Google I/0 2019 App**](https://github.com/google/iosched)

**Android API version:** 24

**Material Library version:** 1.0.0
**Device:** Xiaomi Redmi Note 4

**Comment by Anigif** [comment]
@PatilShreyas Did you find a solution for this? I have the same issue and I'm unsure if I'm doing something wrong or the component doesn't follow the guidelines?
