### ISSUE TITLE
[MaterialDatePicker] Custom TextField to Outlined Box

### ISSUE THREAD

**Issue by rulogarcillan** [material-components/material-components-android#816]
Is your feature request related to a problem? Please describe.
I would like to be able to change the style of the textField so that it is in line with the rest of the application, we currently use Outlined Box, however it is being impossible for me

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/res/layout/mtrl_picker_text_input_date.xml

**Comment by dsn5ft** [comment]
We don't hardcode the style of the `TextInputLayout`s anywhere within `MaterialDatePicker`, so this should be possible by setting the following in your top-level app theme:

    <item name="textInputStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>

E.g.:
![image](https://user-images.githubusercontent.com/1420597/70662989-644f8980-1c35-11ea-95d6-d5298a162c95.png)
