### ISSUE TITLE
[com.google.android.material.bottomnavigation.BottomNavigationView] isChecked not working

### ISSUE THREAD

**Issue by rohit6027** [material-components/material-components-android#819]
BottomNavigation isChecked is not working second time.

Steps to reproduce : 

1. set isChecked false from any fragment
2. set isChecked true again will not work

**Comment by dsn5ft** [comment]
@rohit6027 Please provide a sample app that reproduces the issue with some more explanation.

**Comment by rohit6027** [comment]
Ok i found another solution to unselect all the item of bottom navigaion we use :

 bottom_nav_view.menu.setGroupCheckable(0, false, true);

However, we must later put "mNavigationBottom.getMenu().setGroupCheckable(0, true, true);" somewhere to allow the items to be shown as selected again.
