### ISSUE TITLE
Add new `Menus` component

### ISSUE THREAD

**Issue by sfdexter** [material-components/material-components-android#82]
https://material.io/go/design-menus

**Comment by seasonyuu** [comment]
Actually, the new design seems that isn't for Mobile or touch screen

**Comment by raveeshbhalla** [comment]
I wouldn't necessarily agree with that - it looks like the equivalent of [Spinner](https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md) in some senses.

**Comment by rafads7** [comment]
is the new design "Text field dropdown menu" available for android?
[https://material.io/design/components/menus.html#exposed-dropdown-menu]

**Comment by Gericop** [comment]
Any news about this component?

**Comment by dsn5ft** [comment]
We are currently working on updating PopupMenus to the new Material style, and after that we will likely take a look at other more specific menu components.

**Comment by hamidmalek** [comment]
Can anyone tell me when it had to be completed or is there any alternative for it?

**Comment by tylerwilson** [comment]
I too would like to have this Spinner style available: https://material.io/design/components/menus.html#exposed-dropdown-menu
directly in MDC so we do not have to try to recreate on our side.

**Comment by leticiarossi** [comment]
We currently have Material styles for PopupMenus. An example of it being used can be seen in our catalog demo https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/menu

Regarding the exposed dropdown menu, we have recently started working on its implementation.

**Comment by valentingavran** [comment]
> We currently have Material styles for PopupMenus. An example of it being used can be seen in our catalog demo https://github.com/material-components/material-components-android/tree/master/catalog/java/io/material/catalog/menu
> 
> Regarding the exposed dropdown menu, we have recently started working on its implementation.

When can we expect it to be finished?

**Comment by Rvizarreta14** [comment]
Any update on this?

**Comment by leticiarossi** [comment]
We're aiming to have the exposed dropdown menu component by the end of Q1!

**Comment by dhenry** [comment]
Is the exposed dropdown menu still slated for Q1? I was hoping to find it in the [1.1.0-alpha05](https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha05) release notes from earlier today.

**Comment by fonix232** [comment]
An update would be nice, it's past Q1 and not a word what's happening. Even if part of the alpha, it would be great if we could get a preview of at least the new Material style spinners.

**Comment by kimcy929** [comment]
Yes. Please support the Popup menu with icon. I am using reflect to show icon on Popup menu but it isn't official API so on some device it crashed.

https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F0B54x0KDcs5U-NC1tYmRKQWIzdDA%2Fbehavior-icon.png

**Comment by gaspar-dev** [comment]
Widget.MaterialComponents.TextInputLayout.*.ExposedDropdownMenu
When this style will be available?

**Comment by bohsen** [comment]
@gaspar-dev It already is in [alpha06](https://github.com/material-components/material-components-android/releases).

**Comment by gaspar-dev** [comment]
@bohsen thanks, I updated to alpha06, but see some changes in my TextInputLayouts, is there a some default size changes on them? because my corners is changed.

**Comment by dsn5ft** [comment]
Docs for the Exposed Dropdown Menus that are based on `TextInputLayout` are now available [here](https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md#exposed-dropdown-menus).
