### ISSUE TITLE
[TextInputLayout] Setting gravity to CENTER_HORIZONTAL shows outline box cutout at wrong position

### ISSUE THREAD

**Issue by mpost** [material-components/material-components-android#822]
**Description:**
Setting gravity on the inner EditText of a TextInputLayout to `CENTER_HORIZONTALLY` does not correctly cut out the outline. It only account for the case where gravity is set to `CENTER` but not to `CENTER_HORIZONTAL`. Setting to `CENTER_HORIZONTAL` still shows the following issue:

![image](https://user-images.githubusercontent.com/73655/70707283-19d31900-1cd8-11ea-8758-b6e6d1803e92.png)

A similar issue has been brought up [here](https://github.com/material-components/material-components-android/issues/609).

**Expected behavior:**
The outline cutout should behave as if gravity would be set to `CENTER`.

**Source code:**
```    
    <com.google.android.material.textfield.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="gravity = CENTER_HORIZONTAL">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/tal_url_editText"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal" />
    </com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** API 28

**Material Library version:**  1.2.0-alpha02

**Device:** Emulator

**Comment by matpag** [comment]
Probably [here](https://github.com/material-components/material-components-android/commit/20f113212d6904c6f0ec9dc412e0b7fea8b80ab2#diff-28db4421a98803da13c7de91c7023f5fR215) and [here](https://github.com/material-components/material-components-android/commit/20f113212d6904c6f0ec9dc412e0b7fea8b80ab2#diff-28db4421a98803da13c7de91c7023f5fR225) the condition should be changed to `else if (gravity == Gravity.CENTER || gravitiy == Gravity.CENTER_HORIZONTAL)`

**Comment by mpost** [comment]
@matpag Yes that is correct. I was looking at these places as well.
