### ISSUE TITLE
BadgeDrawable in ListView visible only after "update"

### ISSUE THREAD

**Issue by klux2** [material-components/material-components-android#825]
I want to use a BadgeDrawable for some elements of my ListView.

This is the code I'm using (inside of my adapters getView function and with some condition - copied straight from the example):
`BadgeDrawable badgeDrawable = BadgeDrawable.create(mContext);
BadgeUtils.attachBadgeDrawable(badgeDrawable, text_view, convertView.findViewById(R.id.navigation_activity_frame_layout));`

The problem is: The badges are not visible. Only when a new list item with a badge is added (when moving the list), the badges appear (all of them at once with Android 10 or only the badge of the new item with Android 7.1).

I'm using version _1.1.0-beta02_, and I also tried it with _1.2.0-alpha02_ (the error was still there).

Did I miss some step or is this an error?

**Comment by wcshi** [comment]
1) BadgeUtils is restricted to library, did you surpress the warnings to call it?
2) Could you please provide a sample app that reproduces the behavior you described?

**Comment by klux2** [comment]
1. No, I didn't. I ignored the warnings, and it compiled anyway (and the badges are there). But according to the [docs](https://github.com/material-components/material-components-android/blob/master/docs/components/BadgeDrawable.md) this is the right way to use the badge (I think) ...
2. Sure: https://github.com/klux2/BadgeTest
This is (more or less) the code I use in the real app, and it has the same problem.

**Comment by wcshi** [comment]
Thanks for sharing the sample app, I figured out the issue.

When the badge was initially added to your list items, they have not have been layed out yet, so their bounds were 0 and by extension the badge bounds were 0.
You want to add an OnLayoutChangeListener and update the badge bounds after (and whenever) its anchor's bounds are updated.

e.g.
notenTv.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
			@Override
			public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
				// update badge bounds
				BadgeUtils.setBadgeDrawableBounds(
						badgeDrawable, notenTv, null);
			}
		});

**Comment by klux2** [comment]
Thank you very much :smile:
