### ISSUE TITLE
Update Progress Indicators

### ISSUE THREAD

**Issue by sfdexter** [material-components/material-components-android#83]
https://material.io/go/design-progress-indicators

**Comment by yogeshlanjekar** [comment]
When we are adding this component ?

**Comment by shakil807g** [comment]
Any update on this?

**Comment by Dingenis** [comment]
Looking forward to this component, any updates?

**Comment by gabin8** [comment]
Any updates? Hello from Feb 2019

**Comment by hardysim** [comment]
refs #265

**Comment by wbinarytree** [comment]
FYI. Since we don't have any update yet. 
Here is a library I use for now and I found that also used inside firebase-ui.

https://github.com/DreaminginCodeZH/MaterialProgressBar

**Comment by melaniegoetz** [comment]
LinearProgressIndicator is actively being developed by our team now, expect a more detailed time estimate in the next few weeks!

**Comment by froriz5** [comment]
It would be really cool if could also get a Circular Progress Bar variant at some point as well:
https://material.io/design/components/progress-indicators.html#circular-progress-indicators

I've currently had to fallback to using a `ProgressBar` with the:
`android:theme="@android:style/Widget.DeviceDefault.Light.ProgressBar.Inverse"` applied to it to replicate the circular progress spinner.

However, this theme only supports an indeterminate state. If you want to use determinate progress, you have to write custom code with a `background` and `progressDrawable` to do the drawing manually for determinate states.

**Comment by danielrust** [comment]
Is there an ETA on this?

**Comment by melaniegoetz** [comment]
Progress Indicators are being worked on and expected to land Q2!

**Comment by mukesh8293** [comment]
Eagerly waiting for this :)

**Comment by azharrasheed** [comment]
that will be very helpful please make it available

**Comment by sp0rk** [comment]
@melaniegoetz What's the status? Q2 is slowly coming to an end :)

**Comment by PranjalDesai** [comment]
I believe we are in Q3. Any updates?

**Comment by touficbatache** [comment]
I really need a circular progress bar with determinate progress, any updates @melaniegoetz ?

**Comment by melaniegoetz** [comment]
We hope to open source the linear progress indicator component in Q4, thank you for your patience!

**Comment by mcastagnolo** [comment]
@melaniegoetz Will there be work done to create a progress spinner in a button similar to the examples on the Material page?

**Comment by softmarshmallow** [comment]
Almost end of 2019. any beta release for this?

**Comment by dhirajt** [comment]
Any updates on this please? we're getting into Q1 2020 now.
Thanks

**Comment by 4shadowr** [comment]
> Progress Indicators are being worked on and are expected to land Q2!

Guys, at least an alpha?
Its almost Q2

**Comment by tomblenz** [comment]
They didn't say _which_ Q4

**Comment by kimcy929** [comment]
Nearly 2 years. I hope it will add in the library early!

**Comment by RoarGronmo** [comment]
Rather Q4 if this century...

RG

søn. 5. apr. 2020, 18:52 skrev Kimcy <notifications@github.com>:

**Comment by kimcy929** [comment]
Good new in the next version 😀 
https://github.com/material-components/material-components-android/commit/cc88816b82a709981aebe68b8cd3a72de987c07e

**Comment by NitroG42** [comment]
For information, I just tried it in the catalog app :
The component is an animated progress bar (which means fade animation on showing, disappearing, smooth progression etc..).
Is it available in circle or in a linear way.
I know some people (including me) are expecting the implementation of a progress inside a button as seen [here](https://material.io/components/progress-indicators#circular-progress-indicators) (interacting with action).
I think it will probably by the next step after the progress indicators is released (at least that's what I hope!)

**Comment by danielrust** [comment]
Not gonna lie, this is extremely disappointing from Google

**Comment by tomblenz** [comment]
> Not gonna lie, this is extremely disappointing from Google

What about the implementation disappoints you?

**Comment by mishrabhilash** [comment]
The next version (1.2.0) is here, but no ProgressIndicator :(

**Comment by gabrielemariotti** [comment]
@mishrabhilash The `ProgressIndicator` was introduced with `1.3.0-alpha01`.
