### ISSUE TITLE
[BottomSheetBehavior] Crash when `dimen` is provided

### ISSUE THREAD

**Issue by gmazzo** [material-components/material-components-android#835]
**Description:** At `BottomSheetBehavior` if you set a `dimen` as a value for the `behavior_expandedOffset` attribute it will crash at runtime as it's trying to parse it as an `int`.

**Expected behavior:** We should be able to set `dimen` values in this attribute.

**Source code:**
```xml
app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior"
app:behavior_expandedOffset="?actionBarSize"
```
```java
setExpandedOffset(a.getInt(R.styleable.BottomSheetBehavior_Layout_behavior_expandedOffset, 0));
```

**Android API version:** Any

**Material Library version:** 1.2.0-alpha02

**Device:** Any

**Comment by cketcham** [comment]
Closed by 7ef37a0
