### ISSUE TITLE
[Dialog] Dialogs aren't dark when using MaterialAlertDialogBuilder

### ISSUE THREAD

**Issue by TebbeUbben** [material-components/material-components-android#837]
**Description:** AlertDialogs created using MaterialAlertDialogBuilder don't seem to inherit the dark theme from their parent context; dialogs stay light even if the application has inherited a dark theme (both Dark and DayNight variants affected).

**Expected behavior:** Dialogs should be dark if the application is using a dark theme.

**Source code:**
The activity is using `Theme.MaterialComponents.DayNight.NoActionBar` and the default night mode is set to `MODE_NIGHT_YES`.
```
MaterialAlertDialogBuilder(this)
    .setTitle("I am light")
    .setMessage("... but I should be dark.")
    .setPositiveButton("Close", null)
    .show()
```

**Android API version:** 27 (8.1.0)

**Material Library version:** 1.2.0-alpha02

**Comment by dsn5ft** [comment]
This issue doesn't reproduce in our Catalog demo app. Can you provide a sample app that shows the issue as well as a screenshot? Thank you.

**Comment by TebbeUbben** [comment]
My mistake! I set colorSurface to a very light color which caused the issue... Thanks anyways!
