### ISSUE TITLE
Add new `Slider` component

### ISSUE THREAD

**Issue by sfdexter** [material-components/material-components-android#84]
https://material.io/go/design-sliders

**Comment by YuriDenison** [comment]
Also ranges and RTL support would be great!

**Comment by pavelskala** [comment]
RatingBar with the correct touch behavior and custom drawables support based on Slider would also be great!

**Comment by ionaselig** [comment]
Incredibly frustrating to still be waiting on Android component library, both for designers and developers. Having built out range sliders using a third party library last year, we will have to remove them before entering the play store; resulting in a worse experience for our users as we'll have to start using multiple dropdowns until this component actually exists: https://material.io/design/components/sliders.html at which point we'll then spend more time and resources updating them yet again.

**Comment by ionaselig** [comment]
Any idea of the timeline at least on planned components would be something!

**Comment by jpelgrim** [comment]
*crickets*

**Comment by DanielJung** [comment]
Anything new here?

**Comment by ikim24** [comment]
We do not currently have a timeline for this component.

In the meantime, [SeekBar](https://developer.android.com/reference/android/widget/SeekBar.html) has some of the desired behavior.

**Comment by ldjcmu** [comment]
This component is in the library now.

**Comment by jpelgrim** [comment]
Awesome!!! Thanks much!!!

PS Maybe this page needs to be updated as well to reflect this? https://github.com/material-components/material-components-android/blob/master/docs/components/Slider.md

**Comment by ldjcmu** [comment]
Thanks for the docs notes. We'll get to those shortly.

**Comment by bembem1011** [comment]
I checkout branch master of https://github.com/material-components/material-components-android/blob/master/docs/components/Slider.md . I see in the slider package missing some xml files, so I can't run the example on device.

**Comment by ldjcmu** [comment]
Adding @cketcham  to take a look.

**Comment by cketcham** [comment]
@bembem1011 

You're building the catalog, but unable to see the slider demo right? I think the problem you are having with the demo is that it was only added to an internal catalog. We'll update it so it gets built as part of the catalog on github.

**Comment by bembem1011** [comment]
@cketcham thanks for your response, I will wait for your update
One more question, does slider library can support the below image ?
<img width="316" alt="Screen Shot 2019-10-11 at 11 08 38 PM" src="https://user-images.githubusercontent.com/24663764/66667011-39b87300-ec7c-11e9-8eea-5b64adc7d83d.png">

**Comment by cketcham** [comment]
Range sliders like in that screenshot aren't supported yet, but we're working on adding support now. It will be part of the 1.2.0 release.

**Comment by emitchel** [comment]
1.2.0-alpha04 doesn't contain the RangeSlider, is it getting pushed bacK? @cketcham

**Comment by joshuamking-driveclutch** [comment]
@emitchel See #916. I'd assume it's just going to be in there before the release candidates.
