### ISSUE TITLE
[ImageView] Resources$NotFoundException when using large animated vector drawables

### ISSUE THREAD

**Issue by sanjeevirajm** [material-components/material-components-android#842]
Facing Resources$NotFoundException when using large animated vector drawables. Attached original file.
[NoRecordAnimation.zip](https://github.com/material-components/material-components-android/files/3985082/NoRecordAnimation.zip)

**Source code:** setImageResource()

**Android API version:** Android API version 29

**Material Library version:** 1.2.0-alpha02

**Device:** All

**Comment by ymarian** [comment]
Thanks for trying it! I only added support bitmap drawables (pngs) initially. I'll work on supporting other drawables. 

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/imageview/ShapeableImageView.java#L124-L128
