### ISSUE TITLE
[Slider] Bugging Layout Editor

### ISSUE THREAD

**Issue by ViHtarb** [material-components/material-components-android#845]
After updating to 1.2.0-alpha03 Layout Editor cant instantiate slider class
java.lang.NoSuchFieldError: Slider_trackColorInactive   at com.google.android.material.slider.Slider.processAttributes(Slider.java:348)

In result if reopen layout xml file - editor always wait for build finish
how it`s can be fixed?

**Comment by Nutriz** [comment]
Same here with 1.2.0-alpha03

**Comment by SeboRax** [comment]
Same here with 1.2.0-alpha03. Tried with a fresh installs of Android Studio 3.6 RC1 and 3.5.3.
Once `Slider` is added to layout, LayoutEditor is broken and displays "Waiting for build to finish" for any layout opened.

Only way to recover LayoutEditor is to remove `Slider` from XML and restart Android Studio.

**Comment by romuald** [comment]
I have the same issue © 👍

(BTW is there a way to disable a view in the editor only to workaround this?)

**Comment by cketcham** [comment]
This is a bug in studio preview. Hopefully the fix will be in Studio 4.1 Canary 2.

**Comment by giraybal** [comment]
Android studio 3.6.1
com.google.android.material:material:1.2.0-alpha05
com.google.android.material.slider.Slider android studio preview is still buggy
Waiting for build to finish is showing...

**Comment by Surine** [comment]
Is this bug fixed? This problem has tortured me for a week, it's too uncomfortable.

**Comment by Nutriz** [comment]
The bug is still here with Android Studio 4.0 beta2

**Comment by jasonrobinson** [comment]
It's not fixed in Android Studio 4.1C2

For those who want to try Canary2, note bug https://issuetracker.google.com/issues/151661427 . 

If you're using `firebase.crashlytics`, then you'll get `Gradle sync failed: No such property: scope for class: com.android.build.gradle.internal.variant.ApplicationVariantData`.

**Comment by yenderlobo10** [comment]
This bug it was solved on **Android Studio 4.1 Canary 3**.

**Comment by Nutriz** [comment]
Nice. I hope it will be backported in 3.6 and 4.0, because 4.1 will not be available before 1 year ^^

**Comment by tomspi** [comment]
Not yet resolved in 3.6.2 :( 
still waiting

**Comment by wcshi** [comment]
Thanks @yenderlobo10  for conforming that this bug it was solved on Android Studio 4.1 Canary 3, going to mark this as closed.
In the future, please file Studio rendering bug here instead: 
https://issuetracker.google.com/issues?q=componentid:192714
