### ISSUE TITLE
Bug: sample app doesn't show bottom items' texts

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#846]
**Description:** Full description of issue here
Scroll to the bottom

**Expected behavior:** Screenshots and/or description of expected behavior
Bottom items are cut, not showing texts:
![image](https://user-images.githubusercontent.com/5357526/71321324-7a283e80-24c0-11ea-83e6-9d60645fe154.png)

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.
The sample itself.
[material-components-android.zip](https://github.com/material-components/material-components-android/files/3992390/material-components-android.zip)

**Android API version:** Android API version here
Android Q

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
What's on the sample.

**Device:** Device on which the bug was encountered here
Pixel 4

**Comment by sixpi** [comment]
Hi, I'm still seeing this bug in the 1.1.0 release.
