### ISSUE TITLE
[Material Theme Builder] split into two modules

### ISSUE THREAD

**Issue by gabrielittner** [material-components/material-components-android#854]
**Is your feature request related to a problem? Please describe.**

Currently when you use material theme builder you're supposed to copy certain files from the project to yours. Currently that is color.xml, night/color.xml, type.xml, shape.xml, styles.xml, themes.xml and night/themes.xml. But when you copy those you also need part of the attr.xml and dimen.xml files, as well as the anim folder.

**Describe the solution you'd like**

Split the material theme builder into two modules. The part which contains everything you need to copy and the app that has the preview of the theme. This makes multiple things possible/easier:
- no searching which files to copy you can just take the whole res folder of the library project
- it's possible to just copy the whole library project as is without having to delete anything in case your project is modularized
- you can copy in the app module at any point in time to get a preview of you current theme or just keep the app module in your project permanently
- updating with changes from newer library versions might get easier

**Comment by hunterstich** [comment]
Hey Gabriel,

As an fyi we've started to move this project over into [material-components-android-examples](https://github.com/material-components/material-components-android-examples/tree/develop/MaterialThemeBuilder).

I can definitely see what you mean about making it easier to go from the theme builder to your own project. I can take this and see what the team thinks about modularization. The only concern I could maybe foresee is modularization being confusing to a new developer, but that might be a non-issue with proper documentation. In the meantime, feel free to submit a PR to material-components-android-examples if you have ideas of your own on how this could best be done.
