### ISSUE TITLE
[com.google.android.material.radiobutton] Add option for padding/margin between radio button's button drawable and it's background drawable (if any)

### ISSUE THREAD

**Issue by Jide-xy** [material-components/material-components-android#855]
It is currently not possible to add padding between a radio button and its background drawable. Checked the source code and apparently, in the onDraw method of the CompoundButton class which it inherits from, the background drawable's hotspot is set to the radio button's button drawable's size. 

Could the hotspot and buttonDrawable's bounds could be made to include some padding on the start, maybe take advantage of the drawablePadding attribute from the TextView class which the CompoundButton already inherits from.

Tried to extend the RadioButton class to modify the onDraw behaviour but then I won't get to call the TextView and View" onDraw method without triggering that of the CompoundButton's, messing up the canvas before I'm able to draw the button at my specified location.

Hope this can be looked into. Thanks.

**Comment by drchen** [comment]
Hi, can you elaborate your use scenario?

Can't you just wrap radio buttons in another layout to achieve the effect?

**Comment by dbottillo** [comment]
> Hi, can you elaborate your use scenario?
> 
> Can't you just wrap radio buttons in another layout to achieve the effect?

Hi, I didn't write the original issue but I kind need the same thing! 
I don't think is possible to wrap the radio button into another layout as they need to be a direct child of `RadioGroup`

**Comment by drchen** [comment]
Hi, we may need more concrete use cases to evaluate a feature request. Can you provide more info about your scenarios that may require this?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it with more concrete use cases.
