### ISSUE TITLE
[ExtendedFloatingActionButton] ExtendedFAB size does not adjust when changed text

### ISSUE THREAD

**Issue by NUmeroAndDev** [material-components/material-components-android#858]
**Description:** 
ExtendedFAB size does not adjust when shrink/extended ExtendedFAB text is changed.

- Happens in ExtendedFAB once shrink/extended.
- Happens when with or without CollapsingToolbar.

**Expected behavior:** 
<img src="https://user-images.githubusercontent.com/13705006/71510326-daa8e880-28d1-11ea-912f-2c9420618929.gif" width="45%">

**Source code:** 
https://github.com/NUmeroAndDev/ExtendedFABIssueExample-android/tree/changed_text_issue

Please look `changed_text_issue` branch.  

**Android API version:** 29

**Material Library version:** 1.1.0-rc01

**Device:** Pixel 3 XL

**Comment by ymarian** [comment]
https://github.com/material-components/material-components-android/commit/55200c3a8f18604a723c7ad6ab48fb9ec03391ba#diff-e64c06d41cce9356ff2ee57d8e839d01
