### ISSUE TITLE
[Chip] checkedIcon cannot be tinted

### ISSUE THREAD

**Issue by Shusshu** [material-components/material-components-android#862]
**Description:** 
The checked icon in the Chip Filter cannot be tinted

**Expected behavior:** 
checkedIconTint attribute to tint the checkedIcon

**Source code:** 
Implement the same as https://github.com/material-components/material-components-android/commit/d25fa920210b4fd38bd427a24255962cab0f2749

**Android API version:** 
All

**Material Library version:** 
1.2.0-alpha03 and below

**Device:** 
all

**Comment by wcshi** [comment]
@Shusshu could you tint your checked icon prior to setting it on the chip?

**Comment by Shusshu** [comment]
Possibly but tinting should just work as I run a dark and light mode app.

The icon is actually a vector drawable with a colour taken from the
attribute but even than does not work ?attr/customIconColor

**Comment by wcshi** [comment]
Would you mind sharing vector drawable or a sample app?

**Comment by Shusshu** [comment]
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:fillColor="?attr/colorOnSurface"
      android:pathData="M10.8081,15.8909L6.8412,13.3408C6.409,13.0629 6.2838,12.4873 6.5617,12.0551C6.5738,12.0363 6.5866,12.0179 6.6,12L6.6589,11.9215C6.9663,11.5116 7.5339,11.4004 7.9734,11.664L11.2,13.6L15.4118,7.8087C15.7319,7.3686 16.3482,7.2713 16.7883,7.5914C16.7922,7.5942 16.7961,7.5971 16.8,7.6L16.8094,7.607C17.2475,7.9357 17.3398,8.5556 17.0164,8.9976L12.1559,15.6403C11.8436,16.0671 11.253,16.1769 10.8081,15.8909Z"
      android:fillType="evenOdd"/>
</vector>
`

**Comment by wcshi** [comment]
@Shusshu I tested your vector drawable in the chip demo in the catalog app and it is working as expected. When I set the fill color to `?attr/colorError` the check mark turns red. By default, ?`attr/colorOnSurface` is black in light mode and white in dark mode.

**Comment by Shusshu** [comment]
Weird it doesn't do that for me

I'm using the following style

`    <style name="Widget.MaterialComponents.Chip.Filter.Custom" parent="Widget.MaterialComponents.Chip.Filter">
        <item name="chipBackgroundColor">@color/chip_bg_selector</item>
        <item name="android:textColor">@color/chip_text_selector</item>
        <item name="checkedIcon">@drawable/ic_checkmark_small</item>
        <item name="android:textAppearance">@style/xxxxxx</item>
        <item name="android:fontFamily">@font/xxxxxx</item>
    </style>`

**Comment by wcshi** [comment]
Could you please provide a sample app using your custom style that reproduces the bug?

**Comment by ymarian** [comment]
Closing this as the demo is not provided and we cannot repro.

**Comment by Shusshu** [comment]
alpha06 fixed it using the attribute
