### ISSUE TITLE
[Tabs] Overriding `preferenceTheme` affects tabs appearance

### ISSUE THREAD

**Issue by johnwilde** [material-components/material-components-android#863]
**Description:** 

I'm using a custom `preferenceTheme` in my `AppTheme` in order to inflate a different layout in a PreferenceFragment:
```
        <item name="preferenceTheme">@style/PrefsTheme</item>
````

However, after opening that fragment, my TabItem's have also inflated that layout and I need to set `android:layout="@null"` in the `TabItem` to fix the issue.

**Expected behavior:** 
`preferenceTheme` usage has no effect on tabs

**Source code:** 

**Android API version:** 
29

**Material Library version:** 
`1.2.0-alpha-03`

**Device:** Device on which the bug was encountered here
Pixel 3

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ethanhsuhsu** [comment]
I would be glad to help fix this issue, can you provide me with more resources like a sample app, video and/or source code examples?

**Comment by johnwilde** [comment]
Are you able to apply this patch? 
 Look at Tabs in "Components" tab (looks ok)
 Scroll to "Preferences" tab
 Scroll back to "Components" tab, Tabs are now wonky

[pref.txt](https://github.com/material-components/material-components-android/files/4042930/pref.txt)

**Comment by wcshi** [comment]
Is this a regression of does this bug exist in all versions of the libray?
