### ISSUE TITLE
[MaterialCardView] CardView will not shrink after first measure

### ISSUE THREAD

**Issue by mzroth** [material-components/material-components-android#864]
**Description:** 
This is the same issue that was reported in issue #537, but it has still not been added to RC01. The issue and bug fix can be found in the original issue at https://github.com/material-components/material-components-android/issues/537

**Comment by ABr751** [comment]
on click of the card view will inflate the view

**Comment by pekingme** [comment]
Hi @mzroth , thanks for following up on this issue. The fix just missed the cut of 1.1.0-beta01 for some reason. It will be included in 1.2.0.
