### ISSUE TITLE
[MaterialDatePicker] Labels are not internationalized

### ISSUE THREAD

**Issue by nominalista** [material-components/material-components-android#868]
**Description:** Each label occurs only in English, e.g. "Start date", "End date", "Cancel", "OK", etc. What's more the only way to change these texts is to override private string values, e.g. `mtrl_picker_range_header_unselected`.

**Expected behavior:** Either some customization or auto-internationalization of labels.

**Material Library version:** 1.1.0-r01

**Comment by ethanhsuhsu** [comment]
Interesting issue this is... Even though there is already a todo for this issue, I am going to add another thing that will fix your issue. 

Java bindings for these values are necessary and I believe a part of the "customizability aspect of Material". Plus some people may want to change the text values at runtime (as opposed to compile time).

Java bindings for text values like these are normal and done for every other component. It is just a matter of adding it to the MaterialDatePicker 😉

**Comment by pekingme** [comment]
Hi @nominalista , auto-internationalization is kept low priority for current development phase. To customize these labels for other locales, please defines the corresponding string with the same resource names in the various locale resource directories.

How to use resources for localizations:
https://developer.android.com/guide/topics/resources/localization#using-framework 

Resource names of used labels can be found here:
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/res/values/strings.xml
