### ISSUE TITLE
[BottomSheetDialog] View overlapping when setContentView() called multiple times.

### ISSUE THREAD

**Issue by tarunsingh070** [material-components/material-components-android#869]
**Description:** When `setContentView(View view)` method is called a second time or every subsequent time on the same instance of BottomSheetDialog in order to set a new view (smaller height), the new view to set overlaps the previous view set on the BottomSheetDialog instead of the previous view being removed first. 
Also, the height of the BottomSheetDialog is not re-calculated when updating with the new view with a smaller height and instead remains the same as the previous view set on that instance of BottomSheetDialog. The height seems to be re-calculated only when updating with the new view with a greater height.

![BottomSheetDialog overlapping bug](https://user-images.githubusercontent.com/31713053/71768617-99be5e80-2ee5-11ea-954c-bf2a369a1c98.gif)

**Expected behavior:** Calling `setContentView(View view)` method on an instance of BottomSheetDialog should remove any existing view set and update it with the new view and also re-calculate the height of the BottomSheetDialog based on the new view.

**Source code:** 
```
        BottomSheetDialog dialog = new BottomSheetDialog(this);
        View view1 = LayoutInflater.from(this).inflate(R.layout.view1, null);
        dialog.setContentView(view1);
        dialog.show();

        View view2 = LayoutInflater.from(this).inflate(R.layout.view2, null);
        dialog.setContentView(view2);
```

**Android API version:** Android API 29

**Material Library version:** 1.2.0-alpha03

**Device:** Google Pixel 3A

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ethanhsuhsu** [comment]
@tarunsingh070 Thanks for documenting this issue thoroughly with source and a video! I was surprised that this issue existed (and also got sick when I saw that BottomSheetDialog 🤢)

**Comment by tarunsingh070** [comment]
> @tarunsingh070 Thanks for documenting this issue thoroughly with source and a video! I was surprised that this issue existed (and also got sick when I saw that BottomSheetDialog 🤢)

Thanks so much @ethanhsuhsu for fixing this so quickly. Yes, I was very surprised as well that this bug didn't get caught before. I caught it only after I migrated my project to androidX and started using the material component BottomSheetDialog.
