### ISSUE TITLE
[Maven] Release 1.1.0-rc1 missing from Maven Repository

### ISSUE THREAD

**Issue by JarnoVgr** [material-components/material-components-android#876]
**Description:** Release 1.1.0-rc1 is missing from the official JCenter/Maven repository. It would be great if it can be added. Previous release candidates (e.g. from 1.0.0) were added as well.
https://mvnrepository.com/artifact/com.google.android.material/material

**Expected behavior:** Being able to use the release via JCenter/Maven.

**Material Library version:** 1.1.0-rc1

Thanks in advance.

**Comment by hnljp** [comment]
You can find it here: https://maven.google.com/web/index.html
So it is on the official Google repository.
But yes on mvnrepository.com it is only visible if you look at the ICM repository:
https://mvnrepository.com/artifact/com.google.android.material/material/1.1.0-rc01

**Comment by JarnoVgr** [comment]
Thanks for pointing my in the right direction.

It's confusing as the 1.1.0-rc01 on ICM has a different date than the actual release. And on top of that  the latest 1.2.0 alpha is available on mvnrepository.com Google repository.

**Comment by dsn5ft** [comment]
My guess is that the ICM release is just someone publishing the library to that repo, and that maybe there's a bug in mvnrepository that's not showing the official release from the Google repo.
