### ISSUE TITLE
[TextInputLayout] TextInputLayout not getting focus

### ISSUE THREAD

**Issue by omercanyvision** [material-components/material-components-android#879]
**Description:** Seem like TextInputLayout is not getting focus when typeing text (The TextInputEditText does getting focused just TextInputLayout doesn't).
This problem is preventing from colorstatelist for icon tint for example to be ignored (color under state_focused is not getting called because TextInputLayout never gains focus).

**Expected behavior:** TextInputLayout should be focused (or maybe set some other state to be true like activated etc..) when typing to edit text

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** 28

**Material Library version:** 1.1.0-bet01

**Comment by leticiarossi** [comment]
Hi, can you provide a sample app with the issue?

**Comment by omercanyvision** [comment]
So for example this is the TextInputLayout with password icon:
```
<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/textLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:endIconMode="password_toggle"
            android:endIconTint="@color/text_input_tint_selector"
            style="@style/FoundationTextInputLayout.HighlightBackground.Tint.Password">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/editText"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="hint"
                style = "@style/FoundationTextInputEditText"/>

        </com.google.android.material.textfield.TextInputLayout>
```

This is text_input_tint_selector:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="?android:attr/colorAccent" android:state_focused="true"/>
    <item android:color="?android:attr/textColorHint"/>
</selector>
```
The bug is that the icon is not colored when the edit text is focused. From debugging it i realized it happens because the TextInputLayout.isFocused = false even when the edittext is focused, thus the icon is not colored (focused state is never 'true').

**Comment by leticiarossi** [comment]
I see. States work a bit weirdly in text fields, but there is a `setEndIconActivated` method in `TextInputLayout` that sets the state of the icon to activated. 
So if you have a color state list with 
`<item android:color="?android:attr/colorAccent" android:state_activated="true"/>` 
for the `endIconTint`, you can do something similar to what the dropdown menu component does here: https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/DropdownMenuEndIconDelegate.java#L359
you can set the icon to be activated depending on whether the text field has focus. By default TextInputLayout tints the icon to be `colorPrimary` if `setEndIconActivated` is called.

**Comment by omercanyvision** [comment]
That is what i did to solve it, I just thought there could be a solution for XML level without applying any code to fix the bug

**Comment by rewgoes** [comment]
Can we make it the default behavior? Please, check my pull request #1238 

I'm just adding this to the endIcon, but we can do the same for the start and error icon if you agree.
