### ISSUE TITLE
[MaterialImageView] Image View that casts proper elevation shadows for Vector Drawable Icons

### ISSUE THREAD

**Issue by ocarey** [material-components/material-components-android#891]
Hoping to easily add convex Elevation shadows for Vector Drawable Icons. Similar to what these two opensource packages do:

Material Shadows **(adds so much boilerplate code)**:
- https://github.com/harjot-oberai/MaterialShadows

Elevation Image View **(renders horribly on some low quality devices)**:
- https://github.com/qhutch/ElevationImageView

![Screenshot_1578626572](https://user-images.githubusercontent.com/37121709/72123448-2322c600-3316-11ea-8b43-dc18c49edf62.png)

---------------------------

It'd also be amazing to be able to set elevation on MaterialTextViews, MaterialToolbars, and BottomNavigationViews that have transparent backgrounds and have it just work for both Text & Icon Vector Drawables (Instead of only being able to draw shadows based on bounds/outlineProvider). Maybe a separate Transparent style? 

Adding shadow to literally any view & its subviews is so easy in iOS 😊:

```
view.layer.shadowRadius = 3
```

---------------------------

I have a few activities similar to the screenshot below, and it's hard to render consistent shadows for TextViews, Vector Icon ImageViews, and Toolbars / BottomNavigationViews that all have transparent backgrounds:

![Screenshot_1578626571](https://user-images.githubusercontent.com/37121709/72123263-7d6f5700-3315-11ea-901f-8b2d1e23a4c9.png)

Keep up the awesome work with the new Material library!

**Comment by denis-ismailaj** [comment]
Is there any progress on this issue?

**Comment by ymarian** [comment]
It's not in our roadmap. I'm going to close it for now
