### ISSUE TITLE
[MaterialRadioButton] is not working (not being inflated as expected)

### ISSUE THREAD

**Issue by hrskrs** [material-components/material-components-android#896]
**Description:** 
`MaterialRadioButton` is not showing radio buttons with `Theme.MaterialComponents.Light.NoActionBar`.  **It only shows the label, without the radio button**  

**Expected behavior:** 
`RadioButton` component should be shown

**Source code:** 
```
<RadioGroup
            android:id="@+id/radio_group"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical" />
```
....
```
MaterialRadioButton radioButton = new MaterialRadioButton(getContext());
radioButton.setText("foo")
radio_group.addView(radioButton)
```
...
Attribute defined under `Theme.MaterialComponents.Light.NoActionBar` theme:
` <item name="radioButtonStyle">@style/Material.RadioButton</item>`
...
```
// Played around with different attributes of RadioButton and RadioGroup too with no success
 <style name="Material.RadioButton" parent="Widget.MaterialComponents.CompoundButton.RadioButton">
        <item name="android:textColor">@color/foo_color</item>
        <item name="colorControlNormal">@color/foo_color</item>
        <item name="colorControlActivated">@color/brand_primary</item>
        <item name="useMaterialThemeColors">false</item>
        <item name="enforceMaterialTheme">false</item>
    </style>

```

**Android API version:**  29 (works on other APIs)

**Material Library version:** `com.google.android.material:material:1.2.0-alpha03`

**Device:** Different/multiple emulators

**Comment by pekingme** [comment]
Hi @hrskrs, thanks for reporting this. Could you provide a complete sample project which can reproduce the problem you mentioned? With fragments of codes, it's a bit difficult to recover the entire picture in order to identify the problem.
