### ISSUE TITLE
Feature request - Support Bottom navigation tablet mode

### ISSUE THREAD

**Issue by nico-gonzalez** [material-components/material-components-android#9]
### Overview
It would be nice to have the bottom navigation support tablet mode as the spec states. I am currently working on a PR to include this.

![Bottom navigation tablet mode](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B3321sZLoP_HSTd3UFY2aEp2ZDg/components_bottomnavigation_usage2.png)

**Comment by wcshi** [comment]
This component described in the original issue is called navigation rail: https://material.io/components/navigation-rail/

**Comment by nico-gonzalez** [comment]
I'll close this due to inactivity and probably doesn't make sense anymore

**Comment by wcshi** [comment]
Created a new [FR](https://github.com/material-components/material-components-android/issues/1024) to track navigation rail, please thumb up there, thanks!
