### ISSUE TITLE
Add new `Backdrop` component

### ISSUE THREAD

**Issue by dsn5ft** [material-components/material-components-android#90]
https://material.io/go/design-backdrop

**Comment by yashshah7197** [comment]
Any hints as to when we can expect this to be added?

**Comment by Hassan-Fa** [comment]
i'm not sure if i don't know how , or it's just not possible 
but i couldn't get a shape to be applied to a mapView as background ( I mean even for another parentLayout that contains it )
any help ?

sorry if it's not a good place to ask , i hoped if it's not possible directly you could suggest a workaround 
<3

**Comment by Raghav789** [comment]
is there any alternate way/plugin to implement this?

**Comment by Libco** [comment]
There is an example here: https://codelabs.developers.google.com/codelabs/mdc-104-java/#0

**Comment by pedromassango** [comment]
I made a library (android only) for backdrop. It works fine, but need improves:
https://github.com/pedromassango/IBackdrop

**Comment by Hackertronix** [comment]
Is there any ETA on this and other components under development? I don't seem to be able to find any mention of the timeline except for the "Under Development" tag on the Material web site 😅

**Comment by pedromassango** [comment]
@Hackertronix  All you can do is wait... Or try out my lib (if you wish)

**Comment by DASAR** [comment]
Please give us at least timeline when to expect this component. We as developers should decide wait or implement this on our own.

**Comment by ZieIony** [comment]
Another implementation: https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/widget/BackdropLayout.kt
It's pretty much a layout with a slide animation for one of its children.

**Comment by yashshah7197** [comment]
I guess we aren't getting this anytime soon as per [this comment](https://github.com/material-components/material-components-android/issues/203#issuecomment-431476668) on #203. Probably best that we close this issue for now.

**Comment by jorgeperezruiz** [comment]
Any news on this? The material design guidelines says the implementation is available but once you go to github it still says it is not completed yet.

Thanks.

![Screenshot 2019-05-08 16 13 02](https://user-images.githubusercontent.com/6684689/57386408-2c1e2f00-71ac-11e9-9b14-7a2c86f0fff9.png)

**Comment by ldjcmu** [comment]
We currently have no plans to implement this. I will look into the guidelines error.

**Comment by petitJAM** [comment]
@ldjcmu While you're in there, the iOS component is show as available in the guidelines but appears to not be implemented either.

**Comment by MatriscianoSalvatore** [comment]
![2019_09_16_22_5-1568670687971](https://user-images.githubusercontent.com/11440565/64996019-100a6700-d8dd-11e9-8592-1c9d55b439ce.gif)
![2019_09_16_22_5-1568670611453](https://user-images.githubusercontent.com/11440565/64996027-1567b180-d8dd-11e9-9f50-549479ff0480.gif)
![2019_09_16_22_5-1568670519887](https://user-images.githubusercontent.com/11440565/64996044-1d275600-d8dd-11e9-8fd1-8780859c74e1.gif)
![2019_09_16_22_5-1568670406231](https://user-images.githubusercontent.com/11440565/64996052-26b0be00-d8dd-11e9-95f8-f643ec68e679.gif)

**Comment by amjad-alwareh** [comment]
It's been 2 years since this issue has opened.
Is there any ETA?

**Comment by petitJAM** [comment]
@amjad-alwareh It's not happening :disappointed:: https://github.com/material-components/material-components-android/issues/90#issuecomment-490926277

Though to be fair, this one's not too hard to implement anyway.  You should be able to find some tutorials around the internet.

**Comment by consp1racy** [comment]
It's just the whole app crammed into a bottom sheet, with some extra bits behind it, no?

**Comment by calvarez-ov** [comment]
> Our implementation here:
> https://github.com/keikenofficial/keiken-android/tree/master/app/src/main/java/com/keiken/view/backdrop

Note that that's GPL, so probably not usable in many projects.

**Comment by certified84** [comment]
It's 2023

**Comment by mtrewartha** [comment]
Are backdrops even a thing in M3? In M2 they were listed under the components, but I don't see any mention of them in the [M3 components](https://m3.material.io/components).

**Comment by pedromassango** [comment]
> Are backdrops even a thing in M3

It seems to have been deprecated, I couldn't find either.

**Comment by leticiarossi** [comment]
We currently don't have plans to add support for a Backdrop material component https://github.com/material-components/material-components-android/commit/4c8930133040f4479524c33aab639fd4a463db3c. Closing this tracking ticket.
