### ISSUE TITLE
OutlinedButton style not work

### ISSUE THREAD

**Issue by smrahmadi** [material-components/material-components-android#900]
in this version of dependency
`com.google.android.material:material:1.2.0-alpha03 `
this style
`style="@style/Widget.MaterialComponents.Button.OutlinedButton"`
not workoing.

**Comment by pekingme** [comment]
Hi @smrahmadi, thanks for reporting. Could you specify what you mean "not working"? I just tried this style, it seems to work fine.

**Comment by smrahmadi** [comment]
Hi @pekingme 
im tryng us this code in layout

`
<com.google.android.material.button.MaterialButton
    android:id="@+id/material_text_button"
    style="@style/Widget.MaterialComponents.Button.OutlinedButton"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="@string/outlined_button_label_enabled"/>
`

but in **1.2.0-alpha03** version of dependency, nothing show of widget and state like INVISIBLE visibility

**Comment by pekingme** [comment]
Hi @smrahmadi, this appears weird. It shows on my end. Could you provide a sample to reproduce it? If it's too complicated to peel it from your project, please provide your layout file and any related style and theme files. Could you also verify if the component is laid out using the layout inspector tool? Thanks.

**Comment by ymarian** [comment]
I'm closing this issue as we cannot repro. And a demo wasn't provided things to check:

- Make sure your theme extends a Theme.MaterialComponents
- Make sure you are using AppCompatActivity 
- Checking the Button documentation to see how attributes affect it: https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md
