### ISSUE TITLE
[MaterialDatePicker] Manual Date input does not work on LG device

### ISSUE THREAD

**Issue by p1415604x** [material-components/material-components-android#901]
Description:
When clicking the "edit" button next to "Selected Date" on the picker to manually input a date with the edit text it is not possible to enter a valid date with the LG stock keyboard since the number keyboard that is opened does not allow to enter "/" or ".".

Expected behavior: It should be possible to enter a valid date with the keyboard, either by automatically inserting the special characters to complete the date or by using keyboard variant that supports these needed characters.

Android API version: 26 / Android 8.0

Material Library version: 1.2.0-alpha03

Device: LG G5 (LG-H860)

**Comment by dsn5ft** [comment]
Similar to https://github.com/material-components/material-components-android/issues/682.

**Comment by pekingme** [comment]
@p1415604x Thanks for reporting this. Could you please check with your devices to confirm the fix?

**Comment by p1415604x** [comment]
With updated library version I was still unable to enter date manually. There were no visible changes to keyboard. Only numbers, delete and done buttons.

Material Library version: 1.2.0-alpha04

**Comment by leticiarossi** [comment]
Fixed in https://github.com/material-components/material-components-android/commit/d6b2da8b50bf322ff58cd0eb4a72eb20ebe64bd1
