### ISSUE TITLE
[AlertDialog] How to position Alert Dialog properly

### ISSUE THREAD

**Issue by yanshouwang** [material-components/material-components-android#905]
**Description:**
I can't set the alert dialog's position at a custom position

**Expected behavior:** 
I read this in the official site
![批注 2020-01-14 111131](https://user-images.githubusercontent.com/24455689/72311191-d7c63a00-36be-11ea-8d50-4b9fb7de5d07.png)
seems we are able to custom the dialog's position with the backgroundInset, but I don't konw how to make it, and I am a fresher in Android Development, is there any examples about this?

**Comment by pekingme** [comment]
Hi @yanshouwang, thanks for trying this out. You can create a style for `AlertDialog` like below:
```
<style name="Widget.MyApp.AlertDialog.Test" parent="MaterialAlertDialog.MaterialComponents">
    <item name="backgroundInsetEnd">###dp</item>
    <item name="backgroundInsetTop">###dp</item>
    <item name="backgroundInsetBottom">###dp</item>
    <item name="backgroundInsetStart">###dp</item>
</style>
```
and a theme using it:
```
<style name="ThemeOverlay.MyApp.MaterialAlertDialog.Test" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
    <item name="alertDialogStyle">@style/Widget.MyApp.AlertDialog.Test</item>
</style>
```
While creating the `MaterialAlertDialog`, use this theme in the constructor.
```
new MaterialAlertDialogBuilder(getContext(), R.style.ThemeOverlay_MyApp_MaterialAlertDialog_Test)
            .setTitle(title)
            .setPositiveButton(positiveText, null)
            .setNegativeButton(negativeText, null)
            .setNeutralButton(neutralText, null));
```
Play around with different values at `###`, you should see some difference.

**Comment by maltaisn** [comment]
Alternatively, add `<item name="materialAlertDialogTheme">@style/ThemeOverlay.MyApp.MaterialAlertDialog.Test</item>` to your app theme.
