### ISSUE TITLE
[BottomAppBar] Crash with anchored FAB

### ISSUE THREAD

**Issue by victorlapin** [material-components/material-components-android#906]
**Description:** When FAB is anchored to a bottom bar, the app crashes with the following error:

java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:969)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
        at com.google.android.material.shape.MaterialShapeDrawable.maybeDrawCompatShadow(MaterialShapeDrawable.java:978)
        at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:945)

Bottom bar without FAB works great.
FAB anchored to any other view (or without anchor at all) works great.
FAB anchored to bottom bar and invisible works great.
I suspect it's caused by bottom bar cradle.

**Expected behavior:** FAB should be anchored and cradled without issues

**Source code:** Layout file is in the attachment (had to use .txt instead of .xml
[activity_read_article.txt](https://github.com/material-components/material-components-android/files/4059562/activity_read_article.txt)
)

**Android API version:** SDK 29

**Material Library version:** 1.2.0-alpha03

**Device:** AVD API 28 with Google Play, Samsung SM-T355 with Android 7.1.1

**Comment by cketcham** [comment]
Are you able to consistently reproduce this? We've seen some reports in the past, but we've never been able to cause this crash. 

http://issuetracker.google.com/issues/134254508

**Comment by victorlapin** [comment]
My pet project (the one I've picked layout file from) has this issue 100% reproducible. I'll open up sources shortly, if it can help

**Comment by cketcham** [comment]
That would be great thanks!

**Comment by victorlapin** [comment]
https://gitlab.com/victorlapin/yarik

branch refactor/article_bottom_bar

**Comment by victorlapin** [comment]
![untitled](https://user-images.githubusercontent.com/8329104/72444223-b188c300-37c0-11ea-92b9-8c885a2871a8.gif)

**Comment by cketcham** [comment]
Thanks for the sample! I see the problem comes from a translation of the FAB. It's causing the cutout for the BAB to be defined as something that causes the path bounds to be empty. I think it can be fixed by preventing negative translations of the fab from changing the vertical offset of the cutout on the BAB.
