### ISSUE TITLE
[Material Library] Library layout resources implicitly rely on MaterialComponentsViewInflater.

### ISSUE THREAD

**Issue by MiSikora** [material-components/material-components-android#908]
**Description:**

All of the `mtrl_layout` resources do not use explicitly Material Components. For example [`mtrl_layout_snackbar_include`](https://github.com/material-components/material-components-android/blob/343c93af8da69e1f022c806c3ac04823999fd212/lib/java/com/google/android/material/snackbar/res/layout/mtrl_layout_snackbar_include.xml) uses `TextView` and `Button` instead of `MaterialTextView` and `MaterialTextButton`. This means that consumers have to use `AppCompatActivity`, explicitly provide [`MaterialComponentsViewInflater`](https://github.com/material-components/material-components-android/blob/343c93af8da69e1f022c806c3ac04823999fd212/lib/java/com/google/android/material/theme/MaterialComponentsViewInflater.java) or override layout resources in order for views like `Snackbar` to display properly.

**Source code:** 

```kotlin
// Has Material theme set in the manifest file.
class MainActivity : Activity() {
  override fun onCreate(inState: Bundle?) {
    super.onCreate(inState)
    val content = CoordinatorLayout(this)
    setContentView(content)
    Snackbar.make(content, "Hello,", LENGTH_INDEFINITE).apply {
      setAction("World!") {}
    }.show()
  }
}
```

![Screenshot_1579027883](https://user-images.githubusercontent.com/30936061/72373360-6612de00-3708-11ea-981b-0ddf1fd193bd.png)

**Expected behavior:**

Library should explicitly use Material Components in layout files. For example Snackbar layout should look like this.

```xml
<view
  xmlns:android="http://schemas.android.com/apk/res/android"
  class="com.google.android.material.snackbar.SnackbarContentLayout"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:layout_gravity="bottom">

  <com.google.android.material.textview.MaterialTextView
    android:id="@+id/snackbar_text"
    style="?attr/snackbarTextViewStyle"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_weight="1"
    android:layout_gravity="center_vertical|left|start"/>

  <com.google.android.material.button.MaterialButton
    android:id="@+id/snackbar_action"
    style="?attr/snackbarButtonStyle"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginStart="@dimen/design_snackbar_extra_spacing_horizontal"
    android:layout_marginLeft="@dimen/design_snackbar_extra_spacing_horizontal"
    android:layout_gravity="center_vertical|right|end"
    android:minWidth="48dp"
    android:visibility="gone"/>

</view>
```

![Screenshot_1579027912](https://user-images.githubusercontent.com/30936061/72373383-732fcd00-3708-11ea-99fd-56523e7969a3.png)

**Android API version:** Any version.

**Material Library version:** `1.2.0-alpha03`

**Device:** All devices.

**Comment by pekingme** [comment]
Hi @MiSikora, thanks for your suggestion. We build and test all the components for a backward compatibility. It [requires](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#3-ensure-you-are-using-appcompatactivity) to use AppCompatActivity to ensure all components working as we expected.

**Comment by MiSikora** [comment]
Sure, I get it. But do you think think the resource files can be changed to use Material Components? I'll gladly do a PR. I just want to make sure that it is something that is ok.

**Comment by wcshi** [comment]
We intentionally do not explicitly use Material Components in case devs want to use their own custom view inflaters instead of MaterialComponentsViewInflater.
If you use any of the full material component themes, which we recommend, viewInflaterClass is set to MaterialComponentsViewInflater.
