### ISSUE TITLE
[MaterialShapeDrawable] Gray Artifact On Colorful Shadows

### ISSUE THREAD

**Issue by CertainlyAria** [material-components/material-components-android#909]
**Description:**
When using MaterialShapeDrawable compatible shadow mode (`shadowCompatibilityMode = SHADOW_COMPAT_MODE_ALWAYS`) colorful shadows are not drawn correctly. Take a  look:

![Screenshot_1579034644](https://user-images.githubusercontent.com/44586130/72381075-f9a9d600-372b-11ea-9d3d-a8cf1243e1a0.png)

**Source code:**
`val shapeDrawable = MaterialShapeDrawable()`

`shapeDrawable.fillColor = ColorStateList.valueOf(0xFFD81B60.toInt())`
`shapeDrawable.shadowCompatibilityMode = SHADOW_COMPAT_MODE_ALWAYS`
`shapeDrawable.setShadowColor(0xFFD81B60.toInt())`
`shapeDrawable.elevation = 168f`

`button.background = shapeDrawable`

**Android API version:**
I tested this on API 17 and API 29 emulators and API 24 physical device

**Material Library version:** 
I tried this with 1.1.0-rc01 and 1.2.0-alpha03. Both suffer from this issue.

**Comment by pekingme** [comment]
Hi @CertainlyAria, thanks for reaching out. Could you also provide me you layout file?

**Comment by CertainlyAria** [comment]
@pekingme Sure, [activity_main.xml](https://pastebin.com/nddXDM77)

**Comment by markbeaton** [comment]
Any idea why this was closed? I'm seeing the same problem.
