### ISSUE TITLE
[BadgeDrawable] Ability to add to MenuItem

### ISSUE THREAD

**Issue by aarontwf** [material-components/material-components-android#910]
Would like to add the badge to a toolbar menu item.

i.e. Add a badge with the number of people a list is shared with to the share icon.

**Comment by mrcodeelements** [comment]
This is already addressed at #1405

**Comment by ikim24** [comment]
This is addressed by https://github.com/material-components/material-components-android/commit/5e35d14c187b65b32788cce28d758657f1b5aebb
