### ISSUE TITLE
[navigation bar] The edge-to-edge option doesn't show a scrim for the navigation bar

### ISSUE THREAD

**Issue by Guuz** [material-components/material-components-android#912]
**Description:** The material catalog has the option to go edge-to-edge, as is recommended by Google: https://developer.android.com/guide/navigation/gesturenav
The automatic scrim, as described in the docs, is not applied:
Quote from docs:
> However, when the user is in 2-button or 3-button navigation mode, these buttons don't change color. Instead, the system applies a translucent background so the buttons stay visible. However, the system can only do this if the app targets API level 29 or higher.

I tested this in my own app and the material catalog app. I even updated the catalog app to targetSDK 29 as the docs say.
But on my Android Q emulator a scrim is applied, but on SDK level 27 for instance it is not.

**Expected behavior:**
A scrim should be applied if the user uses the older button navigation on all android versions.
![image](https://user-images.githubusercontent.com/810327/72442503-f145af80-37ac-11ea-9116-85469402aab6.png)
Left: SDK 27, right: android Q

**Source code:** 
```
<item name="android:navigationBarColor">@android:color/transparent</item>
<item name="android:windowLightNavigationBar" tools:targetApi="Q">true</item>
```
**Android API version:** All, tested on 27 and Q

**Material Library version:** 1.1.0-rc01

**Device:** Emulators

**Comment by drchen** [comment]
I cannot reproduce the issue so I assume it's fixed. Please feel free to reopen it if it's still reproducible.

**Comment by cam-shaw** [comment]
@guuz it's been a few years now, but did you happen to come to a solution on this? I get the same issue when following these instructions https://developer.android.com/develop/ui/views/layout/edge-to-edge#java. Not sure if it's a simulator only issue. The scrim isn't appearing 🤔
