### ISSUE TITLE
import com.google.android.material.snackbar.Snackbar

### ISSUE THREAD

**Issue by Mahesh520** [material-components/material-components-android#914]
**Description:** Full description of issue here

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Android API version here

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

**Device:** Device on which the bug was encountered here

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by pekingme** [comment]
Hi @Mahesh520, just want to confirm with you if this issue is created by accident. If so, I can close it; otherwise, please modify the comment with details.
