### ISSUE TITLE
[TextInputLayout] Is it possible to apply elevation to an OutlinedBox TextInputLayout 

### ISSUE THREAD

**Issue by bryandunbar** [material-components/material-components-android#915]
I'm trying to create the following look for my TextInputLayout. My thought was to create an OutlinedBox set the stroke to white and then add an elevation to get the shadow around the box, but it doesn't seem to apply a shadow when I set elevation.

<img width="317" alt="Screen Shot 2020-01-16 at 11 07 35 AM" src="https://user-images.githubusercontent.com/999233/72541432-8483f100-3850-11ea-89a5-08f0d0382d4d.png">

Any suggestion as to how I should implement?

**Comment by pekingme** [comment]
Hi @bryandunbar, there's no design guideline about elevation for [text fields.](https://material.io/components/text-fields/#) If this is what you'd like to implement in your UI, my suggestion for a quick workaround is to try MaterialShapeDrawable. It can draw the shadow you want, then you just replace the component's background with it using `setBackgroundDrawable()`.

**Comment by bryandunbar** [comment]
Thanks. I’ll give it a shot.

**Comment by MahmoudAymann** [comment]
Yes I'd like to do that too but cant right now to set elevation direct to TextInputLayout, so i put it inside cardview

**Comment by bryandunbar** [comment]
@MahmoudAymann does that work? Can you supply sample code on how you setup the card view? I couldn’t quite get the look i wanted with MaterialSgaleDrawable

**Comment by MahmoudAymann** [comment]
@bryandunbar i will do it for you right now just hold a sec...

**Comment by MahmoudAymann** [comment]
@bryandunbar in your layout
 `       
<com.google.android.material.card.MaterialCardView
                android:id="@+id/cv_name"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/dp16w"
                android:layout_marginEnd="@dimen/dp16w"
                app:cardCornerRadius="24dp"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent">
                <com.google.android.material.textfield.TextInputLayout
                    style="@style/TextInputLayoutNoBorder"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
                    <com.google.android.material.textfield.TextInputEditText
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:hint="@string/enter_your_name"
                        android:inputType="textPersonName"
                        android:textAlignment="center" />
                </com.google.android.material.textfield.TextInputLayout>
            </com.google.android.material.card.MaterialCardView>
`
put this in styles.xml
`<style name="TextInputLayoutNoBorder" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="errorIconDrawable">@null</item>
        <item name="errorIconTint">@null</item>
        <item name="hintEnabled">false</item>
        <item name="boxBackgroundMode">none</item>
    </style>`

**Comment by bryandunbar** [comment]
Great. Thanks. Will report back if it works.

**Comment by arok** [comment]
You should apply elevation to `EditText` (as it has background) an not to `TextInputLayout`

**Comment by Attique033** [comment]
How to add shadow to the outlinedTextInputLayout? I've rounded the corners by using custom style but not able to add drop shadow to it. Any help? 

```
    <style name="OutlinedRoundedBox" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.MyApp.TextInputLayout.Rounded</item>
    </style>

    <style name="ShapeAppearanceOverlay.MyApp.TextInputLayout.Rounded" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">10dp</item>
    </style>
```

Above is how style is customised to change radius of ourlinedTextInputLayout.

**Comment by MahmoudAymann** [comment]
> How to add shadow to the outlinedTextInputLayout? I've rounded the corners by using custom style but not able to add drop shadow to it. Any help?
> 
> ```
>     <style name="OutlinedRoundedBox" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
>         <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.MyApp.TextInputLayout.Rounded</item>
>     </style>
> 
>     <style name="ShapeAppearanceOverlay.MyApp.TextInputLayout.Rounded" parent="">
>         <item name="cornerFamily">rounded</item>
>         <item name="cornerSize">10dp</item>
>     </style>
> ```
> 
> Above is how style is customised to change radius of ourlinedTextInputLayout.

or you can use this in your XML :
`
                    app:boxCornerRadiusTopStart=""
                    app:boxCornerRadiusTopEnd=""
                    app:boxCornerRadiusBottomStart=""
                    app:boxCornerRadiusBottomEnd=""`
