### ISSUE TITLE
[Slider] Support Ranged Sliders

### ISSUE THREAD

**Issue by joshuamking-driveclutch** [material-components/material-components-android#916]
**Describe the solution you'd like**
Support for the Slider component to have a lower bounds value and an upper bounds value.

**Additional context**
See the Material Design specs: https://material.io/components/sliders/#usage

**Comment by pekingme** [comment]
Hi @joshuamking-driveclutch, range selection supporting slider is on it way. It's planned to land in Q1 2020. Please stay tuned.
