### ISSUE TITLE
[TextInputLayout] Add public api for changing TransformationMethod

### ISSUE THREAD

**Issue by mobilekosmos** [material-components/material-components-android#918]
**Is your feature request related to a problem? Please describe.**
We need the possibility to define the Password Transformation Method to be used when the password is hidden, why? We want to aovid the letters are being shown on input despite it's only for a second, we don't want the input is being seen at all. As far as I know this is currently not possible.

**Comment by gabrielemariotti** [comment]
I'm not sure whether or not I understand this correctly.
You can use the 

```
          EditText editText = textInputLayout.getEditText();
          editText.setTransformationMethod(PasswordTransformationMethod.getInstance());
```

**Comment by drchen** [comment]
The answer @gabrielemariotti provided is right. And remember not to set endIconMode as password toggle.
