### ISSUE TITLE
[TextInputLayout] Add second input edit text for "password confirmation"

### ISSUE THREAD

**Issue by mobilekosmos** [material-components/material-components-android#919]
When the user needs to declare a password we always have a second edittext with the hint "confirm password". We would like that when the show password eye is clicked also this second editText shows the password/hides it. Currently you can set an onClickListener on the eye and implement your own logic, but if you do this you override the super() logic, there isn't a public way of getting the PasswordToggleEndIconDelegate so one could add a listener to it.

**Comment by drchen** [comment]
It doesn't seem like a general use case. Please just use custom end icon if you have a special requirement. Closing the issue.
