### ISSUE TITLE
[MaterialDatePicker] Entire component feels very janky due to delayed visual cues and overzealous smooth scrolling

### ISSUE THREAD

**Issue by EdwardvanRaak** [material-components/material-components-android#920]
**Description:** The component doesn't feel responsive or snappy due to:

- Overzealous and "slippery" horizontal scrolling where accidentally scrolling too fast skips several pages rather than snapping like you would expect from any normal `ViewPager`. Honestly this is the most finicky and annoying thing ever.
- Laggy and jittery (not 60 fps) horizontal scrolling on at least my own device and emulator.
- Forced animations and sometimes even ignored click events after clicking dates because a circle is "filled" with a grey reveal animation that causes a delayed visual cue.

In comparison to a traditional `DatePickerDialog` this is a step forward in terms of design but a step backwards in terms of responsiveness.

**Android API version:** 9

**Material Library version:** 1.2.0-alpha03

**Device:** Oppo Find X, Emulators

**Comment by Zeliret** [comment]
I can confirm that. It is just impossible to use it. Every tap takes couple of seconds. 
And I feel that there are some leaks or may be multiple listeners somewhere.

**Comment by Zeliret** [comment]
Video here: https://www.evernote.com/l/AmgupMoEgYtKH7mgyuLPx1_xfsrQo1oeMeI

**Comment by dsn5ft** [comment]
Jankiness/delays should be fixed by https://github.com/material-components/material-components-android/commit/b12c5c5b008579d35aab23000f493487d979b257, available in 1.3.0-alpha03.
