### ISSUE TITLE
 [Slider] two-way databinding

### ISSUE THREAD

**Issue by LinggaMG** [material-components/material-components-android#926]
Does Slider(1.2.0-alpha03) support two-way databinding directly in xml?

`android:value=@={model.value}`

**Comment by cketcham** [comment]
We don't have any databinding methods in our library (although maybe that would be useful). But you should be able to write the methods that you need to make it work. Can you add it by writing the methods from these instructions? https://developer.android.com/topic/libraries/data-binding/two-way#two-way-custom-attrs

**Comment by LinggaMG** [comment]
Thank you... I will make it by two-way custom databinding..

**Comment by s7aycool** [comment]
@LinggaMG can you please share you SliderBindingAdapter? )

**Comment by icesmith** [comment]
Here's my [SO answer](https://stackoverflow.com/a/62118131/4858777) describing two-way databinding setup for the Slider. I've also created a demo repo containing a working slider adapter, you can find it [here](https://github.com/icesmith/android-samples/tree/master/SliderDatabinding).
