### ISSUE TITLE
[Docs] Lack of details in documentation

### ISSUE THREAD

**Issue by StephaneBg** [material-components/material-components-android#928]
When I need information, I look into the documentation but most of the time I don't find what I was looking for.

We need a complete documentation that describe for each components all attributes that are used: style, colors...

Here is an example for Text Fields. Doc can be found there:
https://material.io/develop/android/components/text-input-layout/

First, I want to make the style opt-out in my base theme so that I won't have to specify the style in each layout. The key to set is textInputStyle and it is not mentioned anywhere.
Then I need to custom the colors. I can't find how it is internally mapped into the widget. I need a way to know the map between elements of the widget such as outline and color attributes such as colorPrimary, colorControlActivated and that for all states (selected, focused...).

Please make the documentation exhaustive so that we don't have to crawl into the source code and the lot of XML style files to find what attribute has to be overridden to get the wanted styling.

**Comment by andrelabonte** [comment]
Hi @StephaneBg ,

Thanks for reaching out.  
We are actively revisiting our documentation templates and content. Some of the planned improvements should help with the use-cases you mentioned.  I will also make sure the details you sent are shared with the team leading this effort. 
-André
