### ISSUE TITLE
[TextInputLayout] Ripple effect goes beyond the View

### ISSUE THREAD

**Issue by ShadyRover** [material-components/material-components-android#929]
**Description:** I'm using TextInputLayout with the custom right image.
When you click on the right icon, the ripple effect appears under the view and goes beyond its scope.
![image](https://user-images.githubusercontent.com/1470758/72882308-76801580-3d13-11ea-9f04-10085d4a27f8.png)

**Expected behavior:** The ripple effect appears on top of the view and has a smaller size.
![image](https://user-images.githubusercontent.com/1470758/72882450-b0e9b280-3d13-11ea-8856-f03b4591a984.png)

**Source code:** 
```
 <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/login_container"
                style="@style/AppTheme.TextInputLayout"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="16dp"
                android:layout_marginTop="16dp"
                android:layout_marginEnd="16dp"
                android:hint="@string/login_input_login_hint"
                app:hintEnabled="true"
                app:endIconMode="custom"
                app:endIconDrawable="@drawable/ic_info"
                app:colorControlNormal="#FFFFFF"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent">
```

                <com.google.android.material.textfield.TextInputEditText
                    android:id="@+id/login_edit_text"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:imeOptions="actionNext"
                    android:inputType="textEmailAddress"
                    android:maxLength="1024"
                    android:maxLines="1" />

            </com.google.android.material.textfield.TextInputLayout>`

**Android API version:** 21, 22(API versions above work as expected)

**Material Library version:** 1.1.0-beta02 (1.2.0-alpha04 is affected too)

**Device:** irrelevant, e.g. emulator Pixel 3XL 21 API

As a workaround, I wrote an extension for TextInputLayout:
```
@Suppress("MagicNumber")
private val decreaseSizeValue = 8.dpToPx()
@Suppress("MagicNumber")
private val endMargin = 8.dpToPx()
@Suppress("MagicNumber")
private val startMargin = 16.dpToPx()

fun TextInputLayout.fixLollipopRightImageRipple() {
    val imageButton = findViewById<AppCompatImageButton>(R.id.text_input_end_icon)
    imageButton.drawable?.let { drawable ->
        val lp = imageButton.layoutParams as FrameLayout.LayoutParams
        lp.width = drawable.minimumWidth.dpToPx() - decreaseSizeValue
        lp.height = drawable.minimumHeight.dpToPx() - decreaseSizeValue
        lp.marginEnd = endMargin
        lp.marginStart = startMargin
        imageButton.layoutParams = lp
    }
}
fun Int.dpToPx() = (this * Resources.getSystem().displayMetrics.density).toInt()
```
To work correctly, need still set the transparent background for TextInputEditText like this:
```
 <com.google.android.material.textfield.TextInputEditText
                    android:id="@+id/login_edit_text_password"
                    style="@style/AppTheme.TextInputEditText"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:imeOptions="actionDone"
                    android:inputType="textPassword"
                    android:background="@color/transparent"
                    android:maxLength="1024"
                    android:maxLines="1" />
```
Or create a style:
```
  <style name="AppTheme.TextInputEditText" parent="Widget.MaterialComponents.TextInputEditText.FilledBox">
        <item name="android:background">@color/transparent</item>
    </style>
```

**Comment by ryan-w** [comment]
I'm seeing the same issue on an emulator running **API 21** when setting a background color using the `boxBackgroundColor` attribute on a `TextInputLayout`. This is happening with the default password toggle icon (`endIconMode` = `password_toggle`).

Material Library Version: 1.4.0
