### ISSUE TITLE
[SwitchMaterial] Allow theme override

### ISSUE THREAD

**Issue by StephaneBg** [material-components/material-components-android#930]
I want to override the color that is used by SwitchMaterial. It uses colorSecondary but I need it to be a different color.

TextInputLayout allows to override color attributes of theme by setting a theme overlay on materialThemeOverlay attribute. So that it is possible to override theme palette such as colorPrimary, colorSurface...

SwitchMaterial should allow the same so it will be possible to provide a theme overlay to set custom palette that overrides default theme colors such as colorSecondary, colorControlActivated, colorSwitchThumbNormal..

**Comment by ikim24** [comment]
Hi @StephaneBg - SwitchMaterial does support the use of materialThemeOverlay. Note that the default style for SwitchMaterial sets `useMaterialThemeColors` to true which is going to use `colorControlActivated` and `colorOnSurface` (with an alpha on top of `colorSurface`). If you are using one of the (non-bridge) MaterialComponents themes, `colorControlActivated` will be set to `colorAccent` and `colorAccent` will be set to `colorOnSecondary`. If you have changed either `colorControlActivated` or `colorAccent`, changing `colorOnSecondary` will not change your switch color.

If you would like to use attributes like `colorSwitchThumbNormal`, you will need to set `useMaterialThemeColors` to false.

**Comment by StephaneBg** [comment]
Hi @ikim24,

I think I was misunderstood. It is possible to apply a theme overlay to a SwitchMaterial but only in the layout file with the use of `android:theme` but I have to set it in every layout files. I want to make switch styling opt-out and specify it in `switchStyle` in my base theme.

My use case is that in my base theme `colorSecondary` is set to my brand color but I want all the SwitchMaterial to be green (for example). So I need to override `colorSecondary` in the theme overlay that will be applied to all SwitchMaterial.

It is not possible because there is no `materialThemeOverlay` attribute in SwitchMaterial to achieve the desired behaviour.

Please advise.

**Comment by ikim24** [comment]
Hi @StephaneBg - you can add `materialThemeOverlay` to the style that you are setting as your `switchStyle` in your base theme (it does not need to be declared in the switch styleable).

**Comment by StephaneBg** [comment]
Hi @ikim24,
thanks it works. This should definitively appear in the documentation.

**Comment by renatojobal** [comment]
Hi @StephaneBg . Please, could you share how do you solve the problem. I don't know when I have to add `materialThemeOverlay`
