### ISSUE TITLE
[TabLayout] Strange API in Kotlin

### ISSUE THREAD

**Issue by StephaneBg** [material-components/material-components-android#931]
TabLayout exposes getOrCreateBadge method.

Everything is fine in the Java world but once you write your code in Kotlin it looks like tab.orCreateBadge that looks odd.

I understand that it is an API change and I don't know how you can handle it. But this should be taken into account for upcoming APIs.

**Comment by ikim24** [comment]
Thanks for lettings us know. While we aren't going to be changing this API, we will keep this in mind for future APIs.
