### ISSUE TITLE
[TextInputLayout] gravity "top" is not working for hint 

### ISSUE THREAD

**Issue by Pavneet-Sing** [material-components/material-components-android#933]
**Description:**
Prerequisite: `TextInputLayout` with `TextInputEditText` having `hint` attribute
Migrated [a layout](https://github.com/Pavneet-Sing/RoomDemo/blob/master/app/src/main/res/layout/activity_add_note.xml) having design `TextInputEditText` to `material.textfield.TextInputLayout` but it is not placing the hint at the top though it was working with `support.design.widget` and also working for `text` but not for `hint` attribute.

**Expected behavior:** 
[`Content` hint is placed at the top, see in pic](https://github.com/Pavneet-Sing/RoomDemo/blob/master/screenshots/insert.gif)

**Minimal Problematic source code:** 

   ```
 <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/txtInput"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/et_content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="top"
            android:hint="@string/et_content_text" />
    </com.google.android.material.textfield.TextInputLayout>

```

**Android API version:** 
29

**Material Library version:** 
com.google.android.material:material:1.2.0-alpha04

**Device:** Pixel 2 (AVD)

**Note:** 
I've tested this with alpha04 release, still the same issue
![issue sample](https://user-images.githubusercontent.com/11755381/72918409-9c390900-3d6b-11ea-94d6-7682afccecc9.png)

**Comment by LinggaMG** [comment]
same with me.. `android:gravity="top|start"` still not working

**Comment by ionkoto** [comment]
Still now working for me..

Android API version:
29

Material Library version:
com.google.android.material:material:1.2.0-alpha05

If it helps, setting the TextInputLayout's attribute hintEnabled=false does put the EditText to the top, but then I am missing the collapsed hint :/

![image](https://user-images.githubusercontent.com/18002934/78218127-f241cf80-74c5-11ea-8e63-2cf03a3e74b7.png)
![image](https://user-images.githubusercontent.com/18002934/78218153-fd94fb00-74c5-11ea-8e85-d6bd949790e6.png)

**Comment by xiaoyuin** [comment]
still not working with `1.2.0-alpha05`

**Comment by jtschult** [comment]
confirmed to work in `1.2.0-alpha06`

**Comment by farsheel** [comment]
> confirmed to work in `1.2.0-alpha06`

its not working

**Comment by leticiarossi** [comment]
For the filled text field style you have to set `android:minLines` to 2 or greater for it to work (along with` android:gravity="top"`)

**Comment by ionkoto** [comment]
> For the filled text field style you have to set `android:minLines` to 2 or greater for it to work (along with` android:gravity="top"`)

THANK YOU SO MUCH!

**Comment by nikiJava** [comment]
I have the same problem :(

**Comment by fahmieshaq** [comment]
> I have the same problem :(
> 
> **Material Library version:** com.google.android.material:material:1.3.0
> 
> @leticiarossi Excuse me, would it be fixed?

Try > For the filled text field style you have to set `android:minLines` to 2 or greater for it to work (along with` android:gravity="top"`)
