### ISSUE TITLE
[Slider] Set slider values to int-only

### ISSUE THREAD

**Issue by mueller-ma** [material-components/material-components-android#934]
**Is your feature request related to a problem? Please describe.**
I have a slider ranging from 0 to 100. If I want the user to be able to set integer values only (not float), I have to set step to 1.
But then the slider has way too much "discrete dots".

**Describe the solution you'd like**
You could add a flag `intOnly` or `isDiscrete`, so the user can disable these dots even if a step size is set.

**Comment by cketcham** [comment]
What version of the library are you using? Can you try with the latest one to see if that draws less dots? The number of discrete dots is limited to prevent it from showing a lot of them.

Can you include a screenshot?

**Comment by mueller-ma** [comment]
I'm using 1.2.0-alpha04 and you're right, the number of dots are limited. However isn't this against the meaning of the dots?
IMO the dots should say: This is a slider that you cannot drag to any position, but to the few positions with dots.
I suggest to check how many dots need to be displayed and if that's too much, hide them instead of limiting them.

**Comment by ThanosFisherman** [comment]
Can we somehow customize a discrete Slider to look like a continuous slider? i.e without the stepping dots?

**Comment by xitize** [comment]
android:stepSize="1" 
Theres is stepsize to give only int

**Comment by mueller-ma** [comment]
I open a new issue with the request to drop the dots if they are too much.
