### ISSUE TITLE
[Slider] Support AbsSeekBar#setThumb()

### ISSUE THREAD

**Issue by mueller-ma** [material-components/material-components-android#935]
**Is your feature request related to a problem? Please describe.**
As a little Halloween Easter egg, I replace the thumb of a slider with a pumpkin. I'm using [AbsSeekBar#setThumb()](https://developer.android.com/reference/android/widget/AbsSeekBar.html#setThumb(android.graphics.drawable.Drawable)) for that. However I haven't found a way to do so with the Slider from this lib.

**Describe the solution you'd like**
Implement `setThumb`.

**Comment by carstenhag** [comment]
Hello, is there any update on this? Would be nice to have this, as the native ProgressBar supports this already. Our designer is a bit disappointed :D

**Comment by carstenhag** [comment]
Would still love to be able to add thumb drawables to our sliders ;)

**Comment by wcshi** [comment]
Sounds similar to https://github.com/material-components/material-components-android/issues/1522

**Comment by carstenhag** [comment]
Well yes, except that this current qticket is older :P

**Comment by kamilj** [comment]
> Sounds similar to #1522

Similar does not mean the same.
