### ISSUE TITLE
[BottomNavigationView] Is shifting not supported?

### ISSUE THREAD

**Issue by krakz999** [material-components/material-components-android#936]
**Is your feature request related to a problem? Please describe.**
Shifting animation does not work. Even if I set label visibility mode to selected, the menu items just stay in place.

**Describe the solution you'd like**
Shifting animation to be working.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ikim24** [comment]
Hi @krakz999 - can you elaborate on what shifting animation you are referring to?

If you're talking about the icon shifting up and down (up above the label when it is shown and down to be centered vertically when the label is not shown), then that is currently working (see our catalog). If it's not working for you, a sample would help us understand what is causing it to break down.

**Comment by krakz999** [comment]
> Hi @krakz999 - can you elaborate on what shifting animation you are referring to?
> 
> If you're talking about the icon shifting up and down (up above the label when it is shown and down to be centered vertically when the label is not shown), then that is currently working (see our catalog). If it's not working for you, a sample would help us understand what is causing it to break down.

Hi @ikim24, here is a GIF example: https://montemagno.com/content/images/2017/08/ShiftMode.gif

**Comment by ikim24** [comment]
No, this shifting is not supported and we have no plans to support is as Material guidelines specify that "Bottom navigation bar destinations have fixed positions. They don’t scroll or move horizontally."
