### ISSUE TITLE
[MaterialShapeDrawable] Crash on Android 4.4.4 - java.lang.IllegalArgumentException: radius must be > 0

### ISSUE THREAD

**Issue by matpag** [material-components/material-components-android#937]
I'm currently using 1.1.0-beta02

We have this stacktrace on Crashlytics:
`
Fatal Exception: java.lang.IllegalArgumentException: radius must be > 0
       at android.graphics.RadialGradient.<init>(RadialGradient.java:53)
       at com.google.android.material.shadow.ShadowRenderer.drawCornerShadow(ShadowRenderer.java:160)
       at com.google.android.material.shape.ShapePath$ArcShadowOperation.draw(ShapePath.java:385)
       at com.google.android.material.shape.ShapePath$1.draw(ShapePath.java:226)
       at com.google.android.material.shape.ShapePath$ShadowCompatOperation.draw(ShapePath.java:323)
       at com.google.android.material.shape.MaterialShapeDrawable.drawCompatShadow(MaterialShapeDrawable.java:1055)
       at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:958)
       at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:349)
       at android.graphics.drawable.InsetDrawable.draw(InsetDrawable.java:158)
       at android.view.View.draw(View.java:14450)
       at android.view.View.getDisplayList(View.java:13362)
       at android.view.View.getDisplayList(View.java:13404)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13300)
       at android.view.View.getDisplayList(View.java:13404)
      ....
`

There are 0 references to my application code so I think this is caused by something out of our control and is randomly given out on some devices with 4.4.4.

Apparently the cause is [here](https://github.com/material-components/material-components-android/blob/1.1.0-beta02/lib/java/com/google/android/material/shadow/ShadowRenderer.java#L160)
where `bounds.width` is 0 or negative and is passed as the radius parameter to the `RadialGradient`, which crashes [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/graphics/java/android/graphics/RadialGradient.java;l=104?q=RadialGradient) because a radius of 0 or less is not allowed.

Any hint or workaround possible? Maybe we could fix a wrong width providing a default value in [MaterialShapeDrawable.drawCompatShadow](https://github.com/material-components/material-components-android/blob/1.1.0-beta02/lib/java/com/google/android/material/shape/MaterialShapeDrawable.java#L1055) or not trying to draw the shadow at all??

**Comment by ikim24** [comment]
Hi @matpag - Do you have any custom shapes that you're using in your application? I'm trying to understand what shape is causing that radius to be 0 or negative to determine the appropriate resolution.

**Comment by matpag** [comment]
Yes I have custom shapes in styles.
```
    <style name="UserBottomSheet.ShapeAppearanceOverlay.ListButton" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSizeTopRight">50%</item>
        <item name="cornerSizeBottomRight">50%</item>
        <item name="cornerSizeBottomLeft">0dp</item> <!-- I have 0 here -->
        <item name="cornerSizeTopLeft">0dp</item> <!-- I have 0 here -->
    </style>
```
```
    <style name="UserBottomSheet.ShapeAppearanceOverlay.HeaderButton" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">50%</item>
    </style>
```
```
    <style name="UserBottomSheet.ShapeAppearanceOverlay.PrivacyButton" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSizeTopRight">10%</item>
        <item name="cornerSizeBottomRight">10%</item>
        <item name="cornerSizeBottomLeft">10%</item>
        <item name="cornerSizeTopLeft">10%</item>
    </style>
```
```
    <style name="WizardBottomSheet.ShapeAppearance.Style" parent="ShapeAppearance.MaterialComponents.MediumComponent">
        <item name="cornerSizeTopLeft">48dp</item>
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">0px</item> <!-- here I typed 0px, even if not intentional is not causing problem on other devices -->
    </style>
```
```
    <style name="Widget.Default.TextInput.ShapeAppearanceOverlay.Rounded" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">4dp</item>
        <item name="cornerFamilyTopRight">cut</item>
        <item name="cornerSizeTopRight">8dp</item>
    </style>
```
Despite some values are 0, we don't have problem on devices with an Android version greater than 4.4.4.

Just ask for more info,
thank you

**Comment by ikim24** [comment]
Hi @matpag - It makes sense that you'd only have issues with 4.4.4 and earlier as that's (generally) when we'd be drawing the compat shadows (since 4.4.4 and earlier have no framework shadow support).

I'm unable to reproduce this in 4.4.4 with the shapes that you provided -- do you know if you have any interpolation that is happening that might be affecting the shapes?

Also, do you know how frequently you are seeing this on Android 4.4.4?

Thanks!

**Comment by matpag** [comment]
We have a component which is very similar to the `LessonsSheetFragment` of the material example.

We use the style `WizardBottomSheet.ShapeAppearance.Style` posted above at this [line](https://github.com/material-components/material-components-android-examples/blob/374b9c815e51bc53ba072034d2964218852f7370/Owl/app/src/main/java/com/materialstudies/owl/ui/lessons/LessonsSheetFragment.kt#L109).

The sheet background is then interpolated during expansion/restriction of the sheet and interpolated at this [line](https://github.com/material-components/material-components-android-examples/blob/374b9c815e51bc53ba072034d2964218852f7370/Owl/app/src/main/java/com/materialstudies/owl/ui/lessons/LessonsSheetFragment.kt#L131).

This are the only interpolation we have in the app with a style which has a 0 cornerSize.
The crash is rare, the frequency is a couple crashes per 200 4.4.4 installation.

I don't think this deserve too much work, maybe is not worth the time invested with the current informations. 
If I'll find some way to reproduce the problem consistently I will update the issue with more info.
In the meantime thank you for your time :)

**Comment by awenger** [comment]
We also started to get this crash.
I checked our diff for the first release that had this crash. Not sure if it is the cause, but at least could be the reason for the problem:
```
-    material_design_version = '1.1.0-alpha08'
+    material_design_version = '1.1.0-beta02'
```

**Comment by awenger** [comment]
We also had a user contact us with a crash report for this issue and it is apparently reproducible, even after a re install of the app. We also see it across many different devices/manufacturers.

I also took a look into the styles of our MaterialCardViews. We have a stroke around them with a color and 0dp elevation. Otherwise they should be `Widget.MaterialComponents.CardView`. But I only had a few minutes to check this, so it could be that there are other CardViews on this screen that I missed (The crash happens on our start screen which has many card views on it). Also another special case is that we have one place were we needed to Wrap a MaterialCardView inside of another MaterialCardView for some reason I don't remember any more (Not sure if this could cause any strange things).

**Comment by droidartel** [comment]
After changing version to 1.0.0 problem disappears.

**Comment by matpag** [comment]
Downgrading from 1.1.0 to 1.0.0 should not be a viable solution...
We just need to find and fix the problem (if possible)

**Comment by droidartel** [comment]
> Downgrading from 1.1.0 to 1.0.0 should not be a viable solution...
We just need to find and fix the problem (if possible)

Of course, but I serves as a workaround, almost approves the bug and allows to find the problem between changes.

**Comment by muhammad-naderi** [comment]
+1 for this issue
