### ISSUE TITLE
[MaterialTextInputPicker] Mobile date input picker does not look correct to spec

### ISSUE THREAD

**Issue by kassim** [material-components/material-components-android#939]
**Description:** 
When running the demo 'components' app and when including it in my own app, the 'Mobile date input picker' does not look up to spec. 

In particular:
- there is a large space between to input text box and the ok/cancel buttons
- there is no hint to help with the expected input format

the space appears to be due to the height of the 'Mobile calendar picker' which is also inflated (but hidden behind the input view)

![Screenshot_20200123-155254_Material Components Catalog](https://user-images.githubusercontent.com/11020264/72995832-dd77fa00-3df9-11ea-904b-e83b0f34876a.jpg)
![Screenshot_20200123-155301_Material Components Catalog](https://user-images.githubusercontent.com/11020264/72995837-e10b8100-3df9-11ea-841d-5d27d5cbc018.jpg)

**Expected behavior:** 

- there shouldn't be a large space between the input box and the ok/cancel buttons
- there should be a hint to guide the input format

see 'Mobile date input picker' https://material.io/components/pickers/#mobile-pickers
![](https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1wNxz6MUqYsaFugCBe80ekoVz6m1XsS2K%2Fpicker-choosing-textfield.png)

**Android API version:** 
29

**Material Library version:**
1.2.0-alpha04

**Device:** 
Samsung S9
Emulator x86 (Nexus 5X)

**Comment by KarmaBuildsApps** [comment]
The issue still exist on version 1.2.0-alpha05

**Comment by andre-sonect** [comment]
The issue still exists on version 1.3.0-alpha01

**Comment by gabrielemariotti** [comment]
The placeholder text was merged with 6050bd43475aed0448c31e2adcaf01244cdff05d in #1528.
It should be available in the next release.

**Comment by whiteLT** [comment]
The issue still exists on version 1.3.0-alpha03
![image](https://user-images.githubusercontent.com/8414354/95734176-d6489300-0c8b-11eb-9e6f-c1321c5d70b6.png)

**Comment by langsmith** [comment]
@gabrielemariotti , any idea whether this 🐛 will be looked at in the near future?

**Comment by langsmith** [comment]
Looks as if https://github.com/material-components/material-components-android/pull/2162 might fix this

**Comment by drchen** [comment]
Looks like it's been fixed. Close the issue...
