### ISSUE TITLE
[Material.io] Markdown table is incorrectly formatted

### ISSUE THREAD

**Issue by ataulm** [material-components/material-components-android#940]
Markdown table on the color theming page is incorrectly formatted so it doesn't render correctly.

https://material.io/develop/android/theming/color/

![image](https://user-images.githubusercontent.com/2678555/73004938-0d2a0080-3e00-11ea-9405-33d878e710c1.png)

**Comment by ikim24** [comment]
Formatting has been update and we will be updating material.io

**Comment by leticiarossi** [comment]
material.io has been updated
