### ISSUE TITLE
Customization of Material Date Range Picker

### ISSUE THREAD

**Issue by HardikLohogaonkar** [material-components/material-components-android#943]
Pls provide us to show only "Calendar" in Range Picker. Also provide us to disable/customize the buttons in range picker's Header.
![Screenshot_20200124-130505_Material Picker (1)](https://user-images.githubusercontent.com/33368156/73053006-a282ce80-3eac-11ea-8535-ac0d226e4a45.jpg)

**Comment by saurabhdtu** [comment]
What  theme  parameter controls the text color for Week days (s,m,t,w...)?

**Comment by jsouza678** [comment]
You can disable this button by using:
`    <item name="materialCalendarHeaderToggleButton">@style/Widget.AppTheme.MaterialCalendar.HeaderToggleButton</item>
`

`  <style name="Widget.AppTheme.MaterialCalendar.HeaderToggleButton" parent="Widget.MaterialComponents.MaterialCalendar.HeaderToggleButton">
    <item name="android:visibility">gone</item>
  </style>`

**Comment by HardikLohogaonkar** [comment]
> You can disable this button by using it on your material date range picker style:
> ` <item name="materialCalendarHeaderToggleButton">@style/Widget.AppTheme.MaterialCalendar.HeaderToggleButton</item>`
> 
> ` <style name="Widget.AppTheme.MaterialCalendar.HeaderToggleButton" parent="Widget.MaterialComponents.MaterialCalendar.HeaderToggleButton"> <item name="android:visibility">gone</item> </style>`

**Comment by drchen** [comment]
The solution @HardikLohogaonkar provided is a recommended one.  

And about day of week label, in the latest library version you can override ?attr/materialCalendarDayOfWeekLabel in the style depicted in ?attr/materialCalendarTheme to customize the color of it.
