### ISSUE TITLE
will this repo be converted into kotlin?

### ISSUE THREAD

**Issue by touseefbsb** [material-components/material-components-android#95]
after google IO 18, it seems tht kotlin is really loved by all android developer community specially with android jetback and android kotlin ktx. but this repo still seems to be in java, will it be converted into kotlin or will we have a separate branch for kotlin or how would that work basically?

**Comment by cketcham** [comment]
Yes we wont be converting this library to kotlin. We may consider using kotlin for some components in the future, but since kotlin and java are interoperable this isn't really necessary.
