### ISSUE TITLE
[Chip] Double emission on check state change when `selectionRequired` is used

### ISSUE THREAD

**Issue by pavlospt** [material-components/material-components-android#952]
**Description:** 
When using the `selectionRequired` feature in a `ChipGroup` and we try to un-check the last checked `Chip`, any `OnCheckChangeListenter` that is set, is getting double emissions for the state of that `Chip`. The reason for that is because there is a tracking listener which checks the number of already checked `Chip`s and resets the checked state after the first emission has been propagated to the original listener.

**Expected behavior:**
Receive no emissions, if `selectionRequired` is enabled and we try to un-check the last checked `Chip`.

**Source code (location of the issue)**
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/chip/ChipGroup.java#L521 

**Android API version:** Any

**Material Library version:** `1.2.0-alpha04`

**Device:** Any

**Comment by pavlospt** [comment]
I am not 100% sure that this issue was resolved correctly. What I mean by that is, that after the fix we get the emission of a non-checked chip and propagate it to our consumers as a non-checked event. Following the `Chip` is re-selected programmatically and this is never propagated to us. 

The actual event that we are "interested" in though, is the final event and not the user's intention. We are not "interested" in the user's intention, since it actually has no effect on the component. 

I believe this needs to be fixed, but totally open to hear more opinions on that matter 😄

**Comment by wcshi** [comment]
Use the listener in the chip group to propagate checked events to your consumer instead of directly setting listeners on the child chips. See the test in 401b99e

**Comment by pavlospt** [comment]
@wcshi Will take a look at that! Thank you!
