### ISSUE TITLE
[ElevationOverlay] Dark theme overlay not applied when using color state list

### ISSUE THREAD

**Issue by claytongreen** [material-components/material-components-android#955]
**Description:**
When using  `MaterialShapeDrawable.createWithElevationOverlay()` and adding it as the background to a view, it doesn't apply the semi-transparent overlay to indicate elevation if `colorOnSurface` is a color state list resource.

The test app has a night theme with `colorOnSurface` reference to a color state list resource that is used to set the alpha on a color:
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:alpha="0.87" android:color="#fff" />
</selector>
```
There are 2 TextViews and they both have a MaterialShapeDrawable set as their background. The second one uses a theme overlay to illustrate the elevation overlay working with an argb color set as `colorOnSurface`.

```
<style name="ThemeOverlay.App.White87ARGB" parent="ThemeOverlay.MaterialComponents">
    <item name="colorOnSurface">#DEFFFFFF</item>
</style>
```

**Expected behavior:**
The background of `colorOnSurface: @color/white_87` should match `colorOnSurface: #DEFFFFFF`.

![Screenshot_1580244947](https://user-images.githubusercontent.com/3336370/73304722-a6289500-41cd-11ea-9c29-5359796fbc70.png)

**Source code:** 
[https://github.com/claytongreen/elevation_overlay_bug](https://github.com/claytongreen/elevation_overlay_bug)

**Android API version:** 29

**Material Library version:** 1.2.0-alpha04

**Device:** API 29 Pixel 3 emulator

**Comment by BenjaminHolland** [comment]
#359 seems to be related. Using SHADOW_COMPAT_MODE_ALWAYS fixes this.

**Comment by claytongreen** [comment]
Yes, it looks like it is still not working. Not even with `shadowCompatMode`.
I've updated the repository to use `com.google.android.material:material:1.6.0-beta01` and show surfaces using the three different compat modes.

![screenshot](https://user-images.githubusercontent.com/3336370/161873658-68bdc3ab-7594-4237-bd2a-f8aed18758dd.png)
