### ISSUE TITLE
[BottomAppBarTopEdgeTreatment] make methods non-restricted

### ISSUE THREAD

**Issue by hrach** [material-components/material-components-android#961]
I'd like to ask you to make all currently restricted methods of BottomAppBarTopEdgeTreatment non-restricted/public. 

- getFabDiameter
- setFabDiameter
- getHorizontalOffset

(Actually, setHorizontalOffset is not restricted)

**Describe alternatives you've considered**
Copy-past.

**Additional context**
I'd like to use this convenient edge treatment in other componets.

**Comment by drchen** [comment]
Can you explain the reason why you need to know fabs' diameter?

Also setFabDiameter() is a package private method not intended for public use. We have no plan to support it under general use scenarios.

**Comment by hrach** [comment]
TBH I don't even remember why I needed this. Since there is no :+1: or a comment and I don't need this anymore, I'd close this as irrelevant.
