### ISSUE TITLE
[MaterialButton] Lint warning for buttons with icons but no text or content description

### ISSUE THREAD

**Issue by shekibobo** [material-components/material-components-android#964]
**Is your feature request related to a problem? Please describe.**

I was just going through my theme demo with talkback on, and realized my MaterialButton s that contain only an icon (no text) have no content descriptions on them. Since there’s no MaterialImageButton, seems like the go-to for an icon-only button would be the MaterialButton , but there’s apparently no check on it for ensuring it has readable content.

It appears that there's also no lint for FABs ensuring they have a content description.

**Describe the solution you'd like**

A lint warning that ensures a button has either text or a content description if it has an icon, kind of like how the linter will complain if you set something that’s a `labelFor` without it having text or a content description

**Describe alternatives you've considered**

Material theming doesn't apply easily to `ImageButton`. I could write my own linter, but it seems like an issue important enough to share. There may be another suggestion for icon-only buttons with material designs that I'm not considering.

**Comment by drchen** [comment]
Can you elaborate more about the lint warning in your mind?

For example, how do we know if a button have text or content description or not? They may well be set at runtime.

**Comment by drchen** [comment]
I'll close the request due to no further info. Please feel free to reopen it if you have more insights to provide. : )
