### ISSUE TITLE
[MaterialDatePicker] Theme override is not applied to Text Fields in Text Entry Mode

### ISSUE THREAD

**Issue by froriz5** [material-components/material-components-android#966]
**Description:** Full description of issue here
When instantiating a MaterialDatePicker using the Builder, one of the params is a theme override called [setTheme(...)](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/datepicker/MaterialDatePicker.java#L569)

Here, we can modify how to theme the view with different colors.

It looks like this component uses `colorPrimary` for almost all the theming.

However, it looks like the `TextInputLayout` used by the Text Entry mode when selecting a date ignores the `colorPrimary` value passed in the builder.

**Current Behavior**
![datePickerCurrentBehavior](https://user-images.githubusercontent.com/1795695/73573953-25ba9c00-443a-11ea-9dff-1da8b4eccda9.png)

In this current behavior, the `AppTheme` has a `colorPrimary` set to a white value.

**Expected behavior:**
The override theme's `colorPrimary` should be used instead of the app theme's `colorPrimary` attribute.

![datePickerExpectedBehavior](https://user-images.githubusercontent.com/1795695/73573901-0f144500-443a-11ea-9e4c-ae3bf0463aa8.png)

**Source code:** 
Example style:
```
<style name="CustomCalendarDatePickerTheme" parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar">
    <item name="colorPrimary">@color/colorPrimary</item> <!-- #ff364141 -->
</style>
```

In the code:
```
val builder = MaterialDatePicker.Builder.dateRangePicker().apply {
     setTitleText("Title")
     setTheme(R.style.CustomCalendarDatePickerTheme)
}.build()
        
builder.show(supportFragmentManager, "")
```

**Android API version:** 10 Q

**Material Library version:** 1.2.0-alpha04

**Device:** Pixel 2

**Comment by achatina** [comment]
Also has this bug on 1.3.0-alpha01

**Comment by p1415604x** [comment]
I am having similar issue. Setting theme with style for 

- item materialCalendarHeaderLayout - works
- item textInputStyle - does not work

Instead of taking style from the theme given in builder it takes textInputStyle style from application, so it ignores given theme and uses same styling as all other textInputs within application. Meanwhile it takes correct style values given for header, even it is within same style set to the builder.

Android API Version: 9
Material Library Version: 1.3.0-alpha01
Device: LG G5

**Comment by dsn5ft** [comment]
Thanks for reporting this, I'm looking into it.

**Comment by alhajsid** [comment]
i am on 1.3.0 version
bug is still here

**Comment by WestFR** [comment]
Same here
