### ISSUE TITLE
[MaterialAlertDialogBuilder] Crash building dialog with Material Components app theme

### ISSUE THREAD

**Issue by hassieswift621** [material-components/material-components-android#969]
**Description:** Attempting to build a AlertDialog using the MaterialAlertDialogBuilder causes the app to crash in a AppCompatActivity, even though the application theme is set to a Material Components theme.

Stacktrace
```text
java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
        at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:213)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:148)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
        at com.google.android.material.dialog.MaterialDialogs.getDialogBackgroundInsets(MaterialDialogs.java:60)
        at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:117)
        at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:103)
        at ninja.hassie.uni.todo.MainActivity$2.handleFault(MainActivity.java:69)
        at com.backendless.Persistence$1.handleFault(Persistence.java:189)
```

**Expected behavior:** The dialog should build as the app theme is set to a Material Components theme.

**Source code:**
styles.xml
```xml
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorSecondary">@color/colorAccent</item>
    </style>
</resources>
```

MainActivity.java
```java
public class MainActivity extends AppCompatActivity {
    ...
    new MaterialAlertDialogBuilder(getApplicationContext())
         .setMessage("Successfully added task")
         .setPositiveButton(android.R.string.ok, null)
         .show();
```

**Android API version:** 9 Pie

**Material Library version:** 1.2.0-alpha04

**Device:** OnePlus 5T

**Comment by ikim24** [comment]
Hi @hassieswift621 - The application's context isn't guaranteed to have the theme, so you'll either need to call setTheme on it or use the Activity's context.

**Comment by hassieswift621** [comment]
Thanks 😄

**Comment by asiawin** [comment]
Fixed my issue! Thanks

**Comment by i-tanova** [comment]
What?

**Comment by nimaiwalsh** [comment]
Having the same issue, can you please define the setTheme fix a little more? activityContext didn't work for us either.

**Comment by hassieswift621** [comment]
> Having the same issue, can you please define the setTheme fix a little more? activityContext didn't work for us either.

The fix was to use reference the activity for example, in my example, the fix was `MainActivity.this`.

**Comment by nimaiwalsh** [comment]
Unfortunately neither solution works for material design 3.0.0. Tried explicitly setting theme with setTheme on application context (which was also set in the Manifest file before the issue), and specifying the activity for the context.

This is still open and discussed here: https://github.com/material-components/material-components-android/issues/2056.

The only hacky workaround for us at the moment is extending from `Theme.MaterialComponents.Dialog.Alert` instead of `ThemeOverlay.MaterialComponents.MaterialAlertDialog` and using colour references instead of `attr` from theme.
