### ISSUE TITLE
Coordinator Layout

### ISSUE THREAD

**Issue by dovahkiin98** [material-components/material-components-android#97]
Will coordinator layout move from support-design to material components?
Also, what is the min supported Android API for these parts and themes?

**Comment by dsn5ft** [comment]
`CoordinatorLayout` has been moved from the Design library to a separate androidx library (androidx.coordinatorlayout:coordinatorlayout:1.0.0-alpha1) - https://developer.android.com/reference/androidx/coordinatorlayout/widget/CoordinatorLayout. It will not be moving to Material Components.

The minimum supported API level for all Support Libraries is 14 - https://developer.android.com/topic/libraries/support-library/#api-versions.
