### ISSUE TITLE
[MDC] Expose an object with pointers to correct attributes for references

### ISSUE THREAD

**Issue by burntcookie90** [material-components/material-components-android#973]
**Is your feature request related to a problem? Please describe.**
Currently, MDC uses some attributes defined by itself, and other defined by Android. This can lead to confusion on where to access something like `android.R.attr.textColorPrimary` vs `R.attr.colorError`

**Describe the solution you'd like**
Expose a single class that points to things you need!

```kotlin
object MaterialTheme {
  //region primary
  @JvmStatic @AttrRes val colorPrimary = R.attr.colorPrimary
  @JvmStatic @AttrRes val colorPrimaryVariant = R.attr.colorPrimaryVariant
  @JvmStatic @AttrRes val colorOnPrimary = R.attr.colorOnPrimary
  //endregion
  //region secondary
  @JvmStatic @AttrRes val colorSecondary = R.attr.colorSecondary
  @JvmStatic @AttrRes val colorSecondaryVariant = R.attr.colorSecondaryVariant
  @JvmStatic @AttrRes val colorOnSecondary= R.attr.colorOnSecondary
  //endregion
  //region background
  @JvmStatic @AttrRes val colorBackground= android.R.attr.colorBackground
  @JvmStatic @AttrRes val colorOnBackground = R.attr.colorOnBackground
  //endregion
  //region surface
  @JvmStatic @AttrRes val colorSurface= R.attr.colorSurface
  @JvmStatic @AttrRes val colorOnSurface = R.attr.colorOnSurface
  //endregion
  //region error
  @JvmStatic @AttrRes val colorError= R.attr.colorError
  @JvmStatic @AttrRes val colorOnError = R.attr.colorOnError
  //endregion
  //region text
  @JvmStatic @AttrRes val textColorPrimary= android.R.attr.textColorPrimary
  @JvmStatic @AttrRes val textColorSecondary= android.R.attr.textColorSecondary
  @JvmStatic @AttrRes val textColorLink= android.R.attr.textColorLink
  //endregion
}
```

**Describe alternatives you've considered**
Directly referencing attributes. This leads to confusion

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
I agree it is a bit confusing but also seems having very low impact. I can raise this to the team and see what they think.

**Comment by dsn5ft** [comment]
Thanks for the feedback. It is true that some Android framework attributes like `android.R.attr.colorBackground` are "part of the Material color system", but it's less clear for attributes like `android.R.attr.textColorPrimary`. We do our best to set reasonable defaults for those, but our library doesn't really own them, and they are usually ColorStateLists so I'm not sure how common it is for apps to load and use them programmatically.

Also, the main usages of these attributes are in XML, so I'm not sure the value of a class like this outweighs the maintenance cost.
