### ISSUE TITLE
[TextInputLayout] Start icon tint does not follow boxStrokeColor rules in ExposedDropdownMenu

### ISSUE THREAD

**Issue by pavlospt** [material-components/material-components-android#975]
**Is your feature request related to a problem? Please describe.**
We have noticed that when trying to apply custom theming on `ExposedDropdownMenu` components, the Color selector of `startIcontTint` does not follow the same rules that `boxStrokeColor` does, which leads to weird UI incosistencies. Please see screenshots attached below.

**Describe the solution you'd like**
The solution we have thought of, is adding a different Color selector on the `ThemeOverlay`s of `ExposedDropdownMenu` styles, which will follow the same rules that `boxStrokeColor` does.

**Describe alternatives you've considered**
Alternatives are overriding the `startIconTint` in our `TextInputLayout.ExposedDropdownMenu`'s theme overlay and use the same color selector that `boxStrokeColor` uses.

**Additional context**

# Current situation
![Screenshot_1580806363](https://user-images.githubusercontent.com/1070871/73729691-328f0680-473e-11ea-911a-92a4394b7180.png)
![Screenshot_1580806367](https://user-images.githubusercontent.com/1070871/73729692-33279d00-473e-11ea-9378-3417e38e43a7.png)

# Desired behaviour
![Screenshot_1580806311](https://user-images.githubusercontent.com/1070871/73729725-42a6e600-473e-11ea-826f-4734802e6901.png)
![Screenshot_1580806314](https://user-images.githubusercontent.com/1070871/73729728-42a6e600-473e-11ea-9a41-adc3495e9e45.png)

**Comment by ikim24** [comment]
We're checking with our design team as to whether this should be the default behavior for the color of the start icon.

**Comment by ikim24** [comment]
As per https://material.io/components/menus/#exposed-dropdown-menu, exposed dropdown menus don't have start icons by default. As such, we aren't going to be adding default tinting for the start menu in the library. If you are choosing to add a start icon to your exposed dropdown menus, you can certainly create styles based off the default ones that do add start icon tints.
