### ISSUE TITLE
[MaterialButton] Background tint drawable state desynchronizes when using OnAttachStateChangeListener

### ISSUE THREAD

**Issue by damianw** [material-components/material-components-android#982]
**Description:**
Calling `View.getDrawableState` on a `MaterialButton` within an `OnAttachStateChangeListener`
computes a new drawable state without notifying `drawableStateChanged`. This results in the
`MaterialButton` failing to update the drawable state of the background tint until the next time it
changes (by e.g. touching the button, etc). `getDrawableState` is used by many APIs - something as simple as `setTextColor` will call `getDrawableState` and expose the problem.

**Expected behavior:**
I have created a sample project that demonstrates the problem [here](https://github.com/damianw/WasclDrawableStateIssue).

In the following demo, we attach a fragment (defined in [`MainFragment`](https://github.com/damianw/WasclDrawableStateIssue/blob/master/app/src/main/java/wtf/log/wascldrawablestateissue/MainFragment.kt))
at some point after the activity (defined in [`MainActivity`](https://github.com/damianw/WasclDrawableStateIssue/blob/master/app/src/main/java/wtf/log/wascldrawablestateissue/MainActivity.kt)) is created, and
while the window has focus. The background tint of the button (defined in [`button_tint_selector`](https://github.com/damianw/WasclDrawableStateIssue/blob/master/app/src/main/res/color/button_tint_selector.xml))
defines the disabled state as red with a default state of green.

<img src="https://github.com/damianw/WasclDrawableStateIssue/raw/master/demo.gif" width="480"/>

The background tint incorrectly displays the disabled state even though the button
is in the enabled state. Touching the button (or un-focusing and re-focusing the window, etc)
synchronizes the state to the background tint and the issue resolves itself. 

**Source code:** https://github.com/damianw/WasclDrawableStateIssue

**Android API version:** Any (28 in demo)

**Material Library version:** 1.2.0-alpha04

**Device:** Any (Pixel 3 simulator in demo)

**Comment by drchen** [comment]
Hi I think this whole drawable state logic is handled by the framework View class and there's not much we can do about having a generic solution on our end. I'll close this as infeasible.
