### ISSUE TITLE
Change log or update notes from stable 1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by adityabhaskar** [material-components/material-components-android#986]
I just noticed that 1.1.0 stable just landed, and behaviour/API has changed for some components.

Is there a change log, or update notes for developers, to migrate from 1.0.0 to 1.1.0? Something like [this](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.2.0) is for `androidx.lifecycle`.

The release notes here on Github only notify the differences between the stable and last RC version (and so on). There are change notes on each alpha, beta, and RC release, but it's not very helpful to collate them all and try to understand what has changed between two stable versions.

I'm sure there must be a single source of changes somewhere, but I'm just unable to locate it.

**Comment by andrelabonte** [comment]
Notes have been updated for 1.1.0 Release.
