### ISSUE TITLE
tabBackground attr not behavior as expectation.

### ISSUE THREAD

**Issue by Nobler** [material-components/material-components-android#987]
I config TabLayout as blow:
```
    <com.google.android.material.tabs.TabLayout
        android:id="@+id/tab_layout"
        android:layout_width="match_parent"
        android:layout_height="52dp"
        android:clipToPadding="false"
        android:paddingStart="10dp"
        android:paddingEnd="10dp"
        app:tabBackground="@drawable/tab_background"
        app:tabIndicatorHeight="0dp"
        app:tabPaddingEnd="6dp"
        app:tabPaddingStart="6dp">
```

Tab background will be drawn with offset=10dp.
I thought it is because the background drawn without adding padding set in its parent.
```
    // TabView#drawBackground
    private void drawBackground(@NonNull Canvas canvas) {
      if (baseBackgroundDrawable != null) {
        baseBackgroundDrawable.setBounds(getLeft(), getTop(), getRight(), getBottom());
        baseBackgroundDrawable.draw(canvas);
      }
    }
```

**Comment by leticiarossi** [comment]
Can you provide screenshots of your issue and what you expected to have? Or a sample app with the issue.

**Comment by Nobler** [comment]
> Can you provide screenshots of your issue and what you expected to have? Or a sample app with the issue.

Sure. I will provide a sample app later.

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
