### ISSUE TITLE
End alignment of the fab in 1.1.0 causes issues when showing/hiding and menu items exist in BottomAppBar

### ISSUE THREAD

**Issue by jackgu1988** [material-components/material-components-android#989]
When I am showing/hiding the fab in the BottomAppBar, and it is end aligned, I get weird behaviour of the menu items. They 1. sometimes get drawn on top of the fab (instead of the left side of the screen), and 2. flicker a bit when I make them visible, while making the fab invisible. I posted a relevant question on StackOverflow, with relevant code: https://stackoverflow.com/questions/60094746/material-components-version-1-1-0-flicker-when-hiding-fab-showing-menu-item-in-b

**Comment by drchen** [comment]
It looks like this has been fixed. Feel free to reopen it if this is still happening.
