### ISSUE TITLE
[Snackbar] Respect AnchorView's visibility

### ISSUE THREAD

**Issue by yshrsmz** [material-components/material-components-android#991]
Say I have a single Activity application.
The app consists of two Fragments: TopListFragment and DetailFragment.
TopListFragment has a FloatingActionButton, and other Fragment does not.
I want to persist Snackbar while transitioning between two Fragments, so the FloatingActionButton is placed inside the root Activity.
The problem is, Snackbar does not respect FloatingActionButton's visibility. To display Snackbar above the FAB, I write the following code in Activity.

```kotlin
fun showMessage(message: String) {
  Snackbar.make(findViewById(R.id.content), message, Snackbar.LENGTH_SHORT)
    .setAnchorView(R.id.fab)
    .show()
}
```

This does work in TopListFragment, but does not work in DetailFragment. The margin between the Snackbar and the navigation bar is too much as if there is an invisible FAB. You may say that I should not set AnchorView when I'm in the DetailFragment, but that results in the FAB above the Snackbar when I navigate back to TopListFragment while Snackbar is visible.

So it would be nice if Snackbar can handle AnchorView's visibility change, or at least an API to update already visible Snackbar's AnchorView.

**Comment by drchen** [comment]
This is as you said, against the definition of "anchor" view. If the anchor is gone, how do we "anchor" to it? 

In your case, how about using a listener to change the anchor view when the visibility changes? Closing the issue for now...
