### ISSUE TITLE
[Expanding Bottom Sheet] Missing Component

### ISSUE THREAD

**Issue by DonnieWest** [material-components/material-components-android#994]
**Is your feature request related to a problem? Please describe.**
In the [Material Design Guildelines there's an Expanding Bottom Sheet component](https://material.io/components/sheets-bottom/#expanding-bottom-sheet) that isn't available in the Android Components nor is it documented how to achieve a similar effect

I noticed that the [flutter docs have a section also dedicated to this component](https://github.com/material-components/material-components-flutter/blob/master/docs/components/expanding-bottom-sheet.md#expanding-bottom-sheet) which describe this as a rather complex feature and something that is likely to need to be created with your own bespoke solution. It'd be nice to know if that's the same on Android

**Describe the solution you'd like**
Ideally, we'd have an out of the box component that has this behavior. Otherwise, I'd appreciate either a similar disclaimer for Android with some starting points on how to accomplish this on your own

**Describe alternatives you've considered**
N/A

**Additional context**
I ran across the lack of additional documentation while trying to build this feature myself

**Comment by DonnieWest** [comment]
Realizing that this is easily accomplished with the off-the-shelf Bottom sheet component. My confusion was how the Action Button works with the bottom sheet. I thought it was draggable somehow but all examples show that it's clicked

Sorry for the noise

**Comment by leticiarossi** [comment]
Hi, as of now we don't offer it by default. However, the Owl example app has an implementation of it that builds on the existing `BottomSheetBehavior`: https://github.com/material-components/material-components-android-examples/blob/develop/Owl/app/src/main/java/com/materialstudies/owl/ui/lessons/LessonsSheetFragment.kt

We are also currently working on improving documentation of all of our components.

**Comment by DonnieWest** [comment]
@leticiarossi thanks for the direction! My mistake for not checking out the other branches 👍

**Comment by HeyAlex** [comment]
@leticiarossi faced the same problem and make a [library](https://github.com/HeyAlex/CornerSheet) for this kind of behavior. The idea is the same like in metarial sample, but all things done in one behavior.
