### ISSUE TITLE
[ShapeableImageView] Does not draw its background

### ISSUE THREAD

**Issue by takasfz** [material-components/material-components-android#995]
**Description:** ShapeableImageView does not draw its background.

**Expected behavior:** 

|expected|actual|
|-|-|
|<img height="480" src="https://user-images.githubusercontent.com/12707307/74013097-0d64f700-49cf-11ea-921d-cff4d41d1153.png" />|<img height="480" src="https://user-images.githubusercontent.com/12707307/74013108-13f36e80-49cf-11ea-9563-be347c2df112.png" />|

**Source code:** 

catalog_imageview.xml
```diff
  <com.google.android.material.imageview.ShapeableImageView
    android:id="@+id/image_view"
    android:layout_margin="10dp"
    android:layout_gravity="center"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:scaleType="fitXY"
    android:adjustViewBounds="true"
    app:strokeColor="?attr/colorSecondary"
    app:shapeAppearance="?attr/shapeAppearanceMediumComponent"
    app:strokeWidth="1dp"
    app:elevation="5dp"
+   android:background="@color/design_dark_default_color_primary"
    android:padding="8dp"
    app:srcCompat="@drawable/dog_image" />
```

**Android API version:** 29

**Material Library version:**
20d2efed827f622e83b5a32a17835bb52b723ffb

**Device:** Pixel 4

**Comment by ymarian** [comment]
Hi thanks. for the report. I don't think it makes sense given that "shapeable" in our library means the view (and therefore the background is clipped to the shape everywhere else in our library). 

Showing part of the background due to the padding does seem like a bug though. 

I think for your example you would need to put the background in a container. Thoughts?

**Comment by takasfz** [comment]
Indeed. I convinced that the background of the padding should not be displayed. Thanks!
