### ISSUE TITLE
[OutlinedBox.Dense.ExposedDropdownMenu] Using android:layout_marginStart causes the outline to cut into the start of the hint text when focused

### ISSUE THREAD

**Issue by Kdaw** [material-components/material-components-android#996]
**Description:** marginStart does the opposite of what is expected, by moving the hint text further left as the value increases, causing the outline to cut into the text making it more difficult to read

**Expected behavior:** We should see the margin increase as the value increases, rather than being negatively applied

**Source code:** <AutoCompleteTextView
            android:id="@+id/ddBodyPart"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginStart="8dp"
            android:hint="@string/hint_body_part"
            app:layout_constraintBottom_toBottomOf="@+id/textInputBodyPart"
            app:layout_constraintEnd_toEndOf="@+id/textInputBodyPart"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="@+id/textInputBodyPart" />

**Android API version:** Android API version 29

**Material Library version:** Material Android Library version 1.1.0-rc02

**Device:** Samsung Galaxy A10

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Solely from the description I think this is fixed. Please feel free to reopen it if it's still happening. Some screenshots will help!
