### ISSUE TITLE
Is there a way to use ChipGroup like a RecyclerView?

### ISSUE THREAD

**Issue by thsaravana** [material-components/material-components-android#997]
`ChipGroup` has some nifty features like `selectionRequired`, `singleLine` `singleSelection`, etc... But since it's a basic ViewGroup, all I can do is add and remove views (`Chip`). I am looking for something like a RecyclerView, where I can have a DataSet and create Chips based on that, which will let me modify the Chips using DiffUtil.

Is there a way I can do this? I could use a RecyclerView directly, but I don't want to miss out the features already supported by `ChipGroup`.

**Comment by wcshi** [comment]
Hi @thsaravana could you please explain your use case? What kind of data are you trying to modify after populating a chipgroup?

**Comment by thsaravana** [comment]
I am trying to modify the Chips themselves. Basically, the Chips are created from a dataset. I was thinking of implementing it via ViewModel and LiveData in such a way that, when the underlying data changes, the Chips would also change. Right now, when the data changes, I have to remove the views from ChipGroup and add the new ones. I was hoping to get the advantage that the RecyclerView offers. I could simple change the data, and call notify and chips get updated.

**Comment by wcshi** [comment]
Thank you for explaining your use case, this is outside of the mandate of the Material Android library and we have no plans to support this functionality.

**Comment by bpappin** [comment]
This is a common use case, i can't believe they just closed it on you.

**Comment by hunterstich** [comment]
If you're using LiveData as the backing for a list of chips, can you achieve the same effect by wrapping whatever data you're getting for each chip in something like a ChipData class that holds state for things like `selected` and then transforming your LiveData to enforce things like single selectionRequired/singleSelection/etc? 

Other attributes like singleLine should be pretty straight forward with the way you configure your RecyclerView. What would get more challenging is having a Flow layout backed by LiveData.

**Comment by semanticer** [comment]
@wcshi I think this a reasonable request, especially for the lists with unknown amount of items and `app:singleLine=true` usage. 
This should be reopened. I don't understand how is it out of the Material scope? Ideally, you should extract an interface with those handy chip-specific methods and provide `ViewGroup` and `RecyclerView` implementations.

**Comment by RoarGronmo** [comment]
It would have been wonderful and solved manu usecases with chips.

**Comment by desgraci** [comment]
at least a `LayoutManager` would have been nice, something like https://github.com/BelooS/ChipsLayoutManager
