### ISSUE TITLE
[MaterialDatePicker] Context sensitive month name

### ISSUE THREAD

**Issue by klblk** [material-components/material-components-android#999]
**Description:** 
This problem occurs in the Russian locale (maybe in other languages). In the library code: 
```
private static SimpleDateFormat getYearMonthFormat(Locale locale) {
    return getSimpleFormat("MMMM, yyyy", locale);
}
```
Result in UI: 
![image](https://user-images.githubusercontent.com/6357562/74148838-7474ec80-4c17-11ea-8ae4-84d9114f4fd6.png)

**Expected behavior:**
In Russian, it is correct to use standalone month form in this situation
Need change "MMMM, yyyy" to "LLLL, yyyy". 
Result: changed "Февраля" to "Февраль"

More info: 
https://proandroiddev.com/simmmmplllledateformat-6bd326d17012
https://stackoverflow.com/questions/6192781/month-name-as-a-string/25329549#25329549

**Source code:** 
```
MaterialDatePicker.Builder.dateRangePicker()
            .setTitleText("TODO: title")
            .setTheme(R.style.ThemeOverlay_MaterialComponents_MaterialCalendar)
            .build()
            .show(supportFragmentManager, "date_piker")
```

**Android API version:** All

**Material Library version:** 
1.1.0
1.2.0-alpha04

**Device:** All (with switch on Russian locale)

**Comment by paulfthomas** [comment]
Fixed, see https://github.com/material-components/material-components-android/pull/1000.

**Comment by micHar** [comment]
Is this fixed? It works for regular picker, but not for the compose in 1.2.x afaik
